In [9]:
import pandas as pd
df_train=pd.read_csv('data/train.csv')
df_test=pd.read_csv('data/test.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [10]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [11]:
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [12]:
df_test=df_test.drop(['Driver'],axis=1)
df_train_merged=df_train_merged.drop(['Driver'],axis=1)
df_train=df_train.drop(['Driver'],axis=1)

In [13]:
# predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc').fit(
#     train_data=df_train,
#     ag_args_fit={"num_gpus": 2},
#     time_limit=3600*9,
#     presets='best_quality',
#     verbosity=3,
#     num_stack_levels=0
# )

In [14]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [ ]:
import os
import shutil
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models3"
TIME_LIMIT = 30 * 60  # 30 minutes (1800 seconds) per model family

models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

# ============================================================
# DELETE OLD MODELS
# ============================================================

# if os.path.exists(MODEL_DIR):
#     print(f"Deleting existing model directory: {MODEL_DIR}")
#     shutil.rmtree(MODEL_DIR)

# os.makedirs(MODEL_DIR, exist_ok=True)
print(f"Fresh model directory created: {MODEL_DIR}")

# ============================================================
# TRAIN ONE MODEL AT A TIME
# ============================================================

predictors = {}
results = []

for model_name, model_config in models.items():

    model_path = os.path.join(MODEL_DIR, model_name)

    print("\n" + "=" * 80)
    print(f"TRAINING: {model_name}")
    print(f"TIME LIMIT: 30 MINUTES")
    print(f"MODEL PATH: {model_path}")
    print("=" * 80)

    predictor = TabularPredictor(
        label=TARGET,
        eval_metric='roc_auc',
        path=model_path
    ).fit(
        train_data=df_train_merged,
        presets="best_quality",  # Enables bagging (_BAG_L1) and out-of-fold validation
        hyperparameters={model_name: model_config},  # Maps key to config dict properly
        ag_args_fit={
            'num_gpus': 1
        },
        time_limit=TIME_LIMIT,
        verbosity=3,
        num_stack_levels=0
    )

    predictors[model_name] = predictor

    # ========================================================
    # GET RESULT
    # ========================================================

    leaderboard = predictor.leaderboard(silent=True)
    best_row = leaderboard.iloc[0]

    results.append({
        'Model Family': model_name,
        'Best AutoGluon Model': best_row['model'],
        'Validation ROC-AUC': best_row['score_val'],
        'Fit Time (sec)': best_row['fit_time'],
        'Predict Time (sec)': best_row['pred_time_val']
    })

    print(f"\n{model_name} completed.")
    print(f"Validation ROC-AUC: {best_row['score_val']:.6f}")

# ============================================================
# FINAL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    'Validation ROC-AUC',
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 80)
print("FINAL MODEL COMPARISON")
print("=" * 80)

display(results_df)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.99 GB / 15.06 GB (19.9%)
Disk Space Avail:   723.00 GB / 930.47 GB (77.7%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models3\GBM"
Train Data Rows:    540445
Train Data Columns: 13
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

Fresh model directory created: ./ag_models3

================================================================================
TRAINING: GBM
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models3\GBM
================================================================================

	Available Memory:                    3161.44 MB
	Train Data (Original)  Memory Usage: 109.08 MB (3.5% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 2 | ['Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.7s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 42.78 MB (1.4% of available memory)
Data preprocessing and feature engineering runtime = 0.75s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1799.25s of the 1799.25s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281916
[100]	valid_set's binary_logloss: 0.258851
[150]	valid_set's binary_logloss: 0.250295
[200]	valid_set's binary_logloss: 0.245593
[250]	valid_set's binary_logloss: 0.241892
[300]	valid_set's binary_logloss: 0.239033
[350]	valid_set's binary_logloss: 0.23689
[400]	valid_set's binary_logloss: 0.235024
[450]	valid_set's binary_logloss: 0.233251
[500]	valid_set's binary_logloss: 0.231941
[550]	valid_set's binary_logloss: 0.230582
[600]	valid_set's binary_logloss: 0.229416
[650]	valid_set's binary_logloss: 0.228356
[700]	valid_set's binary_logloss: 0.227139
[750]	valid_set's binary_logloss: 0.226295
[800]	valid_set's binary_logloss: 0.225553
[850]	valid_set's binary_logloss: 0.224755
[900]	valid_set's binary_logloss: 0.224193
[950]	valid_set's binary_logloss: 0.223656
[1000]	valid_set's binary_logloss: 0.22302
[1050]	valid_set's binary_logloss: 0.22256
[1100]	valid_set's binary_logloss: 0.222066
[1150]	valid_set's binary_logloss: 0.221527
[1200]	valid_set's binary_logloss: 0.221184
[1250]	valid_set's binary_logloss: 0.220854
[1300]	valid_set's binary_logloss: 0.220485
[1350]	valid_set's binary_logloss: 0.220108
[1400]	valid_set's binary_logloss: 0.219786
[1450]	valid_set's binary_logloss: 0.219529
[1500]	valid_set's binary_logloss: 0.219235
[1550]	valid_set's binary_logloss: 0.218933
[1600]	valid_set's binary_logloss: 0.218735
[1650]	valid_set's binary_logloss: 0.21846
[1700]	valid_set's binary_logloss: 0.218245
[1750]	valid_set's binary_logloss: 0.217962
[1800]	valid_set's binary_logloss: 0.217741
[1850]	valid_set's binary_logloss: 0.217497
[1900]	valid_set's binary_logloss: 0.217264
[1950]	valid_set's binary_logloss: 0.217172
[2000]	valid_set's binary_logloss: 0.216963
[2050]	valid_set's binary_logloss: 0.216841
[2100]	valid_set's binary_logloss: 0.216703
[2150]	valid_set's binary_logloss: 0.216576
[2200]	valid_set's binary_logloss: 0.216435
[2250]	valid_set's binary_logloss: 0.216285
[2300]	valid_set's binary_logloss: 0.216115
[2350]	valid_set's binary_logloss: 0.215933
[2400]	valid_set's binary_logloss: 0.215754
[2450]	valid_set's binary_logloss: 0.215589
[2500]	valid_set's binary_logloss: 0.21547
[2550]	valid_set's binary_logloss: 0.215352
[2600]	valid_set's binary_logloss: 0.215236
[2650]	valid_set's binary_logloss: 0.215128
[2700]	valid_set's binary_logloss: 0.215022
[2750]	valid_set's binary_logloss: 0.214892
[2800]	valid_set's binary_logloss: 0.214734
[2850]	valid_set's binary_logloss: 0.214616
[2900]	valid_set's binary_logloss: 0.214522
[2950]	valid_set's binary_logloss: 0.214399
[3000]	valid_set's binary_logloss: 0.214288
[3050]	valid_set's binary_logloss: 0.214155
[3100]	valid_set's binary_logloss: 0.214108
[3150]	valid_set's binary_logloss: 0.213998
[3200]	valid_set's binary_logloss: 0.213879
[3250]	valid_set's binary_logloss: 0.213832
[3300]	valid_set's binary_logloss: 0.21377
[3350]	valid_set's binary_logloss: 0.213679
[3400]	valid_set's binary_logloss: 0.213623
[3450]	valid_set's binary_logloss: 0.2136
[3500]	valid_set's binary_logloss: 0.213535
[3550]	valid_set's binary_logloss: 0.213477
[3600]	valid_set's binary_logloss: 0.213393
[3650]	valid_set's binary_logloss: 0.213303
[3700]	valid_set's binary_logloss: 0.213167
[3750]	valid_set's binary_logloss: 0.213104
[3800]	valid_set's binary_logloss: 0.213023
[3850]	valid_set's binary_logloss: 0.212937
[3900]	valid_set's binary_logloss: 0.212905
[3950]	valid_set's binary_logloss: 0.212877
[4000]	valid_set's binary_logloss: 0.21282
[4050]	valid_set's binary_logloss: 0.21276
[4100]	valid_set's binary_logloss: 0.212697
[4150]	valid_set's binary_logloss: 0.212665
[4200]	valid_set's binary_logloss: 0.212644
[4250]	valid_set's binary_logloss: 0.212616
[4300]	valid_set's binary_logloss: 0.212537
[4350]	valid_set's binary_logloss: 0.212489
[4400]	valid_set's binary_logloss: 0.212422
[4450]	valid_set's binary_logloss: 0.212356
[4500]	valid_set's binary_logloss: 0.212347
[4550]	valid_set's binary_logloss: 0.212321
[4600]	valid_set's binary_logloss: 0.212331
[4650]	valid_set's binary_logloss: 0.21228
[4700]	valid_set's binary_logloss: 0.212288
[4750]	valid_set's binary_logloss: 0.212251
[4800]	valid_set's binary_logloss: 0.212242
[4850]	valid_set's binary_logloss: 0.212195
[4900]	valid_set's binary_logloss: 0.212186
[4950]	valid_set's binary_logloss: 0.212197
[5000]	valid_set's binary_logloss: 0.212175
[5050]	valid_set's binary_logloss: 0.212162
[5100]	valid_set's binary_logloss: 0.212162
[5150]	valid_set's binary_logloss: 0.212186
[5200]	valid_set's binary_logloss: 0.212157
[5250]	valid_set's binary_logloss: 0.212133
[5300]	valid_set's binary_logloss: 0.21215
[5350]	valid_set's binary_logloss: 0.212141
[5400]	valid_set's binary_logloss: 0.212071
[5450]	valid_set's binary_logloss: 0.212045
[5500]	valid_set's binary_logloss: 0.212034
[5550]	valid_set's binary_logloss: 0.212029
[5600]	valid_set's binary_logloss: 0.212026
[5650]	valid_set's binary_logloss: 0.211988
[5700]	valid_set's binary_logloss: 0.211968
[5750]	valid_set's binary_logloss: 0.211969
[5800]	valid_set's binary_logloss: 0.211944
[5850]	valid_set's binary_logloss: 0.211901
[5900]	valid_set's binary_logloss: 0.211872
[5950]	valid_set's binary_logloss: 0.211858
[6000]	valid_set's binary_logloss: 0.21182
[6050]	valid_set's binary_logloss: 0.211798
[6100]	valid_set's binary_logloss: 0.211774
[6150]	valid_set's binary_logloss: 0.211804
[6200]	valid_set's binary_logloss: 0.211834
[6250]	valid_set's binary_logloss: 0.211784
[6300]	valid_set's binary_logloss: 0.211772
[6350]	valid_set's binary_logloss: 0.21177
[6400]	valid_set's binary_logloss: 0.211751
[6450]	valid_set's binary_logloss: 0.211758
[6500]	valid_set's binary_logloss: 0.21178
[6550]	valid_set's binary_logloss: 0.211811
[6600]	valid_set's binary_logloss: 0.211835
[6650]	valid_set's binary_logloss: 0.211808
[6700]	valid_set's binary_logloss: 0.211784
[6750]	valid_set's binary_logloss: 0.211766
[6800]	valid_set's binary_logloss: 0.211767
[6850]	valid_set's binary_logloss: 0.211763
[6900]	valid_set's binary_logloss: 0.211753
[6950]	valid_set's binary_logloss: 0.211674
[7000]	valid_set's binary_logloss: 0.211698
[7050]	valid_set's binary_logloss: 0.211684
[7100]	valid_set's binary_logloss: 0.211649
[7150]	valid_set's binary_logloss: 0.211654
[7200]	valid_set's binary_logloss: 0.211678
[7250]	valid_set's binary_logloss: 0.211682
[7300]	valid_set's binary_logloss: 0.211653
[7350]	valid_set's binary_logloss: 0.211648
[7400]	valid_set's binary_logloss: 0.211637
[7450]	valid_set's binary_logloss: 0.21165
[7500]	valid_set's binary_logloss: 0.211661
[7550]	valid_set's binary_logloss: 0.211683
[7600]	valid_set's binary_logloss: 0.211683
[7650]	valid_set's binary_logloss: 0.211715
[7700]	valid_set's binary_logloss: 0.211751
[7750]	valid_set's binary_logloss: 0.211742
[7800]	valid_set's binary_logloss: 0.211736
[7850]	valid_set's binary_logloss: 0.211726
[7900]	valid_set's binary_logloss: 0.211719
[7950]	valid_set's binary_logloss: 0.211726
[8000]	valid_set's binary_logloss: 0.211729
[8050]	valid_set's binary_logloss: 0.211781
[8100]	valid_set's binary_logloss: 0.211785
[8150]	valid_set's binary_logloss: 0.211803
[8200]	valid_set's binary_logloss: 0.211831
[8250]	valid_set's binary_logloss: 0.211847
[8300]	valid_set's binary_logloss: 0.211859
[8350]	valid_set's binary_logloss: 0.211847
[8400]	valid_set's binary_logloss: 0.211893
[8450]	valid_set's binary_logloss: 0.211883
[8500]	valid_set's binary_logloss: 0.211889
[8550]	valid_set's binary_logloss: 0.211917
[8600]	valid_set's binary_logloss: 0.211946
[8650]	valid_set's binary_logloss: 0.211977
[8700]	valid_set's binary_logloss: 0.212015
[8750]	valid_set's binary_logloss: 0.212041
[8800]	valid_set's binary_logloss: 0.212092
[8850]	valid_set's binary_logloss: 0.212079
[8900]	valid_set's binary_logloss: 0.21208
[8950]	valid_set's binary_logloss: 0.212068
[9000]	valid_set's binary_logloss: 0.212116
[9050]	valid_set's binary_logloss: 0.212114
[9100]	valid_set's binary_logloss: 0.21215
[9150]	valid_set's binary_logloss: 0.212187
[9200]	valid_set's binary_logloss: 0.212195
[9250]	valid_set's binary_logloss: 0.212217
[9300]	valid_set's binary_logloss: 0.212241
[9350]	valid_set's binary_logloss: 0.212257
[9400]	valid_set's binary_logloss: 0.212232
[9450]	valid_set's binary_logloss: 0.212265
[9500]	valid_set's binary_logloss: 0.212292
[9550]	valid_set's binary_logloss: 0.212308
[9600]	valid_set's binary_logloss: 0.212286

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282968
[100]	valid_set's binary_logloss: 0.259998
[150]	valid_set's binary_logloss: 0.251554
[200]	valid_set's binary_logloss: 0.246652
[250]	valid_set's binary_logloss: 0.242917
[300]	valid_set's binary_logloss: 0.239931
[350]	valid_set's binary_logloss: 0.237476
[400]	valid_set's binary_logloss: 0.235644
[450]	valid_set's binary_logloss: 0.233975
[500]	valid_set's binary_logloss: 0.232679
[550]	valid_set's binary_logloss: 0.231503
[600]	valid_set's binary_logloss: 0.230339
[650]	valid_set's binary_logloss: 0.229135
[700]	valid_set's binary_logloss: 0.228051
[750]	valid_set's binary_logloss: 0.227093
[800]	valid_set's binary_logloss: 0.22632
[850]	valid_set's binary_logloss: 0.225644
[900]	valid_set's binary_logloss: 0.224947
[950]	valid_set's binary_logloss: 0.224195
[1000]	valid_set's binary_logloss: 0.223495
[1050]	valid_set's binary_logloss: 0.222982
[1100]	valid_set's binary_logloss: 0.222513
[1150]	valid_set's binary_logloss: 0.222026
[1200]	valid_set's binary_logloss: 0.221584
[1250]	valid_set's binary_logloss: 0.221217
[1300]	valid_set's binary_logloss: 0.220773
[1350]	valid_set's binary_logloss: 0.220341
[1400]	valid_set's binary_logloss: 0.220045
[1450]	valid_set's binary_logloss: 0.219765
[1500]	valid_set's binary_logloss: 0.219404
[1550]	valid_set's binary_logloss: 0.219193
[1600]	valid_set's binary_logloss: 0.218921
[1650]	valid_set's binary_logloss: 0.218712
[1700]	valid_set's binary_logloss: 0.218464
[1750]	valid_set's binary_logloss: 0.218146
[1800]	valid_set's binary_logloss: 0.217887
[1850]	valid_set's binary_logloss: 0.217591
[1900]	valid_set's binary_logloss: 0.21736
[1950]	valid_set's binary_logloss: 0.21715
[2000]	valid_set's binary_logloss: 0.216974
[2050]	valid_set's binary_logloss: 0.216807
[2100]	valid_set's binary_logloss: 0.216588
[2150]	valid_set's binary_logloss: 0.216384
[2200]	valid_set's binary_logloss: 0.216256
[2250]	valid_set's binary_logloss: 0.216038
[2300]	valid_set's binary_logloss: 0.215908
[2350]	valid_set's binary_logloss: 0.215762
[2400]	valid_set's binary_logloss: 0.215595
[2450]	valid_set's binary_logloss: 0.215414
[2500]	valid_set's binary_logloss: 0.215239
[2550]	valid_set's binary_logloss: 0.21504
[2600]	valid_set's binary_logloss: 0.214918
[2650]	valid_set's binary_logloss: 0.214767
[2700]	valid_set's binary_logloss: 0.214628
[2750]	valid_set's binary_logloss: 0.214519
[2800]	valid_set's binary_logloss: 0.214448
[2850]	valid_set's binary_logloss: 0.214302
[2900]	valid_set's binary_logloss: 0.21421
[2950]	valid_set's binary_logloss: 0.214107
[3000]	valid_set's binary_logloss: 0.21401
[3050]	valid_set's binary_logloss: 0.213924
[3100]	valid_set's binary_logloss: 0.213826
[3150]	valid_set's binary_logloss: 0.213744
[3200]	valid_set's binary_logloss: 0.21361
[3250]	valid_set's binary_logloss: 0.213544
[3300]	valid_set's binary_logloss: 0.213453
[3350]	valid_set's binary_logloss: 0.213362
[3400]	valid_set's binary_logloss: 0.213317
[3450]	valid_set's binary_logloss: 0.213295
[3500]	valid_set's binary_logloss: 0.213239
[3550]	valid_set's binary_logloss: 0.213175
[3600]	valid_set's binary_logloss: 0.213078
[3650]	valid_set's binary_logloss: 0.212978
[3700]	valid_set's binary_logloss: 0.212942
[3750]	valid_set's binary_logloss: 0.212857
[3800]	valid_set's binary_logloss: 0.212787
[3850]	valid_set's binary_logloss: 0.212707
[3900]	valid_set's binary_logloss: 0.212645
[3950]	valid_set's binary_logloss: 0.212579
[4000]	valid_set's binary_logloss: 0.212551
[4050]	valid_set's binary_logloss: 0.212453
[4100]	valid_set's binary_logloss: 0.212361
[4150]	valid_set's binary_logloss: 0.212344
[4200]	valid_set's binary_logloss: 0.212304
[4250]	valid_set's binary_logloss: 0.212271
[4300]	valid_set's binary_logloss: 0.212236
[4350]	valid_set's binary_logloss: 0.212164
[4400]	valid_set's binary_logloss: 0.212168
[4450]	valid_set's binary_logloss: 0.212112
[4500]	valid_set's binary_logloss: 0.21204
[4550]	valid_set's binary_logloss: 0.212007
[4600]	valid_set's binary_logloss: 0.211988
[4650]	valid_set's binary_logloss: 0.211948
[4700]	valid_set's binary_logloss: 0.21191
[4750]	valid_set's binary_logloss: 0.211858
[4800]	valid_set's binary_logloss: 0.211792
[4850]	valid_set's binary_logloss: 0.211732
[4900]	valid_set's binary_logloss: 0.21168
[4950]	valid_set's binary_logloss: 0.21164
[5000]	valid_set's binary_logloss: 0.21158
[5050]	valid_set's binary_logloss: 0.211537
[5100]	valid_set's binary_logloss: 0.211485
[5150]	valid_set's binary_logloss: 0.211416
[5200]	valid_set's binary_logloss: 0.211417
[5250]	valid_set's binary_logloss: 0.211384
[5300]	valid_set's binary_logloss: 0.211366
[5350]	valid_set's binary_logloss: 0.211308
[5400]	valid_set's binary_logloss: 0.211266
[5450]	valid_set's binary_logloss: 0.21125
[5500]	valid_set's binary_logloss: 0.211236
[5550]	valid_set's binary_logloss: 0.211214
[5600]	valid_set's binary_logloss: 0.211194
[5650]	valid_set's binary_logloss: 0.211135
[5700]	valid_set's binary_logloss: 0.211092
[5750]	valid_set's binary_logloss: 0.211041
[5800]	valid_set's binary_logloss: 0.211037
[5850]	valid_set's binary_logloss: 0.211022
[5900]	valid_set's binary_logloss: 0.210977
[5950]	valid_set's binary_logloss: 0.210939
[6000]	valid_set's binary_logloss: 0.210911
[6050]	valid_set's binary_logloss: 0.210897
[6100]	valid_set's binary_logloss: 0.210879
[6150]	valid_set's binary_logloss: 0.210845
[6200]	valid_set's binary_logloss: 0.210817
[6250]	valid_set's binary_logloss: 0.210846
[6300]	valid_set's binary_logloss: 0.210826
[6350]	valid_set's binary_logloss: 0.210796
[6400]	valid_set's binary_logloss: 0.210764
[6450]	valid_set's binary_logloss: 0.210772
[6500]	valid_set's binary_logloss: 0.21078
[6550]	valid_set's binary_logloss: 0.210763
[6600]	valid_set's binary_logloss: 0.210739
[6650]	valid_set's binary_logloss: 0.210759
[6700]	valid_set's binary_logloss: 0.210763
[6750]	valid_set's binary_logloss: 0.210761
[6800]	valid_set's binary_logloss: 0.210719
[6850]	valid_set's binary_logloss: 0.210703
[6900]	valid_set's binary_logloss: 0.210709
[6950]	valid_set's binary_logloss: 0.210695
[7000]	valid_set's binary_logloss: 0.210696
[7050]	valid_set's binary_logloss: 0.210682
[7100]	valid_set's binary_logloss: 0.210658
[7150]	valid_set's binary_logloss: 0.210616
[7200]	valid_set's binary_logloss: 0.210617
[7250]	valid_set's binary_logloss: 0.210594
[7300]	valid_set's binary_logloss: 0.210604
[7350]	valid_set's binary_logloss: 0.210621
[7400]	valid_set's binary_logloss: 0.210613
[7450]	valid_set's binary_logloss: 0.210639
[7500]	valid_set's binary_logloss: 0.210597
[7550]	valid_set's binary_logloss: 0.210546
[7600]	valid_set's binary_logloss: 0.210525
[7650]	valid_set's binary_logloss: 0.210568
[7700]	valid_set's binary_logloss: 0.210588
[7750]	valid_set's binary_logloss: 0.210606
[7800]	valid_set's binary_logloss: 0.210605
[7850]	valid_set's binary_logloss: 0.210618
[7900]	valid_set's binary_logloss: 0.210624
[7950]	valid_set's binary_logloss: 0.210641
[8000]	valid_set's binary_logloss: 0.210622
[8050]	valid_set's binary_logloss: 0.210643
[8100]	valid_set's binary_logloss: 0.21059
[8150]	valid_set's binary_logloss: 0.210603
[8200]	valid_set's binary_logloss: 0.210612
[8250]	valid_set's binary_logloss: 0.210595
[8300]	valid_set's binary_logloss: 0.210566
[8350]	valid_set's binary_logloss: 0.210601
[8400]	valid_set's binary_logloss: 0.210612
[8450]	valid_set's binary_logloss: 0.21063
[8500]	valid_set's binary_logloss: 0.210673
[8550]	valid_set's binary_logloss: 0.210684
[8600]	valid_set's binary_logloss: 0.21068
[8650]	valid_set's binary_logloss: 0.21069
[8700]	valid_set's binary_logloss: 0.210705
[8750]	valid_set's binary_logloss: 0.21072
[8800]	valid_set's binary_logloss: 0.210732
[8850]	valid_set's binary_logloss: 0.210739
[8900]	valid_set's binary_logloss: 0.21072
[8950]	valid_set's binary_logloss: 0.210692
[9000]	valid_set's binary_logloss: 0.210707
[9050]	valid_set's binary_logloss: 0.210726
[9100]	valid_set's binary_logloss: 0.210736
[9150]	valid_set's binary_logloss: 0.210757
[9200]	valid_set's binary_logloss: 0.210798
[9250]	valid_set's binary_logloss: 0.210786
[9300]	valid_set's binary_logloss: 0.210792
[9350]	valid_set's binary_logloss: 0.210815
[9400]	valid_set's binary_logloss: 0.210837
[9450]	valid_set's binary_logloss: 0.210869
[9500]	valid_set's binary_logloss: 0.210883
[9550]	valid_set's binary_logloss: 0.210893
[9600]	valid_set's binary_logloss: 0.210908
[9650]	valid_set's binary_logloss: 0.210899
[9700]	valid_set's binary_logloss: 0.210923
[9750]	valid_set's binary_logloss: 0.210916
[9800]	valid_set's binary_logloss: 0.210915
[9850]	valid_set's binary_logloss: 0.210929

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284443
[100]	valid_set's binary_logloss: 0.261599
[150]	valid_set's binary_logloss: 0.252971
[200]	valid_set's binary_logloss: 0.247621
[250]	valid_set's binary_logloss: 0.24394
[300]	valid_set's binary_logloss: 0.240718
[350]	valid_set's binary_logloss: 0.238514
[400]	valid_set's binary_logloss: 0.236671
[450]	valid_set's binary_logloss: 0.235086
[500]	valid_set's binary_logloss: 0.233756
[550]	valid_set's binary_logloss: 0.232365
[600]	valid_set's binary_logloss: 0.231416
[650]	valid_set's binary_logloss: 0.230617
[700]	valid_set's binary_logloss: 0.229846
[750]	valid_set's binary_logloss: 0.229269
[800]	valid_set's binary_logloss: 0.228541
[850]	valid_set's binary_logloss: 0.227926
[900]	valid_set's binary_logloss: 0.227257
[950]	valid_set's binary_logloss: 0.226526
[1000]	valid_set's binary_logloss: 0.225789
[1050]	valid_set's binary_logloss: 0.225243
[1100]	valid_set's binary_logloss: 0.224659
[1150]	valid_set's binary_logloss: 0.224161
[1200]	valid_set's binary_logloss: 0.223752
[1250]	valid_set's binary_logloss: 0.22344
[1300]	valid_set's binary_logloss: 0.223103
[1350]	valid_set's binary_logloss: 0.222816
[1400]	valid_set's binary_logloss: 0.222539
[1450]	valid_set's binary_logloss: 0.222151
[1500]	valid_set's binary_logloss: 0.221897
[1550]	valid_set's binary_logloss: 0.221632
[1600]	valid_set's binary_logloss: 0.2214
[1650]	valid_set's binary_logloss: 0.221052
[1700]	valid_set's binary_logloss: 0.220731
[1750]	valid_set's binary_logloss: 0.220485
[1800]	valid_set's binary_logloss: 0.220318
[1850]	valid_set's binary_logloss: 0.22008
[1900]	valid_set's binary_logloss: 0.219799
[1950]	valid_set's binary_logloss: 0.219701
[2000]	valid_set's binary_logloss: 0.219563
[2050]	valid_set's binary_logloss: 0.219392
[2100]	valid_set's binary_logloss: 0.219224
[2150]	valid_set's binary_logloss: 0.219053
[2200]	valid_set's binary_logloss: 0.218838
[2250]	valid_set's binary_logloss: 0.218703
[2300]	valid_set's binary_logloss: 0.218543
[2350]	valid_set's binary_logloss: 0.218423
[2400]	valid_set's binary_logloss: 0.21831
[2450]	valid_set's binary_logloss: 0.218205
[2500]	valid_set's binary_logloss: 0.218119
[2550]	valid_set's binary_logloss: 0.217998
[2600]	valid_set's binary_logloss: 0.217904
[2650]	valid_set's binary_logloss: 0.217814
[2700]	valid_set's binary_logloss: 0.21775
[2750]	valid_set's binary_logloss: 0.217663
[2800]	valid_set's binary_logloss: 0.217554
[2850]	valid_set's binary_logloss: 0.217477
[2900]	valid_set's binary_logloss: 0.217336
[2950]	valid_set's binary_logloss: 0.217242
[3000]	valid_set's binary_logloss: 0.217101
[3050]	valid_set's binary_logloss: 0.217047
[3100]	valid_set's binary_logloss: 0.21701
[3150]	valid_set's binary_logloss: 0.216965
[3200]	valid_set's binary_logloss: 0.216883
[3250]	valid_set's binary_logloss: 0.216818
[3300]	valid_set's binary_logloss: 0.216724
[3350]	valid_set's binary_logloss: 0.216659
[3400]	valid_set's binary_logloss: 0.216595
[3450]	valid_set's binary_logloss: 0.216568
[3500]	valid_set's binary_logloss: 0.216506
[3550]	valid_set's binary_logloss: 0.216465
[3600]	valid_set's binary_logloss: 0.216445
[3650]	valid_set's binary_logloss: 0.21641
[3700]	valid_set's binary_logloss: 0.216365
[3750]	valid_set's binary_logloss: 0.216299
[3800]	valid_set's binary_logloss: 0.216254
[3850]	valid_set's binary_logloss: 0.216217
[3900]	valid_set's binary_logloss: 0.21618
[3950]	valid_set's binary_logloss: 0.216109
[4000]	valid_set's binary_logloss: 0.216088
[4050]	valid_set's binary_logloss: 0.216032
[4100]	valid_set's binary_logloss: 0.215985
[4150]	valid_set's binary_logloss: 0.215905
[4200]	valid_set's binary_logloss: 0.215908
[4250]	valid_set's binary_logloss: 0.215874
[4300]	valid_set's binary_logloss: 0.215865
[4350]	valid_set's binary_logloss: 0.215859
[4400]	valid_set's binary_logloss: 0.215824
[4450]	valid_set's binary_logloss: 0.215809
[4500]	valid_set's binary_logloss: 0.21582
[4550]	valid_set's binary_logloss: 0.215815
[4600]	valid_set's binary_logloss: 0.215806
[4650]	valid_set's binary_logloss: 0.215801
[4700]	valid_set's binary_logloss: 0.215773
[4750]	valid_set's binary_logloss: 0.215817
[4800]	valid_set's binary_logloss: 0.21583
[4850]	valid_set's binary_logloss: 0.215815
[4900]	valid_set's binary_logloss: 0.215815
[4950]	valid_set's binary_logloss: 0.215797
[5000]	valid_set's binary_logloss: 0.215792
[5050]	valid_set's binary_logloss: 0.215774
[5100]	valid_set's binary_logloss: 0.215762
[5150]	valid_set's binary_logloss: 0.21577
[5200]	valid_set's binary_logloss: 0.215751
[5250]	valid_set's binary_logloss: 0.215761
[5300]	valid_set's binary_logloss: 0.215771
[5350]	valid_set's binary_logloss: 0.215753
[5400]	valid_set's binary_logloss: 0.215754
[5450]	valid_set's binary_logloss: 0.215742
[5500]	valid_set's binary_logloss: 0.215751
[5550]	valid_set's binary_logloss: 0.215759
[5600]	valid_set's binary_logloss: 0.215762
[5650]	valid_set's binary_logloss: 0.215784
[5700]	valid_set's binary_logloss: 0.215788
[5750]	valid_set's binary_logloss: 0.215807
[5800]	valid_set's binary_logloss: 0.215814
[5850]	valid_set's binary_logloss: 0.215806
[5900]	valid_set's binary_logloss: 0.2158
[5950]	valid_set's binary_logloss: 0.215839
[6000]	valid_set's binary_logloss: 0.215838
[6050]	valid_set's binary_logloss: 0.21589
[6100]	valid_set's binary_logloss: 0.215886
[6150]	valid_set's binary_logloss: 0.215863
[6200]	valid_set's binary_logloss: 0.215862
[6250]	valid_set's binary_logloss: 0.215876
[6300]	valid_set's binary_logloss: 0.215861
[6350]	valid_set's binary_logloss: 0.215854
[6400]	valid_set's binary_logloss: 0.215851
[6450]	valid_set's binary_logloss: 0.215857
[6500]	valid_set's binary_logloss: 0.215859
[6550]	valid_set's binary_logloss: 0.215898
[6600]	valid_set's binary_logloss: 0.215876
[6650]	valid_set's binary_logloss: 0.215862
[6700]	valid_set's binary_logloss: 0.215851
[6750]	valid_set's binary_logloss: 0.215842
[6800]	valid_set's binary_logloss: 0.215899
[6850]	valid_set's binary_logloss: 0.215893
[6900]	valid_set's binary_logloss: 0.215956
[6950]	valid_set's binary_logloss: 0.215929

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.280922
[100]	valid_set's binary_logloss: 0.257829
[150]	valid_set's binary_logloss: 0.249808
[200]	valid_set's binary_logloss: 0.245072
[250]	valid_set's binary_logloss: 0.24169
[300]	valid_set's binary_logloss: 0.238661
[350]	valid_set's binary_logloss: 0.2362
[400]	valid_set's binary_logloss: 0.234337
[450]	valid_set's binary_logloss: 0.232762
[500]	valid_set's binary_logloss: 0.231539
[550]	valid_set's binary_logloss: 0.230457
[600]	valid_set's binary_logloss: 0.22938
[650]	valid_set's binary_logloss: 0.228448
[700]	valid_set's binary_logloss: 0.227442
[750]	valid_set's binary_logloss: 0.226695
[800]	valid_set's binary_logloss: 0.225845
[850]	valid_set's binary_logloss: 0.225239
[900]	valid_set's binary_logloss: 0.224575
[950]	valid_set's binary_logloss: 0.22402
[1000]	valid_set's binary_logloss: 0.22348
[1050]	valid_set's binary_logloss: 0.222956
[1100]	valid_set's binary_logloss: 0.222478
[1150]	valid_set's binary_logloss: 0.222111
[1200]	valid_set's binary_logloss: 0.221664
[1250]	valid_set's binary_logloss: 0.221225
[1300]	valid_set's binary_logloss: 0.220871
[1350]	valid_set's binary_logloss: 0.220576
[1400]	valid_set's binary_logloss: 0.220269
[1450]	valid_set's binary_logloss: 0.219984
[1500]	valid_set's binary_logloss: 0.219698
[1550]	valid_set's binary_logloss: 0.219398
[1600]	valid_set's binary_logloss: 0.219164
[1650]	valid_set's binary_logloss: 0.21894
[1700]	valid_set's binary_logloss: 0.21873
[1750]	valid_set's binary_logloss: 0.218514
[1800]	valid_set's binary_logloss: 0.218234
[1850]	valid_set's binary_logloss: 0.218032
[1900]	valid_set's binary_logloss: 0.217813
[1950]	valid_set's binary_logloss: 0.217579
[2000]	valid_set's binary_logloss: 0.217401
[2050]	valid_set's binary_logloss: 0.217192
[2100]	valid_set's binary_logloss: 0.217036
[2150]	valid_set's binary_logloss: 0.216856
[2200]	valid_set's binary_logloss: 0.216635
[2250]	valid_set's binary_logloss: 0.216517
[2300]	valid_set's binary_logloss: 0.216377
[2350]	valid_set's binary_logloss: 0.216241
[2400]	valid_set's binary_logloss: 0.216082
[2450]	valid_set's binary_logloss: 0.215962
[2500]	valid_set's binary_logloss: 0.215843
[2550]	valid_set's binary_logloss: 0.215665
[2600]	valid_set's binary_logloss: 0.215505
[2650]	valid_set's binary_logloss: 0.215338
[2700]	valid_set's binary_logloss: 0.215203
[2750]	valid_set's binary_logloss: 0.21505
[2800]	valid_set's binary_logloss: 0.214915
[2850]	valid_set's binary_logloss: 0.214859
[2900]	valid_set's binary_logloss: 0.214769
[2950]	valid_set's binary_logloss: 0.214695
[3000]	valid_set's binary_logloss: 0.214582
[3050]	valid_set's binary_logloss: 0.214456
[3100]	valid_set's binary_logloss: 0.214369
[3150]	valid_set's binary_logloss: 0.214329
[3200]	valid_set's binary_logloss: 0.214298
[3250]	valid_set's binary_logloss: 0.214212
[3300]	valid_set's binary_logloss: 0.214155
[3350]	valid_set's binary_logloss: 0.214113
[3400]	valid_set's binary_logloss: 0.214097
[3450]	valid_set's binary_logloss: 0.213974
[3500]	valid_set's binary_logloss: 0.213901
[3550]	valid_set's binary_logloss: 0.213834
[3600]	valid_set's binary_logloss: 0.213828
[3650]	valid_set's binary_logloss: 0.213755
[3700]	valid_set's binary_logloss: 0.213684
[3750]	valid_set's binary_logloss: 0.213582
[3800]	valid_set's binary_logloss: 0.213485
[3850]	valid_set's binary_logloss: 0.213448
[3900]	valid_set's binary_logloss: 0.213389
[3950]	valid_set's binary_logloss: 0.213355
[4000]	valid_set's binary_logloss: 0.213304
[4050]	valid_set's binary_logloss: 0.213257
[4100]	valid_set's binary_logloss: 0.213205
[4150]	valid_set's binary_logloss: 0.213173
[4200]	valid_set's binary_logloss: 0.21313
[4250]	valid_set's binary_logloss: 0.213107
[4300]	valid_set's binary_logloss: 0.213051
[4350]	valid_set's binary_logloss: 0.213042
[4400]	valid_set's binary_logloss: 0.213009
[4450]	valid_set's binary_logloss: 0.212962
[4500]	valid_set's binary_logloss: 0.212912
[4550]	valid_set's binary_logloss: 0.212882
[4600]	valid_set's binary_logloss: 0.212859
[4650]	valid_set's binary_logloss: 0.21281
[4700]	valid_set's binary_logloss: 0.212786
[4750]	valid_set's binary_logloss: 0.212713
[4800]	valid_set's binary_logloss: 0.212711
[4850]	valid_set's binary_logloss: 0.212726
[4900]	valid_set's binary_logloss: 0.212733
[4950]	valid_set's binary_logloss: 0.212744
[5000]	valid_set's binary_logloss: 0.212701
[5050]	valid_set's binary_logloss: 0.212669
[5100]	valid_set's binary_logloss: 0.212635
[5150]	valid_set's binary_logloss: 0.212616
[5200]	valid_set's binary_logloss: 0.212599
[5250]	valid_set's binary_logloss: 0.212574
[5300]	valid_set's binary_logloss: 0.212536
[5350]	valid_set's binary_logloss: 0.212565
[5400]	valid_set's binary_logloss: 0.212495
[5450]	valid_set's binary_logloss: 0.212478
[5500]	valid_set's binary_logloss: 0.212473
[5550]	valid_set's binary_logloss: 0.212467
[5600]	valid_set's binary_logloss: 0.212496
[5650]	valid_set's binary_logloss: 0.212467
[5700]	valid_set's binary_logloss: 0.212439
[5750]	valid_set's binary_logloss: 0.212451
[5800]	valid_set's binary_logloss: 0.212434
[5850]	valid_set's binary_logloss: 0.212435
[5900]	valid_set's binary_logloss: 0.212396
[5950]	valid_set's binary_logloss: 0.212356
[6000]	valid_set's binary_logloss: 0.212351
[6050]	valid_set's binary_logloss: 0.21234
[6100]	valid_set's binary_logloss: 0.212333
[6150]	valid_set's binary_logloss: 0.212318
[6200]	valid_set's binary_logloss: 0.212322
[6250]	valid_set's binary_logloss: 0.212292
[6300]	valid_set's binary_logloss: 0.212282
[6350]	valid_set's binary_logloss: 0.212263
[6400]	valid_set's binary_logloss: 0.212239
[6450]	valid_set's binary_logloss: 0.212255
[6500]	valid_set's binary_logloss: 0.21225
[6550]	valid_set's binary_logloss: 0.212249
[6600]	valid_set's binary_logloss: 0.212245
[6650]	valid_set's binary_logloss: 0.21222
[6700]	valid_set's binary_logloss: 0.212185
[6750]	valid_set's binary_logloss: 0.212147
[6800]	valid_set's binary_logloss: 0.212142
[6850]	valid_set's binary_logloss: 0.212125
[6900]	valid_set's binary_logloss: 0.212121
[6950]	valid_set's binary_logloss: 0.212137
[7000]	valid_set's binary_logloss: 0.212105
[7050]	valid_set's binary_logloss: 0.212097
[7100]	valid_set's binary_logloss: 0.212045
[7150]	valid_set's binary_logloss: 0.212042
[7200]	valid_set's binary_logloss: 0.212013
[7250]	valid_set's binary_logloss: 0.211998
[7300]	valid_set's binary_logloss: 0.211999
[7350]	valid_set's binary_logloss: 0.211999
[7400]	valid_set's binary_logloss: 0.211997
[7450]	valid_set's binary_logloss: 0.212024
[7500]	valid_set's binary_logloss: 0.212015
[7550]	valid_set's binary_logloss: 0.212029
[7600]	valid_set's binary_logloss: 0.212045
[7650]	valid_set's binary_logloss: 0.21203
[7700]	valid_set's binary_logloss: 0.212075
[7750]	valid_set's binary_logloss: 0.212064
[7800]	valid_set's binary_logloss: 0.212054
[7850]	valid_set's binary_logloss: 0.212049
[7900]	valid_set's binary_logloss: 0.212054
[7950]	valid_set's binary_logloss: 0.212044
[8000]	valid_set's binary_logloss: 0.212072
[8050]	valid_set's binary_logloss: 0.212082
[8100]	valid_set's binary_logloss: 0.212072
[8150]	valid_set's binary_logloss: 0.212069
[8200]	valid_set's binary_logloss: 0.212076
[8250]	valid_set's binary_logloss: 0.212045
[8300]	valid_set's binary_logloss: 0.21204
[8350]	valid_set's binary_logloss: 0.212065
[8400]	valid_set's binary_logloss: 0.212064
[8450]	valid_set's binary_logloss: 0.212111
[8500]	valid_set's binary_logloss: 0.212143
[8550]	valid_set's binary_logloss: 0.21216
[8600]	valid_set's binary_logloss: 0.212198
[8650]	valid_set's binary_logloss: 0.212225
[8700]	valid_set's binary_logloss: 0.212212
[8750]	valid_set's binary_logloss: 0.212195
[8800]	valid_set's binary_logloss: 0.212219
[8850]	valid_set's binary_logloss: 0.21222
[8900]	valid_set's binary_logloss: 0.212245
[8950]	valid_set's binary_logloss: 0.21226
[9000]	valid_set's binary_logloss: 0.212269
[9050]	valid_set's binary_logloss: 0.212291
[9100]	valid_set's binary_logloss: 0.212282
[9150]	valid_set's binary_logloss: 0.212287
[9200]	valid_set's binary_logloss: 0.212277
[9250]	valid_set's binary_logloss: 0.212275
[9300]	valid_set's binary_logloss: 0.212291
[9350]	valid_set's binary_logloss: 0.212294
[9400]	valid_set's binary_logloss: 0.212312
[9450]	valid_set's binary_logloss: 0.212286
[9500]	valid_set's binary_logloss: 0.212296
[9550]	valid_set's binary_logloss: 0.212321
[9600]	valid_set's binary_logloss: 0.212318

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282566
[100]	valid_set's binary_logloss: 0.25928
[150]	valid_set's binary_logloss: 0.250393
[200]	valid_set's binary_logloss: 0.245401
[250]	valid_set's binary_logloss: 0.241469
[300]	valid_set's binary_logloss: 0.238558
[350]	valid_set's binary_logloss: 0.23579
[400]	valid_set's binary_logloss: 0.233932
[450]	valid_set's binary_logloss: 0.232608
[500]	valid_set's binary_logloss: 0.231286
[550]	valid_set's binary_logloss: 0.230057
[600]	valid_set's binary_logloss: 0.228942
[650]	valid_set's binary_logloss: 0.227982
[700]	valid_set's binary_logloss: 0.227082
[750]	valid_set's binary_logloss: 0.226256
[800]	valid_set's binary_logloss: 0.225431
[850]	valid_set's binary_logloss: 0.224791
[900]	valid_set's binary_logloss: 0.224109
[950]	valid_set's binary_logloss: 0.223476
[1000]	valid_set's binary_logloss: 0.222897
[1050]	valid_set's binary_logloss: 0.222402
[1100]	valid_set's binary_logloss: 0.221995
[1150]	valid_set's binary_logloss: 0.221453
[1200]	valid_set's binary_logloss: 0.220983
[1250]	valid_set's binary_logloss: 0.22055
[1300]	valid_set's binary_logloss: 0.220137
[1350]	valid_set's binary_logloss: 0.219836
[1400]	valid_set's binary_logloss: 0.219431
[1450]	valid_set's binary_logloss: 0.219121
[1500]	valid_set's binary_logloss: 0.218839
[1550]	valid_set's binary_logloss: 0.218556
[1600]	valid_set's binary_logloss: 0.218256
[1650]	valid_set's binary_logloss: 0.217955
[1700]	valid_set's binary_logloss: 0.217735
[1750]	valid_set's binary_logloss: 0.217478
[1800]	valid_set's binary_logloss: 0.217332
[1850]	valid_set's binary_logloss: 0.217064
[1900]	valid_set's binary_logloss: 0.216806
[1950]	valid_set's binary_logloss: 0.216624
[2000]	valid_set's binary_logloss: 0.216435
[2050]	valid_set's binary_logloss: 0.216177
[2100]	valid_set's binary_logloss: 0.216077
[2150]	valid_set's binary_logloss: 0.215889
[2200]	valid_set's binary_logloss: 0.215738
[2250]	valid_set's binary_logloss: 0.21562
[2300]	valid_set's binary_logloss: 0.215498
[2350]	valid_set's binary_logloss: 0.21538
[2400]	valid_set's binary_logloss: 0.215267
[2450]	valid_set's binary_logloss: 0.215115
[2500]	valid_set's binary_logloss: 0.214956
[2550]	valid_set's binary_logloss: 0.214817
[2600]	valid_set's binary_logloss: 0.21468
[2650]	valid_set's binary_logloss: 0.214576
[2700]	valid_set's binary_logloss: 0.214498
[2750]	valid_set's binary_logloss: 0.214359
[2800]	valid_set's binary_logloss: 0.214211
[2850]	valid_set's binary_logloss: 0.214099
[2900]	valid_set's binary_logloss: 0.21406
[2950]	valid_set's binary_logloss: 0.213954
[3000]	valid_set's binary_logloss: 0.213854
[3050]	valid_set's binary_logloss: 0.213716
[3100]	valid_set's binary_logloss: 0.213636
[3150]	valid_set's binary_logloss: 0.21358
[3200]	valid_set's binary_logloss: 0.213518
[3250]	valid_set's binary_logloss: 0.213383
[3300]	valid_set's binary_logloss: 0.213345
[3350]	valid_set's binary_logloss: 0.213302
[3400]	valid_set's binary_logloss: 0.213259
[3450]	valid_set's binary_logloss: 0.213165
[3500]	valid_set's binary_logloss: 0.213104
[3550]	valid_set's binary_logloss: 0.213006
[3600]	valid_set's binary_logloss: 0.21303
[3650]	valid_set's binary_logloss: 0.21296
[3700]	valid_set's binary_logloss: 0.212873
[3750]	valid_set's binary_logloss: 0.212797
[3800]	valid_set's binary_logloss: 0.212725
[3850]	valid_set's binary_logloss: 0.212672
[3900]	valid_set's binary_logloss: 0.212625
[3950]	valid_set's binary_logloss: 0.212596
[4000]	valid_set's binary_logloss: 0.212559
[4050]	valid_set's binary_logloss: 0.212492
[4100]	valid_set's binary_logloss: 0.212489
[4150]	valid_set's binary_logloss: 0.212402
[4200]	valid_set's binary_logloss: 0.212348
[4250]	valid_set's binary_logloss: 0.212289
[4300]	valid_set's binary_logloss: 0.212236
[4350]	valid_set's binary_logloss: 0.212139
[4400]	valid_set's binary_logloss: 0.212131
[4450]	valid_set's binary_logloss: 0.212079
[4500]	valid_set's binary_logloss: 0.212035
[4550]	valid_set's binary_logloss: 0.211977
[4600]	valid_set's binary_logloss: 0.211961
[4650]	valid_set's binary_logloss: 0.211951
[4700]	valid_set's binary_logloss: 0.211962
[4750]	valid_set's binary_logloss: 0.211933
[4800]	valid_set's binary_logloss: 0.211889
[4850]	valid_set's binary_logloss: 0.211838
[4900]	valid_set's binary_logloss: 0.211779
[4950]	valid_set's binary_logloss: 0.211748
[5000]	valid_set's binary_logloss: 0.211709
[5050]	valid_set's binary_logloss: 0.211664
[5100]	valid_set's binary_logloss: 0.211615
[5150]	valid_set's binary_logloss: 0.211604
[5200]	valid_set's binary_logloss: 0.211606
[5250]	valid_set's binary_logloss: 0.211589
[5300]	valid_set's binary_logloss: 0.211583
[5350]	valid_set's binary_logloss: 0.211575
[5400]	valid_set's binary_logloss: 0.211565
[5450]	valid_set's binary_logloss: 0.211548
[5500]	valid_set's binary_logloss: 0.21151
[5550]	valid_set's binary_logloss: 0.211461
[5600]	valid_set's binary_logloss: 0.211456
[5650]	valid_set's binary_logloss: 0.211439
[5700]	valid_set's binary_logloss: 0.211466
[5750]	valid_set's binary_logloss: 0.211449
[5800]	valid_set's binary_logloss: 0.211478
[5850]	valid_set's binary_logloss: 0.211461
[5900]	valid_set's binary_logloss: 0.211445
[5950]	valid_set's binary_logloss: 0.211438
[6000]	valid_set's binary_logloss: 0.211448
[6050]	valid_set's binary_logloss: 0.21145
[6100]	valid_set's binary_logloss: 0.211465
[6150]	valid_set's binary_logloss: 0.211368
[6200]	valid_set's binary_logloss: 0.211342
[6250]	valid_set's binary_logloss: 0.211266
[6300]	valid_set's binary_logloss: 0.211264
[6350]	valid_set's binary_logloss: 0.211281
[6400]	valid_set's binary_logloss: 0.211267
[6450]	valid_set's binary_logloss: 0.211261
[6500]	valid_set's binary_logloss: 0.211266
[6550]	valid_set's binary_logloss: 0.211295
[6600]	valid_set's binary_logloss: 0.211314
[6650]	valid_set's binary_logloss: 0.211329
[6700]	valid_set's binary_logloss: 0.211326
[6750]	valid_set's binary_logloss: 0.211326
[6800]	valid_set's binary_logloss: 0.211336
[6850]	valid_set's binary_logloss: 0.211351
[6900]	valid_set's binary_logloss: 0.211377
[6950]	valid_set's binary_logloss: 0.211371
[7000]	valid_set's binary_logloss: 0.211384
[7050]	valid_set's binary_logloss: 0.211418
[7100]	valid_set's binary_logloss: 0.21144
[7150]	valid_set's binary_logloss: 0.211453
[7200]	valid_set's binary_logloss: 0.211477
[7250]	valid_set's binary_logloss: 0.211489
[7300]	valid_set's binary_logloss: 0.211459
[7350]	valid_set's binary_logloss: 0.211469
[7400]	valid_set's binary_logloss: 0.211477
[7450]	valid_set's binary_logloss: 0.211463
[7500]	valid_set's binary_logloss: 0.211465
[7550]	valid_set's binary_logloss: 0.211471
[7600]	valid_set's binary_logloss: 0.211519
[7650]	valid_set's binary_logloss: 0.211551
[7700]	valid_set's binary_logloss: 0.211552
[7750]	valid_set's binary_logloss: 0.211535
[7800]	valid_set's binary_logloss: 0.211546
[7850]	valid_set's binary_logloss: 0.211553
[7900]	valid_set's binary_logloss: 0.211551
[7950]	valid_set's binary_logloss: 0.211542
[8000]	valid_set's binary_logloss: 0.21153
[8050]	valid_set's binary_logloss: 0.211582
[8100]	valid_set's binary_logloss: 0.211571
[8150]	valid_set's binary_logloss: 0.211577
[8200]	valid_set's binary_logloss: 0.211566
[8250]	valid_set's binary_logloss: 0.211586
[8300]	valid_set's binary_logloss: 0.21158
[8350]	valid_set's binary_logloss: 0.211594
[8400]	valid_set's binary_logloss: 0.211602
[8450]	valid_set's binary_logloss: 0.211622

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281294
[100]	valid_set's binary_logloss: 0.257945
[150]	valid_set's binary_logloss: 0.249455
[200]	valid_set's binary_logloss: 0.244518
[250]	valid_set's binary_logloss: 0.241302
[300]	valid_set's binary_logloss: 0.238396
[350]	valid_set's binary_logloss: 0.235998
[400]	valid_set's binary_logloss: 0.234212
[450]	valid_set's binary_logloss: 0.23266
[500]	valid_set's binary_logloss: 0.231531
[550]	valid_set's binary_logloss: 0.230338
[600]	valid_set's binary_logloss: 0.229267
[650]	valid_set's binary_logloss: 0.228291
[700]	valid_set's binary_logloss: 0.227361
[750]	valid_set's binary_logloss: 0.226572
[800]	valid_set's binary_logloss: 0.225887
[850]	valid_set's binary_logloss: 0.225245
[900]	valid_set's binary_logloss: 0.224458
[950]	valid_set's binary_logloss: 0.22376
[1000]	valid_set's binary_logloss: 0.223271
[1050]	valid_set's binary_logloss: 0.222853
[1100]	valid_set's binary_logloss: 0.222413
[1150]	valid_set's binary_logloss: 0.222073
[1200]	valid_set's binary_logloss: 0.221579
[1250]	valid_set's binary_logloss: 0.221139
[1300]	valid_set's binary_logloss: 0.220829
[1350]	valid_set's binary_logloss: 0.220488
[1400]	valid_set's binary_logloss: 0.220108
[1450]	valid_set's binary_logloss: 0.219831
[1500]	valid_set's binary_logloss: 0.219623
[1550]	valid_set's binary_logloss: 0.219302
[1600]	valid_set's binary_logloss: 0.21894
[1650]	valid_set's binary_logloss: 0.218646
[1700]	valid_set's binary_logloss: 0.218455
[1750]	valid_set's binary_logloss: 0.218155
[1800]	valid_set's binary_logloss: 0.217955
[1850]	valid_set's binary_logloss: 0.217711
[1900]	valid_set's binary_logloss: 0.217556
[1950]	valid_set's binary_logloss: 0.217347
[2000]	valid_set's binary_logloss: 0.217025
[2050]	valid_set's binary_logloss: 0.21689
[2100]	valid_set's binary_logloss: 0.216685
[2150]	valid_set's binary_logloss: 0.216489
[2200]	valid_set's binary_logloss: 0.216186
[2250]	valid_set's binary_logloss: 0.216032
[2300]	valid_set's binary_logloss: 0.21591
[2350]	valid_set's binary_logloss: 0.215818
[2400]	valid_set's binary_logloss: 0.215656
[2450]	valid_set's binary_logloss: 0.21544
[2500]	valid_set's binary_logloss: 0.215314
[2550]	valid_set's binary_logloss: 0.215215
[2600]	valid_set's binary_logloss: 0.215136
[2650]	valid_set's binary_logloss: 0.215005
[2700]	valid_set's binary_logloss: 0.214903
[2750]	valid_set's binary_logloss: 0.214717
[2800]	valid_set's binary_logloss: 0.214532
[2850]	valid_set's binary_logloss: 0.214442
[2900]	valid_set's binary_logloss: 0.21431
[2950]	valid_set's binary_logloss: 0.214256
[3000]	valid_set's binary_logloss: 0.214157
[3050]	valid_set's binary_logloss: 0.2141
[3100]	valid_set's binary_logloss: 0.214009
[3150]	valid_set's binary_logloss: 0.213858
[3200]	valid_set's binary_logloss: 0.213785
[3250]	valid_set's binary_logloss: 0.213607
[3300]	valid_set's binary_logloss: 0.213545
[3350]	valid_set's binary_logloss: 0.213462
[3400]	valid_set's binary_logloss: 0.213363
[3450]	valid_set's binary_logloss: 0.213302
[3500]	valid_set's binary_logloss: 0.213224
[3550]	valid_set's binary_logloss: 0.213181
[3600]	valid_set's binary_logloss: 0.213121
[3650]	valid_set's binary_logloss: 0.213063
[3700]	valid_set's binary_logloss: 0.212897
[3750]	valid_set's binary_logloss: 0.212851
[3800]	valid_set's binary_logloss: 0.21278
[3850]	valid_set's binary_logloss: 0.212668
[3900]	valid_set's binary_logloss: 0.212604
[3950]	valid_set's binary_logloss: 0.212475
[4000]	valid_set's binary_logloss: 0.212429
[4050]	valid_set's binary_logloss: 0.212409
[4100]	valid_set's binary_logloss: 0.212384
[4150]	valid_set's binary_logloss: 0.212336
[4200]	valid_set's binary_logloss: 0.21229
[4250]	valid_set's binary_logloss: 0.212219
[4300]	valid_set's binary_logloss: 0.212178
[4350]	valid_set's binary_logloss: 0.212114
[4400]	valid_set's binary_logloss: 0.212063
[4450]	valid_set's binary_logloss: 0.212041
[4500]	valid_set's binary_logloss: 0.211982
[4550]	valid_set's binary_logloss: 0.211968
[4600]	valid_set's binary_logloss: 0.211979
[4650]	valid_set's binary_logloss: 0.211891
[4700]	valid_set's binary_logloss: 0.211841
[4750]	valid_set's binary_logloss: 0.211785
[4800]	valid_set's binary_logloss: 0.211743
[4850]	valid_set's binary_logloss: 0.211719
[4900]	valid_set's binary_logloss: 0.211716
[4950]	valid_set's binary_logloss: 0.211716
[5000]	valid_set's binary_logloss: 0.211688
[5050]	valid_set's binary_logloss: 0.211673
[5100]	valid_set's binary_logloss: 0.211654
[5150]	valid_set's binary_logloss: 0.211621
[5200]	valid_set's binary_logloss: 0.211612
[5250]	valid_set's binary_logloss: 0.211594
[5300]	valid_set's binary_logloss: 0.211603
[5350]	valid_set's binary_logloss: 0.211597
[5400]	valid_set's binary_logloss: 0.211565
[5450]	valid_set's binary_logloss: 0.211553
[5500]	valid_set's binary_logloss: 0.211576
[5550]	valid_set's binary_logloss: 0.211565
[5600]	valid_set's binary_logloss: 0.21154
[5650]	valid_set's binary_logloss: 0.211512
[5700]	valid_set's binary_logloss: 0.211501
[5750]	valid_set's binary_logloss: 0.211477
[5800]	valid_set's binary_logloss: 0.211456
[5850]	valid_set's binary_logloss: 0.211396
[5900]	valid_set's binary_logloss: 0.211381
[5950]	valid_set's binary_logloss: 0.211361
[6000]	valid_set's binary_logloss: 0.211357
[6050]	valid_set's binary_logloss: 0.211322
[6100]	valid_set's binary_logloss: 0.211312
[6150]	valid_set's binary_logloss: 0.211268
[6200]	valid_set's binary_logloss: 0.211273
[6250]	valid_set's binary_logloss: 0.211234
[6300]	valid_set's binary_logloss: 0.211158
[6350]	valid_set's binary_logloss: 0.211156
[6400]	valid_set's binary_logloss: 0.211122
[6450]	valid_set's binary_logloss: 0.211107
[6500]	valid_set's binary_logloss: 0.211105
[6550]	valid_set's binary_logloss: 0.21104
[6600]	valid_set's binary_logloss: 0.21104
[6650]	valid_set's binary_logloss: 0.210991
[6700]	valid_set's binary_logloss: 0.210977
[6750]	valid_set's binary_logloss: 0.210951
[6800]	valid_set's binary_logloss: 0.210932
[6850]	valid_set's binary_logloss: 0.210945
[6900]	valid_set's binary_logloss: 0.210925
[6950]	valid_set's binary_logloss: 0.210901
[7000]	valid_set's binary_logloss: 0.210872
[7050]	valid_set's binary_logloss: 0.210873
[7100]	valid_set's binary_logloss: 0.210839
[7150]	valid_set's binary_logloss: 0.210785
[7200]	valid_set's binary_logloss: 0.210769
[7250]	valid_set's binary_logloss: 0.210765
[7300]	valid_set's binary_logloss: 0.210764
[7350]	valid_set's binary_logloss: 0.210777
[7400]	valid_set's binary_logloss: 0.210762
[7450]	valid_set's binary_logloss: 0.210773
[7500]	valid_set's binary_logloss: 0.210762
[7550]	valid_set's binary_logloss: 0.21077
[7600]	valid_set's binary_logloss: 0.210783
[7650]	valid_set's binary_logloss: 0.210835
[7700]	valid_set's binary_logloss: 0.210852
[7750]	valid_set's binary_logloss: 0.210867
[7800]	valid_set's binary_logloss: 0.210903
[7850]	valid_set's binary_logloss: 0.210898
[7900]	valid_set's binary_logloss: 0.210933
[7950]	valid_set's binary_logloss: 0.210921
[8000]	valid_set's binary_logloss: 0.210934
[8050]	valid_set's binary_logloss: 0.210922
[8100]	valid_set's binary_logloss: 0.210907
[8150]	valid_set's binary_logloss: 0.210915
[8200]	valid_set's binary_logloss: 0.210905
[8250]	valid_set's binary_logloss: 0.210926
[8300]	valid_set's binary_logloss: 0.21094
[8350]	valid_set's binary_logloss: 0.210947
[8400]	valid_set's binary_logloss: 0.210951
[8450]	valid_set's binary_logloss: 0.210967
[8500]	valid_set's binary_logloss: 0.210986
[8550]	valid_set's binary_logloss: 0.211017
[8600]	valid_set's binary_logloss: 0.211041
[8650]	valid_set's binary_logloss: 0.211049
[8700]	valid_set's binary_logloss: 0.211093
[8750]	valid_set's binary_logloss: 0.211148
[8800]	valid_set's binary_logloss: 0.211181
[8850]	valid_set's binary_logloss: 0.211214
[8900]	valid_set's binary_logloss: 0.211229
[8950]	valid_set's binary_logloss: 0.211232
[9000]	valid_set's binary_logloss: 0.211283
[9050]	valid_set's binary_logloss: 0.211318
[9100]	valid_set's binary_logloss: 0.211328
[9150]	valid_set's binary_logloss: 0.211337
[9200]	valid_set's binary_logloss: 0.211317
[9250]	valid_set's binary_logloss: 0.211313
[9300]	valid_set's binary_logloss: 0.211333
[9350]	valid_set's binary_logloss: 0.211329
[9400]	valid_set's binary_logloss: 0.211336
[9450]	valid_set's binary_logloss: 0.211386
[9500]	valid_set's binary_logloss: 0.211427
[9550]	valid_set's binary_logloss: 0.211474
[9600]	valid_set's binary_logloss: 0.211506
[9650]	valid_set's binary_logloss: 0.211517

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.280002
[100]	valid_set's binary_logloss: 0.257566
[150]	valid_set's binary_logloss: 0.249471
[200]	valid_set's binary_logloss: 0.244748
[250]	valid_set's binary_logloss: 0.241272
[300]	valid_set's binary_logloss: 0.238372
[350]	valid_set's binary_logloss: 0.236045
[400]	valid_set's binary_logloss: 0.234031
[450]	valid_set's binary_logloss: 0.232463
[500]	valid_set's binary_logloss: 0.231019
[550]	valid_set's binary_logloss: 0.230095
[600]	valid_set's binary_logloss: 0.229063
[650]	valid_set's binary_logloss: 0.228115
[700]	valid_set's binary_logloss: 0.227037
[750]	valid_set's binary_logloss: 0.226292
[800]	valid_set's binary_logloss: 0.225492
[850]	valid_set's binary_logloss: 0.22487
[900]	valid_set's binary_logloss: 0.224296
[950]	valid_set's binary_logloss: 0.223797
[1000]	valid_set's binary_logloss: 0.223335
[1050]	valid_set's binary_logloss: 0.222874
[1100]	valid_set's binary_logloss: 0.22246
[1150]	valid_set's binary_logloss: 0.221985
[1200]	valid_set's binary_logloss: 0.221695
[1250]	valid_set's binary_logloss: 0.221408
[1300]	valid_set's binary_logloss: 0.221138
[1350]	valid_set's binary_logloss: 0.220757
[1400]	valid_set's binary_logloss: 0.220429
[1450]	valid_set's binary_logloss: 0.220116
[1500]	valid_set's binary_logloss: 0.219797
[1550]	valid_set's binary_logloss: 0.219509
[1600]	valid_set's binary_logloss: 0.219253
[1650]	valid_set's binary_logloss: 0.218902
[1700]	valid_set's binary_logloss: 0.218677
[1750]	valid_set's binary_logloss: 0.218455
[1800]	valid_set's binary_logloss: 0.218251
[1850]	valid_set's binary_logloss: 0.218098
[1900]	valid_set's binary_logloss: 0.217945
[1950]	valid_set's binary_logloss: 0.217766
[2000]	valid_set's binary_logloss: 0.217602
[2050]	valid_set's binary_logloss: 0.217467
[2100]	valid_set's binary_logloss: 0.217314
[2150]	valid_set's binary_logloss: 0.217154
[2200]	valid_set's binary_logloss: 0.217063
[2250]	valid_set's binary_logloss: 0.216883
[2300]	valid_set's binary_logloss: 0.216746
[2350]	valid_set's binary_logloss: 0.216624
[2400]	valid_set's binary_logloss: 0.216575
[2450]	valid_set's binary_logloss: 0.216505
[2500]	valid_set's binary_logloss: 0.21635
[2550]	valid_set's binary_logloss: 0.216234
[2600]	valid_set's binary_logloss: 0.216166
[2650]	valid_set's binary_logloss: 0.216082
[2700]	valid_set's binary_logloss: 0.215988
[2750]	valid_set's binary_logloss: 0.21587
[2800]	valid_set's binary_logloss: 0.215719
[2850]	valid_set's binary_logloss: 0.215601
[2900]	valid_set's binary_logloss: 0.215467
[2950]	valid_set's binary_logloss: 0.215368
[3000]	valid_set's binary_logloss: 0.215306
[3050]	valid_set's binary_logloss: 0.215241
[3100]	valid_set's binary_logloss: 0.215186
[3150]	valid_set's binary_logloss: 0.215118
[3200]	valid_set's binary_logloss: 0.21499
[3250]	valid_set's binary_logloss: 0.214892
[3300]	valid_set's binary_logloss: 0.214845
[3350]	valid_set's binary_logloss: 0.214787
[3400]	valid_set's binary_logloss: 0.214713
[3450]	valid_set's binary_logloss: 0.214656
[3500]	valid_set's binary_logloss: 0.214553
[3550]	valid_set's binary_logloss: 0.214497
[3600]	valid_set's binary_logloss: 0.21441
[3650]	valid_set's binary_logloss: 0.21434
[3700]	valid_set's binary_logloss: 0.214272
[3750]	valid_set's binary_logloss: 0.214233
[3800]	valid_set's binary_logloss: 0.214172
[3850]	valid_set's binary_logloss: 0.214145
[3900]	valid_set's binary_logloss: 0.214094
[3950]	valid_set's binary_logloss: 0.214066
[4000]	valid_set's binary_logloss: 0.214076
[4050]	valid_set's binary_logloss: 0.214002
[4100]	valid_set's binary_logloss: 0.213938
[4150]	valid_set's binary_logloss: 0.213881
[4200]	valid_set's binary_logloss: 0.213807
[4250]	valid_set's binary_logloss: 0.213793
[4300]	valid_set's binary_logloss: 0.213804
[4350]	valid_set's binary_logloss: 0.213785
[4400]	valid_set's binary_logloss: 0.213712
[4450]	valid_set's binary_logloss: 0.213698
[4500]	valid_set's binary_logloss: 0.21369
[4550]	valid_set's binary_logloss: 0.213658
[4600]	valid_set's binary_logloss: 0.213594
[4650]	valid_set's binary_logloss: 0.213582
[4700]	valid_set's binary_logloss: 0.213582
[4750]	valid_set's binary_logloss: 0.21357
[4800]	valid_set's binary_logloss: 0.213538
[4850]	valid_set's binary_logloss: 0.21355
[4900]	valid_set's binary_logloss: 0.213567
[4950]	valid_set's binary_logloss: 0.213581
[5000]	valid_set's binary_logloss: 0.21351
[5050]	valid_set's binary_logloss: 0.213473
[5100]	valid_set's binary_logloss: 0.213432
[5150]	valid_set's binary_logloss: 0.2134
[5200]	valid_set's binary_logloss: 0.213314
[5250]	valid_set's binary_logloss: 0.213299
[5300]	valid_set's binary_logloss: 0.213197
[5350]	valid_set's binary_logloss: 0.213161
[5400]	valid_set's binary_logloss: 0.213163
[5450]	valid_set's binary_logloss: 0.21314
[5500]	valid_set's binary_logloss: 0.213128
[5550]	valid_set's binary_logloss: 0.213097
[5600]	valid_set's binary_logloss: 0.213094
[5650]	valid_set's binary_logloss: 0.213063
[5700]	valid_set's binary_logloss: 0.213058
[5750]	valid_set's binary_logloss: 0.213049
[5800]	valid_set's binary_logloss: 0.213029
[5850]	valid_set's binary_logloss: 0.213019
[5900]	valid_set's binary_logloss: 0.213011
[5950]	valid_set's binary_logloss: 0.213
[6000]	valid_set's binary_logloss: 0.213013
[6050]	valid_set's binary_logloss: 0.213028
[6100]	valid_set's binary_logloss: 0.213031
[6150]	valid_set's binary_logloss: 0.212994
[6200]	valid_set's binary_logloss: 0.212974
[6250]	valid_set's binary_logloss: 0.212957
[6300]	valid_set's binary_logloss: 0.213004
[6350]	valid_set's binary_logloss: 0.212948
[6400]	valid_set's binary_logloss: 0.212948
[6450]	valid_set's binary_logloss: 0.212941
[6500]	valid_set's binary_logloss: 0.21296
[6550]	valid_set's binary_logloss: 0.212976
[6600]	valid_set's binary_logloss: 0.212978
[6650]	valid_set's binary_logloss: 0.212938
[6700]	valid_set's binary_logloss: 0.212897
[6750]	valid_set's binary_logloss: 0.212917
[6800]	valid_set's binary_logloss: 0.212926
[6850]	valid_set's binary_logloss: 0.212939
[6900]	valid_set's binary_logloss: 0.212927
[6950]	valid_set's binary_logloss: 0.212881
[7000]	valid_set's binary_logloss: 0.212864
[7050]	valid_set's binary_logloss: 0.212904
[7100]	valid_set's binary_logloss: 0.212884
[7150]	valid_set's binary_logloss: 0.212923
[7200]	valid_set's binary_logloss: 0.212924
[7250]	valid_set's binary_logloss: 0.212903
[7300]	valid_set's binary_logloss: 0.212939
[7350]	valid_set's binary_logloss: 0.212945
[7400]	valid_set's binary_logloss: 0.212938
[7450]	valid_set's binary_logloss: 0.212932
[7500]	valid_set's binary_logloss: 0.212941
[7550]	valid_set's binary_logloss: 0.212935
[7600]	valid_set's binary_logloss: 0.212939
[7650]	valid_set's binary_logloss: 0.212966
[7700]	valid_set's binary_logloss: 0.212996
[7750]	valid_set's binary_logloss: 0.213002
[7800]	valid_set's binary_logloss: 0.212999
[7850]	valid_set's binary_logloss: 0.213023
[7900]	valid_set's binary_logloss: 0.213045
[7950]	valid_set's binary_logloss: 0.213046
[8000]	valid_set's binary_logloss: 0.213042
[8050]	valid_set's binary_logloss: 0.213055
[8100]	valid_set's binary_logloss: 0.213075
[8150]	valid_set's binary_logloss: 0.213091
[8200]	valid_set's binary_logloss: 0.21309
[8250]	valid_set's binary_logloss: 0.21308
[8300]	valid_set's binary_logloss: 0.213058
[8350]	valid_set's binary_logloss: 0.213085
[8400]	valid_set's binary_logloss: 0.213076
[8450]	valid_set's binary_logloss: 0.213093
[8500]	valid_set's binary_logloss: 0.213133
[8550]	valid_set's binary_logloss: 0.213154
[8600]	valid_set's binary_logloss: 0.213207
[8650]	valid_set's binary_logloss: 0.213253
[8700]	valid_set's binary_logloss: 0.213259
[8750]	valid_set's binary_logloss: 0.213241
[8800]	valid_set's binary_logloss: 0.213245
[8850]	valid_set's binary_logloss: 0.213237
[8900]	valid_set's binary_logloss: 0.213229
[8950]	valid_set's binary_logloss: 0.213247
[9000]	valid_set's binary_logloss: 0.213271
[9050]	valid_set's binary_logloss: 0.213282
[9100]	valid_set's binary_logloss: 0.213305

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.279246
[100]	valid_set's binary_logloss: 0.256323
[150]	valid_set's binary_logloss: 0.248116
[200]	valid_set's binary_logloss: 0.242928
[250]	valid_set's binary_logloss: 0.239839
[300]	valid_set's binary_logloss: 0.236472
[350]	valid_set's binary_logloss: 0.23393
[400]	valid_set's binary_logloss: 0.232142
[450]	valid_set's binary_logloss: 0.23057
[500]	valid_set's binary_logloss: 0.229181
[550]	valid_set's binary_logloss: 0.228162
[600]	valid_set's binary_logloss: 0.227128
[650]	valid_set's binary_logloss: 0.226177
[700]	valid_set's binary_logloss: 0.225279
[750]	valid_set's binary_logloss: 0.224537
[800]	valid_set's binary_logloss: 0.223741
[850]	valid_set's binary_logloss: 0.223044
[900]	valid_set's binary_logloss: 0.222423
[950]	valid_set's binary_logloss: 0.22183
[1000]	valid_set's binary_logloss: 0.221285
[1050]	valid_set's binary_logloss: 0.220579
[1100]	valid_set's binary_logloss: 0.220051
[1150]	valid_set's binary_logloss: 0.219623
[1200]	valid_set's binary_logloss: 0.219237
[1250]	valid_set's binary_logloss: 0.218829
[1300]	valid_set's binary_logloss: 0.218457
[1350]	valid_set's binary_logloss: 0.218073
[1400]	valid_set's binary_logloss: 0.217657
[1450]	valid_set's binary_logloss: 0.217354
[1500]	valid_set's binary_logloss: 0.217044
[1550]	valid_set's binary_logloss: 0.216653
[1600]	valid_set's binary_logloss: 0.216369
[1650]	valid_set's binary_logloss: 0.216089
[1700]	valid_set's binary_logloss: 0.215852
[1750]	valid_set's binary_logloss: 0.215559
[1800]	valid_set's binary_logloss: 0.215386
[1850]	valid_set's binary_logloss: 0.21518
[1900]	valid_set's binary_logloss: 0.215001
[1950]	valid_set's binary_logloss: 0.214751
[2000]	valid_set's binary_logloss: 0.214545
[2050]	valid_set's binary_logloss: 0.214373
[2100]	valid_set's binary_logloss: 0.214204
[2150]	valid_set's binary_logloss: 0.214028
[2200]	valid_set's binary_logloss: 0.213883
[2250]	valid_set's binary_logloss: 0.213726
[2300]	valid_set's binary_logloss: 0.213504
[2350]	valid_set's binary_logloss: 0.213362
[2400]	valid_set's binary_logloss: 0.213157
[2450]	valid_set's binary_logloss: 0.212982
[2500]	valid_set's binary_logloss: 0.212834
[2550]	valid_set's binary_logloss: 0.212684
[2600]	valid_set's binary_logloss: 0.212578
[2650]	valid_set's binary_logloss: 0.212435
[2700]	valid_set's binary_logloss: 0.212287
[2750]	valid_set's binary_logloss: 0.212177
[2800]	valid_set's binary_logloss: 0.212076
[2850]	valid_set's binary_logloss: 0.212003
[2900]	valid_set's binary_logloss: 0.211904
[2950]	valid_set's binary_logloss: 0.211815
[3000]	valid_set's binary_logloss: 0.211713
[3050]	valid_set's binary_logloss: 0.211665
[3100]	valid_set's binary_logloss: 0.211584
[3150]	valid_set's binary_logloss: 0.211512
[3200]	valid_set's binary_logloss: 0.211414
[3250]	valid_set's binary_logloss: 0.211358
[3300]	valid_set's binary_logloss: 0.211282
[3350]	valid_set's binary_logloss: 0.211158
[3400]	valid_set's binary_logloss: 0.211064
[3450]	valid_set's binary_logloss: 0.211043
[3500]	valid_set's binary_logloss: 0.210957
[3550]	valid_set's binary_logloss: 0.210871
[3600]	valid_set's binary_logloss: 0.210846
[3650]	valid_set's binary_logloss: 0.21082
[3700]	valid_set's binary_logloss: 0.210771
[3750]	valid_set's binary_logloss: 0.210728
[3800]	valid_set's binary_logloss: 0.210623
[3850]	valid_set's binary_logloss: 0.210571
[3900]	valid_set's binary_logloss: 0.210518
[3950]	valid_set's binary_logloss: 0.210498
[4000]	valid_set's binary_logloss: 0.210436
[4050]	valid_set's binary_logloss: 0.210383
[4100]	valid_set's binary_logloss: 0.210343
[4150]	valid_set's binary_logloss: 0.210294
[4200]	valid_set's binary_logloss: 0.210234
[4250]	valid_set's binary_logloss: 0.210187
[4300]	valid_set's binary_logloss: 0.210178
[4350]	valid_set's binary_logloss: 0.21014
[4400]	valid_set's binary_logloss: 0.210112
[4450]	valid_set's binary_logloss: 0.210084
[4500]	valid_set's binary_logloss: 0.210039
[4550]	valid_set's binary_logloss: 0.209973
[4600]	valid_set's binary_logloss: 0.209932
[4650]	valid_set's binary_logloss: 0.209892
[4700]	valid_set's binary_logloss: 0.209893
[4750]	valid_set's binary_logloss: 0.209891
[4800]	valid_set's binary_logloss: 0.209864
[4850]	valid_set's binary_logloss: 0.209834
[4900]	valid_set's binary_logloss: 0.209779
[4950]	valid_set's binary_logloss: 0.209787
[5000]	valid_set's binary_logloss: 0.209784
[5050]	valid_set's binary_logloss: 0.209747
[5100]	valid_set's binary_logloss: 0.209715
[5150]	valid_set's binary_logloss: 0.209707
[5200]	valid_set's binary_logloss: 0.209688
[5250]	valid_set's binary_logloss: 0.209723
[5300]	valid_set's binary_logloss: 0.209709
[5350]	valid_set's binary_logloss: 0.209675
[5400]	valid_set's binary_logloss: 0.209638
[5450]	valid_set's binary_logloss: 0.209666
[5500]	valid_set's binary_logloss: 0.209671
[5550]	valid_set's binary_logloss: 0.209661
[5600]	valid_set's binary_logloss: 0.209613
[5650]	valid_set's binary_logloss: 0.209539
[5700]	valid_set's binary_logloss: 0.209526
[5750]	valid_set's binary_logloss: 0.209507
[5800]	valid_set's binary_logloss: 0.209544
[5850]	valid_set's binary_logloss: 0.209552
[5900]	valid_set's binary_logloss: 0.209544
[5950]	valid_set's binary_logloss: 0.209528
[6000]	valid_set's binary_logloss: 0.209491
[6050]	valid_set's binary_logloss: 0.209477
[6100]	valid_set's binary_logloss: 0.209435
[6150]	valid_set's binary_logloss: 0.209431
[6200]	valid_set's binary_logloss: 0.20938
[6250]	valid_set's binary_logloss: 0.209401
[6300]	valid_set's binary_logloss: 0.209356
[6350]	valid_set's binary_logloss: 0.209346
[6400]	valid_set's binary_logloss: 0.209353
[6450]	valid_set's binary_logloss: 0.209312
[6500]	valid_set's binary_logloss: 0.209262
[6550]	valid_set's binary_logloss: 0.209238
[6600]	valid_set's binary_logloss: 0.20926
[6650]	valid_set's binary_logloss: 0.209247
[6700]	valid_set's binary_logloss: 0.209261
[6750]	valid_set's binary_logloss: 0.209272
[6800]	valid_set's binary_logloss: 0.209271
[6850]	valid_set's binary_logloss: 0.209285
[6900]	valid_set's binary_logloss: 0.209252
[6950]	valid_set's binary_logloss: 0.209258
[7000]	valid_set's binary_logloss: 0.209232
[7050]	valid_set's binary_logloss: 0.209242
[7100]	valid_set's binary_logloss: 0.209258
[7150]	valid_set's binary_logloss: 0.209264
[7200]	valid_set's binary_logloss: 0.20924
[7250]	valid_set's binary_logloss: 0.20925
[7300]	valid_set's binary_logloss: 0.209278
[7350]	valid_set's binary_logloss: 0.209262
[7400]	valid_set's binary_logloss: 0.209303
[7450]	valid_set's binary_logloss: 0.209287
[7500]	valid_set's binary_logloss: 0.209308
[7550]	valid_set's binary_logloss: 0.20931
[7600]	valid_set's binary_logloss: 0.209344
[7650]	valid_set's binary_logloss: 0.209404
[7700]	valid_set's binary_logloss: 0.209409
[7750]	valid_set's binary_logloss: 0.209407
[7800]	valid_set's binary_logloss: 0.209411
[7850]	valid_set's binary_logloss: 0.209389
[7900]	valid_set's binary_logloss: 0.209365
[7950]	valid_set's binary_logloss: 0.209364
[8000]	valid_set's binary_logloss: 0.209388
[8050]	valid_set's binary_logloss: 0.209393
[8100]	valid_set's binary_logloss: 0.209422
[8150]	valid_set's binary_logloss: 0.209434
[8200]	valid_set's binary_logloss: 0.209461
[8250]	valid_set's binary_logloss: 0.209482
[8300]	valid_set's binary_logloss: 0.209504
[8350]	valid_set's binary_logloss: 0.209493
[8400]	valid_set's binary_logloss: 0.209513
[8450]	valid_set's binary_logloss: 0.209501
[8500]	valid_set's binary_logloss: 0.209524
[8550]	valid_set's binary_logloss: 0.209542
[8600]	valid_set's binary_logloss: 0.209567
[8650]	valid_set's binary_logloss: 0.209569
[8700]	valid_set's binary_logloss: 0.20959
[8750]	valid_set's binary_logloss: 0.209594
[8800]	valid_set's binary_logloss: 0.209639
[8850]	valid_set's binary_logloss: 0.209658
[8900]	valid_set's binary_logloss: 0.209679
[8950]	valid_set's binary_logloss: 0.20973
[9000]	valid_set's binary_logloss: 0.209747
[9050]	valid_set's binary_logloss: 0.209757
[9100]	valid_set's binary_logloss: 0.209771

Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
	0.9573	 = Validation score   (roc_auc)
	179.22s	 = Training   runtime
	12.11s	 = Validation runtime
	5579.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1606.24s of the 1606.24s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.312388
[100]	valid_set's binary_logloss: 0.283257
[150]	valid_set's binary_logloss: 0.270444
[200]	valid_set's binary_logloss: 0.262578
[250]	valid_set's binary_logloss: 0.257546
[300]	valid_set's binary_logloss: 0.253902
[350]	valid_set's binary_logloss: 0.250963
[400]	valid_set's binary_logloss: 0.248617
[450]	valid_set's binary_logloss: 0.246499
[500]	valid_set's binary_logloss: 0.244665
[550]	valid_set's binary_logloss: 0.243017
[600]	valid_set's binary_logloss: 0.24132
[650]	valid_set's binary_logloss: 0.240096
[700]	valid_set's binary_logloss: 0.23894
[750]	valid_set's binary_logloss: 0.237886
[800]	valid_set's binary_logloss: 0.23683
[850]	valid_set's binary_logloss: 0.235989
[900]	valid_set's binary_logloss: 0.235211
[950]	valid_set's binary_logloss: 0.234467
[1000]	valid_set's binary_logloss: 0.233832
[1050]	valid_set's binary_logloss: 0.233104
[1100]	valid_set's binary_logloss: 0.232583
[1150]	valid_set's binary_logloss: 0.232089
[1200]	valid_set's binary_logloss: 0.231491
[1250]	valid_set's binary_logloss: 0.230965
[1300]	valid_set's binary_logloss: 0.230403
[1350]	valid_set's binary_logloss: 0.229978
[1400]	valid_set's binary_logloss: 0.229508
[1450]	valid_set's binary_logloss: 0.229029
[1500]	valid_set's binary_logloss: 0.228588
[1550]	valid_set's binary_logloss: 0.228219
[1600]	valid_set's binary_logloss: 0.227878
[1650]	valid_set's binary_logloss: 0.227519
[1700]	valid_set's binary_logloss: 0.227154
[1750]	valid_set's binary_logloss: 0.226805
[1800]	valid_set's binary_logloss: 0.226506
[1850]	valid_set's binary_logloss: 0.226232
[1900]	valid_set's binary_logloss: 0.225933
[1950]	valid_set's binary_logloss: 0.225604
[2000]	valid_set's binary_logloss: 0.225352
[2050]	valid_set's binary_logloss: 0.225109
[2100]	valid_set's binary_logloss: 0.224861
[2150]	valid_set's binary_logloss: 0.22457
[2200]	valid_set's binary_logloss: 0.224357
[2250]	valid_set's binary_logloss: 0.224157
[2300]	valid_set's binary_logloss: 0.223883
[2350]	valid_set's binary_logloss: 0.223673
[2400]	valid_set's binary_logloss: 0.223457
[2450]	valid_set's binary_logloss: 0.223242
[2500]	valid_set's binary_logloss: 0.223073
[2550]	valid_set's binary_logloss: 0.222861
[2600]	valid_set's binary_logloss: 0.222702
[2650]	valid_set's binary_logloss: 0.222531
[2700]	valid_set's binary_logloss: 0.222347
[2750]	valid_set's binary_logloss: 0.222189
[2800]	valid_set's binary_logloss: 0.221995
[2850]	valid_set's binary_logloss: 0.221842
[2900]	valid_set's binary_logloss: 0.221647
[2950]	valid_set's binary_logloss: 0.221476
[3000]	valid_set's binary_logloss: 0.221348
[3050]	valid_set's binary_logloss: 0.221201
[3100]	valid_set's binary_logloss: 0.221117
[3150]	valid_set's binary_logloss: 0.220983
[3200]	valid_set's binary_logloss: 0.220821
[3250]	valid_set's binary_logloss: 0.220694
[3300]	valid_set's binary_logloss: 0.220572
[3350]	valid_set's binary_logloss: 0.220444
[3400]	valid_set's binary_logloss: 0.220324
[3450]	valid_set's binary_logloss: 0.220223
[3500]	valid_set's binary_logloss: 0.220111
[3550]	valid_set's binary_logloss: 0.220016
[3600]	valid_set's binary_logloss: 0.219904
[3650]	valid_set's binary_logloss: 0.219816
[3700]	valid_set's binary_logloss: 0.219737
[3750]	valid_set's binary_logloss: 0.219626
[3800]	valid_set's binary_logloss: 0.219525
[3850]	valid_set's binary_logloss: 0.219469
[3900]	valid_set's binary_logloss: 0.219403
[3950]	valid_set's binary_logloss: 0.219346
[4000]	valid_set's binary_logloss: 0.219245
[4050]	valid_set's binary_logloss: 0.21914
[4100]	valid_set's binary_logloss: 0.219067
[4150]	valid_set's binary_logloss: 0.219
[4200]	valid_set's binary_logloss: 0.218932
[4250]	valid_set's binary_logloss: 0.218856
[4300]	valid_set's binary_logloss: 0.218776
[4350]	valid_set's binary_logloss: 0.21869
[4400]	valid_set's binary_logloss: 0.218587
[4450]	valid_set's binary_logloss: 0.218518
[4500]	valid_set's binary_logloss: 0.218453
[4550]	valid_set's binary_logloss: 0.218381
[4600]	valid_set's binary_logloss: 0.21833
[4650]	valid_set's binary_logloss: 0.21827
[4700]	valid_set's binary_logloss: 0.218178
[4750]	valid_set's binary_logloss: 0.218156
[4800]	valid_set's binary_logloss: 0.218094
[4850]	valid_set's binary_logloss: 0.21803
[4900]	valid_set's binary_logloss: 0.217936
[4950]	valid_set's binary_logloss: 0.217847
[5000]	valid_set's binary_logloss: 0.217777
[5050]	valid_set's binary_logloss: 0.217714
[5100]	valid_set's binary_logloss: 0.217647
[5150]	valid_set's binary_logloss: 0.217596
[5200]	valid_set's binary_logloss: 0.217512
[5250]	valid_set's binary_logloss: 0.21746
[5300]	valid_set's binary_logloss: 0.217371
[5350]	valid_set's binary_logloss: 0.21732
[5400]	valid_set's binary_logloss: 0.217267
[5450]	valid_set's binary_logloss: 0.217216
[5500]	valid_set's binary_logloss: 0.217174
[5550]	valid_set's binary_logloss: 0.217146
[5600]	valid_set's binary_logloss: 0.217093
[5650]	valid_set's binary_logloss: 0.217031
[5700]	valid_set's binary_logloss: 0.216974
[5750]	valid_set's binary_logloss: 0.21694
[5800]	valid_set's binary_logloss: 0.216898
[5850]	valid_set's binary_logloss: 0.216824
[5900]	valid_set's binary_logloss: 0.216761
[5950]	valid_set's binary_logloss: 0.216729
[6000]	valid_set's binary_logloss: 0.216699
[6050]	valid_set's binary_logloss: 0.216674
[6100]	valid_set's binary_logloss: 0.21662
[6150]	valid_set's binary_logloss: 0.216602
[6200]	valid_set's binary_logloss: 0.216545
[6250]	valid_set's binary_logloss: 0.216501
[6300]	valid_set's binary_logloss: 0.21648
[6350]	valid_set's binary_logloss: 0.21645
[6400]	valid_set's binary_logloss: 0.216399
[6450]	valid_set's binary_logloss: 0.216381
[6500]	valid_set's binary_logloss: 0.216344
[6550]	valid_set's binary_logloss: 0.216324
[6600]	valid_set's binary_logloss: 0.216262
[6650]	valid_set's binary_logloss: 0.216213
[6700]	valid_set's binary_logloss: 0.21617
[6750]	valid_set's binary_logloss: 0.216164
[6800]	valid_set's binary_logloss: 0.216113
[6850]	valid_set's binary_logloss: 0.216089
[6900]	valid_set's binary_logloss: 0.216031
[6950]	valid_set's binary_logloss: 0.21599
[7000]	valid_set's binary_logloss: 0.215946
[7050]	valid_set's binary_logloss: 0.21593
[7100]	valid_set's binary_logloss: 0.215901
[7150]	valid_set's binary_logloss: 0.215863
[7200]	valid_set's binary_logloss: 0.215828
[7250]	valid_set's binary_logloss: 0.215805
[7300]	valid_set's binary_logloss: 0.215759
[7350]	valid_set's binary_logloss: 0.215746
[7400]	valid_set's binary_logloss: 0.215719
[7450]	valid_set's binary_logloss: 0.215705
[7500]	valid_set's binary_logloss: 0.215699
[7550]	valid_set's binary_logloss: 0.215679
[7600]	valid_set's binary_logloss: 0.215667
[7650]	valid_set's binary_logloss: 0.215655
[7700]	valid_set's binary_logloss: 0.215662
[7750]	valid_set's binary_logloss: 0.215636
[7800]	valid_set's binary_logloss: 0.21562
[7850]	valid_set's binary_logloss: 0.215601
[7900]	valid_set's binary_logloss: 0.215586
[7950]	valid_set's binary_logloss: 0.215588
[8000]	valid_set's binary_logloss: 0.215567
[8050]	valid_set's binary_logloss: 0.215543
[8100]	valid_set's binary_logloss: 0.215545
[8150]	valid_set's binary_logloss: 0.215548
[8200]	valid_set's binary_logloss: 0.215528
[8250]	valid_set's binary_logloss: 0.215491
[8300]	valid_set's binary_logloss: 0.215491
[8350]	valid_set's binary_logloss: 0.215457
[8400]	valid_set's binary_logloss: 0.215455
[8450]	valid_set's binary_logloss: 0.21543
[8500]	valid_set's binary_logloss: 0.21541
[8550]	valid_set's binary_logloss: 0.215389
[8600]	valid_set's binary_logloss: 0.215353
[8650]	valid_set's binary_logloss: 0.21535
[8700]	valid_set's binary_logloss: 0.215344
[8750]	valid_set's binary_logloss: 0.215348
[8800]	valid_set's binary_logloss: 0.215327
[8850]	valid_set's binary_logloss: 0.215314
[8900]	valid_set's binary_logloss: 0.215317
[8950]	valid_set's binary_logloss: 0.2153
[9000]	valid_set's binary_logloss: 0.21528
[9050]	valid_set's binary_logloss: 0.21527
[9100]	valid_set's binary_logloss: 0.215298
[9150]	valid_set's binary_logloss: 0.215286
[9200]	valid_set's binary_logloss: 0.215283
[9250]	valid_set's binary_logloss: 0.215282
[9300]	valid_set's binary_logloss: 0.215285
[9350]	valid_set's binary_logloss: 0.215269
[9400]	valid_set's binary_logloss: 0.215269
[9450]	valid_set's binary_logloss: 0.215263
[9500]	valid_set's binary_logloss: 0.215248
[9550]	valid_set's binary_logloss: 0.215231
[9600]	valid_set's binary_logloss: 0.215234
[9650]	valid_set's binary_logloss: 0.215214
[9700]	valid_set's binary_logloss: 0.2152
[9750]	valid_set's binary_logloss: 0.215172
[9800]	valid_set's binary_logloss: 0.215174
[9850]	valid_set's binary_logloss: 0.215172
[9900]	valid_set's binary_logloss: 0.215121
[9950]	valid_set's binary_logloss: 0.215108
[10000]	valid_set's binary_logloss: 0.215109

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.311421
[100]	valid_set's binary_logloss: 0.284521
[150]	valid_set's binary_logloss: 0.271489
[200]	valid_set's binary_logloss: 0.264267
[250]	valid_set's binary_logloss: 0.258903
[300]	valid_set's binary_logloss: 0.255066
[350]	valid_set's binary_logloss: 0.251903
[400]	valid_set's binary_logloss: 0.249402
[450]	valid_set's binary_logloss: 0.247197
[500]	valid_set's binary_logloss: 0.245313
[550]	valid_set's binary_logloss: 0.243557
[600]	valid_set's binary_logloss: 0.241999
[650]	valid_set's binary_logloss: 0.240577
[700]	valid_set's binary_logloss: 0.239427
[750]	valid_set's binary_logloss: 0.238522
[800]	valid_set's binary_logloss: 0.237402
[850]	valid_set's binary_logloss: 0.236582
[900]	valid_set's binary_logloss: 0.235642
[950]	valid_set's binary_logloss: 0.234801
[1000]	valid_set's binary_logloss: 0.234052
[1050]	valid_set's binary_logloss: 0.233364
[1100]	valid_set's binary_logloss: 0.232703
[1150]	valid_set's binary_logloss: 0.232104
[1200]	valid_set's binary_logloss: 0.231575
[1250]	valid_set's binary_logloss: 0.231094
[1300]	valid_set's binary_logloss: 0.230554
[1350]	valid_set's binary_logloss: 0.230062
[1400]	valid_set's binary_logloss: 0.229674
[1450]	valid_set's binary_logloss: 0.229206
[1500]	valid_set's binary_logloss: 0.228853
[1550]	valid_set's binary_logloss: 0.2284
[1600]	valid_set's binary_logloss: 0.227977
[1650]	valid_set's binary_logloss: 0.227605
[1700]	valid_set's binary_logloss: 0.227331
[1750]	valid_set's binary_logloss: 0.226983
[1800]	valid_set's binary_logloss: 0.226628
[1850]	valid_set's binary_logloss: 0.226351
[1900]	valid_set's binary_logloss: 0.226
[1950]	valid_set's binary_logloss: 0.22567
[2000]	valid_set's binary_logloss: 0.225443
[2050]	valid_set's binary_logloss: 0.225166
[2100]	valid_set's binary_logloss: 0.224928
[2150]	valid_set's binary_logloss: 0.224711
[2200]	valid_set's binary_logloss: 0.224481
[2250]	valid_set's binary_logloss: 0.224247
[2300]	valid_set's binary_logloss: 0.22405
[2350]	valid_set's binary_logloss: 0.223836
[2400]	valid_set's binary_logloss: 0.223592
[2450]	valid_set's binary_logloss: 0.223391
[2500]	valid_set's binary_logloss: 0.223189
[2550]	valid_set's binary_logloss: 0.222984
[2600]	valid_set's binary_logloss: 0.22278
[2650]	valid_set's binary_logloss: 0.222616
[2700]	valid_set's binary_logloss: 0.222478
[2750]	valid_set's binary_logloss: 0.222283
[2800]	valid_set's binary_logloss: 0.222124
[2850]	valid_set's binary_logloss: 0.22197
[2900]	valid_set's binary_logloss: 0.22184
[2950]	valid_set's binary_logloss: 0.221704
[3000]	valid_set's binary_logloss: 0.221547
[3050]	valid_set's binary_logloss: 0.221394
[3100]	valid_set's binary_logloss: 0.221245
[3150]	valid_set's binary_logloss: 0.221126
[3200]	valid_set's binary_logloss: 0.220983
[3250]	valid_set's binary_logloss: 0.220838
[3300]	valid_set's binary_logloss: 0.220669
[3350]	valid_set's binary_logloss: 0.220536
[3400]	valid_set's binary_logloss: 0.220396
[3450]	valid_set's binary_logloss: 0.220291
[3500]	valid_set's binary_logloss: 0.220198
[3550]	valid_set's binary_logloss: 0.220105
[3600]	valid_set's binary_logloss: 0.219998
[3650]	valid_set's binary_logloss: 0.219906
[3700]	valid_set's binary_logloss: 0.219754
[3750]	valid_set's binary_logloss: 0.21965
[3800]	valid_set's binary_logloss: 0.219546
[3850]	valid_set's binary_logloss: 0.219393
[3900]	valid_set's binary_logloss: 0.219274
[3950]	valid_set's binary_logloss: 0.219198
[4000]	valid_set's binary_logloss: 0.219092
[4050]	valid_set's binary_logloss: 0.218997
[4100]	valid_set's binary_logloss: 0.218898
[4150]	valid_set's binary_logloss: 0.218827
[4200]	valid_set's binary_logloss: 0.218752
[4250]	valid_set's binary_logloss: 0.218664
[4300]	valid_set's binary_logloss: 0.218582
[4350]	valid_set's binary_logloss: 0.218538
[4400]	valid_set's binary_logloss: 0.218469
[4450]	valid_set's binary_logloss: 0.218399
[4500]	valid_set's binary_logloss: 0.218313
[4550]	valid_set's binary_logloss: 0.218259
[4600]	valid_set's binary_logloss: 0.218186
[4650]	valid_set's binary_logloss: 0.218099
[4700]	valid_set's binary_logloss: 0.218051
[4750]	valid_set's binary_logloss: 0.217981
[4800]	valid_set's binary_logloss: 0.217901
[4850]	valid_set's binary_logloss: 0.217828
[4900]	valid_set's binary_logloss: 0.217751
[4950]	valid_set's binary_logloss: 0.217673
[5000]	valid_set's binary_logloss: 0.217625
[5050]	valid_set's binary_logloss: 0.217558
[5100]	valid_set's binary_logloss: 0.21749
[5150]	valid_set's binary_logloss: 0.217406
[5200]	valid_set's binary_logloss: 0.217362
[5250]	valid_set's binary_logloss: 0.21731
[5300]	valid_set's binary_logloss: 0.217264
[5350]	valid_set's binary_logloss: 0.217219
[5400]	valid_set's binary_logloss: 0.217151
[5450]	valid_set's binary_logloss: 0.21713
[5500]	valid_set's binary_logloss: 0.217091
[5550]	valid_set's binary_logloss: 0.217052
[5600]	valid_set's binary_logloss: 0.217014
[5650]	valid_set's binary_logloss: 0.216957
[5700]	valid_set's binary_logloss: 0.216884
[5750]	valid_set's binary_logloss: 0.216845
[5800]	valid_set's binary_logloss: 0.216783
[5850]	valid_set's binary_logloss: 0.216751
[5900]	valid_set's binary_logloss: 0.216719
[5950]	valid_set's binary_logloss: 0.216707
[6000]	valid_set's binary_logloss: 0.216653
[6050]	valid_set's binary_logloss: 0.216603
[6100]	valid_set's binary_logloss: 0.216551
[6150]	valid_set's binary_logloss: 0.216515
[6200]	valid_set's binary_logloss: 0.216453
[6250]	valid_set's binary_logloss: 0.216409
[6300]	valid_set's binary_logloss: 0.216381
[6350]	valid_set's binary_logloss: 0.216343
[6400]	valid_set's binary_logloss: 0.216308
[6450]	valid_set's binary_logloss: 0.216258
[6500]	valid_set's binary_logloss: 0.216212
[6550]	valid_set's binary_logloss: 0.216185
[6600]	valid_set's binary_logloss: 0.216122
[6650]	valid_set's binary_logloss: 0.2161
[6700]	valid_set's binary_logloss: 0.216075
[6750]	valid_set's binary_logloss: 0.216063
[6800]	valid_set's binary_logloss: 0.216046
[6850]	valid_set's binary_logloss: 0.216009
[6900]	valid_set's binary_logloss: 0.215966
[6950]	valid_set's binary_logloss: 0.215913
[7000]	valid_set's binary_logloss: 0.215888
[7050]	valid_set's binary_logloss: 0.215877
[7100]	valid_set's binary_logloss: 0.215836
[7150]	valid_set's binary_logloss: 0.215803
[7200]	valid_set's binary_logloss: 0.215755
[7250]	valid_set's binary_logloss: 0.215729
[7300]	valid_set's binary_logloss: 0.215719
[7350]	valid_set's binary_logloss: 0.215684
[7400]	valid_set's binary_logloss: 0.21564
[7450]	valid_set's binary_logloss: 0.215613
[7500]	valid_set's binary_logloss: 0.215576
[7550]	valid_set's binary_logloss: 0.215534
[7600]	valid_set's binary_logloss: 0.215536
[7650]	valid_set's binary_logloss: 0.215516
[7700]	valid_set's binary_logloss: 0.215476
[7750]	valid_set's binary_logloss: 0.215434
[7800]	valid_set's binary_logloss: 0.215397
[7850]	valid_set's binary_logloss: 0.21537
[7900]	valid_set's binary_logloss: 0.215328
[7950]	valid_set's binary_logloss: 0.215324
[8000]	valid_set's binary_logloss: 0.21526
[8050]	valid_set's binary_logloss: 0.215242
[8100]	valid_set's binary_logloss: 0.21523
[8150]	valid_set's binary_logloss: 0.215198
[8200]	valid_set's binary_logloss: 0.215168
[8250]	valid_set's binary_logloss: 0.215121
[8300]	valid_set's binary_logloss: 0.215101
[8350]	valid_set's binary_logloss: 0.215061
[8400]	valid_set's binary_logloss: 0.21502
[8450]	valid_set's binary_logloss: 0.21497
[8500]	valid_set's binary_logloss: 0.214946
[8550]	valid_set's binary_logloss: 0.214915
[8600]	valid_set's binary_logloss: 0.214894
[8650]	valid_set's binary_logloss: 0.214859
[8700]	valid_set's binary_logloss: 0.214822
[8750]	valid_set's binary_logloss: 0.214813
[8800]	valid_set's binary_logloss: 0.214774
[8850]	valid_set's binary_logloss: 0.214755
[8900]	valid_set's binary_logloss: 0.214732
[8950]	valid_set's binary_logloss: 0.214705
[9000]	valid_set's binary_logloss: 0.214704
[9050]	valid_set's binary_logloss: 0.214686
[9100]	valid_set's binary_logloss: 0.214649
[9150]	valid_set's binary_logloss: 0.214627
[9200]	valid_set's binary_logloss: 0.214613
[9250]	valid_set's binary_logloss: 0.2146
[9300]	valid_set's binary_logloss: 0.214567
[9350]	valid_set's binary_logloss: 0.214544
[9400]	valid_set's binary_logloss: 0.214533
[9450]	valid_set's binary_logloss: 0.214529
[9500]	valid_set's binary_logloss: 0.214501
[9550]	valid_set's binary_logloss: 0.214488
[9600]	valid_set's binary_logloss: 0.214478
[9650]	valid_set's binary_logloss: 0.214453
[9700]	valid_set's binary_logloss: 0.214442
[9750]	valid_set's binary_logloss: 0.214418
[9800]	valid_set's binary_logloss: 0.214398
[9850]	valid_set's binary_logloss: 0.214408
[9900]	valid_set's binary_logloss: 0.214354
[9950]	valid_set's binary_logloss: 0.214337
[10000]	valid_set's binary_logloss: 0.214329

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.311326
[100]	valid_set's binary_logloss: 0.284649
[150]	valid_set's binary_logloss: 0.272616
[200]	valid_set's binary_logloss: 0.265755
[250]	valid_set's binary_logloss: 0.260648
[300]	valid_set's binary_logloss: 0.25687
[350]	valid_set's binary_logloss: 0.253738
[400]	valid_set's binary_logloss: 0.251407
[450]	valid_set's binary_logloss: 0.249276
[500]	valid_set's binary_logloss: 0.2473
[550]	valid_set's binary_logloss: 0.245682
[600]	valid_set's binary_logloss: 0.244254
[650]	valid_set's binary_logloss: 0.243024
[700]	valid_set's binary_logloss: 0.241763
[750]	valid_set's binary_logloss: 0.240696
[800]	valid_set's binary_logloss: 0.239805
[850]	valid_set's binary_logloss: 0.238927
[900]	valid_set's binary_logloss: 0.238015
[950]	valid_set's binary_logloss: 0.237156
[1000]	valid_set's binary_logloss: 0.236453
[1050]	valid_set's binary_logloss: 0.235818
[1100]	valid_set's binary_logloss: 0.23519
[1150]	valid_set's binary_logloss: 0.234602
[1200]	valid_set's binary_logloss: 0.234009
[1250]	valid_set's binary_logloss: 0.233543
[1300]	valid_set's binary_logloss: 0.233033
[1350]	valid_set's binary_logloss: 0.232642
[1400]	valid_set's binary_logloss: 0.232249
[1450]	valid_set's binary_logloss: 0.23189
[1500]	valid_set's binary_logloss: 0.231542
[1550]	valid_set's binary_logloss: 0.231186
[1600]	valid_set's binary_logloss: 0.230826
[1650]	valid_set's binary_logloss: 0.2305
[1700]	valid_set's binary_logloss: 0.230168
[1750]	valid_set's binary_logloss: 0.229924
[1800]	valid_set's binary_logloss: 0.229602
[1850]	valid_set's binary_logloss: 0.229349
[1900]	valid_set's binary_logloss: 0.229032
[1950]	valid_set's binary_logloss: 0.228777
[2000]	valid_set's binary_logloss: 0.228514
[2050]	valid_set's binary_logloss: 0.228329
[2100]	valid_set's binary_logloss: 0.228088
[2150]	valid_set's binary_logloss: 0.227915
[2200]	valid_set's binary_logloss: 0.227684
[2250]	valid_set's binary_logloss: 0.227464
[2300]	valid_set's binary_logloss: 0.227248
[2350]	valid_set's binary_logloss: 0.227037
[2400]	valid_set's binary_logloss: 0.226888
[2450]	valid_set's binary_logloss: 0.226724
[2500]	valid_set's binary_logloss: 0.226474
[2550]	valid_set's binary_logloss: 0.226305
[2600]	valid_set's binary_logloss: 0.226152
[2650]	valid_set's binary_logloss: 0.225981
[2700]	valid_set's binary_logloss: 0.225814
[2750]	valid_set's binary_logloss: 0.225661
[2800]	valid_set's binary_logloss: 0.225484
[2850]	valid_set's binary_logloss: 0.225318
[2900]	valid_set's binary_logloss: 0.225144
[2950]	valid_set's binary_logloss: 0.225029
[3000]	valid_set's binary_logloss: 0.224937
[3050]	valid_set's binary_logloss: 0.224786
[3100]	valid_set's binary_logloss: 0.224677
[3150]	valid_set's binary_logloss: 0.224545
[3200]	valid_set's binary_logloss: 0.224427
[3250]	valid_set's binary_logloss: 0.224316
[3300]	valid_set's binary_logloss: 0.224213
[3350]	valid_set's binary_logloss: 0.224128
[3400]	valid_set's binary_logloss: 0.223996
[3450]	valid_set's binary_logloss: 0.223914
[3500]	valid_set's binary_logloss: 0.223812
[3550]	valid_set's binary_logloss: 0.223679
[3600]	valid_set's binary_logloss: 0.223587
[3650]	valid_set's binary_logloss: 0.223493
[3700]	valid_set's binary_logloss: 0.223388
[3750]	valid_set's binary_logloss: 0.223275
[3800]	valid_set's binary_logloss: 0.223196
[3850]	valid_set's binary_logloss: 0.223105
[3900]	valid_set's binary_logloss: 0.22302
[3950]	valid_set's binary_logloss: 0.222951
[4000]	valid_set's binary_logloss: 0.222887
[4050]	valid_set's binary_logloss: 0.222759
[4100]	valid_set's binary_logloss: 0.222717
[4150]	valid_set's binary_logloss: 0.222653
[4200]	valid_set's binary_logloss: 0.222559
[4250]	valid_set's binary_logloss: 0.222497
[4300]	valid_set's binary_logloss: 0.222421
[4350]	valid_set's binary_logloss: 0.22234
[4400]	valid_set's binary_logloss: 0.222287
[4450]	valid_set's binary_logloss: 0.222181
[4500]	valid_set's binary_logloss: 0.222093
[4550]	valid_set's binary_logloss: 0.222059
[4600]	valid_set's binary_logloss: 0.221984
[4650]	valid_set's binary_logloss: 0.221909
[4700]	valid_set's binary_logloss: 0.221857
[4750]	valid_set's binary_logloss: 0.221795
[4800]	valid_set's binary_logloss: 0.221716
[4850]	valid_set's binary_logloss: 0.221624
[4900]	valid_set's binary_logloss: 0.221545
[4950]	valid_set's binary_logloss: 0.221532
[5000]	valid_set's binary_logloss: 0.221483
[5050]	valid_set's binary_logloss: 0.221441
[5100]	valid_set's binary_logloss: 0.221389
[5150]	valid_set's binary_logloss: 0.221332
[5200]	valid_set's binary_logloss: 0.221266
[5250]	valid_set's binary_logloss: 0.221194
[5300]	valid_set's binary_logloss: 0.221146
[5350]	valid_set's binary_logloss: 0.221104
[5400]	valid_set's binary_logloss: 0.221069
[5450]	valid_set's binary_logloss: 0.221033
[5500]	valid_set's binary_logloss: 0.221009
[5550]	valid_set's binary_logloss: 0.220908
[5600]	valid_set's binary_logloss: 0.220882
[5650]	valid_set's binary_logloss: 0.220846
[5700]	valid_set's binary_logloss: 0.220781
[5750]	valid_set's binary_logloss: 0.220749
[5800]	valid_set's binary_logloss: 0.220716
[5850]	valid_set's binary_logloss: 0.220671
[5900]	valid_set's binary_logloss: 0.220611
[5950]	valid_set's binary_logloss: 0.220555
[6000]	valid_set's binary_logloss: 0.220482
[6050]	valid_set's binary_logloss: 0.220424
[6100]	valid_set's binary_logloss: 0.220387
[6150]	valid_set's binary_logloss: 0.220356
[6200]	valid_set's binary_logloss: 0.220341
[6250]	valid_set's binary_logloss: 0.220308
[6300]	valid_set's binary_logloss: 0.220289
[6350]	valid_set's binary_logloss: 0.22023
[6400]	valid_set's binary_logloss: 0.220199
[6450]	valid_set's binary_logloss: 0.220177
[6500]	valid_set's binary_logloss: 0.220144
[6550]	valid_set's binary_logloss: 0.2201
[6600]	valid_set's binary_logloss: 0.220062
[6650]	valid_set's binary_logloss: 0.220038
[6700]	valid_set's binary_logloss: 0.220018
[6750]	valid_set's binary_logloss: 0.220048
[6800]	valid_set's binary_logloss: 0.220016
[6850]	valid_set's binary_logloss: 0.219979
[6900]	valid_set's binary_logloss: 0.219953
[6950]	valid_set's binary_logloss: 0.219934
[7000]	valid_set's binary_logloss: 0.219925
[7050]	valid_set's binary_logloss: 0.2199
[7100]	valid_set's binary_logloss: 0.219882
[7150]	valid_set's binary_logloss: 0.219852
[7200]	valid_set's binary_logloss: 0.219836
[7250]	valid_set's binary_logloss: 0.219799
[7300]	valid_set's binary_logloss: 0.219785
[7350]	valid_set's binary_logloss: 0.21977
[7400]	valid_set's binary_logloss: 0.219757
[7450]	valid_set's binary_logloss: 0.219729
[7500]	valid_set's binary_logloss: 0.219689
[7550]	valid_set's binary_logloss: 0.219662
[7600]	valid_set's binary_logloss: 0.219603
[7650]	valid_set's binary_logloss: 0.219579
[7700]	valid_set's binary_logloss: 0.219568
[7750]	valid_set's binary_logloss: 0.219554
[7800]	valid_set's binary_logloss: 0.219534
[7850]	valid_set's binary_logloss: 0.219518
[7900]	valid_set's binary_logloss: 0.219499
[7950]	valid_set's binary_logloss: 0.21949
[8000]	valid_set's binary_logloss: 0.219456
[8050]	valid_set's binary_logloss: 0.219437
[8100]	valid_set's binary_logloss: 0.219406
[8150]	valid_set's binary_logloss: 0.219392
[8200]	valid_set's binary_logloss: 0.219361
[8250]	valid_set's binary_logloss: 0.21936
[8300]	valid_set's binary_logloss: 0.219341
[8350]	valid_set's binary_logloss: 0.219344
[8400]	valid_set's binary_logloss: 0.219337
[8450]	valid_set's binary_logloss: 0.219337
[8500]	valid_set's binary_logloss: 0.219317
[8550]	valid_set's binary_logloss: 0.219274
[8600]	valid_set's binary_logloss: 0.219272
[8650]	valid_set's binary_logloss: 0.219243
[8700]	valid_set's binary_logloss: 0.219247
[8750]	valid_set's binary_logloss: 0.219228
[8800]	valid_set's binary_logloss: 0.219227
[8850]	valid_set's binary_logloss: 0.219229
[8900]	valid_set's binary_logloss: 0.219208
[8950]	valid_set's binary_logloss: 0.219215
[9000]	valid_set's binary_logloss: 0.219219
[9050]	valid_set's binary_logloss: 0.219219
[9100]	valid_set's binary_logloss: 0.219228
[9150]	valid_set's binary_logloss: 0.219232
[9200]	valid_set's binary_logloss: 0.219225
[9250]	valid_set's binary_logloss: 0.219216
[9300]	valid_set's binary_logloss: 0.219223
[9350]	valid_set's binary_logloss: 0.219194
[9400]	valid_set's binary_logloss: 0.219178
[9450]	valid_set's binary_logloss: 0.219185
[9500]	valid_set's binary_logloss: 0.219198
[9550]	valid_set's binary_logloss: 0.21918
[9600]	valid_set's binary_logloss: 0.219154
[9650]	valid_set's binary_logloss: 0.219163
[9700]	valid_set's binary_logloss: 0.219151
[9750]	valid_set's binary_logloss: 0.219157
[9800]	valid_set's binary_logloss: 0.219144
[9850]	valid_set's binary_logloss: 0.219158
[9900]	valid_set's binary_logloss: 0.219133
[9950]	valid_set's binary_logloss: 0.219124
[10000]	valid_set's binary_logloss: 0.219109

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.313515
[100]	valid_set's binary_logloss: 0.283957
[150]	valid_set's binary_logloss: 0.27066
[200]	valid_set's binary_logloss: 0.263237
[250]	valid_set's binary_logloss: 0.257863
[300]	valid_set's binary_logloss: 0.254203
[350]	valid_set's binary_logloss: 0.250893
[400]	valid_set's binary_logloss: 0.248321
[450]	valid_set's binary_logloss: 0.246207
[500]	valid_set's binary_logloss: 0.244135
[550]	valid_set's binary_logloss: 0.242488
[600]	valid_set's binary_logloss: 0.241081
[650]	valid_set's binary_logloss: 0.239697
[700]	valid_set's binary_logloss: 0.238576
[750]	valid_set's binary_logloss: 0.237489
[800]	valid_set's binary_logloss: 0.236385
[850]	valid_set's binary_logloss: 0.235602
[900]	valid_set's binary_logloss: 0.234781
[950]	valid_set's binary_logloss: 0.233926
[1000]	valid_set's binary_logloss: 0.233206
[1050]	valid_set's binary_logloss: 0.232515
[1100]	valid_set's binary_logloss: 0.231876
[1150]	valid_set's binary_logloss: 0.231365
[1200]	valid_set's binary_logloss: 0.230911
[1250]	valid_set's binary_logloss: 0.23042
[1300]	valid_set's binary_logloss: 0.22999
[1350]	valid_set's binary_logloss: 0.22946
[1400]	valid_set's binary_logloss: 0.229039
[1450]	valid_set's binary_logloss: 0.228653
[1500]	valid_set's binary_logloss: 0.228338
[1550]	valid_set's binary_logloss: 0.227967
[1600]	valid_set's binary_logloss: 0.227623
[1650]	valid_set's binary_logloss: 0.227309
[1700]	valid_set's binary_logloss: 0.227006
[1750]	valid_set's binary_logloss: 0.226642
[1800]	valid_set's binary_logloss: 0.226326
[1850]	valid_set's binary_logloss: 0.226007
[1900]	valid_set's binary_logloss: 0.225729
[1950]	valid_set's binary_logloss: 0.2255
[2000]	valid_set's binary_logloss: 0.225212
[2050]	valid_set's binary_logloss: 0.224909
[2100]	valid_set's binary_logloss: 0.224652
[2150]	valid_set's binary_logloss: 0.224459
[2200]	valid_set's binary_logloss: 0.224257
[2250]	valid_set's binary_logloss: 0.224047
[2300]	valid_set's binary_logloss: 0.223864
[2350]	valid_set's binary_logloss: 0.223662
[2400]	valid_set's binary_logloss: 0.223514
[2450]	valid_set's binary_logloss: 0.223356
[2500]	valid_set's binary_logloss: 0.223147
[2550]	valid_set's binary_logloss: 0.223031
[2600]	valid_set's binary_logloss: 0.222858
[2650]	valid_set's binary_logloss: 0.222698
[2700]	valid_set's binary_logloss: 0.222522
[2750]	valid_set's binary_logloss: 0.222343
[2800]	valid_set's binary_logloss: 0.222205
[2850]	valid_set's binary_logloss: 0.22205
[2900]	valid_set's binary_logloss: 0.221866
[2950]	valid_set's binary_logloss: 0.221749
[3000]	valid_set's binary_logloss: 0.221642
[3050]	valid_set's binary_logloss: 0.221511
[3100]	valid_set's binary_logloss: 0.221408
[3150]	valid_set's binary_logloss: 0.221289
[3200]	valid_set's binary_logloss: 0.221157
[3250]	valid_set's binary_logloss: 0.221025
[3300]	valid_set's binary_logloss: 0.220913
[3350]	valid_set's binary_logloss: 0.220796
[3400]	valid_set's binary_logloss: 0.220696
[3450]	valid_set's binary_logloss: 0.220597
[3500]	valid_set's binary_logloss: 0.220505
[3550]	valid_set's binary_logloss: 0.220402
[3600]	valid_set's binary_logloss: 0.220307
[3650]	valid_set's binary_logloss: 0.22019
[3700]	valid_set's binary_logloss: 0.220102
[3750]	valid_set's binary_logloss: 0.220018
[3800]	valid_set's binary_logloss: 0.219919
[3850]	valid_set's binary_logloss: 0.219813
[3900]	valid_set's binary_logloss: 0.219725
[3950]	valid_set's binary_logloss: 0.219671
[4000]	valid_set's binary_logloss: 0.21958
[4050]	valid_set's binary_logloss: 0.219493
[4100]	valid_set's binary_logloss: 0.219438
[4150]	valid_set's binary_logloss: 0.219357
[4200]	valid_set's binary_logloss: 0.219264
[4250]	valid_set's binary_logloss: 0.219186
[4300]	valid_set's binary_logloss: 0.219116
[4350]	valid_set's binary_logloss: 0.219057
[4400]	valid_set's binary_logloss: 0.219017
[4450]	valid_set's binary_logloss: 0.218916
[4500]	valid_set's binary_logloss: 0.218836
[4550]	valid_set's binary_logloss: 0.218769
[4600]	valid_set's binary_logloss: 0.218688
[4650]	valid_set's binary_logloss: 0.218648
[4700]	valid_set's binary_logloss: 0.218563
[4750]	valid_set's binary_logloss: 0.218458
[4800]	valid_set's binary_logloss: 0.218405
[4850]	valid_set's binary_logloss: 0.218347
[4900]	valid_set's binary_logloss: 0.218265
[4950]	valid_set's binary_logloss: 0.218206
[5000]	valid_set's binary_logloss: 0.21814
[5050]	valid_set's binary_logloss: 0.218086
[5100]	valid_set's binary_logloss: 0.218006
[5150]	valid_set's binary_logloss: 0.21795
[5200]	valid_set's binary_logloss: 0.217862
[5250]	valid_set's binary_logloss: 0.21782
[5300]	valid_set's binary_logloss: 0.217745
[5350]	valid_set's binary_logloss: 0.217714
[5400]	valid_set's binary_logloss: 0.217654
[5450]	valid_set's binary_logloss: 0.217591
[5500]	valid_set's binary_logloss: 0.217531
[5550]	valid_set's binary_logloss: 0.217488
[5600]	valid_set's binary_logloss: 0.21745
[5650]	valid_set's binary_logloss: 0.217428
[5700]	valid_set's binary_logloss: 0.217403
[5750]	valid_set's binary_logloss: 0.217336
[5800]	valid_set's binary_logloss: 0.217304
[5850]	valid_set's binary_logloss: 0.217257
[5900]	valid_set's binary_logloss: 0.217207
[5950]	valid_set's binary_logloss: 0.217165
[6000]	valid_set's binary_logloss: 0.217136
[6050]	valid_set's binary_logloss: 0.217075
[6100]	valid_set's binary_logloss: 0.217004
[6150]	valid_set's binary_logloss: 0.216963
[6200]	valid_set's binary_logloss: 0.216906
[6250]	valid_set's binary_logloss: 0.216857
[6300]	valid_set's binary_logloss: 0.216809
[6350]	valid_set's binary_logloss: 0.216792
[6400]	valid_set's binary_logloss: 0.216711
[6450]	valid_set's binary_logloss: 0.216676
[6500]	valid_set's binary_logloss: 0.216633
[6550]	valid_set's binary_logloss: 0.216585
[6600]	valid_set's binary_logloss: 0.216544
[6650]	valid_set's binary_logloss: 0.216513
[6700]	valid_set's binary_logloss: 0.216492
[6750]	valid_set's binary_logloss: 0.216455
[6800]	valid_set's binary_logloss: 0.216432
[6850]	valid_set's binary_logloss: 0.216422
[6900]	valid_set's binary_logloss: 0.216386
[6950]	valid_set's binary_logloss: 0.216384
[7000]	valid_set's binary_logloss: 0.216371
[7050]	valid_set's binary_logloss: 0.216351
[7100]	valid_set's binary_logloss: 0.216303
[7150]	valid_set's binary_logloss: 0.216268
[7200]	valid_set's binary_logloss: 0.216252
[7250]	valid_set's binary_logloss: 0.216235
[7300]	valid_set's binary_logloss: 0.216208
[7350]	valid_set's binary_logloss: 0.216199
[7400]	valid_set's binary_logloss: 0.21618
[7450]	valid_set's binary_logloss: 0.216176
[7500]	valid_set's binary_logloss: 0.216146
[7550]	valid_set's binary_logloss: 0.216137
[7600]	valid_set's binary_logloss: 0.2161
[7650]	valid_set's binary_logloss: 0.216069
[7700]	valid_set's binary_logloss: 0.216044
[7750]	valid_set's binary_logloss: 0.216012
[7800]	valid_set's binary_logloss: 0.215978
[7850]	valid_set's binary_logloss: 0.215948
[7900]	valid_set's binary_logloss: 0.215936
[7950]	valid_set's binary_logloss: 0.215915
[8000]	valid_set's binary_logloss: 0.215901
[8050]	valid_set's binary_logloss: 0.215868
[8100]	valid_set's binary_logloss: 0.215835
[8150]	valid_set's binary_logloss: 0.215814
[8200]	valid_set's binary_logloss: 0.215809
[8250]	valid_set's binary_logloss: 0.215769
[8300]	valid_set's binary_logloss: 0.215763
[8350]	valid_set's binary_logloss: 0.215743
[8400]	valid_set's binary_logloss: 0.215732
[8450]	valid_set's binary_logloss: 0.215717
[8500]	valid_set's binary_logloss: 0.215703
[8550]	valid_set's binary_logloss: 0.215715
[8600]	valid_set's binary_logloss: 0.215697
[8650]	valid_set's binary_logloss: 0.215692
[8700]	valid_set's binary_logloss: 0.215668
[8750]	valid_set's binary_logloss: 0.215635
[8800]	valid_set's binary_logloss: 0.215623
[8850]	valid_set's binary_logloss: 0.215622
[8900]	valid_set's binary_logloss: 0.215605
[8950]	valid_set's binary_logloss: 0.215565
[9000]	valid_set's binary_logloss: 0.215565
[9050]	valid_set's binary_logloss: 0.215547
[9100]	valid_set's binary_logloss: 0.215542
[9150]	valid_set's binary_logloss: 0.215544
[9200]	valid_set's binary_logloss: 0.215537
[9250]	valid_set's binary_logloss: 0.215499
[9300]	valid_set's binary_logloss: 0.215512
[9350]	valid_set's binary_logloss: 0.215491
[9400]	valid_set's binary_logloss: 0.215481
[9450]	valid_set's binary_logloss: 0.215462
[9500]	valid_set's binary_logloss: 0.215456
[9550]	valid_set's binary_logloss: 0.215457
[9600]	valid_set's binary_logloss: 0.215428
[9650]	valid_set's binary_logloss: 0.215421
[9700]	valid_set's binary_logloss: 0.215365
[9750]	valid_set's binary_logloss: 0.21537
[9800]	valid_set's binary_logloss: 0.215372
[9850]	valid_set's binary_logloss: 0.215333
[9900]	valid_set's binary_logloss: 0.215304
[9950]	valid_set's binary_logloss: 0.215315
[10000]	valid_set's binary_logloss: 0.215307

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.311124
[100]	valid_set's binary_logloss: 0.283444
[150]	valid_set's binary_logloss: 0.26984
[200]	valid_set's binary_logloss: 0.262732
[250]	valid_set's binary_logloss: 0.257776
[300]	valid_set's binary_logloss: 0.253795
[350]	valid_set's binary_logloss: 0.251019
[400]	valid_set's binary_logloss: 0.248372
[450]	valid_set's binary_logloss: 0.246111
[500]	valid_set's binary_logloss: 0.244173
[550]	valid_set's binary_logloss: 0.242449
[600]	valid_set's binary_logloss: 0.240893
[650]	valid_set's binary_logloss: 0.239616
[700]	valid_set's binary_logloss: 0.238392
[750]	valid_set's binary_logloss: 0.237383
[800]	valid_set's binary_logloss: 0.236283
[850]	valid_set's binary_logloss: 0.235427
[900]	valid_set's binary_logloss: 0.234573
[950]	valid_set's binary_logloss: 0.233791
[1000]	valid_set's binary_logloss: 0.233153
[1050]	valid_set's binary_logloss: 0.232514
[1100]	valid_set's binary_logloss: 0.231927
[1150]	valid_set's binary_logloss: 0.23127
[1200]	valid_set's binary_logloss: 0.230723
[1250]	valid_set's binary_logloss: 0.230171
[1300]	valid_set's binary_logloss: 0.229682
[1350]	valid_set's binary_logloss: 0.229181
[1400]	valid_set's binary_logloss: 0.228648
[1450]	valid_set's binary_logloss: 0.228204
[1500]	valid_set's binary_logloss: 0.227767
[1550]	valid_set's binary_logloss: 0.227378
[1600]	valid_set's binary_logloss: 0.227031
[1650]	valid_set's binary_logloss: 0.226702
[1700]	valid_set's binary_logloss: 0.226353
[1750]	valid_set's binary_logloss: 0.226073
[1800]	valid_set's binary_logloss: 0.225715
[1850]	valid_set's binary_logloss: 0.225402
[1900]	valid_set's binary_logloss: 0.22517
[1950]	valid_set's binary_logloss: 0.224876
[2000]	valid_set's binary_logloss: 0.22461
[2050]	valid_set's binary_logloss: 0.224373
[2100]	valid_set's binary_logloss: 0.224083
[2150]	valid_set's binary_logloss: 0.223884
[2200]	valid_set's binary_logloss: 0.223658
[2250]	valid_set's binary_logloss: 0.22343
[2300]	valid_set's binary_logloss: 0.223252
[2350]	valid_set's binary_logloss: 0.223046
[2400]	valid_set's binary_logloss: 0.222819
[2450]	valid_set's binary_logloss: 0.222605
[2500]	valid_set's binary_logloss: 0.222368
[2550]	valid_set's binary_logloss: 0.222139
[2600]	valid_set's binary_logloss: 0.221955
[2650]	valid_set's binary_logloss: 0.221796
[2700]	valid_set's binary_logloss: 0.221642
[2750]	valid_set's binary_logloss: 0.221509
[2800]	valid_set's binary_logloss: 0.221304
[2850]	valid_set's binary_logloss: 0.221141
[2900]	valid_set's binary_logloss: 0.221036
[2950]	valid_set's binary_logloss: 0.220914
[3000]	valid_set's binary_logloss: 0.220785
[3050]	valid_set's binary_logloss: 0.22061
[3100]	valid_set's binary_logloss: 0.220443
[3150]	valid_set's binary_logloss: 0.220293
[3200]	valid_set's binary_logloss: 0.220154
[3250]	valid_set's binary_logloss: 0.219992
[3300]	valid_set's binary_logloss: 0.219843
[3350]	valid_set's binary_logloss: 0.219691
[3400]	valid_set's binary_logloss: 0.21956
[3450]	valid_set's binary_logloss: 0.21944
[3500]	valid_set's binary_logloss: 0.219319
[3550]	valid_set's binary_logloss: 0.219219
[3600]	valid_set's binary_logloss: 0.219089
[3650]	valid_set's binary_logloss: 0.219003
[3700]	valid_set's binary_logloss: 0.218866
[3750]	valid_set's binary_logloss: 0.218767
[3800]	valid_set's binary_logloss: 0.218692
[3850]	valid_set's binary_logloss: 0.218628
[3900]	valid_set's binary_logloss: 0.218524
[3950]	valid_set's binary_logloss: 0.21843
[4000]	valid_set's binary_logloss: 0.218323
[4050]	valid_set's binary_logloss: 0.218268
[4100]	valid_set's binary_logloss: 0.218199
[4150]	valid_set's binary_logloss: 0.218126
[4200]	valid_set's binary_logloss: 0.218016
[4250]	valid_set's binary_logloss: 0.217943
[4300]	valid_set's binary_logloss: 0.217899
[4350]	valid_set's binary_logloss: 0.217835
[4400]	valid_set's binary_logloss: 0.217735
[4450]	valid_set's binary_logloss: 0.217646
[4500]	valid_set's binary_logloss: 0.217521
[4550]	valid_set's binary_logloss: 0.217436
[4600]	valid_set's binary_logloss: 0.217379
[4650]	valid_set's binary_logloss: 0.217299
[4700]	valid_set's binary_logloss: 0.21721
[4750]	valid_set's binary_logloss: 0.217143
[4800]	valid_set's binary_logloss: 0.217102
[4850]	valid_set's binary_logloss: 0.217056
[4900]	valid_set's binary_logloss: 0.216996
[4950]	valid_set's binary_logloss: 0.21694
[5000]	valid_set's binary_logloss: 0.216877
[5050]	valid_set's binary_logloss: 0.216811
[5100]	valid_set's binary_logloss: 0.216769
[5150]	valid_set's binary_logloss: 0.216721
[5200]	valid_set's binary_logloss: 0.216661
[5250]	valid_set's binary_logloss: 0.216562
[5300]	valid_set's binary_logloss: 0.216496
[5350]	valid_set's binary_logloss: 0.216462
[5400]	valid_set's binary_logloss: 0.21643
[5450]	valid_set's binary_logloss: 0.216387
[5500]	valid_set's binary_logloss: 0.216329
[5550]	valid_set's binary_logloss: 0.216267
[5600]	valid_set's binary_logloss: 0.216224
[5650]	valid_set's binary_logloss: 0.21619
[5700]	valid_set's binary_logloss: 0.216144
[5750]	valid_set's binary_logloss: 0.216072
[5800]	valid_set's binary_logloss: 0.216041
[5850]	valid_set's binary_logloss: 0.21599
[5900]	valid_set's binary_logloss: 0.215936
[5950]	valid_set's binary_logloss: 0.215911
[6000]	valid_set's binary_logloss: 0.215869
[6050]	valid_set's binary_logloss: 0.215801
[6100]	valid_set's binary_logloss: 0.215737
[6150]	valid_set's binary_logloss: 0.215715
[6200]	valid_set's binary_logloss: 0.215663
[6250]	valid_set's binary_logloss: 0.215622
[6300]	valid_set's binary_logloss: 0.215584
[6350]	valid_set's binary_logloss: 0.215526
[6400]	valid_set's binary_logloss: 0.215466
[6450]	valid_set's binary_logloss: 0.215418
[6500]	valid_set's binary_logloss: 0.215382
[6550]	valid_set's binary_logloss: 0.215327
[6600]	valid_set's binary_logloss: 0.215283
[6650]	valid_set's binary_logloss: 0.21525
[6700]	valid_set's binary_logloss: 0.215235
[6750]	valid_set's binary_logloss: 0.215181
[6800]	valid_set's binary_logloss: 0.215126
[6850]	valid_set's binary_logloss: 0.215097
[6900]	valid_set's binary_logloss: 0.215042
[6950]	valid_set's binary_logloss: 0.215026
[7000]	valid_set's binary_logloss: 0.215009
[7050]	valid_set's binary_logloss: 0.214968
[7100]	valid_set's binary_logloss: 0.214963
[7150]	valid_set's binary_logloss: 0.214937
[7200]	valid_set's binary_logloss: 0.214919
[7250]	valid_set's binary_logloss: 0.214905
[7300]	valid_set's binary_logloss: 0.214887
[7350]	valid_set's binary_logloss: 0.214879
[7400]	valid_set's binary_logloss: 0.214846
[7450]	valid_set's binary_logloss: 0.21481
[7500]	valid_set's binary_logloss: 0.214746
[7550]	valid_set's binary_logloss: 0.214733
[7600]	valid_set's binary_logloss: 0.214684
[7650]	valid_set's binary_logloss: 0.214666
[7700]	valid_set's binary_logloss: 0.214623
[7750]	valid_set's binary_logloss: 0.214613
[7800]	valid_set's binary_logloss: 0.214585
[7850]	valid_set's binary_logloss: 0.214558
[7900]	valid_set's binary_logloss: 0.214543
[7950]	valid_set's binary_logloss: 0.214517
[8000]	valid_set's binary_logloss: 0.214471
[8050]	valid_set's binary_logloss: 0.21444
[8100]	valid_set's binary_logloss: 0.214391
[8150]	valid_set's binary_logloss: 0.214359
[8200]	valid_set's binary_logloss: 0.214335
[8250]	valid_set's binary_logloss: 0.214335
[8300]	valid_set's binary_logloss: 0.214303
[8350]	valid_set's binary_logloss: 0.214283
[8400]	valid_set's binary_logloss: 0.214255
[8450]	valid_set's binary_logloss: 0.214229
[8500]	valid_set's binary_logloss: 0.214197
[8550]	valid_set's binary_logloss: 0.214174
[8600]	valid_set's binary_logloss: 0.214161
[8650]	valid_set's binary_logloss: 0.214152
[8700]	valid_set's binary_logloss: 0.214144
[8750]	valid_set's binary_logloss: 0.214119
[8800]	valid_set's binary_logloss: 0.214097
[8850]	valid_set's binary_logloss: 0.21406
[8900]	valid_set's binary_logloss: 0.214036
[8950]	valid_set's binary_logloss: 0.214036
[9000]	valid_set's binary_logloss: 0.214013
[9050]	valid_set's binary_logloss: 0.214009
[9100]	valid_set's binary_logloss: 0.213973
[9150]	valid_set's binary_logloss: 0.21396
[9200]	valid_set's binary_logloss: 0.21392
[9250]	valid_set's binary_logloss: 0.21391
[9300]	valid_set's binary_logloss: 0.213895
[9350]	valid_set's binary_logloss: 0.213875
[9400]	valid_set's binary_logloss: 0.213888
[9450]	valid_set's binary_logloss: 0.213875
[9500]	valid_set's binary_logloss: 0.213872
[9550]	valid_set's binary_logloss: 0.213844
[9600]	valid_set's binary_logloss: 0.213838
[9650]	valid_set's binary_logloss: 0.213832
[9700]	valid_set's binary_logloss: 0.213833
[9750]	valid_set's binary_logloss: 0.213816
[9800]	valid_set's binary_logloss: 0.213801
[9850]	valid_set's binary_logloss: 0.213777
[9900]	valid_set's binary_logloss: 0.213773
[9950]	valid_set's binary_logloss: 0.213768
[10000]	valid_set's binary_logloss: 0.213752

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.315972
[100]	valid_set's binary_logloss: 0.284814
[150]	valid_set's binary_logloss: 0.272241
[200]	valid_set's binary_logloss: 0.264049
[250]	valid_set's binary_logloss: 0.258622
[300]	valid_set's binary_logloss: 0.254308
[350]	valid_set's binary_logloss: 0.251369
[400]	valid_set's binary_logloss: 0.248986
[450]	valid_set's binary_logloss: 0.24663
[500]	valid_set's binary_logloss: 0.244885
[550]	valid_set's binary_logloss: 0.243309
[600]	valid_set's binary_logloss: 0.241602
[650]	valid_set's binary_logloss: 0.240289
[700]	valid_set's binary_logloss: 0.2391
[750]	valid_set's binary_logloss: 0.238031
[800]	valid_set's binary_logloss: 0.237127
[850]	valid_set's binary_logloss: 0.236204
[900]	valid_set's binary_logloss: 0.235317
[950]	valid_set's binary_logloss: 0.234577
[1000]	valid_set's binary_logloss: 0.233815
[1050]	valid_set's binary_logloss: 0.233164
[1100]	valid_set's binary_logloss: 0.23242
[1150]	valid_set's binary_logloss: 0.231743
[1200]	valid_set's binary_logloss: 0.231267
[1250]	valid_set's binary_logloss: 0.230795
[1300]	valid_set's binary_logloss: 0.230271
[1350]	valid_set's binary_logloss: 0.229747
[1400]	valid_set's binary_logloss: 0.229262
[1450]	valid_set's binary_logloss: 0.228803
[1500]	valid_set's binary_logloss: 0.228418
[1550]	valid_set's binary_logloss: 0.228028
[1600]	valid_set's binary_logloss: 0.227646
[1650]	valid_set's binary_logloss: 0.227303
[1700]	valid_set's binary_logloss: 0.226897
[1750]	valid_set's binary_logloss: 0.226617
[1800]	valid_set's binary_logloss: 0.226313
[1850]	valid_set's binary_logloss: 0.226022
[1900]	valid_set's binary_logloss: 0.225723
[1950]	valid_set's binary_logloss: 0.225442
[2000]	valid_set's binary_logloss: 0.225186
[2050]	valid_set's binary_logloss: 0.224978
[2100]	valid_set's binary_logloss: 0.224702
[2150]	valid_set's binary_logloss: 0.224469
[2200]	valid_set's binary_logloss: 0.22419
[2250]	valid_set's binary_logloss: 0.223939
[2300]	valid_set's binary_logloss: 0.223746
[2350]	valid_set's binary_logloss: 0.223554
[2400]	valid_set's binary_logloss: 0.223307
[2450]	valid_set's binary_logloss: 0.223125
[2500]	valid_set's binary_logloss: 0.222929
[2550]	valid_set's binary_logloss: 0.22277
[2600]	valid_set's binary_logloss: 0.222571
[2650]	valid_set's binary_logloss: 0.222381
[2700]	valid_set's binary_logloss: 0.22225
[2750]	valid_set's binary_logloss: 0.222093
[2800]	valid_set's binary_logloss: 0.2219
[2850]	valid_set's binary_logloss: 0.221771
[2900]	valid_set's binary_logloss: 0.221648
[2950]	valid_set's binary_logloss: 0.221515
[3000]	valid_set's binary_logloss: 0.221346
[3050]	valid_set's binary_logloss: 0.221204
[3100]	valid_set's binary_logloss: 0.221071
[3150]	valid_set's binary_logloss: 0.220944
[3200]	valid_set's binary_logloss: 0.220809
[3250]	valid_set's binary_logloss: 0.220633
[3300]	valid_set's binary_logloss: 0.220532
[3350]	valid_set's binary_logloss: 0.220421
[3400]	valid_set's binary_logloss: 0.220321
[3450]	valid_set's binary_logloss: 0.220189
[3500]	valid_set's binary_logloss: 0.220077
[3550]	valid_set's binary_logloss: 0.219951
[3600]	valid_set's binary_logloss: 0.219843
[3650]	valid_set's binary_logloss: 0.219733
[3700]	valid_set's binary_logloss: 0.21963
[3750]	valid_set's binary_logloss: 0.21957
[3800]	valid_set's binary_logloss: 0.21952
[3850]	valid_set's binary_logloss: 0.219411
[3900]	valid_set's binary_logloss: 0.219321
[3950]	valid_set's binary_logloss: 0.219242
[4000]	valid_set's binary_logloss: 0.219179
[4050]	valid_set's binary_logloss: 0.219099
[4100]	valid_set's binary_logloss: 0.21901
[4150]	valid_set's binary_logloss: 0.218932
[4200]	valid_set's binary_logloss: 0.218857
[4250]	valid_set's binary_logloss: 0.218798
[4300]	valid_set's binary_logloss: 0.218751
[4350]	valid_set's binary_logloss: 0.218681
[4400]	valid_set's binary_logloss: 0.218613
[4450]	valid_set's binary_logloss: 0.218532
[4500]	valid_set's binary_logloss: 0.218433
[4550]	valid_set's binary_logloss: 0.218343
[4600]	valid_set's binary_logloss: 0.218273
[4650]	valid_set's binary_logloss: 0.218197
[4700]	valid_set's binary_logloss: 0.218124
[4750]	valid_set's binary_logloss: 0.218063
[4800]	valid_set's binary_logloss: 0.218019
[4850]	valid_set's binary_logloss: 0.217943
[4900]	valid_set's binary_logloss: 0.217844
[4950]	valid_set's binary_logloss: 0.217802
[5000]	valid_set's binary_logloss: 0.217729
[5050]	valid_set's binary_logloss: 0.217677
[5100]	valid_set's binary_logloss: 0.217578
[5150]	valid_set's binary_logloss: 0.21753
[5200]	valid_set's binary_logloss: 0.217467
[5250]	valid_set's binary_logloss: 0.217372
[5300]	valid_set's binary_logloss: 0.217338
[5350]	valid_set's binary_logloss: 0.217284
[5400]	valid_set's binary_logloss: 0.217258
[5450]	valid_set's binary_logloss: 0.217258
[5500]	valid_set's binary_logloss: 0.217208
[5550]	valid_set's binary_logloss: 0.217169
[5600]	valid_set's binary_logloss: 0.217145
[5650]	valid_set's binary_logloss: 0.21711
[5700]	valid_set's binary_logloss: 0.21705
[5750]	valid_set's binary_logloss: 0.217008
[5800]	valid_set's binary_logloss: 0.216964
[5850]	valid_set's binary_logloss: 0.216913
[5900]	valid_set's binary_logloss: 0.216872
[5950]	valid_set's binary_logloss: 0.216804
[6000]	valid_set's binary_logloss: 0.216779
[6050]	valid_set's binary_logloss: 0.216729
[6100]	valid_set's binary_logloss: 0.216698
[6150]	valid_set's binary_logloss: 0.216676
[6200]	valid_set's binary_logloss: 0.216649
[6250]	valid_set's binary_logloss: 0.216628
[6300]	valid_set's binary_logloss: 0.216561
[6350]	valid_set's binary_logloss: 0.216553
[6400]	valid_set's binary_logloss: 0.216499
[6450]	valid_set's binary_logloss: 0.216489
[6500]	valid_set's binary_logloss: 0.216452
[6550]	valid_set's binary_logloss: 0.216406
[6600]	valid_set's binary_logloss: 0.216383
[6650]	valid_set's binary_logloss: 0.216367
[6700]	valid_set's binary_logloss: 0.216332
[6750]	valid_set's binary_logloss: 0.216298
[6800]	valid_set's binary_logloss: 0.216253
[6850]	valid_set's binary_logloss: 0.21625
[6900]	valid_set's binary_logloss: 0.216234
[6950]	valid_set's binary_logloss: 0.216198
[7000]	valid_set's binary_logloss: 0.21615
[7050]	valid_set's binary_logloss: 0.216142
[7100]	valid_set's binary_logloss: 0.216121
[7150]	valid_set's binary_logloss: 0.216106
[7200]	valid_set's binary_logloss: 0.216068
[7250]	valid_set's binary_logloss: 0.21605
[7300]	valid_set's binary_logloss: 0.21604
[7350]	valid_set's binary_logloss: 0.216024
[7400]	valid_set's binary_logloss: 0.216017
[7450]	valid_set's binary_logloss: 0.216002
[7500]	valid_set's binary_logloss: 0.215971
[7550]	valid_set's binary_logloss: 0.215942
[7600]	valid_set's binary_logloss: 0.215929
[7650]	valid_set's binary_logloss: 0.215923
[7700]	valid_set's binary_logloss: 0.215897
[7750]	valid_set's binary_logloss: 0.215884
[7800]	valid_set's binary_logloss: 0.215844
[7850]	valid_set's binary_logloss: 0.215823
[7900]	valid_set's binary_logloss: 0.215802
[7950]	valid_set's binary_logloss: 0.215781
[8000]	valid_set's binary_logloss: 0.215773
[8050]	valid_set's binary_logloss: 0.215757
[8100]	valid_set's binary_logloss: 0.215753
[8150]	valid_set's binary_logloss: 0.215721
[8200]	valid_set's binary_logloss: 0.215696
[8250]	valid_set's binary_logloss: 0.215678
[8300]	valid_set's binary_logloss: 0.215679
[8350]	valid_set's binary_logloss: 0.21567
[8400]	valid_set's binary_logloss: 0.215645
[8450]	valid_set's binary_logloss: 0.215643
[8500]	valid_set's binary_logloss: 0.215628
[8550]	valid_set's binary_logloss: 0.215608
[8600]	valid_set's binary_logloss: 0.215597
[8650]	valid_set's binary_logloss: 0.215581
[8700]	valid_set's binary_logloss: 0.21555
[8750]	valid_set's binary_logloss: 0.215524
[8800]	valid_set's binary_logloss: 0.215505
[8850]	valid_set's binary_logloss: 0.215473
[8900]	valid_set's binary_logloss: 0.21545
[8950]	valid_set's binary_logloss: 0.215468
[9000]	valid_set's binary_logloss: 0.215426
[9050]	valid_set's binary_logloss: 0.215411
[9100]	valid_set's binary_logloss: 0.215396
[9150]	valid_set's binary_logloss: 0.215398
[9200]	valid_set's binary_logloss: 0.215391
[9250]	valid_set's binary_logloss: 0.215361
[9300]	valid_set's binary_logloss: 0.215314
[9350]	valid_set's binary_logloss: 0.215292
[9400]	valid_set's binary_logloss: 0.215279
[9450]	valid_set's binary_logloss: 0.215271
[9500]	valid_set's binary_logloss: 0.215266
[9550]	valid_set's binary_logloss: 0.215256
[9600]	valid_set's binary_logloss: 0.215259
[9650]	valid_set's binary_logloss: 0.215265
[9700]	valid_set's binary_logloss: 0.215254
[9750]	valid_set's binary_logloss: 0.215253
[9800]	valid_set's binary_logloss: 0.215263
[9850]	valid_set's binary_logloss: 0.215242
[9900]	valid_set's binary_logloss: 0.215241
[9950]	valid_set's binary_logloss: 0.215218
[10000]	valid_set's binary_logloss: 0.215227

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.309298
[100]	valid_set's binary_logloss: 0.278783
[150]	valid_set's binary_logloss: 0.26718
[200]	valid_set's binary_logloss: 0.260602
[250]	valid_set's binary_logloss: 0.255961
[300]	valid_set's binary_logloss: 0.252395
[350]	valid_set's binary_logloss: 0.249711
[400]	valid_set's binary_logloss: 0.247368
[450]	valid_set's binary_logloss: 0.245456
[500]	valid_set's binary_logloss: 0.243727
[550]	valid_set's binary_logloss: 0.24221
[600]	valid_set's binary_logloss: 0.240869
[650]	valid_set's binary_logloss: 0.239577
[700]	valid_set's binary_logloss: 0.238408
[750]	valid_set's binary_logloss: 0.23744
[800]	valid_set's binary_logloss: 0.236557
[850]	valid_set's binary_logloss: 0.235836
[900]	valid_set's binary_logloss: 0.235054
[950]	valid_set's binary_logloss: 0.234307
[1000]	valid_set's binary_logloss: 0.233674
[1050]	valid_set's binary_logloss: 0.233072
[1100]	valid_set's binary_logloss: 0.232507
[1150]	valid_set's binary_logloss: 0.231822
[1200]	valid_set's binary_logloss: 0.231305
[1250]	valid_set's binary_logloss: 0.230875
[1300]	valid_set's binary_logloss: 0.230479
[1350]	valid_set's binary_logloss: 0.230064
[1400]	valid_set's binary_logloss: 0.229626
[1450]	valid_set's binary_logloss: 0.229238
[1500]	valid_set's binary_logloss: 0.228807
[1550]	valid_set's binary_logloss: 0.228454
[1600]	valid_set's binary_logloss: 0.228187
[1650]	valid_set's binary_logloss: 0.227919
[1700]	valid_set's binary_logloss: 0.227619
[1750]	valid_set's binary_logloss: 0.227315
[1800]	valid_set's binary_logloss: 0.227006
[1850]	valid_set's binary_logloss: 0.226722
[1900]	valid_set's binary_logloss: 0.226457
[1950]	valid_set's binary_logloss: 0.226229
[2000]	valid_set's binary_logloss: 0.225981
[2050]	valid_set's binary_logloss: 0.225744
[2100]	valid_set's binary_logloss: 0.225469
[2150]	valid_set's binary_logloss: 0.225249
[2200]	valid_set's binary_logloss: 0.225044
[2250]	valid_set's binary_logloss: 0.224841
[2300]	valid_set's binary_logloss: 0.224633
[2350]	valid_set's binary_logloss: 0.22442
[2400]	valid_set's binary_logloss: 0.22423
[2450]	valid_set's binary_logloss: 0.224106
[2500]	valid_set's binary_logloss: 0.223926
[2550]	valid_set's binary_logloss: 0.223784
[2600]	valid_set's binary_logloss: 0.223626
[2650]	valid_set's binary_logloss: 0.223465
[2700]	valid_set's binary_logloss: 0.223324
[2750]	valid_set's binary_logloss: 0.223215
[2800]	valid_set's binary_logloss: 0.223059
[2850]	valid_set's binary_logloss: 0.222921
[2900]	valid_set's binary_logloss: 0.222797
[2950]	valid_set's binary_logloss: 0.222653
[3000]	valid_set's binary_logloss: 0.222546
[3050]	valid_set's binary_logloss: 0.222423
[3100]	valid_set's binary_logloss: 0.222284
[3150]	valid_set's binary_logloss: 0.222154
[3200]	valid_set's binary_logloss: 0.222078
[3250]	valid_set's binary_logloss: 0.222
[3300]	valid_set's binary_logloss: 0.221898
[3350]	valid_set's binary_logloss: 0.221822
[3400]	valid_set's binary_logloss: 0.221723
[3450]	valid_set's binary_logloss: 0.221627
[3500]	valid_set's binary_logloss: 0.22157
[3550]	valid_set's binary_logloss: 0.221472
[3600]	valid_set's binary_logloss: 0.221375
[3650]	valid_set's binary_logloss: 0.221296
[3700]	valid_set's binary_logloss: 0.221207
[3750]	valid_set's binary_logloss: 0.221109
[3800]	valid_set's binary_logloss: 0.221013
[3850]	valid_set's binary_logloss: 0.220942
[3900]	valid_set's binary_logloss: 0.220842
[3950]	valid_set's binary_logloss: 0.220751
[4000]	valid_set's binary_logloss: 0.220674
[4050]	valid_set's binary_logloss: 0.220614
[4100]	valid_set's binary_logloss: 0.220548
[4150]	valid_set's binary_logloss: 0.220476
[4200]	valid_set's binary_logloss: 0.220392
[4250]	valid_set's binary_logloss: 0.220337
[4300]	valid_set's binary_logloss: 0.220262
[4350]	valid_set's binary_logloss: 0.220207
[4400]	valid_set's binary_logloss: 0.220112
[4450]	valid_set's binary_logloss: 0.220043
[4500]	valid_set's binary_logloss: 0.219976
[4550]	valid_set's binary_logloss: 0.219909
[4600]	valid_set's binary_logloss: 0.219871
[4650]	valid_set's binary_logloss: 0.219794
[4700]	valid_set's binary_logloss: 0.219699
[4750]	valid_set's binary_logloss: 0.219665
[4800]	valid_set's binary_logloss: 0.219599
[4850]	valid_set's binary_logloss: 0.219535
[4900]	valid_set's binary_logloss: 0.219478
[4950]	valid_set's binary_logloss: 0.219414
[5000]	valid_set's binary_logloss: 0.219376
[5050]	valid_set's binary_logloss: 0.21931
[5100]	valid_set's binary_logloss: 0.21924
[5150]	valid_set's binary_logloss: 0.219179
[5200]	valid_set's binary_logloss: 0.219129
[5250]	valid_set's binary_logloss: 0.219051
[5300]	valid_set's binary_logloss: 0.219027
[5350]	valid_set's binary_logloss: 0.218977
[5400]	valid_set's binary_logloss: 0.218928
[5450]	valid_set's binary_logloss: 0.218862
[5500]	valid_set's binary_logloss: 0.218823
[5550]	valid_set's binary_logloss: 0.218784
[5600]	valid_set's binary_logloss: 0.218743
[5650]	valid_set's binary_logloss: 0.218725
[5700]	valid_set's binary_logloss: 0.218689
[5750]	valid_set's binary_logloss: 0.218652
[5800]	valid_set's binary_logloss: 0.21864
[5850]	valid_set's binary_logloss: 0.218601
[5900]	valid_set's binary_logloss: 0.218571
[5950]	valid_set's binary_logloss: 0.21853
[6000]	valid_set's binary_logloss: 0.218488
[6050]	valid_set's binary_logloss: 0.218466
[6100]	valid_set's binary_logloss: 0.218426
[6150]	valid_set's binary_logloss: 0.218352
[6200]	valid_set's binary_logloss: 0.218307
[6250]	valid_set's binary_logloss: 0.218268
[6300]	valid_set's binary_logloss: 0.218215
[6350]	valid_set's binary_logloss: 0.218143
[6400]	valid_set's binary_logloss: 0.218114
[6450]	valid_set's binary_logloss: 0.218082
[6500]	valid_set's binary_logloss: 0.218073
[6550]	valid_set's binary_logloss: 0.218018
[6600]	valid_set's binary_logloss: 0.218011
[6650]	valid_set's binary_logloss: 0.217976
[6700]	valid_set's binary_logloss: 0.217942
[6750]	valid_set's binary_logloss: 0.217929
[6800]	valid_set's binary_logloss: 0.217903
[6850]	valid_set's binary_logloss: 0.217886
[6900]	valid_set's binary_logloss: 0.217849
[6950]	valid_set's binary_logloss: 0.21783
[7000]	valid_set's binary_logloss: 0.217813
[7050]	valid_set's binary_logloss: 0.217798
[7100]	valid_set's binary_logloss: 0.21776
[7150]	valid_set's binary_logloss: 0.217741
[7200]	valid_set's binary_logloss: 0.217703
[7250]	valid_set's binary_logloss: 0.217675
[7300]	valid_set's binary_logloss: 0.21766
[7350]	valid_set's binary_logloss: 0.217636
[7400]	valid_set's binary_logloss: 0.217617
[7450]	valid_set's binary_logloss: 0.217624
[7500]	valid_set's binary_logloss: 0.21757
[7550]	valid_set's binary_logloss: 0.217568
[7600]	valid_set's binary_logloss: 0.217535
[7650]	valid_set's binary_logloss: 0.217486
[7700]	valid_set's binary_logloss: 0.217477
[7750]	valid_set's binary_logloss: 0.217453
[7800]	valid_set's binary_logloss: 0.217442
[7850]	valid_set's binary_logloss: 0.217419
[7900]	valid_set's binary_logloss: 0.217395
[7950]	valid_set's binary_logloss: 0.21738
[8000]	valid_set's binary_logloss: 0.217329
[8050]	valid_set's binary_logloss: 0.217334
[8100]	valid_set's binary_logloss: 0.217297
[8150]	valid_set's binary_logloss: 0.217258
[8200]	valid_set's binary_logloss: 0.217248
[8250]	valid_set's binary_logloss: 0.217216
[8300]	valid_set's binary_logloss: 0.217186
[8350]	valid_set's binary_logloss: 0.217159
[8400]	valid_set's binary_logloss: 0.21711
[8450]	valid_set's binary_logloss: 0.217092
[8500]	valid_set's binary_logloss: 0.217064
[8550]	valid_set's binary_logloss: 0.217063
[8600]	valid_set's binary_logloss: 0.217043
[8650]	valid_set's binary_logloss: 0.217014
[8700]	valid_set's binary_logloss: 0.216995
[8750]	valid_set's binary_logloss: 0.21699
[8800]	valid_set's binary_logloss: 0.216985
[8850]	valid_set's binary_logloss: 0.216981
[8900]	valid_set's binary_logloss: 0.21696
[8950]	valid_set's binary_logloss: 0.216963
[9000]	valid_set's binary_logloss: 0.21695
[9050]	valid_set's binary_logloss: 0.216937
[9100]	valid_set's binary_logloss: 0.216928
[9150]	valid_set's binary_logloss: 0.216941
[9200]	valid_set's binary_logloss: 0.216937
[9250]	valid_set's binary_logloss: 0.216918
[9300]	valid_set's binary_logloss: 0.2169
[9350]	valid_set's binary_logloss: 0.216888
[9400]	valid_set's binary_logloss: 0.216889
[9450]	valid_set's binary_logloss: 0.216899
[9500]	valid_set's binary_logloss: 0.216895
[9550]	valid_set's binary_logloss: 0.21688
[9600]	valid_set's binary_logloss: 0.216862
[9650]	valid_set's binary_logloss: 0.216835
[9700]	valid_set's binary_logloss: 0.216816
[9750]	valid_set's binary_logloss: 0.216812
[9800]	valid_set's binary_logloss: 0.216793
[9850]	valid_set's binary_logloss: 0.216763
[9900]	valid_set's binary_logloss: 0.216759
[9950]	valid_set's binary_logloss: 0.21677
[10000]	valid_set's binary_logloss: 0.216762

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.307915
[100]	valid_set's binary_logloss: 0.279856
[150]	valid_set's binary_logloss: 0.268424
[200]	valid_set's binary_logloss: 0.261321
[250]	valid_set's binary_logloss: 0.256541
[300]	valid_set's binary_logloss: 0.252347
[350]	valid_set's binary_logloss: 0.249121
[400]	valid_set's binary_logloss: 0.246798
[450]	valid_set's binary_logloss: 0.24488
[500]	valid_set's binary_logloss: 0.242967
[550]	valid_set's binary_logloss: 0.241396
[600]	valid_set's binary_logloss: 0.239943
[650]	valid_set's binary_logloss: 0.238633
[700]	valid_set's binary_logloss: 0.237567
[750]	valid_set's binary_logloss: 0.236559
[800]	valid_set's binary_logloss: 0.235484
[850]	valid_set's binary_logloss: 0.234642
[900]	valid_set's binary_logloss: 0.233664
[950]	valid_set's binary_logloss: 0.232803
[1000]	valid_set's binary_logloss: 0.232107
[1050]	valid_set's binary_logloss: 0.231423
[1100]	valid_set's binary_logloss: 0.230754
[1150]	valid_set's binary_logloss: 0.230247
[1200]	valid_set's binary_logloss: 0.229662
[1250]	valid_set's binary_logloss: 0.229128
[1300]	valid_set's binary_logloss: 0.228627
[1350]	valid_set's binary_logloss: 0.22818
[1400]	valid_set's binary_logloss: 0.227774
[1450]	valid_set's binary_logloss: 0.227336
[1500]	valid_set's binary_logloss: 0.226941
[1550]	valid_set's binary_logloss: 0.226576
[1600]	valid_set's binary_logloss: 0.226169
[1650]	valid_set's binary_logloss: 0.225838
[1700]	valid_set's binary_logloss: 0.225458
[1750]	valid_set's binary_logloss: 0.225135
[1800]	valid_set's binary_logloss: 0.224837
[1850]	valid_set's binary_logloss: 0.224567
[1900]	valid_set's binary_logloss: 0.224328
[1950]	valid_set's binary_logloss: 0.224043
[2000]	valid_set's binary_logloss: 0.223775
[2050]	valid_set's binary_logloss: 0.223509
[2100]	valid_set's binary_logloss: 0.223253
[2150]	valid_set's binary_logloss: 0.223009
[2200]	valid_set's binary_logloss: 0.222802
[2250]	valid_set's binary_logloss: 0.222588
[2300]	valid_set's binary_logloss: 0.222365
[2350]	valid_set's binary_logloss: 0.222166
[2400]	valid_set's binary_logloss: 0.222007
[2450]	valid_set's binary_logloss: 0.221828
[2500]	valid_set's binary_logloss: 0.22164
[2550]	valid_set's binary_logloss: 0.221462
[2600]	valid_set's binary_logloss: 0.221307
[2650]	valid_set's binary_logloss: 0.221118
[2700]	valid_set's binary_logloss: 0.220962
[2750]	valid_set's binary_logloss: 0.220754
[2800]	valid_set's binary_logloss: 0.220614
[2850]	valid_set's binary_logloss: 0.220417
[2900]	valid_set's binary_logloss: 0.220267
[2950]	valid_set's binary_logloss: 0.220126
[3000]	valid_set's binary_logloss: 0.219976
[3050]	valid_set's binary_logloss: 0.219811
[3100]	valid_set's binary_logloss: 0.21968
[3150]	valid_set's binary_logloss: 0.219555
[3200]	valid_set's binary_logloss: 0.219438
[3250]	valid_set's binary_logloss: 0.219298
[3300]	valid_set's binary_logloss: 0.219163
[3350]	valid_set's binary_logloss: 0.219043
[3400]	valid_set's binary_logloss: 0.218899
[3450]	valid_set's binary_logloss: 0.218801
[3500]	valid_set's binary_logloss: 0.218689
[3550]	valid_set's binary_logloss: 0.21858
[3600]	valid_set's binary_logloss: 0.218495
[3650]	valid_set's binary_logloss: 0.218377
[3700]	valid_set's binary_logloss: 0.218244
[3750]	valid_set's binary_logloss: 0.218123
[3800]	valid_set's binary_logloss: 0.217991
[3850]	valid_set's binary_logloss: 0.217882
[3900]	valid_set's binary_logloss: 0.217803
[3950]	valid_set's binary_logloss: 0.217704
[4000]	valid_set's binary_logloss: 0.217603
[4050]	valid_set's binary_logloss: 0.217525
[4100]	valid_set's binary_logloss: 0.217427
[4150]	valid_set's binary_logloss: 0.217324
[4200]	valid_set's binary_logloss: 0.217237
[4250]	valid_set's binary_logloss: 0.21716
[4300]	valid_set's binary_logloss: 0.217085
[4350]	valid_set's binary_logloss: 0.216996
[4400]	valid_set's binary_logloss: 0.21692
[4450]	valid_set's binary_logloss: 0.216822
[4500]	valid_set's binary_logloss: 0.216767
[4550]	valid_set's binary_logloss: 0.216677
[4600]	valid_set's binary_logloss: 0.216604
[4650]	valid_set's binary_logloss: 0.216515
[4700]	valid_set's binary_logloss: 0.216411
[4750]	valid_set's binary_logloss: 0.216337
[4800]	valid_set's binary_logloss: 0.21629
[4850]	valid_set's binary_logloss: 0.216235
[4900]	valid_set's binary_logloss: 0.216172
[4950]	valid_set's binary_logloss: 0.216097
[5000]	valid_set's binary_logloss: 0.216026
[5050]	valid_set's binary_logloss: 0.215988
[5100]	valid_set's binary_logloss: 0.215915
[5150]	valid_set's binary_logloss: 0.215874
[5200]	valid_set's binary_logloss: 0.215807
[5250]	valid_set's binary_logloss: 0.215776
[5300]	valid_set's binary_logloss: 0.215755
[5350]	valid_set's binary_logloss: 0.215696
[5400]	valid_set's binary_logloss: 0.21565
[5450]	valid_set's binary_logloss: 0.215584
[5500]	valid_set's binary_logloss: 0.215542
[5550]	valid_set's binary_logloss: 0.21551
[5600]	valid_set's binary_logloss: 0.215426
[5650]	valid_set's binary_logloss: 0.21538
[5700]	valid_set's binary_logloss: 0.215308
[5750]	valid_set's binary_logloss: 0.215241
[5800]	valid_set's binary_logloss: 0.215185
[5850]	valid_set's binary_logloss: 0.215127
[5900]	valid_set's binary_logloss: 0.215102
[5950]	valid_set's binary_logloss: 0.215086
[6000]	valid_set's binary_logloss: 0.215066
[6050]	valid_set's binary_logloss: 0.21504
[6100]	valid_set's binary_logloss: 0.214988
[6150]	valid_set's binary_logloss: 0.214953
[6200]	valid_set's binary_logloss: 0.214878
[6250]	valid_set's binary_logloss: 0.214849
[6300]	valid_set's binary_logloss: 0.214791
[6350]	valid_set's binary_logloss: 0.214744
[6400]	valid_set's binary_logloss: 0.214726
[6450]	valid_set's binary_logloss: 0.214687
[6500]	valid_set's binary_logloss: 0.214624
[6550]	valid_set's binary_logloss: 0.214588
[6600]	valid_set's binary_logloss: 0.214516
[6650]	valid_set's binary_logloss: 0.21449
[6700]	valid_set's binary_logloss: 0.214464
[6750]	valid_set's binary_logloss: 0.214455
[6800]	valid_set's binary_logloss: 0.214417
[6850]	valid_set's binary_logloss: 0.214376
[6900]	valid_set's binary_logloss: 0.214336
[6950]	valid_set's binary_logloss: 0.21431
[7000]	valid_set's binary_logloss: 0.214287
[7050]	valid_set's binary_logloss: 0.214243
[7100]	valid_set's binary_logloss: 0.21423
[7150]	valid_set's binary_logloss: 0.214198
[7200]	valid_set's binary_logloss: 0.21417
[7250]	valid_set's binary_logloss: 0.214133
[7300]	valid_set's binary_logloss: 0.214098
[7350]	valid_set's binary_logloss: 0.214069
[7400]	valid_set's binary_logloss: 0.214059
[7450]	valid_set's binary_logloss: 0.214031
[7500]	valid_set's binary_logloss: 0.213998
[7550]	valid_set's binary_logloss: 0.213972
[7600]	valid_set's binary_logloss: 0.213951
[7650]	valid_set's binary_logloss: 0.213944
[7700]	valid_set's binary_logloss: 0.213916
[7750]	valid_set's binary_logloss: 0.213897
[7800]	valid_set's binary_logloss: 0.213893
[7850]	valid_set's binary_logloss: 0.213857
[7900]	valid_set's binary_logloss: 0.213845
[7950]	valid_set's binary_logloss: 0.213827
[8000]	valid_set's binary_logloss: 0.213801
[8050]	valid_set's binary_logloss: 0.21377
[8100]	valid_set's binary_logloss: 0.213765
[8150]	valid_set's binary_logloss: 0.213744
[8200]	valid_set's binary_logloss: 0.213709
[8250]	valid_set's binary_logloss: 0.213674
[8300]	valid_set's binary_logloss: 0.213651
[8350]	valid_set's binary_logloss: 0.213616
[8400]	valid_set's binary_logloss: 0.213592
[8450]	valid_set's binary_logloss: 0.213547
[8500]	valid_set's binary_logloss: 0.213515
[8550]	valid_set's binary_logloss: 0.213516
[8600]	valid_set's binary_logloss: 0.213499
[8650]	valid_set's binary_logloss: 0.213485
[8700]	valid_set's binary_logloss: 0.21345
[8750]	valid_set's binary_logloss: 0.213439
[8800]	valid_set's binary_logloss: 0.213409
[8850]	valid_set's binary_logloss: 0.213393
[8900]	valid_set's binary_logloss: 0.213377
[8950]	valid_set's binary_logloss: 0.213358
[9000]	valid_set's binary_logloss: 0.213354
[9050]	valid_set's binary_logloss: 0.21333
[9100]	valid_set's binary_logloss: 0.213311
[9150]	valid_set's binary_logloss: 0.213318
[9200]	valid_set's binary_logloss: 0.213302
[9250]	valid_set's binary_logloss: 0.213254
[9300]	valid_set's binary_logloss: 0.213239
[9350]	valid_set's binary_logloss: 0.213236
[9400]	valid_set's binary_logloss: 0.213225
[9450]	valid_set's binary_logloss: 0.21323
[9500]	valid_set's binary_logloss: 0.213216
[9550]	valid_set's binary_logloss: 0.213223
[9600]	valid_set's binary_logloss: 0.213199
[9650]	valid_set's binary_logloss: 0.213193
[9700]	valid_set's binary_logloss: 0.213176
[9750]	valid_set's binary_logloss: 0.213156
[9800]	valid_set's binary_logloss: 0.213154
[9850]	valid_set's binary_logloss: 0.21314
[9900]	valid_set's binary_logloss: 0.213136
[9950]	valid_set's binary_logloss: 0.213127
[10000]	valid_set's binary_logloss: 0.213101

Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl
	0.9556	 = Validation score   (roc_auc)
	229.19s	 = Training   runtime
	24.14s	 = Validation runtime
	2798.7	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1350.60s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.7 GB
Ensemble size: 19
Ensemble weights:
[0.68421053 0.31578947]
	0.55s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBM_BAG_L1': 0.684, 'LightGBMLarge_BAG_L1': 0.316}
	0.9578	 = Validation score   (roc_auc)
	2.55s	 = Training   runtime
	0.05s	 = Validation runtime
	1863.4	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
AutoGluon training complete, total runtime = 452.06s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1863.4 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models3\GBM\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models3\GBM")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       3.75 GB / 15.06 GB (24.9%)
Disk Space Avail:   722.50 GB / 930.47 GB (77.6%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models3\XGB"
Train Data Rows:    540445
Train Data Columns: 13
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

GBM completed.
Validation ROC-AUC: 0.957781

================================================================================
TRAINING: XGB
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models3\XGB
================================================================================

	Available Memory:                    3892.19 MB
	Train Data (Original)  Memory Usage: 109.08 MB (2.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 2 | ['Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.7s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 42.78 MB (1.1% of available memory)
Data preprocessing and feature engineering runtime = 0.75s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\learner.pkl
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\utils\data\y.pkl
Model configs that will be trained (in order):
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1799.25s of the 1799.25s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47387
[50]	validation_0-logloss:0.26484
[100]	validation_0-logloss:0.24941
[150]	validation_0-logloss:0.24283
[200]	validation_0-logloss:0.23754
[250]	validation_0-logloss:0.23408
[300]	validation_0-logloss:0.23097
[350]	validation_0-logloss:0.22840
[400]	validation_0-logloss:0.22665
[450]	validation_0-logloss:0.22497
[500]	validation_0-logloss:0.22373
[550]	validation_0-logloss:0.22269
[600]	validation_0-logloss:0.22177
[650]	validation_0-logloss:0.22114
[700]	validation_0-logloss:0.22044
[750]	validation_0-logloss:0.21995
[800]	validation_0-logloss:0.21939
[850]	validation_0-logloss:0.21889
[900]	validation_0-logloss:0.21850
[950]	validation_0-logloss:0.21801
[1000]	validation_0-logloss:0.21779
[1050]	validation_0-logloss:0.21759
[1100]	validation_0-logloss:0.21732
[1150]	validation_0-logloss:0.21702
[1200]	validation_0-logloss:0.21675
[1250]	validation_0-logloss:0.21653
[1300]	validation_0-logloss:0.21636
[1350]	validation_0-logloss:0.21616
[1400]	validation_0-logloss:0.21601
[1450]	validation_0-logloss:0.21581
[1500]	validation_0-logloss:0.21568
[1550]	validation_0-logloss:0.21563
[1600]	validation_0-logloss:0.21545
[1650]	validation_0-logloss:0.21530
[1700]	validation_0-logloss:0.21520
[1750]	validation_0-logloss:0.21518
[1800]	validation_0-logloss:0.21519
[1850]	validation_0-logloss:0.21515
[1900]	validation_0-logloss:0.21516
[1950]	validation_0-logloss:0.21519
[2000]	validation_0-logloss:0.21514
[2050]	validation_0-logloss:0.21505
[2100]	validation_0-logloss:0.21506
[2150]	validation_0-logloss:0.21508
[2200]	validation_0-logloss:0.21509
[2250]	validation_0-logloss:0.21508
[2300]	validation_0-logloss:0.21511
[2350]	validation_0-logloss:0.21517
[2400]	validation_0-logloss:0.21508
[2450]	validation_0-logloss:0.21508
[2500]	validation_0-logloss:0.21511
[2550]	validation_0-logloss:0.21514
[2600]	validation_0-logloss:0.21512
[2650]	validation_0-logloss:0.21517
[2700]	validation_0-logloss:0.21514
[2712]	validation_0-logloss:0.21513

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47402
[50]	validation_0-logloss:0.26626
[100]	validation_0-logloss:0.25124
[150]	validation_0-logloss:0.24429
[200]	validation_0-logloss:0.23921
[250]	validation_0-logloss:0.23563
[300]	validation_0-logloss:0.23253
[350]	validation_0-logloss:0.23012
[400]	validation_0-logloss:0.22829
[450]	validation_0-logloss:0.22640
[500]	validation_0-logloss:0.22491
[550]	validation_0-logloss:0.22329
[600]	validation_0-logloss:0.22215
[650]	validation_0-logloss:0.22110
[700]	validation_0-logloss:0.22034
[750]	validation_0-logloss:0.21964
[800]	validation_0-logloss:0.21912
[850]	validation_0-logloss:0.21864
[900]	validation_0-logloss:0.21825
[950]	validation_0-logloss:0.21781
[1000]	validation_0-logloss:0.21732
[1050]	validation_0-logloss:0.21696
[1100]	validation_0-logloss:0.21665
[1150]	validation_0-logloss:0.21631
[1200]	validation_0-logloss:0.21606
[1250]	validation_0-logloss:0.21578
[1300]	validation_0-logloss:0.21559
[1350]	validation_0-logloss:0.21536
[1400]	validation_0-logloss:0.21510
[1450]	validation_0-logloss:0.21480
[1500]	validation_0-logloss:0.21454
[1550]	validation_0-logloss:0.21442
[1600]	validation_0-logloss:0.21431
[1650]	validation_0-logloss:0.21428
[1700]	validation_0-logloss:0.21410
[1750]	validation_0-logloss:0.21405
[1800]	validation_0-logloss:0.21402
[1850]	validation_0-logloss:0.21395
[1900]	validation_0-logloss:0.21384
[1950]	validation_0-logloss:0.21377
[2000]	validation_0-logloss:0.21380
[2050]	validation_0-logloss:0.21372
[2100]	validation_0-logloss:0.21365
[2150]	validation_0-logloss:0.21367
[2200]	validation_0-logloss:0.21365
[2250]	validation_0-logloss:0.21358
[2300]	validation_0-logloss:0.21361
[2350]	validation_0-logloss:0.21358
[2400]	validation_0-logloss:0.21361
[2450]	validation_0-logloss:0.21360
[2500]	validation_0-logloss:0.21362
[2550]	validation_0-logloss:0.21369
[2600]	validation_0-logloss:0.21376
[2650]	validation_0-logloss:0.21378
[2700]	validation_0-logloss:0.21380
[2750]	validation_0-logloss:0.21380
[2800]	validation_0-logloss:0.21376
[2850]	validation_0-logloss:0.21376
[2900]	validation_0-logloss:0.21376
[2950]	validation_0-logloss:0.21380
[3000]	validation_0-logloss:0.21388
[3050]	validation_0-logloss:0.21394
[3067]	validation_0-logloss:0.21395

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47404
[50]	validation_0-logloss:0.26768
[100]	validation_0-logloss:0.25305
[150]	validation_0-logloss:0.24588
[200]	validation_0-logloss:0.24072
[250]	validation_0-logloss:0.23684
[300]	validation_0-logloss:0.23418
[350]	validation_0-logloss:0.23173
[400]	validation_0-logloss:0.22994
[450]	validation_0-logloss:0.22842
[500]	validation_0-logloss:0.22702
[550]	validation_0-logloss:0.22622
[600]	validation_0-logloss:0.22546
[650]	validation_0-logloss:0.22472
[700]	validation_0-logloss:0.22406
[750]	validation_0-logloss:0.22331
[800]	validation_0-logloss:0.22275
[850]	validation_0-logloss:0.22251
[900]	validation_0-logloss:0.22201
[950]	validation_0-logloss:0.22155
[1000]	validation_0-logloss:0.22114
[1050]	validation_0-logloss:0.22080
[1100]	validation_0-logloss:0.22042
[1150]	validation_0-logloss:0.22020
[1200]	validation_0-logloss:0.22011
[1250]	validation_0-logloss:0.21995
[1300]	validation_0-logloss:0.21987
[1350]	validation_0-logloss:0.21971
[1400]	validation_0-logloss:0.21965
[1450]	validation_0-logloss:0.21954
[1500]	validation_0-logloss:0.21938
[1550]	validation_0-logloss:0.21933
[1600]	validation_0-logloss:0.21919
[1650]	validation_0-logloss:0.21913
[1700]	validation_0-logloss:0.21910
[1750]	validation_0-logloss:0.21905
[1800]	validation_0-logloss:0.21897
[1850]	validation_0-logloss:0.21895
[1900]	validation_0-logloss:0.21903
[1950]	validation_0-logloss:0.21898
[2000]	validation_0-logloss:0.21888
[2050]	validation_0-logloss:0.21890
[2100]	validation_0-logloss:0.21896
[2150]	validation_0-logloss:0.21901
[2200]	validation_0-logloss:0.21898
[2250]	validation_0-logloss:0.21897
[2300]	validation_0-logloss:0.21898
[2350]	validation_0-logloss:0.21895
[2400]	validation_0-logloss:0.21906
[2450]	validation_0-logloss:0.21904
[2500]	validation_0-logloss:0.21907
[2550]	validation_0-logloss:0.21912
[2600]	validation_0-logloss:0.21916
[2649]	validation_0-logloss:0.21923

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47380
[50]	validation_0-logloss:0.26385
[100]	validation_0-logloss:0.24996
[150]	validation_0-logloss:0.24182
[200]	validation_0-logloss:0.23690
[250]	validation_0-logloss:0.23351
[300]	validation_0-logloss:0.23011
[350]	validation_0-logloss:0.22804
[400]	validation_0-logloss:0.22630
[450]	validation_0-logloss:0.22463
[500]	validation_0-logloss:0.22342
[550]	validation_0-logloss:0.22247
[600]	validation_0-logloss:0.22156
[650]	validation_0-logloss:0.22057
[700]	validation_0-logloss:0.21997
[750]	validation_0-logloss:0.21931
[800]	validation_0-logloss:0.21879
[850]	validation_0-logloss:0.21836
[900]	validation_0-logloss:0.21791
[950]	validation_0-logloss:0.21743
[1000]	validation_0-logloss:0.21699
[1050]	validation_0-logloss:0.21669
[1100]	validation_0-logloss:0.21645
[1150]	validation_0-logloss:0.21608
[1200]	validation_0-logloss:0.21582
[1250]	validation_0-logloss:0.21550
[1300]	validation_0-logloss:0.21536
[1350]	validation_0-logloss:0.21515
[1400]	validation_0-logloss:0.21502
[1450]	validation_0-logloss:0.21503
[1500]	validation_0-logloss:0.21486
[1550]	validation_0-logloss:0.21476
[1600]	validation_0-logloss:0.21465
[1650]	validation_0-logloss:0.21447
[1700]	validation_0-logloss:0.21436
[1750]	validation_0-logloss:0.21427
[1800]	validation_0-logloss:0.21415
[1850]	validation_0-logloss:0.21407
[1900]	validation_0-logloss:0.21397
[1950]	validation_0-logloss:0.21389
[2000]	validation_0-logloss:0.21388
[2050]	validation_0-logloss:0.21383
[2100]	validation_0-logloss:0.21382
[2150]	validation_0-logloss:0.21375
[2200]	validation_0-logloss:0.21368
[2250]	validation_0-logloss:0.21374
[2300]	validation_0-logloss:0.21370
[2350]	validation_0-logloss:0.21371
[2400]	validation_0-logloss:0.21373
[2450]	validation_0-logloss:0.21375
[2500]	validation_0-logloss:0.21368
[2550]	validation_0-logloss:0.21364
[2600]	validation_0-logloss:0.21371
[2650]	validation_0-logloss:0.21369
[2700]	validation_0-logloss:0.21369
[2750]	validation_0-logloss:0.21380
[2800]	validation_0-logloss:0.21385
[2850]	validation_0-logloss:0.21390
[2900]	validation_0-logloss:0.21397
[2950]	validation_0-logloss:0.21400
[3000]	validation_0-logloss:0.21396
[3050]	validation_0-logloss:0.21399
[3100]	validation_0-logloss:0.21403
[3150]	validation_0-logloss:0.21407
[3200]	validation_0-logloss:0.21421
[3250]	validation_0-logloss:0.21428
[3288]	validation_0-logloss:0.21433

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47380
[50]	validation_0-logloss:0.26536
[100]	validation_0-logloss:0.25133
[150]	validation_0-logloss:0.24287
[200]	validation_0-logloss:0.23795
[250]	validation_0-logloss:0.23417
[300]	validation_0-logloss:0.23123
[350]	validation_0-logloss:0.22865
[400]	validation_0-logloss:0.22689
[450]	validation_0-logloss:0.22545
[500]	validation_0-logloss:0.22414
[550]	validation_0-logloss:0.22296
[600]	validation_0-logloss:0.22189
[650]	validation_0-logloss:0.22083
[700]	validation_0-logloss:0.21975
[750]	validation_0-logloss:0.21898
[800]	validation_0-logloss:0.21833
[850]	validation_0-logloss:0.21778
[900]	validation_0-logloss:0.21735
[950]	validation_0-logloss:0.21692
[1000]	validation_0-logloss:0.21651
[1050]	validation_0-logloss:0.21617
[1100]	validation_0-logloss:0.21588
[1150]	validation_0-logloss:0.21566
[1200]	validation_0-logloss:0.21543
[1250]	validation_0-logloss:0.21522
[1300]	validation_0-logloss:0.21494
[1350]	validation_0-logloss:0.21470
[1400]	validation_0-logloss:0.21446
[1450]	validation_0-logloss:0.21430
[1500]	validation_0-logloss:0.21426
[1550]	validation_0-logloss:0.21405
[1600]	validation_0-logloss:0.21395
[1650]	validation_0-logloss:0.21383
[1700]	validation_0-logloss:0.21373
[1750]	validation_0-logloss:0.21367
[1800]	validation_0-logloss:0.21350
[1850]	validation_0-logloss:0.21336
[1900]	validation_0-logloss:0.21328
[1950]	validation_0-logloss:0.21328
[2000]	validation_0-logloss:0.21316
[2050]	validation_0-logloss:0.21315
[2100]	validation_0-logloss:0.21308
[2150]	validation_0-logloss:0.21293
[2200]	validation_0-logloss:0.21287
[2250]	validation_0-logloss:0.21286
[2300]	validation_0-logloss:0.21283
[2350]	validation_0-logloss:0.21288
[2400]	validation_0-logloss:0.21290
[2450]	validation_0-logloss:0.21292
[2500]	validation_0-logloss:0.21295
[2550]	validation_0-logloss:0.21291
[2600]	validation_0-logloss:0.21295
[2650]	validation_0-logloss:0.21292
[2700]	validation_0-logloss:0.21288
[2750]	validation_0-logloss:0.21290
[2800]	validation_0-logloss:0.21303
[2850]	validation_0-logloss:0.21301
[2900]	validation_0-logloss:0.21306
[2950]	validation_0-logloss:0.21305
[2976]	validation_0-logloss:0.21305

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47384
[50]	validation_0-logloss:0.26413
[100]	validation_0-logloss:0.24983
[150]	validation_0-logloss:0.24269
[200]	validation_0-logloss:0.23779
[250]	validation_0-logloss:0.23441
[300]	validation_0-logloss:0.23133
[350]	validation_0-logloss:0.22922
[400]	validation_0-logloss:0.22733
[450]	validation_0-logloss:0.22578
[500]	validation_0-logloss:0.22453
[550]	validation_0-logloss:0.22348
[600]	validation_0-logloss:0.22239
[650]	validation_0-logloss:0.22155
[700]	validation_0-logloss:0.22097
[750]	validation_0-logloss:0.22046
[800]	validation_0-logloss:0.21988
[850]	validation_0-logloss:0.21937
[900]	validation_0-logloss:0.21881
[950]	validation_0-logloss:0.21831
[1000]	validation_0-logloss:0.21805
[1050]	validation_0-logloss:0.21778
[1100]	validation_0-logloss:0.21750
[1150]	validation_0-logloss:0.21733
[1200]	validation_0-logloss:0.21708
[1250]	validation_0-logloss:0.21685
[1300]	validation_0-logloss:0.21658
[1350]	validation_0-logloss:0.21630
[1400]	validation_0-logloss:0.21611
[1450]	validation_0-logloss:0.21588
[1500]	validation_0-logloss:0.21575
[1550]	validation_0-logloss:0.21563
[1600]	validation_0-logloss:0.21556
[1650]	validation_0-logloss:0.21550
[1700]	validation_0-logloss:0.21545
[1750]	validation_0-logloss:0.21537
[1800]	validation_0-logloss:0.21531
[1850]	validation_0-logloss:0.21526
[1900]	validation_0-logloss:0.21523
[1950]	validation_0-logloss:0.21522
[2000]	validation_0-logloss:0.21505
[2050]	validation_0-logloss:0.21497
[2100]	validation_0-logloss:0.21493
[2150]	validation_0-logloss:0.21494
[2200]	validation_0-logloss:0.21498
[2250]	validation_0-logloss:0.21489
[2300]	validation_0-logloss:0.21485
[2350]	validation_0-logloss:0.21489
[2400]	validation_0-logloss:0.21483
[2450]	validation_0-logloss:0.21486
[2500]	validation_0-logloss:0.21489
[2550]	validation_0-logloss:0.21492
[2600]	validation_0-logloss:0.21495
[2650]	validation_0-logloss:0.21492
[2700]	validation_0-logloss:0.21490
[2750]	validation_0-logloss:0.21497
[2800]	validation_0-logloss:0.21500
[2850]	validation_0-logloss:0.21500
[2900]	validation_0-logloss:0.21497
[2950]	validation_0-logloss:0.21498
[3000]	validation_0-logloss:0.21502
[3050]	validation_0-logloss:0.21514
[3100]	validation_0-logloss:0.21514
[3141]	validation_0-logloss:0.21512

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47345
[50]	validation_0-logloss:0.26408
[100]	validation_0-logloss:0.24903
[150]	validation_0-logloss:0.24238
[200]	validation_0-logloss:0.23701
[250]	validation_0-logloss:0.23335
[300]	validation_0-logloss:0.22990
[350]	validation_0-logloss:0.22808
[400]	validation_0-logloss:0.22636
[450]	validation_0-logloss:0.22475
[500]	validation_0-logloss:0.22365
[550]	validation_0-logloss:0.22269
[600]	validation_0-logloss:0.22172
[650]	validation_0-logloss:0.22105
[700]	validation_0-logloss:0.22031
[750]	validation_0-logloss:0.21966
[800]	validation_0-logloss:0.21912
[850]	validation_0-logloss:0.21875
[900]	validation_0-logloss:0.21829
[950]	validation_0-logloss:0.21789
[1000]	validation_0-logloss:0.21758
[1050]	validation_0-logloss:0.21726
[1100]	validation_0-logloss:0.21695
[1150]	validation_0-logloss:0.21671
[1200]	validation_0-logloss:0.21639
[1250]	validation_0-logloss:0.21608
[1300]	validation_0-logloss:0.21583
[1350]	validation_0-logloss:0.21570
[1400]	validation_0-logloss:0.21548
[1450]	validation_0-logloss:0.21537
[1500]	validation_0-logloss:0.21522
[1550]	validation_0-logloss:0.21509
[1600]	validation_0-logloss:0.21506
[1650]	validation_0-logloss:0.21496
[1700]	validation_0-logloss:0.21487
[1750]	validation_0-logloss:0.21478
[1800]	validation_0-logloss:0.21474
[1850]	validation_0-logloss:0.21478
[1900]	validation_0-logloss:0.21476
[1950]	validation_0-logloss:0.21480
[2000]	validation_0-logloss:0.21470
[2050]	validation_0-logloss:0.21473
[2100]	validation_0-logloss:0.21468
[2150]	validation_0-logloss:0.21469
[2200]	validation_0-logloss:0.21464
[2250]	validation_0-logloss:0.21465
[2300]	validation_0-logloss:0.21461
[2350]	validation_0-logloss:0.21457
[2400]	validation_0-logloss:0.21462
[2450]	validation_0-logloss:0.21459
[2500]	validation_0-logloss:0.21454
[2550]	validation_0-logloss:0.21469
[2600]	validation_0-logloss:0.21474
[2650]	validation_0-logloss:0.21478
[2700]	validation_0-logloss:0.21480
[2750]	validation_0-logloss:0.21484
[2800]	validation_0-logloss:0.21485
[2850]	validation_0-logloss:0.21491
[2900]	validation_0-logloss:0.21497
[2950]	validation_0-logloss:0.21497
[3000]	validation_0-logloss:0.21502
[3050]	validation_0-logloss:0.21506
[3100]	validation_0-logloss:0.21510
[3150]	validation_0-logloss:0.21510
[3200]	validation_0-logloss:0.21518
[3250]	validation_0-logloss:0.21528
[3267]	validation_0-logloss:0.21531

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47343
[50]	validation_0-logloss:0.26278
[100]	validation_0-logloss:0.24794
[150]	validation_0-logloss:0.24058
[200]	validation_0-logloss:0.23588
[250]	validation_0-logloss:0.23239
[300]	validation_0-logloss:0.22952
[350]	validation_0-logloss:0.22684
[400]	validation_0-logloss:0.22501
[450]	validation_0-logloss:0.22315
[500]	validation_0-logloss:0.22178
[550]	validation_0-logloss:0.22086
[600]	validation_0-logloss:0.22007
[650]	validation_0-logloss:0.21925
[700]	validation_0-logloss:0.21830
[750]	validation_0-logloss:0.21772
[800]	validation_0-logloss:0.21718
[850]	validation_0-logloss:0.21660
[900]	validation_0-logloss:0.21619
[950]	validation_0-logloss:0.21592
[1000]	validation_0-logloss:0.21559
[1050]	validation_0-logloss:0.21525
[1100]	validation_0-logloss:0.21505
[1150]	validation_0-logloss:0.21489
[1200]	validation_0-logloss:0.21467
[1250]	validation_0-logloss:0.21436
[1300]	validation_0-logloss:0.21420
[1350]	validation_0-logloss:0.21391
[1400]	validation_0-logloss:0.21371
[1450]	validation_0-logloss:0.21360
[1500]	validation_0-logloss:0.21345
[1550]	validation_0-logloss:0.21332
[1600]	validation_0-logloss:0.21328
[1650]	validation_0-logloss:0.21314
[1700]	validation_0-logloss:0.21307
[1750]	validation_0-logloss:0.21295
[1800]	validation_0-logloss:0.21277
[1850]	validation_0-logloss:0.21269
[1900]	validation_0-logloss:0.21270
[1950]	validation_0-logloss:0.21273
[2000]	validation_0-logloss:0.21272
[2050]	validation_0-logloss:0.21270
[2100]	validation_0-logloss:0.21263
[2150]	validation_0-logloss:0.21259
[2200]	validation_0-logloss:0.21254
[2250]	validation_0-logloss:0.21253
[2300]	validation_0-logloss:0.21254
[2350]	validation_0-logloss:0.21249
[2400]	validation_0-logloss:0.21252
[2450]	validation_0-logloss:0.21250
[2500]	validation_0-logloss:0.21253
[2550]	validation_0-logloss:0.21260
[2600]	validation_0-logloss:0.21262
[2650]	validation_0-logloss:0.21264
[2700]	validation_0-logloss:0.21271
[2750]	validation_0-logloss:0.21280
[2800]	validation_0-logloss:0.21288
[2850]	validation_0-logloss:0.21287
[2900]	validation_0-logloss:0.21286
[2950]	validation_0-logloss:0.21290
[3000]	validation_0-logloss:0.21297
[3050]	validation_0-logloss:0.21306
[3100]	validation_0-logloss:0.21315
[3150]	validation_0-logloss:0.21324
[3200]	validation_0-logloss:0.21332
[3232]	validation_0-logloss:0.21338

Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl
	0.9562	 = Validation score   (roc_auc)
	255.02s	 = Training   runtime
	3.17s	 = Validation runtime
	21309.6	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1540.40s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.7 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.29s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.9562	 = Validation score   (roc_auc)
	0.06s	 = Training   runtime
	0.05s	 = Validation runtime
	21267.2	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
AutoGluon training complete, total runtime = 259.76s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 21267.2 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models3\XGB\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models3\XGB")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       3.68 GB / 15.06 GB (24.4%)
Disk Space Avail:   722.38 GB / 930.47 GB (77.6%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models3\CAT"
Train Data Rows:    540445
Train Data Columns: 13
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

XGB completed.
Validation ROC-AUC: 0.956154

================================================================================
TRAINING: CAT
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models3\CAT
================================================================================

	Available Memory:                    3813.61 MB
	Train Data (Original)  Memory Usage: 109.08 MB (2.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 2 | ['Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.7s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 42.78 MB (1.1% of available memory)
Data preprocessing and feature engineering runtime = 0.73s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\learner.pkl
User-specified model hyperparameters to be fit:
{
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\utils\data\y.pkl
Model configs that will be trained (in order):
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1799.27s of the 1799.27s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647844	test: 0.6648337	best: 0.6648337 (0)	total: 106ms	remaining: 106ms
1:	learn: 0.6391145	test: 0.6392027	best: 0.6392027 (1)	total: 111ms	remaining: 0us
bestTest = 0.6392027424
bestIteration = 1
0:	learn: 0.6647844	test: 0.6648337	best: 0.6648337 (0)	total: 4.63ms	remaining: 403ms
20:	learn: 0.4038159	test: 0.4046100	best: 0.4046100 (20)	total: 90ms	remaining: 287ms
40:	learn: 0.3355706	test: 0.3365830	best: 0.3365830 (40)	total: 176ms	remaining: 202ms
60:	learn: 0.3074586	test: 0.3082486	best: 0.3082486 (60)	total: 262ms	remaining: 116ms
80:	learn: 0.2952508	test: 0.2961109	best: 0.2961109 (80)	total: 349ms	remaining: 30.2ms
87:	learn: 0.2925996	test: 0.2934535	best: 0.2934535 (87)	total: 380ms	remaining: 0us
bestTest = 0.293453533
bestIteration = 87

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647821	test: 0.6648525	best: 0.6648525 (0)	total: 4.43ms	remaining: 4.43ms
1:	learn: 0.6391058	test: 0.6392487	best: 0.6392487 (1)	total: 8.97ms	remaining: 0us
bestTest = 0.6392486534
bestIteration = 1
0:	learn: 0.6396315	test: 0.6398387	best: 0.6398387 (0)	total: 16.2ms	remaining: 10.6s
20:	learn: 0.3394635	test: 0.3412405	best: 0.3412405 (20)	total: 317ms	remaining: 9.64s
40:	learn: 0.3082691	test: 0.3104700	best: 0.3104700 (40)	total: 619ms	remaining: 9.33s
60:	learn: 0.2956560	test: 0.2979461	best: 0.2979461 (60)	total: 945ms	remaining: 9.26s
80:	learn: 0.2885789	test: 0.2909708	best: 0.2909708 (80)	total: 1.25s	remaining: 8.94s
100:	learn: 0.2829589	test: 0.2854757	best: 0.2854757 (100)	total: 1.56s	remaining: 8.6s
120:	learn: 0.2779383	test: 0.2805241	best: 0.2805241 (120)	total: 1.86s	remaining: 8.29s
140:	learn: 0.2734196	test: 0.2761315	best: 0.2761315 (140)	total: 2.16s	remaining: 7.95s
160:	learn: 0.2704112	test: 0.2731644	best: 0.2731644 (160)	total: 2.48s	remaining: 7.66s
180:	learn: 0.2679487	test: 0.2708590	best: 0.2708590 (180)	total: 2.78s	remaining: 7.34s
200:	learn: 0.2654354	test: 0.2684054	best: 0.2684054 (200)	total: 3.09s	remaining: 7.05s
220:	learn: 0.2635827	test: 0.2666533	best: 0.2666533 (220)	total: 3.4s	remaining: 6.75s
240:	learn: 0.2617690	test: 0.2649684	best: 0.2649684 (240)	total: 3.71s	remaining: 6.43s
260:	learn: 0.2601472	test: 0.2634900	best: 0.2634900 (260)	total: 4.01s	remaining: 6.12s
280:	learn: 0.2586449	test: 0.2620526	best: 0.2620526 (280)	total: 4.32s	remaining: 5.81s
300:	learn: 0.2573300	test: 0.2608138	best: 0.2608138 (300)	total: 4.63s	remaining: 5.5s
320:	learn: 0.2560620	test: 0.2596408	best: 0.2596408 (320)	total: 4.93s	remaining: 5.19s
340:	learn: 0.2548317	test: 0.2584722	best: 0.2584722 (340)	total: 5.25s	remaining: 4.89s
360:	learn: 0.2536267	test: 0.2573587	best: 0.2573587 (360)	total: 5.55s	remaining: 4.59s
380:	learn: 0.2525350	test: 0.2563141	best: 0.2563141 (380)	total: 5.87s	remaining: 4.28s
400:	learn: 0.2515191	test: 0.2554001	best: 0.2554001 (400)	total: 6.18s	remaining: 3.98s
420:	learn: 0.2504540	test: 0.2543817	best: 0.2543817 (420)	total: 6.49s	remaining: 3.67s
440:	learn: 0.2496115	test: 0.2536056	best: 0.2536056 (440)	total: 6.81s	remaining: 3.37s
460:	learn: 0.2487564	test: 0.2528473	best: 0.2528473 (460)	total: 7.12s	remaining: 3.06s
480:	learn: 0.2480114	test: 0.2522095	best: 0.2522095 (480)	total: 7.42s	remaining: 2.75s
500:	learn: 0.2472054	test: 0.2514882	best: 0.2514882 (500)	total: 7.73s	remaining: 2.44s
520:	learn: 0.2464721	test: 0.2508300	best: 0.2508300 (520)	total: 8.03s	remaining: 2.13s
540:	learn: 0.2456967	test: 0.2501797	best: 0.2501797 (540)	total: 8.35s	remaining: 1.82s
560:	learn: 0.2451504	test: 0.2497294	best: 0.2497294 (560)	total: 8.65s	remaining: 1.51s
580:	learn: 0.2444912	test: 0.2491169	best: 0.2491169 (580)	total: 8.96s	remaining: 1.2s
600:	learn: 0.2438799	test: 0.2485917	best: 0.2485917 (600)	total: 9.27s	remaining: 895ms
620:	learn: 0.2432768	test: 0.2480584	best: 0.2480584 (620)	total: 9.58s	remaining: 586ms
640:	learn: 0.2426825	test: 0.2475406	best: 0.2475406 (640)	total: 9.88s	remaining: 278ms
658:	learn: 0.2420905	test: 0.2470162	best: 0.2470162 (658)	total: 10.2s	remaining: 0us
bestTest = 0.2470162196
bestIteration = 658

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647839	test: 0.6648585	best: 0.6648585 (0)	total: 4.63ms	remaining: 4.63ms
1:	learn: 0.6391077	test: 0.6392668	best: 0.6392668 (1)	total: 8.91ms	remaining: 0us
bestTest = 0.6392667518
bestIteration = 1
0:	learn: 0.6397174	test: 0.6398331	best: 0.6398331 (0)	total: 15.2ms	remaining: 11.7s
20:	learn: 0.3387030	test: 0.3397764	best: 0.3397764 (20)	total: 312ms	remaining: 11.2s
40:	learn: 0.3076004	test: 0.3089517	best: 0.3089517 (40)	total: 617ms	remaining: 11s
60:	learn: 0.2961371	test: 0.2977143	best: 0.2977143 (60)	total: 927ms	remaining: 10.8s
80:	learn: 0.2876981	test: 0.2896734	best: 0.2896734 (80)	total: 1.23s	remaining: 10.5s
100:	learn: 0.2825375	test: 0.2846399	best: 0.2846399 (100)	total: 1.54s	remaining: 10.3s
120:	learn: 0.2775783	test: 0.2799593	best: 0.2799593 (120)	total: 1.85s	remaining: 9.98s
140:	learn: 0.2742467	test: 0.2766863	best: 0.2766863 (140)	total: 2.15s	remaining: 9.69s
160:	learn: 0.2709057	test: 0.2735374	best: 0.2735374 (160)	total: 2.47s	remaining: 9.41s
180:	learn: 0.2680192	test: 0.2708231	best: 0.2708231 (180)	total: 2.78s	remaining: 9.11s
200:	learn: 0.2659471	test: 0.2689612	best: 0.2689612 (200)	total: 3.08s	remaining: 8.8s
220:	learn: 0.2639653	test: 0.2671480	best: 0.2671480 (220)	total: 3.39s	remaining: 8.49s
240:	learn: 0.2622702	test: 0.2655964	best: 0.2655964 (240)	total: 3.69s	remaining: 8.19s
260:	learn: 0.2604070	test: 0.2637917	best: 0.2637917 (260)	total: 4s	remaining: 7.88s
280:	learn: 0.2588670	test: 0.2624441	best: 0.2624441 (280)	total: 4.31s	remaining: 7.58s
300:	learn: 0.2573815	test: 0.2611378	best: 0.2611378 (300)	total: 4.63s	remaining: 7.29s
320:	learn: 0.2559664	test: 0.2598801	best: 0.2598801 (320)	total: 4.94s	remaining: 6.99s
340:	learn: 0.2548782	test: 0.2589445	best: 0.2589445 (340)	total: 5.24s	remaining: 6.67s
360:	learn: 0.2535865	test: 0.2577735	best: 0.2577735 (360)	total: 5.55s	remaining: 6.37s
380:	learn: 0.2523846	test: 0.2566690	best: 0.2566690 (380)	total: 5.86s	remaining: 6.06s
400:	learn: 0.2514055	test: 0.2558575	best: 0.2558575 (400)	total: 6.17s	remaining: 5.75s
420:	learn: 0.2505036	test: 0.2550857	best: 0.2550857 (420)	total: 6.47s	remaining: 5.44s
440:	learn: 0.2497695	test: 0.2544352	best: 0.2544352 (440)	total: 6.78s	remaining: 5.13s
460:	learn: 0.2488830	test: 0.2536135	best: 0.2536135 (460)	total: 7.09s	remaining: 4.83s
480:	learn: 0.2480758	test: 0.2529019	best: 0.2529019 (480)	total: 7.4s	remaining: 4.52s
500:	learn: 0.2472942	test: 0.2522957	best: 0.2522957 (500)	total: 7.7s	remaining: 4.21s
520:	learn: 0.2465619	test: 0.2516413	best: 0.2516413 (520)	total: 8.01s	remaining: 3.91s
540:	learn: 0.2457504	test: 0.2509319	best: 0.2509319 (540)	total: 8.32s	remaining: 3.6s
560:	learn: 0.2449709	test: 0.2502577	best: 0.2502577 (560)	total: 8.64s	remaining: 3.29s
580:	learn: 0.2443205	test: 0.2497141	best: 0.2497141 (580)	total: 8.94s	remaining: 2.98s
600:	learn: 0.2437308	test: 0.2492251	best: 0.2492251 (600)	total: 9.24s	remaining: 2.68s
620:	learn: 0.2430095	test: 0.2485519	best: 0.2485519 (620)	total: 9.55s	remaining: 2.37s
640:	learn: 0.2424514	test: 0.2481120	best: 0.2481120 (640)	total: 9.87s	remaining: 2.06s
660:	learn: 0.2418912	test: 0.2477059	best: 0.2477059 (660)	total: 10.2s	remaining: 1.75s
680:	learn: 0.2413646	test: 0.2472884	best: 0.2472884 (680)	total: 10.5s	remaining: 1.45s
700:	learn: 0.2407797	test: 0.2468275	best: 0.2468275 (700)	total: 10.8s	remaining: 1.14s
720:	learn: 0.2402908	test: 0.2464105	best: 0.2464105 (720)	total: 11.1s	remaining: 831ms
740:	learn: 0.2397577	test: 0.2459883	best: 0.2459883 (740)	total: 11.4s	remaining: 523ms
760:	learn: 0.2392619	test: 0.2455779	best: 0.2455779 (760)	total: 11.7s	remaining: 215ms
774:	learn: 0.2388559	test: 0.2452644	best: 0.2452644 (774)	total: 11.9s	remaining: 0us
bestTest = 0.2452644322
bestIteration = 774

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647835	test: 0.6648258	best: 0.6648258 (0)	total: 4.61ms	remaining: 4.61ms
1:	learn: 0.6391310	test: 0.6392140	best: 0.6392140 (1)	total: 8.73ms	remaining: 0us
bestTest = 0.63921396
bestIteration = 1
0:	learn: 0.6397705	test: 0.6397848	best: 0.6397848 (0)	total: 14.8ms	remaining: 13.6s
20:	learn: 0.3386431	test: 0.3390257	best: 0.3390257 (20)	total: 315ms	remaining: 13.6s
40:	learn: 0.3073270	test: 0.3077833	best: 0.3077833 (40)	total: 619ms	remaining: 13.3s
60:	learn: 0.2958504	test: 0.2963106	best: 0.2963106 (60)	total: 924ms	remaining: 13.1s
80:	learn: 0.2884694	test: 0.2888349	best: 0.2888349 (80)	total: 1.23s	remaining: 12.8s
100:	learn: 0.2829648	test: 0.2834769	best: 0.2834769 (100)	total: 1.53s	remaining: 12.5s
120:	learn: 0.2779289	test: 0.2786021	best: 0.2786021 (120)	total: 1.84s	remaining: 12.2s
140:	learn: 0.2744334	test: 0.2752484	best: 0.2752484 (140)	total: 2.14s	remaining: 11.9s
160:	learn: 0.2711941	test: 0.2721234	best: 0.2721234 (160)	total: 2.46s	remaining: 11.7s
180:	learn: 0.2684258	test: 0.2693566	best: 0.2693566 (180)	total: 2.77s	remaining: 11.4s
200:	learn: 0.2660636	test: 0.2670375	best: 0.2670375 (200)	total: 3.08s	remaining: 11.1s
220:	learn: 0.2641053	test: 0.2650329	best: 0.2650329 (220)	total: 3.38s	remaining: 10.8s
240:	learn: 0.2623921	test: 0.2633563	best: 0.2633563 (240)	total: 3.7s	remaining: 10.5s
260:	learn: 0.2608669	test: 0.2619120	best: 0.2619120 (260)	total: 4s	remaining: 10.2s
280:	learn: 0.2592509	test: 0.2603723	best: 0.2603723 (280)	total: 4.32s	remaining: 9.9s
300:	learn: 0.2577538	test: 0.2589427	best: 0.2589427 (300)	total: 4.63s	remaining: 9.6s
320:	learn: 0.2564064	test: 0.2576588	best: 0.2576588 (320)	total: 4.93s	remaining: 9.28s
340:	learn: 0.2552605	test: 0.2566168	best: 0.2566168 (340)	total: 5.24s	remaining: 8.98s
360:	learn: 0.2541556	test: 0.2555781	best: 0.2555781 (360)	total: 5.55s	remaining: 8.67s
380:	learn: 0.2530003	test: 0.2545237	best: 0.2545237 (380)	total: 5.86s	remaining: 8.37s
400:	learn: 0.2519868	test: 0.2536137	best: 0.2536137 (400)	total: 6.18s	remaining: 8.07s
420:	learn: 0.2511767	test: 0.2528518	best: 0.2528518 (420)	total: 6.48s	remaining: 7.76s
440:	learn: 0.2502814	test: 0.2520732	best: 0.2520732 (440)	total: 6.79s	remaining: 7.45s
460:	learn: 0.2493948	test: 0.2512907	best: 0.2512907 (460)	total: 7.1s	remaining: 7.14s
480:	learn: 0.2485043	test: 0.2505809	best: 0.2505809 (480)	total: 7.41s	remaining: 6.84s
500:	learn: 0.2476853	test: 0.2498582	best: 0.2498582 (500)	total: 7.72s	remaining: 6.53s
520:	learn: 0.2468789	test: 0.2491313	best: 0.2491313 (520)	total: 8.03s	remaining: 6.22s
540:	learn: 0.2462086	test: 0.2485665	best: 0.2485665 (540)	total: 8.34s	remaining: 5.92s
560:	learn: 0.2454871	test: 0.2479300	best: 0.2479300 (560)	total: 8.65s	remaining: 5.61s
580:	learn: 0.2448047	test: 0.2473669	best: 0.2473669 (580)	total: 8.96s	remaining: 5.3s
600:	learn: 0.2442602	test: 0.2469282	best: 0.2469282 (600)	total: 9.26s	remaining: 4.99s
620:	learn: 0.2435938	test: 0.2463508	best: 0.2463508 (620)	total: 9.56s	remaining: 4.68s
640:	learn: 0.2429321	test: 0.2457733	best: 0.2457733 (640)	total: 9.88s	remaining: 4.38s
660:	learn: 0.2422383	test: 0.2451782	best: 0.2451782 (660)	total: 10.2s	remaining: 4.07s
680:	learn: 0.2417108	test: 0.2447269	best: 0.2447269 (680)	total: 10.5s	remaining: 3.76s
700:	learn: 0.2412066	test: 0.2443072	best: 0.2443072 (700)	total: 10.8s	remaining: 3.46s
720:	learn: 0.2406156	test: 0.2438129	best: 0.2438129 (720)	total: 11.1s	remaining: 3.15s
740:	learn: 0.2400888	test: 0.2433907	best: 0.2433907 (740)	total: 11.4s	remaining: 2.84s
760:	learn: 0.2395510	test: 0.2429839	best: 0.2429839 (760)	total: 11.8s	remaining: 2.53s
780:	learn: 0.2390889	test: 0.2426100	best: 0.2426100 (780)	total: 12.1s	remaining: 2.23s
800:	learn: 0.2385476	test: 0.2421372	best: 0.2421372 (800)	total: 12.4s	remaining: 1.92s
820:	learn: 0.2380745	test: 0.2417667	best: 0.2417667 (820)	total: 12.7s	remaining: 1.61s
840:	learn: 0.2375409	test: 0.2413171	best: 0.2413171 (840)	total: 13s	remaining: 1.3s
860:	learn: 0.2370811	test: 0.2409678	best: 0.2409678 (860)	total: 13.3s	remaining: 991ms
880:	learn: 0.2366415	test: 0.2406096	best: 0.2406096 (880)	total: 13.6s	remaining: 681ms
900:	learn: 0.2362203	test: 0.2402676	best: 0.2402676 (900)	total: 14s	remaining: 372ms
920:	learn: 0.2358280	test: 0.2399554	best: 0.2399554 (920)	total: 14.3s	remaining: 62ms
924:	learn: 0.2357561	test: 0.2399018	best: 0.2399018 (924)	total: 14.3s	remaining: 0us
bestTest = 0.2399018384
bestIteration = 924

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647986	test: 0.6647818	best: 0.6647818 (0)	total: 4.82ms	remaining: 4.82ms
1:	learn: 0.6391403	test: 0.6391154	best: 0.6391154 (1)	total: 9.37ms	remaining: 0us
bestTest = 0.6391153728
bestIteration = 1
0:	learn: 0.6397557	test: 0.6397570	best: 0.6397570 (0)	total: 15.8ms	remaining: 18s
20:	learn: 0.3383144	test: 0.3384806	best: 0.3384806 (20)	total: 324ms	remaining: 17.3s
40:	learn: 0.3081294	test: 0.3085953	best: 0.3085953 (40)	total: 637ms	remaining: 17.1s
60:	learn: 0.2964063	test: 0.2970383	best: 0.2970383 (60)	total: 957ms	remaining: 17s
80:	learn: 0.2886746	test: 0.2895310	best: 0.2895310 (80)	total: 1.28s	remaining: 16.8s
100:	learn: 0.2825937	test: 0.2834408	best: 0.2834408 (100)	total: 1.59s	remaining: 16.4s
120:	learn: 0.2783909	test: 0.2793429	best: 0.2793429 (120)	total: 1.91s	remaining: 16.1s
140:	learn: 0.2743541	test: 0.2753196	best: 0.2753196 (140)	total: 2.23s	remaining: 15.8s
160:	learn: 0.2708830	test: 0.2718411	best: 0.2718411 (160)	total: 2.54s	remaining: 15.5s
180:	learn: 0.2683189	test: 0.2693226	best: 0.2693226 (180)	total: 2.85s	remaining: 15.2s
200:	learn: 0.2661100	test: 0.2672323	best: 0.2672323 (200)	total: 3.18s	remaining: 14.9s
220:	learn: 0.2640125	test: 0.2652088	best: 0.2652088 (220)	total: 3.5s	remaining: 14.6s
240:	learn: 0.2622874	test: 0.2635700	best: 0.2635700 (240)	total: 3.82s	remaining: 14.3s
260:	learn: 0.2606793	test: 0.2620328	best: 0.2620328 (260)	total: 4.14s	remaining: 14s
280:	learn: 0.2590683	test: 0.2604660	best: 0.2604660 (280)	total: 4.46s	remaining: 13.7s
300:	learn: 0.2577495	test: 0.2592386	best: 0.2592386 (300)	total: 4.78s	remaining: 13.4s
320:	learn: 0.2564200	test: 0.2580022	best: 0.2580022 (320)	total: 5.09s	remaining: 13.1s
340:	learn: 0.2552255	test: 0.2568463	best: 0.2568463 (340)	total: 5.41s	remaining: 12.7s
360:	learn: 0.2541645	test: 0.2558109	best: 0.2558109 (360)	total: 5.74s	remaining: 12.5s
380:	learn: 0.2531267	test: 0.2548005	best: 0.2548005 (380)	total: 6.05s	remaining: 12.1s
400:	learn: 0.2520922	test: 0.2538856	best: 0.2538856 (400)	total: 6.37s	remaining: 11.8s
420:	learn: 0.2511783	test: 0.2530334	best: 0.2530334 (420)	total: 6.68s	remaining: 11.5s
440:	learn: 0.2502217	test: 0.2521866	best: 0.2521866 (440)	total: 7s	remaining: 11.2s
460:	learn: 0.2494609	test: 0.2515280	best: 0.2515280 (460)	total: 7.31s	remaining: 10.8s
480:	learn: 0.2485392	test: 0.2507266	best: 0.2507266 (480)	total: 7.63s	remaining: 10.5s
500:	learn: 0.2477502	test: 0.2500267	best: 0.2500267 (500)	total: 7.94s	remaining: 10.2s
520:	learn: 0.2470529	test: 0.2494565	best: 0.2494565 (520)	total: 8.26s	remaining: 9.87s
540:	learn: 0.2463722	test: 0.2488574	best: 0.2488574 (540)	total: 8.58s	remaining: 9.56s
560:	learn: 0.2457118	test: 0.2482863	best: 0.2482863 (560)	total: 8.89s	remaining: 9.24s
580:	learn: 0.2450557	test: 0.2477446	best: 0.2477446 (580)	total: 9.2s	remaining: 8.92s
600:	learn: 0.2443492	test: 0.2470888	best: 0.2470888 (600)	total: 9.51s	remaining: 8.6s
620:	learn: 0.2437712	test: 0.2466138	best: 0.2466138 (620)	total: 9.83s	remaining: 8.28s
640:	learn: 0.2431535	test: 0.2460903	best: 0.2460903 (640)	total: 10.1s	remaining: 7.96s
660:	learn: 0.2424995	test: 0.2454915	best: 0.2454915 (660)	total: 10.5s	remaining: 7.64s
680:	learn: 0.2418878	test: 0.2449536	best: 0.2449536 (680)	total: 10.8s	remaining: 7.32s
700:	learn: 0.2412555	test: 0.2443641	best: 0.2443641 (700)	total: 11.1s	remaining: 7s
720:	learn: 0.2407619	test: 0.2439589	best: 0.2439589 (720)	total: 11.4s	remaining: 6.68s
740:	learn: 0.2402787	test: 0.2435784	best: 0.2435784 (740)	total: 11.7s	remaining: 6.36s
760:	learn: 0.2397269	test: 0.2431137	best: 0.2431137 (760)	total: 12s	remaining: 6.04s
780:	learn: 0.2392594	test: 0.2427274	best: 0.2427274 (780)	total: 12.3s	remaining: 5.73s
800:	learn: 0.2387102	test: 0.2422313	best: 0.2422313 (800)	total: 12.6s	remaining: 5.42s
820:	learn: 0.2381583	test: 0.2417286	best: 0.2417286 (820)	total: 13s	remaining: 5.1s
840:	learn: 0.2377319	test: 0.2413947	best: 0.2413947 (840)	total: 13.3s	remaining: 4.78s
860:	learn: 0.2372545	test: 0.2409714	best: 0.2409714 (860)	total: 13.6s	remaining: 4.46s
880:	learn: 0.2368086	test: 0.2405988	best: 0.2405988 (880)	total: 13.9s	remaining: 4.14s
900:	learn: 0.2364224	test: 0.2403009	best: 0.2403009 (900)	total: 14.2s	remaining: 3.82s
920:	learn: 0.2359633	test: 0.2399092	best: 0.2399092 (920)	total: 14.5s	remaining: 3.51s
940:	learn: 0.2355188	test: 0.2395322	best: 0.2395322 (940)	total: 14.8s	remaining: 3.19s
960:	learn: 0.2351403	test: 0.2392473	best: 0.2392473 (960)	total: 15.1s	remaining: 2.88s
980:	learn: 0.2347467	test: 0.2389301	best: 0.2389301 (980)	total: 15.4s	remaining: 2.56s
1000:	learn: 0.2343453	test: 0.2386029	best: 0.2386029 (1000)	total: 15.7s	remaining: 2.25s
1020:	learn: 0.2340188	test: 0.2383423	best: 0.2383423 (1020)	total: 16s	remaining: 1.93s
1040:	learn: 0.2336297	test: 0.2380317	best: 0.2380317 (1040)	total: 16.4s	remaining: 1.62s
1060:	learn: 0.2332464	test: 0.2377374	best: 0.2377374 (1060)	total: 16.7s	remaining: 1.3s
1080:	learn: 0.2329082	test: 0.2374818	best: 0.2374818 (1080)	total: 17s	remaining: 991ms
1100:	learn: 0.2325147	test: 0.2371610	best: 0.2371610 (1100)	total: 17.3s	remaining: 676ms
1120:	learn: 0.2321283	test: 0.2368787	best: 0.2368787 (1120)	total: 17.6s	remaining: 362ms
1140:	learn: 0.2317853	test: 0.2366174	best: 0.2366174 (1140)	total: 17.9s	remaining: 47.2ms
1143:	learn: 0.2317306	test: 0.2365593	best: 0.2365593 (1143)	total: 18s	remaining: 0us
bestTest = 0.23655927
bestIteration = 1143

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6647990	test: 0.6647807	best: 0.6647807 (0)	total: 5.15ms	remaining: 5.15ms
1:	learn: 0.6391601	test: 0.6391251	best: 0.6391251 (1)	total: 9.34ms	remaining: 0us
bestTest = 0.6391251226
bestIteration = 1
0:	learn: 0.6397871	test: 0.6396816	best: 0.6396816 (0)	total: 15ms	remaining: 22.7s
20:	learn: 0.3388503	test: 0.3383491	best: 0.3383491 (20)	total: 318ms	remaining: 22.7s
40:	learn: 0.3076341	test: 0.3073761	best: 0.3073761 (40)	total: 636ms	remaining: 22.9s
60:	learn: 0.2958854	test: 0.2958335	best: 0.2958335 (60)	total: 950ms	remaining: 22.7s
80:	learn: 0.2873448	test: 0.2874051	best: 0.2874051 (80)	total: 1.26s	remaining: 22.3s
100:	learn: 0.2821269	test: 0.2823345	best: 0.2823345 (100)	total: 1.56s	remaining: 21.9s
120:	learn: 0.2776321	test: 0.2779194	best: 0.2779194 (120)	total: 1.87s	remaining: 21.6s
140:	learn: 0.2739889	test: 0.2743264	best: 0.2743264 (140)	total: 2.17s	remaining: 21.2s
160:	learn: 0.2711270	test: 0.2715028	best: 0.2715028 (160)	total: 2.49s	remaining: 21s
180:	learn: 0.2686675	test: 0.2691316	best: 0.2691316 (180)	total: 2.79s	remaining: 20.6s
200:	learn: 0.2661354	test: 0.2666861	best: 0.2666861 (200)	total: 3.1s	remaining: 20.3s
220:	learn: 0.2640912	test: 0.2647220	best: 0.2647220 (220)	total: 3.42s	remaining: 20.1s
240:	learn: 0.2621447	test: 0.2628315	best: 0.2628315 (240)	total: 3.73s	remaining: 19.8s
260:	learn: 0.2605755	test: 0.2613131	best: 0.2613131 (260)	total: 4.05s	remaining: 19.5s
280:	learn: 0.2590247	test: 0.2597994	best: 0.2597994 (280)	total: 4.36s	remaining: 19.2s
300:	learn: 0.2577524	test: 0.2585641	best: 0.2585641 (300)	total: 4.68s	remaining: 18.9s
320:	learn: 0.2562951	test: 0.2572259	best: 0.2572259 (320)	total: 4.98s	remaining: 18.6s
340:	learn: 0.2549719	test: 0.2559756	best: 0.2559756 (340)	total: 5.29s	remaining: 18.3s
360:	learn: 0.2539001	test: 0.2549188	best: 0.2549188 (360)	total: 5.61s	remaining: 18s
380:	learn: 0.2527679	test: 0.2538198	best: 0.2538198 (380)	total: 5.92s	remaining: 17.7s
400:	learn: 0.2519112	test: 0.2530301	best: 0.2530301 (400)	total: 6.23s	remaining: 17.3s
420:	learn: 0.2510125	test: 0.2521849	best: 0.2521849 (420)	total: 6.54s	remaining: 17s
440:	learn: 0.2500638	test: 0.2513128	best: 0.2513128 (440)	total: 6.85s	remaining: 16.7s
460:	learn: 0.2492281	test: 0.2505732	best: 0.2505732 (460)	total: 7.17s	remaining: 16.4s
480:	learn: 0.2483996	test: 0.2498325	best: 0.2498325 (480)	total: 7.49s	remaining: 16.1s
500:	learn: 0.2475614	test: 0.2490712	best: 0.2490712 (500)	total: 7.81s	remaining: 15.8s
520:	learn: 0.2468447	test: 0.2484783	best: 0.2484783 (520)	total: 8.13s	remaining: 15.6s
540:	learn: 0.2461238	test: 0.2479044	best: 0.2479044 (540)	total: 8.46s	remaining: 15.3s
560:	learn: 0.2453925	test: 0.2473131	best: 0.2473131 (560)	total: 8.79s	remaining: 15s
580:	learn: 0.2447742	test: 0.2467795	best: 0.2467795 (580)	total: 9.1s	remaining: 14.7s
600:	learn: 0.2441372	test: 0.2462824	best: 0.2462824 (600)	total: 9.41s	remaining: 14.3s
620:	learn: 0.2433904	test: 0.2456764	best: 0.2456764 (620)	total: 9.73s	remaining: 14s
640:	learn: 0.2427953	test: 0.2452249	best: 0.2452249 (640)	total: 10.1s	remaining: 13.7s
660:	learn: 0.2422179	test: 0.2447574	best: 0.2447574 (660)	total: 10.4s	remaining: 13.4s
680:	learn: 0.2416473	test: 0.2443316	best: 0.2443316 (680)	total: 10.7s	remaining: 13.1s
700:	learn: 0.2410782	test: 0.2438703	best: 0.2438703 (700)	total: 11s	remaining: 12.8s
720:	learn: 0.2404799	test: 0.2433603	best: 0.2433603 (720)	total: 11.3s	remaining: 12.5s
740:	learn: 0.2399181	test: 0.2428482	best: 0.2428482 (740)	total: 11.6s	remaining: 12.2s
760:	learn: 0.2394288	test: 0.2424806	best: 0.2424806 (760)	total: 12s	remaining: 11.9s
780:	learn: 0.2388311	test: 0.2419669	best: 0.2419669 (780)	total: 12.3s	remaining: 11.6s
800:	learn: 0.2383163	test: 0.2415743	best: 0.2415743 (800)	total: 12.6s	remaining: 11.3s
820:	learn: 0.2378542	test: 0.2412149	best: 0.2412149 (820)	total: 12.9s	remaining: 11s
840:	learn: 0.2373861	test: 0.2409120	best: 0.2409120 (840)	total: 13.2s	remaining: 10.6s
860:	learn: 0.2369286	test: 0.2405505	best: 0.2405505 (860)	total: 13.6s	remaining: 10.3s
880:	learn: 0.2365001	test: 0.2402264	best: 0.2402264 (880)	total: 13.9s	remaining: 10s
900:	learn: 0.2359872	test: 0.2397952	best: 0.2397952 (900)	total: 14.2s	remaining: 9.7s
920:	learn: 0.2355666	test: 0.2394864	best: 0.2394864 (920)	total: 14.5s	remaining: 9.39s
940:	learn: 0.2352079	test: 0.2392196	best: 0.2392196 (940)	total: 14.8s	remaining: 9.07s
960:	learn: 0.2348131	test: 0.2389412	best: 0.2389412 (960)	total: 15.1s	remaining: 8.76s
980:	learn: 0.2343944	test: 0.2386226	best: 0.2386226 (980)	total: 15.5s	remaining: 8.44s
1000:	learn: 0.2340121	test: 0.2383336	best: 0.2383336 (1000)	total: 15.8s	remaining: 8.13s
1020:	learn: 0.2335739	test: 0.2379947	best: 0.2379947 (1020)	total: 16.1s	remaining: 7.81s
1040:	learn: 0.2331462	test: 0.2376553	best: 0.2376553 (1040)	total: 16.4s	remaining: 7.5s
1060:	learn: 0.2327826	test: 0.2373722	best: 0.2373722 (1060)	total: 16.7s	remaining: 7.19s
1080:	learn: 0.2324081	test: 0.2370907	best: 0.2370907 (1080)	total: 17s	remaining: 6.87s
1100:	learn: 0.2321110	test: 0.2368925	best: 0.2368925 (1100)	total: 17.3s	remaining: 6.55s
1120:	learn: 0.2317577	test: 0.2366373	best: 0.2366373 (1120)	total: 17.7s	remaining: 6.24s
1140:	learn: 0.2314362	test: 0.2363970	best: 0.2363970 (1140)	total: 18s	remaining: 5.92s
1160:	learn: 0.2311318	test: 0.2361944	best: 0.2361944 (1160)	total: 18.3s	remaining: 5.61s
1180:	learn: 0.2307467	test: 0.2358929	best: 0.2358929 (1180)	total: 18.6s	remaining: 5.29s
1200:	learn: 0.2304391	test: 0.2356783	best: 0.2356783 (1200)	total: 18.9s	remaining: 4.98s
1220:	learn: 0.2301159	test: 0.2354627	best: 0.2354627 (1220)	total: 19.2s	remaining: 4.66s
1240:	learn: 0.2297845	test: 0.2352380	best: 0.2352380 (1240)	total: 19.5s	remaining: 4.35s
1260:	learn: 0.2294055	test: 0.2349513	best: 0.2349513 (1260)	total: 19.9s	remaining: 4.03s
1280:	learn: 0.2291124	test: 0.2347443	best: 0.2347443 (1280)	total: 20.2s	remaining: 3.71s
1300:	learn: 0.2288222	test: 0.2345479	best: 0.2345479 (1300)	total: 20.5s	remaining: 3.4s
1320:	learn: 0.2285382	test: 0.2343608	best: 0.2343608 (1320)	total: 20.8s	remaining: 3.08s
1340:	learn: 0.2282430	test: 0.2341786	best: 0.2341786 (1340)	total: 21.1s	remaining: 2.77s
1360:	learn: 0.2279713	test: 0.2340054	best: 0.2340054 (1360)	total: 21.4s	remaining: 2.45s
1380:	learn: 0.2276356	test: 0.2337512	best: 0.2337512 (1380)	total: 21.7s	remaining: 2.14s
1400:	learn: 0.2273623	test: 0.2335764	best: 0.2335764 (1400)	total: 22s	remaining: 1.82s
1420:	learn: 0.2271324	test: 0.2334281	best: 0.2334281 (1420)	total: 22.3s	remaining: 1.51s
1440:	learn: 0.2268268	test: 0.2332271	best: 0.2332271 (1440)	total: 22.6s	remaining: 1.19s
1460:	learn: 0.2265707	test: 0.2330819	best: 0.2330819 (1460)	total: 22.9s	remaining: 879ms
1480:	learn: 0.2262946	test: 0.2329072	best: 0.2329072 (1480)	total: 23.2s	remaining: 565ms
1500:	learn: 0.2260665	test: 0.2327806	best: 0.2327806 (1500)	total: 23.6s	remaining: 251ms
1516:	learn: 0.2258426	test: 0.2326304	best: 0.2326304 (1516)	total: 23.8s	remaining: 0us
bestTest = 0.232630429
bestIteration = 1516

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6648161	test: 0.6647264	best: 0.6647264 (0)	total: 4.69ms	remaining: 4.69ms
1:	learn: 0.6391711	test: 0.6390053	best: 0.6390053 (1)	total: 8.82ms	remaining: 0us
bestTest = 0.6390053128
bestIteration = 1
0:	learn: 0.6397260	test: 0.6396326	best: 0.6396326 (0)	total: 15.2ms	remaining: 34.4s
20:	learn: 0.3399213	test: 0.3388375	best: 0.3388375 (20)	total: 314ms	remaining: 33.6s
40:	learn: 0.3091269	test: 0.3080043	best: 0.3080043 (40)	total: 622ms	remaining: 33.8s
60:	learn: 0.2966404	test: 0.2954818	best: 0.2954818 (60)	total: 930ms	remaining: 33.7s
80:	learn: 0.2884616	test: 0.2874725	best: 0.2874725 (80)	total: 1.23s	remaining: 33.3s
100:	learn: 0.2830362	test: 0.2821945	best: 0.2821945 (100)	total: 1.54s	remaining: 33s
120:	learn: 0.2783654	test: 0.2776771	best: 0.2776771 (120)	total: 1.84s	remaining: 32.7s
140:	learn: 0.2746790	test: 0.2740989	best: 0.2740989 (140)	total: 2.16s	remaining: 32.6s
160:	learn: 0.2714872	test: 0.2709281	best: 0.2709281 (160)	total: 2.48s	remaining: 32.5s
180:	learn: 0.2681125	test: 0.2677514	best: 0.2677514 (180)	total: 2.78s	remaining: 32.1s
200:	learn: 0.2659374	test: 0.2657031	best: 0.2657031 (200)	total: 3.09s	remaining: 31.8s
220:	learn: 0.2638509	test: 0.2637579	best: 0.2637579 (220)	total: 3.4s	remaining: 31.5s
240:	learn: 0.2622620	test: 0.2623984	best: 0.2623984 (240)	total: 3.71s	remaining: 31.2s
260:	learn: 0.2604262	test: 0.2606880	best: 0.2606880 (260)	total: 4s	remaining: 30.8s
280:	learn: 0.2589510	test: 0.2593623	best: 0.2593623 (280)	total: 4.32s	remaining: 30.5s
300:	learn: 0.2574467	test: 0.2579626	best: 0.2579626 (300)	total: 4.63s	remaining: 30.2s
320:	learn: 0.2561819	test: 0.2568417	best: 0.2568417 (320)	total: 4.94s	remaining: 29.9s
340:	learn: 0.2549338	test: 0.2556640	best: 0.2556640 (340)	total: 5.25s	remaining: 29.7s
360:	learn: 0.2537992	test: 0.2545835	best: 0.2545835 (360)	total: 5.56s	remaining: 29.4s
380:	learn: 0.2528585	test: 0.2537910	best: 0.2537910 (380)	total: 5.87s	remaining: 29.1s
400:	learn: 0.2516908	test: 0.2527866	best: 0.2527866 (400)	total: 6.17s	remaining: 28.7s
420:	learn: 0.2507368	test: 0.2519235	best: 0.2519235 (420)	total: 6.49s	remaining: 28.5s
440:	learn: 0.2498393	test: 0.2511676	best: 0.2511676 (440)	total: 6.8s	remaining: 28.2s
460:	learn: 0.2489468	test: 0.2503872	best: 0.2503872 (460)	total: 7.1s	remaining: 27.8s
480:	learn: 0.2481996	test: 0.2497617	best: 0.2497617 (480)	total: 7.4s	remaining: 27.5s
500:	learn: 0.2473587	test: 0.2490542	best: 0.2490542 (500)	total: 7.72s	remaining: 27.2s
520:	learn: 0.2465832	test: 0.2484105	best: 0.2484105 (520)	total: 8.02s	remaining: 26.9s
540:	learn: 0.2458502	test: 0.2478140	best: 0.2478140 (540)	total: 8.33s	remaining: 26.6s
560:	learn: 0.2451717	test: 0.2472646	best: 0.2472646 (560)	total: 8.63s	remaining: 26.3s
580:	learn: 0.2445571	test: 0.2467358	best: 0.2467358 (580)	total: 8.94s	remaining: 26s
600:	learn: 0.2438973	test: 0.2461938	best: 0.2461938 (600)	total: 9.25s	remaining: 25.6s
620:	learn: 0.2432970	test: 0.2457134	best: 0.2457134 (620)	total: 9.55s	remaining: 25.3s
640:	learn: 0.2426317	test: 0.2451622	best: 0.2451622 (640)	total: 9.85s	remaining: 25s
660:	learn: 0.2420802	test: 0.2446848	best: 0.2446848 (660)	total: 10.2s	remaining: 24.8s
680:	learn: 0.2415571	test: 0.2442635	best: 0.2442635 (680)	total: 10.5s	remaining: 24.5s
700:	learn: 0.2410134	test: 0.2438295	best: 0.2438295 (700)	total: 10.8s	remaining: 24.2s
720:	learn: 0.2404936	test: 0.2434050	best: 0.2434050 (720)	total: 11.1s	remaining: 23.9s
740:	learn: 0.2400185	test: 0.2430183	best: 0.2430183 (740)	total: 11.4s	remaining: 23.5s
760:	learn: 0.2394281	test: 0.2425422	best: 0.2425422 (760)	total: 11.7s	remaining: 23.2s
780:	learn: 0.2389396	test: 0.2421865	best: 0.2421865 (780)	total: 12s	remaining: 22.9s
800:	learn: 0.2384756	test: 0.2418353	best: 0.2418353 (800)	total: 12.4s	remaining: 22.6s
820:	learn: 0.2379372	test: 0.2414098	best: 0.2414098 (820)	total: 12.7s	remaining: 22.3s
840:	learn: 0.2374295	test: 0.2409871	best: 0.2409871 (840)	total: 13s	remaining: 22s
860:	learn: 0.2369748	test: 0.2406347	best: 0.2406347 (860)	total: 13.3s	remaining: 21.7s
880:	learn: 0.2365259	test: 0.2402579	best: 0.2402579 (880)	total: 13.6s	remaining: 21.4s
900:	learn: 0.2360997	test: 0.2399445	best: 0.2399445 (900)	total: 13.9s	remaining: 21.1s
920:	learn: 0.2356681	test: 0.2396262	best: 0.2396262 (920)	total: 14.2s	remaining: 20.8s
940:	learn: 0.2353223	test: 0.2393831	best: 0.2393831 (940)	total: 14.6s	remaining: 20.5s
960:	learn: 0.2349354	test: 0.2391120	best: 0.2391120 (960)	total: 14.9s	remaining: 20.2s
980:	learn: 0.2344883	test: 0.2387961	best: 0.2387961 (980)	total: 15.2s	remaining: 19.9s
1000:	learn: 0.2340953	test: 0.2384908	best: 0.2384908 (1000)	total: 15.5s	remaining: 19.6s
1020:	learn: 0.2336969	test: 0.2382308	best: 0.2382308 (1020)	total: 15.8s	remaining: 19.3s
1040:	learn: 0.2333384	test: 0.2379641	best: 0.2379641 (1040)	total: 16.1s	remaining: 19s
1060:	learn: 0.2329847	test: 0.2377076	best: 0.2377076 (1060)	total: 16.4s	remaining: 18.6s
1080:	learn: 0.2326080	test: 0.2374258	best: 0.2374258 (1080)	total: 16.7s	remaining: 18.3s
1100:	learn: 0.2322405	test: 0.2371768	best: 0.2371768 (1100)	total: 17s	remaining: 18s
1120:	learn: 0.2318690	test: 0.2369097	best: 0.2369097 (1120)	total: 17.3s	remaining: 17.7s
1140:	learn: 0.2315252	test: 0.2366457	best: 0.2366457 (1140)	total: 17.6s	remaining: 17.4s
1160:	learn: 0.2311855	test: 0.2364211	best: 0.2364211 (1160)	total: 17.9s	remaining: 17.1s
1180:	learn: 0.2308736	test: 0.2361968	best: 0.2361968 (1180)	total: 18.2s	remaining: 16.8s
1200:	learn: 0.2305532	test: 0.2359709	best: 0.2359709 (1200)	total: 18.5s	remaining: 16.5s
1220:	learn: 0.2302488	test: 0.2357269	best: 0.2357269 (1220)	total: 18.8s	remaining: 16.1s
1240:	learn: 0.2299162	test: 0.2354883	best: 0.2354883 (1240)	total: 19.1s	remaining: 15.8s
1260:	learn: 0.2295916	test: 0.2352635	best: 0.2352635 (1260)	total: 19.4s	remaining: 15.5s
1280:	learn: 0.2292969	test: 0.2350645	best: 0.2350645 (1280)	total: 19.7s	remaining: 15.2s
1300:	learn: 0.2290189	test: 0.2348936	best: 0.2348936 (1300)	total: 20.1s	remaining: 14.9s
1320:	learn: 0.2286986	test: 0.2347093	best: 0.2347093 (1320)	total: 20.4s	remaining: 14.6s
1340:	learn: 0.2283914	test: 0.2345053	best: 0.2345053 (1340)	total: 20.7s	remaining: 14.3s
1360:	learn: 0.2280972	test: 0.2342995	best: 0.2342995 (1360)	total: 21s	remaining: 14s
1380:	learn: 0.2277941	test: 0.2340992	best: 0.2340992 (1380)	total: 21.3s	remaining: 13.7s
1400:	learn: 0.2274963	test: 0.2339140	best: 0.2339140 (1400)	total: 21.6s	remaining: 13.4s
1420:	learn: 0.2272033	test: 0.2337103	best: 0.2337103 (1420)	total: 21.9s	remaining: 13s
1440:	learn: 0.2269602	test: 0.2335892	best: 0.2335892 (1440)	total: 22.2s	remaining: 12.7s
1460:	learn: 0.2266982	test: 0.2334749	best: 0.2334749 (1460)	total: 22.5s	remaining: 12.4s
1480:	learn: 0.2264684	test: 0.2333668	best: 0.2333668 (1480)	total: 22.8s	remaining: 12.1s
1500:	learn: 0.2261986	test: 0.2331931	best: 0.2331931 (1500)	total: 23.1s	remaining: 11.8s
1520:	learn: 0.2259238	test: 0.2330101	best: 0.2330101 (1520)	total: 23.4s	remaining: 11.5s
1540:	learn: 0.2256935	test: 0.2328902	best: 0.2328902 (1540)	total: 23.7s	remaining: 11.2s
1560:	learn: 0.2254453	test: 0.2327041	best: 0.2327041 (1560)	total: 24.1s	remaining: 10.9s
1580:	learn: 0.2251690	test: 0.2325214	best: 0.2325214 (1580)	total: 24.4s	remaining: 10.6s
1600:	learn: 0.2249157	test: 0.2323755	best: 0.2323755 (1600)	total: 24.7s	remaining: 10.3s
1620:	learn: 0.2246389	test: 0.2322154	best: 0.2322154 (1620)	total: 25s	remaining: 9.97s
1640:	learn: 0.2244205	test: 0.2320862	best: 0.2320860 (1639)	total: 25.3s	remaining: 9.66s
1660:	learn: 0.2241722	test: 0.2319128	best: 0.2319128 (1660)	total: 25.6s	remaining: 9.36s
1680:	learn: 0.2239367	test: 0.2317869	best: 0.2317869 (1680)	total: 25.9s	remaining: 9.05s
1700:	learn: 0.2236733	test: 0.2316206	best: 0.2316206 (1700)	total: 26.2s	remaining: 8.74s
1720:	learn: 0.2234075	test: 0.2314770	best: 0.2314770 (1720)	total: 26.5s	remaining: 8.43s
1740:	learn: 0.2231726	test: 0.2313411	best: 0.2313411 (1740)	total: 26.8s	remaining: 8.12s
1760:	learn: 0.2229000	test: 0.2311835	best: 0.2311835 (1760)	total: 27.1s	remaining: 7.81s
1780:	learn: 0.2226729	test: 0.2310650	best: 0.2310650 (1780)	total: 27.4s	remaining: 7.5s
1800:	learn: 0.2224672	test: 0.2309585	best: 0.2309585 (1800)	total: 27.8s	remaining: 7.2s
1820:	learn: 0.2222328	test: 0.2308117	best: 0.2308117 (1820)	total: 28.1s	remaining: 6.89s
1840:	learn: 0.2219863	test: 0.2306632	best: 0.2306632 (1840)	total: 28.4s	remaining: 6.58s
1860:	learn: 0.2217553	test: 0.2305057	best: 0.2305057 (1860)	total: 28.7s	remaining: 6.27s
1880:	learn: 0.2215369	test: 0.2303802	best: 0.2303802 (1880)	total: 29s	remaining: 5.96s
1900:	learn: 0.2213042	test: 0.2302528	best: 0.2302528 (1900)	total: 29.3s	remaining: 5.65s
1920:	learn: 0.2210754	test: 0.2301414	best: 0.2301414 (1920)	total: 29.6s	remaining: 5.34s
1940:	learn: 0.2208518	test: 0.2300291	best: 0.2300291 (1940)	total: 29.9s	remaining: 5.03s
1960:	learn: 0.2206543	test: 0.2299327	best: 0.2299309 (1959)	total: 30.2s	remaining: 4.72s
1980:	learn: 0.2204572	test: 0.2298307	best: 0.2298307 (1980)	total: 30.5s	remaining: 4.42s
2000:	learn: 0.2202476	test: 0.2297095	best: 0.2297095 (2000)	total: 30.8s	remaining: 4.11s
2020:	learn: 0.2200641	test: 0.2296351	best: 0.2296351 (2020)	total: 31.1s	remaining: 3.8s
2040:	learn: 0.2198707	test: 0.2295447	best: 0.2295446 (2039)	total: 31.4s	remaining: 3.49s
2060:	learn: 0.2196954	test: 0.2294605	best: 0.2294605 (2060)	total: 31.7s	remaining: 3.18s
2080:	learn: 0.2195092	test: 0.2293640	best: 0.2293640 (2080)	total: 32s	remaining: 2.88s
2100:	learn: 0.2193210	test: 0.2292498	best: 0.2292498 (2100)	total: 32.3s	remaining: 2.57s
2120:	learn: 0.2191275	test: 0.2291435	best: 0.2291435 (2120)	total: 32.6s	remaining: 2.26s
2140:	learn: 0.2189245	test: 0.2290091	best: 0.2290091 (2140)	total: 32.9s	remaining: 1.95s
2160:	learn: 0.2187674	test: 0.2289344	best: 0.2289344 (2160)	total: 33.2s	remaining: 1.65s
2180:	learn: 0.2185843	test: 0.2288631	best: 0.2288631 (2180)	total: 33.6s	remaining: 1.34s
2200:	learn: 0.2183910	test: 0.2287721	best: 0.2287721 (2200)	total: 33.9s	remaining: 1.03s
2220:	learn: 0.2182291	test: 0.2286935	best: 0.2286931 (2219)	total: 34.2s	remaining: 723ms
2240:	learn: 0.2180253	test: 0.2285726	best: 0.2285726 (2240)	total: 34.5s	remaining: 415ms
2260:	learn: 0.2178531	test: 0.2284822	best: 0.2284802 (2258)	total: 34.8s	remaining: 108ms
2267:	learn: 0.2178004	test: 0.2284583	best: 0.2284583 (2267)	total: 34.9s	remaining: 0us
bestTest = 0.2284583222
bestIteration = 2267

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6648191	test: 0.6647222	best: 0.6647222 (0)	total: 4.42ms	remaining: 4.42ms
1:	learn: 0.6391827	test: 0.6389874	best: 0.6389874 (1)	total: 9.23ms	remaining: 0us
bestTest = 0.6389874454
bestIteration = 1
0:	learn: 0.6398744	test: 0.6397168	best: 0.6397168 (0)	total: 15ms	remaining: 51.3s
20:	learn: 0.3402192	test: 0.3381433	best: 0.3381433 (20)	total: 311ms	remaining: 50.4s
40:	learn: 0.3092316	test: 0.3062750	best: 0.3062750 (40)	total: 614ms	remaining: 50.6s
60:	learn: 0.2970183	test: 0.2938685	best: 0.2938685 (60)	total: 919ms	remaining: 50.6s
80:	learn: 0.2888973	test: 0.2858265	best: 0.2858265 (80)	total: 1.23s	remaining: 50.5s
100:	learn: 0.2835498	test: 0.2804807	best: 0.2804807 (100)	total: 1.53s	remaining: 50.4s
120:	learn: 0.2794785	test: 0.2765137	best: 0.2765137 (120)	total: 1.83s	remaining: 50s
140:	learn: 0.2746772	test: 0.2718160	best: 0.2718160 (140)	total: 2.14s	remaining: 49.8s
160:	learn: 0.2714445	test: 0.2687823	best: 0.2687823 (160)	total: 2.45s	remaining: 49.6s
180:	learn: 0.2687963	test: 0.2663293	best: 0.2663293 (180)	total: 2.76s	remaining: 49.3s
200:	learn: 0.2663922	test: 0.2640515	best: 0.2640515 (200)	total: 3.07s	remaining: 49.2s
220:	learn: 0.2643709	test: 0.2622510	best: 0.2622510 (220)	total: 3.38s	remaining: 48.9s
240:	learn: 0.2627084	test: 0.2607397	best: 0.2607397 (240)	total: 3.68s	remaining: 48.6s
260:	learn: 0.2611698	test: 0.2593576	best: 0.2593576 (260)	total: 3.99s	remaining: 48.4s
280:	learn: 0.2594455	test: 0.2577520	best: 0.2577520 (280)	total: 4.3s	remaining: 48.1s
300:	learn: 0.2577873	test: 0.2562388	best: 0.2562388 (300)	total: 4.61s	remaining: 47.8s
320:	learn: 0.2566048	test: 0.2552181	best: 0.2552181 (320)	total: 4.92s	remaining: 47.5s
340:	learn: 0.2554818	test: 0.2541924	best: 0.2541924 (340)	total: 5.23s	remaining: 47.2s
360:	learn: 0.2543274	test: 0.2531922	best: 0.2531922 (360)	total: 5.54s	remaining: 46.9s
380:	learn: 0.2533384	test: 0.2523333	best: 0.2523333 (380)	total: 5.84s	remaining: 46.6s
400:	learn: 0.2523097	test: 0.2514408	best: 0.2514408 (400)	total: 6.15s	remaining: 46.3s
420:	learn: 0.2513117	test: 0.2505769	best: 0.2505769 (420)	total: 6.45s	remaining: 46s
440:	learn: 0.2503620	test: 0.2497367	best: 0.2497367 (440)	total: 6.76s	remaining: 45.7s
460:	learn: 0.2495203	test: 0.2490069	best: 0.2490069 (460)	total: 7.07s	remaining: 45.4s
480:	learn: 0.2486355	test: 0.2482890	best: 0.2482890 (480)	total: 7.38s	remaining: 45.1s
500:	learn: 0.2478466	test: 0.2476394	best: 0.2476394 (500)	total: 7.69s	remaining: 44.8s
520:	learn: 0.2470121	test: 0.2469586	best: 0.2469586 (520)	total: 8s	remaining: 44.5s
540:	learn: 0.2462734	test: 0.2463028	best: 0.2463028 (540)	total: 8.3s	remaining: 44.2s
560:	learn: 0.2456640	test: 0.2457976	best: 0.2457976 (560)	total: 8.61s	remaining: 43.9s
580:	learn: 0.2449869	test: 0.2452646	best: 0.2452646 (580)	total: 8.93s	remaining: 43.6s
600:	learn: 0.2442183	test: 0.2445853	best: 0.2445853 (600)	total: 9.23s	remaining: 43.3s
620:	learn: 0.2435458	test: 0.2440243	best: 0.2440243 (620)	total: 9.53s	remaining: 43s
640:	learn: 0.2429235	test: 0.2434965	best: 0.2434965 (640)	total: 9.84s	remaining: 42.7s
660:	learn: 0.2424418	test: 0.2431589	best: 0.2431589 (660)	total: 10.1s	remaining: 42.3s
680:	learn: 0.2418868	test: 0.2427460	best: 0.2427460 (680)	total: 10.4s	remaining: 42s
700:	learn: 0.2413009	test: 0.2422981	best: 0.2422981 (700)	total: 10.8s	remaining: 41.7s
720:	learn: 0.2408046	test: 0.2419046	best: 0.2419046 (720)	total: 11.1s	remaining: 41.4s
740:	learn: 0.2402864	test: 0.2414731	best: 0.2414731 (740)	total: 11.4s	remaining: 41.1s
760:	learn: 0.2397861	test: 0.2411339	best: 0.2411339 (760)	total: 11.7s	remaining: 40.8s
780:	learn: 0.2392936	test: 0.2407338	best: 0.2407338 (780)	total: 12s	remaining: 40.4s
800:	learn: 0.2388216	test: 0.2403753	best: 0.2403753 (800)	total: 12.3s	remaining: 40.1s
820:	learn: 0.2382951	test: 0.2399244	best: 0.2399244 (820)	total: 12.6s	remaining: 39.8s
840:	learn: 0.2378254	test: 0.2395780	best: 0.2395780 (840)	total: 12.9s	remaining: 39.5s
860:	learn: 0.2374369	test: 0.2393105	best: 0.2393098 (859)	total: 13.2s	remaining: 39.2s
880:	learn: 0.2369833	test: 0.2389862	best: 0.2389862 (880)	total: 13.5s	remaining: 38.9s
900:	learn: 0.2365583	test: 0.2386299	best: 0.2386299 (900)	total: 13.8s	remaining: 38.6s
920:	learn: 0.2361237	test: 0.2383026	best: 0.2383026 (920)	total: 14.1s	remaining: 38.3s
940:	learn: 0.2357752	test: 0.2380553	best: 0.2380553 (940)	total: 14.4s	remaining: 37.9s
960:	learn: 0.2353809	test: 0.2377960	best: 0.2377960 (960)	total: 14.7s	remaining: 37.6s
980:	learn: 0.2350562	test: 0.2375845	best: 0.2375845 (980)	total: 15s	remaining: 37.3s
1000:	learn: 0.2346263	test: 0.2372547	best: 0.2372547 (1000)	total: 15.3s	remaining: 37s
1020:	learn: 0.2342141	test: 0.2369348	best: 0.2369348 (1020)	total: 15.6s	remaining: 36.7s
1040:	learn: 0.2338546	test: 0.2366780	best: 0.2366780 (1040)	total: 15.9s	remaining: 36.4s
1060:	learn: 0.2334793	test: 0.2363946	best: 0.2363946 (1060)	total: 16.2s	remaining: 36.1s
1080:	learn: 0.2331179	test: 0.2361352	best: 0.2361352 (1080)	total: 16.5s	remaining: 35.8s
1100:	learn: 0.2328081	test: 0.2359058	best: 0.2359058 (1100)	total: 16.8s	remaining: 35.5s
1120:	learn: 0.2323931	test: 0.2355888	best: 0.2355888 (1120)	total: 17.1s	remaining: 35.1s
1140:	learn: 0.2320518	test: 0.2353127	best: 0.2353127 (1140)	total: 17.4s	remaining: 34.8s
1160:	learn: 0.2317152	test: 0.2350969	best: 0.2350969 (1160)	total: 17.7s	remaining: 34.5s
1180:	learn: 0.2314134	test: 0.2348783	best: 0.2348783 (1180)	total: 18s	remaining: 34.2s
1200:	learn: 0.2311037	test: 0.2346411	best: 0.2346411 (1200)	total: 18.3s	remaining: 33.9s
1220:	learn: 0.2307378	test: 0.2343543	best: 0.2343543 (1220)	total: 18.7s	remaining: 33.6s
1240:	learn: 0.2304430	test: 0.2341613	best: 0.2341613 (1240)	total: 19s	remaining: 33.3s
1260:	learn: 0.2301428	test: 0.2339883	best: 0.2339883 (1260)	total: 19.3s	remaining: 33s
1280:	learn: 0.2297858	test: 0.2336945	best: 0.2336945 (1280)	total: 19.6s	remaining: 32.7s
1300:	learn: 0.2294695	test: 0.2334750	best: 0.2334750 (1300)	total: 19.9s	remaining: 32.4s
1320:	learn: 0.2291852	test: 0.2333141	best: 0.2333141 (1320)	total: 20.2s	remaining: 32.1s
1340:	learn: 0.2288879	test: 0.2330785	best: 0.2330785 (1340)	total: 20.5s	remaining: 31.8s
1360:	learn: 0.2286074	test: 0.2328948	best: 0.2328948 (1360)	total: 20.8s	remaining: 31.5s
1380:	learn: 0.2282999	test: 0.2326670	best: 0.2326670 (1380)	total: 21.1s	remaining: 31.2s
1400:	learn: 0.2280413	test: 0.2325068	best: 0.2325068 (1400)	total: 21.4s	remaining: 30.9s
1420:	learn: 0.2277291	test: 0.2322720	best: 0.2322720 (1420)	total: 21.7s	remaining: 30.6s
1440:	learn: 0.2274649	test: 0.2321139	best: 0.2321139 (1440)	total: 22s	remaining: 30.3s
1460:	learn: 0.2271971	test: 0.2319339	best: 0.2319339 (1460)	total: 22.3s	remaining: 30s
1480:	learn: 0.2269400	test: 0.2317620	best: 0.2317620 (1480)	total: 22.6s	remaining: 29.7s
1500:	learn: 0.2266936	test: 0.2316326	best: 0.2316326 (1500)	total: 22.9s	remaining: 29.3s
1520:	learn: 0.2264517	test: 0.2314718	best: 0.2314718 (1520)	total: 23.2s	remaining: 29s
1540:	learn: 0.2262024	test: 0.2312859	best: 0.2312859 (1540)	total: 23.6s	remaining: 28.7s
1560:	learn: 0.2259510	test: 0.2311432	best: 0.2311432 (1560)	total: 23.9s	remaining: 28.4s
1580:	learn: 0.2256931	test: 0.2309463	best: 0.2309463 (1580)	total: 24.2s	remaining: 28.1s
1600:	learn: 0.2254519	test: 0.2308011	best: 0.2308011 (1600)	total: 24.5s	remaining: 27.8s
1620:	learn: 0.2251690	test: 0.2306143	best: 0.2306143 (1620)	total: 24.8s	remaining: 27.5s
1640:	learn: 0.2249635	test: 0.2304928	best: 0.2304927 (1639)	total: 25.1s	remaining: 27.2s
1660:	learn: 0.2247226	test: 0.2303403	best: 0.2303403 (1660)	total: 25.4s	remaining: 26.9s
1680:	learn: 0.2244472	test: 0.2301405	best: 0.2301405 (1680)	total: 25.7s	remaining: 26.6s
1700:	learn: 0.2241836	test: 0.2299877	best: 0.2299877 (1700)	total: 26s	remaining: 26.3s
1720:	learn: 0.2239665	test: 0.2298727	best: 0.2298727 (1720)	total: 26.3s	remaining: 26s
1740:	learn: 0.2237352	test: 0.2297405	best: 0.2297405 (1740)	total: 26.6s	remaining: 25.7s
1760:	learn: 0.2235144	test: 0.2296299	best: 0.2296299 (1760)	total: 26.9s	remaining: 25.4s
1780:	learn: 0.2232645	test: 0.2294616	best: 0.2294616 (1780)	total: 27.2s	remaining: 25.1s
1800:	learn: 0.2230647	test: 0.2293628	best: 0.2293628 (1800)	total: 27.5s	remaining: 24.8s
1820:	learn: 0.2228095	test: 0.2292115	best: 0.2292115 (1820)	total: 27.8s	remaining: 24.4s
1840:	learn: 0.2225801	test: 0.2290938	best: 0.2290938 (1840)	total: 28.1s	remaining: 24.1s
1860:	learn: 0.2223540	test: 0.2289612	best: 0.2289612 (1860)	total: 28.4s	remaining: 23.8s
1880:	learn: 0.2221332	test: 0.2288138	best: 0.2288138 (1880)	total: 28.7s	remaining: 23.5s
1900:	learn: 0.2219292	test: 0.2286906	best: 0.2286906 (1900)	total: 29.1s	remaining: 23.2s
1920:	learn: 0.2217364	test: 0.2285945	best: 0.2285945 (1920)	total: 29.3s	remaining: 22.9s
1940:	learn: 0.2215125	test: 0.2284695	best: 0.2284695 (1940)	total: 29.7s	remaining: 22.6s
1960:	learn: 0.2213204	test: 0.2283730	best: 0.2283730 (1960)	total: 30s	remaining: 22.3s
1980:	learn: 0.2210929	test: 0.2282411	best: 0.2282393 (1979)	total: 30.3s	remaining: 22s
2000:	learn: 0.2208846	test: 0.2281173	best: 0.2281173 (2000)	total: 30.6s	remaining: 21.7s
2020:	learn: 0.2206683	test: 0.2280281	best: 0.2280281 (2020)	total: 30.9s	remaining: 21.4s
2040:	learn: 0.2204691	test: 0.2279326	best: 0.2279326 (2040)	total: 31.2s	remaining: 21.1s
2060:	learn: 0.2202545	test: 0.2278178	best: 0.2278178 (2060)	total: 31.5s	remaining: 20.8s
2080:	learn: 0.2200608	test: 0.2276992	best: 0.2276992 (2080)	total: 31.8s	remaining: 20.5s
2100:	learn: 0.2198767	test: 0.2276000	best: 0.2275963 (2099)	total: 32.1s	remaining: 20.2s
2120:	learn: 0.2196993	test: 0.2274953	best: 0.2274953 (2120)	total: 32.4s	remaining: 19.9s
2140:	learn: 0.2195178	test: 0.2273893	best: 0.2273893 (2140)	total: 32.7s	remaining: 19.6s
2160:	learn: 0.2193285	test: 0.2273073	best: 0.2273073 (2160)	total: 33s	remaining: 19.3s
2180:	learn: 0.2191359	test: 0.2272161	best: 0.2272161 (2180)	total: 33.3s	remaining: 18.9s
2200:	learn: 0.2189179	test: 0.2270636	best: 0.2270636 (2200)	total: 33.6s	remaining: 18.6s
2220:	learn: 0.2187337	test: 0.2269385	best: 0.2269385 (2220)	total: 33.9s	remaining: 18.3s
2240:	learn: 0.2185359	test: 0.2268173	best: 0.2268173 (2240)	total: 34.2s	remaining: 18s
2260:	learn: 0.2183322	test: 0.2267093	best: 0.2267093 (2260)	total: 34.5s	remaining: 17.7s
2280:	learn: 0.2181509	test: 0.2266168	best: 0.2266168 (2280)	total: 34.9s	remaining: 17.4s
2300:	learn: 0.2179722	test: 0.2265187	best: 0.2265187 (2300)	total: 35.2s	remaining: 17.1s
2320:	learn: 0.2177958	test: 0.2264157	best: 0.2264157 (2320)	total: 35.5s	remaining: 16.8s
2340:	learn: 0.2176087	test: 0.2263525	best: 0.2263525 (2340)	total: 35.8s	remaining: 16.5s
2360:	learn: 0.2174412	test: 0.2262656	best: 0.2262656 (2360)	total: 36.1s	remaining: 16.2s
2380:	learn: 0.2172754	test: 0.2261745	best: 0.2261745 (2380)	total: 36.4s	remaining: 15.9s
2400:	learn: 0.2171114	test: 0.2261147	best: 0.2261147 (2400)	total: 36.7s	remaining: 15.6s
2420:	learn: 0.2169553	test: 0.2260465	best: 0.2260465 (2420)	total: 37s	remaining: 15.3s
2440:	learn: 0.2167695	test: 0.2259664	best: 0.2259664 (2440)	total: 37.3s	remaining: 15s
2460:	learn: 0.2166063	test: 0.2258771	best: 0.2258771 (2460)	total: 37.6s	remaining: 14.7s
2480:	learn: 0.2164435	test: 0.2258041	best: 0.2258041 (2480)	total: 37.9s	remaining: 14.4s
2500:	learn: 0.2162777	test: 0.2257310	best: 0.2257307 (2498)	total: 38.2s	remaining: 14.1s
2520:	learn: 0.2161503	test: 0.2256892	best: 0.2256839 (2519)	total: 38.5s	remaining: 13.8s
2540:	learn: 0.2159784	test: 0.2255720	best: 0.2255720 (2540)	total: 38.8s	remaining: 13.5s
2560:	learn: 0.2158275	test: 0.2254892	best: 0.2254892 (2560)	total: 39.2s	remaining: 13.1s
2580:	learn: 0.2156545	test: 0.2254184	best: 0.2254184 (2580)	total: 39.5s	remaining: 12.8s
2600:	learn: 0.2155085	test: 0.2253693	best: 0.2253693 (2600)	total: 39.8s	remaining: 12.5s
2620:	learn: 0.2153319	test: 0.2252835	best: 0.2252835 (2620)	total: 40.1s	remaining: 12.2s
2640:	learn: 0.2151614	test: 0.2252157	best: 0.2252157 (2640)	total: 40.4s	remaining: 11.9s
2660:	learn: 0.2149882	test: 0.2251417	best: 0.2251417 (2660)	total: 40.7s	remaining: 11.6s
2680:	learn: 0.2148224	test: 0.2250906	best: 0.2250906 (2680)	total: 41s	remaining: 11.3s
2700:	learn: 0.2146327	test: 0.2250038	best: 0.2250038 (2700)	total: 41.3s	remaining: 11s
2720:	learn: 0.2144840	test: 0.2249278	best: 0.2249278 (2720)	total: 41.6s	remaining: 10.7s
2740:	learn: 0.2143039	test: 0.2248328	best: 0.2248328 (2740)	total: 41.9s	remaining: 10.4s
2760:	learn: 0.2141466	test: 0.2247454	best: 0.2247454 (2760)	total: 42.2s	remaining: 10.1s
2780:	learn: 0.2139852	test: 0.2246664	best: 0.2246664 (2780)	total: 42.5s	remaining: 9.79s
2800:	learn: 0.2138133	test: 0.2245931	best: 0.2245931 (2800)	total: 42.8s	remaining: 9.48s
2820:	learn: 0.2136487	test: 0.2245106	best: 0.2245106 (2820)	total: 43.1s	remaining: 9.18s
2840:	learn: 0.2134890	test: 0.2244379	best: 0.2244379 (2840)	total: 43.5s	remaining: 8.87s
2860:	learn: 0.2133449	test: 0.2243837	best: 0.2243837 (2860)	total: 43.8s	remaining: 8.56s
2880:	learn: 0.2131776	test: 0.2243072	best: 0.2243072 (2880)	total: 44.1s	remaining: 8.26s
2900:	learn: 0.2130211	test: 0.2242548	best: 0.2242548 (2900)	total: 44.4s	remaining: 7.96s
2920:	learn: 0.2128584	test: 0.2241715	best: 0.2241715 (2920)	total: 44.7s	remaining: 7.65s
2940:	learn: 0.2127242	test: 0.2241082	best: 0.2241082 (2940)	total: 45s	remaining: 7.34s
2960:	learn: 0.2125663	test: 0.2240465	best: 0.2240465 (2960)	total: 45.3s	remaining: 7.04s
2980:	learn: 0.2124251	test: 0.2239780	best: 0.2239780 (2980)	total: 45.6s	remaining: 6.73s
3000:	learn: 0.2122760	test: 0.2239140	best: 0.2239082 (2996)	total: 45.9s	remaining: 6.43s
3020:	learn: 0.2121200	test: 0.2238314	best: 0.2238314 (3020)	total: 46.2s	remaining: 6.12s
3040:	learn: 0.2119634	test: 0.2237654	best: 0.2237654 (3040)	total: 46.5s	remaining: 5.82s
3060:	learn: 0.2118373	test: 0.2237168	best: 0.2237168 (3060)	total: 46.9s	remaining: 5.51s
3080:	learn: 0.2116940	test: 0.2236479	best: 0.2236479 (3080)	total: 47.2s	remaining: 5.2s
3100:	learn: 0.2115461	test: 0.2235820	best: 0.2235820 (3100)	total: 47.5s	remaining: 4.9s
3120:	learn: 0.2113878	test: 0.2235058	best: 0.2235058 (3120)	total: 47.8s	remaining: 4.59s
3140:	learn: 0.2112319	test: 0.2234366	best: 0.2234356 (3139)	total: 48.1s	remaining: 4.29s
3160:	learn: 0.2110835	test: 0.2233693	best: 0.2233693 (3160)	total: 48.4s	remaining: 3.98s
3180:	learn: 0.2109531	test: 0.2233132	best: 0.2233132 (3180)	total: 48.7s	remaining: 3.67s
3200:	learn: 0.2108238	test: 0.2232596	best: 0.2232596 (3200)	total: 49s	remaining: 3.37s
3220:	learn: 0.2106719	test: 0.2231984	best: 0.2231984 (3220)	total: 49.3s	remaining: 3.06s
3240:	learn: 0.2105229	test: 0.2231331	best: 0.2231331 (3240)	total: 49.6s	remaining: 2.76s
3260:	learn: 0.2103861	test: 0.2230744	best: 0.2230744 (3260)	total: 49.9s	remaining: 2.45s
3280:	learn: 0.2102638	test: 0.2230393	best: 0.2230366 (3277)	total: 50.3s	remaining: 2.14s
3300:	learn: 0.2101283	test: 0.2229740	best: 0.2229740 (3300)	total: 50.6s	remaining: 1.84s
3320:	learn: 0.2099684	test: 0.2229058	best: 0.2229058 (3320)	total: 50.9s	remaining: 1.53s
3340:	learn: 0.2098099	test: 0.2228178	best: 0.2228178 (3340)	total: 51.2s	remaining: 1.23s
3360:	learn: 0.2096879	test: 0.2227654	best: 0.2227654 (3360)	total: 51.5s	remaining: 919ms
3380:	learn: 0.2095609	test: 0.2227271	best: 0.2227271 (3380)	total: 51.8s	remaining: 613ms
3400:	learn: 0.2094062	test: 0.2226637	best: 0.2226630 (3399)	total: 52.1s	remaining: 306ms
3420:	learn: 0.2092517	test: 0.2225967	best: 0.2225960 (3419)	total: 52.4s	remaining: 0us
bestTest = 0.2225960271
bestIteration = 3419
Shrink model to first 3420 iterations.

Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\CatBoost_BAG_L1\model.pkl
	0.9435	 = Validation score   (roc_auc)
	181.82s	 = Training   runtime
	0.16s	 = Validation runtime
	411605.4	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1616.94s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.5 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.29s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	0.9435	 = Validation score   (roc_auc)
	0.06s	 = Training   runtime
	0.05s	 = Validation runtime
	396414.8	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
AutoGluon training complete, total runtime = 183.22s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 396414.8 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models3\CAT\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models3\CAT")

CAT completed.
Validation ROC-AUC: 0.943546

================================================================================
FINAL MODEL COMPARISON
================================================================================

,Model Family,Best AutoGluon Model,Validation ROC-AUC,Fit Time (sec),Predict Time (sec)
0,GBM,WeightedEnsemble_L2,0.957781,410.961213,36.298102
1,XGB,XGBoost_BAG_L1,0.956154,255.022554,3.170212
2,CAT,CatBoost_BAG_L1,0.943546,181.816644,0.164128

In [18]:
import os
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models3"

all_leaderboards = []

# ============================================================
# SCAN & LOAD ALL TRAINED PREDICTORS
# ============================================================

if os.path.exists(MODEL_DIR):
    # Check both subdirectories and root directory for saved predictors
    folder_candidates = [MODEL_DIR] + [
        os.path.join(MODEL_DIR, d) 
        for d in os.listdir(MODEL_DIR) 
        if os.path.isdir(os.path.join(MODEL_DIR, d))
    ]

    for folder_path in folder_candidates:
        # Check if directory contains a valid predictor file
        if os.path.exists(os.path.join(folder_path, "predictor.pkl")):
            try:
                folder_name = os.path.basename(folder_path)
                print(f"Loading predictor from: {folder_path}")
                
                # Load predictor from disk
                predictor = TabularPredictor.load(folder_path)
                
                # Fetch leaderboard
                lb = predictor.leaderboard(silent=True)
                lb.insert(0, "folder_name", folder_name)
                
                all_leaderboards.append(lb)
            except Exception as e:
                print(f"Failed to load predictor from {folder_path}: {e}")

# ============================================================
# MERGE AND PRESENT COMBINED LEADERBOARD
# ============================================================

if all_leaderboards:
    combined_leaderboard = pd.concat(all_leaderboards, ignore_index=True)

    # Sort all trained models by validation ROC-AUC score descending
    combined_leaderboard = combined_leaderboard.sort_values(
        by="score_val", ascending=False
    ).reset_index(drop=True)

    print("\n" + "=" * 80)
    print("COMBINED LEADERBOARD OF ALL LOADED MODELS")
    print("=" * 80)

    display(combined_leaderboard)
else:
    print(f"No valid AutoGluon predictors (`predictor.pkl`) found under '{MODEL_DIR}'.")

Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl

Loading predictor from: ./ag_models3\CAT
Loading predictor from: ./ag_models3\GBM

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl

Loading predictor from: ./ag_models3\XGB

================================================================================
COMBINED LEADERBOARD OF ALL LOADED MODELS
================================================================================

,folder_name,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,GBM,WeightedEnsemble_L2,0.957781,roc_auc,36.298102,410.961213,0.051081,2.553276,2,True,3
1,GBM,LightGBM_BAG_L1,0.957254,roc_auc,12.108692,179.215388,12.108692,179.215388,1,True,1
2,XGB,XGBoost_BAG_L1,0.956154,roc_auc,3.170212,255.022554,3.170212,255.022554,1,True,1
3,XGB,WeightedEnsemble_L2,0.956154,roc_auc,3.220778,255.079135,0.050566,0.056581,2,True,2
4,GBM,LightGBMLarge_BAG_L1,0.955598,roc_auc,24.138329,229.192549,24.138329,229.192549,1,True,2
5,CAT,WeightedEnsemble_L2,0.943546,roc_auc,0.214443,181.873038,0.050315,0.056394,2,True,2
6,CAT,CatBoost_BAG_L1,0.943546,roc_auc,0.164128,181.816644,0.164128,181.816644,1,True,1

In [32]:
predictor = TabularPredictor.load("ag_models3/GBM")
predictor.info()

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F3\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F4\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F5\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F6\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F7\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\S1F8\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F3\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F4\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F5\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F6\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F7\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\S1F8\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl

{'path': 'c:\\Darshak\\Projects\\Hackathon\\ag_models3\\GBM',
 'label': 'PitNextLap',
 'random_state': 0,
 'version': '1.6.1',
 'features': ['Compound',
  'Race',
  'Year',
  'PitStop',
  'LapNumber',
  'Stint',
  'TyreLife',
  'Position',
  'LapTime (s)',
  'LapTime_Delta',
  'Cumulative_Degradation',
  'RaceProgress',
  'Position_Change'],
 'feature_metadata_in': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27b80ebb7d0>,
 'time_fit_preprocessing': 0.7483129501342773,
 'time_fit_training': 451.31227707862854,
 'time_fit_total': 452.0605900287628,
 'time_limit': 1800,
 'time_train_start': 1786365301.0065231,
 'num_rows_train': 540445,
 'num_cols_train': 13,
 'num_rows_val': None,
 'num_rows_test': None,
 'num_classes': 2,
 'problem_type': 'binary',
 'eval_metric': 'roc_auc',
 'best_model': 'WeightedEnsemble_L2',
 'best_model_score_val': np.float64(0.9577806665332587),
 'best_model_stack_level': 2,
 'num_models_trained': 3,
 'num_bag_folds': 8,
 'max_stack_level': 2,
 'max_core_stack_level': 1,
 'model_info': {'LightGBM_BAG_L1': {'name': 'LightGBM_BAG_L1',
   'model_type': 'StackerEnsembleModel',
   'problem_type': 'binary',
   'eval_metric': 'roc_auc',
   'stopping_metric': 'log_loss',
   'fit_time': 179.21538829803467,
   'num_classes': 2,
   'quantile_levels': None,
   'predict_time': 12.108692407608032,
   'val_score': np.float64(0.9572541467316573),
   'hyperparameters': {'use_orig_features': True,
    'valid_stacker': True,
    'max_base_models': 0,
    'max_base_models_per_type': 'auto',
    'save_bag_folds': True,
    'stratify': 'auto',
    'bin': 'auto',
    'n_bins': None,
    'vary_seed_across_folds': False,
    'custom_splits': None,
    'model_random_seed': 0},
   'hyperparameters_user': {},
   'hyperparameters_fit': {},
   'hyperparameters_nondefault': [],
   'ag_args_fit': {'max_memory_usage_ratio': 1.0,
    'max_gpu_memory_usage_ratio': 1.0,
    'max_time_limit_ratio': 1.0,
    'max_time_limit': None,
    'min_time_limit': 0,
    'valid_raw_types': None,
    'valid_special_types': None,
    'ignored_type_group_special': None,
    'ignored_type_group_raw': None,
    'get_features_kwargs': None,
    'get_features_kwargs_extra': None,
    'predict_1_batch_size': None,
    'temperature_scalar': None,
    'drop_unique': False},
   'num_features': 13,
   'features': ['Race',
    'Cumulative_Degradation',
    'LapTime_Delta',
    'LapTime (s)',
    'Compound',
    'PitStop',
    'Position_Change',
    'Year',
    'Stint',
    'Position',
    'RaceProgress',
    'TyreLife',
    'LapNumber'],
   'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27b84a3cbf0>,
   'memory_size': 4250,
   'compile_time': None,
   'is_initialized': True,
   'is_fit': True,
   'is_valid': True,
   'can_infer': True,
   'has_learning_curves': False,
   'num_samples': 540445,
   'val_in_fit': False,
   'unlabeled_in_fit': False,
   'num_cpus': 16,
   'num_gpus': 1,
   'bagged_info': {'child_model_type': 'LGBModel',
    'num_child_models': 8,
    'child_model_names': ['S1F1',
     'S1F2',
     'S1F3',
     'S1F4',
     'S1F5',
     'S1F6',
     'S1F7',
     'S1F8'],
    '_n_repeats': 1,
    '_k_per_n_repeat': [8],
    '_random_state': 1,
    'low_memory': True,
    'bagged_mode': True,
    'max_memory_size': 192235324,
    'min_memory_size': 26264290,
    'child_hyperparameters': {'learning_rate': 0.05, 'seed': 0},
    'child_hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
    'child_hyperparameters_fit': {'num_boost_round': 6953},
    'child_ag_args_fit': {'max_memory_usage_ratio': 1.0,
     'max_gpu_memory_usage_ratio': 1.0,
     'max_time_limit_ratio': 1.0,
     'max_time_limit': None,
     'min_time_limit': 0,
     'valid_raw_types': ['bool', 'int', 'float', 'category'],
     'valid_special_types': None,
     'ignored_type_group_special': None,
     'ignored_type_group_raw': None,
     'get_features_kwargs': None,
     'get_features_kwargs_extra': None,
     'predict_1_batch_size': None,
     'temperature_scalar': None,
     'num_gpus': 1}},
   'stacker_info': {'num_base_models': 0, 'base_model_names': []},
   'children_info': {'S1F1': {'name': 'S1F1',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 24.26169490814209,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.602588415145874,
     'val_score': np.float64(0.9573488739531861),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7380},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00fdd0>,
     'memory_size': 25495371,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F2': {'name': 'S1F2',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 24.621269702911377,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.7326908111572266,
     'val_score': np.float64(0.9577904848768164),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7599},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00e090>,
     'memory_size': 26260040,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F3': {'name': 'S1F3',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 18.412720441818237,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.194077491760254,
     'val_score': np.float64(0.9555303654951979),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 5334},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00d370>,
     'memory_size': 18438838,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F4': {'name': 'S1F4',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 23.66201114654541,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.5674941539764404,
     'val_score': np.float64(0.9571111683856526),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7379},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00cd70>,
     'memory_size': 25501628,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F5': {'name': 'S1F5',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 20.716475009918213,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.4092662334442139,
     'val_score': np.float64(0.9575292137318985),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 6507},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00eb70>,
     'memory_size': 22490274,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F6': {'name': 'S1F6',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 23.33204436302185,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.5863456726074219,
     'val_score': np.float64(0.9576560749752986),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7412},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00f0b0>,
     'memory_size': 25609959,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472890,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F7': {'name': 'S1F7',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 22.029373168945312,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.5050668716430664,
     'val_score': np.float64(0.9567101344485396),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7002},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00e990>,
     'memory_size': 24208057,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472890,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F8': {'name': 'S1F8',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 22.179799556732178,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 1.5111627578735352,
     'val_score': np.float64(0.9583989841515419),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 7014},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 13,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x27dee00d490>,
     'memory_size': 24226907,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472890,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1}}},
  'LightGBMLarge_BAG_L1': {'name': 'LightGBMLarge_BAG_L1',
   'model_type': 'StackerEnsembleModel',
   'problem_type': 'binary',
   'eval_metric': 'roc_auc',
   'stopping_metric': 'log_loss',
   'fit_time': 229.19254851341248,
   'num_classes': 2,
   'quantile_levels': None,
   'predict_time': 24.138328552246094,
   'val_score': np.float64(0.955597555121033),
   'hyperparameters': {'use_orig_features': True,
    'valid_stacker': True,
    'max_base_models': 0,
    'max_base_models_per_type': 'auto',
    'save_bag_folds': True,
    'stratify': 'auto',
    'bin': 'auto',
    'n_bins': None,
    'vary_seed_across_folds': False,
    'custom_splits': None,
    'model_random_seed': 0},
   'hyperparameters_user': {},
   'hyperparameters_fit': {},
   'hyperparameters_nondefault': [],
   'ag_args_fit': {'max_memory_usage_ratio': 1.0,
    'max_gpu_memory_usage_ratio': 1.0,
    'max_time_limit_ratio': 1.0,
    'max_time_limit': None,
    'min_time_limit': 0,
    'valid_raw_types': None,
    'valid_special_types': None,
    'ignored_type_group_special': None,
    'ignored_type_group_raw': None,
    'get_features_kwargs': None,
    'get_features_kwargs_extra': None,
    'predict_1_batch_size': None,
    'temperature_scalar': None,
    'drop_unique': False},
   'num_features': 13,
   'features': ['Race',
    'Cumulative_Degradation',
    'LapTime_Delta',
    'LapTime (s)',
    'Compound',
    'PitStop',
    'Position_Change',

In [33]:
df=predictor.predict_proba(df_test)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl

          0         1
0  0.995913  0.004087
1  0.994767  0.005233
2  0.996719  0.003281
3  0.749973  0.250027
4  0.079022  0.920978

In [34]:
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [35]:
df_sample_out['PitNextLap']=df[1]

In [36]:
df_sample_out.head()

       id  PitNextLap
0  439140    0.004087
1  439141    0.005233
2  439142    0.003281
3  439143    0.250027
4  439144    0.920978

In [37]:
df_sample_out.to_csv("My_output/Without_driver_feature_submission.csv")

In [38]:
### My sampling testing
from multi_sampling_test_predictor import process_and_evaluate_all_csvs
data_dict = process_and_evaluate_all_csvs(predictor,folder_path="Sampling_data_to_test")

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl

----------------------------------------
 Processing: sample_part_1_10000k.csv
----------------------------------------
ground_truth
0    8000
1    2000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_1_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9439
Mismatches                         : 561
Accuracy (%)                       : 94.39
True Positives (Actual 1, Pred 1)  : 1705
True Negatives (Actual 0, Pred 0)  : 7734
False Positives (Actual 0, Pred 1) : 266
False Negatives (Actual 1, Pred 0) : 295
========================================

----------------------------------------
 Processing: sample_part_2_10000k.csv
----------------------------------------
ground_truth
0    8500
1    1500
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_2_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9495
Mismatches                         : 505
Accuracy (%)                       : 94.95
True Positives (Actual 1, Pred 1)  : 1291
True Negatives (Actual 0, Pred 0)  : 8204
False Positives (Actual 0, Pred 1) : 296
False Negatives (Actual 1, Pred 0) : 209
========================================

----------------------------------------
 Processing: sample_part_3_10000k.csv
----------------------------------------
ground_truth
0    7500
1    2500
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_3_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9401
Mismatches                         : 599
Accuracy (%)                       : 94.01
True Positives (Actual 1, Pred 1)  : 2152
True Negatives (Actual 0, Pred 0)  : 7249
False Positives (Actual 0, Pred 1) : 251
False Negatives (Actual 1, Pred 0) : 348
========================================

----------------------------------------
 Processing: sample_part_4_10000k.csv
----------------------------------------
ground_truth
0    7000
1    3000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBMLarge_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_4_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9406
Mismatches                         : 594
Accuracy (%)                       : 94.06
True Positives (Actual 1, Pred 1)  : 2616
True Negatives (Actual 0, Pred 0)  : 6790
False Positives (Actual 0, Pred 1) : 210
False Negatives (Actual 1, Pred 0) : 384
========================================

----------------------------------------
 Processing: sample_part_5_10000k.csv
----------------------------------------
ground_truth
0    9000
1    1000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\WeightedEnsemble_L2\model.pkl

--- Per-File Analysis [sample_part_5_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9560
Mismatches                         : 440
Accuracy (%)                       : 95.6
True Positives (Actual 1, Pred 1)  : 843
True Negatives (Actual 0, Pred 0)  : 8717
False Positives (Actual 0, Pred 1) : 283
False Negatives (Actual 1, Pred 0) : 157
========================================

==================================================
      OVERALL CUMULATIVE ANALYSIS REPORT
==================================================
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 50000
Correct Matches                    : 47301
Mismatches                         : 2699
Accuracy (%)                       : 94.6
True Positives (Actual 1, Pred 1)  : 8607
True Negatives (Actual 0, Pred 0)  : 38694
False Positives (Actual 0, Pred 1) : 1306
False Negatives (Actual 1, Pred 0) : 1393
========================================