In [70]:
import pandas as pd
df_train=pd.read_csv('data/train_fe_cat.csv')
df_test=pd.read_csv('data/test_fe_cat.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

df_train.head()

,Unnamed: 0,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,...,LapNumber_cat,TyreLife_cat,LapTime (s)_cat,LapTime_Delta_cat,Cumulative_Degradation_cat,RaceProgress_cat,Year_cat,PitStop_cat,Stint_cat,Position_cat
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,1.938314,8,...,50,39.0,78.491,-7.564,21.019,0.714286,2022,0,2,8
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,-0.643188,4,...,27,7.0,75.095,-32.617,-223.207,0.346154,2025,1,2,4
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,0.893363,13,...,59,22.0,70.945,-7.540,-100.529,0.819444,2022,0,3,13
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,-1.663862,7,...,2,2.0,94.361,-7.324,-7.324,0.076923,2023,0,1,7
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,-0.802212,2,...,26,6.0,107.878,8.965,-14.139,0.361111,2022,1,3,2

In [71]:
df_train.head()

,Unnamed: 0,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,...,LapNumber_cat,TyreLife_cat,LapTime (s)_cat,LapTime_Delta_cat,Cumulative_Degradation_cat,RaceProgress_cat,Year_cat,PitStop_cat,Stint_cat,Position_cat
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,1.938314,8,...,50,39.0,78.491,-7.564,21.019,0.714286,2022,0,2,8
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,-0.643188,4,...,27,7.0,75.095,-32.617,-223.207,0.346154,2025,1,2,4
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,0.893363,13,...,59,22.0,70.945,-7.540,-100.529,0.819444,2022,0,3,13
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,-1.663862,7,...,2,2.0,94.361,-7.324,-7.324,0.076923,2023,0,1,7
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,-0.802212,2,...,26,6.0,107.878,8.965,-14.139,0.361111,2022,1,3,2

In [72]:
df_test=df_test.drop(['Unnamed: 0', 'id'],axis=1)
df_train=df_train.drop(['Unnamed: 0'],axis=1)

In [73]:
df_train.columns

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap', 'Stint_mean', 'Stint_median', 'Stint_count',
       'Position_mean', 'Position_median', 'Position_count', 'Compound_mean',
       'Compound_median', 'Compound_count', 'Race_mean', 'Race_median',
       'Race_count', 'Driver_mean', 'Driver_median', 'Driver_count',
       'LapNumber_digit_units', 'LapNumber_digit_tens',
       'LapNumber_digit_hundreds', 'TyreLife_digit_units',
       'TyreLife_digit_tens', 'TyreLife_digit_hundreds',
       'LapTime (s)_digit_units', 'LapTime (s)_digit_tens',
       'LapTime (s)_digit_hundreds', 'LapTime_Delta_digit_units',
       'LapTime_Delta_digit_tens', 'LapTime_Delta_digit_hundreds',
       'Cumulative_Degradation_digit_units',
       'Cumulative_Degradation_digit_tens',
       'Cumulative_Degradation_digit_hundreds', 'RaceProgress_digit_units',
       'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds',
       'LapNumber_cat', 'TyreLife_cat', 'LapTime (s)_cat', 'LapTime_Delta_cat',
       'Cumulative_Degradation_cat', 'RaceProgress_cat', 'Year_cat',
       'PitStop_cat', 'Stint_cat', 'Position_cat'],
      dtype='object')

In [74]:
df_test.columns

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'Stint_mean', 'Stint_median', 'Stint_count', 'Position_mean',
       'Position_median', 'Position_count', 'Compound_mean', 'Compound_median',
       'Compound_count', 'Race_mean', 'Race_median', 'Race_count',
       'Driver_mean', 'Driver_median', 'Driver_count', 'LapNumber_digit_units',
       'LapNumber_digit_tens', 'LapNumber_digit_hundreds',
       'TyreLife_digit_units', 'TyreLife_digit_tens',
       'TyreLife_digit_hundreds', 'LapTime (s)_digit_units',
       'LapTime (s)_digit_tens', 'LapTime (s)_digit_hundreds',
       'LapTime_Delta_digit_units', 'LapTime_Delta_digit_tens',
       'LapTime_Delta_digit_hundreds', 'Cumulative_Degradation_digit_units',
       'Cumulative_Degradation_digit_tens',
       'Cumulative_Degradation_digit_hundreds', 'RaceProgress_digit_units',
       'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds',
       'LapNumber_cat', 'TyreLife_cat', 'LapTime (s)_cat', 'LapTime_Delta_cat',
       'Cumulative_Degradation_cat', 'RaceProgress_cat', 'Year_cat',
       'PitStop_cat', 'Stint_cat', 'Position_cat'],
      dtype='object')

In [75]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [76]:
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [77]:
df_test=df_test.drop(['Driver'],axis=1)
df_train_merged=df_train_merged.drop(['Driver'],axis=1)
df_train=df_train.drop(['Driver'],axis=1)

In [78]:
# predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc').fit(
#     train_data=df_train,
#     ag_args_fit={"num_gpus": 2},
#     time_limit=3600*9,
#     presets='best_quality',
#     verbosity=3,
#     num_stack_levels=0
# )

In [79]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [80]:
import os
import shutil
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models4"
TIME_LIMIT = 30 * 60  # 30 minutes (1800 seconds) per model family

models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

# ============================================================
# DELETE OLD MODELS
# ============================================================

# if os.path.exists(MODEL_DIR):
#     print(f"Deleting existing model directory: {MODEL_DIR}")
#     shutil.rmtree(MODEL_DIR)

# os.makedirs(MODEL_DIR, exist_ok=True)
print(f"Fresh model directory created: {MODEL_DIR}")

# ============================================================
# TRAIN ONE MODEL AT A TIME
# ============================================================

predictors = {}
results = []

for model_name, model_config in models.items():

    model_path = os.path.join(MODEL_DIR, model_name)

    print("\n" + "=" * 80)
    print(f"TRAINING: {model_name}")
    print(f"TIME LIMIT: 30 MINUTES")
    print(f"MODEL PATH: {model_path}")
    print("=" * 80)

    predictor = TabularPredictor(
        label=TARGET,
        eval_metric='roc_auc',
        path=model_path
    ).fit(
        train_data=df_train,
        presets="best_quality",  # Enables bagging (_BAG_L1) and out-of-fold validation
        hyperparameters={model_name: model_config},  # Maps key to config dict properly
        ag_args_fit={
            'num_gpus': 1
        },
        time_limit=TIME_LIMIT,
        verbosity=3,
        num_stack_levels=0
    )

    predictors[model_name] = predictor

    # ========================================================
    # GET RESULT
    # ========================================================

    leaderboard = predictor.leaderboard(silent=True)
    best_row = leaderboard.iloc[0]

    results.append({
        'Model Family': model_name,
        'Best AutoGluon Model': best_row['model'],
        'Validation ROC-AUC': best_row['score_val'],
        'Fit Time (sec)': best_row['fit_time'],
        'Predict Time (sec)': best_row['pred_time_val']
    })

    print(f"\n{model_name} completed.")
    print(f"Validation ROC-AUC: {best_row['score_val']:.6f}")

# ============================================================
# FINAL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    'Validation ROC-AUC',
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 80)
print("FINAL MODEL COMPARISON")
print("=" * 80)

display(results_df)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.25 GB / 15.06 GB (14.9%)
Disk Space Avail:   708.37 GB / 930.47 GB (76.1%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\predictor.pkl

Deleting existing model directory: ./ag_models4
Fresh model directory created: ./ag_models4

================================================================================
TRAINING: GBM
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\GBM
================================================================================

Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\GBM"
Train Data Rows:    439140
Train Data Columns: 56
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2639.07 MB
	Train Data (Original)  Memory Usage: 232.45 MB (8.8% of available memory)
	Warning: Data size prior to feature transformation consumes 8.8% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.2s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.1s = Fit runtime
			45 features in original data used to generate 45 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			41 features in original data used to generate 41 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.3s = Fit runtime
	41 features in original data used to generate 41 features in processed data.
	Train Data (Processed) Memory Usage: 125.64 MB (5.0% of available memory)
Data preprocessing and feature engineering runtime = 1.44s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1798.56s of the 1798.56s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.268532
[100]	valid_set's binary_logloss: 0.249229
[150]	valid_set's binary_logloss: 0.242443
[200]	valid_set's binary_logloss: 0.239218
[250]	valid_set's binary_logloss: 0.237275
[300]	valid_set's binary_logloss: 0.236024
[350]	valid_set's binary_logloss: 0.23508
[400]	valid_set's binary_logloss: 0.234329
[450]	valid_set's binary_logloss: 0.233418
[500]	valid_set's binary_logloss: 0.232637
[550]	valid_set's binary_logloss: 0.231976
[600]	valid_set's binary_logloss: 0.231524
[650]	valid_set's binary_logloss: 0.231018
[700]	valid_set's binary_logloss: 0.230782
[750]	valid_set's binary_logloss: 0.230463
[800]	valid_set's binary_logloss: 0.230095
[850]	valid_set's binary_logloss: 0.229778
[900]	valid_set's binary_logloss: 0.229598
[950]	valid_set's binary_logloss: 0.229376
[1000]	valid_set's binary_logloss: 0.229199
[1050]	valid_set's binary_logloss: 0.229031
[1100]	valid_set's binary_logloss: 0.228897
[1150]	valid_set's binary_logloss: 0.228815
[1200]	valid_set's binary_logloss: 0.228766
[1250]	valid_set's binary_logloss: 0.228705
[1300]	valid_set's binary_logloss: 0.228562
[1350]	valid_set's binary_logloss: 0.228469
[1400]	valid_set's binary_logloss: 0.228397
[1450]	valid_set's binary_logloss: 0.228294
[1500]	valid_set's binary_logloss: 0.228234
[1550]	valid_set's binary_logloss: 0.228196
[1600]	valid_set's binary_logloss: 0.228132
[1650]	valid_set's binary_logloss: 0.22805
[1700]	valid_set's binary_logloss: 0.228019
[1750]	valid_set's binary_logloss: 0.228012
[1800]	valid_set's binary_logloss: 0.228005
[1850]	valid_set's binary_logloss: 0.227989
[1900]	valid_set's binary_logloss: 0.227936
[1950]	valid_set's binary_logloss: 0.227872
[2000]	valid_set's binary_logloss: 0.227893
[2050]	valid_set's binary_logloss: 0.227847
[2100]	valid_set's binary_logloss: 0.22779
[2150]	valid_set's binary_logloss: 0.227735
[2200]	valid_set's binary_logloss: 0.227734
[2250]	valid_set's binary_logloss: 0.227739
[2300]	valid_set's binary_logloss: 0.22771
[2350]	valid_set's binary_logloss: 0.227726
[2400]	valid_set's binary_logloss: 0.227757
[2450]	valid_set's binary_logloss: 0.227737
[2500]	valid_set's binary_logloss: 0.227719
[2550]	valid_set's binary_logloss: 0.227711
[2600]	valid_set's binary_logloss: 0.227699
[2650]	valid_set's binary_logloss: 0.227699
[2700]	valid_set's binary_logloss: 0.227765
[2750]	valid_set's binary_logloss: 0.227735
[2800]	valid_set's binary_logloss: 0.227754
[2850]	valid_set's binary_logloss: 0.227818
[2900]	valid_set's binary_logloss: 0.227837
[2950]	valid_set's binary_logloss: 0.227856
[3000]	valid_set's binary_logloss: 0.227879
[3050]	valid_set's binary_logloss: 0.227906
[3100]	valid_set's binary_logloss: 0.227934
[3150]	valid_set's binary_logloss: 0.22798
[3200]	valid_set's binary_logloss: 0.228018
[3250]	valid_set's binary_logloss: 0.228048
[3300]	valid_set's binary_logloss: 0.228036
[3350]	valid_set's binary_logloss: 0.22803
[3400]	valid_set's binary_logloss: 0.228041
[3450]	valid_set's binary_logloss: 0.228006

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269258
[100]	valid_set's binary_logloss: 0.250054
[150]	valid_set's binary_logloss: 0.243392
[200]	valid_set's binary_logloss: 0.239832
[250]	valid_set's binary_logloss: 0.237766
[300]	valid_set's binary_logloss: 0.236136
[350]	valid_set's binary_logloss: 0.235046
[400]	valid_set's binary_logloss: 0.23403
[450]	valid_set's binary_logloss: 0.233136
[500]	valid_set's binary_logloss: 0.232352
[550]	valid_set's binary_logloss: 0.231835
[600]	valid_set's binary_logloss: 0.231247
[650]	valid_set's binary_logloss: 0.230805
[700]	valid_set's binary_logloss: 0.230412
[750]	valid_set's binary_logloss: 0.230147
[800]	valid_set's binary_logloss: 0.229832
[850]	valid_set's binary_logloss: 0.229474
[900]	valid_set's binary_logloss: 0.229255
[950]	valid_set's binary_logloss: 0.229134
[1000]	valid_set's binary_logloss: 0.228868
[1050]	valid_set's binary_logloss: 0.228602
[1100]	valid_set's binary_logloss: 0.228418
[1150]	valid_set's binary_logloss: 0.228269
[1200]	valid_set's binary_logloss: 0.228125
[1250]	valid_set's binary_logloss: 0.227947
[1300]	valid_set's binary_logloss: 0.227719
[1350]	valid_set's binary_logloss: 0.227603
[1400]	valid_set's binary_logloss: 0.227494
[1450]	valid_set's binary_logloss: 0.227368
[1500]	valid_set's binary_logloss: 0.227278
[1550]	valid_set's binary_logloss: 0.227242
[1600]	valid_set's binary_logloss: 0.227159
[1650]	valid_set's binary_logloss: 0.227128
[1700]	valid_set's binary_logloss: 0.22708
[1750]	valid_set's binary_logloss: 0.227035
[1800]	valid_set's binary_logloss: 0.226959
[1850]	valid_set's binary_logloss: 0.226912
[1900]	valid_set's binary_logloss: 0.226858
[1950]	valid_set's binary_logloss: 0.22683
[2000]	valid_set's binary_logloss: 0.226855
[2050]	valid_set's binary_logloss: 0.226868
[2100]	valid_set's binary_logloss: 0.226874
[2150]	valid_set's binary_logloss: 0.226833
[2200]	valid_set's binary_logloss: 0.22682
[2250]	valid_set's binary_logloss: 0.226791
[2300]	valid_set's binary_logloss: 0.226751
[2350]	valid_set's binary_logloss: 0.226737
[2400]	valid_set's binary_logloss: 0.226738
[2450]	valid_set's binary_logloss: 0.226739
[2500]	valid_set's binary_logloss: 0.226719
[2550]	valid_set's binary_logloss: 0.226725
[2600]	valid_set's binary_logloss: 0.226744
[2650]	valid_set's binary_logloss: 0.226768
[2700]	valid_set's binary_logloss: 0.226838
[2750]	valid_set's binary_logloss: 0.226835
[2800]	valid_set's binary_logloss: 0.226827
[2850]	valid_set's binary_logloss: 0.226864
[2900]	valid_set's binary_logloss: 0.226877
[2950]	valid_set's binary_logloss: 0.22686
[3000]	valid_set's binary_logloss: 0.226876
[3050]	valid_set's binary_logloss: 0.226832
[3100]	valid_set's binary_logloss: 0.226772
[3150]	valid_set's binary_logloss: 0.226785

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.264906
[100]	valid_set's binary_logloss: 0.24496
[150]	valid_set's binary_logloss: 0.238368
[200]	valid_set's binary_logloss: 0.234996
[250]	valid_set's binary_logloss: 0.232835
[300]	valid_set's binary_logloss: 0.231496
[350]	valid_set's binary_logloss: 0.230156
[400]	valid_set's binary_logloss: 0.228991
[450]	valid_set's binary_logloss: 0.227945
[500]	valid_set's binary_logloss: 0.227343
[550]	valid_set's binary_logloss: 0.226879
[600]	valid_set's binary_logloss: 0.226375
[650]	valid_set's binary_logloss: 0.225852
[700]	valid_set's binary_logloss: 0.225531
[750]	valid_set's binary_logloss: 0.225141
[800]	valid_set's binary_logloss: 0.224804
[850]	valid_set's binary_logloss: 0.22449
[900]	valid_set's binary_logloss: 0.224291
[950]	valid_set's binary_logloss: 0.224164
[1000]	valid_set's binary_logloss: 0.224042
[1050]	valid_set's binary_logloss: 0.223837
[1100]	valid_set's binary_logloss: 0.223651
[1150]	valid_set's binary_logloss: 0.223475
[1200]	valid_set's binary_logloss: 0.223375
[1250]	valid_set's binary_logloss: 0.223293
[1300]	valid_set's binary_logloss: 0.223157
[1350]	valid_set's binary_logloss: 0.223031
[1400]	valid_set's binary_logloss: 0.222942
[1450]	valid_set's binary_logloss: 0.222799
[1500]	valid_set's binary_logloss: 0.222749
[1550]	valid_set's binary_logloss: 0.222721
[1600]	valid_set's binary_logloss: 0.222566
[1650]	valid_set's binary_logloss: 0.222387
[1700]	valid_set's binary_logloss: 0.222274
[1750]	valid_set's binary_logloss: 0.222267
[1800]	valid_set's binary_logloss: 0.222117
[1850]	valid_set's binary_logloss: 0.222058
[1900]	valid_set's binary_logloss: 0.222047
[1950]	valid_set's binary_logloss: 0.221996
[2000]	valid_set's binary_logloss: 0.221967
[2050]	valid_set's binary_logloss: 0.221994
[2100]	valid_set's binary_logloss: 0.221976
[2150]	valid_set's binary_logloss: 0.221974
[2200]	valid_set's binary_logloss: 0.221944
[2250]	valid_set's binary_logloss: 0.221853
[2300]	valid_set's binary_logloss: 0.221765
[2350]	valid_set's binary_logloss: 0.22176
[2400]	valid_set's binary_logloss: 0.221771
[2450]	valid_set's binary_logloss: 0.221744
[2500]	valid_set's binary_logloss: 0.221702
[2550]	valid_set's binary_logloss: 0.221598
[2600]	valid_set's binary_logloss: 0.221644
[2650]	valid_set's binary_logloss: 0.221571
[2700]	valid_set's binary_logloss: 0.221555
[2750]	valid_set's binary_logloss: 0.22154
[2800]	valid_set's binary_logloss: 0.221567
[2850]	valid_set's binary_logloss: 0.221563
[2900]	valid_set's binary_logloss: 0.221555
[2950]	valid_set's binary_logloss: 0.221535
[3000]	valid_set's binary_logloss: 0.221532
[3050]	valid_set's binary_logloss: 0.221546
[3100]	valid_set's binary_logloss: 0.221559
[3150]	valid_set's binary_logloss: 0.221554
[3200]	valid_set's binary_logloss: 0.221559
[3250]	valid_set's binary_logloss: 0.22155
[3300]	valid_set's binary_logloss: 0.221594
[3350]	valid_set's binary_logloss: 0.221593
[3400]	valid_set's binary_logloss: 0.221642
[3450]	valid_set's binary_logloss: 0.221685
[3500]	valid_set's binary_logloss: 0.221675
[3550]	valid_set's binary_logloss: 0.221669
[3600]	valid_set's binary_logloss: 0.221667
[3650]	valid_set's binary_logloss: 0.221656
[3700]	valid_set's binary_logloss: 0.221674
[3750]	valid_set's binary_logloss: 0.221684
[3800]	valid_set's binary_logloss: 0.221728
[3850]	valid_set's binary_logloss: 0.221751
[3900]	valid_set's binary_logloss: 0.221769

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269758
[100]	valid_set's binary_logloss: 0.25074
[150]	valid_set's binary_logloss: 0.244234
[200]	valid_set's binary_logloss: 0.24094
[250]	valid_set's binary_logloss: 0.238813
[300]	valid_set's binary_logloss: 0.237424
[350]	valid_set's binary_logloss: 0.23644
[400]	valid_set's binary_logloss: 0.235663
[450]	valid_set's binary_logloss: 0.235111
[500]	valid_set's binary_logloss: 0.234486
[550]	valid_set's binary_logloss: 0.233947
[600]	valid_set's binary_logloss: 0.233409
[650]	valid_set's binary_logloss: 0.232611
[700]	valid_set's binary_logloss: 0.232171
[750]	valid_set's binary_logloss: 0.231921
[800]	valid_set's binary_logloss: 0.23148
[850]	valid_set's binary_logloss: 0.231169
[900]	valid_set's binary_logloss: 0.230889
[950]	valid_set's binary_logloss: 0.230606
[1000]	valid_set's binary_logloss: 0.230374
[1050]	valid_set's binary_logloss: 0.230143
[1100]	valid_set's binary_logloss: 0.230067
[1150]	valid_set's binary_logloss: 0.229866
[1200]	valid_set's binary_logloss: 0.229713
[1250]	valid_set's binary_logloss: 0.229518
[1300]	valid_set's binary_logloss: 0.229401
[1350]	valid_set's binary_logloss: 0.229242
[1400]	valid_set's binary_logloss: 0.229091
[1450]	valid_set's binary_logloss: 0.229013
[1500]	valid_set's binary_logloss: 0.228905
[1550]	valid_set's binary_logloss: 0.228794
[1600]	valid_set's binary_logloss: 0.228779
[1650]	valid_set's binary_logloss: 0.228679
[1700]	valid_set's binary_logloss: 0.22862
[1750]	valid_set's binary_logloss: 0.228549
[1800]	valid_set's binary_logloss: 0.228535
[1850]	valid_set's binary_logloss: 0.228516
[1900]	valid_set's binary_logloss: 0.228496
[1950]	valid_set's binary_logloss: 0.228423
[2000]	valid_set's binary_logloss: 0.228413
[2050]	valid_set's binary_logloss: 0.22845
[2100]	valid_set's binary_logloss: 0.228396
[2150]	valid_set's binary_logloss: 0.22833
[2200]	valid_set's binary_logloss: 0.228248
[2250]	valid_set's binary_logloss: 0.228139
[2300]	valid_set's binary_logloss: 0.228121
[2350]	valid_set's binary_logloss: 0.228165
[2400]	valid_set's binary_logloss: 0.228178
[2450]	valid_set's binary_logloss: 0.228154
[2500]	valid_set's binary_logloss: 0.228186
[2550]	valid_set's binary_logloss: 0.22818
[2600]	valid_set's binary_logloss: 0.228148
[2650]	valid_set's binary_logloss: 0.228138
[2700]	valid_set's binary_logloss: 0.228117
[2750]	valid_set's binary_logloss: 0.228062
[2800]	valid_set's binary_logloss: 0.228066
[2850]	valid_set's binary_logloss: 0.228132
[2900]	valid_set's binary_logloss: 0.228192
[2950]	valid_set's binary_logloss: 0.228211
[3000]	valid_set's binary_logloss: 0.228164
[3050]	valid_set's binary_logloss: 0.228195
[3100]	valid_set's binary_logloss: 0.228189
[3150]	valid_set's binary_logloss: 0.228197
[3200]	valid_set's binary_logloss: 0.228219
[3250]	valid_set's binary_logloss: 0.228252
[3300]	valid_set's binary_logloss: 0.22823
[3350]	valid_set's binary_logloss: 0.228191
[3400]	valid_set's binary_logloss: 0.228207
[3450]	valid_set's binary_logloss: 0.22824
[3500]	valid_set's binary_logloss: 0.228222
[3550]	valid_set's binary_logloss: 0.228232

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.268974
[100]	valid_set's binary_logloss: 0.249652
[150]	valid_set's binary_logloss: 0.243041
[200]	valid_set's binary_logloss: 0.239485
[250]	valid_set's binary_logloss: 0.237583
[300]	valid_set's binary_logloss: 0.236411
[350]	valid_set's binary_logloss: 0.235052
[400]	valid_set's binary_logloss: 0.23435
[450]	valid_set's binary_logloss: 0.23329
[500]	valid_set's binary_logloss: 0.232367
[550]	valid_set's binary_logloss: 0.231786
[600]	valid_set's binary_logloss: 0.231198
[650]	valid_set's binary_logloss: 0.230787
[700]	valid_set's binary_logloss: 0.230438
[750]	valid_set's binary_logloss: 0.230188
[800]	valid_set's binary_logloss: 0.229875
[850]	valid_set's binary_logloss: 0.2296
[900]	valid_set's binary_logloss: 0.22935
[950]	valid_set's binary_logloss: 0.229184
[1000]	valid_set's binary_logloss: 0.228927
[1050]	valid_set's binary_logloss: 0.22885
[1100]	valid_set's binary_logloss: 0.228687
[1150]	valid_set's binary_logloss: 0.228412
[1200]	valid_set's binary_logloss: 0.228179
[1250]	valid_set's binary_logloss: 0.227971
[1300]	valid_set's binary_logloss: 0.22786
[1350]	valid_set's binary_logloss: 0.227713
[1400]	valid_set's binary_logloss: 0.22758
[1450]	valid_set's binary_logloss: 0.227483
[1500]	valid_set's binary_logloss: 0.227388
[1550]	valid_set's binary_logloss: 0.227253
[1600]	valid_set's binary_logloss: 0.22716
[1650]	valid_set's binary_logloss: 0.227067
[1700]	valid_set's binary_logloss: 0.227001
[1750]	valid_set's binary_logloss: 0.226909
[1800]	valid_set's binary_logloss: 0.226839
[1850]	valid_set's binary_logloss: 0.226776
[1900]	valid_set's binary_logloss: 0.226769
[1950]	valid_set's binary_logloss: 0.226795
[2000]	valid_set's binary_logloss: 0.226716
[2050]	valid_set's binary_logloss: 0.226734
[2100]	valid_set's binary_logloss: 0.226693
[2150]	valid_set's binary_logloss: 0.226723
[2200]	valid_set's binary_logloss: 0.226603
[2250]	valid_set's binary_logloss: 0.226576
[2300]	valid_set's binary_logloss: 0.226568
[2350]	valid_set's binary_logloss: 0.22657
[2400]	valid_set's binary_logloss: 0.226552
[2450]	valid_set's binary_logloss: 0.226541
[2500]	valid_set's binary_logloss: 0.22647
[2550]	valid_set's binary_logloss: 0.22647
[2600]	valid_set's binary_logloss: 0.226449
[2650]	valid_set's binary_logloss: 0.226452
[2700]	valid_set's binary_logloss: 0.226435
[2750]	valid_set's binary_logloss: 0.226422
[2800]	valid_set's binary_logloss: 0.226469
[2850]	valid_set's binary_logloss: 0.226441
[2900]	valid_set's binary_logloss: 0.22649
[2950]	valid_set's binary_logloss: 0.22647
[3000]	valid_set's binary_logloss: 0.226516
[3050]	valid_set's binary_logloss: 0.226559
[3100]	valid_set's binary_logloss: 0.22652
[3150]	valid_set's binary_logloss: 0.226549
[3200]	valid_set's binary_logloss: 0.226561
[3250]	valid_set's binary_logloss: 0.226603
[3300]	valid_set's binary_logloss: 0.226628
[3350]	valid_set's binary_logloss: 0.226647
[3400]	valid_set's binary_logloss: 0.226643
[3450]	valid_set's binary_logloss: 0.226642
[3500]	valid_set's binary_logloss: 0.226651

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269394
[100]	valid_set's binary_logloss: 0.250973
[150]	valid_set's binary_logloss: 0.244434
[200]	valid_set's binary_logloss: 0.241035
[250]	valid_set's binary_logloss: 0.239014
[300]	valid_set's binary_logloss: 0.237485
[350]	valid_set's binary_logloss: 0.236224
[400]	valid_set's binary_logloss: 0.235419
[450]	valid_set's binary_logloss: 0.234828
[500]	valid_set's binary_logloss: 0.234165
[550]	valid_set's binary_logloss: 0.233532
[600]	valid_set's binary_logloss: 0.233211
[650]	valid_set's binary_logloss: 0.232933
[700]	valid_set's binary_logloss: 0.232537
[750]	valid_set's binary_logloss: 0.232272
[800]	valid_set's binary_logloss: 0.231968
[850]	valid_set's binary_logloss: 0.231578
[900]	valid_set's binary_logloss: 0.231372
[950]	valid_set's binary_logloss: 0.231214
[1000]	valid_set's binary_logloss: 0.230951
[1050]	valid_set's binary_logloss: 0.230805
[1100]	valid_set's binary_logloss: 0.230638
[1150]	valid_set's binary_logloss: 0.230521
[1200]	valid_set's binary_logloss: 0.230321
[1250]	valid_set's binary_logloss: 0.230247
[1300]	valid_set's binary_logloss: 0.230161
[1350]	valid_set's binary_logloss: 0.230112
[1400]	valid_set's binary_logloss: 0.229991
[1450]	valid_set's binary_logloss: 0.229934
[1500]	valid_set's binary_logloss: 0.229822
[1550]	valid_set's binary_logloss: 0.229692
[1600]	valid_set's binary_logloss: 0.229624
[1650]	valid_set's binary_logloss: 0.229527
[1700]	valid_set's binary_logloss: 0.229468
[1750]	valid_set's binary_logloss: 0.229389
[1800]	valid_set's binary_logloss: 0.22933
[1850]	valid_set's binary_logloss: 0.229241
[1900]	valid_set's binary_logloss: 0.229184
[1950]	valid_set's binary_logloss: 0.229074
[2000]	valid_set's binary_logloss: 0.228967
[2050]	valid_set's binary_logloss: 0.228891
[2100]	valid_set's binary_logloss: 0.228819
[2150]	valid_set's binary_logloss: 0.228814
[2200]	valid_set's binary_logloss: 0.228823
[2250]	valid_set's binary_logloss: 0.228767
[2300]	valid_set's binary_logloss: 0.228796
[2350]	valid_set's binary_logloss: 0.228799
[2400]	valid_set's binary_logloss: 0.228798
[2450]	valid_set's binary_logloss: 0.228776
[2500]	valid_set's binary_logloss: 0.22871
[2550]	valid_set's binary_logloss: 0.228716
[2600]	valid_set's binary_logloss: 0.228663
[2650]	valid_set's binary_logloss: 0.228595
[2700]	valid_set's binary_logloss: 0.228638
[2750]	valid_set's binary_logloss: 0.228662
[2800]	valid_set's binary_logloss: 0.2287
[2850]	valid_set's binary_logloss: 0.228756
[2900]	valid_set's binary_logloss: 0.228789
[2950]	valid_set's binary_logloss: 0.228853
[3000]	valid_set's binary_logloss: 0.228916
[3050]	valid_set's binary_logloss: 0.22893
[3100]	valid_set's binary_logloss: 0.228925
[3150]	valid_set's binary_logloss: 0.228911
[3200]	valid_set's binary_logloss: 0.228961
[3250]	valid_set's binary_logloss: 0.22896
[3300]	valid_set's binary_logloss: 0.228963
[3350]	valid_set's binary_logloss: 0.228966
[3400]	valid_set's binary_logloss: 0.229045
[3450]	valid_set's binary_logloss: 0.229059

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269152
[100]	valid_set's binary_logloss: 0.25032
[150]	valid_set's binary_logloss: 0.244016
[200]	valid_set's binary_logloss: 0.240654
[250]	valid_set's binary_logloss: 0.238888
[300]	valid_set's binary_logloss: 0.237461
[350]	valid_set's binary_logloss: 0.236352
[400]	valid_set's binary_logloss: 0.235483
[450]	valid_set's binary_logloss: 0.234843
[500]	valid_set's binary_logloss: 0.234026
[550]	valid_set's binary_logloss: 0.233505
[600]	valid_set's binary_logloss: 0.233206
[650]	valid_set's binary_logloss: 0.232688
[700]	valid_set's binary_logloss: 0.232358
[750]	valid_set's binary_logloss: 0.232071
[800]	valid_set's binary_logloss: 0.231662
[850]	valid_set's binary_logloss: 0.231279
[900]	valid_set's binary_logloss: 0.231086
[950]	valid_set's binary_logloss: 0.2309
[1000]	valid_set's binary_logloss: 0.230678
[1050]	valid_set's binary_logloss: 0.230411
[1100]	valid_set's binary_logloss: 0.230293
[1150]	valid_set's binary_logloss: 0.230177
[1200]	valid_set's binary_logloss: 0.230051
[1250]	valid_set's binary_logloss: 0.229936
[1300]	valid_set's binary_logloss: 0.229878
[1350]	valid_set's binary_logloss: 0.229829
[1400]	valid_set's binary_logloss: 0.229703
[1450]	valid_set's binary_logloss: 0.229559
[1500]	valid_set's binary_logloss: 0.229502
[1550]	valid_set's binary_logloss: 0.2294
[1600]	valid_set's binary_logloss: 0.229336
[1650]	valid_set's binary_logloss: 0.229271
[1700]	valid_set's binary_logloss: 0.229223
[1750]	valid_set's binary_logloss: 0.229182
[1800]	valid_set's binary_logloss: 0.229095
[1850]	valid_set's binary_logloss: 0.2291
[1900]	valid_set's binary_logloss: 0.229056
[1950]	valid_set's binary_logloss: 0.229007
[2000]	valid_set's binary_logloss: 0.229
[2050]	valid_set's binary_logloss: 0.228862
[2100]	valid_set's binary_logloss: 0.228837
[2150]	valid_set's binary_logloss: 0.228807
[2200]	valid_set's binary_logloss: 0.228764
[2250]	valid_set's binary_logloss: 0.228772
[2300]	valid_set's binary_logloss: 0.228764
[2350]	valid_set's binary_logloss: 0.228789
[2400]	valid_set's binary_logloss: 0.228829
[2450]	valid_set's binary_logloss: 0.228858
[2500]	valid_set's binary_logloss: 0.228864
[2550]	valid_set's binary_logloss: 0.228838
[2600]	valid_set's binary_logloss: 0.228842
[2650]	valid_set's binary_logloss: 0.228779
[2700]	valid_set's binary_logloss: 0.228767
[2750]	valid_set's binary_logloss: 0.228755
[2800]	valid_set's binary_logloss: 0.228759
[2850]	valid_set's binary_logloss: 0.228782
[2900]	valid_set's binary_logloss: 0.228732
[2950]	valid_set's binary_logloss: 0.228769
[3000]	valid_set's binary_logloss: 0.22876
[3050]	valid_set's binary_logloss: 0.228797
[3100]	valid_set's binary_logloss: 0.22883
[3150]	valid_set's binary_logloss: 0.228817
[3200]	valid_set's binary_logloss: 0.228821
[3250]	valid_set's binary_logloss: 0.228804
[3300]	valid_set's binary_logloss: 0.228838
[3350]	valid_set's binary_logloss: 0.228899
[3400]	valid_set's binary_logloss: 0.228902
[3450]	valid_set's binary_logloss: 0.228941
[3500]	valid_set's binary_logloss: 0.229005
[3550]	valid_set's binary_logloss: 0.22906
[3600]	valid_set's binary_logloss: 0.229076
[3650]	valid_set's binary_logloss: 0.229141
[3700]	valid_set's binary_logloss: 0.229158
[3750]	valid_set's binary_logloss: 0.229166
[3800]	valid_set's binary_logloss: 0.229195

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.266577
[100]	valid_set's binary_logloss: 0.247487
[150]	valid_set's binary_logloss: 0.240701
[200]	valid_set's binary_logloss: 0.236939
[250]	valid_set's binary_logloss: 0.234758
[300]	valid_set's binary_logloss: 0.233393
[350]	valid_set's binary_logloss: 0.232434
[400]	valid_set's binary_logloss: 0.23142
[450]	valid_set's binary_logloss: 0.230358
[500]	valid_set's binary_logloss: 0.229779
[550]	valid_set's binary_logloss: 0.229346
[600]	valid_set's binary_logloss: 0.228667
[650]	valid_set's binary_logloss: 0.228108
[700]	valid_set's binary_logloss: 0.227707
[750]	valid_set's binary_logloss: 0.22746
[800]	valid_set's binary_logloss: 0.227168
[850]	valid_set's binary_logloss: 0.22689
[900]	valid_set's binary_logloss: 0.226781
[950]	valid_set's binary_logloss: 0.226632
[1000]	valid_set's binary_logloss: 0.226551
[1050]	valid_set's binary_logloss: 0.226478
[1100]	valid_set's binary_logloss: 0.226323
[1150]	valid_set's binary_logloss: 0.226195
[1200]	valid_set's binary_logloss: 0.226028
[1250]	valid_set's binary_logloss: 0.225828
[1300]	valid_set's binary_logloss: 0.225594
[1350]	valid_set's binary_logloss: 0.2255
[1400]	valid_set's binary_logloss: 0.225389
[1450]	valid_set's binary_logloss: 0.225358
[1500]	valid_set's binary_logloss: 0.225217
[1550]	valid_set's binary_logloss: 0.225077
[1600]	valid_set's binary_logloss: 0.224937
[1650]	valid_set's binary_logloss: 0.22486
[1700]	valid_set's binary_logloss: 0.224743
[1750]	valid_set's binary_logloss: 0.224674
[1800]	valid_set's binary_logloss: 0.224612
[1850]	valid_set's binary_logloss: 0.224586
[1900]	valid_set's binary_logloss: 0.224545
[1950]	valid_set's binary_logloss: 0.224482
[2000]	valid_set's binary_logloss: 0.22443
[2050]	valid_set's binary_logloss: 0.224367
[2100]	valid_set's binary_logloss: 0.22433
[2150]	valid_set's binary_logloss: 0.22426
[2200]	valid_set's binary_logloss: 0.224245
[2250]	valid_set's binary_logloss: 0.224184
[2300]	valid_set's binary_logloss: 0.224152
[2350]	valid_set's binary_logloss: 0.224157
[2400]	valid_set's binary_logloss: 0.224147
[2450]	valid_set's binary_logloss: 0.224076
[2500]	valid_set's binary_logloss: 0.22408
[2550]	valid_set's binary_logloss: 0.224093
[2600]	valid_set's binary_logloss: 0.224128
[2650]	valid_set's binary_logloss: 0.224098
[2700]	valid_set's binary_logloss: 0.224098
[2750]	valid_set's binary_logloss: 0.224075
[2800]	valid_set's binary_logloss: 0.224046
[2850]	valid_set's binary_logloss: 0.224034
[2900]	valid_set's binary_logloss: 0.224063
[2950]	valid_set's binary_logloss: 0.224029
[3000]	valid_set's binary_logloss: 0.224064
[3050]	valid_set's binary_logloss: 0.224103
[3100]	valid_set's binary_logloss: 0.224097
[3150]	valid_set's binary_logloss: 0.224049
[3200]	valid_set's binary_logloss: 0.224038
[3250]	valid_set's binary_logloss: 0.224019
[3300]	valid_set's binary_logloss: 0.224028
[3350]	valid_set's binary_logloss: 0.224039
[3400]	valid_set's binary_logloss: 0.22402
[3450]	valid_set's binary_logloss: 0.224095
[3500]	valid_set's binary_logloss: 0.224099
[3550]	valid_set's binary_logloss: 0.224112
[3600]	valid_set's binary_logloss: 0.224142
[3650]	valid_set's binary_logloss: 0.224129
[3700]	valid_set's binary_logloss: 0.224158
[3750]	valid_set's binary_logloss: 0.224169
[3800]	valid_set's binary_logloss: 0.224245
[3850]	valid_set's binary_logloss: 0.224319
[3900]	valid_set's binary_logloss: 0.224361
[3950]	valid_set's binary_logloss: 0.224384
[4000]	valid_set's binary_logloss: 0.224404
[4050]	valid_set's binary_logloss: 0.224432
[4100]	valid_set's binary_logloss: 0.224508
[4150]	valid_set's binary_logloss: 0.224575
[4200]	valid_set's binary_logloss: 0.224602
[4250]	valid_set's binary_logloss: 0.224607

Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\model.pkl
	0.9486	 = Validation score   (roc_auc)
	105.9s	 = Training   runtime
	4.33s	 = Validation runtime
	12691.0	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1687.24s of the 1687.24s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281194
[100]	valid_set's binary_logloss: 0.258622
[150]	valid_set's binary_logloss: 0.249543
[200]	valid_set's binary_logloss: 0.244264
[250]	valid_set's binary_logloss: 0.241104
[300]	valid_set's binary_logloss: 0.23899
[350]	valid_set's binary_logloss: 0.237374
[400]	valid_set's binary_logloss: 0.236172
[450]	valid_set's binary_logloss: 0.235344
[500]	valid_set's binary_logloss: 0.23462
[550]	valid_set's binary_logloss: 0.234077
[600]	valid_set's binary_logloss: 0.233575
[650]	valid_set's binary_logloss: 0.233209
[700]	valid_set's binary_logloss: 0.232814
[750]	valid_set's binary_logloss: 0.232452
[800]	valid_set's binary_logloss: 0.232213
[850]	valid_set's binary_logloss: 0.231976
[900]	valid_set's binary_logloss: 0.231757
[950]	valid_set's binary_logloss: 0.231444
[1000]	valid_set's binary_logloss: 0.231256
[1050]	valid_set's binary_logloss: 0.230993
[1100]	valid_set's binary_logloss: 0.230825
[1150]	valid_set's binary_logloss: 0.230677
[1200]	valid_set's binary_logloss: 0.230548
[1250]	valid_set's binary_logloss: 0.230484
[1300]	valid_set's binary_logloss: 0.230333
[1350]	valid_set's binary_logloss: 0.230208
[1400]	valid_set's binary_logloss: 0.230133
[1450]	valid_set's binary_logloss: 0.229968
[1500]	valid_set's binary_logloss: 0.229903
[1550]	valid_set's binary_logloss: 0.229869
[1600]	valid_set's binary_logloss: 0.22984
[1650]	valid_set's binary_logloss: 0.229728
[1700]	valid_set's binary_logloss: 0.229601
[1750]	valid_set's binary_logloss: 0.229557
[1800]	valid_set's binary_logloss: 0.229471
[1850]	valid_set's binary_logloss: 0.22944
[1900]	valid_set's binary_logloss: 0.229414
[1950]	valid_set's binary_logloss: 0.22934
[2000]	valid_set's binary_logloss: 0.229261
[2050]	valid_set's binary_logloss: 0.229225
[2100]	valid_set's binary_logloss: 0.229193
[2150]	valid_set's binary_logloss: 0.229154
[2200]	valid_set's binary_logloss: 0.229152
[2250]	valid_set's binary_logloss: 0.229089
[2300]	valid_set's binary_logloss: 0.229022
[2350]	valid_set's binary_logloss: 0.228937
[2400]	valid_set's binary_logloss: 0.228913
[2450]	valid_set's binary_logloss: 0.228882
[2500]	valid_set's binary_logloss: 0.228852
[2550]	valid_set's binary_logloss: 0.228829
[2600]	valid_set's binary_logloss: 0.228798
[2650]	valid_set's binary_logloss: 0.228773
[2700]	valid_set's binary_logloss: 0.228739
[2750]	valid_set's binary_logloss: 0.228762
[2800]	valid_set's binary_logloss: 0.228743
[2850]	valid_set's binary_logloss: 0.228689
[2900]	valid_set's binary_logloss: 0.228644
[2950]	valid_set's binary_logloss: 0.228606
[3000]	valid_set's binary_logloss: 0.228644
[3050]	valid_set's binary_logloss: 0.228632
[3100]	valid_set's binary_logloss: 0.228575
[3150]	valid_set's binary_logloss: 0.228565
[3200]	valid_set's binary_logloss: 0.228514
[3250]	valid_set's binary_logloss: 0.228521
[3300]	valid_set's binary_logloss: 0.228474
[3350]	valid_set's binary_logloss: 0.228486
[3400]	valid_set's binary_logloss: 0.228485
[3450]	valid_set's binary_logloss: 0.228424
[3500]	valid_set's binary_logloss: 0.228407
[3550]	valid_set's binary_logloss: 0.228379
[3600]	valid_set's binary_logloss: 0.228396
[3650]	valid_set's binary_logloss: 0.228395
[3700]	valid_set's binary_logloss: 0.228405
[3750]	valid_set's binary_logloss: 0.228389
[3800]	valid_set's binary_logloss: 0.228434
[3850]	valid_set's binary_logloss: 0.228432
[3900]	valid_set's binary_logloss: 0.228435
[3950]	valid_set's binary_logloss: 0.22844
[4000]	valid_set's binary_logloss: 0.228411
[4050]	valid_set's binary_logloss: 0.228439
[4100]	valid_set's binary_logloss: 0.228424
[4150]	valid_set's binary_logloss: 0.228456
[4200]	valid_set's binary_logloss: 0.228411
[4250]	valid_set's binary_logloss: 0.228409
[4300]	valid_set's binary_logloss: 0.228415
[4350]	valid_set's binary_logloss: 0.228436
[4400]	valid_set's binary_logloss: 0.22849
[4450]	valid_set's binary_logloss: 0.228508
[4500]	valid_set's binary_logloss: 0.228505
[4550]	valid_set's binary_logloss: 0.228525
[4600]	valid_set's binary_logloss: 0.228569

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283513
[100]	valid_set's binary_logloss: 0.259908
[150]	valid_set's binary_logloss: 0.250077
[200]	valid_set's binary_logloss: 0.245086
[250]	valid_set's binary_logloss: 0.241553
[300]	valid_set's binary_logloss: 0.239164
[350]	valid_set's binary_logloss: 0.237565
[400]	valid_set's binary_logloss: 0.236122
[450]	valid_set's binary_logloss: 0.235222
[500]	valid_set's binary_logloss: 0.234425
[550]	valid_set's binary_logloss: 0.233852
[600]	valid_set's binary_logloss: 0.233372
[650]	valid_set's binary_logloss: 0.232942
[700]	valid_set's binary_logloss: 0.232511
[750]	valid_set's binary_logloss: 0.232256
[800]	valid_set's binary_logloss: 0.231907
[850]	valid_set's binary_logloss: 0.231572
[900]	valid_set's binary_logloss: 0.231258
[950]	valid_set's binary_logloss: 0.231111
[1000]	valid_set's binary_logloss: 0.230913
[1050]	valid_set's binary_logloss: 0.230774
[1100]	valid_set's binary_logloss: 0.230606
[1150]	valid_set's binary_logloss: 0.230393
[1200]	valid_set's binary_logloss: 0.23023
[1250]	valid_set's binary_logloss: 0.230144
[1300]	valid_set's binary_logloss: 0.23005
[1350]	valid_set's binary_logloss: 0.229908
[1400]	valid_set's binary_logloss: 0.22977
[1450]	valid_set's binary_logloss: 0.229718
[1500]	valid_set's binary_logloss: 0.229653
[1550]	valid_set's binary_logloss: 0.229576
[1600]	valid_set's binary_logloss: 0.229478
[1650]	valid_set's binary_logloss: 0.229362
[1700]	valid_set's binary_logloss: 0.229298
[1750]	valid_set's binary_logloss: 0.229264
[1800]	valid_set's binary_logloss: 0.229197
[1850]	valid_set's binary_logloss: 0.229074
[1900]	valid_set's binary_logloss: 0.229038
[1950]	valid_set's binary_logloss: 0.229
[2000]	valid_set's binary_logloss: 0.228909
[2050]	valid_set's binary_logloss: 0.228851
[2100]	valid_set's binary_logloss: 0.22881
[2150]	valid_set's binary_logloss: 0.228775
[2200]	valid_set's binary_logloss: 0.228726
[2250]	valid_set's binary_logloss: 0.228693
[2300]	valid_set's binary_logloss: 0.228646
[2350]	valid_set's binary_logloss: 0.228624
[2400]	valid_set's binary_logloss: 0.228565
[2450]	valid_set's binary_logloss: 0.228562
[2500]	valid_set's binary_logloss: 0.228563
[2550]	valid_set's binary_logloss: 0.228557
[2600]	valid_set's binary_logloss: 0.22853
[2650]	valid_set's binary_logloss: 0.228539
[2700]	valid_set's binary_logloss: 0.228464
[2750]	valid_set's binary_logloss: 0.228451
[2800]	valid_set's binary_logloss: 0.228382
[2850]	valid_set's binary_logloss: 0.228377
[2900]	valid_set's binary_logloss: 0.228365
[2950]	valid_set's binary_logloss: 0.228385
[3000]	valid_set's binary_logloss: 0.228386
[3050]	valid_set's binary_logloss: 0.228335
[3100]	valid_set's binary_logloss: 0.2283
[3150]	valid_set's binary_logloss: 0.228304
[3200]	valid_set's binary_logloss: 0.228335
[3250]	valid_set's binary_logloss: 0.228345
[3300]	valid_set's binary_logloss: 0.228357
[3350]	valid_set's binary_logloss: 0.228352
[3400]	valid_set's binary_logloss: 0.228348
[3450]	valid_set's binary_logloss: 0.228326
[3500]	valid_set's binary_logloss: 0.228324
[3550]	valid_set's binary_logloss: 0.228292
[3600]	valid_set's binary_logloss: 0.228283
[3650]	valid_set's binary_logloss: 0.228279
[3700]	valid_set's binary_logloss: 0.22825
[3750]	valid_set's binary_logloss: 0.228272
[3800]	valid_set's binary_logloss: 0.228335
[3850]	valid_set's binary_logloss: 0.228308
[3900]	valid_set's binary_logloss: 0.228348
[3950]	valid_set's binary_logloss: 0.228374
[4000]	valid_set's binary_logloss: 0.228393
[4050]	valid_set's binary_logloss: 0.228417
[4100]	valid_set's binary_logloss: 0.228454
[4150]	valid_set's binary_logloss: 0.228461
[4200]	valid_set's binary_logloss: 0.228463
[4250]	valid_set's binary_logloss: 0.228502
[4300]	valid_set's binary_logloss: 0.22853
[4350]	valid_set's binary_logloss: 0.228495
[4400]	valid_set's binary_logloss: 0.228506
[4450]	valid_set's binary_logloss: 0.228516
[4500]	valid_set's binary_logloss: 0.228483
[4550]	valid_set's binary_logloss: 0.22853
[4600]	valid_set's binary_logloss: 0.228531
[4650]	valid_set's binary_logloss: 0.228555
[4700]	valid_set's binary_logloss: 0.228534
[4750]	valid_set's binary_logloss: 0.228549
[4800]	valid_set's binary_logloss: 0.228564

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.27678
[100]	valid_set's binary_logloss: 0.253701
[150]	valid_set's binary_logloss: 0.244434
[200]	valid_set's binary_logloss: 0.239818
[250]	valid_set's binary_logloss: 0.2365
[300]	valid_set's binary_logloss: 0.234212
[350]	valid_set's binary_logloss: 0.232673
[400]	valid_set's binary_logloss: 0.231418
[450]	valid_set's binary_logloss: 0.230448
[500]	valid_set's binary_logloss: 0.229729
[550]	valid_set's binary_logloss: 0.22902
[600]	valid_set's binary_logloss: 0.228452
[650]	valid_set's binary_logloss: 0.228008
[700]	valid_set's binary_logloss: 0.227592
[750]	valid_set's binary_logloss: 0.227241
[800]	valid_set's binary_logloss: 0.226777
[850]	valid_set's binary_logloss: 0.226503
[900]	valid_set's binary_logloss: 0.226309
[950]	valid_set's binary_logloss: 0.226039
[1000]	valid_set's binary_logloss: 0.225885
[1050]	valid_set's binary_logloss: 0.22573
[1100]	valid_set's binary_logloss: 0.22556
[1150]	valid_set's binary_logloss: 0.225412
[1200]	valid_set's binary_logloss: 0.225264
[1250]	valid_set's binary_logloss: 0.225114
[1300]	valid_set's binary_logloss: 0.224952
[1350]	valid_set's binary_logloss: 0.224755
[1400]	valid_set's binary_logloss: 0.224694
[1450]	valid_set's binary_logloss: 0.224618
[1500]	valid_set's binary_logloss: 0.224548
[1550]	valid_set's binary_logloss: 0.224535
[1600]	valid_set's binary_logloss: 0.224468
[1650]	valid_set's binary_logloss: 0.224414
[1700]	valid_set's binary_logloss: 0.224344
[1750]	valid_set's binary_logloss: 0.224275
[1800]	valid_set's binary_logloss: 0.224187
[1850]	valid_set's binary_logloss: 0.224119
[1900]	valid_set's binary_logloss: 0.224052
[1950]	valid_set's binary_logloss: 0.224046
[2000]	valid_set's binary_logloss: 0.223986
[2050]	valid_set's binary_logloss: 0.223899
[2100]	valid_set's binary_logloss: 0.223884
[2150]	valid_set's binary_logloss: 0.223816
[2200]	valid_set's binary_logloss: 0.223723
[2250]	valid_set's binary_logloss: 0.223663
[2300]	valid_set's binary_logloss: 0.223642
[2350]	valid_set's binary_logloss: 0.223595
[2400]	valid_set's binary_logloss: 0.223532
[2450]	valid_set's binary_logloss: 0.223541
[2500]	valid_set's binary_logloss: 0.223507
[2550]	valid_set's binary_logloss: 0.223467
[2600]	valid_set's binary_logloss: 0.223449
[2650]	valid_set's binary_logloss: 0.223419
[2700]	valid_set's binary_logloss: 0.223398
[2750]	valid_set's binary_logloss: 0.223356
[2800]	valid_set's binary_logloss: 0.223325
[2850]	valid_set's binary_logloss: 0.223287
[2900]	valid_set's binary_logloss: 0.223275
[2950]	valid_set's binary_logloss: 0.223256
[3000]	valid_set's binary_logloss: 0.223257
[3050]	valid_set's binary_logloss: 0.223276
[3100]	valid_set's binary_logloss: 0.223277
[3150]	valid_set's binary_logloss: 0.223225
[3200]	valid_set's binary_logloss: 0.223214
[3250]	valid_set's binary_logloss: 0.223159
[3300]	valid_set's binary_logloss: 0.223152
[3350]	valid_set's binary_logloss: 0.223207
[3400]	valid_set's binary_logloss: 0.223171
[3450]	valid_set's binary_logloss: 0.223198
[3500]	valid_set's binary_logloss: 0.223183
[3550]	valid_set's binary_logloss: 0.223206
[3600]	valid_set's binary_logloss: 0.223221
[3650]	valid_set's binary_logloss: 0.223181
[3700]	valid_set's binary_logloss: 0.223174
[3750]	valid_set's binary_logloss: 0.22319
[3800]	valid_set's binary_logloss: 0.223218
[3850]	valid_set's binary_logloss: 0.223211
[3900]	valid_set's binary_logloss: 0.223177
[3950]	valid_set's binary_logloss: 0.223142
[4000]	valid_set's binary_logloss: 0.223143
[4050]	valid_set's binary_logloss: 0.223149
[4100]	valid_set's binary_logloss: 0.223178
[4150]	valid_set's binary_logloss: 0.223176
[4200]	valid_set's binary_logloss: 0.223178
[4250]	valid_set's binary_logloss: 0.223206
[4300]	valid_set's binary_logloss: 0.223231
[4350]	valid_set's binary_logloss: 0.223193
[4400]	valid_set's binary_logloss: 0.223203
[4450]	valid_set's binary_logloss: 0.223202
[4500]	valid_set's binary_logloss: 0.223214
[4550]	valid_set's binary_logloss: 0.223219
[4600]	valid_set's binary_logloss: 0.223226
[4650]	valid_set's binary_logloss: 0.223196
[4700]	valid_set's binary_logloss: 0.223179
[4750]	valid_set's binary_logloss: 0.223188
[4800]	valid_set's binary_logloss: 0.22318
[4850]	valid_set's binary_logloss: 0.223199
[4900]	valid_set's binary_logloss: 0.223215
[4950]	valid_set's binary_logloss: 0.22323
[5000]	valid_set's binary_logloss: 0.223243
[5050]	valid_set's binary_logloss: 0.223228
[5100]	valid_set's binary_logloss: 0.223207
[5150]	valid_set's binary_logloss: 0.223253

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282544
[100]	valid_set's binary_logloss: 0.260518
[150]	valid_set's binary_logloss: 0.251769
[200]	valid_set's binary_logloss: 0.246821
[250]	valid_set's binary_logloss: 0.243289
[300]	valid_set's binary_logloss: 0.24101
[350]	valid_set's binary_logloss: 0.23932
[400]	valid_set's binary_logloss: 0.238069
[450]	valid_set's binary_logloss: 0.237003
[500]	valid_set's binary_logloss: 0.236289
[550]	valid_set's binary_logloss: 0.235759
[600]	valid_set's binary_logloss: 0.235177
[650]	valid_set's binary_logloss: 0.234634
[700]	valid_set's binary_logloss: 0.234321
[750]	valid_set's binary_logloss: 0.233871
[800]	valid_set's binary_logloss: 0.233564
[850]	valid_set's binary_logloss: 0.233325
[900]	valid_set's binary_logloss: 0.233062
[950]	valid_set's binary_logloss: 0.23285
[1000]	valid_set's binary_logloss: 0.232543
[1050]	valid_set's binary_logloss: 0.232361
[1100]	valid_set's binary_logloss: 0.232162
[1150]	valid_set's binary_logloss: 0.231839
[1200]	valid_set's binary_logloss: 0.231616
[1250]	valid_set's binary_logloss: 0.231441
[1300]	valid_set's binary_logloss: 0.231276
[1350]	valid_set's binary_logloss: 0.231195
[1400]	valid_set's binary_logloss: 0.231007
[1450]	valid_set's binary_logloss: 0.230855
[1500]	valid_set's binary_logloss: 0.230739
[1550]	valid_set's binary_logloss: 0.230628
[1600]	valid_set's binary_logloss: 0.230474
[1650]	valid_set's binary_logloss: 0.230325
[1700]	valid_set's binary_logloss: 0.230202
[1750]	valid_set's binary_logloss: 0.230146
[1800]	valid_set's binary_logloss: 0.230044
[1850]	valid_set's binary_logloss: 0.229942
[1900]	valid_set's binary_logloss: 0.229855
[1950]	valid_set's binary_logloss: 0.229795
[2000]	valid_set's binary_logloss: 0.22976
[2050]	valid_set's binary_logloss: 0.22969
[2100]	valid_set's binary_logloss: 0.229644
[2150]	valid_set's binary_logloss: 0.229636
[2200]	valid_set's binary_logloss: 0.229539
[2250]	valid_set's binary_logloss: 0.229438
[2300]	valid_set's binary_logloss: 0.229413
[2350]	valid_set's binary_logloss: 0.229338
[2400]	valid_set's binary_logloss: 0.229342
[2450]	valid_set's binary_logloss: 0.229337
[2500]	valid_set's binary_logloss: 0.229252
[2550]	valid_set's binary_logloss: 0.229215
[2600]	valid_set's binary_logloss: 0.229141
[2650]	valid_set's binary_logloss: 0.229073
[2700]	valid_set's binary_logloss: 0.229054
[2750]	valid_set's binary_logloss: 0.229056
[2800]	valid_set's binary_logloss: 0.229017
[2850]	valid_set's binary_logloss: 0.228988
[2900]	valid_set's binary_logloss: 0.228977
[2950]	valid_set's binary_logloss: 0.22896
[3000]	valid_set's binary_logloss: 0.228995
[3050]	valid_set's binary_logloss: 0.228955
[3100]	valid_set's binary_logloss: 0.228919
[3150]	valid_set's binary_logloss: 0.228897
[3200]	valid_set's binary_logloss: 0.228924
[3250]	valid_set's binary_logloss: 0.228954
[3300]	valid_set's binary_logloss: 0.228895
[3350]	valid_set's binary_logloss: 0.228885
[3400]	valid_set's binary_logloss: 0.22884
[3450]	valid_set's binary_logloss: 0.228848
[3500]	valid_set's binary_logloss: 0.228846
[3550]	valid_set's binary_logloss: 0.228855
[3600]	valid_set's binary_logloss: 0.228865
[3650]	valid_set's binary_logloss: 0.228864
[3700]	valid_set's binary_logloss: 0.22884
[3750]	valid_set's binary_logloss: 0.228853
[3800]	valid_set's binary_logloss: 0.228871
[3850]	valid_set's binary_logloss: 0.228862
[3900]	valid_set's binary_logloss: 0.228872
[3950]	valid_set's binary_logloss: 0.228872
[4000]	valid_set's binary_logloss: 0.228857
[4050]	valid_set's binary_logloss: 0.228868
[4100]	valid_set's binary_logloss: 0.228817
[4150]	valid_set's binary_logloss: 0.228818
[4200]	valid_set's binary_logloss: 0.228815
[4250]	valid_set's binary_logloss: 0.228827
[4300]	valid_set's binary_logloss: 0.228859
[4350]	valid_set's binary_logloss: 0.22886
[4400]	valid_set's binary_logloss: 0.228838
[4450]	valid_set's binary_logloss: 0.228881
[4500]	valid_set's binary_logloss: 0.228895
[4550]	valid_set's binary_logloss: 0.228926
[4600]	valid_set's binary_logloss: 0.228931
[4650]	valid_set's binary_logloss: 0.22898
[4700]	valid_set's binary_logloss: 0.228996
[4750]	valid_set's binary_logloss: 0.22898
[4800]	valid_set's binary_logloss: 0.229036
[4850]	valid_set's binary_logloss: 0.229016
[4900]	valid_set's binary_logloss: 0.229018
[4950]	valid_set's binary_logloss: 0.22903
[5000]	valid_set's binary_logloss: 0.229052
[5050]	valid_set's binary_logloss: 0.229071
[5100]	valid_set's binary_logloss: 0.229052
[5150]	valid_set's binary_logloss: 0.229072
[5200]	valid_set's binary_logloss: 0.229097
[5250]	valid_set's binary_logloss: 0.229099
[5300]	valid_set's binary_logloss: 0.229113
[5350]	valid_set's binary_logloss: 0.229151
[5400]	valid_set's binary_logloss: 0.229171
[5450]	valid_set's binary_logloss: 0.229179
[5500]	valid_set's binary_logloss: 0.229206

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283478
[100]	valid_set's binary_logloss: 0.258578
[150]	valid_set's binary_logloss: 0.24979
[200]	valid_set's binary_logloss: 0.2449
[250]	valid_set's binary_logloss: 0.241599
[300]	valid_set's binary_logloss: 0.239427
[350]	valid_set's binary_logloss: 0.237851
[400]	valid_set's binary_logloss: 0.236603
[450]	valid_set's binary_logloss: 0.23555
[500]	valid_set's binary_logloss: 0.234814
[550]	valid_set's binary_logloss: 0.234148
[600]	valid_set's binary_logloss: 0.233611
[650]	valid_set's binary_logloss: 0.233156
[700]	valid_set's binary_logloss: 0.232716
[750]	valid_set's binary_logloss: 0.232312
[800]	valid_set's binary_logloss: 0.231938
[850]	valid_set's binary_logloss: 0.231604
[900]	valid_set's binary_logloss: 0.231314
[950]	valid_set's binary_logloss: 0.231057
[1000]	valid_set's binary_logloss: 0.230749
[1050]	valid_set's binary_logloss: 0.230495
[1100]	valid_set's binary_logloss: 0.23028
[1150]	valid_set's binary_logloss: 0.230096
[1200]	valid_set's binary_logloss: 0.229924
[1250]	valid_set's binary_logloss: 0.229757
[1300]	valid_set's binary_logloss: 0.229559
[1350]	valid_set's binary_logloss: 0.229372
[1400]	valid_set's binary_logloss: 0.229248
[1450]	valid_set's binary_logloss: 0.229047
[1500]	valid_set's binary_logloss: 0.228927
[1550]	valid_set's binary_logloss: 0.228742
[1600]	valid_set's binary_logloss: 0.228617
[1650]	valid_set's binary_logloss: 0.228481
[1700]	valid_set's binary_logloss: 0.228371
[1750]	valid_set's binary_logloss: 0.228292
[1800]	valid_set's binary_logloss: 0.228228
[1850]	valid_set's binary_logloss: 0.228138
[1900]	valid_set's binary_logloss: 0.228064
[1950]	valid_set's binary_logloss: 0.228011
[2000]	valid_set's binary_logloss: 0.227955
[2050]	valid_set's binary_logloss: 0.227927
[2100]	valid_set's binary_logloss: 0.227863
[2150]	valid_set's binary_logloss: 0.227828
[2200]	valid_set's binary_logloss: 0.227784
[2250]	valid_set's binary_logloss: 0.227725
[2300]	valid_set's binary_logloss: 0.227679
[2350]	valid_set's binary_logloss: 0.227624
[2400]	valid_set's binary_logloss: 0.227585
[2450]	valid_set's binary_logloss: 0.22755
[2500]	valid_set's binary_logloss: 0.227509
[2550]	valid_set's binary_logloss: 0.227471
[2600]	valid_set's binary_logloss: 0.227406
[2650]	valid_set's binary_logloss: 0.227379
[2700]	valid_set's binary_logloss: 0.227314
[2750]	valid_set's binary_logloss: 0.227275
[2800]	valid_set's binary_logloss: 0.227222
[2850]	valid_set's binary_logloss: 0.227204
[2900]	valid_set's binary_logloss: 0.227189
[2950]	valid_set's binary_logloss: 0.227142
[3000]	valid_set's binary_logloss: 0.227082
[3050]	valid_set's binary_logloss: 0.22707
[3100]	valid_set's binary_logloss: 0.227073
[3150]	valid_set's binary_logloss: 0.227081
[3200]	valid_set's binary_logloss: 0.227057
[3250]	valid_set's binary_logloss: 0.227049
[3300]	valid_set's binary_logloss: 0.227015
[3350]	valid_set's binary_logloss: 0.22699
[3400]	valid_set's binary_logloss: 0.226991
[3450]	valid_set's binary_logloss: 0.226945
[3500]	valid_set's binary_logloss: 0.226944
[3550]	valid_set's binary_logloss: 0.226929
[3600]	valid_set's binary_logloss: 0.22693
[3650]	valid_set's binary_logloss: 0.226899
[3700]	valid_set's binary_logloss: 0.226911
[3750]	valid_set's binary_logloss: 0.226876
[3800]	valid_set's binary_logloss: 0.226853
[3850]	valid_set's binary_logloss: 0.226874
[3900]	valid_set's binary_logloss: 0.226837
[3950]	valid_set's binary_logloss: 0.226864
[4000]	valid_set's binary_logloss: 0.226864
[4050]	valid_set's binary_logloss: 0.226872
[4100]	valid_set's binary_logloss: 0.226836
[4150]	valid_set's binary_logloss: 0.226843
[4200]	valid_set's binary_logloss: 0.226828
[4250]	valid_set's binary_logloss: 0.226859
[4300]	valid_set's binary_logloss: 0.226884
[4350]	valid_set's binary_logloss: 0.226854
[4400]	valid_set's binary_logloss: 0.226882
[4450]	valid_set's binary_logloss: 0.226922
[4500]	valid_set's binary_logloss: 0.226975
[4550]	valid_set's binary_logloss: 0.227001
[4600]	valid_set's binary_logloss: 0.227018
[4650]	valid_set's binary_logloss: 0.22704
[4700]	valid_set's binary_logloss: 0.227062
[4750]	valid_set's binary_logloss: 0.227102
[4800]	valid_set's binary_logloss: 0.227102
[4850]	valid_set's binary_logloss: 0.227089
[4900]	valid_set's binary_logloss: 0.227112
[4950]	valid_set's binary_logloss: 0.227149
[5000]	valid_set's binary_logloss: 0.227166
[5050]	valid_set's binary_logloss: 0.227195
[5100]	valid_set's binary_logloss: 0.227227
[5150]	valid_set's binary_logloss: 0.227231
[5200]	valid_set's binary_logloss: 0.227232
[5250]	valid_set's binary_logloss: 0.227216
[5300]	valid_set's binary_logloss: 0.227182
[5350]	valid_set's binary_logloss: 0.227187
[5400]	valid_set's binary_logloss: 0.227159
[5450]	valid_set's binary_logloss: 0.227198

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281931
[100]	valid_set's binary_logloss: 0.258415
[150]	valid_set's binary_logloss: 0.248976
[200]	valid_set's binary_logloss: 0.244172
[250]	valid_set's binary_logloss: 0.241145
[300]	valid_set's binary_logloss: 0.239027
[350]	valid_set's binary_logloss: 0.237657
[400]	valid_set's binary_logloss: 0.236551
[450]	valid_set's binary_logloss: 0.235614
[500]	valid_set's binary_logloss: 0.234903
[550]	valid_set's binary_logloss: 0.234307
[600]	valid_set's binary_logloss: 0.233956
[650]	valid_set's binary_logloss: 0.233483
[700]	valid_set's binary_logloss: 0.233142
[750]	valid_set's binary_logloss: 0.232841
[800]	valid_set's binary_logloss: 0.232526
[850]	valid_set's binary_logloss: 0.232323
[900]	valid_set's binary_logloss: 0.232045
[950]	valid_set's binary_logloss: 0.23184
[1000]	valid_set's binary_logloss: 0.231581
[1050]	valid_set's binary_logloss: 0.231428
[1100]	valid_set's binary_logloss: 0.231242
[1150]	valid_set's binary_logloss: 0.231041
[1200]	valid_set's binary_logloss: 0.230888
[1250]	valid_set's binary_logloss: 0.230774
[1300]	valid_set's binary_logloss: 0.23061
[1350]	valid_set's binary_logloss: 0.230507
[1400]	valid_set's binary_logloss: 0.23038
[1450]	valid_set's binary_logloss: 0.230318
[1500]	valid_set's binary_logloss: 0.230173
[1550]	valid_set's binary_logloss: 0.230024
[1600]	valid_set's binary_logloss: 0.229961
[1650]	valid_set's binary_logloss: 0.229879
[1700]	valid_set's binary_logloss: 0.229795
[1750]	valid_set's binary_logloss: 0.229735
[1800]	valid_set's binary_logloss: 0.229701
[1850]	valid_set's binary_logloss: 0.229648
[1900]	valid_set's binary_logloss: 0.22954
[1950]	valid_set's binary_logloss: 0.229442
[2000]	valid_set's binary_logloss: 0.229363
[2050]	valid_set's binary_logloss: 0.229336
[2100]	valid_set's binary_logloss: 0.229272
[2150]	valid_set's binary_logloss: 0.229257
[2200]	valid_set's binary_logloss: 0.22923
[2250]	valid_set's binary_logloss: 0.229232
[2300]	valid_set's binary_logloss: 0.229178
[2350]	valid_set's binary_logloss: 0.229157
[2400]	valid_set's binary_logloss: 0.229099
[2450]	valid_set's binary_logloss: 0.229042
[2500]	valid_set's binary_logloss: 0.22895
[2550]	valid_set's binary_logloss: 0.228918
[2600]	valid_set's binary_logloss: 0.22889
[2650]	valid_set's binary_logloss: 0.228872
[2700]	valid_set's binary_logloss: 0.228863
[2750]	valid_set's binary_logloss: 0.228858
[2800]	valid_set's binary_logloss: 0.22886
[2850]	valid_set's binary_logloss: 0.228816
[2900]	valid_set's binary_logloss: 0.228799
[2950]	valid_set's binary_logloss: 0.228768
[3000]	valid_set's binary_logloss: 0.228752
[3050]	valid_set's binary_logloss: 0.228729
[3100]	valid_set's binary_logloss: 0.228733
[3150]	valid_set's binary_logloss: 0.228704
[3200]	valid_set's binary_logloss: 0.228731
[3250]	valid_set's binary_logloss: 0.228677
[3300]	valid_set's binary_logloss: 0.228665
[3350]	valid_set's binary_logloss: 0.22863
[3400]	valid_set's binary_logloss: 0.228642
[3450]	valid_set's binary_logloss: 0.228594
[3500]	valid_set's binary_logloss: 0.228612
[3550]	valid_set's binary_logloss: 0.228616
[3600]	valid_set's binary_logloss: 0.228576
[3650]	valid_set's binary_logloss: 0.228553
[3700]	valid_set's binary_logloss: 0.228547
[3750]	valid_set's binary_logloss: 0.228556
[3800]	valid_set's binary_logloss: 0.22852
[3850]	valid_set's binary_logloss: 0.228531
[3900]	valid_set's binary_logloss: 0.228538
[3950]	valid_set's binary_logloss: 0.228559
[4000]	valid_set's binary_logloss: 0.228548
[4050]	valid_set's binary_logloss: 0.228561
[4100]	valid_set's binary_logloss: 0.228608
[4150]	valid_set's binary_logloss: 0.22861
[4200]	valid_set's binary_logloss: 0.228581
[4250]	valid_set's binary_logloss: 0.228556
[4300]	valid_set's binary_logloss: 0.228551
[4350]	valid_set's binary_logloss: 0.228496
[4400]	valid_set's binary_logloss: 0.228459
[4450]	valid_set's binary_logloss: 0.228495
[4500]	valid_set's binary_logloss: 0.228513
[4550]	valid_set's binary_logloss: 0.228476
[4600]	valid_set's binary_logloss: 0.228489
[4650]	valid_set's binary_logloss: 0.22845
[4700]	valid_set's binary_logloss: 0.228487
[4750]	valid_set's binary_logloss: 0.22848
[4800]	valid_set's binary_logloss: 0.228506
[4850]	valid_set's binary_logloss: 0.228518
[4900]	valid_set's binary_logloss: 0.228596
[4950]	valid_set's binary_logloss: 0.228656
[5000]	valid_set's binary_logloss: 0.228704
[5050]	valid_set's binary_logloss: 0.228738
[5100]	valid_set's binary_logloss: 0.228743
[5150]	valid_set's binary_logloss: 0.228788
[5200]	valid_set's binary_logloss: 0.228825
[5250]	valid_set's binary_logloss: 0.228889
[5300]	valid_set's binary_logloss: 0.228917
[5350]	valid_set's binary_logloss: 0.228903
[5400]	valid_set's binary_logloss: 0.228913
[5450]	valid_set's binary_logloss: 0.228917
[5500]	valid_set's binary_logloss: 0.22894
[5550]	valid_set's binary_logloss: 0.228931
[5600]	valid_set's binary_logloss: 0.228971
[5650]	valid_set's binary_logloss: 0.228987
[5700]	valid_set's binary_logloss: 0.228998
[5750]	valid_set's binary_logloss: 0.229047
[5800]	valid_set's binary_logloss: 0.229072
[5850]	valid_set's binary_logloss: 0.229106
[5900]	valid_set's binary_logloss: 0.229137
[5950]	valid_set's binary_logloss: 0.22917
[6000]	valid_set's binary_logloss: 0.22923
[6050]	valid_set's binary_logloss: 0.229264

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283115
[100]	valid_set's binary_logloss: 0.258957
[150]	valid_set's binary_logloss: 0.24992
[200]	valid_set's binary_logloss: 0.245216
[250]	valid_set's binary_logloss: 0.242156
[300]	valid_set's binary_logloss: 0.240111
[350]	valid_set's binary_logloss: 0.238731
[400]	valid_set's binary_logloss: 0.237529
[450]	valid_set's binary_logloss: 0.236556
[500]	valid_set's binary_logloss: 0.235741
[550]	valid_set's binary_logloss: 0.23525
[600]	valid_set's binary_logloss: 0.234725
[650]	valid_set's binary_logloss: 0.23421
[700]	valid_set's binary_logloss: 0.233759
[750]	valid_set's binary_logloss: 0.233517
[800]	valid_set's binary_logloss: 0.233263
[850]	valid_set's binary_logloss: 0.233039
[900]	valid_set's binary_logloss: 0.232785
[950]	valid_set's binary_logloss: 0.232533
[1000]	valid_set's binary_logloss: 0.232374
[1050]	valid_set's binary_logloss: 0.232121
[1100]	valid_set's binary_logloss: 0.23198
[1150]	valid_set's binary_logloss: 0.231832
[1200]	valid_set's binary_logloss: 0.231656
[1250]	valid_set's binary_logloss: 0.231479
[1300]	valid_set's binary_logloss: 0.231361
[1350]	valid_set's binary_logloss: 0.231128
[1400]	valid_set's binary_logloss: 0.231046
[1450]	valid_set's binary_logloss: 0.230946
[1500]	valid_set's binary_logloss: 0.230908
[1550]	valid_set's binary_logloss: 0.230753
[1600]	valid_set's binary_logloss: 0.230676
[1650]	valid_set's binary_logloss: 0.230569
[1700]	valid_set's binary_logloss: 0.230503
[1750]	valid_set's binary_logloss: 0.230447
[1800]	valid_set's binary_logloss: 0.230362
[1850]	valid_set's binary_logloss: 0.230357
[1900]	valid_set's binary_logloss: 0.230252
[1950]	valid_set's binary_logloss: 0.230163
[2000]	valid_set's binary_logloss: 0.230074
[2050]	valid_set's binary_logloss: 0.230025
[2100]	valid_set's binary_logloss: 0.229977
[2150]	valid_set's binary_logloss: 0.229902
[2200]	valid_set's binary_logloss: 0.229903
[2250]	valid_set's binary_logloss: 0.229878
[2300]	valid_set's binary_logloss: 0.229813
[2350]	valid_set's binary_logloss: 0.229718
[2400]	valid_set's binary_logloss: 0.229692
[2450]	valid_set's binary_logloss: 0.229651
[2500]	valid_set's binary_logloss: 0.229688
[2550]	valid_set's binary_logloss: 0.229666
[2600]	valid_set's binary_logloss: 0.229712
[2650]	valid_set's binary_logloss: 0.229717
[2700]	valid_set's binary_logloss: 0.229715
[2750]	valid_set's binary_logloss: 0.229731
[2800]	valid_set's binary_logloss: 0.229705
[2850]	valid_set's binary_logloss: 0.229702
[2900]	valid_set's binary_logloss: 0.229702
[2950]	valid_set's binary_logloss: 0.229673
[3000]	valid_set's binary_logloss: 0.229631
[3050]	valid_set's binary_logloss: 0.229579
[3100]	valid_set's binary_logloss: 0.229598
[3150]	valid_set's binary_logloss: 0.22963
[3200]	valid_set's binary_logloss: 0.22964
[3250]	valid_set's binary_logloss: 0.229666
[3300]	valid_set's binary_logloss: 0.229705
[3350]	valid_set's binary_logloss: 0.229715
[3400]	valid_set's binary_logloss: 0.22974
[3450]	valid_set's binary_logloss: 0.229738
[3500]	valid_set's binary_logloss: 0.229702
[3550]	valid_set's binary_logloss: 0.22971
[3600]	valid_set's binary_logloss: 0.229684
[3650]	valid_set's binary_logloss: 0.229656
[3700]	valid_set's binary_logloss: 0.229709
[3750]	valid_set's binary_logloss: 0.229699
[3800]	valid_set's binary_logloss: 0.229657
[3850]	valid_set's binary_logloss: 0.229645
[3900]	valid_set's binary_logloss: 0.22966
[3950]	valid_set's binary_logloss: 0.229678

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.280769
[100]	valid_set's binary_logloss: 0.257112
[150]	valid_set's binary_logloss: 0.247431
[200]	valid_set's binary_logloss: 0.242273
[250]	valid_set's binary_logloss: 0.239033
[300]	valid_set's binary_logloss: 0.236552
[350]	valid_set's binary_logloss: 0.234891
[400]	valid_set's binary_logloss: 0.233553
[450]	valid_set's binary_logloss: 0.232724
[500]	valid_set's binary_logloss: 0.231885
[550]	valid_set's binary_logloss: 0.231215
[600]	valid_set's binary_logloss: 0.230714
[650]	valid_set's binary_logloss: 0.230266
[700]	valid_set's binary_logloss: 0.229993
[750]	valid_set's binary_logloss: 0.229676
[800]	valid_set's binary_logloss: 0.229341
[850]	valid_set's binary_logloss: 0.229018
[900]	valid_set's binary_logloss: 0.228744
[950]	valid_set's binary_logloss: 0.228566
[1000]	valid_set's binary_logloss: 0.228313
[1050]	valid_set's binary_logloss: 0.228104
[1100]	valid_set's binary_logloss: 0.227949
[1150]	valid_set's binary_logloss: 0.22781
[1200]	valid_set's binary_logloss: 0.227672
[1250]	valid_set's binary_logloss: 0.227543
[1300]	valid_set's binary_logloss: 0.227388
[1350]	valid_set's binary_logloss: 0.227218
[1400]	valid_set's binary_logloss: 0.227073
[1450]	valid_set's binary_logloss: 0.226916
[1500]	valid_set's binary_logloss: 0.226811
[1550]	valid_set's binary_logloss: 0.226735
[1600]	valid_set's binary_logloss: 0.226699
[1650]	valid_set's binary_logloss: 0.22663
[1700]	valid_set's binary_logloss: 0.226534
[1750]	valid_set's binary_logloss: 0.226487
[1800]	valid_set's binary_logloss: 0.226422
[1850]	valid_set's binary_logloss: 0.226359
[1900]	valid_set's binary_logloss: 0.226313
[1950]	valid_set's binary_logloss: 0.226244
[2000]	valid_set's binary_logloss: 0.22617
[2050]	valid_set's binary_logloss: 0.22617
[2100]	valid_set's binary_logloss: 0.226089
[2150]	valid_set's binary_logloss: 0.226062
[2200]	valid_set's binary_logloss: 0.225972
[2250]	valid_set's binary_logloss: 0.225972
[2300]	valid_set's binary_logloss: 0.225902
[2350]	valid_set's binary_logloss: 0.225883
[2400]	valid_set's binary_logloss: 0.22578
[2450]	valid_set's binary_logloss: 0.225781
[2500]	valid_set's binary_logloss: 0.225748
[2550]	valid_set's binary_logloss: 0.225692
[2600]	valid_set's binary_logloss: 0.225618
[2650]	valid_set's binary_logloss: 0.225607
[2700]	valid_set's binary_logloss: 0.225572
[2750]	valid_set's binary_logloss: 0.225548
[2800]	valid_set's binary_logloss: 0.225522
[2850]	valid_set's binary_logloss: 0.225486
[2900]	valid_set's binary_logloss: 0.225469
[2950]	valid_set's binary_logloss: 0.225394
[3000]	valid_set's binary_logloss: 0.225361
[3050]	valid_set's binary_logloss: 0.225369
[3100]	valid_set's binary_logloss: 0.22531
[3150]	valid_set's binary_logloss: 0.225294
[3200]	valid_set's binary_logloss: 0.225303
[3250]	valid_set's binary_logloss: 0.225303
[3300]	valid_set's binary_logloss: 0.225317
[3350]	valid_set's binary_logloss: 0.225349
[3400]	valid_set's binary_logloss: 0.225312
[3450]	valid_set's binary_logloss: 0.22529
[3500]	valid_set's binary_logloss: 0.22531
[3550]	valid_set's binary_logloss: 0.225325
[3600]	valid_set's binary_logloss: 0.225324
[3650]	valid_set's binary_logloss: 0.225336
[3700]	valid_set's binary_logloss: 0.225356
[3750]	valid_set's binary_logloss: 0.225305
[3800]	valid_set's binary_logloss: 0.225279
[3850]	valid_set's binary_logloss: 0.225277
[3900]	valid_set's binary_logloss: 0.225292
[3950]	valid_set's binary_logloss: 0.225281
[4000]	valid_set's binary_logloss: 0.22531
[4050]	valid_set's binary_logloss: 0.225325
[4100]	valid_set's binary_logloss: 0.225359
[4150]	valid_set's binary_logloss: 0.225391
[4200]	valid_set's binary_logloss: 0.225375
[4250]	valid_set's binary_logloss: 0.225367
[4300]	valid_set's binary_logloss: 0.225395
[4350]	valid_set's binary_logloss: 0.225372
[4400]	valid_set's binary_logloss: 0.225378
[4450]	valid_set's binary_logloss: 0.22539
[4500]	valid_set's binary_logloss: 0.225426
[4550]	valid_set's binary_logloss: 0.225445
[4600]	valid_set's binary_logloss: 0.225425
[4650]	valid_set's binary_logloss: 0.225403
[4700]	valid_set's binary_logloss: 0.225429
[4750]	valid_set's binary_logloss: 0.225424
[4800]	valid_set's binary_logloss: 0.225446
[4850]	valid_set's binary_logloss: 0.225445
[4900]	valid_set's binary_logloss: 0.225467
[4950]	valid_set's binary_logloss: 0.225467

Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\model.pkl
	0.9481	 = Validation score   (roc_auc)
	139.56s	 = Training   runtime
	6.76s	 = Validation runtime
	8121.2	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1539.61s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/4.9 GB
Ensemble size: 7
Ensemble weights:
[0.57142857 0.42857143]
	0.35s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBM_BAG_L1': 0.571, 'LightGBMLarge_BAG_L1': 0.429}
	0.9492	 = Validation score   (roc_auc)
	2.03s	 = Training   runtime
	0.04s	 = Validation runtime
	4950.0	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
AutoGluon training complete, total runtime = 262.57s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4950.0 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\GBM")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       5.00 GB / 15.06 GB (33.2%)
Disk Space Avail:   708.05 GB / 930.47 GB (76.1%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\XGB"
Train Data Rows:    439140
Train Data Columns: 56
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0

GBM completed.
Validation ROC-AUC: 0.949192

================================================================================
TRAINING: XGB
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\XGB
================================================================================

Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5091.07 MB
	Train Data (Original)  Memory Usage: 232.70 MB (4.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.2s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.0s = Fit runtime
			45 features in original data used to generate 45 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			41 features in original data used to generate 41 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.1s = Fit runtime
	41 features in original data used to generate 41 features in processed data.
	Train Data (Processed) Memory Usage: 125.64 MB (2.5% of available memory)
Data preprocessing and feature engineering runtime = 1.18s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\utils\data\y.pkl
Model configs that will be trained (in order):
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1798.82s of the 1798.82s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45847
[50]	validation_0-logloss:0.25324
[100]	validation_0-logloss:0.24212
[150]	validation_0-logloss:0.23788
[200]	validation_0-logloss:0.23504
[250]	validation_0-logloss:0.23353
[300]	validation_0-logloss:0.23194
[350]	validation_0-logloss:0.23099
[400]	validation_0-logloss:0.23036
[450]	validation_0-logloss:0.22989
[500]	validation_0-logloss:0.22930
[550]	validation_0-logloss:0.22908
[600]	validation_0-logloss:0.22891
[650]	validation_0-logloss:0.22886
[700]	validation_0-logloss:0.22871
[750]	validation_0-logloss:0.22859
[800]	validation_0-logloss:0.22856
[850]	validation_0-logloss:0.22861
[900]	validation_0-logloss:0.22865
[950]	validation_0-logloss:0.22868
[1000]	validation_0-logloss:0.22882
[1050]	validation_0-logloss:0.22883
[1055]	validation_0-logloss:0.22884

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45866
[50]	validation_0-logloss:0.25464
[100]	validation_0-logloss:0.24242
[150]	validation_0-logloss:0.23794
[200]	validation_0-logloss:0.23483
[250]	validation_0-logloss:0.23278
[300]	validation_0-logloss:0.23130
[350]	validation_0-logloss:0.23028
[400]	validation_0-logloss:0.22940
[450]	validation_0-logloss:0.22879
[500]	validation_0-logloss:0.22810
[550]	validation_0-logloss:0.22793
[600]	validation_0-logloss:0.22775
[650]	validation_0-logloss:0.22773
[700]	validation_0-logloss:0.22766
[750]	validation_0-logloss:0.22763
[800]	validation_0-logloss:0.22762
[850]	validation_0-logloss:0.22768
[900]	validation_0-logloss:0.22773
[903]	validation_0-logloss:0.22773

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45774
[50]	validation_0-logloss:0.24884
[100]	validation_0-logloss:0.23630
[150]	validation_0-logloss:0.23180
[200]	validation_0-logloss:0.22905
[250]	validation_0-logloss:0.22711
[300]	validation_0-logloss:0.22544
[350]	validation_0-logloss:0.22457
[400]	validation_0-logloss:0.22373
[450]	validation_0-logloss:0.22320
[500]	validation_0-logloss:0.22285
[550]	validation_0-logloss:0.22256
[600]	validation_0-logloss:0.22227
[650]	validation_0-logloss:0.22211
[700]	validation_0-logloss:0.22204
[750]	validation_0-logloss:0.22192
[800]	validation_0-logloss:0.22192
[850]	validation_0-logloss:0.22181
[900]	validation_0-logloss:0.22170
[950]	validation_0-logloss:0.22177
[1000]	validation_0-logloss:0.22177
[1050]	validation_0-logloss:0.22179
[1100]	validation_0-logloss:0.22182
[1150]	validation_0-logloss:0.22193
[1197]	validation_0-logloss:0.22197

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45860
[50]	validation_0-logloss:0.25480
[100]	validation_0-logloss:0.24346
[150]	validation_0-logloss:0.23891
[200]	validation_0-logloss:0.23609
[250]	validation_0-logloss:0.23445
[300]	validation_0-logloss:0.23284
[350]	validation_0-logloss:0.23158
[400]	validation_0-logloss:0.23096
[450]	validation_0-logloss:0.23023
[500]	validation_0-logloss:0.22987
[550]	validation_0-logloss:0.22956
[600]	validation_0-logloss:0.22938
[650]	validation_0-logloss:0.22895
[700]	validation_0-logloss:0.22878
[750]	validation_0-logloss:0.22865
[800]	validation_0-logloss:0.22846
[850]	validation_0-logloss:0.22856
[900]	validation_0-logloss:0.22863
[950]	validation_0-logloss:0.22864
[1000]	validation_0-logloss:0.22871
[1050]	validation_0-logloss:0.22861
[1061]	validation_0-logloss:0.22861

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45856
[50]	validation_0-logloss:0.25287
[100]	validation_0-logloss:0.24166
[150]	validation_0-logloss:0.23716
[200]	validation_0-logloss:0.23433
[250]	validation_0-logloss:0.23245
[300]	validation_0-logloss:0.23117
[350]	validation_0-logloss:0.23018
[400]	validation_0-logloss:0.22943
[450]	validation_0-logloss:0.22875
[500]	validation_0-logloss:0.22820
[550]	validation_0-logloss:0.22777
[600]	validation_0-logloss:0.22747
[650]	validation_0-logloss:0.22712
[700]	validation_0-logloss:0.22699
[750]	validation_0-logloss:0.22693
[800]	validation_0-logloss:0.22694
[850]	validation_0-logloss:0.22695
[900]	validation_0-logloss:0.22695
[950]	validation_0-logloss:0.22696
[1000]	validation_0-logloss:0.22700
[1050]	validation_0-logloss:0.22689
[1100]	validation_0-logloss:0.22699
[1150]	validation_0-logloss:0.22711
[1200]	validation_0-logloss:0.22712
[1203]	validation_0-logloss:0.22714

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45843
[50]	validation_0-logloss:0.25545
[100]	validation_0-logloss:0.24372
[150]	validation_0-logloss:0.23900
[200]	validation_0-logloss:0.23610
[250]	validation_0-logloss:0.23415
[300]	validation_0-logloss:0.23281
[350]	validation_0-logloss:0.23189
[400]	validation_0-logloss:0.23114
[450]	validation_0-logloss:0.23060
[500]	validation_0-logloss:0.23021
[550]	validation_0-logloss:0.23007
[600]	validation_0-logloss:0.22982
[650]	validation_0-logloss:0.22979
[700]	validation_0-logloss:0.22974
[750]	validation_0-logloss:0.22969
[800]	validation_0-logloss:0.22974
[850]	validation_0-logloss:0.22973
[900]	validation_0-logloss:0.22972
[950]	validation_0-logloss:0.22968
[968]	validation_0-logloss:0.22966

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45862
[50]	validation_0-logloss:0.25472
[100]	validation_0-logloss:0.24331
[150]	validation_0-logloss:0.23890
[200]	validation_0-logloss:0.23596
[250]	validation_0-logloss:0.23394
[300]	validation_0-logloss:0.23273
[350]	validation_0-logloss:0.23175
[400]	validation_0-logloss:0.23110
[450]	validation_0-logloss:0.23053
[500]	validation_0-logloss:0.23027
[550]	validation_0-logloss:0.22984
[600]	validation_0-logloss:0.22961
[650]	validation_0-logloss:0.22940
[700]	validation_0-logloss:0.22931
[750]	validation_0-logloss:0.22924
[800]	validation_0-logloss:0.22919
[850]	validation_0-logloss:0.22913
[900]	validation_0-logloss:0.22919
[950]	validation_0-logloss:0.22914
[1000]	validation_0-logloss:0.22920
[1050]	validation_0-logloss:0.22934
[1100]	validation_0-logloss:0.22934
[1150]	validation_0-logloss:0.22942
[1154]	validation_0-logloss:0.22943

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45808
[50]	validation_0-logloss:0.25168
[100]	validation_0-logloss:0.24039
[150]	validation_0-logloss:0.23530
[200]	validation_0-logloss:0.23248
[250]	validation_0-logloss:0.23029
[300]	validation_0-logloss:0.22906
[350]	validation_0-logloss:0.22779
[400]	validation_0-logloss:0.22689
[450]	validation_0-logloss:0.22644
[500]	validation_0-logloss:0.22601
[550]	validation_0-logloss:0.22580
[600]	validation_0-logloss:0.22550
[650]	validation_0-logloss:0.22535
[700]	validation_0-logloss:0.22523
[750]	validation_0-logloss:0.22516
[800]	validation_0-logloss:0.22519
[850]	validation_0-logloss:0.22523
[900]	validation_0-logloss:0.22524
[950]	validation_0-logloss:0.22513
[1000]	validation_0-logloss:0.22502
[1050]	validation_0-logloss:0.22508
[1100]	validation_0-logloss:0.22512
[1150]	validation_0-logloss:0.22519
[1200]	validation_0-logloss:0.22540
[1250]	validation_0-logloss:0.22539
[1300]	validation_0-logloss:0.22540
[1329]	validation_0-logloss:0.22552

Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\model.pkl
	0.9483	 = Validation score   (roc_auc)
	125.7s	 = Training   runtime
	1.5s	 = Validation runtime
	36566.2	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1671.01s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/4.8 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.23s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.9483	 = Validation score   (roc_auc)
	0.05s	 = Training   runtime
	0.04s	 = Validation runtime
	36445.1	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
AutoGluon training complete, total runtime = 129.2s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 36445.1 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\XGB")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.88 GB / 15.06 GB (32.4%)
Disk Space Avail:   707.87 GB / 930.47 GB (76.1%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\CAT"
Train Data Rows:    439140
Train Data Columns: 56
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...

XGB completed.
Validation ROC-AUC: 0.948277

================================================================================
TRAINING: CAT
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\CAT
================================================================================

Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5026.57 MB
	Train Data (Original)  Memory Usage: 232.70 MB (4.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 24 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.0s = Fit runtime
			45 features in original data used to generate 45 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 21 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			47 features in original data used to generate 47 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			41 features in original data used to generate 41 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 19 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 17 | ['Year', 'LapNumber', 'Stint', 'Position', 'LapNumber_digit_units', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.0s = Fit runtime
	41 features in original data used to generate 41 features in processed data.
	Train Data (Processed) Memory Usage: 125.64 MB (2.5% of available memory)
Data preprocessing and feature engineering runtime = 1.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
User-specified model hyperparameters to be fit:
{
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\utils\data\y.pkl
Model configs that will be trained (in order):
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1798.89s of the 1798.89s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6321233	test: 0.6320408	best: 0.6320408 (0)	total: 15.2ms	remaining: 15.2ms
1:	learn: 0.5793019	test: 0.5791839	best: 0.5791839 (1)	total: 23.9ms	remaining: 0us
bestTest = 0.5791839138
bestIteration = 1
0:	learn: 0.6301786	test: 0.6301059	best: 0.6301059 (0)	total: 15.9ms	remaining: 4.81s
20:	learn: 0.3176444	test: 0.3182634	best: 0.3182634 (20)	total: 317ms	remaining: 4.26s
40:	learn: 0.2879376	test: 0.2885930	best: 0.2885930 (40)	total: 620ms	remaining: 3.96s
60:	learn: 0.2769229	test: 0.2775798	best: 0.2775798 (60)	total: 920ms	remaining: 3.65s
80:	learn: 0.2699528	test: 0.2706216	best: 0.2706216 (80)	total: 1.22s	remaining: 3.35s
100:	learn: 0.2652591	test: 0.2661987	best: 0.2661987 (100)	total: 1.53s	remaining: 3.05s
120:	learn: 0.2617833	test: 0.2629009	best: 0.2629009 (120)	total: 1.83s	remaining: 2.75s
140:	learn: 0.2587757	test: 0.2601570	best: 0.2601570 (140)	total: 2.12s	remaining: 2.44s
160:	learn: 0.2561894	test: 0.2577028	best: 0.2577028 (160)	total: 2.43s	remaining: 2.15s
180:	learn: 0.2540497	test: 0.2557228	best: 0.2557228 (180)	total: 2.73s	remaining: 1.84s
200:	learn: 0.2521977	test: 0.2540347	best: 0.2540347 (200)	total: 3.03s	remaining: 1.54s
220:	learn: 0.2505495	test: 0.2525685	best: 0.2525685 (220)	total: 3.33s	remaining: 1.24s
240:	learn: 0.2490175	test: 0.2512007	best: 0.2512007 (240)	total: 3.64s	remaining: 936ms
260:	learn: 0.2476414	test: 0.2499768	best: 0.2499768 (260)	total: 3.94s	remaining: 634ms
280:	learn: 0.2461714	test: 0.2486819	best: 0.2486819 (280)	total: 4.24s	remaining: 332ms
300:	learn: 0.2450334	test: 0.2477540	best: 0.2477540 (300)	total: 4.55s	remaining: 30.2ms
302:	learn: 0.2448958	test: 0.2476348	best: 0.2476348 (302)	total: 4.58s	remaining: 0us
bestTest = 0.2476347629
bestIteration = 302

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6323074	test: 0.6322357	best: 0.6322357 (0)	total: 8.84ms	remaining: 8.84ms
1:	learn: 0.5797368	test: 0.5796204	best: 0.5796204 (1)	total: 17.3ms	remaining: 0us
bestTest = 0.5796204164
bestIteration = 1
0:	learn: 0.6303236	test: 0.6302580	best: 0.6302580 (0)	total: 14.7ms	remaining: 10.1s
20:	learn: 0.3176735	test: 0.3184782	best: 0.3184782 (20)	total: 311ms	remaining: 9.85s
40:	learn: 0.2878574	test: 0.2891940	best: 0.2891940 (40)	total: 609ms	remaining: 9.58s
60:	learn: 0.2761755	test: 0.2776218	best: 0.2776218 (60)	total: 911ms	remaining: 9.34s
80:	learn: 0.2699994	test: 0.2715578	best: 0.2715578 (80)	total: 1.23s	remaining: 9.15s
100:	learn: 0.2654752	test: 0.2671451	best: 0.2671451 (100)	total: 1.52s	remaining: 8.83s
120:	learn: 0.2623753	test: 0.2641372	best: 0.2641372 (120)	total: 1.82s	remaining: 8.53s
140:	learn: 0.2593708	test: 0.2611487	best: 0.2611487 (140)	total: 2.12s	remaining: 8.21s
160:	learn: 0.2568962	test: 0.2587743	best: 0.2587743 (160)	total: 2.42s	remaining: 7.9s
180:	learn: 0.2545324	test: 0.2564534	best: 0.2564534 (180)	total: 2.72s	remaining: 7.58s
200:	learn: 0.2527721	test: 0.2547892	best: 0.2547892 (200)	total: 3.01s	remaining: 7.27s
220:	learn: 0.2509391	test: 0.2530849	best: 0.2530849 (220)	total: 3.31s	remaining: 6.97s
240:	learn: 0.2492075	test: 0.2514452	best: 0.2514452 (240)	total: 3.63s	remaining: 6.7s
260:	learn: 0.2478583	test: 0.2502237	best: 0.2502237 (260)	total: 3.92s	remaining: 6.39s
280:	learn: 0.2464204	test: 0.2488226	best: 0.2488226 (280)	total: 4.22s	remaining: 6.09s
300:	learn: 0.2452031	test: 0.2477114	best: 0.2477114 (300)	total: 4.52s	remaining: 5.78s
320:	learn: 0.2442075	test: 0.2467652	best: 0.2467652 (320)	total: 4.82s	remaining: 5.47s
340:	learn: 0.2431950	test: 0.2458529	best: 0.2458529 (340)	total: 5.12s	remaining: 5.18s
360:	learn: 0.2421234	test: 0.2448583	best: 0.2448583 (360)	total: 5.41s	remaining: 4.87s
380:	learn: 0.2412876	test: 0.2441329	best: 0.2441329 (380)	total: 5.71s	remaining: 4.57s
400:	learn: 0.2405056	test: 0.2434792	best: 0.2434792 (400)	total: 6.01s	remaining: 4.27s
420:	learn: 0.2396366	test: 0.2427182	best: 0.2427182 (420)	total: 6.31s	remaining: 3.97s
440:	learn: 0.2389867	test: 0.2421947	best: 0.2421947 (440)	total: 6.6s	remaining: 3.67s
460:	learn: 0.2383005	test: 0.2416442	best: 0.2416442 (460)	total: 6.91s	remaining: 3.37s
480:	learn: 0.2376649	test: 0.2411717	best: 0.2411717 (480)	total: 7.21s	remaining: 3.07s
500:	learn: 0.2369791	test: 0.2405888	best: 0.2405888 (500)	total: 7.51s	remaining: 2.77s
520:	learn: 0.2364599	test: 0.2402256	best: 0.2402256 (520)	total: 7.81s	remaining: 2.47s
540:	learn: 0.2358965	test: 0.2397684	best: 0.2397684 (540)	total: 8.12s	remaining: 2.18s
560:	learn: 0.2352199	test: 0.2392568	best: 0.2392568 (560)	total: 8.42s	remaining: 1.88s
580:	learn: 0.2346958	test: 0.2388837	best: 0.2388837 (580)	total: 8.72s	remaining: 1.58s
600:	learn: 0.2342571	test: 0.2385358	best: 0.2385358 (600)	total: 9.03s	remaining: 1.28s
620:	learn: 0.2338255	test: 0.2382540	best: 0.2382540 (620)	total: 9.32s	remaining: 976ms
640:	learn: 0.2333663	test: 0.2379432	best: 0.2379432 (640)	total: 9.62s	remaining: 675ms
660:	learn: 0.2329338	test: 0.2376530	best: 0.2376530 (660)	total: 9.92s	remaining: 375ms
680:	learn: 0.2325060	test: 0.2373636	best: 0.2373636 (680)	total: 10.2s	remaining: 75ms
685:	learn: 0.2323847	test: 0.2372996	best: 0.2372975 (684)	total: 10.3s	remaining: 0us
bestTest = 0.2372975358
bestIteration = 684
Shrink model to first 685 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6324951	test: 0.6318864	best: 0.6318864 (0)	total: 9.35ms	remaining: 9.35ms
1:	learn: 0.5799800	test: 0.5788566	best: 0.5788566 (1)	total: 17.7ms	remaining: 0us
bestTest = 0.5788565724
bestIteration = 1
0:	learn: 0.6305817	test: 0.6299985	best: 0.6299985 (0)	total: 14.7ms	remaining: 11.5s
20:	learn: 0.3198292	test: 0.3150951	best: 0.3150951 (20)	total: 311ms	remaining: 11.3s
40:	learn: 0.2883621	test: 0.2827534	best: 0.2827534 (40)	total: 608ms	remaining: 11s
60:	learn: 0.2771123	test: 0.2714717	best: 0.2714717 (60)	total: 910ms	remaining: 10.8s
80:	learn: 0.2706589	test: 0.2651423	best: 0.2651423 (80)	total: 1.21s	remaining: 10.5s
100:	learn: 0.2663180	test: 0.2610211	best: 0.2610211 (100)	total: 1.5s	remaining: 10.2s
120:	learn: 0.2630330	test: 0.2579242	best: 0.2579242 (120)	total: 1.82s	remaining: 9.97s
140:	learn: 0.2605314	test: 0.2556283	best: 0.2556283 (140)	total: 2.12s	remaining: 9.66s
160:	learn: 0.2574080	test: 0.2526649	best: 0.2526649 (160)	total: 2.41s	remaining: 9.35s
180:	learn: 0.2551183	test: 0.2505532	best: 0.2505532 (180)	total: 2.72s	remaining: 9.07s
200:	learn: 0.2532604	test: 0.2489302	best: 0.2489302 (200)	total: 3.02s	remaining: 8.78s
220:	learn: 0.2513573	test: 0.2471533	best: 0.2471533 (220)	total: 3.32s	remaining: 8.48s
240:	learn: 0.2497976	test: 0.2457436	best: 0.2457436 (240)	total: 3.62s	remaining: 8.18s
260:	learn: 0.2483745	test: 0.2444458	best: 0.2444458 (260)	total: 3.92s	remaining: 7.88s
280:	learn: 0.2471836	test: 0.2433835	best: 0.2433835 (280)	total: 4.22s	remaining: 7.57s
300:	learn: 0.2460764	test: 0.2424406	best: 0.2424406 (300)	total: 4.52s	remaining: 7.27s
320:	learn: 0.2448835	test: 0.2414395	best: 0.2414395 (320)	total: 4.83s	remaining: 6.98s
340:	learn: 0.2438073	test: 0.2405050	best: 0.2405050 (340)	total: 5.13s	remaining: 6.68s
360:	learn: 0.2428427	test: 0.2396838	best: 0.2396838 (360)	total: 5.44s	remaining: 6.38s
380:	learn: 0.2419208	test: 0.2389304	best: 0.2389304 (380)	total: 5.74s	remaining: 6.09s
400:	learn: 0.2410858	test: 0.2382789	best: 0.2382789 (400)	total: 6.04s	remaining: 5.78s
420:	learn: 0.2402292	test: 0.2375593	best: 0.2375593 (420)	total: 6.34s	remaining: 5.48s
440:	learn: 0.2394972	test: 0.2369601	best: 0.2369601 (440)	total: 6.66s	remaining: 5.19s
460:	learn: 0.2389122	test: 0.2365617	best: 0.2365617 (460)	total: 6.96s	remaining: 4.89s
480:	learn: 0.2382993	test: 0.2360714	best: 0.2360714 (480)	total: 7.25s	remaining: 4.58s
500:	learn: 0.2376149	test: 0.2355799	best: 0.2355799 (500)	total: 7.55s	remaining: 4.28s
520:	learn: 0.2369851	test: 0.2351070	best: 0.2351070 (520)	total: 7.85s	remaining: 3.98s
540:	learn: 0.2364431	test: 0.2347156	best: 0.2347156 (540)	total: 8.14s	remaining: 3.67s
560:	learn: 0.2359701	test: 0.2344407	best: 0.2344407 (560)	total: 8.44s	remaining: 3.37s
580:	learn: 0.2354100	test: 0.2340098	best: 0.2340098 (580)	total: 8.75s	remaining: 3.07s
600:	learn: 0.2348719	test: 0.2335950	best: 0.2335950 (600)	total: 9.05s	remaining: 2.77s
620:	learn: 0.2343701	test: 0.2332751	best: 0.2332751 (620)	total: 9.35s	remaining: 2.47s
640:	learn: 0.2337571	test: 0.2328059	best: 0.2328059 (640)	total: 9.65s	remaining: 2.17s
660:	learn: 0.2333133	test: 0.2325332	best: 0.2325332 (660)	total: 9.94s	remaining: 1.86s
680:	learn: 0.2329098	test: 0.2322843	best: 0.2322843 (680)	total: 10.2s	remaining: 1.56s
700:	learn: 0.2325149	test: 0.2320755	best: 0.2320755 (700)	total: 10.5s	remaining: 1.26s
720:	learn: 0.2321508	test: 0.2318612	best: 0.2318612 (720)	total: 10.8s	remaining: 962ms
740:	learn: 0.2316902	test: 0.2315573	best: 0.2315573 (740)	total: 11.1s	remaining: 661ms
760:	learn: 0.2313049	test: 0.2313327	best: 0.2313327 (760)	total: 11.4s	remaining: 360ms
780:	learn: 0.2309449	test: 0.2311040	best: 0.2311040 (780)	total: 11.7s	remaining: 60ms
784:	learn: 0.2308836	test: 0.2310796	best: 0.2310796 (784)	total: 11.8s	remaining: 0us
bestTest = 0.231079633
bestIteration = 784

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6320987	test: 0.6323856	best: 0.6323856 (0)	total: 9.08ms	remaining: 9.08ms
1:	learn: 0.5794652	test: 0.5799452	best: 0.5799452 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.5799451959
bestIteration = 1
0:	learn: 0.6302194	test: 0.6305141	best: 0.6305141 (0)	total: 15.2ms	remaining: 14.3s
20:	learn: 0.3194244	test: 0.3211350	best: 0.3211350 (20)	total: 314ms	remaining: 13.7s
40:	learn: 0.2874128	test: 0.2892580	best: 0.2892580 (40)	total: 612ms	remaining: 13.4s
60:	learn: 0.2761220	test: 0.2781996	best: 0.2781996 (60)	total: 911ms	remaining: 13.1s
80:	learn: 0.2694419	test: 0.2716746	best: 0.2716746 (80)	total: 1.21s	remaining: 12.8s
100:	learn: 0.2651907	test: 0.2675754	best: 0.2675754 (100)	total: 1.53s	remaining: 12.7s
120:	learn: 0.2617879	test: 0.2642724	best: 0.2642724 (120)	total: 1.84s	remaining: 12.4s
140:	learn: 0.2585554	test: 0.2611029	best: 0.2611029 (140)	total: 2.14s	remaining: 12.1s
160:	learn: 0.2559081	test: 0.2586316	best: 0.2586316 (160)	total: 2.44s	remaining: 11.8s
180:	learn: 0.2537238	test: 0.2566319	best: 0.2566319 (180)	total: 2.73s	remaining: 11.4s
200:	learn: 0.2519686	test: 0.2550166	best: 0.2550166 (200)	total: 3.03s	remaining: 11.1s
220:	learn: 0.2500205	test: 0.2531844	best: 0.2531844 (220)	total: 3.33s	remaining: 10.8s
240:	learn: 0.2484902	test: 0.2517966	best: 0.2517966 (240)	total: 3.63s	remaining: 10.5s
260:	learn: 0.2471767	test: 0.2506241	best: 0.2506241 (260)	total: 3.93s	remaining: 10.2s
280:	learn: 0.2459579	test: 0.2495525	best: 0.2495525 (280)	total: 4.24s	remaining: 9.93s
300:	learn: 0.2448572	test: 0.2486244	best: 0.2486244 (300)	total: 4.54s	remaining: 9.62s
320:	learn: 0.2437185	test: 0.2476306	best: 0.2476306 (320)	total: 4.84s	remaining: 9.32s
340:	learn: 0.2427345	test: 0.2468059	best: 0.2468059 (340)	total: 5.14s	remaining: 9.02s
360:	learn: 0.2418509	test: 0.2461048	best: 0.2461048 (360)	total: 5.44s	remaining: 8.72s
380:	learn: 0.2409672	test: 0.2453687	best: 0.2453687 (380)	total: 5.74s	remaining: 8.41s
400:	learn: 0.2401930	test: 0.2447644	best: 0.2447644 (400)	total: 6.04s	remaining: 8.11s
420:	learn: 0.2394081	test: 0.2441259	best: 0.2441259 (420)	total: 6.34s	remaining: 7.8s
440:	learn: 0.2386324	test: 0.2435257	best: 0.2435257 (440)	total: 6.65s	remaining: 7.51s
460:	learn: 0.2379376	test: 0.2430282	best: 0.2430282 (460)	total: 6.95s	remaining: 7.2s
480:	learn: 0.2373111	test: 0.2425659	best: 0.2425659 (480)	total: 7.24s	remaining: 6.89s
500:	learn: 0.2366655	test: 0.2420548	best: 0.2420548 (500)	total: 7.54s	remaining: 6.59s
520:	learn: 0.2360961	test: 0.2416505	best: 0.2416505 (520)	total: 7.84s	remaining: 6.29s
540:	learn: 0.2355320	test: 0.2412583	best: 0.2412583 (540)	total: 8.14s	remaining: 5.99s
560:	learn: 0.2349936	test: 0.2408639	best: 0.2408639 (560)	total: 8.44s	remaining: 5.69s
580:	learn: 0.2344864	test: 0.2404927	best: 0.2404927 (580)	total: 8.75s	remaining: 5.39s
600:	learn: 0.2340083	test: 0.2402078	best: 0.2402078 (600)	total: 9.05s	remaining: 5.09s
620:	learn: 0.2335785	test: 0.2399740	best: 0.2399740 (620)	total: 9.34s	remaining: 4.78s
640:	learn: 0.2331365	test: 0.2396934	best: 0.2396934 (640)	total: 9.64s	remaining: 4.48s
660:	learn: 0.2326410	test: 0.2393419	best: 0.2393419 (660)	total: 9.94s	remaining: 4.18s
680:	learn: 0.2322263	test: 0.2391134	best: 0.2391134 (680)	total: 10.2s	remaining: 3.88s
700:	learn: 0.2317920	test: 0.2388807	best: 0.2388807 (700)	total: 10.5s	remaining: 3.58s
720:	learn: 0.2313724	test: 0.2386197	best: 0.2386197 (720)	total: 10.8s	remaining: 3.27s
740:	learn: 0.2309302	test: 0.2383327	best: 0.2383327 (740)	total: 11.1s	remaining: 2.97s
760:	learn: 0.2304928	test: 0.2380495	best: 0.2380495 (760)	total: 11.4s	remaining: 2.67s
780:	learn: 0.2301393	test: 0.2378534	best: 0.2378534 (780)	total: 11.7s	remaining: 2.37s
800:	learn: 0.2298228	test: 0.2377256	best: 0.2377256 (800)	total: 12s	remaining: 2.07s
820:	learn: 0.2294161	test: 0.2374996	best: 0.2374996 (820)	total: 12.3s	remaining: 1.77s
840:	learn: 0.2291124	test: 0.2373674	best: 0.2373674 (840)	total: 12.6s	remaining: 1.47s
860:	learn: 0.2287181	test: 0.2371985	best: 0.2371985 (860)	total: 12.9s	remaining: 1.17s
880:	learn: 0.2283784	test: 0.2370236	best: 0.2370236 (880)	total: 13.2s	remaining: 869ms
900:	learn: 0.2280345	test: 0.2368284	best: 0.2368284 (900)	total: 13.5s	remaining: 569ms
920:	learn: 0.2277257	test: 0.2366731	best: 0.2366731 (920)	total: 13.8s	remaining: 270ms
938:	learn: 0.2274017	test: 0.2364990	best: 0.2364990 (938)	total: 14.1s	remaining: 0us
bestTest = 0.236498983
bestIteration = 938

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6320407	test: 0.6320792	best: 0.6320792 (0)	total: 9.31ms	remaining: 9.31ms
1:	learn: 0.5791610	test: 0.5791866	best: 0.5791866 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5791866016
bestIteration = 1
0:	learn: 0.6295884	test: 0.6296366	best: 0.6296366 (0)	total: 15.4ms	remaining: 17.8s
20:	learn: 0.3197495	test: 0.3200966	best: 0.3200966 (20)	total: 313ms	remaining: 16.9s
40:	learn: 0.2877992	test: 0.2884171	best: 0.2884171 (40)	total: 613ms	remaining: 16.7s
60:	learn: 0.2764710	test: 0.2771885	best: 0.2771885 (60)	total: 917ms	remaining: 16.4s
80:	learn: 0.2699860	test: 0.2708394	best: 0.2708394 (80)	total: 1.22s	remaining: 16.2s
100:	learn: 0.2651994	test: 0.2662442	best: 0.2662442 (100)	total: 1.52s	remaining: 15.8s
120:	learn: 0.2617592	test: 0.2628763	best: 0.2628763 (120)	total: 1.81s	remaining: 15.5s
140:	learn: 0.2592592	test: 0.2604504	best: 0.2604504 (140)	total: 2.11s	remaining: 15.2s
160:	learn: 0.2562735	test: 0.2576462	best: 0.2576462 (160)	total: 2.42s	remaining: 14.9s
180:	learn: 0.2543231	test: 0.2558390	best: 0.2558390 (180)	total: 2.72s	remaining: 14.6s
200:	learn: 0.2522137	test: 0.2538079	best: 0.2538079 (200)	total: 3.02s	remaining: 14.3s
220:	learn: 0.2502514	test: 0.2519802	best: 0.2519802 (220)	total: 3.33s	remaining: 14.1s
240:	learn: 0.2485723	test: 0.2503996	best: 0.2503996 (240)	total: 3.63s	remaining: 13.8s
260:	learn: 0.2473282	test: 0.2492441	best: 0.2492441 (260)	total: 3.93s	remaining: 13.5s
280:	learn: 0.2459533	test: 0.2480033	best: 0.2480033 (280)	total: 4.23s	remaining: 13.1s
300:	learn: 0.2446329	test: 0.2468606	best: 0.2468606 (300)	total: 4.53s	remaining: 12.8s
320:	learn: 0.2435856	test: 0.2459415	best: 0.2459415 (320)	total: 4.83s	remaining: 12.5s
340:	learn: 0.2426789	test: 0.2451719	best: 0.2451719 (340)	total: 5.12s	remaining: 12.2s
360:	learn: 0.2418371	test: 0.2444500	best: 0.2444500 (360)	total: 5.43s	remaining: 11.9s
380:	learn: 0.2410199	test: 0.2437981	best: 0.2437981 (380)	total: 5.72s	remaining: 11.6s
400:	learn: 0.2402729	test: 0.2431315	best: 0.2431315 (400)	total: 6.02s	remaining: 11.3s
420:	learn: 0.2394858	test: 0.2425360	best: 0.2425360 (420)	total: 6.33s	remaining: 11s
440:	learn: 0.2386601	test: 0.2418619	best: 0.2418619 (440)	total: 6.62s	remaining: 10.7s
460:	learn: 0.2379717	test: 0.2412940	best: 0.2412940 (460)	total: 6.92s	remaining: 10.4s
480:	learn: 0.2372636	test: 0.2407246	best: 0.2407246 (480)	total: 7.22s	remaining: 10.1s
500:	learn: 0.2366799	test: 0.2402622	best: 0.2402622 (500)	total: 7.51s	remaining: 9.81s
520:	learn: 0.2360392	test: 0.2397527	best: 0.2397527 (520)	total: 7.82s	remaining: 9.52s
540:	learn: 0.2355523	test: 0.2393802	best: 0.2393802 (540)	total: 8.12s	remaining: 9.21s
560:	learn: 0.2349916	test: 0.2389273	best: 0.2389273 (560)	total: 8.41s	remaining: 8.91s
580:	learn: 0.2345280	test: 0.2385983	best: 0.2385983 (580)	total: 8.72s	remaining: 8.61s
600:	learn: 0.2340625	test: 0.2382718	best: 0.2382718 (600)	total: 9.02s	remaining: 8.32s
620:	learn: 0.2336521	test: 0.2380087	best: 0.2380087 (620)	total: 9.31s	remaining: 8.01s
640:	learn: 0.2331870	test: 0.2376901	best: 0.2376901 (640)	total: 9.61s	remaining: 7.7s
660:	learn: 0.2327182	test: 0.2373406	best: 0.2373406 (660)	total: 9.9s	remaining: 7.4s
680:	learn: 0.2322395	test: 0.2369775	best: 0.2369775 (680)	total: 10.2s	remaining: 7.1s
700:	learn: 0.2318175	test: 0.2366659	best: 0.2366659 (700)	total: 10.5s	remaining: 6.8s
720:	learn: 0.2314270	test: 0.2364360	best: 0.2364360 (720)	total: 10.8s	remaining: 6.5s
740:	learn: 0.2310474	test: 0.2362142	best: 0.2362142 (740)	total: 11.1s	remaining: 6.2s
760:	learn: 0.2306170	test: 0.2358956	best: 0.2358956 (760)	total: 11.4s	remaining: 5.9s
780:	learn: 0.2302212	test: 0.2356187	best: 0.2356187 (780)	total: 11.7s	remaining: 5.6s
800:	learn: 0.2298651	test: 0.2354225	best: 0.2354225 (800)	total: 12s	remaining: 5.3s
820:	learn: 0.2295128	test: 0.2352367	best: 0.2352367 (820)	total: 12.3s	remaining: 5s
840:	learn: 0.2291409	test: 0.2349704	best: 0.2349704 (840)	total: 12.6s	remaining: 4.7s
860:	learn: 0.2287947	test: 0.2347627	best: 0.2347627 (860)	total: 12.9s	remaining: 4.4s
880:	learn: 0.2284436	test: 0.2345730	best: 0.2345730 (880)	total: 13.2s	remaining: 4.1s
900:	learn: 0.2281558	test: 0.2344459	best: 0.2344459 (900)	total: 13.5s	remaining: 3.8s
920:	learn: 0.2278217	test: 0.2342520	best: 0.2342520 (920)	total: 13.8s	remaining: 3.5s
940:	learn: 0.2275255	test: 0.2341062	best: 0.2341062 (940)	total: 14.1s	remaining: 3.2s
960:	learn: 0.2271969	test: 0.2338876	best: 0.2338876 (960)	total: 14.4s	remaining: 2.9s
980:	learn: 0.2269306	test: 0.2337807	best: 0.2337807 (980)	total: 14.7s	remaining: 2.6s
1000:	learn: 0.2266465	test: 0.2336546	best: 0.2336546 (1000)	total: 15s	remaining: 2.3s
1020:	learn: 0.2263257	test: 0.2334675	best: 0.2334675 (1020)	total: 15.3s	remaining: 2s
1040:	learn: 0.2260604	test: 0.2333609	best: 0.2333601 (1039)	total: 15.5s	remaining: 1.7s
1060:	learn: 0.2257910	test: 0.2332200	best: 0.2332200 (1060)	total: 15.8s	remaining: 1.4s
1080:	learn: 0.2255220	test: 0.2330954	best: 0.2330949 (1079)	total: 16.1s	remaining: 1.1s
1100:	learn: 0.2252475	test: 0.2329227	best: 0.2329227 (1100)	total: 16.4s	remaining: 806ms
1120:	learn: 0.2249829	test: 0.2328048	best: 0.2328048 (1120)	total: 16.7s	remaining: 508ms
1140:	learn: 0.2246824	test: 0.2326408	best: 0.2326408 (1140)	total: 17s	remaining: 209ms
1154:	learn: 0.2244658	test: 0.2325222	best: 0.2325222 (1154)	total: 17.3s	remaining: 0us
bestTest = 0.2325222497
bestIteration = 1154

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6321025	test: 0.6324786	best: 0.6324786 (0)	total: 9.19ms	remaining: 9.19ms
1:	learn: 0.5793560	test: 0.5800087	best: 0.5800087 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5800087416
bestIteration = 1
0:	learn: 0.6300523	test: 0.6304622	best: 0.6304622 (0)	total: 14.6ms	remaining: 22.6s
20:	learn: 0.3188754	test: 0.3200912	best: 0.3200912 (20)	total: 312ms	remaining: 22.7s
40:	learn: 0.2878751	test: 0.2895659	best: 0.2895659 (40)	total: 608ms	remaining: 22.3s
60:	learn: 0.2771827	test: 0.2793464	best: 0.2793464 (60)	total: 907ms	remaining: 22.1s
80:	learn: 0.2705405	test: 0.2729383	best: 0.2729383 (80)	total: 1.21s	remaining: 21.9s
100:	learn: 0.2656661	test: 0.2682704	best: 0.2682704 (100)	total: 1.51s	remaining: 21.6s
120:	learn: 0.2618908	test: 0.2646446	best: 0.2646446 (120)	total: 1.8s	remaining: 21.3s
140:	learn: 0.2585767	test: 0.2615006	best: 0.2615006 (140)	total: 2.1s	remaining: 21s
160:	learn: 0.2560160	test: 0.2590145	best: 0.2590145 (160)	total: 2.41s	remaining: 20.7s
180:	learn: 0.2538041	test: 0.2568424	best: 0.2568424 (180)	total: 2.73s	remaining: 20.6s
200:	learn: 0.2517061	test: 0.2548782	best: 0.2548782 (200)	total: 3.03s	remaining: 20.3s
220:	learn: 0.2500963	test: 0.2532925	best: 0.2532925 (220)	total: 3.33s	remaining: 20s
240:	learn: 0.2485097	test: 0.2518133	best: 0.2518133 (240)	total: 3.63s	remaining: 19.7s
260:	learn: 0.2471383	test: 0.2505048	best: 0.2505048 (260)	total: 3.93s	remaining: 19.4s
280:	learn: 0.2457249	test: 0.2492398	best: 0.2492398 (280)	total: 4.23s	remaining: 19s
300:	learn: 0.2445677	test: 0.2482480	best: 0.2482480 (300)	total: 4.53s	remaining: 18.7s
320:	learn: 0.2435351	test: 0.2473034	best: 0.2473034 (320)	total: 4.84s	remaining: 18.5s
340:	learn: 0.2426193	test: 0.2465518	best: 0.2465518 (340)	total: 5.15s	remaining: 18.2s
360:	learn: 0.2417963	test: 0.2458942	best: 0.2458942 (360)	total: 5.46s	remaining: 17.9s
380:	learn: 0.2408752	test: 0.2451237	best: 0.2451237 (380)	total: 5.76s	remaining: 17.6s
400:	learn: 0.2401385	test: 0.2445317	best: 0.2445317 (400)	total: 6.06s	remaining: 17.3s
420:	learn: 0.2393453	test: 0.2438928	best: 0.2438928 (420)	total: 6.37s	remaining: 17s
440:	learn: 0.2386190	test: 0.2433580	best: 0.2433580 (440)	total: 6.67s	remaining: 16.7s
460:	learn: 0.2379651	test: 0.2428476	best: 0.2428476 (460)	total: 6.97s	remaining: 16.4s
480:	learn: 0.2372827	test: 0.2423107	best: 0.2423107 (480)	total: 7.26s	remaining: 16.1s
500:	learn: 0.2367548	test: 0.2419607	best: 0.2419607 (500)	total: 7.56s	remaining: 15.8s
520:	learn: 0.2361331	test: 0.2414685	best: 0.2414685 (520)	total: 7.86s	remaining: 15.5s
540:	learn: 0.2355626	test: 0.2409946	best: 0.2409946 (540)	total: 8.16s	remaining: 15.2s
560:	learn: 0.2349833	test: 0.2405373	best: 0.2405373 (560)	total: 8.46s	remaining: 14.9s
580:	learn: 0.2344978	test: 0.2402093	best: 0.2402093 (580)	total: 8.76s	remaining: 14.5s
600:	learn: 0.2340033	test: 0.2398683	best: 0.2398683 (600)	total: 9.06s	remaining: 14.2s
620:	learn: 0.2334951	test: 0.2394885	best: 0.2394885 (620)	total: 9.36s	remaining: 13.9s
640:	learn: 0.2329824	test: 0.2390884	best: 0.2390884 (640)	total: 9.65s	remaining: 13.6s
660:	learn: 0.2325219	test: 0.2387824	best: 0.2387824 (660)	total: 9.95s	remaining: 13.3s
680:	learn: 0.2320586	test: 0.2384948	best: 0.2384948 (680)	total: 10.2s	remaining: 13s
700:	learn: 0.2316523	test: 0.2382251	best: 0.2382251 (700)	total: 10.5s	remaining: 12.7s
720:	learn: 0.2312216	test: 0.2379547	best: 0.2379547 (720)	total: 10.8s	remaining: 12.4s
740:	learn: 0.2308252	test: 0.2376852	best: 0.2376852 (740)	total: 11.1s	remaining: 12.1s
760:	learn: 0.2304315	test: 0.2374488	best: 0.2374488 (760)	total: 11.4s	remaining: 11.8s
780:	learn: 0.2301191	test: 0.2373282	best: 0.2373282 (780)	total: 11.7s	remaining: 11.5s
800:	learn: 0.2298010	test: 0.2371544	best: 0.2371544 (800)	total: 12s	remaining: 11.2s
820:	learn: 0.2294535	test: 0.2369386	best: 0.2369369 (819)	total: 12.3s	remaining: 10.9s
840:	learn: 0.2290931	test: 0.2367495	best: 0.2367495 (840)	total: 12.6s	remaining: 10.6s
860:	learn: 0.2287676	test: 0.2365325	best: 0.2365325 (860)	total: 12.9s	remaining: 10.3s
880:	learn: 0.2284427	test: 0.2363605	best: 0.2363605 (880)	total: 13.2s	remaining: 9.97s
900:	learn: 0.2281016	test: 0.2362162	best: 0.2362162 (900)	total: 13.5s	remaining: 9.67s
920:	learn: 0.2278351	test: 0.2360620	best: 0.2360620 (920)	total: 13.8s	remaining: 9.37s
940:	learn: 0.2274769	test: 0.2358013	best: 0.2358013 (940)	total: 14.1s	remaining: 9.06s
960:	learn: 0.2271436	test: 0.2356252	best: 0.2356252 (960)	total: 14.4s	remaining: 8.76s
980:	learn: 0.2268578	test: 0.2354716	best: 0.2354716 (980)	total: 14.7s	remaining: 8.46s
1000:	learn: 0.2265658	test: 0.2353469	best: 0.2353469 (1000)	total: 15s	remaining: 8.16s
1020:	learn: 0.2262701	test: 0.2352172	best: 0.2352162 (1019)	total: 15.3s	remaining: 7.87s
1040:	learn: 0.2259883	test: 0.2350995	best: 0.2350995 (1040)	total: 15.6s	remaining: 7.57s
1060:	learn: 0.2256993	test: 0.2349723	best: 0.2349723 (1060)	total: 15.9s	remaining: 7.27s
1080:	learn: 0.2254019	test: 0.2348114	best: 0.2348114 (1080)	total: 16.2s	remaining: 6.97s
1100:	learn: 0.2251122	test: 0.2347010	best: 0.2347010 (1100)	total: 16.5s	remaining: 6.67s
1120:	learn: 0.2248561	test: 0.2345967	best: 0.2345967 (1120)	total: 16.8s	remaining: 6.37s
1140:	learn: 0.2246053	test: 0.2344872	best: 0.2344855 (1139)	total: 17.1s	remaining: 6.07s
1160:	learn: 0.2243167	test: 0.2343687	best: 0.2343687 (1160)	total: 17.4s	remaining: 5.77s
1180:	learn: 0.2240554	test: 0.2342624	best: 0.2342624 (1180)	total: 17.7s	remaining: 5.47s
1200:	learn: 0.2238064	test: 0.2341450	best: 0.2341450 (1200)	total: 18s	remaining: 5.17s
1220:	learn: 0.2235694	test: 0.2340522	best: 0.2340522 (1220)	total: 18.3s	remaining: 4.87s
1240:	learn: 0.2233202	test: 0.2339585	best: 0.2339585 (1240)	total: 18.6s	remaining: 4.57s
1260:	learn: 0.2230620	test: 0.2338438	best: 0.2338438 (1260)	total: 18.9s	remaining: 4.27s
1280:	learn: 0.2228002	test: 0.2337152	best: 0.2337152 (1280)	total: 19.2s	remaining: 3.97s
1300:	learn: 0.2225207	test: 0.2335640	best: 0.2335630 (1298)	total: 19.5s	remaining: 3.67s
1320:	learn: 0.2222725	test: 0.2334573	best: 0.2334573 (1320)	total: 19.8s	remaining: 3.37s
1340:	learn: 0.2220730	test: 0.2334106	best: 0.2334067 (1338)	total: 20.1s	remaining: 3.07s
1360:	learn: 0.2218365	test: 0.2333298	best: 0.2333298 (1360)	total: 20.4s	remaining: 2.77s
1380:	learn: 0.2215923	test: 0.2332062	best: 0.2332062 (1380)	total: 20.7s	remaining: 2.47s
1400:	learn: 0.2213351	test: 0.2331064	best: 0.2331064 (1400)	total: 21s	remaining: 2.17s
1420:	learn: 0.2210698	test: 0.2329929	best: 0.2329899 (1419)	total: 21.3s	remaining: 1.87s
1440:	learn: 0.2208506	test: 0.2329238	best: 0.2329234 (1436)	total: 21.6s	remaining: 1.57s
1460:	learn: 0.2206515	test: 0.2328656	best: 0.2328656 (1460)	total: 21.9s	remaining: 1.27s
1480:	learn: 0.2204434	test: 0.2328071	best: 0.2327985 (1474)	total: 22.2s	remaining: 974ms
1500:	learn: 0.2202201	test: 0.2327199	best: 0.2327199 (1500)	total: 22.5s	remaining: 674ms
1520:	learn: 0.2199898	test: 0.2326123	best: 0.2326123 (1520)	total: 22.8s	remaining: 374ms
1540:	learn: 0.2198076	test: 0.2325406	best: 0.2325406 (1540)	total: 23.1s	remaining: 74.9ms
1545:	learn: 0.2197582	test: 0.2325270	best: 0.2325270 (1545)	total: 23.2s	remaining: 0us
bestTest = 0.232526982
bestIteration = 1545

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6320740	test: 0.6321861	best: 0.6321861 (0)	total: 9.04ms	remaining: 9.04ms
1:	learn: 0.5791789	test: 0.5793650	best: 0.5793650 (1)	total: 17.7ms	remaining: 0us
bestTest = 0.5793650059
bestIteration = 1
0:	learn: 0.6300709	test: 0.6301897	best: 0.6301897 (0)	total: 16.6ms	remaining: 37.7s
20:	learn: 0.3182990	test: 0.3198981	best: 0.3198981 (20)	total: 313ms	remaining: 33.6s
40:	learn: 0.2879234	test: 0.2900291	best: 0.2900291 (40)	total: 612ms	remaining: 33.3s
60:	learn: 0.2770162	test: 0.2794543	best: 0.2794543 (60)	total: 914ms	remaining: 33.2s
80:	learn: 0.2712833	test: 0.2739015	best: 0.2739015 (80)	total: 1.21s	remaining: 32.9s
100:	learn: 0.2659160	test: 0.2686994	best: 0.2686994 (100)	total: 1.51s	remaining: 32.6s
120:	learn: 0.2623201	test: 0.2652888	best: 0.2652888 (120)	total: 1.81s	remaining: 32.2s
140:	learn: 0.2589886	test: 0.2621555	best: 0.2621555 (140)	total: 2.11s	remaining: 31.9s
160:	learn: 0.2562486	test: 0.2595571	best: 0.2595571 (160)	total: 2.41s	remaining: 31.6s
180:	learn: 0.2538346	test: 0.2572880	best: 0.2572880 (180)	total: 2.7s	remaining: 31.3s
200:	learn: 0.2520104	test: 0.2556558	best: 0.2556558 (200)	total: 3s	remaining: 31s
220:	learn: 0.2503641	test: 0.2541011	best: 0.2541011 (220)	total: 3.3s	remaining: 30.7s
240:	learn: 0.2489980	test: 0.2529201	best: 0.2529201 (240)	total: 3.6s	remaining: 30.4s
260:	learn: 0.2474715	test: 0.2516326	best: 0.2516326 (260)	total: 3.9s	remaining: 30.1s
280:	learn: 0.2461392	test: 0.2505537	best: 0.2505537 (280)	total: 4.2s	remaining: 29.8s
300:	learn: 0.2448553	test: 0.2494719	best: 0.2494719 (300)	total: 4.5s	remaining: 29.5s
320:	learn: 0.2436888	test: 0.2484636	best: 0.2484636 (320)	total: 4.79s	remaining: 29.2s
340:	learn: 0.2427989	test: 0.2477342	best: 0.2477342 (340)	total: 5.09s	remaining: 28.9s
360:	learn: 0.2417438	test: 0.2468200	best: 0.2468200 (360)	total: 5.39s	remaining: 28.6s
380:	learn: 0.2409783	test: 0.2462231	best: 0.2462231 (380)	total: 5.68s	remaining: 28.2s
400:	learn: 0.2402119	test: 0.2456596	best: 0.2456596 (400)	total: 5.98s	remaining: 27.9s
420:	learn: 0.2395025	test: 0.2451338	best: 0.2451338 (420)	total: 6.27s	remaining: 27.6s
440:	learn: 0.2387435	test: 0.2445079	best: 0.2445079 (440)	total: 6.57s	remaining: 27.3s
460:	learn: 0.2379821	test: 0.2439270	best: 0.2439270 (460)	total: 6.87s	remaining: 27s
480:	learn: 0.2373355	test: 0.2434512	best: 0.2434512 (480)	total: 7.17s	remaining: 26.7s
500:	learn: 0.2368223	test: 0.2430849	best: 0.2430849 (500)	total: 7.46s	remaining: 26.4s
520:	learn: 0.2362172	test: 0.2426108	best: 0.2426108 (520)	total: 7.76s	remaining: 26.1s
540:	learn: 0.2356065	test: 0.2421460	best: 0.2421460 (540)	total: 8.05s	remaining: 25.8s
560:	learn: 0.2351521	test: 0.2418222	best: 0.2418222 (560)	total: 8.36s	remaining: 25.5s
580:	learn: 0.2346672	test: 0.2414642	best: 0.2414642 (580)	total: 8.66s	remaining: 25.2s
600:	learn: 0.2341532	test: 0.2410978	best: 0.2410978 (600)	total: 8.96s	remaining: 24.9s
620:	learn: 0.2336753	test: 0.2408001	best: 0.2408001 (620)	total: 9.26s	remaining: 24.7s
640:	learn: 0.2331347	test: 0.2403818	best: 0.2403818 (640)	total: 9.56s	remaining: 24.4s
660:	learn: 0.2326401	test: 0.2400617	best: 0.2400617 (660)	total: 9.86s	remaining: 24.1s
680:	learn: 0.2321633	test: 0.2397479	best: 0.2397479 (680)	total: 10.2s	remaining: 23.8s
700:	learn: 0.2317528	test: 0.2395027	best: 0.2395027 (700)	total: 10.4s	remaining: 23.5s
720:	learn: 0.2313635	test: 0.2393008	best: 0.2393008 (720)	total: 10.7s	remaining: 23.2s
740:	learn: 0.2309944	test: 0.2391010	best: 0.2391010 (740)	total: 11s	remaining: 22.8s
760:	learn: 0.2305925	test: 0.2388691	best: 0.2388691 (760)	total: 11.3s	remaining: 22.5s
780:	learn: 0.2301998	test: 0.2386459	best: 0.2386459 (780)	total: 11.6s	remaining: 22.2s
800:	learn: 0.2297299	test: 0.2383211	best: 0.2383211 (800)	total: 11.9s	remaining: 21.9s
820:	learn: 0.2293591	test: 0.2381293	best: 0.2381293 (820)	total: 12.2s	remaining: 21.6s
840:	learn: 0.2289782	test: 0.2378796	best: 0.2378796 (840)	total: 12.5s	remaining: 21.3s
860:	learn: 0.2286258	test: 0.2376701	best: 0.2376701 (860)	total: 12.8s	remaining: 21.1s
880:	learn: 0.2282964	test: 0.2374863	best: 0.2374863 (880)	total: 13.1s	remaining: 20.8s
900:	learn: 0.2279789	test: 0.2372945	best: 0.2372945 (900)	total: 13.4s	remaining: 20.5s
920:	learn: 0.2276656	test: 0.2371786	best: 0.2371734 (918)	total: 13.7s	remaining: 20.2s
940:	learn: 0.2273268	test: 0.2369964	best: 0.2369964 (940)	total: 14s	remaining: 19.9s
960:	learn: 0.2269637	test: 0.2368442	best: 0.2368442 (960)	total: 14.3s	remaining: 19.6s
980:	learn: 0.2266677	test: 0.2367090	best: 0.2367090 (980)	total: 14.6s	remaining: 19.3s
1000:	learn: 0.2264107	test: 0.2365907	best: 0.2365907 (1000)	total: 14.9s	remaining: 19s
1020:	learn: 0.2261072	test: 0.2364176	best: 0.2364176 (1020)	total: 15.2s	remaining: 18.7s
1040:	learn: 0.2257974	test: 0.2362540	best: 0.2362540 (1040)	total: 15.5s	remaining: 18.4s
1060:	learn: 0.2254661	test: 0.2360680	best: 0.2360680 (1060)	total: 15.8s	remaining: 18.1s
1080:	learn: 0.2252023	test: 0.2359290	best: 0.2359290 (1080)	total: 16.1s	remaining: 17.8s
1100:	learn: 0.2249344	test: 0.2358441	best: 0.2358441 (1100)	total: 16.4s	remaining: 17.5s
1120:	learn: 0.2246530	test: 0.2356986	best: 0.2356986 (1120)	total: 16.7s	remaining: 17.2s
1140:	learn: 0.2244001	test: 0.2355718	best: 0.2355718 (1140)	total: 17s	remaining: 16.9s
1160:	learn: 0.2241618	test: 0.2354600	best: 0.2354600 (1160)	total: 17.3s	remaining: 16.6s
1180:	learn: 0.2238496	test: 0.2353218	best: 0.2353218 (1180)	total: 17.6s	remaining: 16.3s
1200:	learn: 0.2236053	test: 0.2352192	best: 0.2352192 (1200)	total: 17.9s	remaining: 16s
1220:	learn: 0.2233773	test: 0.2351308	best: 0.2351304 (1218)	total: 18.2s	remaining: 15.7s
1240:	learn: 0.2231220	test: 0.2350448	best: 0.2350448 (1240)	total: 18.5s	remaining: 15.4s
1260:	learn: 0.2228293	test: 0.2348828	best: 0.2348828 (1260)	total: 18.8s	remaining: 15.1s
1280:	learn: 0.2225779	test: 0.2347755	best: 0.2347755 (1280)	total: 19.1s	remaining: 14.8s
1300:	learn: 0.2223192	test: 0.2346839	best: 0.2346839 (1300)	total: 19.4s	remaining: 14.5s
1320:	learn: 0.2220479	test: 0.2345421	best: 0.2345421 (1320)	total: 19.7s	remaining: 14.2s
1340:	learn: 0.2218323	test: 0.2344744	best: 0.2344744 (1340)	total: 20s	remaining: 13.9s
1360:	learn: 0.2215678	test: 0.2343200	best: 0.2343200 (1360)	total: 20.3s	remaining: 13.6s
1380:	learn: 0.2213279	test: 0.2341953	best: 0.2341953 (1380)	total: 20.6s	remaining: 13.3s
1400:	learn: 0.2211009	test: 0.2340701	best: 0.2340701 (1400)	total: 20.9s	remaining: 13s
1420:	learn: 0.2208935	test: 0.2340201	best: 0.2340176 (1418)	total: 21.2s	remaining: 12.7s
1440:	learn: 0.2206657	test: 0.2339342	best: 0.2339342 (1440)	total: 21.5s	remaining: 12.4s
1460:	learn: 0.2204417	test: 0.2338619	best: 0.2338619 (1460)	total: 21.8s	remaining: 12.1s
1480:	learn: 0.2202266	test: 0.2337774	best: 0.2337774 (1480)	total: 22s	remaining: 11.8s
1500:	learn: 0.2199881	test: 0.2336897	best: 0.2336897 (1500)	total: 22.3s	remaining: 11.5s
1520:	learn: 0.2197900	test: 0.2336204	best: 0.2336204 (1520)	total: 22.6s	remaining: 11.2s
1540:	learn: 0.2195783	test: 0.2335397	best: 0.2335397 (1540)	total: 22.9s	remaining: 10.9s
1560:	learn: 0.2193950	test: 0.2334900	best: 0.2334900 (1560)	total: 23.3s	remaining: 10.6s
1580:	learn: 0.2191400	test: 0.2333565	best: 0.2333565 (1580)	total: 23.6s	remaining: 10.3s
1600:	learn: 0.2189347	test: 0.2332899	best: 0.2332899 (1600)	total: 23.9s	remaining: 10s
1620:	learn: 0.2187395	test: 0.2332296	best: 0.2332296 (1620)	total: 24.2s	remaining: 9.75s
1640:	learn: 0.2185301	test: 0.2331782	best: 0.2331744 (1638)	total: 24.5s	remaining: 9.45s
1660:	learn: 0.2183278	test: 0.2330981	best: 0.2330981 (1660)	total: 24.8s	remaining: 9.15s
1680:	learn: 0.2181300	test: 0.2330405	best: 0.2330396 (1679)	total: 25.1s	remaining: 8.85s
1700:	learn: 0.2179285	test: 0.2329752	best: 0.2329752 (1700)	total: 25.4s	remaining: 8.55s
1720:	learn: 0.2177153	test: 0.2329271	best: 0.2329271 (1720)	total: 25.7s	remaining: 8.26s
1740:	learn: 0.2174987	test: 0.2328262	best: 0.2328262 (1740)	total: 26s	remaining: 7.96s
1760:	learn: 0.2172862	test: 0.2327527	best: 0.2327527 (1760)	total: 26.3s	remaining: 7.67s
1780:	learn: 0.2170707	test: 0.2326577	best: 0.2326577 (1780)	total: 26.6s	remaining: 7.37s
1800:	learn: 0.2168991	test: 0.2326077	best: 0.2326077 (1800)	total: 26.9s	remaining: 7.07s
1820:	learn: 0.2167268	test: 0.2325731	best: 0.2325731 (1820)	total: 27.2s	remaining: 6.77s
1840:	learn: 0.2165383	test: 0.2325183	best: 0.2325178 (1839)	total: 27.5s	remaining: 6.47s
1860:	learn: 0.2163621	test: 0.2325116	best: 0.2325092 (1851)	total: 27.8s	remaining: 6.17s
1880:	learn: 0.2161488	test: 0.2324285	best: 0.2324265 (1879)	total: 28.1s	remaining: 5.88s
1900:	learn: 0.2159588	test: 0.2323876	best: 0.2323876 (1900)	total: 28.4s	remaining: 5.58s
1920:	learn: 0.2157891	test: 0.2323407	best: 0.2323348 (1916)	total: 28.6s	remaining: 5.28s
1940:	learn: 0.2155915	test: 0.2322950	best: 0.2322950 (1940)	total: 28.9s	remaining: 4.98s
1960:	learn: 0.2154143	test: 0.2322461	best: 0.2322461 (1960)	total: 29.2s	remaining: 4.68s
1980:	learn: 0.2152320	test: 0.2321909	best: 0.2321909 (1980)	total: 29.5s	remaining: 4.38s
2000:	learn: 0.2150527	test: 0.2321516	best: 0.2321510 (1996)	total: 29.8s	remaining: 4.09s
2020:	learn: 0.2148451	test: 0.2320875	best: 0.2320875 (2020)	total: 30.1s	remaining: 3.79s
2040:	learn: 0.2146582	test: 0.2320172	best: 0.2320172 (2040)	total: 30.4s	remaining: 3.49s
2060:	learn: 0.2144703	test: 0.2319706	best: 0.2319706 (2060)	total: 30.7s	remaining: 3.19s
2080:	learn: 0.2142963	test: 0.2319204	best: 0.2319204 (2080)	total: 31s	remaining: 2.89s
2100:	learn: 0.2141295	test: 0.2318822	best: 0.2318822 (2100)	total: 31.3s	remaining: 2.59s
2120:	learn: 0.2139463	test: 0.2318336	best: 0.2318328 (2119)	total: 31.6s	remaining: 2.3s
2140:	learn: 0.2137754	test: 0.2318107	best: 0.2318085 (2137)	total: 31.9s	remaining: 2s
2160:	learn: 0.2135924	test: 0.2317735	best: 0.2317735 (2160)	total: 32.2s	remaining: 1.7s
2180:	learn: 0.2134208	test: 0.2317388	best: 0.2317388 (2180)	total: 32.5s	remaining: 1.4s
2200:	learn: 0.2132384	test: 0.2317284	best: 0.2317264 (2199)	total: 32.8s	remaining: 1.1s
2220:	learn: 0.2130627	test: 0.2316892	best: 0.2316892 (2220)	total: 33.1s	remaining: 805ms
2240:	learn: 0.2129123	test: 0.2316792	best: 0.2316785 (2238)	total: 33.4s	remaining: 507ms
2260:	learn: 0.2127349	test: 0.2316567	best: 0.2316544 (2256)	total: 33.7s	remaining: 209ms
2274:	learn: 0.2126186	test: 0.2316433	best: 0.2316375 (2269)	total: 33.9s	remaining: 0us
bestTest = 0.2316375223
bestIteration = 2269
Shrink model to first 2270 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6321809	test: 0.6322583	best: 0.6322583 (0)	total: 9.13ms	remaining: 9.13ms
1:	learn: 0.5795183	test: 0.5796278	best: 0.5796278 (1)	total: 17.7ms	remaining: 0us
bestTest = 0.5796278089
bestIteration = 1
0:	learn: 0.6302387	test: 0.6302816	best: 0.6302816 (0)	total: 15.2ms	remaining: 1m 8s
20:	learn: 0.3204203	test: 0.3197526	best: 0.3197526 (20)	total: 313ms	remaining: 1m 6s
40:	learn: 0.2889613	test: 0.2880650	best: 0.2880650 (40)	total: 627ms	remaining: 1m 7s
60:	learn: 0.2768147	test: 0.2759763	best: 0.2759763 (60)	total: 929ms	remaining: 1m 7s
80:	learn: 0.2707607	test: 0.2701336	best: 0.2701336 (80)	total: 1.22s	remaining: 1m 6s
100:	learn: 0.2662863	test: 0.2658013	best: 0.2658013 (100)	total: 1.52s	remaining: 1m 5s
120:	learn: 0.2624323	test: 0.2621330	best: 0.2621330 (120)	total: 1.82s	remaining: 1m 5s
140:	learn: 0.2590546	test: 0.2588688	best: 0.2588688 (140)	total: 2.12s	remaining: 1m 5s
160:	learn: 0.2564358	test: 0.2562922	best: 0.2562922 (160)	total: 2.42s	remaining: 1m 4s
180:	learn: 0.2543671	test: 0.2543567	best: 0.2543567 (180)	total: 2.71s	remaining: 1m 4s
200:	learn: 0.2523492	test: 0.2524804	best: 0.2524804 (200)	total: 3.01s	remaining: 1m 4s
220:	learn: 0.2505550	test: 0.2506935	best: 0.2506935 (220)	total: 3.31s	remaining: 1m 3s
240:	learn: 0.2489352	test: 0.2492469	best: 0.2492469 (240)	total: 3.61s	remaining: 1m 3s
260:	learn: 0.2475568	test: 0.2479617	best: 0.2479617 (260)	total: 3.91s	remaining: 1m 3s
280:	learn: 0.2461212	test: 0.2466445	best: 0.2466445 (280)	total: 4.21s	remaining: 1m 2s
300:	learn: 0.2449004	test: 0.2455988	best: 0.2455988 (300)	total: 4.52s	remaining: 1m 2s
320:	learn: 0.2438873	test: 0.2447041	best: 0.2447041 (320)	total: 4.82s	remaining: 1m 2s
340:	learn: 0.2430113	test: 0.2439386	best: 0.2439386 (340)	total: 5.12s	remaining: 1m 1s
360:	learn: 0.2420609	test: 0.2431293	best: 0.2431293 (360)	total: 5.42s	remaining: 1m 1s
380:	learn: 0.2411997	test: 0.2423481	best: 0.2423481 (380)	total: 5.72s	remaining: 1m 1s
400:	learn: 0.2404510	test: 0.2416933	best: 0.2416933 (400)	total: 6.03s	remaining: 1m 1s
420:	learn: 0.2397519	test: 0.2411446	best: 0.2411446 (420)	total: 6.33s	remaining: 1m
440:	learn: 0.2390318	test: 0.2405427	best: 0.2405427 (440)	total: 6.63s	remaining: 1m
460:	learn: 0.2382862	test: 0.2398986	best: 0.2398986 (460)	total: 6.93s	remaining: 1m
480:	learn: 0.2376423	test: 0.2393795	best: 0.2393795 (480)	total: 7.23s	remaining: 59.9s
500:	learn: 0.2371000	test: 0.2389912	best: 0.2389912 (500)	total: 7.53s	remaining: 59.6s
520:	learn: 0.2365106	test: 0.2385157	best: 0.2385157 (520)	total: 7.82s	remaining: 59.3s
540:	learn: 0.2358587	test: 0.2379703	best: 0.2379703 (540)	total: 8.11s	remaining: 58.9s
560:	learn: 0.2353682	test: 0.2375842	best: 0.2375842 (560)	total: 8.42s	remaining: 58.6s
580:	learn: 0.2348847	test: 0.2372585	best: 0.2372585 (580)	total: 8.72s	remaining: 58.3s
600:	learn: 0.2343031	test: 0.2367615	best: 0.2367615 (600)	total: 9.03s	remaining: 58.1s
620:	learn: 0.2338650	test: 0.2364693	best: 0.2364693 (620)	total: 9.32s	remaining: 57.8s
640:	learn: 0.2333536	test: 0.2360844	best: 0.2360844 (640)	total: 9.62s	remaining: 57.5s
660:	learn: 0.2329113	test: 0.2357950	best: 0.2357950 (660)	total: 9.92s	remaining: 57.1s
680:	learn: 0.2324578	test: 0.2354861	best: 0.2354861 (680)	total: 10.2s	remaining: 56.8s
700:	learn: 0.2320005	test: 0.2351212	best: 0.2351212 (700)	total: 10.5s	remaining: 56.5s
720:	learn: 0.2315220	test: 0.2348191	best: 0.2348191 (720)	total: 10.8s	remaining: 56.2s
740:	learn: 0.2311617	test: 0.2345883	best: 0.2345883 (740)	total: 11.1s	remaining: 55.9s
760:	learn: 0.2307898	test: 0.2343530	best: 0.2343530 (760)	total: 11.4s	remaining: 55.6s
780:	learn: 0.2304633	test: 0.2341586	best: 0.2341586 (780)	total: 11.7s	remaining: 55.2s
800:	learn: 0.2301168	test: 0.2339325	best: 0.2339325 (800)	total: 12s	remaining: 54.9s
820:	learn: 0.2297627	test: 0.2336913	best: 0.2336913 (820)	total: 12.3s	remaining: 54.6s
840:	learn: 0.2294283	test: 0.2334821	best: 0.2334821 (840)	total: 12.6s	remaining: 54.3s
860:	learn: 0.2290538	test: 0.2332311	best: 0.2332311 (860)	total: 12.9s	remaining: 54s
880:	learn: 0.2287101	test: 0.2330549	best: 0.2330549 (880)	total: 13.2s	remaining: 53.7s
900:	learn: 0.2283417	test: 0.2328402	best: 0.2328402 (900)	total: 13.5s	remaining: 53.4s
920:	learn: 0.2280244	test: 0.2326699	best: 0.2326686 (919)	total: 13.8s	remaining: 53.1s
940:	learn: 0.2277108	test: 0.2325122	best: 0.2325122 (940)	total: 14.1s	remaining: 52.9s
960:	learn: 0.2273951	test: 0.2323400	best: 0.2323400 (960)	total: 14.4s	remaining: 52.6s
980:	learn: 0.2270473	test: 0.2321494	best: 0.2321488 (979)	total: 14.7s	remaining: 52.2s
1000:	learn: 0.2267212	test: 0.2319537	best: 0.2319537 (1000)	total: 15s	remaining: 51.9s
1020:	learn: 0.2264076	test: 0.2317889	best: 0.2317889 (1020)	total: 15.3s	remaining: 51.6s
1040:	learn: 0.2260837	test: 0.2316217	best: 0.2316217 (1040)	total: 15.6s	remaining: 51.3s
1060:	learn: 0.2257677	test: 0.2314579	best: 0.2314579 (1060)	total: 15.9s	remaining: 51s
1080:	learn: 0.2254611	test: 0.2313039	best: 0.2313035 (1079)	total: 16.2s	remaining: 50.7s
1100:	learn: 0.2251990	test: 0.2311818	best: 0.2311781 (1099)	total: 16.5s	remaining: 50.4s
1120:	learn: 0.2249306	test: 0.2311006	best: 0.2311006 (1120)	total: 16.8s	remaining: 50.1s
1140:	learn: 0.2246458	test: 0.2309767	best: 0.2309767 (1140)	total: 17.1s	remaining: 49.8s
1160:	learn: 0.2244084	test: 0.2308476	best: 0.2308476 (1160)	total: 17.4s	remaining: 49.5s
1180:	learn: 0.2241405	test: 0.2307235	best: 0.2307235 (1180)	total: 17.7s	remaining: 49.2s
1200:	learn: 0.2238160	test: 0.2305586	best: 0.2305586 (1200)	total: 18s	remaining: 48.9s
1220:	learn: 0.2236015	test: 0.2304795	best: 0.2304795 (1220)	total: 18.3s	remaining: 48.6s
1240:	learn: 0.2233701	test: 0.2303995	best: 0.2303948 (1239)	total: 18.6s	remaining: 48.3s
1260:	learn: 0.2231320	test: 0.2303238	best: 0.2303238 (1260)	total: 18.9s	remaining: 48s
1280:	learn: 0.2228865	test: 0.2302536	best: 0.2302536 (1280)	total: 19.1s	remaining: 47.7s
1300:	learn: 0.2226326	test: 0.2301008	best: 0.2301008 (1300)	total: 19.5s	remaining: 47.4s
1320:	learn: 0.2224193	test: 0.2300267	best: 0.2300267 (1320)	total: 19.8s	remaining: 47.1s
1340:	learn: 0.2222198	test: 0.2299706	best: 0.2299678 (1339)	total: 20s	remaining: 46.8s
1360:	learn: 0.2220077	test: 0.2299158	best: 0.2299143 (1359)	total: 20.3s	remaining: 46.5s
1380:	learn: 0.2217593	test: 0.2298127	best: 0.2298127 (1380)	total: 20.6s	remaining: 46.2s
1400:	learn: 0.2215064	test: 0.2296917	best: 0.2296896 (1399)	total: 20.9s	remaining: 45.9s
1420:	learn: 0.2212629	test: 0.2295993	best: 0.2295993 (1420)	total: 21.2s	remaining: 45.5s
1440:	learn: 0.2210441	test: 0.2295137	best: 0.2295137 (1440)	total: 21.5s	remaining: 45.3s
1460:	learn: 0.2208362	test: 0.2294633	best: 0.2294594 (1459)	total: 21.8s	remaining: 44.9s
1480:	learn: 0.2206145	test: 0.2293989	best: 0.2293986 (1479)	total: 22.1s	remaining: 44.6s
1500:	learn: 0.2203875	test: 0.2293675	best: 0.2293675 (1500)	total: 22.4s	remaining: 44.3s
1520:	learn: 0.2201671	test: 0.2292846	best: 0.2292846 (1520)	total: 22.7s	remaining: 44s
1540:	learn: 0.2199657	test: 0.2292443	best: 0.2292443 (1540)	total: 23s	remaining: 43.7s
1560:	learn: 0.2197594	test: 0.2291547	best: 0.2291547 (1560)	total: 23.3s	remaining: 43.4s
1580:	learn: 0.2195640	test: 0.2290937	best: 0.2290915 (1577)	total: 23.6s	remaining: 43.1s
1600:	learn: 0.2193636	test: 0.2290619	best: 0.2290619 (1600)	total: 23.9s	remaining: 42.8s
1620:	learn: 0.2191486	test: 0.2289889	best: 0.2289855 (1619)	total: 24.2s	remaining: 42.5s
1640:	learn: 0.2189384	test: 0.2289286	best: 0.2289286 (1640)	total: 24.5s	remaining: 42.2s
1660:	learn: 0.2187531	test: 0.2288976	best: 0.2288976 (1660)	total: 24.8s	remaining: 41.9s
1680:	learn: 0.2185579	test: 0.2288390	best: 0.2288384 (1679)	total: 25.1s	remaining: 41.6s
1700:	learn: 0.2183451	test: 0.2287787	best: 0.2287787 (1700)	total: 25.4s	remaining: 41.3s
1720:	learn: 0.2181595	test: 0.2287430	best: 0.2287404 (1715)	total: 25.7s	remaining: 41s
1740:	learn: 0.2179751	test: 0.2286958	best: 0.2286958 (1740)	total: 26s	remaining: 40.7s
1760:	learn: 0.2177833	test: 0.2286336	best: 0.2286336 (1760)	total: 26.3s	remaining: 40.4s
1780:	learn: 0.2175807	test: 0.2285773	best: 0.2285679 (1777)	total: 26.6s	remaining: 40.1s
1800:	learn: 0.2174023	test: 0.2285380	best: 0.2285380 (1800)	total: 26.9s	remaining: 39.8s
1820:	learn: 0.2172287	test: 0.2285282	best: 0.2285233 (1816)	total: 27.2s	remaining: 39.5s
1840:	learn: 0.2170432	test: 0.2284984	best: 0.2284970 (1839)	total: 27.5s	remaining: 39.3s
1860:	learn: 0.2168613	test: 0.2284579	best: 0.2284579 (1860)	total: 27.8s	remaining: 38.9s
1880:	learn: 0.2166773	test: 0.2283984	best: 0.2283984 (1880)	total: 28.1s	remaining: 38.6s
1900:	learn: 0.2164722	test: 0.2283565	best: 0.2283496 (1898)	total: 28.4s	remaining: 38.3s
1920:	learn: 0.2162665	test: 0.2282999	best: 0.2282999 (1920)	total: 28.7s	remaining: 38s
1940:	learn: 0.2160784	test: 0.2282447	best: 0.2282447 (1940)	total: 29s	remaining: 37.7s
1960:	learn: 0.2159010	test: 0.2282090	best: 0.2282090 (1960)	total: 29.3s	remaining: 37.4s
1980:	learn: 0.2157252	test: 0.2281750	best: 0.2281750 (1980)	total: 29.6s	remaining: 37.2s
2000:	learn: 0.2155446	test: 0.2281193	best: 0.2281193 (2000)	total: 29.9s	remaining: 36.8s
2020:	learn: 0.2153293	test: 0.2280621	best: 0.2280621 (2020)	total: 30.2s	remaining: 36.5s
2040:	learn: 0.2151509	test: 0.2280363	best: 0.2280345 (2039)	total: 30.5s	remaining: 36.3s
2060:	learn: 0.2149578	test: 0.2280020	best: 0.2280009 (2059)	total: 30.8s	remaining: 36s
2080:	learn: 0.2148031	test: 0.2280030	best: 0.2280009 (2059)	total: 31.1s	remaining: 35.7s
2100:	learn: 0.2146164	test: 0.2279405	best: 0.2279375 (2099)	total: 31.4s	remaining: 35.4s
2120:	learn: 0.2144496	test: 0.2278971	best: 0.2278971 (2120)	total: 31.7s	remaining: 35.1s
2140:	learn: 0.2142794	test: 0.2278655	best: 0.2278655 (2140)	total: 32s	remaining: 34.8s
2160:	learn: 0.2140972	test: 0.2278281	best: 0.2278281 (2160)	total: 32.3s	remaining: 34.5s
2180:	learn: 0.2139422	test: 0.2277930	best: 0.2277930 (2180)	total: 32.6s	remaining: 34.2s
2200:	learn: 0.2137857	test: 0.2277531	best: 0.2277531 (2200)	total: 32.9s	remaining: 33.9s
2220:	learn: 0.2136305	test: 0.2277260	best: 0.2277260 (2220)	total: 33.2s	remaining: 33.6s
2240:	learn: 0.2134550	test: 0.2276842	best: 0.2276842 (2240)	total: 33.5s	remaining: 33.3s
2260:	learn: 0.2132699	test: 0.2276465	best: 0.2276465 (2260)	total: 33.8s	remaining: 33s
2280:	learn: 0.2131096	test: 0.2276344	best: 0.2276261 (2273)	total: 34.1s	remaining: 32.7s
2300:	learn: 0.2129507	test: 0.2276050	best: 0.2276050 (2300)	total: 34.4s	remaining: 32.4s
2320:	learn: 0.2127871	test: 0.2275463	best: 0.2275463 (2320)	total: 34.6s	remaining: 32.1s
2340:	learn: 0.2126267	test: 0.2275396	best: 0.2275375 (2330)	total: 34.9s	remaining: 31.8s
2360:	learn: 0.2124478	test: 0.2275149	best: 0.2275144 (2353)	total: 35.2s	remaining: 31.5s
2380:	learn: 0.2122730	test: 0.2274814	best: 0.2274814 (2380)	total: 35.5s	remaining: 31.2s
2400:	learn: 0.2121164	test: 0.2274558	best: 0.2274558 (2400)	total: 35.9s	remaining: 30.9s
2420:	learn: 0.2119494	test: 0.2274072	best: 0.2274019 (2415)	total: 36.1s	remaining: 30.6s
2440:	learn: 0.2117856	test: 0.2273771	best: 0.2273749 (2436)	total: 36.4s	remaining: 30.3s
2460:	learn: 0.2116196	test: 0.2273305	best: 0.2273305 (2460)	total: 36.7s	remaining: 30s
2480:	learn: 0.2114491	test: 0.2272850	best: 0.2272850 (2480)	total: 37s	remaining: 29.7s
2500:	learn: 0.2112783	test: 0.2272359	best: 0.2272359 (2500)	total: 37.3s	remaining: 29.4s
2520:	learn: 0.2111149	test: 0.2271920	best: 0.2271920 (2520)	total: 37.6s	remaining: 29.1s
2540:	learn: 0.2109764	test: 0.2271815	best: 0.2271799 (2534)	total: 37.9s	remaining: 28.8s
2560:	learn: 0.2108266	test: 0.2271557	best: 0.2271543 (2556)	total: 38.2s	remaining: 28.5s
2580:	learn: 0.2106720	test: 0.2271211	best: 0.2271211 (2580)	total: 38.6s	remaining: 28.2s
2600:	learn: 0.2104971	test: 0.2270704	best: 0.2270664 (2598)	total: 38.9s	remaining: 27.9s
2620:	learn: 0.2103326	test: 0.2270436	best: 0.2270416 (2618)	total: 39.1s	remaining: 27.6s
2640:	learn: 0.2101571	test: 0.2270166	best: 0.2270166 (2640)	total: 39.4s	remaining: 27.3s
2660:	learn: 0.2100017	test: 0.2269973	best: 0.2269962 (2656)	total: 39.8s	remaining: 27s
2680:	learn: 0.2098284	test: 0.2269495	best: 0.2269489 (2677)	total: 40.1s	remaining: 26.7s
2700:	learn: 0.2096758	test: 0.2269154	best: 0.2269154 (2700)	total: 40.4s	remaining: 26.4s
2720:	learn: 0.2095039	test: 0.2268778	best: 0.2268778 (2720)	total: 40.6s	remaining: 26.1s
2740:	learn: 0.2093537	test: 0.2268532	best: 0.2268519 (2738)	total: 40.9s	remaining: 25.8s
2760:	learn: 0.2091848	test: 0.2268059	best: 0.2268059 (2760)	total: 41.2s	remaining: 25.5s
2780:	learn: 0.2090344	test: 0.2267777	best: 0.2267777 (2780)	total: 41.5s	remaining: 25.2s
2800:	learn: 0.2088801	test: 0.2267716	best: 0.2267699 (2797)	total: 41.8s	remaining: 24.9s
2820:	learn: 0.2087176	test: 0.2267376	best: 0.2267376 (2820)	total: 42.1s	remaining: 24.6s
2840:	learn: 0.2085544	test: 0.2267009	best: 0.2266957 (2838)	total: 42.4s	remaining: 24.3s
2860:	learn: 0.2084026	test: 0.2266700	best: 0.2266633 (2854)	total: 42.7s	remaining: 24s
2880:	learn: 0.2082495	test: 0.2266525	best: 0.2266525 (2880)	total: 43s	remaining: 23.7s
2900:	learn: 0.2080801	test: 0.2266112	best: 0.2266112 (2900)	total: 43.3s	remaining: 23.4s
2920:	learn: 0.2079201	test: 0.2265479	best: 0.2265479 (2920)	total: 43.6s	remaining: 23.1s
2940:	learn: 0.2077624	test: 0.2265155	best: 0.2265155 (2940)	total: 43.9s	remaining: 22.8s
2960:	learn: 0.2076150	test: 0.2264721	best: 0.2264665 (2959)	total: 44.3s	remaining: 22.6s
2980:	learn: 0.2074680	test: 0.2264602	best: 0.2264574 (2976)	total: 44.5s	remaining: 22.3s
3000:	learn: 0.2073235	test: 0.2264434	best: 0.2264417 (2993)	total: 44.8s	remaining: 22s
3020:	learn: 0.2071857	test: 0.2264285	best: 0.2264245 (3015)	total: 45.1s	remaining: 21.7s
3040:	learn: 0.2070533	test: 0.2263944	best: 0.2263886 (3039)	total: 45.4s	remaining: 21.4s
3060:	learn: 0.2069273	test: 0.2263873	best: 0.2263873 (3060)	total: 45.8s	remaining: 21.1s
3080:	learn: 0.2067754	test: 0.2263662	best: 0.2263647 (3079)	total: 46.1s	remaining: 20.8s
3100:	learn: 0.2066284	test: 0.2263391	best: 0.2263391 (3100)	total: 46.4s	remaining: 20.5s
3120:	learn: 0.2064838	test: 0.2263051	best: 0.2263051 (3120)	total: 46.7s	remaining: 20.2s
3140:	learn: 0.2063387	test: 0.2262744	best: 0.2262744 (3140)	total: 47s	remaining: 19.9s
3160:	learn: 0.2061912	test: 0.2262540	best: 0.2262540 (3160)	total: 47.3s	remaining: 19.6s
3180:	learn: 0.2060401	test: 0.2262269	best: 0.2262266 (3172)	total: 47.6s	remaining: 19.3s
3200:	learn: 0.2059064	test: 0.2262049	best: 0.2262045 (3199)	total: 47.9s	remaining: 19s
3220:	learn: 0.2057566	test: 0.2261802	best: 0.2261789 (3219)	total: 48.2s	remaining: 18.7s
3240:	learn: 0.2056198	test: 0.2261574	best: 0.2261519 (3239)	total: 48.5s	remaining: 18.4s
3260:	learn: 0.2054723	test: 0.2261405	best: 0.2261405 (3260)	total: 48.8s	remaining: 18.1s
3280:	learn: 0.2053275	test: 0.2261202	best: 0.2261169 (3275)	total: 49.1s	remaining: 17.8s
3300:	learn: 0.2051895	test: 0.2261026	best: 0.2261009 (3297)	total: 49.4s	remaining: 17.5s
3320:	learn: 0.2050499	test: 0.2260964	best: 0.2260953 (3318)	total: 49.7s	remaining: 17.2s
3340:	learn: 0.2048937	test: 0.2260866	best: 0.2260824 (3331)	total: 50s	remaining: 16.9s
3360:	learn: 0.2047613	test: 0.2260780	best: 0.2260780 (3360)	total: 50.3s	remaining: 16.6s
3380:	learn: 0.2046216	test: 0.2260698	best: 0.2260677 (3365)	total: 50.6s	remaining: 16.3s
3400:	learn: 0.2044776	test: 0.2260525	best: 0.2260525 (3400)	total: 50.9s	remaining: 16s
3420:	learn: 0.2043324	test: 0.2260357	best: 0.2260357 (3420)	total: 51.2s	remaining: 15.7s
3440:	learn: 0.2042071	test: 0.2260080	best: 0.2260059 (3433)	total: 51.5s	remaining: 15.4s
3460:	learn: 0.2040648	test: 0.2259800	best: 0.2259761 (3459)	total: 51.8s	remaining: 15.1s
3480:	learn: 0.2039287	test: 0.2259425	best: 0.2259425 (3480)	total: 52.1s	remaining: 14.8s
3500:	learn: 0.2037745	test: 0.2259126	best: 0.2259125 (3488)	total: 52.4s	remaining: 14.5s
3520:	learn: 0.2036243	test: 0.2258856	best: 0.2258737 (3516)	total: 52.7s	remaining: 14.2s
3540:	learn: 0.2034872	test: 0.2258835	best: 0.2258737 (3516)	total: 53s	remaining: 13.9s
3560:	learn: 0.2033498	test: 0.2258608	best: 0.2258608 (3560)	total: 53.3s	remaining: 13.6s
3580:	learn: 0.2032096	test: 0.2258430	best: 0.2258430 (3580)	total: 53.6s	remaining: 13.3s
3600:	learn: 0.2030604	test: 0.2258174	best: 0.2258126 (3596)	total: 53.9s	remaining: 13s
3620:	learn: 0.2029367	test: 0.2258028	best: 0.2258006 (3619)	total: 54.2s	remaining: 12.7s
3640:	learn: 0.2027986	test: 0.2257816	best: 0.2257813 (3639)	total: 54.5s	remaining: 12.4s
3660:	learn: 0.2026750	test: 0.2257736	best: 0.2257705 (3648)	total: 54.8s	remaining: 12.1s
3680:	learn: 0.2025488	test: 0.2257743	best: 0.2257686 (3670)	total: 55.1s	remaining: 11.8s
3700:	learn: 0.2024378	test: 0.2257613	best: 0.2257613 (3700)	total: 55.4s	remaining: 11.5s
3720:	learn: 0.2022952	test: 0.2257499	best: 0.2257441 (3709)	total: 55.7s	remaining: 11.2s
3740:	learn: 0.2021496	test: 0.2257210	best: 0.2257203 (3737)	total: 56s	remaining: 10.9s
3760:	learn: 0.2020121	test: 0.2257076	best: 0.2257060 (3758)	total: 56.3s	remaining: 10.6s
3780:	learn: 0.2018731	test: 0.2256992	best: 0.2256951 (3774)	total: 56.6s	remaining: 10.3s
3800:	learn: 0.2017323	test: 0.2256936	best: 0.2256936 (3800)	total: 56.9s	remaining: 10s
3820:	learn: 0.2016180	test: 0.2256846	best: 0.2256760 (3810)	total: 57.2s	remaining: 9.72s
3840:	learn: 0.2014882	test: 0.2256801	best: 0.2256760 (3810)	total: 57.5s	remaining: 9.42s
3860:	learn: 0.2013740	test: 0.2256873	best: 0.2256719 (3846)	total: 57.8s	remaining: 9.12s
3880:	learn: 0.2012291	test: 0.2256633	best: 0.2256617 (3875)	total: 58.1s	remaining: 8.82s
3900:	learn: 0.2010920	test: 0.2256362	best: 0.2256362 (3900)	total: 58.4s	remaining: 8.52s
3920:	learn: 0.2009487	test: 0.2256027	best: 0.2255952 (3914)	total: 58.7s	remaining: 8.22s
3940:	learn: 0.2008179	test: 0.2255976	best: 0.2255952 (3914)	total: 59s	remaining: 7.92s
3960:	learn: 0.2006964	test: 0.2255880	best: 0.2255844 (3959)	total: 59.3s	remaining: 7.62s
3980:	learn: 0.2005811	test: 0.2255777	best: 0.2255777 (3980)	total: 59.6s	remaining: 7.32s
4000:	learn: 0.2004355	test: 0.2255479	best: 0.2255394 (3997)	total: 59.9s	remaining: 7.02s
4020:	learn: 0.2003124	test: 0.2255402	best: 0.2255392 (4018)	total: 1m	remaining: 6.72s
4040:	learn: 0.2001702	test: 0.2255412	best: 0.2255392 (4018)	total: 1m	remaining: 6.42s
4060:	learn: 0.2000439	test: 0.2255262	best: 0.2255262 (4060)	total: 1m	remaining: 6.13s
4080:	learn: 0.1999180	test: 0.2255271	best: 0.2255194 (4070)	total: 1m 1s	remaining: 5.83s
4100:	learn: 0.1997822	test: 0.2255222	best: 0.2255149 (4085)	total: 1m 1s	remaining: 5.53s
4120:	learn: 0.1996603	test: 0.2255094	best: 0.2255094 (4120)	total: 1m 1s	remaining: 5.23s
4140:	learn: 0.1995270	test: 0.2255155	best: 0.2255026 (4122)	total: 1m 2s	remaining: 4.93s
4160:	learn: 0.1994030	test: 0.2255131	best: 0.2255026 (4122)	total: 1m 2s	remaining: 4.63s
4180:	learn: 0.1992671	test: 0.2254826	best: 0.2254813 (4178)	total: 1m 2s	remaining: 4.33s
4200:	learn: 0.1991434	test: 0.2254875	best: 0.2254721 (4185)	total: 1m 2s	remaining: 4.03s
4220:	learn: 0.1990289	test: 0.2254947	best: 0.2254721 (4185)	total: 1m 3s	remaining: 3.73s
bestTest = 0.2254720776
bestIteration = 4185
Shrink model to first 4186 iterations.

Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\model.pkl
	0.945	 = Validation score   (roc_auc)
	191.26s	 = Training   runtime
	0.16s	 = Validation runtime
	337358.3	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1606.95s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/5.0 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.3s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	0.945	 = Validation score   (roc_auc)
	0.07s	 = Training   runtime
	0.04s	 = Validation runtime
	326323.3	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
AutoGluon training complete, total runtime = 193.28s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 326323.3 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\CAT")

CAT completed.
Validation ROC-AUC: 0.944955

================================================================================
FINAL MODEL COMPARISON
================================================================================

,Model Family,Best AutoGluon Model,Validation ROC-AUC,Fit Time (sec),Predict Time (sec)
0,GBM,WeightedEnsemble_L2,0.949192,247.498546,11.124629
1,XGB,XGBoost_BAG_L1,0.948277,125.696552,1.501197
2,CAT,CatBoost_BAG_L1,0.944955,191.263761,0.162714

In [1]:
import os
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models4"

all_leaderboards = []

# ============================================================
# SCAN & LOAD ALL TRAINED PREDICTORS
# ============================================================

if os.path.exists(MODEL_DIR):
    # Check both subdirectories and root directory for saved predictors
    folder_candidates = [MODEL_DIR] + [
        os.path.join(MODEL_DIR, d) 
        for d in os.listdir(MODEL_DIR) 
        if os.path.isdir(os.path.join(MODEL_DIR, d))
    ]

    for folder_path in folder_candidates:
        # Check if directory contains a valid predictor file
        if os.path.exists(os.path.join(folder_path, "predictor.pkl")):
            try:
                folder_name = os.path.basename(folder_path)
                print(f"Loading predictor from: {folder_path}")
                
                # Load predictor from disk
                predictor = TabularPredictor.load(folder_path)
                
                # Fetch leaderboard
                lb = predictor.leaderboard(silent=True)
                lb.insert(0, "folder_name", folder_name)
                
                all_leaderboards.append(lb)
            except Exception as e:
                print(f"Failed to load predictor from {folder_path}: {e}")

# ============================================================
# MERGE AND PRESENT COMBINED LEADERBOARD
# ============================================================

if all_leaderboards:
    combined_leaderboard = pd.concat(all_leaderboards, ignore_index=True)

    # Sort all trained models by validation ROC-AUC score descending
    combined_leaderboard = combined_leaderboard.sort_values(
        by="score_val", ascending=False
    ).reset_index(drop=True)

    print("\n" + "=" * 80)
    print("COMBINED LEADERBOARD OF ALL LOADED MODELS")
    print("=" * 80)

    display(combined_leaderboard)
else:
    print(f"No valid AutoGluon predictors (`predictor.pkl`) found under '{MODEL_DIR}'.")

Loading predictor from: ./ag_models4\CAT
Loading predictor from: ./ag_models4\GBM
Loading predictor from: ./ag_models4\XGB

================================================================================
COMBINED LEADERBOARD OF ALL LOADED MODELS
================================================================================

,folder_name,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,GBM,WeightedEnsemble_L2,0.949192,roc_auc,11.124629,247.498546,0.040048,2.032160,2,True,3
1,GBM,LightGBM_BAG_L1,0.948594,roc_auc,4.325338,105.902930,4.325338,105.902930,1,True,1
2,XGB,XGBoost_BAG_L1,0.948277,roc_auc,1.501197,125.696552,1.501197,125.696552,1,True,1
3,XGB,WeightedEnsemble_L2,0.948277,roc_auc,1.541103,125.742321,0.039906,0.045769,2,True,2
4,GBM,LightGBMLarge_BAG_L1,0.948132,roc_auc,6.759242,139.563455,6.759242,139.563455,1,True,2
5,CAT,WeightedEnsemble_L2,0.944955,roc_auc,0.206733,191.333495,0.044019,0.069734,2,True,2
6,CAT,CatBoost_BAG_L1,0.944955,roc_auc,0.162714,191.263761,0.162714,191.263761,1,True,1

In [2]:
predictor = TabularPredictor.load("ag_models4/GBM")
predictor.info()

{'path': 'c:\\Darshak\\Projects\\Hackathon\\ag_models4\\GBM',
 'label': 'PitNextLap',
 'random_state': 0,
 'version': '1.6.1',
 'features': ['Compound',
  'Race',
  'Year',
  'PitStop',
  'LapNumber',
  'Stint',
  'TyreLife',
  'Position',
  'LapTime (s)',
  'LapTime_Delta',
  'Cumulative_Degradation',
  'RaceProgress',
  'Position_Change',
  'Stint_mean',
  'Stint_count',
  'Position_mean',
  'Position_count',
  'Compound_mean',
  'Compound_count',
  'Race_mean',
  'Race_count',
  'Driver_mean',
  'Driver_count',
  'LapNumber_digit_units',
  'LapNumber_digit_tens',
  'TyreLife_digit_units',
  'TyreLife_digit_tens',
  'LapTime (s)_digit_units',
  'LapTime (s)_digit_tens',
  'LapTime (s)_digit_hundreds',
  'LapTime_Delta_digit_units',
  'LapTime_Delta_digit_tens',
  'LapTime_Delta_digit_hundreds',
  'Cumulative_Degradation_digit_units',
  'Cumulative_Degradation_digit_tens',
  'Cumulative_Degradation_digit_hundreds',
  'RaceProgress_digit_units',
  'TyreLife_cat',
  'LapTime (s)_cat',
  'LapTime_Delta_cat',
  'Cumulative_Degradation_cat'],
 'feature_metadata_in': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc077d0>,
 'time_fit_preprocessing': 1.4397411346435547,
 'time_fit_training': 261.1305043697357,
 'time_fit_total': 262.5702455043793,
 'time_limit': 1800,
 'time_train_start': 1786379949.7849903,
 'num_rows_train': 439140,
 'num_cols_train': 41,
 'num_rows_val': None,
 'num_rows_test': None,
 'num_classes': 2,
 'problem_type': 'binary',
 'eval_metric': 'roc_auc',
 'best_model': 'WeightedEnsemble_L2',
 'best_model_score_val': np.float64(0.9491921037646196),
 'best_model_stack_level': 2,
 'num_models_trained': 3,
 'num_bag_folds': 8,
 'max_stack_level': 2,
 'max_core_stack_level': 1,
 'model_info': {'LightGBM_BAG_L1': {'name': 'LightGBM_BAG_L1',
   'model_type': 'StackerEnsembleModel',
   'problem_type': 'binary',
   'eval_metric': 'roc_auc',
   'stopping_metric': 'log_loss',
   'fit_time': 105.90293049812317,
   'num_classes': 2,
   'quantile_levels': None,
   'predict_time': 4.325338125228882,
   'val_score': np.float64(0.9485944595502239),
   'hyperparameters': {'use_orig_features': True,
    'valid_stacker': True,
    'max_base_models': 0,
    'max_base_models_per_type': 'auto',
    'save_bag_folds': True,
    'stratify': 'auto',
    'bin': 'auto',
    'n_bins': None,
    'vary_seed_across_folds': False,
    'custom_splits': None,
    'model_random_seed': 0},
   'hyperparameters_user': {},
   'hyperparameters_fit': {},
   'hyperparameters_nondefault': [],
   'ag_args_fit': {'max_memory_usage_ratio': 1.0,
    'max_gpu_memory_usage_ratio': 1.0,
    'max_time_limit_ratio': 1.0,
    'max_time_limit': None,
    'min_time_limit': 0,
    'valid_raw_types': None,
    'valid_special_types': None,
    'ignored_type_group_special': None,
    'ignored_type_group_raw': None,
    'get_features_kwargs': None,
    'get_features_kwargs_extra': None,
    'predict_1_batch_size': None,
    'temperature_scalar': None,
    'drop_unique': False},
   'num_features': 41,
   'features': ['Position',
    'PitStop',
    'Cumulative_Degradation_digit_hundreds',
    'Stint_count',
    'TyreLife_digit_units',
    'LapTime (s)_digit_hundreds',
    'Driver_mean',
    'LapTime_Delta_digit_units',
    'Compound_mean',
    'Position_count',
    'TyreLife',
    'Cumulative_Degradation',
    'LapTime_Delta_digit_hundreds',
    'Stint_mean',
    'Stint',
    'Compound',
    'TyreLife_digit_tens',
    'LapTime (s)_digit_units',
    'LapTime (s)_cat',
    'LapTime_Delta',
    'RaceProgress',
    'Position_Change',
    'Compound_count',
    'Driver_count',
    'Year',
    'TyreLife_cat',
    'Race',
    'LapNumber',
    'LapNumber_digit_tens',
    'Race_mean',
    'Cumulative_Degradation_cat',
    'Position_mean',
    'RaceProgress_digit_units',
    'LapTime_Delta_digit_tens',
    'LapNumber_digit_units',
    'Cumulative_Degradation_digit_tens',
    'LapTime (s)_digit_tens',
    'LapTime_Delta_cat',
    'Cumulative_Degradation_digit_units',
    'LapTime (s)',
    'Race_count'],
   'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc06d50>,
   'memory_size': 4982,
   'compile_time': None,
   'is_initialized': True,
   'is_fit': True,
   'is_valid': True,
   'can_infer': True,
   'has_learning_curves': False,
   'num_samples': 439140,
   'val_in_fit': False,
   'unlabeled_in_fit': False,
   'num_cpus': 16,
   'num_gpus': 1,
   'bagged_info': {'child_model_type': 'LGBModel',
    'num_child_models': 8,
    'child_model_names': ['S1F1',
     'S1F2',
     'S1F3',
     'S1F4',
     'S1F5',
     'S1F6',
     'S1F7',
     'S1F8'],
    '_n_repeats': 1,
    '_k_per_n_repeat': [8],
    '_random_state': 1,
    'low_memory': True,
    'bagged_mode': True,
    'max_memory_size': 77797693,
    'min_memory_size': 11420368,
    'child_hyperparameters': {'learning_rate': 0.05, 'seed': 0},
    'child_hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
    'child_hyperparameters_fit': {'num_boost_round': 2794},
    'child_ag_args_fit': {'max_memory_usage_ratio': 1.0,
     'max_gpu_memory_usage_ratio': 1.0,
     'max_time_limit_ratio': 1.0,
     'max_time_limit': None,
     'min_time_limit': 0,
     'valid_raw_types': ['bool', 'int', 'float', 'category'],
     'valid_special_types': None,
     'ignored_type_group_special': None,
     'ignored_type_group_raw': None,
     'get_features_kwargs': None,
     'get_features_kwargs_extra': None,
     'predict_1_batch_size': None,
     'temperature_scalar': None,
     'num_gpus': 1}},
   'stacker_info': {'num_base_models': 0, 'base_model_names': []},
   'children_info': {'S1F1': {'name': 'S1F1',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 12.987188339233398,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.509131669998169,
     'val_score': np.float64(0.9479601936194834),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 2647},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Stint_mean',
      'Stint_count',
      'Position_mean',
      'Position_count',
      'Compound_mean',
      'Compound_count',
      'Race_mean',
      'Race_count',
      'Driver_mean',
      'Driver_count',
      'LapNumber_digit_units',
      'LapNumber_digit_tens',
      'TyreLife_digit_units',
      'TyreLife_digit_tens',
      'LapTime (s)_digit_units',
      'LapTime (s)_digit_tens',
      'LapTime (s)_digit_hundreds',
      'LapTime_Delta_digit_units',
      'LapTime_Delta_digit_tens',
      'LapTime_Delta_digit_hundreds',
      'Cumulative_Degradation_digit_units',
      'Cumulative_Degradation_digit_tens',
      'Cumulative_Degradation_digit_hundreds',
      'RaceProgress_digit_units',
      'TyreLife_cat',
      'LapTime (s)_cat',
      'LapTime_Delta_cat',
      'Cumulative_Degradation_cat',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900e62c470>,
     'memory_size': 9215184,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 384247,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F2': {'name': 'S1F2',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 12.10496473312378,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.466235876083374,
     'val_score': np.float64(0.9484821792325466),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 2410},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Stint_mean',
      'Stint_count',
      'Position_mean',
      'Position_count',
      'Compound_mean',
      'Compound_count',
      'Race_mean',
      'Race_count',
      'Driver_mean',
      'Driver_count',
      'LapNumber_digit_units',
      'LapNumber_digit_tens',
      'TyreLife_digit_units',
      'TyreLife_digit_tens',
      'LapTime (s)_digit_units',
      'LapTime (s)_digit_tens',
      'LapTime (s)_digit_hundreds',
      'LapTime_Delta_digit_units',
      'LapTime_Delta_digit_tens',
      'LapTime_Delta_digit_hundreds',
      'Cumulative_Degradation_digit_units',
      'Cumulative_Degradation_digit_tens',
      'Cumulative_Degradation_digit_hundreds',
      'RaceProgress_digit_units',
      'TyreLife_cat',
      'LapTime (s)_cat',
      'LapTime_Delta_cat',
      'Cumulative_Degradation_cat',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc79790>,
     'memory_size': 8391480,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 384247,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F3': {'name': 'S1F3',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 13.10432744026184,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.570976972579956,
     'val_score': np.float64(0.9510729957012338),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 3014},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Stint_mean',
      'Stint_count',
      'Position_mean',
      'Position_count',
      'Compound_mean',
      'Compound_count',
      'Race_mean',
      'Race_count',
      'Driver_mean',
      'Driver_count',
      'LapNumber_digit_units',
      'LapNumber_digit_tens',
      'TyreLife_digit_units',
      'TyreLife_digit_tens',
      'LapTime (s)_digit_units',
      'LapTime (s)_digit_tens',
      'LapTime (s)_digit_hundreds',
      'LapTime_Delta_digit_units',
      'LapTime_Delta_digit_tens',
      'LapTime_Delta_digit_hundreds',
      'Cumulative_Degradation_digit_units',
      'Cumulative_Degradation_digit_tens',
      'Cumulative_Degradation_digit_hundreds',
      'RaceProgress_digit_units',
      'TyreLife_cat',
      'LapTime (s)_cat',
      'LapTime_Delta_cat',
      'Cumulative_Degradation_cat',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc79a90>,
     'memory_size': 10486085,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 384247,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F4': {'name': 'S1F4',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 12.213118314743042,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5166482925415039,
     'val_score': np.float64(0.9479603716390402),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 2746},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Stint_mean',
      'Stint_count',
      'Position_mean',
      'Position_count',
      'Compound_mean',
      'Compound_count',
      'Race_mean',
      'Race_count',
      'Driver_mean',
      'Driver_count',
      'LapNumber_digit_units',
      'LapNumber_digit_tens',
      'TyreLife_digit_units',
      'TyreLife_digit_tens',
      'LapTime (s)_digit_units',
      'LapTime (s)_digit_tens',
      'LapTime (s)_digit_hundreds',
      'LapTime_Delta_digit_units',
      'LapTime_Delta_digit_tens',
      'LapTime_Delta_digit_hundreds',
      'Cumulative_Degradation_digit_units',
      'Cumulative_Degradation_digit_tens',
      'Cumulative_Degradation_digit_hundreds',
      'RaceProgress_digit_units',
      'TyreLife_cat',
      'LapTime (s)_cat',
      'LapTime_Delta_cat',
      'Cumulative_Degradation_cat',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc7a330>,
     'memory_size': 9558907,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 384247,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F5': {'name': 'S1F5',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 12.256346702575684,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5189683437347412,
     'val_score': np.float64(0.9484868552585446),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 2684},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Stint_mean',
      'Stint_count',
      'Position_mean',
      'Position_count',
      'Compound_mean',
      'Compound_count',
      'Race_mean',
      'Race_count',
      'Driver_mean',
      'Driver_count',
      'LapNumber_digit_units',
      'LapNumber_digit_tens',
      'TyreLife_digit_units',
      'TyreLife_digit_tens',
      'LapTime (s)_digit_units',
      'LapTime (s)_digit_tens',
      'LapTime (s)_digit_hundreds',
      'LapTime_Delta_digit_units',
      'LapTime_Delta_digit_tens',
      'LapTime_Delta_digit_hundreds',
      'Cumulative_Degradation_digit_units',
      'Cumulative_Degradation_digit_tens',
      'Cumulative_Degradation_digit_hundreds',
      'RaceProgress_digit_units',
      'TyreLife_cat',
      'LapTime (s)_cat',
      'LapTime_Delta_cat',
      'Cumulative_Degradation_cat',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x2900fc7a450>,
     'memory_size': 9345204,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 384248,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F6': {'name': 'S1F6',
     'model_type': 'LGBModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 12.986938238143921,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5548136234283447,
     'val_score': np.float64(0.9475184914703334),
     'hyperparameters': {'learning_rate': 0.05, 'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'num_boost_round': 2653},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 41,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',

In [83]:
df=predictor.predict_proba(df_test)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\model.pkl

          0         1
0  0.995166  0.004834
1  0.996427  0.003573
2  0.996501  0.003499
3  0.876546  0.123454
4  0.123173  0.876827

In [84]:
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [85]:
df_sample_out['PitNextLap']=df[1]

In [86]:
df_sample_out.head()

       id  PitNextLap
0  439140    0.004834
1  439141    0.003573
2  439142    0.003499
3  439143    0.123454
4  439144    0.876827

In [87]:
df_sample_out.to_csv("My_output/feature_engineered_submission.csv")

In [3]:
### My sampling testing
from multi_sampling_test_predictor import process_and_evaluate_all_csvs
data_dict = process_and_evaluate_all_csvs(predictor,folder_path="Sampling_FE_data_to_test")

----------------------------------------
 Processing: sample_part_1_10000k.csv
----------------------------------------
ground_truth
0    8000
1    2000
Name: count, dtype: int64
--- Per-File Analysis [sample_part_1_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9273
Mismatches                         : 727
Accuracy (%)                       : 92.73
True Positives (Actual 1, Pred 1)  : 1602
True Negatives (Actual 0, Pred 0)  : 7671
False Positives (Actual 0, Pred 1) : 329
False Negatives (Actual 1, Pred 0) : 398
========================================

----------------------------------------
 Processing: sample_part_2_10000k.csv
----------------------------------------
ground_truth
0    8500
1    1500
Name: count, dtype: int64
--- Per-File Analysis [sample_part_2_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9336
Mismatches                         : 664
Accuracy (%)                       : 93.36
True Positives (Actual 1, Pred 1)  : 1189
True Negatives (Actual 0, Pred 0)  : 8147
False Positives (Actual 0, Pred 1) : 353
False Negatives (Actual 1, Pred 0) : 311
========================================

----------------------------------------
 Processing: sample_part_3_10000k.csv
----------------------------------------
ground_truth
0    7500
1    2500
Name: count, dtype: int64
--- Per-File Analysis [sample_part_3_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9158
Mismatches                         : 842
Accuracy (%)                       : 91.58
True Positives (Actual 1, Pred 1)  : 1987
True Negatives (Actual 0, Pred 0)  : 7171
False Positives (Actual 0, Pred 1) : 329
False Negatives (Actual 1, Pred 0) : 513
========================================

----------------------------------------
 Processing: sample_part_4_10000k.csv
----------------------------------------
ground_truth
0    7000
1    3000
Name: count, dtype: int64
--- Per-File Analysis [sample_part_4_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9106
Mismatches                         : 894
Accuracy (%)                       : 91.06
True Positives (Actual 1, Pred 1)  : 2380
True Negatives (Actual 0, Pred 0)  : 6726
False Positives (Actual 0, Pred 1) : 274
False Negatives (Actual 1, Pred 0) : 620
========================================

==================================================
      OVERALL CUMULATIVE ANALYSIS REPORT
==================================================
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 40000
Correct Matches                    : 36873
Mismatches                         : 3127
Accuracy (%)                       : 92.18
True Positives (Actual 1, Pred 1)  : 7158
True Negatives (Actual 0, Pred 0)  : 29715
False Positives (Actual 0, Pred 1) : 1285
False Negatives (Actual 1, Pred 0) : 1842
========================================