In [3]:
import pandas as pd
df_train=pd.read_csv('data/train.csv')
df_test=pd.read_csv('data/test.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [4]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [6]:
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [ ]:
# predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc').fit(
#     train_data=df_train,
#     ag_args_fit={"num_gpus": 2},
#     time_limit=3600*9,
#     presets='best_quality',
#     verbosity=3,
#     num_stack_levels=0
# )

In [9]:

TIME_LIMIT = 40 * 60   # 30 minutes

# Example: train ONE model
predictor = TabularPredictor(
    label=TARGET,
    eval_metric='roc_auc'
).fit(
    train_data=df_train_merged,
    hyperparameters={
        'GBM': {}
    },
    ag_args_fit={
        'num_gpus': 1
    },
    time_limit=TIME_LIMIT,
    verbosity=3,
    num_stack_levels=0
)

No path specified. Models will be saved in: "AutogluonModels\ag-20260810_090805"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.56 GB / 15.06 GB (17.0%)
Disk Space Avail:   724.66 GB / 930.47 GB (77.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1}, 'num_stack_levels': 0, 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': False,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\predictor.pkl
Beginning AutoGluon training ... Time limit = 2400s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2786.52 MB
	Train Data (Original)  Memory Usage: 136.13 MB (4.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.7s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.6% of available memory)
Data preprocessing and feature engineering runtime = 0.79s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\learner.pkl
Automatically generating train/validation split with holdout_frac=0.01, Train Rows: 535040, Val Rows: 5405
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
}
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\data\y.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\data\X_val.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\data\y_val.pkl
Model configs that will be trained (in order):
	LightGBM: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 2399.21s of the 2399.21s of remaining time.
	Fitting LightGBM with 'num_gpus': 1, 'num_cpus': 8
	Fitting with cpus=8, gpus=1, mem=0.3/2.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.275483
[100]	valid_set's binary_logloss: 0.254122
[150]	valid_set's binary_logloss: 0.247101
[200]	valid_set's binary_logloss: 0.243129
[250]	valid_set's binary_logloss: 0.240237
[300]	valid_set's binary_logloss: 0.237969
[350]	valid_set's binary_logloss: 0.235701
[400]	valid_set's binary_logloss: 0.234111
[450]	valid_set's binary_logloss: 0.232334
[500]	valid_set's binary_logloss: 0.231063
[550]	valid_set's binary_logloss: 0.229917
[600]	valid_set's binary_logloss: 0.229147
[650]	valid_set's binary_logloss: 0.228527
[700]	valid_set's binary_logloss: 0.227876
[750]	valid_set's binary_logloss: 0.227018
[800]	valid_set's binary_logloss: 0.22647
[850]	valid_set's binary_logloss: 0.226167
[900]	valid_set's binary_logloss: 0.225877
[950]	valid_set's binary_logloss: 0.225567
[1000]	valid_set's binary_logloss: 0.225277
[1050]	valid_set's binary_logloss: 0.224841
[1100]	valid_set's binary_logloss: 0.224583
[1150]	valid_set's binary_logloss: 0.2244
[1200]	valid_set's binary_logloss: 0.224356
[1250]	valid_set's binary_logloss: 0.223738
[1300]	valid_set's binary_logloss: 0.223543
[1350]	valid_set's binary_logloss: 0.22349
[1400]	valid_set's binary_logloss: 0.223302
[1450]	valid_set's binary_logloss: 0.223037
[1500]	valid_set's binary_logloss: 0.222898
[1550]	valid_set's binary_logloss: 0.222889
[1600]	valid_set's binary_logloss: 0.222903
[1650]	valid_set's binary_logloss: 0.222815
[1700]	valid_set's binary_logloss: 0.222589
[1750]	valid_set's binary_logloss: 0.222381
[1800]	valid_set's binary_logloss: 0.222539
[1850]	valid_set's binary_logloss: 0.222566
[1900]	valid_set's binary_logloss: 0.222524
[1950]	valid_set's binary_logloss: 0.222448
[2000]	valid_set's binary_logloss: 0.222297
[2050]	valid_set's binary_logloss: 0.222483
[2100]	valid_set's binary_logloss: 0.222273
[2150]	valid_set's binary_logloss: 0.222151
[2200]	valid_set's binary_logloss: 0.222214
[2250]	valid_set's binary_logloss: 0.221852
[2300]	valid_set's binary_logloss: 0.222006
[2350]	valid_set's binary_logloss: 0.221875
[2400]	valid_set's binary_logloss: 0.221945
[2450]	valid_set's binary_logloss: 0.222047
[2500]	valid_set's binary_logloss: 0.221951
[2550]	valid_set's binary_logloss: 0.222179
[2600]	valid_set's binary_logloss: 0.222144
[2650]	valid_set's binary_logloss: 0.222099
[2700]	valid_set's binary_logloss: 0.222042
[2750]	valid_set's binary_logloss: 0.222196
[2800]	valid_set's binary_logloss: 0.222092
[2850]	valid_set's binary_logloss: 0.221992
[2900]	valid_set's binary_logloss: 0.221909
[2950]	valid_set's binary_logloss: 0.221839

Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\LightGBM\model.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\attr\LightGBM\y_pred_proba_val.pkl
	0.952	 = Validation score   (roc_auc)
	12.78s	 = Training   runtime
	0.09s	 = Validation runtime
	62832.7	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\utils\attr\LightGBM\y_pred_proba_val.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 2386.24s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.6 GB
Ensemble size: 1
Ensemble weights:
[1.]
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBM': 1.0}
	0.952	 = Validation score   (roc_auc)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
	62157.3	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
AutoGluon training complete, total runtime = 13.91s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 62157.3 rows/s (5405 batch size)
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_090805")

In [10]:
predictor = TabularPredictor(
    label=TARGET,
    eval_metric='roc_auc'
).fit(
    train_data=df_train_merged,
    hyperparameters={
        'CAT': {}
    },
    ag_args_fit={
        'num_gpus': 1
    },
    time_limit=30 * 60,
    verbosity=3,
    num_stack_levels=0
)

No path specified. Models will be saved in: "AutogluonModels\ag-20260810_091043"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.30 GB / 15.06 GB (15.3%)
Disk Space Avail:   724.59 GB / 930.47 GB (77.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1}, 'num_stack_levels': 0, 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': False,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2543.63 MB
	Train Data (Original)  Memory Usage: 136.13 MB (5.4% of available memory)
	Warning: Data size prior to feature transformation consumes 5.4% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.8s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.7% of available memory)
Data preprocessing and feature engineering runtime = 0.83s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\learner.pkl
Automatically generating train/validation split with holdout_frac=0.01, Train Rows: 535040, Val Rows: 5405
User-specified model hyperparameters to be fit:
{
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\data\y.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\data\X_val.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\data\y_val.pkl
Model configs that will be trained (in order):
	CatBoost: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost ... Training model for up to 1799.17s of the 1799.17s of remaining time.
	Fitting CatBoost with 'num_gpus': 1, 'num_cpus': 8
	Fitting with cpus=8, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 8, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645674	test: 0.6639836	best: 0.6639836 (0)	total: 50.9ms	remaining: 50.9ms
1:	learn: 0.6387020	test: 0.6375287	best: 0.6375287 (1)	total: 55.5ms	remaining: 0us
bestTest = 0.6375287277
bestIteration = 1
0:	learn: 0.6399016	test: 0.6395524	best: 0.6395524 (0)	total: 20.8ms	remaining: 22.1s
20:	learn: 0.3351516	test: 0.3286870	best: 0.3286870 (20)	total: 425ms	remaining: 21.1s
40:	learn: 0.3022777	test: 0.2936625	best: 0.2936625 (40)	total: 839ms	remaining: 20.9s
60:	learn: 0.2889676	test: 0.2794733	best: 0.2794733 (60)	total: 1.26s	remaining: 20.7s
80:	learn: 0.2808662	test: 0.2719609	best: 0.2719609 (80)	total: 1.67s	remaining: 20.2s
100:	learn: 0.2744543	test: 0.2656587	best: 0.2656587 (100)	total: 2.1s	remaining: 20s
120:	learn: 0.2694177	test: 0.2606031	best: 0.2606031 (120)	total: 2.49s	remaining: 19.4s
140:	learn: 0.2654660	test: 0.2567623	best: 0.2567623 (140)	total: 2.87s	remaining: 18.8s
160:	learn: 0.2617526	test: 0.2533480	best: 0.2533480 (160)	total: 3.27s	remaining: 18.3s
180:	learn: 0.2586770	test: 0.2504645	best: 0.2504645 (180)	total: 3.66s	remaining: 17.8s
200:	learn: 0.2561395	test: 0.2485812	best: 0.2485812 (200)	total: 4.04s	remaining: 17.3s
220:	learn: 0.2540079	test: 0.2466809	best: 0.2466809 (220)	total: 4.42s	remaining: 16.8s
240:	learn: 0.2522080	test: 0.2453880	best: 0.2453880 (240)	total: 4.8s	remaining: 16.4s
260:	learn: 0.2506261	test: 0.2441675	best: 0.2441675 (260)	total: 5.18s	remaining: 15.9s
280:	learn: 0.2488218	test: 0.2425031	best: 0.2425031 (280)	total: 5.57s	remaining: 15.5s
300:	learn: 0.2470988	test: 0.2411347	best: 0.2411347 (300)	total: 5.95s	remaining: 15.1s
320:	learn: 0.2454905	test: 0.2398165	best: 0.2398165 (320)	total: 6.32s	remaining: 14.6s
340:	learn: 0.2443397	test: 0.2388501	best: 0.2388501 (340)	total: 6.7s	remaining: 14.2s
360:	learn: 0.2431678	test: 0.2379439	best: 0.2379439 (360)	total: 7.07s	remaining: 13.7s
380:	learn: 0.2419608	test: 0.2367682	best: 0.2367682 (380)	total: 7.45s	remaining: 13.3s
400:	learn: 0.2408541	test: 0.2357559	best: 0.2357559 (400)	total: 7.82s	remaining: 12.9s
420:	learn: 0.2394683	test: 0.2346371	best: 0.2346371 (420)	total: 8.19s	remaining: 12.5s
440:	learn: 0.2384070	test: 0.2338389	best: 0.2338389 (440)	total: 8.57s	remaining: 12.1s
460:	learn: 0.2375224	test: 0.2331983	best: 0.2331983 (460)	total: 8.94s	remaining: 11.7s
480:	learn: 0.2364843	test: 0.2323625	best: 0.2323625 (480)	total: 9.31s	remaining: 11.3s
500:	learn: 0.2358181	test: 0.2319045	best: 0.2319045 (500)	total: 9.69s	remaining: 10.9s
520:	learn: 0.2350258	test: 0.2313547	best: 0.2313547 (520)	total: 10.1s	remaining: 10.5s
540:	learn: 0.2342414	test: 0.2307152	best: 0.2307152 (540)	total: 10.4s	remaining: 10.1s
560:	learn: 0.2335718	test: 0.2302586	best: 0.2302586 (560)	total: 10.8s	remaining: 9.68s
580:	learn: 0.2328822	test: 0.2298109	best: 0.2298109 (580)	total: 11.2s	remaining: 9.28s
600:	learn: 0.2321321	test: 0.2293155	best: 0.2293155 (600)	total: 11.6s	remaining: 8.89s
620:	learn: 0.2314131	test: 0.2286931	best: 0.2286931 (620)	total: 11.9s	remaining: 8.5s
640:	learn: 0.2308919	test: 0.2284039	best: 0.2284039 (640)	total: 12.3s	remaining: 8.11s
660:	learn: 0.2303330	test: 0.2279384	best: 0.2279384 (660)	total: 12.7s	remaining: 7.72s
680:	learn: 0.2297262	test: 0.2273346	best: 0.2273346 (680)	total: 13.1s	remaining: 7.34s
700:	learn: 0.2292821	test: 0.2270924	best: 0.2270811 (699)	total: 13.5s	remaining: 6.95s
720:	learn: 0.2288104	test: 0.2267327	best: 0.2267327 (720)	total: 13.8s	remaining: 6.56s
740:	learn: 0.2283865	test: 0.2264791	best: 0.2264791 (740)	total: 14.2s	remaining: 6.17s
760:	learn: 0.2279639	test: 0.2262689	best: 0.2262689 (760)	total: 14.6s	remaining: 5.78s
780:	learn: 0.2274868	test: 0.2259498	best: 0.2259498 (780)	total: 14.9s	remaining: 5.39s
800:	learn: 0.2270078	test: 0.2255988	best: 0.2255988 (800)	total: 15.3s	remaining: 5.01s
820:	learn: 0.2265050	test: 0.2252786	best: 0.2252786 (820)	total: 15.7s	remaining: 4.62s
840:	learn: 0.2260439	test: 0.2250030	best: 0.2249986 (839)	total: 16.1s	remaining: 4.24s
860:	learn: 0.2255881	test: 0.2246022	best: 0.2246022 (860)	total: 16.4s	remaining: 3.86s
880:	learn: 0.2251446	test: 0.2242876	best: 0.2242876 (880)	total: 16.8s	remaining: 3.47s
900:	learn: 0.2247427	test: 0.2240227	best: 0.2240227 (900)	total: 17.2s	remaining: 3.09s
920:	learn: 0.2243066	test: 0.2236546	best: 0.2236546 (920)	total: 17.6s	remaining: 2.71s
940:	learn: 0.2238322	test: 0.2232977	best: 0.2232930 (938)	total: 18s	remaining: 2.33s
960:	learn: 0.2234617	test: 0.2229805	best: 0.2229787 (959)	total: 18.3s	remaining: 1.95s
980:	learn: 0.2230638	test: 0.2225828	best: 0.2225828 (980)	total: 18.7s	remaining: 1.56s
1000:	learn: 0.2227213	test: 0.2223616	best: 0.2223616 (1000)	total: 19.1s	remaining: 1.18s
1020:	learn: 0.2224031	test: 0.2221399	best: 0.2221399 (1020)	total: 19.5s	remaining: 800ms
1040:	learn: 0.2220999	test: 0.2219984	best: 0.2219984 (1040)	total: 19.8s	remaining: 419ms
1060:	learn: 0.2217845	test: 0.2216907	best: 0.2216907 (1060)	total: 20.2s	remaining: 38.1ms
1062:	learn: 0.2217518	test: 0.2216577	best: 0.2216577 (1062)	total: 20.2s	remaining: 0us
bestTest = 0.2216577352
bestIteration = 1062

Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\CatBoost\model.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\attr\CatBoost\y_pred_proba_val.pkl
	0.9526	 = Validation score   (roc_auc)
	23.37s	 = Training   runtime
	0.01s	 = Validation runtime
	468276.7	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\utils\attr\CatBoost\y_pred_proba_val.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1775.42s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.4 GB
Ensemble size: 1
Ensemble weights:
[1.]
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost': 1.0}
	0.9526	 = Validation score   (roc_auc)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
	443045.9	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
AutoGluon training complete, total runtime = 24.73s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 443045.9 rows/s (5405 batch size)
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091043")

In [11]:
predictor = TabularPredictor(
    label=TARGET,
    eval_metric='roc_auc'
).fit(
    train_data=df_train_merged,
    hyperparameters={
        'XGB': {}
    },
    ag_args_fit={
        'num_gpus': 1
    },
    time_limit=30 * 60,
    verbosity=3,
    num_stack_levels=0
)

No path specified. Models will be saved in: "AutogluonModels\ag-20260810_091122"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.58 GB / 15.06 GB (17.1%)
Disk Space Avail:   709.14 GB / 930.47 GB (76.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1}, 'num_stack_levels': 0, 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': False,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2687.45 MB
	Train Data (Original)  Memory Usage: 136.13 MB (5.1% of available memory)
	Warning: Data size prior to feature transformation consumes 5.1% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.2s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.9s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.6% of available memory)
Data preprocessing and feature engineering runtime = 1.0s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\learner.pkl
Automatically generating train/validation split with holdout_frac=0.01, Train Rows: 535040, Val Rows: 5405
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\data\y.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\data\X_val.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\data\y_val.pkl
Model configs that will be trained (in order):
	XGBoost: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost ... Training model for up to 1799.00s of the 1798.99s of remaining time.
	Fitting XGBoost with 'num_gpus': 1, 'num_cpus': 8
	Fitting with cpus=8, gpus=1

[0]	validation_0-logloss:0.47212
[50]	validation_0-logloss:0.25951
[100]	validation_0-logloss:0.24524
[150]	validation_0-logloss:0.23813
[200]	validation_0-logloss:0.23298
[250]	validation_0-logloss:0.22875
[300]	validation_0-logloss:0.22543
[350]	validation_0-logloss:0.22310
[400]	validation_0-logloss:0.22115
[450]	validation_0-logloss:0.21867
[500]	validation_0-logloss:0.21727
[550]	validation_0-logloss:0.21599
[600]	validation_0-logloss:0.21484
[650]	validation_0-logloss:0.21368
[700]	validation_0-logloss:0.21248
[750]	validation_0-logloss:0.21201
[800]	validation_0-logloss:0.21140
[850]	validation_0-logloss:0.21073
[900]	validation_0-logloss:0.20961
[950]	validation_0-logloss:0.20896
[1000]	validation_0-logloss:0.20862
[1050]	validation_0-logloss:0.20846
[1100]	validation_0-logloss:0.20808
[1150]	validation_0-logloss:0.20757
[1200]	validation_0-logloss:0.20732
[1250]	validation_0-logloss:0.20701
[1300]	validation_0-logloss:0.20666
[1350]	validation_0-logloss:0.20621
[1400]	validation_0-logloss:0.20636
[1450]	validation_0-logloss:0.20648
[1500]	validation_0-logloss:0.20665
[1550]	validation_0-logloss:0.20622
[1600]	validation_0-logloss:0.20613
[1650]	validation_0-logloss:0.20598
[1700]	validation_0-logloss:0.20609
[1750]	validation_0-logloss:0.20572
[1800]	validation_0-logloss:0.20551
[1850]	validation_0-logloss:0.20535
[1900]	validation_0-logloss:0.20513
[1950]	validation_0-logloss:0.20484
[2000]	validation_0-logloss:0.20468
[2050]	validation_0-logloss:0.20457
[2100]	validation_0-logloss:0.20445
[2150]	validation_0-logloss:0.20442
[2200]	validation_0-logloss:0.20436
[2250]	validation_0-logloss:0.20421
[2300]	validation_0-logloss:0.20390
[2350]	validation_0-logloss:0.20406
[2400]	validation_0-logloss:0.20390
[2450]	validation_0-logloss:0.20391
[2500]	validation_0-logloss:0.20389
[2550]	validation_0-logloss:0.20361
[2600]	validation_0-logloss:0.20354
[2650]	validation_0-logloss:0.20337
[2700]	validation_0-logloss:0.20333
[2750]	validation_0-logloss:0.20335
[2800]	validation_0-logloss:0.20348
[2850]	validation_0-logloss:0.20324
[2900]	validation_0-logloss:0.20308
[2950]	validation_0-logloss:0.20303
[3000]	validation_0-logloss:0.20296
[3050]	validation_0-logloss:0.20270
[3100]	validation_0-logloss:0.20261
[3150]	validation_0-logloss:0.20252
[3200]	validation_0-logloss:0.20285
[3250]	validation_0-logloss:0.20296
[3300]	validation_0-logloss:0.20309
[3350]	validation_0-logloss:0.20303
[3400]	validation_0-logloss:0.20294
[3450]	validation_0-logloss:0.20283
[3500]	validation_0-logloss:0.20287
[3550]	validation_0-logloss:0.20291
[3600]	validation_0-logloss:0.20298
[3650]	validation_0-logloss:0.20311
[3700]	validation_0-logloss:0.20320
[3750]	validation_0-logloss:0.20337
[3800]	validation_0-logloss:0.20335
[3850]	validation_0-logloss:0.20352
[3900]	validation_0-logloss:0.20345
[3950]	validation_0-logloss:0.20368
[4000]	validation_0-logloss:0.20375
[4050]	validation_0-logloss:0.20388
[4099]	validation_0-logloss:0.20398

Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\XGBoost\model.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\attr\XGBoost\y_pred_proba_val.pkl
	0.9605	 = Validation score   (roc_auc)
	34.85s	 = Training   runtime
	0.05s	 = Validation runtime
	100501.0	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\utils\attr\XGBoost\y_pred_proba_val.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1764.01s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.6 GB
Ensemble size: 1
Ensemble weights:
[1.]
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost': 1.0}
	0.9605	 = Validation score   (roc_auc)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
	98688.4	 = Inference  throughput (rows/s | 5405 batch size)
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
AutoGluon training complete, total runtime = 36.15s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 98688.4 rows/s (5405 batch size)
Loading: c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\learner.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\AutogluonModels\ag-20260810_091122")

In [24]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [ ]:
import os
import shutil
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models2"
TIME_LIMIT = 30 * 60  # 30 minutes (1800 seconds) per model family

models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

# ============================================================
# DELETE OLD MODELS
# ============================================================

if os.path.exists(MODEL_DIR):
    print(f"Deleting existing model directory: {MODEL_DIR}")
    shutil.rmtree(MODEL_DIR)

os.makedirs(MODEL_DIR, exist_ok=True)
print(f"Fresh model directory created: {MODEL_DIR}")

# ============================================================
# TRAIN ONE MODEL AT A TIME
# ============================================================

predictors = {}
results = []

for model_name, model_config in models.items():

    model_path = os.path.join(MODEL_DIR, model_name)

    print("\n" + "=" * 80)
    print(f"TRAINING: {model_name}")
    print(f"TIME LIMIT: 30 MINUTES")
    print(f"MODEL PATH: {model_path}")
    print("=" * 80)

    predictor = TabularPredictor(
        label=TARGET,
        eval_metric='roc_auc',
        path=model_path
    ).fit(
        train_data=df_train_merged,
        presets="best_quality",  # Enables bagging (_BAG_L1) and out-of-fold validation
        hyperparameters={model_name: model_config},  # Maps key to config dict properly
        ag_args_fit={
            'num_gpus': 1
        },
        time_limit=TIME_LIMIT,
        verbosity=3,
        num_stack_levels=0
    )

    predictors[model_name] = predictor

    # ========================================================
    # GET RESULT
    # ========================================================

    leaderboard = predictor.leaderboard(silent=True)
    best_row = leaderboard.iloc[0]

    results.append({
        'Model Family': model_name,
        'Best AutoGluon Model': best_row['model'],
        'Validation ROC-AUC': best_row['score_val'],
        'Fit Time (sec)': best_row['fit_time'],
        'Predict Time (sec)': best_row['pred_time_val']
    })

    print(f"\n{model_name} completed.")
    print(f"Validation ROC-AUC: {best_row['score_val']:.6f}")

# ============================================================
# FINAL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    'Validation ROC-AUC',
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 80)
print("FINAL MODEL COMPARISON")
print("=" * 80)

display(results_df)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.87 GB / 15.06 GB (19.1%)
Disk Space Avail:   724.91 GB / 930.47 GB (77.9%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models2\GBM"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

Deleting existing model directory: ./ag_models2
Fresh model directory created: ./ag_models2

================================================================================
TRAINING: GBM
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models2\GBM
================================================================================

	Available Memory:                    2996.13 MB
	Train Data (Original)  Memory Usage: 136.13 MB (4.5% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.7s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.5% of available memory)
Data preprocessing and feature engineering runtime = 0.8s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1799.20s of the 1799.20s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
Will use sequential fold fitting strategy because import of ray failed. Reason: ray is required to train folds in parallel for TabularPredictor or HPO for MultiModalPredictor. A quick tip is to install via `pip install "ray>=2.43.0,<2.57.0"`
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281445
[100]	valid_set's binary_logloss: 0.260036
[150]	valid_set's binary_logloss: 0.25199
[200]	valid_set's binary_logloss: 0.247187
[250]	valid_set's binary_logloss: 0.243627
[300]	valid_set's binary_logloss: 0.240783
[350]	valid_set's binary_logloss: 0.23862
[400]	valid_set's binary_logloss: 0.236582
[450]	valid_set's binary_logloss: 0.234896
[500]	valid_set's binary_logloss: 0.233701
[550]	valid_set's binary_logloss: 0.232697
[600]	valid_set's binary_logloss: 0.231964
[650]	valid_set's binary_logloss: 0.231146
[700]	valid_set's binary_logloss: 0.230417
[750]	valid_set's binary_logloss: 0.22974
[800]	valid_set's binary_logloss: 0.229188
[850]	valid_set's binary_logloss: 0.228568
[900]	valid_set's binary_logloss: 0.228074
[950]	valid_set's binary_logloss: 0.227555
[1000]	valid_set's binary_logloss: 0.227149
[1050]	valid_set's binary_logloss: 0.226735
[1100]	valid_set's binary_logloss: 0.226487
[1150]	valid_set's binary_logloss: 0.226146
[1200]	valid_set's binary_logloss: 0.225909
[1250]	valid_set's binary_logloss: 0.225707
[1300]	valid_set's binary_logloss: 0.225554
[1350]	valid_set's binary_logloss: 0.225443
[1400]	valid_set's binary_logloss: 0.225253
[1450]	valid_set's binary_logloss: 0.225081
[1500]	valid_set's binary_logloss: 0.224978
[1550]	valid_set's binary_logloss: 0.22483
[1600]	valid_set's binary_logloss: 0.22477
[1650]	valid_set's binary_logloss: 0.224682
[1700]	valid_set's binary_logloss: 0.224616
[1750]	valid_set's binary_logloss: 0.224502
[1800]	valid_set's binary_logloss: 0.224477
[1850]	valid_set's binary_logloss: 0.224346
[1900]	valid_set's binary_logloss: 0.224333
[1950]	valid_set's binary_logloss: 0.224322
[2000]	valid_set's binary_logloss: 0.224394
[2050]	valid_set's binary_logloss: 0.224387
[2100]	valid_set's binary_logloss: 0.22446
[2150]	valid_set's binary_logloss: 0.224512
[2200]	valid_set's binary_logloss: 0.224612
[2250]	valid_set's binary_logloss: 0.224649
[2300]	valid_set's binary_logloss: 0.224662
[2350]	valid_set's binary_logloss: 0.224703
[2400]	valid_set's binary_logloss: 0.224775
[2450]	valid_set's binary_logloss: 0.224825
[2500]	valid_set's binary_logloss: 0.224891
[2550]	valid_set's binary_logloss: 0.22494

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283034
[100]	valid_set's binary_logloss: 0.261641
[150]	valid_set's binary_logloss: 0.25394
[200]	valid_set's binary_logloss: 0.248926
[250]	valid_set's binary_logloss: 0.245444
[300]	valid_set's binary_logloss: 0.242644
[350]	valid_set's binary_logloss: 0.240329
[400]	valid_set's binary_logloss: 0.238109
[450]	valid_set's binary_logloss: 0.236788
[500]	valid_set's binary_logloss: 0.23558
[550]	valid_set's binary_logloss: 0.234712
[600]	valid_set's binary_logloss: 0.233943
[650]	valid_set's binary_logloss: 0.233117
[700]	valid_set's binary_logloss: 0.232533
[750]	valid_set's binary_logloss: 0.231818
[800]	valid_set's binary_logloss: 0.231282
[850]	valid_set's binary_logloss: 0.230866
[900]	valid_set's binary_logloss: 0.230417
[950]	valid_set's binary_logloss: 0.230038
[1000]	valid_set's binary_logloss: 0.2298
[1050]	valid_set's binary_logloss: 0.229532
[1100]	valid_set's binary_logloss: 0.229189
[1150]	valid_set's binary_logloss: 0.228974
[1200]	valid_set's binary_logloss: 0.228749
[1250]	valid_set's binary_logloss: 0.228551
[1300]	valid_set's binary_logloss: 0.228447
[1350]	valid_set's binary_logloss: 0.228242
[1400]	valid_set's binary_logloss: 0.22803
[1450]	valid_set's binary_logloss: 0.227882
[1500]	valid_set's binary_logloss: 0.227818
[1550]	valid_set's binary_logloss: 0.227738
[1600]	valid_set's binary_logloss: 0.227672
[1650]	valid_set's binary_logloss: 0.227508
[1700]	valid_set's binary_logloss: 0.22747
[1750]	valid_set's binary_logloss: 0.227384
[1800]	valid_set's binary_logloss: 0.227391
[1850]	valid_set's binary_logloss: 0.227296
[1900]	valid_set's binary_logloss: 0.227197
[1950]	valid_set's binary_logloss: 0.22715
[2000]	valid_set's binary_logloss: 0.227122
[2050]	valid_set's binary_logloss: 0.227079
[2100]	valid_set's binary_logloss: 0.22703
[2150]	valid_set's binary_logloss: 0.226968
[2200]	valid_set's binary_logloss: 0.226943
[2250]	valid_set's binary_logloss: 0.226943
[2300]	valid_set's binary_logloss: 0.226978
[2350]	valid_set's binary_logloss: 0.226999
[2400]	valid_set's binary_logloss: 0.227064
[2450]	valid_set's binary_logloss: 0.227092
[2500]	valid_set's binary_logloss: 0.227155
[2550]	valid_set's binary_logloss: 0.227231
[2600]	valid_set's binary_logloss: 0.227211
[2650]	valid_set's binary_logloss: 0.227195
[2700]	valid_set's binary_logloss: 0.227241
[2750]	valid_set's binary_logloss: 0.227211
[2800]	valid_set's binary_logloss: 0.227256
[2850]	valid_set's binary_logloss: 0.227345
[2900]	valid_set's binary_logloss: 0.227369

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284233
[100]	valid_set's binary_logloss: 0.263106
[150]	valid_set's binary_logloss: 0.255162
[200]	valid_set's binary_logloss: 0.249785
[250]	valid_set's binary_logloss: 0.246171
[300]	valid_set's binary_logloss: 0.243716
[350]	valid_set's binary_logloss: 0.241568
[400]	valid_set's binary_logloss: 0.239231
[450]	valid_set's binary_logloss: 0.237637
[500]	valid_set's binary_logloss: 0.236701
[550]	valid_set's binary_logloss: 0.235853
[600]	valid_set's binary_logloss: 0.235213
[650]	valid_set's binary_logloss: 0.234525
[700]	valid_set's binary_logloss: 0.233696
[750]	valid_set's binary_logloss: 0.233122
[800]	valid_set's binary_logloss: 0.232638
[850]	valid_set's binary_logloss: 0.232194
[900]	valid_set's binary_logloss: 0.231854
[950]	valid_set's binary_logloss: 0.231392
[1000]	valid_set's binary_logloss: 0.231064
[1050]	valid_set's binary_logloss: 0.230707
[1100]	valid_set's binary_logloss: 0.230511
[1150]	valid_set's binary_logloss: 0.230258
[1200]	valid_set's binary_logloss: 0.230025
[1250]	valid_set's binary_logloss: 0.229946
[1300]	valid_set's binary_logloss: 0.229712
[1350]	valid_set's binary_logloss: 0.229568
[1400]	valid_set's binary_logloss: 0.229532
[1450]	valid_set's binary_logloss: 0.229415
[1500]	valid_set's binary_logloss: 0.229346
[1550]	valid_set's binary_logloss: 0.229351
[1600]	valid_set's binary_logloss: 0.229284
[1650]	valid_set's binary_logloss: 0.229221
[1700]	valid_set's binary_logloss: 0.229179
[1750]	valid_set's binary_logloss: 0.229102
[1800]	valid_set's binary_logloss: 0.229084
[1850]	valid_set's binary_logloss: 0.229098
[1900]	valid_set's binary_logloss: 0.229079
[1950]	valid_set's binary_logloss: 0.229055
[2000]	valid_set's binary_logloss: 0.229097
[2050]	valid_set's binary_logloss: 0.2291
[2100]	valid_set's binary_logloss: 0.229126
[2150]	valid_set's binary_logloss: 0.229259
[2200]	valid_set's binary_logloss: 0.229332
[2250]	valid_set's binary_logloss: 0.229397
[2300]	valid_set's binary_logloss: 0.229434
[2350]	valid_set's binary_logloss: 0.229457
[2400]	valid_set's binary_logloss: 0.229527
[2450]	valid_set's binary_logloss: 0.229653
[2500]	valid_set's binary_logloss: 0.229769

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281039
[100]	valid_set's binary_logloss: 0.259556
[150]	valid_set's binary_logloss: 0.25177
[200]	valid_set's binary_logloss: 0.246534
[250]	valid_set's binary_logloss: 0.243425
[300]	valid_set's binary_logloss: 0.240826
[350]	valid_set's binary_logloss: 0.238307
[400]	valid_set's binary_logloss: 0.236305
[450]	valid_set's binary_logloss: 0.234873
[500]	valid_set's binary_logloss: 0.233571
[550]	valid_set's binary_logloss: 0.232608
[600]	valid_set's binary_logloss: 0.23171
[650]	valid_set's binary_logloss: 0.231068
[700]	valid_set's binary_logloss: 0.23039
[750]	valid_set's binary_logloss: 0.229993
[800]	valid_set's binary_logloss: 0.229392
[850]	valid_set's binary_logloss: 0.228903
[900]	valid_set's binary_logloss: 0.228552
[950]	valid_set's binary_logloss: 0.228256
[1000]	valid_set's binary_logloss: 0.227898
[1050]	valid_set's binary_logloss: 0.227445
[1100]	valid_set's binary_logloss: 0.227093
[1150]	valid_set's binary_logloss: 0.226727
[1200]	valid_set's binary_logloss: 0.226528
[1250]	valid_set's binary_logloss: 0.226295
[1300]	valid_set's binary_logloss: 0.226131
[1350]	valid_set's binary_logloss: 0.225936
[1400]	valid_set's binary_logloss: 0.225817
[1450]	valid_set's binary_logloss: 0.225722
[1500]	valid_set's binary_logloss: 0.225548
[1550]	valid_set's binary_logloss: 0.225398
[1600]	valid_set's binary_logloss: 0.225353
[1650]	valid_set's binary_logloss: 0.225349
[1700]	valid_set's binary_logloss: 0.225291
[1750]	valid_set's binary_logloss: 0.225312
[1800]	valid_set's binary_logloss: 0.225308
[1850]	valid_set's binary_logloss: 0.225316
[1900]	valid_set's binary_logloss: 0.22526
[1950]	valid_set's binary_logloss: 0.225287
[2000]	valid_set's binary_logloss: 0.225315
[2050]	valid_set's binary_logloss: 0.225363
[2100]	valid_set's binary_logloss: 0.22542
[2150]	valid_set's binary_logloss: 0.225463
[2200]	valid_set's binary_logloss: 0.225541
[2250]	valid_set's binary_logloss: 0.22562
[2300]	valid_set's binary_logloss: 0.225657
[2350]	valid_set's binary_logloss: 0.225729
[2400]	valid_set's binary_logloss: 0.225798
[2450]	valid_set's binary_logloss: 0.225872
[2500]	valid_set's binary_logloss: 0.225954

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282259
[100]	valid_set's binary_logloss: 0.260393
[150]	valid_set's binary_logloss: 0.252154
[200]	valid_set's binary_logloss: 0.24726
[250]	valid_set's binary_logloss: 0.243428
[300]	valid_set's binary_logloss: 0.240235
[350]	valid_set's binary_logloss: 0.23805
[400]	valid_set's binary_logloss: 0.23643
[450]	valid_set's binary_logloss: 0.234675
[500]	valid_set's binary_logloss: 0.233598
[550]	valid_set's binary_logloss: 0.232503
[600]	valid_set's binary_logloss: 0.231608
[650]	valid_set's binary_logloss: 0.230801
[700]	valid_set's binary_logloss: 0.229955
[750]	valid_set's binary_logloss: 0.229237
[800]	valid_set's binary_logloss: 0.228719
[850]	valid_set's binary_logloss: 0.228115
[900]	valid_set's binary_logloss: 0.227697
[950]	valid_set's binary_logloss: 0.227309
[1000]	valid_set's binary_logloss: 0.226974
[1050]	valid_set's binary_logloss: 0.226609
[1100]	valid_set's binary_logloss: 0.226343
[1150]	valid_set's binary_logloss: 0.226106
[1200]	valid_set's binary_logloss: 0.225863
[1250]	valid_set's binary_logloss: 0.22561
[1300]	valid_set's binary_logloss: 0.22545
[1350]	valid_set's binary_logloss: 0.225353
[1400]	valid_set's binary_logloss: 0.225162
[1450]	valid_set's binary_logloss: 0.224977
[1500]	valid_set's binary_logloss: 0.224807
[1550]	valid_set's binary_logloss: 0.224715
[1600]	valid_set's binary_logloss: 0.224542
[1650]	valid_set's binary_logloss: 0.224388
[1700]	valid_set's binary_logloss: 0.224392
[1750]	valid_set's binary_logloss: 0.224373
[1800]	valid_set's binary_logloss: 0.224368
[1850]	valid_set's binary_logloss: 0.224358
[1900]	valid_set's binary_logloss: 0.224356
[1950]	valid_set's binary_logloss: 0.224354
[2000]	valid_set's binary_logloss: 0.224395
[2050]	valid_set's binary_logloss: 0.224416
[2100]	valid_set's binary_logloss: 0.224452
[2150]	valid_set's binary_logloss: 0.22447
[2200]	valid_set's binary_logloss: 0.224521
[2250]	valid_set's binary_logloss: 0.224512
[2300]	valid_set's binary_logloss: 0.224496
[2350]	valid_set's binary_logloss: 0.224571

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281744
[100]	valid_set's binary_logloss: 0.259387
[150]	valid_set's binary_logloss: 0.251677
[200]	valid_set's binary_logloss: 0.247061
[250]	valid_set's binary_logloss: 0.243246
[300]	valid_set's binary_logloss: 0.240711
[350]	valid_set's binary_logloss: 0.238346
[400]	valid_set's binary_logloss: 0.236547
[450]	valid_set's binary_logloss: 0.234803
[500]	valid_set's binary_logloss: 0.233715
[550]	valid_set's binary_logloss: 0.232658
[600]	valid_set's binary_logloss: 0.23165
[650]	valid_set's binary_logloss: 0.230861
[700]	valid_set's binary_logloss: 0.230226
[750]	valid_set's binary_logloss: 0.22972
[800]	valid_set's binary_logloss: 0.229181
[850]	valid_set's binary_logloss: 0.228636
[900]	valid_set's binary_logloss: 0.228302
[950]	valid_set's binary_logloss: 0.227761
[1000]	valid_set's binary_logloss: 0.227359
[1050]	valid_set's binary_logloss: 0.227053
[1100]	valid_set's binary_logloss: 0.2268
[1150]	valid_set's binary_logloss: 0.226516
[1200]	valid_set's binary_logloss: 0.226351
[1250]	valid_set's binary_logloss: 0.22601
[1300]	valid_set's binary_logloss: 0.22575
[1350]	valid_set's binary_logloss: 0.225628
[1400]	valid_set's binary_logloss: 0.225489
[1450]	valid_set's binary_logloss: 0.225394
[1500]	valid_set's binary_logloss: 0.225316
[1550]	valid_set's binary_logloss: 0.225218
[1600]	valid_set's binary_logloss: 0.225122
[1650]	valid_set's binary_logloss: 0.225038
[1700]	valid_set's binary_logloss: 0.22492
[1750]	valid_set's binary_logloss: 0.22481
[1800]	valid_set's binary_logloss: 0.224882
[1850]	valid_set's binary_logloss: 0.224889
[1900]	valid_set's binary_logloss: 0.224882
[1950]	valid_set's binary_logloss: 0.224927
[2000]	valid_set's binary_logloss: 0.224935
[2050]	valid_set's binary_logloss: 0.224977
[2100]	valid_set's binary_logloss: 0.224925
[2150]	valid_set's binary_logloss: 0.224951
[2200]	valid_set's binary_logloss: 0.225031
[2250]	valid_set's binary_logloss: 0.225051
[2300]	valid_set's binary_logloss: 0.225075

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.27958
[100]	valid_set's binary_logloss: 0.259089
[150]	valid_set's binary_logloss: 0.251672
[200]	valid_set's binary_logloss: 0.246665
[250]	valid_set's binary_logloss: 0.243094
[300]	valid_set's binary_logloss: 0.240373
[350]	valid_set's binary_logloss: 0.238276
[400]	valid_set's binary_logloss: 0.236621
[450]	valid_set's binary_logloss: 0.235106
[500]	valid_set's binary_logloss: 0.233975
[550]	valid_set's binary_logloss: 0.232971
[600]	valid_set's binary_logloss: 0.231852
[650]	valid_set's binary_logloss: 0.231218
[700]	valid_set's binary_logloss: 0.2305
[750]	valid_set's binary_logloss: 0.229842
[800]	valid_set's binary_logloss: 0.229111
[850]	valid_set's binary_logloss: 0.228802
[900]	valid_set's binary_logloss: 0.228509
[950]	valid_set's binary_logloss: 0.228123
[1000]	valid_set's binary_logloss: 0.227796
[1050]	valid_set's binary_logloss: 0.227594
[1100]	valid_set's binary_logloss: 0.227442
[1150]	valid_set's binary_logloss: 0.227276
[1200]	valid_set's binary_logloss: 0.227149
[1250]	valid_set's binary_logloss: 0.226938
[1300]	valid_set's binary_logloss: 0.226826
[1350]	valid_set's binary_logloss: 0.226722
[1400]	valid_set's binary_logloss: 0.226607
[1450]	valid_set's binary_logloss: 0.226452
[1500]	valid_set's binary_logloss: 0.226304
[1550]	valid_set's binary_logloss: 0.226273
[1600]	valid_set's binary_logloss: 0.226153
[1650]	valid_set's binary_logloss: 0.226055
[1700]	valid_set's binary_logloss: 0.226048
[1750]	valid_set's binary_logloss: 0.226075
[1800]	valid_set's binary_logloss: 0.226105
[1850]	valid_set's binary_logloss: 0.226073
[1900]	valid_set's binary_logloss: 0.226107
[1950]	valid_set's binary_logloss: 0.226153
[2000]	valid_set's binary_logloss: 0.226217
[2050]	valid_set's binary_logloss: 0.226362
[2100]	valid_set's binary_logloss: 0.226414
[2150]	valid_set's binary_logloss: 0.226515
[2200]	valid_set's binary_logloss: 0.226589

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.279247
[100]	valid_set's binary_logloss: 0.257587
[150]	valid_set's binary_logloss: 0.249825
[200]	valid_set's binary_logloss: 0.244982
[250]	valid_set's binary_logloss: 0.241383
[300]	valid_set's binary_logloss: 0.238449
[350]	valid_set's binary_logloss: 0.23621
[400]	valid_set's binary_logloss: 0.234566
[450]	valid_set's binary_logloss: 0.232984
[500]	valid_set's binary_logloss: 0.232001
[550]	valid_set's binary_logloss: 0.230702
[600]	valid_set's binary_logloss: 0.229906
[650]	valid_set's binary_logloss: 0.229136
[700]	valid_set's binary_logloss: 0.228485
[750]	valid_set's binary_logloss: 0.227797
[800]	valid_set's binary_logloss: 0.227394
[850]	valid_set's binary_logloss: 0.226948
[900]	valid_set's binary_logloss: 0.226445
[950]	valid_set's binary_logloss: 0.226105
[1000]	valid_set's binary_logloss: 0.225673
[1050]	valid_set's binary_logloss: 0.225286
[1100]	valid_set's binary_logloss: 0.224974
[1150]	valid_set's binary_logloss: 0.224737
[1200]	valid_set's binary_logloss: 0.224591
[1250]	valid_set's binary_logloss: 0.224335
[1300]	valid_set's binary_logloss: 0.224232
[1350]	valid_set's binary_logloss: 0.224137
[1400]	valid_set's binary_logloss: 0.224024
[1450]	valid_set's binary_logloss: 0.223871
[1500]	valid_set's binary_logloss: 0.223754
[1550]	valid_set's binary_logloss: 0.223579
[1600]	valid_set's binary_logloss: 0.223484
[1650]	valid_set's binary_logloss: 0.223369
[1700]	valid_set's binary_logloss: 0.223191
[1750]	valid_set's binary_logloss: 0.223081
[1800]	valid_set's binary_logloss: 0.222987
[1850]	valid_set's binary_logloss: 0.223009
[1900]	valid_set's binary_logloss: 0.222946
[1950]	valid_set's binary_logloss: 0.222909
[2000]	valid_set's binary_logloss: 0.222905
[2050]	valid_set's binary_logloss: 0.222868
[2100]	valid_set's binary_logloss: 0.222907
[2150]	valid_set's binary_logloss: 0.222953
[2200]	valid_set's binary_logloss: 0.222924
[2250]	valid_set's binary_logloss: 0.222904
[2300]	valid_set's binary_logloss: 0.222949
[2350]	valid_set's binary_logloss: 0.222956
[2400]	valid_set's binary_logloss: 0.22299
[2450]	valid_set's binary_logloss: 0.223045
[2500]	valid_set's binary_logloss: 0.22308
[2550]	valid_set's binary_logloss: 0.22315
[2600]	valid_set's binary_logloss: 0.223218
[2650]	valid_set's binary_logloss: 0.223293

Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBM_BAG_L1\model.pkl
	0.951	 = Validation score   (roc_auc)
	80.25s	 = Training   runtime
	4.96s	 = Validation runtime
	13607.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1713.14s of the 1713.14s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.314719
[100]	valid_set's binary_logloss: 0.280986
[150]	valid_set's binary_logloss: 0.267949
[200]	valid_set's binary_logloss: 0.259563
[250]	valid_set's binary_logloss: 0.254195
[300]	valid_set's binary_logloss: 0.250373
[350]	valid_set's binary_logloss: 0.247148
[400]	valid_set's binary_logloss: 0.244472
[450]	valid_set's binary_logloss: 0.242082
[500]	valid_set's binary_logloss: 0.240142
[550]	valid_set's binary_logloss: 0.238587
[600]	valid_set's binary_logloss: 0.237138
[650]	valid_set's binary_logloss: 0.235718
[700]	valid_set's binary_logloss: 0.234636
[750]	valid_set's binary_logloss: 0.233565
[800]	valid_set's binary_logloss: 0.232735
[850]	valid_set's binary_logloss: 0.23201
[900]	valid_set's binary_logloss: 0.231118
[950]	valid_set's binary_logloss: 0.230465
[1000]	valid_set's binary_logloss: 0.22974
[1050]	valid_set's binary_logloss: 0.228993
[1100]	valid_set's binary_logloss: 0.228588
[1150]	valid_set's binary_logloss: 0.228076
[1200]	valid_set's binary_logloss: 0.227642
[1250]	valid_set's binary_logloss: 0.227251
[1300]	valid_set's binary_logloss: 0.226832
[1350]	valid_set's binary_logloss: 0.226337
[1400]	valid_set's binary_logloss: 0.225883
[1450]	valid_set's binary_logloss: 0.22551
[1500]	valid_set's binary_logloss: 0.225102
[1550]	valid_set's binary_logloss: 0.224705
[1600]	valid_set's binary_logloss: 0.224493
[1650]	valid_set's binary_logloss: 0.22429
[1700]	valid_set's binary_logloss: 0.224054
[1750]	valid_set's binary_logloss: 0.223791
[1800]	valid_set's binary_logloss: 0.223492
[1850]	valid_set's binary_logloss: 0.223268
[1900]	valid_set's binary_logloss: 0.223032
[1950]	valid_set's binary_logloss: 0.222848
[2000]	valid_set's binary_logloss: 0.222642
[2050]	valid_set's binary_logloss: 0.222428
[2100]	valid_set's binary_logloss: 0.222407
[2150]	valid_set's binary_logloss: 0.222254
[2200]	valid_set's binary_logloss: 0.222116
[2250]	valid_set's binary_logloss: 0.221997
[2300]	valid_set's binary_logloss: 0.221857
[2350]	valid_set's binary_logloss: 0.221706
[2400]	valid_set's binary_logloss: 0.221568
[2450]	valid_set's binary_logloss: 0.221449
[2500]	valid_set's binary_logloss: 0.221351
[2550]	valid_set's binary_logloss: 0.221291
[2600]	valid_set's binary_logloss: 0.221183
[2650]	valid_set's binary_logloss: 0.221058
[2700]	valid_set's binary_logloss: 0.220977
[2750]	valid_set's binary_logloss: 0.220918
[2800]	valid_set's binary_logloss: 0.220849
[2850]	valid_set's binary_logloss: 0.220711
[2900]	valid_set's binary_logloss: 0.220664
[2950]	valid_set's binary_logloss: 0.220609
[3000]	valid_set's binary_logloss: 0.220511
[3050]	valid_set's binary_logloss: 0.22049
[3100]	valid_set's binary_logloss: 0.220397
[3150]	valid_set's binary_logloss: 0.220321
[3200]	valid_set's binary_logloss: 0.220229
[3250]	valid_set's binary_logloss: 0.220089
[3300]	valid_set's binary_logloss: 0.220092
[3350]	valid_set's binary_logloss: 0.220049
[3400]	valid_set's binary_logloss: 0.219996
[3450]	valid_set's binary_logloss: 0.219973
[3500]	valid_set's binary_logloss: 0.219993
[3550]	valid_set's binary_logloss: 0.21993
[3600]	valid_set's binary_logloss: 0.21987
[3650]	valid_set's binary_logloss: 0.219824
[3700]	valid_set's binary_logloss: 0.219754
[3750]	valid_set's binary_logloss: 0.219719
[3800]	valid_set's binary_logloss: 0.219704
[3850]	valid_set's binary_logloss: 0.219656
[3900]	valid_set's binary_logloss: 0.219629
[3950]	valid_set's binary_logloss: 0.219611
[4000]	valid_set's binary_logloss: 0.219599
[4050]	valid_set's binary_logloss: 0.219618
[4100]	valid_set's binary_logloss: 0.219615
[4150]	valid_set's binary_logloss: 0.219623
[4200]	valid_set's binary_logloss: 0.219607
[4250]	valid_set's binary_logloss: 0.219616
[4300]	valid_set's binary_logloss: 0.219635
[4350]	valid_set's binary_logloss: 0.219645
[4400]	valid_set's binary_logloss: 0.219649
[4450]	valid_set's binary_logloss: 0.219653
[4500]	valid_set's binary_logloss: 0.219668
[4550]	valid_set's binary_logloss: 0.219662
[4600]	valid_set's binary_logloss: 0.219683
[4650]	valid_set's binary_logloss: 0.219711
[4700]	valid_set's binary_logloss: 0.219734
[4750]	valid_set's binary_logloss: 0.21975
[4800]	valid_set's binary_logloss: 0.219788
[4850]	valid_set's binary_logloss: 0.219811
[4900]	valid_set's binary_logloss: 0.219853
[4950]	valid_set's binary_logloss: 0.219843
[5000]	valid_set's binary_logloss: 0.219867
[5050]	valid_set's binary_logloss: 0.219915
[5100]	valid_set's binary_logloss: 0.219959
[5150]	valid_set's binary_logloss: 0.220004
[5200]	valid_set's binary_logloss: 0.220035

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.3125
[100]	valid_set's binary_logloss: 0.28269
[150]	valid_set's binary_logloss: 0.26969
[200]	valid_set's binary_logloss: 0.262323
[250]	valid_set's binary_logloss: 0.256811
[300]	valid_set's binary_logloss: 0.252975
[350]	valid_set's binary_logloss: 0.249918
[400]	valid_set's binary_logloss: 0.247268
[450]	valid_set's binary_logloss: 0.245121
[500]	valid_set's binary_logloss: 0.243228
[550]	valid_set's binary_logloss: 0.241431
[600]	valid_set's binary_logloss: 0.239953
[650]	valid_set's binary_logloss: 0.238762
[700]	valid_set's binary_logloss: 0.237654
[750]	valid_set's binary_logloss: 0.23669
[800]	valid_set's binary_logloss: 0.235709
[850]	valid_set's binary_logloss: 0.234788
[900]	valid_set's binary_logloss: 0.234073
[950]	valid_set's binary_logloss: 0.233398
[1000]	valid_set's binary_logloss: 0.23282
[1050]	valid_set's binary_logloss: 0.232108
[1100]	valid_set's binary_logloss: 0.231558
[1150]	valid_set's binary_logloss: 0.231039
[1200]	valid_set's binary_logloss: 0.230582
[1250]	valid_set's binary_logloss: 0.23016
[1300]	valid_set's binary_logloss: 0.229758
[1350]	valid_set's binary_logloss: 0.229374
[1400]	valid_set's binary_logloss: 0.228903
[1450]	valid_set's binary_logloss: 0.22851
[1500]	valid_set's binary_logloss: 0.228136
[1550]	valid_set's binary_logloss: 0.227816
[1600]	valid_set's binary_logloss: 0.227567
[1650]	valid_set's binary_logloss: 0.227293
[1700]	valid_set's binary_logloss: 0.227095
[1750]	valid_set's binary_logloss: 0.226853
[1800]	valid_set's binary_logloss: 0.226621
[1850]	valid_set's binary_logloss: 0.226311
[1900]	valid_set's binary_logloss: 0.226126
[1950]	valid_set's binary_logloss: 0.225945
[2000]	valid_set's binary_logloss: 0.225785
[2050]	valid_set's binary_logloss: 0.2256
[2100]	valid_set's binary_logloss: 0.225407
[2150]	valid_set's binary_logloss: 0.225311
[2200]	valid_set's binary_logloss: 0.225236
[2250]	valid_set's binary_logloss: 0.225119
[2300]	valid_set's binary_logloss: 0.224991
[2350]	valid_set's binary_logloss: 0.224885
[2400]	valid_set's binary_logloss: 0.224741
[2450]	valid_set's binary_logloss: 0.22463
[2500]	valid_set's binary_logloss: 0.224574
[2550]	valid_set's binary_logloss: 0.22446
[2600]	valid_set's binary_logloss: 0.224441
[2650]	valid_set's binary_logloss: 0.224348
[2700]	valid_set's binary_logloss: 0.224306
[2750]	valid_set's binary_logloss: 0.224226
[2800]	valid_set's binary_logloss: 0.224091
[2850]	valid_set's binary_logloss: 0.223985
[2900]	valid_set's binary_logloss: 0.223926
[2950]	valid_set's binary_logloss: 0.223839
[3000]	valid_set's binary_logloss: 0.223755
[3050]	valid_set's binary_logloss: 0.223664
[3100]	valid_set's binary_logloss: 0.223651
[3150]	valid_set's binary_logloss: 0.223562
[3200]	valid_set's binary_logloss: 0.223471
[3250]	valid_set's binary_logloss: 0.223433
[3300]	valid_set's binary_logloss: 0.223382
[3350]	valid_set's binary_logloss: 0.223351
[3400]	valid_set's binary_logloss: 0.223288
[3450]	valid_set's binary_logloss: 0.223248
[3500]	valid_set's binary_logloss: 0.223256
[3550]	valid_set's binary_logloss: 0.223196
[3600]	valid_set's binary_logloss: 0.223202
[3650]	valid_set's binary_logloss: 0.223221
[3700]	valid_set's binary_logloss: 0.2232
[3750]	valid_set's binary_logloss: 0.223212
[3800]	valid_set's binary_logloss: 0.223211
[3850]	valid_set's binary_logloss: 0.223222
[3900]	valid_set's binary_logloss: 0.223168
[3950]	valid_set's binary_logloss: 0.223156
[4000]	valid_set's binary_logloss: 0.223148
[4050]	valid_set's binary_logloss: 0.223159
[4100]	valid_set's binary_logloss: 0.223111
[4150]	valid_set's binary_logloss: 0.223102
[4200]	valid_set's binary_logloss: 0.223083
[4250]	valid_set's binary_logloss: 0.223054
[4300]	valid_set's binary_logloss: 0.223065
[4350]	valid_set's binary_logloss: 0.223083
[4400]	valid_set's binary_logloss: 0.223114
[4450]	valid_set's binary_logloss: 0.223134
[4500]	valid_set's binary_logloss: 0.223129
[4550]	valid_set's binary_logloss: 0.223184
[4600]	valid_set's binary_logloss: 0.223189
[4650]	valid_set's binary_logloss: 0.223228
[4700]	valid_set's binary_logloss: 0.223236
[4750]	valid_set's binary_logloss: 0.223277
[4800]	valid_set's binary_logloss: 0.223273
[4850]	valid_set's binary_logloss: 0.22334
[4900]	valid_set's binary_logloss: 0.223383
[4950]	valid_set's binary_logloss: 0.223406
[5000]	valid_set's binary_logloss: 0.223413
[5050]	valid_set's binary_logloss: 0.223434
[5100]	valid_set's binary_logloss: 0.223444
[5150]	valid_set's binary_logloss: 0.223444
[5200]	valid_set's binary_logloss: 0.223506
[5250]	valid_set's binary_logloss: 0.223524
[5300]	valid_set's binary_logloss: 0.223528
[5350]	valid_set's binary_logloss: 0.223537
[5400]	valid_set's binary_logloss: 0.223552
[5450]	valid_set's binary_logloss: 0.223557
[5500]	valid_set's binary_logloss: 0.223606
[5550]	valid_set's binary_logloss: 0.223595
[5600]	valid_set's binary_logloss: 0.223634

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.31038
[100]	valid_set's binary_logloss: 0.280382
[150]	valid_set's binary_logloss: 0.268603
[200]	valid_set's binary_logloss: 0.261863
[250]	valid_set's binary_logloss: 0.256549
[300]	valid_set's binary_logloss: 0.252699
[350]	valid_set's binary_logloss: 0.249544
[400]	valid_set's binary_logloss: 0.247032
[450]	valid_set's binary_logloss: 0.244841
[500]	valid_set's binary_logloss: 0.242915
[550]	valid_set's binary_logloss: 0.241571
[600]	valid_set's binary_logloss: 0.24005
[650]	valid_set's binary_logloss: 0.238936
[700]	valid_set's binary_logloss: 0.237855
[750]	valid_set's binary_logloss: 0.236913
[800]	valid_set's binary_logloss: 0.236121
[850]	valid_set's binary_logloss: 0.235535
[900]	valid_set's binary_logloss: 0.23474
[950]	valid_set's binary_logloss: 0.234067
[1000]	valid_set's binary_logloss: 0.23351
[1050]	valid_set's binary_logloss: 0.232956
[1100]	valid_set's binary_logloss: 0.23237
[1150]	valid_set's binary_logloss: 0.231779
[1200]	valid_set's binary_logloss: 0.231293
[1250]	valid_set's binary_logloss: 0.230919
[1300]	valid_set's binary_logloss: 0.230531
[1350]	valid_set's binary_logloss: 0.230181
[1400]	valid_set's binary_logloss: 0.229823
[1450]	valid_set's binary_logloss: 0.229528
[1500]	valid_set's binary_logloss: 0.229228
[1550]	valid_set's binary_logloss: 0.228985
[1600]	valid_set's binary_logloss: 0.228768
[1650]	valid_set's binary_logloss: 0.228511
[1700]	valid_set's binary_logloss: 0.228284
[1750]	valid_set's binary_logloss: 0.228011
[1800]	valid_set's binary_logloss: 0.22775
[1850]	valid_set's binary_logloss: 0.227608
[1900]	valid_set's binary_logloss: 0.227405
[1950]	valid_set's binary_logloss: 0.227194
[2000]	valid_set's binary_logloss: 0.227063
[2050]	valid_set's binary_logloss: 0.227009
[2100]	valid_set's binary_logloss: 0.2269
[2150]	valid_set's binary_logloss: 0.226785
[2200]	valid_set's binary_logloss: 0.226664
[2250]	valid_set's binary_logloss: 0.22661
[2300]	valid_set's binary_logloss: 0.226497
[2350]	valid_set's binary_logloss: 0.226448
[2400]	valid_set's binary_logloss: 0.226363
[2450]	valid_set's binary_logloss: 0.226238
[2500]	valid_set's binary_logloss: 0.226142
[2550]	valid_set's binary_logloss: 0.226085
[2600]	valid_set's binary_logloss: 0.226015
[2650]	valid_set's binary_logloss: 0.225956
[2700]	valid_set's binary_logloss: 0.225881
[2750]	valid_set's binary_logloss: 0.225848
[2800]	valid_set's binary_logloss: 0.225711
[2850]	valid_set's binary_logloss: 0.225699
[2900]	valid_set's binary_logloss: 0.225625
[2950]	valid_set's binary_logloss: 0.225604
[3000]	valid_set's binary_logloss: 0.225518
[3050]	valid_set's binary_logloss: 0.225557
[3100]	valid_set's binary_logloss: 0.225484
[3150]	valid_set's binary_logloss: 0.225484
[3200]	valid_set's binary_logloss: 0.225431
[3250]	valid_set's binary_logloss: 0.22539
[3300]	valid_set's binary_logloss: 0.225298
[3350]	valid_set's binary_logloss: 0.225272
[3400]	valid_set's binary_logloss: 0.225237
[3450]	valid_set's binary_logloss: 0.225205
[3500]	valid_set's binary_logloss: 0.225171
[3550]	valid_set's binary_logloss: 0.225185
[3600]	valid_set's binary_logloss: 0.225205
[3650]	valid_set's binary_logloss: 0.225231
[3700]	valid_set's binary_logloss: 0.225196
[3750]	valid_set's binary_logloss: 0.225209
[3800]	valid_set's binary_logloss: 0.22521
[3850]	valid_set's binary_logloss: 0.225239
[3900]	valid_set's binary_logloss: 0.225268
[3950]	valid_set's binary_logloss: 0.225311
[4000]	valid_set's binary_logloss: 0.225304
[4050]	valid_set's binary_logloss: 0.225281
[4100]	valid_set's binary_logloss: 0.22528
[4150]	valid_set's binary_logloss: 0.225318
[4200]	valid_set's binary_logloss: 0.225333
[4250]	valid_set's binary_logloss: 0.225362
[4300]	valid_set's binary_logloss: 0.225382
[4350]	valid_set's binary_logloss: 0.225368
[4400]	valid_set's binary_logloss: 0.225348
[4450]	valid_set's binary_logloss: 0.225365
[4500]	valid_set's binary_logloss: 0.225369
[4550]	valid_set's binary_logloss: 0.225384

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.310503
[100]	valid_set's binary_logloss: 0.279759
[150]	valid_set's binary_logloss: 0.26661
[200]	valid_set's binary_logloss: 0.259369
[250]	valid_set's binary_logloss: 0.254374
[300]	valid_set's binary_logloss: 0.25016
[350]	valid_set's binary_logloss: 0.247173
[400]	valid_set's binary_logloss: 0.244591
[450]	valid_set's binary_logloss: 0.242461
[500]	valid_set's binary_logloss: 0.240519
[550]	valid_set's binary_logloss: 0.238988
[600]	valid_set's binary_logloss: 0.237567
[650]	valid_set's binary_logloss: 0.23627
[700]	valid_set's binary_logloss: 0.235052
[750]	valid_set's binary_logloss: 0.233966
[800]	valid_set's binary_logloss: 0.23304
[850]	valid_set's binary_logloss: 0.232269
[900]	valid_set's binary_logloss: 0.231547
[950]	valid_set's binary_logloss: 0.230947
[1000]	valid_set's binary_logloss: 0.230342
[1050]	valid_set's binary_logloss: 0.229664
[1100]	valid_set's binary_logloss: 0.229209
[1150]	valid_set's binary_logloss: 0.228704
[1200]	valid_set's binary_logloss: 0.22835
[1250]	valid_set's binary_logloss: 0.227912
[1300]	valid_set's binary_logloss: 0.227531
[1350]	valid_set's binary_logloss: 0.227193
[1400]	valid_set's binary_logloss: 0.226827
[1450]	valid_set's binary_logloss: 0.226523
[1500]	valid_set's binary_logloss: 0.226244
[1550]	valid_set's binary_logloss: 0.226009
[1600]	valid_set's binary_logloss: 0.225722
[1650]	valid_set's binary_logloss: 0.225501
[1700]	valid_set's binary_logloss: 0.225244
[1750]	valid_set's binary_logloss: 0.224999
[1800]	valid_set's binary_logloss: 0.224799
[1850]	valid_set's binary_logloss: 0.224587
[1900]	valid_set's binary_logloss: 0.224389
[1950]	valid_set's binary_logloss: 0.224262
[2000]	valid_set's binary_logloss: 0.224089
[2050]	valid_set's binary_logloss: 0.223922
[2100]	valid_set's binary_logloss: 0.223717
[2150]	valid_set's binary_logloss: 0.223604
[2200]	valid_set's binary_logloss: 0.223459
[2250]	valid_set's binary_logloss: 0.223324
[2300]	valid_set's binary_logloss: 0.223197
[2350]	valid_set's binary_logloss: 0.223116
[2400]	valid_set's binary_logloss: 0.223005
[2450]	valid_set's binary_logloss: 0.222895
[2500]	valid_set's binary_logloss: 0.222792
[2550]	valid_set's binary_logloss: 0.222673
[2600]	valid_set's binary_logloss: 0.222575
[2650]	valid_set's binary_logloss: 0.222504
[2700]	valid_set's binary_logloss: 0.222385
[2750]	valid_set's binary_logloss: 0.222277
[2800]	valid_set's binary_logloss: 0.222156
[2850]	valid_set's binary_logloss: 0.222074
[2900]	valid_set's binary_logloss: 0.221943
[2950]	valid_set's binary_logloss: 0.221891
[3000]	valid_set's binary_logloss: 0.221855
[3050]	valid_set's binary_logloss: 0.221739
[3100]	valid_set's binary_logloss: 0.221713
[3150]	valid_set's binary_logloss: 0.221665
[3200]	valid_set's binary_logloss: 0.221587
[3250]	valid_set's binary_logloss: 0.221543
[3300]	valid_set's binary_logloss: 0.221473
[3350]	valid_set's binary_logloss: 0.221453
[3400]	valid_set's binary_logloss: 0.22142
[3450]	valid_set's binary_logloss: 0.221386
[3500]	valid_set's binary_logloss: 0.221344
[3550]	valid_set's binary_logloss: 0.221344
[3600]	valid_set's binary_logloss: 0.22132
[3650]	valid_set's binary_logloss: 0.221296
[3700]	valid_set's binary_logloss: 0.221266
[3750]	valid_set's binary_logloss: 0.22125
[3800]	valid_set's binary_logloss: 0.221255
[3850]	valid_set's binary_logloss: 0.221296
[3900]	valid_set's binary_logloss: 0.221265
[3950]	valid_set's binary_logloss: 0.221189
[4000]	valid_set's binary_logloss: 0.221188
[4050]	valid_set's binary_logloss: 0.221218
[4100]	valid_set's binary_logloss: 0.22116
[4150]	valid_set's binary_logloss: 0.221124
[4200]	valid_set's binary_logloss: 0.221119
[4250]	valid_set's binary_logloss: 0.22114
[4300]	valid_set's binary_logloss: 0.221144
[4350]	valid_set's binary_logloss: 0.221163
[4400]	valid_set's binary_logloss: 0.221172
[4450]	valid_set's binary_logloss: 0.22116
[4500]	valid_set's binary_logloss: 0.221187
[4550]	valid_set's binary_logloss: 0.221176
[4600]	valid_set's binary_logloss: 0.22117
[4650]	valid_set's binary_logloss: 0.221184
[4700]	valid_set's binary_logloss: 0.22121
[4750]	valid_set's binary_logloss: 0.221259
[4800]	valid_set's binary_logloss: 0.221327
[4850]	valid_set's binary_logloss: 0.22134
[4900]	valid_set's binary_logloss: 0.221322
[4950]	valid_set's binary_logloss: 0.221316
[5000]	valid_set's binary_logloss: 0.221349
[5050]	valid_set's binary_logloss: 0.221346
[5100]	valid_set's binary_logloss: 0.221381
[5150]	valid_set's binary_logloss: 0.221382
[5200]	valid_set's binary_logloss: 0.221365
[5250]	valid_set's binary_logloss: 0.221405
[5300]	valid_set's binary_logloss: 0.221445
[5350]	valid_set's binary_logloss: 0.221478
[5400]	valid_set's binary_logloss: 0.221536
[5450]	valid_set's binary_logloss: 0.221572

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.31216
[100]	valid_set's binary_logloss: 0.280889
[150]	valid_set's binary_logloss: 0.267073
[200]	valid_set's binary_logloss: 0.259935
[250]	valid_set's binary_logloss: 0.25472
[300]	valid_set's binary_logloss: 0.250963
[350]	valid_set's binary_logloss: 0.247298
[400]	valid_set's binary_logloss: 0.244863
[450]	valid_set's binary_logloss: 0.242553
[500]	valid_set's binary_logloss: 0.240633
[550]	valid_set's binary_logloss: 0.238994
[600]	valid_set's binary_logloss: 0.237573
[650]	valid_set's binary_logloss: 0.236186
[700]	valid_set's binary_logloss: 0.234954
[750]	valid_set's binary_logloss: 0.233878
[800]	valid_set's binary_logloss: 0.232991
[850]	valid_set's binary_logloss: 0.23209
[900]	valid_set's binary_logloss: 0.231253
[950]	valid_set's binary_logloss: 0.230584
[1000]	valid_set's binary_logloss: 0.229876
[1050]	valid_set's binary_logloss: 0.229307
[1100]	valid_set's binary_logloss: 0.228712
[1150]	valid_set's binary_logloss: 0.22824
[1200]	valid_set's binary_logloss: 0.227737
[1250]	valid_set's binary_logloss: 0.227302
[1300]	valid_set's binary_logloss: 0.226873
[1350]	valid_set's binary_logloss: 0.226509
[1400]	valid_set's binary_logloss: 0.226005
[1450]	valid_set's binary_logloss: 0.225745
[1500]	valid_set's binary_logloss: 0.225437
[1550]	valid_set's binary_logloss: 0.22523
[1600]	valid_set's binary_logloss: 0.224921
[1650]	valid_set's binary_logloss: 0.224656
[1700]	valid_set's binary_logloss: 0.224317
[1750]	valid_set's binary_logloss: 0.224132
[1800]	valid_set's binary_logloss: 0.223859
[1850]	valid_set's binary_logloss: 0.223653
[1900]	valid_set's binary_logloss: 0.223395
[1950]	valid_set's binary_logloss: 0.223257
[2000]	valid_set's binary_logloss: 0.223042
[2050]	valid_set's binary_logloss: 0.222874
[2100]	valid_set's binary_logloss: 0.222736
[2150]	valid_set's binary_logloss: 0.222584
[2200]	valid_set's binary_logloss: 0.222493
[2250]	valid_set's binary_logloss: 0.222282
[2300]	valid_set's binary_logloss: 0.222182
[2350]	valid_set's binary_logloss: 0.222049
[2400]	valid_set's binary_logloss: 0.221915
[2450]	valid_set's binary_logloss: 0.221773
[2500]	valid_set's binary_logloss: 0.221678
[2550]	valid_set's binary_logloss: 0.221581
[2600]	valid_set's binary_logloss: 0.221466
[2650]	valid_set's binary_logloss: 0.221328
[2700]	valid_set's binary_logloss: 0.221232
[2750]	valid_set's binary_logloss: 0.221194
[2800]	valid_set's binary_logloss: 0.221069
[2850]	valid_set's binary_logloss: 0.220941
[2900]	valid_set's binary_logloss: 0.220809
[2950]	valid_set's binary_logloss: 0.220802
[3000]	valid_set's binary_logloss: 0.220775
[3050]	valid_set's binary_logloss: 0.220736
[3100]	valid_set's binary_logloss: 0.220698
[3150]	valid_set's binary_logloss: 0.220684
[3200]	valid_set's binary_logloss: 0.220608
[3250]	valid_set's binary_logloss: 0.220532
[3300]	valid_set's binary_logloss: 0.220483
[3350]	valid_set's binary_logloss: 0.220471
[3400]	valid_set's binary_logloss: 0.220417
[3450]	valid_set's binary_logloss: 0.22037
[3500]	valid_set's binary_logloss: 0.220271
[3550]	valid_set's binary_logloss: 0.220239
[3600]	valid_set's binary_logloss: 0.220228
[3650]	valid_set's binary_logloss: 0.220191
[3700]	valid_set's binary_logloss: 0.220192
[3750]	valid_set's binary_logloss: 0.22016
[3800]	valid_set's binary_logloss: 0.220151
[3850]	valid_set's binary_logloss: 0.220097
[3900]	valid_set's binary_logloss: 0.220049
[3950]	valid_set's binary_logloss: 0.220035
[4000]	valid_set's binary_logloss: 0.220001
[4050]	valid_set's binary_logloss: 0.219972
[4100]	valid_set's binary_logloss: 0.219976
[4150]	valid_set's binary_logloss: 0.219941
[4200]	valid_set's binary_logloss: 0.219897
[4250]	valid_set's binary_logloss: 0.219856
[4300]	valid_set's binary_logloss: 0.219854
[4350]	valid_set's binary_logloss: 0.219839
[4400]	valid_set's binary_logloss: 0.219832
[4450]	valid_set's binary_logloss: 0.219847
[4500]	valid_set's binary_logloss: 0.21984
[4550]	valid_set's binary_logloss: 0.219855
[4600]	valid_set's binary_logloss: 0.219842
[4650]	valid_set's binary_logloss: 0.219856
[4700]	valid_set's binary_logloss: 0.219844
[4750]	valid_set's binary_logloss: 0.219846
[4800]	valid_set's binary_logloss: 0.219912
[4850]	valid_set's binary_logloss: 0.219913
[4900]	valid_set's binary_logloss: 0.219938
[4950]	valid_set's binary_logloss: 0.219974
[5000]	valid_set's binary_logloss: 0.219982
[5050]	valid_set's binary_logloss: 0.219985
[5100]	valid_set's binary_logloss: 0.22002
[5150]	valid_set's binary_logloss: 0.22006
[5200]	valid_set's binary_logloss: 0.220087
[5250]	valid_set's binary_logloss: 0.220079
[5300]	valid_set's binary_logloss: 0.220114
[5350]	valid_set's binary_logloss: 0.220099
[5400]	valid_set's binary_logloss: 0.220109
[5450]	valid_set's binary_logloss: 0.220133
[5500]	valid_set's binary_logloss: 0.220147
[5550]	valid_set's binary_logloss: 0.220173
[5600]	valid_set's binary_logloss: 0.220189
[5650]	valid_set's binary_logloss: 0.220214
[5700]	valid_set's binary_logloss: 0.220221

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.311676
[100]	valid_set's binary_logloss: 0.279995
[150]	valid_set's binary_logloss: 0.26618
[200]	valid_set's binary_logloss: 0.259062
[250]	valid_set's binary_logloss: 0.253566
[300]	valid_set's binary_logloss: 0.250017
[350]	valid_set's binary_logloss: 0.247148
[400]	valid_set's binary_logloss: 0.244483
[450]	valid_set's binary_logloss: 0.242466
[500]	valid_set's binary_logloss: 0.240508
[550]	valid_set's binary_logloss: 0.23884
[600]	valid_set's binary_logloss: 0.237392
[650]	valid_set's binary_logloss: 0.23618
[700]	valid_set's binary_logloss: 0.234964
[750]	valid_set's binary_logloss: 0.233896
[800]	valid_set's binary_logloss: 0.232917
[850]	valid_set's binary_logloss: 0.232055
[900]	valid_set's binary_logloss: 0.231231
[950]	valid_set's binary_logloss: 0.230433
[1000]	valid_set's binary_logloss: 0.22983
[1050]	valid_set's binary_logloss: 0.229167
[1100]	valid_set's binary_logloss: 0.228605
[1150]	valid_set's binary_logloss: 0.228024
[1200]	valid_set's binary_logloss: 0.227583
[1250]	valid_set's binary_logloss: 0.227142
[1300]	valid_set's binary_logloss: 0.226715
[1350]	valid_set's binary_logloss: 0.226329
[1400]	valid_set's binary_logloss: 0.225992
[1450]	valid_set's binary_logloss: 0.225711
[1500]	valid_set's binary_logloss: 0.225352
[1550]	valid_set's binary_logloss: 0.225093
[1600]	valid_set's binary_logloss: 0.224855
[1650]	valid_set's binary_logloss: 0.224578
[1700]	valid_set's binary_logloss: 0.22429
[1750]	valid_set's binary_logloss: 0.223974
[1800]	valid_set's binary_logloss: 0.223793
[1850]	valid_set's binary_logloss: 0.223597
[1900]	valid_set's binary_logloss: 0.223434
[1950]	valid_set's binary_logloss: 0.223237
[2000]	valid_set's binary_logloss: 0.223086
[2050]	valid_set's binary_logloss: 0.222841
[2100]	valid_set's binary_logloss: 0.222641
[2150]	valid_set's binary_logloss: 0.222457
[2200]	valid_set's binary_logloss: 0.222361
[2250]	valid_set's binary_logloss: 0.222201
[2300]	valid_set's binary_logloss: 0.222065
[2350]	valid_set's binary_logloss: 0.221908
[2400]	valid_set's binary_logloss: 0.221761
[2450]	valid_set's binary_logloss: 0.221692
[2500]	valid_set's binary_logloss: 0.221606
[2550]	valid_set's binary_logloss: 0.221478
[2600]	valid_set's binary_logloss: 0.221331
[2650]	valid_set's binary_logloss: 0.221238
[2700]	valid_set's binary_logloss: 0.221162
[2750]	valid_set's binary_logloss: 0.221074
[2800]	valid_set's binary_logloss: 0.221027
[2850]	valid_set's binary_logloss: 0.220936
[2900]	valid_set's binary_logloss: 0.2209
[2950]	valid_set's binary_logloss: 0.220859
[3000]	valid_set's binary_logloss: 0.220839
[3050]	valid_set's binary_logloss: 0.220727
[3100]	valid_set's binary_logloss: 0.220667
[3150]	valid_set's binary_logloss: 0.220583
[3200]	valid_set's binary_logloss: 0.220555
[3250]	valid_set's binary_logloss: 0.220489
[3300]	valid_set's binary_logloss: 0.22048
[3350]	valid_set's binary_logloss: 0.220414
[3400]	valid_set's binary_logloss: 0.220428
[3450]	valid_set's binary_logloss: 0.220328
[3500]	valid_set's binary_logloss: 0.2203
[3550]	valid_set's binary_logloss: 0.220237
[3600]	valid_set's binary_logloss: 0.220225
[3650]	valid_set's binary_logloss: 0.220197
[3700]	valid_set's binary_logloss: 0.220193
[3750]	valid_set's binary_logloss: 0.220127
[3800]	valid_set's binary_logloss: 0.22009
[3850]	valid_set's binary_logloss: 0.220034
[3900]	valid_set's binary_logloss: 0.220024
[3950]	valid_set's binary_logloss: 0.220017
[4000]	valid_set's binary_logloss: 0.220024
[4050]	valid_set's binary_logloss: 0.219971
[4100]	valid_set's binary_logloss: 0.219955
[4150]	valid_set's binary_logloss: 0.219947
[4200]	valid_set's binary_logloss: 0.219997
[4250]	valid_set's binary_logloss: 0.219974
[4300]	valid_set's binary_logloss: 0.219943
[4350]	valid_set's binary_logloss: 0.219905
[4400]	valid_set's binary_logloss: 0.219924
[4450]	valid_set's binary_logloss: 0.219904
[4500]	valid_set's binary_logloss: 0.219919
[4550]	valid_set's binary_logloss: 0.219933
[4600]	valid_set's binary_logloss: 0.219918
[4650]	valid_set's binary_logloss: 0.21991
[4700]	valid_set's binary_logloss: 0.219971
[4750]	valid_set's binary_logloss: 0.219938
[4800]	valid_set's binary_logloss: 0.219921
[4850]	valid_set's binary_logloss: 0.21996
[4900]	valid_set's binary_logloss: 0.219978
[4950]	valid_set's binary_logloss: 0.219987
[5000]	valid_set's binary_logloss: 0.219995
[5050]	valid_set's binary_logloss: 0.22002
[5100]	valid_set's binary_logloss: 0.220021
[5150]	valid_set's binary_logloss: 0.220042
[5200]	valid_set's binary_logloss: 0.220059
[5250]	valid_set's binary_logloss: 0.220085
[5300]	valid_set's binary_logloss: 0.220067
[5350]	valid_set's binary_logloss: 0.220114
[5400]	valid_set's binary_logloss: 0.220097
[5450]	valid_set's binary_logloss: 0.220151
[5500]	valid_set's binary_logloss: 0.220196
[5550]	valid_set's binary_logloss: 0.220243
[5600]	valid_set's binary_logloss: 0.220268
[5650]	valid_set's binary_logloss: 0.220293
[5700]	valid_set's binary_logloss: 0.220271
[5750]	valid_set's binary_logloss: 0.220258

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.306384
[100]	valid_set's binary_logloss: 0.276563
[150]	valid_set's binary_logloss: 0.264527
[200]	valid_set's binary_logloss: 0.257311
[250]	valid_set's binary_logloss: 0.252003
[300]	valid_set's binary_logloss: 0.248148
[350]	valid_set's binary_logloss: 0.245292
[400]	valid_set's binary_logloss: 0.243184
[450]	valid_set's binary_logloss: 0.241291
[500]	valid_set's binary_logloss: 0.239554
[550]	valid_set's binary_logloss: 0.238024
[600]	valid_set's binary_logloss: 0.236594
[650]	valid_set's binary_logloss: 0.235267
[700]	valid_set's binary_logloss: 0.234299
[750]	valid_set's binary_logloss: 0.233348
[800]	valid_set's binary_logloss: 0.232492
[850]	valid_set's binary_logloss: 0.231729
[900]	valid_set's binary_logloss: 0.231042
[950]	valid_set's binary_logloss: 0.230454
[1000]	valid_set's binary_logloss: 0.229926
[1050]	valid_set's binary_logloss: 0.229419
[1100]	valid_set's binary_logloss: 0.228856
[1150]	valid_set's binary_logloss: 0.228394
[1200]	valid_set's binary_logloss: 0.227936
[1250]	valid_set's binary_logloss: 0.227433
[1300]	valid_set's binary_logloss: 0.227096
[1350]	valid_set's binary_logloss: 0.226768
[1400]	valid_set's binary_logloss: 0.226408
[1450]	valid_set's binary_logloss: 0.22615
[1500]	valid_set's binary_logloss: 0.225873
[1550]	valid_set's binary_logloss: 0.225562
[1600]	valid_set's binary_logloss: 0.225343
[1650]	valid_set's binary_logloss: 0.225106
[1700]	valid_set's binary_logloss: 0.224889
[1750]	valid_set's binary_logloss: 0.224666
[1800]	valid_set's binary_logloss: 0.224506
[1850]	valid_set's binary_logloss: 0.224237
[1900]	valid_set's binary_logloss: 0.224075
[1950]	valid_set's binary_logloss: 0.223922
[2000]	valid_set's binary_logloss: 0.223807
[2050]	valid_set's binary_logloss: 0.223689
[2100]	valid_set's binary_logloss: 0.223609
[2150]	valid_set's binary_logloss: 0.223468
[2200]	valid_set's binary_logloss: 0.223254
[2250]	valid_set's binary_logloss: 0.223158
[2300]	valid_set's binary_logloss: 0.223103
[2350]	valid_set's binary_logloss: 0.222968
[2400]	valid_set's binary_logloss: 0.222829
[2450]	valid_set's binary_logloss: 0.22275
[2500]	valid_set's binary_logloss: 0.222628
[2550]	valid_set's binary_logloss: 0.222461
[2600]	valid_set's binary_logloss: 0.222431
[2650]	valid_set's binary_logloss: 0.222406
[2700]	valid_set's binary_logloss: 0.222341
[2750]	valid_set's binary_logloss: 0.222278
[2800]	valid_set's binary_logloss: 0.222177
[2850]	valid_set's binary_logloss: 0.222105
[2900]	valid_set's binary_logloss: 0.222072
[2950]	valid_set's binary_logloss: 0.222023
[3000]	valid_set's binary_logloss: 0.221946
[3050]	valid_set's binary_logloss: 0.221921
[3100]	valid_set's binary_logloss: 0.221841
[3150]	valid_set's binary_logloss: 0.221817
[3200]	valid_set's binary_logloss: 0.221777
[3250]	valid_set's binary_logloss: 0.221759
[3300]	valid_set's binary_logloss: 0.221736
[3350]	valid_set's binary_logloss: 0.221758
[3400]	valid_set's binary_logloss: 0.221802
[3450]	valid_set's binary_logloss: 0.221728
[3500]	valid_set's binary_logloss: 0.221658
[3550]	valid_set's binary_logloss: 0.22162
[3600]	valid_set's binary_logloss: 0.221629
[3650]	valid_set's binary_logloss: 0.221578
[3700]	valid_set's binary_logloss: 0.221582
[3750]	valid_set's binary_logloss: 0.221593
[3800]	valid_set's binary_logloss: 0.221608
[3850]	valid_set's binary_logloss: 0.221587
[3900]	valid_set's binary_logloss: 0.221573
[3950]	valid_set's binary_logloss: 0.221544
[4000]	valid_set's binary_logloss: 0.221509
[4050]	valid_set's binary_logloss: 0.221482
[4100]	valid_set's binary_logloss: 0.221506
[4150]	valid_set's binary_logloss: 0.221532
[4200]	valid_set's binary_logloss: 0.221558
[4250]	valid_set's binary_logloss: 0.22156
[4300]	valid_set's binary_logloss: 0.221582
[4350]	valid_set's binary_logloss: 0.221604
[4400]	valid_set's binary_logloss: 0.221594
[4450]	valid_set's binary_logloss: 0.221595
[4500]	valid_set's binary_logloss: 0.221561
[4550]	valid_set's binary_logloss: 0.22158
[4600]	valid_set's binary_logloss: 0.221522
[4650]	valid_set's binary_logloss: 0.221525
[4700]	valid_set's binary_logloss: 0.221523
[4750]	valid_set's binary_logloss: 0.221518
[4800]	valid_set's binary_logloss: 0.221536
[4850]	valid_set's binary_logloss: 0.22157
[4900]	valid_set's binary_logloss: 0.221622
[4950]	valid_set's binary_logloss: 0.22164
[5000]	valid_set's binary_logloss: 0.221648
[5050]	valid_set's binary_logloss: 0.221675
[5100]	valid_set's binary_logloss: 0.221713
[5150]	valid_set's binary_logloss: 0.221744
[5200]	valid_set's binary_logloss: 0.221774
[5250]	valid_set's binary_logloss: 0.221863

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.306565
[100]	valid_set's binary_logloss: 0.276107
[150]	valid_set's binary_logloss: 0.262547
[200]	valid_set's binary_logloss: 0.255838
[250]	valid_set's binary_logloss: 0.250943
[300]	valid_set's binary_logloss: 0.247496
[350]	valid_set's binary_logloss: 0.244706
[400]	valid_set's binary_logloss: 0.242332
[450]	valid_set's binary_logloss: 0.240264
[500]	valid_set's binary_logloss: 0.238438
[550]	valid_set's binary_logloss: 0.236992
[600]	valid_set's binary_logloss: 0.235531
[650]	valid_set's binary_logloss: 0.234282
[700]	valid_set's binary_logloss: 0.233292
[750]	valid_set's binary_logloss: 0.232415
[800]	valid_set's binary_logloss: 0.231514
[850]	valid_set's binary_logloss: 0.230521
[900]	valid_set's binary_logloss: 0.229737
[950]	valid_set's binary_logloss: 0.229066
[1000]	valid_set's binary_logloss: 0.228492
[1050]	valid_set's binary_logloss: 0.227988
[1100]	valid_set's binary_logloss: 0.22745
[1150]	valid_set's binary_logloss: 0.226828
[1200]	valid_set's binary_logloss: 0.22629
[1250]	valid_set's binary_logloss: 0.225952
[1300]	valid_set's binary_logloss: 0.225577
[1350]	valid_set's binary_logloss: 0.225212
[1400]	valid_set's binary_logloss: 0.224923
[1450]	valid_set's binary_logloss: 0.224605
[1500]	valid_set's binary_logloss: 0.224272
[1550]	valid_set's binary_logloss: 0.22397
[1600]	valid_set's binary_logloss: 0.223679
[1650]	valid_set's binary_logloss: 0.223463
[1700]	valid_set's binary_logloss: 0.223242
[1750]	valid_set's binary_logloss: 0.223085
[1800]	valid_set's binary_logloss: 0.22285
[1850]	valid_set's binary_logloss: 0.222673
[1900]	valid_set's binary_logloss: 0.222581
[1950]	valid_set's binary_logloss: 0.222401
[2000]	valid_set's binary_logloss: 0.222165
[2050]	valid_set's binary_logloss: 0.221989
[2100]	valid_set's binary_logloss: 0.221922
[2150]	valid_set's binary_logloss: 0.221841
[2200]	valid_set's binary_logloss: 0.22167
[2250]	valid_set's binary_logloss: 0.221608
[2300]	valid_set's binary_logloss: 0.221477
[2350]	valid_set's binary_logloss: 0.221398
[2400]	valid_set's binary_logloss: 0.221292
[2450]	valid_set's binary_logloss: 0.221125
[2500]	valid_set's binary_logloss: 0.221026
[2550]	valid_set's binary_logloss: 0.220949
[2600]	valid_set's binary_logloss: 0.220902
[2650]	valid_set's binary_logloss: 0.220795
[2700]	valid_set's binary_logloss: 0.220665
[2750]	valid_set's binary_logloss: 0.220544
[2800]	valid_set's binary_logloss: 0.220464
[2850]	valid_set's binary_logloss: 0.220361
[2900]	valid_set's binary_logloss: 0.220283
[2950]	valid_set's binary_logloss: 0.220285
[3000]	valid_set's binary_logloss: 0.220174
[3050]	valid_set's binary_logloss: 0.220108
[3100]	valid_set's binary_logloss: 0.220019
[3150]	valid_set's binary_logloss: 0.219996
[3200]	valid_set's binary_logloss: 0.219942
[3250]	valid_set's binary_logloss: 0.219888
[3300]	valid_set's binary_logloss: 0.219889
[3350]	valid_set's binary_logloss: 0.219889
[3400]	valid_set's binary_logloss: 0.219863
[3450]	valid_set's binary_logloss: 0.219797
[3500]	valid_set's binary_logloss: 0.219773
[3550]	valid_set's binary_logloss: 0.219774
[3600]	valid_set's binary_logloss: 0.219737
[3650]	valid_set's binary_logloss: 0.219682
[3700]	valid_set's binary_logloss: 0.21966
[3750]	valid_set's binary_logloss: 0.219618
[3800]	valid_set's binary_logloss: 0.219613
[3850]	valid_set's binary_logloss: 0.219574
[3900]	valid_set's binary_logloss: 0.219555
[3950]	valid_set's binary_logloss: 0.21953
[4000]	valid_set's binary_logloss: 0.219484
[4050]	valid_set's binary_logloss: 0.219439
[4100]	valid_set's binary_logloss: 0.21945
[4150]	valid_set's binary_logloss: 0.219425
[4200]	valid_set's binary_logloss: 0.219371
[4250]	valid_set's binary_logloss: 0.219369
[4300]	valid_set's binary_logloss: 0.219364
[4350]	valid_set's binary_logloss: 0.219352
[4400]	valid_set's binary_logloss: 0.219317
[4450]	valid_set's binary_logloss: 0.219317
[4500]	valid_set's binary_logloss: 0.219299
[4550]	valid_set's binary_logloss: 0.219321
[4600]	valid_set's binary_logloss: 0.219328
[4650]	valid_set's binary_logloss: 0.219301
[4700]	valid_set's binary_logloss: 0.219273
[4750]	valid_set's binary_logloss: 0.219288
[4800]	valid_set's binary_logloss: 0.21931
[4850]	valid_set's binary_logloss: 0.219322
[4900]	valid_set's binary_logloss: 0.219289
[4950]	valid_set's binary_logloss: 0.219291
[5000]	valid_set's binary_logloss: 0.219239
[5050]	valid_set's binary_logloss: 0.21926
[5100]	valid_set's binary_logloss: 0.219285
[5150]	valid_set's binary_logloss: 0.219258
[5200]	valid_set's binary_logloss: 0.219262
[5250]	valid_set's binary_logloss: 0.219349
[5300]	valid_set's binary_logloss: 0.219346
[5350]	valid_set's binary_logloss: 0.219387
[5400]	valid_set's binary_logloss: 0.219427
[5450]	valid_set's binary_logloss: 0.219449
[5500]	valid_set's binary_logloss: 0.219501
[5550]	valid_set's binary_logloss: 0.219513
[5600]	valid_set's binary_logloss: 0.219519
[5650]	valid_set's binary_logloss: 0.219487
[5700]	valid_set's binary_logloss: 0.219503
[5750]	valid_set's binary_logloss: 0.219555
[5800]	valid_set's binary_logloss: 0.21958
[5850]	valid_set's binary_logloss: 0.219559
[5900]	valid_set's binary_logloss: 0.219598
[5950]	valid_set's binary_logloss: 0.219621
[6000]	valid_set's binary_logloss: 0.219633
[6050]	valid_set's binary_logloss: 0.219665
[6100]	valid_set's binary_logloss: 0.219695
[6150]	valid_set's binary_logloss: 0.219707
[6200]	valid_set's binary_logloss: 0.219737
[6250]	valid_set's binary_logloss: 0.219778
[6300]	valid_set's binary_logloss: 0.219788
[6350]	valid_set's binary_logloss: 0.219822
[6400]	valid_set's binary_logloss: 0.219902
[6450]	valid_set's binary_logloss: 0.219941
[6500]	valid_set's binary_logloss: 0.219956
[6550]	valid_set's binary_logloss: 0.219975
[6600]	valid_set's binary_logloss: 0.220018
[6650]	valid_set's binary_logloss: 0.220096
[6700]	valid_set's binary_logloss: 0.220153

Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBMLarge_BAG_L1\model.pkl
	0.9529	 = Validation score   (roc_auc)
	172.91s	 = Training   runtime
	13.48s	 = Validation runtime
	5012.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1525.41s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.8 GB
Ensemble size: 3
Ensemble weights:
[0.33333333 0.66666667]
	0.48s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 0.667, 'LightGBM_BAG_L1': 0.333}
	0.9536	 = Validation score   (roc_auc)
	2.83s	 = Training   runtime
	0.06s	 = Validation runtime
	3661.8	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
AutoGluon training complete, total runtime = 277.53s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3661.8 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models2\GBM\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models2\GBM")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.74 GB / 15.06 GB (18.2%)
Disk Space Avail:   724.69 GB / 930.47 GB (77.9%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models2\XGB"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

GBM completed.
Validation ROC-AUC: 0.953617

================================================================================
TRAINING: XGB
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models2\XGB
================================================================================

	Available Memory:                    2876.71 MB
	Train Data (Original)  Memory Usage: 136.13 MB (4.7% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.8s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.5% of available memory)
Data preprocessing and feature engineering runtime = 0.92s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\utils\data\y.pkl
Model configs that will be trained (in order):
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1799.08s of the 1799.07s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47381
[50]	validation_0-logloss:0.26494
[100]	validation_0-logloss:0.24920
[150]	validation_0-logloss:0.24177
[200]	validation_0-logloss:0.23672
[250]	validation_0-logloss:0.23322
[300]	validation_0-logloss:0.22976
[350]	validation_0-logloss:0.22735
[400]	validation_0-logloss:0.22509
[450]	validation_0-logloss:0.22342
[500]	validation_0-logloss:0.22167
[550]	validation_0-logloss:0.22042
[600]	validation_0-logloss:0.21928
[650]	validation_0-logloss:0.21837
[700]	validation_0-logloss:0.21741
[750]	validation_0-logloss:0.21673
[800]	validation_0-logloss:0.21600
[850]	validation_0-logloss:0.21521
[900]	validation_0-logloss:0.21469
[950]	validation_0-logloss:0.21433
[1000]	validation_0-logloss:0.21374
[1050]	validation_0-logloss:0.21331
[1100]	validation_0-logloss:0.21294
[1150]	validation_0-logloss:0.21265
[1200]	validation_0-logloss:0.21232
[1250]	validation_0-logloss:0.21212
[1300]	validation_0-logloss:0.21171
[1350]	validation_0-logloss:0.21142
[1400]	validation_0-logloss:0.21120
[1450]	validation_0-logloss:0.21107
[1500]	validation_0-logloss:0.21080
[1550]	validation_0-logloss:0.21060
[1600]	validation_0-logloss:0.21044
[1650]	validation_0-logloss:0.21023
[1700]	validation_0-logloss:0.21002
[1750]	validation_0-logloss:0.20982
[1800]	validation_0-logloss:0.20960
[1850]	validation_0-logloss:0.20945
[1900]	validation_0-logloss:0.20937
[1950]	validation_0-logloss:0.20931
[2000]	validation_0-logloss:0.20927
[2050]	validation_0-logloss:0.20911
[2100]	validation_0-logloss:0.20897
[2150]	validation_0-logloss:0.20887
[2200]	validation_0-logloss:0.20886
[2250]	validation_0-logloss:0.20880
[2300]	validation_0-logloss:0.20871
[2350]	validation_0-logloss:0.20862
[2400]	validation_0-logloss:0.20860
[2450]	validation_0-logloss:0.20861
[2500]	validation_0-logloss:0.20860
[2550]	validation_0-logloss:0.20856
[2600]	validation_0-logloss:0.20843
[2650]	validation_0-logloss:0.20843
[2700]	validation_0-logloss:0.20838
[2750]	validation_0-logloss:0.20838
[2800]	validation_0-logloss:0.20840
[2850]	validation_0-logloss:0.20843
[2900]	validation_0-logloss:0.20841
[2950]	validation_0-logloss:0.20849
[3000]	validation_0-logloss:0.20850
[3050]	validation_0-logloss:0.20846
[3100]	validation_0-logloss:0.20846
[3150]	validation_0-logloss:0.20854
[3200]	validation_0-logloss:0.20853
[3250]	validation_0-logloss:0.20861
[3300]	validation_0-logloss:0.20869
[3350]	validation_0-logloss:0.20868
[3400]	validation_0-logloss:0.20879
[3450]	validation_0-logloss:0.20881
[3500]	validation_0-logloss:0.20881
[3522]	validation_0-logloss:0.20887

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47401
[50]	validation_0-logloss:0.26585
[100]	validation_0-logloss:0.25120
[150]	validation_0-logloss:0.24362
[200]	validation_0-logloss:0.23819
[250]	validation_0-logloss:0.23435
[300]	validation_0-logloss:0.23093
[350]	validation_0-logloss:0.22868
[400]	validation_0-logloss:0.22644
[450]	validation_0-logloss:0.22466
[500]	validation_0-logloss:0.22296
[550]	validation_0-logloss:0.22177
[600]	validation_0-logloss:0.22054
[650]	validation_0-logloss:0.21977
[700]	validation_0-logloss:0.21857
[750]	validation_0-logloss:0.21782
[800]	validation_0-logloss:0.21706
[850]	validation_0-logloss:0.21640
[900]	validation_0-logloss:0.21575
[950]	validation_0-logloss:0.21525
[1000]	validation_0-logloss:0.21478
[1050]	validation_0-logloss:0.21438
[1100]	validation_0-logloss:0.21393
[1150]	validation_0-logloss:0.21366
[1200]	validation_0-logloss:0.21348
[1250]	validation_0-logloss:0.21308
[1300]	validation_0-logloss:0.21284
[1350]	validation_0-logloss:0.21252
[1400]	validation_0-logloss:0.21217
[1450]	validation_0-logloss:0.21198
[1500]	validation_0-logloss:0.21166
[1550]	validation_0-logloss:0.21153
[1600]	validation_0-logloss:0.21137
[1650]	validation_0-logloss:0.21119
[1700]	validation_0-logloss:0.21109
[1750]	validation_0-logloss:0.21088
[1800]	validation_0-logloss:0.21058
[1850]	validation_0-logloss:0.21039
[1900]	validation_0-logloss:0.21028
[1950]	validation_0-logloss:0.21004
[2000]	validation_0-logloss:0.21002
[2050]	validation_0-logloss:0.20994
[2100]	validation_0-logloss:0.20995
[2150]	validation_0-logloss:0.20991
[2200]	validation_0-logloss:0.20990
[2250]	validation_0-logloss:0.20983
[2300]	validation_0-logloss:0.20973
[2350]	validation_0-logloss:0.20962
[2400]	validation_0-logloss:0.20950
[2450]	validation_0-logloss:0.20945
[2500]	validation_0-logloss:0.20944
[2550]	validation_0-logloss:0.20936
[2600]	validation_0-logloss:0.20930
[2650]	validation_0-logloss:0.20931
[2700]	validation_0-logloss:0.20925
[2750]	validation_0-logloss:0.20913
[2800]	validation_0-logloss:0.20911
[2850]	validation_0-logloss:0.20905
[2900]	validation_0-logloss:0.20903
[2950]	validation_0-logloss:0.20904
[3000]	validation_0-logloss:0.20904
[3050]	validation_0-logloss:0.20905
[3100]	validation_0-logloss:0.20901
[3150]	validation_0-logloss:0.20902
[3200]	validation_0-logloss:0.20903
[3250]	validation_0-logloss:0.20900
[3300]	validation_0-logloss:0.20899
[3350]	validation_0-logloss:0.20893
[3400]	validation_0-logloss:0.20889
[3450]	validation_0-logloss:0.20892
[3500]	validation_0-logloss:0.20896
[3550]	validation_0-logloss:0.20895
[3600]	validation_0-logloss:0.20891
[3650]	validation_0-logloss:0.20892
[3700]	validation_0-logloss:0.20893
[3750]	validation_0-logloss:0.20892
[3800]	validation_0-logloss:0.20887
[3850]	validation_0-logloss:0.20897
[3900]	validation_0-logloss:0.20902
[3950]	validation_0-logloss:0.20907
[4000]	validation_0-logloss:0.20904
[4050]	validation_0-logloss:0.20909
[4100]	validation_0-logloss:0.20909
[4150]	validation_0-logloss:0.20915
[4200]	validation_0-logloss:0.20918
[4250]	validation_0-logloss:0.20924
[4300]	validation_0-logloss:0.20929
[4350]	validation_0-logloss:0.20933
[4400]	validation_0-logloss:0.20939
[4450]	validation_0-logloss:0.20948
[4500]	validation_0-logloss:0.20957
[4550]	validation_0-logloss:0.20964
[4600]	validation_0-logloss:0.20973
[4650]	validation_0-logloss:0.20980
[4700]	validation_0-logloss:0.20987
[4750]	validation_0-logloss:0.20990
[4800]	validation_0-logloss:0.20991
[4850]	validation_0-logloss:0.20996
[4900]	validation_0-logloss:0.21008
[4950]	validation_0-logloss:0.21016
[4967]	validation_0-logloss:0.21020

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47405
[50]	validation_0-logloss:0.26652
[100]	validation_0-logloss:0.25225
[150]	validation_0-logloss:0.24502
[200]	validation_0-logloss:0.24007
[250]	validation_0-logloss:0.23628
[300]	validation_0-logloss:0.23308
[350]	validation_0-logloss:0.23066
[400]	validation_0-logloss:0.22848
[450]	validation_0-logloss:0.22722
[500]	validation_0-logloss:0.22566
[550]	validation_0-logloss:0.22440
[600]	validation_0-logloss:0.22340
[650]	validation_0-logloss:0.22243
[700]	validation_0-logloss:0.22157
[750]	validation_0-logloss:0.22049
[800]	validation_0-logloss:0.21977
[850]	validation_0-logloss:0.21935
[900]	validation_0-logloss:0.21844
[950]	validation_0-logloss:0.21796
[1000]	validation_0-logloss:0.21746
[1050]	validation_0-logloss:0.21704
[1100]	validation_0-logloss:0.21661
[1150]	validation_0-logloss:0.21627
[1200]	validation_0-logloss:0.21592
[1250]	validation_0-logloss:0.21571
[1300]	validation_0-logloss:0.21532
[1350]	validation_0-logloss:0.21518
[1400]	validation_0-logloss:0.21501
[1450]	validation_0-logloss:0.21478
[1500]	validation_0-logloss:0.21464
[1550]	validation_0-logloss:0.21451
[1600]	validation_0-logloss:0.21441
[1650]	validation_0-logloss:0.21426
[1700]	validation_0-logloss:0.21417
[1750]	validation_0-logloss:0.21407
[1800]	validation_0-logloss:0.21394
[1850]	validation_0-logloss:0.21384
[1900]	validation_0-logloss:0.21373
[1950]	validation_0-logloss:0.21372
[2000]	validation_0-logloss:0.21362
[2050]	validation_0-logloss:0.21359
[2100]	validation_0-logloss:0.21355
[2150]	validation_0-logloss:0.21357
[2200]	validation_0-logloss:0.21348
[2250]	validation_0-logloss:0.21344
[2300]	validation_0-logloss:0.21342
[2350]	validation_0-logloss:0.21343
[2400]	validation_0-logloss:0.21336
[2450]	validation_0-logloss:0.21333
[2500]	validation_0-logloss:0.21343
[2550]	validation_0-logloss:0.21345
[2600]	validation_0-logloss:0.21348
[2650]	validation_0-logloss:0.21341
[2700]	validation_0-logloss:0.21331
[2750]	validation_0-logloss:0.21330
[2800]	validation_0-logloss:0.21329
[2850]	validation_0-logloss:0.21335
[2900]	validation_0-logloss:0.21339
[2950]	validation_0-logloss:0.21344
[3000]	validation_0-logloss:0.21344
[3050]	validation_0-logloss:0.21344
[3100]	validation_0-logloss:0.21339
[3150]	validation_0-logloss:0.21346
[3200]	validation_0-logloss:0.21357
[3250]	validation_0-logloss:0.21367
[3300]	validation_0-logloss:0.21364
[3350]	validation_0-logloss:0.21366
[3400]	validation_0-logloss:0.21381
[3450]	validation_0-logloss:0.21389
[3500]	validation_0-logloss:0.21392
[3550]	validation_0-logloss:0.21398
[3577]	validation_0-logloss:0.21406

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47378
[50]	validation_0-logloss:0.26329
[100]	validation_0-logloss:0.24897
[150]	validation_0-logloss:0.24134
[200]	validation_0-logloss:0.23637
[250]	validation_0-logloss:0.23258
[300]	validation_0-logloss:0.22965
[350]	validation_0-logloss:0.22726
[400]	validation_0-logloss:0.22513
[450]	validation_0-logloss:0.22347
[500]	validation_0-logloss:0.22184
[550]	validation_0-logloss:0.22042
[600]	validation_0-logloss:0.21922
[650]	validation_0-logloss:0.21833
[700]	validation_0-logloss:0.21755
[750]	validation_0-logloss:0.21689
[800]	validation_0-logloss:0.21599
[850]	validation_0-logloss:0.21529
[900]	validation_0-logloss:0.21460
[950]	validation_0-logloss:0.21415
[1000]	validation_0-logloss:0.21364
[1050]	validation_0-logloss:0.21337
[1100]	validation_0-logloss:0.21309
[1150]	validation_0-logloss:0.21281
[1200]	validation_0-logloss:0.21239
[1250]	validation_0-logloss:0.21226
[1300]	validation_0-logloss:0.21202
[1350]	validation_0-logloss:0.21174
[1400]	validation_0-logloss:0.21162
[1450]	validation_0-logloss:0.21131
[1500]	validation_0-logloss:0.21110
[1550]	validation_0-logloss:0.21101
[1600]	validation_0-logloss:0.21088
[1650]	validation_0-logloss:0.21077
[1700]	validation_0-logloss:0.21071
[1750]	validation_0-logloss:0.21055
[1800]	validation_0-logloss:0.21036
[1850]	validation_0-logloss:0.21024
[1900]	validation_0-logloss:0.21016
[1950]	validation_0-logloss:0.20995
[2000]	validation_0-logloss:0.20987
[2050]	validation_0-logloss:0.20982
[2100]	validation_0-logloss:0.20971
[2150]	validation_0-logloss:0.20965
[2200]	validation_0-logloss:0.20958
[2250]	validation_0-logloss:0.20945
[2300]	validation_0-logloss:0.20937
[2350]	validation_0-logloss:0.20924
[2400]	validation_0-logloss:0.20919
[2450]	validation_0-logloss:0.20904
[2500]	validation_0-logloss:0.20896
[2550]	validation_0-logloss:0.20897
[2600]	validation_0-logloss:0.20898
[2650]	validation_0-logloss:0.20895
[2700]	validation_0-logloss:0.20888
[2750]	validation_0-logloss:0.20890
[2800]	validation_0-logloss:0.20890
[2850]	validation_0-logloss:0.20895
[2900]	validation_0-logloss:0.20894
[2950]	validation_0-logloss:0.20889
[3000]	validation_0-logloss:0.20890
[3050]	validation_0-logloss:0.20888
[3100]	validation_0-logloss:0.20889
[3150]	validation_0-logloss:0.20887
[3200]	validation_0-logloss:0.20883
[3250]	validation_0-logloss:0.20888
[3300]	validation_0-logloss:0.20888
[3350]	validation_0-logloss:0.20887
[3400]	validation_0-logloss:0.20894
[3450]	validation_0-logloss:0.20905
[3500]	validation_0-logloss:0.20906
[3550]	validation_0-logloss:0.20907
[3600]	validation_0-logloss:0.20914
[3650]	validation_0-logloss:0.20922
[3700]	validation_0-logloss:0.20923
[3750]	validation_0-logloss:0.20925
[3800]	validation_0-logloss:0.20925
[3850]	validation_0-logloss:0.20934
[3900]	validation_0-logloss:0.20939
[3950]	validation_0-logloss:0.20939
[4000]	validation_0-logloss:0.20952
[4050]	validation_0-logloss:0.20952
[4100]	validation_0-logloss:0.20959
[4150]	validation_0-logloss:0.20966
[4200]	validation_0-logloss:0.20970
[4250]	validation_0-logloss:0.20974
[4300]	validation_0-logloss:0.20986
[4339]	validation_0-logloss:0.20995

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47380
[50]	validation_0-logloss:0.26430
[100]	validation_0-logloss:0.24952
[150]	validation_0-logloss:0.24224
[200]	validation_0-logloss:0.23772
[250]	validation_0-logloss:0.23363
[300]	validation_0-logloss:0.23067
[350]	validation_0-logloss:0.22783
[400]	validation_0-logloss:0.22560
[450]	validation_0-logloss:0.22370
[500]	validation_0-logloss:0.22244
[550]	validation_0-logloss:0.22088
[600]	validation_0-logloss:0.21964
[650]	validation_0-logloss:0.21883
[700]	validation_0-logloss:0.21762
[750]	validation_0-logloss:0.21680
[800]	validation_0-logloss:0.21633
[850]	validation_0-logloss:0.21570
[900]	validation_0-logloss:0.21494
[950]	validation_0-logloss:0.21421
[1000]	validation_0-logloss:0.21376
[1050]	validation_0-logloss:0.21322
[1100]	validation_0-logloss:0.21272
[1150]	validation_0-logloss:0.21231
[1200]	validation_0-logloss:0.21196
[1250]	validation_0-logloss:0.21157
[1300]	validation_0-logloss:0.21137
[1350]	validation_0-logloss:0.21106
[1400]	validation_0-logloss:0.21067
[1450]	validation_0-logloss:0.21045
[1500]	validation_0-logloss:0.21022
[1550]	validation_0-logloss:0.21006
[1600]	validation_0-logloss:0.20988
[1650]	validation_0-logloss:0.20966
[1700]	validation_0-logloss:0.20937
[1750]	validation_0-logloss:0.20922
[1800]	validation_0-logloss:0.20900
[1850]	validation_0-logloss:0.20885
[1900]	validation_0-logloss:0.20880
[1950]	validation_0-logloss:0.20872
[2000]	validation_0-logloss:0.20868
[2050]	validation_0-logloss:0.20849
[2100]	validation_0-logloss:0.20846
[2150]	validation_0-logloss:0.20831
[2200]	validation_0-logloss:0.20827
[2250]	validation_0-logloss:0.20807
[2300]	validation_0-logloss:0.20801
[2350]	validation_0-logloss:0.20786
[2400]	validation_0-logloss:0.20778
[2450]	validation_0-logloss:0.20769
[2500]	validation_0-logloss:0.20768
[2550]	validation_0-logloss:0.20760
[2600]	validation_0-logloss:0.20753
[2650]	validation_0-logloss:0.20744
[2700]	validation_0-logloss:0.20736
[2750]	validation_0-logloss:0.20733
[2800]	validation_0-logloss:0.20727
[2850]	validation_0-logloss:0.20728
[2900]	validation_0-logloss:0.20735
[2950]	validation_0-logloss:0.20731
[3000]	validation_0-logloss:0.20729
[3050]	validation_0-logloss:0.20722
[3100]	validation_0-logloss:0.20720
[3150]	validation_0-logloss:0.20718
[3200]	validation_0-logloss:0.20714
[3250]	validation_0-logloss:0.20715
[3300]	validation_0-logloss:0.20712
[3350]	validation_0-logloss:0.20716
[3400]	validation_0-logloss:0.20716
[3450]	validation_0-logloss:0.20716
[3500]	validation_0-logloss:0.20722
[3550]	validation_0-logloss:0.20725
[3600]	validation_0-logloss:0.20727
[3650]	validation_0-logloss:0.20729
[3700]	validation_0-logloss:0.20729
[3750]	validation_0-logloss:0.20732
[3800]	validation_0-logloss:0.20741
[3850]	validation_0-logloss:0.20752
[3900]	validation_0-logloss:0.20758
[3950]	validation_0-logloss:0.20764
[4000]	validation_0-logloss:0.20765
[4050]	validation_0-logloss:0.20775
[4100]	validation_0-logloss:0.20779
[4150]	validation_0-logloss:0.20786
[4200]	validation_0-logloss:0.20793
[4250]	validation_0-logloss:0.20794
[4287]	validation_0-logloss:0.20795

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47383
[50]	validation_0-logloss:0.26385
[100]	validation_0-logloss:0.24925
[150]	validation_0-logloss:0.24199
[200]	validation_0-logloss:0.23702
[250]	validation_0-logloss:0.23288
[300]	validation_0-logloss:0.23020
[350]	validation_0-logloss:0.22747
[400]	validation_0-logloss:0.22552
[450]	validation_0-logloss:0.22378
[500]	validation_0-logloss:0.22228
[550]	validation_0-logloss:0.22117
[600]	validation_0-logloss:0.22007
[650]	validation_0-logloss:0.21901
[700]	validation_0-logloss:0.21825
[750]	validation_0-logloss:0.21772
[800]	validation_0-logloss:0.21679
[850]	validation_0-logloss:0.21615
[900]	validation_0-logloss:0.21554
[950]	validation_0-logloss:0.21494
[1000]	validation_0-logloss:0.21439
[1050]	validation_0-logloss:0.21414
[1100]	validation_0-logloss:0.21385
[1150]	validation_0-logloss:0.21346
[1200]	validation_0-logloss:0.21320
[1250]	validation_0-logloss:0.21291
[1300]	validation_0-logloss:0.21260
[1350]	validation_0-logloss:0.21229
[1400]	validation_0-logloss:0.21182
[1450]	validation_0-logloss:0.21156
[1500]	validation_0-logloss:0.21143
[1550]	validation_0-logloss:0.21125
[1600]	validation_0-logloss:0.21109
[1650]	validation_0-logloss:0.21099
[1700]	validation_0-logloss:0.21085
[1750]	validation_0-logloss:0.21062
[1800]	validation_0-logloss:0.21049
[1850]	validation_0-logloss:0.21047
[1900]	validation_0-logloss:0.21038
[1950]	validation_0-logloss:0.21027
[2000]	validation_0-logloss:0.21030
[2050]	validation_0-logloss:0.21017
[2100]	validation_0-logloss:0.21006
[2150]	validation_0-logloss:0.20993
[2200]	validation_0-logloss:0.20989
[2250]	validation_0-logloss:0.20972
[2300]	validation_0-logloss:0.20976
[2350]	validation_0-logloss:0.20966
[2400]	validation_0-logloss:0.20971
[2450]	validation_0-logloss:0.20974
[2500]	validation_0-logloss:0.20974
[2550]	validation_0-logloss:0.20972
[2600]	validation_0-logloss:0.20966
[2650]	validation_0-logloss:0.20956
[2700]	validation_0-logloss:0.20962
[2750]	validation_0-logloss:0.20965
[2800]	validation_0-logloss:0.20967
[2850]	validation_0-logloss:0.20966
[2900]	validation_0-logloss:0.20963
[2950]	validation_0-logloss:0.20965
[3000]	validation_0-logloss:0.20964
[3050]	validation_0-logloss:0.20966
[3100]	validation_0-logloss:0.20974
[3150]	validation_0-logloss:0.20981
[3200]	validation_0-logloss:0.20984
[3250]	validation_0-logloss:0.20980
[3300]	validation_0-logloss:0.20970
[3350]	validation_0-logloss:0.20975
[3400]	validation_0-logloss:0.20981
[3445]	validation_0-logloss:0.20983

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47348
[50]	validation_0-logloss:0.26290
[100]	validation_0-logloss:0.24852
[150]	validation_0-logloss:0.24127
[200]	validation_0-logloss:0.23612
[250]	validation_0-logloss:0.23289
[300]	validation_0-logloss:0.22953
[350]	validation_0-logloss:0.22705
[400]	validation_0-logloss:0.22519
[450]	validation_0-logloss:0.22390
[500]	validation_0-logloss:0.22231
[550]	validation_0-logloss:0.22131
[600]	validation_0-logloss:0.22001
[650]	validation_0-logloss:0.21867
[700]	validation_0-logloss:0.21780
[750]	validation_0-logloss:0.21690
[800]	validation_0-logloss:0.21625
[850]	validation_0-logloss:0.21585
[900]	validation_0-logloss:0.21539
[950]	validation_0-logloss:0.21489
[1000]	validation_0-logloss:0.21453
[1050]	validation_0-logloss:0.21423
[1100]	validation_0-logloss:0.21379
[1150]	validation_0-logloss:0.21356
[1200]	validation_0-logloss:0.21316
[1250]	validation_0-logloss:0.21281
[1300]	validation_0-logloss:0.21248
[1350]	validation_0-logloss:0.21220
[1400]	validation_0-logloss:0.21199
[1450]	validation_0-logloss:0.21182
[1500]	validation_0-logloss:0.21153
[1550]	validation_0-logloss:0.21123
[1600]	validation_0-logloss:0.21097
[1650]	validation_0-logloss:0.21072
[1700]	validation_0-logloss:0.21054
[1750]	validation_0-logloss:0.21044
[1800]	validation_0-logloss:0.21031
[1850]	validation_0-logloss:0.21010
[1900]	validation_0-logloss:0.21002
[1950]	validation_0-logloss:0.20994
[2000]	validation_0-logloss:0.20985
[2050]	validation_0-logloss:0.20975
[2100]	validation_0-logloss:0.20971
[2150]	validation_0-logloss:0.20966
[2200]	validation_0-logloss:0.20960
[2250]	validation_0-logloss:0.20957
[2300]	validation_0-logloss:0.20949
[2350]	validation_0-logloss:0.20940
[2400]	validation_0-logloss:0.20937
[2450]	validation_0-logloss:0.20936
[2500]	validation_0-logloss:0.20937
[2550]	validation_0-logloss:0.20938
[2600]	validation_0-logloss:0.20938
[2650]	validation_0-logloss:0.20944
[2700]	validation_0-logloss:0.20942
[2750]	validation_0-logloss:0.20933
[2800]	validation_0-logloss:0.20930
[2850]	validation_0-logloss:0.20928
[2900]	validation_0-logloss:0.20935
[2950]	validation_0-logloss:0.20937
[3000]	validation_0-logloss:0.20932
[3050]	validation_0-logloss:0.20932
[3100]	validation_0-logloss:0.20929
[3150]	validation_0-logloss:0.20921
[3200]	validation_0-logloss:0.20925
[3250]	validation_0-logloss:0.20933
[3300]	validation_0-logloss:0.20942
[3350]	validation_0-logloss:0.20949
[3400]	validation_0-logloss:0.20955
[3450]	validation_0-logloss:0.20952
[3500]	validation_0-logloss:0.20959
[3550]	validation_0-logloss:0.20967
[3600]	validation_0-logloss:0.20973
[3650]	validation_0-logloss:0.20976
[3700]	validation_0-logloss:0.20982
[3750]	validation_0-logloss:0.20985
[3800]	validation_0-logloss:0.20989
[3850]	validation_0-logloss:0.20996
[3900]	validation_0-logloss:0.21001
[3950]	validation_0-logloss:0.21005
[4000]	validation_0-logloss:0.21014
[4050]	validation_0-logloss:0.21022
[4099]	validation_0-logloss:0.21030

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47342
[50]	validation_0-logloss:0.26227
[100]	validation_0-logloss:0.24766
[150]	validation_0-logloss:0.24057
[200]	validation_0-logloss:0.23543
[250]	validation_0-logloss:0.23195
[300]	validation_0-logloss:0.22857
[350]	validation_0-logloss:0.22593
[400]	validation_0-logloss:0.22427
[450]	validation_0-logloss:0.22256
[500]	validation_0-logloss:0.22103
[550]	validation_0-logloss:0.21953
[600]	validation_0-logloss:0.21839
[650]	validation_0-logloss:0.21758
[700]	validation_0-logloss:0.21653
[750]	validation_0-logloss:0.21572
[800]	validation_0-logloss:0.21481
[850]	validation_0-logloss:0.21410
[900]	validation_0-logloss:0.21361
[950]	validation_0-logloss:0.21309
[1000]	validation_0-logloss:0.21254
[1050]	validation_0-logloss:0.21210
[1100]	validation_0-logloss:0.21190
[1150]	validation_0-logloss:0.21159
[1200]	validation_0-logloss:0.21124
[1250]	validation_0-logloss:0.21088
[1300]	validation_0-logloss:0.21071
[1350]	validation_0-logloss:0.21047
[1400]	validation_0-logloss:0.21025
[1450]	validation_0-logloss:0.21008
[1500]	validation_0-logloss:0.20998
[1550]	validation_0-logloss:0.20971
[1600]	validation_0-logloss:0.20957
[1650]	validation_0-logloss:0.20946
[1700]	validation_0-logloss:0.20938
[1750]	validation_0-logloss:0.20927
[1800]	validation_0-logloss:0.20918
[1850]	validation_0-logloss:0.20895
[1900]	validation_0-logloss:0.20879
[1950]	validation_0-logloss:0.20864
[2000]	validation_0-logloss:0.20851
[2050]	validation_0-logloss:0.20843
[2100]	validation_0-logloss:0.20831
[2150]	validation_0-logloss:0.20826
[2200]	validation_0-logloss:0.20823
[2250]	validation_0-logloss:0.20823
[2300]	validation_0-logloss:0.20822
[2350]	validation_0-logloss:0.20822
[2400]	validation_0-logloss:0.20820
[2450]	validation_0-logloss:0.20823
[2500]	validation_0-logloss:0.20818
[2550]	validation_0-logloss:0.20816
[2600]	validation_0-logloss:0.20818
[2650]	validation_0-logloss:0.20811
[2700]	validation_0-logloss:0.20814
[2750]	validation_0-logloss:0.20815
[2800]	validation_0-logloss:0.20817
[2850]	validation_0-logloss:0.20816
[2900]	validation_0-logloss:0.20816
[2950]	validation_0-logloss:0.20817
[3000]	validation_0-logloss:0.20825
[3050]	validation_0-logloss:0.20827
[3100]	validation_0-logloss:0.20829
[3150]	validation_0-logloss:0.20829
[3200]	validation_0-logloss:0.20830
[3250]	validation_0-logloss:0.20832
[3300]	validation_0-logloss:0.20831
[3350]	validation_0-logloss:0.20828
[3400]	validation_0-logloss:0.20827
[3450]	validation_0-logloss:0.20834
[3495]	validation_0-logloss:0.20833

Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\model.pkl
	0.9582	 = Validation score   (roc_auc)
	601.78s	 = Training   runtime
	4.34s	 = Validation runtime
	15551.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1192.18s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.1 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.31s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.9582	 = Validation score   (roc_auc)
	0.06s	 = Training   runtime
	0.05s	 = Validation runtime
	15527.6	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
AutoGluon training complete, total runtime = 607.98s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 15527.6 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models2\XGB\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models2\XGB")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       3.10 GB / 15.06 GB (20.6%)
Disk Space Avail:   724.31 GB / 930.47 GB (77.8%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models2\CAT"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

XGB completed.
Validation ROC-AUC: 0.958240

================================================================================
TRAINING: CAT
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models2\CAT
================================================================================

	Available Memory:                    3239.30 MB
	Train Data (Original)  Memory Usage: 136.13 MB (4.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.8s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.3% of available memory)
Data preprocessing and feature engineering runtime = 0.86s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\learner.pkl
User-specified model hyperparameters to be fit:
{
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\utils\data\y.pkl
Model configs that will be trained (in order):
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1799.14s of the 1799.14s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645542	test: 0.6645853	best: 0.6645853 (0)	total: 5.14ms	remaining: 5.14ms
1:	learn: 0.6386750	test: 0.6387354	best: 0.6387354 (1)	total: 10.3ms	remaining: 0us
bestTest = 0.638735364
bestIteration = 1
0:	learn: 0.6399425	test: 0.6400635	best: 0.6400635 (0)	total: 19.4ms	remaining: 5.35s
20:	learn: 0.3358512	test: 0.3362112	best: 0.3362112 (20)	total: 438ms	remaining: 5.34s
40:	learn: 0.3029078	test: 0.3031673	best: 0.3031673 (40)	total: 849ms	remaining: 4.89s
60:	learn: 0.2893096	test: 0.2891336	best: 0.2891336 (60)	total: 1.26s	remaining: 4.47s
80:	learn: 0.2810941	test: 0.2807428	best: 0.2807428 (80)	total: 1.67s	remaining: 4.04s
100:	learn: 0.2746054	test: 0.2739660	best: 0.2739660 (100)	total: 2.06s	remaining: 3.59s
120:	learn: 0.2696823	test: 0.2689095	best: 0.2689095 (120)	total: 2.45s	remaining: 3.16s
140:	learn: 0.2657470	test: 0.2648139	best: 0.2648139 (140)	total: 2.84s	remaining: 2.74s
160:	learn: 0.2622548	test: 0.2612113	best: 0.2612113 (160)	total: 3.24s	remaining: 2.33s
180:	learn: 0.2590721	test: 0.2579126	best: 0.2579126 (180)	total: 3.63s	remaining: 1.92s
200:	learn: 0.2564540	test: 0.2552462	best: 0.2552462 (200)	total: 4.01s	remaining: 1.51s
220:	learn: 0.2539532	test: 0.2526705	best: 0.2526705 (220)	total: 4.38s	remaining: 1.11s
240:	learn: 0.2516009	test: 0.2502394	best: 0.2502394 (240)	total: 4.77s	remaining: 713ms
260:	learn: 0.2496268	test: 0.2483094	best: 0.2483094 (260)	total: 5.17s	remaining: 317ms
276:	learn: 0.2483970	test: 0.2471037	best: 0.2471037 (276)	total: 5.48s	remaining: 0us
bestTest = 0.247103676
bestIteration = 276

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645342	test: 0.6646592	best: 0.6646592 (0)	total: 5.27ms	remaining: 5.27ms
1:	learn: 0.6386355	test: 0.6388839	best: 0.6388839 (1)	total: 10.3ms	remaining: 0us
bestTest = 0.6388838519
bestIteration = 1
0:	learn: 0.6397470	test: 0.6400253	best: 0.6400253 (0)	total: 19ms	remaining: 10.1s
20:	learn: 0.3344490	test: 0.3365073	best: 0.3365073 (20)	total: 433ms	remaining: 10.6s
40:	learn: 0.3006305	test: 0.3030997	best: 0.3030997 (40)	total: 842ms	remaining: 10.1s
60:	learn: 0.2877957	test: 0.2899635	best: 0.2899635 (60)	total: 1.25s	remaining: 9.75s
80:	learn: 0.2780738	test: 0.2799241	best: 0.2799241 (80)	total: 1.67s	remaining: 9.37s
100:	learn: 0.2729790	test: 0.2748190	best: 0.2748190 (100)	total: 2.09s	remaining: 8.99s
120:	learn: 0.2689998	test: 0.2707972	best: 0.2707972 (120)	total: 2.49s	remaining: 8.54s
140:	learn: 0.2643352	test: 0.2661018	best: 0.2661018 (140)	total: 2.9s	remaining: 8.1s
160:	learn: 0.2607609	test: 0.2625923	best: 0.2625923 (160)	total: 3.29s	remaining: 7.64s
180:	learn: 0.2579845	test: 0.2598380	best: 0.2598380 (180)	total: 3.69s	remaining: 7.21s
200:	learn: 0.2553604	test: 0.2569768	best: 0.2569768 (200)	total: 4.12s	remaining: 6.84s
220:	learn: 0.2532643	test: 0.2547981	best: 0.2547981 (220)	total: 4.51s	remaining: 6.41s
240:	learn: 0.2510723	test: 0.2524955	best: 0.2524955 (240)	total: 4.92s	remaining: 6s
260:	learn: 0.2490238	test: 0.2503471	best: 0.2503471 (260)	total: 5.33s	remaining: 5.59s
280:	learn: 0.2475550	test: 0.2488329	best: 0.2488329 (280)	total: 5.73s	remaining: 5.18s
300:	learn: 0.2459227	test: 0.2471690	best: 0.2471690 (300)	total: 6.13s	remaining: 4.77s
320:	learn: 0.2445199	test: 0.2457867	best: 0.2457867 (320)	total: 6.52s	remaining: 4.35s
340:	learn: 0.2433390	test: 0.2446406	best: 0.2446406 (340)	total: 6.91s	remaining: 3.93s
360:	learn: 0.2422491	test: 0.2436713	best: 0.2436713 (360)	total: 7.3s	remaining: 3.52s
380:	learn: 0.2409128	test: 0.2423706	best: 0.2423706 (380)	total: 7.72s	remaining: 3.12s
400:	learn: 0.2397950	test: 0.2413376	best: 0.2413376 (400)	total: 8.12s	remaining: 2.71s
420:	learn: 0.2388946	test: 0.2404475	best: 0.2404475 (420)	total: 8.51s	remaining: 2.3s
440:	learn: 0.2380002	test: 0.2395995	best: 0.2395995 (440)	total: 8.91s	remaining: 1.9s
460:	learn: 0.2370717	test: 0.2386827	best: 0.2386827 (460)	total: 9.31s	remaining: 1.5s
480:	learn: 0.2363368	test: 0.2380500	best: 0.2380500 (480)	total: 9.72s	remaining: 1.09s
500:	learn: 0.2354347	test: 0.2372408	best: 0.2372408 (500)	total: 10.1s	remaining: 687ms
520:	learn: 0.2347201	test: 0.2365862	best: 0.2365862 (520)	total: 10.5s	remaining: 283ms
534:	learn: 0.2343264	test: 0.2362724	best: 0.2362724 (534)	total: 10.8s	remaining: 0us
bestTest = 0.2362723553
bestIteration = 534

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645496	test: 0.6646142	best: 0.6646142 (0)	total: 5.63ms	remaining: 5.63ms
1:	learn: 0.6386624	test: 0.6388009	best: 0.6388009 (1)	total: 10.5ms	remaining: 0us
bestTest = 0.6388009346
bestIteration = 1
0:	learn: 0.6399189	test: 0.6399821	best: 0.6399821 (0)	total: 19.9ms	remaining: 12.3s
20:	learn: 0.3359186	test: 0.3368528	best: 0.3368528 (20)	total: 445ms	remaining: 12.7s
40:	learn: 0.3022278	test: 0.3035941	best: 0.3035941 (40)	total: 866ms	remaining: 12.3s
60:	learn: 0.2894653	test: 0.2905800	best: 0.2905800 (60)	total: 1.29s	remaining: 11.9s
80:	learn: 0.2811065	test: 0.2822411	best: 0.2822411 (80)	total: 1.72s	remaining: 11.5s
100:	learn: 0.2752100	test: 0.2763467	best: 0.2763467 (100)	total: 2.11s	remaining: 10.9s
120:	learn: 0.2701063	test: 0.2714468	best: 0.2714468 (120)	total: 2.5s	remaining: 10.3s
140:	learn: 0.2660930	test: 0.2674454	best: 0.2674454 (140)	total: 2.88s	remaining: 9.83s
160:	learn: 0.2619203	test: 0.2631670	best: 0.2631670 (160)	total: 3.27s	remaining: 9.38s
180:	learn: 0.2589910	test: 0.2603500	best: 0.2603500 (180)	total: 3.66s	remaining: 8.91s
200:	learn: 0.2562076	test: 0.2573833	best: 0.2573833 (200)	total: 4.06s	remaining: 8.51s
220:	learn: 0.2539381	test: 0.2551862	best: 0.2551862 (220)	total: 4.47s	remaining: 8.12s
240:	learn: 0.2517968	test: 0.2531813	best: 0.2531813 (240)	total: 4.86s	remaining: 7.68s
260:	learn: 0.2498995	test: 0.2512677	best: 0.2512677 (260)	total: 5.25s	remaining: 7.26s
280:	learn: 0.2482607	test: 0.2496983	best: 0.2496983 (280)	total: 5.62s	remaining: 6.83s
300:	learn: 0.2466902	test: 0.2482124	best: 0.2482124 (300)	total: 6.02s	remaining: 6.42s
320:	learn: 0.2447666	test: 0.2462369	best: 0.2462369 (320)	total: 6.42s	remaining: 6.02s
340:	learn: 0.2432839	test: 0.2448112	best: 0.2448112 (340)	total: 6.81s	remaining: 5.61s
360:	learn: 0.2423031	test: 0.2440250	best: 0.2440250 (360)	total: 7.19s	remaining: 5.2s
380:	learn: 0.2412890	test: 0.2431612	best: 0.2431612 (380)	total: 7.57s	remaining: 4.79s
400:	learn: 0.2403198	test: 0.2422805	best: 0.2422805 (400)	total: 7.95s	remaining: 4.38s
420:	learn: 0.2392517	test: 0.2412567	best: 0.2412567 (420)	total: 8.34s	remaining: 3.98s
440:	learn: 0.2382439	test: 0.2403314	best: 0.2403314 (440)	total: 8.74s	remaining: 3.58s
460:	learn: 0.2374091	test: 0.2395853	best: 0.2395853 (460)	total: 9.13s	remaining: 3.19s
480:	learn: 0.2365837	test: 0.2388478	best: 0.2388478 (480)	total: 9.51s	remaining: 2.79s
500:	learn: 0.2357717	test: 0.2381211	best: 0.2381211 (500)	total: 9.91s	remaining: 2.39s
520:	learn: 0.2350005	test: 0.2374195	best: 0.2374195 (520)	total: 10.3s	remaining: 2s
540:	learn: 0.2342659	test: 0.2367815	best: 0.2367815 (540)	total: 10.7s	remaining: 1.6s
560:	learn: 0.2336191	test: 0.2362335	best: 0.2362335 (560)	total: 11.1s	remaining: 1.21s
580:	learn: 0.2328429	test: 0.2355900	best: 0.2355900 (580)	total: 11.5s	remaining: 811ms
600:	learn: 0.2322153	test: 0.2350870	best: 0.2350870 (600)	total: 11.9s	remaining: 415ms
620:	learn: 0.2315518	test: 0.2345021	best: 0.2345021 (620)	total: 12.3s	remaining: 19.7ms
621:	learn: 0.2315326	test: 0.2344923	best: 0.2344923 (621)	total: 12.3s	remaining: 0us
bestTest = 0.2344922927
bestIteration = 621

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645499	test: 0.6645861	best: 0.6645861 (0)	total: 5.23ms	remaining: 5.23ms
1:	learn: 0.6386830	test: 0.6387550	best: 0.6387550 (1)	total: 10.2ms	remaining: 0us
bestTest = 0.6387549658
bestIteration = 1
0:	learn: 0.6399839	test: 0.6397896	best: 0.6397896 (0)	total: 18.7ms	remaining: 13.9s
20:	learn: 0.3356798	test: 0.3351188	best: 0.3351188 (20)	total: 428ms	remaining: 14.7s
40:	learn: 0.3028135	test: 0.3021782	best: 0.3021782 (40)	total: 833ms	remaining: 14.2s
60:	learn: 0.2893867	test: 0.2883411	best: 0.2883411 (60)	total: 1.25s	remaining: 13.9s
80:	learn: 0.2806703	test: 0.2793080	best: 0.2793080 (80)	total: 1.66s	remaining: 13.5s
100:	learn: 0.2744139	test: 0.2730750	best: 0.2730750 (100)	total: 2.06s	remaining: 13.1s
120:	learn: 0.2696039	test: 0.2683865	best: 0.2683865 (120)	total: 2.44s	remaining: 12.5s
140:	learn: 0.2656911	test: 0.2644345	best: 0.2644345 (140)	total: 2.83s	remaining: 12.1s
160:	learn: 0.2619283	test: 0.2602524	best: 0.2602524 (160)	total: 3.23s	remaining: 11.7s
180:	learn: 0.2588481	test: 0.2571652	best: 0.2571652 (180)	total: 3.63s	remaining: 11.2s
200:	learn: 0.2562015	test: 0.2546272	best: 0.2546272 (200)	total: 4.01s	remaining: 10.8s
220:	learn: 0.2538038	test: 0.2521621	best: 0.2521621 (220)	total: 4.4s	remaining: 10.4s
240:	learn: 0.2517833	test: 0.2501218	best: 0.2501218 (240)	total: 4.79s	remaining: 9.96s
260:	learn: 0.2500220	test: 0.2484292	best: 0.2484292 (260)	total: 5.18s	remaining: 9.54s
280:	learn: 0.2484337	test: 0.2468636	best: 0.2468636 (280)	total: 5.57s	remaining: 9.13s
300:	learn: 0.2468450	test: 0.2453035	best: 0.2453035 (300)	total: 5.95s	remaining: 8.72s
320:	learn: 0.2457201	test: 0.2443079	best: 0.2443079 (320)	total: 6.33s	remaining: 8.3s
340:	learn: 0.2443900	test: 0.2430896	best: 0.2430896 (340)	total: 6.72s	remaining: 7.9s
360:	learn: 0.2432654	test: 0.2420690	best: 0.2420690 (360)	total: 7.1s	remaining: 7.49s
380:	learn: 0.2421210	test: 0.2409618	best: 0.2409618 (380)	total: 7.48s	remaining: 7.09s
400:	learn: 0.2410408	test: 0.2399257	best: 0.2399257 (400)	total: 7.86s	remaining: 6.68s
420:	learn: 0.2396850	test: 0.2385846	best: 0.2385846 (420)	total: 8.24s	remaining: 6.28s
440:	learn: 0.2388686	test: 0.2378489	best: 0.2378489 (440)	total: 8.62s	remaining: 5.88s
460:	learn: 0.2378751	test: 0.2369521	best: 0.2369521 (460)	total: 9.01s	remaining: 5.49s
480:	learn: 0.2368825	test: 0.2360232	best: 0.2360232 (480)	total: 9.39s	remaining: 5.1s
500:	learn: 0.2362181	test: 0.2354440	best: 0.2354440 (500)	total: 9.78s	remaining: 4.7s
520:	learn: 0.2355002	test: 0.2347878	best: 0.2347878 (520)	total: 10.2s	remaining: 4.31s
540:	learn: 0.2348384	test: 0.2342133	best: 0.2342133 (540)	total: 10.6s	remaining: 3.92s
560:	learn: 0.2341959	test: 0.2336902	best: 0.2336902 (560)	total: 10.9s	remaining: 3.53s
580:	learn: 0.2334604	test: 0.2330484	best: 0.2330484 (580)	total: 11.3s	remaining: 3.14s
600:	learn: 0.2328495	test: 0.2325569	best: 0.2325569 (600)	total: 11.7s	remaining: 2.74s
620:	learn: 0.2322186	test: 0.2319908	best: 0.2319908 (620)	total: 12.1s	remaining: 2.36s
640:	learn: 0.2317091	test: 0.2315809	best: 0.2315809 (640)	total: 12.5s	remaining: 1.96s
660:	learn: 0.2311447	test: 0.2311439	best: 0.2311439 (660)	total: 12.8s	remaining: 1.57s
680:	learn: 0.2306249	test: 0.2307461	best: 0.2307461 (680)	total: 13.2s	remaining: 1.18s
700:	learn: 0.2300904	test: 0.2302532	best: 0.2302532 (700)	total: 13.6s	remaining: 797ms
720:	learn: 0.2295573	test: 0.2298239	best: 0.2298239 (720)	total: 14s	remaining: 408ms
740:	learn: 0.2289235	test: 0.2292416	best: 0.2292416 (740)	total: 14.4s	remaining: 19.4ms
741:	learn: 0.2288956	test: 0.2292167	best: 0.2292167 (741)	total: 14.4s	remaining: 0us
bestTest = 0.2292167071
bestIteration = 741

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645572	test: 0.6645441	best: 0.6645441 (0)	total: 5.48ms	remaining: 5.48ms
1:	learn: 0.6386832	test: 0.6386617	best: 0.6386617 (1)	total: 10.2ms	remaining: 0us
bestTest = 0.6386616983
bestIteration = 1
0:	learn: 0.6400674	test: 0.6400890	best: 0.6400890 (0)	total: 18.6ms	remaining: 17.4s
20:	learn: 0.3349261	test: 0.3353332	best: 0.3353332 (20)	total: 429ms	remaining: 18.7s
40:	learn: 0.3034185	test: 0.3041214	best: 0.3041214 (40)	total: 841ms	remaining: 18.3s
60:	learn: 0.2900421	test: 0.2901246	best: 0.2901246 (60)	total: 1.26s	remaining: 18s
80:	learn: 0.2814410	test: 0.2813066	best: 0.2813066 (80)	total: 1.66s	remaining: 17.5s
100:	learn: 0.2762633	test: 0.2759699	best: 0.2759699 (100)	total: 2.05s	remaining: 16.9s
120:	learn: 0.2712418	test: 0.2708109	best: 0.2708109 (120)	total: 2.42s	remaining: 16.3s
140:	learn: 0.2668658	test: 0.2660017	best: 0.2660017 (140)	total: 2.81s	remaining: 15.8s
160:	learn: 0.2626584	test: 0.2615510	best: 0.2615510 (160)	total: 3.2s	remaining: 15.4s
180:	learn: 0.2601098	test: 0.2590110	best: 0.2590110 (180)	total: 3.59s	remaining: 14.9s
200:	learn: 0.2570698	test: 0.2558217	best: 0.2558217 (200)	total: 3.99s	remaining: 14.6s
220:	learn: 0.2544148	test: 0.2529698	best: 0.2529698 (220)	total: 4.38s	remaining: 14.2s
240:	learn: 0.2517311	test: 0.2500714	best: 0.2500714 (240)	total: 4.76s	remaining: 13.7s
260:	learn: 0.2498228	test: 0.2481619	best: 0.2481619 (260)	total: 5.15s	remaining: 13.3s
280:	learn: 0.2482618	test: 0.2466076	best: 0.2466076 (280)	total: 5.53s	remaining: 12.9s
300:	learn: 0.2467635	test: 0.2451295	best: 0.2451295 (300)	total: 5.9s	remaining: 12.4s
320:	learn: 0.2453050	test: 0.2436593	best: 0.2436593 (320)	total: 6.28s	remaining: 12s
340:	learn: 0.2441750	test: 0.2425735	best: 0.2425735 (340)	total: 6.66s	remaining: 11.6s
360:	learn: 0.2430479	test: 0.2415480	best: 0.2415480 (360)	total: 7.04s	remaining: 11.2s
380:	learn: 0.2418722	test: 0.2403554	best: 0.2403554 (380)	total: 7.42s	remaining: 10.8s
400:	learn: 0.2408956	test: 0.2394739	best: 0.2394739 (400)	total: 7.8s	remaining: 10.4s
420:	learn: 0.2398286	test: 0.2384415	best: 0.2384415 (420)	total: 8.18s	remaining: 9.98s
440:	learn: 0.2387270	test: 0.2373959	best: 0.2373959 (440)	total: 8.56s	remaining: 9.59s
460:	learn: 0.2378026	test: 0.2365308	best: 0.2365308 (460)	total: 8.95s	remaining: 9.2s
480:	learn: 0.2370484	test: 0.2358521	best: 0.2358521 (480)	total: 9.34s	remaining: 8.81s
500:	learn: 0.2361434	test: 0.2350121	best: 0.2350121 (500)	total: 9.72s	remaining: 8.42s
520:	learn: 0.2355531	test: 0.2345423	best: 0.2345423 (520)	total: 10.1s	remaining: 8.04s
540:	learn: 0.2347188	test: 0.2337693	best: 0.2337693 (540)	total: 10.5s	remaining: 7.64s
560:	learn: 0.2340185	test: 0.2331523	best: 0.2331523 (560)	total: 10.9s	remaining: 7.24s
580:	learn: 0.2333726	test: 0.2325376	best: 0.2325376 (580)	total: 11.2s	remaining: 6.85s
600:	learn: 0.2326817	test: 0.2319423	best: 0.2319423 (600)	total: 11.6s	remaining: 6.46s
620:	learn: 0.2320442	test: 0.2314102	best: 0.2314102 (620)	total: 12s	remaining: 6.08s
640:	learn: 0.2315732	test: 0.2310359	best: 0.2310359 (640)	total: 12.4s	remaining: 5.69s
660:	learn: 0.2309366	test: 0.2304659	best: 0.2304659 (660)	total: 12.8s	remaining: 5.29s
680:	learn: 0.2303220	test: 0.2298707	best: 0.2298707 (680)	total: 13.2s	remaining: 4.91s
700:	learn: 0.2298465	test: 0.2295233	best: 0.2295233 (700)	total: 13.5s	remaining: 4.52s
720:	learn: 0.2292681	test: 0.2289948	best: 0.2289948 (720)	total: 13.9s	remaining: 4.13s
740:	learn: 0.2287056	test: 0.2285233	best: 0.2285233 (740)	total: 14.3s	remaining: 3.75s
760:	learn: 0.2281084	test: 0.2279753	best: 0.2279753 (760)	total: 14.7s	remaining: 3.36s
780:	learn: 0.2276245	test: 0.2275540	best: 0.2275540 (780)	total: 15.1s	remaining: 2.97s
800:	learn: 0.2270900	test: 0.2270290	best: 0.2270290 (800)	total: 15.5s	remaining: 2.58s
820:	learn: 0.2266088	test: 0.2266442	best: 0.2266442 (820)	total: 15.8s	remaining: 2.2s
840:	learn: 0.2262485	test: 0.2263749	best: 0.2263749 (840)	total: 16.2s	remaining: 1.81s
860:	learn: 0.2257774	test: 0.2259533	best: 0.2259533 (860)	total: 16.6s	remaining: 1.43s
880:	learn: 0.2253950	test: 0.2256735	best: 0.2256735 (880)	total: 17s	remaining: 1.04s
900:	learn: 0.2250052	test: 0.2253394	best: 0.2253394 (900)	total: 17.4s	remaining: 656ms
920:	learn: 0.2246340	test: 0.2250510	best: 0.2250510 (920)	total: 17.8s	remaining: 270ms
934:	learn: 0.2244277	test: 0.2249048	best: 0.2249048 (934)	total: 18s	remaining: 0us
bestTest = 0.2249047752
bestIteration = 934

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645644	test: 0.6645412	best: 0.6645412 (0)	total: 5.08ms	remaining: 5.08ms
1:	learn: 0.6387112	test: 0.6386665	best: 0.6386665 (1)	total: 10ms	remaining: 0us
bestTest = 0.6386665263
bestIteration = 1
0:	learn: 0.6398220	test: 0.6395630	best: 0.6395630 (0)	total: 18.9ms	remaining: 23.1s
20:	learn: 0.3337624	test: 0.3336918	best: 0.3336918 (20)	total: 437ms	remaining: 25.1s
40:	learn: 0.3027506	test: 0.3029605	best: 0.3029605 (40)	total: 847ms	remaining: 24.5s
60:	learn: 0.2883685	test: 0.2878140	best: 0.2878140 (60)	total: 1.26s	remaining: 24.1s
80:	learn: 0.2797838	test: 0.2789524	best: 0.2789524 (80)	total: 1.66s	remaining: 23.4s
100:	learn: 0.2739211	test: 0.2729982	best: 0.2729982 (100)	total: 2.04s	remaining: 22.8s
120:	learn: 0.2693127	test: 0.2684128	best: 0.2684128 (120)	total: 2.43s	remaining: 22.2s
140:	learn: 0.2653927	test: 0.2643228	best: 0.2643228 (140)	total: 2.83s	remaining: 21.8s
160:	learn: 0.2617757	test: 0.2605429	best: 0.2605429 (160)	total: 3.22s	remaining: 21.3s
180:	learn: 0.2588261	test: 0.2576271	best: 0.2576271 (180)	total: 3.61s	remaining: 20.9s
200:	learn: 0.2557178	test: 0.2543598	best: 0.2543598 (200)	total: 3.99s	remaining: 20.4s
220:	learn: 0.2532507	test: 0.2517926	best: 0.2517926 (220)	total: 4.37s	remaining: 19.9s
240:	learn: 0.2511042	test: 0.2496130	best: 0.2496130 (240)	total: 4.76s	remaining: 19.5s
260:	learn: 0.2493084	test: 0.2477894	best: 0.2477894 (260)	total: 5.15s	remaining: 19s
280:	learn: 0.2478407	test: 0.2463662	best: 0.2463662 (280)	total: 5.54s	remaining: 18.7s
300:	learn: 0.2464213	test: 0.2450236	best: 0.2450236 (300)	total: 5.91s	remaining: 18.2s
320:	learn: 0.2450999	test: 0.2437887	best: 0.2437887 (320)	total: 6.27s	remaining: 17.7s
340:	learn: 0.2437202	test: 0.2424084	best: 0.2424084 (340)	total: 6.66s	remaining: 17.3s
360:	learn: 0.2422912	test: 0.2409515	best: 0.2409515 (360)	total: 7.04s	remaining: 16.9s
380:	learn: 0.2414132	test: 0.2401773	best: 0.2401773 (380)	total: 7.42s	remaining: 16.5s
400:	learn: 0.2404370	test: 0.2392950	best: 0.2392950 (400)	total: 7.8s	remaining: 16.1s
420:	learn: 0.2394628	test: 0.2383605	best: 0.2383605 (420)	total: 8.18s	remaining: 15.7s
440:	learn: 0.2384766	test: 0.2374523	best: 0.2374523 (440)	total: 8.56s	remaining: 15.3s
460:	learn: 0.2377002	test: 0.2367436	best: 0.2367436 (460)	total: 8.95s	remaining: 14.9s
480:	learn: 0.2369534	test: 0.2360929	best: 0.2360929 (480)	total: 9.33s	remaining: 14.5s
500:	learn: 0.2361977	test: 0.2354406	best: 0.2354406 (500)	total: 9.72s	remaining: 14.1s
520:	learn: 0.2354578	test: 0.2347544	best: 0.2347544 (520)	total: 10.1s	remaining: 13.7s
540:	learn: 0.2346079	test: 0.2339757	best: 0.2339757 (540)	total: 10.6s	remaining: 13.4s
560:	learn: 0.2339435	test: 0.2334084	best: 0.2334084 (560)	total: 11s	remaining: 13s
580:	learn: 0.2330862	test: 0.2325745	best: 0.2325745 (580)	total: 11.4s	remaining: 12.6s
600:	learn: 0.2324610	test: 0.2320480	best: 0.2320480 (600)	total: 11.8s	remaining: 12.3s
620:	learn: 0.2318261	test: 0.2315068	best: 0.2315068 (620)	total: 12.2s	remaining: 11.9s
640:	learn: 0.2311785	test: 0.2309609	best: 0.2309609 (640)	total: 12.6s	remaining: 11.5s
660:	learn: 0.2305478	test: 0.2304560	best: 0.2304560 (660)	total: 13s	remaining: 11.1s
680:	learn: 0.2299984	test: 0.2300193	best: 0.2300193 (680)	total: 13.4s	remaining: 10.7s
700:	learn: 0.2294740	test: 0.2296030	best: 0.2296030 (700)	total: 13.8s	remaining: 10.3s
720:	learn: 0.2288198	test: 0.2290525	best: 0.2290525 (720)	total: 14.2s	remaining: 9.95s
740:	learn: 0.2283262	test: 0.2286516	best: 0.2286516 (740)	total: 14.6s	remaining: 9.56s
760:	learn: 0.2278021	test: 0.2282056	best: 0.2282056 (760)	total: 15s	remaining: 9.16s
780:	learn: 0.2273624	test: 0.2278932	best: 0.2278932 (780)	total: 15.4s	remaining: 8.77s
800:	learn: 0.2269277	test: 0.2275763	best: 0.2275763 (800)	total: 15.8s	remaining: 8.38s
820:	learn: 0.2264727	test: 0.2272282	best: 0.2272282 (820)	total: 16.2s	remaining: 7.99s
840:	learn: 0.2260332	test: 0.2268929	best: 0.2268929 (840)	total: 16.6s	remaining: 7.6s
860:	learn: 0.2256090	test: 0.2265444	best: 0.2265444 (860)	total: 16.9s	remaining: 7.2s
880:	learn: 0.2251936	test: 0.2262410	best: 0.2262410 (880)	total: 17.3s	remaining: 6.81s
900:	learn: 0.2248112	test: 0.2259584	best: 0.2259584 (900)	total: 17.8s	remaining: 6.43s
920:	learn: 0.2243742	test: 0.2256514	best: 0.2256514 (920)	total: 18.2s	remaining: 6.03s
940:	learn: 0.2239944	test: 0.2253940	best: 0.2253940 (940)	total: 18.6s	remaining: 5.64s
960:	learn: 0.2235683	test: 0.2250714	best: 0.2250714 (960)	total: 19s	remaining: 5.25s
980:	learn: 0.2231049	test: 0.2246860	best: 0.2246860 (980)	total: 19.4s	remaining: 4.86s
1000:	learn: 0.2227721	test: 0.2244405	best: 0.2244405 (1000)	total: 19.8s	remaining: 4.46s
1020:	learn: 0.2223945	test: 0.2241305	best: 0.2241305 (1020)	total: 20.2s	remaining: 4.07s
1040:	learn: 0.2220288	test: 0.2238879	best: 0.2238879 (1040)	total: 20.6s	remaining: 3.68s
1060:	learn: 0.2216946	test: 0.2236768	best: 0.2236768 (1060)	total: 21s	remaining: 3.28s
1080:	learn: 0.2213542	test: 0.2234292	best: 0.2234292 (1080)	total: 21.4s	remaining: 2.89s
1100:	learn: 0.2210288	test: 0.2231685	best: 0.2231685 (1100)	total: 21.8s	remaining: 2.49s
1120:	learn: 0.2207033	test: 0.2229394	best: 0.2229394 (1120)	total: 22.2s	remaining: 2.1s
1140:	learn: 0.2204332	test: 0.2227589	best: 0.2227589 (1140)	total: 22.6s	remaining: 1.7s
1160:	learn: 0.2201067	test: 0.2225518	best: 0.2225518 (1160)	total: 23s	remaining: 1.31s
1180:	learn: 0.2197715	test: 0.2223438	best: 0.2223438 (1180)	total: 23.4s	remaining: 911ms
1200:	learn: 0.2195051	test: 0.2221821	best: 0.2221821 (1200)	total: 23.8s	remaining: 515ms
1220:	learn: 0.2192046	test: 0.2219678	best: 0.2219678 (1220)	total: 24.2s	remaining: 119ms
1226:	learn: 0.2191116	test: 0.2218939	best: 0.2218939 (1226)	total: 24.3s	remaining: 0us
bestTest = 0.2218938937
bestIteration = 1226

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645826	test: 0.6644929	best: 0.6644929 (0)	total: 5.61ms	remaining: 5.61ms
1:	learn: 0.6387275	test: 0.6385586	best: 0.6385586 (1)	total: 10.6ms	remaining: 0us
bestTest = 0.6385586282
bestIteration = 1
0:	learn: 0.6402532	test: 0.6401011	best: 0.6401011 (0)	total: 18.9ms	remaining: 30s
20:	learn: 0.3353548	test: 0.3336641	best: 0.3336641 (20)	total: 430ms	remaining: 32s
40:	learn: 0.3033939	test: 0.3015607	best: 0.3015607 (40)	total: 858ms	remaining: 32.3s
60:	learn: 0.2898147	test: 0.2876867	best: 0.2876867 (60)	total: 1.29s	remaining: 32.1s
80:	learn: 0.2803573	test: 0.2779504	best: 0.2779504 (80)	total: 1.7s	remaining: 31.5s
100:	learn: 0.2746655	test: 0.2723523	best: 0.2723523 (100)	total: 2.1s	remaining: 30.8s
120:	learn: 0.2700822	test: 0.2679755	best: 0.2679755 (120)	total: 2.49s	remaining: 30.1s
140:	learn: 0.2657649	test: 0.2637083	best: 0.2637083 (140)	total: 2.89s	remaining: 29.6s
160:	learn: 0.2617710	test: 0.2598875	best: 0.2598875 (160)	total: 3.28s	remaining: 29s
180:	learn: 0.2584081	test: 0.2566526	best: 0.2566526 (180)	total: 3.68s	remaining: 28.5s
200:	learn: 0.2556681	test: 0.2540082	best: 0.2540082 (200)	total: 4.07s	remaining: 28s
220:	learn: 0.2537551	test: 0.2522514	best: 0.2522514 (220)	total: 4.45s	remaining: 27.5s
240:	learn: 0.2521505	test: 0.2507460	best: 0.2507460 (240)	total: 4.86s	remaining: 27.1s
260:	learn: 0.2504720	test: 0.2492506	best: 0.2492506 (260)	total: 5.25s	remaining: 26.6s
280:	learn: 0.2488228	test: 0.2476752	best: 0.2476752 (280)	total: 5.63s	remaining: 26.1s
300:	learn: 0.2473950	test: 0.2463746	best: 0.2463746 (300)	total: 6.03s	remaining: 25.7s
320:	learn: 0.2457981	test: 0.2448126	best: 0.2448126 (320)	total: 6.41s	remaining: 25.2s
340:	learn: 0.2442462	test: 0.2433179	best: 0.2433179 (340)	total: 6.8s	remaining: 24.8s
360:	learn: 0.2427725	test: 0.2419333	best: 0.2419333 (360)	total: 7.18s	remaining: 24.3s
380:	learn: 0.2414938	test: 0.2406586	best: 0.2406586 (380)	total: 7.61s	remaining: 24s
400:	learn: 0.2403608	test: 0.2395793	best: 0.2395793 (400)	total: 8s	remaining: 23.6s
420:	learn: 0.2393788	test: 0.2386863	best: 0.2386863 (420)	total: 8.38s	remaining: 23.2s
440:	learn: 0.2382492	test: 0.2376791	best: 0.2376791 (440)	total: 8.76s	remaining: 22.7s
460:	learn: 0.2373820	test: 0.2369283	best: 0.2369283 (460)	total: 9.14s	remaining: 22.3s
480:	learn: 0.2365193	test: 0.2362102	best: 0.2362102 (480)	total: 9.51s	remaining: 21.8s
500:	learn: 0.2356415	test: 0.2354420	best: 0.2354420 (500)	total: 9.9s	remaining: 21.4s
520:	learn: 0.2348491	test: 0.2347539	best: 0.2347539 (520)	total: 10.3s	remaining: 20.9s
540:	learn: 0.2340854	test: 0.2340601	best: 0.2340601 (540)	total: 10.7s	remaining: 20.5s
560:	learn: 0.2330611	test: 0.2331276	best: 0.2331276 (560)	total: 11s	remaining: 20.1s
580:	learn: 0.2324855	test: 0.2326731	best: 0.2326731 (580)	total: 11.4s	remaining: 19.7s
600:	learn: 0.2317202	test: 0.2319950	best: 0.2319950 (600)	total: 11.8s	remaining: 19.3s
620:	learn: 0.2311962	test: 0.2315983	best: 0.2315983 (620)	total: 12.2s	remaining: 18.9s
640:	learn: 0.2304995	test: 0.2309808	best: 0.2309808 (640)	total: 12.6s	remaining: 18.5s
660:	learn: 0.2298895	test: 0.2305016	best: 0.2305016 (660)	total: 13s	remaining: 18.1s
680:	learn: 0.2293865	test: 0.2301360	best: 0.2301360 (680)	total: 13.3s	remaining: 17.7s
700:	learn: 0.2288453	test: 0.2296964	best: 0.2296964 (700)	total: 13.7s	remaining: 17.3s
720:	learn: 0.2283784	test: 0.2293813	best: 0.2293813 (720)	total: 14.1s	remaining: 16.9s
740:	learn: 0.2279101	test: 0.2290439	best: 0.2290439 (740)	total: 14.5s	remaining: 16.5s
760:	learn: 0.2273819	test: 0.2286307	best: 0.2286307 (760)	total: 14.9s	remaining: 16.2s
780:	learn: 0.2269733	test: 0.2283053	best: 0.2283053 (780)	total: 15.3s	remaining: 15.8s
800:	learn: 0.2265513	test: 0.2280032	best: 0.2280032 (800)	total: 15.7s	remaining: 15.4s
820:	learn: 0.2260490	test: 0.2276020	best: 0.2276020 (820)	total: 16.1s	remaining: 15s
840:	learn: 0.2256222	test: 0.2272897	best: 0.2272897 (840)	total: 16.5s	remaining: 14.6s
860:	learn: 0.2252497	test: 0.2270044	best: 0.2270044 (860)	total: 16.9s	remaining: 14.2s
880:	learn: 0.2248629	test: 0.2267411	best: 0.2267411 (880)	total: 17.3s	remaining: 13.8s
900:	learn: 0.2244717	test: 0.2264942	best: 0.2264942 (900)	total: 17.7s	remaining: 13.4s
920:	learn: 0.2241472	test: 0.2262853	best: 0.2262853 (920)	total: 18.1s	remaining: 13s
940:	learn: 0.2237639	test: 0.2259845	best: 0.2259845 (940)	total: 18.5s	remaining: 12.6s
960:	learn: 0.2233114	test: 0.2256350	best: 0.2256350 (960)	total: 18.9s	remaining: 12.3s
980:	learn: 0.2229838	test: 0.2254217	best: 0.2254217 (980)	total: 19.3s	remaining: 11.9s
1000:	learn: 0.2226618	test: 0.2252000	best: 0.2252000 (1000)	total: 19.7s	remaining: 11.5s
1020:	learn: 0.2223471	test: 0.2249994	best: 0.2249994 (1020)	total: 20.1s	remaining: 11.1s
1040:	learn: 0.2220064	test: 0.2247437	best: 0.2247437 (1040)	total: 20.5s	remaining: 10.7s
1060:	learn: 0.2216114	test: 0.2244472	best: 0.2244472 (1060)	total: 20.9s	remaining: 10.3s
1080:	learn: 0.2212992	test: 0.2242591	best: 0.2242591 (1080)	total: 21.3s	remaining: 9.92s
1100:	learn: 0.2210016	test: 0.2240807	best: 0.2240807 (1100)	total: 21.7s	remaining: 9.52s
1120:	learn: 0.2206739	test: 0.2238777	best: 0.2238777 (1120)	total: 22.1s	remaining: 9.12s
1140:	learn: 0.2203091	test: 0.2235682	best: 0.2235682 (1140)	total: 22.5s	remaining: 8.73s
1160:	learn: 0.2200005	test: 0.2233654	best: 0.2233654 (1160)	total: 22.9s	remaining: 8.34s
1180:	learn: 0.2197786	test: 0.2232426	best: 0.2232426 (1180)	total: 23.3s	remaining: 7.94s
1200:	learn: 0.2195344	test: 0.2231020	best: 0.2231020 (1200)	total: 23.7s	remaining: 7.55s
1220:	learn: 0.2192926	test: 0.2229480	best: 0.2229480 (1220)	total: 24.1s	remaining: 7.16s
1240:	learn: 0.2189631	test: 0.2226880	best: 0.2226880 (1240)	total: 24.5s	remaining: 6.76s
1260:	learn: 0.2186554	test: 0.2224765	best: 0.2224765 (1260)	total: 24.9s	remaining: 6.37s
1280:	learn: 0.2183964	test: 0.2223217	best: 0.2223217 (1280)	total: 25.3s	remaining: 5.98s
1300:	learn: 0.2181545	test: 0.2222003	best: 0.2222003 (1300)	total: 25.7s	remaining: 5.59s
1320:	learn: 0.2178736	test: 0.2220646	best: 0.2220646 (1320)	total: 26.1s	remaining: 5.19s
1340:	learn: 0.2176407	test: 0.2219299	best: 0.2219299 (1340)	total: 26.5s	remaining: 4.8s
1360:	learn: 0.2174235	test: 0.2217899	best: 0.2217899 (1360)	total: 26.9s	remaining: 4.4s
1380:	learn: 0.2171914	test: 0.2216682	best: 0.2216682 (1380)	total: 27.3s	remaining: 4.01s
1400:	learn: 0.2169438	test: 0.2215185	best: 0.2215185 (1400)	total: 27.7s	remaining: 3.62s
1420:	learn: 0.2166762	test: 0.2213372	best: 0.2213372 (1420)	total: 28.1s	remaining: 3.22s
1440:	learn: 0.2164087	test: 0.2211823	best: 0.2211823 (1440)	total: 28.5s	remaining: 2.83s
1460:	learn: 0.2161484	test: 0.2210486	best: 0.2210486 (1460)	total: 28.9s	remaining: 2.43s
1480:	learn: 0.2159464	test: 0.2209554	best: 0.2209554 (1480)	total: 29.3s	remaining: 2.04s
1500:	learn: 0.2157492	test: 0.2208369	best: 0.2208369 (1500)	total: 29.7s	remaining: 1.64s
1520:	learn: 0.2154841	test: 0.2206202	best: 0.2206202 (1520)	total: 30.1s	remaining: 1.25s
1540:	learn: 0.2152551	test: 0.2204747	best: 0.2204747 (1540)	total: 30.5s	remaining: 850ms
1560:	learn: 0.2150306	test: 0.2203289	best: 0.2203289 (1560)	total: 30.9s	remaining: 455ms
1580:	learn: 0.2147996	test: 0.2201876	best: 0.2201876 (1580)	total: 31.3s	remaining: 59.3ms
1583:	learn: 0.2147586	test: 0.2201680	best: 0.2201680 (1583)	total: 31.3s	remaining: 0us
bestTest = 0.2201679563
bestIteration = 1583

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645893	test: 0.6644789	best: 0.6644789 (0)	total: 5.51ms	remaining: 5.51ms
1:	learn: 0.6387454	test: 0.6385254	best: 0.6385254 (1)	total: 10.2ms	remaining: 0us
bestTest = 0.6385253798
bestIteration = 1
0:	learn: 0.6400207	test: 0.6398211	best: 0.6398211 (0)	total: 19.5ms	remaining: 41.8s
20:	learn: 0.3348168	test: 0.3329329	best: 0.3329329 (20)	total: 422ms	remaining: 42.8s
40:	learn: 0.3030510	test: 0.3002933	best: 0.3002933 (40)	total: 835ms	remaining: 42.9s
60:	learn: 0.2899778	test: 0.2866055	best: 0.2866055 (60)	total: 1.24s	remaining: 42.3s
80:	learn: 0.2818726	test: 0.2781329	best: 0.2781329 (80)	total: 1.64s	remaining: 41.8s
100:	learn: 0.2770053	test: 0.2733906	best: 0.2733906 (100)	total: 2.03s	remaining: 41.2s
120:	learn: 0.2721738	test: 0.2684800	best: 0.2684800 (120)	total: 2.41s	remaining: 40.4s
140:	learn: 0.2672211	test: 0.2635351	best: 0.2635351 (140)	total: 2.79s	remaining: 39.8s
160:	learn: 0.2635019	test: 0.2598517	best: 0.2598517 (160)	total: 3.17s	remaining: 39.2s
180:	learn: 0.2603972	test: 0.2568492	best: 0.2568492 (180)	total: 3.55s	remaining: 38.6s
200:	learn: 0.2580962	test: 0.2546913	best: 0.2546913 (200)	total: 3.92s	remaining: 38s
220:	learn: 0.2555616	test: 0.2520822	best: 0.2520822 (220)	total: 4.32s	remaining: 37.7s
240:	learn: 0.2532270	test: 0.2497961	best: 0.2497961 (240)	total: 4.7s	remaining: 37.3s
260:	learn: 0.2513276	test: 0.2479322	best: 0.2479322 (260)	total: 5.08s	remaining: 36.7s
280:	learn: 0.2493124	test: 0.2458464	best: 0.2458464 (280)	total: 5.47s	remaining: 36.4s
300:	learn: 0.2477789	test: 0.2444381	best: 0.2444381 (300)	total: 5.86s	remaining: 36s
320:	learn: 0.2462486	test: 0.2429908	best: 0.2429908 (320)	total: 6.25s	remaining: 35.6s
340:	learn: 0.2446992	test: 0.2414133	best: 0.2414133 (340)	total: 6.64s	remaining: 35.2s
360:	learn: 0.2435220	test: 0.2403359	best: 0.2403359 (360)	total: 7.01s	remaining: 34.8s
380:	learn: 0.2424481	test: 0.2393613	best: 0.2393613 (380)	total: 7.39s	remaining: 34.3s
400:	learn: 0.2413012	test: 0.2382754	best: 0.2382754 (400)	total: 7.78s	remaining: 33.9s
420:	learn: 0.2401817	test: 0.2372406	best: 0.2372406 (420)	total: 8.15s	remaining: 33.5s
440:	learn: 0.2391712	test: 0.2362971	best: 0.2362971 (440)	total: 8.55s	remaining: 33.1s
460:	learn: 0.2383046	test: 0.2355467	best: 0.2355467 (460)	total: 8.94s	remaining: 32.7s
480:	learn: 0.2374780	test: 0.2348455	best: 0.2348455 (480)	total: 9.32s	remaining: 32.3s
500:	learn: 0.2365020	test: 0.2339509	best: 0.2339509 (500)	total: 9.71s	remaining: 31.9s
520:	learn: 0.2358082	test: 0.2333757	best: 0.2333757 (520)	total: 10.1s	remaining: 31.6s
540:	learn: 0.2351213	test: 0.2327746	best: 0.2327746 (540)	total: 10.5s	remaining: 31.1s
560:	learn: 0.2344581	test: 0.2322410	best: 0.2322410 (560)	total: 10.8s	remaining: 30.7s
580:	learn: 0.2338254	test: 0.2317092	best: 0.2317092 (580)	total: 11.2s	remaining: 30.3s
600:	learn: 0.2330353	test: 0.2309468	best: 0.2309468 (600)	total: 11.6s	remaining: 29.9s
620:	learn: 0.2324319	test: 0.2304597	best: 0.2304597 (620)	total: 12s	remaining: 29.5s
640:	learn: 0.2318575	test: 0.2299688	best: 0.2299688 (640)	total: 12.4s	remaining: 29.2s
660:	learn: 0.2311212	test: 0.2293286	best: 0.2293286 (660)	total: 12.8s	remaining: 28.8s
680:	learn: 0.2304965	test: 0.2287826	best: 0.2287826 (680)	total: 13.1s	remaining: 28.4s
700:	learn: 0.2299214	test: 0.2282794	best: 0.2282794 (700)	total: 13.5s	remaining: 28s
720:	learn: 0.2294383	test: 0.2278856	best: 0.2278856 (720)	total: 13.9s	remaining: 27.6s
740:	learn: 0.2290096	test: 0.2275484	best: 0.2275484 (740)	total: 14.3s	remaining: 27.2s
760:	learn: 0.2284930	test: 0.2271364	best: 0.2271364 (760)	total: 14.7s	remaining: 26.8s
780:	learn: 0.2279631	test: 0.2267404	best: 0.2267404 (780)	total: 15s	remaining: 26.4s
800:	learn: 0.2275270	test: 0.2263727	best: 0.2263727 (800)	total: 15.4s	remaining: 26s
820:	learn: 0.2270864	test: 0.2260486	best: 0.2260486 (820)	total: 15.8s	remaining: 25.6s
840:	learn: 0.2265755	test: 0.2256333	best: 0.2256333 (840)	total: 16.2s	remaining: 25.2s
860:	learn: 0.2262005	test: 0.2253371	best: 0.2253364 (859)	total: 16.6s	remaining: 24.8s
880:	learn: 0.2257830	test: 0.2250548	best: 0.2250548 (880)	total: 17s	remaining: 24.4s
900:	learn: 0.2253265	test: 0.2246770	best: 0.2246770 (900)	total: 17.3s	remaining: 24s
920:	learn: 0.2248741	test: 0.2243158	best: 0.2243158 (920)	total: 17.7s	remaining: 23.7s
940:	learn: 0.2245508	test: 0.2240943	best: 0.2240943 (940)	total: 18.1s	remaining: 23.3s
960:	learn: 0.2240694	test: 0.2237041	best: 0.2237041 (960)	total: 18.5s	remaining: 22.9s
980:	learn: 0.2237298	test: 0.2235224	best: 0.2235224 (980)	total: 18.9s	remaining: 22.5s
1000:	learn: 0.2233132	test: 0.2232010	best: 0.2232010 (1000)	total: 19.3s	remaining: 22.1s
1020:	learn: 0.2229037	test: 0.2228768	best: 0.2228768 (1020)	total: 19.7s	remaining: 21.7s
1040:	learn: 0.2225650	test: 0.2226377	best: 0.2226377 (1040)	total: 20s	remaining: 21.3s
1060:	learn: 0.2221864	test: 0.2223562	best: 0.2223562 (1060)	total: 20.4s	remaining: 21s
1080:	learn: 0.2217535	test: 0.2220220	best: 0.2220220 (1080)	total: 20.8s	remaining: 20.6s
1100:	learn: 0.2214892	test: 0.2218333	best: 0.2218333 (1100)	total: 21.2s	remaining: 20.2s
1120:	learn: 0.2211099	test: 0.2215863	best: 0.2215863 (1120)	total: 21.6s	remaining: 19.8s
1140:	learn: 0.2207867	test: 0.2213515	best: 0.2213515 (1140)	total: 22s	remaining: 19.4s
1160:	learn: 0.2204443	test: 0.2210965	best: 0.2210965 (1160)	total: 22.3s	remaining: 19s
1180:	learn: 0.2201188	test: 0.2208288	best: 0.2208288 (1180)	total: 22.7s	remaining: 18.7s
1200:	learn: 0.2198189	test: 0.2206067	best: 0.2206067 (1200)	total: 23.1s	remaining: 18.3s
1220:	learn: 0.2194206	test: 0.2202937	best: 0.2202937 (1220)	total: 23.5s	remaining: 17.9s
1240:	learn: 0.2191429	test: 0.2201005	best: 0.2201005 (1240)	total: 23.9s	remaining: 17.5s
1260:	learn: 0.2188901	test: 0.2199546	best: 0.2199546 (1260)	total: 24.3s	remaining: 17.1s
1280:	learn: 0.2186137	test: 0.2197904	best: 0.2197904 (1280)	total: 24.7s	remaining: 16.7s
1300:	learn: 0.2183007	test: 0.2195942	best: 0.2195942 (1300)	total: 25.1s	remaining: 16.4s
1320:	learn: 0.2180425	test: 0.2194394	best: 0.2194394 (1320)	total: 25.4s	remaining: 16s
1340:	learn: 0.2177499	test: 0.2192369	best: 0.2192369 (1340)	total: 25.8s	remaining: 15.6s
1360:	learn: 0.2174633	test: 0.2190385	best: 0.2190385 (1360)	total: 26.2s	remaining: 15.2s
1380:	learn: 0.2172136	test: 0.2189108	best: 0.2189108 (1380)	total: 26.6s	remaining: 14.8s
1400:	learn: 0.2169336	test: 0.2187354	best: 0.2187354 (1400)	total: 27s	remaining: 14.4s
1420:	learn: 0.2167175	test: 0.2186013	best: 0.2186013 (1420)	total: 27.4s	remaining: 14.1s
1440:	learn: 0.2164764	test: 0.2184817	best: 0.2184810 (1439)	total: 27.8s	remaining: 13.7s
1460:	learn: 0.2162463	test: 0.2183453	best: 0.2183453 (1460)	total: 28.2s	remaining: 13.3s
1480:	learn: 0.2160117	test: 0.2182309	best: 0.2182309 (1480)	total: 28.6s	remaining: 12.9s
1500:	learn: 0.2157745	test: 0.2180895	best: 0.2180895 (1500)	total: 28.9s	remaining: 12.5s
1520:	learn: 0.2155647	test: 0.2179699	best: 0.2179699 (1520)	total: 29.3s	remaining: 12.1s
1540:	learn: 0.2153632	test: 0.2178778	best: 0.2178778 (1540)	total: 29.7s	remaining: 11.7s
1560:	learn: 0.2151324	test: 0.2177538	best: 0.2177538 (1560)	total: 30.1s	remaining: 11.4s
1580:	learn: 0.2149206	test: 0.2176308	best: 0.2176308 (1580)	total: 30.5s	remaining: 11s
1600:	learn: 0.2146821	test: 0.2174921	best: 0.2174921 (1600)	total: 30.9s	remaining: 10.6s
1620:	learn: 0.2144141	test: 0.2172899	best: 0.2172899 (1620)	total: 31.3s	remaining: 10.2s
1640:	learn: 0.2142149	test: 0.2171580	best: 0.2171580 (1640)	total: 31.7s	remaining: 9.82s
1660:	learn: 0.2140090	test: 0.2170510	best: 0.2170510 (1660)	total: 32.1s	remaining: 9.44s
1680:	learn: 0.2137963	test: 0.2169197	best: 0.2169197 (1680)	total: 32.5s	remaining: 9.06s
1700:	learn: 0.2135909	test: 0.2167968	best: 0.2167968 (1700)	total: 32.9s	remaining: 8.67s
1720:	learn: 0.2134085	test: 0.2167311	best: 0.2167307 (1717)	total: 33.3s	remaining: 8.29s
1740:	learn: 0.2131812	test: 0.2165871	best: 0.2165871 (1740)	total: 33.7s	remaining: 7.91s
1760:	learn: 0.2129579	test: 0.2164516	best: 0.2164516 (1760)	total: 34.1s	remaining: 7.53s
1780:	learn: 0.2127494	test: 0.2163135	best: 0.2163135 (1780)	total: 34.5s	remaining: 7.14s
1800:	learn: 0.2125582	test: 0.2162250	best: 0.2162250 (1800)	total: 34.9s	remaining: 6.75s
1820:	learn: 0.2123719	test: 0.2161508	best: 0.2161508 (1820)	total: 35.3s	remaining: 6.37s
1840:	learn: 0.2121671	test: 0.2160466	best: 0.2160463 (1839)	total: 35.7s	remaining: 5.98s
1860:	learn: 0.2120081	test: 0.2159614	best: 0.2159614 (1860)	total: 36.1s	remaining: 5.6s
1880:	learn: 0.2118381	test: 0.2158780	best: 0.2158780 (1880)	total: 36.4s	remaining: 5.21s
1900:	learn: 0.2116586	test: 0.2157814	best: 0.2157814 (1900)	total: 36.8s	remaining: 4.82s
1920:	learn: 0.2115037	test: 0.2157242	best: 0.2157226 (1919)	total: 37.2s	remaining: 4.44s
1940:	learn: 0.2113052	test: 0.2156126	best: 0.2156126 (1940)	total: 37.6s	remaining: 4.05s
1960:	learn: 0.2111174	test: 0.2155610	best: 0.2155610 (1960)	total: 38s	remaining: 3.66s
1980:	learn: 0.2109233	test: 0.2154540	best: 0.2154531 (1979)	total: 38.4s	remaining: 3.27s
2000:	learn: 0.2107177	test: 0.2153104	best: 0.2153093 (1999)	total: 38.8s	remaining: 2.89s
2020:	learn: 0.2105660	test: 0.2152567	best: 0.2152567 (2020)	total: 39.2s	remaining: 2.5s
2040:	learn: 0.2104056	test: 0.2151633	best: 0.2151633 (2040)	total: 39.6s	remaining: 2.11s
2060:	learn: 0.2101910	test: 0.2150297	best: 0.2150297 (2060)	total: 40s	remaining: 1.73s
2080:	learn: 0.2099934	test: 0.2149427	best: 0.2149427 (2080)	total: 40.4s	remaining: 1.34s
2100:	learn: 0.2098199	test: 0.2148551	best: 0.2148551 (2100)	total: 40.8s	remaining: 951ms
2120:	learn: 0.2096482	test: 0.2147377	best: 0.2147377 (2120)	total: 41.2s	remaining: 563ms
2140:	learn: 0.2094684	test: 0.2146687	best: 0.2146687 (2140)	total: 41.6s	remaining: 175ms
2149:	learn: 0.2094091	test: 0.2146511	best: 0.2146511 (2149)	total: 41.7s	remaining: 0us
bestTest = 0.2146510974
bestIteration = 2149

Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\model.pkl
	0.9502	 = Validation score   (roc_auc)
	179.69s	 = Training   runtime
	0.72s	 = Validation runtime
	93449.0	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1615.88s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.4 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.34s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	0.9502	 = Validation score   (roc_auc)
	0.07s	 = Training   runtime
	0.06s	 = Validation runtime
	92526.6	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
AutoGluon training complete, total runtime = 184.3s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 92526.6 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models2\CAT\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models2\CAT")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       3.35 GB / 15.06 GB (22.3%)
Disk Space Avail:   705.67 GB / 930.47 GB (75.8%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models2\RF"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

CAT completed.
Validation ROC-AUC: 0.950199

================================================================================
TRAINING: RF
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models2\RF
================================================================================

	Available Memory:                    3509.96 MB
	Train Data (Original)  Memory Usage: 136.13 MB (3.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.8s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (1.2% of available memory)
Data preprocessing and feature engineering runtime = 0.88s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\learner.pkl
User-specified model hyperparameters to be fit:
{
	'RF': [{'criterion': 'entropy'}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\utils\data\y.pkl
Model configs that will be trained (in order):
	RandomForest_BAG_L1: 	{'criterion': 'entropy', 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.rf.rf_model.RFModel'>, 'priority': 80}, 'ag_args_fit': {'num_gpus': 1}, 'ag_args_ensemble': {'use_child_oof': True}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: RandomForest_BAG_L1 ... Training model for up to 1799.12s of the 1799.12s of remaining time.
	Fitting RandomForest_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\models\RandomForest_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\models\RandomForest_BAG_L1\utils\model_template.pkl
	Warning: Not enough memory to safely train model. Estimated to require 2.688 GB out of 3.291 GB available memory (81.669%)... (50.000% of avail memory is the max safe size)
	To force training the model, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.68 to avoid the error)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Not enough memory to train RandomForest_BAG_L1... Skipping this model.
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\models\RandomForest_BAG_L1\utils\model_template.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl
No base models to train on, skipping auxiliary stack level 2...
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl
Warning: AutoGluon did not successfully train any models
Saving c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl
AutoGluon training complete, total runtime = 1.17s ... Best model: None
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl

RuntimeError: No models were trained successfully during fit(). Inspect the log output or increase verbosity to determine why no models were fit. Alternatively, set `raise_on_no_models_fitted` to False during the fit call.

In [29]:
import os
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models2"

all_leaderboards = []

# ============================================================
# SCAN & LOAD ALL TRAINED PREDICTORS
# ============================================================

if os.path.exists(MODEL_DIR):
    # Check both subdirectories and root directory for saved predictors
    folder_candidates = [MODEL_DIR] + [
        os.path.join(MODEL_DIR, d) 
        for d in os.listdir(MODEL_DIR) 
        if os.path.isdir(os.path.join(MODEL_DIR, d))
    ]

    for folder_path in folder_candidates:
        # Check if directory contains a valid predictor file
        if os.path.exists(os.path.join(folder_path, "predictor.pkl")):
            try:
                folder_name = os.path.basename(folder_path)
                print(f"Loading predictor from: {folder_path}")
                
                # Load predictor from disk
                predictor = TabularPredictor.load(folder_path)
                
                # Fetch leaderboard
                lb = predictor.leaderboard(silent=True)
                lb.insert(0, "folder_name", folder_name)
                
                all_leaderboards.append(lb)
            except Exception as e:
                print(f"Failed to load predictor from {folder_path}: {e}")

# ============================================================
# MERGE AND PRESENT COMBINED LEADERBOARD
# ============================================================

if all_leaderboards:
    combined_leaderboard = pd.concat(all_leaderboards, ignore_index=True)

    # Sort all trained models by validation ROC-AUC score descending
    combined_leaderboard = combined_leaderboard.sort_values(
        by="score_val", ascending=False
    ).reset_index(drop=True)

    print("\n" + "=" * 80)
    print("COMBINED LEADERBOARD OF ALL LOADED MODELS")
    print("=" * 80)

    display(combined_leaderboard)
else:
    print(f"No valid AutoGluon predictors (`predictor.pkl`) found under '{MODEL_DIR}'.")

Loading predictor from: ./ag_models2\CAT

Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl

Loading predictor from: ./ag_models2\GBM
Loading predictor from: ./ag_models2\RF

Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl

Loading predictor from: ./ag_models2\XGB

================================================================================
COMBINED LEADERBOARD OF ALL LOADED MODELS
================================================================================

,folder_name,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGB,WeightedEnsemble_L2,0.958240,roc_auc,4.397609,601.833442,0.053591,0.057095,2.0,1.0,2.0
1,XGB,XGBoost_BAG_L1,0.958240,roc_auc,4.344018,601.776347,4.344018,601.776347,1.0,1.0,1.0
2,GBM,WeightedEnsemble_L2,0.953617,roc_auc,18.501622,255.991845,0.060542,2.829900,2.0,1.0,3.0
3,GBM,LightGBMLarge_BAG_L1,0.952897,roc_auc,13.476475,172.914947,13.476475,172.914947,1.0,1.0,2.0
4,GBM,LightGBM_BAG_L1,0.951028,roc_auc,4.964605,80.246999,4.964605,80.246999,1.0,1.0,1.0
5,CAT,WeightedEnsemble_L2,0.950199,roc_auc,0.780571,179.753519,0.057653,0.067708,2.0,1.0,2.0
6,CAT,CatBoost_BAG_L1,0.950199,roc_auc,0.722918,179.685812,0.722918,179.685812,1.0,1.0,1.0