In [1]:
!pip uninstall torch

WARNING: Skipping torch as it is not installed.

In [3]:
# !pip freeze > req.txt
!pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu129

^C

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://download.pytorch.org/whl/cu129
Collecting torch==2.8.0
  Downloading https://download-r2.pytorch.org/whl/cu129/torch-2.8.0%2Bcu129-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting torchvision==0.23.0
  Downloading https://download-r2.pytorch.org/whl/cu129/torchvision-0.23.0%2Bcu129-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting torchaudio==2.8.0
  Downloading https://download-r2.pytorch.org/whl/cu129/torchaudio-2.8.0%2Bcu129-cp313-cp313-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: filelock in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (3.32.2)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (4.16.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (1.14.0)
Requirement already satisfied: networkx in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (3.1.6)
Requirement already satisfied: fsspec in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (2025.3.0)
Requirement already satisfied: setuptools in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torch==2.8.0) (81.0.0)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torchvision==0.23.0) (2.4.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from torchvision==0.23.0) (12.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from sympy>=1.13.3->torch==2.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from jinja2->torch==2.8.0) (3.0.3)
Downloading https://download-r2.pytorch.org/whl/cu129/torch-2.8.0%2Bcu129-cp313-cp313-win_amd64.whl (3571.8 MB)
   ---------------------------------------- 0.0/3.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/3.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/3.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/3.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/3.6 GB 1.2 MB/s eta 0:49:15
   ---------------------------------------- 0.0/3.6 GB 1.7 MB/s eta 0:34:36
   ---------------------------------------- 0.0/3.6 GB 2.7 MB/s eta 0:22:22
   ---------------------------------------- 0.0/3.6 GB 3.9 MB/s eta 0:15:17
   ---------------------------------------- 0.0/3.6 GB 6.0 MB/s eta 0:09:51
   ---------------------------------------- 0.0/3.6 GB 9.7 MB/s eta 0:06:08
   ---------------------------------------- 0.0/3.6 GB 11.7 MB/s eta 0:05:04
   ---------------------------------------- 0.0/3.6 GB 11.7 MB/s eta 0:05:04
   ---------------------------------------- 0.0/3.6 GB 12.1 MB/s eta 0:04:54
   ---------------------------------------- 0.0/3.6 GB 12.0 MB/s eta 0:04:57
   ---------------------------------------- 0.0/3.6 GB 12.0 MB/s eta 0:04:56
   ---------------------------------------- 0.0/3.6 GB 11.8 MB/s eta 0:05:00
   ---------------------------------------- 0.0/3.6 GB 11.4 MB/s eta 0:05:12
   ---------------------------------------- 0.0/3.6 GB 11.2 MB/s eta 0:05:16
   ---------------------------------------- 0.0/3.6 GB 10.8 MB/s eta 0:05:28
   ---------------------------------------- 0.0/3.6 GB 10.9 MB/s eta 0:05:26
   ---------------------------------------- 0.0/3.6 GB 10.6 MB/s eta 0:05:33
   ---------------------------------------- 0.0/3.6 GB 10.6 MB/s eta 0:05:34
   ---------------------------------------- 0.0/3.6 GB 10.6 MB/s eta 0:05:34
   ---------------------------------------- 0.0/3.6 GB 10.6 MB/s eta 0:05:32
    --------------------------------------- 0.0/3.6 GB 10.5 MB/s eta 0:05:38
    --------------------------------------- 0.0/3.6 GB 10.3 MB/s eta 0:05:44
    --------------------------------------- 0.0/3.6 GB 10.2 MB/s eta 0:05:47
    --------------------------------------- 0.0/3.6 GB 9.9 MB/s eta 0:05:58
    --------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:06:02
    --------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:06:02
    --------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:05:59
    --------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:06:00
    --------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:06:01
    --------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:06
    --------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:05
    --------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:05
    --------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:04
    --------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:06:01
    --------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:04
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:08
    --------------------------------------- 0.1/3.6 GB 9.4 MB/s eta 0:06:11
    --------------------------------------- 0.1/3.6 GB 9.4 MB/s eta 0:06:13
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:10
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:10
    --------------------------------------- 0.1/3.6 GB 9.4 MB/s eta 0:06:12
    --------------------------------------- 0.1/3.6 GB 9.4 MB/s eta 0:06:13
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:08
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:06
    --------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:08
   - -------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:05
   - -------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:04
   - -------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:09
   - -------------------------------------- 0.1/3.6 GB 9.5 MB/s eta 0:06:06
   - -------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:03
   - -------------------------------------- 0.1/3.6 GB 9.6 MB/s eta 0:06:01
   - -------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:05:58
   - -------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:05:55
   - -------------------------------------- 0.1/3.6 GB 9.7 MB/s eta 0:05:56
   - -------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:05:54
   - -------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:05:53
   - -------------------------------------- 0.1/3.6 GB 9.8 MB/s eta 0:05:52
   - -------------------------------------- 0.1/3.6 GB 10.1 MB/s eta 0:05:43
   - -------------------------------------- 0.1/3.6 GB 10.2 MB/s eta 0:05:38
   - -------------------------------------- 0.1/3.6 GB 10.3 MB/s eta 0:05:37
   - -------------------------------------- 0.1/3.6 GB 10.2 MB/s eta 0:05:38
   - -------------------------------------- 0.1/3.6 GB 10.1 MB/s eta 0:05:40
   - -------------------------------------- 0.1/3.6 GB 10.1 MB/s eta 0:05:41
   - -------------------------------------- 0.1/3.6 GB 10.1 MB/s eta 0:05:43
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:44
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:45
   - -------------------------------------- 0.1/3.6 GB 9.9 MB/s eta 0:05:46
   - -------------------------------------- 0.1/3.6 GB 9.9 MB/s eta 0:05:46
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:45
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:43
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:44
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:44
   - -------------------------------------- 0.1/3.6 GB 10.0 MB/s eta 0:05:44
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:44
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:45
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:46
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:46
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:45
   - -------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:49
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:43
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:43
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:42
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:40
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:41
   - -------------------------------------- 0.2/3.6 GB 10.0 MB/s eta 0:05:42
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:43
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:44
   - -------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:44
   -- ------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:45
   -- ------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:44
   -- ------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:44
   -- ------------------------------------- 0.2/3.6 GB 9.9 MB/s eta 0:05:44
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:45
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:45
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:46
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:46
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:47
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:48
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:47
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:46
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:45
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:46
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:47
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:48
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:47
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:48
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:50
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:50
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:51
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:53
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:53
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:53
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:54
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:53
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:54
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:53
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:52
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:45
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:41
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:40
   -- ------------------------------------- 0.2/3.6 GB 9.8 MB/s eta 0:05:42
   -- ------------------------------------- 0.2/3.6 GB 9.7 MB/s eta 0:05:44
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:47
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:48
   -- ------------------------------------- 0.2/3.6 GB 9.6 MB/s eta 0:05:49
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:49
   -- ------------------------------------- 0.2/3.6 GB 9.5 MB/s eta 0:05:49
   -- ------------------------------------- 0.3/3.6 GB 9.6 MB/s eta 0:05:47
   -- ------------------------------------- 0.3/3.6 GB 9.6 MB/s eta 0:05:48
   -- ------------------------------------- 0.3/3.6 GB 9.6 MB/s eta 0:05:46
   -- ------------------------------------- 0.3/3.6 GB 9.6 MB/s eta 0:05:46
   -- ------------------------------------- 0.3/3.6 GB 9.5 MB/s eta 0:05:48
   -- ------------------------------------- 0.3/3.6 GB 9.5 MB/s eta 0:05:48
   -- ------------------------------------- 0.3/3.6 GB 9.5 MB/s eta 0:05:48
   -- ------------------------------------- 0.3/3.6 GB 9.6 MB/s eta 0:05:46
   -- ------------------------------------- 0.3/3.6 GB 9.7 MB/s eta 0:05:41
   -- ------------------------------------- 0.3/3.6 GB 9.7 MB/s eta 0:05:41
   --- ------------------------------------ 0.3/3.6 GB 9.7 MB/s eta 0:05:42
   --- ------------------------------------ 0.3/3.6 GB 9.6 MB/s eta 0:05:43
   --- ------------------------------------ 0.3/3.6 GB 9.6 MB/s eta 0:05:45
   --- ------------------------------------ 0.3/3.6 GB 9.5 MB/s eta 0:05:46
   --- ------------------------------------ 0.3/3.6 GB 9.6 MB/s eta 0:05:43
   --- ------------------------------------ 0.3/3.6 GB 9.6 MB/s eta 0:05:41
   --- ------------------------------------ 0.3/3.6 GB 9.6 MB/s eta 0:05:41
   --- ------------------------------------ 0.3/3.6 GB 9.7 MB/s eta 0:05:39
   --- ------------------------------------ 0.3/3.6 GB 9.7 MB/s eta 0:05:37
   --- ------------------------------------ 0.3/3.6 GB 9.8 MB/s eta 0:05:35
   --- ------------------------------------ 0.3/3.6 GB 9.8 MB/s eta 0:05:35
   --- ------------------------------------ 0.3/3.6 GB 9.8 MB/s eta 0:05:34
   --- ------------------------------------ 0.3/3.6 GB 9.8 MB/s eta 0:05:33
   --- ------------------------------------ 0.3/3.6 GB 9.8 MB/s eta 0:05:33
   --- ------------------------------------ 0.3/3.6 GB 9.9 MB/s eta 0:05:29
   --- ------------------------------------ 0.3/3.6 GB 10.0 MB/s eta 0:05:27
   --- ------------------------------------ 0.3/3.6 GB 10.0 MB/s eta 0:05:25
   --- ------------------------------------ 0.3/3.6 GB 10.1 MB/s eta 0:05:24
   --- ------------------------------------ 0.3/3.6 GB 10.1 MB/s eta 0:05:23
   --- ------------------------------------ 0.3/3.6 GB 10.2 MB/s eta 0:05:21
   --- ------------------------------------ 0.3/3.6 GB 10.2 MB/s eta 0:05:20
   --- ------------------------------------ 0.3/3.6 GB 10.2 MB/s eta 0:05:19
   --- ------------------------------------ 0.3/3.6 GB 10.2 MB/s eta 0:05:19
   --- ------------------------------------ 0.3/3.6 GB 10.2 MB/s eta 0:05:18
   --- ------------------------------------ 0.3/3.6 GB 10.3 MB/s eta 0:05:15
   --- ------------------------------------ 0.3/3.6 GB 10.3 MB/s eta 0:05:14
   --- ------------------------------------ 0.3/3.6 GB 10.3 MB/s eta 0:05:13
   --- ------------------------------------ 0.3/3.6 GB 10.4 MB/s eta 0:05:11
   --- ------------------------------------ 0.3/3.6 GB 10.4 MB/s eta 0:05:11
   --- ------------------------------------ 0.3/3.6 GB 10.4 MB/s eta 0:05:11
   --- ------------------------------------ 0.3/3.6 GB 10.4 MB/s eta 0:05:09
   --- ------------------------------------ 0.3/3.6 GB 10.4 MB/s eta 0:05:10
   --- ------------------------------------ 0.4/3.6 GB 10.4 MB/s eta 0:05:11
   --- ------------------------------------ 0.4/3.6 GB 10.4 MB/s eta 0:05:11
   --- ------------------------------------ 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:08
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:08
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:07
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:07
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:07
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:09
   ---- ----------------------------------- 0.4/3.6 GB 10.3 MB/s eta 0:05:10
   ---- ----------------------------------- 0.4/3.6 GB 10.3 MB/s eta 0:05:10
   ---- ----------------------------------- 0.4/3.6 GB 10.3 MB/s eta 0:05:08
   ---- ----------------------------------- 0.4/3.6 GB 10.4 MB/s eta 0:05:06
   ---- ----------------------------------- 0.4/3.6 GB 10.5 MB/s eta 0:05:05
   ---- ----------------------------------- 0.4/3.6 GB 10.5 MB/s eta 0:05:02
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:05:01
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:05:01
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:05:01
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:05:00
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:04:58
   ---- ----------------------------------- 0.4/3.6 GB 10.6 MB/s eta 0:04:58
   ---- ----------------------------------- 0.4/3.6 GB 10.7 MB/s eta 0:04:56
   ---- ----------------------------------- 0.4/3.6 GB 10.7 MB/s eta 0:04:55
   ---- ----------------------------------- 0.4/3.6 GB 10.7 MB/s eta 0:04:54
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:52
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:53
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:53
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:52
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:52
   ---- ----------------------------------- 0.4/3.6 GB 10.8 MB/s eta 0:04:51
   ---- ----------------------------------- 0.4/3.6 GB 10.9 MB/s eta 0:04:49
   ---- ----------------------------------- 0.4/3.6 GB 10.9 MB/s eta 0:04:47
   ---- ----------------------------------- 0.4/3.6 GB 10.9 MB/s eta 0:04:46
   ---- ----------------------------------- 0.4/3.6 GB 11.0 MB/s eta 0:04:46
   ---- ----------------------------------- 0.4/3.6 GB 11.0 MB/s eta 0:04:44
   ----- ---------------------------------- 0.4/3.6 GB 11.1 MB/s eta 0:04:43
   ----- ---------------------------------- 0.5/3.6 GB 11.1 MB/s eta 0:04:42
   ----- ---------------------------------- 0.5/3.6 GB 11.1 MB/s eta 0:04:41
   ----- ---------------------------------- 0.5/3.6 GB 11.2 MB/s eta 0:04:38
   ----- ---------------------------------- 0.5/3.6 GB 11.3 MB/s eta 0:04:37
   ----- ---------------------------------- 0.5/3.6 GB 11.3 MB/s eta 0:04:37
   ----- ---------------------------------- 0.5/3.6 GB 11.2 MB/s eta 0:04:37
   ----- ---------------------------------- 0.5/3.6 GB 11.3 MB/s eta 0:04:35
   ----- ---------------------------------- 0.5/3.6 GB 11.4 MB/s eta 0:04:33
   ----- ---------------------------------- 0.5/3.6 GB 11.4 MB/s eta 0:04:32
   ----- ---------------------------------- 0.5/3.6 GB 11.5 MB/s eta 0:04:30
   ----- ---------------------------------- 0.5/3.6 GB 11.6 MB/s eta 0:04:26
   ----- ---------------------------------- 0.5/3.6 GB 11.7 MB/s eta 0:04:25
   ----- ---------------------------------- 0.5/3.6 GB 11.8 MB/s eta 0:04:23
   ----- ---------------------------------- 0.5/3.6 GB 11.8 MB/s eta 0:04:22
   ----- ---------------------------------- 0.5/3.6 GB 11.8 MB/s eta 0:04:21
   ----- ---------------------------------- 0.5/3.6 GB 11.9 MB/s eta 0:04:21
   ----- ---------------------------------- 0.5/3.6 GB 11.8 MB/s eta 0:04:21
   ----- ---------------------------------- 0.5/3.6 GB 11.8 MB/s eta 0:04:23
   ----- ---------------------------------- 0.5/3.6 GB 11.7 MB/s eta 0:04:24

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.6.1 requires torch<2.14,>=2.10, but you have torch 2.8.0+cu129 which is incompatible.
autogluon-timeseries 1.6.1 requires torch<2.14,>=2.10, but you have torch 2.8.0+cu129 which is incompatible.

In [1]:
import pandas as pd
df_train=pd.read_csv('data/train.csv')
df_test=pd.read_csv('data/test.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [2]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [3]:
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [4]:
# predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc').fit(
#     train_data=df_train,
#     ag_args_fit={"num_gpus": 2},
#     time_limit=3600*9,
#     presets='best_quality',
#     verbosity=3,
#     num_stack_levels=0
# )

In [5]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [6]:
models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

In [7]:
predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc', path='ag_models5').fit(
    train_data=df_train_merged,
    ag_args_fit={"num_gpus": 1},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=0,
    hyperparameters=models,
)

Warning: path already exists! This predictor may overwrite an existing predictor! path="ag_models5"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.8.0+cu129
CUDA Version:       12.9
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.85 GB / 15.06 GB (32.2%)
Disk Space Avail:   717.41 GB / 930.47 GB (77.1%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models5\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\predictor.pkl
Beginning AutoGluon training ... Time limit = 32400s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models5"
Train Data Rows:    540445
Train Data Columns: 14
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5021.39 MB
	Train Data (Original)  Memory Usage: 135.82 MB (2.7% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.0s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			14 features in original data used to generate 14 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	0.9s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 43.81 MB (0.9% of available memory)
Data preprocessing and feature engineering runtime = 1.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models5\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
	'XGB': [{}],
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models5\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 32398.99s of the 32398.98s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBM_BAG_L1\utils\model_template.pkl
Will use sequential fold fitting strategy because import of ray failed. Reason: ray is required to train folds in parallel for TabularPredictor or HPO for MultiModalPredictor. A quick tip is to install via `pip install "ray>=2.43.0,<2.57.0"`
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281445
[100]	valid_set's binary_logloss: 0.260036
[150]	valid_set's binary_logloss: 0.25199
[200]	valid_set's binary_logloss: 0.247187
[250]	valid_set's binary_logloss: 0.243627
[300]	valid_set's binary_logloss: 0.240783
[350]	valid_set's binary_logloss: 0.23862
[400]	valid_set's binary_logloss: 0.236582
[450]	valid_set's binary_logloss: 0.234896
[500]	valid_set's binary_logloss: 0.233701
[550]	valid_set's binary_logloss: 0.232697
[600]	valid_set's binary_logloss: 0.231964
[650]	valid_set's binary_logloss: 0.231146
[700]	valid_set's binary_logloss: 0.230417
[750]	valid_set's binary_logloss: 0.22974
[800]	valid_set's binary_logloss: 0.229188
[850]	valid_set's binary_logloss: 0.228568
[900]	valid_set's binary_logloss: 0.228074
[950]	valid_set's binary_logloss: 0.227555
[1000]	valid_set's binary_logloss: 0.227149
[1050]	valid_set's binary_logloss: 0.226735
[1100]	valid_set's binary_logloss: 0.226487
[1150]	valid_set's binary_logloss: 0.226146
[1200]	valid_set's binary_logloss: 0.225909
[1250]	valid_set's binary_logloss: 0.225707
[1300]	valid_set's binary_logloss: 0.225554
[1350]	valid_set's binary_logloss: 0.225443
[1400]	valid_set's binary_logloss: 0.225253
[1450]	valid_set's binary_logloss: 0.225081
[1500]	valid_set's binary_logloss: 0.224978
[1550]	valid_set's binary_logloss: 0.22483
[1600]	valid_set's binary_logloss: 0.22477
[1650]	valid_set's binary_logloss: 0.224682
[1700]	valid_set's binary_logloss: 0.224616
[1750]	valid_set's binary_logloss: 0.224502
[1800]	valid_set's binary_logloss: 0.224477
[1850]	valid_set's binary_logloss: 0.224346
[1900]	valid_set's binary_logloss: 0.224333
[1950]	valid_set's binary_logloss: 0.224322
[2000]	valid_set's binary_logloss: 0.224394
[2050]	valid_set's binary_logloss: 0.224387
[2100]	valid_set's binary_logloss: 0.22446
[2150]	valid_set's binary_logloss: 0.224512
[2200]	valid_set's binary_logloss: 0.224612
[2250]	valid_set's binary_logloss: 0.224649
[2300]	valid_set's binary_logloss: 0.224662
[2350]	valid_set's binary_logloss: 0.224703
[2400]	valid_set's binary_logloss: 0.224775
[2450]	valid_set's binary_logloss: 0.224825
[2500]	valid_set's binary_logloss: 0.224891
[2550]	valid_set's binary_logloss: 0.22494

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283034
[100]	valid_set's binary_logloss: 0.261641
[150]	valid_set's binary_logloss: 0.25394
[200]	valid_set's binary_logloss: 0.248926
[250]	valid_set's binary_logloss: 0.245444
[300]	valid_set's binary_logloss: 0.242644
[350]	valid_set's binary_logloss: 0.240329
[400]	valid_set's binary_logloss: 0.238109
[450]	valid_set's binary_logloss: 0.236788
[500]	valid_set's binary_logloss: 0.23558
[550]	valid_set's binary_logloss: 0.234712
[600]	valid_set's binary_logloss: 0.233943
[650]	valid_set's binary_logloss: 0.233117
[700]	valid_set's binary_logloss: 0.232533
[750]	valid_set's binary_logloss: 0.231818
[800]	valid_set's binary_logloss: 0.231282
[850]	valid_set's binary_logloss: 0.230866
[900]	valid_set's binary_logloss: 0.230417
[950]	valid_set's binary_logloss: 0.230038
[1000]	valid_set's binary_logloss: 0.2298
[1050]	valid_set's binary_logloss: 0.229532
[1100]	valid_set's binary_logloss: 0.229189
[1150]	valid_set's binary_logloss: 0.228974
[1200]	valid_set's binary_logloss: 0.228749
[1250]	valid_set's binary_logloss: 0.228551
[1300]	valid_set's binary_logloss: 0.228447
[1350]	valid_set's binary_logloss: 0.228242
[1400]	valid_set's binary_logloss: 0.22803
[1450]	valid_set's binary_logloss: 0.227882
[1500]	valid_set's binary_logloss: 0.227818
[1550]	valid_set's binary_logloss: 0.227738
[1600]	valid_set's binary_logloss: 0.227672
[1650]	valid_set's binary_logloss: 0.227508
[1700]	valid_set's binary_logloss: 0.22747
[1750]	valid_set's binary_logloss: 0.227384
[1800]	valid_set's binary_logloss: 0.227391
[1850]	valid_set's binary_logloss: 0.227296
[1900]	valid_set's binary_logloss: 0.227197
[1950]	valid_set's binary_logloss: 0.22715
[2000]	valid_set's binary_logloss: 0.227122
[2050]	valid_set's binary_logloss: 0.227079
[2100]	valid_set's binary_logloss: 0.22703
[2150]	valid_set's binary_logloss: 0.226968
[2200]	valid_set's binary_logloss: 0.226943
[2250]	valid_set's binary_logloss: 0.226943
[2300]	valid_set's binary_logloss: 0.226978
[2350]	valid_set's binary_logloss: 0.226999
[2400]	valid_set's binary_logloss: 0.227064
[2450]	valid_set's binary_logloss: 0.227092
[2500]	valid_set's binary_logloss: 0.227155
[2550]	valid_set's binary_logloss: 0.227231
[2600]	valid_set's binary_logloss: 0.227211
[2650]	valid_set's binary_logloss: 0.227195
[2700]	valid_set's binary_logloss: 0.227241
[2750]	valid_set's binary_logloss: 0.227211
[2800]	valid_set's binary_logloss: 0.227256
[2850]	valid_set's binary_logloss: 0.227345
[2900]	valid_set's binary_logloss: 0.227369

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284233
[100]	valid_set's binary_logloss: 0.263106
[150]	valid_set's binary_logloss: 0.255162
[200]	valid_set's binary_logloss: 0.249785
[250]	valid_set's binary_logloss: 0.246171
[300]	valid_set's binary_logloss: 0.243716
[350]	valid_set's binary_logloss: 0.241568
[400]	valid_set's binary_logloss: 0.239231
[450]	valid_set's binary_logloss: 0.237637
[500]	valid_set's binary_logloss: 0.236701
[550]	valid_set's binary_logloss: 0.235853
[600]	valid_set's binary_logloss: 0.235213
[650]	valid_set's binary_logloss: 0.234525
[700]	valid_set's binary_logloss: 0.233696
[750]	valid_set's binary_logloss: 0.233122
[800]	valid_set's binary_logloss: 0.232638
[850]	valid_set's binary_logloss: 0.232194
[900]	valid_set's binary_logloss: 0.231854
[950]	valid_set's binary_logloss: 0.231392
[1000]	valid_set's binary_logloss: 0.231064
[1050]	valid_set's binary_logloss: 0.230707
[1100]	valid_set's binary_logloss: 0.230511
[1150]	valid_set's binary_logloss: 0.230258
[1200]	valid_set's binary_logloss: 0.230025
[1250]	valid_set's binary_logloss: 0.229946
[1300]	valid_set's binary_logloss: 0.229712
[1350]	valid_set's binary_logloss: 0.229568
[1400]	valid_set's binary_logloss: 0.229532
[1450]	valid_set's binary_logloss: 0.229415
[1500]	valid_set's binary_logloss: 0.229346
[1550]	valid_set's binary_logloss: 0.229351
[1600]	valid_set's binary_logloss: 0.229284
[1650]	valid_set's binary_logloss: 0.229221
[1700]	valid_set's binary_logloss: 0.229179
[1750]	valid_set's binary_logloss: 0.229102
[1800]	valid_set's binary_logloss: 0.229084
[1850]	valid_set's binary_logloss: 0.229098
[1900]	valid_set's binary_logloss: 0.229079
[1950]	valid_set's binary_logloss: 0.229055
[2000]	valid_set's binary_logloss: 0.229097
[2050]	valid_set's binary_logloss: 0.2291
[2100]	valid_set's binary_logloss: 0.229126
[2150]	valid_set's binary_logloss: 0.229259
[2200]	valid_set's binary_logloss: 0.229332
[2250]	valid_set's binary_logloss: 0.229397
[2300]	valid_set's binary_logloss: 0.229434
[2350]	valid_set's binary_logloss: 0.229457
[2400]	valid_set's binary_logloss: 0.229527
[2450]	valid_set's binary_logloss: 0.229653
[2500]	valid_set's binary_logloss: 0.229769

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281039
[100]	valid_set's binary_logloss: 0.259556
[150]	valid_set's binary_logloss: 0.25177
[200]	valid_set's binary_logloss: 0.246534
[250]	valid_set's binary_logloss: 0.243425
[300]	valid_set's binary_logloss: 0.240826
[350]	valid_set's binary_logloss: 0.238307
[400]	valid_set's binary_logloss: 0.236305
[450]	valid_set's binary_logloss: 0.234873
[500]	valid_set's binary_logloss: 0.233571
[550]	valid_set's binary_logloss: 0.232608
[600]	valid_set's binary_logloss: 0.23171
[650]	valid_set's binary_logloss: 0.231068
[700]	valid_set's binary_logloss: 0.23039
[750]	valid_set's binary_logloss: 0.229993
[800]	valid_set's binary_logloss: 0.229392
[850]	valid_set's binary_logloss: 0.228903
[900]	valid_set's binary_logloss: 0.228552
[950]	valid_set's binary_logloss: 0.228256
[1000]	valid_set's binary_logloss: 0.227898
[1050]	valid_set's binary_logloss: 0.227445
[1100]	valid_set's binary_logloss: 0.227093
[1150]	valid_set's binary_logloss: 0.226727
[1200]	valid_set's binary_logloss: 0.226528
[1250]	valid_set's binary_logloss: 0.226295
[1300]	valid_set's binary_logloss: 0.226131
[1350]	valid_set's binary_logloss: 0.225936
[1400]	valid_set's binary_logloss: 0.225817
[1450]	valid_set's binary_logloss: 0.225722
[1500]	valid_set's binary_logloss: 0.225548
[1550]	valid_set's binary_logloss: 0.225398
[1600]	valid_set's binary_logloss: 0.225353
[1650]	valid_set's binary_logloss: 0.225349
[1700]	valid_set's binary_logloss: 0.225291
[1750]	valid_set's binary_logloss: 0.225312
[1800]	valid_set's binary_logloss: 0.225308
[1850]	valid_set's binary_logloss: 0.225316
[1900]	valid_set's binary_logloss: 0.22526
[1950]	valid_set's binary_logloss: 0.225287
[2000]	valid_set's binary_logloss: 0.225315
[2050]	valid_set's binary_logloss: 0.225363
[2100]	valid_set's binary_logloss: 0.22542
[2150]	valid_set's binary_logloss: 0.225463
[2200]	valid_set's binary_logloss: 0.225541
[2250]	valid_set's binary_logloss: 0.22562
[2300]	valid_set's binary_logloss: 0.225657
[2350]	valid_set's binary_logloss: 0.225729
[2400]	valid_set's binary_logloss: 0.225798
[2450]	valid_set's binary_logloss: 0.225872
[2500]	valid_set's binary_logloss: 0.225954

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282259
[100]	valid_set's binary_logloss: 0.260393
[150]	valid_set's binary_logloss: 0.252154
[200]	valid_set's binary_logloss: 0.24726
[250]	valid_set's binary_logloss: 0.243428
[300]	valid_set's binary_logloss: 0.240235
[350]	valid_set's binary_logloss: 0.23805
[400]	valid_set's binary_logloss: 0.23643
[450]	valid_set's binary_logloss: 0.234675
[500]	valid_set's binary_logloss: 0.233598
[550]	valid_set's binary_logloss: 0.232503
[600]	valid_set's binary_logloss: 0.231608
[650]	valid_set's binary_logloss: 0.230801
[700]	valid_set's binary_logloss: 0.229955
[750]	valid_set's binary_logloss: 0.229237
[800]	valid_set's binary_logloss: 0.228719
[850]	valid_set's binary_logloss: 0.228115
[900]	valid_set's binary_logloss: 0.227697
[950]	valid_set's binary_logloss: 0.227309
[1000]	valid_set's binary_logloss: 0.226974
[1050]	valid_set's binary_logloss: 0.226609
[1100]	valid_set's binary_logloss: 0.226343
[1150]	valid_set's binary_logloss: 0.226106
[1200]	valid_set's binary_logloss: 0.225863
[1250]	valid_set's binary_logloss: 0.22561
[1300]	valid_set's binary_logloss: 0.22545
[1350]	valid_set's binary_logloss: 0.225353
[1400]	valid_set's binary_logloss: 0.225162
[1450]	valid_set's binary_logloss: 0.224977
[1500]	valid_set's binary_logloss: 0.224807
[1550]	valid_set's binary_logloss: 0.224715
[1600]	valid_set's binary_logloss: 0.224542
[1650]	valid_set's binary_logloss: 0.224388
[1700]	valid_set's binary_logloss: 0.224392
[1750]	valid_set's binary_logloss: 0.224373
[1800]	valid_set's binary_logloss: 0.224368
[1850]	valid_set's binary_logloss: 0.224358
[1900]	valid_set's binary_logloss: 0.224356
[1950]	valid_set's binary_logloss: 0.224354
[2000]	valid_set's binary_logloss: 0.224395
[2050]	valid_set's binary_logloss: 0.224416
[2100]	valid_set's binary_logloss: 0.224452
[2150]	valid_set's binary_logloss: 0.22447
[2200]	valid_set's binary_logloss: 0.224521
[2250]	valid_set's binary_logloss: 0.224512
[2300]	valid_set's binary_logloss: 0.224496
[2350]	valid_set's binary_logloss: 0.224571

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281744
[100]	valid_set's binary_logloss: 0.259387
[150]	valid_set's binary_logloss: 0.251677
[200]	valid_set's binary_logloss: 0.247061
[250]	valid_set's binary_logloss: 0.243246
[300]	valid_set's binary_logloss: 0.240711
[350]	valid_set's binary_logloss: 0.238346
[400]	valid_set's binary_logloss: 0.236547
[450]	valid_set's binary_logloss: 0.234803
[500]	valid_set's binary_logloss: 0.233715
[550]	valid_set's binary_logloss: 0.232658
[600]	valid_set's binary_logloss: 0.23165
[650]	valid_set's binary_logloss: 0.230861
[700]	valid_set's binary_logloss: 0.230226
[750]	valid_set's binary_logloss: 0.22972
[800]	valid_set's binary_logloss: 0.229181
[850]	valid_set's binary_logloss: 0.228636
[900]	valid_set's binary_logloss: 0.228302
[950]	valid_set's binary_logloss: 0.227761
[1000]	valid_set's binary_logloss: 0.227359
[1050]	valid_set's binary_logloss: 0.227053
[1100]	valid_set's binary_logloss: 0.2268
[1150]	valid_set's binary_logloss: 0.226516
[1200]	valid_set's binary_logloss: 0.226351
[1250]	valid_set's binary_logloss: 0.22601
[1300]	valid_set's binary_logloss: 0.22575
[1350]	valid_set's binary_logloss: 0.225628
[1400]	valid_set's binary_logloss: 0.225489
[1450]	valid_set's binary_logloss: 0.225394
[1500]	valid_set's binary_logloss: 0.225316
[1550]	valid_set's binary_logloss: 0.225218
[1600]	valid_set's binary_logloss: 0.225122
[1650]	valid_set's binary_logloss: 0.225038
[1700]	valid_set's binary_logloss: 0.22492
[1750]	valid_set's binary_logloss: 0.22481
[1800]	valid_set's binary_logloss: 0.224882
[1850]	valid_set's binary_logloss: 0.224889
[1900]	valid_set's binary_logloss: 0.224882
[1950]	valid_set's binary_logloss: 0.224927
[2000]	valid_set's binary_logloss: 0.224935
[2050]	valid_set's binary_logloss: 0.224977
[2100]	valid_set's binary_logloss: 0.224925
[2150]	valid_set's binary_logloss: 0.224951
[2200]	valid_set's binary_logloss: 0.225031
[2250]	valid_set's binary_logloss: 0.225051
[2300]	valid_set's binary_logloss: 0.225075

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.27958
[100]	valid_set's binary_logloss: 0.259089
[150]	valid_set's binary_logloss: 0.251672
[200]	valid_set's binary_logloss: 0.246665
[250]	valid_set's binary_logloss: 0.243094
[300]	valid_set's binary_logloss: 0.240373
[350]	valid_set's binary_logloss: 0.238276
[400]	valid_set's binary_logloss: 0.236621
[450]	valid_set's binary_logloss: 0.235106
[500]	valid_set's binary_logloss: 0.233975
[550]	valid_set's binary_logloss: 0.232971
[600]	valid_set's binary_logloss: 0.231852
[650]	valid_set's binary_logloss: 0.231218
[700]	valid_set's binary_logloss: 0.2305
[750]	valid_set's binary_logloss: 0.229842
[800]	valid_set's binary_logloss: 0.229111
[850]	valid_set's binary_logloss: 0.228802
[900]	valid_set's binary_logloss: 0.228509
[950]	valid_set's binary_logloss: 0.228123
[1000]	valid_set's binary_logloss: 0.227796
[1050]	valid_set's binary_logloss: 0.227594
[1100]	valid_set's binary_logloss: 0.227442
[1150]	valid_set's binary_logloss: 0.227276
[1200]	valid_set's binary_logloss: 0.227149
[1250]	valid_set's binary_logloss: 0.226938
[1300]	valid_set's binary_logloss: 0.226826
[1350]	valid_set's binary_logloss: 0.226722
[1400]	valid_set's binary_logloss: 0.226607
[1450]	valid_set's binary_logloss: 0.226452
[1500]	valid_set's binary_logloss: 0.226304
[1550]	valid_set's binary_logloss: 0.226273
[1600]	valid_set's binary_logloss: 0.226153
[1650]	valid_set's binary_logloss: 0.226055
[1700]	valid_set's binary_logloss: 0.226048
[1750]	valid_set's binary_logloss: 0.226075
[1800]	valid_set's binary_logloss: 0.226105
[1850]	valid_set's binary_logloss: 0.226073
[1900]	valid_set's binary_logloss: 0.226107
[1950]	valid_set's binary_logloss: 0.226153
[2000]	valid_set's binary_logloss: 0.226217
[2050]	valid_set's binary_logloss: 0.226362
[2100]	valid_set's binary_logloss: 0.226414
[2150]	valid_set's binary_logloss: 0.226515
[2200]	valid_set's binary_logloss: 0.226589

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.279247
[100]	valid_set's binary_logloss: 0.257587
[150]	valid_set's binary_logloss: 0.249825
[200]	valid_set's binary_logloss: 0.244982
[250]	valid_set's binary_logloss: 0.241383
[300]	valid_set's binary_logloss: 0.238449
[350]	valid_set's binary_logloss: 0.23621
[400]	valid_set's binary_logloss: 0.234566
[450]	valid_set's binary_logloss: 0.232984
[500]	valid_set's binary_logloss: 0.232001
[550]	valid_set's binary_logloss: 0.230702
[600]	valid_set's binary_logloss: 0.229906
[650]	valid_set's binary_logloss: 0.229136
[700]	valid_set's binary_logloss: 0.228485
[750]	valid_set's binary_logloss: 0.227797
[800]	valid_set's binary_logloss: 0.227394
[850]	valid_set's binary_logloss: 0.226948
[900]	valid_set's binary_logloss: 0.226445
[950]	valid_set's binary_logloss: 0.226105
[1000]	valid_set's binary_logloss: 0.225673
[1050]	valid_set's binary_logloss: 0.225286
[1100]	valid_set's binary_logloss: 0.224974
[1150]	valid_set's binary_logloss: 0.224737
[1200]	valid_set's binary_logloss: 0.224591
[1250]	valid_set's binary_logloss: 0.224335
[1300]	valid_set's binary_logloss: 0.224232
[1350]	valid_set's binary_logloss: 0.224137
[1400]	valid_set's binary_logloss: 0.224024
[1450]	valid_set's binary_logloss: 0.223871
[1500]	valid_set's binary_logloss: 0.223754
[1550]	valid_set's binary_logloss: 0.223579
[1600]	valid_set's binary_logloss: 0.223484
[1650]	valid_set's binary_logloss: 0.223369
[1700]	valid_set's binary_logloss: 0.223191
[1750]	valid_set's binary_logloss: 0.223081
[1800]	valid_set's binary_logloss: 0.222987
[1850]	valid_set's binary_logloss: 0.223009
[1900]	valid_set's binary_logloss: 0.222946
[1950]	valid_set's binary_logloss: 0.222909
[2000]	valid_set's binary_logloss: 0.222905
[2050]	valid_set's binary_logloss: 0.222868
[2100]	valid_set's binary_logloss: 0.222907
[2150]	valid_set's binary_logloss: 0.222953
[2200]	valid_set's binary_logloss: 0.222924
[2250]	valid_set's binary_logloss: 0.222904
[2300]	valid_set's binary_logloss: 0.222949
[2350]	valid_set's binary_logloss: 0.222956
[2400]	valid_set's binary_logloss: 0.22299
[2450]	valid_set's binary_logloss: 0.223045
[2500]	valid_set's binary_logloss: 0.22308
[2550]	valid_set's binary_logloss: 0.22315
[2600]	valid_set's binary_logloss: 0.223218
[2650]	valid_set's binary_logloss: 0.223293

Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBM_BAG_L1\model.pkl
	0.951	 = Validation score   (roc_auc)
	87.42s	 = Training   runtime
	5.04s	 = Validation runtime
	13402.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 32304.16s of the 32304.16s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.314719
[100]	valid_set's binary_logloss: 0.280986
[150]	valid_set's binary_logloss: 0.267949
[200]	valid_set's binary_logloss: 0.259563
[250]	valid_set's binary_logloss: 0.254195
[300]	valid_set's binary_logloss: 0.250373
[350]	valid_set's binary_logloss: 0.247148
[400]	valid_set's binary_logloss: 0.244472
[450]	valid_set's binary_logloss: 0.242082
[500]	valid_set's binary_logloss: 0.240142
[550]	valid_set's binary_logloss: 0.238587
[600]	valid_set's binary_logloss: 0.237138
[650]	valid_set's binary_logloss: 0.235718
[700]	valid_set's binary_logloss: 0.234636
[750]	valid_set's binary_logloss: 0.233565
[800]	valid_set's binary_logloss: 0.232735
[850]	valid_set's binary_logloss: 0.23201
[900]	valid_set's binary_logloss: 0.231118
[950]	valid_set's binary_logloss: 0.230465
[1000]	valid_set's binary_logloss: 0.22974
[1050]	valid_set's binary_logloss: 0.228993
[1100]	valid_set's binary_logloss: 0.228588
[1150]	valid_set's binary_logloss: 0.228076
[1200]	valid_set's binary_logloss: 0.227642
[1250]	valid_set's binary_logloss: 0.227251
[1300]	valid_set's binary_logloss: 0.226832
[1350]	valid_set's binary_logloss: 0.226337
[1400]	valid_set's binary_logloss: 0.225883
[1450]	valid_set's binary_logloss: 0.22551
[1500]	valid_set's binary_logloss: 0.225102
[1550]	valid_set's binary_logloss: 0.224705
[1600]	valid_set's binary_logloss: 0.224493
[1650]	valid_set's binary_logloss: 0.22429
[1700]	valid_set's binary_logloss: 0.224054
[1750]	valid_set's binary_logloss: 0.223791
[1800]	valid_set's binary_logloss: 0.223492
[1850]	valid_set's binary_logloss: 0.223268
[1900]	valid_set's binary_logloss: 0.223032
[1950]	valid_set's binary_logloss: 0.222848
[2000]	valid_set's binary_logloss: 0.222642
[2050]	valid_set's binary_logloss: 0.222428
[2100]	valid_set's binary_logloss: 0.222407
[2150]	valid_set's binary_logloss: 0.222254
[2200]	valid_set's binary_logloss: 0.222116
[2250]	valid_set's binary_logloss: 0.221997
[2300]	valid_set's binary_logloss: 0.221857
[2350]	valid_set's binary_logloss: 0.221706
[2400]	valid_set's binary_logloss: 0.221568
[2450]	valid_set's binary_logloss: 0.221449
[2500]	valid_set's binary_logloss: 0.221351
[2550]	valid_set's binary_logloss: 0.221291
[2600]	valid_set's binary_logloss: 0.221183
[2650]	valid_set's binary_logloss: 0.221058
[2700]	valid_set's binary_logloss: 0.220977
[2750]	valid_set's binary_logloss: 0.220918
[2800]	valid_set's binary_logloss: 0.220849
[2850]	valid_set's binary_logloss: 0.220711
[2900]	valid_set's binary_logloss: 0.220664
[2950]	valid_set's binary_logloss: 0.220609
[3000]	valid_set's binary_logloss: 0.220511
[3050]	valid_set's binary_logloss: 0.22049
[3100]	valid_set's binary_logloss: 0.220397
[3150]	valid_set's binary_logloss: 0.220321
[3200]	valid_set's binary_logloss: 0.220229
[3250]	valid_set's binary_logloss: 0.220089
[3300]	valid_set's binary_logloss: 0.220092
[3350]	valid_set's binary_logloss: 0.220049
[3400]	valid_set's binary_logloss: 0.219996
[3450]	valid_set's binary_logloss: 0.219973
[3500]	valid_set's binary_logloss: 0.219993
[3550]	valid_set's binary_logloss: 0.21993
[3600]	valid_set's binary_logloss: 0.21987
[3650]	valid_set's binary_logloss: 0.219824
[3700]	valid_set's binary_logloss: 0.219754
[3750]	valid_set's binary_logloss: 0.219719
[3800]	valid_set's binary_logloss: 0.219704
[3850]	valid_set's binary_logloss: 0.219656
[3900]	valid_set's binary_logloss: 0.219629
[3950]	valid_set's binary_logloss: 0.219611
[4000]	valid_set's binary_logloss: 0.219599
[4050]	valid_set's binary_logloss: 0.219618
[4100]	valid_set's binary_logloss: 0.219615
[4150]	valid_set's binary_logloss: 0.219623
[4200]	valid_set's binary_logloss: 0.219607
[4250]	valid_set's binary_logloss: 0.219616
[4300]	valid_set's binary_logloss: 0.219635
[4350]	valid_set's binary_logloss: 0.219645
[4400]	valid_set's binary_logloss: 0.219649
[4450]	valid_set's binary_logloss: 0.219653
[4500]	valid_set's binary_logloss: 0.219668
[4550]	valid_set's binary_logloss: 0.219662
[4600]	valid_set's binary_logloss: 0.219683
[4650]	valid_set's binary_logloss: 0.219711
[4700]	valid_set's binary_logloss: 0.219734
[4750]	valid_set's binary_logloss: 0.21975
[4800]	valid_set's binary_logloss: 0.219788
[4850]	valid_set's binary_logloss: 0.219811
[4900]	valid_set's binary_logloss: 0.219853
[4950]	valid_set's binary_logloss: 0.219843
[5000]	valid_set's binary_logloss: 0.219867
[5050]	valid_set's binary_logloss: 0.219915
[5100]	valid_set's binary_logloss: 0.219959
[5150]	valid_set's binary_logloss: 0.220004
[5200]	valid_set's binary_logloss: 0.220035

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.3125
[100]	valid_set's binary_logloss: 0.28269
[150]	valid_set's binary_logloss: 0.26969
[200]	valid_set's binary_logloss: 0.262323
[250]	valid_set's binary_logloss: 0.256811
[300]	valid_set's binary_logloss: 0.252975
[350]	valid_set's binary_logloss: 0.249918
[400]	valid_set's binary_logloss: 0.247268
[450]	valid_set's binary_logloss: 0.245121
[500]	valid_set's binary_logloss: 0.243228
[550]	valid_set's binary_logloss: 0.241431
[600]	valid_set's binary_logloss: 0.239953
[650]	valid_set's binary_logloss: 0.238762
[700]	valid_set's binary_logloss: 0.237654
[750]	valid_set's binary_logloss: 0.23669
[800]	valid_set's binary_logloss: 0.235709
[850]	valid_set's binary_logloss: 0.234788
[900]	valid_set's binary_logloss: 0.234073
[950]	valid_set's binary_logloss: 0.233398
[1000]	valid_set's binary_logloss: 0.23282
[1050]	valid_set's binary_logloss: 0.232108
[1100]	valid_set's binary_logloss: 0.231558
[1150]	valid_set's binary_logloss: 0.231039
[1200]	valid_set's binary_logloss: 0.230582
[1250]	valid_set's binary_logloss: 0.23016
[1300]	valid_set's binary_logloss: 0.229758
[1350]	valid_set's binary_logloss: 0.229374
[1400]	valid_set's binary_logloss: 0.228903
[1450]	valid_set's binary_logloss: 0.22851
[1500]	valid_set's binary_logloss: 0.228136
[1550]	valid_set's binary_logloss: 0.227816
[1600]	valid_set's binary_logloss: 0.227567
[1650]	valid_set's binary_logloss: 0.227293
[1700]	valid_set's binary_logloss: 0.227095
[1750]	valid_set's binary_logloss: 0.226853
[1800]	valid_set's binary_logloss: 0.226621
[1850]	valid_set's binary_logloss: 0.226311
[1900]	valid_set's binary_logloss: 0.226126
[1950]	valid_set's binary_logloss: 0.225945
[2000]	valid_set's binary_logloss: 0.225785
[2050]	valid_set's binary_logloss: 0.2256
[2100]	valid_set's binary_logloss: 0.225407
[2150]	valid_set's binary_logloss: 0.225311
[2200]	valid_set's binary_logloss: 0.225236
[2250]	valid_set's binary_logloss: 0.225119
[2300]	valid_set's binary_logloss: 0.224991
[2350]	valid_set's binary_logloss: 0.224885
[2400]	valid_set's binary_logloss: 0.224741
[2450]	valid_set's binary_logloss: 0.22463
[2500]	valid_set's binary_logloss: 0.224574
[2550]	valid_set's binary_logloss: 0.22446
[2600]	valid_set's binary_logloss: 0.224441
[2650]	valid_set's binary_logloss: 0.224348
[2700]	valid_set's binary_logloss: 0.224306
[2750]	valid_set's binary_logloss: 0.224226
[2800]	valid_set's binary_logloss: 0.224091
[2850]	valid_set's binary_logloss: 0.223985
[2900]	valid_set's binary_logloss: 0.223926
[2950]	valid_set's binary_logloss: 0.223839
[3000]	valid_set's binary_logloss: 0.223755
[3050]	valid_set's binary_logloss: 0.223664
[3100]	valid_set's binary_logloss: 0.223651
[3150]	valid_set's binary_logloss: 0.223562
[3200]	valid_set's binary_logloss: 0.223471
[3250]	valid_set's binary_logloss: 0.223433
[3300]	valid_set's binary_logloss: 0.223382
[3350]	valid_set's binary_logloss: 0.223351
[3400]	valid_set's binary_logloss: 0.223288
[3450]	valid_set's binary_logloss: 0.223248
[3500]	valid_set's binary_logloss: 0.223256
[3550]	valid_set's binary_logloss: 0.223196
[3600]	valid_set's binary_logloss: 0.223202
[3650]	valid_set's binary_logloss: 0.223221
[3700]	valid_set's binary_logloss: 0.2232
[3750]	valid_set's binary_logloss: 0.223212
[3800]	valid_set's binary_logloss: 0.223211
[3850]	valid_set's binary_logloss: 0.223222
[3900]	valid_set's binary_logloss: 0.223168
[3950]	valid_set's binary_logloss: 0.223156
[4000]	valid_set's binary_logloss: 0.223148
[4050]	valid_set's binary_logloss: 0.223159
[4100]	valid_set's binary_logloss: 0.223111
[4150]	valid_set's binary_logloss: 0.223102
[4200]	valid_set's binary_logloss: 0.223083
[4250]	valid_set's binary_logloss: 0.223054
[4300]	valid_set's binary_logloss: 0.223065
[4350]	valid_set's binary_logloss: 0.223083
[4400]	valid_set's binary_logloss: 0.223114
[4450]	valid_set's binary_logloss: 0.223134
[4500]	valid_set's binary_logloss: 0.223129
[4550]	valid_set's binary_logloss: 0.223184
[4600]	valid_set's binary_logloss: 0.223189
[4650]	valid_set's binary_logloss: 0.223228
[4700]	valid_set's binary_logloss: 0.223236
[4750]	valid_set's binary_logloss: 0.223277
[4800]	valid_set's binary_logloss: 0.223273
[4850]	valid_set's binary_logloss: 0.22334
[4900]	valid_set's binary_logloss: 0.223383
[4950]	valid_set's binary_logloss: 0.223406
[5000]	valid_set's binary_logloss: 0.223413
[5050]	valid_set's binary_logloss: 0.223434
[5100]	valid_set's binary_logloss: 0.223444
[5150]	valid_set's binary_logloss: 0.223444
[5200]	valid_set's binary_logloss: 0.223506
[5250]	valid_set's binary_logloss: 0.223524
[5300]	valid_set's binary_logloss: 0.223528
[5350]	valid_set's binary_logloss: 0.223537
[5400]	valid_set's binary_logloss: 0.223552
[5450]	valid_set's binary_logloss: 0.223557
[5500]	valid_set's binary_logloss: 0.223606
[5550]	valid_set's binary_logloss: 0.223595
[5600]	valid_set's binary_logloss: 0.223634

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.31038
[100]	valid_set's binary_logloss: 0.280382
[150]	valid_set's binary_logloss: 0.268603
[200]	valid_set's binary_logloss: 0.261863
[250]	valid_set's binary_logloss: 0.256549
[300]	valid_set's binary_logloss: 0.252699
[350]	valid_set's binary_logloss: 0.249544
[400]	valid_set's binary_logloss: 0.247032
[450]	valid_set's binary_logloss: 0.244841
[500]	valid_set's binary_logloss: 0.242915
[550]	valid_set's binary_logloss: 0.241571
[600]	valid_set's binary_logloss: 0.24005
[650]	valid_set's binary_logloss: 0.238936
[700]	valid_set's binary_logloss: 0.237855
[750]	valid_set's binary_logloss: 0.236913
[800]	valid_set's binary_logloss: 0.236121
[850]	valid_set's binary_logloss: 0.235535
[900]	valid_set's binary_logloss: 0.23474
[950]	valid_set's binary_logloss: 0.234067
[1000]	valid_set's binary_logloss: 0.23351
[1050]	valid_set's binary_logloss: 0.232956
[1100]	valid_set's binary_logloss: 0.23237
[1150]	valid_set's binary_logloss: 0.231779
[1200]	valid_set's binary_logloss: 0.231293
[1250]	valid_set's binary_logloss: 0.230919
[1300]	valid_set's binary_logloss: 0.230531
[1350]	valid_set's binary_logloss: 0.230181
[1400]	valid_set's binary_logloss: 0.229823
[1450]	valid_set's binary_logloss: 0.229528
[1500]	valid_set's binary_logloss: 0.229228
[1550]	valid_set's binary_logloss: 0.228985
[1600]	valid_set's binary_logloss: 0.228768
[1650]	valid_set's binary_logloss: 0.228511
[1700]	valid_set's binary_logloss: 0.228284
[1750]	valid_set's binary_logloss: 0.228011
[1800]	valid_set's binary_logloss: 0.22775
[1850]	valid_set's binary_logloss: 0.227608
[1900]	valid_set's binary_logloss: 0.227405
[1950]	valid_set's binary_logloss: 0.227194
[2000]	valid_set's binary_logloss: 0.227063
[2050]	valid_set's binary_logloss: 0.227009
[2100]	valid_set's binary_logloss: 0.2269
[2150]	valid_set's binary_logloss: 0.226785
[2200]	valid_set's binary_logloss: 0.226664
[2250]	valid_set's binary_logloss: 0.22661
[2300]	valid_set's binary_logloss: 0.226497
[2350]	valid_set's binary_logloss: 0.226448
[2400]	valid_set's binary_logloss: 0.226363
[2450]	valid_set's binary_logloss: 0.226238
[2500]	valid_set's binary_logloss: 0.226142
[2550]	valid_set's binary_logloss: 0.226085
[2600]	valid_set's binary_logloss: 0.226015
[2650]	valid_set's binary_logloss: 0.225956
[2700]	valid_set's binary_logloss: 0.225881
[2750]	valid_set's binary_logloss: 0.225848
[2800]	valid_set's binary_logloss: 0.225711
[2850]	valid_set's binary_logloss: 0.225699
[2900]	valid_set's binary_logloss: 0.225625
[2950]	valid_set's binary_logloss: 0.225604
[3000]	valid_set's binary_logloss: 0.225518
[3050]	valid_set's binary_logloss: 0.225557
[3100]	valid_set's binary_logloss: 0.225484
[3150]	valid_set's binary_logloss: 0.225484
[3200]	valid_set's binary_logloss: 0.225431
[3250]	valid_set's binary_logloss: 0.22539
[3300]	valid_set's binary_logloss: 0.225298
[3350]	valid_set's binary_logloss: 0.225272
[3400]	valid_set's binary_logloss: 0.225237
[3450]	valid_set's binary_logloss: 0.225205
[3500]	valid_set's binary_logloss: 0.225171
[3550]	valid_set's binary_logloss: 0.225185
[3600]	valid_set's binary_logloss: 0.225205
[3650]	valid_set's binary_logloss: 0.225231
[3700]	valid_set's binary_logloss: 0.225196
[3750]	valid_set's binary_logloss: 0.225209
[3800]	valid_set's binary_logloss: 0.22521
[3850]	valid_set's binary_logloss: 0.225239
[3900]	valid_set's binary_logloss: 0.225268
[3950]	valid_set's binary_logloss: 0.225311
[4000]	valid_set's binary_logloss: 0.225304
[4050]	valid_set's binary_logloss: 0.225281
[4100]	valid_set's binary_logloss: 0.22528
[4150]	valid_set's binary_logloss: 0.225318
[4200]	valid_set's binary_logloss: 0.225333
[4250]	valid_set's binary_logloss: 0.225362
[4300]	valid_set's binary_logloss: 0.225382
[4350]	valid_set's binary_logloss: 0.225368
[4400]	valid_set's binary_logloss: 0.225348
[4450]	valid_set's binary_logloss: 0.225365
[4500]	valid_set's binary_logloss: 0.225369
[4550]	valid_set's binary_logloss: 0.225384

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.310503
[100]	valid_set's binary_logloss: 0.279759
[150]	valid_set's binary_logloss: 0.26661
[200]	valid_set's binary_logloss: 0.259369
[250]	valid_set's binary_logloss: 0.254374
[300]	valid_set's binary_logloss: 0.25016
[350]	valid_set's binary_logloss: 0.247173
[400]	valid_set's binary_logloss: 0.244591
[450]	valid_set's binary_logloss: 0.242461
[500]	valid_set's binary_logloss: 0.240519
[550]	valid_set's binary_logloss: 0.238988
[600]	valid_set's binary_logloss: 0.237567
[650]	valid_set's binary_logloss: 0.23627
[700]	valid_set's binary_logloss: 0.235052
[750]	valid_set's binary_logloss: 0.233966
[800]	valid_set's binary_logloss: 0.23304
[850]	valid_set's binary_logloss: 0.232269
[900]	valid_set's binary_logloss: 0.231547
[950]	valid_set's binary_logloss: 0.230947
[1000]	valid_set's binary_logloss: 0.230342
[1050]	valid_set's binary_logloss: 0.229664
[1100]	valid_set's binary_logloss: 0.229209
[1150]	valid_set's binary_logloss: 0.228704
[1200]	valid_set's binary_logloss: 0.22835
[1250]	valid_set's binary_logloss: 0.227912
[1300]	valid_set's binary_logloss: 0.227531
[1350]	valid_set's binary_logloss: 0.227193
[1400]	valid_set's binary_logloss: 0.226827
[1450]	valid_set's binary_logloss: 0.226523
[1500]	valid_set's binary_logloss: 0.226244
[1550]	valid_set's binary_logloss: 0.226009
[1600]	valid_set's binary_logloss: 0.225722
[1650]	valid_set's binary_logloss: 0.225501
[1700]	valid_set's binary_logloss: 0.225244
[1750]	valid_set's binary_logloss: 0.224999
[1800]	valid_set's binary_logloss: 0.224799
[1850]	valid_set's binary_logloss: 0.224587
[1900]	valid_set's binary_logloss: 0.224389
[1950]	valid_set's binary_logloss: 0.224262
[2000]	valid_set's binary_logloss: 0.224089
[2050]	valid_set's binary_logloss: 0.223922
[2100]	valid_set's binary_logloss: 0.223717
[2150]	valid_set's binary_logloss: 0.223604
[2200]	valid_set's binary_logloss: 0.223459
[2250]	valid_set's binary_logloss: 0.223324
[2300]	valid_set's binary_logloss: 0.223197
[2350]	valid_set's binary_logloss: 0.223116
[2400]	valid_set's binary_logloss: 0.223005
[2450]	valid_set's binary_logloss: 0.222895
[2500]	valid_set's binary_logloss: 0.222792
[2550]	valid_set's binary_logloss: 0.222673
[2600]	valid_set's binary_logloss: 0.222575
[2650]	valid_set's binary_logloss: 0.222504
[2700]	valid_set's binary_logloss: 0.222385
[2750]	valid_set's binary_logloss: 0.222277
[2800]	valid_set's binary_logloss: 0.222156
[2850]	valid_set's binary_logloss: 0.222074
[2900]	valid_set's binary_logloss: 0.221943
[2950]	valid_set's binary_logloss: 0.221891
[3000]	valid_set's binary_logloss: 0.221855
[3050]	valid_set's binary_logloss: 0.221739
[3100]	valid_set's binary_logloss: 0.221713
[3150]	valid_set's binary_logloss: 0.221665
[3200]	valid_set's binary_logloss: 0.221587
[3250]	valid_set's binary_logloss: 0.221543
[3300]	valid_set's binary_logloss: 0.221473
[3350]	valid_set's binary_logloss: 0.221453
[3400]	valid_set's binary_logloss: 0.22142
[3450]	valid_set's binary_logloss: 0.221386
[3500]	valid_set's binary_logloss: 0.221344
[3550]	valid_set's binary_logloss: 0.221344
[3600]	valid_set's binary_logloss: 0.22132
[3650]	valid_set's binary_logloss: 0.221296
[3700]	valid_set's binary_logloss: 0.221266
[3750]	valid_set's binary_logloss: 0.22125
[3800]	valid_set's binary_logloss: 0.221255
[3850]	valid_set's binary_logloss: 0.221296
[3900]	valid_set's binary_logloss: 0.221265
[3950]	valid_set's binary_logloss: 0.221189
[4000]	valid_set's binary_logloss: 0.221188
[4050]	valid_set's binary_logloss: 0.221218
[4100]	valid_set's binary_logloss: 0.22116
[4150]	valid_set's binary_logloss: 0.221124
[4200]	valid_set's binary_logloss: 0.221119
[4250]	valid_set's binary_logloss: 0.22114
[4300]	valid_set's binary_logloss: 0.221144
[4350]	valid_set's binary_logloss: 0.221163
[4400]	valid_set's binary_logloss: 0.221172
[4450]	valid_set's binary_logloss: 0.22116
[4500]	valid_set's binary_logloss: 0.221187
[4550]	valid_set's binary_logloss: 0.221176
[4600]	valid_set's binary_logloss: 0.22117
[4650]	valid_set's binary_logloss: 0.221184
[4700]	valid_set's binary_logloss: 0.22121
[4750]	valid_set's binary_logloss: 0.221259
[4800]	valid_set's binary_logloss: 0.221327
[4850]	valid_set's binary_logloss: 0.22134
[4900]	valid_set's binary_logloss: 0.221322
[4950]	valid_set's binary_logloss: 0.221316
[5000]	valid_set's binary_logloss: 0.221349
[5050]	valid_set's binary_logloss: 0.221346
[5100]	valid_set's binary_logloss: 0.221381
[5150]	valid_set's binary_logloss: 0.221382
[5200]	valid_set's binary_logloss: 0.221365
[5250]	valid_set's binary_logloss: 0.221405
[5300]	valid_set's binary_logloss: 0.221445
[5350]	valid_set's binary_logloss: 0.221478
[5400]	valid_set's binary_logloss: 0.221536
[5450]	valid_set's binary_logloss: 0.221572

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.31216
[100]	valid_set's binary_logloss: 0.280889
[150]	valid_set's binary_logloss: 0.267073
[200]	valid_set's binary_logloss: 0.259935
[250]	valid_set's binary_logloss: 0.25472
[300]	valid_set's binary_logloss: 0.250963
[350]	valid_set's binary_logloss: 0.247298
[400]	valid_set's binary_logloss: 0.244863
[450]	valid_set's binary_logloss: 0.242553
[500]	valid_set's binary_logloss: 0.240633
[550]	valid_set's binary_logloss: 0.238994
[600]	valid_set's binary_logloss: 0.237573
[650]	valid_set's binary_logloss: 0.236186
[700]	valid_set's binary_logloss: 0.234954
[750]	valid_set's binary_logloss: 0.233878
[800]	valid_set's binary_logloss: 0.232991
[850]	valid_set's binary_logloss: 0.23209
[900]	valid_set's binary_logloss: 0.231253
[950]	valid_set's binary_logloss: 0.230584
[1000]	valid_set's binary_logloss: 0.229876
[1050]	valid_set's binary_logloss: 0.229307
[1100]	valid_set's binary_logloss: 0.228712
[1150]	valid_set's binary_logloss: 0.22824
[1200]	valid_set's binary_logloss: 0.227737
[1250]	valid_set's binary_logloss: 0.227302
[1300]	valid_set's binary_logloss: 0.226873
[1350]	valid_set's binary_logloss: 0.226509
[1400]	valid_set's binary_logloss: 0.226005
[1450]	valid_set's binary_logloss: 0.225745
[1500]	valid_set's binary_logloss: 0.225437
[1550]	valid_set's binary_logloss: 0.22523
[1600]	valid_set's binary_logloss: 0.224921
[1650]	valid_set's binary_logloss: 0.224656
[1700]	valid_set's binary_logloss: 0.224317
[1750]	valid_set's binary_logloss: 0.224132
[1800]	valid_set's binary_logloss: 0.223859
[1850]	valid_set's binary_logloss: 0.223653
[1900]	valid_set's binary_logloss: 0.223395
[1950]	valid_set's binary_logloss: 0.223257
[2000]	valid_set's binary_logloss: 0.223042
[2050]	valid_set's binary_logloss: 0.222874
[2100]	valid_set's binary_logloss: 0.222736
[2150]	valid_set's binary_logloss: 0.222584
[2200]	valid_set's binary_logloss: 0.222493
[2250]	valid_set's binary_logloss: 0.222282
[2300]	valid_set's binary_logloss: 0.222182
[2350]	valid_set's binary_logloss: 0.222049
[2400]	valid_set's binary_logloss: 0.221915
[2450]	valid_set's binary_logloss: 0.221773
[2500]	valid_set's binary_logloss: 0.221678
[2550]	valid_set's binary_logloss: 0.221581
[2600]	valid_set's binary_logloss: 0.221466
[2650]	valid_set's binary_logloss: 0.221328
[2700]	valid_set's binary_logloss: 0.221232
[2750]	valid_set's binary_logloss: 0.221194
[2800]	valid_set's binary_logloss: 0.221069
[2850]	valid_set's binary_logloss: 0.220941
[2900]	valid_set's binary_logloss: 0.220809
[2950]	valid_set's binary_logloss: 0.220802
[3000]	valid_set's binary_logloss: 0.220775
[3050]	valid_set's binary_logloss: 0.220736
[3100]	valid_set's binary_logloss: 0.220698
[3150]	valid_set's binary_logloss: 0.220684
[3200]	valid_set's binary_logloss: 0.220608
[3250]	valid_set's binary_logloss: 0.220532
[3300]	valid_set's binary_logloss: 0.220483
[3350]	valid_set's binary_logloss: 0.220471
[3400]	valid_set's binary_logloss: 0.220417
[3450]	valid_set's binary_logloss: 0.22037
[3500]	valid_set's binary_logloss: 0.220271
[3550]	valid_set's binary_logloss: 0.220239
[3600]	valid_set's binary_logloss: 0.220228
[3650]	valid_set's binary_logloss: 0.220191
[3700]	valid_set's binary_logloss: 0.220192
[3750]	valid_set's binary_logloss: 0.22016
[3800]	valid_set's binary_logloss: 0.220151
[3850]	valid_set's binary_logloss: 0.220097
[3900]	valid_set's binary_logloss: 0.220049
[3950]	valid_set's binary_logloss: 0.220035
[4000]	valid_set's binary_logloss: 0.220001
[4050]	valid_set's binary_logloss: 0.219972
[4100]	valid_set's binary_logloss: 0.219976
[4150]	valid_set's binary_logloss: 0.219941
[4200]	valid_set's binary_logloss: 0.219897
[4250]	valid_set's binary_logloss: 0.219856
[4300]	valid_set's binary_logloss: 0.219854
[4350]	valid_set's binary_logloss: 0.219839
[4400]	valid_set's binary_logloss: 0.219832
[4450]	valid_set's binary_logloss: 0.219847
[4500]	valid_set's binary_logloss: 0.21984
[4550]	valid_set's binary_logloss: 0.219855
[4600]	valid_set's binary_logloss: 0.219842
[4650]	valid_set's binary_logloss: 0.219856
[4700]	valid_set's binary_logloss: 0.219844
[4750]	valid_set's binary_logloss: 0.219846
[4800]	valid_set's binary_logloss: 0.219912
[4850]	valid_set's binary_logloss: 0.219913
[4900]	valid_set's binary_logloss: 0.219938
[4950]	valid_set's binary_logloss: 0.219974
[5000]	valid_set's binary_logloss: 0.219982
[5050]	valid_set's binary_logloss: 0.219985
[5100]	valid_set's binary_logloss: 0.22002
[5150]	valid_set's binary_logloss: 0.22006
[5200]	valid_set's binary_logloss: 0.220087
[5250]	valid_set's binary_logloss: 0.220079
[5300]	valid_set's binary_logloss: 0.220114
[5350]	valid_set's binary_logloss: 0.220099
[5400]	valid_set's binary_logloss: 0.220109
[5450]	valid_set's binary_logloss: 0.220133
[5500]	valid_set's binary_logloss: 0.220147
[5550]	valid_set's binary_logloss: 0.220173
[5600]	valid_set's binary_logloss: 0.220189
[5650]	valid_set's binary_logloss: 0.220214
[5700]	valid_set's binary_logloss: 0.220221

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.311676
[100]	valid_set's binary_logloss: 0.279995
[150]	valid_set's binary_logloss: 0.26618
[200]	valid_set's binary_logloss: 0.259062
[250]	valid_set's binary_logloss: 0.253566
[300]	valid_set's binary_logloss: 0.250017
[350]	valid_set's binary_logloss: 0.247148
[400]	valid_set's binary_logloss: 0.244483
[450]	valid_set's binary_logloss: 0.242466
[500]	valid_set's binary_logloss: 0.240508
[550]	valid_set's binary_logloss: 0.23884
[600]	valid_set's binary_logloss: 0.237392
[650]	valid_set's binary_logloss: 0.23618
[700]	valid_set's binary_logloss: 0.234964
[750]	valid_set's binary_logloss: 0.233896
[800]	valid_set's binary_logloss: 0.232917
[850]	valid_set's binary_logloss: 0.232055
[900]	valid_set's binary_logloss: 0.231231
[950]	valid_set's binary_logloss: 0.230433
[1000]	valid_set's binary_logloss: 0.22983
[1050]	valid_set's binary_logloss: 0.229167
[1100]	valid_set's binary_logloss: 0.228605
[1150]	valid_set's binary_logloss: 0.228024
[1200]	valid_set's binary_logloss: 0.227583
[1250]	valid_set's binary_logloss: 0.227142
[1300]	valid_set's binary_logloss: 0.226715
[1350]	valid_set's binary_logloss: 0.226329
[1400]	valid_set's binary_logloss: 0.225992
[1450]	valid_set's binary_logloss: 0.225711
[1500]	valid_set's binary_logloss: 0.225352
[1550]	valid_set's binary_logloss: 0.225093
[1600]	valid_set's binary_logloss: 0.224855
[1650]	valid_set's binary_logloss: 0.224578
[1700]	valid_set's binary_logloss: 0.22429
[1750]	valid_set's binary_logloss: 0.223974
[1800]	valid_set's binary_logloss: 0.223793
[1850]	valid_set's binary_logloss: 0.223597
[1900]	valid_set's binary_logloss: 0.223434
[1950]	valid_set's binary_logloss: 0.223237
[2000]	valid_set's binary_logloss: 0.223086
[2050]	valid_set's binary_logloss: 0.222841
[2100]	valid_set's binary_logloss: 0.222641
[2150]	valid_set's binary_logloss: 0.222457
[2200]	valid_set's binary_logloss: 0.222361
[2250]	valid_set's binary_logloss: 0.222201
[2300]	valid_set's binary_logloss: 0.222065
[2350]	valid_set's binary_logloss: 0.221908
[2400]	valid_set's binary_logloss: 0.221761
[2450]	valid_set's binary_logloss: 0.221692
[2500]	valid_set's binary_logloss: 0.221606
[2550]	valid_set's binary_logloss: 0.221478
[2600]	valid_set's binary_logloss: 0.221331
[2650]	valid_set's binary_logloss: 0.221238
[2700]	valid_set's binary_logloss: 0.221162
[2750]	valid_set's binary_logloss: 0.221074
[2800]	valid_set's binary_logloss: 0.221027
[2850]	valid_set's binary_logloss: 0.220936
[2900]	valid_set's binary_logloss: 0.2209
[2950]	valid_set's binary_logloss: 0.220859
[3000]	valid_set's binary_logloss: 0.220839
[3050]	valid_set's binary_logloss: 0.220727
[3100]	valid_set's binary_logloss: 0.220667
[3150]	valid_set's binary_logloss: 0.220583
[3200]	valid_set's binary_logloss: 0.220555
[3250]	valid_set's binary_logloss: 0.220489
[3300]	valid_set's binary_logloss: 0.22048
[3350]	valid_set's binary_logloss: 0.220414
[3400]	valid_set's binary_logloss: 0.220428
[3450]	valid_set's binary_logloss: 0.220328
[3500]	valid_set's binary_logloss: 0.2203
[3550]	valid_set's binary_logloss: 0.220237
[3600]	valid_set's binary_logloss: 0.220225
[3650]	valid_set's binary_logloss: 0.220197
[3700]	valid_set's binary_logloss: 0.220193
[3750]	valid_set's binary_logloss: 0.220127
[3800]	valid_set's binary_logloss: 0.22009
[3850]	valid_set's binary_logloss: 0.220034
[3900]	valid_set's binary_logloss: 0.220024
[3950]	valid_set's binary_logloss: 0.220017
[4000]	valid_set's binary_logloss: 0.220024
[4050]	valid_set's binary_logloss: 0.219971
[4100]	valid_set's binary_logloss: 0.219955
[4150]	valid_set's binary_logloss: 0.219947
[4200]	valid_set's binary_logloss: 0.219997
[4250]	valid_set's binary_logloss: 0.219974
[4300]	valid_set's binary_logloss: 0.219943
[4350]	valid_set's binary_logloss: 0.219905
[4400]	valid_set's binary_logloss: 0.219924
[4450]	valid_set's binary_logloss: 0.219904
[4500]	valid_set's binary_logloss: 0.219919
[4550]	valid_set's binary_logloss: 0.219933
[4600]	valid_set's binary_logloss: 0.219918
[4650]	valid_set's binary_logloss: 0.21991
[4700]	valid_set's binary_logloss: 0.219971
[4750]	valid_set's binary_logloss: 0.219938
[4800]	valid_set's binary_logloss: 0.219921
[4850]	valid_set's binary_logloss: 0.21996
[4900]	valid_set's binary_logloss: 0.219978
[4950]	valid_set's binary_logloss: 0.219987
[5000]	valid_set's binary_logloss: 0.219995
[5050]	valid_set's binary_logloss: 0.22002
[5100]	valid_set's binary_logloss: 0.220021
[5150]	valid_set's binary_logloss: 0.220042
[5200]	valid_set's binary_logloss: 0.220059
[5250]	valid_set's binary_logloss: 0.220085
[5300]	valid_set's binary_logloss: 0.220067
[5350]	valid_set's binary_logloss: 0.220114
[5400]	valid_set's binary_logloss: 0.220097
[5450]	valid_set's binary_logloss: 0.220151
[5500]	valid_set's binary_logloss: 0.220196
[5550]	valid_set's binary_logloss: 0.220243
[5600]	valid_set's binary_logloss: 0.220268
[5650]	valid_set's binary_logloss: 0.220293
[5700]	valid_set's binary_logloss: 0.220271
[5750]	valid_set's binary_logloss: 0.220258

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.306384
[100]	valid_set's binary_logloss: 0.276563
[150]	valid_set's binary_logloss: 0.264527
[200]	valid_set's binary_logloss: 0.257311
[250]	valid_set's binary_logloss: 0.252003
[300]	valid_set's binary_logloss: 0.248148
[350]	valid_set's binary_logloss: 0.245292
[400]	valid_set's binary_logloss: 0.243184
[450]	valid_set's binary_logloss: 0.241291
[500]	valid_set's binary_logloss: 0.239554
[550]	valid_set's binary_logloss: 0.238024
[600]	valid_set's binary_logloss: 0.236594
[650]	valid_set's binary_logloss: 0.235267
[700]	valid_set's binary_logloss: 0.234299
[750]	valid_set's binary_logloss: 0.233348
[800]	valid_set's binary_logloss: 0.232492
[850]	valid_set's binary_logloss: 0.231729
[900]	valid_set's binary_logloss: 0.231042
[950]	valid_set's binary_logloss: 0.230454
[1000]	valid_set's binary_logloss: 0.229926
[1050]	valid_set's binary_logloss: 0.229419
[1100]	valid_set's binary_logloss: 0.228856
[1150]	valid_set's binary_logloss: 0.228394
[1200]	valid_set's binary_logloss: 0.227936
[1250]	valid_set's binary_logloss: 0.227433
[1300]	valid_set's binary_logloss: 0.227096
[1350]	valid_set's binary_logloss: 0.226768
[1400]	valid_set's binary_logloss: 0.226408
[1450]	valid_set's binary_logloss: 0.22615
[1500]	valid_set's binary_logloss: 0.225873
[1550]	valid_set's binary_logloss: 0.225562
[1600]	valid_set's binary_logloss: 0.225343
[1650]	valid_set's binary_logloss: 0.225106
[1700]	valid_set's binary_logloss: 0.224889
[1750]	valid_set's binary_logloss: 0.224666
[1800]	valid_set's binary_logloss: 0.224506
[1850]	valid_set's binary_logloss: 0.224237
[1900]	valid_set's binary_logloss: 0.224075
[1950]	valid_set's binary_logloss: 0.223922
[2000]	valid_set's binary_logloss: 0.223807
[2050]	valid_set's binary_logloss: 0.223689
[2100]	valid_set's binary_logloss: 0.223609
[2150]	valid_set's binary_logloss: 0.223468
[2200]	valid_set's binary_logloss: 0.223254
[2250]	valid_set's binary_logloss: 0.223158
[2300]	valid_set's binary_logloss: 0.223103
[2350]	valid_set's binary_logloss: 0.222968
[2400]	valid_set's binary_logloss: 0.222829
[2450]	valid_set's binary_logloss: 0.22275
[2500]	valid_set's binary_logloss: 0.222628
[2550]	valid_set's binary_logloss: 0.222461
[2600]	valid_set's binary_logloss: 0.222431
[2650]	valid_set's binary_logloss: 0.222406
[2700]	valid_set's binary_logloss: 0.222341
[2750]	valid_set's binary_logloss: 0.222278
[2800]	valid_set's binary_logloss: 0.222177
[2850]	valid_set's binary_logloss: 0.222105
[2900]	valid_set's binary_logloss: 0.222072
[2950]	valid_set's binary_logloss: 0.222023
[3000]	valid_set's binary_logloss: 0.221946
[3050]	valid_set's binary_logloss: 0.221921
[3100]	valid_set's binary_logloss: 0.221841
[3150]	valid_set's binary_logloss: 0.221817
[3200]	valid_set's binary_logloss: 0.221777
[3250]	valid_set's binary_logloss: 0.221759
[3300]	valid_set's binary_logloss: 0.221736
[3350]	valid_set's binary_logloss: 0.221758
[3400]	valid_set's binary_logloss: 0.221802
[3450]	valid_set's binary_logloss: 0.221728
[3500]	valid_set's binary_logloss: 0.221658
[3550]	valid_set's binary_logloss: 0.22162
[3600]	valid_set's binary_logloss: 0.221629
[3650]	valid_set's binary_logloss: 0.221578
[3700]	valid_set's binary_logloss: 0.221582
[3750]	valid_set's binary_logloss: 0.221593
[3800]	valid_set's binary_logloss: 0.221608
[3850]	valid_set's binary_logloss: 0.221587
[3900]	valid_set's binary_logloss: 0.221573
[3950]	valid_set's binary_logloss: 0.221544
[4000]	valid_set's binary_logloss: 0.221509
[4050]	valid_set's binary_logloss: 0.221482
[4100]	valid_set's binary_logloss: 0.221506
[4150]	valid_set's binary_logloss: 0.221532
[4200]	valid_set's binary_logloss: 0.221558
[4250]	valid_set's binary_logloss: 0.22156
[4300]	valid_set's binary_logloss: 0.221582
[4350]	valid_set's binary_logloss: 0.221604
[4400]	valid_set's binary_logloss: 0.221594
[4450]	valid_set's binary_logloss: 0.221595
[4500]	valid_set's binary_logloss: 0.221561
[4550]	valid_set's binary_logloss: 0.22158
[4600]	valid_set's binary_logloss: 0.221522
[4650]	valid_set's binary_logloss: 0.221525
[4700]	valid_set's binary_logloss: 0.221523
[4750]	valid_set's binary_logloss: 0.221518
[4800]	valid_set's binary_logloss: 0.221536
[4850]	valid_set's binary_logloss: 0.22157
[4900]	valid_set's binary_logloss: 0.221622
[4950]	valid_set's binary_logloss: 0.22164
[5000]	valid_set's binary_logloss: 0.221648
[5050]	valid_set's binary_logloss: 0.221675
[5100]	valid_set's binary_logloss: 0.221713
[5150]	valid_set's binary_logloss: 0.221744
[5200]	valid_set's binary_logloss: 0.221774
[5250]	valid_set's binary_logloss: 0.221863

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.306565
[100]	valid_set's binary_logloss: 0.276107
[150]	valid_set's binary_logloss: 0.262547
[200]	valid_set's binary_logloss: 0.255838
[250]	valid_set's binary_logloss: 0.250943
[300]	valid_set's binary_logloss: 0.247496
[350]	valid_set's binary_logloss: 0.244706
[400]	valid_set's binary_logloss: 0.242332
[450]	valid_set's binary_logloss: 0.240264
[500]	valid_set's binary_logloss: 0.238438
[550]	valid_set's binary_logloss: 0.236992
[600]	valid_set's binary_logloss: 0.235531
[650]	valid_set's binary_logloss: 0.234282
[700]	valid_set's binary_logloss: 0.233292
[750]	valid_set's binary_logloss: 0.232415
[800]	valid_set's binary_logloss: 0.231514
[850]	valid_set's binary_logloss: 0.230521
[900]	valid_set's binary_logloss: 0.229737
[950]	valid_set's binary_logloss: 0.229066
[1000]	valid_set's binary_logloss: 0.228492
[1050]	valid_set's binary_logloss: 0.227988
[1100]	valid_set's binary_logloss: 0.22745
[1150]	valid_set's binary_logloss: 0.226828
[1200]	valid_set's binary_logloss: 0.22629
[1250]	valid_set's binary_logloss: 0.225952
[1300]	valid_set's binary_logloss: 0.225577
[1350]	valid_set's binary_logloss: 0.225212
[1400]	valid_set's binary_logloss: 0.224923
[1450]	valid_set's binary_logloss: 0.224605
[1500]	valid_set's binary_logloss: 0.224272
[1550]	valid_set's binary_logloss: 0.22397
[1600]	valid_set's binary_logloss: 0.223679
[1650]	valid_set's binary_logloss: 0.223463
[1700]	valid_set's binary_logloss: 0.223242
[1750]	valid_set's binary_logloss: 0.223085
[1800]	valid_set's binary_logloss: 0.22285
[1850]	valid_set's binary_logloss: 0.222673
[1900]	valid_set's binary_logloss: 0.222581
[1950]	valid_set's binary_logloss: 0.222401
[2000]	valid_set's binary_logloss: 0.222165
[2050]	valid_set's binary_logloss: 0.221989
[2100]	valid_set's binary_logloss: 0.221922
[2150]	valid_set's binary_logloss: 0.221841
[2200]	valid_set's binary_logloss: 0.22167
[2250]	valid_set's binary_logloss: 0.221608
[2300]	valid_set's binary_logloss: 0.221477
[2350]	valid_set's binary_logloss: 0.221398
[2400]	valid_set's binary_logloss: 0.221292
[2450]	valid_set's binary_logloss: 0.221125
[2500]	valid_set's binary_logloss: 0.221026
[2550]	valid_set's binary_logloss: 0.220949
[2600]	valid_set's binary_logloss: 0.220902
[2650]	valid_set's binary_logloss: 0.220795
[2700]	valid_set's binary_logloss: 0.220665
[2750]	valid_set's binary_logloss: 0.220544
[2800]	valid_set's binary_logloss: 0.220464
[2850]	valid_set's binary_logloss: 0.220361
[2900]	valid_set's binary_logloss: 0.220283
[2950]	valid_set's binary_logloss: 0.220285
[3000]	valid_set's binary_logloss: 0.220174
[3050]	valid_set's binary_logloss: 0.220108
[3100]	valid_set's binary_logloss: 0.220019
[3150]	valid_set's binary_logloss: 0.219996
[3200]	valid_set's binary_logloss: 0.219942
[3250]	valid_set's binary_logloss: 0.219888
[3300]	valid_set's binary_logloss: 0.219889
[3350]	valid_set's binary_logloss: 0.219889
[3400]	valid_set's binary_logloss: 0.219863
[3450]	valid_set's binary_logloss: 0.219797
[3500]	valid_set's binary_logloss: 0.219773
[3550]	valid_set's binary_logloss: 0.219774
[3600]	valid_set's binary_logloss: 0.219737
[3650]	valid_set's binary_logloss: 0.219682
[3700]	valid_set's binary_logloss: 0.21966
[3750]	valid_set's binary_logloss: 0.219618
[3800]	valid_set's binary_logloss: 0.219613
[3850]	valid_set's binary_logloss: 0.219574
[3900]	valid_set's binary_logloss: 0.219555
[3950]	valid_set's binary_logloss: 0.21953
[4000]	valid_set's binary_logloss: 0.219484
[4050]	valid_set's binary_logloss: 0.219439
[4100]	valid_set's binary_logloss: 0.21945
[4150]	valid_set's binary_logloss: 0.219425
[4200]	valid_set's binary_logloss: 0.219371
[4250]	valid_set's binary_logloss: 0.219369
[4300]	valid_set's binary_logloss: 0.219364
[4350]	valid_set's binary_logloss: 0.219352
[4400]	valid_set's binary_logloss: 0.219317
[4450]	valid_set's binary_logloss: 0.219317
[4500]	valid_set's binary_logloss: 0.219299
[4550]	valid_set's binary_logloss: 0.219321
[4600]	valid_set's binary_logloss: 0.219328
[4650]	valid_set's binary_logloss: 0.219301
[4700]	valid_set's binary_logloss: 0.219273
[4750]	valid_set's binary_logloss: 0.219288
[4800]	valid_set's binary_logloss: 0.21931
[4850]	valid_set's binary_logloss: 0.219322
[4900]	valid_set's binary_logloss: 0.219289
[4950]	valid_set's binary_logloss: 0.219291
[5000]	valid_set's binary_logloss: 0.219239
[5050]	valid_set's binary_logloss: 0.21926
[5100]	valid_set's binary_logloss: 0.219285
[5150]	valid_set's binary_logloss: 0.219258
[5200]	valid_set's binary_logloss: 0.219262
[5250]	valid_set's binary_logloss: 0.219349
[5300]	valid_set's binary_logloss: 0.219346
[5350]	valid_set's binary_logloss: 0.219387
[5400]	valid_set's binary_logloss: 0.219427
[5450]	valid_set's binary_logloss: 0.219449
[5500]	valid_set's binary_logloss: 0.219501
[5550]	valid_set's binary_logloss: 0.219513
[5600]	valid_set's binary_logloss: 0.219519
[5650]	valid_set's binary_logloss: 0.219487
[5700]	valid_set's binary_logloss: 0.219503
[5750]	valid_set's binary_logloss: 0.219555
[5800]	valid_set's binary_logloss: 0.21958
[5850]	valid_set's binary_logloss: 0.219559
[5900]	valid_set's binary_logloss: 0.219598
[5950]	valid_set's binary_logloss: 0.219621
[6000]	valid_set's binary_logloss: 0.219633
[6050]	valid_set's binary_logloss: 0.219665
[6100]	valid_set's binary_logloss: 0.219695
[6150]	valid_set's binary_logloss: 0.219707
[6200]	valid_set's binary_logloss: 0.219737
[6250]	valid_set's binary_logloss: 0.219778
[6300]	valid_set's binary_logloss: 0.219788
[6350]	valid_set's binary_logloss: 0.219822
[6400]	valid_set's binary_logloss: 0.219902
[6450]	valid_set's binary_logloss: 0.219941
[6500]	valid_set's binary_logloss: 0.219956
[6550]	valid_set's binary_logloss: 0.219975
[6600]	valid_set's binary_logloss: 0.220018
[6650]	valid_set's binary_logloss: 0.220096
[6700]	valid_set's binary_logloss: 0.220153

Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
	0.9529	 = Validation score   (roc_auc)
	173.93s	 = Training   runtime
	14.05s	 = Validation runtime
	4808.4	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 32114.83s of the 32114.82s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645541	test: 0.6645852	best: 0.6645852 (0)	total: 115ms	remaining: 115ms
1:	learn: 0.6386749	test: 0.6387355	best: 0.6387355 (1)	total: 121ms	remaining: 0us
bestTest = 0.6387354796
bestIteration = 1
0:	learn: 0.6399530	test: 0.6400741	best: 0.6400741 (0)	total: 21.9ms	remaining: 39.4s
20:	learn: 0.3358518	test: 0.3362118	best: 0.3362118 (20)	total: 457ms	remaining: 38.7s
40:	learn: 0.3029080	test: 0.3031676	best: 0.3031676 (40)	total: 896ms	remaining: 38.4s
60:	learn: 0.2893111	test: 0.2891351	best: 0.2891351 (60)	total: 1.34s	remaining: 38.1s
80:	learn: 0.2810953	test: 0.2807439	best: 0.2807439 (80)	total: 1.77s	remaining: 37.5s
100:	learn: 0.2746064	test: 0.2739670	best: 0.2739670 (100)	total: 2.19s	remaining: 36.8s
120:	learn: 0.2696832	test: 0.2689104	best: 0.2689104 (120)	total: 2.62s	remaining: 36.3s
140:	learn: 0.2657481	test: 0.2648148	best: 0.2648148 (140)	total: 3.03s	remaining: 35.6s
160:	learn: 0.2622558	test: 0.2612122	best: 0.2612122 (160)	total: 3.43s	remaining: 34.9s
180:	learn: 0.2590732	test: 0.2579133	best: 0.2579133 (180)	total: 3.82s	remaining: 34.1s
200:	learn: 0.2564548	test: 0.2552469	best: 0.2552469 (200)	total: 4.21s	remaining: 33.4s
220:	learn: 0.2539539	test: 0.2526710	best: 0.2526710 (220)	total: 4.58s	remaining: 32.7s
240:	learn: 0.2516015	test: 0.2502399	best: 0.2502399 (240)	total: 4.98s	remaining: 32.1s
260:	learn: 0.2496274	test: 0.2483098	best: 0.2483098 (260)	total: 5.36s	remaining: 31.6s
280:	learn: 0.2480394	test: 0.2467170	best: 0.2467170 (280)	total: 5.74s	remaining: 31s
300:	learn: 0.2465511	test: 0.2451189	best: 0.2451189 (300)	total: 6.13s	remaining: 30.5s
320:	learn: 0.2451853	test: 0.2438146	best: 0.2438146 (320)	total: 6.52s	remaining: 30s
340:	learn: 0.2439973	test: 0.2426082	best: 0.2426082 (340)	total: 6.91s	remaining: 29.5s
360:	learn: 0.2430656	test: 0.2417296	best: 0.2417296 (360)	total: 7.27s	remaining: 28.9s
380:	learn: 0.2420330	test: 0.2407841	best: 0.2407841 (380)	total: 7.65s	remaining: 28.4s
400:	learn: 0.2410121	test: 0.2397722	best: 0.2397722 (400)	total: 8.03s	remaining: 27.9s
420:	learn: 0.2398926	test: 0.2386536	best: 0.2386536 (420)	total: 8.42s	remaining: 27.5s
440:	learn: 0.2387828	test: 0.2376077	best: 0.2376077 (440)	total: 8.8s	remaining: 27.1s
460:	learn: 0.2378768	test: 0.2368011	best: 0.2368011 (460)	total: 9.2s	remaining: 26.7s
480:	learn: 0.2370898	test: 0.2361210	best: 0.2361210 (480)	total: 9.58s	remaining: 26.2s
500:	learn: 0.2362632	test: 0.2353750	best: 0.2353750 (500)	total: 9.95s	remaining: 25.8s
520:	learn: 0.2354594	test: 0.2346776	best: 0.2346776 (520)	total: 10.3s	remaining: 25.3s
540:	learn: 0.2347401	test: 0.2340239	best: 0.2340239 (540)	total: 10.7s	remaining: 24.9s
560:	learn: 0.2338685	test: 0.2331988	best: 0.2331988 (560)	total: 11.1s	remaining: 24.5s
580:	learn: 0.2333077	test: 0.2327001	best: 0.2327001 (580)	total: 11.5s	remaining: 24.1s
600:	learn: 0.2326469	test: 0.2320908	best: 0.2320908 (600)	total: 11.9s	remaining: 23.7s
620:	learn: 0.2320464	test: 0.2315519	best: 0.2315519 (620)	total: 12.3s	remaining: 23.3s
640:	learn: 0.2314671	test: 0.2310829	best: 0.2310829 (640)	total: 12.7s	remaining: 22.9s
660:	learn: 0.2308518	test: 0.2305487	best: 0.2305487 (660)	total: 13.1s	remaining: 22.4s
680:	learn: 0.2302225	test: 0.2299362	best: 0.2299362 (680)	total: 13.5s	remaining: 22.1s
700:	learn: 0.2297113	test: 0.2294757	best: 0.2294740 (699)	total: 13.9s	remaining: 21.7s
720:	learn: 0.2292240	test: 0.2291053	best: 0.2291053 (720)	total: 14.2s	remaining: 21.3s
740:	learn: 0.2287804	test: 0.2287670	best: 0.2287670 (740)	total: 14.6s	remaining: 20.8s
760:	learn: 0.2282775	test: 0.2283545	best: 0.2283545 (760)	total: 15s	remaining: 20.4s
780:	learn: 0.2277517	test: 0.2279459	best: 0.2279459 (780)	total: 15.4s	remaining: 20s
800:	learn: 0.2272910	test: 0.2275831	best: 0.2275831 (800)	total: 15.8s	remaining: 19.6s
820:	learn: 0.2268586	test: 0.2272539	best: 0.2272539 (820)	total: 16.2s	remaining: 19.2s
840:	learn: 0.2264584	test: 0.2269771	best: 0.2269771 (840)	total: 16.6s	remaining: 18.9s
860:	learn: 0.2260405	test: 0.2267129	best: 0.2267129 (860)	total: 17s	remaining: 18.5s
880:	learn: 0.2255489	test: 0.2262860	best: 0.2262860 (880)	total: 17.4s	remaining: 18.1s
900:	learn: 0.2251201	test: 0.2258907	best: 0.2258907 (900)	total: 17.8s	remaining: 17.7s
920:	learn: 0.2246775	test: 0.2255169	best: 0.2255169 (920)	total: 18.3s	remaining: 17.4s
940:	learn: 0.2242770	test: 0.2252144	best: 0.2252144 (940)	total: 18.7s	remaining: 17s
960:	learn: 0.2239710	test: 0.2249735	best: 0.2249735 (960)	total: 19.1s	remaining: 16.6s
980:	learn: 0.2236477	test: 0.2247450	best: 0.2247450 (980)	total: 19.5s	remaining: 16.2s
1000:	learn: 0.2233388	test: 0.2245193	best: 0.2245193 (1000)	total: 19.9s	remaining: 15.9s
1020:	learn: 0.2229614	test: 0.2242587	best: 0.2242587 (1020)	total: 20.4s	remaining: 15.5s
1040:	learn: 0.2226229	test: 0.2240108	best: 0.2240108 (1040)	total: 20.8s	remaining: 15.1s
1060:	learn: 0.2222494	test: 0.2237350	best: 0.2237350 (1060)	total: 21.2s	remaining: 14.7s
1080:	learn: 0.2218466	test: 0.2234473	best: 0.2234473 (1080)	total: 21.6s	remaining: 14.3s
1100:	learn: 0.2215446	test: 0.2232266	best: 0.2232266 (1100)	total: 22.1s	remaining: 14s
1120:	learn: 0.2212002	test: 0.2229401	best: 0.2229401 (1120)	total: 22.5s	remaining: 13.6s
1140:	learn: 0.2208892	test: 0.2227218	best: 0.2227218 (1140)	total: 22.9s	remaining: 13.2s
1160:	learn: 0.2205966	test: 0.2225282	best: 0.2225282 (1160)	total: 23.3s	remaining: 12.8s
1180:	learn: 0.2201936	test: 0.2222175	best: 0.2222175 (1180)	total: 23.7s	remaining: 12.4s
1200:	learn: 0.2198987	test: 0.2220621	best: 0.2220621 (1200)	total: 24.1s	remaining: 12s
1220:	learn: 0.2195990	test: 0.2218367	best: 0.2218359 (1219)	total: 24.5s	remaining: 11.6s
1240:	learn: 0.2193302	test: 0.2216615	best: 0.2216615 (1240)	total: 25s	remaining: 11.2s
1260:	learn: 0.2190547	test: 0.2214523	best: 0.2214523 (1260)	total: 25.4s	remaining: 10.8s
1280:	learn: 0.2187873	test: 0.2212805	best: 0.2212793 (1279)	total: 25.8s	remaining: 10.4s
1300:	learn: 0.2185504	test: 0.2211409	best: 0.2211409 (1300)	total: 26.2s	remaining: 9.99s
1320:	learn: 0.2182735	test: 0.2209563	best: 0.2209563 (1320)	total: 26.6s	remaining: 9.6s
1340:	learn: 0.2179801	test: 0.2207576	best: 0.2207576 (1340)	total: 27s	remaining: 9.2s
1360:	learn: 0.2176741	test: 0.2205295	best: 0.2205295 (1360)	total: 27.5s	remaining: 8.8s
1380:	learn: 0.2174223	test: 0.2203662	best: 0.2203662 (1380)	total: 27.9s	remaining: 8.4s
1400:	learn: 0.2171761	test: 0.2202131	best: 0.2202131 (1400)	total: 28.3s	remaining: 7.99s
1420:	learn: 0.2169135	test: 0.2200642	best: 0.2200642 (1420)	total: 28.7s	remaining: 7.59s
1440:	learn: 0.2166770	test: 0.2199165	best: 0.2199165 (1440)	total: 29.1s	remaining: 7.19s
1460:	learn: 0.2164647	test: 0.2197958	best: 0.2197958 (1460)	total: 29.5s	remaining: 6.79s
1480:	learn: 0.2162558	test: 0.2196703	best: 0.2196678 (1479)	total: 29.9s	remaining: 6.38s
1500:	learn: 0.2160440	test: 0.2195641	best: 0.2195641 (1500)	total: 30.3s	remaining: 5.98s
1520:	learn: 0.2158274	test: 0.2194087	best: 0.2194087 (1520)	total: 30.7s	remaining: 5.58s
1540:	learn: 0.2155506	test: 0.2192257	best: 0.2192257 (1540)	total: 31.1s	remaining: 5.17s
1560:	learn: 0.2153391	test: 0.2190886	best: 0.2190886 (1560)	total: 31.6s	remaining: 4.77s
1580:	learn: 0.2151439	test: 0.2189772	best: 0.2189772 (1580)	total: 32s	remaining: 4.37s
1600:	learn: 0.2149755	test: 0.2188817	best: 0.2188817 (1600)	total: 32.4s	remaining: 3.97s
1620:	learn: 0.2147532	test: 0.2187304	best: 0.2187304 (1620)	total: 32.8s	remaining: 3.56s
1640:	learn: 0.2145760	test: 0.2186392	best: 0.2186392 (1640)	total: 33.2s	remaining: 3.16s
1660:	learn: 0.2143137	test: 0.2184549	best: 0.2184549 (1660)	total: 33.6s	remaining: 2.75s
1680:	learn: 0.2141017	test: 0.2183481	best: 0.2183481 (1680)	total: 34s	remaining: 2.35s
1700:	learn: 0.2138441	test: 0.2182043	best: 0.2182043 (1700)	total: 34.4s	remaining: 1.94s
1720:	learn: 0.2136544	test: 0.2181015	best: 0.2181007 (1719)	total: 34.8s	remaining: 1.54s
1740:	learn: 0.2134739	test: 0.2179906	best: 0.2179906 (1740)	total: 35.3s	remaining: 1.13s
1760:	learn: 0.2132470	test: 0.2179025	best: 0.2179025 (1760)	total: 35.7s	remaining: 729ms
1780:	learn: 0.2130198	test: 0.2177755	best: 0.2177755 (1780)	total: 36s	remaining: 324ms
1796:	learn: 0.2128805	test: 0.2177176	best: 0.2177176 (1796)	total: 36.4s	remaining: 0us
bestTest = 0.21771761
bestIteration = 1796

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645341	test: 0.6646592	best: 0.6646592 (0)	total: 5.05ms	remaining: 5.05ms
1:	learn: 0.6386355	test: 0.6388839	best: 0.6388839 (1)	total: 10.1ms	remaining: 0us
bestTest = 0.6388839097
bestIteration = 1
0:	learn: 0.6397529	test: 0.6400311	best: 0.6400311 (0)	total: 19.8ms	remaining: 1m 40s
20:	learn: 0.3344490	test: 0.3365073	best: 0.3365073 (20)	total: 436ms	remaining: 1m 44s
40:	learn: 0.3006330	test: 0.3031021	best: 0.3031021 (40)	total: 870ms	remaining: 1m 46s
60:	learn: 0.2877984	test: 0.2899659	best: 0.2899659 (60)	total: 1.32s	remaining: 1m 48s
80:	learn: 0.2780761	test: 0.2799262	best: 0.2799262 (80)	total: 1.76s	remaining: 1m 48s
100:	learn: 0.2729810	test: 0.2748209	best: 0.2748209 (100)	total: 2.18s	remaining: 1m 47s
120:	learn: 0.2690019	test: 0.2707992	best: 0.2707992 (120)	total: 2.58s	remaining: 1m 45s
140:	learn: 0.2643367	test: 0.2661032	best: 0.2661032 (140)	total: 2.99s	remaining: 1m 44s
160:	learn: 0.2607623	test: 0.2625935	best: 0.2625935 (160)	total: 3.38s	remaining: 1m 43s
180:	learn: 0.2579857	test: 0.2598391	best: 0.2598391 (180)	total: 3.78s	remaining: 1m 42s
200:	learn: 0.2553615	test: 0.2569777	best: 0.2569777 (200)	total: 4.21s	remaining: 1m 41s
220:	learn: 0.2532655	test: 0.2547991	best: 0.2547991 (220)	total: 4.63s	remaining: 1m 41s
240:	learn: 0.2510732	test: 0.2524965	best: 0.2524965 (240)	total: 5.05s	remaining: 1m 41s
260:	learn: 0.2490246	test: 0.2503479	best: 0.2503479 (260)	total: 5.47s	remaining: 1m 40s
280:	learn: 0.2475556	test: 0.2488339	best: 0.2488339 (280)	total: 5.9s	remaining: 1m 40s
300:	learn: 0.2459237	test: 0.2471699	best: 0.2471699 (300)	total: 6.31s	remaining: 1m 39s
320:	learn: 0.2445206	test: 0.2457876	best: 0.2457876 (320)	total: 6.7s	remaining: 1m 39s
340:	learn: 0.2433397	test: 0.2446415	best: 0.2446415 (340)	total: 7.11s	remaining: 1m 38s
360:	learn: 0.2422495	test: 0.2436721	best: 0.2436721 (360)	total: 7.52s	remaining: 1m 37s
380:	learn: 0.2409135	test: 0.2423715	best: 0.2423715 (380)	total: 7.94s	remaining: 1m 37s
400:	learn: 0.2397955	test: 0.2413384	best: 0.2413384 (400)	total: 8.35s	remaining: 1m 37s
420:	learn: 0.2388950	test: 0.2404483	best: 0.2404483 (420)	total: 8.78s	remaining: 1m 36s
440:	learn: 0.2380009	test: 0.2396002	best: 0.2396002 (440)	total: 9.2s	remaining: 1m 36s
460:	learn: 0.2370720	test: 0.2386834	best: 0.2386834 (460)	total: 9.61s	remaining: 1m 35s
480:	learn: 0.2363372	test: 0.2380506	best: 0.2380506 (480)	total: 10s	remaining: 1m 35s
500:	learn: 0.2354351	test: 0.2372414	best: 0.2372414 (500)	total: 10.4s	remaining: 1m 34s
520:	learn: 0.2347206	test: 0.2365867	best: 0.2365867 (520)	total: 10.8s	remaining: 1m 34s
540:	learn: 0.2341601	test: 0.2361562	best: 0.2361562 (540)	total: 11.2s	remaining: 1m 33s
560:	learn: 0.2334119	test: 0.2355173	best: 0.2355173 (560)	total: 11.7s	remaining: 1m 33s
580:	learn: 0.2327465	test: 0.2349913	best: 0.2349913 (580)	total: 12.1s	remaining: 1m 33s
600:	learn: 0.2320128	test: 0.2342628	best: 0.2342628 (600)	total: 12.5s	remaining: 1m 32s
620:	learn: 0.2314588	test: 0.2338121	best: 0.2338121 (620)	total: 12.8s	remaining: 1m 31s
640:	learn: 0.2308574	test: 0.2333063	best: 0.2333063 (640)	total: 13.2s	remaining: 1m 31s
660:	learn: 0.2302969	test: 0.2328454	best: 0.2328454 (660)	total: 13.6s	remaining: 1m 30s
680:	learn: 0.2297251	test: 0.2323721	best: 0.2323721 (680)	total: 14s	remaining: 1m 30s
700:	learn: 0.2291635	test: 0.2318757	best: 0.2318757 (700)	total: 14.4s	remaining: 1m 29s
720:	learn: 0.2285791	test: 0.2313221	best: 0.2313221 (720)	total: 14.8s	remaining: 1m 28s
740:	learn: 0.2280161	test: 0.2308341	best: 0.2308341 (740)	total: 15.2s	remaining: 1m 28s
760:	learn: 0.2274935	test: 0.2304011	best: 0.2304011 (760)	total: 15.5s	remaining: 1m 27s
780:	learn: 0.2269191	test: 0.2299324	best: 0.2299324 (780)	total: 15.9s	remaining: 1m 27s
800:	learn: 0.2264421	test: 0.2295649	best: 0.2295649 (800)	total: 16.3s	remaining: 1m 26s
820:	learn: 0.2260434	test: 0.2292995	best: 0.2292995 (820)	total: 16.7s	remaining: 1m 26s
840:	learn: 0.2256912	test: 0.2290213	best: 0.2290213 (840)	total: 17.1s	remaining: 1m 25s
860:	learn: 0.2252585	test: 0.2286398	best: 0.2286398 (860)	total: 17.5s	remaining: 1m 25s
880:	learn: 0.2248927	test: 0.2283534	best: 0.2283534 (880)	total: 17.8s	remaining: 1m 24s
900:	learn: 0.2243718	test: 0.2278604	best: 0.2278604 (900)	total: 18.2s	remaining: 1m 24s
920:	learn: 0.2238966	test: 0.2274960	best: 0.2274960 (920)	total: 18.6s	remaining: 1m 23s
940:	learn: 0.2234684	test: 0.2272068	best: 0.2272068 (940)	total: 19s	remaining: 1m 23s
960:	learn: 0.2230976	test: 0.2269127	best: 0.2269127 (960)	total: 19.4s	remaining: 1m 22s
980:	learn: 0.2226486	test: 0.2265360	best: 0.2265360 (980)	total: 19.8s	remaining: 1m 22s
1000:	learn: 0.2222050	test: 0.2261892	best: 0.2261892 (1000)	total: 20.2s	remaining: 1m 21s
1020:	learn: 0.2218695	test: 0.2259619	best: 0.2259619 (1020)	total: 20.6s	remaining: 1m 21s
1040:	learn: 0.2214329	test: 0.2256166	best: 0.2256166 (1040)	total: 21s	remaining: 1m 21s
1060:	learn: 0.2211343	test: 0.2254170	best: 0.2254170 (1060)	total: 21.4s	remaining: 1m 20s
1080:	learn: 0.2208837	test: 0.2252423	best: 0.2252423 (1080)	total: 21.8s	remaining: 1m 20s
1100:	learn: 0.2204939	test: 0.2249683	best: 0.2249683 (1100)	total: 22.2s	remaining: 1m 19s
1120:	learn: 0.2202627	test: 0.2248232	best: 0.2248232 (1120)	total: 22.5s	remaining: 1m 19s
1140:	learn: 0.2199395	test: 0.2245707	best: 0.2245692 (1139)	total: 23s	remaining: 1m 18s
1160:	learn: 0.2196846	test: 0.2244177	best: 0.2244177 (1160)	total: 23.4s	remaining: 1m 18s
1180:	learn: 0.2193106	test: 0.2241084	best: 0.2241084 (1180)	total: 23.7s	remaining: 1m 18s
1200:	learn: 0.2190503	test: 0.2239140	best: 0.2239140 (1200)	total: 24.1s	remaining: 1m 17s
1220:	learn: 0.2188035	test: 0.2237357	best: 0.2237357 (1220)	total: 24.5s	remaining: 1m 17s
1240:	learn: 0.2185916	test: 0.2236172	best: 0.2236172 (1240)	total: 24.9s	remaining: 1m 16s
1260:	learn: 0.2182881	test: 0.2233799	best: 0.2233799 (1260)	total: 25.3s	remaining: 1m 16s
1280:	learn: 0.2180206	test: 0.2232160	best: 0.2232160 (1280)	total: 25.7s	remaining: 1m 15s
1300:	learn: 0.2177556	test: 0.2230524	best: 0.2230524 (1300)	total: 26.1s	remaining: 1m 15s
1320:	learn: 0.2175049	test: 0.2228755	best: 0.2228755 (1320)	total: 26.5s	remaining: 1m 15s
1340:	learn: 0.2172145	test: 0.2226890	best: 0.2226890 (1340)	total: 26.9s	remaining: 1m 14s
1360:	learn: 0.2169715	test: 0.2225416	best: 0.2225416 (1360)	total: 27.3s	remaining: 1m 14s
1380:	learn: 0.2167383	test: 0.2224130	best: 0.2224130 (1380)	total: 27.7s	remaining: 1m 13s
1400:	learn: 0.2164666	test: 0.2222581	best: 0.2222581 (1400)	total: 28.1s	remaining: 1m 13s
1420:	learn: 0.2162784	test: 0.2221246	best: 0.2221246 (1420)	total: 28.5s	remaining: 1m 12s
1440:	learn: 0.2160385	test: 0.2219569	best: 0.2219569 (1440)	total: 28.9s	remaining: 1m 12s
1460:	learn: 0.2157842	test: 0.2217967	best: 0.2217967 (1460)	total: 29.3s	remaining: 1m 12s
1480:	learn: 0.2154729	test: 0.2215342	best: 0.2215342 (1480)	total: 29.7s	remaining: 1m 11s
1500:	learn: 0.2151641	test: 0.2213005	best: 0.2213005 (1500)	total: 30.1s	remaining: 1m 11s
1520:	learn: 0.2149422	test: 0.2211560	best: 0.2211560 (1520)	total: 30.4s	remaining: 1m 10s
1540:	learn: 0.2147169	test: 0.2210047	best: 0.2210047 (1540)	total: 30.8s	remaining: 1m 10s
1560:	learn: 0.2145125	test: 0.2208803	best: 0.2208803 (1560)	total: 31.2s	remaining: 1m 10s
1580:	learn: 0.2142596	test: 0.2207542	best: 0.2207521 (1577)	total: 31.6s	remaining: 1m 9s
1600:	learn: 0.2140623	test: 0.2206125	best: 0.2206125 (1600)	total: 32s	remaining: 1m 9s
1620:	learn: 0.2138459	test: 0.2204928	best: 0.2204928 (1620)	total: 32.4s	remaining: 1m 8s
1640:	learn: 0.2135635	test: 0.2202861	best: 0.2202861 (1640)	total: 32.8s	remaining: 1m 8s
1660:	learn: 0.2133602	test: 0.2201786	best: 0.2201773 (1659)	total: 33.2s	remaining: 1m 7s
1680:	learn: 0.2131878	test: 0.2200769	best: 0.2200769 (1680)	total: 33.6s	remaining: 1m 7s
1700:	learn: 0.2129707	test: 0.2199450	best: 0.2199450 (1700)	total: 33.9s	remaining: 1m 7s
1720:	learn: 0.2127783	test: 0.2198371	best: 0.2198371 (1720)	total: 34.3s	remaining: 1m 6s
1740:	learn: 0.2125510	test: 0.2197066	best: 0.2197066 (1740)	total: 34.7s	remaining: 1m 6s
1760:	learn: 0.2123711	test: 0.2195809	best: 0.2195809 (1760)	total: 35.1s	remaining: 1m 5s
1780:	learn: 0.2121456	test: 0.2194375	best: 0.2194375 (1780)	total: 35.5s	remaining: 1m 5s
1800:	learn: 0.2119277	test: 0.2192813	best: 0.2192813 (1800)	total: 35.9s	remaining: 1m 4s
1820:	learn: 0.2117407	test: 0.2191571	best: 0.2191571 (1820)	total: 36.2s	remaining: 1m 4s
1840:	learn: 0.2115605	test: 0.2190605	best: 0.2190605 (1840)	total: 36.6s	remaining: 1m 4s
1860:	learn: 0.2113659	test: 0.2189312	best: 0.2189312 (1860)	total: 37s	remaining: 1m 3s
1880:	learn: 0.2111875	test: 0.2188491	best: 0.2188491 (1880)	total: 37.4s	remaining: 1m 3s
1900:	learn: 0.2109810	test: 0.2187355	best: 0.2187353 (1899)	total: 37.8s	remaining: 1m 2s
1920:	learn: 0.2107510	test: 0.2185714	best: 0.2185714 (1920)	total: 38.2s	remaining: 1m 2s
1940:	learn: 0.2105861	test: 0.2184870	best: 0.2184870 (1939)	total: 38.6s	remaining: 1m 2s
1960:	learn: 0.2104139	test: 0.2183813	best: 0.2183813 (1960)	total: 39s	remaining: 1m 1s
1980:	learn: 0.2102207	test: 0.2182669	best: 0.2182669 (1980)	total: 39.4s	remaining: 1m 1s
2000:	learn: 0.2100411	test: 0.2181964	best: 0.2181964 (2000)	total: 39.8s	remaining: 1m
2020:	learn: 0.2098580	test: 0.2181065	best: 0.2181065 (2020)	total: 40.1s	remaining: 1m
2040:	learn: 0.2096906	test: 0.2180175	best: 0.2180175 (2040)	total: 40.5s	remaining: 1m
2060:	learn: 0.2094580	test: 0.2178775	best: 0.2178775 (2060)	total: 40.9s	remaining: 59.6s
2080:	learn: 0.2092813	test: 0.2177479	best: 0.2177479 (2080)	total: 41.3s	remaining: 59.2s
2100:	learn: 0.2091075	test: 0.2176609	best: 0.2176609 (2100)	total: 41.7s	remaining: 58.8s
2120:	learn: 0.2089446	test: 0.2175898	best: 0.2175898 (2120)	total: 42.1s	remaining: 58.4s
2140:	learn: 0.2087789	test: 0.2175124	best: 0.2175124 (2140)	total: 42.5s	remaining: 58s
2160:	learn: 0.2085994	test: 0.2174224	best: 0.2174224 (2160)	total: 42.9s	remaining: 57.6s
2180:	learn: 0.2084142	test: 0.2173320	best: 0.2173320 (2180)	total: 43.3s	remaining: 57.2s
2200:	learn: 0.2082543	test: 0.2172376	best: 0.2172376 (2200)	total: 43.7s	remaining: 56.8s
2220:	learn: 0.2080673	test: 0.2171438	best: 0.2171438 (2220)	total: 44.1s	remaining: 56.4s
2240:	learn: 0.2078995	test: 0.2170338	best: 0.2170338 (2240)	total: 44.5s	remaining: 56s
2260:	learn: 0.2077179	test: 0.2169286	best: 0.2169286 (2260)	total: 44.9s	remaining: 55.6s
2280:	learn: 0.2075498	test: 0.2168726	best: 0.2168726 (2280)	total: 45.2s	remaining: 55.2s
2300:	learn: 0.2073772	test: 0.2167778	best: 0.2167778 (2300)	total: 45.6s	remaining: 54.8s
2320:	learn: 0.2071966	test: 0.2167069	best: 0.2167069 (2320)	total: 46s	remaining: 54.4s
2340:	learn: 0.2070180	test: 0.2165822	best: 0.2165809 (2339)	total: 46.4s	remaining: 54s
2360:	learn: 0.2068715	test: 0.2165185	best: 0.2165185 (2360)	total: 46.8s	remaining: 53.5s
2380:	learn: 0.2067116	test: 0.2164589	best: 0.2164589 (2380)	total: 47.2s	remaining: 53.1s
2400:	learn: 0.2065261	test: 0.2163420	best: 0.2163420 (2400)	total: 47.5s	remaining: 52.7s
2420:	learn: 0.2063808	test: 0.2162743	best: 0.2162743 (2420)	total: 47.9s	remaining: 52.3s
2440:	learn: 0.2062020	test: 0.2161943	best: 0.2161943 (2440)	total: 48.3s	remaining: 51.9s
2460:	learn: 0.2060169	test: 0.2160745	best: 0.2160745 (2460)	total: 48.7s	remaining: 51.5s
2480:	learn: 0.2058429	test: 0.2159723	best: 0.2159700 (2479)	total: 49.1s	remaining: 51.1s
2500:	learn: 0.2057090	test: 0.2159046	best: 0.2159046 (2499)	total: 49.5s	remaining: 50.8s
2520:	learn: 0.2055888	test: 0.2158535	best: 0.2158535 (2520)	total: 49.9s	remaining: 50.4s
2540:	learn: 0.2054298	test: 0.2157950	best: 0.2157950 (2540)	total: 50.3s	remaining: 49.9s
2560:	learn: 0.2052784	test: 0.2157297	best: 0.2157297 (2560)	total: 50.7s	remaining: 49.5s
2580:	learn: 0.2051073	test: 0.2156402	best: 0.2156402 (2580)	total: 51.1s	remaining: 49.1s
2600:	learn: 0.2049708	test: 0.2155899	best: 0.2155898 (2599)	total: 51.5s	remaining: 48.8s
2620:	learn: 0.2047723	test: 0.2154749	best: 0.2154749 (2620)	total: 51.9s	remaining: 48.4s
2640:	learn: 0.2046285	test: 0.2153840	best: 0.2153840 (2640)	total: 52.3s	remaining: 48s
2660:	learn: 0.2044604	test: 0.2153110	best: 0.2153110 (2660)	total: 52.7s	remaining: 47.6s
2680:	learn: 0.2043276	test: 0.2152628	best: 0.2152628 (2680)	total: 53.1s	remaining: 47.2s
2700:	learn: 0.2041897	test: 0.2152026	best: 0.2152026 (2700)	total: 53.5s	remaining: 46.8s
2720:	learn: 0.2040300	test: 0.2151191	best: 0.2151191 (2720)	total: 53.9s	remaining: 46.4s
2740:	learn: 0.2038738	test: 0.2150398	best: 0.2150398 (2740)	total: 54.3s	remaining: 46s
2760:	learn: 0.2037414	test: 0.2150057	best: 0.2150048 (2757)	total: 54.7s	remaining: 45.6s
2780:	learn: 0.2035953	test: 0.2149295	best: 0.2149295 (2780)	total: 55.1s	remaining: 45.2s
2800:	learn: 0.2034595	test: 0.2148637	best: 0.2148637 (2800)	total: 55.5s	remaining: 44.8s
2820:	learn: 0.2033163	test: 0.2148141	best: 0.2148141 (2820)	total: 55.9s	remaining: 44.4s
2840:	learn: 0.2031877	test: 0.2147572	best: 0.2147559 (2838)	total: 56.3s	remaining: 44s
2860:	learn: 0.2030617	test: 0.2147087	best: 0.2147087 (2860)	total: 56.7s	remaining: 43.6s
2880:	learn: 0.2029514	test: 0.2146560	best: 0.2146560 (2880)	total: 57.1s	remaining: 43.2s
2900:	learn: 0.2028081	test: 0.2146187	best: 0.2146187 (2900)	total: 57.5s	remaining: 42.8s
2920:	learn: 0.2026684	test: 0.2145459	best: 0.2145459 (2920)	total: 57.9s	remaining: 42.4s
2940:	learn: 0.2025450	test: 0.2145047	best: 0.2145033 (2939)	total: 58.3s	remaining: 42s
2960:	learn: 0.2024070	test: 0.2144662	best: 0.2144662 (2960)	total: 58.7s	remaining: 41.6s
2980:	learn: 0.2022852	test: 0.2144101	best: 0.2144101 (2980)	total: 59.1s	remaining: 41.2s
3000:	learn: 0.2021378	test: 0.2143244	best: 0.2143225 (2998)	total: 59.5s	remaining: 40.9s
3020:	learn: 0.2020158	test: 0.2142873	best: 0.2142873 (3020)	total: 59.9s	remaining: 40.5s
3040:	learn: 0.2018833	test: 0.2142089	best: 0.2142089 (3040)	total: 1m	remaining: 40.1s
3060:	learn: 0.2017745	test: 0.2141775	best: 0.2141775 (3060)	total: 1m	remaining: 39.7s
3080:	learn: 0.2016452	test: 0.2141194	best: 0.2141194 (3080)	total: 1m 1s	remaining: 39.3s
3100:	learn: 0.2015408	test: 0.2140758	best: 0.2140758 (3100)	total: 1m 1s	remaining: 38.9s
3120:	learn: 0.2014166	test: 0.2140258	best: 0.2140258 (3120)	total: 1m 1s	remaining: 38.5s
3140:	learn: 0.2012920	test: 0.2139737	best: 0.2139702 (3138)	total: 1m 2s	remaining: 38.1s
3160:	learn: 0.2011548	test: 0.2139221	best: 0.2139221 (3160)	total: 1m 2s	remaining: 37.7s
3180:	learn: 0.2010314	test: 0.2138903	best: 0.2138903 (3180)	total: 1m 3s	remaining: 37.3s
3200:	learn: 0.2009260	test: 0.2138619	best: 0.2138619 (3200)	total: 1m 3s	remaining: 36.9s
3220:	learn: 0.2007979	test: 0.2138051	best: 0.2138051 (3220)	total: 1m 3s	remaining: 36.5s
3240:	learn: 0.2006744	test: 0.2137568	best: 0.2137567 (3239)	total: 1m 4s	remaining: 36.1s
3260:	learn: 0.2005342	test: 0.2137164	best: 0.2137164 (3260)	total: 1m 4s	remaining: 35.7s
3280:	learn: 0.2004155	test: 0.2136924	best: 0.2136914 (3279)	total: 1m 5s	remaining: 35.3s
3300:	learn: 0.2002992	test: 0.2136517	best: 0.2136504 (3298)	total: 1m 5s	remaining: 34.9s
3320:	learn: 0.2001557	test: 0.2135874	best: 0.2135874 (3320)	total: 1m 5s	remaining: 34.5s
3340:	learn: 0.2000495	test: 0.2135556	best: 0.2135556 (3340)	total: 1m 6s	remaining: 34.1s
3360:	learn: 0.1999431	test: 0.2135052	best: 0.2135032 (3359)	total: 1m 6s	remaining: 33.7s
3380:	learn: 0.1998350	test: 0.2134642	best: 0.2134642 (3380)	total: 1m 7s	remaining: 33.4s
3400:	learn: 0.1997233	test: 0.2134239	best: 0.2134239 (3400)	total: 1m 7s	remaining: 33s
3420:	learn: 0.1996000	test: 0.2133708	best: 0.2133708 (3420)	total: 1m 7s	remaining: 32.6s
3440:	learn: 0.1994860	test: 0.2133229	best: 0.2133229 (3440)	total: 1m 8s	remaining: 32.2s
3460:	learn: 0.1993745	test: 0.2132754	best: 0.2132745 (3459)	total: 1m 8s	remaining: 31.8s
3480:	learn: 0.1992763	test: 0.2132407	best: 0.2132407 (3480)	total: 1m 9s	remaining: 31.4s
3500:	learn: 0.1991463	test: 0.2131861	best: 0.2131861 (3500)	total: 1m 9s	remaining: 31s
3520:	learn: 0.1990220	test: 0.2131716	best: 0.2131712 (3519)	total: 1m 9s	remaining: 30.6s
3540:	learn: 0.1988988	test: 0.2131228	best: 0.2131228 (3540)	total: 1m 10s	remaining: 30.2s
3560:	learn: 0.1987968	test: 0.2130790	best: 0.2130790 (3560)	total: 1m 10s	remaining: 29.8s
3580:	learn: 0.1986688	test: 0.2130206	best: 0.2130206 (3580)	total: 1m 11s	remaining: 29.4s
3600:	learn: 0.1985581	test: 0.2130006	best: 0.2130006 (3600)	total: 1m 11s	remaining: 29s
3620:	learn: 0.1984440	test: 0.2129529	best: 0.2129518 (3618)	total: 1m 11s	remaining: 28.6s
3640:	learn: 0.1983241	test: 0.2129077	best: 0.2129077 (3640)	total: 1m 12s	remaining: 28.2s
3660:	learn: 0.1982154	test: 0.2128715	best: 0.2128703 (3659)	total: 1m 12s	remaining: 27.8s
3680:	learn: 0.1980853	test: 0.2128064	best: 0.2128062 (3679)	total: 1m 13s	remaining: 27.4s
3700:	learn: 0.1979477	test: 0.2127493	best: 0.2127493 (3700)	total: 1m 13s	remaining: 27s
3720:	learn: 0.1978375	test: 0.2127041	best: 0.2127041 (3720)	total: 1m 13s	remaining: 26.6s
3740:	learn: 0.1977193	test: 0.2126705	best: 0.2126705 (3740)	total: 1m 14s	remaining: 26.2s
3760:	learn: 0.1975827	test: 0.2126182	best: 0.2126182 (3760)	total: 1m 14s	remaining: 25.8s
3780:	learn: 0.1974616	test: 0.2125621	best: 0.2125621 (3780)	total: 1m 15s	remaining: 25.5s
3800:	learn: 0.1973546	test: 0.2125309	best: 0.2125309 (3800)	total: 1m 15s	remaining: 25.1s
3820:	learn: 0.1972248	test: 0.2124674	best: 0.2124674 (3820)	total: 1m 15s	remaining: 24.7s
3840:	learn: 0.1971168	test: 0.2124291	best: 0.2124291 (3840)	total: 1m 16s	remaining: 24.3s
3860:	learn: 0.1970147	test: 0.2124123	best: 0.2124121 (3858)	total: 1m 16s	remaining: 23.9s
3880:	learn: 0.1969106	test: 0.2123775	best: 0.2123775 (3880)	total: 1m 17s	remaining: 23.5s
3900:	learn: 0.1968117	test: 0.2123330	best: 0.2123330 (3900)	total: 1m 17s	remaining: 23.1s
3920:	learn: 0.1966964	test: 0.2123061	best: 0.2123061 (3920)	total: 1m 17s	remaining: 22.7s
3940:	learn: 0.1965918	test: 0.2122900	best: 0.2122883 (3937)	total: 1m 18s	remaining: 22.3s
3960:	learn: 0.1964703	test: 0.2122365	best: 0.2122365 (3960)	total: 1m 18s	remaining: 21.9s
3980:	learn: 0.1963827	test: 0.2122076	best: 0.2122076 (3980)	total: 1m 19s	remaining: 21.5s
4000:	learn: 0.1962738	test: 0.2121615	best: 0.2121615 (4000)	total: 1m 19s	remaining: 21.1s
4020:	learn: 0.1961680	test: 0.2121429	best: 0.2121429 (4020)	total: 1m 19s	remaining: 20.7s
4040:	learn: 0.1960591	test: 0.2121089	best: 0.2121038 (4038)	total: 1m 20s	remaining: 20.3s
4060:	learn: 0.1959637	test: 0.2120727	best: 0.2120727 (4060)	total: 1m 20s	remaining: 19.9s
4080:	learn: 0.1958624	test: 0.2120446	best: 0.2120446 (4080)	total: 1m 21s	remaining: 19.5s
4100:	learn: 0.1957566	test: 0.2120168	best: 0.2120134 (4096)	total: 1m 21s	remaining: 19.1s
4120:	learn: 0.1956454	test: 0.2119901	best: 0.2119901 (4120)	total: 1m 21s	remaining: 18.7s
4140:	learn: 0.1955449	test: 0.2119670	best: 0.2119670 (4140)	total: 1m 22s	remaining: 18.3s
4160:	learn: 0.1954369	test: 0.2119482	best: 0.2119482 (4160)	total: 1m 22s	remaining: 17.9s
4180:	learn: 0.1953517	test: 0.2119243	best: 0.2119242 (4174)	total: 1m 23s	remaining: 17.6s
4200:	learn: 0.1952491	test: 0.2119055	best: 0.2119046 (4198)	total: 1m 23s	remaining: 17.2s
4220:	learn: 0.1951525	test: 0.2118927	best: 0.2118884 (4218)	total: 1m 24s	remaining: 16.8s
4240:	learn: 0.1950619	test: 0.2118901	best: 0.2118761 (4232)	total: 1m 24s	remaining: 16.4s
4260:	learn: 0.1949656	test: 0.2118688	best: 0.2118688 (4260)	total: 1m 24s	remaining: 16s
4280:	learn: 0.1948468	test: 0.2118312	best: 0.2118298 (4279)	total: 1m 25s	remaining: 15.6s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645496	test: 0.6646141	best: 0.6646141 (0)	total: 5.23ms	remaining: 5.23ms
1:	learn: 0.6386625	test: 0.6388009	best: 0.6388009 (1)	total: 10.5ms	remaining: 0us
bestTest = 0.6388009346
bestIteration = 1
0:	learn: 0.6399179	test: 0.6399812	best: 0.6399812 (0)	total: 18.6ms	remaining: 2m 2s
20:	learn: 0.3359186	test: 0.3368528	best: 0.3368528 (20)	total: 426ms	remaining: 2m 12s
40:	learn: 0.3022278	test: 0.3035941	best: 0.3035941 (40)	total: 837ms	remaining: 2m 13s
60:	learn: 0.2894654	test: 0.2905801	best: 0.2905801 (60)	total: 1.24s	remaining: 2m 12s
80:	learn: 0.2811064	test: 0.2822411	best: 0.2822411 (80)	total: 1.65s	remaining: 2m 11s
100:	learn: 0.2752100	test: 0.2763467	best: 0.2763467 (100)	total: 2.03s	remaining: 2m 9s
120:	learn: 0.2701063	test: 0.2714467	best: 0.2714467 (120)	total: 2.41s	remaining: 2m 8s
140:	learn: 0.2660929	test: 0.2674454	best: 0.2674454 (140)	total: 2.81s	remaining: 2m 7s
160:	learn: 0.2619203	test: 0.2631671	best: 0.2631671 (160)	total: 3.22s	remaining: 2m 8s
180:	learn: 0.2589911	test: 0.2603500	best: 0.2603500 (180)	total: 3.61s	remaining: 2m 7s
200:	learn: 0.2562077	test: 0.2573833	best: 0.2573833 (200)	total: 4.02s	remaining: 2m 7s
220:	learn: 0.2539381	test: 0.2551862	best: 0.2551862 (220)	total: 4.42s	remaining: 2m 6s
240:	learn: 0.2517969	test: 0.2531814	best: 0.2531814 (240)	total: 4.8s	remaining: 2m 6s
260:	learn: 0.2498996	test: 0.2512678	best: 0.2512678 (260)	total: 5.2s	remaining: 2m 5s
280:	learn: 0.2482608	test: 0.2496984	best: 0.2496984 (280)	total: 5.58s	remaining: 2m 4s
300:	learn: 0.2466902	test: 0.2482124	best: 0.2482124 (300)	total: 5.98s	remaining: 2m 4s
320:	learn: 0.2447666	test: 0.2462370	best: 0.2462370 (320)	total: 6.38s	remaining: 2m 3s
340:	learn: 0.2432839	test: 0.2448113	best: 0.2448113 (340)	total: 6.78s	remaining: 2m 3s
360:	learn: 0.2423032	test: 0.2440250	best: 0.2440250 (360)	total: 7.16s	remaining: 2m 2s
380:	learn: 0.2412890	test: 0.2431612	best: 0.2431612 (380)	total: 7.53s	remaining: 2m 2s
400:	learn: 0.2403198	test: 0.2422806	best: 0.2422806 (400)	total: 7.92s	remaining: 2m 1s
420:	learn: 0.2392519	test: 0.2412567	best: 0.2412567 (420)	total: 8.31s	remaining: 2m 1s
440:	learn: 0.2382440	test: 0.2403314	best: 0.2403314 (440)	total: 8.72s	remaining: 2m
460:	learn: 0.2374092	test: 0.2395854	best: 0.2395854 (460)	total: 9.11s	remaining: 2m
480:	learn: 0.2365838	test: 0.2388479	best: 0.2388479 (480)	total: 9.5s	remaining: 2m
500:	learn: 0.2357719	test: 0.2381212	best: 0.2381212 (500)	total: 9.89s	remaining: 1m 59s
520:	learn: 0.2350007	test: 0.2374196	best: 0.2374196 (520)	total: 10.3s	remaining: 1m 59s
540:	learn: 0.2342660	test: 0.2367816	best: 0.2367816 (540)	total: 10.7s	remaining: 1m 58s
560:	learn: 0.2336191	test: 0.2362334	best: 0.2362334 (560)	total: 11.1s	remaining: 1m 58s
580:	learn: 0.2328429	test: 0.2355899	best: 0.2355899 (580)	total: 11.5s	remaining: 1m 57s
600:	learn: 0.2322153	test: 0.2350871	best: 0.2350871 (600)	total: 11.8s	remaining: 1m 57s
620:	learn: 0.2315520	test: 0.2345022	best: 0.2345022 (620)	total: 12.2s	remaining: 1m 56s
640:	learn: 0.2308778	test: 0.2339752	best: 0.2339752 (640)	total: 12.6s	remaining: 1m 56s
660:	learn: 0.2302790	test: 0.2335048	best: 0.2335048 (660)	total: 13s	remaining: 1m 56s
680:	learn: 0.2296884	test: 0.2329612	best: 0.2329612 (680)	total: 13.4s	remaining: 1m 55s
700:	learn: 0.2291972	test: 0.2326010	best: 0.2326010 (700)	total: 13.8s	remaining: 1m 54s
720:	learn: 0.2286919	test: 0.2322207	best: 0.2322207 (720)	total: 14.1s	remaining: 1m 54s
740:	learn: 0.2281393	test: 0.2317546	best: 0.2317546 (740)	total: 14.5s	remaining: 1m 54s
760:	learn: 0.2276256	test: 0.2313265	best: 0.2313265 (760)	total: 14.9s	remaining: 1m 53s
780:	learn: 0.2271423	test: 0.2309420	best: 0.2309420 (780)	total: 15.3s	remaining: 1m 53s
800:	learn: 0.2267827	test: 0.2307012	best: 0.2307012 (800)	total: 15.7s	remaining: 1m 52s
820:	learn: 0.2263869	test: 0.2304653	best: 0.2304653 (820)	total: 16s	remaining: 1m 52s
840:	learn: 0.2259366	test: 0.2301104	best: 0.2301104 (840)	total: 16.4s	remaining: 1m 51s
860:	learn: 0.2254604	test: 0.2297080	best: 0.2297080 (860)	total: 16.8s	remaining: 1m 51s
880:	learn: 0.2249670	test: 0.2292573	best: 0.2292573 (880)	total: 17.2s	remaining: 1m 51s
900:	learn: 0.2246035	test: 0.2289906	best: 0.2289906 (900)	total: 17.6s	remaining: 1m 50s
920:	learn: 0.2242323	test: 0.2287066	best: 0.2287066 (920)	total: 18s	remaining: 1m 50s
940:	learn: 0.2239030	test: 0.2285044	best: 0.2285044 (940)	total: 18.4s	remaining: 1m 49s
960:	learn: 0.2235425	test: 0.2282475	best: 0.2282475 (960)	total: 18.8s	remaining: 1m 49s
980:	learn: 0.2230860	test: 0.2279052	best: 0.2279052 (980)	total: 19.2s	remaining: 1m 49s
1000:	learn: 0.2226592	test: 0.2275411	best: 0.2275411 (1000)	total: 19.5s	remaining: 1m 48s
1020:	learn: 0.2222232	test: 0.2271907	best: 0.2271907 (1020)	total: 19.9s	remaining: 1m 48s
1040:	learn: 0.2217870	test: 0.2268225	best: 0.2268225 (1040)	total: 20.3s	remaining: 1m 47s
1060:	learn: 0.2213575	test: 0.2264844	best: 0.2264844 (1060)	total: 20.7s	remaining: 1m 47s
1080:	learn: 0.2210281	test: 0.2262791	best: 0.2262791 (1080)	total: 21.1s	remaining: 1m 47s
1100:	learn: 0.2207237	test: 0.2260919	best: 0.2260919 (1100)	total: 21.5s	remaining: 1m 46s
1120:	learn: 0.2204197	test: 0.2258515	best: 0.2258515 (1120)	total: 21.9s	remaining: 1m 46s
1140:	learn: 0.2200948	test: 0.2256187	best: 0.2256187 (1140)	total: 22.3s	remaining: 1m 46s
1160:	learn: 0.2197679	test: 0.2253709	best: 0.2253709 (1160)	total: 22.7s	remaining: 1m 45s
1180:	learn: 0.2194899	test: 0.2252109	best: 0.2252109 (1180)	total: 23.1s	remaining: 1m 45s
1200:	learn: 0.2191858	test: 0.2250042	best: 0.2250042 (1200)	total: 23.5s	remaining: 1m 44s
1220:	learn: 0.2189001	test: 0.2247972	best: 0.2247972 (1220)	total: 23.9s	remaining: 1m 44s
1240:	learn: 0.2186074	test: 0.2245984	best: 0.2245984 (1240)	total: 24.2s	remaining: 1m 43s
1260:	learn: 0.2183333	test: 0.2243963	best: 0.2243963 (1260)	total: 24.6s	remaining: 1m 43s
1280:	learn: 0.2180354	test: 0.2242250	best: 0.2242250 (1280)	total: 25s	remaining: 1m 43s
1300:	learn: 0.2178043	test: 0.2240949	best: 0.2240949 (1300)	total: 25.4s	remaining: 1m 42s
1320:	learn: 0.2174627	test: 0.2238313	best: 0.2238313 (1320)	total: 25.8s	remaining: 1m 42s
1340:	learn: 0.2172230	test: 0.2236692	best: 0.2236692 (1340)	total: 26.1s	remaining: 1m 41s
1360:	learn: 0.2169852	test: 0.2235232	best: 0.2235232 (1360)	total: 26.5s	remaining: 1m 41s
1380:	learn: 0.2167472	test: 0.2233726	best: 0.2233726 (1380)	total: 26.9s	remaining: 1m 41s
1400:	learn: 0.2165138	test: 0.2232135	best: 0.2232135 (1400)	total: 27.3s	remaining: 1m 40s
1420:	learn: 0.2162308	test: 0.2230398	best: 0.2230398 (1420)	total: 27.7s	remaining: 1m 40s
1440:	learn: 0.2159864	test: 0.2228806	best: 0.2228806 (1440)	total: 28.1s	remaining: 1m 39s
1460:	learn: 0.2157695	test: 0.2227404	best: 0.2227404 (1460)	total: 28.5s	remaining: 1m 39s
1480:	learn: 0.2155097	test: 0.2225746	best: 0.2225735 (1479)	total: 28.9s	remaining: 1m 38s
1500:	learn: 0.2152490	test: 0.2224031	best: 0.2224031 (1500)	total: 29.2s	remaining: 1m 38s
1520:	learn: 0.2150023	test: 0.2222309	best: 0.2222309 (1520)	total: 29.6s	remaining: 1m 38s
1540:	learn: 0.2147455	test: 0.2220552	best: 0.2220552 (1540)	total: 30s	remaining: 1m 37s
1560:	learn: 0.2145150	test: 0.2219051	best: 0.2219051 (1560)	total: 30.4s	remaining: 1m 37s
1580:	learn: 0.2142904	test: 0.2217764	best: 0.2217764 (1580)	total: 30.8s	remaining: 1m 37s
1600:	learn: 0.2140716	test: 0.2216701	best: 0.2216701 (1600)	total: 31.2s	remaining: 1m 36s
1620:	learn: 0.2138400	test: 0.2215341	best: 0.2215267 (1619)	total: 31.6s	remaining: 1m 36s
1640:	learn: 0.2135912	test: 0.2213830	best: 0.2213830 (1640)	total: 32s	remaining: 1m 35s
1660:	learn: 0.2134020	test: 0.2212943	best: 0.2212943 (1660)	total: 32.4s	remaining: 1m 35s
1680:	learn: 0.2131824	test: 0.2211929	best: 0.2211929 (1680)	total: 32.8s	remaining: 1m 35s
1700:	learn: 0.2129700	test: 0.2210861	best: 0.2210861 (1700)	total: 33.1s	remaining: 1m 34s
1720:	learn: 0.2127676	test: 0.2209941	best: 0.2209941 (1720)	total: 33.6s	remaining: 1m 34s
1740:	learn: 0.2125714	test: 0.2208903	best: 0.2208903 (1740)	total: 33.9s	remaining: 1m 34s
1760:	learn: 0.2123784	test: 0.2207874	best: 0.2207874 (1760)	total: 34.3s	remaining: 1m 33s
1780:	learn: 0.2121685	test: 0.2206694	best: 0.2206694 (1780)	total: 34.7s	remaining: 1m 33s
1800:	learn: 0.2119773	test: 0.2205835	best: 0.2205835 (1800)	total: 35.1s	remaining: 1m 32s
1820:	learn: 0.2117906	test: 0.2205012	best: 0.2205012 (1820)	total: 35.5s	remaining: 1m 32s
1840:	learn: 0.2115794	test: 0.2203634	best: 0.2203633 (1838)	total: 35.9s	remaining: 1m 32s
1860:	learn: 0.2113724	test: 0.2202560	best: 0.2202560 (1860)	total: 36.3s	remaining: 1m 31s
1880:	learn: 0.2112030	test: 0.2201762	best: 0.2201762 (1880)	total: 36.7s	remaining: 1m 31s
1900:	learn: 0.2110130	test: 0.2200760	best: 0.2200760 (1900)	total: 37.1s	remaining: 1m 30s
1920:	learn: 0.2108523	test: 0.2199974	best: 0.2199974 (1920)	total: 37.5s	remaining: 1m 30s
1940:	learn: 0.2106221	test: 0.2198307	best: 0.2198307 (1940)	total: 37.9s	remaining: 1m 30s
1960:	learn: 0.2104267	test: 0.2197408	best: 0.2197408 (1960)	total: 38.3s	remaining: 1m 29s
1980:	learn: 0.2101908	test: 0.2195878	best: 0.2195878 (1980)	total: 38.7s	remaining: 1m 29s
2000:	learn: 0.2099987	test: 0.2194671	best: 0.2194649 (1999)	total: 39.1s	remaining: 1m 29s
2020:	learn: 0.2098392	test: 0.2193925	best: 0.2193925 (2020)	total: 39.5s	remaining: 1m 28s
2040:	learn: 0.2096809	test: 0.2193281	best: 0.2193281 (2040)	total: 39.9s	remaining: 1m 28s
2060:	learn: 0.2094890	test: 0.2192132	best: 0.2192132 (2059)	total: 40.3s	remaining: 1m 27s
2080:	learn: 0.2093010	test: 0.2190940	best: 0.2190940 (2080)	total: 40.7s	remaining: 1m 27s
2100:	learn: 0.2091078	test: 0.2189820	best: 0.2189820 (2100)	total: 41.1s	remaining: 1m 27s
2120:	learn: 0.2089479	test: 0.2188970	best: 0.2188957 (2119)	total: 41.5s	remaining: 1m 26s
2140:	learn: 0.2087732	test: 0.2188082	best: 0.2188082 (2140)	total: 41.9s	remaining: 1m 26s
2160:	learn: 0.2085994	test: 0.2187144	best: 0.2187144 (2160)	total: 42.3s	remaining: 1m 26s
2180:	learn: 0.2084219	test: 0.2186217	best: 0.2186217 (2180)	total: 42.6s	remaining: 1m 25s
2200:	learn: 0.2082436	test: 0.2185302	best: 0.2185302 (2200)	total: 43s	remaining: 1m 25s
2220:	learn: 0.2080825	test: 0.2184561	best: 0.2184561 (2220)	total: 43.4s	remaining: 1m 24s
2240:	learn: 0.2079304	test: 0.2183957	best: 0.2183957 (2240)	total: 43.8s	remaining: 1m 24s
2260:	learn: 0.2077854	test: 0.2183418	best: 0.2183418 (2260)	total: 44.2s	remaining: 1m 24s
2280:	learn: 0.2076199	test: 0.2182534	best: 0.2182534 (2280)	total: 44.6s	remaining: 1m 23s
2300:	learn: 0.2074689	test: 0.2182061	best: 0.2182061 (2300)	total: 45s	remaining: 1m 23s
2320:	learn: 0.2072890	test: 0.2181257	best: 0.2181257 (2320)	total: 45.4s	remaining: 1m 22s
2340:	learn: 0.2071096	test: 0.2180255	best: 0.2180255 (2340)	total: 45.8s	remaining: 1m 22s
2360:	learn: 0.2069813	test: 0.2179730	best: 0.2179724 (2359)	total: 46.2s	remaining: 1m 22s
2380:	learn: 0.2067813	test: 0.2178495	best: 0.2178495 (2380)	total: 46.6s	remaining: 1m 21s
2400:	learn: 0.2066510	test: 0.2177892	best: 0.2177892 (2400)	total: 47s	remaining: 1m 21s
2420:	learn: 0.2064979	test: 0.2177249	best: 0.2177249 (2420)	total: 47.4s	remaining: 1m 21s
2440:	learn: 0.2063330	test: 0.2176516	best: 0.2176516 (2440)	total: 47.7s	remaining: 1m 20s
2460:	learn: 0.2061991	test: 0.2176140	best: 0.2176133 (2459)	total: 48.1s	remaining: 1m 20s
2480:	learn: 0.2060524	test: 0.2175469	best: 0.2175466 (2479)	total: 48.5s	remaining: 1m 19s
2500:	learn: 0.2058765	test: 0.2174599	best: 0.2174599 (2500)	total: 48.9s	remaining: 1m 19s
2520:	learn: 0.2057077	test: 0.2173838	best: 0.2173838 (2520)	total: 49.3s	remaining: 1m 19s
2540:	learn: 0.2055404	test: 0.2172893	best: 0.2172890 (2539)	total: 49.7s	remaining: 1m 18s
2560:	learn: 0.2053712	test: 0.2172103	best: 0.2172103 (2560)	total: 50.1s	remaining: 1m 18s
2580:	learn: 0.2052252	test: 0.2171389	best: 0.2171389 (2580)	total: 50.5s	remaining: 1m 17s
2600:	learn: 0.2050806	test: 0.2170898	best: 0.2170898 (2600)	total: 50.9s	remaining: 1m 17s
2620:	learn: 0.2049542	test: 0.2170484	best: 0.2170472 (2619)	total: 51.3s	remaining: 1m 17s
2640:	learn: 0.2048189	test: 0.2169788	best: 0.2169788 (2640)	total: 51.7s	remaining: 1m 16s
2660:	learn: 0.2046755	test: 0.2169656	best: 0.2169621 (2643)	total: 52.1s	remaining: 1m 16s
2680:	learn: 0.2045192	test: 0.2169003	best: 0.2169003 (2680)	total: 52.5s	remaining: 1m 15s
2700:	learn: 0.2043938	test: 0.2168608	best: 0.2168578 (2698)	total: 52.9s	remaining: 1m 15s
2720:	learn: 0.2042784	test: 0.2168110	best: 0.2168110 (2720)	total: 53.3s	remaining: 1m 15s
2740:	learn: 0.2041511	test: 0.2167619	best: 0.2167619 (2740)	total: 53.7s	remaining: 1m 14s
2760:	learn: 0.2040089	test: 0.2166885	best: 0.2166885 (2760)	total: 54.1s	remaining: 1m 14s
2780:	learn: 0.2038500	test: 0.2166074	best: 0.2166074 (2780)	total: 54.5s	remaining: 1m 14s
2800:	learn: 0.2036620	test: 0.2164885	best: 0.2164885 (2800)	total: 54.9s	remaining: 1m 13s
2820:	learn: 0.2035305	test: 0.2164243	best: 0.2164243 (2820)	total: 55.3s	remaining: 1m 13s
2840:	learn: 0.2033886	test: 0.2163480	best: 0.2163472 (2839)	total: 55.7s	remaining: 1m 12s
2860:	learn: 0.2032580	test: 0.2163051	best: 0.2163022 (2858)	total: 56.1s	remaining: 1m 12s
2880:	learn: 0.2031317	test: 0.2162727	best: 0.2162727 (2880)	total: 56.5s	remaining: 1m 12s
2900:	learn: 0.2029975	test: 0.2162176	best: 0.2162176 (2900)	total: 56.9s	remaining: 1m 11s
2920:	learn: 0.2028419	test: 0.2161649	best: 0.2161649 (2920)	total: 57.3s	remaining: 1m 11s
2940:	learn: 0.2027146	test: 0.2161321	best: 0.2161321 (2940)	total: 57.7s	remaining: 1m 10s
2960:	learn: 0.2025905	test: 0.2160871	best: 0.2160871 (2960)	total: 58.1s	remaining: 1m 10s
2980:	learn: 0.2024686	test: 0.2160475	best: 0.2160475 (2980)	total: 58.4s	remaining: 1m 10s
3000:	learn: 0.2023282	test: 0.2159996	best: 0.2159996 (3000)	total: 58.8s	remaining: 1m 9s
3020:	learn: 0.2022056	test: 0.2159490	best: 0.2159490 (3020)	total: 59.2s	remaining: 1m 9s
3040:	learn: 0.2020696	test: 0.2158999	best: 0.2158983 (3037)	total: 59.6s	remaining: 1m 9s
3060:	learn: 0.2019329	test: 0.2158659	best: 0.2158659 (3060)	total: 1m	remaining: 1m 8s
3080:	learn: 0.2018323	test: 0.2158479	best: 0.2158434 (3071)	total: 1m	remaining: 1m 8s
3100:	learn: 0.2016913	test: 0.2157844	best: 0.2157844 (3100)	total: 1m	remaining: 1m 7s
3120:	learn: 0.2015786	test: 0.2157535	best: 0.2157535 (3120)	total: 1m 1s	remaining: 1m 7s
3140:	learn: 0.2014459	test: 0.2157014	best: 0.2157014 (3140)	total: 1m 1s	remaining: 1m 7s
3160:	learn: 0.2013248	test: 0.2156514	best: 0.2156514 (3160)	total: 1m 2s	remaining: 1m 6s
3180:	learn: 0.2011960	test: 0.2155940	best: 0.2155940 (3180)	total: 1m 2s	remaining: 1m 6s
3200:	learn: 0.2010584	test: 0.2155354	best: 0.2155345 (3197)	total: 1m 2s	remaining: 1m 5s
3220:	learn: 0.2009214	test: 0.2154918	best: 0.2154918 (3220)	total: 1m 3s	remaining: 1m 5s
3240:	learn: 0.2007940	test: 0.2154203	best: 0.2154196 (3238)	total: 1m 3s	remaining: 1m 5s
3260:	learn: 0.2006617	test: 0.2153701	best: 0.2153696 (3259)	total: 1m 4s	remaining: 1m 4s
3280:	learn: 0.2005299	test: 0.2153204	best: 0.2153169 (3279)	total: 1m 4s	remaining: 1m 4s
3300:	learn: 0.2004287	test: 0.2152803	best: 0.2152803 (3298)	total: 1m 4s	remaining: 1m 4s
3320:	learn: 0.2002947	test: 0.2152208	best: 0.2152208 (3320)	total: 1m 5s	remaining: 1m 3s
3340:	learn: 0.2001656	test: 0.2151648	best: 0.2151635 (3339)	total: 1m 5s	remaining: 1m 3s
3360:	learn: 0.2000370	test: 0.2151356	best: 0.2151356 (3360)	total: 1m 6s	remaining: 1m 2s
3380:	learn: 0.1999023	test: 0.2150995	best: 0.2150995 (3380)	total: 1m 6s	remaining: 1m 2s
3400:	learn: 0.1997858	test: 0.2150626	best: 0.2150612 (3398)	total: 1m 6s	remaining: 1m 2s
3420:	learn: 0.1996554	test: 0.2150392	best: 0.2150392 (3420)	total: 1m 7s	remaining: 1m 1s
3440:	learn: 0.1995430	test: 0.2149860	best: 0.2149860 (3440)	total: 1m 7s	remaining: 1m 1s
3460:	learn: 0.1994255	test: 0.2149134	best: 0.2149134 (3460)	total: 1m 8s	remaining: 1m 1s
3480:	learn: 0.1992994	test: 0.2148602	best: 0.2148602 (3480)	total: 1m 8s	remaining: 1m
3500:	learn: 0.1991661	test: 0.2148091	best: 0.2148057 (3499)	total: 1m 9s	remaining: 1m
3520:	learn: 0.1990379	test: 0.2147608	best: 0.2147608 (3520)	total: 1m 9s	remaining: 59.9s
3540:	learn: 0.1989169	test: 0.2147139	best: 0.2147139 (3540)	total: 1m 9s	remaining: 59.6s
3560:	learn: 0.1987972	test: 0.2146839	best: 0.2146813 (3559)	total: 1m 10s	remaining: 59.2s
3580:	learn: 0.1986635	test: 0.2146176	best: 0.2146162 (3576)	total: 1m 10s	remaining: 58.8s
3600:	learn: 0.1985465	test: 0.2145690	best: 0.2145690 (3600)	total: 1m 11s	remaining: 58.4s
3620:	learn: 0.1984252	test: 0.2145259	best: 0.2145259 (3620)	total: 1m 11s	remaining: 58s
3640:	learn: 0.1983078	test: 0.2144856	best: 0.2144856 (3640)	total: 1m 11s	remaining: 57.6s
3660:	learn: 0.1981825	test: 0.2144467	best: 0.2144467 (3660)	total: 1m 12s	remaining: 57.3s
3680:	learn: 0.1980631	test: 0.2144211	best: 0.2144211 (3680)	total: 1m 12s	remaining: 56.9s
3700:	learn: 0.1979566	test: 0.2143797	best: 0.2143797 (3700)	total: 1m 13s	remaining: 56.5s
3720:	learn: 0.1978505	test: 0.2143452	best: 0.2143452 (3720)	total: 1m 13s	remaining: 56.1s
3740:	learn: 0.1977319	test: 0.2143007	best: 0.2143007 (3740)	total: 1m 13s	remaining: 55.7s
3760:	learn: 0.1976247	test: 0.2142660	best: 0.2142660 (3760)	total: 1m 14s	remaining: 55.3s
3780:	learn: 0.1975317	test: 0.2142341	best: 0.2142316 (3777)	total: 1m 14s	remaining: 54.9s
3800:	learn: 0.1974358	test: 0.2142075	best: 0.2142075 (3800)	total: 1m 15s	remaining: 54.6s
3820:	learn: 0.1973199	test: 0.2141747	best: 0.2141736 (3817)	total: 1m 15s	remaining: 54.2s
3840:	learn: 0.1972023	test: 0.2141441	best: 0.2141426 (3839)	total: 1m 15s	remaining: 53.8s
3860:	learn: 0.1970992	test: 0.2141141	best: 0.2141124 (3858)	total: 1m 16s	remaining: 53.4s
3880:	learn: 0.1969751	test: 0.2140611	best: 0.2140611 (3880)	total: 1m 16s	remaining: 53s
3900:	learn: 0.1968904	test: 0.2140325	best: 0.2140321 (3899)	total: 1m 17s	remaining: 52.7s
3920:	learn: 0.1967697	test: 0.2140114	best: 0.2140114 (3920)	total: 1m 17s	remaining: 52.3s
3940:	learn: 0.1966282	test: 0.2139537	best: 0.2139537 (3940)	total: 1m 18s	remaining: 51.9s
3960:	learn: 0.1965139	test: 0.2139036	best: 0.2139036 (3960)	total: 1m 18s	remaining: 51.5s
3980:	learn: 0.1963832	test: 0.2138796	best: 0.2138796 (3980)	total: 1m 18s	remaining: 51.1s
4000:	learn: 0.1962786	test: 0.2138424	best: 0.2138424 (4000)	total: 1m 19s	remaining: 50.7s
4020:	learn: 0.1961795	test: 0.2138048	best: 0.2138046 (4019)	total: 1m 19s	remaining: 50.3s
4040:	learn: 0.1960415	test: 0.2137324	best: 0.2137324 (4040)	total: 1m 20s	remaining: 49.9s
4060:	learn: 0.1959166	test: 0.2136950	best: 0.2136950 (4060)	total: 1m 20s	remaining: 49.6s
4080:	learn: 0.1958033	test: 0.2136554	best: 0.2136545 (4079)	total: 1m 20s	remaining: 49.2s
4100:	learn: 0.1956882	test: 0.2136247	best: 0.2136215 (4097)	total: 1m 21s	remaining: 48.8s
4120:	learn: 0.1955853	test: 0.2136009	best: 0.2136000 (4118)	total: 1m 21s	remaining: 48.4s
4140:	learn: 0.1954731	test: 0.2135641	best: 0.2135633 (4136)	total: 1m 22s	remaining: 48s
4160:	learn: 0.1953562	test: 0.2135366	best: 0.2135360 (4159)	total: 1m 22s	remaining: 47.6s
4180:	learn: 0.1952558	test: 0.2135307	best: 0.2135277 (4175)	total: 1m 22s	remaining: 47.2s
4200:	learn: 0.1951455	test: 0.2135061	best: 0.2135061 (4200)	total: 1m 23s	remaining: 46.8s
4220:	learn: 0.1950038	test: 0.2134553	best: 0.2134546 (4219)	total: 1m 23s	remaining: 46.4s
4240:	learn: 0.1948857	test: 0.2134078	best: 0.2134071 (4238)	total: 1m 24s	remaining: 46.1s
4260:	learn: 0.1947826	test: 0.2133936	best: 0.2133925 (4258)	total: 1m 24s	remaining: 45.7s
4280:	learn: 0.1946827	test: 0.2133588	best: 0.2133588 (4280)	total: 1m 24s	remaining: 45.3s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645499	test: 0.6645863	best: 0.6645863 (0)	total: 4.79ms	remaining: 4.79ms
1:	learn: 0.6386830	test: 0.6387550	best: 0.6387550 (1)	total: 8.96ms	remaining: 0us
bestTest = 0.6387549658
bestIteration = 1
0:	learn: 0.6399846	test: 0.6397901	best: 0.6397901 (0)	total: 18.7ms	remaining: 2m 4s
20:	learn: 0.3356801	test: 0.3351190	best: 0.3351190 (20)	total: 423ms	remaining: 2m 13s
40:	learn: 0.3028136	test: 0.3021785	best: 0.3021785 (40)	total: 815ms	remaining: 2m 11s
60:	learn: 0.2893060	test: 0.2883944	best: 0.2883944 (60)	total: 1.22s	remaining: 2m 11s
80:	learn: 0.2803200	test: 0.2794163	best: 0.2794163 (80)	total: 1.6s	remaining: 2m 9s
100:	learn: 0.2738969	test: 0.2726600	best: 0.2726600 (100)	total: 1.98s	remaining: 2m 8s
120:	learn: 0.2700468	test: 0.2687849	best: 0.2687849 (120)	total: 2.38s	remaining: 2m 8s
140:	learn: 0.2661014	test: 0.2648459	best: 0.2648459 (140)	total: 2.77s	remaining: 2m 8s
160:	learn: 0.2624533	test: 0.2611544	best: 0.2611544 (160)	total: 3.17s	remaining: 2m 7s
180:	learn: 0.2597410	test: 0.2585581	best: 0.2585581 (180)	total: 3.56s	remaining: 2m 7s
200:	learn: 0.2570735	test: 0.2559011	best: 0.2559011 (200)	total: 3.95s	remaining: 2m 6s
220:	learn: 0.2546526	test: 0.2535017	best: 0.2535017 (220)	total: 4.33s	remaining: 2m 5s
240:	learn: 0.2525006	test: 0.2514203	best: 0.2514203 (240)	total: 4.72s	remaining: 2m 5s
260:	learn: 0.2505717	test: 0.2495055	best: 0.2495055 (260)	total: 5.12s	remaining: 2m 5s
280:	learn: 0.2490416	test: 0.2480868	best: 0.2480868 (280)	total: 5.52s	remaining: 2m 5s
300:	learn: 0.2476195	test: 0.2467207	best: 0.2467207 (300)	total: 5.9s	remaining: 2m 4s
320:	learn: 0.2463729	test: 0.2454864	best: 0.2454864 (320)	total: 6.26s	remaining: 2m 3s
340:	learn: 0.2450114	test: 0.2442010	best: 0.2442010 (340)	total: 6.64s	remaining: 2m 2s
360:	learn: 0.2437956	test: 0.2430506	best: 0.2430506 (360)	total: 7.02s	remaining: 2m 2s
380:	learn: 0.2425683	test: 0.2418659	best: 0.2418659 (380)	total: 7.39s	remaining: 2m 1s
400:	learn: 0.2412411	test: 0.2405258	best: 0.2405258 (400)	total: 7.78s	remaining: 2m 1s
420:	learn: 0.2399577	test: 0.2392820	best: 0.2392820 (420)	total: 8.15s	remaining: 2m
440:	learn: 0.2390528	test: 0.2384531	best: 0.2384531 (440)	total: 8.52s	remaining: 1m 59s
460:	learn: 0.2381581	test: 0.2376306	best: 0.2376306 (460)	total: 8.89s	remaining: 1m 59s
480:	learn: 0.2371607	test: 0.2366968	best: 0.2366968 (480)	total: 9.27s	remaining: 1m 58s
500:	learn: 0.2363925	test: 0.2359561	best: 0.2359561 (500)	total: 9.63s	remaining: 1m 58s
520:	learn: 0.2357071	test: 0.2353290	best: 0.2353290 (520)	total: 10s	remaining: 1m 57s
540:	learn: 0.2350784	test: 0.2347834	best: 0.2347834 (540)	total: 10.4s	remaining: 1m 56s
560:	learn: 0.2343029	test: 0.2340523	best: 0.2340523 (560)	total: 10.7s	remaining: 1m 56s
580:	learn: 0.2335700	test: 0.2334513	best: 0.2334513 (580)	total: 11.1s	remaining: 1m 55s
600:	learn: 0.2330135	test: 0.2329954	best: 0.2329954 (600)	total: 11.5s	remaining: 1m 55s
620:	learn: 0.2324612	test: 0.2325084	best: 0.2325084 (620)	total: 11.8s	remaining: 1m 55s
640:	learn: 0.2318044	test: 0.2319340	best: 0.2319340 (640)	total: 12.2s	remaining: 1m 54s
660:	learn: 0.2310865	test: 0.2313041	best: 0.2313041 (660)	total: 12.6s	remaining: 1m 54s
680:	learn: 0.2305257	test: 0.2308380	best: 0.2308380 (680)	total: 13s	remaining: 1m 53s
700:	learn: 0.2300192	test: 0.2303742	best: 0.2303742 (700)	total: 13.3s	remaining: 1m 53s
720:	learn: 0.2295937	test: 0.2300374	best: 0.2300374 (720)	total: 13.7s	remaining: 1m 52s
740:	learn: 0.2290285	test: 0.2295342	best: 0.2295342 (740)	total: 14.1s	remaining: 1m 52s
760:	learn: 0.2284334	test: 0.2290176	best: 0.2290176 (760)	total: 14.4s	remaining: 1m 51s
780:	learn: 0.2279461	test: 0.2286511	best: 0.2286511 (780)	total: 14.8s	remaining: 1m 51s
800:	learn: 0.2274071	test: 0.2281933	best: 0.2281933 (800)	total: 15.2s	remaining: 1m 50s
820:	learn: 0.2269906	test: 0.2279039	best: 0.2279039 (820)	total: 15.5s	remaining: 1m 50s
840:	learn: 0.2265624	test: 0.2275900	best: 0.2275900 (840)	total: 15.9s	remaining: 1m 49s
860:	learn: 0.2261164	test: 0.2272392	best: 0.2272392 (860)	total: 16.3s	remaining: 1m 49s
880:	learn: 0.2257131	test: 0.2269263	best: 0.2269263 (880)	total: 16.6s	remaining: 1m 48s
900:	learn: 0.2253012	test: 0.2266423	best: 0.2266423 (900)	total: 17s	remaining: 1m 48s
920:	learn: 0.2248590	test: 0.2263004	best: 0.2263004 (920)	total: 17.4s	remaining: 1m 47s
940:	learn: 0.2243697	test: 0.2258977	best: 0.2258977 (940)	total: 17.7s	remaining: 1m 47s
960:	learn: 0.2239635	test: 0.2256130	best: 0.2256130 (960)	total: 18.1s	remaining: 1m 47s
980:	learn: 0.2235300	test: 0.2252849	best: 0.2252849 (980)	total: 18.5s	remaining: 1m 46s
1000:	learn: 0.2231632	test: 0.2249859	best: 0.2249859 (1000)	total: 18.8s	remaining: 1m 46s
1020:	learn: 0.2227861	test: 0.2246836	best: 0.2246836 (1020)	total: 19.2s	remaining: 1m 45s
1040:	learn: 0.2224009	test: 0.2243603	best: 0.2243603 (1040)	total: 19.6s	remaining: 1m 45s
1060:	learn: 0.2220913	test: 0.2241586	best: 0.2241586 (1060)	total: 19.9s	remaining: 1m 44s
1080:	learn: 0.2217554	test: 0.2239439	best: 0.2239439 (1080)	total: 20.3s	remaining: 1m 44s
1100:	learn: 0.2214576	test: 0.2237288	best: 0.2237288 (1100)	total: 20.7s	remaining: 1m 44s
1120:	learn: 0.2211529	test: 0.2235294	best: 0.2235294 (1120)	total: 21s	remaining: 1m 43s
1140:	learn: 0.2208409	test: 0.2233471	best: 0.2233471 (1140)	total: 21.4s	remaining: 1m 43s
1160:	learn: 0.2205411	test: 0.2231375	best: 0.2231375 (1160)	total: 21.8s	remaining: 1m 42s
1180:	learn: 0.2202821	test: 0.2229699	best: 0.2229699 (1180)	total: 22.1s	remaining: 1m 42s
1200:	learn: 0.2198824	test: 0.2226765	best: 0.2226765 (1200)	total: 22.5s	remaining: 1m 42s
1220:	learn: 0.2196181	test: 0.2225010	best: 0.2225010 (1220)	total: 22.9s	remaining: 1m 41s
1240:	learn: 0.2192984	test: 0.2222659	best: 0.2222659 (1240)	total: 23.2s	remaining: 1m 41s
1260:	learn: 0.2190658	test: 0.2221250	best: 0.2221250 (1260)	total: 23.6s	remaining: 1m 40s
1280:	learn: 0.2187401	test: 0.2219147	best: 0.2219147 (1280)	total: 24s	remaining: 1m 40s
1300:	learn: 0.2183834	test: 0.2216297	best: 0.2216297 (1300)	total: 24.4s	remaining: 1m 40s
1320:	learn: 0.2181044	test: 0.2214261	best: 0.2214261 (1320)	total: 24.7s	remaining: 1m 39s
1340:	learn: 0.2178816	test: 0.2212944	best: 0.2212944 (1340)	total: 25.1s	remaining: 1m 39s
1360:	learn: 0.2176372	test: 0.2211157	best: 0.2211157 (1360)	total: 25.5s	remaining: 1m 38s
1380:	learn: 0.2174106	test: 0.2209659	best: 0.2209659 (1380)	total: 25.9s	remaining: 1m 38s
1400:	learn: 0.2170925	test: 0.2207323	best: 0.2207323 (1400)	total: 26.2s	remaining: 1m 38s
1420:	learn: 0.2168673	test: 0.2206231	best: 0.2206231 (1420)	total: 26.6s	remaining: 1m 37s
1440:	learn: 0.2166357	test: 0.2204552	best: 0.2204552 (1440)	total: 27s	remaining: 1m 37s
1460:	learn: 0.2164062	test: 0.2203345	best: 0.2203340 (1459)	total: 27.3s	remaining: 1m 37s
1480:	learn: 0.2161748	test: 0.2201939	best: 0.2201939 (1480)	total: 27.7s	remaining: 1m 36s
1500:	learn: 0.2159363	test: 0.2200615	best: 0.2200615 (1500)	total: 28.1s	remaining: 1m 36s
1520:	learn: 0.2156901	test: 0.2199252	best: 0.2199252 (1520)	total: 28.5s	remaining: 1m 35s
1540:	learn: 0.2154300	test: 0.2197312	best: 0.2197312 (1540)	total: 28.9s	remaining: 1m 35s
1560:	learn: 0.2151337	test: 0.2194993	best: 0.2194993 (1560)	total: 29.2s	remaining: 1m 35s
1580:	learn: 0.2149661	test: 0.2194190	best: 0.2194190 (1580)	total: 29.6s	remaining: 1m 34s
1600:	learn: 0.2147795	test: 0.2193175	best: 0.2193175 (1600)	total: 30s	remaining: 1m 34s
1620:	learn: 0.2145493	test: 0.2191969	best: 0.2191969 (1620)	total: 30.4s	remaining: 1m 34s
1640:	learn: 0.2142966	test: 0.2190229	best: 0.2190229 (1640)	total: 30.7s	remaining: 1m 33s
1660:	learn: 0.2140648	test: 0.2188942	best: 0.2188942 (1660)	total: 31.1s	remaining: 1m 33s
1680:	learn: 0.2138402	test: 0.2187696	best: 0.2187696 (1680)	total: 31.4s	remaining: 1m 32s
1700:	learn: 0.2136400	test: 0.2186942	best: 0.2186942 (1700)	total: 31.8s	remaining: 1m 32s
1720:	learn: 0.2134272	test: 0.2185639	best: 0.2185639 (1720)	total: 32.2s	remaining: 1m 32s
1740:	learn: 0.2132173	test: 0.2184108	best: 0.2184108 (1740)	total: 32.6s	remaining: 1m 31s
1760:	learn: 0.2129606	test: 0.2182485	best: 0.2182485 (1760)	total: 32.9s	remaining: 1m 31s
1780:	learn: 0.2127461	test: 0.2181155	best: 0.2181155 (1780)	total: 33.3s	remaining: 1m 31s
1800:	learn: 0.2125299	test: 0.2179752	best: 0.2179752 (1800)	total: 33.7s	remaining: 1m 30s
1820:	learn: 0.2123439	test: 0.2178652	best: 0.2178652 (1820)	total: 34s	remaining: 1m 30s
1840:	learn: 0.2121760	test: 0.2177912	best: 0.2177912 (1840)	total: 34.4s	remaining: 1m 29s
1860:	learn: 0.2119509	test: 0.2176656	best: 0.2176656 (1860)	total: 34.8s	remaining: 1m 29s
1880:	learn: 0.2117854	test: 0.2175960	best: 0.2175960 (1880)	total: 35.1s	remaining: 1m 29s
1900:	learn: 0.2115905	test: 0.2174763	best: 0.2174763 (1900)	total: 35.5s	remaining: 1m 28s
1920:	learn: 0.2113851	test: 0.2173639	best: 0.2173639 (1920)	total: 35.9s	remaining: 1m 28s
1940:	learn: 0.2112023	test: 0.2172577	best: 0.2172577 (1940)	total: 36.3s	remaining: 1m 27s
1960:	learn: 0.2110277	test: 0.2171885	best: 0.2171885 (1960)	total: 36.6s	remaining: 1m 27s
1980:	learn: 0.2108302	test: 0.2170727	best: 0.2170727 (1980)	total: 37s	remaining: 1m 27s
2000:	learn: 0.2106198	test: 0.2169419	best: 0.2169419 (2000)	total: 37.4s	remaining: 1m 26s
2020:	learn: 0.2104359	test: 0.2168370	best: 0.2168370 (2020)	total: 37.7s	remaining: 1m 26s
2040:	learn: 0.2102590	test: 0.2167274	best: 0.2167274 (2040)	total: 38.1s	remaining: 1m 26s
2060:	learn: 0.2100600	test: 0.2166160	best: 0.2166150 (2059)	total: 38.5s	remaining: 1m 25s
2080:	learn: 0.2098410	test: 0.2164819	best: 0.2164819 (2080)	total: 38.9s	remaining: 1m 25s
2100:	learn: 0.2096324	test: 0.2163638	best: 0.2163638 (2100)	total: 39.3s	remaining: 1m 24s
2120:	learn: 0.2094434	test: 0.2162930	best: 0.2162930 (2120)	total: 39.6s	remaining: 1m 24s
2140:	learn: 0.2092549	test: 0.2161637	best: 0.2161637 (2140)	total: 40s	remaining: 1m 24s
2160:	learn: 0.2091018	test: 0.2160982	best: 0.2160982 (2160)	total: 40.4s	remaining: 1m 23s
2180:	learn: 0.2089147	test: 0.2160082	best: 0.2160082 (2180)	total: 40.7s	remaining: 1m 23s
2200:	learn: 0.2087579	test: 0.2159442	best: 0.2159442 (2200)	total: 41.1s	remaining: 1m 23s
2220:	learn: 0.2086000	test: 0.2158881	best: 0.2158881 (2220)	total: 41.5s	remaining: 1m 22s
2240:	learn: 0.2084385	test: 0.2158206	best: 0.2158206 (2240)	total: 41.8s	remaining: 1m 22s
2260:	learn: 0.2082602	test: 0.2157492	best: 0.2157477 (2259)	total: 42.2s	remaining: 1m 21s
2280:	learn: 0.2081055	test: 0.2156764	best: 0.2156764 (2280)	total: 42.6s	remaining: 1m 21s
2300:	learn: 0.2079293	test: 0.2155801	best: 0.2155801 (2300)	total: 42.9s	remaining: 1m 21s
2320:	learn: 0.2077322	test: 0.2154624	best: 0.2154624 (2320)	total: 43.3s	remaining: 1m 20s
2340:	learn: 0.2075682	test: 0.2153855	best: 0.2153855 (2340)	total: 43.7s	remaining: 1m 20s
2360:	learn: 0.2073967	test: 0.2153052	best: 0.2153052 (2360)	total: 44s	remaining: 1m 19s
2380:	learn: 0.2071645	test: 0.2151550	best: 0.2151550 (2380)	total: 44.4s	remaining: 1m 19s
2400:	learn: 0.2069997	test: 0.2150958	best: 0.2150958 (2400)	total: 44.8s	remaining: 1m 19s
2420:	learn: 0.2068540	test: 0.2150275	best: 0.2150275 (2420)	total: 45.2s	remaining: 1m 18s
2440:	learn: 0.2066926	test: 0.2149687	best: 0.2149687 (2440)	total: 45.5s	remaining: 1m 18s
2460:	learn: 0.2065639	test: 0.2149197	best: 0.2149197 (2460)	total: 45.9s	remaining: 1m 18s
2480:	learn: 0.2064012	test: 0.2148409	best: 0.2148409 (2480)	total: 46.3s	remaining: 1m 17s
2500:	learn: 0.2062033	test: 0.2147454	best: 0.2147454 (2500)	total: 46.7s	remaining: 1m 17s
2520:	learn: 0.2060571	test: 0.2146859	best: 0.2146859 (2520)	total: 47s	remaining: 1m 16s
2540:	learn: 0.2058967	test: 0.2146215	best: 0.2146203 (2539)	total: 47.4s	remaining: 1m 16s
2560:	learn: 0.2057585	test: 0.2145843	best: 0.2145843 (2560)	total: 47.8s	remaining: 1m 16s
2580:	learn: 0.2056012	test: 0.2144990	best: 0.2144990 (2580)	total: 48.1s	remaining: 1m 15s
2600:	learn: 0.2054661	test: 0.2144458	best: 0.2144431 (2599)	total: 48.5s	remaining: 1m 15s
2620:	learn: 0.2052953	test: 0.2143825	best: 0.2143825 (2620)	total: 48.8s	remaining: 1m 15s
2640:	learn: 0.2051370	test: 0.2142887	best: 0.2142887 (2640)	total: 49.2s	remaining: 1m 14s
2660:	learn: 0.2050035	test: 0.2142404	best: 0.2142404 (2660)	total: 49.6s	remaining: 1m 14s
2680:	learn: 0.2048735	test: 0.2141729	best: 0.2141729 (2680)	total: 50s	remaining: 1m 13s
2700:	learn: 0.2047371	test: 0.2141259	best: 0.2141213 (2699)	total: 50.4s	remaining: 1m 13s
2720:	learn: 0.2045979	test: 0.2140508	best: 0.2140508 (2720)	total: 50.7s	remaining: 1m 13s
2740:	learn: 0.2044422	test: 0.2139810	best: 0.2139810 (2740)	total: 51.1s	remaining: 1m 12s
2760:	learn: 0.2042727	test: 0.2139166	best: 0.2139166 (2760)	total: 51.5s	remaining: 1m 12s
2780:	learn: 0.2041586	test: 0.2138779	best: 0.2138779 (2780)	total: 51.9s	remaining: 1m 12s
2800:	learn: 0.2040295	test: 0.2138289	best: 0.2138285 (2798)	total: 52.2s	remaining: 1m 11s
2820:	learn: 0.2038967	test: 0.2137813	best: 0.2137813 (2820)	total: 52.6s	remaining: 1m 11s
2840:	learn: 0.2037257	test: 0.2136702	best: 0.2136702 (2840)	total: 53s	remaining: 1m 11s
2860:	learn: 0.2035783	test: 0.2135998	best: 0.2135998 (2860)	total: 53.4s	remaining: 1m 10s
2880:	learn: 0.2034521	test: 0.2135469	best: 0.2135469 (2880)	total: 53.8s	remaining: 1m 10s
2900:	learn: 0.2032973	test: 0.2134983	best: 0.2134983 (2900)	total: 54.1s	remaining: 1m 9s
2920:	learn: 0.2031703	test: 0.2134467	best: 0.2134467 (2920)	total: 54.5s	remaining: 1m 9s
2940:	learn: 0.2030288	test: 0.2133767	best: 0.2133767 (2940)	total: 54.9s	remaining: 1m 9s
2960:	learn: 0.2029021	test: 0.2133274	best: 0.2133274 (2960)	total: 55.3s	remaining: 1m 8s
2980:	learn: 0.2027555	test: 0.2132540	best: 0.2132540 (2980)	total: 55.7s	remaining: 1m 8s
3000:	learn: 0.2026408	test: 0.2132176	best: 0.2132153 (2999)	total: 56.1s	remaining: 1m 8s
3020:	learn: 0.2024988	test: 0.2131647	best: 0.2131647 (3020)	total: 56.4s	remaining: 1m 7s
3040:	learn: 0.2023862	test: 0.2131213	best: 0.2131213 (3040)	total: 56.8s	remaining: 1m 7s
3060:	learn: 0.2022506	test: 0.2130694	best: 0.2130694 (3060)	total: 57.2s	remaining: 1m 7s
3080:	learn: 0.2021174	test: 0.2130183	best: 0.2130183 (3080)	total: 57.7s	remaining: 1m 6s
3100:	learn: 0.2019960	test: 0.2129859	best: 0.2129850 (3099)	total: 58s	remaining: 1m 6s
3120:	learn: 0.2018671	test: 0.2129186	best: 0.2129186 (3120)	total: 58.4s	remaining: 1m 6s
3140:	learn: 0.2017513	test: 0.2128843	best: 0.2128843 (3140)	total: 58.8s	remaining: 1m 5s
3160:	learn: 0.2016163	test: 0.2128382	best: 0.2128382 (3160)	total: 59.2s	remaining: 1m 5s
3180:	learn: 0.2014969	test: 0.2127984	best: 0.2127984 (3180)	total: 59.6s	remaining: 1m 4s
3200:	learn: 0.2013664	test: 0.2127529	best: 0.2127519 (3195)	total: 60s	remaining: 1m 4s
3220:	learn: 0.2012313	test: 0.2127045	best: 0.2127045 (3220)	total: 1m	remaining: 1m 4s
3240:	learn: 0.2010878	test: 0.2126667	best: 0.2126600 (3230)	total: 1m	remaining: 1m 3s
3260:	learn: 0.2009891	test: 0.2126276	best: 0.2126276 (3260)	total: 1m 1s	remaining: 1m 3s
3280:	learn: 0.2008756	test: 0.2125966	best: 0.2125966 (3280)	total: 1m 1s	remaining: 1m 3s
3300:	learn: 0.2007575	test: 0.2125575	best: 0.2125575 (3300)	total: 1m 1s	remaining: 1m 2s
3320:	learn: 0.2006227	test: 0.2124985	best: 0.2124985 (3320)	total: 1m 2s	remaining: 1m 2s
3340:	learn: 0.2004934	test: 0.2124325	best: 0.2124325 (3340)	total: 1m 2s	remaining: 1m 2s
3360:	learn: 0.2003669	test: 0.2123824	best: 0.2123824 (3360)	total: 1m 3s	remaining: 1m 1s
3380:	learn: 0.2002506	test: 0.2123269	best: 0.2123269 (3380)	total: 1m 3s	remaining: 1m 1s
3400:	learn: 0.2001465	test: 0.2122892	best: 0.2122892 (3400)	total: 1m 3s	remaining: 1m
3420:	learn: 0.2000190	test: 0.2122781	best: 0.2122680 (3414)	total: 1m 4s	remaining: 1m
3440:	learn: 0.1998912	test: 0.2122265	best: 0.2122265 (3440)	total: 1m 4s	remaining: 1m
3460:	learn: 0.1997810	test: 0.2121888	best: 0.2121888 (3460)	total: 1m 4s	remaining: 59.8s
3480:	learn: 0.1996598	test: 0.2121334	best: 0.2121334 (3480)	total: 1m 5s	remaining: 59.4s
3500:	learn: 0.1995396	test: 0.2120857	best: 0.2120857 (3500)	total: 1m 5s	remaining: 59.1s
3520:	learn: 0.1994302	test: 0.2120424	best: 0.2120424 (3520)	total: 1m 6s	remaining: 58.7s
3540:	learn: 0.1993146	test: 0.2120122	best: 0.2120111 (3538)	total: 1m 6s	remaining: 58.3s
3560:	learn: 0.1991916	test: 0.2119775	best: 0.2119763 (3559)	total: 1m 6s	remaining: 58s
3580:	learn: 0.1990822	test: 0.2119295	best: 0.2119295 (3580)	total: 1m 7s	remaining: 57.6s
3600:	learn: 0.1989651	test: 0.2118986	best: 0.2118986 (3600)	total: 1m 7s	remaining: 57.2s
3620:	learn: 0.1988725	test: 0.2118722	best: 0.2118708 (3619)	total: 1m 8s	remaining: 56.9s
3640:	learn: 0.1987354	test: 0.2117936	best: 0.2117936 (3640)	total: 1m 8s	remaining: 56.5s
3660:	learn: 0.1986101	test: 0.2117420	best: 0.2117384 (3658)	total: 1m 8s	remaining: 56.1s
3680:	learn: 0.1984993	test: 0.2117112	best: 0.2117078 (3678)	total: 1m 9s	remaining: 55.8s
3700:	learn: 0.1983825	test: 0.2116689	best: 0.2116655 (3698)	total: 1m 9s	remaining: 55.4s
3720:	learn: 0.1982736	test: 0.2116331	best: 0.2116331 (3720)	total: 1m 9s	remaining: 55s
3740:	learn: 0.1981501	test: 0.2115762	best: 0.2115762 (3740)	total: 1m 10s	remaining: 54.6s
3760:	learn: 0.1980247	test: 0.2115215	best: 0.2115214 (3759)	total: 1m 10s	remaining: 54.3s
3780:	learn: 0.1979159	test: 0.2114942	best: 0.2114910 (3777)	total: 1m 11s	remaining: 53.9s
3800:	learn: 0.1977912	test: 0.2114596	best: 0.2114596 (3800)	total: 1m 11s	remaining: 53.5s
3820:	learn: 0.1976796	test: 0.2114380	best: 0.2114380 (3820)	total: 1m 11s	remaining: 53.1s
3840:	learn: 0.1975487	test: 0.2113959	best: 0.2113959 (3840)	total: 1m 12s	remaining: 52.8s
3860:	learn: 0.1974213	test: 0.2113537	best: 0.2113523 (3858)	total: 1m 12s	remaining: 52.4s
3880:	learn: 0.1973150	test: 0.2113052	best: 0.2113052 (3880)	total: 1m 12s	remaining: 52s
3900:	learn: 0.1972086	test: 0.2112787	best: 0.2112787 (3900)	total: 1m 13s	remaining: 51.6s
3920:	learn: 0.1971007	test: 0.2112342	best: 0.2112342 (3920)	total: 1m 13s	remaining: 51.3s
3940:	learn: 0.1969789	test: 0.2111939	best: 0.2111939 (3940)	total: 1m 14s	remaining: 50.9s
3960:	learn: 0.1968780	test: 0.2111580	best: 0.2111572 (3959)	total: 1m 14s	remaining: 50.5s
3980:	learn: 0.1967591	test: 0.2111097	best: 0.2111097 (3976)	total: 1m 14s	remaining: 50.2s
4000:	learn: 0.1966658	test: 0.2110823	best: 0.2110823 (4000)	total: 1m 15s	remaining: 49.8s
4020:	learn: 0.1965395	test: 0.2110452	best: 0.2110429 (4016)	total: 1m 15s	remaining: 49.4s
4040:	learn: 0.1964261	test: 0.2110060	best: 0.2110060 (4040)	total: 1m 16s	remaining: 49.1s
4060:	learn: 0.1963237	test: 0.2109781	best: 0.2109777 (4059)	total: 1m 16s	remaining: 48.7s
4080:	learn: 0.1962338	test: 0.2109501	best: 0.2109501 (4080)	total: 1m 16s	remaining: 48.3s
4100:	learn: 0.1961259	test: 0.2109197	best: 0.2109185 (4094)	total: 1m 17s	remaining: 47.9s
4120:	learn: 0.1960098	test: 0.2108807	best: 0.2108807 (4120)	total: 1m 17s	remaining: 47.6s
4140:	learn: 0.1958716	test: 0.2107888	best: 0.2107888 (4140)	total: 1m 17s	remaining: 47.2s
4160:	learn: 0.1957575	test: 0.2107347	best: 0.2107347 (4160)	total: 1m 18s	remaining: 46.8s
4180:	learn: 0.1956622	test: 0.2107044	best: 0.2107044 (4180)	total: 1m 18s	remaining: 46.5s
4200:	learn: 0.1955658	test: 0.2106888	best: 0.2106865 (4199)	total: 1m 19s	remaining: 46.1s
4220:	learn: 0.1954758	test: 0.2106468	best: 0.2106468 (4220)	total: 1m 19s	remaining: 45.7s
4240:	learn: 0.1953703	test: 0.2106078	best: 0.2106078 (4240)	total: 1m 19s	remaining: 45.4s
4260:	learn: 0.1952777	test: 0.2105828	best: 0.2105821 (4254)	total: 1m 20s	remaining: 45s
4280:	learn: 0.1951732	test: 0.2105413	best: 0.2105413 (4280)	total: 1m 20s	remaining: 44.6s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645573	test: 0.6645441	best: 0.6645441 (0)	total: 5.18ms	remaining: 5.18ms
1:	learn: 0.6386832	test: 0.6386618	best: 0.6386618 (1)	total: 9.46ms	remaining: 0us
bestTest = 0.6386617561
bestIteration = 1
0:	learn: 0.6400678	test: 0.6400896	best: 0.6400896 (0)	total: 18ms	remaining: 2m 1s
20:	learn: 0.3349260	test: 0.3353332	best: 0.3353332 (20)	total: 406ms	remaining: 2m 9s
40:	learn: 0.3034184	test: 0.3041213	best: 0.3041213 (40)	total: 794ms	remaining: 2m 9s
60:	learn: 0.2900422	test: 0.2901248	best: 0.2901248 (60)	total: 1.19s	remaining: 2m 10s
80:	learn: 0.2814410	test: 0.2813067	best: 0.2813067 (80)	total: 1.57s	remaining: 2m 8s
100:	learn: 0.2762634	test: 0.2759699	best: 0.2759699 (100)	total: 1.94s	remaining: 2m 7s
120:	learn: 0.2712419	test: 0.2708109	best: 0.2708109 (120)	total: 2.29s	remaining: 2m 4s
140:	learn: 0.2668657	test: 0.2660017	best: 0.2660017 (140)	total: 2.66s	remaining: 2m 4s
160:	learn: 0.2626582	test: 0.2615509	best: 0.2615509 (160)	total: 3.03s	remaining: 2m 3s
180:	learn: 0.2601096	test: 0.2590110	best: 0.2590110 (180)	total: 3.39s	remaining: 2m 2s
200:	learn: 0.2570697	test: 0.2558216	best: 0.2558216 (200)	total: 3.77s	remaining: 2m 2s
220:	learn: 0.2544147	test: 0.2529698	best: 0.2529698 (220)	total: 4.14s	remaining: 2m 1s
240:	learn: 0.2517311	test: 0.2500714	best: 0.2500714 (240)	total: 4.5s	remaining: 2m 1s
260:	learn: 0.2498227	test: 0.2481618	best: 0.2481618 (260)	total: 4.86s	remaining: 2m
280:	learn: 0.2482617	test: 0.2466076	best: 0.2466076 (280)	total: 5.22s	remaining: 1m 59s
300:	learn: 0.2467634	test: 0.2451296	best: 0.2451296 (300)	total: 5.57s	remaining: 1m 58s
320:	learn: 0.2453049	test: 0.2436593	best: 0.2436593 (320)	total: 5.92s	remaining: 1m 58s
340:	learn: 0.2441749	test: 0.2425735	best: 0.2425735 (340)	total: 6.28s	remaining: 1m 57s
360:	learn: 0.2430478	test: 0.2415480	best: 0.2415480 (360)	total: 6.64s	remaining: 1m 57s
380:	learn: 0.2418722	test: 0.2403553	best: 0.2403553 (380)	total: 7s	remaining: 1m 56s
400:	learn: 0.2408955	test: 0.2394739	best: 0.2394739 (400)	total: 7.35s	remaining: 1m 56s
420:	learn: 0.2398286	test: 0.2384415	best: 0.2384415 (420)	total: 7.71s	remaining: 1m 55s
440:	learn: 0.2387269	test: 0.2373958	best: 0.2373958 (440)	total: 8.07s	remaining: 1m 55s
460:	learn: 0.2378025	test: 0.2365308	best: 0.2365308 (460)	total: 8.44s	remaining: 1m 54s
480:	learn: 0.2370483	test: 0.2358520	best: 0.2358520 (480)	total: 8.81s	remaining: 1m 54s
500:	learn: 0.2361434	test: 0.2350121	best: 0.2350121 (500)	total: 9.17s	remaining: 1m 54s
520:	learn: 0.2355530	test: 0.2345422	best: 0.2345422 (520)	total: 9.53s	remaining: 1m 53s
540:	learn: 0.2347187	test: 0.2337692	best: 0.2337692 (540)	total: 9.89s	remaining: 1m 53s
560:	learn: 0.2340183	test: 0.2331522	best: 0.2331522 (560)	total: 10.2s	remaining: 1m 52s
580:	learn: 0.2333725	test: 0.2325375	best: 0.2325375 (580)	total: 10.6s	remaining: 1m 52s
600:	learn: 0.2326814	test: 0.2319421	best: 0.2319421 (600)	total: 10.9s	remaining: 1m 51s
620:	learn: 0.2320439	test: 0.2314100	best: 0.2314100 (620)	total: 11.3s	remaining: 1m 51s
640:	learn: 0.2315730	test: 0.2310357	best: 0.2310357 (640)	total: 11.7s	remaining: 1m 50s
660:	learn: 0.2309364	test: 0.2304657	best: 0.2304657 (660)	total: 12s	remaining: 1m 50s
680:	learn: 0.2303219	test: 0.2298706	best: 0.2298706 (680)	total: 12.4s	remaining: 1m 50s
700:	learn: 0.2298464	test: 0.2295233	best: 0.2295233 (700)	total: 12.8s	remaining: 1m 49s
720:	learn: 0.2292679	test: 0.2289947	best: 0.2289947 (720)	total: 13.1s	remaining: 1m 49s
740:	learn: 0.2287055	test: 0.2285232	best: 0.2285232 (740)	total: 13.5s	remaining: 1m 48s
760:	learn: 0.2281081	test: 0.2279752	best: 0.2279752 (760)	total: 13.8s	remaining: 1m 48s
780:	learn: 0.2276243	test: 0.2275538	best: 0.2275538 (780)	total: 14.2s	remaining: 1m 48s
800:	learn: 0.2270897	test: 0.2270288	best: 0.2270288 (800)	total: 14.6s	remaining: 1m 47s
820:	learn: 0.2266085	test: 0.2266440	best: 0.2266440 (820)	total: 14.9s	remaining: 1m 47s
840:	learn: 0.2262483	test: 0.2263747	best: 0.2263747 (840)	total: 15.3s	remaining: 1m 47s
860:	learn: 0.2257772	test: 0.2259532	best: 0.2259532 (860)	total: 15.6s	remaining: 1m 46s
880:	learn: 0.2253948	test: 0.2256734	best: 0.2256734 (880)	total: 16s	remaining: 1m 46s
900:	learn: 0.2250048	test: 0.2253392	best: 0.2253392 (900)	total: 16.4s	remaining: 1m 45s
920:	learn: 0.2246337	test: 0.2250508	best: 0.2250508 (920)	total: 16.7s	remaining: 1m 45s
940:	learn: 0.2243335	test: 0.2248329	best: 0.2248329 (940)	total: 17.1s	remaining: 1m 45s
960:	learn: 0.2239758	test: 0.2245672	best: 0.2245672 (960)	total: 17.5s	remaining: 1m 44s
980:	learn: 0.2236093	test: 0.2242867	best: 0.2242867 (980)	total: 17.8s	remaining: 1m 44s
1000:	learn: 0.2231767	test: 0.2239145	best: 0.2239145 (1000)	total: 18.2s	remaining: 1m 44s
1020:	learn: 0.2228701	test: 0.2237170	best: 0.2237170 (1020)	total: 18.6s	remaining: 1m 43s
1040:	learn: 0.2225127	test: 0.2234248	best: 0.2234248 (1040)	total: 18.9s	remaining: 1m 43s
1060:	learn: 0.2222415	test: 0.2232392	best: 0.2232392 (1060)	total: 19.3s	remaining: 1m 43s
1080:	learn: 0.2219399	test: 0.2230243	best: 0.2230243 (1080)	total: 19.6s	remaining: 1m 42s
1100:	learn: 0.2215298	test: 0.2226940	best: 0.2226940 (1100)	total: 20s	remaining: 1m 42s
1120:	learn: 0.2211167	test: 0.2223491	best: 0.2223491 (1120)	total: 20.4s	remaining: 1m 42s
1140:	learn: 0.2208119	test: 0.2221018	best: 0.2221018 (1140)	total: 20.7s	remaining: 1m 41s
1160:	learn: 0.2204784	test: 0.2218321	best: 0.2218321 (1160)	total: 21.1s	remaining: 1m 41s
1180:	learn: 0.2201964	test: 0.2216864	best: 0.2216864 (1180)	total: 21.5s	remaining: 1m 40s
1200:	learn: 0.2198661	test: 0.2214356	best: 0.2214356 (1200)	total: 21.8s	remaining: 1m 40s
1220:	learn: 0.2195632	test: 0.2212252	best: 0.2212252 (1220)	total: 22.2s	remaining: 1m 40s
1240:	learn: 0.2192916	test: 0.2210495	best: 0.2210495 (1240)	total: 22.6s	remaining: 1m 39s
1260:	learn: 0.2189822	test: 0.2208412	best: 0.2208412 (1260)	total: 22.9s	remaining: 1m 39s
1280:	learn: 0.2186980	test: 0.2206658	best: 0.2206658 (1280)	total: 23.3s	remaining: 1m 39s
1300:	learn: 0.2184467	test: 0.2205090	best: 0.2205090 (1300)	total: 23.7s	remaining: 1m 38s
1320:	learn: 0.2181819	test: 0.2203236	best: 0.2203236 (1320)	total: 24s	remaining: 1m 38s
1340:	learn: 0.2179249	test: 0.2201618	best: 0.2201618 (1340)	total: 24.4s	remaining: 1m 38s
1360:	learn: 0.2176628	test: 0.2199964	best: 0.2199964 (1360)	total: 24.8s	remaining: 1m 37s
1380:	learn: 0.2173866	test: 0.2197920	best: 0.2197920 (1380)	total: 25.1s	remaining: 1m 37s
1400:	learn: 0.2170798	test: 0.2195791	best: 0.2195791 (1400)	total: 25.5s	remaining: 1m 37s
1420:	learn: 0.2168492	test: 0.2194189	best: 0.2194189 (1420)	total: 25.9s	remaining: 1m 36s
1440:	learn: 0.2165956	test: 0.2192660	best: 0.2192656 (1439)	total: 26.2s	remaining: 1m 36s
1460:	learn: 0.2163825	test: 0.2191254	best: 0.2191254 (1460)	total: 26.6s	remaining: 1m 35s
1480:	learn: 0.2161580	test: 0.2189675	best: 0.2189675 (1480)	total: 27s	remaining: 1m 35s
1500:	learn: 0.2159236	test: 0.2188174	best: 0.2188174 (1500)	total: 27.3s	remaining: 1m 35s
1520:	learn: 0.2156698	test: 0.2186524	best: 0.2186524 (1520)	total: 27.7s	remaining: 1m 34s
1540:	learn: 0.2154297	test: 0.2184966	best: 0.2184966 (1540)	total: 28.1s	remaining: 1m 34s
1560:	learn: 0.2151906	test: 0.2183209	best: 0.2183209 (1560)	total: 28.5s	remaining: 1m 34s
1580:	learn: 0.2149068	test: 0.2180692	best: 0.2180692 (1580)	total: 28.9s	remaining: 1m 33s
1600:	learn: 0.2146866	test: 0.2179272	best: 0.2179272 (1600)	total: 29.2s	remaining: 1m 33s
1620:	learn: 0.2144751	test: 0.2178007	best: 0.2178007 (1620)	total: 29.6s	remaining: 1m 33s
1640:	learn: 0.2142412	test: 0.2176403	best: 0.2176403 (1640)	total: 30s	remaining: 1m 32s
1660:	learn: 0.2140293	test: 0.2175127	best: 0.2175127 (1660)	total: 30.4s	remaining: 1m 32s
1680:	learn: 0.2138438	test: 0.2174213	best: 0.2174213 (1680)	total: 30.7s	remaining: 1m 32s
1700:	learn: 0.2136268	test: 0.2172821	best: 0.2172821 (1700)	total: 31.1s	remaining: 1m 32s
1720:	learn: 0.2134419	test: 0.2171577	best: 0.2171577 (1720)	total: 31.5s	remaining: 1m 31s
1740:	learn: 0.2132729	test: 0.2170874	best: 0.2170874 (1740)	total: 31.9s	remaining: 1m 31s
1760:	learn: 0.2130769	test: 0.2169864	best: 0.2169864 (1760)	total: 32.3s	remaining: 1m 31s
1780:	learn: 0.2128904	test: 0.2168780	best: 0.2168780 (1780)	total: 32.7s	remaining: 1m 30s
1800:	learn: 0.2127012	test: 0.2167671	best: 0.2167671 (1800)	total: 33s	remaining: 1m 30s
1820:	learn: 0.2125296	test: 0.2167013	best: 0.2167013 (1820)	total: 33.4s	remaining: 1m 30s
1840:	learn: 0.2123669	test: 0.2166306	best: 0.2166306 (1840)	total: 33.8s	remaining: 1m 29s
1860:	learn: 0.2121611	test: 0.2165057	best: 0.2165057 (1860)	total: 34.2s	remaining: 1m 29s
1880:	learn: 0.2119335	test: 0.2163273	best: 0.2163250 (1879)	total: 34.5s	remaining: 1m 29s
1900:	learn: 0.2117789	test: 0.2162557	best: 0.2162557 (1900)	total: 34.9s	remaining: 1m 28s
1920:	learn: 0.2115737	test: 0.2161258	best: 0.2161258 (1920)	total: 35.3s	remaining: 1m 28s
1940:	learn: 0.2113603	test: 0.2160021	best: 0.2160021 (1940)	total: 35.7s	remaining: 1m 27s
1960:	learn: 0.2111400	test: 0.2158545	best: 0.2158545 (1960)	total: 36s	remaining: 1m 27s
1980:	learn: 0.2109694	test: 0.2157662	best: 0.2157662 (1980)	total: 36.4s	remaining: 1m 27s
2000:	learn: 0.2108161	test: 0.2156882	best: 0.2156882 (2000)	total: 36.8s	remaining: 1m 26s
2020:	learn: 0.2106223	test: 0.2155673	best: 0.2155673 (2020)	total: 37.2s	remaining: 1m 26s
2040:	learn: 0.2104118	test: 0.2154619	best: 0.2154619 (2040)	total: 37.6s	remaining: 1m 26s
2060:	learn: 0.2102586	test: 0.2153676	best: 0.2153676 (2060)	total: 38s	remaining: 1m 25s
2080:	learn: 0.2100164	test: 0.2151944	best: 0.2151944 (2080)	total: 38.3s	remaining: 1m 25s
2100:	learn: 0.2098371	test: 0.2150910	best: 0.2150910 (2100)	total: 38.7s	remaining: 1m 25s
2120:	learn: 0.2096742	test: 0.2150072	best: 0.2150072 (2120)	total: 39.1s	remaining: 1m 24s
2140:	learn: 0.2094729	test: 0.2148776	best: 0.2148776 (2140)	total: 39.4s	remaining: 1m 24s
2160:	learn: 0.2092865	test: 0.2147757	best: 0.2147757 (2160)	total: 39.8s	remaining: 1m 24s
2180:	learn: 0.2090785	test: 0.2146508	best: 0.2146508 (2180)	total: 40.2s	remaining: 1m 23s
2200:	learn: 0.2088925	test: 0.2145672	best: 0.2145672 (2200)	total: 40.6s	remaining: 1m 23s
2220:	learn: 0.2087321	test: 0.2144712	best: 0.2144712 (2220)	total: 40.9s	remaining: 1m 23s
2240:	learn: 0.2085809	test: 0.2143932	best: 0.2143932 (2240)	total: 41.3s	remaining: 1m 22s
2260:	learn: 0.2084238	test: 0.2143148	best: 0.2143148 (2260)	total: 41.7s	remaining: 1m 22s
2280:	learn: 0.2082425	test: 0.2142184	best: 0.2142184 (2280)	total: 42.1s	remaining: 1m 22s
2300:	learn: 0.2080854	test: 0.2141296	best: 0.2141296 (2300)	total: 42.4s	remaining: 1m 21s
2320:	learn: 0.2078977	test: 0.2139811	best: 0.2139811 (2320)	total: 42.8s	remaining: 1m 21s
2340:	learn: 0.2077688	test: 0.2139205	best: 0.2139205 (2340)	total: 43.2s	remaining: 1m 20s
2360:	learn: 0.2076098	test: 0.2138580	best: 0.2138580 (2360)	total: 43.5s	remaining: 1m 20s
2380:	learn: 0.2074261	test: 0.2137526	best: 0.2137526 (2380)	total: 43.9s	remaining: 1m 20s
2400:	learn: 0.2072689	test: 0.2136757	best: 0.2136757 (2400)	total: 44.3s	remaining: 1m 19s
2420:	learn: 0.2071115	test: 0.2136030	best: 0.2136027 (2418)	total: 44.7s	remaining: 1m 19s
2440:	learn: 0.2069604	test: 0.2135128	best: 0.2135128 (2440)	total: 45s	remaining: 1m 19s
2460:	learn: 0.2068313	test: 0.2134505	best: 0.2134505 (2460)	total: 45.4s	remaining: 1m 18s
2480:	learn: 0.2066494	test: 0.2133375	best: 0.2133375 (2480)	total: 45.8s	remaining: 1m 18s
2500:	learn: 0.2065040	test: 0.2132843	best: 0.2132825 (2498)	total: 46.2s	remaining: 1m 18s
2520:	learn: 0.2063687	test: 0.2132227	best: 0.2132227 (2520)	total: 46.5s	remaining: 1m 17s
2540:	learn: 0.2062298	test: 0.2131647	best: 0.2131647 (2540)	total: 46.9s	remaining: 1m 17s
2560:	learn: 0.2060937	test: 0.2131016	best: 0.2131009 (2558)	total: 47.3s	remaining: 1m 16s
2580:	learn: 0.2059487	test: 0.2130298	best: 0.2130298 (2580)	total: 47.6s	remaining: 1m 16s
2600:	learn: 0.2057993	test: 0.2129594	best: 0.2129594 (2600)	total: 48s	remaining: 1m 16s
2620:	learn: 0.2056390	test: 0.2129011	best: 0.2128986 (2619)	total: 48.4s	remaining: 1m 15s
2640:	learn: 0.2054976	test: 0.2128393	best: 0.2128385 (2639)	total: 48.8s	remaining: 1m 15s
2660:	learn: 0.2053790	test: 0.2128100	best: 0.2128100 (2660)	total: 49.1s	remaining: 1m 15s
2680:	learn: 0.2052198	test: 0.2127530	best: 0.2127507 (2679)	total: 49.5s	remaining: 1m 14s
2700:	learn: 0.2050814	test: 0.2126842	best: 0.2126842 (2700)	total: 49.9s	remaining: 1m 14s
2720:	learn: 0.2049108	test: 0.2125856	best: 0.2125856 (2720)	total: 50.3s	remaining: 1m 14s
2740:	learn: 0.2047579	test: 0.2125158	best: 0.2125158 (2740)	total: 50.6s	remaining: 1m 13s
2760:	learn: 0.2046243	test: 0.2124789	best: 0.2124789 (2760)	total: 51s	remaining: 1m 13s
2780:	learn: 0.2044857	test: 0.2124223	best: 0.2124223 (2780)	total: 51.4s	remaining: 1m 12s
2800:	learn: 0.2043494	test: 0.2123853	best: 0.2123853 (2800)	total: 51.7s	remaining: 1m 12s
2820:	learn: 0.2042282	test: 0.2123430	best: 0.2123430 (2820)	total: 52.1s	remaining: 1m 12s
2840:	learn: 0.2040913	test: 0.2122811	best: 0.2122811 (2840)	total: 52.5s	remaining: 1m 11s
2860:	learn: 0.2039672	test: 0.2122376	best: 0.2122362 (2859)	total: 52.9s	remaining: 1m 11s
2880:	learn: 0.2038467	test: 0.2121845	best: 0.2121845 (2880)	total: 53.3s	remaining: 1m 11s
2900:	learn: 0.2037160	test: 0.2121337	best: 0.2121337 (2900)	total: 53.6s	remaining: 1m 10s
2920:	learn: 0.2035535	test: 0.2120650	best: 0.2120650 (2920)	total: 54s	remaining: 1m 10s
2940:	learn: 0.2034225	test: 0.2120127	best: 0.2120127 (2940)	total: 54.4s	remaining: 1m 10s
2960:	learn: 0.2032950	test: 0.2119680	best: 0.2119680 (2960)	total: 54.7s	remaining: 1m 9s
2980:	learn: 0.2031667	test: 0.2119321	best: 0.2119321 (2980)	total: 55.1s	remaining: 1m 9s
3000:	learn: 0.2030388	test: 0.2118820	best: 0.2118820 (3000)	total: 55.5s	remaining: 1m 8s
3020:	learn: 0.2029076	test: 0.2118315	best: 0.2118315 (3020)	total: 55.9s	remaining: 1m 8s
3040:	learn: 0.2027482	test: 0.2117284	best: 0.2117284 (3040)	total: 56.2s	remaining: 1m 8s
3060:	learn: 0.2026257	test: 0.2116697	best: 0.2116697 (3060)	total: 56.6s	remaining: 1m 7s
3080:	learn: 0.2024994	test: 0.2116295	best: 0.2116274 (3078)	total: 57s	remaining: 1m 7s
3100:	learn: 0.2023605	test: 0.2115676	best: 0.2115676 (3100)	total: 57.4s	remaining: 1m 7s
3120:	learn: 0.2022095	test: 0.2114836	best: 0.2114836 (3120)	total: 57.8s	remaining: 1m 6s
3140:	learn: 0.2020878	test: 0.2114282	best: 0.2114282 (3140)	total: 58.1s	remaining: 1m 6s
3160:	learn: 0.2019670	test: 0.2114048	best: 0.2114048 (3160)	total: 58.5s	remaining: 1m 6s
3180:	learn: 0.2018509	test: 0.2113469	best: 0.2113469 (3180)	total: 58.9s	remaining: 1m 5s
3200:	learn: 0.2017055	test: 0.2112781	best: 0.2112781 (3200)	total: 59.3s	remaining: 1m 5s
3220:	learn: 0.2015943	test: 0.2112391	best: 0.2112378 (3219)	total: 59.7s	remaining: 1m 4s
3240:	learn: 0.2014821	test: 0.2111973	best: 0.2111973 (3240)	total: 1m	remaining: 1m 4s
3260:	learn: 0.2013597	test: 0.2111657	best: 0.2111642 (3257)	total: 1m	remaining: 1m 4s
3280:	learn: 0.2012268	test: 0.2111000	best: 0.2111000 (3280)	total: 1m	remaining: 1m 3s
3300:	learn: 0.2011041	test: 0.2110624	best: 0.2110603 (3299)	total: 1m 1s	remaining: 1m 3s
3320:	learn: 0.2009882	test: 0.2110148	best: 0.2110148 (3320)	total: 1m 1s	remaining: 1m 3s
3340:	learn: 0.2008731	test: 0.2109576	best: 0.2109576 (3340)	total: 1m 1s	remaining: 1m 2s
3360:	learn: 0.2007262	test: 0.2108993	best: 0.2108993 (3360)	total: 1m 2s	remaining: 1m 2s
3380:	learn: 0.2005867	test: 0.2108449	best: 0.2108449 (3380)	total: 1m 2s	remaining: 1m 2s
3400:	learn: 0.2004906	test: 0.2108262	best: 0.2108262 (3400)	total: 1m 3s	remaining: 1m 1s
3420:	learn: 0.2003694	test: 0.2107957	best: 0.2107957 (3420)	total: 1m 3s	remaining: 1m 1s
3440:	learn: 0.2002359	test: 0.2107377	best: 0.2107377 (3440)	total: 1m 3s	remaining: 1m
3460:	learn: 0.2001291	test: 0.2107049	best: 0.2107049 (3460)	total: 1m 4s	remaining: 1m
3480:	learn: 0.2000118	test: 0.2106375	best: 0.2106375 (3480)	total: 1m 4s	remaining: 1m
3500:	learn: 0.1998886	test: 0.2106015	best: 0.2106007 (3499)	total: 1m 4s	remaining: 59.9s
3520:	learn: 0.1997791	test: 0.2105680	best: 0.2105680 (3520)	total: 1m 5s	remaining: 59.5s
3540:	learn: 0.1996686	test: 0.2105365	best: 0.2105364 (3539)	total: 1m 5s	remaining: 59.2s
3560:	learn: 0.1995662	test: 0.2104851	best: 0.2104847 (3559)	total: 1m 6s	remaining: 58.8s
3580:	learn: 0.1994367	test: 0.2104339	best: 0.2104339 (3580)	total: 1m 6s	remaining: 58.4s
3600:	learn: 0.1993361	test: 0.2104034	best: 0.2104034 (3600)	total: 1m 6s	remaining: 58.1s
3620:	learn: 0.1992098	test: 0.2103426	best: 0.2103426 (3620)	total: 1m 7s	remaining: 57.7s
3640:	learn: 0.1990868	test: 0.2102865	best: 0.2102865 (3640)	total: 1m 7s	remaining: 57.3s
3660:	learn: 0.1989854	test: 0.2102679	best: 0.2102662 (3659)	total: 1m 7s	remaining: 57s
3680:	learn: 0.1989000	test: 0.2102371	best: 0.2102371 (3680)	total: 1m 8s	remaining: 56.6s
3700:	learn: 0.1987856	test: 0.2101972	best: 0.2101972 (3700)	total: 1m 8s	remaining: 56.2s
3720:	learn: 0.1986995	test: 0.2101889	best: 0.2101867 (3713)	total: 1m 9s	remaining: 55.9s
3740:	learn: 0.1985969	test: 0.2101677	best: 0.2101677 (3740)	total: 1m 9s	remaining: 55.5s
3760:	learn: 0.1984605	test: 0.2101145	best: 0.2101145 (3760)	total: 1m 9s	remaining: 55.2s
3780:	learn: 0.1982991	test: 0.2100281	best: 0.2100281 (3780)	total: 1m 10s	remaining: 54.8s
3800:	learn: 0.1981583	test: 0.2099673	best: 0.2099673 (3800)	total: 1m 10s	remaining: 54.4s
3820:	learn: 0.1980424	test: 0.2099276	best: 0.2099275 (3819)	total: 1m 10s	remaining: 54s
3840:	learn: 0.1979295	test: 0.2098800	best: 0.2098800 (3840)	total: 1m 11s	remaining: 53.7s
3860:	learn: 0.1977838	test: 0.2097940	best: 0.2097940 (3860)	total: 1m 11s	remaining: 53.3s
3880:	learn: 0.1976798	test: 0.2097545	best: 0.2097545 (3880)	total: 1m 12s	remaining: 52.9s
3900:	learn: 0.1975784	test: 0.2097212	best: 0.2097196 (3898)	total: 1m 12s	remaining: 52.6s
3920:	learn: 0.1974299	test: 0.2096524	best: 0.2096524 (3920)	total: 1m 12s	remaining: 52.2s
3940:	learn: 0.1973434	test: 0.2096333	best: 0.2096327 (3939)	total: 1m 13s	remaining: 51.9s
3960:	learn: 0.1972326	test: 0.2095829	best: 0.2095829 (3960)	total: 1m 13s	remaining: 51.5s
3980:	learn: 0.1971205	test: 0.2095392	best: 0.2095392 (3980)	total: 1m 14s	remaining: 51.1s
4000:	learn: 0.1970121	test: 0.2095164	best: 0.2095164 (4000)	total: 1m 14s	remaining: 50.8s
4020:	learn: 0.1969160	test: 0.2094942	best: 0.2094908 (4018)	total: 1m 14s	remaining: 50.4s
4040:	learn: 0.1968346	test: 0.2094790	best: 0.2094790 (4040)	total: 1m 15s	remaining: 50.1s
4060:	learn: 0.1967312	test: 0.2094504	best: 0.2094496 (4059)	total: 1m 15s	remaining: 49.7s
4080:	learn: 0.1966364	test: 0.2094248	best: 0.2094248 (4080)	total: 1m 16s	remaining: 49.4s
4100:	learn: 0.1965200	test: 0.2093733	best: 0.2093733 (4100)	total: 1m 16s	remaining: 49s
4120:	learn: 0.1964013	test: 0.2093318	best: 0.2093318 (4120)	total: 1m 16s	remaining: 48.6s
4140:	learn: 0.1962912	test: 0.2093138	best: 0.2093128 (4138)	total: 1m 17s	remaining: 48.3s
4160:	learn: 0.1961923	test: 0.2092675	best: 0.2092675 (4160)	total: 1m 17s	remaining: 47.9s
4180:	learn: 0.1961024	test: 0.2092404	best: 0.2092404 (4180)	total: 1m 17s	remaining: 47.5s
4200:	learn: 0.1960072	test: 0.2092139	best: 0.2092139 (4200)	total: 1m 18s	remaining: 47.2s
4220:	learn: 0.1958978	test: 0.2091770	best: 0.2091770 (4220)	total: 1m 18s	remaining: 46.8s
4240:	learn: 0.1957994	test: 0.2091427	best: 0.2091427 (4240)	total: 1m 19s	remaining: 46.4s
4260:	learn: 0.1956984	test: 0.2091134	best: 0.2091134 (4260)	total: 1m 19s	remaining: 46.1s
4280:	learn: 0.1956043	test: 0.2090773	best: 0.2090773 (4280)	total: 1m 19s	remaining: 45.7s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645644	test: 0.6645411	best: 0.6645411 (0)	total: 4.67ms	remaining: 4.67ms
1:	learn: 0.6387113	test: 0.6386664	best: 0.6386664 (1)	total: 9.56ms	remaining: 0us
bestTest = 0.6386664107
bestIteration = 1
0:	learn: 0.6398220	test: 0.6395629	best: 0.6395629 (0)	total: 17.8ms	remaining: 1m 57s
20:	learn: 0.3337624	test: 0.3336918	best: 0.3336918 (20)	total: 406ms	remaining: 2m 7s
40:	learn: 0.3027509	test: 0.3029605	best: 0.3029605 (40)	total: 796ms	remaining: 2m 7s
60:	learn: 0.2883686	test: 0.2878142	best: 0.2878142 (60)	total: 1.19s	remaining: 2m 7s
80:	learn: 0.2797840	test: 0.2789526	best: 0.2789526 (80)	total: 1.57s	remaining: 2m 6s
100:	learn: 0.2739213	test: 0.2729983	best: 0.2729983 (100)	total: 1.94s	remaining: 2m 4s
120:	learn: 0.2693127	test: 0.2684130	best: 0.2684130 (120)	total: 2.31s	remaining: 2m 3s
140:	learn: 0.2653928	test: 0.2643229	best: 0.2643229 (140)	total: 2.69s	remaining: 2m 3s
160:	learn: 0.2617758	test: 0.2605430	best: 0.2605430 (160)	total: 3.06s	remaining: 2m 2s
180:	learn: 0.2588262	test: 0.2576271	best: 0.2576271 (180)	total: 3.43s	remaining: 2m 1s
200:	learn: 0.2557179	test: 0.2543599	best: 0.2543599 (200)	total: 3.8s	remaining: 2m 1s
220:	learn: 0.2532508	test: 0.2517926	best: 0.2517926 (220)	total: 4.16s	remaining: 2m
240:	learn: 0.2511043	test: 0.2496131	best: 0.2496131 (240)	total: 4.53s	remaining: 1m 59s
260:	learn: 0.2493084	test: 0.2477895	best: 0.2477895 (260)	total: 4.9s	remaining: 1m 59s
280:	learn: 0.2478408	test: 0.2463662	best: 0.2463662 (280)	total: 5.26s	remaining: 1m 58s
300:	learn: 0.2464213	test: 0.2450236	best: 0.2450236 (300)	total: 5.61s	remaining: 1m 57s
320:	learn: 0.2451000	test: 0.2437888	best: 0.2437888 (320)	total: 5.96s	remaining: 1m 56s
340:	learn: 0.2437202	test: 0.2424085	best: 0.2424085 (340)	total: 6.32s	remaining: 1m 56s
360:	learn: 0.2422913	test: 0.2409516	best: 0.2409516 (360)	total: 6.69s	remaining: 1m 55s
380:	learn: 0.2414133	test: 0.2401773	best: 0.2401773 (380)	total: 7.05s	remaining: 1m 55s
400:	learn: 0.2404371	test: 0.2392951	best: 0.2392951 (400)	total: 7.41s	remaining: 1m 54s
420:	learn: 0.2394628	test: 0.2383604	best: 0.2383604 (420)	total: 7.77s	remaining: 1m 54s
440:	learn: 0.2384765	test: 0.2374523	best: 0.2374523 (440)	total: 8.13s	remaining: 1m 53s
460:	learn: 0.2377002	test: 0.2367436	best: 0.2367436 (460)	total: 8.5s	remaining: 1m 53s
480:	learn: 0.2369533	test: 0.2360930	best: 0.2360930 (480)	total: 8.86s	remaining: 1m 52s
500:	learn: 0.2361976	test: 0.2354405	best: 0.2354405 (500)	total: 9.21s	remaining: 1m 52s
520:	learn: 0.2354578	test: 0.2347544	best: 0.2347544 (520)	total: 9.59s	remaining: 1m 51s
540:	learn: 0.2346077	test: 0.2339756	best: 0.2339756 (540)	total: 9.94s	remaining: 1m 51s
560:	learn: 0.2339434	test: 0.2334083	best: 0.2334083 (560)	total: 10.3s	remaining: 1m 50s
580:	learn: 0.2330860	test: 0.2325744	best: 0.2325744 (580)	total: 10.7s	remaining: 1m 50s
600:	learn: 0.2324609	test: 0.2320479	best: 0.2320479 (600)	total: 11s	remaining: 1m 50s
620:	learn: 0.2318259	test: 0.2315067	best: 0.2315067 (620)	total: 11.4s	remaining: 1m 49s
640:	learn: 0.2311784	test: 0.2309608	best: 0.2309608 (640)	total: 11.8s	remaining: 1m 49s
660:	learn: 0.2305476	test: 0.2304559	best: 0.2304559 (660)	total: 12.1s	remaining: 1m 48s
680:	learn: 0.2299983	test: 0.2300192	best: 0.2300192 (680)	total: 12.5s	remaining: 1m 48s
700:	learn: 0.2294739	test: 0.2296029	best: 0.2296029 (700)	total: 12.8s	remaining: 1m 48s
720:	learn: 0.2288197	test: 0.2290525	best: 0.2290525 (720)	total: 13.2s	remaining: 1m 47s
740:	learn: 0.2283261	test: 0.2286515	best: 0.2286515 (740)	total: 13.6s	remaining: 1m 47s
760:	learn: 0.2278020	test: 0.2282056	best: 0.2282056 (760)	total: 13.9s	remaining: 1m 46s
780:	learn: 0.2273624	test: 0.2278931	best: 0.2278931 (780)	total: 14.3s	remaining: 1m 46s
800:	learn: 0.2269277	test: 0.2275762	best: 0.2275762 (800)	total: 14.6s	remaining: 1m 45s
820:	learn: 0.2264727	test: 0.2272281	best: 0.2272281 (820)	total: 15s	remaining: 1m 45s
840:	learn: 0.2260331	test: 0.2268928	best: 0.2268928 (840)	total: 15.3s	remaining: 1m 45s
860:	learn: 0.2256091	test: 0.2265444	best: 0.2265444 (860)	total: 15.7s	remaining: 1m 44s
880:	learn: 0.2251936	test: 0.2262410	best: 0.2262410 (880)	total: 16s	remaining: 1m 44s
900:	learn: 0.2248111	test: 0.2259584	best: 0.2259584 (900)	total: 16.4s	remaining: 1m 44s
920:	learn: 0.2243741	test: 0.2256514	best: 0.2256514 (920)	total: 16.8s	remaining: 1m 43s
940:	learn: 0.2239944	test: 0.2253940	best: 0.2253940 (940)	total: 17.1s	remaining: 1m 43s
960:	learn: 0.2235684	test: 0.2250715	best: 0.2250715 (960)	total: 17.5s	remaining: 1m 42s
980:	learn: 0.2231050	test: 0.2246862	best: 0.2246862 (980)	total: 17.9s	remaining: 1m 42s
1000:	learn: 0.2227724	test: 0.2244407	best: 0.2244407 (1000)	total: 18.2s	remaining: 1m 42s
1020:	learn: 0.2223947	test: 0.2241306	best: 0.2241306 (1020)	total: 18.6s	remaining: 1m 41s
1040:	learn: 0.2220290	test: 0.2238880	best: 0.2238880 (1040)	total: 19s	remaining: 1m 41s
1060:	learn: 0.2216945	test: 0.2236770	best: 0.2236770 (1060)	total: 19.4s	remaining: 1m 41s
1080:	learn: 0.2213544	test: 0.2234293	best: 0.2234293 (1080)	total: 19.7s	remaining: 1m 40s
1100:	learn: 0.2210290	test: 0.2231685	best: 0.2231685 (1100)	total: 20.1s	remaining: 1m 40s
1120:	learn: 0.2207034	test: 0.2229396	best: 0.2229396 (1120)	total: 20.4s	remaining: 1m 39s
1140:	learn: 0.2204332	test: 0.2227590	best: 0.2227590 (1140)	total: 20.8s	remaining: 1m 39s
1160:	learn: 0.2201066	test: 0.2225519	best: 0.2225519 (1160)	total: 21.2s	remaining: 1m 39s
1180:	learn: 0.2197715	test: 0.2223439	best: 0.2223439 (1180)	total: 21.5s	remaining: 1m 38s
1200:	learn: 0.2195052	test: 0.2221822	best: 0.2221822 (1200)	total: 21.9s	remaining: 1m 38s
1220:	learn: 0.2192048	test: 0.2219679	best: 0.2219679 (1220)	total: 22.3s	remaining: 1m 38s
1240:	learn: 0.2189414	test: 0.2217905	best: 0.2217905 (1240)	total: 22.6s	remaining: 1m 37s
1260:	learn: 0.2186787	test: 0.2216165	best: 0.2216165 (1260)	total: 23s	remaining: 1m 37s
1280:	learn: 0.2184089	test: 0.2214654	best: 0.2214654 (1280)	total: 23.3s	remaining: 1m 37s
1300:	learn: 0.2181833	test: 0.2213337	best: 0.2213337 (1300)	total: 23.7s	remaining: 1m 36s
1320:	learn: 0.2179390	test: 0.2211789	best: 0.2211789 (1320)	total: 24.1s	remaining: 1m 36s
1340:	learn: 0.2175319	test: 0.2208732	best: 0.2208732 (1340)	total: 24.4s	remaining: 1m 36s
1360:	learn: 0.2172497	test: 0.2207099	best: 0.2207056 (1359)	total: 24.8s	remaining: 1m 35s
1380:	learn: 0.2169238	test: 0.2204727	best: 0.2204727 (1380)	total: 25.2s	remaining: 1m 35s
1400:	learn: 0.2166474	test: 0.2202976	best: 0.2202976 (1400)	total: 25.5s	remaining: 1m 34s
1420:	learn: 0.2164298	test: 0.2201698	best: 0.2201698 (1420)	total: 25.9s	remaining: 1m 34s
1440:	learn: 0.2162170	test: 0.2200612	best: 0.2200612 (1440)	total: 26.3s	remaining: 1m 34s
1460:	learn: 0.2160126	test: 0.2199684	best: 0.2199684 (1460)	total: 26.6s	remaining: 1m 33s
1480:	learn: 0.2157722	test: 0.2198188	best: 0.2198188 (1480)	total: 27s	remaining: 1m 33s
1500:	learn: 0.2155250	test: 0.2196779	best: 0.2196779 (1500)	total: 27.3s	remaining: 1m 33s
1520:	learn: 0.2152798	test: 0.2195430	best: 0.2195430 (1520)	total: 27.7s	remaining: 1m 32s
1540:	learn: 0.2149902	test: 0.2193226	best: 0.2193226 (1540)	total: 28.1s	remaining: 1m 32s
1560:	learn: 0.2147815	test: 0.2192001	best: 0.2192001 (1560)	total: 28.4s	remaining: 1m 31s
1580:	learn: 0.2145100	test: 0.2190124	best: 0.2190124 (1580)	total: 28.8s	remaining: 1m 31s
1600:	learn: 0.2143036	test: 0.2189122	best: 0.2189122 (1600)	total: 29.2s	remaining: 1m 31s
1620:	learn: 0.2140276	test: 0.2187260	best: 0.2187260 (1620)	total: 29.5s	remaining: 1m 30s
1640:	learn: 0.2138294	test: 0.2186283	best: 0.2186283 (1640)	total: 29.9s	remaining: 1m 30s
1660:	learn: 0.2136101	test: 0.2184948	best: 0.2184934 (1659)	total: 30.3s	remaining: 1m 30s
1680:	learn: 0.2134235	test: 0.2184128	best: 0.2184128 (1680)	total: 30.6s	remaining: 1m 29s
1700:	learn: 0.2131889	test: 0.2182697	best: 0.2182685 (1699)	total: 31s	remaining: 1m 29s
1720:	learn: 0.2129561	test: 0.2181081	best: 0.2181081 (1720)	total: 31.4s	remaining: 1m 29s
1740:	learn: 0.2127699	test: 0.2179933	best: 0.2179933 (1740)	total: 31.7s	remaining: 1m 28s
1760:	learn: 0.2125514	test: 0.2178849	best: 0.2178849 (1760)	total: 32.1s	remaining: 1m 28s
1780:	learn: 0.2123447	test: 0.2177848	best: 0.2177848 (1780)	total: 32.5s	remaining: 1m 28s
1800:	learn: 0.2121493	test: 0.2176745	best: 0.2176745 (1800)	total: 32.8s	remaining: 1m 27s
1820:	learn: 0.2119592	test: 0.2176032	best: 0.2176032 (1820)	total: 33.2s	remaining: 1m 27s
1840:	learn: 0.2117770	test: 0.2175429	best: 0.2175429 (1840)	total: 33.6s	remaining: 1m 26s
1860:	learn: 0.2115915	test: 0.2174497	best: 0.2174497 (1860)	total: 33.9s	remaining: 1m 26s
1880:	learn: 0.2113988	test: 0.2173474	best: 0.2173474 (1880)	total: 34.3s	remaining: 1m 26s
1900:	learn: 0.2111959	test: 0.2172227	best: 0.2172227 (1900)	total: 34.7s	remaining: 1m 25s
1920:	learn: 0.2110279	test: 0.2171507	best: 0.2171507 (1920)	total: 35s	remaining: 1m 25s
1940:	learn: 0.2108598	test: 0.2170643	best: 0.2170643 (1940)	total: 35.4s	remaining: 1m 25s
1960:	learn: 0.2106622	test: 0.2169634	best: 0.2169634 (1960)	total: 35.8s	remaining: 1m 24s
1980:	learn: 0.2104983	test: 0.2168943	best: 0.2168943 (1980)	total: 36.2s	remaining: 1m 24s
2000:	learn: 0.2103384	test: 0.2168115	best: 0.2168115 (2000)	total: 36.5s	remaining: 1m 24s
2020:	learn: 0.2101608	test: 0.2167342	best: 0.2167342 (2020)	total: 36.9s	remaining: 1m 23s
2040:	learn: 0.2099921	test: 0.2166526	best: 0.2166526 (2040)	total: 37.3s	remaining: 1m 23s
2060:	learn: 0.2098205	test: 0.2165782	best: 0.2165782 (2060)	total: 37.6s	remaining: 1m 22s
2080:	learn: 0.2096627	test: 0.2165020	best: 0.2165020 (2080)	total: 38s	remaining: 1m 22s
2100:	learn: 0.2094965	test: 0.2163827	best: 0.2163827 (2100)	total: 38.4s	remaining: 1m 22s
2120:	learn: 0.2093134	test: 0.2162857	best: 0.2162856 (2119)	total: 38.7s	remaining: 1m 21s
2140:	learn: 0.2091329	test: 0.2162095	best: 0.2162095 (2140)	total: 39.1s	remaining: 1m 21s
2160:	learn: 0.2089344	test: 0.2161318	best: 0.2161318 (2160)	total: 39.5s	remaining: 1m 21s
2180:	learn: 0.2087638	test: 0.2160493	best: 0.2160493 (2180)	total: 39.8s	remaining: 1m 20s
2200:	learn: 0.2086170	test: 0.2159845	best: 0.2159845 (2200)	total: 40.2s	remaining: 1m 20s
2220:	learn: 0.2084629	test: 0.2159161	best: 0.2159161 (2220)	total: 40.6s	remaining: 1m 20s
2240:	learn: 0.2083051	test: 0.2158418	best: 0.2158418 (2240)	total: 40.9s	remaining: 1m 19s
2260:	learn: 0.2081535	test: 0.2157678	best: 0.2157678 (2260)	total: 41.3s	remaining: 1m 19s
2280:	learn: 0.2079584	test: 0.2156797	best: 0.2156797 (2280)	total: 41.7s	remaining: 1m 19s
2300:	learn: 0.2078086	test: 0.2156126	best: 0.2156126 (2300)	total: 42.1s	remaining: 1m 18s
2320:	learn: 0.2076259	test: 0.2155265	best: 0.2155265 (2320)	total: 42.4s	remaining: 1m 18s
2340:	learn: 0.2074788	test: 0.2154710	best: 0.2154710 (2340)	total: 42.8s	remaining: 1m 18s
2360:	learn: 0.2073347	test: 0.2154040	best: 0.2154040 (2360)	total: 43.2s	remaining: 1m 17s
2380:	learn: 0.2071821	test: 0.2153474	best: 0.2153439 (2377)	total: 43.6s	remaining: 1m 17s
2400:	learn: 0.2070376	test: 0.2153007	best: 0.2153007 (2400)	total: 43.9s	remaining: 1m 16s
2420:	learn: 0.2068990	test: 0.2152472	best: 0.2152472 (2420)	total: 44.3s	remaining: 1m 16s
2440:	learn: 0.2067082	test: 0.2151422	best: 0.2151411 (2436)	total: 44.7s	remaining: 1m 16s
2460:	learn: 0.2065353	test: 0.2150729	best: 0.2150729 (2460)	total: 45s	remaining: 1m 15s
2480:	learn: 0.2063908	test: 0.2150104	best: 0.2150104 (2480)	total: 45.4s	remaining: 1m 15s
2500:	learn: 0.2062402	test: 0.2149522	best: 0.2149522 (2500)	total: 45.8s	remaining: 1m 15s
2520:	learn: 0.2060798	test: 0.2148487	best: 0.2148487 (2520)	total: 46.1s	remaining: 1m 14s
2540:	learn: 0.2059378	test: 0.2147975	best: 0.2147975 (2540)	total: 46.5s	remaining: 1m 14s
2560:	learn: 0.2057733	test: 0.2147193	best: 0.2147193 (2560)	total: 46.8s	remaining: 1m 14s
2580:	learn: 0.2056377	test: 0.2146544	best: 0.2146544 (2580)	total: 47.2s	remaining: 1m 13s
2600:	learn: 0.2054851	test: 0.2145765	best: 0.2145750 (2599)	total: 47.6s	remaining: 1m 13s
2620:	learn: 0.2053389	test: 0.2145267	best: 0.2145267 (2620)	total: 48s	remaining: 1m 12s
2640:	learn: 0.2051703	test: 0.2144433	best: 0.2144433 (2640)	total: 48.3s	remaining: 1m 12s
2660:	learn: 0.2050399	test: 0.2143866	best: 0.2143866 (2660)	total: 48.7s	remaining: 1m 12s
2680:	learn: 0.2048883	test: 0.2143531	best: 0.2143524 (2679)	total: 49.1s	remaining: 1m 11s
2700:	learn: 0.2047688	test: 0.2143024	best: 0.2143024 (2700)	total: 49.5s	remaining: 1m 11s
2720:	learn: 0.2046624	test: 0.2142701	best: 0.2142701 (2720)	total: 49.8s	remaining: 1m 11s
2740:	learn: 0.2045298	test: 0.2142179	best: 0.2142155 (2739)	total: 50.2s	remaining: 1m 10s
2760:	learn: 0.2044067	test: 0.2141637	best: 0.2141637 (2760)	total: 50.6s	remaining: 1m 10s
2780:	learn: 0.2042439	test: 0.2140801	best: 0.2140801 (2780)	total: 50.9s	remaining: 1m 10s
2800:	learn: 0.2040991	test: 0.2140341	best: 0.2140341 (2800)	total: 51.3s	remaining: 1m 9s
2820:	learn: 0.2039681	test: 0.2139949	best: 0.2139942 (2818)	total: 51.7s	remaining: 1m 9s
2840:	learn: 0.2038302	test: 0.2139353	best: 0.2139353 (2840)	total: 52.1s	remaining: 1m 9s
2860:	learn: 0.2037057	test: 0.2138987	best: 0.2138986 (2859)	total: 52.5s	remaining: 1m 8s
2880:	learn: 0.2035767	test: 0.2138718	best: 0.2138718 (2880)	total: 52.8s	remaining: 1m 8s
2900:	learn: 0.2034626	test: 0.2138218	best: 0.2138218 (2900)	total: 53.2s	remaining: 1m 7s
2920:	learn: 0.2033032	test: 0.2137481	best: 0.2137481 (2920)	total: 53.6s	remaining: 1m 7s
2940:	learn: 0.2031889	test: 0.2137039	best: 0.2137038 (2939)	total: 53.9s	remaining: 1m 7s
2960:	learn: 0.2030718	test: 0.2136513	best: 0.2136509 (2959)	total: 54.3s	remaining: 1m 6s
2980:	learn: 0.2028746	test: 0.2135404	best: 0.2135404 (2980)	total: 54.7s	remaining: 1m 6s
3000:	learn: 0.2027352	test: 0.2134898	best: 0.2134898 (3000)	total: 55s	remaining: 1m 6s
3020:	learn: 0.2025728	test: 0.2133949	best: 0.2133949 (3018)	total: 55.4s	remaining: 1m 5s
3040:	learn: 0.2024374	test: 0.2133319	best: 0.2133319 (3040)	total: 55.8s	remaining: 1m 5s
3060:	learn: 0.2022996	test: 0.2132707	best: 0.2132707 (3060)	total: 56.2s	remaining: 1m 5s
3080:	learn: 0.2021618	test: 0.2132386	best: 0.2132369 (3079)	total: 56.6s	remaining: 1m 4s
3100:	learn: 0.2020065	test: 0.2131706	best: 0.2131706 (3100)	total: 56.9s	remaining: 1m 4s
3120:	learn: 0.2018872	test: 0.2131380	best: 0.2131380 (3120)	total: 57.3s	remaining: 1m 4s
3140:	learn: 0.2017838	test: 0.2131073	best: 0.2131039 (3139)	total: 57.7s	remaining: 1m 3s
3160:	learn: 0.2016312	test: 0.2130456	best: 0.2130456 (3160)	total: 58.1s	remaining: 1m 3s
3180:	learn: 0.2015052	test: 0.2130060	best: 0.2130060 (3180)	total: 58.4s	remaining: 1m 2s
3200:	learn: 0.2013621	test: 0.2129284	best: 0.2129284 (3200)	total: 58.8s	remaining: 1m 2s
3220:	learn: 0.2012350	test: 0.2128520	best: 0.2128510 (3219)	total: 59.2s	remaining: 1m 2s
3240:	learn: 0.2011218	test: 0.2128220	best: 0.2128161 (3237)	total: 59.6s	remaining: 1m 1s
3260:	learn: 0.2009696	test: 0.2127693	best: 0.2127693 (3260)	total: 60s	remaining: 1m 1s
3280:	learn: 0.2008498	test: 0.2127247	best: 0.2127247 (3280)	total: 1m	remaining: 1m 1s
3300:	learn: 0.2007288	test: 0.2126849	best: 0.2126849 (3300)	total: 1m	remaining: 1m
3320:	learn: 0.2006150	test: 0.2126558	best: 0.2126558 (3320)	total: 1m 1s	remaining: 1m
3340:	learn: 0.2004834	test: 0.2125973	best: 0.2125958 (3337)	total: 1m 1s	remaining: 1m
3360:	learn: 0.2003534	test: 0.2125637	best: 0.2125634 (3359)	total: 1m 1s	remaining: 59.7s
3380:	learn: 0.2002365	test: 0.2125182	best: 0.2125170 (3378)	total: 1m 2s	remaining: 59.4s
3400:	learn: 0.2000996	test: 0.2124591	best: 0.2124571 (3399)	total: 1m 2s	remaining: 59s
3420:	learn: 0.1999869	test: 0.2124275	best: 0.2124275 (3420)	total: 1m 2s	remaining: 58.7s
3440:	learn: 0.1998793	test: 0.2123804	best: 0.2123804 (3440)	total: 1m 3s	remaining: 58.3s
3460:	learn: 0.1997498	test: 0.2123281	best: 0.2123281 (3460)	total: 1m 3s	remaining: 58s
3480:	learn: 0.1996565	test: 0.2122979	best: 0.2122979 (3480)	total: 1m 4s	remaining: 57.6s
3500:	learn: 0.1995142	test: 0.2122452	best: 0.2122452 (3500)	total: 1m 4s	remaining: 57.2s
3520:	learn: 0.1994137	test: 0.2122197	best: 0.2122191 (3519)	total: 1m 4s	remaining: 56.9s
3540:	learn: 0.1992893	test: 0.2121979	best: 0.2121979 (3540)	total: 1m 5s	remaining: 56.5s
3560:	learn: 0.1991765	test: 0.2121569	best: 0.2121569 (3560)	total: 1m 5s	remaining: 56.2s
3580:	learn: 0.1990531	test: 0.2121237	best: 0.2121237 (3580)	total: 1m 6s	remaining: 55.8s
3600:	learn: 0.1989318	test: 0.2120805	best: 0.2120788 (3597)	total: 1m 6s	remaining: 55.4s
3620:	learn: 0.1988330	test: 0.2120507	best: 0.2120507 (3620)	total: 1m 6s	remaining: 55.1s
3640:	learn: 0.1987389	test: 0.2120185	best: 0.2120185 (3640)	total: 1m 7s	remaining: 54.7s
3660:	learn: 0.1986221	test: 0.2119787	best: 0.2119778 (3656)	total: 1m 7s	remaining: 54.4s
3680:	learn: 0.1984767	test: 0.2119017	best: 0.2119017 (3680)	total: 1m 7s	remaining: 54s
3700:	learn: 0.1983578	test: 0.2118622	best: 0.2118617 (3699)	total: 1m 8s	remaining: 53.6s
3720:	learn: 0.1982522	test: 0.2118299	best: 0.2118299 (3720)	total: 1m 8s	remaining: 53.3s
3740:	learn: 0.1981268	test: 0.2117857	best: 0.2117857 (3740)	total: 1m 9s	remaining: 52.9s
3760:	learn: 0.1980116	test: 0.2117342	best: 0.2117342 (3760)	total: 1m 9s	remaining: 52.5s
3780:	learn: 0.1978959	test: 0.2116966	best: 0.2116946 (3778)	total: 1m 9s	remaining: 52.2s
3800:	learn: 0.1977872	test: 0.2116616	best: 0.2116616 (3800)	total: 1m 10s	remaining: 51.8s
3820:	learn: 0.1976703	test: 0.2116212	best: 0.2116212 (3820)	total: 1m 10s	remaining: 51.5s
3840:	learn: 0.1975688	test: 0.2115824	best: 0.2115824 (3840)	total: 1m 10s	remaining: 51.1s
3860:	learn: 0.1974511	test: 0.2115610	best: 0.2115610 (3860)	total: 1m 11s	remaining: 50.7s
3880:	learn: 0.1973268	test: 0.2115184	best: 0.2115165 (3879)	total: 1m 11s	remaining: 50.4s
3900:	learn: 0.1972201	test: 0.2114908	best: 0.2114861 (3894)	total: 1m 12s	remaining: 50s
3920:	learn: 0.1971062	test: 0.2114454	best: 0.2114447 (3919)	total: 1m 12s	remaining: 49.6s
3940:	learn: 0.1970070	test: 0.2114233	best: 0.2114233 (3940)	total: 1m 12s	remaining: 49.3s
3960:	learn: 0.1968929	test: 0.2114052	best: 0.2114038 (3959)	total: 1m 13s	remaining: 48.9s
3980:	learn: 0.1967907	test: 0.2113840	best: 0.2113840 (3980)	total: 1m 13s	remaining: 48.5s
4000:	learn: 0.1966788	test: 0.2113545	best: 0.2113508 (3998)	total: 1m 13s	remaining: 48.2s
4020:	learn: 0.1965720	test: 0.2113137	best: 0.2113136 (4019)	total: 1m 14s	remaining: 47.8s
4040:	learn: 0.1964746	test: 0.2112832	best: 0.2112832 (4040)	total: 1m 14s	remaining: 47.5s
4060:	learn: 0.1963617	test: 0.2112559	best: 0.2112559 (4060)	total: 1m 15s	remaining: 47.1s
4080:	learn: 0.1962146	test: 0.2111939	best: 0.2111926 (4079)	total: 1m 15s	remaining: 46.8s
4100:	learn: 0.1961025	test: 0.2111387	best: 0.2111387 (4100)	total: 1m 15s	remaining: 46.4s
4120:	learn: 0.1959922	test: 0.2111168	best: 0.2111168 (4120)	total: 1m 16s	remaining: 46s
4140:	learn: 0.1958745	test: 0.2110784	best: 0.2110784 (4140)	total: 1m 16s	remaining: 45.7s
4160:	learn: 0.1957889	test: 0.2110607	best: 0.2110607 (4160)	total: 1m 17s	remaining: 45.3s
4180:	learn: 0.1956843	test: 0.2110367	best: 0.2110367 (4180)	total: 1m 17s	remaining: 44.9s
4200:	learn: 0.1955651	test: 0.2109980	best: 0.2109980 (4200)	total: 1m 17s	remaining: 44.6s
4220:	learn: 0.1954412	test: 0.2109448	best: 0.2109448 (4220)	total: 1m 18s	remaining: 44.2s
4240:	learn: 0.1953058	test: 0.2108684	best: 0.2108669 (4239)	total: 1m 18s	remaining: 43.9s
4260:	learn: 0.1951925	test: 0.2108393	best: 0.2108393 (4259)	total: 1m 19s	remaining: 43.5s
4280:	learn: 0.1950868	test: 0.2108027	best: 0.2108027 (4280)	total: 1m 19s	remaining: 43.1s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645825	test: 0.6644929	best: 0.6644929 (0)	total: 4.63ms	remaining: 4.63ms
1:	learn: 0.6387274	test: 0.6385587	best: 0.6385587 (1)	total: 9.05ms	remaining: 0us
bestTest = 0.638558686
bestIteration = 1
0:	learn: 0.6402530	test: 0.6401010	best: 0.6401010 (0)	total: 17.3ms	remaining: 1m 56s
20:	learn: 0.3353550	test: 0.3336644	best: 0.3336644 (20)	total: 400ms	remaining: 2m 8s
40:	learn: 0.3033941	test: 0.3015609	best: 0.3015609 (40)	total: 786ms	remaining: 2m 8s
60:	learn: 0.2898150	test: 0.2876868	best: 0.2876868 (60)	total: 1.18s	remaining: 2m 9s
80:	learn: 0.2803574	test: 0.2779505	best: 0.2779505 (80)	total: 1.55s	remaining: 2m 8s
100:	learn: 0.2746657	test: 0.2723525	best: 0.2723525 (100)	total: 1.92s	remaining: 2m 6s
120:	learn: 0.2700822	test: 0.2679756	best: 0.2679756 (120)	total: 2.28s	remaining: 2m 5s
140:	learn: 0.2657648	test: 0.2637084	best: 0.2637084 (140)	total: 2.65s	remaining: 2m 4s
160:	learn: 0.2617710	test: 0.2598876	best: 0.2598876 (160)	total: 3s	remaining: 2m 3s
180:	learn: 0.2584082	test: 0.2566527	best: 0.2566527 (180)	total: 3.37s	remaining: 2m 2s
200:	learn: 0.2556681	test: 0.2540083	best: 0.2540083 (200)	total: 3.75s	remaining: 2m 2s
220:	learn: 0.2537550	test: 0.2522514	best: 0.2522514 (220)	total: 4.1s	remaining: 2m 1s
240:	learn: 0.2521505	test: 0.2507461	best: 0.2507461 (240)	total: 4.47s	remaining: 2m
260:	learn: 0.2504719	test: 0.2492507	best: 0.2492507 (260)	total: 4.83s	remaining: 2m
280:	learn: 0.2488228	test: 0.2476753	best: 0.2476753 (280)	total: 5.2s	remaining: 1m 59s
300:	learn: 0.2473951	test: 0.2463746	best: 0.2463746 (300)	total: 5.56s	remaining: 1m 59s
320:	learn: 0.2457980	test: 0.2448127	best: 0.2448127 (320)	total: 5.92s	remaining: 1m 58s
340:	learn: 0.2442463	test: 0.2433179	best: 0.2433179 (340)	total: 6.28s	remaining: 1m 57s
360:	learn: 0.2427725	test: 0.2419332	best: 0.2419332 (360)	total: 6.63s	remaining: 1m 57s
380:	learn: 0.2414938	test: 0.2406587	best: 0.2406587 (380)	total: 7.01s	remaining: 1m 57s
400:	learn: 0.2403608	test: 0.2395794	best: 0.2395794 (400)	total: 7.36s	remaining: 1m 56s
420:	learn: 0.2393789	test: 0.2386864	best: 0.2386864 (420)	total: 7.72s	remaining: 1m 56s
440:	learn: 0.2382493	test: 0.2376792	best: 0.2376792 (440)	total: 8.07s	remaining: 1m 55s
460:	learn: 0.2373820	test: 0.2369283	best: 0.2369283 (460)	total: 8.42s	remaining: 1m 54s
480:	learn: 0.2365193	test: 0.2362102	best: 0.2362102 (480)	total: 8.77s	remaining: 1m 54s
500:	learn: 0.2356415	test: 0.2354420	best: 0.2354420 (500)	total: 9.13s	remaining: 1m 53s
520:	learn: 0.2348491	test: 0.2347538	best: 0.2347538 (520)	total: 9.48s	remaining: 1m 53s
540:	learn: 0.2340855	test: 0.2340600	best: 0.2340600 (540)	total: 9.85s	remaining: 1m 53s
560:	learn: 0.2330611	test: 0.2331275	best: 0.2331275 (560)	total: 10.2s	remaining: 1m 52s
580:	learn: 0.2324855	test: 0.2326730	best: 0.2326730 (580)	total: 10.6s	remaining: 1m 52s
600:	learn: 0.2317201	test: 0.2319948	best: 0.2319948 (600)	total: 10.9s	remaining: 1m 51s
620:	learn: 0.2311962	test: 0.2315982	best: 0.2315982 (620)	total: 11.3s	remaining: 1m 51s
640:	learn: 0.2304996	test: 0.2309807	best: 0.2309807 (640)	total: 11.7s	remaining: 1m 51s
660:	learn: 0.2298894	test: 0.2305015	best: 0.2305015 (660)	total: 12s	remaining: 1m 50s
680:	learn: 0.2293864	test: 0.2301359	best: 0.2301359 (680)	total: 12.4s	remaining: 1m 50s
700:	learn: 0.2288453	test: 0.2296963	best: 0.2296963 (700)	total: 12.7s	remaining: 1m 50s
720:	learn: 0.2283783	test: 0.2293811	best: 0.2293811 (720)	total: 13.1s	remaining: 1m 49s
740:	learn: 0.2279100	test: 0.2290437	best: 0.2290437 (740)	total: 13.5s	remaining: 1m 49s
760:	learn: 0.2273818	test: 0.2286306	best: 0.2286306 (760)	total: 13.8s	remaining: 1m 48s
780:	learn: 0.2269732	test: 0.2283051	best: 0.2283051 (780)	total: 14.2s	remaining: 1m 48s
800:	learn: 0.2265513	test: 0.2280030	best: 0.2280030 (800)	total: 14.5s	remaining: 1m 47s
820:	learn: 0.2260489	test: 0.2276019	best: 0.2276019 (820)	total: 14.9s	remaining: 1m 47s
840:	learn: 0.2256223	test: 0.2272895	best: 0.2272895 (840)	total: 15.2s	remaining: 1m 47s
860:	learn: 0.2252496	test: 0.2270043	best: 0.2270043 (860)	total: 15.6s	remaining: 1m 46s
880:	learn: 0.2248629	test: 0.2267410	best: 0.2267410 (880)	total: 15.9s	remaining: 1m 46s
900:	learn: 0.2244716	test: 0.2264940	best: 0.2264940 (900)	total: 16.3s	remaining: 1m 45s
920:	learn: 0.2241333	test: 0.2262651	best: 0.2262651 (920)	total: 16.7s	remaining: 1m 45s
940:	learn: 0.2237375	test: 0.2259335	best: 0.2259335 (940)	total: 17s	remaining: 1m 45s
960:	learn: 0.2232494	test: 0.2255288	best: 0.2255288 (960)	total: 17.4s	remaining: 1m 44s
980:	learn: 0.2229065	test: 0.2252742	best: 0.2252742 (980)	total: 17.7s	remaining: 1m 44s
1000:	learn: 0.2225566	test: 0.2250161	best: 0.2250161 (1000)	total: 18.1s	remaining: 1m 43s
1020:	learn: 0.2222137	test: 0.2247889	best: 0.2247889 (1020)	total: 18.5s	remaining: 1m 43s
1040:	learn: 0.2218569	test: 0.2245158	best: 0.2245158 (1040)	total: 18.8s	remaining: 1m 43s
1060:	learn: 0.2215183	test: 0.2242692	best: 0.2242692 (1060)	total: 19.2s	remaining: 1m 43s
1080:	learn: 0.2211793	test: 0.2240406	best: 0.2240406 (1080)	total: 19.6s	remaining: 1m 42s
1100:	learn: 0.2208903	test: 0.2238191	best: 0.2238191 (1100)	total: 19.9s	remaining: 1m 42s
1120:	learn: 0.2205854	test: 0.2236203	best: 0.2236203 (1120)	total: 20.3s	remaining: 1m 41s
1140:	learn: 0.2202164	test: 0.2232936	best: 0.2232936 (1140)	total: 20.7s	remaining: 1m 41s
1160:	learn: 0.2198763	test: 0.2230345	best: 0.2230345 (1160)	total: 21s	remaining: 1m 41s
1180:	learn: 0.2196359	test: 0.2228796	best: 0.2228796 (1180)	total: 21.4s	remaining: 1m 40s
1200:	learn: 0.2193823	test: 0.2227321	best: 0.2227321 (1200)	total: 21.7s	remaining: 1m 40s
1220:	learn: 0.2191321	test: 0.2225778	best: 0.2225778 (1220)	total: 22.1s	remaining: 1m 40s
1240:	learn: 0.2188317	test: 0.2223491	best: 0.2223491 (1240)	total: 22.5s	remaining: 1m 39s
1260:	learn: 0.2184821	test: 0.2221021	best: 0.2221021 (1260)	total: 22.8s	remaining: 1m 39s
1280:	learn: 0.2182307	test: 0.2219726	best: 0.2219726 (1280)	total: 23.2s	remaining: 1m 39s
1300:	learn: 0.2179711	test: 0.2218432	best: 0.2218432 (1300)	total: 23.5s	remaining: 1m 38s
1320:	learn: 0.2177095	test: 0.2216804	best: 0.2216804 (1320)	total: 23.9s	remaining: 1m 38s
1340:	learn: 0.2174729	test: 0.2215514	best: 0.2215514 (1340)	total: 24.3s	remaining: 1m 37s
1360:	learn: 0.2171904	test: 0.2213361	best: 0.2213361 (1360)	total: 24.7s	remaining: 1m 37s
1380:	learn: 0.2169518	test: 0.2211870	best: 0.2211870 (1380)	total: 25s	remaining: 1m 37s
1400:	learn: 0.2167180	test: 0.2210552	best: 0.2210552 (1400)	total: 25.4s	remaining: 1m 36s
1420:	learn: 0.2164448	test: 0.2208865	best: 0.2208865 (1420)	total: 25.7s	remaining: 1m 36s
1440:	learn: 0.2162363	test: 0.2207824	best: 0.2207824 (1440)	total: 26.1s	remaining: 1m 36s
1460:	learn: 0.2160012	test: 0.2206534	best: 0.2206534 (1460)	total: 26.5s	remaining: 1m 35s
1480:	learn: 0.2158046	test: 0.2205473	best: 0.2205473 (1480)	total: 26.8s	remaining: 1m 35s
1500:	learn: 0.2155839	test: 0.2204240	best: 0.2204240 (1500)	total: 27.2s	remaining: 1m 35s
1520:	learn: 0.2153616	test: 0.2202764	best: 0.2202764 (1520)	total: 27.5s	remaining: 1m 34s
1540:	learn: 0.2151423	test: 0.2201427	best: 0.2201427 (1540)	total: 27.9s	remaining: 1m 34s
1560:	learn: 0.2149560	test: 0.2200337	best: 0.2200337 (1560)	total: 28.3s	remaining: 1m 33s
1580:	learn: 0.2147291	test: 0.2198889	best: 0.2198889 (1580)	total: 28.6s	remaining: 1m 33s
1600:	learn: 0.2145286	test: 0.2197948	best: 0.2197948 (1600)	total: 29s	remaining: 1m 33s
1620:	learn: 0.2142767	test: 0.2196290	best: 0.2196290 (1620)	total: 29.3s	remaining: 1m 32s
1640:	learn: 0.2140498	test: 0.2194983	best: 0.2194983 (1640)	total: 29.7s	remaining: 1m 32s
1660:	learn: 0.2138186	test: 0.2193801	best: 0.2193801 (1660)	total: 30.1s	remaining: 1m 32s
1680:	learn: 0.2135912	test: 0.2192331	best: 0.2192331 (1680)	total: 30.4s	remaining: 1m 31s
1700:	learn: 0.2133885	test: 0.2191498	best: 0.2191498 (1700)	total: 30.8s	remaining: 1m 31s
1720:	learn: 0.2132060	test: 0.2190504	best: 0.2190504 (1720)	total: 31.2s	remaining: 1m 31s
1740:	learn: 0.2130303	test: 0.2189403	best: 0.2189399 (1739)	total: 31.6s	remaining: 1m 30s
1760:	learn: 0.2127924	test: 0.2188067	best: 0.2188067 (1760)	total: 31.9s	remaining: 1m 30s
1780:	learn: 0.2126060	test: 0.2186935	best: 0.2186935 (1780)	total: 32.3s	remaining: 1m 30s
1800:	learn: 0.2123359	test: 0.2185181	best: 0.2185181 (1800)	total: 32.7s	remaining: 1m 29s
1820:	learn: 0.2121407	test: 0.2184177	best: 0.2184177 (1820)	total: 33s	remaining: 1m 29s
1840:	learn: 0.2119504	test: 0.2183317	best: 0.2183317 (1840)	total: 33.4s	remaining: 1m 29s
1860:	learn: 0.2117354	test: 0.2182242	best: 0.2182242 (1860)	total: 33.7s	remaining: 1m 28s
1880:	learn: 0.2115558	test: 0.2181170	best: 0.2181170 (1880)	total: 34.1s	remaining: 1m 28s
1900:	learn: 0.2113709	test: 0.2180112	best: 0.2180112 (1900)	total: 34.5s	remaining: 1m 27s
1920:	learn: 0.2111851	test: 0.2179242	best: 0.2179242 (1920)	total: 34.8s	remaining: 1m 27s
1940:	learn: 0.2110109	test: 0.2178175	best: 0.2178175 (1940)	total: 35.2s	remaining: 1m 27s
1960:	learn: 0.2108380	test: 0.2177236	best: 0.2177236 (1960)	total: 35.6s	remaining: 1m 26s
1980:	learn: 0.2106649	test: 0.2176401	best: 0.2176401 (1980)	total: 35.9s	remaining: 1m 26s
2000:	learn: 0.2104629	test: 0.2175307	best: 0.2175307 (2000)	total: 36.3s	remaining: 1m 26s
2020:	learn: 0.2102715	test: 0.2174050	best: 0.2174050 (2020)	total: 36.7s	remaining: 1m 25s
2040:	learn: 0.2100541	test: 0.2172573	best: 0.2172573 (2040)	total: 37s	remaining: 1m 25s
2060:	learn: 0.2099053	test: 0.2171788	best: 0.2171788 (2060)	total: 37.4s	remaining: 1m 25s
2080:	learn: 0.2097407	test: 0.2170930	best: 0.2170930 (2080)	total: 37.8s	remaining: 1m 24s
2100:	learn: 0.2095403	test: 0.2169976	best: 0.2169976 (2100)	total: 38.2s	remaining: 1m 24s
2120:	learn: 0.2093897	test: 0.2169427	best: 0.2169427 (2120)	total: 38.5s	remaining: 1m 24s
2140:	learn: 0.2092343	test: 0.2168848	best: 0.2168848 (2140)	total: 38.9s	remaining: 1m 23s
2160:	learn: 0.2090587	test: 0.2167801	best: 0.2167801 (2160)	total: 39.3s	remaining: 1m 23s
2180:	learn: 0.2088722	test: 0.2166852	best: 0.2166852 (2180)	total: 39.6s	remaining: 1m 23s
2200:	learn: 0.2087198	test: 0.2166202	best: 0.2166201 (2199)	total: 40s	remaining: 1m 22s
2220:	learn: 0.2085513	test: 0.2165264	best: 0.2165264 (2220)	total: 40.4s	remaining: 1m 22s
2240:	learn: 0.2083991	test: 0.2164365	best: 0.2164365 (2240)	total: 40.7s	remaining: 1m 22s
2260:	learn: 0.2082389	test: 0.2163850	best: 0.2163850 (2260)	total: 41.1s	remaining: 1m 21s
2280:	learn: 0.2080571	test: 0.2162811	best: 0.2162811 (2280)	total: 41.5s	remaining: 1m 21s
2300:	learn: 0.2078867	test: 0.2162084	best: 0.2162084 (2300)	total: 41.9s	remaining: 1m 20s
2320:	learn: 0.2077490	test: 0.2161688	best: 0.2161678 (2319)	total: 42.2s	remaining: 1m 20s
2340:	learn: 0.2075933	test: 0.2161128	best: 0.2161128 (2340)	total: 42.6s	remaining: 1m 20s
2360:	learn: 0.2074416	test: 0.2160459	best: 0.2160459 (2360)	total: 42.9s	remaining: 1m 19s
2380:	learn: 0.2072836	test: 0.2159791	best: 0.2159791 (2380)	total: 43.3s	remaining: 1m 19s
2400:	learn: 0.2071424	test: 0.2159298	best: 0.2159298 (2400)	total: 43.7s	remaining: 1m 19s
2420:	learn: 0.2069808	test: 0.2158527	best: 0.2158527 (2420)	total: 44s	remaining: 1m 18s
2440:	learn: 0.2068289	test: 0.2157858	best: 0.2157858 (2440)	total: 44.4s	remaining: 1m 18s
2460:	learn: 0.2066680	test: 0.2156867	best: 0.2156867 (2460)	total: 44.8s	remaining: 1m 18s
2480:	learn: 0.2065245	test: 0.2156161	best: 0.2156161 (2480)	total: 45.1s	remaining: 1m 17s
2500:	learn: 0.2063380	test: 0.2155240	best: 0.2155240 (2500)	total: 45.5s	remaining: 1m 17s
2520:	learn: 0.2061718	test: 0.2154348	best: 0.2154348 (2520)	total: 45.9s	remaining: 1m 16s
2540:	learn: 0.2060139	test: 0.2153773	best: 0.2153769 (2539)	total: 46.3s	remaining: 1m 16s
2560:	learn: 0.2058964	test: 0.2153306	best: 0.2153306 (2560)	total: 46.6s	remaining: 1m 16s
2580:	learn: 0.2057548	test: 0.2152963	best: 0.2152954 (2575)	total: 47s	remaining: 1m 15s
2600:	learn: 0.2055811	test: 0.2152160	best: 0.2152145 (2598)	total: 47.4s	remaining: 1m 15s
2620:	learn: 0.2054304	test: 0.2151380	best: 0.2151380 (2620)	total: 47.8s	remaining: 1m 15s
2640:	learn: 0.2052499	test: 0.2150738	best: 0.2150738 (2640)	total: 48.2s	remaining: 1m 14s
2660:	learn: 0.2050817	test: 0.2149946	best: 0.2149946 (2660)	total: 48.5s	remaining: 1m 14s
2680:	learn: 0.2049218	test: 0.2149087	best: 0.2149087 (2680)	total: 48.9s	remaining: 1m 14s
2700:	learn: 0.2047491	test: 0.2148322	best: 0.2148308 (2699)	total: 49.3s	remaining: 1m 13s
2720:	learn: 0.2046393	test: 0.2147868	best: 0.2147840 (2717)	total: 49.6s	remaining: 1m 13s
2740:	learn: 0.2044805	test: 0.2146897	best: 0.2146897 (2740)	total: 50s	remaining: 1m 13s
2760:	learn: 0.2043157	test: 0.2146035	best: 0.2146035 (2760)	total: 50.4s	remaining: 1m 12s
2780:	learn: 0.2041497	test: 0.2145205	best: 0.2145205 (2780)	total: 50.7s	remaining: 1m 12s
2800:	learn: 0.2040276	test: 0.2144708	best: 0.2144708 (2800)	total: 51.1s	remaining: 1m 12s
2820:	learn: 0.2038907	test: 0.2144286	best: 0.2144286 (2820)	total: 51.5s	remaining: 1m 11s
2840:	learn: 0.2037521	test: 0.2144045	best: 0.2144045 (2840)	total: 51.9s	remaining: 1m 11s
2860:	learn: 0.2036398	test: 0.2143575	best: 0.2143575 (2860)	total: 52.3s	remaining: 1m 11s
2880:	learn: 0.2035083	test: 0.2143102	best: 0.2143102 (2880)	total: 52.7s	remaining: 1m 10s
2900:	learn: 0.2033737	test: 0.2142608	best: 0.2142608 (2900)	total: 53s	remaining: 1m 10s
2920:	learn: 0.2032222	test: 0.2141903	best: 0.2141903 (2920)	total: 53.4s	remaining: 1m 10s
2940:	learn: 0.2030892	test: 0.2141434	best: 0.2141434 (2940)	total: 53.8s	remaining: 1m 9s
2960:	learn: 0.2029561	test: 0.2141074	best: 0.2141074 (2960)	total: 54.2s	remaining: 1m 9s
2980:	learn: 0.2028190	test: 0.2140334	best: 0.2140334 (2980)	total: 54.5s	remaining: 1m 8s
3000:	learn: 0.2026990	test: 0.2139916	best: 0.2139916 (3000)	total: 54.9s	remaining: 1m 8s
3020:	learn: 0.2025827	test: 0.2139288	best: 0.2139288 (3020)	total: 55.3s	remaining: 1m 8s
3040:	learn: 0.2024652	test: 0.2138882	best: 0.2138882 (3040)	total: 55.7s	remaining: 1m 7s
3060:	learn: 0.2023199	test: 0.2138327	best: 0.2138327 (3060)	total: 56s	remaining: 1m 7s
3080:	learn: 0.2021847	test: 0.2137935	best: 0.2137935 (3080)	total: 56.4s	remaining: 1m 7s
3100:	learn: 0.2020753	test: 0.2137581	best: 0.2137581 (3100)	total: 56.8s	remaining: 1m 6s
3120:	learn: 0.2019437	test: 0.2137057	best: 0.2137057 (3120)	total: 57.2s	remaining: 1m 6s
3140:	learn: 0.2017975	test: 0.2136649	best: 0.2136649 (3140)	total: 57.5s	remaining: 1m 6s
3160:	learn: 0.2016643	test: 0.2136050	best: 0.2136050 (3160)	total: 57.9s	remaining: 1m 5s
3180:	learn: 0.2015439	test: 0.2135779	best: 0.2135779 (3180)	total: 58.3s	remaining: 1m 5s
3200:	learn: 0.2014027	test: 0.2135233	best: 0.2135214 (3198)	total: 58.7s	remaining: 1m 5s
3220:	learn: 0.2012888	test: 0.2135013	best: 0.2135013 (3220)	total: 59s	remaining: 1m 4s
3240:	learn: 0.2011363	test: 0.2134239	best: 0.2134239 (3240)	total: 59.4s	remaining: 1m 4s
3260:	learn: 0.2010183	test: 0.2133547	best: 0.2133547 (3260)	total: 59.8s	remaining: 1m 4s
3280:	learn: 0.2008857	test: 0.2132923	best: 0.2132923 (3280)	total: 1m	remaining: 1m 3s
3300:	learn: 0.2007774	test: 0.2132650	best: 0.2132650 (3300)	total: 1m	remaining: 1m 3s
3320:	learn: 0.2006476	test: 0.2131981	best: 0.2131981 (3320)	total: 1m	remaining: 1m 2s
3340:	learn: 0.2005244	test: 0.2131554	best: 0.2131554 (3340)	total: 1m 1s	remaining: 1m 2s
3360:	learn: 0.2003816	test: 0.2131150	best: 0.2131150 (3360)	total: 1m 1s	remaining: 1m 2s
3380:	learn: 0.2002470	test: 0.2130810	best: 0.2130810 (3380)	total: 1m 2s	remaining: 1m 1s
3400:	learn: 0.2001243	test: 0.2130229	best: 0.2130225 (3399)	total: 1m 2s	remaining: 1m 1s
3420:	learn: 0.2000196	test: 0.2130140	best: 0.2130109 (3407)	total: 1m 2s	remaining: 1m 1s
3440:	learn: 0.1998817	test: 0.2129727	best: 0.2129725 (3439)	total: 1m 3s	remaining: 1m
3460:	learn: 0.1997612	test: 0.2129327	best: 0.2129327 (3460)	total: 1m 3s	remaining: 1m
3480:	learn: 0.1996404	test: 0.2128805	best: 0.2128805 (3479)	total: 1m 3s	remaining: 1m
3500:	learn: 0.1995151	test: 0.2128452	best: 0.2128452 (3500)	total: 1m 4s	remaining: 59.7s
3520:	learn: 0.1994054	test: 0.2128093	best: 0.2128093 (3520)	total: 1m 4s	remaining: 59.3s
3540:	learn: 0.1992880	test: 0.2127954	best: 0.2127938 (3539)	total: 1m 5s	remaining: 59s
3560:	learn: 0.1991621	test: 0.2127524	best: 0.2127519 (3559)	total: 1m 5s	remaining: 58.6s
3580:	learn: 0.1990504	test: 0.2127088	best: 0.2127088 (3580)	total: 1m 5s	remaining: 58.2s
3600:	learn: 0.1989334	test: 0.2126679	best: 0.2126679 (3600)	total: 1m 6s	remaining: 57.9s
3620:	learn: 0.1988064	test: 0.2126368	best: 0.2126368 (3620)	total: 1m 6s	remaining: 57.5s
3640:	learn: 0.1986837	test: 0.2125960	best: 0.2125960 (3640)	total: 1m 6s	remaining: 57.2s
3660:	learn: 0.1985901	test: 0.2125591	best: 0.2125577 (3658)	total: 1m 7s	remaining: 56.8s
3680:	learn: 0.1984788	test: 0.2125165	best: 0.2125165 (3680)	total: 1m 7s	remaining: 56.4s
3700:	learn: 0.1983642	test: 0.2124683	best: 0.2124672 (3699)	total: 1m 8s	remaining: 56.1s
3720:	learn: 0.1982589	test: 0.2124250	best: 0.2124250 (3720)	total: 1m 8s	remaining: 55.7s
3740:	learn: 0.1981261	test: 0.2123786	best: 0.2123752 (3738)	total: 1m 8s	remaining: 55.3s
3760:	learn: 0.1979915	test: 0.2123305	best: 0.2123275 (3758)	total: 1m 9s	remaining: 55s
3780:	learn: 0.1978728	test: 0.2123016	best: 0.2122987 (3767)	total: 1m 9s	remaining: 54.6s
3800:	learn: 0.1977612	test: 0.2122643	best: 0.2122643 (3800)	total: 1m 9s	remaining: 54.3s
3820:	learn: 0.1976461	test: 0.2122100	best: 0.2122100 (3820)	total: 1m 10s	remaining: 53.9s
3840:	learn: 0.1975115	test: 0.2121447	best: 0.2121447 (3840)	total: 1m 10s	remaining: 53.6s
3860:	learn: 0.1974113	test: 0.2121288	best: 0.2121288 (3860)	total: 1m 11s	remaining: 53.2s
3880:	learn: 0.1972608	test: 0.2120619	best: 0.2120594 (3879)	total: 1m 11s	remaining: 52.8s
3900:	learn: 0.1971173	test: 0.2119934	best: 0.2119934 (3900)	total: 1m 11s	remaining: 52.5s
3920:	learn: 0.1969997	test: 0.2119567	best: 0.2119567 (3920)	total: 1m 12s	remaining: 52.1s
3940:	learn: 0.1968866	test: 0.2119338	best: 0.2119338 (3940)	total: 1m 12s	remaining: 51.8s
3960:	learn: 0.1967635	test: 0.2118994	best: 0.2118989 (3949)	total: 1m 12s	remaining: 51.4s
3980:	learn: 0.1966421	test: 0.2118490	best: 0.2118468 (3979)	total: 1m 13s	remaining: 51s
4000:	learn: 0.1965297	test: 0.2118110	best: 0.2118090 (3997)	total: 1m 13s	remaining: 50.7s
4020:	learn: 0.1964192	test: 0.2117767	best: 0.2117757 (4017)	total: 1m 14s	remaining: 50.3s
4040:	learn: 0.1963105	test: 0.2117664	best: 0.2117609 (4031)	total: 1m 14s	remaining: 49.9s
4060:	learn: 0.1961848	test: 0.2117342	best: 0.2117342 (4060)	total: 1m 14s	remaining: 49.6s
4080:	learn: 0.1960647	test: 0.2117085	best: 0.2117085 (4080)	total: 1m 15s	remaining: 49.2s
4100:	learn: 0.1959492	test: 0.2116760	best: 0.2116760 (4100)	total: 1m 15s	remaining: 48.9s
4120:	learn: 0.1958487	test: 0.2116397	best: 0.2116397 (4120)	total: 1m 15s	remaining: 48.5s
4140:	learn: 0.1957418	test: 0.2115964	best: 0.2115964 (4140)	total: 1m 16s	remaining: 48.1s
4160:	learn: 0.1956419	test: 0.2115740	best: 0.2115704 (4158)	total: 1m 16s	remaining: 47.8s
4180:	learn: 0.1955413	test: 0.2115471	best: 0.2115471 (4180)	total: 1m 17s	remaining: 47.4s
4200:	learn: 0.1954359	test: 0.2115148	best: 0.2115148 (4200)	total: 1m 17s	remaining: 47s
4220:	learn: 0.1953453	test: 0.2114893	best: 0.2114867 (4218)	total: 1m 17s	remaining: 46.7s
4240:	learn: 0.1952409	test: 0.2114544	best: 0.2114542 (4239)	total: 1m 18s	remaining: 46.3s
4260:	learn: 0.1951361	test: 0.2114104	best: 0.2114104 (4260)	total: 1m 18s	remaining: 45.9s
4280:	learn: 0.1950357	test: 0.2113936	best: 0.2113922 (4279)	total: 1m 19s	remaining: 45.6s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6645893	test: 0.6644790	best: 0.6644790 (0)	total: 5.34ms	remaining: 5.34ms
1:	learn: 0.6387455	test: 0.6385254	best: 0.6385254 (1)	total: 9.61ms	remaining: 0us
bestTest = 0.6385254376
bestIteration = 1
0:	learn: 0.6400220	test: 0.6398224	best: 0.6398224 (0)	total: 17.8ms	remaining: 2m 5s
20:	learn: 0.3348168	test: 0.3329329	best: 0.3329329 (20)	total: 402ms	remaining: 2m 14s
40:	learn: 0.3030511	test: 0.3002934	best: 0.3002934 (40)	total: 793ms	remaining: 2m 15s
60:	learn: 0.2899779	test: 0.2866054	best: 0.2866054 (60)	total: 1.18s	remaining: 2m 14s
80:	learn: 0.2818727	test: 0.2781330	best: 0.2781330 (80)	total: 1.56s	remaining: 2m 14s
100:	learn: 0.2770053	test: 0.2733906	best: 0.2733906 (100)	total: 1.94s	remaining: 2m 13s
120:	learn: 0.2721739	test: 0.2684801	best: 0.2684801 (120)	total: 2.3s	remaining: 2m 11s
140:	learn: 0.2672212	test: 0.2635352	best: 0.2635352 (140)	total: 2.67s	remaining: 2m 10s
160:	learn: 0.2635021	test: 0.2598518	best: 0.2598518 (160)	total: 3.02s	remaining: 2m 9s
180:	learn: 0.2603973	test: 0.2568493	best: 0.2568493 (180)	total: 3.39s	remaining: 2m 8s
200:	learn: 0.2580964	test: 0.2546913	best: 0.2546913 (200)	total: 3.74s	remaining: 2m 7s
220:	learn: 0.2555617	test: 0.2520822	best: 0.2520822 (220)	total: 4.12s	remaining: 2m 7s
240:	learn: 0.2532272	test: 0.2497962	best: 0.2497962 (240)	total: 4.48s	remaining: 2m 6s
260:	learn: 0.2513278	test: 0.2479324	best: 0.2479324 (260)	total: 4.84s	remaining: 2m 5s
280:	learn: 0.2493126	test: 0.2458465	best: 0.2458465 (280)	total: 5.22s	remaining: 2m 5s
300:	learn: 0.2477790	test: 0.2444383	best: 0.2444383 (300)	total: 5.58s	remaining: 2m 5s
320:	learn: 0.2462487	test: 0.2429910	best: 0.2429910 (320)	total: 5.95s	remaining: 2m 4s
340:	learn: 0.2446993	test: 0.2414133	best: 0.2414133 (340)	total: 6.31s	remaining: 2m 4s
360:	learn: 0.2435219	test: 0.2403359	best: 0.2403359 (360)	total: 6.67s	remaining: 2m 3s
380:	learn: 0.2424481	test: 0.2393612	best: 0.2393612 (380)	total: 7.03s	remaining: 2m 3s
400:	learn: 0.2413013	test: 0.2382754	best: 0.2382754 (400)	total: 7.39s	remaining: 2m 2s
420:	learn: 0.2401776	test: 0.2372493	best: 0.2372493 (420)	total: 7.75s	remaining: 2m 2s
440:	learn: 0.2392055	test: 0.2363271	best: 0.2363271 (440)	total: 8.12s	remaining: 2m 1s
460:	learn: 0.2382256	test: 0.2354423	best: 0.2354423 (460)	total: 8.49s	remaining: 2m 1s
480:	learn: 0.2374630	test: 0.2348321	best: 0.2348321 (480)	total: 8.84s	remaining: 2m
500:	learn: 0.2365432	test: 0.2339515	best: 0.2339515 (500)	total: 9.21s	remaining: 2m
520:	learn: 0.2357470	test: 0.2332495	best: 0.2332495 (520)	total: 9.57s	remaining: 2m
540:	learn: 0.2350715	test: 0.2326432	best: 0.2326432 (540)	total: 9.93s	remaining: 1m 59s
560:	learn: 0.2342439	test: 0.2318895	best: 0.2318895 (560)	total: 10.3s	remaining: 1m 59s
580:	learn: 0.2334506	test: 0.2311879	best: 0.2311879 (580)	total: 10.7s	remaining: 1m 58s
600:	learn: 0.2327639	test: 0.2305851	best: 0.2305851 (600)	total: 11s	remaining: 1m 58s
620:	learn: 0.2321513	test: 0.2300675	best: 0.2300675 (620)	total: 11.4s	remaining: 1m 57s
640:	learn: 0.2314960	test: 0.2295103	best: 0.2295103 (640)	total: 11.7s	remaining: 1m 57s
660:	learn: 0.2308385	test: 0.2289834	best: 0.2289834 (660)	total: 12.1s	remaining: 1m 57s
680:	learn: 0.2303171	test: 0.2285924	best: 0.2285924 (680)	total: 12.4s	remaining: 1m 56s
700:	learn: 0.2297159	test: 0.2280861	best: 0.2280861 (700)	total: 12.8s	remaining: 1m 56s
720:	learn: 0.2292370	test: 0.2276807	best: 0.2276807 (720)	total: 13.2s	remaining: 1m 55s
740:	learn: 0.2287042	test: 0.2272261	best: 0.2272261 (740)	total: 13.5s	remaining: 1m 55s
760:	learn: 0.2281686	test: 0.2268068	best: 0.2268068 (760)	total: 13.9s	remaining: 1m 54s
780:	learn: 0.2277072	test: 0.2264997	best: 0.2264997 (780)	total: 14.3s	remaining: 1m 54s
800:	learn: 0.2272781	test: 0.2261982	best: 0.2261982 (800)	total: 14.6s	remaining: 1m 54s
820:	learn: 0.2268123	test: 0.2258517	best: 0.2258517 (820)	total: 15s	remaining: 1m 53s
840:	learn: 0.2263665	test: 0.2254922	best: 0.2254922 (840)	total: 15.4s	remaining: 1m 53s
860:	learn: 0.2259259	test: 0.2251588	best: 0.2251588 (860)	total: 15.7s	remaining: 1m 53s
880:	learn: 0.2254399	test: 0.2247616	best: 0.2247616 (880)	total: 16.1s	remaining: 1m 52s
900:	learn: 0.2250745	test: 0.2245288	best: 0.2245288 (900)	total: 16.4s	remaining: 1m 52s
920:	learn: 0.2247008	test: 0.2242586	best: 0.2242586 (920)	total: 16.8s	remaining: 1m 51s
940:	learn: 0.2243312	test: 0.2240092	best: 0.2240092 (940)	total: 17.2s	remaining: 1m 51s
960:	learn: 0.2238933	test: 0.2236877	best: 0.2236877 (960)	total: 17.5s	remaining: 1m 51s
980:	learn: 0.2235391	test: 0.2234542	best: 0.2234542 (980)	total: 17.9s	remaining: 1m 50s
1000:	learn: 0.2231076	test: 0.2231274	best: 0.2231274 (1000)	total: 18.3s	remaining: 1m 50s
1020:	learn: 0.2227777	test: 0.2228797	best: 0.2228797 (1020)	total: 18.6s	remaining: 1m 50s
1040:	learn: 0.2224502	test: 0.2226522	best: 0.2226522 (1040)	total: 19s	remaining: 1m 49s
1060:	learn: 0.2220803	test: 0.2223854	best: 0.2223854 (1060)	total: 19.3s	remaining: 1m 49s
1080:	learn: 0.2217245	test: 0.2221495	best: 0.2221495 (1080)	total: 19.7s	remaining: 1m 48s
1100:	learn: 0.2214392	test: 0.2219483	best: 0.2219483 (1100)	total: 20.1s	remaining: 1m 48s
1120:	learn: 0.2211029	test: 0.2217503	best: 0.2217503 (1120)	total: 20.4s	remaining: 1m 48s
1140:	learn: 0.2207947	test: 0.2215209	best: 0.2215209 (1140)	total: 20.8s	remaining: 1m 47s
1160:	learn: 0.2204378	test: 0.2212647	best: 0.2212647 (1160)	total: 21.2s	remaining: 1m 47s
1180:	learn: 0.2201023	test: 0.2209813	best: 0.2209813 (1180)	total: 21.5s	remaining: 1m 47s
1200:	learn: 0.2197885	test: 0.2207512	best: 0.2207512 (1200)	total: 21.9s	remaining: 1m 46s
1220:	learn: 0.2194265	test: 0.2204782	best: 0.2204782 (1220)	total: 22.3s	remaining: 1m 46s
1240:	learn: 0.2191225	test: 0.2202336	best: 0.2202336 (1240)	total: 22.6s	remaining: 1m 46s
1260:	learn: 0.2188784	test: 0.2200847	best: 0.2200847 (1260)	total: 23s	remaining: 1m 45s
1280:	learn: 0.2185995	test: 0.2198869	best: 0.2198869 (1280)	total: 23.4s	remaining: 1m 45s
1300:	learn: 0.2182632	test: 0.2196409	best: 0.2196409 (1300)	total: 23.7s	remaining: 1m 44s
1320:	learn: 0.2179875	test: 0.2194731	best: 0.2194731 (1320)	total: 24.1s	remaining: 1m 44s
1340:	learn: 0.2177076	test: 0.2192938	best: 0.2192938 (1340)	total: 24.5s	remaining: 1m 44s
1360:	learn: 0.2174280	test: 0.2191181	best: 0.2191181 (1360)	total: 24.8s	remaining: 1m 43s
1380:	learn: 0.2171888	test: 0.2189750	best: 0.2189744 (1379)	total: 25.2s	remaining: 1m 43s
1400:	learn: 0.2169336	test: 0.2188136	best: 0.2188136 (1400)	total: 25.6s	remaining: 1m 43s
1420:	learn: 0.2167091	test: 0.2186835	best: 0.2186835 (1420)	total: 25.9s	remaining: 1m 42s
1440:	learn: 0.2164679	test: 0.2185527	best: 0.2185527 (1440)	total: 26.3s	remaining: 1m 42s
1460:	learn: 0.2162145	test: 0.2183655	best: 0.2183655 (1460)	total: 26.7s	remaining: 1m 42s
1480:	learn: 0.2159951	test: 0.2182555	best: 0.2182555 (1480)	total: 27s	remaining: 1m 41s
1500:	learn: 0.2157470	test: 0.2181019	best: 0.2181019 (1500)	total: 27.4s	remaining: 1m 41s
1520:	learn: 0.2155682	test: 0.2179956	best: 0.2179956 (1520)	total: 27.7s	remaining: 1m 41s
1540:	learn: 0.2153330	test: 0.2178530	best: 0.2178530 (1540)	total: 28.1s	remaining: 1m 40s
1560:	learn: 0.2151068	test: 0.2177304	best: 0.2177304 (1560)	total: 28.5s	remaining: 1m 40s
1580:	learn: 0.2148892	test: 0.2175856	best: 0.2175856 (1580)	total: 28.8s	remaining: 1m 39s
1600:	learn: 0.2146931	test: 0.2174848	best: 0.2174848 (1600)	total: 29.2s	remaining: 1m 39s
1620:	learn: 0.2144782	test: 0.2173785	best: 0.2173785 (1620)	total: 29.6s	remaining: 1m 39s
1640:	learn: 0.2142835	test: 0.2172841	best: 0.2172841 (1640)	total: 29.9s	remaining: 1m 38s
1660:	learn: 0.2140193	test: 0.2171331	best: 0.2171331 (1660)	total: 30.3s	remaining: 1m 38s
1680:	learn: 0.2138331	test: 0.2170549	best: 0.2170549 (1680)	total: 30.7s	remaining: 1m 38s
1700:	learn: 0.2136435	test: 0.2169767	best: 0.2169767 (1700)	total: 31s	remaining: 1m 37s
1720:	learn: 0.2134674	test: 0.2169093	best: 0.2169093 (1720)	total: 31.4s	remaining: 1m 37s
1740:	learn: 0.2132520	test: 0.2167860	best: 0.2167860 (1740)	total: 31.8s	remaining: 1m 37s
1760:	learn: 0.2130288	test: 0.2166605	best: 0.2166605 (1760)	total: 32.2s	remaining: 1m 36s
1780:	learn: 0.2128478	test: 0.2165368	best: 0.2165368 (1780)	total: 32.5s	remaining: 1m 36s
1800:	learn: 0.2126142	test: 0.2163954	best: 0.2163954 (1800)	total: 32.9s	remaining: 1m 35s
1820:	learn: 0.2124372	test: 0.2163205	best: 0.2163205 (1820)	total: 33.2s	remaining: 1m 35s
1840:	learn: 0.2122529	test: 0.2162461	best: 0.2162450 (1839)	total: 33.6s	remaining: 1m 35s
1860:	learn: 0.2120600	test: 0.2161057	best: 0.2161057 (1860)	total: 34s	remaining: 1m 34s
1880:	learn: 0.2119167	test: 0.2160308	best: 0.2160300 (1879)	total: 34.4s	remaining: 1m 34s
1900:	learn: 0.2117501	test: 0.2159700	best: 0.2159700 (1900)	total: 34.7s	remaining: 1m 34s
1920:	learn: 0.2115960	test: 0.2159047	best: 0.2159047 (1920)	total: 35.1s	remaining: 1m 33s
1940:	learn: 0.2113899	test: 0.2157835	best: 0.2157835 (1940)	total: 35.5s	remaining: 1m 33s
1960:	learn: 0.2112204	test: 0.2157266	best: 0.2157251 (1959)	total: 35.8s	remaining: 1m 33s
1980:	learn: 0.2110643	test: 0.2156695	best: 0.2156685 (1979)	total: 36.2s	remaining: 1m 32s
2000:	learn: 0.2108956	test: 0.2156060	best: 0.2156043 (1997)	total: 36.6s	remaining: 1m 32s
2020:	learn: 0.2107039	test: 0.2154931	best: 0.2154931 (2020)	total: 36.9s	remaining: 1m 32s
2040:	learn: 0.2105030	test: 0.2153878	best: 0.2153878 (2040)	total: 37.3s	remaining: 1m 31s
2060:	learn: 0.2102851	test: 0.2152538	best: 0.2152538 (2060)	total: 37.7s	remaining: 1m 31s
2080:	learn: 0.2100906	test: 0.2151566	best: 0.2151566 (2080)	total: 38s	remaining: 1m 30s
2100:	learn: 0.2099196	test: 0.2150539	best: 0.2150539 (2100)	total: 38.4s	remaining: 1m 30s
2120:	learn: 0.2097455	test: 0.2149621	best: 0.2149621 (2120)	total: 38.8s	remaining: 1m 30s
2140:	learn: 0.2095618	test: 0.2148672	best: 0.2148672 (2140)	total: 39.2s	remaining: 1m 29s
2160:	learn: 0.2093981	test: 0.2147886	best: 0.2147886 (2160)	total: 39.5s	remaining: 1m 29s
2180:	learn: 0.2092143	test: 0.2146812	best: 0.2146792 (2178)	total: 39.9s	remaining: 1m 29s
2200:	learn: 0.2090406	test: 0.2145725	best: 0.2145725 (2200)	total: 40.3s	remaining: 1m 28s
2220:	learn: 0.2088522	test: 0.2144879	best: 0.2144872 (2219)	total: 40.6s	remaining: 1m 28s
2240:	learn: 0.2086573	test: 0.2144301	best: 0.2144293 (2239)	total: 41s	remaining: 1m 28s
2260:	learn: 0.2085055	test: 0.2143656	best: 0.2143656 (2260)	total: 41.4s	remaining: 1m 27s
2280:	learn: 0.2083348	test: 0.2142699	best: 0.2142699 (2280)	total: 41.7s	remaining: 1m 27s
2300:	learn: 0.2081524	test: 0.2141897	best: 0.2141897 (2300)	total: 42.1s	remaining: 1m 27s
2320:	learn: 0.2080003	test: 0.2141203	best: 0.2141203 (2320)	total: 42.5s	remaining: 1m 26s
2340:	learn: 0.2078278	test: 0.2140325	best: 0.2140325 (2340)	total: 42.9s	remaining: 1m 26s
2360:	learn: 0.2076435	test: 0.2139514	best: 0.2139514 (2360)	total: 43.2s	remaining: 1m 26s
2380:	learn: 0.2074409	test: 0.2138100	best: 0.2138083 (2379)	total: 43.6s	remaining: 1m 25s
2400:	learn: 0.2072944	test: 0.2137455	best: 0.2137451 (2399)	total: 44s	remaining: 1m 25s
2420:	learn: 0.2071188	test: 0.2136517	best: 0.2136517 (2420)	total: 44.3s	remaining: 1m 24s
2440:	learn: 0.2069686	test: 0.2135872	best: 0.2135872 (2440)	total: 44.7s	remaining: 1m 24s
2460:	learn: 0.2068299	test: 0.2135141	best: 0.2135141 (2460)	total: 45.1s	remaining: 1m 24s
2480:	learn: 0.2066736	test: 0.2134444	best: 0.2134444 (2480)	total: 45.5s	remaining: 1m 23s
2500:	learn: 0.2065210	test: 0.2133501	best: 0.2133501 (2500)	total: 45.8s	remaining: 1m 23s
2520:	learn: 0.2063806	test: 0.2133139	best: 0.2133119 (2519)	total: 46.2s	remaining: 1m 23s
2540:	learn: 0.2062042	test: 0.2132208	best: 0.2132208 (2540)	total: 46.6s	remaining: 1m 22s
2560:	learn: 0.2060753	test: 0.2131639	best: 0.2131639 (2560)	total: 46.9s	remaining: 1m 22s
2580:	learn: 0.2059066	test: 0.2130944	best: 0.2130944 (2580)	total: 47.3s	remaining: 1m 22s
2600:	learn: 0.2057851	test: 0.2130578	best: 0.2130563 (2599)	total: 47.7s	remaining: 1m 21s
2620:	learn: 0.2056380	test: 0.2129805	best: 0.2129805 (2620)	total: 48.1s	remaining: 1m 21s
2640:	learn: 0.2054955	test: 0.2129317	best: 0.2129317 (2640)	total: 48.4s	remaining: 1m 21s
2660:	learn: 0.2053168	test: 0.2128324	best: 0.2128324 (2660)	total: 48.8s	remaining: 1m 20s
2680:	learn: 0.2051647	test: 0.2127549	best: 0.2127549 (2680)	total: 49.2s	remaining: 1m 20s
2700:	learn: 0.2050181	test: 0.2126895	best: 0.2126895 (2700)	total: 49.6s	remaining: 1m 19s
2720:	learn: 0.2048078	test: 0.2125793	best: 0.2125793 (2720)	total: 49.9s	remaining: 1m 19s
2740:	learn: 0.2046757	test: 0.2125247	best: 0.2125247 (2740)	total: 50.3s	remaining: 1m 19s
2760:	learn: 0.2045305	test: 0.2124468	best: 0.2124465 (2759)	total: 50.7s	remaining: 1m 18s
2780:	learn: 0.2043769	test: 0.2123794	best: 0.2123794 (2780)	total: 51.1s	remaining: 1m 18s
2800:	learn: 0.2042130	test: 0.2123294	best: 0.2123294 (2800)	total: 51.4s	remaining: 1m 18s
2820:	learn: 0.2040750	test: 0.2122722	best: 0.2122722 (2820)	total: 51.8s	remaining: 1m 17s
2840:	learn: 0.2039304	test: 0.2122379	best: 0.2122378 (2838)	total: 52.2s	remaining: 1m 17s
2860:	learn: 0.2038110	test: 0.2121930	best: 0.2121923 (2859)	total: 52.5s	remaining: 1m 17s
2880:	learn: 0.2036735	test: 0.2121313	best: 0.2121313 (2880)	total: 52.9s	remaining: 1m 16s
2900:	learn: 0.2035400	test: 0.2120719	best: 0.2120719 (2900)	total: 53.3s	remaining: 1m 16s
2920:	learn: 0.2033855	test: 0.2119948	best: 0.2119948 (2920)	total: 53.7s	remaining: 1m 16s
2940:	learn: 0.2032535	test: 0.2119437	best: 0.2119437 (2940)	total: 54s	remaining: 1m 15s
2960:	learn: 0.2031018	test: 0.2118715	best: 0.2118715 (2960)	total: 54.4s	remaining: 1m 15s
2980:	learn: 0.2029709	test: 0.2118358	best: 0.2118354 (2979)	total: 54.8s	remaining: 1m 14s
3000:	learn: 0.2028090	test: 0.2117631	best: 0.2117595 (2999)	total: 55.1s	remaining: 1m 14s
3020:	learn: 0.2026558	test: 0.2117023	best: 0.2117023 (3020)	total: 55.5s	remaining: 1m 14s
3040:	learn: 0.2025252	test: 0.2116409	best: 0.2116409 (3040)	total: 55.9s	remaining: 1m 13s
3060:	learn: 0.2023989	test: 0.2115828	best: 0.2115828 (3060)	total: 56.3s	remaining: 1m 13s
3080:	learn: 0.2022756	test: 0.2115546	best: 0.2115546 (3080)	total: 56.6s	remaining: 1m 13s
3100:	learn: 0.2021441	test: 0.2114983	best: 0.2114983 (3100)	total: 57s	remaining: 1m 12s
3120:	learn: 0.2020171	test: 0.2114589	best: 0.2114589 (3120)	total: 57.4s	remaining: 1m 12s
3140:	learn: 0.2019058	test: 0.2114210	best: 0.2114210 (3140)	total: 57.8s	remaining: 1m 12s
3160:	learn: 0.2017437	test: 0.2113451	best: 0.2113451 (3160)	total: 58.2s	remaining: 1m 11s
3180:	learn: 0.2016331	test: 0.2112931	best: 0.2112931 (3180)	total: 58.5s	remaining: 1m 11s
3200:	learn: 0.2015252	test: 0.2112590	best: 0.2112582 (3199)	total: 58.9s	remaining: 1m 10s
3220:	learn: 0.2013886	test: 0.2111999	best: 0.2111999 (3220)	total: 59.3s	remaining: 1m 10s
3240:	learn: 0.2012692	test: 0.2111589	best: 0.2111589 (3240)	total: 59.7s	remaining: 1m 10s
3260:	learn: 0.2011146	test: 0.2110956	best: 0.2110956 (3260)	total: 1m	remaining: 1m 9s
3280:	learn: 0.2010149	test: 0.2110756	best: 0.2110756 (3280)	total: 1m	remaining: 1m 9s
3300:	learn: 0.2008968	test: 0.2110627	best: 0.2110552 (3297)	total: 1m	remaining: 1m 9s
3320:	learn: 0.2007735	test: 0.2110081	best: 0.2110081 (3320)	total: 1m 1s	remaining: 1m 8s
3340:	learn: 0.2006455	test: 0.2109790	best: 0.2109790 (3340)	total: 1m 1s	remaining: 1m 8s
3360:	learn: 0.2005448	test: 0.2109301	best: 0.2109301 (3360)	total: 1m 1s	remaining: 1m 8s
3380:	learn: 0.2004224	test: 0.2108880	best: 0.2108875 (3379)	total: 1m 2s	remaining: 1m 7s
3400:	learn: 0.2002924	test: 0.2108481	best: 0.2108475 (3397)	total: 1m 2s	remaining: 1m 7s
3420:	learn: 0.2001828	test: 0.2108023	best: 0.2108021 (3419)	total: 1m 3s	remaining: 1m 7s
3440:	learn: 0.2000636	test: 0.2107607	best: 0.2107591 (3439)	total: 1m 3s	remaining: 1m 6s
3460:	learn: 0.1999315	test: 0.2107100	best: 0.2107074 (3459)	total: 1m 3s	remaining: 1m 6s
3480:	learn: 0.1997805	test: 0.2106231	best: 0.2106223 (3477)	total: 1m 4s	remaining: 1m 5s
3500:	learn: 0.1996586	test: 0.2105685	best: 0.2105685 (3500)	total: 1m 4s	remaining: 1m 5s
3520:	learn: 0.1995558	test: 0.2105365	best: 0.2105365 (3520)	total: 1m 4s	remaining: 1m 5s
3540:	learn: 0.1994075	test: 0.2104548	best: 0.2104536 (3539)	total: 1m 5s	remaining: 1m 4s
3560:	learn: 0.1992870	test: 0.2104114	best: 0.2104114 (3560)	total: 1m 5s	remaining: 1m 4s
3580:	learn: 0.1991746	test: 0.2103816	best: 0.2103794 (3579)	total: 1m 6s	remaining: 1m 4s
3600:	learn: 0.1990779	test: 0.2103636	best: 0.2103615 (3599)	total: 1m 6s	remaining: 1m 3s
3620:	learn: 0.1989742	test: 0.2103233	best: 0.2103230 (3619)	total: 1m 6s	remaining: 1m 3s
3640:	learn: 0.1988643	test: 0.2102762	best: 0.2102762 (3640)	total: 1m 7s	remaining: 1m 3s
3660:	learn: 0.1987527	test: 0.2102488	best: 0.2102488 (3660)	total: 1m 7s	remaining: 1m 2s
3680:	learn: 0.1986353	test: 0.2102122	best: 0.2102122 (3680)	total: 1m 8s	remaining: 1m 2s
3700:	learn: 0.1985059	test: 0.2101793	best: 0.2101793 (3700)	total: 1m 8s	remaining: 1m 2s
3720:	learn: 0.1983773	test: 0.2101237	best: 0.2101237 (3720)	total: 1m 8s	remaining: 1m 1s
3740:	learn: 0.1982747	test: 0.2100945	best: 0.2100945 (3740)	total: 1m 9s	remaining: 1m 1s
3760:	learn: 0.1981679	test: 0.2100690	best: 0.2100690 (3760)	total: 1m 9s	remaining: 1m
3780:	learn: 0.1980561	test: 0.2100229	best: 0.2100224 (3779)	total: 1m 9s	remaining: 1m
3800:	learn: 0.1979491	test: 0.2099734	best: 0.2099734 (3800)	total: 1m 10s	remaining: 1m
3820:	learn: 0.1978611	test: 0.2099409	best: 0.2099406 (3818)	total: 1m 10s	remaining: 59.9s
3840:	learn: 0.1977432	test: 0.2098982	best: 0.2098982 (3840)	total: 1m 11s	remaining: 59.5s
3860:	learn: 0.1976431	test: 0.2098735	best: 0.2098735 (3860)	total: 1m 11s	remaining: 59.2s
3880:	learn: 0.1975242	test: 0.2098284	best: 0.2098284 (3880)	total: 1m 11s	remaining: 58.8s
3900:	learn: 0.1974055	test: 0.2097756	best: 0.2097756 (3900)	total: 1m 12s	remaining: 58.5s
3920:	learn: 0.1973122	test: 0.2097437	best: 0.2097437 (3920)	total: 1m 12s	remaining: 58.1s
3940:	learn: 0.1972057	test: 0.2097066	best: 0.2097060 (3937)	total: 1m 13s	remaining: 57.7s
3960:	learn: 0.1971092	test: 0.2096636	best: 0.2096636 (3960)	total: 1m 13s	remaining: 57.4s
3980:	learn: 0.1969703	test: 0.2095998	best: 0.2095998 (3980)	total: 1m 13s	remaining: 57s
4000:	learn: 0.1968758	test: 0.2095595	best: 0.2095595 (4000)	total: 1m 14s	remaining: 56.7s
4020:	learn: 0.1967638	test: 0.2095151	best: 0.2095151 (4020)	total: 1m 14s	remaining: 56.3s
4040:	learn: 0.1966716	test: 0.2094884	best: 0.2094881 (4039)	total: 1m 14s	remaining: 56s
4060:	learn: 0.1965663	test: 0.2094644	best: 0.2094635 (4059)	total: 1m 15s	remaining: 55.6s
4080:	learn: 0.1964616	test: 0.2094292	best: 0.2094292 (4080)	total: 1m 15s	remaining: 55.2s
4100:	learn: 0.1963591	test: 0.2093988	best: 0.2093988 (4100)	total: 1m 16s	remaining: 54.9s
4120:	learn: 0.1962559	test: 0.2093850	best: 0.2093843 (4116)	total: 1m 16s	remaining: 54.5s
4140:	learn: 0.1961387	test: 0.2093409	best: 0.2093409 (4140)	total: 1m 16s	remaining: 54.1s
4160:	learn: 0.1960361	test: 0.2092983	best: 0.2092983 (4160)	total: 1m 17s	remaining: 53.8s
4180:	learn: 0.1959143	test: 0.2092598	best: 0.2092598 (4180)	total: 1m 17s	remaining: 53.4s
4200:	learn: 0.1958116	test: 0.2092257	best: 0.2092257 (4200)	total: 1m 18s	remaining: 53s
4220:	learn: 0.1957011	test: 0.2091872	best: 0.2091869 (4219)	total: 1m 18s	remaining: 52.7s
4240:	learn: 0.1955781	test: 0.2091529	best: 0.2091509 (4239)	total: 1m 18s	remaining: 52.3s
4260:	learn: 0.1954622	test: 0.2091111	best: 0.2091101 (4259)	total: 1m 19s	remaining: 52s
4280:	learn: 0.1953589	test: 0.2090888	best: 0.2090888 (4280)	total: 1m 19s	remaining: 51.6s

Saving c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl
	0.9581	 = Validation score   (roc_auc)
	966.62s	 = Training   runtime
	4.22s	 = Validation runtime
	16006.0	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Fitting model: XGBoost_BAG_L1 ... Training model for up to 31136.60s of the 31136.60s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47381
[50]	validation_0-logloss:0.26494
[100]	validation_0-logloss:0.24920
[150]	validation_0-logloss:0.24177
[200]	validation_0-logloss:0.23672
[250]	validation_0-logloss:0.23322
[300]	validation_0-logloss:0.22976
[350]	validation_0-logloss:0.22735
[400]	validation_0-logloss:0.22509
[450]	validation_0-logloss:0.22342
[500]	validation_0-logloss:0.22167
[550]	validation_0-logloss:0.22042
[600]	validation_0-logloss:0.21928
[650]	validation_0-logloss:0.21837
[700]	validation_0-logloss:0.21741
[750]	validation_0-logloss:0.21673
[800]	validation_0-logloss:0.21600
[850]	validation_0-logloss:0.21521
[900]	validation_0-logloss:0.21469
[950]	validation_0-logloss:0.21433
[1000]	validation_0-logloss:0.21374
[1050]	validation_0-logloss:0.21331
[1100]	validation_0-logloss:0.21294
[1150]	validation_0-logloss:0.21265
[1200]	validation_0-logloss:0.21232
[1250]	validation_0-logloss:0.21212
[1300]	validation_0-logloss:0.21171
[1350]	validation_0-logloss:0.21142
[1400]	validation_0-logloss:0.21120
[1450]	validation_0-logloss:0.21107
[1500]	validation_0-logloss:0.21080
[1550]	validation_0-logloss:0.21060
[1600]	validation_0-logloss:0.21044
[1650]	validation_0-logloss:0.21023
[1700]	validation_0-logloss:0.21002
[1750]	validation_0-logloss:0.20982
[1800]	validation_0-logloss:0.20960
[1850]	validation_0-logloss:0.20945
[1900]	validation_0-logloss:0.20937
[1950]	validation_0-logloss:0.20931
[2000]	validation_0-logloss:0.20927
[2050]	validation_0-logloss:0.20911
[2100]	validation_0-logloss:0.20897
[2150]	validation_0-logloss:0.20887
[2200]	validation_0-logloss:0.20886
[2250]	validation_0-logloss:0.20880
[2300]	validation_0-logloss:0.20871
[2350]	validation_0-logloss:0.20862
[2400]	validation_0-logloss:0.20860
[2450]	validation_0-logloss:0.20861
[2500]	validation_0-logloss:0.20860
[2550]	validation_0-logloss:0.20856
[2600]	validation_0-logloss:0.20843
[2650]	validation_0-logloss:0.20843
[2700]	validation_0-logloss:0.20838
[2750]	validation_0-logloss:0.20838
[2800]	validation_0-logloss:0.20840
[2850]	validation_0-logloss:0.20843
[2900]	validation_0-logloss:0.20841
[2950]	validation_0-logloss:0.20849
[3000]	validation_0-logloss:0.20850
[3050]	validation_0-logloss:0.20846
[3100]	validation_0-logloss:0.20846
[3150]	validation_0-logloss:0.20854
[3200]	validation_0-logloss:0.20853
[3250]	validation_0-logloss:0.20861
[3300]	validation_0-logloss:0.20869
[3350]	validation_0-logloss:0.20868
[3400]	validation_0-logloss:0.20879
[3450]	validation_0-logloss:0.20881
[3500]	validation_0-logloss:0.20881
[3522]	validation_0-logloss:0.20887

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47401
[50]	validation_0-logloss:0.26585
[100]	validation_0-logloss:0.25120
[150]	validation_0-logloss:0.24362
[200]	validation_0-logloss:0.23819
[250]	validation_0-logloss:0.23435
[300]	validation_0-logloss:0.23093
[350]	validation_0-logloss:0.22868
[400]	validation_0-logloss:0.22644
[450]	validation_0-logloss:0.22466
[500]	validation_0-logloss:0.22296
[550]	validation_0-logloss:0.22177
[600]	validation_0-logloss:0.22054
[650]	validation_0-logloss:0.21977
[700]	validation_0-logloss:0.21857
[750]	validation_0-logloss:0.21782
[800]	validation_0-logloss:0.21706
[850]	validation_0-logloss:0.21640
[900]	validation_0-logloss:0.21575
[950]	validation_0-logloss:0.21525
[1000]	validation_0-logloss:0.21478
[1050]	validation_0-logloss:0.21438
[1100]	validation_0-logloss:0.21393
[1150]	validation_0-logloss:0.21366
[1200]	validation_0-logloss:0.21348
[1250]	validation_0-logloss:0.21308
[1300]	validation_0-logloss:0.21284
[1350]	validation_0-logloss:0.21252
[1400]	validation_0-logloss:0.21217
[1450]	validation_0-logloss:0.21198
[1500]	validation_0-logloss:0.21166
[1550]	validation_0-logloss:0.21153
[1600]	validation_0-logloss:0.21137
[1650]	validation_0-logloss:0.21119
[1700]	validation_0-logloss:0.21109
[1750]	validation_0-logloss:0.21088
[1800]	validation_0-logloss:0.21058
[1850]	validation_0-logloss:0.21039
[1900]	validation_0-logloss:0.21028
[1950]	validation_0-logloss:0.21004
[2000]	validation_0-logloss:0.21002
[2050]	validation_0-logloss:0.20994
[2100]	validation_0-logloss:0.20995
[2150]	validation_0-logloss:0.20991
[2200]	validation_0-logloss:0.20990
[2250]	validation_0-logloss:0.20983
[2300]	validation_0-logloss:0.20973
[2350]	validation_0-logloss:0.20962
[2400]	validation_0-logloss:0.20950
[2450]	validation_0-logloss:0.20945
[2500]	validation_0-logloss:0.20944
[2550]	validation_0-logloss:0.20936
[2600]	validation_0-logloss:0.20930
[2650]	validation_0-logloss:0.20931
[2700]	validation_0-logloss:0.20925
[2750]	validation_0-logloss:0.20913
[2800]	validation_0-logloss:0.20911
[2850]	validation_0-logloss:0.20905
[2900]	validation_0-logloss:0.20903
[2950]	validation_0-logloss:0.20904
[3000]	validation_0-logloss:0.20904
[3050]	validation_0-logloss:0.20905
[3100]	validation_0-logloss:0.20901
[3150]	validation_0-logloss:0.20902
[3200]	validation_0-logloss:0.20903
[3250]	validation_0-logloss:0.20900
[3300]	validation_0-logloss:0.20899
[3350]	validation_0-logloss:0.20893
[3400]	validation_0-logloss:0.20889
[3450]	validation_0-logloss:0.20892
[3500]	validation_0-logloss:0.20896
[3550]	validation_0-logloss:0.20895
[3600]	validation_0-logloss:0.20891
[3650]	validation_0-logloss:0.20892
[3700]	validation_0-logloss:0.20893
[3750]	validation_0-logloss:0.20892
[3800]	validation_0-logloss:0.20887
[3850]	validation_0-logloss:0.20897
[3900]	validation_0-logloss:0.20902
[3950]	validation_0-logloss:0.20907
[4000]	validation_0-logloss:0.20904
[4050]	validation_0-logloss:0.20909
[4100]	validation_0-logloss:0.20909
[4150]	validation_0-logloss:0.20915
[4200]	validation_0-logloss:0.20918
[4250]	validation_0-logloss:0.20924
[4300]	validation_0-logloss:0.20929
[4350]	validation_0-logloss:0.20933
[4400]	validation_0-logloss:0.20939
[4450]	validation_0-logloss:0.20948
[4500]	validation_0-logloss:0.20957
[4550]	validation_0-logloss:0.20964
[4600]	validation_0-logloss:0.20973
[4650]	validation_0-logloss:0.20980
[4700]	validation_0-logloss:0.20987
[4750]	validation_0-logloss:0.20990
[4800]	validation_0-logloss:0.20991
[4850]	validation_0-logloss:0.20996
[4900]	validation_0-logloss:0.21008
[4950]	validation_0-logloss:0.21016
[4967]	validation_0-logloss:0.21020

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47405
[50]	validation_0-logloss:0.26652
[100]	validation_0-logloss:0.25225
[150]	validation_0-logloss:0.24502
[200]	validation_0-logloss:0.24007
[250]	validation_0-logloss:0.23628
[300]	validation_0-logloss:0.23308
[350]	validation_0-logloss:0.23066
[400]	validation_0-logloss:0.22848
[450]	validation_0-logloss:0.22722
[500]	validation_0-logloss:0.22566
[550]	validation_0-logloss:0.22440
[600]	validation_0-logloss:0.22340
[650]	validation_0-logloss:0.22243
[700]	validation_0-logloss:0.22157
[750]	validation_0-logloss:0.22049
[800]	validation_0-logloss:0.21977
[850]	validation_0-logloss:0.21935
[900]	validation_0-logloss:0.21844
[950]	validation_0-logloss:0.21796
[1000]	validation_0-logloss:0.21746
[1050]	validation_0-logloss:0.21704
[1100]	validation_0-logloss:0.21661
[1150]	validation_0-logloss:0.21627
[1200]	validation_0-logloss:0.21592
[1250]	validation_0-logloss:0.21571
[1300]	validation_0-logloss:0.21532
[1350]	validation_0-logloss:0.21518
[1400]	validation_0-logloss:0.21501
[1450]	validation_0-logloss:0.21478
[1500]	validation_0-logloss:0.21464
[1550]	validation_0-logloss:0.21451
[1600]	validation_0-logloss:0.21441
[1650]	validation_0-logloss:0.21426
[1700]	validation_0-logloss:0.21417
[1750]	validation_0-logloss:0.21407
[1800]	validation_0-logloss:0.21394
[1850]	validation_0-logloss:0.21384
[1900]	validation_0-logloss:0.21373
[1950]	validation_0-logloss:0.21372
[2000]	validation_0-logloss:0.21362
[2050]	validation_0-logloss:0.21359
[2100]	validation_0-logloss:0.21355
[2150]	validation_0-logloss:0.21357
[2200]	validation_0-logloss:0.21348
[2250]	validation_0-logloss:0.21344
[2300]	validation_0-logloss:0.21342
[2350]	validation_0-logloss:0.21343
[2400]	validation_0-logloss:0.21336
[2450]	validation_0-logloss:0.21333
[2500]	validation_0-logloss:0.21343
[2550]	validation_0-logloss:0.21345
[2600]	validation_0-logloss:0.21348
[2650]	validation_0-logloss:0.21341
[2700]	validation_0-logloss:0.21331
[2750]	validation_0-logloss:0.21330
[2800]	validation_0-logloss:0.21329
[2850]	validation_0-logloss:0.21335
[2900]	validation_0-logloss:0.21339
[2950]	validation_0-logloss:0.21344
[3000]	validation_0-logloss:0.21344
[3050]	validation_0-logloss:0.21344
[3100]	validation_0-logloss:0.21339
[3150]	validation_0-logloss:0.21346
[3200]	validation_0-logloss:0.21357
[3250]	validation_0-logloss:0.21367
[3300]	validation_0-logloss:0.21364
[3350]	validation_0-logloss:0.21366
[3400]	validation_0-logloss:0.21381
[3450]	validation_0-logloss:0.21389
[3500]	validation_0-logloss:0.21392
[3550]	validation_0-logloss:0.21398
[3577]	validation_0-logloss:0.21406

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47378
[50]	validation_0-logloss:0.26329
[100]	validation_0-logloss:0.24897
[150]	validation_0-logloss:0.24134
[200]	validation_0-logloss:0.23637
[250]	validation_0-logloss:0.23258
[300]	validation_0-logloss:0.22965
[350]	validation_0-logloss:0.22726
[400]	validation_0-logloss:0.22513
[450]	validation_0-logloss:0.22347
[500]	validation_0-logloss:0.22184
[550]	validation_0-logloss:0.22042
[600]	validation_0-logloss:0.21922
[650]	validation_0-logloss:0.21833
[700]	validation_0-logloss:0.21755
[750]	validation_0-logloss:0.21689
[800]	validation_0-logloss:0.21599
[850]	validation_0-logloss:0.21529
[900]	validation_0-logloss:0.21460
[950]	validation_0-logloss:0.21415
[1000]	validation_0-logloss:0.21364
[1050]	validation_0-logloss:0.21337
[1100]	validation_0-logloss:0.21309
[1150]	validation_0-logloss:0.21281
[1200]	validation_0-logloss:0.21239
[1250]	validation_0-logloss:0.21226
[1300]	validation_0-logloss:0.21202
[1350]	validation_0-logloss:0.21174
[1400]	validation_0-logloss:0.21162
[1450]	validation_0-logloss:0.21131
[1500]	validation_0-logloss:0.21110
[1550]	validation_0-logloss:0.21101
[1600]	validation_0-logloss:0.21088
[1650]	validation_0-logloss:0.21077
[1700]	validation_0-logloss:0.21071
[1750]	validation_0-logloss:0.21055
[1800]	validation_0-logloss:0.21036
[1850]	validation_0-logloss:0.21024
[1900]	validation_0-logloss:0.21016
[1950]	validation_0-logloss:0.20995
[2000]	validation_0-logloss:0.20987
[2050]	validation_0-logloss:0.20982
[2100]	validation_0-logloss:0.20971
[2150]	validation_0-logloss:0.20965
[2200]	validation_0-logloss:0.20958
[2250]	validation_0-logloss:0.20945
[2300]	validation_0-logloss:0.20937
[2350]	validation_0-logloss:0.20924
[2400]	validation_0-logloss:0.20919
[2450]	validation_0-logloss:0.20904
[2500]	validation_0-logloss:0.20896
[2550]	validation_0-logloss:0.20897
[2600]	validation_0-logloss:0.20898
[2650]	validation_0-logloss:0.20895
[2700]	validation_0-logloss:0.20888
[2750]	validation_0-logloss:0.20890
[2800]	validation_0-logloss:0.20890
[2850]	validation_0-logloss:0.20895
[2900]	validation_0-logloss:0.20894
[2950]	validation_0-logloss:0.20889
[3000]	validation_0-logloss:0.20890
[3050]	validation_0-logloss:0.20888
[3100]	validation_0-logloss:0.20889
[3150]	validation_0-logloss:0.20887
[3200]	validation_0-logloss:0.20883
[3250]	validation_0-logloss:0.20888
[3300]	validation_0-logloss:0.20888
[3350]	validation_0-logloss:0.20887
[3400]	validation_0-logloss:0.20894
[3450]	validation_0-logloss:0.20905
[3500]	validation_0-logloss:0.20906
[3550]	validation_0-logloss:0.20907
[3600]	validation_0-logloss:0.20914
[3650]	validation_0-logloss:0.20922
[3700]	validation_0-logloss:0.20923
[3750]	validation_0-logloss:0.20925
[3800]	validation_0-logloss:0.20925
[3850]	validation_0-logloss:0.20934
[3900]	validation_0-logloss:0.20939
[3950]	validation_0-logloss:0.20939
[4000]	validation_0-logloss:0.20952
[4050]	validation_0-logloss:0.20952
[4100]	validation_0-logloss:0.20959
[4150]	validation_0-logloss:0.20966
[4200]	validation_0-logloss:0.20970
[4250]	validation_0-logloss:0.20974
[4300]	validation_0-logloss:0.20986
[4339]	validation_0-logloss:0.20995

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47380
[50]	validation_0-logloss:0.26430
[100]	validation_0-logloss:0.24952
[150]	validation_0-logloss:0.24224
[200]	validation_0-logloss:0.23772
[250]	validation_0-logloss:0.23363
[300]	validation_0-logloss:0.23067
[350]	validation_0-logloss:0.22783
[400]	validation_0-logloss:0.22560
[450]	validation_0-logloss:0.22370
[500]	validation_0-logloss:0.22244
[550]	validation_0-logloss:0.22088
[600]	validation_0-logloss:0.21964
[650]	validation_0-logloss:0.21883
[700]	validation_0-logloss:0.21762
[750]	validation_0-logloss:0.21680
[800]	validation_0-logloss:0.21633
[850]	validation_0-logloss:0.21570
[900]	validation_0-logloss:0.21494
[950]	validation_0-logloss:0.21421
[1000]	validation_0-logloss:0.21376
[1050]	validation_0-logloss:0.21322
[1100]	validation_0-logloss:0.21272
[1150]	validation_0-logloss:0.21231
[1200]	validation_0-logloss:0.21196
[1250]	validation_0-logloss:0.21157
[1300]	validation_0-logloss:0.21137
[1350]	validation_0-logloss:0.21106
[1400]	validation_0-logloss:0.21067
[1450]	validation_0-logloss:0.21045
[1500]	validation_0-logloss:0.21022
[1550]	validation_0-logloss:0.21006
[1600]	validation_0-logloss:0.20988
[1650]	validation_0-logloss:0.20966
[1700]	validation_0-logloss:0.20937
[1750]	validation_0-logloss:0.20922
[1800]	validation_0-logloss:0.20900
[1850]	validation_0-logloss:0.20885
[1900]	validation_0-logloss:0.20880
[1950]	validation_0-logloss:0.20872
[2000]	validation_0-logloss:0.20868
[2050]	validation_0-logloss:0.20849
[2100]	validation_0-logloss:0.20846
[2150]	validation_0-logloss:0.20831
[2200]	validation_0-logloss:0.20827
[2250]	validation_0-logloss:0.20807
[2300]	validation_0-logloss:0.20801
[2350]	validation_0-logloss:0.20786
[2400]	validation_0-logloss:0.20778
[2450]	validation_0-logloss:0.20769
[2500]	validation_0-logloss:0.20768
[2550]	validation_0-logloss:0.20760
[2600]	validation_0-logloss:0.20753
[2650]	validation_0-logloss:0.20744
[2700]	validation_0-logloss:0.20736
[2750]	validation_0-logloss:0.20733
[2800]	validation_0-logloss:0.20727
[2850]	validation_0-logloss:0.20728
[2900]	validation_0-logloss:0.20735
[2950]	validation_0-logloss:0.20731
[3000]	validation_0-logloss:0.20729
[3050]	validation_0-logloss:0.20722
[3100]	validation_0-logloss:0.20720
[3150]	validation_0-logloss:0.20718
[3200]	validation_0-logloss:0.20714
[3250]	validation_0-logloss:0.20715
[3300]	validation_0-logloss:0.20712
[3350]	validation_0-logloss:0.20716
[3400]	validation_0-logloss:0.20716
[3450]	validation_0-logloss:0.20716
[3500]	validation_0-logloss:0.20722
[3550]	validation_0-logloss:0.20725
[3600]	validation_0-logloss:0.20727
[3650]	validation_0-logloss:0.20729
[3700]	validation_0-logloss:0.20729
[3750]	validation_0-logloss:0.20732
[3800]	validation_0-logloss:0.20741
[3850]	validation_0-logloss:0.20752
[3900]	validation_0-logloss:0.20758
[3950]	validation_0-logloss:0.20764
[4000]	validation_0-logloss:0.20765
[4050]	validation_0-logloss:0.20775
[4100]	validation_0-logloss:0.20779
[4150]	validation_0-logloss:0.20786
[4200]	validation_0-logloss:0.20793
[4250]	validation_0-logloss:0.20794
[4287]	validation_0-logloss:0.20795

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47383
[50]	validation_0-logloss:0.26385
[100]	validation_0-logloss:0.24925
[150]	validation_0-logloss:0.24199
[200]	validation_0-logloss:0.23702
[250]	validation_0-logloss:0.23288
[300]	validation_0-logloss:0.23020
[350]	validation_0-logloss:0.22747
[400]	validation_0-logloss:0.22552
[450]	validation_0-logloss:0.22378
[500]	validation_0-logloss:0.22228
[550]	validation_0-logloss:0.22117
[600]	validation_0-logloss:0.22007
[650]	validation_0-logloss:0.21901
[700]	validation_0-logloss:0.21825
[750]	validation_0-logloss:0.21772
[800]	validation_0-logloss:0.21679
[850]	validation_0-logloss:0.21615
[900]	validation_0-logloss:0.21554
[950]	validation_0-logloss:0.21494
[1000]	validation_0-logloss:0.21439
[1050]	validation_0-logloss:0.21414
[1100]	validation_0-logloss:0.21385
[1150]	validation_0-logloss:0.21346
[1200]	validation_0-logloss:0.21320
[1250]	validation_0-logloss:0.21291
[1300]	validation_0-logloss:0.21260
[1350]	validation_0-logloss:0.21229
[1400]	validation_0-logloss:0.21182
[1450]	validation_0-logloss:0.21156
[1500]	validation_0-logloss:0.21143
[1550]	validation_0-logloss:0.21125
[1600]	validation_0-logloss:0.21109
[1650]	validation_0-logloss:0.21099
[1700]	validation_0-logloss:0.21085
[1750]	validation_0-logloss:0.21062
[1800]	validation_0-logloss:0.21049
[1850]	validation_0-logloss:0.21047
[1900]	validation_0-logloss:0.21038
[1950]	validation_0-logloss:0.21027
[2000]	validation_0-logloss:0.21030
[2050]	validation_0-logloss:0.21017
[2100]	validation_0-logloss:0.21006
[2150]	validation_0-logloss:0.20993
[2200]	validation_0-logloss:0.20989
[2250]	validation_0-logloss:0.20972
[2300]	validation_0-logloss:0.20976
[2350]	validation_0-logloss:0.20966
[2400]	validation_0-logloss:0.20971
[2450]	validation_0-logloss:0.20974
[2500]	validation_0-logloss:0.20974
[2550]	validation_0-logloss:0.20972
[2600]	validation_0-logloss:0.20966
[2650]	validation_0-logloss:0.20956
[2700]	validation_0-logloss:0.20962
[2750]	validation_0-logloss:0.20965
[2800]	validation_0-logloss:0.20967
[2850]	validation_0-logloss:0.20966
[2900]	validation_0-logloss:0.20963
[2950]	validation_0-logloss:0.20965
[3000]	validation_0-logloss:0.20964
[3050]	validation_0-logloss:0.20966
[3100]	validation_0-logloss:0.20974
[3150]	validation_0-logloss:0.20981
[3200]	validation_0-logloss:0.20984
[3250]	validation_0-logloss:0.20980
[3300]	validation_0-logloss:0.20970
[3350]	validation_0-logloss:0.20975
[3400]	validation_0-logloss:0.20981
[3445]	validation_0-logloss:0.20983

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47348
[50]	validation_0-logloss:0.26290
[100]	validation_0-logloss:0.24852
[150]	validation_0-logloss:0.24127
[200]	validation_0-logloss:0.23612
[250]	validation_0-logloss:0.23289
[300]	validation_0-logloss:0.22953
[350]	validation_0-logloss:0.22705
[400]	validation_0-logloss:0.22519
[450]	validation_0-logloss:0.22390
[500]	validation_0-logloss:0.22231
[550]	validation_0-logloss:0.22131
[600]	validation_0-logloss:0.22001
[650]	validation_0-logloss:0.21867
[700]	validation_0-logloss:0.21780
[750]	validation_0-logloss:0.21690
[800]	validation_0-logloss:0.21625
[850]	validation_0-logloss:0.21585
[900]	validation_0-logloss:0.21539
[950]	validation_0-logloss:0.21489
[1000]	validation_0-logloss:0.21453
[1050]	validation_0-logloss:0.21423
[1100]	validation_0-logloss:0.21379
[1150]	validation_0-logloss:0.21356
[1200]	validation_0-logloss:0.21316
[1250]	validation_0-logloss:0.21281
[1300]	validation_0-logloss:0.21248
[1350]	validation_0-logloss:0.21220
[1400]	validation_0-logloss:0.21199
[1450]	validation_0-logloss:0.21182
[1500]	validation_0-logloss:0.21153
[1550]	validation_0-logloss:0.21123
[1600]	validation_0-logloss:0.21097
[1650]	validation_0-logloss:0.21072
[1700]	validation_0-logloss:0.21054
[1750]	validation_0-logloss:0.21044
[1800]	validation_0-logloss:0.21031
[1850]	validation_0-logloss:0.21010
[1900]	validation_0-logloss:0.21002
[1950]	validation_0-logloss:0.20994
[2000]	validation_0-logloss:0.20985
[2050]	validation_0-logloss:0.20975
[2100]	validation_0-logloss:0.20971
[2150]	validation_0-logloss:0.20966
[2200]	validation_0-logloss:0.20960
[2250]	validation_0-logloss:0.20957
[2300]	validation_0-logloss:0.20949
[2350]	validation_0-logloss:0.20940
[2400]	validation_0-logloss:0.20937
[2450]	validation_0-logloss:0.20936
[2500]	validation_0-logloss:0.20937
[2550]	validation_0-logloss:0.20938
[2600]	validation_0-logloss:0.20938
[2650]	validation_0-logloss:0.20944
[2700]	validation_0-logloss:0.20942
[2750]	validation_0-logloss:0.20933
[2800]	validation_0-logloss:0.20930
[2850]	validation_0-logloss:0.20928
[2900]	validation_0-logloss:0.20935
[2950]	validation_0-logloss:0.20937
[3000]	validation_0-logloss:0.20932
[3050]	validation_0-logloss:0.20932
[3100]	validation_0-logloss:0.20929
[3150]	validation_0-logloss:0.20921
[3200]	validation_0-logloss:0.20925
[3250]	validation_0-logloss:0.20933
[3300]	validation_0-logloss:0.20942
[3350]	validation_0-logloss:0.20949
[3400]	validation_0-logloss:0.20955
[3450]	validation_0-logloss:0.20952
[3500]	validation_0-logloss:0.20959
[3550]	validation_0-logloss:0.20967
[3600]	validation_0-logloss:0.20973
[3650]	validation_0-logloss:0.20976
[3700]	validation_0-logloss:0.20982
[3750]	validation_0-logloss:0.20985
[3800]	validation_0-logloss:0.20989
[3850]	validation_0-logloss:0.20996
[3900]	validation_0-logloss:0.21001
[3950]	validation_0-logloss:0.21005
[4000]	validation_0-logloss:0.21014
[4050]	validation_0-logloss:0.21022
[4099]	validation_0-logloss:0.21030

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47342
[50]	validation_0-logloss:0.26227
[100]	validation_0-logloss:0.24766
[150]	validation_0-logloss:0.24057
[200]	validation_0-logloss:0.23543
[250]	validation_0-logloss:0.23195
[300]	validation_0-logloss:0.22857
[350]	validation_0-logloss:0.22593
[400]	validation_0-logloss:0.22427
[450]	validation_0-logloss:0.22256
[500]	validation_0-logloss:0.22103
[550]	validation_0-logloss:0.21953
[600]	validation_0-logloss:0.21839
[650]	validation_0-logloss:0.21758
[700]	validation_0-logloss:0.21653
[750]	validation_0-logloss:0.21572
[800]	validation_0-logloss:0.21481
[850]	validation_0-logloss:0.21410
[900]	validation_0-logloss:0.21361
[950]	validation_0-logloss:0.21309
[1000]	validation_0-logloss:0.21254
[1050]	validation_0-logloss:0.21210
[1100]	validation_0-logloss:0.21190
[1150]	validation_0-logloss:0.21159
[1200]	validation_0-logloss:0.21124
[1250]	validation_0-logloss:0.21088
[1300]	validation_0-logloss:0.21071
[1350]	validation_0-logloss:0.21047
[1400]	validation_0-logloss:0.21025
[1450]	validation_0-logloss:0.21008
[1500]	validation_0-logloss:0.20998
[1550]	validation_0-logloss:0.20971
[1600]	validation_0-logloss:0.20957
[1650]	validation_0-logloss:0.20946
[1700]	validation_0-logloss:0.20938
[1750]	validation_0-logloss:0.20927
[1800]	validation_0-logloss:0.20918
[1850]	validation_0-logloss:0.20895
[1900]	validation_0-logloss:0.20879
[1950]	validation_0-logloss:0.20864
[2000]	validation_0-logloss:0.20851
[2050]	validation_0-logloss:0.20843
[2100]	validation_0-logloss:0.20831
[2150]	validation_0-logloss:0.20826
[2200]	validation_0-logloss:0.20823
[2250]	validation_0-logloss:0.20823
[2300]	validation_0-logloss:0.20822
[2350]	validation_0-logloss:0.20822
[2400]	validation_0-logloss:0.20820
[2450]	validation_0-logloss:0.20823
[2500]	validation_0-logloss:0.20818
[2550]	validation_0-logloss:0.20816
[2600]	validation_0-logloss:0.20818
[2650]	validation_0-logloss:0.20811
[2700]	validation_0-logloss:0.20814
[2750]	validation_0-logloss:0.20815
[2800]	validation_0-logloss:0.20817
[2850]	validation_0-logloss:0.20816
[2900]	validation_0-logloss:0.20816
[2950]	validation_0-logloss:0.20817
[3000]	validation_0-logloss:0.20825
[3050]	validation_0-logloss:0.20827
[3100]	validation_0-logloss:0.20829
[3150]	validation_0-logloss:0.20829
[3200]	validation_0-logloss:0.20830
[3250]	validation_0-logloss:0.20832
[3300]	validation_0-logloss:0.20831
[3350]	validation_0-logloss:0.20828
[3400]	validation_0-logloss:0.20827
[3450]	validation_0-logloss:0.20834
[3495]	validation_0-logloss:0.20833

Saving c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
	0.9582	 = Validation score   (roc_auc)
	558.77s	 = Training   runtime
	4.33s	 = Validation runtime
	15612.6	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 3239.90s of the 30572.71s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/7.0 GB
Ensemble size: 25
Ensemble weights:
[0.   0.08 0.44 0.48]
	0.48s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost_BAG_L1': 0.48, 'CatBoost_BAG_L1': 0.44, 'LightGBMLarge_BAG_L1': 0.08}
	0.96	 = Validation score   (roc_auc)
	5.01s	 = Training   runtime
	0.05s	 = Validation runtime
	2988.7	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
AutoGluon training complete, total runtime = 1832.64s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 2988.7 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models5\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models5\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models5")

In [8]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.959994,roc_auc,22.646903,1704.332377,0.049652,5.011189,2,True,5
1,XGBoost_BAG_L1,0.958240,roc_auc,4.327017,558.767684,4.327017,558.767684,1,True,4
2,CatBoost_BAG_L1,0.958136,roc_auc,4.220672,966.620621,4.220672,966.620621,1,True,3
3,LightGBMLarge_BAG_L1,0.952897,roc_auc,14.049562,173.932884,14.049562,173.932884,1,True,2
4,LightGBM_BAG_L1,0.951028,roc_auc,5.040709,87.416877,5.040709,87.416877,1,True,1

In [10]:
df=predictor.predict_proba(df_test)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl

          0         1
0  0.994529  0.005471
1  0.994558  0.005442
2  0.995153  0.004847
3  0.828029  0.171971
4  0.073202  0.926798

In [ ]:
# import os
# import pandas as pd
# from autogluon.tabular import TabularPredictor

# # ============================================================
# # CONFIG
# # ============================================================

# MODEL_DIR = "./ag_models2"

# all_leaderboards = []

# # ============================================================
# # SCAN & LOAD ALL TRAINED PREDICTORS
# # ============================================================

# if os.path.exists(MODEL_DIR):
#     # Check both subdirectories and root directory for saved predictors
#     folder_candidates = [MODEL_DIR] + [
#         os.path.join(MODEL_DIR, d) 
#         for d in os.listdir(MODEL_DIR) 
#         if os.path.isdir(os.path.join(MODEL_DIR, d))
#     ]

#     for folder_path in folder_candidates:
#         # Check if directory contains a valid predictor file
#         if os.path.exists(os.path.join(folder_path, "predictor.pkl")):
#             try:
#                 folder_name = os.path.basename(folder_path)
#                 print(f"Loading predictor from: {folder_path}")
                
#                 # Load predictor from disk
#                 predictor = TabularPredictor.load(folder_path)
                
#                 # Fetch leaderboard
#                 lb = predictor.leaderboard(silent=True)
#                 lb.insert(0, "folder_name", folder_name)
                
#                 all_leaderboards.append(lb)
#             except Exception as e:
#                 print(f"Failed to load predictor from {folder_path}: {e}")

# # ============================================================
# # MERGE AND PRESENT COMBINED LEADERBOARD
# # ============================================================

# if all_leaderboards:
#     combined_leaderboard = pd.concat(all_leaderboards, ignore_index=True)

#     # Sort all trained models by validation ROC-AUC score descending
#     combined_leaderboard = combined_leaderboard.sort_values(
#         by="score_val", ascending=False
#     ).reset_index(drop=True)

#     print("\n" + "=" * 80)
#     print("COMBINED LEADERBOARD OF ALL LOADED MODELS")
#     print("=" * 80)

#     display(combined_leaderboard)
# else:
#     print(f"No valid AutoGluon predictors (`predictor.pkl`) found under '{MODEL_DIR}'.")

Loading predictor from: ./ag_models2\CAT

Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\GBM\models\trainer.pkl

Loading predictor from: ./ag_models2\GBM
Loading predictor from: ./ag_models2\RF

Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\RF\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl

Loading predictor from: ./ag_models2\XGB

================================================================================
COMBINED LEADERBOARD OF ALL LOADED MODELS
================================================================================

,folder_name,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGB,WeightedEnsemble_L2,0.958240,roc_auc,4.397609,601.833442,0.053591,0.057095,2.0,1.0,2.0
1,XGB,XGBoost_BAG_L1,0.958240,roc_auc,4.344018,601.776347,4.344018,601.776347,1.0,1.0,1.0
2,GBM,WeightedEnsemble_L2,0.953617,roc_auc,18.501622,255.991845,0.060542,2.829900,2.0,1.0,3.0
3,GBM,LightGBMLarge_BAG_L1,0.952897,roc_auc,13.476475,172.914947,13.476475,172.914947,1.0,1.0,2.0
4,GBM,LightGBM_BAG_L1,0.951028,roc_auc,4.964605,80.246999,4.964605,80.246999,1.0,1.0,1.0
5,CAT,WeightedEnsemble_L2,0.950199,roc_auc,0.780571,179.753519,0.057653,0.067708,2.0,1.0,2.0
6,CAT,CatBoost_BAG_L1,0.950199,roc_auc,0.722918,179.685812,0.722918,179.685812,1.0,1.0,1.0

In [ ]:
# predictor = TabularPredictor.load("ag_models2/XGB")
# predictor.info()

Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F3\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F4\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F5\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F6\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F7\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\S1F8\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\model.pkl

{'path': 'c:\\Darshak\\Projects\\Hackathon\\ag_models2\\XGB',
 'label': 'PitNextLap',
 'random_state': 0,
 'version': '1.6.1',
 'features': ['Driver',
  'Compound',
  'Race',
  'Year',
  'PitStop',
  'LapNumber',
  'Stint',
  'TyreLife',
  'Position',
  'LapTime (s)',
  'LapTime_Delta',
  'Cumulative_Degradation',
  'RaceProgress',
  'Position_Change'],
 'feature_metadata_in': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a176d61b0>,
 'time_fit_preprocessing': 0.8181874752044678,
 'time_fit_training': 607.6769812107086,
 'time_fit_total': 608.4951686859131,
 'time_limit': 1800,
 'time_train_start': 1786370652.9010363,
 'num_rows_train': 540445,
 'num_cols_train': 14,
 'num_rows_val': None,
 'num_rows_test': None,
 'num_classes': 2,
 'problem_type': 'binary',
 'eval_metric': 'roc_auc',
 'best_model': 'WeightedEnsemble_L2',
 'best_model_score_val': np.float64(0.9582403341215795),
 'best_model_stack_level': 2,
 'num_models_trained': 2,
 'num_bag_folds': 8,
 'max_stack_level': 2,
 'max_core_stack_level': 1,
 'model_info': {'XGBoost_BAG_L1': {'name': 'XGBoost_BAG_L1',
   'model_type': 'StackerEnsembleModel',
   'problem_type': 'binary',
   'eval_metric': 'roc_auc',
   'stopping_metric': 'log_loss',
   'fit_time': 602.3145225048065,
   'num_classes': 2,
   'quantile_levels': None,
   'predict_time': 4.416460990905762,
   'val_score': np.float64(0.9582403341215795),
   'hyperparameters': {'use_orig_features': True,
    'valid_stacker': True,
    'max_base_models': 0,
    'max_base_models_per_type': 'auto',
    'save_bag_folds': True,
    'stratify': 'auto',
    'bin': 'auto',
    'n_bins': None,
    'vary_seed_across_folds': False,
    'custom_splits': None,
    'model_random_seed': 0},
   'hyperparameters_user': {},
   'hyperparameters_fit': {},
   'hyperparameters_nondefault': [],
   'ag_args_fit': {'max_memory_usage_ratio': 1.0,
    'max_gpu_memory_usage_ratio': 1.0,
    'max_time_limit_ratio': 1.0,
    'max_time_limit': None,
    'min_time_limit': 0,
    'valid_raw_types': None,
    'valid_special_types': None,
    'ignored_type_group_special': None,
    'ignored_type_group_raw': None,
    'get_features_kwargs': None,
    'get_features_kwargs_extra': None,
    'predict_1_batch_size': None,
    'temperature_scalar': None,
    'drop_unique': False},
   'num_features': 14,
   'features': ['RaceProgress',
    'Stint',
    'LapNumber',
    'Position_Change',
    'Race',
    'LapTime (s)',
    'Driver',
    'TyreLife',
    'Year',
    'PitStop',
    'Compound',
    'Position',
    'LapTime_Delta',
    'Cumulative_Degradation'],
   'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a176d76b0>,
   'memory_size': 4273,
   'compile_time': None,
   'is_initialized': True,
   'is_fit': True,
   'is_valid': True,
   'can_infer': True,
   'has_learning_curves': False,
   'num_samples': 540445,
   'val_in_fit': False,
   'unlabeled_in_fit': False,
   'num_cpus': 16,
   'num_gpus': 1,
   'bagged_info': {'child_model_type': 'XGBoostModel',
    'num_child_models': 8,
    'child_model_names': ['S1F1',
     'S1F2',
     'S1F3',
     'S1F4',
     'S1F5',
     'S1F6',
     'S1F7',
     'S1F8'],
    '_n_repeats': 1,
    '_k_per_n_repeat': [8],
    '_random_state': 1,
    'low_memory': True,
    'bagged_mode': True,
    'max_memory_size': 124317234,
    'min_memory_size': 19411241,
    'child_hyperparameters': {'n_estimators': 10000,
     'learning_rate': 0.1,
     'n_jobs': -1,
     'proc.max_category_levels': 100,
     'objective': 'binary:logistic',
     'booster': 'gbtree',
     'seed': 0},
    'child_hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
    'child_hyperparameters_fit': {'n_estimators': 3037},
    'child_ag_args_fit': {'max_memory_usage_ratio': 1.0,
     'max_gpu_memory_usage_ratio': 1.0,
     'max_time_limit_ratio': 1.0,
     'max_time_limit': None,
     'min_time_limit': 0,
     'valid_raw_types': ['bool', 'int', 'float', 'category'],
     'valid_special_types': None,
     'ignored_type_group_special': None,
     'ignored_type_group_raw': None,
     'get_features_kwargs': None,
     'get_features_kwargs_extra': None,
     'predict_1_batch_size': None,
     'temperature_scalar': None,
     'num_gpus': 1}},
   'stacker_info': {'num_base_models': 0, 'base_model_names': []},
   'children_info': {'S1F1': {'name': 'S1F1',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 67.1378562450409,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5748686790466309,
     'val_score': np.float64(0.9585020087543992),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 2695},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e143b30>,
     'memory_size': 13760186,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F2': {'name': 'S1F2',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 94.40736246109009,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.6614913940429688,
     'val_score': np.float64(0.9586009772558983),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 3806},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e142bd0>,
     'memory_size': 19406968,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F3': {'name': 'S1F3',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 67.39362454414368,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.48779940605163574,
     'val_score': np.float64(0.9565995515192431),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 2737},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e142210>,
     'memory_size': 14017015,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F4': {'name': 'S1F4',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 82.32537770271301,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5845222473144531,
     'val_score': np.float64(0.9583834819202168),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 3323},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e143770>,
     'memory_size': 16993591,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F5': {'name': 'S1F5',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 81.33959031105042,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5881736278533936,
     'val_score': np.float64(0.9591060554118972),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 3283},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e142ab0>,
     'memory_size': 16726939,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472889,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F6': {'name': 'S1F6',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 65.65677666664124,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.4864377975463867,
     'val_score': np.float64(0.9580150193670824),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 2636},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e1423f0>,
     'memory_size': 13525178,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472890,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F7': {'name': 'S1F7',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 77.38286662101746,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.5537416934967041,
     'val_score': np.float64(0.9579987280187475),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 3139},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e142330>,
     'memory_size': 16106257,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,
     'num_samples': 472890,
     'val_in_fit': True,
     'unlabeled_in_fit': False,
     'num_cpus': 16,
     'num_gpus': 1},
    'S1F8': {'name': 'S1F8',
     'model_type': 'XGBoostModel',
     'problem_type': 'binary',
     'eval_metric': 'roc_auc',
     'stopping_metric': 'log_loss',
     'fit_time': 66.67106795310974,
     'num_classes': 2,
     'quantile_levels': None,
     'predict_time': 0.47942614555358887,
     'val_score': np.float64(0.9587957215331033),
     'hyperparameters': {'n_estimators': 10000,
      'learning_rate': 0.1,
      'n_jobs': -1,
      'proc.max_category_levels': 100,
      'objective': 'binary:logistic',
      'booster': 'gbtree',
      'seed': 0},
     'hyperparameters_user': {'ag_args_fit': {'num_gpus': 1}},
     'hyperparameters_fit': {'n_estimators': 2674},
     'hyperparameters_nondefault': [],
     'ag_args_fit': {'max_memory_usage_ratio': 1.0,
      'max_gpu_memory_usage_ratio': 1.0,
      'max_time_limit_ratio': 1.0,
      'max_time_limit': None,
      'min_time_limit': 0,
      'valid_raw_types': ['bool', 'int', 'float', 'category'],
      'valid_special_types': None,
      'ignored_type_group_special': None,
      'ignored_type_group_raw': None,
      'get_features_kwargs': None,
      'get_features_kwargs_extra': None,
      'predict_1_batch_size': None,
      'temperature_scalar': None,
      'num_gpus': 1},
     'num_features': 14,
     'features': ['Year',
      'PitStop',
      'LapNumber',
      'Stint',
      'TyreLife',
      'Position',
      'LapTime (s)',
      'LapTime_Delta',
      'Cumulative_Degradation',
      'RaceProgress',
      'Position_Change',
      'Driver',
      'Compound',
      'Race'],
     'feature_metadata': <autogluon.common.features.feature_metadata.FeatureMetadata at 0x18a2e141190>,
     'memory_size': 13776827,
     'compile_time': None,
     'is_initialized': True,
     'is_fit': True,
     'is_valid': True,
     'can_infer': True,
     'has_learning_curves': False,

In [76]:
df=predictor.predict_proba(df_test)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models2\XGB\models\WeightedEnsemble_L2\model.pkl

          0         1
0  0.995741  0.004259
1  0.995626  0.004374
2  0.996494  0.003506
3  0.800449  0.199551
4  0.039684  0.960316

In [11]:
# df.to_csv("With_driver_feature_submission.csv")
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [12]:
df_sample_out['PitNextLap']=df[1]

In [13]:
df_sample_out.head()

       id  PitNextLap
0  439140    0.005471
1  439141    0.005442
2  439142    0.004847
3  439143    0.171971
4  439144    0.926798

In [14]:
df_sample_out.to_csv("My_output/all_model_together_submission.csv")

Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\CatBoost_BAG_L1\model.pkl

Loading: c:\Darshak\Projects\Hackathon\ag_models2\CAT\models\WeightedEnsemble_L2\model.pkl

========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9126
Mismatches                         : 874
Accuracy (%)                       : 91.26
True Positives (Actual 1, Pred 1)  : 1527
True Negatives (Actual 0, Pred 0)  : 7599
False Positives (Actual 0, Pred 1) : 401
False Negatives (Actual 1, Pred 0) : 473
========================================
Loaded: sample_part_1_10000k.csv -> Shape: (10000, 15)

In [15]:
from multi_sampling_test_predictor import process_and_evaluate_all_csvs
data_dict = process_and_evaluate_all_csvs(predictor,folder_path="Sampling_data_to_test",drop_cols=[])

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl

----------------------------------------
 Processing: sample_part_1_10000k.csv
----------------------------------------
ground_truth
0    8000
1    2000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_1_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9396
Mismatches                         : 604
Accuracy (%)                       : 93.96
True Positives (Actual 1, Pred 1)  : 1676
True Negatives (Actual 0, Pred 0)  : 7720
False Positives (Actual 0, Pred 1) : 280
False Negatives (Actual 1, Pred 0) : 324
========================================

----------------------------------------
 Processing: sample_part_2_10000k.csv
----------------------------------------
ground_truth
0    8500
1    1500
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_2_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9460
Mismatches                         : 540
Accuracy (%)                       : 94.6
True Positives (Actual 1, Pred 1)  : 1278
True Negatives (Actual 0, Pred 0)  : 8182
False Positives (Actual 0, Pred 1) : 318
False Negatives (Actual 1, Pred 0) : 222
========================================

----------------------------------------
 Processing: sample_part_3_10000k.csv
----------------------------------------
ground_truth
0    7500
1    2500
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_3_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9360
Mismatches                         : 640
Accuracy (%)                       : 93.6
True Positives (Actual 1, Pred 1)  : 2118
True Negatives (Actual 0, Pred 0)  : 7242
False Positives (Actual 0, Pred 1) : 258
False Negatives (Actual 1, Pred 0) : 382
========================================

----------------------------------------
 Processing: sample_part_4_10000k.csv
----------------------------------------
ground_truth
0    7000
1    3000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\CatBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_4_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9335
Mismatches                         : 665
Accuracy (%)                       : 93.35
True Positives (Actual 1, Pred 1)  : 2566
True Negatives (Actual 0, Pred 0)  : 6769
False Positives (Actual 0, Pred 1) : 231
False Negatives (Actual 1, Pred 0) : 434
========================================

----------------------------------------
 Processing: sample_part_5_10000k.csv
----------------------------------------
ground_truth
0    9000
1    1000
Name: count, dtype: int64

Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models5\models\WeightedEnsemble_L2\model.pkl

--- Per-File Analysis [sample_part_5_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9516
Mismatches                         : 484
Accuracy (%)                       : 95.16
True Positives (Actual 1, Pred 1)  : 831
True Negatives (Actual 0, Pred 0)  : 8685
False Positives (Actual 0, Pred 1) : 315
False Negatives (Actual 1, Pred 0) : 169
========================================

==================================================
      OVERALL CUMULATIVE ANALYSIS REPORT
==================================================
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 50000
Correct Matches                    : 47067
Mismatches                         : 2933
Accuracy (%)                       : 94.13
True Positives (Actual 1, Pred 1)  : 8469
True Negatives (Actual 0, Pred 0)  : 38598
False Positives (Actual 0, Pred 1) : 1402
False Negatives (Actual 1, Pred 0) : 1531
========================================