In [ ]:
import pandas as pd
df_train=pd.read_csv('data/train_fe_cat.csv')
df_test=pd.read_csv('data/test_fe_cat.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [3]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [4]:
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [5]:
df_test=df_test.drop(['Driver'],axis=1)
df_train_merged=df_train_merged.drop(['Driver'],axis=1)
df_train=df_train.drop(['Driver'],axis=1)

In [6]:
# predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc').fit(
#     train_data=df_train,
#     ag_args_fit={"num_gpus": 2},
#     time_limit=3600*9,
#     presets='best_quality',
#     verbosity=3,
#     num_stack_levels=0
# )

In [7]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [ ]:
import os
import shutil
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models4"
TIME_LIMIT = 30 * 60  # 30 minutes (1800 seconds) per model family

models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

# ============================================================
# DELETE OLD MODELS
# ============================================================

# if os.path.exists(MODEL_DIR):
#     print(f"Deleting existing model directory: {MODEL_DIR}")
#     shutil.rmtree(MODEL_DIR)

# os.makedirs(MODEL_DIR, exist_ok=True)
print(f"Fresh model directory created: {MODEL_DIR}")

# ============================================================
# TRAIN ONE MODEL AT A TIME
# ============================================================

predictors = {}
results = []

for model_name, model_config in models.items():

    model_path = os.path.join(MODEL_DIR, model_name)

    print("\n" + "=" * 80)
    print(f"TRAINING: {model_name}")
    print(f"TIME LIMIT: 30 MINUTES")
    print(f"MODEL PATH: {model_path}")
    print("=" * 80)

    predictor = TabularPredictor(
        label=TARGET,
        eval_metric='roc_auc',
        path=model_path
    ).fit(
        train_data=df_train,
        presets="best_quality",  # Enables bagging (_BAG_L1) and out-of-fold validation
        hyperparameters={model_name: model_config},  # Maps key to config dict properly
        ag_args_fit={
            'num_gpus': 1
        },
        time_limit=TIME_LIMIT,
        verbosity=3,
        num_stack_levels=0
    )

    predictors[model_name] = predictor

    # ========================================================
    # GET RESULT
    # ========================================================

    leaderboard = predictor.leaderboard(silent=True)
    best_row = leaderboard.iloc[0]

    results.append({
        'Model Family': model_name,
        'Best AutoGluon Model': best_row['model'],
        'Validation ROC-AUC': best_row['score_val'],
        'Fit Time (sec)': best_row['fit_time'],
        'Predict Time (sec)': best_row['pred_time_val']
    })

    print(f"\n{model_name} completed.")
    print(f"Validation ROC-AUC: {best_row['score_val']:.6f}")

# ============================================================
# FINAL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    'Validation ROC-AUC',
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 80)
print("FINAL MODEL COMPARISON")
print("=" * 80)

display(results_df)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.03 GB / 15.06 GB (26.7%)
Disk Space Avail:   711.20 GB / 930.47 GB (76.4%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\predictor.pkl

Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\GBM"
Train Data Rows:    439140
Train Data Columns: 57
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...

Deleting existing model directory: ./ag_models4
Fresh model directory created: ./ag_models4

================================================================================
TRAINING: GBM
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\GBM
================================================================================

Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4040.40 MB
	Train Data (Original)  Memory Usage: 235.80 MB (5.8% of available memory)
	Warning: Data size prior to feature transformation consumes 5.8% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.0s = Fit runtime
			46 features in original data used to generate 46 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			42 features in original data used to generate 42 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.1s = Fit runtime
	42 features in original data used to generate 42 features in processed data.
	Train Data (Processed) Memory Usage: 128.99 MB (3.2% of available memory)
Data preprocessing and feature engineering runtime = 1.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1798.75s of the 1798.74s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.268532
[100]	valid_set's binary_logloss: 0.249238
[150]	valid_set's binary_logloss: 0.242833
[200]	valid_set's binary_logloss: 0.239158
[250]	valid_set's binary_logloss: 0.237178
[300]	valid_set's binary_logloss: 0.236075
[350]	valid_set's binary_logloss: 0.235218
[400]	valid_set's binary_logloss: 0.234336
[450]	valid_set's binary_logloss: 0.233665
[500]	valid_set's binary_logloss: 0.232995
[550]	valid_set's binary_logloss: 0.232264
[600]	valid_set's binary_logloss: 0.231744
[650]	valid_set's binary_logloss: 0.231349
[700]	valid_set's binary_logloss: 0.230934
[750]	valid_set's binary_logloss: 0.230608
[800]	valid_set's binary_logloss: 0.230224
[850]	valid_set's binary_logloss: 0.230109
[900]	valid_set's binary_logloss: 0.229942
[950]	valid_set's binary_logloss: 0.229806
[1000]	valid_set's binary_logloss: 0.229732
[1050]	valid_set's binary_logloss: 0.229563
[1100]	valid_set's binary_logloss: 0.229446
[1150]	valid_set's binary_logloss: 0.22939
[1200]	valid_set's binary_logloss: 0.229287
[1250]	valid_set's binary_logloss: 0.229147
[1300]	valid_set's binary_logloss: 0.229078
[1350]	valid_set's binary_logloss: 0.22907
[1400]	valid_set's binary_logloss: 0.228952
[1450]	valid_set's binary_logloss: 0.228907
[1500]	valid_set's binary_logloss: 0.228866
[1550]	valid_set's binary_logloss: 0.228821
[1600]	valid_set's binary_logloss: 0.228818
[1650]	valid_set's binary_logloss: 0.2287
[1700]	valid_set's binary_logloss: 0.228714
[1750]	valid_set's binary_logloss: 0.228674
[1800]	valid_set's binary_logloss: 0.228673
[1850]	valid_set's binary_logloss: 0.228622
[1900]	valid_set's binary_logloss: 0.228641
[1950]	valid_set's binary_logloss: 0.228693
[2000]	valid_set's binary_logloss: 0.228751
[2050]	valid_set's binary_logloss: 0.22871
[2100]	valid_set's binary_logloss: 0.228744
[2150]	valid_set's binary_logloss: 0.228718
[2200]	valid_set's binary_logloss: 0.228717
[2250]	valid_set's binary_logloss: 0.228746
[2300]	valid_set's binary_logloss: 0.228741
[2350]	valid_set's binary_logloss: 0.228781
[2400]	valid_set's binary_logloss: 0.228839

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269258
[100]	valid_set's binary_logloss: 0.250054
[150]	valid_set's binary_logloss: 0.243392
[200]	valid_set's binary_logloss: 0.23988
[250]	valid_set's binary_logloss: 0.237902
[300]	valid_set's binary_logloss: 0.236522
[350]	valid_set's binary_logloss: 0.235299
[400]	valid_set's binary_logloss: 0.234231
[450]	valid_set's binary_logloss: 0.233176
[500]	valid_set's binary_logloss: 0.232473
[550]	valid_set's binary_logloss: 0.231884
[600]	valid_set's binary_logloss: 0.231504
[650]	valid_set's binary_logloss: 0.230927
[700]	valid_set's binary_logloss: 0.230414
[750]	valid_set's binary_logloss: 0.230133
[800]	valid_set's binary_logloss: 0.22983
[850]	valid_set's binary_logloss: 0.229664
[900]	valid_set's binary_logloss: 0.229421
[950]	valid_set's binary_logloss: 0.229344
[1000]	valid_set's binary_logloss: 0.229159
[1050]	valid_set's binary_logloss: 0.229001
[1100]	valid_set's binary_logloss: 0.22899
[1150]	valid_set's binary_logloss: 0.228988
[1200]	valid_set's binary_logloss: 0.228862
[1250]	valid_set's binary_logloss: 0.228763
[1300]	valid_set's binary_logloss: 0.228704
[1350]	valid_set's binary_logloss: 0.228693
[1400]	valid_set's binary_logloss: 0.228615
[1450]	valid_set's binary_logloss: 0.228588
[1500]	valid_set's binary_logloss: 0.228569
[1550]	valid_set's binary_logloss: 0.228536
[1600]	valid_set's binary_logloss: 0.228452
[1650]	valid_set's binary_logloss: 0.228359
[1700]	valid_set's binary_logloss: 0.228263
[1750]	valid_set's binary_logloss: 0.228176
[1800]	valid_set's binary_logloss: 0.228155
[1850]	valid_set's binary_logloss: 0.228167
[1900]	valid_set's binary_logloss: 0.228086
[1950]	valid_set's binary_logloss: 0.228109
[2000]	valid_set's binary_logloss: 0.228108
[2050]	valid_set's binary_logloss: 0.228119
[2100]	valid_set's binary_logloss: 0.228095
[2150]	valid_set's binary_logloss: 0.228099
[2200]	valid_set's binary_logloss: 0.228081
[2250]	valid_set's binary_logloss: 0.228081
[2300]	valid_set's binary_logloss: 0.228096
[2350]	valid_set's binary_logloss: 0.228059
[2400]	valid_set's binary_logloss: 0.228051
[2450]	valid_set's binary_logloss: 0.228033
[2500]	valid_set's binary_logloss: 0.228022
[2550]	valid_set's binary_logloss: 0.227975
[2600]	valid_set's binary_logloss: 0.227943
[2650]	valid_set's binary_logloss: 0.227953
[2700]	valid_set's binary_logloss: 0.227983
[2750]	valid_set's binary_logloss: 0.228019
[2800]	valid_set's binary_logloss: 0.228004
[2850]	valid_set's binary_logloss: 0.228049
[2900]	valid_set's binary_logloss: 0.228087
[2950]	valid_set's binary_logloss: 0.228086
[3000]	valid_set's binary_logloss: 0.228049
[3050]	valid_set's binary_logloss: 0.228083
[3100]	valid_set's binary_logloss: 0.228157
[3150]	valid_set's binary_logloss: 0.228195
[3200]	valid_set's binary_logloss: 0.228223
[3250]	valid_set's binary_logloss: 0.228233
[3300]	valid_set's binary_logloss: 0.228276
[3350]	valid_set's binary_logloss: 0.22833
[3400]	valid_set's binary_logloss: 0.228376

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.264906
[100]	valid_set's binary_logloss: 0.24496
[150]	valid_set's binary_logloss: 0.238368
[200]	valid_set's binary_logloss: 0.23501
[250]	valid_set's binary_logloss: 0.233081
[300]	valid_set's binary_logloss: 0.231559
[350]	valid_set's binary_logloss: 0.230369
[400]	valid_set's binary_logloss: 0.229171
[450]	valid_set's binary_logloss: 0.228336
[500]	valid_set's binary_logloss: 0.227767
[550]	valid_set's binary_logloss: 0.227023
[600]	valid_set's binary_logloss: 0.226705
[650]	valid_set's binary_logloss: 0.226297
[700]	valid_set's binary_logloss: 0.225943
[750]	valid_set's binary_logloss: 0.225679
[800]	valid_set's binary_logloss: 0.225449
[850]	valid_set's binary_logloss: 0.22525
[900]	valid_set's binary_logloss: 0.225021
[950]	valid_set's binary_logloss: 0.224845
[1000]	valid_set's binary_logloss: 0.224475
[1050]	valid_set's binary_logloss: 0.224394
[1100]	valid_set's binary_logloss: 0.224152
[1150]	valid_set's binary_logloss: 0.224058
[1200]	valid_set's binary_logloss: 0.22391
[1250]	valid_set's binary_logloss: 0.223819
[1300]	valid_set's binary_logloss: 0.223798
[1350]	valid_set's binary_logloss: 0.223702
[1400]	valid_set's binary_logloss: 0.223626
[1450]	valid_set's binary_logloss: 0.223561
[1500]	valid_set's binary_logloss: 0.223432
[1550]	valid_set's binary_logloss: 0.223395
[1600]	valid_set's binary_logloss: 0.223336
[1650]	valid_set's binary_logloss: 0.223239
[1700]	valid_set's binary_logloss: 0.223105
[1750]	valid_set's binary_logloss: 0.223027
[1800]	valid_set's binary_logloss: 0.222981
[1850]	valid_set's binary_logloss: 0.222913
[1900]	valid_set's binary_logloss: 0.222907
[1950]	valid_set's binary_logloss: 0.22286
[2000]	valid_set's binary_logloss: 0.222862
[2050]	valid_set's binary_logloss: 0.222819
[2100]	valid_set's binary_logloss: 0.222805
[2150]	valid_set's binary_logloss: 0.222812
[2200]	valid_set's binary_logloss: 0.222757
[2250]	valid_set's binary_logloss: 0.222771
[2300]	valid_set's binary_logloss: 0.222718
[2350]	valid_set's binary_logloss: 0.222751
[2400]	valid_set's binary_logloss: 0.222706
[2450]	valid_set's binary_logloss: 0.222668
[2500]	valid_set's binary_logloss: 0.222712
[2550]	valid_set's binary_logloss: 0.222743
[2600]	valid_set's binary_logloss: 0.222716
[2650]	valid_set's binary_logloss: 0.22274
[2700]	valid_set's binary_logloss: 0.222724
[2750]	valid_set's binary_logloss: 0.222745
[2800]	valid_set's binary_logloss: 0.222698
[2850]	valid_set's binary_logloss: 0.222651
[2900]	valid_set's binary_logloss: 0.222668
[2950]	valid_set's binary_logloss: 0.222714
[3000]	valid_set's binary_logloss: 0.222694
[3050]	valid_set's binary_logloss: 0.222642
[3100]	valid_set's binary_logloss: 0.222632
[3150]	valid_set's binary_logloss: 0.222661
[3200]	valid_set's binary_logloss: 0.222664
[3250]	valid_set's binary_logloss: 0.222678
[3300]	valid_set's binary_logloss: 0.222686
[3350]	valid_set's binary_logloss: 0.222695
[3400]	valid_set's binary_logloss: 0.222735
[3450]	valid_set's binary_logloss: 0.222736
[3500]	valid_set's binary_logloss: 0.222809
[3550]	valid_set's binary_logloss: 0.222802
[3600]	valid_set's binary_logloss: 0.222823
[3650]	valid_set's binary_logloss: 0.222897
[3700]	valid_set's binary_logloss: 0.222944
[3750]	valid_set's binary_logloss: 0.222977
[3800]	valid_set's binary_logloss: 0.22304
[3850]	valid_set's binary_logloss: 0.223085
[3900]	valid_set's binary_logloss: 0.223102
[3950]	valid_set's binary_logloss: 0.223135
[4000]	valid_set's binary_logloss: 0.223165

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269758
[100]	valid_set's binary_logloss: 0.25074
[150]	valid_set's binary_logloss: 0.244133
[200]	valid_set's binary_logloss: 0.241077
[250]	valid_set's binary_logloss: 0.239023
[300]	valid_set's binary_logloss: 0.237801
[350]	valid_set's binary_logloss: 0.236798
[400]	valid_set's binary_logloss: 0.235809
[450]	valid_set's binary_logloss: 0.234957
[500]	valid_set's binary_logloss: 0.234396
[550]	valid_set's binary_logloss: 0.233982
[600]	valid_set's binary_logloss: 0.233489
[650]	valid_set's binary_logloss: 0.233174
[700]	valid_set's binary_logloss: 0.232828
[750]	valid_set's binary_logloss: 0.232631
[800]	valid_set's binary_logloss: 0.232226
[850]	valid_set's binary_logloss: 0.231768
[900]	valid_set's binary_logloss: 0.231521
[950]	valid_set's binary_logloss: 0.231244
[1000]	valid_set's binary_logloss: 0.231076
[1050]	valid_set's binary_logloss: 0.23088
[1100]	valid_set's binary_logloss: 0.230728
[1150]	valid_set's binary_logloss: 0.230612
[1200]	valid_set's binary_logloss: 0.230489
[1250]	valid_set's binary_logloss: 0.230315
[1300]	valid_set's binary_logloss: 0.23022
[1350]	valid_set's binary_logloss: 0.230146
[1400]	valid_set's binary_logloss: 0.230017
[1450]	valid_set's binary_logloss: 0.229881
[1500]	valid_set's binary_logloss: 0.229828
[1550]	valid_set's binary_logloss: 0.229791
[1600]	valid_set's binary_logloss: 0.229765
[1650]	valid_set's binary_logloss: 0.229644
[1700]	valid_set's binary_logloss: 0.229667
[1750]	valid_set's binary_logloss: 0.229582
[1800]	valid_set's binary_logloss: 0.229578
[1850]	valid_set's binary_logloss: 0.229519
[1900]	valid_set's binary_logloss: 0.229456
[1950]	valid_set's binary_logloss: 0.229413
[2000]	valid_set's binary_logloss: 0.229352
[2050]	valid_set's binary_logloss: 0.229329
[2100]	valid_set's binary_logloss: 0.229307
[2150]	valid_set's binary_logloss: 0.229264
[2200]	valid_set's binary_logloss: 0.229253
[2250]	valid_set's binary_logloss: 0.229231
[2300]	valid_set's binary_logloss: 0.229194
[2350]	valid_set's binary_logloss: 0.229193
[2400]	valid_set's binary_logloss: 0.229105
[2450]	valid_set's binary_logloss: 0.229081
[2500]	valid_set's binary_logloss: 0.229035
[2550]	valid_set's binary_logloss: 0.229028
[2600]	valid_set's binary_logloss: 0.228999
[2650]	valid_set's binary_logloss: 0.228999
[2700]	valid_set's binary_logloss: 0.229002
[2750]	valid_set's binary_logloss: 0.228977
[2800]	valid_set's binary_logloss: 0.228966
[2850]	valid_set's binary_logloss: 0.228998
[2900]	valid_set's binary_logloss: 0.229015
[2950]	valid_set's binary_logloss: 0.229065
[3000]	valid_set's binary_logloss: 0.229121
[3050]	valid_set's binary_logloss: 0.229134
[3100]	valid_set's binary_logloss: 0.229109
[3150]	valid_set's binary_logloss: 0.229031
[3200]	valid_set's binary_logloss: 0.228958
[3250]	valid_set's binary_logloss: 0.228949
[3300]	valid_set's binary_logloss: 0.228933
[3350]	valid_set's binary_logloss: 0.228934
[3400]	valid_set's binary_logloss: 0.228991
[3450]	valid_set's binary_logloss: 0.229043
[3500]	valid_set's binary_logloss: 0.229118
[3550]	valid_set's binary_logloss: 0.22916
[3600]	valid_set's binary_logloss: 0.229173
[3650]	valid_set's binary_logloss: 0.229219
[3700]	valid_set's binary_logloss: 0.229269
[3750]	valid_set's binary_logloss: 0.229315
[3800]	valid_set's binary_logloss: 0.229349
[3850]	valid_set's binary_logloss: 0.229355
[3900]	valid_set's binary_logloss: 0.229405
[3950]	valid_set's binary_logloss: 0.229467
[4000]	valid_set's binary_logloss: 0.229466
[4050]	valid_set's binary_logloss: 0.229487
[4100]	valid_set's binary_logloss: 0.229539
[4150]	valid_set's binary_logloss: 0.22958
[4200]	valid_set's binary_logloss: 0.229612
[4250]	valid_set's binary_logloss: 0.229653
[4300]	valid_set's binary_logloss: 0.229679

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.268974
[100]	valid_set's binary_logloss: 0.249652
[150]	valid_set's binary_logloss: 0.243161
[200]	valid_set's binary_logloss: 0.239657
[250]	valid_set's binary_logloss: 0.237462
[300]	valid_set's binary_logloss: 0.236084
[350]	valid_set's binary_logloss: 0.235053
[400]	valid_set's binary_logloss: 0.234244
[450]	valid_set's binary_logloss: 0.233363
[500]	valid_set's binary_logloss: 0.232659
[550]	valid_set's binary_logloss: 0.232138
[600]	valid_set's binary_logloss: 0.231639
[650]	valid_set's binary_logloss: 0.231255
[700]	valid_set's binary_logloss: 0.230773
[750]	valid_set's binary_logloss: 0.230453
[800]	valid_set's binary_logloss: 0.230253
[850]	valid_set's binary_logloss: 0.229973
[900]	valid_set's binary_logloss: 0.229762
[950]	valid_set's binary_logloss: 0.229557
[1000]	valid_set's binary_logloss: 0.229373
[1050]	valid_set's binary_logloss: 0.229193
[1100]	valid_set's binary_logloss: 0.229045
[1150]	valid_set's binary_logloss: 0.228865
[1200]	valid_set's binary_logloss: 0.228744
[1250]	valid_set's binary_logloss: 0.228606
[1300]	valid_set's binary_logloss: 0.228468
[1350]	valid_set's binary_logloss: 0.228278
[1400]	valid_set's binary_logloss: 0.228187
[1450]	valid_set's binary_logloss: 0.228062
[1500]	valid_set's binary_logloss: 0.228047
[1550]	valid_set's binary_logloss: 0.227969
[1600]	valid_set's binary_logloss: 0.227879
[1650]	valid_set's binary_logloss: 0.227847
[1700]	valid_set's binary_logloss: 0.227827
[1750]	valid_set's binary_logloss: 0.227818
[1800]	valid_set's binary_logloss: 0.227776
[1850]	valid_set's binary_logloss: 0.227701
[1900]	valid_set's binary_logloss: 0.227692
[1950]	valid_set's binary_logloss: 0.227627
[2000]	valid_set's binary_logloss: 0.227617
[2050]	valid_set's binary_logloss: 0.227611
[2100]	valid_set's binary_logloss: 0.227495
[2150]	valid_set's binary_logloss: 0.227485
[2200]	valid_set's binary_logloss: 0.227489
[2250]	valid_set's binary_logloss: 0.227456
[2300]	valid_set's binary_logloss: 0.227466
[2350]	valid_set's binary_logloss: 0.227436
[2400]	valid_set's binary_logloss: 0.227417
[2450]	valid_set's binary_logloss: 0.227415
[2500]	valid_set's binary_logloss: 0.227386
[2550]	valid_set's binary_logloss: 0.22743
[2600]	valid_set's binary_logloss: 0.22744
[2650]	valid_set's binary_logloss: 0.227403
[2700]	valid_set's binary_logloss: 0.227362
[2750]	valid_set's binary_logloss: 0.227332
[2800]	valid_set's binary_logloss: 0.227346
[2850]	valid_set's binary_logloss: 0.227419
[2900]	valid_set's binary_logloss: 0.227448
[2950]	valid_set's binary_logloss: 0.227508
[3000]	valid_set's binary_logloss: 0.227541
[3050]	valid_set's binary_logloss: 0.227498
[3100]	valid_set's binary_logloss: 0.22752
[3150]	valid_set's binary_logloss: 0.227535
[3200]	valid_set's binary_logloss: 0.227548
[3250]	valid_set's binary_logloss: 0.227528
[3300]	valid_set's binary_logloss: 0.227536
[3350]	valid_set's binary_logloss: 0.227517
[3400]	valid_set's binary_logloss: 0.22753
[3450]	valid_set's binary_logloss: 0.227505
[3500]	valid_set's binary_logloss: 0.227477
[3550]	valid_set's binary_logloss: 0.227498

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269394
[100]	valid_set's binary_logloss: 0.250973
[150]	valid_set's binary_logloss: 0.244589
[200]	valid_set's binary_logloss: 0.241092
[250]	valid_set's binary_logloss: 0.239246
[300]	valid_set's binary_logloss: 0.237569
[350]	valid_set's binary_logloss: 0.236671
[400]	valid_set's binary_logloss: 0.235893
[450]	valid_set's binary_logloss: 0.235216
[500]	valid_set's binary_logloss: 0.234683
[550]	valid_set's binary_logloss: 0.234099
[600]	valid_set's binary_logloss: 0.233667
[650]	valid_set's binary_logloss: 0.233194
[700]	valid_set's binary_logloss: 0.232836
[750]	valid_set's binary_logloss: 0.232513
[800]	valid_set's binary_logloss: 0.232205
[850]	valid_set's binary_logloss: 0.231894
[900]	valid_set's binary_logloss: 0.231619
[950]	valid_set's binary_logloss: 0.231416
[1000]	valid_set's binary_logloss: 0.231267
[1050]	valid_set's binary_logloss: 0.23113
[1100]	valid_set's binary_logloss: 0.230925
[1150]	valid_set's binary_logloss: 0.23081
[1200]	valid_set's binary_logloss: 0.230686
[1250]	valid_set's binary_logloss: 0.23055
[1300]	valid_set's binary_logloss: 0.230431
[1350]	valid_set's binary_logloss: 0.230361
[1400]	valid_set's binary_logloss: 0.230207
[1450]	valid_set's binary_logloss: 0.230084
[1500]	valid_set's binary_logloss: 0.229994
[1550]	valid_set's binary_logloss: 0.229855
[1600]	valid_set's binary_logloss: 0.229755
[1650]	valid_set's binary_logloss: 0.229741
[1700]	valid_set's binary_logloss: 0.229743
[1750]	valid_set's binary_logloss: 0.229678
[1800]	valid_set's binary_logloss: 0.229572
[1850]	valid_set's binary_logloss: 0.22953
[1900]	valid_set's binary_logloss: 0.229504
[1950]	valid_set's binary_logloss: 0.2294
[2000]	valid_set's binary_logloss: 0.229388
[2050]	valid_set's binary_logloss: 0.229336
[2100]	valid_set's binary_logloss: 0.229308
[2150]	valid_set's binary_logloss: 0.229258
[2200]	valid_set's binary_logloss: 0.229263
[2250]	valid_set's binary_logloss: 0.229213
[2300]	valid_set's binary_logloss: 0.229197
[2350]	valid_set's binary_logloss: 0.229183
[2400]	valid_set's binary_logloss: 0.229196
[2450]	valid_set's binary_logloss: 0.229201
[2500]	valid_set's binary_logloss: 0.229198
[2550]	valid_set's binary_logloss: 0.229219
[2600]	valid_set's binary_logloss: 0.229223
[2650]	valid_set's binary_logloss: 0.229181
[2700]	valid_set's binary_logloss: 0.229242
[2750]	valid_set's binary_logloss: 0.229258
[2800]	valid_set's binary_logloss: 0.229282
[2850]	valid_set's binary_logloss: 0.229264
[2900]	valid_set's binary_logloss: 0.229356
[2950]	valid_set's binary_logloss: 0.229291
[3000]	valid_set's binary_logloss: 0.229379
[3050]	valid_set's binary_logloss: 0.229458

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.269152
[100]	valid_set's binary_logloss: 0.25032
[150]	valid_set's binary_logloss: 0.243867
[200]	valid_set's binary_logloss: 0.240752
[250]	valid_set's binary_logloss: 0.239075
[300]	valid_set's binary_logloss: 0.237565
[350]	valid_set's binary_logloss: 0.236559
[400]	valid_set's binary_logloss: 0.235486
[450]	valid_set's binary_logloss: 0.234722
[500]	valid_set's binary_logloss: 0.234238
[550]	valid_set's binary_logloss: 0.233729
[600]	valid_set's binary_logloss: 0.233166
[650]	valid_set's binary_logloss: 0.232723
[700]	valid_set's binary_logloss: 0.232445
[750]	valid_set's binary_logloss: 0.232027
[800]	valid_set's binary_logloss: 0.231718
[850]	valid_set's binary_logloss: 0.231474
[900]	valid_set's binary_logloss: 0.231212
[950]	valid_set's binary_logloss: 0.230961
[1000]	valid_set's binary_logloss: 0.230808
[1050]	valid_set's binary_logloss: 0.230666
[1100]	valid_set's binary_logloss: 0.230455
[1150]	valid_set's binary_logloss: 0.230378
[1200]	valid_set's binary_logloss: 0.230262
[1250]	valid_set's binary_logloss: 0.230055
[1300]	valid_set's binary_logloss: 0.229954
[1350]	valid_set's binary_logloss: 0.229897
[1400]	valid_set's binary_logloss: 0.229685
[1450]	valid_set's binary_logloss: 0.229552
[1500]	valid_set's binary_logloss: 0.229522
[1550]	valid_set's binary_logloss: 0.229479
[1600]	valid_set's binary_logloss: 0.229481
[1650]	valid_set's binary_logloss: 0.229411
[1700]	valid_set's binary_logloss: 0.229315
[1750]	valid_set's binary_logloss: 0.229265
[1800]	valid_set's binary_logloss: 0.229174
[1850]	valid_set's binary_logloss: 0.229202
[1900]	valid_set's binary_logloss: 0.229199
[1950]	valid_set's binary_logloss: 0.229174
[2000]	valid_set's binary_logloss: 0.229212
[2050]	valid_set's binary_logloss: 0.229267
[2100]	valid_set's binary_logloss: 0.229291
[2150]	valid_set's binary_logloss: 0.229198
[2200]	valid_set's binary_logloss: 0.229039
[2250]	valid_set's binary_logloss: 0.229009
[2300]	valid_set's binary_logloss: 0.228945
[2350]	valid_set's binary_logloss: 0.228928
[2400]	valid_set's binary_logloss: 0.228975
[2450]	valid_set's binary_logloss: 0.228926
[2500]	valid_set's binary_logloss: 0.228959
[2550]	valid_set's binary_logloss: 0.229007
[2600]	valid_set's binary_logloss: 0.22903
[2650]	valid_set's binary_logloss: 0.229028
[2700]	valid_set's binary_logloss: 0.22912
[2750]	valid_set's binary_logloss: 0.229155
[2800]	valid_set's binary_logloss: 0.229176
[2850]	valid_set's binary_logloss: 0.229189
[2900]	valid_set's binary_logloss: 0.229192
[2950]	valid_set's binary_logloss: 0.229173
[3000]	valid_set's binary_logloss: 0.229216

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.266577
[100]	valid_set's binary_logloss: 0.247487
[150]	valid_set's binary_logloss: 0.240624
[200]	valid_set's binary_logloss: 0.237198
[250]	valid_set's binary_logloss: 0.235335
[300]	valid_set's binary_logloss: 0.233925
[350]	valid_set's binary_logloss: 0.232764
[400]	valid_set's binary_logloss: 0.231631
[450]	valid_set's binary_logloss: 0.23085
[500]	valid_set's binary_logloss: 0.230088
[550]	valid_set's binary_logloss: 0.22957
[600]	valid_set's binary_logloss: 0.22916
[650]	valid_set's binary_logloss: 0.22872
[700]	valid_set's binary_logloss: 0.228239
[750]	valid_set's binary_logloss: 0.227918
[800]	valid_set's binary_logloss: 0.227528
[850]	valid_set's binary_logloss: 0.227326
[900]	valid_set's binary_logloss: 0.227122
[950]	valid_set's binary_logloss: 0.226917
[1000]	valid_set's binary_logloss: 0.226828
[1050]	valid_set's binary_logloss: 0.226713
[1100]	valid_set's binary_logloss: 0.226544
[1150]	valid_set's binary_logloss: 0.226417
[1200]	valid_set's binary_logloss: 0.226275
[1250]	valid_set's binary_logloss: 0.226191
[1300]	valid_set's binary_logloss: 0.226038
[1350]	valid_set's binary_logloss: 0.225937
[1400]	valid_set's binary_logloss: 0.225853
[1450]	valid_set's binary_logloss: 0.22588
[1500]	valid_set's binary_logloss: 0.225826
[1550]	valid_set's binary_logloss: 0.225738
[1600]	valid_set's binary_logloss: 0.225595
[1650]	valid_set's binary_logloss: 0.225499
[1700]	valid_set's binary_logloss: 0.225421
[1750]	valid_set's binary_logloss: 0.225343
[1800]	valid_set's binary_logloss: 0.225351
[1850]	valid_set's binary_logloss: 0.225245
[1900]	valid_set's binary_logloss: 0.225212
[1950]	valid_set's binary_logloss: 0.22518
[2000]	valid_set's binary_logloss: 0.225206
[2050]	valid_set's binary_logloss: 0.225159
[2100]	valid_set's binary_logloss: 0.225095
[2150]	valid_set's binary_logloss: 0.225029
[2200]	valid_set's binary_logloss: 0.225011
[2250]	valid_set's binary_logloss: 0.225032
[2300]	valid_set's binary_logloss: 0.225002
[2350]	valid_set's binary_logloss: 0.224978
[2400]	valid_set's binary_logloss: 0.224979
[2450]	valid_set's binary_logloss: 0.224996
[2500]	valid_set's binary_logloss: 0.225024
[2550]	valid_set's binary_logloss: 0.225066
[2600]	valid_set's binary_logloss: 0.225046
[2650]	valid_set's binary_logloss: 0.225068
[2700]	valid_set's binary_logloss: 0.225056
[2750]	valid_set's binary_logloss: 0.225026
[2800]	valid_set's binary_logloss: 0.225021
[2850]	valid_set's binary_logloss: 0.225036
[2900]	valid_set's binary_logloss: 0.225006
[2950]	valid_set's binary_logloss: 0.225017
[3000]	valid_set's binary_logloss: 0.225012
[3050]	valid_set's binary_logloss: 0.225042

Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\model.pkl
	0.9482	 = Validation score   (roc_auc)
	101.51s	 = Training   runtime
	4.35s	 = Validation runtime
	12631.6	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1691.85s of the 1691.85s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283036
[100]	valid_set's binary_logloss: 0.258718
[150]	valid_set's binary_logloss: 0.249051
[200]	valid_set's binary_logloss: 0.243936
[250]	valid_set's binary_logloss: 0.240893
[300]	valid_set's binary_logloss: 0.238698
[350]	valid_set's binary_logloss: 0.237111
[400]	valid_set's binary_logloss: 0.236061
[450]	valid_set's binary_logloss: 0.23525
[500]	valid_set's binary_logloss: 0.234543
[550]	valid_set's binary_logloss: 0.23398
[600]	valid_set's binary_logloss: 0.233437
[650]	valid_set's binary_logloss: 0.232978
[700]	valid_set's binary_logloss: 0.232661
[750]	valid_set's binary_logloss: 0.232345
[800]	valid_set's binary_logloss: 0.231994
[850]	valid_set's binary_logloss: 0.231727
[900]	valid_set's binary_logloss: 0.231462
[950]	valid_set's binary_logloss: 0.231213
[1000]	valid_set's binary_logloss: 0.230936
[1050]	valid_set's binary_logloss: 0.230782
[1100]	valid_set's binary_logloss: 0.230607
[1150]	valid_set's binary_logloss: 0.230501
[1200]	valid_set's binary_logloss: 0.230389
[1250]	valid_set's binary_logloss: 0.230295
[1300]	valid_set's binary_logloss: 0.230154
[1350]	valid_set's binary_logloss: 0.230086
[1400]	valid_set's binary_logloss: 0.229967
[1450]	valid_set's binary_logloss: 0.229866
[1500]	valid_set's binary_logloss: 0.229802
[1550]	valid_set's binary_logloss: 0.229668
[1600]	valid_set's binary_logloss: 0.22957
[1650]	valid_set's binary_logloss: 0.229465
[1700]	valid_set's binary_logloss: 0.229418
[1750]	valid_set's binary_logloss: 0.229339
[1800]	valid_set's binary_logloss: 0.229251
[1850]	valid_set's binary_logloss: 0.229156
[1900]	valid_set's binary_logloss: 0.229128
[1950]	valid_set's binary_logloss: 0.229116
[2000]	valid_set's binary_logloss: 0.229102
[2050]	valid_set's binary_logloss: 0.229049
[2100]	valid_set's binary_logloss: 0.228983
[2150]	valid_set's binary_logloss: 0.228918
[2200]	valid_set's binary_logloss: 0.228882
[2250]	valid_set's binary_logloss: 0.228848
[2300]	valid_set's binary_logloss: 0.228875
[2350]	valid_set's binary_logloss: 0.228821
[2400]	valid_set's binary_logloss: 0.228844
[2450]	valid_set's binary_logloss: 0.228839
[2500]	valid_set's binary_logloss: 0.228835
[2550]	valid_set's binary_logloss: 0.228809
[2600]	valid_set's binary_logloss: 0.228808
[2650]	valid_set's binary_logloss: 0.228829
[2700]	valid_set's binary_logloss: 0.228834
[2750]	valid_set's binary_logloss: 0.2288
[2800]	valid_set's binary_logloss: 0.22877
[2850]	valid_set's binary_logloss: 0.228787
[2900]	valid_set's binary_logloss: 0.228793
[2950]	valid_set's binary_logloss: 0.228753
[3000]	valid_set's binary_logloss: 0.228706
[3050]	valid_set's binary_logloss: 0.228702
[3100]	valid_set's binary_logloss: 0.228653
[3150]	valid_set's binary_logloss: 0.22856
[3200]	valid_set's binary_logloss: 0.228555
[3250]	valid_set's binary_logloss: 0.228537
[3300]	valid_set's binary_logloss: 0.228541
[3350]	valid_set's binary_logloss: 0.228529
[3400]	valid_set's binary_logloss: 0.228542
[3450]	valid_set's binary_logloss: 0.228572
[3500]	valid_set's binary_logloss: 0.22854
[3550]	valid_set's binary_logloss: 0.228569
[3600]	valid_set's binary_logloss: 0.228573
[3650]	valid_set's binary_logloss: 0.228551
[3700]	valid_set's binary_logloss: 0.228542
[3750]	valid_set's binary_logloss: 0.228537
[3800]	valid_set's binary_logloss: 0.228542
[3850]	valid_set's binary_logloss: 0.228547
[3900]	valid_set's binary_logloss: 0.228505
[3950]	valid_set's binary_logloss: 0.228457
[4000]	valid_set's binary_logloss: 0.228406
[4050]	valid_set's binary_logloss: 0.228432
[4100]	valid_set's binary_logloss: 0.22844
[4150]	valid_set's binary_logloss: 0.228449
[4200]	valid_set's binary_logloss: 0.228464
[4250]	valid_set's binary_logloss: 0.228425
[4300]	valid_set's binary_logloss: 0.228474
[4350]	valid_set's binary_logloss: 0.228496
[4400]	valid_set's binary_logloss: 0.228461
[4450]	valid_set's binary_logloss: 0.22846
[4500]	valid_set's binary_logloss: 0.228459
[4550]	valid_set's binary_logloss: 0.228468
[4600]	valid_set's binary_logloss: 0.228519
[4650]	valid_set's binary_logloss: 0.228524
[4700]	valid_set's binary_logloss: 0.228536
[4750]	valid_set's binary_logloss: 0.228548
[4800]	valid_set's binary_logloss: 0.228623
[4850]	valid_set's binary_logloss: 0.228663
[4900]	valid_set's binary_logloss: 0.228711
[4950]	valid_set's binary_logloss: 0.228691
[5000]	valid_set's binary_logloss: 0.228703
[5050]	valid_set's binary_logloss: 0.228693
[5100]	valid_set's binary_logloss: 0.228713
[5150]	valid_set's binary_logloss: 0.228734
[5200]	valid_set's binary_logloss: 0.228753

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284636
[100]	valid_set's binary_logloss: 0.258861
[150]	valid_set's binary_logloss: 0.249516
[200]	valid_set's binary_logloss: 0.244295
[250]	valid_set's binary_logloss: 0.240991
[300]	valid_set's binary_logloss: 0.238813
[350]	valid_set's binary_logloss: 0.237174
[400]	valid_set's binary_logloss: 0.235956
[450]	valid_set's binary_logloss: 0.23495
[500]	valid_set's binary_logloss: 0.234231
[550]	valid_set's binary_logloss: 0.233674
[600]	valid_set's binary_logloss: 0.23313
[650]	valid_set's binary_logloss: 0.232615
[700]	valid_set's binary_logloss: 0.23227
[750]	valid_set's binary_logloss: 0.23193
[800]	valid_set's binary_logloss: 0.231716
[850]	valid_set's binary_logloss: 0.231429
[900]	valid_set's binary_logloss: 0.231184
[950]	valid_set's binary_logloss: 0.230997
[1000]	valid_set's binary_logloss: 0.230768
[1050]	valid_set's binary_logloss: 0.230637
[1100]	valid_set's binary_logloss: 0.230435
[1150]	valid_set's binary_logloss: 0.23025
[1200]	valid_set's binary_logloss: 0.230113
[1250]	valid_set's binary_logloss: 0.230023
[1300]	valid_set's binary_logloss: 0.229844
[1350]	valid_set's binary_logloss: 0.229728
[1400]	valid_set's binary_logloss: 0.229697
[1450]	valid_set's binary_logloss: 0.229621
[1500]	valid_set's binary_logloss: 0.229575
[1550]	valid_set's binary_logloss: 0.229465
[1600]	valid_set's binary_logloss: 0.229419
[1650]	valid_set's binary_logloss: 0.229399
[1700]	valid_set's binary_logloss: 0.229294
[1750]	valid_set's binary_logloss: 0.229246
[1800]	valid_set's binary_logloss: 0.229141
[1850]	valid_set's binary_logloss: 0.229096
[1900]	valid_set's binary_logloss: 0.229012
[1950]	valid_set's binary_logloss: 0.22894
[2000]	valid_set's binary_logloss: 0.22889
[2050]	valid_set's binary_logloss: 0.228878
[2100]	valid_set's binary_logloss: 0.228886
[2150]	valid_set's binary_logloss: 0.228863
[2200]	valid_set's binary_logloss: 0.228803
[2250]	valid_set's binary_logloss: 0.228715
[2300]	valid_set's binary_logloss: 0.228705
[2350]	valid_set's binary_logloss: 0.22865
[2400]	valid_set's binary_logloss: 0.22864
[2450]	valid_set's binary_logloss: 0.228571
[2500]	valid_set's binary_logloss: 0.228553
[2550]	valid_set's binary_logloss: 0.228559
[2600]	valid_set's binary_logloss: 0.228509
[2650]	valid_set's binary_logloss: 0.228483
[2700]	valid_set's binary_logloss: 0.228452
[2750]	valid_set's binary_logloss: 0.228437
[2800]	valid_set's binary_logloss: 0.228462
[2850]	valid_set's binary_logloss: 0.228522
[2900]	valid_set's binary_logloss: 0.228518
[2950]	valid_set's binary_logloss: 0.228498
[3000]	valid_set's binary_logloss: 0.228477
[3050]	valid_set's binary_logloss: 0.228483
[3100]	valid_set's binary_logloss: 0.228482
[3150]	valid_set's binary_logloss: 0.228479
[3200]	valid_set's binary_logloss: 0.228475
[3250]	valid_set's binary_logloss: 0.228492
[3300]	valid_set's binary_logloss: 0.228515
[3350]	valid_set's binary_logloss: 0.228537
[3400]	valid_set's binary_logloss: 0.22857
[3450]	valid_set's binary_logloss: 0.22856
[3500]	valid_set's binary_logloss: 0.228569
[3550]	valid_set's binary_logloss: 0.22853
[3600]	valid_set's binary_logloss: 0.228521

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.277433
[100]	valid_set's binary_logloss: 0.254013
[150]	valid_set's binary_logloss: 0.244794
[200]	valid_set's binary_logloss: 0.239356
[250]	valid_set's binary_logloss: 0.236158
[300]	valid_set's binary_logloss: 0.233973
[350]	valid_set's binary_logloss: 0.232525
[400]	valid_set's binary_logloss: 0.231453
[450]	valid_set's binary_logloss: 0.230533
[500]	valid_set's binary_logloss: 0.229783
[550]	valid_set's binary_logloss: 0.22916
[600]	valid_set's binary_logloss: 0.228422
[650]	valid_set's binary_logloss: 0.228007
[700]	valid_set's binary_logloss: 0.227624
[750]	valid_set's binary_logloss: 0.227237
[800]	valid_set's binary_logloss: 0.226856
[850]	valid_set's binary_logloss: 0.226635
[900]	valid_set's binary_logloss: 0.226362
[950]	valid_set's binary_logloss: 0.22614
[1000]	valid_set's binary_logloss: 0.225958
[1050]	valid_set's binary_logloss: 0.225765
[1100]	valid_set's binary_logloss: 0.225599
[1150]	valid_set's binary_logloss: 0.225408
[1200]	valid_set's binary_logloss: 0.22539
[1250]	valid_set's binary_logloss: 0.225307
[1300]	valid_set's binary_logloss: 0.225235
[1350]	valid_set's binary_logloss: 0.225182
[1400]	valid_set's binary_logloss: 0.225071
[1450]	valid_set's binary_logloss: 0.224958
[1500]	valid_set's binary_logloss: 0.224861
[1550]	valid_set's binary_logloss: 0.224786
[1600]	valid_set's binary_logloss: 0.224695
[1650]	valid_set's binary_logloss: 0.224614
[1700]	valid_set's binary_logloss: 0.224535
[1750]	valid_set's binary_logloss: 0.224474
[1800]	valid_set's binary_logloss: 0.224312
[1850]	valid_set's binary_logloss: 0.224273
[1900]	valid_set's binary_logloss: 0.2242
[1950]	valid_set's binary_logloss: 0.22411
[2000]	valid_set's binary_logloss: 0.224056
[2050]	valid_set's binary_logloss: 0.224027
[2100]	valid_set's binary_logloss: 0.223996
[2150]	valid_set's binary_logloss: 0.223887
[2200]	valid_set's binary_logloss: 0.223824
[2250]	valid_set's binary_logloss: 0.223774
[2300]	valid_set's binary_logloss: 0.223729
[2350]	valid_set's binary_logloss: 0.223694
[2400]	valid_set's binary_logloss: 0.223716
[2450]	valid_set's binary_logloss: 0.223678
[2500]	valid_set's binary_logloss: 0.223598
[2550]	valid_set's binary_logloss: 0.223571
[2600]	valid_set's binary_logloss: 0.223575
[2650]	valid_set's binary_logloss: 0.223532
[2700]	valid_set's binary_logloss: 0.223516
[2750]	valid_set's binary_logloss: 0.223496
[2800]	valid_set's binary_logloss: 0.223452
[2850]	valid_set's binary_logloss: 0.223393
[2900]	valid_set's binary_logloss: 0.223412
[2950]	valid_set's binary_logloss: 0.223394
[3000]	valid_set's binary_logloss: 0.223374
[3050]	valid_set's binary_logloss: 0.223357
[3100]	valid_set's binary_logloss: 0.223326
[3150]	valid_set's binary_logloss: 0.223321
[3200]	valid_set's binary_logloss: 0.223271
[3250]	valid_set's binary_logloss: 0.223228
[3300]	valid_set's binary_logloss: 0.223224
[3350]	valid_set's binary_logloss: 0.223205
[3400]	valid_set's binary_logloss: 0.223175
[3450]	valid_set's binary_logloss: 0.223179
[3500]	valid_set's binary_logloss: 0.223227
[3550]	valid_set's binary_logloss: 0.223236
[3600]	valid_set's binary_logloss: 0.223276
[3650]	valid_set's binary_logloss: 0.223267
[3700]	valid_set's binary_logloss: 0.223295
[3750]	valid_set's binary_logloss: 0.223275
[3800]	valid_set's binary_logloss: 0.223288
[3850]	valid_set's binary_logloss: 0.223343
[3900]	valid_set's binary_logloss: 0.223334
[3950]	valid_set's binary_logloss: 0.223278
[4000]	valid_set's binary_logloss: 0.223254
[4050]	valid_set's binary_logloss: 0.223276
[4100]	valid_set's binary_logloss: 0.223288
[4150]	valid_set's binary_logloss: 0.223329
[4200]	valid_set's binary_logloss: 0.22333
[4250]	valid_set's binary_logloss: 0.223355
[4300]	valid_set's binary_logloss: 0.223328
[4350]	valid_set's binary_logloss: 0.223349
[4400]	valid_set's binary_logloss: 0.223318

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.285006
[100]	valid_set's binary_logloss: 0.259476
[150]	valid_set's binary_logloss: 0.249965
[200]	valid_set's binary_logloss: 0.245433
[250]	valid_set's binary_logloss: 0.242104
[300]	valid_set's binary_logloss: 0.240003
[350]	valid_set's binary_logloss: 0.23857
[400]	valid_set's binary_logloss: 0.237466
[450]	valid_set's binary_logloss: 0.236565
[500]	valid_set's binary_logloss: 0.235851
[550]	valid_set's binary_logloss: 0.235145
[600]	valid_set's binary_logloss: 0.234672
[650]	valid_set's binary_logloss: 0.234228
[700]	valid_set's binary_logloss: 0.233901
[750]	valid_set's binary_logloss: 0.233578
[800]	valid_set's binary_logloss: 0.233297
[850]	valid_set's binary_logloss: 0.233076
[900]	valid_set's binary_logloss: 0.232837
[950]	valid_set's binary_logloss: 0.232595
[1000]	valid_set's binary_logloss: 0.232393
[1050]	valid_set's binary_logloss: 0.232167
[1100]	valid_set's binary_logloss: 0.231946
[1150]	valid_set's binary_logloss: 0.231756
[1200]	valid_set's binary_logloss: 0.231546
[1250]	valid_set's binary_logloss: 0.231404
[1300]	valid_set's binary_logloss: 0.231198
[1350]	valid_set's binary_logloss: 0.231124
[1400]	valid_set's binary_logloss: 0.230929
[1450]	valid_set's binary_logloss: 0.230792
[1500]	valid_set's binary_logloss: 0.230709
[1550]	valid_set's binary_logloss: 0.230674
[1600]	valid_set's binary_logloss: 0.230516
[1650]	valid_set's binary_logloss: 0.230405
[1700]	valid_set's binary_logloss: 0.230345
[1750]	valid_set's binary_logloss: 0.230246
[1800]	valid_set's binary_logloss: 0.230152
[1850]	valid_set's binary_logloss: 0.23009
[1900]	valid_set's binary_logloss: 0.230025
[1950]	valid_set's binary_logloss: 0.229939
[2000]	valid_set's binary_logloss: 0.229861
[2050]	valid_set's binary_logloss: 0.229802
[2100]	valid_set's binary_logloss: 0.229762
[2150]	valid_set's binary_logloss: 0.229721
[2200]	valid_set's binary_logloss: 0.229669
[2250]	valid_set's binary_logloss: 0.229634
[2300]	valid_set's binary_logloss: 0.229607
[2350]	valid_set's binary_logloss: 0.229595
[2400]	valid_set's binary_logloss: 0.229569
[2450]	valid_set's binary_logloss: 0.229518
[2500]	valid_set's binary_logloss: 0.229537
[2550]	valid_set's binary_logloss: 0.229527
[2600]	valid_set's binary_logloss: 0.229466
[2650]	valid_set's binary_logloss: 0.22948
[2700]	valid_set's binary_logloss: 0.229468
[2750]	valid_set's binary_logloss: 0.229419
[2800]	valid_set's binary_logloss: 0.229401
[2850]	valid_set's binary_logloss: 0.229392
[2900]	valid_set's binary_logloss: 0.229381
[2950]	valid_set's binary_logloss: 0.22936
[3000]	valid_set's binary_logloss: 0.229329
[3050]	valid_set's binary_logloss: 0.229277
[3100]	valid_set's binary_logloss: 0.229297
[3150]	valid_set's binary_logloss: 0.22931
[3200]	valid_set's binary_logloss: 0.229342
[3250]	valid_set's binary_logloss: 0.229335
[3300]	valid_set's binary_logloss: 0.229292
[3350]	valid_set's binary_logloss: 0.229237
[3400]	valid_set's binary_logloss: 0.229211
[3450]	valid_set's binary_logloss: 0.229263
[3500]	valid_set's binary_logloss: 0.229259
[3550]	valid_set's binary_logloss: 0.229265
[3600]	valid_set's binary_logloss: 0.229268
[3650]	valid_set's binary_logloss: 0.22926
[3700]	valid_set's binary_logloss: 0.22922
[3750]	valid_set's binary_logloss: 0.229205
[3800]	valid_set's binary_logloss: 0.229195
[3850]	valid_set's binary_logloss: 0.229162
[3900]	valid_set's binary_logloss: 0.229228
[3950]	valid_set's binary_logloss: 0.229265
[4000]	valid_set's binary_logloss: 0.229258
[4050]	valid_set's binary_logloss: 0.229287
[4100]	valid_set's binary_logloss: 0.229283
[4150]	valid_set's binary_logloss: 0.229316
[4200]	valid_set's binary_logloss: 0.229325
[4250]	valid_set's binary_logloss: 0.229318
[4300]	valid_set's binary_logloss: 0.229286
[4350]	valid_set's binary_logloss: 0.229285
[4400]	valid_set's binary_logloss: 0.229248
[4450]	valid_set's binary_logloss: 0.229232
[4500]	valid_set's binary_logloss: 0.229235
[4550]	valid_set's binary_logloss: 0.229282
[4600]	valid_set's binary_logloss: 0.229322
[4650]	valid_set's binary_logloss: 0.229349
[4700]	valid_set's binary_logloss: 0.229369
[4750]	valid_set's binary_logloss: 0.229369
[4800]	valid_set's binary_logloss: 0.229395
[4850]	valid_set's binary_logloss: 0.229406
[4900]	valid_set's binary_logloss: 0.229433
[4950]	valid_set's binary_logloss: 0.229436
[5000]	valid_set's binary_logloss: 0.229469

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283372
[100]	valid_set's binary_logloss: 0.25922
[150]	valid_set's binary_logloss: 0.249802
[200]	valid_set's binary_logloss: 0.244502
[250]	valid_set's binary_logloss: 0.241352
[300]	valid_set's binary_logloss: 0.239013
[350]	valid_set's binary_logloss: 0.237514
[400]	valid_set's binary_logloss: 0.2361
[450]	valid_set's binary_logloss: 0.235123
[500]	valid_set's binary_logloss: 0.234482
[550]	valid_set's binary_logloss: 0.233932
[600]	valid_set's binary_logloss: 0.233481
[650]	valid_set's binary_logloss: 0.232919
[700]	valid_set's binary_logloss: 0.232579
[750]	valid_set's binary_logloss: 0.232212
[800]	valid_set's binary_logloss: 0.231919
[850]	valid_set's binary_logloss: 0.231573
[900]	valid_set's binary_logloss: 0.231344
[950]	valid_set's binary_logloss: 0.231037
[1000]	valid_set's binary_logloss: 0.230788
[1050]	valid_set's binary_logloss: 0.23059
[1100]	valid_set's binary_logloss: 0.23039
[1150]	valid_set's binary_logloss: 0.230258
[1200]	valid_set's binary_logloss: 0.230087
[1250]	valid_set's binary_logloss: 0.229924
[1300]	valid_set's binary_logloss: 0.229802
[1350]	valid_set's binary_logloss: 0.229664
[1400]	valid_set's binary_logloss: 0.229552
[1450]	valid_set's binary_logloss: 0.229486
[1500]	valid_set's binary_logloss: 0.229344
[1550]	valid_set's binary_logloss: 0.229211
[1600]	valid_set's binary_logloss: 0.229125
[1650]	valid_set's binary_logloss: 0.228995
[1700]	valid_set's binary_logloss: 0.228925
[1750]	valid_set's binary_logloss: 0.228904
[1800]	valid_set's binary_logloss: 0.228837
[1850]	valid_set's binary_logloss: 0.228764
[1900]	valid_set's binary_logloss: 0.228669
[1950]	valid_set's binary_logloss: 0.228613
[2000]	valid_set's binary_logloss: 0.228549
[2050]	valid_set's binary_logloss: 0.228448
[2100]	valid_set's binary_logloss: 0.228406
[2150]	valid_set's binary_logloss: 0.228383
[2200]	valid_set's binary_logloss: 0.228356
[2250]	valid_set's binary_logloss: 0.228337
[2300]	valid_set's binary_logloss: 0.228317
[2350]	valid_set's binary_logloss: 0.228286
[2400]	valid_set's binary_logloss: 0.228227
[2450]	valid_set's binary_logloss: 0.228183
[2500]	valid_set's binary_logloss: 0.22816
[2550]	valid_set's binary_logloss: 0.228089
[2600]	valid_set's binary_logloss: 0.228056
[2650]	valid_set's binary_logloss: 0.228033
[2700]	valid_set's binary_logloss: 0.228003
[2750]	valid_set's binary_logloss: 0.227979
[2800]	valid_set's binary_logloss: 0.227946
[2850]	valid_set's binary_logloss: 0.227917
[2900]	valid_set's binary_logloss: 0.22789
[2950]	valid_set's binary_logloss: 0.227889
[3000]	valid_set's binary_logloss: 0.227923
[3050]	valid_set's binary_logloss: 0.227951
[3100]	valid_set's binary_logloss: 0.22795
[3150]	valid_set's binary_logloss: 0.227924
[3200]	valid_set's binary_logloss: 0.227854
[3250]	valid_set's binary_logloss: 0.227867
[3300]	valid_set's binary_logloss: 0.227878
[3350]	valid_set's binary_logloss: 0.227841
[3400]	valid_set's binary_logloss: 0.22781
[3450]	valid_set's binary_logloss: 0.227747
[3500]	valid_set's binary_logloss: 0.227758
[3550]	valid_set's binary_logloss: 0.227722
[3600]	valid_set's binary_logloss: 0.227688
[3650]	valid_set's binary_logloss: 0.227695
[3700]	valid_set's binary_logloss: 0.22769
[3750]	valid_set's binary_logloss: 0.227696
[3800]	valid_set's binary_logloss: 0.227701
[3850]	valid_set's binary_logloss: 0.227675
[3900]	valid_set's binary_logloss: 0.227693
[3950]	valid_set's binary_logloss: 0.2277
[4000]	valid_set's binary_logloss: 0.227697
[4050]	valid_set's binary_logloss: 0.227733
[4100]	valid_set's binary_logloss: 0.227735
[4150]	valid_set's binary_logloss: 0.227774
[4200]	valid_set's binary_logloss: 0.2278
[4250]	valid_set's binary_logloss: 0.227751
[4300]	valid_set's binary_logloss: 0.227784
[4350]	valid_set's binary_logloss: 0.22779
[4400]	valid_set's binary_logloss: 0.227777
[4450]	valid_set's binary_logloss: 0.22773
[4500]	valid_set's binary_logloss: 0.227744
[4550]	valid_set's binary_logloss: 0.22778
[4600]	valid_set's binary_logloss: 0.227804
[4650]	valid_set's binary_logloss: 0.2278
[4700]	valid_set's binary_logloss: 0.227763
[4750]	valid_set's binary_logloss: 0.227767
[4800]	valid_set's binary_logloss: 0.227773
[4850]	valid_set's binary_logloss: 0.227805
[4900]	valid_set's binary_logloss: 0.227811
[4950]	valid_set's binary_logloss: 0.227808
[5000]	valid_set's binary_logloss: 0.227807

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282531
[100]	valid_set's binary_logloss: 0.259115
[150]	valid_set's binary_logloss: 0.2496
[200]	valid_set's binary_logloss: 0.244679
[250]	valid_set's binary_logloss: 0.241623
[300]	valid_set's binary_logloss: 0.239507
[350]	valid_set's binary_logloss: 0.237989
[400]	valid_set's binary_logloss: 0.236884
[450]	valid_set's binary_logloss: 0.236064
[500]	valid_set's binary_logloss: 0.235346
[550]	valid_set's binary_logloss: 0.234775
[600]	valid_set's binary_logloss: 0.234345
[650]	valid_set's binary_logloss: 0.233939
[700]	valid_set's binary_logloss: 0.23365
[750]	valid_set's binary_logloss: 0.23332
[800]	valid_set's binary_logloss: 0.233025
[850]	valid_set's binary_logloss: 0.232773
[900]	valid_set's binary_logloss: 0.232507
[950]	valid_set's binary_logloss: 0.232312
[1000]	valid_set's binary_logloss: 0.232141
[1050]	valid_set's binary_logloss: 0.231994
[1100]	valid_set's binary_logloss: 0.231851
[1150]	valid_set's binary_logloss: 0.231658
[1200]	valid_set's binary_logloss: 0.231512
[1250]	valid_set's binary_logloss: 0.231391
[1300]	valid_set's binary_logloss: 0.231293
[1350]	valid_set's binary_logloss: 0.23115
[1400]	valid_set's binary_logloss: 0.231048
[1450]	valid_set's binary_logloss: 0.230908
[1500]	valid_set's binary_logloss: 0.230801
[1550]	valid_set's binary_logloss: 0.230657
[1600]	valid_set's binary_logloss: 0.23059
[1650]	valid_set's binary_logloss: 0.230502
[1700]	valid_set's binary_logloss: 0.230462
[1750]	valid_set's binary_logloss: 0.230371
[1800]	valid_set's binary_logloss: 0.230315
[1850]	valid_set's binary_logloss: 0.230203
[1900]	valid_set's binary_logloss: 0.230165
[1950]	valid_set's binary_logloss: 0.23012
[2000]	valid_set's binary_logloss: 0.230101
[2050]	valid_set's binary_logloss: 0.23
[2100]	valid_set's binary_logloss: 0.229935
[2150]	valid_set's binary_logloss: 0.229899
[2200]	valid_set's binary_logloss: 0.229837
[2250]	valid_set's binary_logloss: 0.229792
[2300]	valid_set's binary_logloss: 0.229792
[2350]	valid_set's binary_logloss: 0.229725
[2400]	valid_set's binary_logloss: 0.229726
[2450]	valid_set's binary_logloss: 0.229722
[2500]	valid_set's binary_logloss: 0.229725
[2550]	valid_set's binary_logloss: 0.229733
[2600]	valid_set's binary_logloss: 0.229733
[2650]	valid_set's binary_logloss: 0.229755
[2700]	valid_set's binary_logloss: 0.229661
[2750]	valid_set's binary_logloss: 0.229686
[2800]	valid_set's binary_logloss: 0.229647
[2850]	valid_set's binary_logloss: 0.229636
[2900]	valid_set's binary_logloss: 0.229593
[2950]	valid_set's binary_logloss: 0.22958
[3000]	valid_set's binary_logloss: 0.229552
[3050]	valid_set's binary_logloss: 0.229485
[3100]	valid_set's binary_logloss: 0.229479
[3150]	valid_set's binary_logloss: 0.229442
[3200]	valid_set's binary_logloss: 0.229452
[3250]	valid_set's binary_logloss: 0.229431
[3300]	valid_set's binary_logloss: 0.229426
[3350]	valid_set's binary_logloss: 0.229393
[3400]	valid_set's binary_logloss: 0.22939
[3450]	valid_set's binary_logloss: 0.229433
[3500]	valid_set's binary_logloss: 0.229441
[3550]	valid_set's binary_logloss: 0.229408
[3600]	valid_set's binary_logloss: 0.229432
[3650]	valid_set's binary_logloss: 0.229365
[3700]	valid_set's binary_logloss: 0.229378
[3750]	valid_set's binary_logloss: 0.229371
[3800]	valid_set's binary_logloss: 0.229366
[3850]	valid_set's binary_logloss: 0.229351
[3900]	valid_set's binary_logloss: 0.229376
[3950]	valid_set's binary_logloss: 0.229393
[4000]	valid_set's binary_logloss: 0.229375
[4050]	valid_set's binary_logloss: 0.229384
[4100]	valid_set's binary_logloss: 0.229371
[4150]	valid_set's binary_logloss: 0.229371
[4200]	valid_set's binary_logloss: 0.229341
[4250]	valid_set's binary_logloss: 0.229337
[4300]	valid_set's binary_logloss: 0.229331
[4350]	valid_set's binary_logloss: 0.229326
[4400]	valid_set's binary_logloss: 0.229335
[4450]	valid_set's binary_logloss: 0.229349
[4500]	valid_set's binary_logloss: 0.22939
[4550]	valid_set's binary_logloss: 0.229407
[4600]	valid_set's binary_logloss: 0.229417
[4650]	valid_set's binary_logloss: 0.22943
[4700]	valid_set's binary_logloss: 0.229458
[4750]	valid_set's binary_logloss: 0.229432
[4800]	valid_set's binary_logloss: 0.229462
[4850]	valid_set's binary_logloss: 0.229487
[4900]	valid_set's binary_logloss: 0.229506
[4950]	valid_set's binary_logloss: 0.229501
[5000]	valid_set's binary_logloss: 0.229481
[5050]	valid_set's binary_logloss: 0.229497
[5100]	valid_set's binary_logloss: 0.229513
[5150]	valid_set's binary_logloss: 0.229515
[5200]	valid_set's binary_logloss: 0.22951
[5250]	valid_set's binary_logloss: 0.229542
[5300]	valid_set's binary_logloss: 0.229573
[5350]	valid_set's binary_logloss: 0.229593
[5400]	valid_set's binary_logloss: 0.229613
[5450]	valid_set's binary_logloss: 0.229633
[5500]	valid_set's binary_logloss: 0.229649
[5550]	valid_set's binary_logloss: 0.229651
[5600]	valid_set's binary_logloss: 0.22967
[5650]	valid_set's binary_logloss: 0.229703
[5700]	valid_set's binary_logloss: 0.229752

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282323
[100]	valid_set's binary_logloss: 0.259064
[150]	valid_set's binary_logloss: 0.250107
[200]	valid_set's binary_logloss: 0.245329
[250]	valid_set's binary_logloss: 0.242538
[300]	valid_set's binary_logloss: 0.240462
[350]	valid_set's binary_logloss: 0.239063
[400]	valid_set's binary_logloss: 0.237865
[450]	valid_set's binary_logloss: 0.236858
[500]	valid_set's binary_logloss: 0.236125
[550]	valid_set's binary_logloss: 0.235389
[600]	valid_set's binary_logloss: 0.234968
[650]	valid_set's binary_logloss: 0.234592
[700]	valid_set's binary_logloss: 0.234128
[750]	valid_set's binary_logloss: 0.233788
[800]	valid_set's binary_logloss: 0.23348
[850]	valid_set's binary_logloss: 0.233262
[900]	valid_set's binary_logloss: 0.233053
[950]	valid_set's binary_logloss: 0.232809
[1000]	valid_set's binary_logloss: 0.232584
[1050]	valid_set's binary_logloss: 0.232427
[1100]	valid_set's binary_logloss: 0.232228
[1150]	valid_set's binary_logloss: 0.232144
[1200]	valid_set's binary_logloss: 0.232
[1250]	valid_set's binary_logloss: 0.231845
[1300]	valid_set's binary_logloss: 0.231682
[1350]	valid_set's binary_logloss: 0.231601
[1400]	valid_set's binary_logloss: 0.231524
[1450]	valid_set's binary_logloss: 0.231396
[1500]	valid_set's binary_logloss: 0.231333
[1550]	valid_set's binary_logloss: 0.231295
[1600]	valid_set's binary_logloss: 0.231166
[1650]	valid_set's binary_logloss: 0.231098
[1700]	valid_set's binary_logloss: 0.23099
[1750]	valid_set's binary_logloss: 0.230945
[1800]	valid_set's binary_logloss: 0.23088
[1850]	valid_set's binary_logloss: 0.230801
[1900]	valid_set's binary_logloss: 0.230729
[1950]	valid_set's binary_logloss: 0.230698
[2000]	valid_set's binary_logloss: 0.230622
[2050]	valid_set's binary_logloss: 0.230619
[2100]	valid_set's binary_logloss: 0.230555
[2150]	valid_set's binary_logloss: 0.230543
[2200]	valid_set's binary_logloss: 0.230535
[2250]	valid_set's binary_logloss: 0.230521
[2300]	valid_set's binary_logloss: 0.230454
[2350]	valid_set's binary_logloss: 0.230462
[2400]	valid_set's binary_logloss: 0.230423
[2450]	valid_set's binary_logloss: 0.230372
[2500]	valid_set's binary_logloss: 0.230358
[2550]	valid_set's binary_logloss: 0.230266
[2600]	valid_set's binary_logloss: 0.230237
[2650]	valid_set's binary_logloss: 0.230252
[2700]	valid_set's binary_logloss: 0.230244
[2750]	valid_set's binary_logloss: 0.230246
[2800]	valid_set's binary_logloss: 0.23023
[2850]	valid_set's binary_logloss: 0.230249
[2900]	valid_set's binary_logloss: 0.230234
[2950]	valid_set's binary_logloss: 0.23018
[3000]	valid_set's binary_logloss: 0.230156
[3050]	valid_set's binary_logloss: 0.23018
[3100]	valid_set's binary_logloss: 0.230212
[3150]	valid_set's binary_logloss: 0.230227
[3200]	valid_set's binary_logloss: 0.230236
[3250]	valid_set's binary_logloss: 0.230189
[3300]	valid_set's binary_logloss: 0.230146
[3350]	valid_set's binary_logloss: 0.230108
[3400]	valid_set's binary_logloss: 0.230092
[3450]	valid_set's binary_logloss: 0.23013
[3500]	valid_set's binary_logloss: 0.2301
[3550]	valid_set's binary_logloss: 0.230108
[3600]	valid_set's binary_logloss: 0.230119
[3650]	valid_set's binary_logloss: 0.230157
[3700]	valid_set's binary_logloss: 0.230124
[3750]	valid_set's binary_logloss: 0.230093
[3800]	valid_set's binary_logloss: 0.230011
[3850]	valid_set's binary_logloss: 0.230033
[3900]	valid_set's binary_logloss: 0.230012
[3950]	valid_set's binary_logloss: 0.230024
[4000]	valid_set's binary_logloss: 0.230055
[4050]	valid_set's binary_logloss: 0.230039
[4100]	valid_set's binary_logloss: 0.230036
[4150]	valid_set's binary_logloss: 0.229995
[4200]	valid_set's binary_logloss: 0.230041
[4250]	valid_set's binary_logloss: 0.230067
[4300]	valid_set's binary_logloss: 0.230069
[4350]	valid_set's binary_logloss: 0.230109
[4400]	valid_set's binary_logloss: 0.23016
[4450]	valid_set's binary_logloss: 0.230199
[4500]	valid_set's binary_logloss: 0.230218
[4550]	valid_set's binary_logloss: 0.23021
[4600]	valid_set's binary_logloss: 0.23024
[4650]	valid_set's binary_logloss: 0.230259
[4700]	valid_set's binary_logloss: 0.230286
[4750]	valid_set's binary_logloss: 0.230287
[4800]	valid_set's binary_logloss: 0.230334
[4850]	valid_set's binary_logloss: 0.230413
[4900]	valid_set's binary_logloss: 0.230454
[4950]	valid_set's binary_logloss: 0.230454
[5000]	valid_set's binary_logloss: 0.230433
[5050]	valid_set's binary_logloss: 0.23042
[5100]	valid_set's binary_logloss: 0.230439
[5150]	valid_set's binary_logloss: 0.230422
[5200]	valid_set's binary_logloss: 0.23042
[5250]	valid_set's binary_logloss: 0.230478
[5300]	valid_set's binary_logloss: 0.230543
[5350]	valid_set's binary_logloss: 0.230561

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.278992
[100]	valid_set's binary_logloss: 0.256113
[150]	valid_set's binary_logloss: 0.246721
[200]	valid_set's binary_logloss: 0.242152
[250]	valid_set's binary_logloss: 0.238931
[300]	valid_set's binary_logloss: 0.236879
[350]	valid_set's binary_logloss: 0.23508
[400]	valid_set's binary_logloss: 0.23384
[450]	valid_set's binary_logloss: 0.232836
[500]	valid_set's binary_logloss: 0.232057
[550]	valid_set's binary_logloss: 0.23155
[600]	valid_set's binary_logloss: 0.231067
[650]	valid_set's binary_logloss: 0.230621
[700]	valid_set's binary_logloss: 0.230127
[750]	valid_set's binary_logloss: 0.22976
[800]	valid_set's binary_logloss: 0.229473
[850]	valid_set's binary_logloss: 0.229228
[900]	valid_set's binary_logloss: 0.229025
[950]	valid_set's binary_logloss: 0.228831
[1000]	valid_set's binary_logloss: 0.228668
[1050]	valid_set's binary_logloss: 0.228385
[1100]	valid_set's binary_logloss: 0.228217
[1150]	valid_set's binary_logloss: 0.228024
[1200]	valid_set's binary_logloss: 0.227872
[1250]	valid_set's binary_logloss: 0.227726
[1300]	valid_set's binary_logloss: 0.227547
[1350]	valid_set's binary_logloss: 0.227405
[1400]	valid_set's binary_logloss: 0.227291
[1450]	valid_set's binary_logloss: 0.227202
[1500]	valid_set's binary_logloss: 0.227079
[1550]	valid_set's binary_logloss: 0.226959
[1600]	valid_set's binary_logloss: 0.226865
[1650]	valid_set's binary_logloss: 0.226817
[1700]	valid_set's binary_logloss: 0.226688
[1750]	valid_set's binary_logloss: 0.226612
[1800]	valid_set's binary_logloss: 0.226558
[1850]	valid_set's binary_logloss: 0.226464
[1900]	valid_set's binary_logloss: 0.226422
[1950]	valid_set's binary_logloss: 0.226322
[2000]	valid_set's binary_logloss: 0.226277
[2050]	valid_set's binary_logloss: 0.226245
[2100]	valid_set's binary_logloss: 0.226191
[2150]	valid_set's binary_logloss: 0.226188
[2200]	valid_set's binary_logloss: 0.226122
[2250]	valid_set's binary_logloss: 0.226048
[2300]	valid_set's binary_logloss: 0.225966
[2350]	valid_set's binary_logloss: 0.22589
[2400]	valid_set's binary_logloss: 0.225853
[2450]	valid_set's binary_logloss: 0.225826
[2500]	valid_set's binary_logloss: 0.225844
[2550]	valid_set's binary_logloss: 0.225817
[2600]	valid_set's binary_logloss: 0.225798
[2650]	valid_set's binary_logloss: 0.225809
[2700]	valid_set's binary_logloss: 0.225817
[2750]	valid_set's binary_logloss: 0.225825
[2800]	valid_set's binary_logloss: 0.225795
[2850]	valid_set's binary_logloss: 0.225809
[2900]	valid_set's binary_logloss: 0.225723
[2950]	valid_set's binary_logloss: 0.225701
[3000]	valid_set's binary_logloss: 0.225739
[3050]	valid_set's binary_logloss: 0.225718
[3100]	valid_set's binary_logloss: 0.225723
[3150]	valid_set's binary_logloss: 0.225712
[3200]	valid_set's binary_logloss: 0.225716
[3250]	valid_set's binary_logloss: 0.225696
[3300]	valid_set's binary_logloss: 0.225695
[3350]	valid_set's binary_logloss: 0.225689
[3400]	valid_set's binary_logloss: 0.225671
[3450]	valid_set's binary_logloss: 0.225677
[3500]	valid_set's binary_logloss: 0.225686
[3550]	valid_set's binary_logloss: 0.225658
[3600]	valid_set's binary_logloss: 0.225665
[3650]	valid_set's binary_logloss: 0.22567
[3700]	valid_set's binary_logloss: 0.225667
[3750]	valid_set's binary_logloss: 0.225614
[3800]	valid_set's binary_logloss: 0.225653
[3850]	valid_set's binary_logloss: 0.225631
[3900]	valid_set's binary_logloss: 0.225624
[3950]	valid_set's binary_logloss: 0.225626
[4000]	valid_set's binary_logloss: 0.225635
[4050]	valid_set's binary_logloss: 0.225627
[4100]	valid_set's binary_logloss: 0.225667
[4150]	valid_set's binary_logloss: 0.225665
[4200]	valid_set's binary_logloss: 0.2257
[4250]	valid_set's binary_logloss: 0.225744
[4300]	valid_set's binary_logloss: 0.225782
[4350]	valid_set's binary_logloss: 0.22578
[4400]	valid_set's binary_logloss: 0.225801
[4450]	valid_set's binary_logloss: 0.225818
[4500]	valid_set's binary_logloss: 0.225806
[4550]	valid_set's binary_logloss: 0.225828
[4600]	valid_set's binary_logloss: 0.225824
[4650]	valid_set's binary_logloss: 0.225803
[4700]	valid_set's binary_logloss: 0.225799
[4750]	valid_set's binary_logloss: 0.225812
[4800]	valid_set's binary_logloss: 0.225833
[4850]	valid_set's binary_logloss: 0.225848
[4900]	valid_set's binary_logloss: 0.225845

Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\model.pkl
	0.948	 = Validation score   (roc_auc)
	153.4s	 = Training   runtime
	6.84s	 = Validation runtime
	8024.4	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1530.32s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.1 GB
Ensemble size: 11
Ensemble weights:
[0.54545455 0.45454545]
	0.35s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBM_BAG_L1': 0.545, 'LightGBMLarge_BAG_L1': 0.455}
	0.9489	 = Validation score   (roc_auc)
	2.15s	 = Training   runtime
	0.04s	 = Validation runtime
	4904.8	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
AutoGluon training complete, total runtime = 271.97s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4904.8 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\GBM\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\GBM")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       3.22 GB / 15.06 GB (21.4%)
Disk Space Avail:   710.89 GB / 930.47 GB (76.4%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\XGB"
Train Data Rows:    439140
Train Data Columns: 57
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...

GBM completed.
Validation ROC-AUC: 0.948897

================================================================================
TRAINING: XGB
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\XGB
================================================================================

Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3340.82 MB
	Train Data (Original)  Memory Usage: 236.05 MB (7.1% of available memory)
	Warning: Data size prior to feature transformation consumes 7.1% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.2s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.0s = Fit runtime
			46 features in original data used to generate 46 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			42 features in original data used to generate 42 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.1s = Fit runtime
	42 features in original data used to generate 42 features in processed data.
	Train Data (Processed) Memory Usage: 128.99 MB (3.9% of available memory)
Data preprocessing and feature engineering runtime = 1.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\utils\data\y.pkl
Model configs that will be trained (in order):
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1798.81s of the 1798.81s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45848
[50]	validation_0-logloss:0.25302
[100]	validation_0-logloss:0.24191
[150]	validation_0-logloss:0.23752
[200]	validation_0-logloss:0.23466
[250]	validation_0-logloss:0.23311
[300]	validation_0-logloss:0.23183
[350]	validation_0-logloss:0.23117
[400]	validation_0-logloss:0.23054
[450]	validation_0-logloss:0.22993
[500]	validation_0-logloss:0.22964
[550]	validation_0-logloss:0.22955
[600]	validation_0-logloss:0.22941
[650]	validation_0-logloss:0.22938
[700]	validation_0-logloss:0.22925
[750]	validation_0-logloss:0.22926
[800]	validation_0-logloss:0.22929
[850]	validation_0-logloss:0.22937
[900]	validation_0-logloss:0.22947
[950]	validation_0-logloss:0.22948
[1000]	validation_0-logloss:0.22954
[1011]	validation_0-logloss:0.22955

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45866
[50]	validation_0-logloss:0.25464
[100]	validation_0-logloss:0.24321
[150]	validation_0-logloss:0.23801
[200]	validation_0-logloss:0.23533
[250]	validation_0-logloss:0.23326
[300]	validation_0-logloss:0.23179
[350]	validation_0-logloss:0.23082
[400]	validation_0-logloss:0.23014
[450]	validation_0-logloss:0.22946
[500]	validation_0-logloss:0.22913
[550]	validation_0-logloss:0.22886
[600]	validation_0-logloss:0.22868
[650]	validation_0-logloss:0.22848
[700]	validation_0-logloss:0.22832
[750]	validation_0-logloss:0.22820
[800]	validation_0-logloss:0.22800
[850]	validation_0-logloss:0.22805
[900]	validation_0-logloss:0.22798
[950]	validation_0-logloss:0.22798
[1000]	validation_0-logloss:0.22795
[1050]	validation_0-logloss:0.22806
[1100]	validation_0-logloss:0.22815
[1150]	validation_0-logloss:0.22830
[1200]	validation_0-logloss:0.22854
[1250]	validation_0-logloss:0.22870
[1300]	validation_0-logloss:0.22881
[1306]	validation_0-logloss:0.22885

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45774
[50]	validation_0-logloss:0.24901
[100]	validation_0-logloss:0.23732
[150]	validation_0-logloss:0.23251
[200]	validation_0-logloss:0.22957
[250]	validation_0-logloss:0.22778
[300]	validation_0-logloss:0.22642
[350]	validation_0-logloss:0.22522
[400]	validation_0-logloss:0.22441
[450]	validation_0-logloss:0.22405
[500]	validation_0-logloss:0.22371
[550]	validation_0-logloss:0.22334
[600]	validation_0-logloss:0.22298
[650]	validation_0-logloss:0.22281
[700]	validation_0-logloss:0.22265
[750]	validation_0-logloss:0.22261
[800]	validation_0-logloss:0.22258
[850]	validation_0-logloss:0.22274
[900]	validation_0-logloss:0.22283
[950]	validation_0-logloss:0.22298
[1000]	validation_0-logloss:0.22282
[1050]	validation_0-logloss:0.22284
[1051]	validation_0-logloss:0.22283

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45860
[50]	validation_0-logloss:0.25475
[100]	validation_0-logloss:0.24312
[150]	validation_0-logloss:0.23893
[200]	validation_0-logloss:0.23563
[250]	validation_0-logloss:0.23380
[300]	validation_0-logloss:0.23262
[350]	validation_0-logloss:0.23180
[400]	validation_0-logloss:0.23110
[450]	validation_0-logloss:0.23064
[500]	validation_0-logloss:0.23020
[550]	validation_0-logloss:0.22989
[600]	validation_0-logloss:0.22972
[650]	validation_0-logloss:0.22958
[700]	validation_0-logloss:0.22932
[750]	validation_0-logloss:0.22928
[800]	validation_0-logloss:0.22931
[850]	validation_0-logloss:0.22933
[900]	validation_0-logloss:0.22934
[950]	validation_0-logloss:0.22936
[986]	validation_0-logloss:0.22945

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45856
[50]	validation_0-logloss:0.25316
[100]	validation_0-logloss:0.24164
[150]	validation_0-logloss:0.23708
[200]	validation_0-logloss:0.23438
[250]	validation_0-logloss:0.23248
[300]	validation_0-logloss:0.23125
[350]	validation_0-logloss:0.23021
[400]	validation_0-logloss:0.22937
[450]	validation_0-logloss:0.22883
[500]	validation_0-logloss:0.22848
[550]	validation_0-logloss:0.22833
[600]	validation_0-logloss:0.22814
[650]	validation_0-logloss:0.22809
[700]	validation_0-logloss:0.22780
[750]	validation_0-logloss:0.22777
[800]	validation_0-logloss:0.22766
[850]	validation_0-logloss:0.22755
[900]	validation_0-logloss:0.22772
[950]	validation_0-logloss:0.22769
[1000]	validation_0-logloss:0.22776
[1050]	validation_0-logloss:0.22775
[1091]	validation_0-logloss:0.22786

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45843
[50]	validation_0-logloss:0.25530
[100]	validation_0-logloss:0.24351
[150]	validation_0-logloss:0.23838
[200]	validation_0-logloss:0.23565
[250]	validation_0-logloss:0.23386
[300]	validation_0-logloss:0.23256
[350]	validation_0-logloss:0.23173
[400]	validation_0-logloss:0.23125
[450]	validation_0-logloss:0.23081
[500]	validation_0-logloss:0.23044
[550]	validation_0-logloss:0.23009
[600]	validation_0-logloss:0.22986
[650]	validation_0-logloss:0.22990
[700]	validation_0-logloss:0.22995
[750]	validation_0-logloss:0.22995
[773]	validation_0-logloss:0.22988

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45862
[50]	validation_0-logloss:0.25457
[100]	validation_0-logloss:0.24301
[150]	validation_0-logloss:0.23895
[200]	validation_0-logloss:0.23601
[250]	validation_0-logloss:0.23391
[300]	validation_0-logloss:0.23265
[350]	validation_0-logloss:0.23179
[400]	validation_0-logloss:0.23116
[450]	validation_0-logloss:0.23079
[500]	validation_0-logloss:0.23030
[550]	validation_0-logloss:0.23009
[600]	validation_0-logloss:0.22998
[650]	validation_0-logloss:0.23005
[700]	validation_0-logloss:0.22999
[750]	validation_0-logloss:0.23006
[792]	validation_0-logloss:0.23004

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45808
[50]	validation_0-logloss:0.25194
[100]	validation_0-logloss:0.24003
[150]	validation_0-logloss:0.23515
[200]	validation_0-logloss:0.23207
[250]	validation_0-logloss:0.23014
[300]	validation_0-logloss:0.22874
[350]	validation_0-logloss:0.22804
[400]	validation_0-logloss:0.22702
[450]	validation_0-logloss:0.22653
[500]	validation_0-logloss:0.22630
[550]	validation_0-logloss:0.22593
[600]	validation_0-logloss:0.22585
[650]	validation_0-logloss:0.22573
[700]	validation_0-logloss:0.22553
[750]	validation_0-logloss:0.22556
[800]	validation_0-logloss:0.22561
[850]	validation_0-logloss:0.22568
[900]	validation_0-logloss:0.22562
[950]	validation_0-logloss:0.22568
[951]	validation_0-logloss:0.22565

Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\model.pkl
	0.948	 = Validation score   (roc_auc)
	128.01s	 = Training   runtime
	1.46s	 = Validation runtime
	37574.0	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1668.75s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.6 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.24s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.948	 = Validation score   (roc_auc)
	0.06s	 = Training   runtime
	0.04s	 = Validation runtime
	37450.1	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
AutoGluon training complete, total runtime = 131.45s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 37450.1 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\XGB\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\XGB")
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.13.0+cu126
CUDA Version:       12.6
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       2.67 GB / 15.06 GB (17.7%)
Disk Space Avail:   710.72 GB / 930.47 GB (76.4%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\predictor.pkl
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4\CAT"
Train Data Rows:    439140
Train Data Columns: 57
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2775.74 MB

XGB completed.
Validation ROC-AUC: 0.947970

================================================================================
TRAINING: CAT
TIME LIMIT: 30 MINUTES
MODEL PATH: ./ag_models4\CAT
================================================================================

	Train Data (Original)  Memory Usage: 236.05 MB (8.5% of available memory)
	Warning: Data size prior to feature transformation consumes 8.5% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 25 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.2s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.0s = Fit runtime
			46 features in original data used to generate 46 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 21 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 22 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  3 | ['PitStop', 'RaceProgress_digit_units', 'PitStop_cat']
			0.2s = Fit runtime
			48 features in original data used to generate 48 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			6 duplicate columns removed: ['Year_cat', 'PitStop_cat', 'LapNumber_cat', 'Stint_cat', 'Position_cat', 'RaceProgress_cat']
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
				('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
			0.1s = Fit runtime
			42 features in original data used to generate 42 features in processed data.
	Useless Original Features (Count: 9): ['Stint_median', 'Position_median', 'Compound_median', 'Race_median', 'Driver_median', 'LapNumber_digit_hundreds', 'TyreLife_digit_hundreds', 'RaceProgress_digit_tens', 'RaceProgress_digit_hundreds']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 6): ['LapNumber_cat', 'RaceProgress_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 1 | ['RaceProgress_cat']
		('int', [])   : 5 | ['LapNumber_cat', 'Year_cat', 'PitStop_cat', 'Stint_cat', 'Position_cat']
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 20 | ['Unnamed: 0', 'Year', 'PitStop', 'LapNumber', 'Stint', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int8', 'int')          :  2 | ['PitStop', 'RaceProgress_digit_units']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 20 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 18 | ['Unnamed: 0', 'Year', 'LapNumber', 'Stint', 'Position', ...]
		('int', ['bool']) :  2 | ['PitStop', 'RaceProgress_digit_units']
	1.0s = Fit runtime
	42 features in original data used to generate 42 features in processed data.
	Train Data (Processed) Memory Usage: 128.99 MB (4.7% of available memory)
Data preprocessing and feature engineering runtime = 1.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
User-specified model hyperparameters to be fit:
{
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\utils\data\y.pkl
Model configs that will be trained (in order):
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1798.87s of the 1798.87s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6295811	test: 0.6294880	best: 0.6294880 (0)	total: 9.88ms	remaining: 9.88ms
1:	learn: 0.5771663	test: 0.5770367	best: 0.5770367 (1)	total: 19.3ms	remaining: 0us
bestTest = 0.5770366611
bestIteration = 1
0:	learn: 0.6297098	test: 0.6296223	best: 0.6296223 (0)	total: 14.6ms	remaining: 4.23s
20:	learn: 0.3171171	test: 0.3177078	best: 0.3177078 (20)	total: 321ms	remaining: 4.13s
40:	learn: 0.2869205	test: 0.2876425	best: 0.2876425 (40)	total: 629ms	remaining: 3.83s
60:	learn: 0.2761079	test: 0.2769069	best: 0.2769069 (60)	total: 945ms	remaining: 3.56s
80:	learn: 0.2699942	test: 0.2710172	best: 0.2710172 (80)	total: 1.26s	remaining: 3.27s
100:	learn: 0.2660399	test: 0.2672235	best: 0.2672235 (100)	total: 1.57s	remaining: 2.96s
120:	learn: 0.2623998	test: 0.2636426	best: 0.2636426 (120)	total: 1.89s	remaining: 2.66s
140:	learn: 0.2595893	test: 0.2609698	best: 0.2609698 (140)	total: 2.19s	remaining: 2.34s
160:	learn: 0.2570048	test: 0.2585869	best: 0.2585869 (160)	total: 2.5s	remaining: 2.02s
180:	learn: 0.2545189	test: 0.2563030	best: 0.2563030 (180)	total: 2.81s	remaining: 1.71s
200:	learn: 0.2525644	test: 0.2544755	best: 0.2544755 (200)	total: 3.14s	remaining: 1.41s
220:	learn: 0.2507731	test: 0.2528739	best: 0.2528739 (220)	total: 3.45s	remaining: 1.09s
240:	learn: 0.2491065	test: 0.2514262	best: 0.2514262 (240)	total: 3.74s	remaining: 777ms
260:	learn: 0.2476825	test: 0.2502095	best: 0.2502095 (260)	total: 4.04s	remaining: 465ms
280:	learn: 0.2462369	test: 0.2489627	best: 0.2489627 (280)	total: 4.34s	remaining: 155ms
290:	learn: 0.2456087	test: 0.2484194	best: 0.2484194 (290)	total: 4.49s	remaining: 0us
bestTest = 0.2484193503
bestIteration = 290

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6297931	test: 0.6297100	best: 0.6297100 (0)	total: 9.81ms	remaining: 9.81ms
1:	learn: 0.5775159	test: 0.5773928	best: 0.5773928 (1)	total: 18.9ms	remaining: 0us
bestTest = 0.5773927872
bestIteration = 1
0:	learn: 0.6297927	test: 0.6297099	best: 0.6297099 (0)	total: 14.5ms	remaining: 9.71s
20:	learn: 0.3199195	test: 0.3208548	best: 0.3208548 (20)	total: 302ms	remaining: 9.32s
40:	learn: 0.2873646	test: 0.2885631	best: 0.2885631 (40)	total: 594ms	remaining: 9.09s
60:	learn: 0.2767640	test: 0.2781065	best: 0.2781065 (60)	total: 920ms	remaining: 9.17s
80:	learn: 0.2700337	test: 0.2713790	best: 0.2713790 (80)	total: 1.24s	remaining: 9.01s
100:	learn: 0.2655029	test: 0.2669133	best: 0.2669133 (100)	total: 1.54s	remaining: 8.69s
120:	learn: 0.2621528	test: 0.2636052	best: 0.2636052 (120)	total: 1.85s	remaining: 8.37s
140:	learn: 0.2587972	test: 0.2603175	best: 0.2603175 (140)	total: 2.16s	remaining: 8.09s
160:	learn: 0.2561581	test: 0.2577987	best: 0.2577987 (160)	total: 2.48s	remaining: 7.84s
180:	learn: 0.2543932	test: 0.2561253	best: 0.2561253 (180)	total: 2.83s	remaining: 7.63s
200:	learn: 0.2524509	test: 0.2542879	best: 0.2542879 (200)	total: 3.12s	remaining: 7.27s
220:	learn: 0.2508611	test: 0.2527880	best: 0.2527880 (220)	total: 3.5s	remaining: 7.1s
240:	learn: 0.2492892	test: 0.2512252	best: 0.2512252 (240)	total: 3.83s	remaining: 6.8s
260:	learn: 0.2478631	test: 0.2499524	best: 0.2499524 (260)	total: 4.13s	remaining: 6.46s
280:	learn: 0.2463459	test: 0.2485095	best: 0.2485095 (280)	total: 4.48s	remaining: 6.19s
300:	learn: 0.2450182	test: 0.2472423	best: 0.2472423 (300)	total: 4.8s	remaining: 5.87s
320:	learn: 0.2440784	test: 0.2464148	best: 0.2464148 (320)	total: 5.13s	remaining: 5.57s
340:	learn: 0.2431979	test: 0.2456416	best: 0.2456416 (340)	total: 5.46s	remaining: 5.26s
360:	learn: 0.2423797	test: 0.2449573	best: 0.2449573 (360)	total: 5.78s	remaining: 4.93s
380:	learn: 0.2414209	test: 0.2440626	best: 0.2440626 (380)	total: 6.17s	remaining: 4.66s
400:	learn: 0.2404706	test: 0.2432262	best: 0.2432262 (400)	total: 6.52s	remaining: 4.36s
420:	learn: 0.2397372	test: 0.2426155	best: 0.2426155 (420)	total: 6.83s	remaining: 4.02s
440:	learn: 0.2390941	test: 0.2421027	best: 0.2421027 (440)	total: 7.13s	remaining: 3.68s
460:	learn: 0.2383967	test: 0.2415551	best: 0.2415551 (460)	total: 7.49s	remaining: 3.38s
480:	learn: 0.2377724	test: 0.2410621	best: 0.2410621 (480)	total: 7.81s	remaining: 3.05s
500:	learn: 0.2371301	test: 0.2405271	best: 0.2405271 (500)	total: 8.12s	remaining: 2.72s
520:	learn: 0.2366017	test: 0.2401220	best: 0.2401220 (520)	total: 8.45s	remaining: 2.4s
540:	learn: 0.2360666	test: 0.2397337	best: 0.2397337 (540)	total: 8.76s	remaining: 2.07s
560:	learn: 0.2353912	test: 0.2391908	best: 0.2391908 (560)	total: 9.06s	remaining: 1.74s
580:	learn: 0.2349411	test: 0.2388785	best: 0.2388785 (580)	total: 9.37s	remaining: 1.42s
600:	learn: 0.2344483	test: 0.2384829	best: 0.2384829 (600)	total: 9.66s	remaining: 1.09s
620:	learn: 0.2339795	test: 0.2381639	best: 0.2381639 (620)	total: 9.96s	remaining: 770ms
640:	learn: 0.2335020	test: 0.2378329	best: 0.2378329 (640)	total: 10.2s	remaining: 447ms
660:	learn: 0.2330710	test: 0.2375459	best: 0.2375459 (660)	total: 10.5s	remaining: 128ms
668:	learn: 0.2328961	test: 0.2374318	best: 0.2374318 (668)	total: 10.7s	remaining: 0us
bestTest = 0.2374317636
bestIteration = 668

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6299417	test: 0.6293931	best: 0.6293931 (0)	total: 9.65ms	remaining: 9.65ms
1:	learn: 0.5778240	test: 0.5767533	best: 0.5767533 (1)	total: 18.2ms	remaining: 0us
bestTest = 0.5767532617
bestIteration = 1
0:	learn: 0.6300597	test: 0.6295349	best: 0.6295349 (0)	total: 15ms	remaining: 11.7s
20:	learn: 0.3200348	test: 0.3153686	best: 0.3153686 (20)	total: 322ms	remaining: 11.7s
40:	learn: 0.2884953	test: 0.2828745	best: 0.2828745 (40)	total: 621ms	remaining: 11.2s
60:	learn: 0.2767087	test: 0.2710092	best: 0.2710092 (60)	total: 924ms	remaining: 10.9s
80:	learn: 0.2710790	test: 0.2656117	best: 0.2656117 (80)	total: 1.21s	remaining: 10.5s
100:	learn: 0.2666190	test: 0.2613387	best: 0.2613387 (100)	total: 1.52s	remaining: 10.3s
120:	learn: 0.2634781	test: 0.2584515	best: 0.2584515 (120)	total: 1.82s	remaining: 9.94s
140:	learn: 0.2600750	test: 0.2551624	best: 0.2551624 (140)	total: 2.12s	remaining: 9.64s
160:	learn: 0.2572453	test: 0.2525879	best: 0.2525879 (160)	total: 2.42s	remaining: 9.34s
180:	learn: 0.2546460	test: 0.2500969	best: 0.2500969 (180)	total: 2.72s	remaining: 9.04s
200:	learn: 0.2526884	test: 0.2482733	best: 0.2482733 (200)	total: 3.02s	remaining: 8.73s
220:	learn: 0.2510838	test: 0.2468886	best: 0.2468886 (220)	total: 3.32s	remaining: 8.45s
240:	learn: 0.2495135	test: 0.2454965	best: 0.2454965 (240)	total: 3.62s	remaining: 8.14s
260:	learn: 0.2481614	test: 0.2443580	best: 0.2443580 (260)	total: 3.92s	remaining: 7.83s
280:	learn: 0.2465507	test: 0.2429267	best: 0.2429267 (280)	total: 4.21s	remaining: 7.53s
300:	learn: 0.2455008	test: 0.2420510	best: 0.2420510 (300)	total: 4.51s	remaining: 7.22s
320:	learn: 0.2443779	test: 0.2411111	best: 0.2411111 (320)	total: 4.81s	remaining: 6.92s
340:	learn: 0.2433688	test: 0.2402628	best: 0.2402628 (340)	total: 5.11s	remaining: 6.62s
360:	learn: 0.2424512	test: 0.2395076	best: 0.2395076 (360)	total: 5.4s	remaining: 6.31s
380:	learn: 0.2416984	test: 0.2388734	best: 0.2388734 (380)	total: 5.7s	remaining: 6.01s
400:	learn: 0.2409210	test: 0.2382829	best: 0.2382829 (400)	total: 6s	remaining: 5.71s
420:	learn: 0.2401397	test: 0.2376867	best: 0.2376867 (420)	total: 6.29s	remaining: 5.41s
440:	learn: 0.2394257	test: 0.2371336	best: 0.2371336 (440)	total: 6.61s	remaining: 5.13s
460:	learn: 0.2387673	test: 0.2366393	best: 0.2366393 (460)	total: 6.93s	remaining: 4.84s
480:	learn: 0.2380563	test: 0.2360823	best: 0.2360823 (480)	total: 7.25s	remaining: 4.55s
500:	learn: 0.2374030	test: 0.2355660	best: 0.2355660 (500)	total: 7.56s	remaining: 4.26s
520:	learn: 0.2367757	test: 0.2350863	best: 0.2350863 (520)	total: 7.88s	remaining: 3.96s
540:	learn: 0.2362230	test: 0.2347137	best: 0.2347137 (540)	total: 8.17s	remaining: 3.66s
560:	learn: 0.2357602	test: 0.2343887	best: 0.2343887 (560)	total: 8.47s	remaining: 3.35s
580:	learn: 0.2351840	test: 0.2339780	best: 0.2339780 (580)	total: 8.77s	remaining: 3.05s
600:	learn: 0.2346493	test: 0.2335684	best: 0.2335684 (600)	total: 9.06s	remaining: 2.74s
620:	learn: 0.2341777	test: 0.2332659	best: 0.2332659 (620)	total: 9.35s	remaining: 2.44s
640:	learn: 0.2336865	test: 0.2329065	best: 0.2329065 (640)	total: 9.66s	remaining: 2.14s
660:	learn: 0.2332480	test: 0.2326330	best: 0.2326330 (660)	total: 9.95s	remaining: 1.84s
680:	learn: 0.2327882	test: 0.2323293	best: 0.2323293 (680)	total: 10.2s	remaining: 1.53s
700:	learn: 0.2323943	test: 0.2321095	best: 0.2321095 (700)	total: 10.5s	remaining: 1.23s
720:	learn: 0.2320163	test: 0.2319042	best: 0.2319042 (720)	total: 10.8s	remaining: 932ms
740:	learn: 0.2315625	test: 0.2315989	best: 0.2315989 (740)	total: 11.1s	remaining: 632ms
760:	learn: 0.2311985	test: 0.2313790	best: 0.2313790 (760)	total: 11.5s	remaining: 331ms
780:	learn: 0.2308717	test: 0.2311976	best: 0.2311976 (780)	total: 11.8s	remaining: 30.1ms
782:	learn: 0.2308371	test: 0.2311850	best: 0.2311850 (782)	total: 11.8s	remaining: 0us
bestTest = 0.2311849872
bestIteration = 782

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6296686	test: 0.6299541	best: 0.6299541 (0)	total: 9.74ms	remaining: 9.74ms
1:	learn: 0.5773242	test: 0.5778611	best: 0.5778611 (1)	total: 18ms	remaining: 0us
bestTest = 0.5778610632
bestIteration = 1
0:	learn: 0.6296685	test: 0.6299540	best: 0.6299540 (0)	total: 14.4ms	remaining: 13.2s
20:	learn: 0.3184249	test: 0.3200832	best: 0.3200832 (20)	total: 303ms	remaining: 13s
40:	learn: 0.2864653	test: 0.2881136	best: 0.2881136 (40)	total: 602ms	remaining: 12.9s
60:	learn: 0.2758551	test: 0.2776840	best: 0.2776840 (60)	total: 900ms	remaining: 12.7s
80:	learn: 0.2699039	test: 0.2719495	best: 0.2719495 (80)	total: 1.19s	remaining: 12.4s
100:	learn: 0.2656900	test: 0.2678760	best: 0.2678760 (100)	total: 1.48s	remaining: 12s
120:	learn: 0.2623225	test: 0.2646291	best: 0.2646291 (120)	total: 1.77s	remaining: 11.7s
140:	learn: 0.2590535	test: 0.2615567	best: 0.2615567 (140)	total: 2.08s	remaining: 11.5s
160:	learn: 0.2566927	test: 0.2592973	best: 0.2592973 (160)	total: 2.38s	remaining: 11.2s
180:	learn: 0.2548207	test: 0.2575793	best: 0.2575793 (180)	total: 2.78s	remaining: 11.3s
200:	learn: 0.2527687	test: 0.2556936	best: 0.2556936 (200)	total: 3.12s	remaining: 11.2s
220:	learn: 0.2509909	test: 0.2540575	best: 0.2540575 (220)	total: 3.44s	remaining: 10.9s
240:	learn: 0.2495313	test: 0.2527233	best: 0.2527233 (240)	total: 3.76s	remaining: 10.6s
260:	learn: 0.2478583	test: 0.2511475	best: 0.2511475 (260)	total: 4.07s	remaining: 10.3s
280:	learn: 0.2463162	test: 0.2497634	best: 0.2497634 (280)	total: 4.39s	remaining: 9.99s
300:	learn: 0.2451592	test: 0.2487653	best: 0.2487653 (300)	total: 4.71s	remaining: 9.69s
320:	learn: 0.2441117	test: 0.2477756	best: 0.2477756 (320)	total: 5.05s	remaining: 9.42s
340:	learn: 0.2433353	test: 0.2472045	best: 0.2472045 (340)	total: 5.37s	remaining: 9.12s
360:	learn: 0.2424347	test: 0.2465096	best: 0.2465096 (360)	total: 5.69s	remaining: 8.81s
380:	learn: 0.2416047	test: 0.2458285	best: 0.2458285 (380)	total: 6s	remaining: 8.49s
400:	learn: 0.2407247	test: 0.2450872	best: 0.2450872 (400)	total: 6.32s	remaining: 8.18s
420:	learn: 0.2398522	test: 0.2443905	best: 0.2443905 (420)	total: 6.63s	remaining: 7.86s
440:	learn: 0.2390645	test: 0.2437635	best: 0.2437635 (440)	total: 6.94s	remaining: 7.54s
460:	learn: 0.2382412	test: 0.2431573	best: 0.2431573 (460)	total: 7.27s	remaining: 7.24s
480:	learn: 0.2376459	test: 0.2427739	best: 0.2427739 (480)	total: 7.6s	remaining: 6.94s
500:	learn: 0.2370485	test: 0.2423009	best: 0.2423009 (500)	total: 7.92s	remaining: 6.63s
520:	learn: 0.2364412	test: 0.2418862	best: 0.2418862 (520)	total: 8.24s	remaining: 6.31s
540:	learn: 0.2358063	test: 0.2414218	best: 0.2414218 (540)	total: 8.55s	remaining: 5.99s
560:	learn: 0.2352011	test: 0.2409494	best: 0.2409494 (560)	total: 8.87s	remaining: 5.67s
580:	learn: 0.2346394	test: 0.2404969	best: 0.2404969 (580)	total: 9.18s	remaining: 5.36s
600:	learn: 0.2341605	test: 0.2402202	best: 0.2402202 (600)	total: 9.49s	remaining: 5.04s
620:	learn: 0.2336929	test: 0.2399414	best: 0.2399414 (620)	total: 9.81s	remaining: 4.72s
640:	learn: 0.2332356	test: 0.2396687	best: 0.2396687 (640)	total: 10.1s	remaining: 4.42s
660:	learn: 0.2327546	test: 0.2393582	best: 0.2393582 (660)	total: 10.5s	remaining: 4.11s
680:	learn: 0.2323212	test: 0.2390983	best: 0.2390983 (680)	total: 10.8s	remaining: 3.8s
700:	learn: 0.2319255	test: 0.2388559	best: 0.2388559 (700)	total: 11.2s	remaining: 3.49s
720:	learn: 0.2314889	test: 0.2385795	best: 0.2385795 (720)	total: 11.5s	remaining: 3.18s
740:	learn: 0.2310352	test: 0.2382835	best: 0.2382835 (740)	total: 11.9s	remaining: 2.87s
760:	learn: 0.2306022	test: 0.2380246	best: 0.2380246 (760)	total: 12.2s	remaining: 2.55s
780:	learn: 0.2302351	test: 0.2377671	best: 0.2377671 (780)	total: 12.6s	remaining: 2.23s
800:	learn: 0.2298962	test: 0.2375596	best: 0.2375596 (800)	total: 12.9s	remaining: 1.91s
820:	learn: 0.2294941	test: 0.2373617	best: 0.2373617 (820)	total: 13.2s	remaining: 1.59s
840:	learn: 0.2292021	test: 0.2372554	best: 0.2372554 (840)	total: 13.5s	remaining: 1.27s
860:	learn: 0.2288179	test: 0.2370263	best: 0.2370263 (860)	total: 13.8s	remaining: 948ms
880:	learn: 0.2285047	test: 0.2368856	best: 0.2368856 (880)	total: 14.2s	remaining: 627ms
900:	learn: 0.2281838	test: 0.2367472	best: 0.2367472 (900)	total: 14.5s	remaining: 306ms
919:	learn: 0.2278567	test: 0.2365224	best: 0.2365214 (918)	total: 14.8s	remaining: 0us
bestTest = 0.2365213632
bestIteration = 918
Shrink model to first 919 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6294859	test: 0.6295160	best: 0.6295160 (0)	total: 9.24ms	remaining: 9.24ms
1:	learn: 0.5769943	test: 0.5770137	best: 0.5770137 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5770136914
bestIteration = 1
0:	learn: 0.6295740	test: 0.6296334	best: 0.6296334 (0)	total: 17.6ms	remaining: 19.1s
20:	learn: 0.3218704	test: 0.3222873	best: 0.3222873 (20)	total: 327ms	remaining: 16.6s
40:	learn: 0.2879402	test: 0.2884844	best: 0.2884844 (40)	total: 638ms	remaining: 16.3s
60:	learn: 0.2770231	test: 0.2776449	best: 0.2776449 (60)	total: 960ms	remaining: 16.2s
80:	learn: 0.2707261	test: 0.2714853	best: 0.2714853 (80)	total: 1.27s	remaining: 15.9s
100:	learn: 0.2659165	test: 0.2668273	best: 0.2668273 (100)	total: 1.58s	remaining: 15.5s
120:	learn: 0.2620739	test: 0.2630778	best: 0.2630778 (120)	total: 1.89s	remaining: 15.2s
140:	learn: 0.2591963	test: 0.2603094	best: 0.2603094 (140)	total: 2.21s	remaining: 14.8s
160:	learn: 0.2567135	test: 0.2579856	best: 0.2579856 (160)	total: 2.55s	remaining: 14.7s
180:	learn: 0.2544663	test: 0.2558500	best: 0.2558500 (180)	total: 2.86s	remaining: 14.3s
200:	learn: 0.2523684	test: 0.2538832	best: 0.2538832 (200)	total: 3.16s	remaining: 14s
220:	learn: 0.2503608	test: 0.2520475	best: 0.2520475 (220)	total: 3.46s	remaining: 13.6s
240:	learn: 0.2488124	test: 0.2505967	best: 0.2505967 (240)	total: 3.76s	remaining: 13.2s
260:	learn: 0.2472662	test: 0.2491939	best: 0.2491939 (260)	total: 4.07s	remaining: 12.9s
280:	learn: 0.2460233	test: 0.2480578	best: 0.2480578 (280)	total: 4.38s	remaining: 12.6s
300:	learn: 0.2448704	test: 0.2470788	best: 0.2470788 (300)	total: 4.68s	remaining: 12.3s
320:	learn: 0.2439019	test: 0.2462255	best: 0.2462255 (320)	total: 4.97s	remaining: 11.9s
340:	learn: 0.2428718	test: 0.2453605	best: 0.2453605 (340)	total: 5.28s	remaining: 11.6s
360:	learn: 0.2419602	test: 0.2445475	best: 0.2445475 (360)	total: 5.58s	remaining: 11.3s
380:	learn: 0.2411187	test: 0.2438782	best: 0.2438782 (380)	total: 5.88s	remaining: 10.9s
400:	learn: 0.2403342	test: 0.2432113	best: 0.2432113 (400)	total: 6.18s	remaining: 10.6s
420:	learn: 0.2395178	test: 0.2425071	best: 0.2425071 (420)	total: 6.47s	remaining: 10.3s
440:	learn: 0.2388212	test: 0.2419394	best: 0.2419394 (440)	total: 6.76s	remaining: 9.93s
460:	learn: 0.2381580	test: 0.2414178	best: 0.2414178 (460)	total: 7.05s	remaining: 9.6s
480:	learn: 0.2374583	test: 0.2408741	best: 0.2408741 (480)	total: 7.35s	remaining: 9.29s
500:	learn: 0.2367866	test: 0.2403034	best: 0.2403034 (500)	total: 7.64s	remaining: 8.97s
520:	learn: 0.2361793	test: 0.2398627	best: 0.2398627 (520)	total: 7.96s	remaining: 8.67s
540:	learn: 0.2356745	test: 0.2394838	best: 0.2394838 (540)	total: 8.28s	remaining: 8.38s
560:	learn: 0.2351269	test: 0.2390736	best: 0.2390736 (560)	total: 8.59s	remaining: 8.09s
580:	learn: 0.2346504	test: 0.2387966	best: 0.2387966 (580)	total: 8.88s	remaining: 7.76s
600:	learn: 0.2340793	test: 0.2383388	best: 0.2383388 (600)	total: 9.18s	remaining: 7.45s
620:	learn: 0.2336098	test: 0.2380172	best: 0.2380172 (620)	total: 9.49s	remaining: 7.15s
640:	learn: 0.2331864	test: 0.2377540	best: 0.2377540 (640)	total: 9.85s	remaining: 6.88s
660:	learn: 0.2327526	test: 0.2374839	best: 0.2374839 (660)	total: 10.2s	remaining: 6.58s
680:	learn: 0.2322866	test: 0.2371623	best: 0.2371623 (680)	total: 10.5s	remaining: 6.29s
700:	learn: 0.2318790	test: 0.2369167	best: 0.2369167 (700)	total: 10.8s	remaining: 5.99s
720:	learn: 0.2315004	test: 0.2366973	best: 0.2366973 (720)	total: 11.1s	remaining: 5.68s
740:	learn: 0.2310923	test: 0.2364503	best: 0.2364503 (740)	total: 11.4s	remaining: 5.36s
760:	learn: 0.2307384	test: 0.2362357	best: 0.2362357 (760)	total: 11.7s	remaining: 5.04s
780:	learn: 0.2303117	test: 0.2359247	best: 0.2359247 (780)	total: 12s	remaining: 4.73s
800:	learn: 0.2299471	test: 0.2357459	best: 0.2357459 (800)	total: 12.3s	remaining: 4.42s
820:	learn: 0.2296101	test: 0.2355506	best: 0.2355506 (820)	total: 12.6s	remaining: 4.11s
840:	learn: 0.2292437	test: 0.2353082	best: 0.2353082 (840)	total: 12.9s	remaining: 3.8s
860:	learn: 0.2288918	test: 0.2350627	best: 0.2350627 (860)	total: 13.2s	remaining: 3.49s
880:	learn: 0.2285101	test: 0.2347987	best: 0.2347987 (880)	total: 13.5s	remaining: 3.18s
900:	learn: 0.2282062	test: 0.2346567	best: 0.2346567 (900)	total: 13.8s	remaining: 2.88s
920:	learn: 0.2278839	test: 0.2344546	best: 0.2344546 (920)	total: 14.1s	remaining: 2.57s
940:	learn: 0.2275753	test: 0.2342750	best: 0.2342750 (940)	total: 14.4s	remaining: 2.26s
960:	learn: 0.2272730	test: 0.2341046	best: 0.2341046 (960)	total: 14.7s	remaining: 1.96s
980:	learn: 0.2269950	test: 0.2340038	best: 0.2340038 (980)	total: 15s	remaining: 1.65s
1000:	learn: 0.2267208	test: 0.2339150	best: 0.2339073 (998)	total: 15.3s	remaining: 1.34s
1020:	learn: 0.2264234	test: 0.2337304	best: 0.2337304 (1020)	total: 15.6s	remaining: 1.03s
1040:	learn: 0.2261680	test: 0.2336489	best: 0.2336489 (1040)	total: 15.8s	remaining: 731ms
1060:	learn: 0.2259022	test: 0.2335225	best: 0.2335225 (1060)	total: 16.1s	remaining: 426ms
1080:	learn: 0.2256124	test: 0.2333606	best: 0.2333606 (1080)	total: 16.4s	remaining: 122ms
1088:	learn: 0.2255057	test: 0.2333254	best: 0.2333254 (1088)	total: 16.6s	remaining: 0us
bestTest = 0.2333253714
bestIteration = 1088

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6295959	test: 0.6299773	best: 0.6299773 (0)	total: 8.69ms	remaining: 8.69ms
1:	learn: 0.5771533	test: 0.5778489	best: 0.5778489 (1)	total: 16.7ms	remaining: 0us
bestTest = 0.5778489252
bestIteration = 1
0:	learn: 0.6295979	test: 0.6299793	best: 0.6299793 (0)	total: 14.8ms	remaining: 22.8s
20:	learn: 0.3187850	test: 0.3201151	best: 0.3201151 (20)	total: 304ms	remaining: 22.1s
40:	learn: 0.2874248	test: 0.2892134	best: 0.2892134 (40)	total: 598ms	remaining: 22s
60:	learn: 0.2767248	test: 0.2788410	best: 0.2788410 (60)	total: 904ms	remaining: 22s
80:	learn: 0.2701314	test: 0.2724059	best: 0.2724059 (80)	total: 1.2s	remaining: 21.7s
100:	learn: 0.2654894	test: 0.2679464	best: 0.2679464 (100)	total: 1.52s	remaining: 21.8s
120:	learn: 0.2619467	test: 0.2645219	best: 0.2645219 (120)	total: 1.82s	remaining: 21.5s
140:	learn: 0.2588272	test: 0.2615828	best: 0.2615828 (140)	total: 2.24s	remaining: 22.4s
160:	learn: 0.2559909	test: 0.2589021	best: 0.2589021 (160)	total: 2.6s	remaining: 22.4s
180:	learn: 0.2537203	test: 0.2567707	best: 0.2567707 (180)	total: 2.9s	remaining: 21.9s
200:	learn: 0.2518927	test: 0.2550653	best: 0.2550653 (200)	total: 3.25s	remaining: 21.8s
220:	learn: 0.2498776	test: 0.2531881	best: 0.2531881 (220)	total: 3.63s	remaining: 21.8s
240:	learn: 0.2484184	test: 0.2518175	best: 0.2518175 (240)	total: 3.95s	remaining: 21.4s
260:	learn: 0.2471703	test: 0.2506595	best: 0.2506595 (260)	total: 4.24s	remaining: 20.9s
280:	learn: 0.2459400	test: 0.2495363	best: 0.2495363 (280)	total: 4.53s	remaining: 20.4s
300:	learn: 0.2448573	test: 0.2485940	best: 0.2485940 (300)	total: 4.82s	remaining: 20s
320:	learn: 0.2438077	test: 0.2477148	best: 0.2477148 (320)	total: 5.1s	remaining: 19.5s
340:	learn: 0.2426624	test: 0.2467172	best: 0.2467172 (340)	total: 5.4s	remaining: 19.1s
360:	learn: 0.2418121	test: 0.2460168	best: 0.2460168 (360)	total: 5.69s	remaining: 18.7s
380:	learn: 0.2408969	test: 0.2452521	best: 0.2452521 (380)	total: 5.98s	remaining: 18.3s
400:	learn: 0.2401872	test: 0.2446883	best: 0.2446883 (400)	total: 6.28s	remaining: 18s
420:	learn: 0.2393595	test: 0.2439853	best: 0.2439853 (420)	total: 6.59s	remaining: 17.6s
440:	learn: 0.2386048	test: 0.2434206	best: 0.2434206 (440)	total: 6.89s	remaining: 17.3s
460:	learn: 0.2379061	test: 0.2429042	best: 0.2429042 (460)	total: 7.18s	remaining: 16.9s
480:	learn: 0.2372410	test: 0.2423765	best: 0.2423765 (480)	total: 7.48s	remaining: 16.6s
500:	learn: 0.2367272	test: 0.2420124	best: 0.2420124 (500)	total: 7.78s	remaining: 16.3s
520:	learn: 0.2361046	test: 0.2415194	best: 0.2415194 (520)	total: 8.1s	remaining: 16s
540:	learn: 0.2355234	test: 0.2410959	best: 0.2410959 (540)	total: 8.39s	remaining: 15.6s
560:	learn: 0.2350581	test: 0.2407937	best: 0.2407937 (560)	total: 8.7s	remaining: 15.3s
580:	learn: 0.2345211	test: 0.2404035	best: 0.2404035 (580)	total: 9s	remaining: 15s
600:	learn: 0.2339783	test: 0.2400136	best: 0.2400136 (600)	total: 9.31s	remaining: 14.7s
620:	learn: 0.2334662	test: 0.2396672	best: 0.2396672 (620)	total: 9.61s	remaining: 14.3s
640:	learn: 0.2330358	test: 0.2393624	best: 0.2393624 (640)	total: 9.92s	remaining: 14s
660:	learn: 0.2326220	test: 0.2391378	best: 0.2391378 (660)	total: 10.2s	remaining: 13.7s
680:	learn: 0.2321338	test: 0.2388316	best: 0.2388316 (680)	total: 10.5s	remaining: 13.4s
700:	learn: 0.2316919	test: 0.2385371	best: 0.2385371 (700)	total: 10.8s	remaining: 13.1s
720:	learn: 0.2312723	test: 0.2382572	best: 0.2382572 (720)	total: 11.1s	remaining: 12.8s
740:	learn: 0.2308722	test: 0.2379720	best: 0.2379720 (740)	total: 11.5s	remaining: 12.5s
760:	learn: 0.2304807	test: 0.2377436	best: 0.2377436 (760)	total: 11.8s	remaining: 12.2s
780:	learn: 0.2301045	test: 0.2375146	best: 0.2375146 (780)	total: 12.1s	remaining: 11.9s
800:	learn: 0.2297603	test: 0.2373364	best: 0.2373364 (800)	total: 12.5s	remaining: 11.6s
820:	learn: 0.2294100	test: 0.2371090	best: 0.2371071 (819)	total: 12.8s	remaining: 11.3s
840:	learn: 0.2290966	test: 0.2369153	best: 0.2369153 (840)	total: 13.1s	remaining: 11s
860:	learn: 0.2287529	test: 0.2367287	best: 0.2367287 (860)	total: 13.4s	remaining: 10.7s
880:	learn: 0.2284088	test: 0.2365271	best: 0.2365271 (880)	total: 13.7s	remaining: 10.4s
900:	learn: 0.2280769	test: 0.2363799	best: 0.2363799 (900)	total: 14s	remaining: 10.1s
920:	learn: 0.2278120	test: 0.2362314	best: 0.2362314 (920)	total: 14.3s	remaining: 9.73s
940:	learn: 0.2274700	test: 0.2360216	best: 0.2360216 (940)	total: 14.6s	remaining: 9.41s
960:	learn: 0.2271409	test: 0.2358507	best: 0.2358491 (959)	total: 14.9s	remaining: 9.09s
980:	learn: 0.2268416	test: 0.2357207	best: 0.2357207 (980)	total: 15.2s	remaining: 8.77s
1000:	learn: 0.2265883	test: 0.2356353	best: 0.2356332 (999)	total: 15.5s	remaining: 8.45s
1020:	learn: 0.2262863	test: 0.2354956	best: 0.2354956 (1020)	total: 15.8s	remaining: 8.13s
1040:	learn: 0.2260141	test: 0.2353924	best: 0.2353924 (1040)	total: 16.1s	remaining: 7.82s
1060:	learn: 0.2256996	test: 0.2352436	best: 0.2352436 (1060)	total: 16.4s	remaining: 7.51s
1080:	learn: 0.2254083	test: 0.2351023	best: 0.2351023 (1080)	total: 16.6s	remaining: 7.19s
1100:	learn: 0.2251062	test: 0.2349580	best: 0.2349580 (1100)	total: 16.9s	remaining: 6.88s
1120:	learn: 0.2248580	test: 0.2348690	best: 0.2348690 (1120)	total: 17.2s	remaining: 6.56s
1140:	learn: 0.2245717	test: 0.2347180	best: 0.2347180 (1140)	total: 17.5s	remaining: 6.25s
1160:	learn: 0.2243149	test: 0.2346095	best: 0.2346095 (1160)	total: 17.8s	remaining: 5.95s
1180:	learn: 0.2240584	test: 0.2345069	best: 0.2345069 (1180)	total: 18.2s	remaining: 5.65s
1200:	learn: 0.2238117	test: 0.2344234	best: 0.2344234 (1200)	total: 18.5s	remaining: 5.34s
1220:	learn: 0.2235786	test: 0.2343406	best: 0.2343406 (1220)	total: 18.8s	remaining: 5.04s
1240:	learn: 0.2232943	test: 0.2342192	best: 0.2342181 (1238)	total: 19.1s	remaining: 4.73s
1260:	learn: 0.2230627	test: 0.2341172	best: 0.2341172 (1260)	total: 19.4s	remaining: 4.42s
1280:	learn: 0.2228057	test: 0.2340100	best: 0.2340100 (1280)	total: 19.7s	remaining: 4.1s
1300:	learn: 0.2225113	test: 0.2338558	best: 0.2338558 (1300)	total: 20s	remaining: 3.79s
1320:	learn: 0.2222745	test: 0.2337582	best: 0.2337582 (1320)	total: 20.3s	remaining: 3.48s
1340:	learn: 0.2220350	test: 0.2336941	best: 0.2336941 (1340)	total: 20.6s	remaining: 3.18s
1360:	learn: 0.2217866	test: 0.2335800	best: 0.2335800 (1360)	total: 20.9s	remaining: 2.87s
1380:	learn: 0.2215717	test: 0.2334862	best: 0.2334862 (1380)	total: 21.2s	remaining: 2.56s
1400:	learn: 0.2213195	test: 0.2333898	best: 0.2333898 (1400)	total: 21.4s	remaining: 2.25s
1420:	learn: 0.2210766	test: 0.2333074	best: 0.2333074 (1420)	total: 21.7s	remaining: 1.94s
1440:	learn: 0.2208641	test: 0.2332620	best: 0.2332581 (1439)	total: 22s	remaining: 1.64s
1460:	learn: 0.2206428	test: 0.2331787	best: 0.2331768 (1459)	total: 22.3s	remaining: 1.33s
1480:	learn: 0.2204028	test: 0.2330918	best: 0.2330918 (1480)	total: 22.6s	remaining: 1.02s
1500:	learn: 0.2201906	test: 0.2330159	best: 0.2330154 (1499)	total: 22.9s	remaining: 718ms
1520:	learn: 0.2199592	test: 0.2328852	best: 0.2328852 (1520)	total: 23.2s	remaining: 412ms
1540:	learn: 0.2197533	test: 0.2328295	best: 0.2328295 (1540)	total: 23.5s	remaining: 107ms
1547:	learn: 0.2196865	test: 0.2328275	best: 0.2328208 (1543)	total: 23.6s	remaining: 0us
bestTest = 0.2328207762
bestIteration = 1543
Shrink model to first 1544 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6295544	test: 0.6295790	best: 0.6295790 (0)	total: 9.05ms	remaining: 9.05ms
1:	learn: 0.5770676	test: 0.5771699	best: 0.5771699 (1)	total: 18.6ms	remaining: 0us
bestTest = 0.577169893
bestIteration = 1
0:	learn: 0.6296796	test: 0.6297410	best: 0.6297410 (0)	total: 15.6ms	remaining: 32.4s
20:	learn: 0.3188794	test: 0.3205362	best: 0.3205362 (20)	total: 309ms	remaining: 30.1s
40:	learn: 0.2865730	test: 0.2885637	best: 0.2885637 (40)	total: 614ms	remaining: 30.4s
60:	learn: 0.2763185	test: 0.2785229	best: 0.2785229 (60)	total: 919ms	remaining: 30.3s
80:	learn: 0.2696956	test: 0.2721357	best: 0.2721357 (80)	total: 1.21s	remaining: 29.9s
100:	learn: 0.2655005	test: 0.2681440	best: 0.2681440 (100)	total: 1.53s	remaining: 29.9s
120:	learn: 0.2618720	test: 0.2646734	best: 0.2646734 (120)	total: 1.83s	remaining: 29.5s
140:	learn: 0.2586482	test: 0.2616439	best: 0.2616439 (140)	total: 2.13s	remaining: 29.2s
160:	learn: 0.2564147	test: 0.2595396	best: 0.2595396 (160)	total: 2.43s	remaining: 28.9s
180:	learn: 0.2538128	test: 0.2571407	best: 0.2571407 (180)	total: 2.73s	remaining: 28.5s
200:	learn: 0.2519450	test: 0.2554650	best: 0.2554650 (200)	total: 3.02s	remaining: 28.2s
220:	learn: 0.2500800	test: 0.2537331	best: 0.2537331 (220)	total: 3.32s	remaining: 27.8s
240:	learn: 0.2485929	test: 0.2524553	best: 0.2524553 (240)	total: 3.62s	remaining: 27.5s
260:	learn: 0.2473835	test: 0.2514166	best: 0.2514166 (260)	total: 3.92s	remaining: 27.3s
280:	learn: 0.2459732	test: 0.2501254	best: 0.2501254 (280)	total: 4.22s	remaining: 26.9s
300:	learn: 0.2448190	test: 0.2491901	best: 0.2491901 (300)	total: 4.51s	remaining: 26.6s
320:	learn: 0.2435534	test: 0.2480848	best: 0.2480848 (320)	total: 4.8s	remaining: 26.2s
340:	learn: 0.2426267	test: 0.2472921	best: 0.2472921 (340)	total: 5.1s	remaining: 25.9s
360:	learn: 0.2416341	test: 0.2465220	best: 0.2465220 (360)	total: 5.38s	remaining: 25.5s
380:	learn: 0.2408373	test: 0.2458710	best: 0.2458710 (380)	total: 5.67s	remaining: 25.2s
400:	learn: 0.2401744	test: 0.2453380	best: 0.2453380 (400)	total: 5.96s	remaining: 24.9s
420:	learn: 0.2395359	test: 0.2449070	best: 0.2449070 (420)	total: 6.25s	remaining: 24.5s
440:	learn: 0.2389109	test: 0.2444227	best: 0.2444227 (440)	total: 6.55s	remaining: 24.3s
460:	learn: 0.2381229	test: 0.2438029	best: 0.2438029 (460)	total: 6.86s	remaining: 24s
480:	learn: 0.2374253	test: 0.2432663	best: 0.2432663 (480)	total: 7.15s	remaining: 23.7s
500:	learn: 0.2368385	test: 0.2428564	best: 0.2428564 (500)	total: 7.45s	remaining: 23.4s
520:	learn: 0.2361478	test: 0.2423032	best: 0.2423032 (520)	total: 7.74s	remaining: 23.1s
540:	learn: 0.2355226	test: 0.2418173	best: 0.2418173 (540)	total: 8.03s	remaining: 22.7s
560:	learn: 0.2349802	test: 0.2414460	best: 0.2414460 (560)	total: 8.32s	remaining: 22.4s
580:	learn: 0.2344194	test: 0.2410621	best: 0.2410621 (580)	total: 8.61s	remaining: 22.1s
600:	learn: 0.2338786	test: 0.2406865	best: 0.2406865 (600)	total: 8.9s	remaining: 21.8s
620:	learn: 0.2333860	test: 0.2403347	best: 0.2403347 (620)	total: 9.19s	remaining: 21.5s
640:	learn: 0.2329010	test: 0.2400112	best: 0.2400112 (640)	total: 9.48s	remaining: 21.2s
660:	learn: 0.2325044	test: 0.2397689	best: 0.2397689 (660)	total: 9.76s	remaining: 20.9s
680:	learn: 0.2320573	test: 0.2394743	best: 0.2394743 (680)	total: 10.1s	remaining: 20.6s
700:	learn: 0.2316377	test: 0.2391578	best: 0.2391578 (700)	total: 10.3s	remaining: 20.2s
720:	learn: 0.2312686	test: 0.2389591	best: 0.2389591 (720)	total: 10.6s	remaining: 19.9s
740:	learn: 0.2309164	test: 0.2387820	best: 0.2387820 (740)	total: 10.9s	remaining: 19.6s
760:	learn: 0.2305467	test: 0.2385943	best: 0.2385943 (760)	total: 11.2s	remaining: 19.3s
780:	learn: 0.2301538	test: 0.2384042	best: 0.2384042 (780)	total: 11.5s	remaining: 19s
800:	learn: 0.2297488	test: 0.2381730	best: 0.2381730 (800)	total: 11.8s	remaining: 18.7s
820:	learn: 0.2293883	test: 0.2379322	best: 0.2379322 (820)	total: 12.1s	remaining: 18.4s
840:	learn: 0.2290593	test: 0.2377534	best: 0.2377534 (840)	total: 12.4s	remaining: 18.1s
860:	learn: 0.2287281	test: 0.2375942	best: 0.2375942 (860)	total: 12.7s	remaining: 17.8s
880:	learn: 0.2284274	test: 0.2374604	best: 0.2374604 (880)	total: 13s	remaining: 17.5s
900:	learn: 0.2280560	test: 0.2372125	best: 0.2372125 (900)	total: 13.3s	remaining: 17.2s
920:	learn: 0.2277081	test: 0.2370260	best: 0.2370260 (920)	total: 13.5s	remaining: 16.9s
940:	learn: 0.2273452	test: 0.2368156	best: 0.2368156 (940)	total: 13.8s	remaining: 16.6s
960:	learn: 0.2269926	test: 0.2366243	best: 0.2366243 (960)	total: 14.1s	remaining: 16.3s
980:	learn: 0.2267267	test: 0.2365146	best: 0.2365118 (978)	total: 14.4s	remaining: 16s
1000:	learn: 0.2264493	test: 0.2363958	best: 0.2363958 (1000)	total: 14.7s	remaining: 15.7s
1020:	learn: 0.2261678	test: 0.2362640	best: 0.2362640 (1020)	total: 15s	remaining: 15.4s
1040:	learn: 0.2258724	test: 0.2361243	best: 0.2361243 (1040)	total: 15.3s	remaining: 15.1s
1060:	learn: 0.2255346	test: 0.2359662	best: 0.2359662 (1060)	total: 15.6s	remaining: 14.8s
1080:	learn: 0.2252943	test: 0.2358589	best: 0.2358589 (1080)	total: 15.9s	remaining: 14.6s
1100:	learn: 0.2250005	test: 0.2357479	best: 0.2357479 (1100)	total: 16.1s	remaining: 14.3s
1120:	learn: 0.2247496	test: 0.2356279	best: 0.2356279 (1120)	total: 16.4s	remaining: 14s
1140:	learn: 0.2244901	test: 0.2355443	best: 0.2355443 (1140)	total: 16.7s	remaining: 13.7s
1160:	learn: 0.2242629	test: 0.2354798	best: 0.2354798 (1160)	total: 17s	remaining: 13.4s
1180:	learn: 0.2239574	test: 0.2353473	best: 0.2353464 (1178)	total: 17.3s	remaining: 13.1s
1200:	learn: 0.2236870	test: 0.2352154	best: 0.2352154 (1200)	total: 17.6s	remaining: 12.8s
1220:	learn: 0.2234088	test: 0.2350758	best: 0.2350758 (1220)	total: 17.9s	remaining: 12.5s
1240:	learn: 0.2231979	test: 0.2349868	best: 0.2349868 (1240)	total: 18.2s	remaining: 12.2s
1260:	learn: 0.2229322	test: 0.2348572	best: 0.2348572 (1260)	total: 18.5s	remaining: 11.9s
1280:	learn: 0.2226866	test: 0.2347983	best: 0.2347983 (1280)	total: 18.8s	remaining: 11.6s
1300:	learn: 0.2224368	test: 0.2346790	best: 0.2346790 (1300)	total: 19.1s	remaining: 11.3s
1320:	learn: 0.2221982	test: 0.2345864	best: 0.2345864 (1320)	total: 19.4s	remaining: 11s
1340:	learn: 0.2219768	test: 0.2345122	best: 0.2345122 (1340)	total: 19.7s	remaining: 10.7s
1360:	learn: 0.2217279	test: 0.2343753	best: 0.2343753 (1360)	total: 20s	remaining: 10.5s
1380:	learn: 0.2215047	test: 0.2342730	best: 0.2342730 (1380)	total: 20.3s	remaining: 10.2s
1400:	learn: 0.2212972	test: 0.2342099	best: 0.2342099 (1400)	total: 20.6s	remaining: 9.88s
1420:	learn: 0.2210766	test: 0.2341667	best: 0.2341646 (1416)	total: 20.9s	remaining: 9.59s
1440:	learn: 0.2208390	test: 0.2340916	best: 0.2340916 (1440)	total: 21.2s	remaining: 9.3s
1460:	learn: 0.2206383	test: 0.2340200	best: 0.2340200 (1460)	total: 21.5s	remaining: 9s
1480:	learn: 0.2204183	test: 0.2339221	best: 0.2339221 (1480)	total: 21.8s	remaining: 8.7s
1500:	learn: 0.2201932	test: 0.2338296	best: 0.2338283 (1499)	total: 22.1s	remaining: 8.42s
1520:	learn: 0.2199933	test: 0.2337755	best: 0.2337755 (1520)	total: 22.4s	remaining: 8.12s
1540:	learn: 0.2197614	test: 0.2336837	best: 0.2336837 (1540)	total: 22.7s	remaining: 7.83s
1560:	learn: 0.2195851	test: 0.2336444	best: 0.2336393 (1557)	total: 23s	remaining: 7.53s
1580:	learn: 0.2193347	test: 0.2335088	best: 0.2335088 (1580)	total: 23.3s	remaining: 7.24s
1600:	learn: 0.2191327	test: 0.2334634	best: 0.2334634 (1600)	total: 23.6s	remaining: 6.95s
1620:	learn: 0.2189547	test: 0.2334258	best: 0.2334249 (1619)	total: 23.9s	remaining: 6.65s
1640:	learn: 0.2187323	test: 0.2333749	best: 0.2333694 (1638)	total: 24.2s	remaining: 6.36s
1660:	learn: 0.2185069	test: 0.2332885	best: 0.2332885 (1660)	total: 24.5s	remaining: 6.07s
1680:	learn: 0.2183124	test: 0.2332564	best: 0.2332550 (1678)	total: 24.8s	remaining: 5.77s
1700:	learn: 0.2181159	test: 0.2332178	best: 0.2332164 (1697)	total: 25s	remaining: 5.48s
1720:	learn: 0.2179043	test: 0.2331798	best: 0.2331791 (1718)	total: 25.3s	remaining: 5.18s
1740:	learn: 0.2177003	test: 0.2330930	best: 0.2330930 (1740)	total: 25.6s	remaining: 4.89s
1760:	learn: 0.2174672	test: 0.2329986	best: 0.2329978 (1759)	total: 25.9s	remaining: 4.59s
1780:	learn: 0.2172881	test: 0.2329551	best: 0.2329544 (1778)	total: 26.2s	remaining: 4.3s
1800:	learn: 0.2170960	test: 0.2328991	best: 0.2328991 (1800)	total: 26.5s	remaining: 4.01s
1820:	learn: 0.2169184	test: 0.2328688	best: 0.2328688 (1820)	total: 26.8s	remaining: 3.71s
1840:	learn: 0.2167093	test: 0.2328177	best: 0.2328172 (1839)	total: 27.1s	remaining: 3.42s
1860:	learn: 0.2165348	test: 0.2327916	best: 0.2327916 (1860)	total: 27.4s	remaining: 3.12s
1880:	learn: 0.2163292	test: 0.2327478	best: 0.2327478 (1880)	total: 27.7s	remaining: 2.83s
1900:	learn: 0.2161363	test: 0.2327076	best: 0.2327075 (1898)	total: 28s	remaining: 2.53s
1920:	learn: 0.2159478	test: 0.2326887	best: 0.2326838 (1919)	total: 28.3s	remaining: 2.24s
1940:	learn: 0.2157637	test: 0.2326748	best: 0.2326738 (1939)	total: 28.6s	remaining: 1.95s
1960:	learn: 0.2155869	test: 0.2326245	best: 0.2326245 (1960)	total: 28.9s	remaining: 1.65s
1980:	learn: 0.2153846	test: 0.2325600	best: 0.2325600 (1980)	total: 29.2s	remaining: 1.36s
2000:	learn: 0.2151943	test: 0.2325271	best: 0.2325271 (2000)	total: 29.5s	remaining: 1.06s
2020:	learn: 0.2149932	test: 0.2325042	best: 0.2324967 (2017)	total: 29.8s	remaining: 767ms
2040:	learn: 0.2148141	test: 0.2324585	best: 0.2324575 (2039)	total: 30.1s	remaining: 472ms
2060:	learn: 0.2146285	test: 0.2324073	best: 0.2324073 (2060)	total: 30.4s	remaining: 177ms
2072:	learn: 0.2145147	test: 0.2323800	best: 0.2323800 (2072)	total: 30.6s	remaining: 0us
bestTest = 0.2323800493
bestIteration = 2072

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6297417	test: 0.6297829	best: 0.6297829 (0)	total: 10.6ms	remaining: 10.6ms
1:	learn: 0.5774066	test: 0.5774634	best: 0.5774634 (1)	total: 24.9ms	remaining: 0us
bestTest = 0.5774634381
bestIteration = 1
0:	learn: 0.6297339	test: 0.6297751	best: 0.6297751 (0)	total: 18ms	remaining: 37.6s
20:	learn: 0.3208769	test: 0.3203010	best: 0.3203010 (20)	total: 347ms	remaining: 34.1s
40:	learn: 0.2881425	test: 0.2874317	best: 0.2874317 (40)	total: 693ms	remaining: 34.6s
60:	learn: 0.2770586	test: 0.2763410	best: 0.2763410 (60)	total: 1.06s	remaining: 35.2s
80:	learn: 0.2700832	test: 0.2694712	best: 0.2694712 (80)	total: 1.38s	remaining: 34.1s
100:	learn: 0.2658269	test: 0.2653005	best: 0.2653005 (100)	total: 1.68s	remaining: 33s
120:	learn: 0.2616686	test: 0.2612385	best: 0.2612385 (120)	total: 1.98s	remaining: 32.1s
140:	learn: 0.2585588	test: 0.2583064	best: 0.2583064 (140)	total: 2.27s	remaining: 31.4s
160:	learn: 0.2563238	test: 0.2562308	best: 0.2562308 (160)	total: 2.59s	remaining: 31s
180:	learn: 0.2541720	test: 0.2541923	best: 0.2541923 (180)	total: 2.9s	remaining: 30.6s
200:	learn: 0.2523223	test: 0.2524107	best: 0.2524107 (200)	total: 3.27s	remaining: 30.7s
220:	learn: 0.2505964	test: 0.2507356	best: 0.2507356 (220)	total: 3.56s	remaining: 30.1s
240:	learn: 0.2490794	test: 0.2493273	best: 0.2493273 (240)	total: 3.9s	remaining: 29.9s
260:	learn: 0.2478360	test: 0.2482087	best: 0.2482087 (260)	total: 4.24s	remaining: 29.7s
280:	learn: 0.2461985	test: 0.2467164	best: 0.2467164 (280)	total: 4.54s	remaining: 29.2s
300:	learn: 0.2450442	test: 0.2456672	best: 0.2456672 (300)	total: 4.83s	remaining: 28.7s
320:	learn: 0.2439025	test: 0.2446491	best: 0.2446491 (320)	total: 5.13s	remaining: 28.3s
340:	learn: 0.2430910	test: 0.2439754	best: 0.2439754 (340)	total: 5.44s	remaining: 27.9s
360:	learn: 0.2422144	test: 0.2431831	best: 0.2431831 (360)	total: 5.75s	remaining: 27.5s
380:	learn: 0.2413887	test: 0.2424773	best: 0.2424773 (380)	total: 6.06s	remaining: 27.2s
400:	learn: 0.2405784	test: 0.2417630	best: 0.2417630 (400)	total: 6.36s	remaining: 26.8s
420:	learn: 0.2397820	test: 0.2410719	best: 0.2410719 (420)	total: 6.65s	remaining: 26.4s
440:	learn: 0.2391002	test: 0.2404954	best: 0.2404954 (440)	total: 6.94s	remaining: 25.9s
460:	learn: 0.2384150	test: 0.2399677	best: 0.2399677 (460)	total: 7.23s	remaining: 25.5s
480:	learn: 0.2377831	test: 0.2395021	best: 0.2395021 (480)	total: 7.54s	remaining: 25.2s
500:	learn: 0.2371921	test: 0.2390551	best: 0.2390551 (500)	total: 7.83s	remaining: 24.8s
520:	learn: 0.2365963	test: 0.2385950	best: 0.2385950 (520)	total: 8.12s	remaining: 24.4s
540:	learn: 0.2360168	test: 0.2381188	best: 0.2381188 (540)	total: 8.4s	remaining: 24.1s
560:	learn: 0.2355081	test: 0.2377636	best: 0.2377636 (560)	total: 8.73s	remaining: 23.8s
580:	learn: 0.2349544	test: 0.2373526	best: 0.2373526 (580)	total: 9.04s	remaining: 23.5s
600:	learn: 0.2344907	test: 0.2370053	best: 0.2370053 (600)	total: 9.39s	remaining: 23.3s
620:	learn: 0.2340465	test: 0.2366974	best: 0.2366974 (620)	total: 9.71s	remaining: 23s
640:	learn: 0.2335284	test: 0.2363475	best: 0.2363475 (640)	total: 10s	remaining: 22.6s
660:	learn: 0.2330792	test: 0.2360276	best: 0.2360276 (660)	total: 10.3s	remaining: 22.3s
680:	learn: 0.2325683	test: 0.2356403	best: 0.2356403 (680)	total: 10.6s	remaining: 22s
700:	learn: 0.2320963	test: 0.2352774	best: 0.2352774 (700)	total: 11s	remaining: 21.8s
720:	learn: 0.2316796	test: 0.2350155	best: 0.2350155 (720)	total: 11.3s	remaining: 21.5s
740:	learn: 0.2313237	test: 0.2348053	best: 0.2348053 (740)	total: 11.7s	remaining: 21.2s
760:	learn: 0.2309444	test: 0.2345691	best: 0.2345691 (760)	total: 12s	remaining: 20.9s
780:	learn: 0.2306129	test: 0.2343696	best: 0.2343696 (780)	total: 12.3s	remaining: 20.6s
800:	learn: 0.2302415	test: 0.2341601	best: 0.2341601 (800)	total: 12.6s	remaining: 20.2s
820:	learn: 0.2298572	test: 0.2339403	best: 0.2339403 (820)	total: 12.9s	remaining: 19.9s
840:	learn: 0.2295338	test: 0.2337493	best: 0.2337493 (840)	total: 13.2s	remaining: 19.6s
860:	learn: 0.2292109	test: 0.2335828	best: 0.2335828 (860)	total: 13.5s	remaining: 19.3s
880:	learn: 0.2288685	test: 0.2334119	best: 0.2334119 (880)	total: 13.8s	remaining: 18.9s
900:	learn: 0.2285448	test: 0.2332273	best: 0.2332273 (900)	total: 14.1s	remaining: 18.6s
920:	learn: 0.2282129	test: 0.2330451	best: 0.2330451 (920)	total: 14.4s	remaining: 18.3s
940:	learn: 0.2278916	test: 0.2328927	best: 0.2328927 (940)	total: 14.7s	remaining: 17.9s
960:	learn: 0.2275672	test: 0.2327091	best: 0.2327062 (959)	total: 15s	remaining: 17.6s
980:	learn: 0.2271736	test: 0.2324844	best: 0.2324844 (980)	total: 15.3s	remaining: 17.3s
1000:	learn: 0.2268105	test: 0.2322873	best: 0.2322873 (1000)	total: 15.6s	remaining: 16.9s
1020:	learn: 0.2264796	test: 0.2321017	best: 0.2321017 (1020)	total: 15.9s	remaining: 16.6s
1040:	learn: 0.2261753	test: 0.2319558	best: 0.2319558 (1040)	total: 16.2s	remaining: 16.3s
1060:	learn: 0.2258654	test: 0.2318048	best: 0.2318048 (1060)	total: 16.5s	remaining: 16s
1080:	learn: 0.2256135	test: 0.2317095	best: 0.2317095 (1080)	total: 16.9s	remaining: 15.7s
1100:	learn: 0.2253580	test: 0.2315940	best: 0.2315940 (1100)	total: 17.2s	remaining: 15.4s
1120:	learn: 0.2250608	test: 0.2314850	best: 0.2314850 (1120)	total: 17.5s	remaining: 15.1s
1140:	learn: 0.2247933	test: 0.2313600	best: 0.2313600 (1140)	total: 17.8s	remaining: 14.8s
1160:	learn: 0.2245313	test: 0.2312211	best: 0.2312211 (1160)	total: 18.1s	remaining: 14.4s
1180:	learn: 0.2242802	test: 0.2311197	best: 0.2311168 (1178)	total: 18.4s	remaining: 14.1s
1200:	learn: 0.2239934	test: 0.2309879	best: 0.2309879 (1200)	total: 18.7s	remaining: 13.8s
1220:	learn: 0.2237461	test: 0.2308849	best: 0.2308846 (1218)	total: 18.9s	remaining: 13.5s
1240:	learn: 0.2234742	test: 0.2307627	best: 0.2307627 (1240)	total: 19.2s	remaining: 13.1s
1260:	learn: 0.2232095	test: 0.2306328	best: 0.2306322 (1259)	total: 19.5s	remaining: 12.8s
1280:	learn: 0.2229351	test: 0.2305466	best: 0.2305466 (1280)	total: 19.8s	remaining: 12.5s
1300:	learn: 0.2226847	test: 0.2304617	best: 0.2304616 (1299)	total: 20.1s	remaining: 12.2s
1320:	learn: 0.2224617	test: 0.2304016	best: 0.2304000 (1319)	total: 20.4s	remaining: 11.9s
1340:	learn: 0.2222447	test: 0.2303236	best: 0.2303236 (1340)	total: 20.7s	remaining: 11.6s
1360:	learn: 0.2220339	test: 0.2302842	best: 0.2302803 (1359)	total: 21s	remaining: 11.2s
1380:	learn: 0.2218169	test: 0.2302140	best: 0.2302132 (1376)	total: 21.3s	remaining: 10.9s
1400:	learn: 0.2215773	test: 0.2301355	best: 0.2301355 (1400)	total: 21.6s	remaining: 10.6s
1420:	learn: 0.2213446	test: 0.2300307	best: 0.2300307 (1420)	total: 21.9s	remaining: 10.3s
1440:	learn: 0.2211348	test: 0.2299521	best: 0.2299521 (1440)	total: 22.2s	remaining: 9.98s
1460:	learn: 0.2209011	test: 0.2298587	best: 0.2298570 (1459)	total: 22.5s	remaining: 9.66s
1480:	learn: 0.2206844	test: 0.2297868	best: 0.2297868 (1480)	total: 22.8s	remaining: 9.35s
1500:	learn: 0.2204812	test: 0.2297478	best: 0.2297478 (1500)	total: 23.1s	remaining: 9.04s
1520:	learn: 0.2202484	test: 0.2296605	best: 0.2296596 (1519)	total: 23.4s	remaining: 8.73s
1540:	learn: 0.2200534	test: 0.2296250	best: 0.2296250 (1540)	total: 23.7s	remaining: 8.41s
1560:	learn: 0.2198527	test: 0.2295575	best: 0.2295575 (1560)	total: 23.9s	remaining: 8.1s
1580:	learn: 0.2196618	test: 0.2294936	best: 0.2294936 (1580)	total: 24.2s	remaining: 7.79s
1600:	learn: 0.2194577	test: 0.2294313	best: 0.2294313 (1600)	total: 24.5s	remaining: 7.48s
1620:	learn: 0.2192319	test: 0.2293676	best: 0.2293649 (1619)	total: 24.8s	remaining: 7.17s
1640:	learn: 0.2190324	test: 0.2293378	best: 0.2293354 (1639)	total: 25.2s	remaining: 6.87s
1660:	learn: 0.2188493	test: 0.2292968	best: 0.2292968 (1660)	total: 25.5s	remaining: 6.57s
1680:	learn: 0.2186810	test: 0.2292541	best: 0.2292541 (1680)	total: 25.8s	remaining: 6.26s
1700:	learn: 0.2184662	test: 0.2291855	best: 0.2291855 (1700)	total: 26.1s	remaining: 5.95s
1720:	learn: 0.2182827	test: 0.2291553	best: 0.2291528 (1715)	total: 26.4s	remaining: 5.64s
1740:	learn: 0.2180842	test: 0.2290886	best: 0.2290886 (1740)	total: 26.7s	remaining: 5.33s
1760:	learn: 0.2178907	test: 0.2290556	best: 0.2290556 (1760)	total: 27s	remaining: 5.02s
1780:	learn: 0.2176905	test: 0.2290208	best: 0.2290153 (1777)	total: 27.3s	remaining: 4.72s
1800:	learn: 0.2175101	test: 0.2289626	best: 0.2289626 (1800)	total: 27.6s	remaining: 4.42s
1820:	learn: 0.2173114	test: 0.2289207	best: 0.2289106 (1816)	total: 28s	remaining: 4.12s
1840:	learn: 0.2171203	test: 0.2288870	best: 0.2288870 (1840)	total: 28.3s	remaining: 3.81s
1860:	learn: 0.2169598	test: 0.2288554	best: 0.2288455 (1853)	total: 28.6s	remaining: 3.51s
1880:	learn: 0.2167698	test: 0.2288152	best: 0.2288069 (1877)	total: 28.9s	remaining: 3.2s
1900:	learn: 0.2165717	test: 0.2287461	best: 0.2287422 (1898)	total: 29.3s	remaining: 2.89s
1920:	learn: 0.2163600	test: 0.2286812	best: 0.2286812 (1920)	total: 29.6s	remaining: 2.59s
1940:	learn: 0.2161680	test: 0.2286264	best: 0.2286264 (1940)	total: 29.9s	remaining: 2.28s
1960:	learn: 0.2159945	test: 0.2286091	best: 0.2286091 (1960)	total: 30.3s	remaining: 1.97s
1980:	learn: 0.2158107	test: 0.2285761	best: 0.2285751 (1976)	total: 30.6s	remaining: 1.67s
2000:	learn: 0.2156164	test: 0.2285398	best: 0.2285367 (1999)	total: 30.9s	remaining: 1.36s
2020:	learn: 0.2154290	test: 0.2285343	best: 0.2285309 (2006)	total: 31.3s	remaining: 1.05s
2040:	learn: 0.2152530	test: 0.2284912	best: 0.2284896 (2038)	total: 31.6s	remaining: 742ms
2060:	learn: 0.2150691	test: 0.2284545	best: 0.2284545 (2060)	total: 31.9s	remaining: 433ms
2080:	learn: 0.2148844	test: 0.2284339	best: 0.2284289 (2075)	total: 32.2s	remaining: 124ms
2088:	learn: 0.2148108	test: 0.2284302	best: 0.2284273 (2087)	total: 32.3s	remaining: 0us
bestTest = 0.2284272946
bestIteration = 2087
Shrink model to first 2088 iterations.

Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\model.pkl
	0.9446	 = Validation score   (roc_auc)
	157.69s	 = Training   runtime
	0.14s	 = Validation runtime
	387764.6	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\CatBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1640.52s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/2.3 GB
Ensemble size: 1
Ensemble weights:
[1.]
	0.28s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	0.9446	 = Validation score   (roc_auc)
	0.05s	 = Training   runtime
	0.04s	 = Validation runtime
	374534.9	 = Inference  throughput (rows/s | 54893 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
AutoGluon training complete, total runtime = 159.67s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 374534.9 rows/s (54893 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\CAT\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4\CAT")

CAT completed.
Validation ROC-AUC: 0.944636

================================================================================
FINAL MODEL COMPARISON
================================================================================

,Model Family,Best AutoGluon Model,Validation ROC-AUC,Fit Time (sec),Predict Time (sec)
0,GBM,WeightedEnsemble_L2,0.948897,257.058052,11.228144
1,XGB,XGBoost_BAG_L1,0.947970,128.010609,1.460929
2,CAT,CatBoost_BAG_L1,0.944636,157.690471,0.141563

In [16]:
import os
import pandas as pd
from autogluon.tabular import TabularPredictor

# ============================================================
# CONFIG
# ============================================================

MODEL_DIR = "./ag_models3"

all_leaderboards = []

# ============================================================
# SCAN & LOAD ALL TRAINED PREDICTORS
# ============================================================

if os.path.exists(MODEL_DIR):
    # Check both subdirectories and root directory for saved predictors
    folder_candidates = [MODEL_DIR] + [
        os.path.join(MODEL_DIR, d) 
        for d in os.listdir(MODEL_DIR) 
        if os.path.isdir(os.path.join(MODEL_DIR, d))
    ]

    for folder_path in folder_candidates:
        # Check if directory contains a valid predictor file
        if os.path.exists(os.path.join(folder_path, "predictor.pkl")):
            try:
                folder_name = os.path.basename(folder_path)
                print(f"Loading predictor from: {folder_path}")
                
                # Load predictor from disk
                predictor = TabularPredictor.load(folder_path)
                
                # Fetch leaderboard
                lb = predictor.leaderboard(silent=True)
                lb.insert(0, "folder_name", folder_name)
                
                all_leaderboards.append(lb)
            except Exception as e:
                print(f"Failed to load predictor from {folder_path}: {e}")

# ============================================================
# MERGE AND PRESENT COMBINED LEADERBOARD
# ============================================================

if all_leaderboards:
    combined_leaderboard = pd.concat(all_leaderboards, ignore_index=True)

    # Sort all trained models by validation ROC-AUC score descending
    combined_leaderboard = combined_leaderboard.sort_values(
        by="score_val", ascending=False
    ).reset_index(drop=True)

    print("\n" + "=" * 80)
    print("COMBINED LEADERBOARD OF ALL LOADED MODELS")
    print("=" * 80)

    display(combined_leaderboard)
else:
    print(f"No valid AutoGluon predictors (`predictor.pkl`) found under '{MODEL_DIR}'.")

Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\CAT\models\trainer.pkl

Loading predictor from: ./ag_models3\CAT
Loading predictor from: ./ag_models3\GBM

Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\GBM\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\predictor.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\learner.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\trainer.pkl

Loading predictor from: ./ag_models3\XGB

================================================================================
COMBINED LEADERBOARD OF ALL LOADED MODELS
================================================================================

,folder_name,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,GBM,WeightedEnsemble_L2,0.957781,roc_auc,36.298102,410.961213,0.051081,2.553276,2,True,3
1,GBM,LightGBM_BAG_L1,0.957254,roc_auc,12.108692,179.215388,12.108692,179.215388,1,True,1
2,XGB,XGBoost_BAG_L1,0.956154,roc_auc,3.170212,255.022554,3.170212,255.022554,1,True,1
3,XGB,WeightedEnsemble_L2,0.956154,roc_auc,3.220778,255.079135,0.050566,0.056581,2,True,2
4,GBM,LightGBMLarge_BAG_L1,0.955598,roc_auc,24.138329,229.192549,24.138329,229.192549,1,True,2
5,CAT,WeightedEnsemble_L2,0.943546,roc_auc,0.214443,181.873038,0.050315,0.056394,2,True,2
6,CAT,CatBoost_BAG_L1,0.943546,roc_auc,0.164128,181.816644,0.164128,181.816644,1,True,1

In [17]:
df=predictor.predict_proba(df_test)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl

          0         1
0  0.999910  0.000090
1  0.999970  0.000030
2  0.999918  0.000082
3  0.978575  0.021425
4  0.998234  0.001766

In [18]:
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [19]:
df_sample_out['PitNextLap']=df[1]

In [20]:
df_sample_out.head()

       id  PitNextLap
0  439140    0.000090
1  439141    0.000030
2  439142    0.000082
3  439143    0.021425
4  439144    0.001766

In [21]:
df_sample_out.to_csv("My_output/feature_engineered_submission.csv")

In [24]:
### My sampling testing
from multi_sampling_test import process_and_evaluate_all_csvs
data_dict = process_and_evaluate_all_csvs(predictor,folder_path="Sampling_data_to_test")

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl

----------------------------------------
 Processing: sample_part_1_10000k.csv
----------------------------------------

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_1_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9403
Mismatches                         : 597
Accuracy (%)                       : 94.03
True Positives (Actual 1, Pred 1)  : 1683
True Negatives (Actual 0, Pred 0)  : 7720
False Positives (Actual 0, Pred 1) : 280
False Negatives (Actual 1, Pred 0) : 317
========================================

----------------------------------------
 Processing: sample_part_2_10000k.csv
----------------------------------------

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_2_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9457
Mismatches                         : 543
Accuracy (%)                       : 94.57
True Positives (Actual 1, Pred 1)  : 1279
True Negatives (Actual 0, Pred 0)  : 8178
False Positives (Actual 0, Pred 1) : 322
False Negatives (Actual 1, Pred 0) : 221
========================================

----------------------------------------
 Processing: sample_part_3_10000k.csv
----------------------------------------

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_3_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9379
Mismatches                         : 621
Accuracy (%)                       : 93.79
True Positives (Actual 1, Pred 1)  : 2133
True Negatives (Actual 0, Pred 0)  : 7246
False Positives (Actual 0, Pred 1) : 254
False Negatives (Actual 1, Pred 0) : 367
========================================

----------------------------------------
 Processing: sample_part_4_10000k.csv
----------------------------------------

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\XGBoost_BAG_L1\model.pkl

--- Per-File Analysis [sample_part_4_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9344
Mismatches                         : 656
Accuracy (%)                       : 93.44
True Positives (Actual 1, Pred 1)  : 2574
True Negatives (Actual 0, Pred 0)  : 6770
False Positives (Actual 0, Pred 1) : 230
False Negatives (Actual 1, Pred 0) : 426
========================================

----------------------------------------
 Processing: sample_part_5_10000k.csv
----------------------------------------

Loading: c:\Darshak\Projects\Hackathon\ag_models3\XGB\models\WeightedEnsemble_L2\model.pkl

--- Per-File Analysis [sample_part_5_10000k.csv] ---
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 10000
Correct Matches                    : 9518
Mismatches                         : 482
Accuracy (%)                       : 95.18
True Positives (Actual 1, Pred 1)  : 833
True Negatives (Actual 0, Pred 0)  : 8685
False Positives (Actual 0, Pred 1) : 315
False Negatives (Actual 1, Pred 0) : 167
========================================

==================================================
      OVERALL CUMULATIVE ANALYSIS REPORT
==================================================
========================================
      PREDICTION ANALYSIS REPORT
========================================
Total Records                      : 50000
Correct Matches                    : 47101
Mismatches                         : 2899
Accuracy (%)                       : 94.2
True Positives (Actual 1, Pred 1)  : 8502
True Negatives (Actual 0, Pred 0)  : 38599
False Positives (Actual 0, Pred 1) : 1401
False Negatives (Actual 1, Pred 0) : 1498
========================================