In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [2]:
predictor = TabularPredictor.load(f"ag_models26_optimize")
leaderboard = predictor.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3,0.960554,roc_auc,41.162426,6202.491388,0.050462,12.554040,3,True,12
1,CatBoost_BAG_L2,0.960453,roc_auc,37.901692,5319.889488,0.112630,75.265388,2,True,9
2,XGBoost_BAG_L2,0.960411,roc_auc,38.547848,5270.678005,0.758785,26.053904,2,True,10
3,LightGBM_BAG_L2,0.960372,roc_auc,38.096403,5259.947896,0.307340,15.323796,2,True,7
4,LightGBMLarge_BAG_L2,0.960310,roc_auc,38.481809,5268.079809,0.692746,23.455709,2,True,8
5,WeightedEnsemble_L2,0.960139,roc_auc,37.590145,4940.622525,0.049729,6.281797,2,True,6
6,NeuralNetTorch_BAG_L2,0.960057,roc_auc,39.240462,6049.838551,1.451400,805.214451,2,True,11
7,LightGBM_BAG_L1,0.958659,roc_auc,11.098258,229.201080,11.098258,229.201080,1,True,1
8,XGBoost_BAG_L1,0.957616,roc_auc,3.182534,316.204000,3.182534,316.204000,1,True,4
9,LightGBMLarge_BAG_L1,0.957522,roc_auc,22.141456,315.104320,22.141456,315.104320,1,True,2
10,NeuralNetTorch_BAG_L1,0.954561,roc_auc,1.118168,4073.831328,1.118168,4073.831328,1,True,5
11,CatBoost_BAG_L1,0.952446,roc_auc,0.248646,310.283371,0.248646,310.283371,1,True,3

In [8]:
lb = predictor.leaderboard(silent=True)

top5 = (
    lb[
        ~lb["model"].str.contains("WeightedEnsemble", na=False)
    ]
    .sort_values("score_val", ascending=False)
    .head(5)["model"]
    .tolist()
)

print("Top 3 models:")
print(top5)

Top 3 models:
['CatBoost_BAG_L2', 'XGBoost_BAG_L2', 'LightGBM_BAG_L2', 'LightGBMLarge_BAG_L2', 'NeuralNetTorch_BAG_L2']

In [9]:
top3_ensemble = predictor.fit_weighted_ensemble(
    base_models=top5,
    name_suffix="Top5"
)

print(top3_ensemble)

['WeightedEnsemble_L3Top5']

In [10]:
predictor.leaderboard(silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3Top5,0.960554,roc_auc,41.163463,6196.774231,0.051499,6.836883,3,True,14
1,WeightedEnsemble_L3,0.960554,roc_auc,41.162426,6202.491388,0.050462,12.554040,3,True,12
2,WeightedEnsemble_L3Top3,0.960532,roc_auc,39.035766,5365.382985,0.067948,4.115797,3,True,13
3,CatBoost_BAG_L2,0.960453,roc_auc,37.901692,5319.889488,0.112630,75.265388,2,True,9
4,XGBoost_BAG_L2,0.960411,roc_auc,38.547848,5270.678005,0.758785,26.053904,2,True,10
5,LightGBM_BAG_L2,0.960372,roc_auc,38.096403,5259.947896,0.307340,15.323796,2,True,7
6,LightGBMLarge_BAG_L2,0.960310,roc_auc,38.481809,5268.079809,0.692746,23.455709,2,True,8
7,WeightedEnsemble_L2,0.960139,roc_auc,37.590145,4940.622525,0.049729,6.281797,2,True,6
8,NeuralNetTorch_BAG_L2,0.960057,roc_auc,39.240462,6049.838551,1.451400,805.214451,2,True,11
9,LightGBM_BAG_L1,0.958659,roc_auc,11.098258,229.201080,11.098258,229.201080,1,True,1
10,XGBoost_BAG_L1,0.957616,roc_auc,3.182534,316.204000,3.182534,316.204000,1,True,4
11,LightGBMLarge_BAG_L1,0.957522,roc_auc,22.141456,315.104320,22.141456,315.104320,1,True,2
12,NeuralNetTorch_BAG_L1,0.954561,roc_auc,1.118168,4073.831328,1.118168,4073.831328,1,True,5
13,CatBoost_BAG_L1,0.952446,roc_auc,0.248646,310.283371,0.248646,310.283371,1,True,3