In [31]:
import pandas as pd
df_train=pd.read_csv('data/train.csv')
df_test=pd.read_csv('data/test.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

In [32]:
print(df_train.columns)

Index(['id', 'Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber',
       'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [35]:
df_train_merged["Race"].unique()

array(['Mexico City Grand Prix', 'Italian Grand Prix',
       'Monaco Grand Prix', 'Azerbaijan Grand Prix',
       'São Paulo Grand Prix', 'Emilia Romagna Grand Prix',
       'Canadian Grand Prix', 'Chinese Grand Prix',
       'Singapore Grand Prix', 'Hungarian Grand Prix',
       'French Grand Prix', 'Abu Dhabi Grand Prix', 'Austrian Grand Prix',
       'Japanese Grand Prix', 'Belgian Grand Prix', 'British Grand Prix',
       'Dutch Grand Prix', 'United States Grand Prix', 'Miami Grand Prix',
       'Spanish Grand Prix', 'Saudi Arabian Grand Prix',
       'Las Vegas Grand Prix', 'Qatar Grand Prix',
       'Australian Grand Prix', 'Bahrain Grand Prix',
       'Pre-Season Testing', 'Pre-Season Track Session',
       'Pre-Season Test'], dtype=object)

In [36]:
df_train_merged.columns

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')

In [37]:
df_train_merged[["Compound"]].value_counts()

Compound
MEDIUM          248780
HARD            215485
SOFT             51488
INTERMEDIATE     22938
WET               1754
Name: count, dtype: int64

In [38]:
#Tire dataset
def add_tire_life_columns(df):
    max_tire_life = {
        "MEDIUM": 40,
        "HARD": 55,
        "SOFT": 30,
        "INTERMEDIATE": 25,
        "WET": 20
    }

    df["MaxTireLife"] = df["Compound"].map(max_tire_life)

    df["TireRemainingLife"] = (
        df["MaxTireLife"] - df["TyreLife"]
    ).clip(lower=0)
    df["TireAgePct"] = (
    df["TyreLife"] / df["MaxTireLife"]).clip(0, 1)
    df["TireRemainingPct"] = (df["TireRemainingLife"] / df["MaxTireLife"]).clip(0, 1)
    

    return df

In [39]:
df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [40]:
def add_laps_for_each_race(df):
    df["RaceLaps"] = (
    df["LapNumber"] / (df["RaceProgress"])
).round()
    df["LapsRemaining"] = df["RaceLaps"] - df["LapNumber"]
    return df

In [41]:
def prev_position_calcute(df):
    df["Prev_Position"] = df["Position"] + df["Position_Change"]
    return df

In [42]:
def get_trend_data(df):
    df["LapTimeAvg_3"] = (
        df.groupby(["Year", "Race", "Driver"])["LapTime (s)"]
        .transform(lambda x: x.rolling(3, min_periods=1).mean())
    )
    return df

In [43]:
def set_fe(df):
    df = add_tire_life_columns(df)
    df = add_laps_for_each_race(df)
    df= prev_position_calcute(df)
    df = get_trend_data(df)
    return df

In [14]:
def calculate_race_progress(df, is_drop=True):
    condition = (df["Race"] == "Pre-Season Testing") & (
        (df["RaceLaps"] < 31) | (df["RaceLaps"] > 78)
    )

    if is_drop:
        # Keep rows that do NOT match the condition
        df = df[~condition] 
    F1_RACE_LAPS = {
        "Bahrain Grand Prix": 57,
        "Saudi Arabian Grand Prix": 50,
        "Australian Grand Prix": 58,
        "Azerbaijan Grand Prix": 51,
        "Miami Grand Prix": 57,
        "Monaco Grand Prix": 78,
        "Spanish Grand Prix": 66,
        "Canadian Grand Prix": 70,
        "Austrian Grand Prix": 71,
        "British Grand Prix": 52,
        "Hungarian Grand Prix": 70,
        "Belgian Grand Prix": 44,
        "Dutch Grand Prix": 72,
        "Italian Grand Prix": 51,
        "Singapore Grand Prix": 62,
        "Japanese Grand Prix": 53,
        "Qatar Grand Prix": 57,
        "United States Grand Prix": 56,
        "Mexico City Grand Prix": 71,
        "São Paulo Grand Prix": 71,
        "Las Vegas Grand Prix": 50,
        "Abu Dhabi Grand Prix": 58,
        }
    mask = df["Race"].isin(F1_RACE_LAPS.keys())

    # Update only matching rows
    df.loc[mask, "RaceLaps"] = df.loc[mask, "Race"].map(F1_RACE_LAPS)
    df["RaceLaps"] = df["Race"].map(F1_RACE_LAPS)
    df["RaceProgress"] = df["LapNumber"] / df["RaceLaps"]
    df["LapsRemaining"] = df["RaceLaps"] - df["LapNumber"]
    return df

In [44]:
# df_external_fe =set_fe(df_external.copy())
df_train_fe =set_fe(df_train.copy())
df_train_merged_fe =set_fe(df_train_merged.copy())
df_test_fe =set_fe(df_test.copy())

In [ ]:
# df_train_fe =calculate_race_progress(df_train_fe)
# df_train_merged_fe =calculate_race_progress(df_train_merged_fe)
# df_test_fe =calculate_race_progress(df_test_fe,is_drop=False)

C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["RaceLaps"] = df["Race"].map(F1_RACE_LAPS)
C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["RaceProgress"] = df["LapNumber"] / df["RaceLaps"]
C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["LapsRemaining"] = df["RaceLaps"] - df["LapNumber"]
C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["RaceLaps"] = df["Race"].map(F1_RACE_LAPS)
C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["RaceProgress"] = df["LapNumber"] / df["RaceLaps"]
C:\Users\Admin\AppData\Local\Temp\ipykernel_24560\1365074506.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["LapsRemaining"] = df["RaceLaps"] - df["LapNumber"]

In [45]:
df_train =df_train.drop("id",axis=1)
df_test =df_test.drop("id",axis=1)

In [46]:
df_train_fe =df_train_fe.drop("id",axis=1)
df_test_fe =df_test_fe.drop("id",axis=1)

In [47]:
df_train_merged.isnull().sum()

Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
PitNextLap                0
dtype: int64

In [48]:
df_train_merged.nunique().sort_values(ascending=False)

Cumulative_Degradation    163914
LapTime_Delta              73068
LapTime (s)                45108
RaceProgress                1947
Driver                       887
TyreLife                      79
LapNumber                     78
Position_Change               37
Race                          28
Position                      20
Stint                          8
Compound                       5
Year                           4
PitStop                        2
PitNextLap                     2
dtype: int64

In [49]:
df_train_merged['Normalized_TyreLife'] = df_train_merged['TyreLife'] / df_train_merged.groupby(
    ['Year', 'Race', 'Driver', 'Stint']
)['TyreLife'].transform('max')

In [50]:
df_test['Normalized_TyreLife'] = df_test['TyreLife'] / df_test.groupby(['Year', 'Race', 'Driver', 'Stint'])['TyreLife'].transform('max')

In [80]:
df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),...,PitNextLap,MaxTireLife,TireRemainingLife,TireAgePct,TireRemainingPct,RaceLaps,LapsRemaining,Prev_Position,LapTimeAvg_3,Normalized_TyreLife
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,...,0.0,40,34.0,0.150000,0.850000,71.0,65.0,12.0,83.921,0.222222
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,...,1.0,55,38.0,0.309091,0.690909,77.0,53.0,6.0,83.845,0.566667
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,...,0.0,40,17.0,0.575000,0.425000,76.0,53.0,9.0,79.239,0.389831
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,...,1.0,55,22.0,0.600000,0.400000,72.0,22.0,14.0,87.076,1.000000
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,...,0.0,55,6.0,0.890909,0.109091,75.0,26.0,12.0,78.328,0.710145

In [ ]:
# df_train_merged["Cumulative_Degradation"] = df_train_merged["Cumulative_Degradation"].fillna(0).astype("int")
# cols = ["LapTimeAvg_3",
# "Cumulative_Degradation",
# "LapTime_Delta",
# "LapTime (s)"]
# df_train_merged[cols] = df_train_merged[cols].round(1)
# df_train_merged["RaceProgress"] = df_train_merged["RaceProgress"].round(2)

In [ ]:
# df_test["Cumulative_Degradation"] = df_test["Cumulative_Degradation"].fillna(0).astype("int")
# cols = ["LapTimeAvg_3",
# "Cumulative_Degradation",
# "LapTime_Delta",
# "LapTime (s)"]
# df_test[cols] = df_test[cols].round(1)
# df_test["RaceProgress"] = df_train_merged["RaceProgress"].round(2)

In [ ]:
# df_train_merged[["LapTimeAvg_3",
# "Cumulative_Degradation",
# "LapTime_Delta",
# "LapTime (s)",
# "RaceProgress"]].head()

,LapTimeAvg_3,Cumulative_Degradation,LapTime_Delta,LapTime (s),RaceProgress
0,83.9,-10,-21.2,83.9,0.08
1,83.8,-33,-22.9,83.8,0.31
2,79.2,-12,0.1,79.2,0.30
3,87.1,-31,-13.9,87.1,0.69
4,78.3,-33,-0.5,78.3,0.65

In [ ]:
# df_train_merged.nunique().sort_values(ascending=False)

LapTime_Delta             1606
LapTime (s)                942
LapTimeAvg_3               914
Driver                     887
Cumulative_Degradation     463
TireAgePct                 130
TireRemainingPct           130
RaceLaps                   123
LapsRemaining              117
RaceProgress               100
TyreLife                    79
LapNumber                   78
TireRemainingLife           55
Prev_Position               50
Position_Change             37
Race                        28
Position                    20
Stint                        8
Compound                     5
MaxTireLife                  5
Year                         4
PitStop                      2
PitNextLap                   2
dtype: int64

In [47]:
df_test.isnull().sum()

Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
MaxTireLife               0
TireRemainingLife         0
TireAgePct                0
TireRemainingPct          0
RaceLaps                  0
LapsRemaining             0
Prev_Position             0
LapTimeAvg_3              0
dtype: int64

In [51]:
from autogluon.tabular import TabularDataset, TabularPredictor
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [52]:
print(df_train.columns)
print(df_train.columns)

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')
Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')

In [53]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [54]:
models = {
    # --- Existing Gradient Boosted Trees ---
    "GBM": [
        {},  # Standard LightGBM
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # ExtraTrees LightGBM
    ],
    "XGB": {},  # XGBoost
    "CAT": {},  # CatBoost

    # --- TOP ADDITION 1: PyTorch Neural Network ---
    "NN_TORCH": {},  # Generates NeuralNetTorch_BAG_L1

    # --- TOP ADDITION 2: Extra Trees (Gini & Entropy) ---
    "XT": [
        {"criterion": "gini", "ag_args": {"name_suffix": "Gini"}},
        {"criterion": "entropy", "ag_args": {"name_suffix": "Entr"}},
    ],
}

In [ ]:
predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc', path='ag_models15').fit(
    train_data=df_train_merged_fe,
    ag_args_fit={"num_gpus": 1},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=1,
    hyperparameters=models,
)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.8.0+cu129
CUDA Version:       12.9
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.60 GB / 15.06 GB (30.5%)
Disk Space Avail:   647.19 GB / 930.47 GB (69.6%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 1,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 1,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 8100s of the 32400s of remaining time (25%).
DyStack: Disabling memory safe fit mode in DyStack because GPUs were detected and num_gpus='auto' (GPUs cannot be used in memory safe fit mode). If you want to use memory safe fit mode, manually set `num_gpus=0`.
Running DyStack sub-fit ...
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\predictor.pkl
Beginning AutoGluon training ... Time limit = 8100s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho"
Train Data Rows:    480395
Train Data Columns: 22
Label Column:       PitNextLap
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4650.35 MB
	Train Data (Original)  Memory Usage: 150.33 MB (3.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			0.2s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			19 features in original data used to generate 19 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int8', 'int')          :  1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int', ['bool']) :  1 | ['PitStop']
	0.9s = Fit runtime
	22 features in original data used to generate 22 features in processed data.
	Train Data (Processed) Memory Usage: 68.26 MB (1.5% of available memory)
Data preprocessing and feature engineering runtime = 0.96s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
	'XGB': [{}],
	'CAT': [{}],
	'NN_TORCH': [{}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini'}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr'}}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\utils\data\y.pkl
AutoGluon will fit 2 stack levels (L1 to L2) ...
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
	ExtraTreesGini_BAG_L1: 	{'criterion': 'gini', 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile'], 'name_suffix': 'Gini', 'model_type': <class 'autogluon.tabular.models.xt.xt_model.XTModel'>, 'priority': 60}, 'ag_args_fit': {'num_gpus': 1}, 'ag_args_ensemble': {'use_child_oof': True}}
	ExtraTreesEntr_BAG_L1: 	{'criterion': 'entropy', 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile'], 'name_suffix': 'Entr', 'model_type': <class 'autogluon.tabular.models.xt.xt_model.XTModel'>, 'priority': 60}, 'ag_args_fit': {'num_gpus': 1}, 'ag_args_ensemble': {'use_child_oof': True}}
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
	NeuralNetTorch_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.tabular_nn.torch.tabular_nn_torch.TabularNeuralNetTorchModel'>, 'priority': 25}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 7 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 5398.01s of the 8099.04s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L1\utils\model_template.pkl
Will use sequential fold fitting strategy because import of ray failed. Reason: ray is required to train folds in parallel for TabularPredictor or HPO for MultiModalPredictor. A quick tip is to install via `pip install "ray>=2.43.0,<2.57.0"`
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283978
[100]	valid_set's binary_logloss: 0.260726
[150]	valid_set's binary_logloss: 0.251852
[200]	valid_set's binary_logloss: 0.246249
[250]	valid_set's binary_logloss: 0.243079
[300]	valid_set's binary_logloss: 0.240699
[350]	valid_set's binary_logloss: 0.238587
[400]	valid_set's binary_logloss: 0.237128
[450]	valid_set's binary_logloss: 0.235646
[500]	valid_set's binary_logloss: 0.234578
[550]	valid_set's binary_logloss: 0.233693
[600]	valid_set's binary_logloss: 0.232974
[650]	valid_set's binary_logloss: 0.232242
[700]	valid_set's binary_logloss: 0.231662
[750]	valid_set's binary_logloss: 0.231113
[800]	valid_set's binary_logloss: 0.230736
[850]	valid_set's binary_logloss: 0.230197
[900]	valid_set's binary_logloss: 0.229975
[950]	valid_set's binary_logloss: 0.229565
[1000]	valid_set's binary_logloss: 0.229264
[1050]	valid_set's binary_logloss: 0.228929
[1100]	valid_set's binary_logloss: 0.228678
[1150]	valid_set's binary_logloss: 0.22847
[1200]	valid_set's binary_logloss: 0.228157
[1250]	valid_set's binary_logloss: 0.228002
[1300]	valid_set's binary_logloss: 0.227908
[1350]	valid_set's binary_logloss: 0.227769
[1400]	valid_set's binary_logloss: 0.227601
[1450]	valid_set's binary_logloss: 0.227489
[1500]	valid_set's binary_logloss: 0.227467
[1550]	valid_set's binary_logloss: 0.227435
[1600]	valid_set's binary_logloss: 0.227334
[1650]	valid_set's binary_logloss: 0.227322
[1700]	valid_set's binary_logloss: 0.227309
[1750]	valid_set's binary_logloss: 0.227286
[1800]	valid_set's binary_logloss: 0.227234
[1850]	valid_set's binary_logloss: 0.227273
[1900]	valid_set's binary_logloss: 0.227296
[1950]	valid_set's binary_logloss: 0.22734
[2000]	valid_set's binary_logloss: 0.227348
[2050]	valid_set's binary_logloss: 0.227285
[2100]	valid_set's binary_logloss: 0.227404
[2150]	valid_set's binary_logloss: 0.227488
[2200]	valid_set's binary_logloss: 0.227583
[2250]	valid_set's binary_logloss: 0.227686
[2300]	valid_set's binary_logloss: 0.22779
[2350]	valid_set's binary_logloss: 0.227854

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283521
[100]	valid_set's binary_logloss: 0.261787
[150]	valid_set's binary_logloss: 0.252812
[200]	valid_set's binary_logloss: 0.247872
[250]	valid_set's binary_logloss: 0.243723
[300]	valid_set's binary_logloss: 0.240709
[350]	valid_set's binary_logloss: 0.238279
[400]	valid_set's binary_logloss: 0.236717
[450]	valid_set's binary_logloss: 0.235286
[500]	valid_set's binary_logloss: 0.234188
[550]	valid_set's binary_logloss: 0.233261
[600]	valid_set's binary_logloss: 0.232232
[650]	valid_set's binary_logloss: 0.231411
[700]	valid_set's binary_logloss: 0.230678
[750]	valid_set's binary_logloss: 0.230063
[800]	valid_set's binary_logloss: 0.229524
[850]	valid_set's binary_logloss: 0.229003
[900]	valid_set's binary_logloss: 0.228463
[950]	valid_set's binary_logloss: 0.227981
[1000]	valid_set's binary_logloss: 0.227657
[1050]	valid_set's binary_logloss: 0.227204
[1100]	valid_set's binary_logloss: 0.226903
[1150]	valid_set's binary_logloss: 0.226738
[1200]	valid_set's binary_logloss: 0.226478
[1250]	valid_set's binary_logloss: 0.226245
[1300]	valid_set's binary_logloss: 0.226147
[1350]	valid_set's binary_logloss: 0.225986
[1400]	valid_set's binary_logloss: 0.225831
[1450]	valid_set's binary_logloss: 0.225638
[1500]	valid_set's binary_logloss: 0.225532
[1550]	valid_set's binary_logloss: 0.225422
[1600]	valid_set's binary_logloss: 0.225246
[1650]	valid_set's binary_logloss: 0.225213
[1700]	valid_set's binary_logloss: 0.22514
[1750]	valid_set's binary_logloss: 0.225111
[1800]	valid_set's binary_logloss: 0.225074
[1850]	valid_set's binary_logloss: 0.224999
[1900]	valid_set's binary_logloss: 0.224933
[1950]	valid_set's binary_logloss: 0.224897
[2000]	valid_set's binary_logloss: 0.224986
[2050]	valid_set's binary_logloss: 0.225008
[2100]	valid_set's binary_logloss: 0.224972
[2150]	valid_set's binary_logloss: 0.225014
[2200]	valid_set's binary_logloss: 0.225093
[2250]	valid_set's binary_logloss: 0.225145
[2300]	valid_set's binary_logloss: 0.225186
[2350]	valid_set's binary_logloss: 0.225235
[2400]	valid_set's binary_logloss: 0.225298
[2450]	valid_set's binary_logloss: 0.225336
[2500]	valid_set's binary_logloss: 0.225335

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.285039
[100]	valid_set's binary_logloss: 0.262537
[150]	valid_set's binary_logloss: 0.253162
[200]	valid_set's binary_logloss: 0.247947
[250]	valid_set's binary_logloss: 0.244521
[300]	valid_set's binary_logloss: 0.241451
[350]	valid_set's binary_logloss: 0.23927
[400]	valid_set's binary_logloss: 0.237742
[450]	valid_set's binary_logloss: 0.236397
[500]	valid_set's binary_logloss: 0.235256
[550]	valid_set's binary_logloss: 0.233991
[600]	valid_set's binary_logloss: 0.233221
[650]	valid_set's binary_logloss: 0.232439
[700]	valid_set's binary_logloss: 0.232043
[750]	valid_set's binary_logloss: 0.231366
[800]	valid_set's binary_logloss: 0.230763
[850]	valid_set's binary_logloss: 0.2304
[900]	valid_set's binary_logloss: 0.229986
[950]	valid_set's binary_logloss: 0.229544
[1000]	valid_set's binary_logloss: 0.229163
[1050]	valid_set's binary_logloss: 0.228865
[1100]	valid_set's binary_logloss: 0.228749
[1150]	valid_set's binary_logloss: 0.228467
[1200]	valid_set's binary_logloss: 0.228275
[1250]	valid_set's binary_logloss: 0.228126
[1300]	valid_set's binary_logloss: 0.227943
[1350]	valid_set's binary_logloss: 0.227816
[1400]	valid_set's binary_logloss: 0.227679
[1450]	valid_set's binary_logloss: 0.227622
[1500]	valid_set's binary_logloss: 0.227554
[1550]	valid_set's binary_logloss: 0.227322
[1600]	valid_set's binary_logloss: 0.227305
[1650]	valid_set's binary_logloss: 0.227294
[1700]	valid_set's binary_logloss: 0.227206
[1750]	valid_set's binary_logloss: 0.227087
[1800]	valid_set's binary_logloss: 0.227082
[1850]	valid_set's binary_logloss: 0.227066
[1900]	valid_set's binary_logloss: 0.227084
[1950]	valid_set's binary_logloss: 0.227007
[2000]	valid_set's binary_logloss: 0.227005
[2050]	valid_set's binary_logloss: 0.22703
[2100]	valid_set's binary_logloss: 0.227114
[2150]	valid_set's binary_logloss: 0.227179
[2200]	valid_set's binary_logloss: 0.22723
[2250]	valid_set's binary_logloss: 0.227312
[2300]	valid_set's binary_logloss: 0.227361
[2350]	valid_set's binary_logloss: 0.227494
[2400]	valid_set's binary_logloss: 0.22746
[2450]	valid_set's binary_logloss: 0.227482
[2500]	valid_set's binary_logloss: 0.227548
[2550]	valid_set's binary_logloss: 0.227617

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284563
[100]	valid_set's binary_logloss: 0.262302
[150]	valid_set's binary_logloss: 0.253135
[200]	valid_set's binary_logloss: 0.248086
[250]	valid_set's binary_logloss: 0.244273
[300]	valid_set's binary_logloss: 0.241621
[350]	valid_set's binary_logloss: 0.239507
[400]	valid_set's binary_logloss: 0.237667
[450]	valid_set's binary_logloss: 0.235953
[500]	valid_set's binary_logloss: 0.234788
[550]	valid_set's binary_logloss: 0.233847
[600]	valid_set's binary_logloss: 0.233074
[650]	valid_set's binary_logloss: 0.232245
[700]	valid_set's binary_logloss: 0.231486
[750]	valid_set's binary_logloss: 0.230918
[800]	valid_set's binary_logloss: 0.230314
[850]	valid_set's binary_logloss: 0.229734
[900]	valid_set's binary_logloss: 0.229203
[950]	valid_set's binary_logloss: 0.228798
[1000]	valid_set's binary_logloss: 0.228507
[1050]	valid_set's binary_logloss: 0.228104
[1100]	valid_set's binary_logloss: 0.22775
[1150]	valid_set's binary_logloss: 0.227543
[1200]	valid_set's binary_logloss: 0.227355
[1250]	valid_set's binary_logloss: 0.227107
[1300]	valid_set's binary_logloss: 0.226971
[1350]	valid_set's binary_logloss: 0.226875
[1400]	valid_set's binary_logloss: 0.226708
[1450]	valid_set's binary_logloss: 0.226602
[1500]	valid_set's binary_logloss: 0.226488
[1550]	valid_set's binary_logloss: 0.226374
[1600]	valid_set's binary_logloss: 0.226321
[1650]	valid_set's binary_logloss: 0.226238
[1700]	valid_set's binary_logloss: 0.226236
[1750]	valid_set's binary_logloss: 0.226199
[1800]	valid_set's binary_logloss: 0.226159
[1850]	valid_set's binary_logloss: 0.22595
[1900]	valid_set's binary_logloss: 0.225995
[1950]	valid_set's binary_logloss: 0.226016
[2000]	valid_set's binary_logloss: 0.226068
[2050]	valid_set's binary_logloss: 0.226055
[2100]	valid_set's binary_logloss: 0.226059
[2150]	valid_set's binary_logloss: 0.226093
[2200]	valid_set's binary_logloss: 0.226078
[2250]	valid_set's binary_logloss: 0.226163
[2300]	valid_set's binary_logloss: 0.226211
[2350]	valid_set's binary_logloss: 0.226334
[2400]	valid_set's binary_logloss: 0.226367

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281116
[100]	valid_set's binary_logloss: 0.258967
[150]	valid_set's binary_logloss: 0.249256
[200]	valid_set's binary_logloss: 0.244272
[250]	valid_set's binary_logloss: 0.240315
[300]	valid_set's binary_logloss: 0.236962
[350]	valid_set's binary_logloss: 0.23486
[400]	valid_set's binary_logloss: 0.233069
[450]	valid_set's binary_logloss: 0.231634
[500]	valid_set's binary_logloss: 0.230595
[550]	valid_set's binary_logloss: 0.229427
[600]	valid_set's binary_logloss: 0.228802
[650]	valid_set's binary_logloss: 0.228066
[700]	valid_set's binary_logloss: 0.227548
[750]	valid_set's binary_logloss: 0.226816
[800]	valid_set's binary_logloss: 0.226129
[850]	valid_set's binary_logloss: 0.225641
[900]	valid_set's binary_logloss: 0.225246
[950]	valid_set's binary_logloss: 0.224872
[1000]	valid_set's binary_logloss: 0.224478
[1050]	valid_set's binary_logloss: 0.224161
[1100]	valid_set's binary_logloss: 0.223828
[1150]	valid_set's binary_logloss: 0.223508
[1200]	valid_set's binary_logloss: 0.223267
[1250]	valid_set's binary_logloss: 0.223049
[1300]	valid_set's binary_logloss: 0.222915
[1350]	valid_set's binary_logloss: 0.222846
[1400]	valid_set's binary_logloss: 0.222808
[1450]	valid_set's binary_logloss: 0.222756
[1500]	valid_set's binary_logloss: 0.222588
[1550]	valid_set's binary_logloss: 0.222547
[1600]	valid_set's binary_logloss: 0.22249
[1650]	valid_set's binary_logloss: 0.222546
[1700]	valid_set's binary_logloss: 0.222628
[1750]	valid_set's binary_logloss: 0.222583
[1800]	valid_set's binary_logloss: 0.222589
[1850]	valid_set's binary_logloss: 0.222679
[1900]	valid_set's binary_logloss: 0.222725
[1950]	valid_set's binary_logloss: 0.222665
[2000]	valid_set's binary_logloss: 0.222653
[2050]	valid_set's binary_logloss: 0.222748

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.285344
[100]	valid_set's binary_logloss: 0.26278
[150]	valid_set's binary_logloss: 0.253738
[200]	valid_set's binary_logloss: 0.248281
[250]	valid_set's binary_logloss: 0.244678
[300]	valid_set's binary_logloss: 0.242365
[350]	valid_set's binary_logloss: 0.240295
[400]	valid_set's binary_logloss: 0.238312
[450]	valid_set's binary_logloss: 0.236711
[500]	valid_set's binary_logloss: 0.235582
[550]	valid_set's binary_logloss: 0.234543
[600]	valid_set's binary_logloss: 0.233771
[650]	valid_set's binary_logloss: 0.233167
[700]	valid_set's binary_logloss: 0.232448
[750]	valid_set's binary_logloss: 0.232022
[800]	valid_set's binary_logloss: 0.231415
[850]	valid_set's binary_logloss: 0.231047
[900]	valid_set's binary_logloss: 0.230588
[950]	valid_set's binary_logloss: 0.230228
[1000]	valid_set's binary_logloss: 0.229817
[1050]	valid_set's binary_logloss: 0.229651
[1100]	valid_set's binary_logloss: 0.229407
[1150]	valid_set's binary_logloss: 0.229215
[1200]	valid_set's binary_logloss: 0.229
[1250]	valid_set's binary_logloss: 0.228852
[1300]	valid_set's binary_logloss: 0.228757
[1350]	valid_set's binary_logloss: 0.228635
[1400]	valid_set's binary_logloss: 0.228519
[1450]	valid_set's binary_logloss: 0.228423
[1500]	valid_set's binary_logloss: 0.228399
[1550]	valid_set's binary_logloss: 0.228337
[1600]	valid_set's binary_logloss: 0.22823
[1650]	valid_set's binary_logloss: 0.228109
[1700]	valid_set's binary_logloss: 0.2281
[1750]	valid_set's binary_logloss: 0.228093
[1800]	valid_set's binary_logloss: 0.22819
[1850]	valid_set's binary_logloss: 0.228168
[1900]	valid_set's binary_logloss: 0.22821
[1950]	valid_set's binary_logloss: 0.228218
[2000]	valid_set's binary_logloss: 0.22816
[2050]	valid_set's binary_logloss: 0.228212
[2100]	valid_set's binary_logloss: 0.228243
[2150]	valid_set's binary_logloss: 0.228278
[2200]	valid_set's binary_logloss: 0.228356
[2250]	valid_set's binary_logloss: 0.228429

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281715
[100]	valid_set's binary_logloss: 0.259393
[150]	valid_set's binary_logloss: 0.250902
[200]	valid_set's binary_logloss: 0.245705
[250]	valid_set's binary_logloss: 0.242024
[300]	valid_set's binary_logloss: 0.239374
[350]	valid_set's binary_logloss: 0.237116
[400]	valid_set's binary_logloss: 0.235387
[450]	valid_set's binary_logloss: 0.234073
[500]	valid_set's binary_logloss: 0.23271
[550]	valid_set's binary_logloss: 0.23147
[600]	valid_set's binary_logloss: 0.230704
[650]	valid_set's binary_logloss: 0.229887
[700]	valid_set's binary_logloss: 0.229306
[750]	valid_set's binary_logloss: 0.228821
[800]	valid_set's binary_logloss: 0.22833
[850]	valid_set's binary_logloss: 0.227856
[900]	valid_set's binary_logloss: 0.227443
[950]	valid_set's binary_logloss: 0.227164
[1000]	valid_set's binary_logloss: 0.22684
[1050]	valid_set's binary_logloss: 0.226596
[1100]	valid_set's binary_logloss: 0.226322
[1150]	valid_set's binary_logloss: 0.226229
[1200]	valid_set's binary_logloss: 0.226065
[1250]	valid_set's binary_logloss: 0.225972
[1300]	valid_set's binary_logloss: 0.225804
[1350]	valid_set's binary_logloss: 0.225674
[1400]	valid_set's binary_logloss: 0.225608
[1450]	valid_set's binary_logloss: 0.225554
[1500]	valid_set's binary_logloss: 0.225506
[1550]	valid_set's binary_logloss: 0.225416
[1600]	valid_set's binary_logloss: 0.225303
[1650]	valid_set's binary_logloss: 0.225172
[1700]	valid_set's binary_logloss: 0.225169
[1750]	valid_set's binary_logloss: 0.225135
[1800]	valid_set's binary_logloss: 0.225117
[1850]	valid_set's binary_logloss: 0.22516
[1900]	valid_set's binary_logloss: 0.22518
[1950]	valid_set's binary_logloss: 0.225185
[2000]	valid_set's binary_logloss: 0.225183
[2050]	valid_set's binary_logloss: 0.225293
[2100]	valid_set's binary_logloss: 0.225326
[2150]	valid_set's binary_logloss: 0.22538

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.2841
[100]	valid_set's binary_logloss: 0.260887
[150]	valid_set's binary_logloss: 0.251756
[200]	valid_set's binary_logloss: 0.246929
[250]	valid_set's binary_logloss: 0.242928
[300]	valid_set's binary_logloss: 0.2404
[350]	valid_set's binary_logloss: 0.238402
[400]	valid_set's binary_logloss: 0.236751
[450]	valid_set's binary_logloss: 0.235494
[500]	valid_set's binary_logloss: 0.234269
[550]	valid_set's binary_logloss: 0.233269
[600]	valid_set's binary_logloss: 0.232403
[650]	valid_set's binary_logloss: 0.231737
[700]	valid_set's binary_logloss: 0.231091
[750]	valid_set's binary_logloss: 0.230582
[800]	valid_set's binary_logloss: 0.230189
[850]	valid_set's binary_logloss: 0.229705
[900]	valid_set's binary_logloss: 0.229332
[950]	valid_set's binary_logloss: 0.228976
[1000]	valid_set's binary_logloss: 0.228722
[1050]	valid_set's binary_logloss: 0.228513
[1100]	valid_set's binary_logloss: 0.228317
[1150]	valid_set's binary_logloss: 0.227935
[1200]	valid_set's binary_logloss: 0.227846
[1250]	valid_set's binary_logloss: 0.227678
[1300]	valid_set's binary_logloss: 0.227468
[1350]	valid_set's binary_logloss: 0.227411
[1400]	valid_set's binary_logloss: 0.227296
[1450]	valid_set's binary_logloss: 0.227198
[1500]	valid_set's binary_logloss: 0.227025
[1550]	valid_set's binary_logloss: 0.22695
[1600]	valid_set's binary_logloss: 0.226826
[1650]	valid_set's binary_logloss: 0.226847
[1700]	valid_set's binary_logloss: 0.22684
[1750]	valid_set's binary_logloss: 0.226846
[1800]	valid_set's binary_logloss: 0.226964
[1850]	valid_set's binary_logloss: 0.226977
[1900]	valid_set's binary_logloss: 0.227021
[1950]	valid_set's binary_logloss: 0.227078
[2000]	valid_set's binary_logloss: 0.227103
[2050]	valid_set's binary_logloss: 0.227212
[2100]	valid_set's binary_logloss: 0.227277

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L1\model.pkl
	0.9509	 = Validation score   (roc_auc)
	80.44s	 = Training   runtime
	4.05s	 = Validation runtime
	14843.4	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 5310.79s of the 8011.81s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.304762
[100]	valid_set's binary_logloss: 0.275488
[150]	valid_set's binary_logloss: 0.263011
[200]	valid_set's binary_logloss: 0.256469
[250]	valid_set's binary_logloss: 0.250995
[300]	valid_set's binary_logloss: 0.247135
[350]	valid_set's binary_logloss: 0.244333
[400]	valid_set's binary_logloss: 0.242176
[450]	valid_set's binary_logloss: 0.240252
[500]	valid_set's binary_logloss: 0.238529
[550]	valid_set's binary_logloss: 0.237155
[600]	valid_set's binary_logloss: 0.235819
[650]	valid_set's binary_logloss: 0.234759
[700]	valid_set's binary_logloss: 0.233771
[750]	valid_set's binary_logloss: 0.232918
[800]	valid_set's binary_logloss: 0.231994
[850]	valid_set's binary_logloss: 0.23126
[900]	valid_set's binary_logloss: 0.230521
[950]	valid_set's binary_logloss: 0.22984
[1000]	valid_set's binary_logloss: 0.229247
[1050]	valid_set's binary_logloss: 0.228685
[1100]	valid_set's binary_logloss: 0.228201
[1150]	valid_set's binary_logloss: 0.227707
[1200]	valid_set's binary_logloss: 0.227317
[1250]	valid_set's binary_logloss: 0.227017
[1300]	valid_set's binary_logloss: 0.226683
[1350]	valid_set's binary_logloss: 0.226441
[1400]	valid_set's binary_logloss: 0.226101
[1450]	valid_set's binary_logloss: 0.225822
[1500]	valid_set's binary_logloss: 0.225534
[1550]	valid_set's binary_logloss: 0.225261
[1600]	valid_set's binary_logloss: 0.225001
[1650]	valid_set's binary_logloss: 0.224873
[1700]	valid_set's binary_logloss: 0.224649
[1750]	valid_set's binary_logloss: 0.224339
[1800]	valid_set's binary_logloss: 0.224191
[1850]	valid_set's binary_logloss: 0.224018
[1900]	valid_set's binary_logloss: 0.223913
[1950]	valid_set's binary_logloss: 0.223774
[2000]	valid_set's binary_logloss: 0.223591
[2050]	valid_set's binary_logloss: 0.223413
[2100]	valid_set's binary_logloss: 0.223269
[2150]	valid_set's binary_logloss: 0.223115
[2200]	valid_set's binary_logloss: 0.222977
[2250]	valid_set's binary_logloss: 0.222846
[2300]	valid_set's binary_logloss: 0.222747
[2350]	valid_set's binary_logloss: 0.222598
[2400]	valid_set's binary_logloss: 0.222503
[2450]	valid_set's binary_logloss: 0.222445
[2500]	valid_set's binary_logloss: 0.222433
[2550]	valid_set's binary_logloss: 0.222319
[2600]	valid_set's binary_logloss: 0.222239
[2650]	valid_set's binary_logloss: 0.222113
[2700]	valid_set's binary_logloss: 0.22201
[2750]	valid_set's binary_logloss: 0.221958
[2800]	valid_set's binary_logloss: 0.221867
[2850]	valid_set's binary_logloss: 0.221762
[2900]	valid_set's binary_logloss: 0.221724
[2950]	valid_set's binary_logloss: 0.221618
[3000]	valid_set's binary_logloss: 0.221595
[3050]	valid_set's binary_logloss: 0.221523
[3100]	valid_set's binary_logloss: 0.221447
[3150]	valid_set's binary_logloss: 0.221463
[3200]	valid_set's binary_logloss: 0.221469
[3250]	valid_set's binary_logloss: 0.221451
[3300]	valid_set's binary_logloss: 0.22143
[3350]	valid_set's binary_logloss: 0.221369
[3400]	valid_set's binary_logloss: 0.221333
[3450]	valid_set's binary_logloss: 0.221247
[3500]	valid_set's binary_logloss: 0.221229
[3550]	valid_set's binary_logloss: 0.22123
[3600]	valid_set's binary_logloss: 0.221207
[3650]	valid_set's binary_logloss: 0.221223
[3700]	valid_set's binary_logloss: 0.221216
[3750]	valid_set's binary_logloss: 0.221239
[3800]	valid_set's binary_logloss: 0.221232
[3850]	valid_set's binary_logloss: 0.221238
[3900]	valid_set's binary_logloss: 0.221318
[3950]	valid_set's binary_logloss: 0.221338
[4000]	valid_set's binary_logloss: 0.221346
[4050]	valid_set's binary_logloss: 0.221356
[4100]	valid_set's binary_logloss: 0.22136
[4150]	valid_set's binary_logloss: 0.221358
[4200]	valid_set's binary_logloss: 0.221379
[4250]	valid_set's binary_logloss: 0.221394
[4300]	valid_set's binary_logloss: 0.221367
[4350]	valid_set's binary_logloss: 0.221347
[4400]	valid_set's binary_logloss: 0.221384
[4450]	valid_set's binary_logloss: 0.221379
[4500]	valid_set's binary_logloss: 0.221437
[4550]	valid_set's binary_logloss: 0.221464
[4600]	valid_set's binary_logloss: 0.221438
[4650]	valid_set's binary_logloss: 0.221417

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.301736
[100]	valid_set's binary_logloss: 0.27589
[150]	valid_set's binary_logloss: 0.26523
[200]	valid_set's binary_logloss: 0.258177
[250]	valid_set's binary_logloss: 0.252901
[300]	valid_set's binary_logloss: 0.249205
[350]	valid_set's binary_logloss: 0.246228
[400]	valid_set's binary_logloss: 0.243649
[450]	valid_set's binary_logloss: 0.241601
[500]	valid_set's binary_logloss: 0.239724
[550]	valid_set's binary_logloss: 0.23827
[600]	valid_set's binary_logloss: 0.236874
[650]	valid_set's binary_logloss: 0.235639
[700]	valid_set's binary_logloss: 0.234653
[750]	valid_set's binary_logloss: 0.23361
[800]	valid_set's binary_logloss: 0.23265
[850]	valid_set's binary_logloss: 0.231938
[900]	valid_set's binary_logloss: 0.23122
[950]	valid_set's binary_logloss: 0.230466
[1000]	valid_set's binary_logloss: 0.229848
[1050]	valid_set's binary_logloss: 0.229336
[1100]	valid_set's binary_logloss: 0.228807
[1150]	valid_set's binary_logloss: 0.228318
[1200]	valid_set's binary_logloss: 0.227857
[1250]	valid_set's binary_logloss: 0.227427
[1300]	valid_set's binary_logloss: 0.227053
[1350]	valid_set's binary_logloss: 0.226641
[1400]	valid_set's binary_logloss: 0.226334
[1450]	valid_set's binary_logloss: 0.225986
[1500]	valid_set's binary_logloss: 0.22572
[1550]	valid_set's binary_logloss: 0.225418
[1600]	valid_set's binary_logloss: 0.225134
[1650]	valid_set's binary_logloss: 0.224896
[1700]	valid_set's binary_logloss: 0.224565
[1750]	valid_set's binary_logloss: 0.224381
[1800]	valid_set's binary_logloss: 0.224107
[1850]	valid_set's binary_logloss: 0.223825
[1900]	valid_set's binary_logloss: 0.223576
[1950]	valid_set's binary_logloss: 0.223401
[2000]	valid_set's binary_logloss: 0.223217
[2050]	valid_set's binary_logloss: 0.223128
[2100]	valid_set's binary_logloss: 0.222933
[2150]	valid_set's binary_logloss: 0.222785
[2200]	valid_set's binary_logloss: 0.222597
[2250]	valid_set's binary_logloss: 0.222438
[2300]	valid_set's binary_logloss: 0.222384
[2350]	valid_set's binary_logloss: 0.222234
[2400]	valid_set's binary_logloss: 0.222084
[2450]	valid_set's binary_logloss: 0.22196
[2500]	valid_set's binary_logloss: 0.221891
[2550]	valid_set's binary_logloss: 0.221802
[2600]	valid_set's binary_logloss: 0.221743
[2650]	valid_set's binary_logloss: 0.221642
[2700]	valid_set's binary_logloss: 0.221582
[2750]	valid_set's binary_logloss: 0.221505
[2800]	valid_set's binary_logloss: 0.221455
[2850]	valid_set's binary_logloss: 0.221381
[2900]	valid_set's binary_logloss: 0.221315
[2950]	valid_set's binary_logloss: 0.221234
[3000]	valid_set's binary_logloss: 0.221192
[3050]	valid_set's binary_logloss: 0.221147
[3100]	valid_set's binary_logloss: 0.221049
[3150]	valid_set's binary_logloss: 0.221003
[3200]	valid_set's binary_logloss: 0.220985
[3250]	valid_set's binary_logloss: 0.220946
[3300]	valid_set's binary_logloss: 0.220912
[3350]	valid_set's binary_logloss: 0.220912
[3400]	valid_set's binary_logloss: 0.220854
[3450]	valid_set's binary_logloss: 0.220811
[3500]	valid_set's binary_logloss: 0.220773
[3550]	valid_set's binary_logloss: 0.22075
[3600]	valid_set's binary_logloss: 0.220738
[3650]	valid_set's binary_logloss: 0.220607
[3700]	valid_set's binary_logloss: 0.22051
[3750]	valid_set's binary_logloss: 0.220463
[3800]	valid_set's binary_logloss: 0.220428
[3850]	valid_set's binary_logloss: 0.220426
[3900]	valid_set's binary_logloss: 0.220417
[3950]	valid_set's binary_logloss: 0.220426
[4000]	valid_set's binary_logloss: 0.220409
[4050]	valid_set's binary_logloss: 0.220377
[4100]	valid_set's binary_logloss: 0.220339
[4150]	valid_set's binary_logloss: 0.220305
[4200]	valid_set's binary_logloss: 0.220307
[4250]	valid_set's binary_logloss: 0.220304
[4300]	valid_set's binary_logloss: 0.220222
[4350]	valid_set's binary_logloss: 0.220177
[4400]	valid_set's binary_logloss: 0.220191
[4450]	valid_set's binary_logloss: 0.220222
[4500]	valid_set's binary_logloss: 0.220256
[4550]	valid_set's binary_logloss: 0.220292
[4600]	valid_set's binary_logloss: 0.220296
[4650]	valid_set's binary_logloss: 0.220324
[4700]	valid_set's binary_logloss: 0.220283
[4750]	valid_set's binary_logloss: 0.220283
[4800]	valid_set's binary_logloss: 0.220274
[4850]	valid_set's binary_logloss: 0.220318
[4900]	valid_set's binary_logloss: 0.220357
[4950]	valid_set's binary_logloss: 0.220419
[5000]	valid_set's binary_logloss: 0.220452
[5050]	valid_set's binary_logloss: 0.220495
[5100]	valid_set's binary_logloss: 0.22051
[5150]	valid_set's binary_logloss: 0.220549
[5200]	valid_set's binary_logloss: 0.220538
[5250]	valid_set's binary_logloss: 0.220551
[5300]	valid_set's binary_logloss: 0.220591
[5350]	valid_set's binary_logloss: 0.220607
[5400]	valid_set's binary_logloss: 0.220612
[5450]	valid_set's binary_logloss: 0.220654
[5500]	valid_set's binary_logloss: 0.220698
[5550]	valid_set's binary_logloss: 0.220766
[5600]	valid_set's binary_logloss: 0.220793
[5650]	valid_set's binary_logloss: 0.220839

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.304049
[100]	valid_set's binary_logloss: 0.275731
[150]	valid_set's binary_logloss: 0.264153
[200]	valid_set's binary_logloss: 0.257707
[250]	valid_set's binary_logloss: 0.253064
[300]	valid_set's binary_logloss: 0.249433
[350]	valid_set's binary_logloss: 0.246419
[400]	valid_set's binary_logloss: 0.243972
[450]	valid_set's binary_logloss: 0.241796
[500]	valid_set's binary_logloss: 0.239932
[550]	valid_set's binary_logloss: 0.238422
[600]	valid_set's binary_logloss: 0.236979
[650]	valid_set's binary_logloss: 0.235789
[700]	valid_set's binary_logloss: 0.234799
[750]	valid_set's binary_logloss: 0.233865
[800]	valid_set's binary_logloss: 0.233033
[850]	valid_set's binary_logloss: 0.232318
[900]	valid_set's binary_logloss: 0.231684
[950]	valid_set's binary_logloss: 0.230895
[1000]	valid_set's binary_logloss: 0.23013
[1050]	valid_set's binary_logloss: 0.22957
[1100]	valid_set's binary_logloss: 0.229012
[1150]	valid_set's binary_logloss: 0.22859
[1200]	valid_set's binary_logloss: 0.228261
[1250]	valid_set's binary_logloss: 0.227822
[1300]	valid_set's binary_logloss: 0.22746
[1350]	valid_set's binary_logloss: 0.227065
[1400]	valid_set's binary_logloss: 0.226753
[1450]	valid_set's binary_logloss: 0.226357
[1500]	valid_set's binary_logloss: 0.226073
[1550]	valid_set's binary_logloss: 0.225855
[1600]	valid_set's binary_logloss: 0.225602
[1650]	valid_set's binary_logloss: 0.225372
[1700]	valid_set's binary_logloss: 0.225132
[1750]	valid_set's binary_logloss: 0.2249
[1800]	valid_set's binary_logloss: 0.224768
[1850]	valid_set's binary_logloss: 0.224516
[1900]	valid_set's binary_logloss: 0.224332
[1950]	valid_set's binary_logloss: 0.224218
[2000]	valid_set's binary_logloss: 0.224075
[2050]	valid_set's binary_logloss: 0.223885
[2100]	valid_set's binary_logloss: 0.223772
[2150]	valid_set's binary_logloss: 0.223608
[2200]	valid_set's binary_logloss: 0.223449
[2250]	valid_set's binary_logloss: 0.223289
[2300]	valid_set's binary_logloss: 0.223219
[2350]	valid_set's binary_logloss: 0.22316
[2400]	valid_set's binary_logloss: 0.223097
[2450]	valid_set's binary_logloss: 0.223017
[2500]	valid_set's binary_logloss: 0.222919
[2550]	valid_set's binary_logloss: 0.222887
[2600]	valid_set's binary_logloss: 0.222806
[2650]	valid_set's binary_logloss: 0.222696
[2700]	valid_set's binary_logloss: 0.222578
[2750]	valid_set's binary_logloss: 0.222452
[2800]	valid_set's binary_logloss: 0.222383
[2850]	valid_set's binary_logloss: 0.222285
[2900]	valid_set's binary_logloss: 0.222267
[2950]	valid_set's binary_logloss: 0.222204
[3000]	valid_set's binary_logloss: 0.222136
[3050]	valid_set's binary_logloss: 0.222115
[3100]	valid_set's binary_logloss: 0.222039
[3150]	valid_set's binary_logloss: 0.221983
[3200]	valid_set's binary_logloss: 0.221904
[3250]	valid_set's binary_logloss: 0.221844
[3300]	valid_set's binary_logloss: 0.221791
[3350]	valid_set's binary_logloss: 0.221757
[3400]	valid_set's binary_logloss: 0.221721
[3450]	valid_set's binary_logloss: 0.22166
[3500]	valid_set's binary_logloss: 0.221579
[3550]	valid_set's binary_logloss: 0.221523
[3600]	valid_set's binary_logloss: 0.221496
[3650]	valid_set's binary_logloss: 0.221448
[3700]	valid_set's binary_logloss: 0.221414
[3750]	valid_set's binary_logloss: 0.221342
[3800]	valid_set's binary_logloss: 0.221339
[3850]	valid_set's binary_logloss: 0.221343
[3900]	valid_set's binary_logloss: 0.221302
[3950]	valid_set's binary_logloss: 0.22126
[4000]	valid_set's binary_logloss: 0.221249
[4050]	valid_set's binary_logloss: 0.221252
[4100]	valid_set's binary_logloss: 0.221223
[4150]	valid_set's binary_logloss: 0.221256
[4200]	valid_set's binary_logloss: 0.221201
[4250]	valid_set's binary_logloss: 0.221208
[4300]	valid_set's binary_logloss: 0.22122
[4350]	valid_set's binary_logloss: 0.221245
[4400]	valid_set's binary_logloss: 0.221243
[4450]	valid_set's binary_logloss: 0.221248
[4500]	valid_set's binary_logloss: 0.221251
[4550]	valid_set's binary_logloss: 0.221205
[4600]	valid_set's binary_logloss: 0.221226
[4650]	valid_set's binary_logloss: 0.221227
[4700]	valid_set's binary_logloss: 0.221202
[4750]	valid_set's binary_logloss: 0.221267
[4800]	valid_set's binary_logloss: 0.221272
[4850]	valid_set's binary_logloss: 0.221286
[4900]	valid_set's binary_logloss: 0.221355
[4950]	valid_set's binary_logloss: 0.221364
[5000]	valid_set's binary_logloss: 0.221394
[5050]	valid_set's binary_logloss: 0.22144
[5100]	valid_set's binary_logloss: 0.221424
[5150]	valid_set's binary_logloss: 0.221443
[5200]	valid_set's binary_logloss: 0.221442
[5250]	valid_set's binary_logloss: 0.221491
[5300]	valid_set's binary_logloss: 0.22155
[5350]	valid_set's binary_logloss: 0.221524
[5400]	valid_set's binary_logloss: 0.221532
[5450]	valid_set's binary_logloss: 0.221584

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.306519
[100]	valid_set's binary_logloss: 0.276549
[150]	valid_set's binary_logloss: 0.264159
[200]	valid_set's binary_logloss: 0.257489
[250]	valid_set's binary_logloss: 0.252494
[300]	valid_set's binary_logloss: 0.249172
[350]	valid_set's binary_logloss: 0.246116
[400]	valid_set's binary_logloss: 0.243739
[450]	valid_set's binary_logloss: 0.241651
[500]	valid_set's binary_logloss: 0.239632
[550]	valid_set's binary_logloss: 0.238089
[600]	valid_set's binary_logloss: 0.236472
[650]	valid_set's binary_logloss: 0.235293
[700]	valid_set's binary_logloss: 0.234237
[750]	valid_set's binary_logloss: 0.233325
[800]	valid_set's binary_logloss: 0.232464
[850]	valid_set's binary_logloss: 0.231797
[900]	valid_set's binary_logloss: 0.230969
[950]	valid_set's binary_logloss: 0.230276
[1000]	valid_set's binary_logloss: 0.229672
[1050]	valid_set's binary_logloss: 0.229115
[1100]	valid_set's binary_logloss: 0.228544
[1150]	valid_set's binary_logloss: 0.228012
[1200]	valid_set's binary_logloss: 0.227572
[1250]	valid_set's binary_logloss: 0.227163
[1300]	valid_set's binary_logloss: 0.226748
[1350]	valid_set's binary_logloss: 0.226327
[1400]	valid_set's binary_logloss: 0.225973
[1450]	valid_set's binary_logloss: 0.225584
[1500]	valid_set's binary_logloss: 0.225236
[1550]	valid_set's binary_logloss: 0.22501
[1600]	valid_set's binary_logloss: 0.224775
[1650]	valid_set's binary_logloss: 0.224452
[1700]	valid_set's binary_logloss: 0.224241
[1750]	valid_set's binary_logloss: 0.224009
[1800]	valid_set's binary_logloss: 0.223832
[1850]	valid_set's binary_logloss: 0.223638
[1900]	valid_set's binary_logloss: 0.22347
[1950]	valid_set's binary_logloss: 0.22319
[2000]	valid_set's binary_logloss: 0.222983
[2050]	valid_set's binary_logloss: 0.222856
[2100]	valid_set's binary_logloss: 0.222744
[2150]	valid_set's binary_logloss: 0.222591
[2200]	valid_set's binary_logloss: 0.222421
[2250]	valid_set's binary_logloss: 0.222355
[2300]	valid_set's binary_logloss: 0.222277
[2350]	valid_set's binary_logloss: 0.222167
[2400]	valid_set's binary_logloss: 0.222085
[2450]	valid_set's binary_logloss: 0.221882
[2500]	valid_set's binary_logloss: 0.221809
[2550]	valid_set's binary_logloss: 0.221683
[2600]	valid_set's binary_logloss: 0.221545
[2650]	valid_set's binary_logloss: 0.221473
[2700]	valid_set's binary_logloss: 0.221385
[2750]	valid_set's binary_logloss: 0.221261
[2800]	valid_set's binary_logloss: 0.221183
[2850]	valid_set's binary_logloss: 0.221027
[2900]	valid_set's binary_logloss: 0.220924
[2950]	valid_set's binary_logloss: 0.22084
[3000]	valid_set's binary_logloss: 0.220711
[3050]	valid_set's binary_logloss: 0.220585
[3100]	valid_set's binary_logloss: 0.220457
[3150]	valid_set's binary_logloss: 0.220413
[3200]	valid_set's binary_logloss: 0.220392
[3250]	valid_set's binary_logloss: 0.220345
[3300]	valid_set's binary_logloss: 0.220312
[3350]	valid_set's binary_logloss: 0.22029
[3400]	valid_set's binary_logloss: 0.220291
[3450]	valid_set's binary_logloss: 0.220291
[3500]	valid_set's binary_logloss: 0.220279
[3550]	valid_set's binary_logloss: 0.220244
[3600]	valid_set's binary_logloss: 0.220256
[3650]	valid_set's binary_logloss: 0.220223
[3700]	valid_set's binary_logloss: 0.220216
[3750]	valid_set's binary_logloss: 0.220152
[3800]	valid_set's binary_logloss: 0.220161
[3850]	valid_set's binary_logloss: 0.220092
[3900]	valid_set's binary_logloss: 0.220028
[3950]	valid_set's binary_logloss: 0.220025
[4000]	valid_set's binary_logloss: 0.219978
[4050]	valid_set's binary_logloss: 0.219975
[4100]	valid_set's binary_logloss: 0.219997
[4150]	valid_set's binary_logloss: 0.219941
[4200]	valid_set's binary_logloss: 0.219928
[4250]	valid_set's binary_logloss: 0.219952
[4300]	valid_set's binary_logloss: 0.21995
[4350]	valid_set's binary_logloss: 0.219928
[4400]	valid_set's binary_logloss: 0.219936
[4450]	valid_set's binary_logloss: 0.219954
[4500]	valid_set's binary_logloss: 0.220008
[4550]	valid_set's binary_logloss: 0.220018
[4600]	valid_set's binary_logloss: 0.220012
[4650]	valid_set's binary_logloss: 0.220035
[4700]	valid_set's binary_logloss: 0.220044
[4750]	valid_set's binary_logloss: 0.22003
[4800]	valid_set's binary_logloss: 0.22005
[4850]	valid_set's binary_logloss: 0.220104
[4900]	valid_set's binary_logloss: 0.220083
[4950]	valid_set's binary_logloss: 0.220123
[5000]	valid_set's binary_logloss: 0.220069
[5050]	valid_set's binary_logloss: 0.220058
[5100]	valid_set's binary_logloss: 0.220049
[5150]	valid_set's binary_logloss: 0.220029
[5200]	valid_set's binary_logloss: 0.220038
[5250]	valid_set's binary_logloss: 0.22007
[5300]	valid_set's binary_logloss: 0.220117
[5350]	valid_set's binary_logloss: 0.220102
[5400]	valid_set's binary_logloss: 0.220133
[5450]	valid_set's binary_logloss: 0.220151

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303122
[100]	valid_set's binary_logloss: 0.273151
[150]	valid_set's binary_logloss: 0.261371
[200]	valid_set's binary_logloss: 0.254284
[250]	valid_set's binary_logloss: 0.249442
[300]	valid_set's binary_logloss: 0.245495
[350]	valid_set's binary_logloss: 0.242329
[400]	valid_set's binary_logloss: 0.239849
[450]	valid_set's binary_logloss: 0.237614
[500]	valid_set's binary_logloss: 0.235647
[550]	valid_set's binary_logloss: 0.234015
[600]	valid_set's binary_logloss: 0.232553
[650]	valid_set's binary_logloss: 0.231304
[700]	valid_set's binary_logloss: 0.229916
[750]	valid_set's binary_logloss: 0.228866
[800]	valid_set's binary_logloss: 0.228107
[850]	valid_set's binary_logloss: 0.227248
[900]	valid_set's binary_logloss: 0.226509
[950]	valid_set's binary_logloss: 0.22596
[1000]	valid_set's binary_logloss: 0.225256
[1050]	valid_set's binary_logloss: 0.224671
[1100]	valid_set's binary_logloss: 0.224118
[1150]	valid_set's binary_logloss: 0.223536
[1200]	valid_set's binary_logloss: 0.223105
[1250]	valid_set's binary_logloss: 0.222632
[1300]	valid_set's binary_logloss: 0.222235
[1350]	valid_set's binary_logloss: 0.221813
[1400]	valid_set's binary_logloss: 0.221566
[1450]	valid_set's binary_logloss: 0.221248
[1500]	valid_set's binary_logloss: 0.220873
[1550]	valid_set's binary_logloss: 0.2206
[1600]	valid_set's binary_logloss: 0.220337
[1650]	valid_set's binary_logloss: 0.220063
[1700]	valid_set's binary_logloss: 0.219849
[1750]	valid_set's binary_logloss: 0.21967
[1800]	valid_set's binary_logloss: 0.219518
[1850]	valid_set's binary_logloss: 0.219298
[1900]	valid_set's binary_logloss: 0.21905
[1950]	valid_set's binary_logloss: 0.218849
[2000]	valid_set's binary_logloss: 0.218744
[2050]	valid_set's binary_logloss: 0.218612
[2100]	valid_set's binary_logloss: 0.218471
[2150]	valid_set's binary_logloss: 0.21829
[2200]	valid_set's binary_logloss: 0.218147
[2250]	valid_set's binary_logloss: 0.218034
[2300]	valid_set's binary_logloss: 0.217869
[2350]	valid_set's binary_logloss: 0.217768
[2400]	valid_set's binary_logloss: 0.217632
[2450]	valid_set's binary_logloss: 0.217544
[2500]	valid_set's binary_logloss: 0.217463
[2550]	valid_set's binary_logloss: 0.21742
[2600]	valid_set's binary_logloss: 0.21739
[2650]	valid_set's binary_logloss: 0.217287
[2700]	valid_set's binary_logloss: 0.217192
[2750]	valid_set's binary_logloss: 0.217132
[2800]	valid_set's binary_logloss: 0.217094
[2850]	valid_set's binary_logloss: 0.217056
[2900]	valid_set's binary_logloss: 0.216942
[2950]	valid_set's binary_logloss: 0.2169
[3000]	valid_set's binary_logloss: 0.216821
[3050]	valid_set's binary_logloss: 0.216761
[3100]	valid_set's binary_logloss: 0.216765
[3150]	valid_set's binary_logloss: 0.216692
[3200]	valid_set's binary_logloss: 0.216707
[3250]	valid_set's binary_logloss: 0.216652
[3300]	valid_set's binary_logloss: 0.216581
[3350]	valid_set's binary_logloss: 0.21652
[3400]	valid_set's binary_logloss: 0.216526
[3450]	valid_set's binary_logloss: 0.216507
[3500]	valid_set's binary_logloss: 0.216462
[3550]	valid_set's binary_logloss: 0.216403
[3600]	valid_set's binary_logloss: 0.216402
[3650]	valid_set's binary_logloss: 0.216395
[3700]	valid_set's binary_logloss: 0.216357
[3750]	valid_set's binary_logloss: 0.216288
[3800]	valid_set's binary_logloss: 0.216258
[3850]	valid_set's binary_logloss: 0.216264
[3900]	valid_set's binary_logloss: 0.216274
[3950]	valid_set's binary_logloss: 0.216295
[4000]	valid_set's binary_logloss: 0.216282
[4050]	valid_set's binary_logloss: 0.216287
[4100]	valid_set's binary_logloss: 0.216262
[4150]	valid_set's binary_logloss: 0.216262
[4200]	valid_set's binary_logloss: 0.216245
[4250]	valid_set's binary_logloss: 0.216264
[4300]	valid_set's binary_logloss: 0.21623
[4350]	valid_set's binary_logloss: 0.216257
[4400]	valid_set's binary_logloss: 0.21627
[4450]	valid_set's binary_logloss: 0.216269
[4500]	valid_set's binary_logloss: 0.216191
[4550]	valid_set's binary_logloss: 0.216234
[4600]	valid_set's binary_logloss: 0.216186
[4650]	valid_set's binary_logloss: 0.216175
[4700]	valid_set's binary_logloss: 0.216222
[4750]	valid_set's binary_logloss: 0.21624
[4800]	valid_set's binary_logloss: 0.216254
[4850]	valid_set's binary_logloss: 0.216302
[4900]	valid_set's binary_logloss: 0.216368
[4950]	valid_set's binary_logloss: 0.216429
[5000]	valid_set's binary_logloss: 0.216432
[5050]	valid_set's binary_logloss: 0.216476
[5100]	valid_set's binary_logloss: 0.216517
[5150]	valid_set's binary_logloss: 0.216535
[5200]	valid_set's binary_logloss: 0.216517
[5250]	valid_set's binary_logloss: 0.216583
[5300]	valid_set's binary_logloss: 0.216552
[5350]	valid_set's binary_logloss: 0.216572
[5400]	valid_set's binary_logloss: 0.216659
[5450]	valid_set's binary_logloss: 0.216683
[5500]	valid_set's binary_logloss: 0.216707
[5550]	valid_set's binary_logloss: 0.216789
[5600]	valid_set's binary_logloss: 0.21684
[5650]	valid_set's binary_logloss: 0.216909
[5700]	valid_set's binary_logloss: 0.216936
[5750]	valid_set's binary_logloss: 0.216972
[5800]	valid_set's binary_logloss: 0.217015
[5850]	valid_set's binary_logloss: 0.217058
[5900]	valid_set's binary_logloss: 0.217071
[5950]	valid_set's binary_logloss: 0.217095
[6000]	valid_set's binary_logloss: 0.217125
[6050]	valid_set's binary_logloss: 0.217171

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.30876
[100]	valid_set's binary_logloss: 0.278011
[150]	valid_set's binary_logloss: 0.266028
[200]	valid_set's binary_logloss: 0.258537
[250]	valid_set's binary_logloss: 0.25359
[300]	valid_set's binary_logloss: 0.249778
[350]	valid_set's binary_logloss: 0.246771
[400]	valid_set's binary_logloss: 0.244529
[450]	valid_set's binary_logloss: 0.242527
[500]	valid_set's binary_logloss: 0.240637
[550]	valid_set's binary_logloss: 0.239102
[600]	valid_set's binary_logloss: 0.237751
[650]	valid_set's binary_logloss: 0.236641
[700]	valid_set's binary_logloss: 0.235451
[750]	valid_set's binary_logloss: 0.234481
[800]	valid_set's binary_logloss: 0.233653
[850]	valid_set's binary_logloss: 0.232998
[900]	valid_set's binary_logloss: 0.232251
[950]	valid_set's binary_logloss: 0.231637
[1000]	valid_set's binary_logloss: 0.231108
[1050]	valid_set's binary_logloss: 0.230527
[1100]	valid_set's binary_logloss: 0.230113
[1150]	valid_set's binary_logloss: 0.229655
[1200]	valid_set's binary_logloss: 0.229135
[1250]	valid_set's binary_logloss: 0.228686
[1300]	valid_set's binary_logloss: 0.228314
[1350]	valid_set's binary_logloss: 0.227929
[1400]	valid_set's binary_logloss: 0.227627
[1450]	valid_set's binary_logloss: 0.227251
[1500]	valid_set's binary_logloss: 0.226948
[1550]	valid_set's binary_logloss: 0.226615
[1600]	valid_set's binary_logloss: 0.226264
[1650]	valid_set's binary_logloss: 0.226047
[1700]	valid_set's binary_logloss: 0.22584
[1750]	valid_set's binary_logloss: 0.225634
[1800]	valid_set's binary_logloss: 0.225442
[1850]	valid_set's binary_logloss: 0.22521
[1900]	valid_set's binary_logloss: 0.22508
[1950]	valid_set's binary_logloss: 0.22498
[2000]	valid_set's binary_logloss: 0.224824
[2050]	valid_set's binary_logloss: 0.224725
[2100]	valid_set's binary_logloss: 0.224681
[2150]	valid_set's binary_logloss: 0.22456
[2200]	valid_set's binary_logloss: 0.224432
[2250]	valid_set's binary_logloss: 0.22437
[2300]	valid_set's binary_logloss: 0.224265
[2350]	valid_set's binary_logloss: 0.224215
[2400]	valid_set's binary_logloss: 0.224122
[2450]	valid_set's binary_logloss: 0.224027
[2500]	valid_set's binary_logloss: 0.22393
[2550]	valid_set's binary_logloss: 0.223794
[2600]	valid_set's binary_logloss: 0.223703
[2650]	valid_set's binary_logloss: 0.223592
[2700]	valid_set's binary_logloss: 0.223572
[2750]	valid_set's binary_logloss: 0.223482
[2800]	valid_set's binary_logloss: 0.223467
[2850]	valid_set's binary_logloss: 0.22339
[2900]	valid_set's binary_logloss: 0.223361
[2950]	valid_set's binary_logloss: 0.223266
[3000]	valid_set's binary_logloss: 0.223199
[3050]	valid_set's binary_logloss: 0.223072
[3100]	valid_set's binary_logloss: 0.222976
[3150]	valid_set's binary_logloss: 0.222957
[3200]	valid_set's binary_logloss: 0.222915
[3250]	valid_set's binary_logloss: 0.222901
[3300]	valid_set's binary_logloss: 0.222918
[3350]	valid_set's binary_logloss: 0.222897
[3400]	valid_set's binary_logloss: 0.222874
[3450]	valid_set's binary_logloss: 0.222862
[3500]	valid_set's binary_logloss: 0.222808
[3550]	valid_set's binary_logloss: 0.222764
[3600]	valid_set's binary_logloss: 0.222776
[3650]	valid_set's binary_logloss: 0.222799
[3700]	valid_set's binary_logloss: 0.222795
[3750]	valid_set's binary_logloss: 0.222816
[3800]	valid_set's binary_logloss: 0.222784
[3850]	valid_set's binary_logloss: 0.222832
[3900]	valid_set's binary_logloss: 0.222835
[3950]	valid_set's binary_logloss: 0.222849
[4000]	valid_set's binary_logloss: 0.222814
[4050]	valid_set's binary_logloss: 0.222803
[4100]	valid_set's binary_logloss: 0.222814
[4150]	valid_set's binary_logloss: 0.222853
[4200]	valid_set's binary_logloss: 0.222826
[4250]	valid_set's binary_logloss: 0.222839
[4300]	valid_set's binary_logloss: 0.222869
[4350]	valid_set's binary_logloss: 0.222831
[4400]	valid_set's binary_logloss: 0.222822
[4450]	valid_set's binary_logloss: 0.222839
[4500]	valid_set's binary_logloss: 0.222881
[4550]	valid_set's binary_logloss: 0.222862
[4600]	valid_set's binary_logloss: 0.222896
[4650]	valid_set's binary_logloss: 0.222926

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303065
[100]	valid_set's binary_logloss: 0.274138
[150]	valid_set's binary_logloss: 0.262368
[200]	valid_set's binary_logloss: 0.255761
[250]	valid_set's binary_logloss: 0.251073
[300]	valid_set's binary_logloss: 0.247572
[350]	valid_set's binary_logloss: 0.244582
[400]	valid_set's binary_logloss: 0.242114
[450]	valid_set's binary_logloss: 0.240174
[500]	valid_set's binary_logloss: 0.238454
[550]	valid_set's binary_logloss: 0.237022
[600]	valid_set's binary_logloss: 0.235506
[650]	valid_set's binary_logloss: 0.234305
[700]	valid_set's binary_logloss: 0.233134
[750]	valid_set's binary_logloss: 0.232192
[800]	valid_set's binary_logloss: 0.231293
[850]	valid_set's binary_logloss: 0.230636
[900]	valid_set's binary_logloss: 0.230092
[950]	valid_set's binary_logloss: 0.229481
[1000]	valid_set's binary_logloss: 0.228881
[1050]	valid_set's binary_logloss: 0.228376
[1100]	valid_set's binary_logloss: 0.227673
[1150]	valid_set's binary_logloss: 0.227211
[1200]	valid_set's binary_logloss: 0.226782
[1250]	valid_set's binary_logloss: 0.22631
[1300]	valid_set's binary_logloss: 0.225906
[1350]	valid_set's binary_logloss: 0.225554
[1400]	valid_set's binary_logloss: 0.225182
[1450]	valid_set's binary_logloss: 0.224849
[1500]	valid_set's binary_logloss: 0.224509
[1550]	valid_set's binary_logloss: 0.224227
[1600]	valid_set's binary_logloss: 0.223958
[1650]	valid_set's binary_logloss: 0.223786
[1700]	valid_set's binary_logloss: 0.223593
[1750]	valid_set's binary_logloss: 0.223276
[1800]	valid_set's binary_logloss: 0.223069
[1850]	valid_set's binary_logloss: 0.222921
[1900]	valid_set's binary_logloss: 0.222749
[1950]	valid_set's binary_logloss: 0.222561
[2000]	valid_set's binary_logloss: 0.222348
[2050]	valid_set's binary_logloss: 0.222222
[2100]	valid_set's binary_logloss: 0.222033
[2150]	valid_set's binary_logloss: 0.221888
[2200]	valid_set's binary_logloss: 0.221681
[2250]	valid_set's binary_logloss: 0.221512
[2300]	valid_set's binary_logloss: 0.221456
[2350]	valid_set's binary_logloss: 0.221403
[2400]	valid_set's binary_logloss: 0.221267
[2450]	valid_set's binary_logloss: 0.221146
[2500]	valid_set's binary_logloss: 0.221078
[2550]	valid_set's binary_logloss: 0.220965
[2600]	valid_set's binary_logloss: 0.220873
[2650]	valid_set's binary_logloss: 0.220796
[2700]	valid_set's binary_logloss: 0.22077
[2750]	valid_set's binary_logloss: 0.220672
[2800]	valid_set's binary_logloss: 0.220596
[2850]	valid_set's binary_logloss: 0.220569
[2900]	valid_set's binary_logloss: 0.220496
[2950]	valid_set's binary_logloss: 0.220442
[3000]	valid_set's binary_logloss: 0.220333
[3050]	valid_set's binary_logloss: 0.220291
[3100]	valid_set's binary_logloss: 0.220271
[3150]	valid_set's binary_logloss: 0.220283
[3200]	valid_set's binary_logloss: 0.22024
[3250]	valid_set's binary_logloss: 0.220212
[3300]	valid_set's binary_logloss: 0.220175
[3350]	valid_set's binary_logloss: 0.220127
[3400]	valid_set's binary_logloss: 0.220143
[3450]	valid_set's binary_logloss: 0.220149
[3500]	valid_set's binary_logloss: 0.220138
[3550]	valid_set's binary_logloss: 0.220061
[3600]	valid_set's binary_logloss: 0.220089
[3650]	valid_set's binary_logloss: 0.220071
[3700]	valid_set's binary_logloss: 0.220048
[3750]	valid_set's binary_logloss: 0.220098
[3800]	valid_set's binary_logloss: 0.220099
[3850]	valid_set's binary_logloss: 0.220077
[3900]	valid_set's binary_logloss: 0.220098
[3950]	valid_set's binary_logloss: 0.220097
[4000]	valid_set's binary_logloss: 0.220101
[4050]	valid_set's binary_logloss: 0.220104
[4100]	valid_set's binary_logloss: 0.22002
[4150]	valid_set's binary_logloss: 0.220021
[4200]	valid_set's binary_logloss: 0.219991
[4250]	valid_set's binary_logloss: 0.220039
[4300]	valid_set's binary_logloss: 0.220055
[4350]	valid_set's binary_logloss: 0.220076
[4400]	valid_set's binary_logloss: 0.220126
[4450]	valid_set's binary_logloss: 0.22012
[4500]	valid_set's binary_logloss: 0.220196
[4550]	valid_set's binary_logloss: 0.220196
[4600]	valid_set's binary_logloss: 0.220229
[4650]	valid_set's binary_logloss: 0.220187
[4700]	valid_set's binary_logloss: 0.220184
[4750]	valid_set's binary_logloss: 0.220208
[4800]	valid_set's binary_logloss: 0.220241
[4850]	valid_set's binary_logloss: 0.220241
[4900]	valid_set's binary_logloss: 0.220259
[4950]	valid_set's binary_logloss: 0.220274
[5000]	valid_set's binary_logloss: 0.22028
[5050]	valid_set's binary_logloss: 0.220288
[5100]	valid_set's binary_logloss: 0.220336
[5150]	valid_set's binary_logloss: 0.220346
[5200]	valid_set's binary_logloss: 0.220393
[5250]	valid_set's binary_logloss: 0.220379
[5300]	valid_set's binary_logloss: 0.220408
[5350]	valid_set's binary_logloss: 0.220463
[5400]	valid_set's binary_logloss: 0.220514
[5450]	valid_set's binary_logloss: 0.220587

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.304604
[100]	valid_set's binary_logloss: 0.276497
[150]	valid_set's binary_logloss: 0.264353
[200]	valid_set's binary_logloss: 0.258004
[250]	valid_set's binary_logloss: 0.253248
[300]	valid_set's binary_logloss: 0.249259
[350]	valid_set's binary_logloss: 0.246037
[400]	valid_set's binary_logloss: 0.243624
[450]	valid_set's binary_logloss: 0.241561
[500]	valid_set's binary_logloss: 0.239712
[550]	valid_set's binary_logloss: 0.238246
[600]	valid_set's binary_logloss: 0.236855
[650]	valid_set's binary_logloss: 0.235465
[700]	valid_set's binary_logloss: 0.234465
[750]	valid_set's binary_logloss: 0.233598
[800]	valid_set's binary_logloss: 0.232811
[850]	valid_set's binary_logloss: 0.232006
[900]	valid_set's binary_logloss: 0.231424
[950]	valid_set's binary_logloss: 0.230899
[1000]	valid_set's binary_logloss: 0.230304
[1050]	valid_set's binary_logloss: 0.229663
[1100]	valid_set's binary_logloss: 0.229127
[1150]	valid_set's binary_logloss: 0.228622
[1200]	valid_set's binary_logloss: 0.228209
[1250]	valid_set's binary_logloss: 0.227886
[1300]	valid_set's binary_logloss: 0.227522
[1350]	valid_set's binary_logloss: 0.227233
[1400]	valid_set's binary_logloss: 0.226893
[1450]	valid_set's binary_logloss: 0.22655
[1500]	valid_set's binary_logloss: 0.22632
[1550]	valid_set's binary_logloss: 0.226068
[1600]	valid_set's binary_logloss: 0.22585
[1650]	valid_set's binary_logloss: 0.225561
[1700]	valid_set's binary_logloss: 0.225265
[1750]	valid_set's binary_logloss: 0.224986
[1800]	valid_set's binary_logloss: 0.224776
[1850]	valid_set's binary_logloss: 0.224494
[1900]	valid_set's binary_logloss: 0.224271
[1950]	valid_set's binary_logloss: 0.224097
[2000]	valid_set's binary_logloss: 0.223952
[2050]	valid_set's binary_logloss: 0.22371
[2100]	valid_set's binary_logloss: 0.223513
[2150]	valid_set's binary_logloss: 0.223337
[2200]	valid_set's binary_logloss: 0.223223
[2250]	valid_set's binary_logloss: 0.223157
[2300]	valid_set's binary_logloss: 0.223026
[2350]	valid_set's binary_logloss: 0.222914
[2400]	valid_set's binary_logloss: 0.222811
[2450]	valid_set's binary_logloss: 0.222689
[2500]	valid_set's binary_logloss: 0.222616
[2550]	valid_set's binary_logloss: 0.222519
[2600]	valid_set's binary_logloss: 0.222395
[2650]	valid_set's binary_logloss: 0.222369
[2700]	valid_set's binary_logloss: 0.22232
[2750]	valid_set's binary_logloss: 0.222276
[2800]	valid_set's binary_logloss: 0.222195
[2850]	valid_set's binary_logloss: 0.222079
[2900]	valid_set's binary_logloss: 0.222008
[2950]	valid_set's binary_logloss: 0.221944
[3000]	valid_set's binary_logloss: 0.221845
[3050]	valid_set's binary_logloss: 0.221731
[3100]	valid_set's binary_logloss: 0.221685
[3150]	valid_set's binary_logloss: 0.221634
[3200]	valid_set's binary_logloss: 0.221584
[3250]	valid_set's binary_logloss: 0.221554
[3300]	valid_set's binary_logloss: 0.221516
[3350]	valid_set's binary_logloss: 0.221472
[3400]	valid_set's binary_logloss: 0.221405
[3450]	valid_set's binary_logloss: 0.221391
[3500]	valid_set's binary_logloss: 0.22132
[3550]	valid_set's binary_logloss: 0.221305
[3600]	valid_set's binary_logloss: 0.221266
[3650]	valid_set's binary_logloss: 0.22124
[3700]	valid_set's binary_logloss: 0.221198
[3750]	valid_set's binary_logloss: 0.22117
[3800]	valid_set's binary_logloss: 0.221144
[3850]	valid_set's binary_logloss: 0.221106
[3900]	valid_set's binary_logloss: 0.221136
[3950]	valid_set's binary_logloss: 0.22113
[4000]	valid_set's binary_logloss: 0.221168
[4050]	valid_set's binary_logloss: 0.221193
[4100]	valid_set's binary_logloss: 0.221177
[4150]	valid_set's binary_logloss: 0.221193
[4200]	valid_set's binary_logloss: 0.221206
[4250]	valid_set's binary_logloss: 0.221162
[4300]	valid_set's binary_logloss: 0.221153
[4350]	valid_set's binary_logloss: 0.221201
[4400]	valid_set's binary_logloss: 0.221202
[4450]	valid_set's binary_logloss: 0.22125
[4500]	valid_set's binary_logloss: 0.221245
[4550]	valid_set's binary_logloss: 0.221251
[4600]	valid_set's binary_logloss: 0.221288
[4650]	valid_set's binary_logloss: 0.221319
[4700]	valid_set's binary_logloss: 0.221349
[4750]	valid_set's binary_logloss: 0.221351
[4800]	valid_set's binary_logloss: 0.221366
[4850]	valid_set's binary_logloss: 0.221371
[4900]	valid_set's binary_logloss: 0.221389
[4950]	valid_set's binary_logloss: 0.221392
[5000]	valid_set's binary_logloss: 0.221383

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L1\model.pkl
	0.9534	 = Validation score   (roc_auc)
	171.63s	 = Training   runtime
	11.07s	 = Validation runtime
	5425.4	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 5126.85s of the 7827.88s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403883	test: 0.6403678	best: 0.6403678 (0)	total: 111ms	remaining: 111ms
1:	learn: 0.5954296	test: 0.5953906	best: 0.5953906 (1)	total: 120ms	remaining: 0us
bestTest = 0.59539056
bestIteration = 1
0:	learn: 0.6414239	test: 0.6414638	best: 0.6414638 (0)	total: 19.1ms	remaining: 16.9s
20:	learn: 0.3353687	test: 0.3353691	best: 0.3353691 (20)	total: 396ms	remaining: 16.3s
40:	learn: 0.3023125	test: 0.3018904	best: 0.3018904 (40)	total: 782ms	remaining: 16.1s
60:	learn: 0.2879553	test: 0.2871522	best: 0.2871522 (60)	total: 1.16s	remaining: 15.7s
80:	learn: 0.2804847	test: 0.2795620	best: 0.2795620 (80)	total: 1.52s	remaining: 15.1s
100:	learn: 0.2759344	test: 0.2751381	best: 0.2751381 (100)	total: 1.88s	remaining: 14.6s
120:	learn: 0.2705005	test: 0.2692794	best: 0.2692794 (120)	total: 2.25s	remaining: 14.2s
140:	learn: 0.2666954	test: 0.2655602	best: 0.2655602 (140)	total: 2.61s	remaining: 13.8s
160:	learn: 0.2630122	test: 0.2619282	best: 0.2619282 (160)	total: 2.97s	remaining: 13.4s
180:	learn: 0.2596616	test: 0.2585016	best: 0.2585016 (180)	total: 3.32s	remaining: 12.9s
200:	learn: 0.2568056	test: 0.2557241	best: 0.2557241 (200)	total: 3.67s	remaining: 12.5s
220:	learn: 0.2547017	test: 0.2537391	best: 0.2537391 (220)	total: 4.04s	remaining: 12.1s
240:	learn: 0.2525620	test: 0.2516574	best: 0.2516574 (240)	total: 4.4s	remaining: 11.8s
260:	learn: 0.2507329	test: 0.2499218	best: 0.2499218 (260)	total: 4.75s	remaining: 11.4s
280:	learn: 0.2489112	test: 0.2481452	best: 0.2481452 (280)	total: 5.1s	remaining: 11s
300:	learn: 0.2471685	test: 0.2464681	best: 0.2464681 (300)	total: 5.46s	remaining: 10.6s
320:	learn: 0.2456597	test: 0.2450456	best: 0.2450456 (320)	total: 5.83s	remaining: 10.3s
340:	learn: 0.2441924	test: 0.2437108	best: 0.2437108 (340)	total: 6.19s	remaining: 9.9s
360:	learn: 0.2429026	test: 0.2425212	best: 0.2425212 (360)	total: 6.55s	remaining: 9.52s
380:	learn: 0.2416311	test: 0.2413828	best: 0.2413828 (380)	total: 6.9s	remaining: 9.14s
400:	learn: 0.2404091	test: 0.2402501	best: 0.2402501 (400)	total: 7.25s	remaining: 8.77s
420:	learn: 0.2391570	test: 0.2390446	best: 0.2390446 (420)	total: 7.62s	remaining: 8.42s
440:	learn: 0.2378618	test: 0.2378079	best: 0.2378079 (440)	total: 7.98s	remaining: 8.06s
460:	learn: 0.2368839	test: 0.2369541	best: 0.2369541 (460)	total: 8.33s	remaining: 7.68s
480:	learn: 0.2361127	test: 0.2362677	best: 0.2362677 (480)	total: 8.69s	remaining: 7.32s
500:	learn: 0.2352839	test: 0.2355459	best: 0.2355459 (500)	total: 9.06s	remaining: 6.96s
520:	learn: 0.2344672	test: 0.2348306	best: 0.2348306 (520)	total: 9.41s	remaining: 6.6s
540:	learn: 0.2337040	test: 0.2341887	best: 0.2341887 (540)	total: 9.77s	remaining: 6.23s
560:	learn: 0.2330199	test: 0.2336708	best: 0.2336708 (560)	total: 10.1s	remaining: 5.87s
580:	learn: 0.2322974	test: 0.2330041	best: 0.2330041 (580)	total: 10.5s	remaining: 5.5s
600:	learn: 0.2314694	test: 0.2322791	best: 0.2322791 (600)	total: 10.8s	remaining: 5.13s
620:	learn: 0.2308325	test: 0.2317849	best: 0.2317849 (620)	total: 11.2s	remaining: 4.77s
640:	learn: 0.2300721	test: 0.2311031	best: 0.2311031 (640)	total: 11.5s	remaining: 4.41s
660:	learn: 0.2295159	test: 0.2306512	best: 0.2306512 (660)	total: 11.9s	remaining: 4.04s
680:	learn: 0.2289779	test: 0.2301920	best: 0.2301920 (680)	total: 12.2s	remaining: 3.69s
700:	learn: 0.2283993	test: 0.2297426	best: 0.2297426 (700)	total: 12.6s	remaining: 3.33s
720:	learn: 0.2278825	test: 0.2293418	best: 0.2293418 (720)	total: 13s	remaining: 2.96s
740:	learn: 0.2272867	test: 0.2288539	best: 0.2288539 (740)	total: 13.3s	remaining: 2.6s
760:	learn: 0.2268051	test: 0.2285061	best: 0.2285061 (760)	total: 13.6s	remaining: 2.24s
780:	learn: 0.2263471	test: 0.2281605	best: 0.2281605 (780)	total: 14s	remaining: 1.88s
800:	learn: 0.2257664	test: 0.2277242	best: 0.2277242 (800)	total: 14.4s	remaining: 1.52s
820:	learn: 0.2251351	test: 0.2272197	best: 0.2272197 (820)	total: 14.7s	remaining: 1.16s
840:	learn: 0.2246768	test: 0.2268365	best: 0.2268365 (840)	total: 15.1s	remaining: 806ms
860:	learn: 0.2242134	test: 0.2264710	best: 0.2264710 (860)	total: 15.4s	remaining: 448ms
880:	learn: 0.2237733	test: 0.2261521	best: 0.2261521 (880)	total: 15.8s	remaining: 89.5ms
885:	learn: 0.2236437	test: 0.2260497	best: 0.2260497 (885)	total: 15.9s	remaining: 0us
bestTest = 0.2260496949
bestIteration = 885

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403956	test: 0.6403474	best: 0.6403474 (0)	total: 9.16ms	remaining: 9.16ms
1:	learn: 0.5955584	test: 0.5955090	best: 0.5955090 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5955089509
bestIteration = 1
0:	learn: 0.6413593	test: 0.6412570	best: 0.6412570 (0)	total: 16.7ms	remaining: 28.9s
20:	learn: 0.3350585	test: 0.3358660	best: 0.3358660 (20)	total: 401ms	remaining: 32.7s
40:	learn: 0.3038788	test: 0.3055327	best: 0.3055327 (40)	total: 786ms	remaining: 32.4s
60:	learn: 0.2887798	test: 0.2900183	best: 0.2900183 (60)	total: 1.17s	remaining: 32s
80:	learn: 0.2797310	test: 0.2804268	best: 0.2804268 (80)	total: 1.55s	remaining: 31.6s
100:	learn: 0.2753552	test: 0.2760521	best: 0.2760521 (100)	total: 1.91s	remaining: 30.7s
120:	learn: 0.2707151	test: 0.2714008	best: 0.2714008 (120)	total: 2.29s	remaining: 30.5s
140:	learn: 0.2668871	test: 0.2674473	best: 0.2674473 (140)	total: 2.67s	remaining: 30.1s
160:	learn: 0.2632113	test: 0.2636303	best: 0.2636303 (160)	total: 3.04s	remaining: 29.7s
180:	learn: 0.2602590	test: 0.2607132	best: 0.2607132 (180)	total: 3.4s	remaining: 29.1s
200:	learn: 0.2575663	test: 0.2580159	best: 0.2580159 (200)	total: 3.76s	remaining: 28.6s
220:	learn: 0.2549884	test: 0.2552869	best: 0.2552869 (220)	total: 4.13s	remaining: 28.2s
240:	learn: 0.2526024	test: 0.2528483	best: 0.2528483 (240)	total: 4.49s	remaining: 27.7s
260:	learn: 0.2505366	test: 0.2507860	best: 0.2507860 (260)	total: 4.85s	remaining: 27.3s
280:	learn: 0.2486842	test: 0.2489455	best: 0.2489455 (280)	total: 5.22s	remaining: 26.9s
300:	learn: 0.2467983	test: 0.2470188	best: 0.2470188 (300)	total: 5.6s	remaining: 26.6s
320:	learn: 0.2452424	test: 0.2454769	best: 0.2454769 (320)	total: 5.96s	remaining: 26.2s
340:	learn: 0.2438466	test: 0.2441731	best: 0.2441731 (340)	total: 6.32s	remaining: 25.8s
360:	learn: 0.2425598	test: 0.2430403	best: 0.2430403 (360)	total: 6.68s	remaining: 25.3s
380:	learn: 0.2412976	test: 0.2419479	best: 0.2419479 (380)	total: 7.03s	remaining: 24.9s
400:	learn: 0.2400351	test: 0.2407278	best: 0.2407278 (400)	total: 7.4s	remaining: 24.5s
420:	learn: 0.2389157	test: 0.2396676	best: 0.2396676 (420)	total: 7.75s	remaining: 24.1s
440:	learn: 0.2379626	test: 0.2388112	best: 0.2388112 (440)	total: 8.11s	remaining: 23.7s
460:	learn: 0.2369531	test: 0.2379065	best: 0.2379065 (460)	total: 8.47s	remaining: 23.3s
480:	learn: 0.2360806	test: 0.2371008	best: 0.2371008 (480)	total: 8.83s	remaining: 22.9s
500:	learn: 0.2352041	test: 0.2362782	best: 0.2362782 (500)	total: 9.18s	remaining: 22.5s
520:	learn: 0.2342931	test: 0.2354899	best: 0.2354899 (520)	total: 9.54s	remaining: 22.1s
540:	learn: 0.2335373	test: 0.2348822	best: 0.2348822 (540)	total: 9.9s	remaining: 21.8s
560:	learn: 0.2328014	test: 0.2342465	best: 0.2342465 (560)	total: 10.3s	remaining: 21.4s
580:	learn: 0.2320154	test: 0.2335508	best: 0.2335508 (580)	total: 10.6s	remaining: 21s
600:	learn: 0.2311784	test: 0.2327911	best: 0.2327911 (600)	total: 11s	remaining: 20.6s
620:	learn: 0.2305002	test: 0.2321569	best: 0.2321569 (620)	total: 11.3s	remaining: 20.2s
640:	learn: 0.2297844	test: 0.2315522	best: 0.2315522 (640)	total: 11.7s	remaining: 19.8s
660:	learn: 0.2291174	test: 0.2309418	best: 0.2309418 (660)	total: 12s	remaining: 19.4s
680:	learn: 0.2285708	test: 0.2305228	best: 0.2305228 (680)	total: 12.4s	remaining: 19s
700:	learn: 0.2279044	test: 0.2299710	best: 0.2299710 (700)	total: 12.7s	remaining: 18.7s
720:	learn: 0.2272332	test: 0.2293753	best: 0.2293753 (720)	total: 13.1s	remaining: 18.3s
740:	learn: 0.2267370	test: 0.2289735	best: 0.2289735 (740)	total: 13.4s	remaining: 17.9s
760:	learn: 0.2260834	test: 0.2283797	best: 0.2283797 (760)	total: 13.8s	remaining: 17.5s
780:	learn: 0.2255373	test: 0.2279509	best: 0.2279509 (780)	total: 14.1s	remaining: 17.2s
800:	learn: 0.2250152	test: 0.2275273	best: 0.2275273 (800)	total: 14.5s	remaining: 16.8s
820:	learn: 0.2244844	test: 0.2270938	best: 0.2270938 (820)	total: 14.8s	remaining: 16.4s
840:	learn: 0.2240074	test: 0.2267368	best: 0.2267368 (840)	total: 15.2s	remaining: 16s
860:	learn: 0.2235401	test: 0.2264035	best: 0.2264035 (860)	total: 15.5s	remaining: 15.7s
880:	learn: 0.2231263	test: 0.2261049	best: 0.2261049 (880)	total: 15.9s	remaining: 15.3s
900:	learn: 0.2226798	test: 0.2257566	best: 0.2257566 (900)	total: 16.2s	remaining: 14.9s
920:	learn: 0.2221360	test: 0.2252812	best: 0.2252812 (920)	total: 16.6s	remaining: 14.5s
940:	learn: 0.2217598	test: 0.2249944	best: 0.2249944 (940)	total: 16.9s	remaining: 14.2s
960:	learn: 0.2213685	test: 0.2247427	best: 0.2247427 (960)	total: 17.3s	remaining: 13.8s
980:	learn: 0.2209893	test: 0.2244714	best: 0.2244714 (980)	total: 17.6s	remaining: 13.4s
1000:	learn: 0.2205543	test: 0.2241836	best: 0.2241836 (1000)	total: 18s	remaining: 13.1s
1020:	learn: 0.2201883	test: 0.2239301	best: 0.2239301 (1020)	total: 18.3s	remaining: 12.7s
1040:	learn: 0.2198449	test: 0.2236671	best: 0.2236671 (1040)	total: 18.7s	remaining: 12.4s
1060:	learn: 0.2195149	test: 0.2234338	best: 0.2234338 (1060)	total: 19s	remaining: 12s
1080:	learn: 0.2191097	test: 0.2231331	best: 0.2231331 (1080)	total: 19.4s	remaining: 11.6s
1100:	learn: 0.2187381	test: 0.2228671	best: 0.2228671 (1100)	total: 19.7s	remaining: 11.3s
1120:	learn: 0.2184564	test: 0.2227206	best: 0.2227206 (1120)	total: 20.1s	remaining: 10.9s
1140:	learn: 0.2180188	test: 0.2223624	best: 0.2223624 (1140)	total: 20.4s	remaining: 10.5s
1160:	learn: 0.2176973	test: 0.2221241	best: 0.2221241 (1160)	total: 20.8s	remaining: 10.2s
1180:	learn: 0.2174461	test: 0.2219752	best: 0.2219752 (1180)	total: 21.1s	remaining: 9.82s
1200:	learn: 0.2171348	test: 0.2217731	best: 0.2217731 (1200)	total: 21.5s	remaining: 9.46s
1220:	learn: 0.2168239	test: 0.2215637	best: 0.2215637 (1220)	total: 21.8s	remaining: 9.1s
1240:	learn: 0.2164961	test: 0.2213288	best: 0.2213288 (1240)	total: 22.2s	remaining: 8.74s
1260:	learn: 0.2161939	test: 0.2211114	best: 0.2211114 (1260)	total: 22.5s	remaining: 8.38s
1280:	learn: 0.2158861	test: 0.2208981	best: 0.2208981 (1280)	total: 22.9s	remaining: 8.03s
1300:	learn: 0.2156237	test: 0.2207165	best: 0.2207165 (1300)	total: 23.3s	remaining: 7.67s
1320:	learn: 0.2153433	test: 0.2205557	best: 0.2205557 (1320)	total: 23.6s	remaining: 7.31s
1340:	learn: 0.2150585	test: 0.2203899	best: 0.2203899 (1340)	total: 23.9s	remaining: 6.95s
1360:	learn: 0.2147637	test: 0.2202055	best: 0.2202055 (1360)	total: 24.3s	remaining: 6.59s
1380:	learn: 0.2145305	test: 0.2200571	best: 0.2200571 (1380)	total: 24.7s	remaining: 6.23s
1400:	learn: 0.2142446	test: 0.2198623	best: 0.2198614 (1399)	total: 25s	remaining: 5.87s
1420:	learn: 0.2139678	test: 0.2196885	best: 0.2196885 (1420)	total: 25.3s	remaining: 5.51s
1440:	learn: 0.2137384	test: 0.2195682	best: 0.2195682 (1440)	total: 25.7s	remaining: 5.15s
1460:	learn: 0.2134974	test: 0.2194108	best: 0.2194108 (1460)	total: 26s	remaining: 4.79s
1480:	learn: 0.2132463	test: 0.2192911	best: 0.2192911 (1480)	total: 26.4s	remaining: 4.44s
1500:	learn: 0.2130037	test: 0.2191406	best: 0.2191406 (1500)	total: 26.8s	remaining: 4.08s
1520:	learn: 0.2127157	test: 0.2189731	best: 0.2189731 (1520)	total: 27.1s	remaining: 3.73s
1540:	learn: 0.2125049	test: 0.2188590	best: 0.2188590 (1540)	total: 27.5s	remaining: 3.37s
1560:	learn: 0.2122779	test: 0.2187296	best: 0.2187296 (1560)	total: 27.8s	remaining: 3.01s
1580:	learn: 0.2120271	test: 0.2186265	best: 0.2186265 (1580)	total: 28.2s	remaining: 2.65s
1600:	learn: 0.2117621	test: 0.2184882	best: 0.2184882 (1600)	total: 28.5s	remaining: 2.3s
1620:	learn: 0.2115051	test: 0.2183460	best: 0.2183451 (1619)	total: 28.9s	remaining: 1.94s
1640:	learn: 0.2112783	test: 0.2182366	best: 0.2182366 (1640)	total: 29.2s	remaining: 1.58s
1660:	learn: 0.2110586	test: 0.2181246	best: 0.2181246 (1660)	total: 29.6s	remaining: 1.23s
1680:	learn: 0.2107717	test: 0.2179535	best: 0.2179535 (1680)	total: 29.9s	remaining: 873ms
1700:	learn: 0.2104594	test: 0.2177491	best: 0.2177491 (1700)	total: 30.3s	remaining: 516ms
1720:	learn: 0.2102134	test: 0.2176292	best: 0.2176292 (1720)	total: 30.6s	remaining: 160ms
1729:	learn: 0.2101206	test: 0.2175892	best: 0.2175892 (1729)	total: 30.8s	remaining: 0us
bestTest = 0.2175892485
bestIteration = 1729

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404682	test: 0.6404734	best: 0.6404734 (0)	total: 8.97ms	remaining: 8.97ms
1:	learn: 0.5955481	test: 0.5955632	best: 0.5955632 (1)	total: 17.7ms	remaining: 0us
bestTest = 0.5955632025
bestIteration = 1
0:	learn: 0.6414262	test: 0.6415655	best: 0.6415655 (0)	total: 16.8ms	remaining: 29.3s
20:	learn: 0.3360574	test: 0.3366846	best: 0.3366846 (20)	total: 396ms	remaining: 32.5s
40:	learn: 0.3042963	test: 0.3051400	best: 0.3051400 (40)	total: 775ms	remaining: 32.2s
60:	learn: 0.2899563	test: 0.2904447	best: 0.2904447 (60)	total: 1.16s	remaining: 32.2s
80:	learn: 0.2815050	test: 0.2820812	best: 0.2820812 (80)	total: 1.54s	remaining: 31.7s
100:	learn: 0.2756028	test: 0.2760391	best: 0.2760391 (100)	total: 1.91s	remaining: 31.1s
120:	learn: 0.2715905	test: 0.2721195	best: 0.2721195 (120)	total: 2.27s	remaining: 30.5s
140:	learn: 0.2673928	test: 0.2677283	best: 0.2677283 (140)	total: 2.63s	remaining: 29.9s
160:	learn: 0.2625153	test: 0.2627312	best: 0.2627312 (160)	total: 2.99s	remaining: 29.4s
180:	learn: 0.2594977	test: 0.2596536	best: 0.2596536 (180)	total: 3.33s	remaining: 28.8s
200:	learn: 0.2563955	test: 0.2565787	best: 0.2565787 (200)	total: 3.69s	remaining: 28.4s
220:	learn: 0.2542346	test: 0.2545187	best: 0.2545187 (220)	total: 4.04s	remaining: 27.9s
240:	learn: 0.2520475	test: 0.2522731	best: 0.2522731 (240)	total: 4.42s	remaining: 27.6s
260:	learn: 0.2498515	test: 0.2499437	best: 0.2499437 (260)	total: 4.78s	remaining: 27.2s
280:	learn: 0.2482647	test: 0.2484547	best: 0.2484547 (280)	total: 5.13s	remaining: 26.8s
300:	learn: 0.2466697	test: 0.2469094	best: 0.2469094 (300)	total: 5.49s	remaining: 26.4s
320:	learn: 0.2451765	test: 0.2455523	best: 0.2455523 (320)	total: 5.84s	remaining: 25.9s
340:	learn: 0.2436936	test: 0.2441287	best: 0.2441287 (340)	total: 6.2s	remaining: 25.5s
360:	learn: 0.2423345	test: 0.2429415	best: 0.2429415 (360)	total: 6.55s	remaining: 25.1s
380:	learn: 0.2413013	test: 0.2419783	best: 0.2419783 (380)	total: 6.91s	remaining: 24.7s
400:	learn: 0.2402687	test: 0.2410695	best: 0.2410695 (400)	total: 7.26s	remaining: 24.4s
420:	learn: 0.2390302	test: 0.2398652	best: 0.2398652 (420)	total: 7.62s	remaining: 24s
440:	learn: 0.2380469	test: 0.2390231	best: 0.2390231 (440)	total: 7.98s	remaining: 23.6s
460:	learn: 0.2370824	test: 0.2381452	best: 0.2381452 (460)	total: 8.33s	remaining: 23.2s
480:	learn: 0.2359786	test: 0.2370911	best: 0.2370911 (480)	total: 8.7s	remaining: 22.9s
500:	learn: 0.2351550	test: 0.2364295	best: 0.2364295 (500)	total: 9.05s	remaining: 22.5s
520:	learn: 0.2344207	test: 0.2358376	best: 0.2358376 (520)	total: 9.4s	remaining: 22.1s
540:	learn: 0.2336787	test: 0.2352429	best: 0.2352429 (540)	total: 9.75s	remaining: 21.7s
560:	learn: 0.2328579	test: 0.2345351	best: 0.2345351 (560)	total: 10.1s	remaining: 21.4s
580:	learn: 0.2321954	test: 0.2339421	best: 0.2339421 (580)	total: 10.5s	remaining: 21s
600:	learn: 0.2314093	test: 0.2332539	best: 0.2332539 (600)	total: 10.8s	remaining: 20.6s
620:	learn: 0.2305711	test: 0.2325060	best: 0.2325060 (620)	total: 11.2s	remaining: 20.2s
640:	learn: 0.2298627	test: 0.2319105	best: 0.2319105 (640)	total: 11.5s	remaining: 19.8s
660:	learn: 0.2292550	test: 0.2314416	best: 0.2314416 (660)	total: 11.9s	remaining: 19.5s
680:	learn: 0.2285704	test: 0.2308668	best: 0.2308668 (680)	total: 12.2s	remaining: 19.1s
700:	learn: 0.2279755	test: 0.2303743	best: 0.2303743 (700)	total: 12.6s	remaining: 18.7s
720:	learn: 0.2274585	test: 0.2299797	best: 0.2299797 (720)	total: 12.9s	remaining: 18.4s
740:	learn: 0.2269610	test: 0.2296240	best: 0.2296240 (740)	total: 13.3s	remaining: 18s
760:	learn: 0.2264117	test: 0.2292223	best: 0.2292223 (760)	total: 13.6s	remaining: 17.6s
780:	learn: 0.2258959	test: 0.2288788	best: 0.2288788 (780)	total: 14s	remaining: 17.3s
800:	learn: 0.2253021	test: 0.2284517	best: 0.2284517 (800)	total: 14.3s	remaining: 16.9s
820:	learn: 0.2247592	test: 0.2280113	best: 0.2280113 (820)	total: 14.7s	remaining: 16.5s
840:	learn: 0.2242822	test: 0.2276188	best: 0.2276188 (840)	total: 15s	remaining: 16.1s
860:	learn: 0.2238605	test: 0.2273189	best: 0.2273189 (860)	total: 15.4s	remaining: 15.8s
880:	learn: 0.2234325	test: 0.2270190	best: 0.2270190 (880)	total: 15.7s	remaining: 15.4s
900:	learn: 0.2230047	test: 0.2267231	best: 0.2267231 (900)	total: 16.1s	remaining: 15.1s
920:	learn: 0.2225651	test: 0.2263811	best: 0.2263811 (920)	total: 16.4s	remaining: 14.7s
940:	learn: 0.2222116	test: 0.2261721	best: 0.2261721 (940)	total: 16.8s	remaining: 14.3s
960:	learn: 0.2218127	test: 0.2258786	best: 0.2258786 (960)	total: 17.1s	remaining: 14s
980:	learn: 0.2214349	test: 0.2255809	best: 0.2255809 (980)	total: 17.5s	remaining: 13.6s
1000:	learn: 0.2210505	test: 0.2252970	best: 0.2252970 (1000)	total: 17.8s	remaining: 13.3s
1020:	learn: 0.2206718	test: 0.2250319	best: 0.2250319 (1020)	total: 18.2s	remaining: 12.9s
1040:	learn: 0.2203631	test: 0.2248643	best: 0.2248643 (1040)	total: 18.5s	remaining: 12.5s
1060:	learn: 0.2200137	test: 0.2246741	best: 0.2246741 (1060)	total: 18.9s	remaining: 12.2s
1080:	learn: 0.2196024	test: 0.2243970	best: 0.2243970 (1080)	total: 19.2s	remaining: 11.8s
1100:	learn: 0.2192049	test: 0.2241303	best: 0.2241303 (1100)	total: 19.6s	remaining: 11.5s
1120:	learn: 0.2187963	test: 0.2238571	best: 0.2238571 (1120)	total: 19.9s	remaining: 11.1s
1140:	learn: 0.2184736	test: 0.2236320	best: 0.2236320 (1140)	total: 20.3s	remaining: 10.8s
1160:	learn: 0.2180948	test: 0.2233696	best: 0.2233696 (1160)	total: 20.7s	remaining: 10.4s
1180:	learn: 0.2177617	test: 0.2231660	best: 0.2231660 (1180)	total: 21s	remaining: 10s
1200:	learn: 0.2173827	test: 0.2228948	best: 0.2228948 (1200)	total: 21.4s	remaining: 9.69s
1220:	learn: 0.2170757	test: 0.2227394	best: 0.2227394 (1220)	total: 21.7s	remaining: 9.33s
1240:	learn: 0.2167614	test: 0.2225595	best: 0.2225595 (1240)	total: 22.1s	remaining: 8.97s
1260:	learn: 0.2164605	test: 0.2223878	best: 0.2223878 (1260)	total: 22.4s	remaining: 8.62s
1280:	learn: 0.2161445	test: 0.2221844	best: 0.2221844 (1280)	total: 22.7s	remaining: 8.25s
1300:	learn: 0.2158063	test: 0.2219672	best: 0.2219672 (1300)	total: 23.1s	remaining: 7.9s
1320:	learn: 0.2155676	test: 0.2218660	best: 0.2218660 (1320)	total: 23.4s	remaining: 7.54s
1340:	learn: 0.2152891	test: 0.2217274	best: 0.2217274 (1340)	total: 23.8s	remaining: 7.19s
1360:	learn: 0.2149778	test: 0.2215383	best: 0.2215383 (1360)	total: 24.2s	remaining: 6.83s
1380:	learn: 0.2147358	test: 0.2214188	best: 0.2214188 (1380)	total: 24.5s	remaining: 6.48s
1400:	learn: 0.2143750	test: 0.2211705	best: 0.2211705 (1400)	total: 24.9s	remaining: 6.12s
1420:	learn: 0.2140740	test: 0.2209855	best: 0.2209855 (1420)	total: 25.2s	remaining: 5.77s
1440:	learn: 0.2137226	test: 0.2207261	best: 0.2207261 (1440)	total: 25.6s	remaining: 5.41s
1460:	learn: 0.2134935	test: 0.2206260	best: 0.2206260 (1460)	total: 25.9s	remaining: 5.05s
1480:	learn: 0.2132725	test: 0.2205139	best: 0.2205139 (1480)	total: 26.3s	remaining: 4.7s
1500:	learn: 0.2130133	test: 0.2203176	best: 0.2203176 (1500)	total: 26.6s	remaining: 4.34s
1520:	learn: 0.2127382	test: 0.2201328	best: 0.2201328 (1520)	total: 27s	remaining: 3.99s
1540:	learn: 0.2124355	test: 0.2198893	best: 0.2198893 (1540)	total: 27.3s	remaining: 3.64s
1560:	learn: 0.2121886	test: 0.2197391	best: 0.2197391 (1560)	total: 27.7s	remaining: 3.28s
1580:	learn: 0.2119140	test: 0.2195337	best: 0.2195337 (1580)	total: 28.1s	remaining: 2.93s
1600:	learn: 0.2117029	test: 0.2194312	best: 0.2194289 (1599)	total: 28.4s	remaining: 2.57s
1620:	learn: 0.2114452	test: 0.2192837	best: 0.2192837 (1620)	total: 28.8s	remaining: 2.22s
1640:	learn: 0.2111392	test: 0.2191069	best: 0.2191069 (1640)	total: 29.1s	remaining: 1.86s
1660:	learn: 0.2108423	test: 0.2188515	best: 0.2188515 (1660)	total: 29.5s	remaining: 1.51s
1680:	learn: 0.2106089	test: 0.2187173	best: 0.2187173 (1680)	total: 29.8s	remaining: 1.15s
1700:	learn: 0.2103959	test: 0.2186059	best: 0.2186059 (1700)	total: 30.2s	remaining: 798ms
1720:	learn: 0.2100975	test: 0.2184200	best: 0.2184200 (1720)	total: 30.5s	remaining: 443ms
1740:	learn: 0.2099190	test: 0.2183356	best: 0.2183356 (1740)	total: 30.9s	remaining: 88.7ms
1745:	learn: 0.2098623	test: 0.2183074	best: 0.2183074 (1745)	total: 31s	remaining: 0us
bestTest = 0.2183073676
bestIteration = 1745

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404078	test: 0.6405121	best: 0.6405121 (0)	total: 8.66ms	remaining: 8.66ms
1:	learn: 0.5954479	test: 0.5956213	best: 0.5956213 (1)	total: 17.3ms	remaining: 0us
bestTest = 0.5956213233
bestIteration = 1
0:	learn: 0.6414466	test: 0.6415251	best: 0.6415251 (0)	total: 16.7ms	remaining: 35.4s
20:	learn: 0.3359946	test: 0.3359399	best: 0.3359399 (20)	total: 391ms	remaining: 39s
40:	learn: 0.3040518	test: 0.3038384	best: 0.3038384 (40)	total: 766ms	remaining: 38.8s
60:	learn: 0.2901644	test: 0.2895496	best: 0.2895496 (60)	total: 1.15s	remaining: 38.6s
80:	learn: 0.2822328	test: 0.2815078	best: 0.2815078 (80)	total: 1.52s	remaining: 38.2s
100:	learn: 0.2765258	test: 0.2758220	best: 0.2758220 (100)	total: 1.9s	remaining: 37.9s
120:	learn: 0.2723103	test: 0.2717627	best: 0.2717627 (120)	total: 2.27s	remaining: 37.4s
140:	learn: 0.2683645	test: 0.2678247	best: 0.2678247 (140)	total: 2.64s	remaining: 37s
160:	learn: 0.2635913	test: 0.2627998	best: 0.2627998 (160)	total: 3.03s	remaining: 36.8s
180:	learn: 0.2604420	test: 0.2597451	best: 0.2597451 (180)	total: 3.39s	remaining: 36.2s
200:	learn: 0.2574312	test: 0.2567304	best: 0.2567304 (200)	total: 3.75s	remaining: 35.7s
220:	learn: 0.2548521	test: 0.2541231	best: 0.2541231 (220)	total: 4.11s	remaining: 35.2s
240:	learn: 0.2525995	test: 0.2518454	best: 0.2518454 (240)	total: 4.46s	remaining: 34.7s
260:	learn: 0.2505088	test: 0.2497730	best: 0.2497730 (260)	total: 4.83s	remaining: 34.3s
280:	learn: 0.2486725	test: 0.2479268	best: 0.2479268 (280)	total: 5.18s	remaining: 33.8s
300:	learn: 0.2470973	test: 0.2465092	best: 0.2465092 (300)	total: 5.54s	remaining: 33.4s
320:	learn: 0.2456197	test: 0.2451564	best: 0.2451564 (320)	total: 5.91s	remaining: 33.1s
340:	learn: 0.2442709	test: 0.2438780	best: 0.2438780 (340)	total: 6.25s	remaining: 32.6s
360:	learn: 0.2427913	test: 0.2423794	best: 0.2423794 (360)	total: 6.63s	remaining: 32.2s
380:	learn: 0.2414905	test: 0.2411596	best: 0.2411596 (380)	total: 7s	remaining: 31.9s
400:	learn: 0.2403234	test: 0.2400456	best: 0.2400456 (400)	total: 7.36s	remaining: 31.5s
420:	learn: 0.2393572	test: 0.2390799	best: 0.2390799 (420)	total: 7.72s	remaining: 31.1s
440:	learn: 0.2382581	test: 0.2380512	best: 0.2380512 (440)	total: 8.09s	remaining: 30.7s
460:	learn: 0.2373938	test: 0.2373107	best: 0.2373107 (460)	total: 8.44s	remaining: 30.3s
480:	learn: 0.2364766	test: 0.2364888	best: 0.2364888 (480)	total: 8.81s	remaining: 29.9s
500:	learn: 0.2354704	test: 0.2355914	best: 0.2355914 (500)	total: 9.15s	remaining: 29.5s
520:	learn: 0.2345854	test: 0.2347729	best: 0.2347729 (520)	total: 9.52s	remaining: 29.1s
540:	learn: 0.2338628	test: 0.2341619	best: 0.2341619 (540)	total: 9.88s	remaining: 28.8s
560:	learn: 0.2329186	test: 0.2332976	best: 0.2332976 (560)	total: 10.2s	remaining: 28.4s
580:	learn: 0.2321760	test: 0.2326918	best: 0.2326918 (580)	total: 10.6s	remaining: 28s
600:	learn: 0.2314661	test: 0.2320998	best: 0.2320998 (600)	total: 11s	remaining: 27.6s
620:	learn: 0.2306096	test: 0.2313128	best: 0.2313128 (620)	total: 11.3s	remaining: 27.2s
640:	learn: 0.2299814	test: 0.2308172	best: 0.2308172 (640)	total: 11.7s	remaining: 26.8s
660:	learn: 0.2294013	test: 0.2303515	best: 0.2303515 (660)	total: 12s	remaining: 26.4s
680:	learn: 0.2288801	test: 0.2299482	best: 0.2299482 (680)	total: 12.4s	remaining: 26s
700:	learn: 0.2282069	test: 0.2293333	best: 0.2293333 (700)	total: 12.7s	remaining: 25.6s
720:	learn: 0.2275358	test: 0.2287343	best: 0.2287343 (720)	total: 13s	remaining: 25.2s
740:	learn: 0.2270010	test: 0.2282782	best: 0.2282782 (740)	total: 13.4s	remaining: 24.9s
760:	learn: 0.2264798	test: 0.2278720	best: 0.2278720 (760)	total: 13.8s	remaining: 24.5s
780:	learn: 0.2260092	test: 0.2274826	best: 0.2274826 (780)	total: 14.1s	remaining: 24.1s
800:	learn: 0.2254796	test: 0.2270581	best: 0.2270581 (800)	total: 14.5s	remaining: 23.7s
820:	learn: 0.2248987	test: 0.2265640	best: 0.2265640 (820)	total: 14.8s	remaining: 23.4s
840:	learn: 0.2243714	test: 0.2261502	best: 0.2261502 (840)	total: 15.2s	remaining: 23s
860:	learn: 0.2238577	test: 0.2257030	best: 0.2257030 (860)	total: 15.5s	remaining: 22.6s
880:	learn: 0.2234293	test: 0.2253991	best: 0.2253991 (880)	total: 15.9s	remaining: 22.3s
900:	learn: 0.2230421	test: 0.2251487	best: 0.2251487 (900)	total: 16.2s	remaining: 21.9s
920:	learn: 0.2225605	test: 0.2247308	best: 0.2247308 (920)	total: 16.6s	remaining: 21.5s
940:	learn: 0.2221881	test: 0.2244744	best: 0.2244744 (940)	total: 16.9s	remaining: 21.1s
960:	learn: 0.2217883	test: 0.2241631	best: 0.2241631 (960)	total: 17.3s	remaining: 20.8s
980:	learn: 0.2213442	test: 0.2238313	best: 0.2238313 (980)	total: 17.6s	remaining: 20.4s
1000:	learn: 0.2209551	test: 0.2235779	best: 0.2235779 (1000)	total: 18s	remaining: 20s
1020:	learn: 0.2205425	test: 0.2232614	best: 0.2232614 (1020)	total: 18.3s	remaining: 19.7s
1040:	learn: 0.2201736	test: 0.2230072	best: 0.2230072 (1040)	total: 18.7s	remaining: 19.3s
1060:	learn: 0.2198713	test: 0.2228260	best: 0.2228260 (1060)	total: 19s	remaining: 18.9s
1080:	learn: 0.2195165	test: 0.2225923	best: 0.2225923 (1080)	total: 19.4s	remaining: 18.6s
1100:	learn: 0.2191873	test: 0.2223826	best: 0.2223826 (1100)	total: 19.7s	remaining: 18.2s
1120:	learn: 0.2188457	test: 0.2221678	best: 0.2221678 (1120)	total: 20.1s	remaining: 17.8s
1140:	learn: 0.2184512	test: 0.2218693	best: 0.2218693 (1140)	total: 20.4s	remaining: 17.5s
1160:	learn: 0.2181108	test: 0.2216694	best: 0.2216694 (1160)	total: 20.8s	remaining: 17.1s
1180:	learn: 0.2177844	test: 0.2214831	best: 0.2214831 (1180)	total: 21.1s	remaining: 16.7s
1200:	learn: 0.2174627	test: 0.2212719	best: 0.2212719 (1200)	total: 21.5s	remaining: 16.4s
1220:	learn: 0.2171517	test: 0.2210733	best: 0.2210733 (1220)	total: 21.8s	remaining: 16s
1240:	learn: 0.2168388	test: 0.2208760	best: 0.2208760 (1240)	total: 22.2s	remaining: 15.6s
1260:	learn: 0.2165362	test: 0.2206127	best: 0.2206127 (1260)	total: 22.5s	remaining: 15.3s
1280:	learn: 0.2162333	test: 0.2204146	best: 0.2204146 (1280)	total: 22.9s	remaining: 14.9s
1300:	learn: 0.2159451	test: 0.2201652	best: 0.2201652 (1300)	total: 23.3s	remaining: 14.6s
1320:	learn: 0.2156755	test: 0.2200335	best: 0.2200335 (1320)	total: 23.6s	remaining: 14.2s
1340:	learn: 0.2154118	test: 0.2198823	best: 0.2198823 (1340)	total: 24s	remaining: 13.8s
1360:	learn: 0.2150490	test: 0.2196048	best: 0.2196048 (1360)	total: 24.3s	remaining: 13.5s
1380:	learn: 0.2148073	test: 0.2194456	best: 0.2194456 (1380)	total: 24.7s	remaining: 13.1s
1400:	learn: 0.2145238	test: 0.2192561	best: 0.2192561 (1400)	total: 25s	remaining: 12.8s
1420:	learn: 0.2142581	test: 0.2190819	best: 0.2190819 (1420)	total: 25.4s	remaining: 12.4s
1440:	learn: 0.2139992	test: 0.2189421	best: 0.2189414 (1439)	total: 25.7s	remaining: 12.1s
1460:	learn: 0.2137372	test: 0.2187791	best: 0.2187791 (1460)	total: 26.1s	remaining: 11.7s
1480:	learn: 0.2134458	test: 0.2185890	best: 0.2185890 (1480)	total: 26.4s	remaining: 11.3s
1500:	learn: 0.2132188	test: 0.2184846	best: 0.2184846 (1500)	total: 26.8s	remaining: 11s
1520:	learn: 0.2129587	test: 0.2183629	best: 0.2183629 (1520)	total: 27.2s	remaining: 10.6s
1540:	learn: 0.2127173	test: 0.2182030	best: 0.2182030 (1540)	total: 27.5s	remaining: 10.3s
1560:	learn: 0.2124884	test: 0.2180924	best: 0.2180924 (1560)	total: 27.9s	remaining: 9.91s
1580:	learn: 0.2122824	test: 0.2180054	best: 0.2180054 (1580)	total: 28.2s	remaining: 9.54s
1600:	learn: 0.2120333	test: 0.2178643	best: 0.2178643 (1600)	total: 28.6s	remaining: 9.19s
1620:	learn: 0.2117817	test: 0.2176948	best: 0.2176948 (1620)	total: 28.9s	remaining: 8.83s
1640:	learn: 0.2115528	test: 0.2175639	best: 0.2175639 (1640)	total: 29.3s	remaining: 8.47s
1660:	learn: 0.2113334	test: 0.2174460	best: 0.2174460 (1660)	total: 29.6s	remaining: 8.11s
1680:	learn: 0.2111101	test: 0.2173136	best: 0.2173129 (1679)	total: 30s	remaining: 7.76s
1700:	learn: 0.2108683	test: 0.2171543	best: 0.2171543 (1700)	total: 30.3s	remaining: 7.4s
1720:	learn: 0.2106179	test: 0.2170089	best: 0.2170089 (1720)	total: 30.7s	remaining: 7.05s
1740:	learn: 0.2104072	test: 0.2168996	best: 0.2168996 (1740)	total: 31.1s	remaining: 6.69s
1760:	learn: 0.2101847	test: 0.2167853	best: 0.2167853 (1760)	total: 31.4s	remaining: 6.33s
1780:	learn: 0.2099563	test: 0.2166546	best: 0.2166546 (1780)	total: 31.8s	remaining: 5.98s
1800:	learn: 0.2097289	test: 0.2165420	best: 0.2165420 (1800)	total: 32.1s	remaining: 5.62s
1820:	learn: 0.2095057	test: 0.2163987	best: 0.2163987 (1820)	total: 32.5s	remaining: 5.27s
1840:	learn: 0.2092526	test: 0.2162549	best: 0.2162549 (1840)	total: 32.9s	remaining: 4.91s
1860:	learn: 0.2089938	test: 0.2160998	best: 0.2160998 (1860)	total: 33.2s	remaining: 4.55s
1880:	learn: 0.2087363	test: 0.2159553	best: 0.2159553 (1880)	total: 33.6s	remaining: 4.19s
1900:	learn: 0.2085354	test: 0.2158550	best: 0.2158550 (1900)	total: 33.9s	remaining: 3.84s
1920:	learn: 0.2083456	test: 0.2157605	best: 0.2157605 (1920)	total: 34.3s	remaining: 3.48s
1940:	learn: 0.2081646	test: 0.2156999	best: 0.2156978 (1939)	total: 34.6s	remaining: 3.12s
1960:	learn: 0.2079239	test: 0.2155521	best: 0.2155521 (1960)	total: 35s	remaining: 2.77s
1980:	learn: 0.2077237	test: 0.2154476	best: 0.2154476 (1980)	total: 35.4s	remaining: 2.41s
2000:	learn: 0.2075585	test: 0.2153837	best: 0.2153834 (1999)	total: 35.7s	remaining: 2.05s
2020:	learn: 0.2073753	test: 0.2152981	best: 0.2152981 (2020)	total: 36.1s	remaining: 1.7s
2040:	learn: 0.2071889	test: 0.2152246	best: 0.2152246 (2040)	total: 36.4s	remaining: 1.34s
2060:	learn: 0.2069836	test: 0.2151245	best: 0.2151245 (2060)	total: 36.8s	remaining: 981ms
2080:	learn: 0.2067838	test: 0.2150209	best: 0.2150209 (2080)	total: 37.1s	remaining: 625ms
2100:	learn: 0.2065948	test: 0.2149193	best: 0.2149193 (2100)	total: 37.5s	remaining: 268ms
2115:	learn: 0.2064420	test: 0.2148449	best: 0.2148449 (2115)	total: 37.7s	remaining: 0us
bestTest = 0.2148449372
bestIteration = 2115

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404510	test: 0.6401678	best: 0.6401678 (0)	total: 9.3ms	remaining: 9.3ms
1:	learn: 0.5955294	test: 0.5950090	best: 0.5950090 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5950089979
bestIteration = 1
0:	learn: 0.6415232	test: 0.6411816	best: 0.6411816 (0)	total: 16.3ms	remaining: 43.5s
20:	learn: 0.3349206	test: 0.3323661	best: 0.3323661 (20)	total: 393ms	remaining: 49.6s
40:	learn: 0.3035266	test: 0.3006881	best: 0.3006881 (40)	total: 769ms	remaining: 49.3s
60:	learn: 0.2902518	test: 0.2868429	best: 0.2868429 (60)	total: 1.16s	remaining: 49.7s
80:	learn: 0.2825192	test: 0.2790573	best: 0.2790573 (80)	total: 1.53s	remaining: 48.8s
100:	learn: 0.2760259	test: 0.2720921	best: 0.2720921 (100)	total: 1.89s	remaining: 48.2s
120:	learn: 0.2719580	test: 0.2679707	best: 0.2679707 (120)	total: 2.26s	remaining: 47.6s
140:	learn: 0.2671821	test: 0.2631925	best: 0.2631925 (140)	total: 2.61s	remaining: 46.9s
160:	learn: 0.2637019	test: 0.2596462	best: 0.2596462 (160)	total: 2.98s	remaining: 46.5s
180:	learn: 0.2607799	test: 0.2567024	best: 0.2567024 (180)	total: 3.34s	remaining: 46s
200:	learn: 0.2582973	test: 0.2542811	best: 0.2542811 (200)	total: 3.69s	remaining: 45.4s
220:	learn: 0.2554789	test: 0.2513676	best: 0.2513676 (220)	total: 4.05s	remaining: 44.9s
240:	learn: 0.2530076	test: 0.2487428	best: 0.2487428 (240)	total: 4.42s	remaining: 44.6s
260:	learn: 0.2509798	test: 0.2467680	best: 0.2467680 (260)	total: 4.77s	remaining: 44.1s
280:	learn: 0.2492355	test: 0.2450476	best: 0.2450476 (280)	total: 5.14s	remaining: 43.8s
300:	learn: 0.2475615	test: 0.2434848	best: 0.2434848 (300)	total: 5.48s	remaining: 43.2s
320:	learn: 0.2460756	test: 0.2420450	best: 0.2420450 (320)	total: 5.83s	remaining: 42.7s
340:	learn: 0.2443155	test: 0.2402786	best: 0.2402786 (340)	total: 6.18s	remaining: 42.3s
360:	learn: 0.2430833	test: 0.2391316	best: 0.2391316 (360)	total: 6.54s	remaining: 41.9s
380:	learn: 0.2419228	test: 0.2380560	best: 0.2380560 (380)	total: 6.89s	remaining: 41.4s
400:	learn: 0.2410174	test: 0.2372383	best: 0.2372383 (400)	total: 7.25s	remaining: 41.1s
420:	learn: 0.2399218	test: 0.2362238	best: 0.2362238 (420)	total: 7.61s	remaining: 40.7s
440:	learn: 0.2389196	test: 0.2352749	best: 0.2352749 (440)	total: 7.97s	remaining: 40.3s
460:	learn: 0.2377668	test: 0.2341599	best: 0.2341599 (460)	total: 8.33s	remaining: 40s
480:	learn: 0.2367860	test: 0.2332129	best: 0.2332129 (480)	total: 8.7s	remaining: 39.6s
500:	learn: 0.2359206	test: 0.2324279	best: 0.2324279 (500)	total: 9.04s	remaining: 39.2s
520:	learn: 0.2351090	test: 0.2316888	best: 0.2316888 (520)	total: 9.4s	remaining: 38.8s
540:	learn: 0.2343166	test: 0.2310245	best: 0.2310245 (540)	total: 9.75s	remaining: 38.4s
560:	learn: 0.2335245	test: 0.2303247	best: 0.2303247 (560)	total: 10.1s	remaining: 38s
580:	learn: 0.2328601	test: 0.2297769	best: 0.2297769 (580)	total: 10.4s	remaining: 37.6s
600:	learn: 0.2322081	test: 0.2292224	best: 0.2292224 (600)	total: 10.8s	remaining: 37.2s
620:	learn: 0.2313156	test: 0.2283947	best: 0.2283947 (620)	total: 11.2s	remaining: 36.8s
640:	learn: 0.2306256	test: 0.2277424	best: 0.2277424 (640)	total: 11.5s	remaining: 36.4s
660:	learn: 0.2299480	test: 0.2271552	best: 0.2271552 (660)	total: 11.8s	remaining: 36s
680:	learn: 0.2294171	test: 0.2267389	best: 0.2267389 (680)	total: 12.2s	remaining: 35.6s
700:	learn: 0.2288325	test: 0.2262648	best: 0.2262648 (700)	total: 12.5s	remaining: 35.3s
720:	learn: 0.2281279	test: 0.2256434	best: 0.2256434 (720)	total: 12.9s	remaining: 34.9s
740:	learn: 0.2275397	test: 0.2251563	best: 0.2251563 (740)	total: 13.2s	remaining: 34.5s
760:	learn: 0.2269384	test: 0.2246265	best: 0.2246265 (760)	total: 13.6s	remaining: 34.1s
780:	learn: 0.2263086	test: 0.2240500	best: 0.2240500 (780)	total: 14s	remaining: 33.8s
800:	learn: 0.2257777	test: 0.2236229	best: 0.2236229 (800)	total: 14.3s	remaining: 33.4s
820:	learn: 0.2253506	test: 0.2232666	best: 0.2232666 (820)	total: 14.7s	remaining: 33.1s
840:	learn: 0.2249046	test: 0.2229009	best: 0.2229009 (840)	total: 15s	remaining: 32.7s
860:	learn: 0.2243184	test: 0.2224282	best: 0.2224282 (860)	total: 15.4s	remaining: 32.3s
880:	learn: 0.2238449	test: 0.2220940	best: 0.2220940 (880)	total: 15.7s	remaining: 31.9s
900:	learn: 0.2234580	test: 0.2218155	best: 0.2218155 (900)	total: 16s	remaining: 31.5s
920:	learn: 0.2230528	test: 0.2215059	best: 0.2215059 (920)	total: 16.4s	remaining: 31.2s
940:	learn: 0.2225899	test: 0.2211423	best: 0.2211423 (940)	total: 16.7s	remaining: 30.8s
960:	learn: 0.2221956	test: 0.2208713	best: 0.2208713 (960)	total: 17.1s	remaining: 30.4s
980:	learn: 0.2217795	test: 0.2205642	best: 0.2205642 (980)	total: 17.4s	remaining: 30s
1000:	learn: 0.2213708	test: 0.2202714	best: 0.2202714 (1000)	total: 17.8s	remaining: 29.7s
1020:	learn: 0.2209898	test: 0.2199719	best: 0.2199719 (1020)	total: 18.1s	remaining: 29.3s
1040:	learn: 0.2206743	test: 0.2197740	best: 0.2197740 (1040)	total: 18.5s	remaining: 29s
1060:	learn: 0.2203739	test: 0.2195784	best: 0.2195784 (1060)	total: 18.8s	remaining: 28.6s
1080:	learn: 0.2200508	test: 0.2193444	best: 0.2193444 (1080)	total: 19.2s	remaining: 28.2s
1100:	learn: 0.2196767	test: 0.2190408	best: 0.2190408 (1100)	total: 19.5s	remaining: 27.9s
1120:	learn: 0.2193970	test: 0.2188968	best: 0.2188968 (1120)	total: 19.9s	remaining: 27.5s
1140:	learn: 0.2190312	test: 0.2186791	best: 0.2186791 (1140)	total: 20.2s	remaining: 27.1s
1160:	learn: 0.2186966	test: 0.2184795	best: 0.2184795 (1160)	total: 20.6s	remaining: 26.8s
1180:	learn: 0.2183322	test: 0.2182230	best: 0.2182230 (1180)	total: 20.9s	remaining: 26.4s
1200:	learn: 0.2180253	test: 0.2180106	best: 0.2180106 (1200)	total: 21.3s	remaining: 26s
1220:	learn: 0.2177102	test: 0.2177679	best: 0.2177679 (1220)	total: 21.6s	remaining: 25.7s
1240:	learn: 0.2173280	test: 0.2174352	best: 0.2174352 (1240)	total: 22s	remaining: 25.3s
1260:	learn: 0.2170767	test: 0.2172715	best: 0.2172715 (1260)	total: 22.3s	remaining: 25s
1280:	learn: 0.2167389	test: 0.2170639	best: 0.2170639 (1280)	total: 22.7s	remaining: 24.6s
1300:	learn: 0.2164387	test: 0.2168460	best: 0.2168460 (1300)	total: 23s	remaining: 24.2s
1320:	learn: 0.2161362	test: 0.2166450	best: 0.2166450 (1320)	total: 23.4s	remaining: 23.9s
1340:	learn: 0.2157935	test: 0.2164004	best: 0.2164004 (1340)	total: 23.7s	remaining: 23.5s
1360:	learn: 0.2155104	test: 0.2162138	best: 0.2162138 (1360)	total: 24.1s	remaining: 23.2s
1380:	learn: 0.2151698	test: 0.2159737	best: 0.2159737 (1380)	total: 24.4s	remaining: 22.8s
1400:	learn: 0.2149103	test: 0.2158391	best: 0.2158391 (1400)	total: 24.8s	remaining: 22.5s
1420:	learn: 0.2146246	test: 0.2156567	best: 0.2156567 (1420)	total: 25.1s	remaining: 22.1s
1440:	learn: 0.2144049	test: 0.2155595	best: 0.2155593 (1439)	total: 25.5s	remaining: 21.8s
1460:	learn: 0.2141811	test: 0.2154228	best: 0.2154228 (1460)	total: 25.8s	remaining: 21.4s
1480:	learn: 0.2139107	test: 0.2152601	best: 0.2152601 (1480)	total: 26.2s	remaining: 21s
1500:	learn: 0.2136486	test: 0.2151201	best: 0.2151201 (1500)	total: 26.5s	remaining: 20.7s
1520:	learn: 0.2134396	test: 0.2149838	best: 0.2149838 (1520)	total: 26.9s	remaining: 20.3s
1540:	learn: 0.2131619	test: 0.2148006	best: 0.2148006 (1540)	total: 27.2s	remaining: 20s
1560:	learn: 0.2128891	test: 0.2146505	best: 0.2146505 (1560)	total: 27.6s	remaining: 19.6s
1580:	learn: 0.2126402	test: 0.2145059	best: 0.2145059 (1580)	total: 27.9s	remaining: 19.3s
1600:	learn: 0.2124106	test: 0.2143932	best: 0.2143932 (1600)	total: 28.3s	remaining: 18.9s
1620:	learn: 0.2121783	test: 0.2142635	best: 0.2142635 (1620)	total: 28.6s	remaining: 18.5s
1640:	learn: 0.2119647	test: 0.2141597	best: 0.2141597 (1640)	total: 29s	remaining: 18.2s
1660:	learn: 0.2117484	test: 0.2140390	best: 0.2140390 (1660)	total: 29.3s	remaining: 17.8s
1680:	learn: 0.2115436	test: 0.2139304	best: 0.2139304 (1680)	total: 29.7s	remaining: 17.5s
1700:	learn: 0.2112863	test: 0.2137716	best: 0.2137716 (1700)	total: 30s	remaining: 17.1s
1720:	learn: 0.2110170	test: 0.2135901	best: 0.2135901 (1720)	total: 30.4s	remaining: 16.8s
1740:	learn: 0.2107633	test: 0.2134807	best: 0.2134807 (1740)	total: 30.8s	remaining: 16.4s
1760:	learn: 0.2105442	test: 0.2133937	best: 0.2133937 (1760)	total: 31.1s	remaining: 16.1s
1780:	learn: 0.2103551	test: 0.2133101	best: 0.2133083 (1779)	total: 31.5s	remaining: 15.7s
1800:	learn: 0.2101546	test: 0.2132085	best: 0.2132085 (1800)	total: 31.8s	remaining: 15.4s
1820:	learn: 0.2099302	test: 0.2131036	best: 0.2131036 (1820)	total: 32.2s	remaining: 15s
1840:	learn: 0.2096993	test: 0.2129790	best: 0.2129790 (1840)	total: 32.5s	remaining: 14.7s
1860:	learn: 0.2094622	test: 0.2128162	best: 0.2128162 (1860)	total: 32.9s	remaining: 14.3s
1880:	learn: 0.2092414	test: 0.2126676	best: 0.2126676 (1880)	total: 33.2s	remaining: 14s
1900:	learn: 0.2090210	test: 0.2125334	best: 0.2125334 (1900)	total: 33.6s	remaining: 13.6s
1920:	learn: 0.2087805	test: 0.2123823	best: 0.2123823 (1920)	total: 33.9s	remaining: 13.3s
1940:	learn: 0.2086139	test: 0.2122949	best: 0.2122949 (1940)	total: 34.3s	remaining: 12.9s
1960:	learn: 0.2083900	test: 0.2121602	best: 0.2121602 (1960)	total: 34.6s	remaining: 12.6s
1980:	learn: 0.2081664	test: 0.2120540	best: 0.2120540 (1980)	total: 35s	remaining: 12.2s
2000:	learn: 0.2080132	test: 0.2119898	best: 0.2119898 (2000)	total: 35.4s	remaining: 11.9s
2020:	learn: 0.2078011	test: 0.2118610	best: 0.2118610 (2020)	total: 35.7s	remaining: 11.5s
2040:	learn: 0.2076287	test: 0.2117680	best: 0.2117680 (2040)	total: 36.1s	remaining: 11.1s
2060:	learn: 0.2074164	test: 0.2116679	best: 0.2116679 (2060)	total: 36.4s	remaining: 10.8s
2080:	learn: 0.2072507	test: 0.2115900	best: 0.2115900 (2080)	total: 36.8s	remaining: 10.4s
2100:	learn: 0.2070715	test: 0.2115036	best: 0.2115036 (2100)	total: 37.1s	remaining: 10.1s
2120:	learn: 0.2068645	test: 0.2113800	best: 0.2113800 (2120)	total: 37.5s	remaining: 9.74s
2140:	learn: 0.2066891	test: 0.2112986	best: 0.2112986 (2140)	total: 37.8s	remaining: 9.38s
2160:	learn: 0.2065318	test: 0.2112398	best: 0.2112398 (2160)	total: 38.2s	remaining: 9.03s
2180:	learn: 0.2063649	test: 0.2111766	best: 0.2111766 (2180)	total: 38.6s	remaining: 8.68s
2200:	learn: 0.2061752	test: 0.2111050	best: 0.2111050 (2200)	total: 38.9s	remaining: 8.33s
2220:	learn: 0.2060187	test: 0.2110540	best: 0.2110540 (2220)	total: 39.3s	remaining: 7.97s
2240:	learn: 0.2058228	test: 0.2109669	best: 0.2109669 (2240)	total: 39.6s	remaining: 7.62s
2260:	learn: 0.2055924	test: 0.2107862	best: 0.2107862 (2260)	total: 39.9s	remaining: 7.26s
2280:	learn: 0.2054012	test: 0.2107031	best: 0.2107031 (2280)	total: 40.3s	remaining: 6.91s
2300:	learn: 0.2051988	test: 0.2105510	best: 0.2105510 (2300)	total: 40.7s	remaining: 6.55s
2320:	learn: 0.2049894	test: 0.2104557	best: 0.2104538 (2319)	total: 41s	remaining: 6.2s
2340:	learn: 0.2048160	test: 0.2103766	best: 0.2103766 (2340)	total: 41.4s	remaining: 5.85s
2360:	learn: 0.2046171	test: 0.2102816	best: 0.2102816 (2360)	total: 41.7s	remaining: 5.5s
2380:	learn: 0.2044353	test: 0.2101829	best: 0.2101827 (2379)	total: 42.1s	remaining: 5.14s
2400:	learn: 0.2042777	test: 0.2101151	best: 0.2101151 (2400)	total: 42.4s	remaining: 4.79s
2420:	learn: 0.2040832	test: 0.2099748	best: 0.2099748 (2420)	total: 42.8s	remaining: 4.44s
2440:	learn: 0.2039252	test: 0.2099143	best: 0.2099143 (2440)	total: 43.1s	remaining: 4.08s
2460:	learn: 0.2037509	test: 0.2098429	best: 0.2098429 (2460)	total: 43.5s	remaining: 3.73s
2480:	learn: 0.2035647	test: 0.2097659	best: 0.2097658 (2479)	total: 43.9s	remaining: 3.38s
2500:	learn: 0.2034104	test: 0.2096986	best: 0.2096986 (2500)	total: 44.2s	remaining: 3.02s
2520:	learn: 0.2032713	test: 0.2096404	best: 0.2096401 (2519)	total: 44.6s	remaining: 2.67s
2540:	learn: 0.2030950	test: 0.2095547	best: 0.2095547 (2540)	total: 45s	remaining: 2.32s
2560:	learn: 0.2028996	test: 0.2094581	best: 0.2094574 (2556)	total: 45.3s	remaining: 1.96s
2580:	learn: 0.2027319	test: 0.2093878	best: 0.2093862 (2579)	total: 45.7s	remaining: 1.61s
2600:	learn: 0.2025702	test: 0.2093250	best: 0.2093250 (2600)	total: 46s	remaining: 1.26s
2620:	learn: 0.2024047	test: 0.2092386	best: 0.2092386 (2620)	total: 46.4s	remaining: 902ms
2640:	learn: 0.2022277	test: 0.2091212	best: 0.2091212 (2640)	total: 46.7s	remaining: 549ms
2660:	learn: 0.2020860	test: 0.2090805	best: 0.2090757 (2656)	total: 47.1s	remaining: 195ms
2671:	learn: 0.2019958	test: 0.2090458	best: 0.2090458 (2671)	total: 47.3s	remaining: 0us
bestTest = 0.2090457669
bestIteration = 2671

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6402916	test: 0.6406232	best: 0.6406232 (0)	total: 9.73ms	remaining: 9.73ms
1:	learn: 0.5952605	test: 0.5959131	best: 0.5959131 (1)	total: 18.4ms	remaining: 0us
bestTest = 0.5959131423
bestIteration = 1
0:	learn: 0.6412484	test: 0.6416013	best: 0.6416013 (0)	total: 16.5ms	remaining: 54.6s
20:	learn: 0.3347368	test: 0.3371799	best: 0.3371799 (20)	total: 391ms	remaining: 1m 1s
40:	learn: 0.3026268	test: 0.3055761	best: 0.3055761 (40)	total: 769ms	remaining: 1m 1s
60:	learn: 0.2896528	test: 0.2921023	best: 0.2921023 (60)	total: 1.15s	remaining: 1m 1s
80:	learn: 0.2816636	test: 0.2841652	best: 0.2841652 (80)	total: 1.51s	remaining: 1m
100:	learn: 0.2752492	test: 0.2775981	best: 0.2775981 (100)	total: 1.88s	remaining: 59.6s
120:	learn: 0.2711960	test: 0.2736248	best: 0.2736248 (120)	total: 2.22s	remaining: 58.6s
140:	learn: 0.2673615	test: 0.2697601	best: 0.2697601 (140)	total: 2.57s	remaining: 57.8s
160:	learn: 0.2630155	test: 0.2652665	best: 0.2652665 (160)	total: 2.94s	remaining: 57.6s
180:	learn: 0.2598095	test: 0.2621175	best: 0.2621175 (180)	total: 3.3s	remaining: 57.1s
200:	learn: 0.2568197	test: 0.2590348	best: 0.2590348 (200)	total: 3.67s	remaining: 56.7s
220:	learn: 0.2546428	test: 0.2569275	best: 0.2569275 (220)	total: 4.04s	remaining: 56.5s
240:	learn: 0.2522255	test: 0.2545294	best: 0.2545294 (240)	total: 4.41s	remaining: 56.1s
260:	learn: 0.2504492	test: 0.2527833	best: 0.2527833 (260)	total: 4.75s	remaining: 55.5s
280:	learn: 0.2487721	test: 0.2511455	best: 0.2511455 (280)	total: 5.11s	remaining: 55.1s
300:	learn: 0.2469892	test: 0.2493849	best: 0.2493849 (300)	total: 5.45s	remaining: 54.5s
320:	learn: 0.2454534	test: 0.2479653	best: 0.2479653 (320)	total: 5.8s	remaining: 54s
340:	learn: 0.2441532	test: 0.2467751	best: 0.2467751 (340)	total: 6.15s	remaining: 53.6s
360:	learn: 0.2427840	test: 0.2454222	best: 0.2454222 (360)	total: 6.52s	remaining: 53.3s
380:	learn: 0.2413294	test: 0.2438827	best: 0.2438827 (380)	total: 6.88s	remaining: 52.9s
400:	learn: 0.2400836	test: 0.2427160	best: 0.2427160 (400)	total: 7.23s	remaining: 52.5s
420:	learn: 0.2387893	test: 0.2415050	best: 0.2415050 (420)	total: 7.59s	remaining: 52.1s
440:	learn: 0.2377539	test: 0.2405596	best: 0.2405596 (440)	total: 7.94s	remaining: 51.7s
460:	learn: 0.2367208	test: 0.2395600	best: 0.2395600 (460)	total: 8.3s	remaining: 51.3s
480:	learn: 0.2357680	test: 0.2386814	best: 0.2386814 (480)	total: 8.65s	remaining: 50.9s
500:	learn: 0.2349332	test: 0.2379167	best: 0.2379167 (500)	total: 9.02s	remaining: 50.6s
520:	learn: 0.2339911	test: 0.2370007	best: 0.2370007 (520)	total: 9.38s	remaining: 50.2s
540:	learn: 0.2331770	test: 0.2362668	best: 0.2362668 (540)	total: 9.74s	remaining: 49.9s
560:	learn: 0.2324094	test: 0.2355230	best: 0.2355230 (560)	total: 10.1s	remaining: 49.5s
580:	learn: 0.2315550	test: 0.2347935	best: 0.2347935 (580)	total: 10.4s	remaining: 49.1s
600:	learn: 0.2307690	test: 0.2340721	best: 0.2340721 (600)	total: 10.8s	remaining: 48.7s
620:	learn: 0.2300216	test: 0.2334510	best: 0.2334510 (620)	total: 11.2s	remaining: 48.4s
640:	learn: 0.2294774	test: 0.2330043	best: 0.2330043 (640)	total: 11.5s	remaining: 48s
660:	learn: 0.2288247	test: 0.2324839	best: 0.2324839 (660)	total: 11.9s	remaining: 47.7s
680:	learn: 0.2282110	test: 0.2319925	best: 0.2319925 (680)	total: 12.2s	remaining: 47.3s
700:	learn: 0.2276270	test: 0.2315272	best: 0.2315272 (700)	total: 12.6s	remaining: 46.9s
720:	learn: 0.2269616	test: 0.2309010	best: 0.2309010 (720)	total: 13s	remaining: 46.5s
740:	learn: 0.2264398	test: 0.2304909	best: 0.2304909 (740)	total: 13.3s	remaining: 46.1s
760:	learn: 0.2259851	test: 0.2301583	best: 0.2301583 (760)	total: 13.6s	remaining: 45.7s
780:	learn: 0.2254832	test: 0.2297977	best: 0.2297977 (780)	total: 14s	remaining: 45.2s
800:	learn: 0.2249002	test: 0.2293293	best: 0.2293293 (800)	total: 14.3s	remaining: 44.8s
820:	learn: 0.2244297	test: 0.2289793	best: 0.2289793 (820)	total: 14.7s	remaining: 44.5s
840:	learn: 0.2238892	test: 0.2285378	best: 0.2285378 (840)	total: 15s	remaining: 44.1s
860:	learn: 0.2233663	test: 0.2281015	best: 0.2281015 (860)	total: 15.4s	remaining: 43.7s
880:	learn: 0.2229712	test: 0.2278054	best: 0.2278054 (880)	total: 15.7s	remaining: 43.4s
900:	learn: 0.2225066	test: 0.2274470	best: 0.2274470 (900)	total: 16.1s	remaining: 43s
920:	learn: 0.2221083	test: 0.2271221	best: 0.2271221 (920)	total: 16.4s	remaining: 42.6s
940:	learn: 0.2216544	test: 0.2267525	best: 0.2267525 (940)	total: 16.8s	remaining: 42.3s
960:	learn: 0.2212161	test: 0.2264171	best: 0.2264171 (960)	total: 17.1s	remaining: 41.9s
980:	learn: 0.2208483	test: 0.2261769	best: 0.2261769 (980)	total: 17.5s	remaining: 41.5s
1000:	learn: 0.2205054	test: 0.2259526	best: 0.2259526 (1000)	total: 17.8s	remaining: 41.2s
1020:	learn: 0.2201149	test: 0.2256811	best: 0.2256811 (1020)	total: 18.2s	remaining: 40.8s
1040:	learn: 0.2197225	test: 0.2253928	best: 0.2253928 (1040)	total: 18.6s	remaining: 40.5s
1060:	learn: 0.2193728	test: 0.2251209	best: 0.2251209 (1060)	total: 18.9s	remaining: 40.1s
1080:	learn: 0.2190552	test: 0.2249216	best: 0.2249216 (1080)	total: 19.3s	remaining: 39.7s
1100:	learn: 0.2186324	test: 0.2246087	best: 0.2246087 (1100)	total: 19.6s	remaining: 39.4s
1120:	learn: 0.2182401	test: 0.2243023	best: 0.2243023 (1120)	total: 20s	remaining: 39s
1140:	learn: 0.2179288	test: 0.2240859	best: 0.2240859 (1140)	total: 20.3s	remaining: 38.7s
1160:	learn: 0.2175952	test: 0.2238563	best: 0.2238563 (1160)	total: 20.7s	remaining: 38.3s
1180:	learn: 0.2172857	test: 0.2236310	best: 0.2236310 (1180)	total: 21s	remaining: 38s
1200:	learn: 0.2169578	test: 0.2234072	best: 0.2234072 (1200)	total: 21.4s	remaining: 37.6s
1220:	learn: 0.2166810	test: 0.2232520	best: 0.2232520 (1220)	total: 21.8s	remaining: 37.2s
1240:	learn: 0.2163674	test: 0.2230893	best: 0.2230893 (1240)	total: 22.1s	remaining: 36.9s
1260:	learn: 0.2160283	test: 0.2228507	best: 0.2228507 (1260)	total: 22.5s	remaining: 36.5s
1280:	learn: 0.2156710	test: 0.2225822	best: 0.2225822 (1280)	total: 22.8s	remaining: 36.1s
1300:	learn: 0.2153797	test: 0.2224078	best: 0.2224078 (1300)	total: 23.2s	remaining: 35.8s
1320:	learn: 0.2150680	test: 0.2221942	best: 0.2221942 (1320)	total: 23.5s	remaining: 35.4s
1340:	learn: 0.2146694	test: 0.2218525	best: 0.2218525 (1340)	total: 23.9s	remaining: 35.1s
1360:	learn: 0.2143969	test: 0.2216804	best: 0.2216804 (1360)	total: 24.2s	remaining: 34.7s
1380:	learn: 0.2141100	test: 0.2214786	best: 0.2214786 (1380)	total: 24.6s	remaining: 34.4s
1400:	learn: 0.2138130	test: 0.2212882	best: 0.2212882 (1400)	total: 24.9s	remaining: 34s
1420:	learn: 0.2135697	test: 0.2211477	best: 0.2211477 (1420)	total: 25.3s	remaining: 33.6s
1440:	learn: 0.2133139	test: 0.2210143	best: 0.2210143 (1440)	total: 25.6s	remaining: 33.3s
1460:	learn: 0.2130487	test: 0.2208648	best: 0.2208648 (1460)	total: 26s	remaining: 32.9s
1480:	learn: 0.2127541	test: 0.2206566	best: 0.2206566 (1480)	total: 26.3s	remaining: 32.5s
1500:	learn: 0.2124298	test: 0.2204419	best: 0.2204419 (1500)	total: 26.7s	remaining: 32.2s
1520:	learn: 0.2121747	test: 0.2203043	best: 0.2203042 (1519)	total: 27s	remaining: 31.8s
1540:	learn: 0.2118775	test: 0.2201425	best: 0.2201351 (1539)	total: 27.4s	remaining: 31.5s
1560:	learn: 0.2116221	test: 0.2199808	best: 0.2199808 (1560)	total: 27.8s	remaining: 31.1s
1580:	learn: 0.2113672	test: 0.2198130	best: 0.2198130 (1580)	total: 28.1s	remaining: 30.7s
1600:	learn: 0.2110985	test: 0.2196532	best: 0.2196477 (1598)	total: 28.5s	remaining: 30.4s
1620:	learn: 0.2108893	test: 0.2195448	best: 0.2195445 (1618)	total: 28.8s	remaining: 30s
1640:	learn: 0.2106281	test: 0.2193973	best: 0.2193973 (1640)	total: 29.2s	remaining: 29.7s
1660:	learn: 0.2103746	test: 0.2192675	best: 0.2192675 (1660)	total: 29.5s	remaining: 29.3s
1680:	learn: 0.2101585	test: 0.2191473	best: 0.2191473 (1680)	total: 29.9s	remaining: 29s
1700:	learn: 0.2098927	test: 0.2190270	best: 0.2190270 (1700)	total: 30.2s	remaining: 28.6s
1720:	learn: 0.2096946	test: 0.2189300	best: 0.2189300 (1720)	total: 30.6s	remaining: 28.2s
1740:	learn: 0.2094571	test: 0.2187999	best: 0.2187999 (1740)	total: 30.9s	remaining: 27.9s
1760:	learn: 0.2092570	test: 0.2186794	best: 0.2186794 (1760)	total: 31.3s	remaining: 27.5s
1780:	learn: 0.2090384	test: 0.2185628	best: 0.2185628 (1780)	total: 31.7s	remaining: 27.2s
1800:	learn: 0.2088412	test: 0.2184646	best: 0.2184646 (1800)	total: 32s	remaining: 26.9s
1820:	learn: 0.2086160	test: 0.2183206	best: 0.2183206 (1820)	total: 32.4s	remaining: 26.5s
1840:	learn: 0.2084086	test: 0.2182129	best: 0.2182129 (1840)	total: 32.8s	remaining: 26.2s
1860:	learn: 0.2081721	test: 0.2180882	best: 0.2180882 (1860)	total: 33.1s	remaining: 25.8s
1880:	learn: 0.2079302	test: 0.2179230	best: 0.2179230 (1880)	total: 33.5s	remaining: 25.4s
1900:	learn: 0.2077099	test: 0.2178078	best: 0.2178078 (1900)	total: 33.8s	remaining: 25.1s
1920:	learn: 0.2074950	test: 0.2177104	best: 0.2177104 (1920)	total: 34.2s	remaining: 24.7s
1940:	learn: 0.2072730	test: 0.2175853	best: 0.2175853 (1940)	total: 34.5s	remaining: 24.4s
1960:	learn: 0.2070391	test: 0.2174415	best: 0.2174415 (1960)	total: 34.9s	remaining: 24s
1980:	learn: 0.2067957	test: 0.2172914	best: 0.2172914 (1980)	total: 35.3s	remaining: 23.7s
2000:	learn: 0.2066081	test: 0.2172006	best: 0.2172006 (2000)	total: 35.6s	remaining: 23.3s
2020:	learn: 0.2063876	test: 0.2170946	best: 0.2170946 (2020)	total: 36s	remaining: 23s
2040:	learn: 0.2062097	test: 0.2170124	best: 0.2170124 (2040)	total: 36.3s	remaining: 22.6s
2060:	learn: 0.2060199	test: 0.2169534	best: 0.2169530 (2059)	total: 36.7s	remaining: 22.2s
2080:	learn: 0.2057938	test: 0.2168422	best: 0.2168422 (2080)	total: 37s	remaining: 21.9s
2100:	learn: 0.2055934	test: 0.2167533	best: 0.2167533 (2100)	total: 37.4s	remaining: 21.5s
2120:	learn: 0.2054009	test: 0.2166611	best: 0.2166596 (2118)	total: 37.7s	remaining: 21.2s
2140:	learn: 0.2051788	test: 0.2165576	best: 0.2165576 (2140)	total: 38.1s	remaining: 20.8s
2160:	learn: 0.2050081	test: 0.2164841	best: 0.2164841 (2160)	total: 38.4s	remaining: 20.4s
2180:	learn: 0.2048108	test: 0.2163846	best: 0.2163834 (2179)	total: 38.8s	remaining: 20.1s
2200:	learn: 0.2046287	test: 0.2163288	best: 0.2163288 (2200)	total: 39.1s	remaining: 19.7s
2220:	learn: 0.2043840	test: 0.2161490	best: 0.2161490 (2220)	total: 39.5s	remaining: 19.4s
2240:	learn: 0.2042160	test: 0.2160847	best: 0.2160847 (2240)	total: 39.8s	remaining: 19s
2260:	learn: 0.2040210	test: 0.2160083	best: 0.2160083 (2260)	total: 40.2s	remaining: 18.6s
2280:	learn: 0.2038396	test: 0.2159391	best: 0.2159391 (2280)	total: 40.5s	remaining: 18.3s
2300:	learn: 0.2036645	test: 0.2158420	best: 0.2158420 (2300)	total: 40.9s	remaining: 17.9s
2320:	learn: 0.2034916	test: 0.2157811	best: 0.2157802 (2319)	total: 41.2s	remaining: 17.6s
2340:	learn: 0.2033195	test: 0.2157155	best: 0.2157155 (2340)	total: 41.6s	remaining: 17.2s
2360:	learn: 0.2031418	test: 0.2156086	best: 0.2156086 (2360)	total: 41.9s	remaining: 16.9s
2380:	learn: 0.2029870	test: 0.2155681	best: 0.2155681 (2380)	total: 42.3s	remaining: 16.5s
2400:	learn: 0.2027789	test: 0.2154456	best: 0.2154456 (2400)	total: 42.6s	remaining: 16.2s
2420:	learn: 0.2026244	test: 0.2154090	best: 0.2154090 (2420)	total: 43s	remaining: 15.8s
2440:	learn: 0.2024693	test: 0.2153427	best: 0.2153427 (2440)	total: 43.4s	remaining: 15.5s
2460:	learn: 0.2022797	test: 0.2152676	best: 0.2152676 (2460)	total: 43.7s	remaining: 15.1s
2480:	learn: 0.2021005	test: 0.2151894	best: 0.2151894 (2480)	total: 44.1s	remaining: 14.7s
2500:	learn: 0.2019322	test: 0.2151263	best: 0.2151263 (2500)	total: 44.4s	remaining: 14.4s
2520:	learn: 0.2017186	test: 0.2149821	best: 0.2149821 (2520)	total: 44.8s	remaining: 14s
2540:	learn: 0.2015435	test: 0.2149121	best: 0.2149115 (2539)	total: 45.1s	remaining: 13.7s
2560:	learn: 0.2013544	test: 0.2148228	best: 0.2148228 (2560)	total: 45.5s	remaining: 13.3s
2580:	learn: 0.2011736	test: 0.2147316	best: 0.2147316 (2580)	total: 45.8s	remaining: 13s
2600:	learn: 0.2010220	test: 0.2146500	best: 0.2146494 (2599)	total: 46.2s	remaining: 12.6s
2620:	learn: 0.2008425	test: 0.2145846	best: 0.2145846 (2620)	total: 46.6s	remaining: 12.3s
2640:	learn: 0.2006893	test: 0.2145175	best: 0.2145175 (2640)	total: 46.9s	remaining: 11.9s
2660:	learn: 0.2005346	test: 0.2144672	best: 0.2144672 (2660)	total: 47.3s	remaining: 11.5s
2680:	learn: 0.2003758	test: 0.2143979	best: 0.2143979 (2680)	total: 47.6s	remaining: 11.2s
2700:	learn: 0.2002081	test: 0.2143372	best: 0.2143372 (2700)	total: 48s	remaining: 10.8s
2720:	learn: 0.2000765	test: 0.2142956	best: 0.2142947 (2718)	total: 48.4s	remaining: 10.5s
2740:	learn: 0.1998895	test: 0.2142226	best: 0.2142226 (2740)	total: 48.7s	remaining: 10.1s
2760:	learn: 0.1997383	test: 0.2141564	best: 0.2141564 (2760)	total: 49.1s	remaining: 9.78s
2780:	learn: 0.1995762	test: 0.2140976	best: 0.2140974 (2779)	total: 49.4s	remaining: 9.42s
2800:	learn: 0.1993828	test: 0.2140234	best: 0.2140208 (2799)	total: 49.8s	remaining: 9.07s
2820:	learn: 0.1991976	test: 0.2139429	best: 0.2139387 (2819)	total: 50.2s	remaining: 8.71s
2840:	learn: 0.1990245	test: 0.2138609	best: 0.2138609 (2840)	total: 50.5s	remaining: 8.36s
2860:	learn: 0.1988812	test: 0.2138128	best: 0.2138128 (2860)	total: 50.9s	remaining: 8s
2880:	learn: 0.1987068	test: 0.2137420	best: 0.2137420 (2880)	total: 51.2s	remaining: 7.64s
2900:	learn: 0.1985663	test: 0.2137207	best: 0.2137182 (2899)	total: 51.6s	remaining: 7.29s
2920:	learn: 0.1984077	test: 0.2136519	best: 0.2136519 (2920)	total: 51.9s	remaining: 6.93s
2940:	learn: 0.1982653	test: 0.2135983	best: 0.2135983 (2940)	total: 52.3s	remaining: 6.58s
2960:	learn: 0.1981094	test: 0.2135376	best: 0.2135376 (2960)	total: 52.7s	remaining: 6.23s
2980:	learn: 0.1979654	test: 0.2135166	best: 0.2135166 (2980)	total: 53s	remaining: 5.87s
3000:	learn: 0.1978306	test: 0.2134687	best: 0.2134687 (3000)	total: 53.4s	remaining: 5.52s
3020:	learn: 0.1976861	test: 0.2134298	best: 0.2134298 (3020)	total: 53.8s	remaining: 5.16s
3040:	learn: 0.1975499	test: 0.2133693	best: 0.2133693 (3040)	total: 54.1s	remaining: 4.81s
3060:	learn: 0.1974135	test: 0.2133135	best: 0.2133135 (3060)	total: 54.5s	remaining: 4.45s
3080:	learn: 0.1972517	test: 0.2132553	best: 0.2132553 (3080)	total: 54.9s	remaining: 4.09s
3100:	learn: 0.1970969	test: 0.2132144	best: 0.2132115 (3099)	total: 55.2s	remaining: 3.74s
3120:	learn: 0.1969505	test: 0.2131792	best: 0.2131758 (3118)	total: 55.6s	remaining: 3.38s
3140:	learn: 0.1968123	test: 0.2131349	best: 0.2131349 (3140)	total: 55.9s	remaining: 3.03s
3160:	learn: 0.1966678	test: 0.2130975	best: 0.2130961 (3159)	total: 56.3s	remaining: 2.67s
3180:	learn: 0.1965094	test: 0.2130408	best: 0.2130408 (3180)	total: 56.6s	remaining: 2.31s
3200:	learn: 0.1963743	test: 0.2130257	best: 0.2130240 (3196)	total: 57s	remaining: 1.96s
3220:	learn: 0.1962420	test: 0.2130078	best: 0.2130051 (3219)	total: 57.4s	remaining: 1.6s
3240:	learn: 0.1960895	test: 0.2129546	best: 0.2129546 (3240)	total: 57.7s	remaining: 1.25s
3260:	learn: 0.1959360	test: 0.2128960	best: 0.2128941 (3259)	total: 58.1s	remaining: 891ms
3280:	learn: 0.1958162	test: 0.2128577	best: 0.2128577 (3280)	total: 58.4s	remaining: 534ms
3300:	learn: 0.1956779	test: 0.2128376	best: 0.2128370 (3294)	total: 58.8s	remaining: 178ms
3310:	learn: 0.1956142	test: 0.2128144	best: 0.2128144 (3310)	total: 59s	remaining: 0us
bestTest = 0.2128143852
bestIteration = 3310

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6405174	test: 0.6405767	best: 0.6405767 (0)	total: 9.13ms	remaining: 9.13ms
1:	learn: 0.5956592	test: 0.5957290	best: 0.5957290 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5957290478
bestIteration = 1
0:	learn: 0.6412850	test: 0.6413004	best: 0.6413004 (0)	total: 16.7ms	remaining: 1m 22s
20:	learn: 0.3356640	test: 0.3340889	best: 0.3340889 (20)	total: 403ms	remaining: 1m 34s
40:	learn: 0.3029197	test: 0.3007273	best: 0.3007273 (40)	total: 776ms	remaining: 1m 32s
60:	learn: 0.2893793	test: 0.2864305	best: 0.2864305 (60)	total: 1.18s	remaining: 1m 34s
80:	learn: 0.2814489	test: 0.2784145	best: 0.2784145 (80)	total: 1.53s	remaining: 1m 31s
100:	learn: 0.2759530	test: 0.2728259	best: 0.2728259 (100)	total: 1.89s	remaining: 1m 30s
120:	learn: 0.2713104	test: 0.2681659	best: 0.2681659 (120)	total: 2.26s	remaining: 1m 29s
140:	learn: 0.2671310	test: 0.2639126	best: 0.2639126 (140)	total: 2.62s	remaining: 1m 28s
160:	learn: 0.2632901	test: 0.2600854	best: 0.2600854 (160)	total: 2.98s	remaining: 1m 28s
180:	learn: 0.2599895	test: 0.2567819	best: 0.2567819 (180)	total: 3.35s	remaining: 1m 27s
200:	learn: 0.2571070	test: 0.2540284	best: 0.2540284 (200)	total: 3.7s	remaining: 1m 27s
220:	learn: 0.2548292	test: 0.2517641	best: 0.2517641 (220)	total: 4.07s	remaining: 1m 26s
240:	learn: 0.2528191	test: 0.2498421	best: 0.2498421 (240)	total: 4.43s	remaining: 1m 26s
260:	learn: 0.2505609	test: 0.2475809	best: 0.2475809 (260)	total: 4.79s	remaining: 1m 25s
280:	learn: 0.2486614	test: 0.2457905	best: 0.2457905 (280)	total: 5.14s	remaining: 1m 25s
300:	learn: 0.2472202	test: 0.2445108	best: 0.2445108 (300)	total: 5.5s	remaining: 1m 24s
320:	learn: 0.2459209	test: 0.2432922	best: 0.2432922 (320)	total: 5.84s	remaining: 1m 23s
340:	learn: 0.2446252	test: 0.2421023	best: 0.2421023 (340)	total: 6.2s	remaining: 1m 23s
360:	learn: 0.2430813	test: 0.2406041	best: 0.2406041 (360)	total: 6.56s	remaining: 1m 22s
380:	learn: 0.2418355	test: 0.2395007	best: 0.2395007 (380)	total: 6.91s	remaining: 1m 22s
400:	learn: 0.2405261	test: 0.2383257	best: 0.2383257 (400)	total: 7.27s	remaining: 1m 22s
420:	learn: 0.2394337	test: 0.2373583	best: 0.2373583 (420)	total: 7.63s	remaining: 1m 21s
440:	learn: 0.2383161	test: 0.2364082	best: 0.2364082 (440)	total: 8s	remaining: 1m 21s
460:	learn: 0.2373777	test: 0.2355830	best: 0.2355830 (460)	total: 8.35s	remaining: 1m 20s
480:	learn: 0.2364099	test: 0.2347797	best: 0.2347797 (480)	total: 8.71s	remaining: 1m 20s
500:	learn: 0.2354444	test: 0.2339308	best: 0.2339308 (500)	total: 9.07s	remaining: 1m 20s
520:	learn: 0.2345655	test: 0.2331886	best: 0.2331886 (520)	total: 9.43s	remaining: 1m 19s
540:	learn: 0.2337237	test: 0.2325381	best: 0.2325381 (540)	total: 9.77s	remaining: 1m 19s
560:	learn: 0.2328543	test: 0.2318130	best: 0.2318130 (560)	total: 10.1s	remaining: 1m 18s
580:	learn: 0.2320315	test: 0.2310901	best: 0.2310901 (580)	total: 10.5s	remaining: 1m 18s
600:	learn: 0.2312679	test: 0.2303858	best: 0.2303858 (600)	total: 10.8s	remaining: 1m 17s
620:	learn: 0.2306152	test: 0.2299384	best: 0.2299384 (620)	total: 11.2s	remaining: 1m 17s
640:	learn: 0.2299980	test: 0.2294554	best: 0.2294554 (640)	total: 11.5s	remaining: 1m 17s
660:	learn: 0.2293431	test: 0.2289139	best: 0.2289139 (660)	total: 11.9s	remaining: 1m 16s
680:	learn: 0.2287453	test: 0.2284444	best: 0.2284444 (680)	total: 12.2s	remaining: 1m 16s
700:	learn: 0.2280318	test: 0.2278349	best: 0.2278349 (700)	total: 12.6s	remaining: 1m 15s
720:	learn: 0.2274212	test: 0.2273288	best: 0.2273288 (720)	total: 12.9s	remaining: 1m 15s
740:	learn: 0.2269367	test: 0.2269632	best: 0.2269632 (740)	total: 13.3s	remaining: 1m 15s
760:	learn: 0.2263421	test: 0.2265256	best: 0.2265256 (760)	total: 13.6s	remaining: 1m 14s
780:	learn: 0.2258522	test: 0.2261433	best: 0.2261433 (780)	total: 14s	remaining: 1m 14s
800:	learn: 0.2253062	test: 0.2257040	best: 0.2257040 (800)	total: 14.3s	remaining: 1m 13s
820:	learn: 0.2248277	test: 0.2253568	best: 0.2253568 (820)	total: 14.6s	remaining: 1m 13s
840:	learn: 0.2243314	test: 0.2250070	best: 0.2250070 (840)	total: 15s	remaining: 1m 12s
860:	learn: 0.2238691	test: 0.2247002	best: 0.2247002 (860)	total: 15.3s	remaining: 1m 12s
880:	learn: 0.2233242	test: 0.2242616	best: 0.2242616 (880)	total: 15.7s	remaining: 1m 12s
900:	learn: 0.2228472	test: 0.2238535	best: 0.2238535 (900)	total: 16s	remaining: 1m 11s
920:	learn: 0.2224804	test: 0.2236351	best: 0.2236351 (920)	total: 16.4s	remaining: 1m 11s
940:	learn: 0.2220545	test: 0.2233377	best: 0.2233377 (940)	total: 16.7s	remaining: 1m 10s
960:	learn: 0.2216646	test: 0.2231023	best: 0.2231023 (960)	total: 17.1s	remaining: 1m 10s
980:	learn: 0.2212583	test: 0.2228047	best: 0.2228047 (980)	total: 17.4s	remaining: 1m 10s
1000:	learn: 0.2208772	test: 0.2225228	best: 0.2225228 (1000)	total: 17.8s	remaining: 1m 9s
1020:	learn: 0.2205052	test: 0.2222971	best: 0.2222971 (1020)	total: 18.1s	remaining: 1m 9s
1040:	learn: 0.2200692	test: 0.2219644	best: 0.2219644 (1040)	total: 18.5s	remaining: 1m 9s
1060:	learn: 0.2196995	test: 0.2217204	best: 0.2217204 (1060)	total: 18.9s	remaining: 1m 8s
1080:	learn: 0.2193602	test: 0.2214954	best: 0.2214954 (1080)	total: 19.2s	remaining: 1m 8s
1100:	learn: 0.2190432	test: 0.2212867	best: 0.2212867 (1100)	total: 19.5s	remaining: 1m 7s
1120:	learn: 0.2186878	test: 0.2210504	best: 0.2210504 (1120)	total: 19.9s	remaining: 1m 7s
1140:	learn: 0.2183965	test: 0.2208965	best: 0.2208965 (1140)	total: 20.2s	remaining: 1m 7s
1160:	learn: 0.2180861	test: 0.2206972	best: 0.2206972 (1160)	total: 20.6s	remaining: 1m 6s
1180:	learn: 0.2177246	test: 0.2204215	best: 0.2204215 (1180)	total: 20.9s	remaining: 1m 6s
1200:	learn: 0.2174043	test: 0.2201860	best: 0.2201860 (1200)	total: 21.3s	remaining: 1m 6s
1220:	learn: 0.2170984	test: 0.2199977	best: 0.2199977 (1220)	total: 21.6s	remaining: 1m 5s
1240:	learn: 0.2167817	test: 0.2198213	best: 0.2198213 (1240)	total: 22s	remaining: 1m 5s
1260:	learn: 0.2164583	test: 0.2196107	best: 0.2196107 (1260)	total: 22.3s	remaining: 1m 4s
1280:	learn: 0.2161858	test: 0.2194641	best: 0.2194641 (1280)	total: 22.7s	remaining: 1m 4s
1300:	learn: 0.2158989	test: 0.2193274	best: 0.2193274 (1300)	total: 23s	remaining: 1m 4s
1320:	learn: 0.2155861	test: 0.2191243	best: 0.2191243 (1320)	total: 23.4s	remaining: 1m 3s
1340:	learn: 0.2153243	test: 0.2189949	best: 0.2189949 (1340)	total: 23.7s	remaining: 1m 3s
1360:	learn: 0.2150027	test: 0.2187968	best: 0.2187968 (1360)	total: 24.1s	remaining: 1m 3s
1380:	learn: 0.2146972	test: 0.2185720	best: 0.2185720 (1380)	total: 24.5s	remaining: 1m 2s
1400:	learn: 0.2144505	test: 0.2184749	best: 0.2184749 (1400)	total: 24.8s	remaining: 1m 2s
1420:	learn: 0.2141869	test: 0.2183585	best: 0.2183585 (1420)	total: 25.2s	remaining: 1m 2s
1440:	learn: 0.2138837	test: 0.2181702	best: 0.2181702 (1440)	total: 25.5s	remaining: 1m 1s
1460:	learn: 0.2135802	test: 0.2180127	best: 0.2180127 (1460)	total: 25.9s	remaining: 1m 1s
1480:	learn: 0.2133312	test: 0.2178910	best: 0.2178910 (1480)	total: 26.2s	remaining: 1m 1s
1500:	learn: 0.2130413	test: 0.2177411	best: 0.2177411 (1500)	total: 26.6s	remaining: 1m
1520:	learn: 0.2127386	test: 0.2175545	best: 0.2175545 (1520)	total: 26.9s	remaining: 1m
1540:	learn: 0.2124856	test: 0.2174295	best: 0.2174287 (1539)	total: 27.3s	remaining: 60s
1560:	learn: 0.2122563	test: 0.2173218	best: 0.2173218 (1560)	total: 27.6s	remaining: 59.6s
1580:	learn: 0.2120121	test: 0.2171775	best: 0.2171775 (1580)	total: 28s	remaining: 59.2s
1600:	learn: 0.2116790	test: 0.2170149	best: 0.2170149 (1600)	total: 28.3s	remaining: 58.9s
1620:	learn: 0.2113841	test: 0.2168627	best: 0.2168627 (1620)	total: 28.7s	remaining: 58.5s
1640:	learn: 0.2111640	test: 0.2167487	best: 0.2167487 (1640)	total: 29s	remaining: 58.2s
1660:	learn: 0.2109407	test: 0.2166504	best: 0.2166504 (1660)	total: 29.4s	remaining: 57.8s
1680:	learn: 0.2107434	test: 0.2165607	best: 0.2165607 (1680)	total: 29.7s	remaining: 57.4s
1700:	learn: 0.2105414	test: 0.2164500	best: 0.2164494 (1699)	total: 30.1s	remaining: 57.1s
1720:	learn: 0.2103300	test: 0.2163119	best: 0.2163119 (1720)	total: 30.5s	remaining: 56.8s
1740:	learn: 0.2101289	test: 0.2162329	best: 0.2162329 (1740)	total: 30.8s	remaining: 56.4s
1760:	learn: 0.2098859	test: 0.2161209	best: 0.2161206 (1759)	total: 31.2s	remaining: 56s
1780:	learn: 0.2096844	test: 0.2160277	best: 0.2160277 (1780)	total: 31.5s	remaining: 55.7s
1800:	learn: 0.2094490	test: 0.2159376	best: 0.2159376 (1800)	total: 31.9s	remaining: 55.3s
1820:	learn: 0.2092305	test: 0.2158278	best: 0.2158278 (1820)	total: 32.2s	remaining: 55s
1840:	learn: 0.2090236	test: 0.2157218	best: 0.2157218 (1840)	total: 32.6s	remaining: 54.6s
1860:	learn: 0.2087472	test: 0.2155567	best: 0.2155567 (1860)	total: 32.9s	remaining: 54.2s
1880:	learn: 0.2085765	test: 0.2154783	best: 0.2154783 (1880)	total: 33.3s	remaining: 53.9s
1900:	learn: 0.2083430	test: 0.2153366	best: 0.2153366 (1900)	total: 33.6s	remaining: 53.6s
1920:	learn: 0.2081372	test: 0.2152494	best: 0.2152486 (1919)	total: 34s	remaining: 53.2s
1940:	learn: 0.2079281	test: 0.2151310	best: 0.2151310 (1940)	total: 34.3s	remaining: 52.8s
1960:	learn: 0.2076952	test: 0.2150226	best: 0.2150226 (1960)	total: 34.7s	remaining: 52.5s
1980:	learn: 0.2075289	test: 0.2149441	best: 0.2149441 (1980)	total: 35.1s	remaining: 52.2s
2000:	learn: 0.2072902	test: 0.2147878	best: 0.2147878 (2000)	total: 35.4s	remaining: 51.8s
2020:	learn: 0.2071007	test: 0.2147000	best: 0.2147000 (2020)	total: 35.8s	remaining: 51.5s
2040:	learn: 0.2068910	test: 0.2145995	best: 0.2145995 (2040)	total: 36.1s	remaining: 51.1s
2060:	learn: 0.2067179	test: 0.2145068	best: 0.2145068 (2060)	total: 36.5s	remaining: 50.8s
2080:	learn: 0.2065216	test: 0.2144395	best: 0.2144384 (2077)	total: 36.8s	remaining: 50.4s
2100:	learn: 0.2063271	test: 0.2143642	best: 0.2143642 (2100)	total: 37.2s	remaining: 50.1s
2120:	learn: 0.2061496	test: 0.2143155	best: 0.2143155 (2120)	total: 37.6s	remaining: 49.7s
2140:	learn: 0.2059392	test: 0.2142414	best: 0.2142414 (2140)	total: 37.9s	remaining: 49.4s
2160:	learn: 0.2057322	test: 0.2141579	best: 0.2141579 (2160)	total: 38.3s	remaining: 49s
2180:	learn: 0.2055516	test: 0.2140740	best: 0.2140724 (2179)	total: 38.6s	remaining: 48.7s
2200:	learn: 0.2053605	test: 0.2139772	best: 0.2139772 (2200)	total: 39s	remaining: 48.3s
2220:	learn: 0.2051933	test: 0.2139197	best: 0.2139197 (2220)	total: 39.3s	remaining: 48s
2240:	learn: 0.2050116	test: 0.2138225	best: 0.2138225 (2240)	total: 39.7s	remaining: 47.6s
2260:	learn: 0.2048167	test: 0.2137688	best: 0.2137688 (2259)	total: 40.1s	remaining: 47.3s
2280:	learn: 0.2046275	test: 0.2136908	best: 0.2136908 (2280)	total: 40.4s	remaining: 46.9s
2300:	learn: 0.2044731	test: 0.2136529	best: 0.2136529 (2300)	total: 40.8s	remaining: 46.6s
2320:	learn: 0.2043237	test: 0.2136126	best: 0.2136126 (2320)	total: 41.1s	remaining: 46.2s
2340:	learn: 0.2041806	test: 0.2135606	best: 0.2135606 (2340)	total: 41.5s	remaining: 45.9s
2360:	learn: 0.2040419	test: 0.2135195	best: 0.2135195 (2360)	total: 41.9s	remaining: 45.5s
2380:	learn: 0.2038655	test: 0.2134619	best: 0.2134619 (2380)	total: 42.2s	remaining: 45.1s
2400:	learn: 0.2036883	test: 0.2134074	best: 0.2134062 (2396)	total: 42.6s	remaining: 44.8s
2420:	learn: 0.2035114	test: 0.2133302	best: 0.2133302 (2420)	total: 42.9s	remaining: 44.4s
2440:	learn: 0.2033095	test: 0.2132230	best: 0.2132230 (2440)	total: 43.3s	remaining: 44.1s
2460:	learn: 0.2031471	test: 0.2131714	best: 0.2131714 (2460)	total: 43.6s	remaining: 43.7s
2480:	learn: 0.2029696	test: 0.2131017	best: 0.2131017 (2480)	total: 44s	remaining: 43.4s
2500:	learn: 0.2028108	test: 0.2130596	best: 0.2130596 (2500)	total: 44.3s	remaining: 43s
2520:	learn: 0.2026571	test: 0.2129987	best: 0.2129987 (2520)	total: 44.7s	remaining: 42.7s
2540:	learn: 0.2024717	test: 0.2129410	best: 0.2129410 (2540)	total: 45s	remaining: 42.3s
2560:	learn: 0.2023088	test: 0.2128979	best: 0.2128958 (2558)	total: 45.4s	remaining: 41.9s
2580:	learn: 0.2021379	test: 0.2128181	best: 0.2128181 (2580)	total: 45.8s	remaining: 41.6s
2600:	learn: 0.2019950	test: 0.2127511	best: 0.2127511 (2600)	total: 46.1s	remaining: 41.3s
2620:	learn: 0.2018203	test: 0.2126781	best: 0.2126781 (2620)	total: 46.5s	remaining: 40.9s
2640:	learn: 0.2016639	test: 0.2126256	best: 0.2126234 (2638)	total: 46.8s	remaining: 40.6s
2660:	learn: 0.2014511	test: 0.2125075	best: 0.2125075 (2660)	total: 47.2s	remaining: 40.2s
2680:	learn: 0.2012708	test: 0.2124477	best: 0.2124454 (2678)	total: 47.6s	remaining: 39.9s
2700:	learn: 0.2011237	test: 0.2123858	best: 0.2123858 (2700)	total: 47.9s	remaining: 39.5s
2720:	learn: 0.2009580	test: 0.2123124	best: 0.2123124 (2720)	total: 48.3s	remaining: 39.2s
2740:	learn: 0.2007986	test: 0.2122228	best: 0.2122228 (2740)	total: 48.6s	remaining: 38.8s
2760:	learn: 0.2005943	test: 0.2121067	best: 0.2121067 (2760)	total: 49s	remaining: 38.5s
2780:	learn: 0.2004410	test: 0.2120766	best: 0.2120766 (2780)	total: 49.4s	remaining: 38.1s
2800:	learn: 0.2003103	test: 0.2120386	best: 0.2120386 (2800)	total: 49.7s	remaining: 37.8s
2820:	learn: 0.2001386	test: 0.2119514	best: 0.2119514 (2820)	total: 50.1s	remaining: 37.4s
2840:	learn: 0.1999855	test: 0.2118945	best: 0.2118945 (2840)	total: 50.5s	remaining: 37.1s
2860:	learn: 0.1998539	test: 0.2118645	best: 0.2118645 (2860)	total: 50.8s	remaining: 36.7s
2880:	learn: 0.1996797	test: 0.2117921	best: 0.2117921 (2880)	total: 51.1s	remaining: 36.3s
2900:	learn: 0.1994941	test: 0.2117272	best: 0.2117272 (2900)	total: 51.5s	remaining: 36s
2920:	learn: 0.1993451	test: 0.2116765	best: 0.2116765 (2920)	total: 51.9s	remaining: 35.6s
2940:	learn: 0.1992113	test: 0.2116403	best: 0.2116389 (2937)	total: 52.2s	remaining: 35.3s
2960:	learn: 0.1990499	test: 0.2115711	best: 0.2115711 (2960)	total: 52.6s	remaining: 34.9s
2980:	learn: 0.1988905	test: 0.2115152	best: 0.2115147 (2979)	total: 53s	remaining: 34.6s
3000:	learn: 0.1987617	test: 0.2114705	best: 0.2114705 (3000)	total: 53.3s	remaining: 34.2s
3020:	learn: 0.1986211	test: 0.2114085	best: 0.2114085 (3020)	total: 53.7s	remaining: 33.9s
3040:	learn: 0.1984801	test: 0.2113745	best: 0.2113745 (3040)	total: 54s	remaining: 33.5s
3060:	learn: 0.1983565	test: 0.2113407	best: 0.2113407 (3060)	total: 54.4s	remaining: 33.2s
3080:	learn: 0.1981833	test: 0.2112910	best: 0.2112910 (3080)	total: 54.8s	remaining: 32.8s
3100:	learn: 0.1980495	test: 0.2112572	best: 0.2112572 (3100)	total: 55.1s	remaining: 32.5s
3120:	learn: 0.1978981	test: 0.2112027	best: 0.2112027 (3120)	total: 55.5s	remaining: 32.1s
3140:	learn: 0.1977130	test: 0.2111237	best: 0.2111237 (3140)	total: 55.8s	remaining: 31.8s
3160:	learn: 0.1975906	test: 0.2110939	best: 0.2110931 (3159)	total: 56.2s	remaining: 31.4s
3180:	learn: 0.1974259	test: 0.2110271	best: 0.2110255 (3179)	total: 56.6s	remaining: 31.1s
3200:	learn: 0.1972912	test: 0.2109811	best: 0.2109809 (3197)	total: 56.9s	remaining: 30.7s
3220:	learn: 0.1971485	test: 0.2109277	best: 0.2109277 (3220)	total: 57.3s	remaining: 30.4s
3240:	learn: 0.1970202	test: 0.2108922	best: 0.2108922 (3240)	total: 57.7s	remaining: 30s
3260:	learn: 0.1968767	test: 0.2108333	best: 0.2108333 (3260)	total: 58s	remaining: 29.7s
3280:	learn: 0.1967287	test: 0.2108175	best: 0.2108175 (3280)	total: 58.4s	remaining: 29.3s
3300:	learn: 0.1965882	test: 0.2107899	best: 0.2107884 (3297)	total: 58.8s	remaining: 29s
3320:	learn: 0.1964523	test: 0.2107625	best: 0.2107625 (3320)	total: 59.1s	remaining: 28.6s
3340:	learn: 0.1963173	test: 0.2107115	best: 0.2107115 (3340)	total: 59.5s	remaining: 28.3s
3360:	learn: 0.1961525	test: 0.2106276	best: 0.2106273 (3358)	total: 59.9s	remaining: 27.9s
3380:	learn: 0.1960111	test: 0.2105815	best: 0.2105815 (3380)	total: 1m	remaining: 27.6s
3400:	learn: 0.1958865	test: 0.2105433	best: 0.2105433 (3400)	total: 1m	remaining: 27.2s
3420:	learn: 0.1957195	test: 0.2104827	best: 0.2104822 (3418)	total: 1m	remaining: 26.9s
3440:	learn: 0.1955460	test: 0.2103972	best: 0.2103962 (3439)	total: 1m 1s	remaining: 26.5s
3460:	learn: 0.1954065	test: 0.2103355	best: 0.2103355 (3460)	total: 1m 1s	remaining: 26.2s
3480:	learn: 0.1952602	test: 0.2102713	best: 0.2102697 (3479)	total: 1m 2s	remaining: 25.8s
3500:	learn: 0.1951429	test: 0.2102386	best: 0.2102386 (3500)	total: 1m 2s	remaining: 25.4s
3520:	learn: 0.1950029	test: 0.2101854	best: 0.2101854 (3520)	total: 1m 2s	remaining: 25.1s
3540:	learn: 0.1948356	test: 0.2101063	best: 0.2101063 (3540)	total: 1m 3s	remaining: 24.7s
3560:	learn: 0.1946942	test: 0.2100674	best: 0.2100674 (3560)	total: 1m 3s	remaining: 24.4s
3580:	learn: 0.1945777	test: 0.2100417	best: 0.2100383 (3574)	total: 1m 3s	remaining: 24s
3600:	learn: 0.1944414	test: 0.2100135	best: 0.2100135 (3600)	total: 1m 4s	remaining: 23.7s
3620:	learn: 0.1943247	test: 0.2099854	best: 0.2099854 (3620)	total: 1m 4s	remaining: 23.3s
3640:	learn: 0.1941666	test: 0.2099390	best: 0.2099389 (3638)	total: 1m 5s	remaining: 23s
3660:	learn: 0.1940485	test: 0.2099041	best: 0.2099041 (3660)	total: 1m 5s	remaining: 22.6s
3680:	learn: 0.1939237	test: 0.2098668	best: 0.2098668 (3680)	total: 1m 5s	remaining: 22.3s
3700:	learn: 0.1937972	test: 0.2098189	best: 0.2098189 (3700)	total: 1m 6s	remaining: 21.9s
3720:	learn: 0.1936680	test: 0.2097905	best: 0.2097885 (3718)	total: 1m 6s	remaining: 21.6s
3740:	learn: 0.1935593	test: 0.2097598	best: 0.2097598 (3740)	total: 1m 6s	remaining: 21.2s
3760:	learn: 0.1934238	test: 0.2097180	best: 0.2097180 (3760)	total: 1m 7s	remaining: 20.8s
3780:	learn: 0.1932842	test: 0.2096677	best: 0.2096677 (3780)	total: 1m 7s	remaining: 20.5s
3800:	learn: 0.1931350	test: 0.2096002	best: 0.2096002 (3800)	total: 1m 7s	remaining: 20.1s
3820:	learn: 0.1930164	test: 0.2095690	best: 0.2095690 (3820)	total: 1m 8s	remaining: 19.8s
3840:	learn: 0.1928765	test: 0.2095414	best: 0.2095379 (3839)	total: 1m 8s	remaining: 19.4s
3860:	learn: 0.1927444	test: 0.2095055	best: 0.2095055 (3860)	total: 1m 9s	remaining: 19.1s
3880:	learn: 0.1926168	test: 0.2094719	best: 0.2094698 (3879)	total: 1m 9s	remaining: 18.7s
3900:	learn: 0.1924922	test: 0.2094317	best: 0.2094317 (3900)	total: 1m 9s	remaining: 18.4s
3920:	learn: 0.1923829	test: 0.2094032	best: 0.2094015 (3919)	total: 1m 10s	remaining: 18s
3940:	learn: 0.1922628	test: 0.2093703	best: 0.2093703 (3940)	total: 1m 10s	remaining: 17.7s
3960:	learn: 0.1921387	test: 0.2093435	best: 0.2093435 (3960)	total: 1m 10s	remaining: 17.3s
3980:	learn: 0.1920116	test: 0.2093062	best: 0.2092982 (3976)	total: 1m 11s	remaining: 16.9s
4000:	learn: 0.1918705	test: 0.2092776	best: 0.2092776 (4000)	total: 1m 11s	remaining: 16.6s
4020:	learn: 0.1917666	test: 0.2092609	best: 0.2092609 (4020)	total: 1m 11s	remaining: 16.2s
4040:	learn: 0.1916495	test: 0.2092237	best: 0.2092194 (4039)	total: 1m 12s	remaining: 15.9s
4060:	learn: 0.1915317	test: 0.2092042	best: 0.2092042 (4060)	total: 1m 12s	remaining: 15.5s
4080:	learn: 0.1913964	test: 0.2091656	best: 0.2091656 (4080)	total: 1m 13s	remaining: 15.2s
4100:	learn: 0.1912436	test: 0.2091000	best: 0.2091000 (4100)	total: 1m 13s	remaining: 14.8s
4120:	learn: 0.1911091	test: 0.2090460	best: 0.2090460 (4120)	total: 1m 13s	remaining: 14.5s
4140:	learn: 0.1909897	test: 0.2090217	best: 0.2090217 (4140)	total: 1m 14s	remaining: 14.1s
4160:	learn: 0.1908775	test: 0.2090008	best: 0.2090004 (4154)	total: 1m 14s	remaining: 13.7s
4180:	learn: 0.1907495	test: 0.2089789	best: 0.2089789 (4180)	total: 1m 14s	remaining: 13.4s
4200:	learn: 0.1906461	test: 0.2089493	best: 0.2089492 (4199)	total: 1m 15s	remaining: 13s
4220:	learn: 0.1904853	test: 0.2088990	best: 0.2088932 (4217)	total: 1m 15s	remaining: 12.7s
4240:	learn: 0.1903657	test: 0.2088837	best: 0.2088784 (4238)	total: 1m 16s	remaining: 12.3s
4260:	learn: 0.1902378	test: 0.2088377	best: 0.2088363 (4259)	total: 1m 16s	remaining: 12s
4280:	learn: 0.1901236	test: 0.2088246	best: 0.2088242 (4279)	total: 1m 16s	remaining: 11.6s
4300:	learn: 0.1899858	test: 0.2087897	best: 0.2087897 (4300)	total: 1m 17s	remaining: 11.2s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6405000	test: 0.6403977	best: 0.6403977 (0)	total: 9.2ms	remaining: 9.2ms
1:	learn: 0.5956157	test: 0.5954168	best: 0.5954168 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5954168028
bestIteration = 1
0:	learn: 0.6410847	test: 0.6409700	best: 0.6409700 (0)	total: 16.8ms	remaining: 1m 37s
20:	learn: 0.3363955	test: 0.3355267	best: 0.3355267 (20)	total: 390ms	remaining: 1m 47s
40:	learn: 0.3047761	test: 0.3041458	best: 0.3041458 (40)	total: 773ms	remaining: 1m 48s
60:	learn: 0.2900251	test: 0.2888809	best: 0.2888809 (60)	total: 1.15s	remaining: 1m 48s
80:	learn: 0.2812965	test: 0.2798907	best: 0.2798907 (80)	total: 1.53s	remaining: 1m 47s
100:	learn: 0.2758657	test: 0.2744935	best: 0.2744935 (100)	total: 1.9s	remaining: 1m 47s
120:	learn: 0.2707285	test: 0.2692834	best: 0.2692834 (120)	total: 2.25s	remaining: 1m 45s
140:	learn: 0.2662341	test: 0.2647641	best: 0.2647641 (140)	total: 2.61s	remaining: 1m 44s
160:	learn: 0.2620368	test: 0.2605045	best: 0.2605045 (160)	total: 2.97s	remaining: 1m 44s
180:	learn: 0.2596676	test: 0.2582399	best: 0.2582399 (180)	total: 3.33s	remaining: 1m 43s
200:	learn: 0.2574513	test: 0.2561560	best: 0.2561560 (200)	total: 3.69s	remaining: 1m 42s
220:	learn: 0.2548795	test: 0.2535796	best: 0.2535796 (220)	total: 4.06s	remaining: 1m 42s
240:	learn: 0.2528114	test: 0.2516842	best: 0.2516842 (240)	total: 4.42s	remaining: 1m 41s
260:	learn: 0.2510722	test: 0.2499424	best: 0.2499424 (260)	total: 4.78s	remaining: 1m 41s
280:	learn: 0.2490456	test: 0.2480549	best: 0.2480549 (280)	total: 5.13s	remaining: 1m 40s
300:	learn: 0.2474674	test: 0.2465077	best: 0.2465077 (300)	total: 5.5s	remaining: 1m 40s
320:	learn: 0.2455899	test: 0.2446744	best: 0.2446744 (320)	total: 5.88s	remaining: 1m 40s
340:	learn: 0.2440759	test: 0.2432321	best: 0.2432321 (340)	total: 6.24s	remaining: 1m 39s
360:	learn: 0.2428579	test: 0.2420999	best: 0.2420999 (360)	total: 6.59s	remaining: 1m 39s
380:	learn: 0.2417177	test: 0.2410597	best: 0.2410597 (380)	total: 6.95s	remaining: 1m 38s
400:	learn: 0.2405044	test: 0.2399225	best: 0.2399225 (400)	total: 7.32s	remaining: 1m 38s
420:	learn: 0.2393813	test: 0.2389087	best: 0.2389087 (420)	total: 7.67s	remaining: 1m 38s
440:	learn: 0.2384367	test: 0.2381035	best: 0.2381035 (440)	total: 8.03s	remaining: 1m 37s
460:	learn: 0.2374836	test: 0.2372969	best: 0.2372969 (460)	total: 8.39s	remaining: 1m 37s
480:	learn: 0.2364548	test: 0.2363646	best: 0.2363646 (480)	total: 8.75s	remaining: 1m 36s
500:	learn: 0.2355062	test: 0.2355127	best: 0.2355127 (500)	total: 9.11s	remaining: 1m 36s
520:	learn: 0.2346938	test: 0.2348719	best: 0.2348719 (520)	total: 9.46s	remaining: 1m 35s
540:	learn: 0.2337236	test: 0.2339673	best: 0.2339673 (540)	total: 9.81s	remaining: 1m 35s
560:	learn: 0.2330389	test: 0.2334125	best: 0.2334125 (560)	total: 10.2s	remaining: 1m 34s
580:	learn: 0.2320265	test: 0.2324861	best: 0.2324861 (580)	total: 10.5s	remaining: 1m 34s
600:	learn: 0.2313835	test: 0.2319792	best: 0.2319792 (600)	total: 10.8s	remaining: 1m 33s
620:	learn: 0.2307028	test: 0.2314204	best: 0.2314204 (620)	total: 11.2s	remaining: 1m 33s
640:	learn: 0.2301079	test: 0.2309464	best: 0.2309464 (640)	total: 11.5s	remaining: 1m 32s
660:	learn: 0.2294654	test: 0.2303944	best: 0.2303944 (660)	total: 11.9s	remaining: 1m 32s
680:	learn: 0.2288972	test: 0.2299463	best: 0.2299463 (680)	total: 12.2s	remaining: 1m 32s
700:	learn: 0.2283666	test: 0.2295661	best: 0.2295661 (700)	total: 12.6s	remaining: 1m 31s
720:	learn: 0.2278181	test: 0.2291411	best: 0.2291411 (720)	total: 12.9s	remaining: 1m 31s
740:	learn: 0.2273141	test: 0.2287532	best: 0.2287532 (740)	total: 13.3s	remaining: 1m 30s
760:	learn: 0.2267827	test: 0.2283725	best: 0.2283725 (760)	total: 13.6s	remaining: 1m 30s
780:	learn: 0.2261484	test: 0.2278440	best: 0.2278440 (780)	total: 14s	remaining: 1m 29s
800:	learn: 0.2254956	test: 0.2272794	best: 0.2272794 (800)	total: 14.3s	remaining: 1m 29s
820:	learn: 0.2249426	test: 0.2268630	best: 0.2268630 (820)	total: 14.7s	remaining: 1m 29s
840:	learn: 0.2244393	test: 0.2265127	best: 0.2265127 (840)	total: 15s	remaining: 1m 28s
860:	learn: 0.2240176	test: 0.2262254	best: 0.2262254 (860)	total: 15.4s	remaining: 1m 28s
880:	learn: 0.2235714	test: 0.2258956	best: 0.2258956 (880)	total: 15.7s	remaining: 1m 27s
900:	learn: 0.2230606	test: 0.2255402	best: 0.2255402 (900)	total: 16.1s	remaining: 1m 27s
920:	learn: 0.2226438	test: 0.2252516	best: 0.2252516 (920)	total: 16.4s	remaining: 1m 27s
940:	learn: 0.2221773	test: 0.2249016	best: 0.2249016 (940)	total: 16.8s	remaining: 1m 26s
960:	learn: 0.2216606	test: 0.2245249	best: 0.2245249 (960)	total: 17.1s	remaining: 1m 26s
980:	learn: 0.2213317	test: 0.2243118	best: 0.2243118 (980)	total: 17.5s	remaining: 1m 25s
1000:	learn: 0.2209311	test: 0.2240144	best: 0.2240144 (1000)	total: 17.8s	remaining: 1m 25s
1020:	learn: 0.2205709	test: 0.2237764	best: 0.2237764 (1020)	total: 18.2s	remaining: 1m 25s
1040:	learn: 0.2202311	test: 0.2235505	best: 0.2235505 (1040)	total: 18.5s	remaining: 1m 24s
1060:	learn: 0.2198387	test: 0.2232520	best: 0.2232520 (1060)	total: 18.9s	remaining: 1m 24s
1080:	learn: 0.2194668	test: 0.2229729	best: 0.2229729 (1080)	total: 19.2s	remaining: 1m 23s
1100:	learn: 0.2191372	test: 0.2227727	best: 0.2227727 (1100)	total: 19.6s	remaining: 1m 23s
1120:	learn: 0.2187551	test: 0.2224769	best: 0.2224769 (1120)	total: 19.9s	remaining: 1m 23s
1140:	learn: 0.2184519	test: 0.2222679	best: 0.2222679 (1140)	total: 20.3s	remaining: 1m 22s
1160:	learn: 0.2181539	test: 0.2220893	best: 0.2220893 (1160)	total: 20.6s	remaining: 1m 22s
1180:	learn: 0.2178509	test: 0.2219110	best: 0.2219110 (1180)	total: 21s	remaining: 1m 22s
1200:	learn: 0.2175565	test: 0.2217174	best: 0.2217174 (1200)	total: 21.3s	remaining: 1m 21s
1220:	learn: 0.2172225	test: 0.2214992	best: 0.2214992 (1220)	total: 21.7s	remaining: 1m 21s
1240:	learn: 0.2169342	test: 0.2213638	best: 0.2213638 (1240)	total: 22s	remaining: 1m 20s
1260:	learn: 0.2165844	test: 0.2211345	best: 0.2211345 (1260)	total: 22.4s	remaining: 1m 20s
1280:	learn: 0.2162599	test: 0.2209176	best: 0.2209176 (1280)	total: 22.7s	remaining: 1m 20s
1300:	learn: 0.2159108	test: 0.2206564	best: 0.2206564 (1300)	total: 23.1s	remaining: 1m 19s
1320:	learn: 0.2156312	test: 0.2204979	best: 0.2204979 (1320)	total: 23.5s	remaining: 1m 19s
1340:	learn: 0.2153465	test: 0.2203280	best: 0.2203280 (1340)	total: 23.8s	remaining: 1m 19s
1360:	learn: 0.2150590	test: 0.2201905	best: 0.2201905 (1360)	total: 24.2s	remaining: 1m 18s
1380:	learn: 0.2147565	test: 0.2199844	best: 0.2199844 (1380)	total: 24.5s	remaining: 1m 18s
1400:	learn: 0.2144746	test: 0.2198209	best: 0.2198209 (1400)	total: 24.9s	remaining: 1m 18s
1420:	learn: 0.2142143	test: 0.2196933	best: 0.2196933 (1420)	total: 25.2s	remaining: 1m 17s
1440:	learn: 0.2139444	test: 0.2195332	best: 0.2195332 (1440)	total: 25.6s	remaining: 1m 17s
1460:	learn: 0.2136266	test: 0.2193279	best: 0.2193279 (1460)	total: 25.9s	remaining: 1m 17s
1480:	learn: 0.2133696	test: 0.2191827	best: 0.2191827 (1480)	total: 26.3s	remaining: 1m 16s
1500:	learn: 0.2131265	test: 0.2190545	best: 0.2190545 (1500)	total: 26.6s	remaining: 1m 16s
1520:	learn: 0.2128291	test: 0.2188623	best: 0.2188623 (1520)	total: 27s	remaining: 1m 15s
1540:	learn: 0.2125787	test: 0.2187543	best: 0.2187543 (1540)	total: 27.4s	remaining: 1m 15s
1560:	learn: 0.2123229	test: 0.2186312	best: 0.2186312 (1560)	total: 27.7s	remaining: 1m 15s
1580:	learn: 0.2120486	test: 0.2184816	best: 0.2184816 (1580)	total: 28.1s	remaining: 1m 14s
1600:	learn: 0.2118218	test: 0.2183417	best: 0.2183417 (1600)	total: 28.4s	remaining: 1m 14s
1620:	learn: 0.2115811	test: 0.2182130	best: 0.2182130 (1620)	total: 28.8s	remaining: 1m 14s
1640:	learn: 0.2113666	test: 0.2181114	best: 0.2181114 (1640)	total: 29.1s	remaining: 1m 13s
1660:	learn: 0.2111271	test: 0.2179995	best: 0.2179995 (1660)	total: 29.5s	remaining: 1m 13s
1680:	learn: 0.2109302	test: 0.2179034	best: 0.2179034 (1678)	total: 29.8s	remaining: 1m 13s
1700:	learn: 0.2106370	test: 0.2177387	best: 0.2177387 (1700)	total: 30.2s	remaining: 1m 12s
1720:	learn: 0.2104358	test: 0.2176628	best: 0.2176628 (1720)	total: 30.5s	remaining: 1m 12s
1740:	learn: 0.2102074	test: 0.2175230	best: 0.2175230 (1740)	total: 30.9s	remaining: 1m 12s
1760:	learn: 0.2099646	test: 0.2173910	best: 0.2173910 (1760)	total: 31.3s	remaining: 1m 11s
1780:	learn: 0.2097675	test: 0.2172877	best: 0.2172877 (1780)	total: 31.6s	remaining: 1m 11s
1800:	learn: 0.2095694	test: 0.2171803	best: 0.2171803 (1800)	total: 32s	remaining: 1m 11s
1820:	learn: 0.2093602	test: 0.2171005	best: 0.2171005 (1820)	total: 32.3s	remaining: 1m 10s
1840:	learn: 0.2090911	test: 0.2169135	best: 0.2169135 (1840)	total: 32.7s	remaining: 1m 10s
1860:	learn: 0.2088746	test: 0.2168092	best: 0.2168092 (1860)	total: 33s	remaining: 1m 9s
1880:	learn: 0.2086492	test: 0.2166636	best: 0.2166636 (1880)	total: 33.4s	remaining: 1m 9s
1900:	learn: 0.2084385	test: 0.2165641	best: 0.2165641 (1900)	total: 33.7s	remaining: 1m 9s
1920:	learn: 0.2082276	test: 0.2164550	best: 0.2164550 (1920)	total: 34.1s	remaining: 1m 8s
1940:	learn: 0.2080238	test: 0.2163637	best: 0.2163637 (1940)	total: 34.5s	remaining: 1m 8s
1960:	learn: 0.2078472	test: 0.2163100	best: 0.2163086 (1959)	total: 34.8s	remaining: 1m 8s
1980:	learn: 0.2076734	test: 0.2162099	best: 0.2162099 (1980)	total: 35.2s	remaining: 1m 7s
2000:	learn: 0.2074743	test: 0.2161172	best: 0.2161172 (2000)	total: 35.5s	remaining: 1m 7s
2020:	learn: 0.2072594	test: 0.2160179	best: 0.2160179 (2020)	total: 35.9s	remaining: 1m 7s
2040:	learn: 0.2070788	test: 0.2159349	best: 0.2159349 (2040)	total: 36.2s	remaining: 1m 6s
2060:	learn: 0.2068743	test: 0.2158349	best: 0.2158349 (2060)	total: 36.6s	remaining: 1m 6s
2080:	learn: 0.2066240	test: 0.2156726	best: 0.2156726 (2080)	total: 37s	remaining: 1m 6s
2100:	learn: 0.2064474	test: 0.2156011	best: 0.2156011 (2100)	total: 37.3s	remaining: 1m 5s
2120:	learn: 0.2062642	test: 0.2155185	best: 0.2155185 (2120)	total: 37.7s	remaining: 1m 5s
2140:	learn: 0.2060868	test: 0.2154325	best: 0.2154325 (2140)	total: 38s	remaining: 1m 5s
2160:	learn: 0.2058951	test: 0.2153517	best: 0.2153517 (2160)	total: 38.4s	remaining: 1m 4s
2180:	learn: 0.2057278	test: 0.2152597	best: 0.2152597 (2180)	total: 38.8s	remaining: 1m 4s
2200:	learn: 0.2055271	test: 0.2151564	best: 0.2151564 (2200)	total: 39.1s	remaining: 1m 3s
2220:	learn: 0.2053482	test: 0.2150616	best: 0.2150616 (2220)	total: 39.5s	remaining: 1m 3s
2240:	learn: 0.2051787	test: 0.2150048	best: 0.2150048 (2240)	total: 39.8s	remaining: 1m 3s
2260:	learn: 0.2050085	test: 0.2149240	best: 0.2149240 (2260)	total: 40.2s	remaining: 1m 2s
2280:	learn: 0.2048034	test: 0.2148299	best: 0.2148299 (2280)	total: 40.5s	remaining: 1m 2s
2300:	learn: 0.2046110	test: 0.2147454	best: 0.2147422 (2299)	total: 40.9s	remaining: 1m 2s
2320:	learn: 0.2044537	test: 0.2146647	best: 0.2146647 (2320)	total: 41.3s	remaining: 1m 1s
2340:	learn: 0.2042743	test: 0.2146072	best: 0.2146072 (2340)	total: 41.6s	remaining: 1m 1s
2360:	learn: 0.2041124	test: 0.2145317	best: 0.2145317 (2360)	total: 42s	remaining: 1m 1s
2380:	learn: 0.2039086	test: 0.2144269	best: 0.2144269 (2380)	total: 42.4s	remaining: 1m
2400:	learn: 0.2037324	test: 0.2143119	best: 0.2143119 (2400)	total: 42.7s	remaining: 1m
2420:	learn: 0.2035433	test: 0.2142150	best: 0.2142150 (2420)	total: 43.1s	remaining: 1m
2440:	learn: 0.2033886	test: 0.2141405	best: 0.2141405 (2440)	total: 43.4s	remaining: 59.8s
2460:	learn: 0.2032309	test: 0.2140829	best: 0.2140829 (2460)	total: 43.8s	remaining: 59.4s
2480:	learn: 0.2030561	test: 0.2140213	best: 0.2140152 (2477)	total: 44.2s	remaining: 59.1s
2500:	learn: 0.2029027	test: 0.2139519	best: 0.2139519 (2500)	total: 44.5s	remaining: 58.7s
2520:	learn: 0.2027623	test: 0.2139197	best: 0.2139197 (2519)	total: 44.9s	remaining: 58.4s
2540:	learn: 0.2025714	test: 0.2138367	best: 0.2138367 (2540)	total: 45.2s	remaining: 58s
2560:	learn: 0.2024222	test: 0.2137782	best: 0.2137782 (2560)	total: 45.6s	remaining: 57.7s
2580:	learn: 0.2022905	test: 0.2137263	best: 0.2137263 (2580)	total: 45.9s	remaining: 57.3s
2600:	learn: 0.2021342	test: 0.2136716	best: 0.2136716 (2600)	total: 46.3s	remaining: 57s
2620:	learn: 0.2019774	test: 0.2136122	best: 0.2136122 (2620)	total: 46.7s	remaining: 56.6s
2640:	learn: 0.2018115	test: 0.2135415	best: 0.2135415 (2640)	total: 47s	remaining: 56.3s
2660:	learn: 0.2016476	test: 0.2134722	best: 0.2134721 (2659)	total: 47.4s	remaining: 55.9s
2680:	learn: 0.2014574	test: 0.2133690	best: 0.2133690 (2680)	total: 47.7s	remaining: 55.6s
2700:	learn: 0.2013357	test: 0.2133291	best: 0.2133291 (2700)	total: 48.1s	remaining: 55.2s
2720:	learn: 0.2011769	test: 0.2132532	best: 0.2132532 (2720)	total: 48.5s	remaining: 54.9s
2740:	learn: 0.2010268	test: 0.2131917	best: 0.2131917 (2740)	total: 48.9s	remaining: 54.5s
2760:	learn: 0.2008772	test: 0.2131583	best: 0.2131583 (2760)	total: 49.2s	remaining: 54.2s
2780:	learn: 0.2007198	test: 0.2131192	best: 0.2131192 (2780)	total: 49.6s	remaining: 53.8s
2800:	learn: 0.2005642	test: 0.2130850	best: 0.2130850 (2800)	total: 49.9s	remaining: 53.5s
2820:	learn: 0.2004309	test: 0.2130499	best: 0.2130499 (2820)	total: 50.3s	remaining: 53.1s
2840:	learn: 0.2002880	test: 0.2129970	best: 0.2129970 (2840)	total: 50.7s	remaining: 52.8s
2860:	learn: 0.2001453	test: 0.2129575	best: 0.2129575 (2860)	total: 51s	remaining: 52.5s
2880:	learn: 0.2000008	test: 0.2129078	best: 0.2129078 (2880)	total: 51.4s	remaining: 52.1s
2900:	learn: 0.1998443	test: 0.2128417	best: 0.2128417 (2900)	total: 51.8s	remaining: 51.8s
2920:	learn: 0.1996997	test: 0.2127889	best: 0.2127889 (2920)	total: 52.1s	remaining: 51.4s
2940:	learn: 0.1995258	test: 0.2126942	best: 0.2126942 (2940)	total: 52.5s	remaining: 51.1s
2960:	learn: 0.1993755	test: 0.2126330	best: 0.2126330 (2960)	total: 52.9s	remaining: 50.7s
2980:	learn: 0.1992151	test: 0.2125611	best: 0.2125611 (2980)	total: 53.3s	remaining: 50.4s
3000:	learn: 0.1990343	test: 0.2124772	best: 0.2124772 (3000)	total: 53.6s	remaining: 50s
3020:	learn: 0.1988804	test: 0.2124207	best: 0.2124207 (3020)	total: 53.9s	remaining: 49.6s
3040:	learn: 0.1987627	test: 0.2123982	best: 0.2123948 (3037)	total: 54.3s	remaining: 49.3s
3060:	learn: 0.1985808	test: 0.2122960	best: 0.2122960 (3060)	total: 54.7s	remaining: 48.9s
3080:	learn: 0.1984443	test: 0.2122454	best: 0.2122454 (3080)	total: 55s	remaining: 48.6s
3100:	learn: 0.1983164	test: 0.2121983	best: 0.2121943 (3099)	total: 55.4s	remaining: 48.2s
3120:	learn: 0.1981534	test: 0.2121228	best: 0.2121228 (3120)	total: 55.8s	remaining: 47.9s
3140:	learn: 0.1979763	test: 0.2120384	best: 0.2120384 (3140)	total: 56.1s	remaining: 47.5s
3160:	learn: 0.1978410	test: 0.2119979	best: 0.2119979 (3160)	total: 56.5s	remaining: 47.2s
3180:	learn: 0.1977116	test: 0.2119561	best: 0.2119561 (3180)	total: 56.8s	remaining: 46.8s
3200:	learn: 0.1975892	test: 0.2118965	best: 0.2118965 (3200)	total: 57.2s	remaining: 46.5s
3220:	learn: 0.1974380	test: 0.2118387	best: 0.2118387 (3220)	total: 57.6s	remaining: 46.1s
3240:	learn: 0.1972823	test: 0.2117657	best: 0.2117657 (3240)	total: 57.9s	remaining: 45.8s
3260:	learn: 0.1971720	test: 0.2117191	best: 0.2117191 (3260)	total: 58.3s	remaining: 45.4s
3280:	learn: 0.1970132	test: 0.2116614	best: 0.2116614 (3280)	total: 58.7s	remaining: 45.1s
3300:	learn: 0.1968744	test: 0.2116160	best: 0.2116160 (3300)	total: 59s	remaining: 44.7s
3320:	learn: 0.1967549	test: 0.2115958	best: 0.2115958 (3317)	total: 59.4s	remaining: 44.4s
3340:	learn: 0.1966172	test: 0.2115368	best: 0.2115368 (3340)	total: 59.8s	remaining: 44s
3360:	learn: 0.1964914	test: 0.2115371	best: 0.2115350 (3359)	total: 1m	remaining: 43.6s
3380:	learn: 0.1963401	test: 0.2114826	best: 0.2114826 (3380)	total: 1m	remaining: 43.3s
3400:	learn: 0.1962094	test: 0.2114504	best: 0.2114504 (3400)	total: 1m	remaining: 42.9s
3420:	learn: 0.1960784	test: 0.2114050	best: 0.2114014 (3418)	total: 1m 1s	remaining: 42.6s
3440:	learn: 0.1959151	test: 0.2113232	best: 0.2113232 (3440)	total: 1m 1s	remaining: 42.2s
3460:	learn: 0.1957906	test: 0.2112828	best: 0.2112828 (3460)	total: 1m 1s	remaining: 41.9s
3480:	learn: 0.1956438	test: 0.2112337	best: 0.2112337 (3480)	total: 1m 2s	remaining: 41.5s
3500:	learn: 0.1954708	test: 0.2111342	best: 0.2111342 (3500)	total: 1m 2s	remaining: 41.2s
3520:	learn: 0.1953385	test: 0.2111036	best: 0.2111036 (3520)	total: 1m 3s	remaining: 40.8s
3540:	learn: 0.1951623	test: 0.2110370	best: 0.2110355 (3538)	total: 1m 3s	remaining: 40.5s
3560:	learn: 0.1950479	test: 0.2110072	best: 0.2110052 (3559)	total: 1m 3s	remaining: 40.1s
3580:	learn: 0.1949187	test: 0.2109792	best: 0.2109787 (3574)	total: 1m 4s	remaining: 39.7s
3600:	learn: 0.1947882	test: 0.2109498	best: 0.2109498 (3600)	total: 1m 4s	remaining: 39.4s
3620:	learn: 0.1946593	test: 0.2109188	best: 0.2109188 (3620)	total: 1m 4s	remaining: 39s
3640:	learn: 0.1945188	test: 0.2108602	best: 0.2108602 (3640)	total: 1m 5s	remaining: 38.7s
3660:	learn: 0.1943956	test: 0.2108266	best: 0.2108252 (3659)	total: 1m 5s	remaining: 38.3s
3680:	learn: 0.1942680	test: 0.2107870	best: 0.2107870 (3680)	total: 1m 5s	remaining: 38s
3700:	learn: 0.1941499	test: 0.2107483	best: 0.2107483 (3700)	total: 1m 6s	remaining: 37.6s
3720:	learn: 0.1940224	test: 0.2107066	best: 0.2107066 (3720)	total: 1m 6s	remaining: 37.3s
3740:	learn: 0.1938833	test: 0.2106654	best: 0.2106637 (3738)	total: 1m 7s	remaining: 36.9s
3760:	learn: 0.1937720	test: 0.2106383	best: 0.2106383 (3760)	total: 1m 7s	remaining: 36.6s
3780:	learn: 0.1936551	test: 0.2106126	best: 0.2106126 (3780)	total: 1m 7s	remaining: 36.2s
3800:	learn: 0.1935160	test: 0.2105752	best: 0.2105752 (3800)	total: 1m 8s	remaining: 35.8s
3820:	learn: 0.1933913	test: 0.2105163	best: 0.2105163 (3820)	total: 1m 8s	remaining: 35.5s
3840:	learn: 0.1932780	test: 0.2104696	best: 0.2104659 (3838)	total: 1m 8s	remaining: 35.1s
3860:	learn: 0.1931471	test: 0.2104358	best: 0.2104358 (3860)	total: 1m 9s	remaining: 34.8s
3880:	learn: 0.1930264	test: 0.2103973	best: 0.2103942 (3877)	total: 1m 9s	remaining: 34.4s
3900:	learn: 0.1929092	test: 0.2103596	best: 0.2103549 (3898)	total: 1m 9s	remaining: 34.1s
3920:	learn: 0.1928027	test: 0.2103273	best: 0.2103273 (3920)	total: 1m 10s	remaining: 33.7s
3940:	learn: 0.1926727	test: 0.2102740	best: 0.2102693 (3935)	total: 1m 10s	remaining: 33.4s
3960:	learn: 0.1925496	test: 0.2102285	best: 0.2102285 (3960)	total: 1m 11s	remaining: 33s
3980:	learn: 0.1924249	test: 0.2102059	best: 0.2102019 (3978)	total: 1m 11s	remaining: 32.6s
4000:	learn: 0.1922932	test: 0.2101549	best: 0.2101549 (4000)	total: 1m 11s	remaining: 32.3s
4020:	learn: 0.1921709	test: 0.2101224	best: 0.2101224 (4020)	total: 1m 12s	remaining: 31.9s
4040:	learn: 0.1920563	test: 0.2100797	best: 0.2100797 (4040)	total: 1m 12s	remaining: 31.6s
4060:	learn: 0.1919310	test: 0.2100251	best: 0.2100251 (4060)	total: 1m 12s	remaining: 31.2s
4080:	learn: 0.1917947	test: 0.2099831	best: 0.2099831 (4080)	total: 1m 13s	remaining: 30.9s
4100:	learn: 0.1916877	test: 0.2099605	best: 0.2099605 (4100)	total: 1m 13s	remaining: 30.5s
4120:	learn: 0.1915434	test: 0.2099311	best: 0.2099309 (4114)	total: 1m 13s	remaining: 30.2s
4140:	learn: 0.1914390	test: 0.2099005	best: 0.2099005 (4140)	total: 1m 14s	remaining: 29.8s
4160:	learn: 0.1913054	test: 0.2098823	best: 0.2098821 (4156)	total: 1m 14s	remaining: 29.4s
4180:	learn: 0.1911802	test: 0.2098625	best: 0.2098624 (4179)	total: 1m 15s	remaining: 29.1s
4200:	learn: 0.1910673	test: 0.2098247	best: 0.2098247 (4200)	total: 1m 15s	remaining: 28.7s
4220:	learn: 0.1909137	test: 0.2097723	best: 0.2097723 (4220)	total: 1m 15s	remaining: 28.4s
4240:	learn: 0.1907947	test: 0.2097307	best: 0.2097307 (4239)	total: 1m 16s	remaining: 28s
4260:	learn: 0.1906535	test: 0.2096815	best: 0.2096815 (4260)	total: 1m 16s	remaining: 27.7s
4280:	learn: 0.1905264	test: 0.2096394	best: 0.2096394 (4280)	total: 1m 16s	remaining: 27.3s

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L1\model.pkl
	0.9563	 = Validation score   (roc_auc)
	443.53s	 = Training   runtime
	1.5s	 = Validation runtime
	39997.7	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 4677.79s of the 7378.82s of remaining time.
	Fitting ExtraTreesGini_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L1\utils\model_template.pkl
	Warning: Potentially not enough memory to safely train model. Estimated to require 2.518 GB out of 5.182 GB available memory (48.593%)... (50.000% of avail memory is the max safe size)
	To avoid this warning, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.26 to avoid the warning)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=2.5/5.2 GB
	36.19s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L1\model.pkl
	0.9377	 = Validation score   (roc_auc)
	15.89s	 = Training   runtime
	7.94s	 = Validation runtime
	60505.4	 = Inference  throughput (rows/s | 480395 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 4653.34s of the 7354.37s of remaining time.
	Fitting ExtraTreesEntr_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
	Warning: Not enough memory to safely train model. Estimated to require 2.518 GB out of 4.740 GB available memory (53.119%)... (50.000% of avail memory is the max safe size)
	To force training the model, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.11 to avoid the error)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Not enough memory to train ExtraTreesEntr_BAG_L1... Skipping this model.
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: XGBoost_BAG_L1 ... Training model for up to 4653.03s of the 7354.05s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47507
[50]	validation_0-logloss:0.26432
[100]	validation_0-logloss:0.24827
[150]	validation_0-logloss:0.23998
[200]	validation_0-logloss:0.23440
[250]	validation_0-logloss:0.23064
[300]	validation_0-logloss:0.22773
[350]	validation_0-logloss:0.22504
[400]	validation_0-logloss:0.22282
[450]	validation_0-logloss:0.22137
[500]	validation_0-logloss:0.22010
[550]	validation_0-logloss:0.21896
[600]	validation_0-logloss:0.21800
[650]	validation_0-logloss:0.21684
[700]	validation_0-logloss:0.21586
[750]	validation_0-logloss:0.21515
[800]	validation_0-logloss:0.21451
[850]	validation_0-logloss:0.21390
[900]	validation_0-logloss:0.21339
[950]	validation_0-logloss:0.21290
[1000]	validation_0-logloss:0.21252
[1050]	validation_0-logloss:0.21221
[1100]	validation_0-logloss:0.21184
[1150]	validation_0-logloss:0.21137
[1200]	validation_0-logloss:0.21109
[1250]	validation_0-logloss:0.21080
[1300]	validation_0-logloss:0.21053
[1350]	validation_0-logloss:0.21044
[1400]	validation_0-logloss:0.21036
[1450]	validation_0-logloss:0.21016
[1500]	validation_0-logloss:0.21003
[1550]	validation_0-logloss:0.20994
[1600]	validation_0-logloss:0.20988
[1650]	validation_0-logloss:0.20981
[1700]	validation_0-logloss:0.20980
[1750]	validation_0-logloss:0.20967
[1800]	validation_0-logloss:0.20966
[1850]	validation_0-logloss:0.20966
[1900]	validation_0-logloss:0.20949
[1950]	validation_0-logloss:0.20945
[2000]	validation_0-logloss:0.20933
[2050]	validation_0-logloss:0.20929
[2100]	validation_0-logloss:0.20924
[2150]	validation_0-logloss:0.20926
[2200]	validation_0-logloss:0.20922
[2250]	validation_0-logloss:0.20916
[2300]	validation_0-logloss:0.20914
[2350]	validation_0-logloss:0.20925
[2400]	validation_0-logloss:0.20922
[2450]	validation_0-logloss:0.20923
[2500]	validation_0-logloss:0.20923
[2550]	validation_0-logloss:0.20924
[2600]	validation_0-logloss:0.20923
[2650]	validation_0-logloss:0.20907
[2700]	validation_0-logloss:0.20918
[2750]	validation_0-logloss:0.20924
[2800]	validation_0-logloss:0.20925
[2850]	validation_0-logloss:0.20937
[2900]	validation_0-logloss:0.20943
[2950]	validation_0-logloss:0.20946
[3000]	validation_0-logloss:0.20954
[3050]	validation_0-logloss:0.20960
[3100]	validation_0-logloss:0.20954
[3150]	validation_0-logloss:0.20954
[3200]	validation_0-logloss:0.20965
[3250]	validation_0-logloss:0.20971
[3300]	validation_0-logloss:0.20975
[3350]	validation_0-logloss:0.20983
[3400]	validation_0-logloss:0.20991
[3450]	validation_0-logloss:0.20990
[3464]	validation_0-logloss:0.20991

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47509
[50]	validation_0-logloss:0.26475
[100]	validation_0-logloss:0.24894
[150]	validation_0-logloss:0.24041
[200]	validation_0-logloss:0.23455
[250]	validation_0-logloss:0.23076
[300]	validation_0-logloss:0.22812
[350]	validation_0-logloss:0.22527
[400]	validation_0-logloss:0.22321
[450]	validation_0-logloss:0.22141
[500]	validation_0-logloss:0.21993
[550]	validation_0-logloss:0.21860
[600]	validation_0-logloss:0.21744
[650]	validation_0-logloss:0.21652
[700]	validation_0-logloss:0.21561
[750]	validation_0-logloss:0.21502
[800]	validation_0-logloss:0.21442
[850]	validation_0-logloss:0.21370
[900]	validation_0-logloss:0.21319
[950]	validation_0-logloss:0.21283
[1000]	validation_0-logloss:0.21250
[1050]	validation_0-logloss:0.21208
[1100]	validation_0-logloss:0.21171
[1150]	validation_0-logloss:0.21129
[1200]	validation_0-logloss:0.21087
[1250]	validation_0-logloss:0.21052
[1300]	validation_0-logloss:0.21026
[1350]	validation_0-logloss:0.21011
[1400]	validation_0-logloss:0.21003
[1450]	validation_0-logloss:0.20991
[1500]	validation_0-logloss:0.20985
[1550]	validation_0-logloss:0.20977
[1600]	validation_0-logloss:0.20964
[1650]	validation_0-logloss:0.20959
[1700]	validation_0-logloss:0.20954
[1750]	validation_0-logloss:0.20947
[1800]	validation_0-logloss:0.20942
[1850]	validation_0-logloss:0.20940
[1900]	validation_0-logloss:0.20929
[1950]	validation_0-logloss:0.20920
[2000]	validation_0-logloss:0.20918
[2050]	validation_0-logloss:0.20912
[2100]	validation_0-logloss:0.20907
[2150]	validation_0-logloss:0.20894
[2200]	validation_0-logloss:0.20890
[2250]	validation_0-logloss:0.20881
[2300]	validation_0-logloss:0.20881
[2350]	validation_0-logloss:0.20870
[2400]	validation_0-logloss:0.20853
[2450]	validation_0-logloss:0.20855
[2500]	validation_0-logloss:0.20852
[2550]	validation_0-logloss:0.20850
[2600]	validation_0-logloss:0.20853
[2650]	validation_0-logloss:0.20860
[2700]	validation_0-logloss:0.20864
[2750]	validation_0-logloss:0.20867
[2800]	validation_0-logloss:0.20864
[2850]	validation_0-logloss:0.20871
[2900]	validation_0-logloss:0.20863
[2950]	validation_0-logloss:0.20868
[3000]	validation_0-logloss:0.20872
[3050]	validation_0-logloss:0.20877
[3100]	validation_0-logloss:0.20888
[3150]	validation_0-logloss:0.20887
[3200]	validation_0-logloss:0.20889
[3250]	validation_0-logloss:0.20897
[3300]	validation_0-logloss:0.20894
[3312]	validation_0-logloss:0.20895

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47512
[50]	validation_0-logloss:0.26640
[100]	validation_0-logloss:0.24997
[150]	validation_0-logloss:0.24159
[200]	validation_0-logloss:0.23586
[250]	validation_0-logloss:0.23234
[300]	validation_0-logloss:0.22936
[350]	validation_0-logloss:0.22709
[400]	validation_0-logloss:0.22497
[450]	validation_0-logloss:0.22314
[500]	validation_0-logloss:0.22165
[550]	validation_0-logloss:0.22044
[600]	validation_0-logloss:0.21918
[650]	validation_0-logloss:0.21842
[700]	validation_0-logloss:0.21785
[750]	validation_0-logloss:0.21708
[800]	validation_0-logloss:0.21640
[850]	validation_0-logloss:0.21574
[900]	validation_0-logloss:0.21536
[950]	validation_0-logloss:0.21509
[1000]	validation_0-logloss:0.21478
[1050]	validation_0-logloss:0.21450
[1100]	validation_0-logloss:0.21420
[1150]	validation_0-logloss:0.21388
[1200]	validation_0-logloss:0.21349
[1250]	validation_0-logloss:0.21318
[1300]	validation_0-logloss:0.21308
[1350]	validation_0-logloss:0.21264
[1400]	validation_0-logloss:0.21238
[1450]	validation_0-logloss:0.21222
[1500]	validation_0-logloss:0.21216
[1550]	validation_0-logloss:0.21202
[1600]	validation_0-logloss:0.21201
[1650]	validation_0-logloss:0.21193
[1700]	validation_0-logloss:0.21174
[1750]	validation_0-logloss:0.21156
[1800]	validation_0-logloss:0.21149
[1850]	validation_0-logloss:0.21140
[1900]	validation_0-logloss:0.21135
[1950]	validation_0-logloss:0.21124
[2000]	validation_0-logloss:0.21116
[2050]	validation_0-logloss:0.21116
[2100]	validation_0-logloss:0.21107
[2150]	validation_0-logloss:0.21104
[2200]	validation_0-logloss:0.21107
[2250]	validation_0-logloss:0.21099
[2300]	validation_0-logloss:0.21104
[2350]	validation_0-logloss:0.21100
[2400]	validation_0-logloss:0.21105
[2450]	validation_0-logloss:0.21104
[2500]	validation_0-logloss:0.21113
[2550]	validation_0-logloss:0.21110
[2600]	validation_0-logloss:0.21107
[2650]	validation_0-logloss:0.21098
[2700]	validation_0-logloss:0.21101
[2750]	validation_0-logloss:0.21100
[2800]	validation_0-logloss:0.21108
[2850]	validation_0-logloss:0.21111
[2900]	validation_0-logloss:0.21108
[2950]	validation_0-logloss:0.21108
[3000]	validation_0-logloss:0.21112
[3050]	validation_0-logloss:0.21115
[3100]	validation_0-logloss:0.21123
[3150]	validation_0-logloss:0.21129
[3200]	validation_0-logloss:0.21136
[3250]	validation_0-logloss:0.21146
[3300]	validation_0-logloss:0.21145
[3350]	validation_0-logloss:0.21151
[3400]	validation_0-logloss:0.21153
[3450]	validation_0-logloss:0.21160
[3491]	validation_0-logloss:0.21167

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47491
[50]	validation_0-logloss:0.26570
[100]	validation_0-logloss:0.24933
[150]	validation_0-logloss:0.24126
[200]	validation_0-logloss:0.23558
[250]	validation_0-logloss:0.23164
[300]	validation_0-logloss:0.22831
[350]	validation_0-logloss:0.22609
[400]	validation_0-logloss:0.22372
[450]	validation_0-logloss:0.22198
[500]	validation_0-logloss:0.22059
[550]	validation_0-logloss:0.21923
[600]	validation_0-logloss:0.21803
[650]	validation_0-logloss:0.21731
[700]	validation_0-logloss:0.21669
[750]	validation_0-logloss:0.21608
[800]	validation_0-logloss:0.21544
[850]	validation_0-logloss:0.21498
[900]	validation_0-logloss:0.21453
[950]	validation_0-logloss:0.21417
[1000]	validation_0-logloss:0.21374
[1050]	validation_0-logloss:0.21327
[1100]	validation_0-logloss:0.21301
[1150]	validation_0-logloss:0.21271
[1200]	validation_0-logloss:0.21248
[1250]	validation_0-logloss:0.21232
[1300]	validation_0-logloss:0.21197
[1350]	validation_0-logloss:0.21174
[1400]	validation_0-logloss:0.21154
[1450]	validation_0-logloss:0.21140
[1500]	validation_0-logloss:0.21117
[1550]	validation_0-logloss:0.21103
[1600]	validation_0-logloss:0.21094
[1650]	validation_0-logloss:0.21078
[1700]	validation_0-logloss:0.21076
[1750]	validation_0-logloss:0.21069
[1800]	validation_0-logloss:0.21068
[1850]	validation_0-logloss:0.21058
[1900]	validation_0-logloss:0.21046
[1950]	validation_0-logloss:0.21044
[2000]	validation_0-logloss:0.21045
[2050]	validation_0-logloss:0.21035
[2100]	validation_0-logloss:0.21036
[2150]	validation_0-logloss:0.21030
[2200]	validation_0-logloss:0.21031
[2250]	validation_0-logloss:0.21026
[2300]	validation_0-logloss:0.21026
[2350]	validation_0-logloss:0.21028
[2400]	validation_0-logloss:0.21029
[2450]	validation_0-logloss:0.21020
[2500]	validation_0-logloss:0.21022
[2550]	validation_0-logloss:0.21010
[2600]	validation_0-logloss:0.21007
[2650]	validation_0-logloss:0.21016
[2700]	validation_0-logloss:0.21016
[2750]	validation_0-logloss:0.21016
[2800]	validation_0-logloss:0.21017
[2850]	validation_0-logloss:0.21024
[2900]	validation_0-logloss:0.21029
[2950]	validation_0-logloss:0.21029
[3000]	validation_0-logloss:0.21037
[3050]	validation_0-logloss:0.21042
[3100]	validation_0-logloss:0.21044
[3150]	validation_0-logloss:0.21045
[3200]	validation_0-logloss:0.21048
[3250]	validation_0-logloss:0.21053
[3300]	validation_0-logloss:0.21055
[3350]	validation_0-logloss:0.21061
[3400]	validation_0-logloss:0.21073
[3401]	validation_0-logloss:0.21073

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47470
[50]	validation_0-logloss:0.26171
[100]	validation_0-logloss:0.24545
[150]	validation_0-logloss:0.23699
[200]	validation_0-logloss:0.23119
[250]	validation_0-logloss:0.22706
[300]	validation_0-logloss:0.22379
[350]	validation_0-logloss:0.22121
[400]	validation_0-logloss:0.21914
[450]	validation_0-logloss:0.21722
[500]	validation_0-logloss:0.21548
[550]	validation_0-logloss:0.21405
[600]	validation_0-logloss:0.21291
[650]	validation_0-logloss:0.21188
[700]	validation_0-logloss:0.21094
[750]	validation_0-logloss:0.21013
[800]	validation_0-logloss:0.20939
[850]	validation_0-logloss:0.20881
[900]	validation_0-logloss:0.20825
[950]	validation_0-logloss:0.20786
[1000]	validation_0-logloss:0.20745
[1050]	validation_0-logloss:0.20696
[1100]	validation_0-logloss:0.20665
[1150]	validation_0-logloss:0.20637
[1200]	validation_0-logloss:0.20618
[1250]	validation_0-logloss:0.20584
[1300]	validation_0-logloss:0.20558
[1350]	validation_0-logloss:0.20543
[1400]	validation_0-logloss:0.20518
[1450]	validation_0-logloss:0.20506
[1500]	validation_0-logloss:0.20489
[1550]	validation_0-logloss:0.20470
[1600]	validation_0-logloss:0.20461
[1650]	validation_0-logloss:0.20454
[1700]	validation_0-logloss:0.20437
[1750]	validation_0-logloss:0.20422
[1800]	validation_0-logloss:0.20412
[1850]	validation_0-logloss:0.20408
[1900]	validation_0-logloss:0.20393
[1950]	validation_0-logloss:0.20388
[2000]	validation_0-logloss:0.20390
[2050]	validation_0-logloss:0.20387
[2100]	validation_0-logloss:0.20377
[2150]	validation_0-logloss:0.20369
[2200]	validation_0-logloss:0.20372
[2250]	validation_0-logloss:0.20370
[2300]	validation_0-logloss:0.20366
[2350]	validation_0-logloss:0.20362
[2400]	validation_0-logloss:0.20366
[2450]	validation_0-logloss:0.20361
[2500]	validation_0-logloss:0.20364
[2550]	validation_0-logloss:0.20370
[2600]	validation_0-logloss:0.20376
[2650]	validation_0-logloss:0.20387
[2700]	validation_0-logloss:0.20386
[2750]	validation_0-logloss:0.20384
[2800]	validation_0-logloss:0.20386
[2850]	validation_0-logloss:0.20387
[2900]	validation_0-logloss:0.20389
[2950]	validation_0-logloss:0.20385
[3000]	validation_0-logloss:0.20390
[3050]	validation_0-logloss:0.20392
[3100]	validation_0-logloss:0.20396
[3150]	validation_0-logloss:0.20407
[3200]	validation_0-logloss:0.20412
[3236]	validation_0-logloss:0.20418

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47496
[50]	validation_0-logloss:0.26616
[100]	validation_0-logloss:0.25004
[150]	validation_0-logloss:0.24155
[200]	validation_0-logloss:0.23620
[250]	validation_0-logloss:0.23241
[300]	validation_0-logloss:0.22915
[350]	validation_0-logloss:0.22706
[400]	validation_0-logloss:0.22489
[450]	validation_0-logloss:0.22341
[500]	validation_0-logloss:0.22203
[550]	validation_0-logloss:0.22030
[600]	validation_0-logloss:0.21952
[650]	validation_0-logloss:0.21857
[700]	validation_0-logloss:0.21806
[750]	validation_0-logloss:0.21750
[800]	validation_0-logloss:0.21671
[850]	validation_0-logloss:0.21603
[900]	validation_0-logloss:0.21567
[950]	validation_0-logloss:0.21517
[1000]	validation_0-logloss:0.21483
[1050]	validation_0-logloss:0.21466
[1100]	validation_0-logloss:0.21413
[1150]	validation_0-logloss:0.21376
[1200]	validation_0-logloss:0.21349
[1250]	validation_0-logloss:0.21316
[1300]	validation_0-logloss:0.21296
[1350]	validation_0-logloss:0.21269
[1400]	validation_0-logloss:0.21256
[1450]	validation_0-logloss:0.21248
[1500]	validation_0-logloss:0.21232
[1550]	validation_0-logloss:0.21220
[1600]	validation_0-logloss:0.21209
[1650]	validation_0-logloss:0.21200
[1700]	validation_0-logloss:0.21184
[1750]	validation_0-logloss:0.21179
[1800]	validation_0-logloss:0.21164
[1850]	validation_0-logloss:0.21162
[1900]	validation_0-logloss:0.21153
[1950]	validation_0-logloss:0.21153
[2000]	validation_0-logloss:0.21157
[2050]	validation_0-logloss:0.21154
[2100]	validation_0-logloss:0.21150
[2150]	validation_0-logloss:0.21148
[2200]	validation_0-logloss:0.21140
[2250]	validation_0-logloss:0.21144
[2300]	validation_0-logloss:0.21134
[2350]	validation_0-logloss:0.21137
[2400]	validation_0-logloss:0.21146
[2450]	validation_0-logloss:0.21141
[2500]	validation_0-logloss:0.21147
[2550]	validation_0-logloss:0.21152
[2600]	validation_0-logloss:0.21153
[2650]	validation_0-logloss:0.21150
[2700]	validation_0-logloss:0.21153
[2750]	validation_0-logloss:0.21156
[2800]	validation_0-logloss:0.21159
[2850]	validation_0-logloss:0.21166
[2900]	validation_0-logloss:0.21177
[2950]	validation_0-logloss:0.21185
[3000]	validation_0-logloss:0.21191
[3006]	validation_0-logloss:0.21192

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47488
[50]	validation_0-logloss:0.26287
[100]	validation_0-logloss:0.24667
[150]	validation_0-logloss:0.23909
[200]	validation_0-logloss:0.23326
[250]	validation_0-logloss:0.22940
[300]	validation_0-logloss:0.22653
[350]	validation_0-logloss:0.22424
[400]	validation_0-logloss:0.22219
[450]	validation_0-logloss:0.22073
[500]	validation_0-logloss:0.21932
[550]	validation_0-logloss:0.21834
[600]	validation_0-logloss:0.21738
[650]	validation_0-logloss:0.21642
[700]	validation_0-logloss:0.21549
[750]	validation_0-logloss:0.21474
[800]	validation_0-logloss:0.21412
[850]	validation_0-logloss:0.21347
[900]	validation_0-logloss:0.21290
[950]	validation_0-logloss:0.21248
[1000]	validation_0-logloss:0.21200
[1050]	validation_0-logloss:0.21160
[1100]	validation_0-logloss:0.21135
[1150]	validation_0-logloss:0.21090
[1200]	validation_0-logloss:0.21063
[1250]	validation_0-logloss:0.21044
[1300]	validation_0-logloss:0.21018
[1350]	validation_0-logloss:0.20980
[1400]	validation_0-logloss:0.20972
[1450]	validation_0-logloss:0.20948
[1500]	validation_0-logloss:0.20937
[1550]	validation_0-logloss:0.20926
[1600]	validation_0-logloss:0.20920
[1650]	validation_0-logloss:0.20912
[1700]	validation_0-logloss:0.20903
[1750]	validation_0-logloss:0.20882
[1800]	validation_0-logloss:0.20871
[1850]	validation_0-logloss:0.20866
[1900]	validation_0-logloss:0.20858
[1950]	validation_0-logloss:0.20848
[2000]	validation_0-logloss:0.20840
[2050]	validation_0-logloss:0.20838
[2100]	validation_0-logloss:0.20837
[2150]	validation_0-logloss:0.20843
[2200]	validation_0-logloss:0.20835
[2250]	validation_0-logloss:0.20826
[2300]	validation_0-logloss:0.20824
[2350]	validation_0-logloss:0.20824
[2400]	validation_0-logloss:0.20822
[2450]	validation_0-logloss:0.20821
[2500]	validation_0-logloss:0.20819
[2550]	validation_0-logloss:0.20816
[2600]	validation_0-logloss:0.20820
[2650]	validation_0-logloss:0.20823
[2700]	validation_0-logloss:0.20827
[2750]	validation_0-logloss:0.20838
[2800]	validation_0-logloss:0.20845
[2850]	validation_0-logloss:0.20850
[2900]	validation_0-logloss:0.20857
[2950]	validation_0-logloss:0.20856
[3000]	validation_0-logloss:0.20852
[3050]	validation_0-logloss:0.20854
[3100]	validation_0-logloss:0.20864
[3150]	validation_0-logloss:0.20867
[3200]	validation_0-logloss:0.20875
[3250]	validation_0-logloss:0.20884
[3300]	validation_0-logloss:0.20888
[3306]	validation_0-logloss:0.20889

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47501
[50]	validation_0-logloss:0.26414
[100]	validation_0-logloss:0.24749
[150]	validation_0-logloss:0.24000
[200]	validation_0-logloss:0.23448
[250]	validation_0-logloss:0.23130
[300]	validation_0-logloss:0.22797
[350]	validation_0-logloss:0.22489
[400]	validation_0-logloss:0.22276
[450]	validation_0-logloss:0.22143
[500]	validation_0-logloss:0.22019
[550]	validation_0-logloss:0.21921
[600]	validation_0-logloss:0.21780
[650]	validation_0-logloss:0.21688
[700]	validation_0-logloss:0.21599
[750]	validation_0-logloss:0.21521
[800]	validation_0-logloss:0.21457
[850]	validation_0-logloss:0.21404
[900]	validation_0-logloss:0.21369
[950]	validation_0-logloss:0.21300
[1000]	validation_0-logloss:0.21252
[1050]	validation_0-logloss:0.21215
[1100]	validation_0-logloss:0.21187
[1150]	validation_0-logloss:0.21158
[1200]	validation_0-logloss:0.21136
[1250]	validation_0-logloss:0.21116
[1300]	validation_0-logloss:0.21105
[1350]	validation_0-logloss:0.21091
[1400]	validation_0-logloss:0.21076
[1450]	validation_0-logloss:0.21066
[1500]	validation_0-logloss:0.21040
[1550]	validation_0-logloss:0.21015
[1600]	validation_0-logloss:0.20989
[1650]	validation_0-logloss:0.20981
[1700]	validation_0-logloss:0.20971
[1750]	validation_0-logloss:0.20956
[1800]	validation_0-logloss:0.20937
[1850]	validation_0-logloss:0.20937
[1900]	validation_0-logloss:0.20928
[1950]	validation_0-logloss:0.20925
[2000]	validation_0-logloss:0.20923
[2050]	validation_0-logloss:0.20924
[2100]	validation_0-logloss:0.20917
[2150]	validation_0-logloss:0.20903
[2200]	validation_0-logloss:0.20895
[2250]	validation_0-logloss:0.20899
[2300]	validation_0-logloss:0.20899
[2350]	validation_0-logloss:0.20901
[2400]	validation_0-logloss:0.20901
[2450]	validation_0-logloss:0.20902
[2500]	validation_0-logloss:0.20900
[2550]	validation_0-logloss:0.20910
[2600]	validation_0-logloss:0.20906
[2650]	validation_0-logloss:0.20907
[2700]	validation_0-logloss:0.20900
[2750]	validation_0-logloss:0.20906
[2800]	validation_0-logloss:0.20906
[2850]	validation_0-logloss:0.20905
[2884]	validation_0-logloss:0.20912

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L1\model.pkl
	0.9584	 = Validation score   (roc_auc)
	487.22s	 = Training   runtime
	3.3s	 = Validation runtime
	18221.4	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 4161.82s of the 6862.85s of remaining time.
	Fitting NeuralNetTorch_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\NeuralNetTorch_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\NeuralNetTorch_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420345 examples, 22 features (19 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=54, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.3249, Val roc_auc: 0.9188, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2857, Val roc_auc: 0.9286, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2731, Val roc_auc: 0.9336, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.2652, Val roc_auc: 0.9377, Best Epoch: 4
Epoch 5 (Update 8205).	Train loss: 0.2591, Val roc_auc: 0.9401, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.254, Val roc_auc: 0.942, Best Epoch: 6
Epoch 7 (Update 11487).	Train loss: 0.2506, Val roc_auc: 0.944, Best Epoch: 7
Epoch 8 (Update 13128).	Train loss: 0.2471, Val roc_auc: 0.945, Best Epoch: 8
Epoch 9 (Update 14769).	Train loss: 0.2442, Val roc_auc: 0.9457, Best Epoch: 9
Epoch 10 (Update 16410).	Train loss: 0.2414, Val roc_auc: 0.9477, Best Epoch: 10
Epoch 11 (Update 18051).	Train loss: 0.2389, Val roc_auc: 0.9481, Best Epoch: 11
Epoch 12 (Update 19692).	Train loss: 0.2366, Val roc_auc: 0.9492, Best Epoch: 12
Epoch 13 (Update 21333).	Train loss: 0.2345, Val roc_auc: 0.9496, Best Epoch: 13
Epoch 14 (Update 22974).	Train loss: 0.2329, Val roc_auc: 0.9505, Best Epoch: 14
Epoch 15 (Update 24615).	Train loss: 0.2307, Val roc_auc: 0.9509, Best Epoch: 15
Epoch 16 (Update 26256).	Train loss: 0.2288, Val roc_auc: 0.9514, Best Epoch: 16
Epoch 17 (Update 27897).	Train loss: 0.2275, Val roc_auc: 0.9517, Best Epoch: 17
Epoch 18 (Update 29538).	Train loss: 0.2266, Val roc_auc: 0.9519, Best Epoch: 18
Epoch 19 (Update 31179).	Train loss: 0.2255, Val roc_auc: 0.9526, Best Epoch: 19
Epoch 20 (Update 32820).	Train loss: 0.2242, Val roc_auc: 0.9522, Best Epoch: 19
Epoch 21 (Update 34461).	Train loss: 0.223, Val roc_auc: 0.9534, Best Epoch: 21
Epoch 22 (Update 36102).	Train loss: 0.2219, Val roc_auc: 0.9531, Best Epoch: 21
Epoch 23 (Update 37743).	Train loss: 0.2211, Val roc_auc: 0.9534, Best Epoch: 21
Epoch 24 (Update 39384).	Train loss: 0.2203, Val roc_auc: 0.9533, Best Epoch: 21
Epoch 25 (Update 41025).	Train loss: 0.2196, Val roc_auc: 0.9538, Best Epoch: 25
Epoch 26 (Update 42666).	Train loss: 0.2192, Val roc_auc: 0.9541, Best Epoch: 26
Epoch 27 (Update 44307).	Train loss: 0.218, Val roc_auc: 0.9541, Best Epoch: 27
Epoch 28 (Update 45948).	Train loss: 0.2174, Val roc_auc: 0.9537, Best Epoch: 27
Epoch 29 (Update 47589).	Train loss: 0.2164, Val roc_auc: 0.9544, Best Epoch: 29
Epoch 30 (Update 49230).	Train loss: 0.2164, Val roc_auc: 0.9547, Best Epoch: 30
Epoch 31 (Update 50871).	Train loss: 0.2153, Val roc_auc: 0.9548, Best Epoch: 31
Epoch 32 (Update 52512).	Train loss: 0.2145, Val roc_auc: 0.9544, Best Epoch: 31
Epoch 33 (Update 54153).	Train loss: 0.2146, Val roc_auc: 0.955, Best Epoch: 33
Epoch 34 (Update 55794).	Train loss: 0.214, Val roc_auc: 0.955, Best Epoch: 34
Epoch 35 (Update 57435).	Train loss: 0.2139, Val roc_auc: 0.955, Best Epoch: 34
Epoch 36 (Update 59076).	Train loss: 0.2129, Val roc_auc: 0.9549, Best Epoch: 34
Epoch 37 (Update 60717).	Train loss: 0.2128, Val roc_auc: 0.9553, Best Epoch: 37
Epoch 38 (Update 62358).	Train loss: 0.2124, Val roc_auc: 0.955, Best Epoch: 37
Epoch 39 (Update 63999).	Train loss: 0.212, Val roc_auc: 0.9552, Best Epoch: 37
Epoch 40 (Update 65640).	Train loss: 0.2112, Val roc_auc: 0.9554, Best Epoch: 40
Epoch 41 (Update 67281).	Train loss: 0.2107, Val roc_auc: 0.9553, Best Epoch: 40
Epoch 42 (Update 68922).	Train loss: 0.2106, Val roc_auc: 0.9553, Best Epoch: 40
Epoch 43 (Update 70563).	Train loss: 0.2102, Val roc_auc: 0.9558, Best Epoch: 43
Epoch 44 (Update 72204).	Train loss: 0.2099, Val roc_auc: 0.9555, Best Epoch: 43
Epoch 45 (Update 73845).	Train loss: 0.2096, Val roc_auc: 0.9559, Best Epoch: 45
Epoch 46 (Update 75486).	Train loss: 0.2097, Val roc_auc: 0.9555, Best Epoch: 45
Epoch 47 (Update 77127).	Train loss: 0.2092, Val roc_auc: 0.9554, Best Epoch: 45
Epoch 48 (Update 78768).	Train loss: 0.2088, Val roc_auc: 0.956, Best Epoch: 48
Epoch 49 (Update 80409).	Train loss: 0.2085, Val roc_auc: 0.9558, Best Epoch: 48
Epoch 50 (Update 82050).	Train loss: 0.2076, Val roc_auc: 0.956, Best Epoch: 48
Epoch 51 (Update 83691).	Train loss: 0.2071, Val roc_auc: 0.9556, Best Epoch: 48
Epoch 52 (Update 85332).	Train loss: 0.2072, Val roc_auc: 0.9561, Best Epoch: 52
Epoch 53 (Update 86973).	Train loss: 0.2073, Val roc_auc: 0.9559, Best Epoch: 52
Epoch 54 (Update 88614).	Train loss: 0.2071, Val roc_auc: 0.9557, Best Epoch: 52
Epoch 55 (Update 90255).	Train loss: 0.2072, Val roc_auc: 0.9562, Best Epoch: 55
Epoch 56 (Update 91896).	Train loss: 0.2063, Val roc_auc: 0.9562, Best Epoch: 56
Epoch 57 (Update 93537).	Train loss: 0.2059, Val roc_auc: 0.9559, Best Epoch: 56
Epoch 58 (Update 95178).	Train loss: 0.206, Val roc_auc: 0.9561, Best Epoch: 56
Epoch 59 (Update 96819).	Train loss: 0.2058, Val roc_auc: 0.956, Best Epoch: 56
Epoch 60 (Update 98460).	Train loss: 0.2055, Val roc_auc: 0.9559, Best Epoch: 56
Epoch 61 (Update 100101).	Train loss: 0.2053, Val roc_auc: 0.9562, Best Epoch: 56
Epoch 62 (Update 101742).	Train loss: 0.2049, Val roc_auc: 0.9563, Best Epoch: 62
Epoch 63 (Update 103383).	Train loss: 0.2046, Val roc_auc: 0.9563, Best Epoch: 62
Epoch 64 (Update 105024).	Train loss: 0.2043, Val roc_auc: 0.9559, Best Epoch: 62
Epoch 65 (Update 106665).	Train loss: 0.2044, Val roc_auc: 0.9559, Best Epoch: 62
Epoch 66 (Update 108306).	Train loss: 0.2047, Val roc_auc: 0.9561, Best Epoch: 62
Epoch 67 (Update 109947).	Train loss: 0.2037, Val roc_auc: 0.9562, Best Epoch: 62
Epoch 68 (Update 111588).	Train loss: 0.2039, Val roc_auc: 0.9561, Best Epoch: 62
Epoch 69 (Update 113229).	Train loss: 0.2036, Val roc_auc: 0.9559, Best Epoch: 62
Epoch 70 (Update 114870).	Train loss: 0.203, Val roc_auc: 0.9559, Best Epoch: 62
Epoch 71 (Update 116511).	Train loss: 0.2032, Val roc_auc: 0.9558, Best Epoch: 62
Epoch 72 (Update 118152).	Train loss: 0.2031, Val roc_auc: 0.9562, Best Epoch: 62
Epoch 73 (Update 119793).	Train loss: 0.203, Val roc_auc: 0.9562, Best Epoch: 62
Epoch 74 (Update 121434).	Train loss: 0.2024, Val roc_auc: 0.9562, Best Epoch: 62
Epoch 75 (Update 123075).	Train loss: 0.2023, Val roc_auc: 0.9562, Best Epoch: 62
Epoch 76 (Update 124716).	Train loss: 0.2027, Val roc_auc: 0.9564, Best Epoch: 76
Epoch 77 (Update 126357).	Train loss: 0.202, Val roc_auc: 0.9562, Best Epoch: 76
Epoch 78 (Update 127998).	Train loss: 0.2019, Val roc_auc: 0.9561, Best Epoch: 76
Epoch 79 (Update 129639).	Train loss: 0.2018, Val roc_auc: 0.9562, Best Epoch: 76
Epoch 80 (Update 131280).	Train loss: 0.2016, Val roc_auc: 0.9563, Best Epoch: 76
Epoch 81 (Update 132921).	Train loss: 0.2019, Val roc_auc: 0.9563, Best Epoch: 76
Epoch 82 (Update 134562).	Train loss: 0.2013, Val roc_auc: 0.9563, Best Epoch: 76
Epoch 83 (Update 136203).	Train loss: 0.2013, Val roc_auc: 0.9567, Best Epoch: 83
Epoch 84 (Update 137844).	Train loss: 0.2012, Val roc_auc: 0.9563, Best Epoch: 83
Epoch 85 (Update 139485).	Train loss: 0.2014, Val roc_auc: 0.9565, Best Epoch: 83
Epoch 86 (Update 141126).	Train loss: 0.2, Val roc_auc: 0.9563, Best Epoch: 83
Epoch 87 (Update 142767).	Train loss: 0.2007, Val roc_auc: 0.9561, Best Epoch: 83
Epoch 88 (Update 144408).	Train loss: 0.2005, Val roc_auc: 0.9564, Best Epoch: 83
Epoch 89 (Update 146049).	Train loss: 0.2005, Val roc_auc: 0.9565, Best Epoch: 83
Epoch 90 (Update 147690).	Train loss: 0.201, Val roc_auc: 0.956, Best Epoch: 83
Epoch 91 (Update 149331).	Train loss: 0.2005, Val roc_auc: 0.9564, Best Epoch: 83
Epoch 92 (Update 150972).	Train loss: 0.2001, Val roc_auc: 0.9568, Best Epoch: 92
Epoch 93 (Update 152613).	Train loss: 0.2, Val roc_auc: 0.9565, Best Epoch: 92
Epoch 94 (Update 154254).	Train loss: 0.2, Val roc_auc: 0.9565, Best Epoch: 92
Epoch 95 (Update 155895).	Train loss: 0.1992, Val roc_auc: 0.9561, Best Epoch: 92
Epoch 96 (Update 157536).	Train loss: 0.1995, Val roc_auc: 0.9568, Best Epoch: 92
Epoch 97 (Update 159177).	Train loss: 0.1991, Val roc_auc: 0.957, Best Epoch: 97
Epoch 98 (Update 160818).	Train loss: 0.1995, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 99 (Update 162459).	Train loss: 0.1986, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 100 (Update 164100).	Train loss: 0.1991, Val roc_auc: 0.9567, Best Epoch: 97
Epoch 101 (Update 165741).	Train loss: 0.1989, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 102 (Update 167382).	Train loss: 0.1986, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 103 (Update 169023).	Train loss: 0.199, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 104 (Update 170664).	Train loss: 0.1986, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 105 (Update 172305).	Train loss: 0.1981, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 106 (Update 173946).	Train loss: 0.198, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 107 (Update 175587).	Train loss: 0.1981, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 108 (Update 177228).	Train loss: 0.1982, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 109 (Update 178869).	Train loss: 0.1982, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 110 (Update 180510).	Train loss: 0.1977, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 111 (Update 182151).	Train loss: 0.198, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 112 (Update 183792).	Train loss: 0.1977, Val roc_auc: 0.9568, Best Epoch: 97
Epoch 113 (Update 185433).	Train loss: 0.1976, Val roc_auc: 0.9567, Best Epoch: 97
Epoch 114 (Update 187074).	Train loss: 0.1971, Val roc_auc: 0.9568, Best Epoch: 97
Epoch 115 (Update 188715).	Train loss: 0.1977, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 116 (Update 190356).	Train loss: 0.1969, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 117 (Update 191997).	Train loss: 0.197, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 118 (Update 193638).	Train loss: 0.197, Val roc_auc: 0.956, Best Epoch: 97
Epoch 119 (Update 195279).	Train loss: 0.1974, Val roc_auc: 0.9568, Best Epoch: 97
Epoch 120 (Update 196920).	Train loss: 0.1974, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 121 (Update 198561).	Train loss: 0.1968, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 122 (Update 200202).	Train loss: 0.1965, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 123 (Update 201843).	Train loss: 0.1966, Val roc_auc: 0.9567, Best Epoch: 97
Epoch 124 (Update 203484).	Train loss: 0.1965, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 125 (Update 205125).	Train loss: 0.1964, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 126 (Update 206766).	Train loss: 0.1962, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 127 (Update 208407).	Train loss: 0.1959, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 128 (Update 210048).	Train loss: 0.1969, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 129 (Update 211689).	Train loss: 0.1964, Val roc_auc: 0.9568, Best Epoch: 97
Epoch 130 (Update 213330).	Train loss: 0.1964, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 131 (Update 214971).	Train loss: 0.1959, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 132 (Update 216612).	Train loss: 0.1957, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 133 (Update 218253).	Train loss: 0.1957, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 134 (Update 219894).	Train loss: 0.1957, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 135 (Update 221535).	Train loss: 0.1954, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 136 (Update 223176).	Train loss: 0.1955, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 137 (Update 224817).	Train loss: 0.1952, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 138 (Update 226458).	Train loss: 0.1959, Val roc_auc: 0.956, Best Epoch: 97
Epoch 139 (Update 228099).	Train loss: 0.1953, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 140 (Update 229740).	Train loss: 0.1951, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 141 (Update 231381).	Train loss: 0.1951, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 142 (Update 233022).	Train loss: 0.1951, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 143 (Update 234663).	Train loss: 0.1948, Val roc_auc: 0.9561, Best Epoch: 97
Epoch 144 (Update 236304).	Train loss: 0.1944, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 145 (Update 237945).	Train loss: 0.1948, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 146 (Update 239586).	Train loss: 0.1947, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 147 (Update 241227).	Train loss: 0.195, Val roc_auc: 0.956, Best Epoch: 97
Epoch 148 (Update 242868).	Train loss: 0.1946, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 149 (Update 244509).	Train loss: 0.1944, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 150 (Update 246150).	Train loss: 0.1945, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 151 (Update 247791).	Train loss: 0.1946, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 152 (Update 249432).	Train loss: 0.1949, Val roc_auc: 0.9565, Best Epoch: 97
Epoch 153 (Update 251073).	Train loss: 0.1942, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 154 (Update 252714).	Train loss: 0.1942, Val roc_auc: 0.9563, Best Epoch: 97
Epoch 155 (Update 254355).	Train loss: 0.1946, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 156 (Update 255996).	Train loss: 0.1938, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 157 (Update 257637).	Train loss: 0.1942, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 158 (Update 259278).	Train loss: 0.1931, Val roc_auc: 0.956, Best Epoch: 97
Epoch 159 (Update 260919).	Train loss: 0.1941, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 160 (Update 262560).	Train loss: 0.1938, Val roc_auc: 0.9567, Best Epoch: 97
Epoch 161 (Update 264201).	Train loss: 0.1941, Val roc_auc: 0.9566, Best Epoch: 97
Epoch 162 (Update 265842).	Train loss: 0.194, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 163 (Update 267483).	Train loss: 0.1938, Val roc_auc: 0.9562, Best Epoch: 97
Epoch 164 (Update 269124).	Train loss: 0.1931, Val roc_auc: 0.9564, Best Epoch: 97
Epoch 165 (Update 270765).	Train loss: 0.1938, Val roc_auc: 0.9563, Best Epoch: 97
Best model found on Epoch 97 (Update 159177). Val roc_auc: 0.9569809201662065
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420345 examples, 22 features (19 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=54, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.325, Val roc_auc: 0.9156, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2851, Val roc_auc: 0.9261, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2721, Val roc_auc: 0.9321, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.2637, Val roc_auc: 0.9352, Best Epoch: 4
Epoch 5 (Update 8205).	Train loss: 0.2579, Val roc_auc: 0.9382, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.253, Val roc_auc: 0.94, Best Epoch: 6
Epoch 7 (Update 11487).	Train loss: 0.25, Val roc_auc: 0.942, Best Epoch: 7
Epoch 8 (Update 13128).	Train loss: 0.2465, Val roc_auc: 0.9434, Best Epoch: 8
Epoch 9 (Update 14769).	Train loss: 0.2434, Val roc_auc: 0.9447, Best Epoch: 9
Epoch 10 (Update 16410).	Train loss: 0.2411, Val roc_auc: 0.9456, Best Epoch: 10
Epoch 11 (Update 18051).	Train loss: 0.2391, Val roc_auc: 0.9461, Best Epoch: 11
Epoch 12 (Update 19692).	Train loss: 0.2366, Val roc_auc: 0.9471, Best Epoch: 12
Epoch 13 (Update 21333).	Train loss: 0.235, Val roc_auc: 0.9478, Best Epoch: 13
Epoch 14 (Update 22974).	Train loss: 0.2331, Val roc_auc: 0.9483, Best Epoch: 14
Epoch 15 (Update 24615).	Train loss: 0.2316, Val roc_auc: 0.949, Best Epoch: 15
Epoch 16 (Update 26256).	Train loss: 0.23, Val roc_auc: 0.9493, Best Epoch: 16
Epoch 17 (Update 27897).	Train loss: 0.2284, Val roc_auc: 0.9499, Best Epoch: 17
Epoch 18 (Update 29538).	Train loss: 0.227, Val roc_auc: 0.9501, Best Epoch: 18
Epoch 19 (Update 31179).	Train loss: 0.2264, Val roc_auc: 0.9503, Best Epoch: 19
Epoch 20 (Update 32820).	Train loss: 0.225, Val roc_auc: 0.9508, Best Epoch: 20
Epoch 21 (Update 34461).	Train loss: 0.2237, Val roc_auc: 0.9511, Best Epoch: 21
Epoch 22 (Update 36102).	Train loss: 0.223, Val roc_auc: 0.951, Best Epoch: 21
Epoch 23 (Update 37743).	Train loss: 0.2218, Val roc_auc: 0.9515, Best Epoch: 23
Epoch 24 (Update 39384).	Train loss: 0.2212, Val roc_auc: 0.9519, Best Epoch: 24
Epoch 25 (Update 41025).	Train loss: 0.2207, Val roc_auc: 0.952, Best Epoch: 25
Epoch 26 (Update 42666).	Train loss: 0.2195, Val roc_auc: 0.9519, Best Epoch: 25

[50]	valid_set's binary_logloss: 0.207702
[100]	valid_set's binary_logloss: 0.198925
[150]	valid_set's binary_logloss: 0.198799

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.21158
[100]	valid_set's binary_logloss: 0.203159
[150]	valid_set's binary_logloss: 0.203089

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209434
[100]	valid_set's binary_logloss: 0.201126
[150]	valid_set's binary_logloss: 0.20136

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.210834
[100]	valid_set's binary_logloss: 0.201931
[150]	valid_set's binary_logloss: 0.202027

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.208802
[100]	valid_set's binary_logloss: 0.199375
[150]	valid_set's binary_logloss: 0.199206
[200]	valid_set's binary_logloss: 0.199603

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.207591
[100]	valid_set's binary_logloss: 0.198397
[150]	valid_set's binary_logloss: 0.198302

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209138
[100]	valid_set's binary_logloss: 0.199939
[150]	valid_set's binary_logloss: 0.199913

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209438
[100]	valid_set's binary_logloss: 0.200707
[150]	valid_set's binary_logloss: 0.200746

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBM_BAG_L2\model.pkl
	0.9616	 = Validation score   (roc_auc)
	12.27s	 = Training   runtime
	0.24s	 = Validation runtime
	2712.5	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 3222.24s of the 3222.21s of remaining time.
	Fitting LightGBMLarge_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.210198
[100]	valid_set's binary_logloss: 0.199064
[150]	valid_set's binary_logloss: 0.198213
[200]	valid_set's binary_logloss: 0.198095
[250]	valid_set's binary_logloss: 0.198214

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.21402
[100]	valid_set's binary_logloss: 0.203313
[150]	valid_set's binary_logloss: 0.202306
[200]	valid_set's binary_logloss: 0.202162
[250]	valid_set's binary_logloss: 0.202242

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.212343
[100]	valid_set's binary_logloss: 0.200837
[150]	valid_set's binary_logloss: 0.200029
[200]	valid_set's binary_logloss: 0.199969
[250]	valid_set's binary_logloss: 0.199974
[300]	valid_set's binary_logloss: 0.200124

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.213106
[100]	valid_set's binary_logloss: 0.201849
[150]	valid_set's binary_logloss: 0.200993
[200]	valid_set's binary_logloss: 0.200779
[250]	valid_set's binary_logloss: 0.200905

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.211107
[100]	valid_set's binary_logloss: 0.199742
[150]	valid_set's binary_logloss: 0.19887
[200]	valid_set's binary_logloss: 0.198656
[250]	valid_set's binary_logloss: 0.198775

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.210444
[100]	valid_set's binary_logloss: 0.198934
[150]	valid_set's binary_logloss: 0.197886
[200]	valid_set's binary_logloss: 0.197645
[250]	valid_set's binary_logloss: 0.197776
[300]	valid_set's binary_logloss: 0.197785

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.210769
[100]	valid_set's binary_logloss: 0.199799
[150]	valid_set's binary_logloss: 0.199005
[200]	valid_set's binary_logloss: 0.19897
[250]	valid_set's binary_logloss: 0.199184

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.211165
[100]	valid_set's binary_logloss: 0.200283
[150]	valid_set's binary_logloss: 0.19934
[200]	valid_set's binary_logloss: 0.199298

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\LightGBMLarge_BAG_L2\model.pkl
	0.962	 = Validation score   (roc_auc)
	16.97s	 = Training   runtime
	0.5s	 = Validation runtime
	2681.2	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: CatBoost_BAG_L2 ... Training model for up to 3204.25s of the 3204.22s of remaining time.
	Fitting CatBoost_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6203154	test: 0.6201246	best: 0.6201246 (0)	total: 10.3ms	remaining: 10.3ms
1:	learn: 0.5564343	test: 0.5561849	best: 0.5561849 (1)	total: 19ms	remaining: 0us
bestTest = 0.556184885
bestIteration = 1
0:	learn: 0.6206019	test: 0.6204189	best: 0.6204189 (0)	total: 17.3ms	remaining: 13.5s
20:	learn: 0.2328401	test: 0.2311328	best: 0.2311328 (20)	total: 356ms	remaining: 12.9s
40:	learn: 0.2047168	test: 0.2030778	best: 0.2030778 (40)	total: 687ms	remaining: 12.4s
60:	learn: 0.2005127	test: 0.1991224	best: 0.1991224 (60)	total: 1.02s	remaining: 12s
80:	learn: 0.1992774	test: 0.1980581	best: 0.1980581 (80)	total: 1.37s	remaining: 11.9s
100:	learn: 0.1986175	test: 0.1975671	best: 0.1975671 (100)	total: 1.73s	remaining: 11.6s
120:	learn: 0.1982232	test: 0.1973696	best: 0.1973696 (120)	total: 2.07s	remaining: 11.3s
140:	learn: 0.1977913	test: 0.1971263	best: 0.1971263 (140)	total: 2.41s	remaining: 10.9s
160:	learn: 0.1974410	test: 0.1970070	best: 0.1970070 (160)	total: 2.75s	remaining: 10.6s
180:	learn: 0.1971696	test: 0.1969213	best: 0.1969213 (180)	total: 3.1s	remaining: 10.3s
200:	learn: 0.1969307	test: 0.1968391	best: 0.1968391 (200)	total: 3.45s	remaining: 9.96s
220:	learn: 0.1966819	test: 0.1967839	best: 0.1967828 (219)	total: 3.79s	remaining: 9.6s
240:	learn: 0.1964235	test: 0.1967080	best: 0.1967080 (240)	total: 4.13s	remaining: 9.25s
260:	learn: 0.1961459	test: 0.1966482	best: 0.1966450 (258)	total: 4.47s	remaining: 8.9s
280:	learn: 0.1959188	test: 0.1966065	best: 0.1966057 (279)	total: 4.81s	remaining: 8.57s
300:	learn: 0.1957303	test: 0.1965803	best: 0.1965803 (300)	total: 5.15s	remaining: 8.21s
320:	learn: 0.1955063	test: 0.1965519	best: 0.1965510 (319)	total: 5.5s	remaining: 7.88s
340:	learn: 0.1952967	test: 0.1964957	best: 0.1964957 (340)	total: 5.85s	remaining: 7.55s
360:	learn: 0.1951144	test: 0.1964572	best: 0.1964562 (359)	total: 6.21s	remaining: 7.22s
380:	learn: 0.1949200	test: 0.1964311	best: 0.1964311 (380)	total: 6.55s	remaining: 6.87s
400:	learn: 0.1947475	test: 0.1964154	best: 0.1964136 (399)	total: 6.9s	remaining: 6.54s
420:	learn: 0.1945688	test: 0.1964016	best: 0.1963993 (418)	total: 7.24s	remaining: 6.19s
440:	learn: 0.1944184	test: 0.1964060	best: 0.1963993 (418)	total: 7.59s	remaining: 5.85s
460:	learn: 0.1942454	test: 0.1963929	best: 0.1963914 (453)	total: 7.95s	remaining: 5.52s
480:	learn: 0.1940569	test: 0.1964055	best: 0.1963914 (453)	total: 8.3s	remaining: 5.18s
500:	learn: 0.1938511	test: 0.1963838	best: 0.1963793 (496)	total: 8.64s	remaining: 4.83s
520:	learn: 0.1936595	test: 0.1963406	best: 0.1963406 (520)	total: 8.98s	remaining: 4.48s
540:	learn: 0.1934947	test: 0.1963351	best: 0.1963325 (535)	total: 9.34s	remaining: 4.14s
560:	learn: 0.1933095	test: 0.1963385	best: 0.1963325 (535)	total: 9.68s	remaining: 3.8s
580:	learn: 0.1931464	test: 0.1963213	best: 0.1963197 (575)	total: 10s	remaining: 3.45s
600:	learn: 0.1929772	test: 0.1963127	best: 0.1963005 (592)	total: 10.4s	remaining: 3.1s
620:	learn: 0.1928254	test: 0.1963085	best: 0.1962984 (615)	total: 10.7s	remaining: 2.76s
640:	learn: 0.1926639	test: 0.1963106	best: 0.1962984 (615)	total: 11.1s	remaining: 2.42s
660:	learn: 0.1925072	test: 0.1963107	best: 0.1962965 (650)	total: 11.4s	remaining: 2.07s
680:	learn: 0.1923255	test: 0.1962968	best: 0.1962918 (676)	total: 11.8s	remaining: 1.73s
700:	learn: 0.1921577	test: 0.1962812	best: 0.1962785 (698)	total: 12.1s	remaining: 1.38s
720:	learn: 0.1919878	test: 0.1962578	best: 0.1962457 (713)	total: 12.4s	remaining: 1.03s
740:	learn: 0.1918459	test: 0.1962425	best: 0.1962385 (736)	total: 12.8s	remaining: 691ms
760:	learn: 0.1916935	test: 0.1962420	best: 0.1962218 (752)	total: 13.1s	remaining: 345ms
780:	learn: 0.1915443	test: 0.1962281	best: 0.1962218 (752)	total: 13.5s	remaining: 0us
bestTest = 0.1962218334
bestIteration = 752
Shrink model to first 753 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6202263	test: 0.6204914	best: 0.6204914 (0)	total: 8.87ms	remaining: 8.87ms
1:	learn: 0.5592513	test: 0.5597753	best: 0.5597753 (1)	total: 17.5ms	remaining: 0us
bestTest = 0.5597753174
bestIteration = 1
0:	learn: 0.6190428	test: 0.6192414	best: 0.6192414 (0)	total: 17.2ms	remaining: 18.1s
20:	learn: 0.2322030	test: 0.2348311	best: 0.2348311 (20)	total: 347ms	remaining: 17.1s
40:	learn: 0.2041541	test: 0.2075219	best: 0.2075219 (40)	total: 676ms	remaining: 16.7s
60:	learn: 0.1999789	test: 0.2036281	best: 0.2036281 (60)	total: 1.01s	remaining: 16.5s
80:	learn: 0.1986034	test: 0.2024410	best: 0.2024410 (80)	total: 1.35s	remaining: 16.2s
100:	learn: 0.1980020	test: 0.2020218	best: 0.2020218 (100)	total: 1.69s	remaining: 16s
120:	learn: 0.1975643	test: 0.2018005	best: 0.2018005 (120)	total: 2.03s	remaining: 15.7s
140:	learn: 0.1971921	test: 0.2016221	best: 0.2016221 (140)	total: 2.38s	remaining: 15.4s
160:	learn: 0.1968821	test: 0.2014921	best: 0.2014921 (160)	total: 2.73s	remaining: 15.1s
180:	learn: 0.1965983	test: 0.2013574	best: 0.2013574 (180)	total: 3.08s	remaining: 14.9s
200:	learn: 0.1963713	test: 0.2013131	best: 0.2013086 (197)	total: 3.45s	remaining: 14.6s
220:	learn: 0.1961037	test: 0.2012136	best: 0.2012136 (220)	total: 3.79s	remaining: 14.3s
240:	learn: 0.1958451	test: 0.2011265	best: 0.2011256 (239)	total: 4.13s	remaining: 14s
260:	learn: 0.1955908	test: 0.2010729	best: 0.2010682 (259)	total: 4.47s	remaining: 13.6s
280:	learn: 0.1953515	test: 0.2009868	best: 0.2009849 (279)	total: 4.81s	remaining: 13.2s
300:	learn: 0.1951436	test: 0.2009360	best: 0.2009360 (300)	total: 5.17s	remaining: 13s
320:	learn: 0.1949314	test: 0.2008924	best: 0.2008924 (320)	total: 5.52s	remaining: 12.6s
340:	learn: 0.1947553	test: 0.2008538	best: 0.2008538 (340)	total: 5.86s	remaining: 12.3s
360:	learn: 0.1945797	test: 0.2008158	best: 0.2008158 (360)	total: 6.21s	remaining: 11.9s
380:	learn: 0.1943993	test: 0.2007983	best: 0.2007957 (379)	total: 6.56s	remaining: 11.6s
400:	learn: 0.1942178	test: 0.2007716	best: 0.2007713 (399)	total: 6.9s	remaining: 11.3s
420:	learn: 0.1940345	test: 0.2007536	best: 0.2007499 (416)	total: 7.25s	remaining: 10.9s
440:	learn: 0.1938490	test: 0.2007368	best: 0.2007368 (440)	total: 7.6s	remaining: 10.6s
460:	learn: 0.1936738	test: 0.2007147	best: 0.2007134 (457)	total: 7.94s	remaining: 10.2s
480:	learn: 0.1935151	test: 0.2007004	best: 0.2007004 (480)	total: 8.3s	remaining: 9.9s
500:	learn: 0.1933510	test: 0.2006822	best: 0.2006822 (500)	total: 8.64s	remaining: 9.55s
520:	learn: 0.1931968	test: 0.2006761	best: 0.2006666 (518)	total: 8.99s	remaining: 9.22s
540:	learn: 0.1929965	test: 0.2006399	best: 0.2006399 (540)	total: 9.33s	remaining: 8.87s
560:	learn: 0.1928108	test: 0.2006152	best: 0.2006036 (555)	total: 9.69s	remaining: 8.53s
580:	learn: 0.1926613	test: 0.2006145	best: 0.2006004 (571)	total: 10s	remaining: 8.19s
600:	learn: 0.1924991	test: 0.2006001	best: 0.2006001 (600)	total: 10.4s	remaining: 7.84s
620:	learn: 0.1923294	test: 0.2005652	best: 0.2005596 (618)	total: 10.7s	remaining: 7.49s
640:	learn: 0.1921774	test: 0.2005716	best: 0.2005576 (626)	total: 11.1s	remaining: 7.15s
660:	learn: 0.1920268	test: 0.2005646	best: 0.2005576 (626)	total: 11.4s	remaining: 6.81s
680:	learn: 0.1918880	test: 0.2005714	best: 0.2005568 (663)	total: 11.8s	remaining: 6.46s
700:	learn: 0.1917240	test: 0.2005459	best: 0.2005437 (697)	total: 12.1s	remaining: 6.11s
720:	learn: 0.1915589	test: 0.2005455	best: 0.2005437 (697)	total: 12.5s	remaining: 5.77s
740:	learn: 0.1913897	test: 0.2005551	best: 0.2005437 (697)	total: 12.8s	remaining: 5.42s
bestTest = 0.2005437201
bestIteration = 697
Shrink model to first 698 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6202849	test: 0.6202491	best: 0.6202491 (0)	total: 9.04ms	remaining: 9.04ms
1:	learn: 0.5565666	test: 0.5564870	best: 0.5564870 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.556487042
bestIteration = 1
0:	learn: 0.6205973	test: 0.6205079	best: 0.6205079 (0)	total: 16.3ms	remaining: 19.8s
20:	learn: 0.2308807	test: 0.2309048	best: 0.2309048 (20)	total: 347ms	remaining: 19.7s
40:	learn: 0.2048654	test: 0.2053788	best: 0.2053788 (40)	total: 677ms	remaining: 19.4s
60:	learn: 0.2003099	test: 0.2011856	best: 0.2011856 (60)	total: 1.01s	remaining: 19.1s
80:	learn: 0.1990016	test: 0.2001716	best: 0.2001716 (80)	total: 1.35s	remaining: 18.9s
100:	learn: 0.1984019	test: 0.1997764	best: 0.1997764 (100)	total: 1.69s	remaining: 18.7s
120:	learn: 0.1979785	test: 0.1995534	best: 0.1995534 (120)	total: 2.04s	remaining: 18.4s
140:	learn: 0.1976510	test: 0.1993941	best: 0.1993941 (140)	total: 2.39s	remaining: 18.2s
160:	learn: 0.1973356	test: 0.1992553	best: 0.1992553 (160)	total: 2.73s	remaining: 17.9s
180:	learn: 0.1970245	test: 0.1991138	best: 0.1991138 (180)	total: 3.08s	remaining: 17.6s
200:	learn: 0.1967826	test: 0.1990097	best: 0.1990097 (200)	total: 3.42s	remaining: 17.3s
220:	learn: 0.1965576	test: 0.1989415	best: 0.1989404 (219)	total: 3.77s	remaining: 17s
240:	learn: 0.1962984	test: 0.1988524	best: 0.1988516 (237)	total: 4.12s	remaining: 16.7s
260:	learn: 0.1960581	test: 0.1987712	best: 0.1987712 (260)	total: 4.47s	remaining: 16.3s
280:	learn: 0.1958247	test: 0.1986910	best: 0.1986894 (278)	total: 4.84s	remaining: 16.1s
300:	learn: 0.1956269	test: 0.1986373	best: 0.1986373 (300)	total: 5.19s	remaining: 15.8s
320:	learn: 0.1954272	test: 0.1985852	best: 0.1985852 (320)	total: 5.54s	remaining: 15.4s
340:	learn: 0.1952001	test: 0.1985409	best: 0.1985409 (340)	total: 5.88s	remaining: 15.1s
360:	learn: 0.1949942	test: 0.1985019	best: 0.1985019 (360)	total: 6.23s	remaining: 14.7s
380:	learn: 0.1947861	test: 0.1984550	best: 0.1984508 (377)	total: 6.57s	remaining: 14.4s
400:	learn: 0.1945689	test: 0.1983943	best: 0.1983926 (399)	total: 6.92s	remaining: 14.1s
420:	learn: 0.1943635	test: 0.1983649	best: 0.1983640 (416)	total: 7.27s	remaining: 13.7s
440:	learn: 0.1942100	test: 0.1983367	best: 0.1983367 (440)	total: 7.62s	remaining: 13.4s
460:	learn: 0.1939970	test: 0.1982984	best: 0.1982853 (452)	total: 7.96s	remaining: 13s
480:	learn: 0.1938031	test: 0.1982687	best: 0.1982685 (479)	total: 8.3s	remaining: 12.7s
500:	learn: 0.1936157	test: 0.1982663	best: 0.1982625 (497)	total: 8.65s	remaining: 12.3s
520:	learn: 0.1934549	test: 0.1982664	best: 0.1982607 (513)	total: 9s	remaining: 12s
540:	learn: 0.1932761	test: 0.1982537	best: 0.1982507 (535)	total: 9.34s	remaining: 11.6s
560:	learn: 0.1930945	test: 0.1982115	best: 0.1982115 (560)	total: 9.69s	remaining: 11.3s
580:	learn: 0.1929233	test: 0.1981952	best: 0.1981952 (580)	total: 10s	remaining: 10.9s
600:	learn: 0.1927539	test: 0.1981733	best: 0.1981657 (598)	total: 10.4s	remaining: 10.6s
620:	learn: 0.1925841	test: 0.1981682	best: 0.1981630 (610)	total: 10.7s	remaining: 10.2s
640:	learn: 0.1924037	test: 0.1981593	best: 0.1981593 (640)	total: 11s	remaining: 9.89s
660:	learn: 0.1922441	test: 0.1981666	best: 0.1981550 (651)	total: 11.4s	remaining: 9.53s
680:	learn: 0.1920823	test: 0.1981675	best: 0.1981546 (666)	total: 11.7s	remaining: 9.19s
700:	learn: 0.1919227	test: 0.1981461	best: 0.1981461 (700)	total: 12.1s	remaining: 8.85s
720:	learn: 0.1917684	test: 0.1981435	best: 0.1981389 (719)	total: 12.4s	remaining: 8.5s
740:	learn: 0.1916106	test: 0.1981207	best: 0.1981181 (739)	total: 12.8s	remaining: 8.16s
760:	learn: 0.1914459	test: 0.1981082	best: 0.1981082 (760)	total: 13.1s	remaining: 7.81s
780:	learn: 0.1912785	test: 0.1980982	best: 0.1980917 (767)	total: 13.4s	remaining: 7.46s
800:	learn: 0.1911453	test: 0.1981050	best: 0.1980876 (785)	total: 13.8s	remaining: 7.12s
820:	learn: 0.1909952	test: 0.1980985	best: 0.1980876 (785)	total: 14.1s	remaining: 6.77s
bestTest = 0.1980876451
bestIteration = 785
Shrink model to first 786 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6201578	test: 0.6204578	best: 0.6204578 (0)	total: 8.92ms	remaining: 8.92ms
1:	learn: 0.5609438	test: 0.5614831	best: 0.5614831 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5614831221
bestIteration = 1
0:	learn: 0.6205977	test: 0.6208953	best: 0.6208953 (0)	total: 16.6ms	remaining: 24s
20:	learn: 0.2314674	test: 0.2334169	best: 0.2334169 (20)	total: 346ms	remaining: 23.5s
40:	learn: 0.2042109	test: 0.2065682	best: 0.2065682 (40)	total: 676ms	remaining: 23.2s
60:	learn: 0.1998576	test: 0.2024997	best: 0.2024997 (60)	total: 1.01s	remaining: 23s
80:	learn: 0.1986647	test: 0.2015373	best: 0.2015373 (80)	total: 1.35s	remaining: 22.8s
100:	learn: 0.1980292	test: 0.2011102	best: 0.2011102 (100)	total: 1.69s	remaining: 22.6s
120:	learn: 0.1976355	test: 0.2008597	best: 0.2008597 (120)	total: 2.03s	remaining: 22.3s
140:	learn: 0.1972877	test: 0.2006836	best: 0.2006823 (139)	total: 2.38s	remaining: 22.1s
160:	learn: 0.1969600	test: 0.2005035	best: 0.2005035 (160)	total: 2.73s	remaining: 21.8s
180:	learn: 0.1967237	test: 0.2004077	best: 0.2004077 (180)	total: 3.07s	remaining: 21.5s
200:	learn: 0.1964664	test: 0.2002735	best: 0.2002735 (200)	total: 3.41s	remaining: 21.2s
220:	learn: 0.1962160	test: 0.2001804	best: 0.2001804 (220)	total: 3.75s	remaining: 20.8s
240:	learn: 0.1959984	test: 0.2001312	best: 0.2001312 (240)	total: 4.1s	remaining: 20.5s
260:	learn: 0.1957464	test: 0.2000538	best: 0.2000538 (260)	total: 4.45s	remaining: 20.3s
280:	learn: 0.1955279	test: 0.2000039	best: 0.2000039 (280)	total: 4.79s	remaining: 19.9s
300:	learn: 0.1952966	test: 0.1999434	best: 0.1999434 (300)	total: 5.13s	remaining: 19.6s
320:	learn: 0.1950812	test: 0.1998788	best: 0.1998788 (320)	total: 5.5s	remaining: 19.3s
340:	learn: 0.1948637	test: 0.1998088	best: 0.1998088 (340)	total: 5.84s	remaining: 19s
360:	learn: 0.1946784	test: 0.1997706	best: 0.1997706 (360)	total: 6.19s	remaining: 18.7s
380:	learn: 0.1945128	test: 0.1997377	best: 0.1997377 (380)	total: 6.54s	remaining: 18.4s
400:	learn: 0.1942958	test: 0.1997057	best: 0.1996992 (397)	total: 6.88s	remaining: 18s
420:	learn: 0.1941137	test: 0.1996723	best: 0.1996723 (420)	total: 7.23s	remaining: 17.7s
440:	learn: 0.1939211	test: 0.1996295	best: 0.1996295 (440)	total: 7.58s	remaining: 17.3s
460:	learn: 0.1937395	test: 0.1996204	best: 0.1996163 (456)	total: 7.92s	remaining: 17s
480:	learn: 0.1935609	test: 0.1995832	best: 0.1995832 (480)	total: 8.26s	remaining: 16.6s
500:	learn: 0.1933856	test: 0.1995263	best: 0.1995263 (500)	total: 8.61s	remaining: 16.3s
520:	learn: 0.1932127	test: 0.1994898	best: 0.1994880 (519)	total: 8.95s	remaining: 16s
540:	learn: 0.1930714	test: 0.1994772	best: 0.1994772 (540)	total: 9.31s	remaining: 15.6s
560:	learn: 0.1929038	test: 0.1994663	best: 0.1994647 (548)	total: 9.65s	remaining: 15.3s
580:	learn: 0.1927352	test: 0.1994621	best: 0.1994621 (580)	total: 9.99s	remaining: 14.9s
600:	learn: 0.1925707	test: 0.1994308	best: 0.1994308 (600)	total: 10.3s	remaining: 14.6s
620:	learn: 0.1924125	test: 0.1994164	best: 0.1994116 (618)	total: 10.7s	remaining: 14.2s
640:	learn: 0.1922535	test: 0.1994063	best: 0.1994063 (640)	total: 11s	remaining: 13.9s
660:	learn: 0.1920865	test: 0.1993764	best: 0.1993764 (660)	total: 11.3s	remaining: 13.5s
680:	learn: 0.1919163	test: 0.1993606	best: 0.1993554 (674)	total: 11.7s	remaining: 13.2s
700:	learn: 0.1917523	test: 0.1993820	best: 0.1993554 (674)	total: 12s	remaining: 12.9s
720:	learn: 0.1916080	test: 0.1993868	best: 0.1993554 (674)	total: 12.4s	remaining: 12.5s
bestTest = 0.1993553735
bestIteration = 674
Shrink model to first 675 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6203855	test: 0.6203159	best: 0.6203159 (0)	total: 8.87ms	remaining: 8.87ms
1:	learn: 0.5606343	test: 0.5605274	best: 0.5605274 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5605273922
bestIteration = 1
0:	learn: 0.6206356	test: 0.6205897	best: 0.6205897 (0)	total: 16.8ms	remaining: 30.5s
20:	learn: 0.2314180	test: 0.2315061	best: 0.2315061 (20)	total: 348ms	remaining: 29.9s
40:	learn: 0.2047796	test: 0.2048391	best: 0.2048391 (40)	total: 681ms	remaining: 29.6s
60:	learn: 0.2004515	test: 0.2004960	best: 0.2004960 (60)	total: 1.01s	remaining: 29.3s
80:	learn: 0.1991152	test: 0.1991704	best: 0.1991704 (80)	total: 1.35s	remaining: 29.1s
100:	learn: 0.1984510	test: 0.1985221	best: 0.1985221 (100)	total: 1.7s	remaining: 28.9s
120:	learn: 0.1981018	test: 0.1983044	best: 0.1983044 (120)	total: 2.03s	remaining: 28.6s
140:	learn: 0.1977256	test: 0.1980651	best: 0.1980651 (140)	total: 2.38s	remaining: 28.4s
160:	learn: 0.1974546	test: 0.1979371	best: 0.1979371 (160)	total: 2.73s	remaining: 28.2s
180:	learn: 0.1971616	test: 0.1978196	best: 0.1978196 (180)	total: 3.08s	remaining: 28s
200:	learn: 0.1968956	test: 0.1976705	best: 0.1976705 (200)	total: 3.42s	remaining: 27.6s
220:	learn: 0.1966656	test: 0.1975849	best: 0.1975835 (219)	total: 3.76s	remaining: 27.3s
240:	learn: 0.1964045	test: 0.1974828	best: 0.1974828 (240)	total: 4.11s	remaining: 27s
260:	learn: 0.1961855	test: 0.1974215	best: 0.1974152 (257)	total: 4.45s	remaining: 26.7s
280:	learn: 0.1959401	test: 0.1973318	best: 0.1973318 (280)	total: 4.79s	remaining: 26.3s
300:	learn: 0.1956851	test: 0.1972673	best: 0.1972673 (300)	total: 5.13s	remaining: 26s
320:	learn: 0.1954502	test: 0.1971759	best: 0.1971759 (320)	total: 5.47s	remaining: 25.6s
340:	learn: 0.1952558	test: 0.1971467	best: 0.1971442 (339)	total: 5.81s	remaining: 25.3s
360:	learn: 0.1950628	test: 0.1971140	best: 0.1971140 (360)	total: 6.17s	remaining: 25s
380:	learn: 0.1948860	test: 0.1970666	best: 0.1970666 (380)	total: 6.53s	remaining: 24.7s
400:	learn: 0.1947043	test: 0.1970129	best: 0.1970120 (399)	total: 6.88s	remaining: 24.4s
420:	learn: 0.1945041	test: 0.1969565	best: 0.1969565 (420)	total: 7.23s	remaining: 24.1s
440:	learn: 0.1943257	test: 0.1969370	best: 0.1969345 (430)	total: 7.59s	remaining: 23.8s
460:	learn: 0.1941625	test: 0.1969158	best: 0.1969141 (459)	total: 7.95s	remaining: 23.5s
480:	learn: 0.1939745	test: 0.1968544	best: 0.1968544 (480)	total: 8.29s	remaining: 23.2s
500:	learn: 0.1938105	test: 0.1968154	best: 0.1968154 (499)	total: 8.64s	remaining: 22.8s
520:	learn: 0.1936424	test: 0.1967985	best: 0.1967953 (511)	total: 9s	remaining: 22.5s
540:	learn: 0.1934387	test: 0.1967700	best: 0.1967700 (540)	total: 9.34s	remaining: 22.1s
560:	learn: 0.1932507	test: 0.1967642	best: 0.1967642 (560)	total: 9.69s	remaining: 21.8s
580:	learn: 0.1930629	test: 0.1967395	best: 0.1967381 (577)	total: 10s	remaining: 21.5s
600:	learn: 0.1928955	test: 0.1967537	best: 0.1967381 (577)	total: 10.4s	remaining: 21.1s
620:	learn: 0.1927290	test: 0.1967216	best: 0.1967216 (620)	total: 10.7s	remaining: 20.8s
640:	learn: 0.1925610	test: 0.1966741	best: 0.1966741 (640)	total: 11.1s	remaining: 20.4s
660:	learn: 0.1923938	test: 0.1966856	best: 0.1966668 (644)	total: 11.4s	remaining: 20.1s
680:	learn: 0.1922235	test: 0.1966641	best: 0.1966623 (678)	total: 11.7s	remaining: 19.7s
700:	learn: 0.1920736	test: 0.1966547	best: 0.1966491 (699)	total: 12.1s	remaining: 19.4s
720:	learn: 0.1919213	test: 0.1966514	best: 0.1966401 (710)	total: 12.4s	remaining: 19s
740:	learn: 0.1917440	test: 0.1966069	best: 0.1966028 (735)	total: 12.8s	remaining: 18.7s
760:	learn: 0.1915816	test: 0.1966045	best: 0.1965911 (752)	total: 13.1s	remaining: 18.4s
780:	learn: 0.1914297	test: 0.1966292	best: 0.1965911 (752)	total: 13.5s	remaining: 18s
800:	learn: 0.1913038	test: 0.1966206	best: 0.1965911 (752)	total: 13.8s	remaining: 17.7s
bestTest = 0.196591127
bestIteration = 752
Shrink model to first 753 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6206249	test: 0.6204316	best: 0.6204316 (0)	total: 9.5ms	remaining: 9.5ms
1:	learn: 0.5605017	test: 0.5601860	best: 0.5601860 (1)	total: 18.3ms	remaining: 0us
bestTest = 0.5601860043
bestIteration = 1
0:	learn: 0.6205062	test: 0.6203550	best: 0.6203550 (0)	total: 16.8ms	remaining: 40.4s
20:	learn: 0.2320252	test: 0.2307122	best: 0.2307122 (20)	total: 348ms	remaining: 39.6s
40:	learn: 0.2048364	test: 0.2032999	best: 0.2032999 (40)	total: 679ms	remaining: 39.3s
60:	learn: 0.2004441	test: 0.1988827	best: 0.1988827 (60)	total: 1.01s	remaining: 39s
80:	learn: 0.1992286	test: 0.1977480	best: 0.1977480 (80)	total: 1.35s	remaining: 38.8s
100:	learn: 0.1986046	test: 0.1972551	best: 0.1972551 (100)	total: 1.7s	remaining: 38.8s
120:	learn: 0.1981963	test: 0.1969996	best: 0.1969996 (120)	total: 2.04s	remaining: 38.7s
140:	learn: 0.1978848	test: 0.1968122	best: 0.1968122 (140)	total: 2.4s	remaining: 38.6s
160:	learn: 0.1975752	test: 0.1966624	best: 0.1966624 (160)	total: 2.74s	remaining: 38.3s
180:	learn: 0.1973105	test: 0.1965397	best: 0.1965397 (180)	total: 3.08s	remaining: 38s
200:	learn: 0.1969987	test: 0.1964291	best: 0.1964291 (200)	total: 3.42s	remaining: 37.7s
220:	learn: 0.1967568	test: 0.1963593	best: 0.1963593 (220)	total: 3.76s	remaining: 37.3s
240:	learn: 0.1965270	test: 0.1962896	best: 0.1962896 (240)	total: 4.12s	remaining: 37.1s
260:	learn: 0.1962918	test: 0.1962028	best: 0.1962028 (260)	total: 4.46s	remaining: 36.7s
280:	learn: 0.1960497	test: 0.1961534	best: 0.1961474 (274)	total: 4.8s	remaining: 36.4s
300:	learn: 0.1958339	test: 0.1960651	best: 0.1960651 (300)	total: 5.14s	remaining: 36.1s
320:	learn: 0.1956446	test: 0.1960230	best: 0.1960229 (319)	total: 5.49s	remaining: 35.8s
340:	learn: 0.1954746	test: 0.1959887	best: 0.1959887 (340)	total: 5.84s	remaining: 35.5s
360:	learn: 0.1952908	test: 0.1959380	best: 0.1959380 (360)	total: 6.18s	remaining: 35.1s
380:	learn: 0.1951344	test: 0.1959297	best: 0.1959272 (376)	total: 6.54s	remaining: 34.9s
400:	learn: 0.1949149	test: 0.1958692	best: 0.1958692 (400)	total: 6.89s	remaining: 34.5s
420:	learn: 0.1947081	test: 0.1958525	best: 0.1958371 (414)	total: 7.23s	remaining: 34.2s
440:	learn: 0.1945427	test: 0.1958423	best: 0.1958371 (414)	total: 7.58s	remaining: 33.9s
460:	learn: 0.1943810	test: 0.1958259	best: 0.1958213 (454)	total: 7.94s	remaining: 33.6s
480:	learn: 0.1941812	test: 0.1957900	best: 0.1957725 (475)	total: 8.28s	remaining: 33.3s
500:	learn: 0.1940031	test: 0.1957451	best: 0.1957451 (500)	total: 8.63s	remaining: 32.9s
520:	learn: 0.1938052	test: 0.1957077	best: 0.1957077 (520)	total: 8.97s	remaining: 32.6s
540:	learn: 0.1936395	test: 0.1957019	best: 0.1956961 (531)	total: 9.32s	remaining: 32.2s
560:	learn: 0.1934731	test: 0.1956841	best: 0.1956841 (560)	total: 9.66s	remaining: 31.9s
580:	learn: 0.1933082	test: 0.1956698	best: 0.1956634 (574)	total: 10s	remaining: 31.5s
600:	learn: 0.1931621	test: 0.1956478	best: 0.1956405 (596)	total: 10.3s	remaining: 31.2s
620:	learn: 0.1929928	test: 0.1956445	best: 0.1956405 (596)	total: 10.7s	remaining: 30.8s
640:	learn: 0.1928470	test: 0.1956463	best: 0.1956334 (630)	total: 11s	remaining: 30.5s
660:	learn: 0.1926688	test: 0.1956307	best: 0.1956292 (659)	total: 11.4s	remaining: 30.1s
680:	learn: 0.1925284	test: 0.1956244	best: 0.1956113 (673)	total: 11.7s	remaining: 29.8s
700:	learn: 0.1923728	test: 0.1956204	best: 0.1956113 (673)	total: 12.1s	remaining: 29.4s
720:	learn: 0.1921761	test: 0.1955827	best: 0.1955827 (720)	total: 12.4s	remaining: 29.1s
740:	learn: 0.1920233	test: 0.1955613	best: 0.1955613 (740)	total: 12.7s	remaining: 28.7s
760:	learn: 0.1918655	test: 0.1955536	best: 0.1955482 (751)	total: 13.1s	remaining: 28.4s
780:	learn: 0.1917227	test: 0.1955455	best: 0.1955357 (774)	total: 13.4s	remaining: 28.1s
800:	learn: 0.1915666	test: 0.1955423	best: 0.1955357 (774)	total: 13.8s	remaining: 27.7s
820:	learn: 0.1914322	test: 0.1955334	best: 0.1955334 (820)	total: 14.1s	remaining: 27.4s
840:	learn: 0.1912889	test: 0.1955196	best: 0.1955177 (826)	total: 14.5s	remaining: 27s
860:	learn: 0.1911295	test: 0.1955026	best: 0.1955026 (860)	total: 14.8s	remaining: 26.7s
880:	learn: 0.1909678	test: 0.1954818	best: 0.1954818 (880)	total: 15.1s	remaining: 26.3s
900:	learn: 0.1907939	test: 0.1954885	best: 0.1954735 (882)	total: 15.5s	remaining: 26s
920:	learn: 0.1906627	test: 0.1955022	best: 0.1954735 (882)	total: 15.8s	remaining: 25.6s
bestTest = 0.1954734851
bestIteration = 882
Shrink model to first 883 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6205721	test: 0.6205959	best: 0.6205959 (0)	total: 8.98ms	remaining: 8.98ms
1:	learn: 0.5570010	test: 0.5571003	best: 0.5571003 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5571003082
bestIteration = 1
0:	learn: 0.6205918	test: 0.6206058	best: 0.6206058 (0)	total: 16.6ms	remaining: 59.1s
20:	learn: 0.2328604	test: 0.2328575	best: 0.2328575 (20)	total: 347ms	remaining: 58.6s
40:	learn: 0.2048907	test: 0.2045923	best: 0.2045923 (40)	total: 691ms	remaining: 59.4s
60:	learn: 0.2004599	test: 0.2001224	best: 0.2001224 (60)	total: 1.02s	remaining: 58.8s
80:	learn: 0.1991525	test: 0.1988816	best: 0.1988816 (80)	total: 1.36s	remaining: 58.8s
100:	learn: 0.1985542	test: 0.1984528	best: 0.1984528 (100)	total: 1.7s	remaining: 58.4s
120:	learn: 0.1980742	test: 0.1981225	best: 0.1981225 (120)	total: 2.04s	remaining: 58.1s
140:	learn: 0.1977369	test: 0.1979593	best: 0.1979593 (140)	total: 2.38s	remaining: 57.9s
160:	learn: 0.1973851	test: 0.1978037	best: 0.1978037 (160)	total: 2.73s	remaining: 57.7s
180:	learn: 0.1971374	test: 0.1977261	best: 0.1977261 (180)	total: 3.08s	remaining: 57.7s
200:	learn: 0.1969089	test: 0.1976629	best: 0.1976629 (200)	total: 3.44s	remaining: 57.6s
220:	learn: 0.1966639	test: 0.1975801	best: 0.1975801 (220)	total: 3.81s	remaining: 57.7s
240:	learn: 0.1964138	test: 0.1975077	best: 0.1975066 (238)	total: 4.16s	remaining: 57.5s
260:	learn: 0.1962107	test: 0.1974479	best: 0.1974479 (260)	total: 4.5s	remaining: 57.1s
280:	learn: 0.1960198	test: 0.1974290	best: 0.1974229 (270)	total: 4.86s	remaining: 56.8s
300:	learn: 0.1957920	test: 0.1973558	best: 0.1973558 (300)	total: 5.2s	remaining: 56.5s
320:	learn: 0.1955842	test: 0.1972911	best: 0.1972911 (320)	total: 5.55s	remaining: 56.1s
340:	learn: 0.1954082	test: 0.1972786	best: 0.1972784 (339)	total: 5.89s	remaining: 55.8s
360:	learn: 0.1951872	test: 0.1972197	best: 0.1972139 (359)	total: 6.23s	remaining: 55.4s
380:	learn: 0.1949927	test: 0.1972037	best: 0.1972025 (379)	total: 6.58s	remaining: 55.1s
400:	learn: 0.1948107	test: 0.1972074	best: 0.1971938 (393)	total: 6.95s	remaining: 54.9s
420:	learn: 0.1946417	test: 0.1971606	best: 0.1971585 (418)	total: 7.3s	remaining: 54.6s
440:	learn: 0.1944393	test: 0.1971529	best: 0.1971448 (424)	total: 7.64s	remaining: 54.2s
460:	learn: 0.1942390	test: 0.1971210	best: 0.1971146 (459)	total: 7.98s	remaining: 53.8s
480:	learn: 0.1940933	test: 0.1971041	best: 0.1971030 (479)	total: 8.34s	remaining: 53.6s
500:	learn: 0.1939227	test: 0.1970708	best: 0.1970708 (500)	total: 8.69s	remaining: 53.2s
520:	learn: 0.1937429	test: 0.1970751	best: 0.1970691 (514)	total: 9.04s	remaining: 52.9s
540:	learn: 0.1935912	test: 0.1970304	best: 0.1970304 (540)	total: 9.38s	remaining: 52.5s
560:	learn: 0.1934140	test: 0.1970242	best: 0.1970184 (550)	total: 9.74s	remaining: 52.2s
580:	learn: 0.1932187	test: 0.1970222	best: 0.1970137 (574)	total: 10.1s	remaining: 51.8s
600:	learn: 0.1930553	test: 0.1970234	best: 0.1970137 (574)	total: 10.4s	remaining: 51.5s
620:	learn: 0.1928863	test: 0.1970215	best: 0.1970137 (574)	total: 10.8s	remaining: 51.1s
640:	learn: 0.1927345	test: 0.1970164	best: 0.1970124 (623)	total: 11.1s	remaining: 50.8s
660:	learn: 0.1925764	test: 0.1969861	best: 0.1969861 (660)	total: 11.5s	remaining: 50.4s
680:	learn: 0.1924083	test: 0.1969713	best: 0.1969713 (680)	total: 11.8s	remaining: 50.1s
700:	learn: 0.1922514	test: 0.1969710	best: 0.1969615 (683)	total: 12.2s	remaining: 49.7s
720:	learn: 0.1921007	test: 0.1969572	best: 0.1969521 (719)	total: 12.5s	remaining: 49.4s
740:	learn: 0.1919446	test: 0.1969355	best: 0.1969348 (739)	total: 12.8s	remaining: 49s
760:	learn: 0.1917851	test: 0.1969236	best: 0.1969236 (760)	total: 13.2s	remaining: 48.7s
780:	learn: 0.1916247	test: 0.1969190	best: 0.1969070 (762)	total: 13.5s	remaining: 48.3s
800:	learn: 0.1914542	test: 0.1969081	best: 0.1968999 (786)	total: 13.9s	remaining: 48s
820:	learn: 0.1913154	test: 0.1969108	best: 0.1968980 (807)	total: 14.2s	remaining: 47.6s
840:	learn: 0.1911614	test: 0.1969078	best: 0.1968980 (807)	total: 14.6s	remaining: 47.3s
bestTest = 0.1968980053
bestIteration = 807
Shrink model to first 808 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6202888	test: 0.6202651	best: 0.6202651 (0)	total: 9.21ms	remaining: 9.21ms
1:	learn: 0.5612935	test: 0.5612647	best: 0.5612647 (1)	total: 18ms	remaining: 0us
bestTest = 0.5612647458
bestIteration = 1
0:	learn: 0.6189827	test: 0.6189609	best: 0.6189609 (0)	total: 16.9ms	remaining: 1m 57s
20:	learn: 0.2316852	test: 0.2318977	best: 0.2318977 (20)	total: 348ms	remaining: 1m 54s
40:	learn: 0.2045978	test: 0.2050325	best: 0.2050325 (40)	total: 690ms	remaining: 1m 55s
60:	learn: 0.2002664	test: 0.2008288	best: 0.2008288 (60)	total: 1.02s	remaining: 1m 55s
80:	learn: 0.1989773	test: 0.1996453	best: 0.1996453 (80)	total: 1.36s	remaining: 1m 55s
100:	learn: 0.1983694	test: 0.1991569	best: 0.1991569 (100)	total: 1.71s	remaining: 1m 55s
120:	learn: 0.1980140	test: 0.1989364	best: 0.1989364 (120)	total: 2.06s	remaining: 1m 55s
140:	learn: 0.1976535	test: 0.1987165	best: 0.1987165 (140)	total: 2.4s	remaining: 1m 55s
160:	learn: 0.1972804	test: 0.1984982	best: 0.1984982 (160)	total: 2.73s	remaining: 1m 54s
180:	learn: 0.1970003	test: 0.1983468	best: 0.1983468 (180)	total: 3.09s	remaining: 1m 55s
200:	learn: 0.1967521	test: 0.1982804	best: 0.1982804 (200)	total: 3.43s	remaining: 1m 54s
220:	learn: 0.1964877	test: 0.1981556	best: 0.1981556 (220)	total: 3.77s	remaining: 1m 54s
240:	learn: 0.1962502	test: 0.1980668	best: 0.1980668 (240)	total: 4.12s	remaining: 1m 54s
260:	learn: 0.1960016	test: 0.1979847	best: 0.1979847 (260)	total: 4.46s	remaining: 1m 54s
280:	learn: 0.1957784	test: 0.1979418	best: 0.1979418 (280)	total: 4.81s	remaining: 1m 53s
300:	learn: 0.1955105	test: 0.1978834	best: 0.1978834 (300)	total: 5.14s	remaining: 1m 53s
320:	learn: 0.1953340	test: 0.1978254	best: 0.1978236 (319)	total: 5.48s	remaining: 1m 52s
340:	learn: 0.1951550	test: 0.1978016	best: 0.1978008 (339)	total: 5.82s	remaining: 1m 52s
360:	learn: 0.1949452	test: 0.1977797	best: 0.1977797 (360)	total: 6.16s	remaining: 1m 52s
380:	learn: 0.1947091	test: 0.1976964	best: 0.1976964 (380)	total: 6.51s	remaining: 1m 51s
400:	learn: 0.1945347	test: 0.1976606	best: 0.1976606 (400)	total: 6.86s	remaining: 1m 51s
420:	learn: 0.1943612	test: 0.1976411	best: 0.1976411 (420)	total: 7.21s	remaining: 1m 51s
440:	learn: 0.1941674	test: 0.1975806	best: 0.1975760 (437)	total: 7.56s	remaining: 1m 51s
460:	learn: 0.1940014	test: 0.1975379	best: 0.1975361 (459)	total: 7.91s	remaining: 1m 51s
480:	learn: 0.1938318	test: 0.1975159	best: 0.1975155 (479)	total: 8.27s	remaining: 1m 50s
500:	learn: 0.1936460	test: 0.1974999	best: 0.1974932 (497)	total: 8.61s	remaining: 1m 50s
520:	learn: 0.1934699	test: 0.1974739	best: 0.1974739 (520)	total: 8.95s	remaining: 1m 50s
540:	learn: 0.1933053	test: 0.1974404	best: 0.1974404 (540)	total: 9.3s	remaining: 1m 49s
560:	learn: 0.1931656	test: 0.1974276	best: 0.1974200 (554)	total: 9.64s	remaining: 1m 49s
580:	learn: 0.1929983	test: 0.1974186	best: 0.1974169 (577)	total: 9.98s	remaining: 1m 49s
600:	learn: 0.1928236	test: 0.1973941	best: 0.1973861 (599)	total: 10.3s	remaining: 1m 48s
620:	learn: 0.1926686	test: 0.1973640	best: 0.1973601 (619)	total: 10.7s	remaining: 1m 48s
640:	learn: 0.1924919	test: 0.1973482	best: 0.1973431 (626)	total: 11s	remaining: 1m 48s
660:	learn: 0.1923240	test: 0.1973330	best: 0.1973330 (660)	total: 11.4s	remaining: 1m 47s
680:	learn: 0.1921494	test: 0.1972982	best: 0.1972982 (680)	total: 11.7s	remaining: 1m 47s
700:	learn: 0.1920150	test: 0.1972743	best: 0.1972715 (693)	total: 12.1s	remaining: 1m 47s
720:	learn: 0.1918653	test: 0.1972676	best: 0.1972663 (718)	total: 12.4s	remaining: 1m 46s
740:	learn: 0.1917112	test: 0.1972631	best: 0.1972548 (727)	total: 12.8s	remaining: 1m 46s
760:	learn: 0.1915572	test: 0.1972414	best: 0.1972414 (760)	total: 13.1s	remaining: 1m 46s
780:	learn: 0.1914179	test: 0.1972440	best: 0.1972414 (760)	total: 13.4s	remaining: 1m 45s
800:	learn: 0.1912827	test: 0.1972166	best: 0.1972152 (799)	total: 13.8s	remaining: 1m 45s
820:	learn: 0.1911395	test: 0.1971997	best: 0.1971997 (820)	total: 14.1s	remaining: 1m 45s
840:	learn: 0.1909816	test: 0.1971585	best: 0.1971585 (840)	total: 14.5s	remaining: 1m 44s
860:	learn: 0.1908198	test: 0.1971667	best: 0.1971585 (840)	total: 14.8s	remaining: 1m 44s
880:	learn: 0.1906899	test: 0.1971599	best: 0.1971577 (872)	total: 15.2s	remaining: 1m 44s
900:	learn: 0.1905503	test: 0.1971272	best: 0.1971272 (900)	total: 15.5s	remaining: 1m 43s
920:	learn: 0.1904050	test: 0.1971171	best: 0.1971171 (920)	total: 15.8s	remaining: 1m 43s
940:	learn: 0.1902692	test: 0.1971215	best: 0.1971141 (930)	total: 16.2s	remaining: 1m 43s
960:	learn: 0.1901296	test: 0.1971051	best: 0.1971046 (958)	total: 16.5s	remaining: 1m 42s
980:	learn: 0.1900026	test: 0.1971076	best: 0.1970998 (971)	total: 16.9s	remaining: 1m 42s
1000:	learn: 0.1898488	test: 0.1971167	best: 0.1970998 (971)	total: 17.2s	remaining: 1m 42s
1020:	learn: 0.1897077	test: 0.1971153	best: 0.1970998 (971)	total: 17.6s	remaining: 1m 41s
bestTest = 0.1970997611
bestIteration = 971
Shrink model to first 972 iterations.

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\CatBoost_BAG_L2\model.pkl
	0.9627	 = Validation score   (roc_auc)
	130.02s	 = Training   runtime
	0.22s	 = Validation runtime
	2715.7	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 3073.46s of the 3073.43s of remaining time.
	Fitting ExtraTreesGini_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L2\utils\model_template.pkl
	Warning: Potentially not enough memory to safely train model. Estimated to require 2.561 GB out of 6.100 GB available memory (41.983%)... (50.000% of avail memory is the max safe size)
	To avoid this warning, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.10 to avoid the warning)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=2.6/6.1 GB
	36.83s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesGini_BAG_L2\model.pkl
	0.9614	 = Validation score   (roc_auc)
	16.27s	 = Training   runtime
	7.11s	 = Validation runtime
	2635.7	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 3049.49s of the 3049.45s of remaining time.
	Fitting ExtraTreesEntr_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L2\utils\model_template.pkl
	Warning: Potentially not enough memory to safely train model. Estimated to require 2.561 GB out of 5.619 GB available memory (45.575%)... (50.000% of avail memory is the max safe size)
	To avoid this warning, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.19 to avoid the warning)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=2.6/5.6 GB
	36.97s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\ExtraTreesEntr_BAG_L2\model.pkl
	0.9617	 = Validation score   (roc_auc)
	19.76s	 = Training   runtime
	8.08s	 = Validation runtime
	2621.8	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: XGBoost_BAG_L2 ... Training model for up to 3020.94s of the 3020.91s of remaining time.
	Fitting XGBoost_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45339
[50]	validation_0-logloss:0.19786
[100]	validation_0-logloss:0.19755
[128]	validation_0-logloss:0.19771

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45412
[50]	validation_0-logloss:0.20226
[100]	validation_0-logloss:0.20189
[143]	validation_0-logloss:0.20192

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45381
[50]	validation_0-logloss:0.20005
[100]	validation_0-logloss:0.19973
[143]	validation_0-logloss:0.19976

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45400
[50]	validation_0-logloss:0.20131
[100]	validation_0-logloss:0.20087
[150]	validation_0-logloss:0.20094
[166]	validation_0-logloss:0.20099

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45382
[50]	validation_0-logloss:0.19856
[100]	validation_0-logloss:0.19797
[150]	validation_0-logloss:0.19792
[200]	validation_0-logloss:0.19809
[205]	validation_0-logloss:0.19810

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45355
[50]	validation_0-logloss:0.19740
[100]	validation_0-logloss:0.19663
[150]	validation_0-logloss:0.19652
[200]	validation_0-logloss:0.19666
[219]	validation_0-logloss:0.19667

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45385
[50]	validation_0-logloss:0.19906
[100]	validation_0-logloss:0.19863
[150]	validation_0-logloss:0.19857
[169]	validation_0-logloss:0.19860

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45378
[50]	validation_0-logloss:0.19899
[100]	validation_0-logloss:0.19832
[150]	validation_0-logloss:0.19843
[163]	validation_0-logloss:0.19846

Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\XGBoost_BAG_L2\model.pkl
	0.9622	 = Validation score   (roc_auc)
	37.96s	 = Training   runtime
	0.71s	 = Validation runtime
	2657.1	 = Inference  throughput (rows/s | 60050 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\trainer.pkl
Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 2981.79s of the 2981.75s of remaining time.
	Fitting NeuralNetTorch_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\NeuralNetTorch_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\ds_sub_fit\sub_fit_ho\models\NeuralNetTorch_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "ExtraTreesGini_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420345 examples, 28 features (25 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=60, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.2202, Val roc_auc: 0.9614, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2039, Val roc_auc: 0.962, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2021, Val roc_auc: 0.9621, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.2011, Val roc_auc: 0.9622, Best Epoch: 4
Epoch 5 (Update 8205).	Train loss: 0.2002, Val roc_auc: 0.9623, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.1997, Val roc_auc: 0.9624, Best Epoch: 6
Epoch 7 (Update 11487).	Train loss: 0.1991, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 8 (Update 13128).	Train loss: 0.1986, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 9 (Update 14769).	Train loss: 0.1982, Val roc_auc: 0.9624, Best Epoch: 6
Epoch 10 (Update 16410).	Train loss: 0.1977, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 11 (Update 18051).	Train loss: 0.1975, Val roc_auc: 0.9622, Best Epoch: 6
Epoch 12 (Update 19692).	Train loss: 0.197, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 13 (Update 21333).	Train loss: 0.1968, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 14 (Update 22974).	Train loss: 0.1963, Val roc_auc: 0.9621, Best Epoch: 6
Epoch 15 (Update 24615).	Train loss: 0.1962, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 16 (Update 26256).	Train loss: 0.1959, Val roc_auc: 0.9621, Best Epoch: 6
Epoch 17 (Update 27897).	Train loss: 0.1951, Val roc_auc: 0.9621, Best Epoch: 6
Epoch 18 (Update 29538).	Train loss: 0.1949, Val roc_auc: 0.9621, Best Epoch: 6
Epoch 19 (Update 31179).	Train loss: 0.1946, Val roc_auc: 0.962, Best Epoch: 6
Epoch 20 (Update 32820).	Train loss: 0.1944, Val roc_auc: 0.962, Best Epoch: 6
Epoch 21 (Update 34461).	Train loss: 0.1941, Val roc_auc: 0.962, Best Epoch: 6
Epoch 22 (Update 36102).	Train loss: 0.1936, Val roc_auc: 0.9619, Best Epoch: 6
Epoch 23 (Update 37743).	Train loss: 0.1934, Val roc_auc: 0.9615, Best Epoch: 6
Epoch 24 (Update 39384).	Train loss: 0.1931, Val roc_auc: 0.9619, Best Epoch: 6
Epoch 25 (Update 41025).	Train loss: 0.1927, Val roc_auc: 0.9617, Best Epoch: 6
Epoch 26 (Update 42666).	Train loss: 0.1926, Val roc_auc: 0.9615, Best Epoch: 6
Epoch 27 (Update 44307).	Train loss: 0.1922, Val roc_auc: 0.9617, Best Epoch: 6
Epoch 28 (Update 45948).	Train loss: 0.192, Val roc_auc: 0.9616, Best Epoch: 6
Best model found on Epoch 6 (Update 9846). Val roc_auc: 0.962419923010646
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "ExtraTreesGini_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420345 examples, 28 features (25 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=60, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.2197, Val roc_auc: 0.9598, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2035, Val roc_auc: 0.9605, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2019, Val roc_auc: 0.9606, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.2008, Val roc_auc: 0.9606, Best Epoch: 3
Epoch 5 (Update 8205).	Train loss: 0.2002, Val roc_auc: 0.9607, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.1995, Val roc_auc: 0.9608, Best Epoch: 6
Epoch 7 (Update 11487).	Train loss: 0.1989, Val roc_auc: 0.9608, Best Epoch: 7
Epoch 8 (Update 13128).	Train loss: 0.1984, Val roc_auc: 0.9608, Best Epoch: 7
Epoch 9 (Update 14769).	Train loss: 0.1979, Val roc_auc: 0.961, Best Epoch: 9
Epoch 10 (Update 16410).	Train loss: 0.1976, Val roc_auc: 0.961, Best Epoch: 10
Epoch 11 (Update 18051).	Train loss: 0.1972, Val roc_auc: 0.9609, Best Epoch: 10
Epoch 12 (Update 19692).	Train loss: 0.1971, Val roc_auc: 0.961, Best Epoch: 12
Epoch 13 (Update 21333).	Train loss: 0.1965, Val roc_auc: 0.961, Best Epoch: 12
Epoch 14 (Update 22974).	Train loss: 0.1963, Val roc_auc: 0.9609, Best Epoch: 12
Epoch 15 (Update 24615).	Train loss: 0.1959, Val roc_auc: 0.9609, Best Epoch: 12
Epoch 16 (Update 26256).	Train loss: 0.1955, Val roc_auc: 0.9608, Best Epoch: 12
Epoch 17 (Update 27897).	Train loss: 0.1951, Val roc_auc: 0.9609, Best Epoch: 12
Epoch 18 (Update 29538).	Train loss: 0.1948, Val roc_auc: 0.9606, Best Epoch: 12
Epoch 19 (Update 31179).	Train loss: 0.1947, Val roc_auc: 0.9607, Best Epoch: 12
Epoch 20 (Update 32820).	Train loss: 0.1943, Val roc_auc: 0.9608, Best Epoch: 12
Epoch 21 (Update 34461).	Train loss: 0.1939, Val roc_auc: 0.9605, Best Epoch: 12
Epoch 22 (Update 36102).	Train loss: 0.1938, Val roc_auc: 0.9606, Best Epoch: 12
Epoch 23 (Update 37743).	Train loss: 0.1934, Val roc_auc: 0.9604, Best Epoch: 12
Epoch 24 (Update 39384).	Train loss: 0.1931, Val roc_auc: 0.9604, Best Epoch: 12
Epoch 25 (Update 41025).	Train loss: 0.1928, Val roc_auc: 0.9605, Best Epoch: 12
Epoch 26 (Update 42666).	Train loss: 0.1926, Val roc_auc: 0.9602, Best Epoch: 12
Epoch 27 (Update 44307).	Train loss: 0.1922, Val roc_auc: 0.9603, Best Epoch: 12
Epoch 28 (Update 45948).	Train loss: 0.192, Val roc_auc: 0.96, Best Epoch: 12
Epoch 29 (Update 47589).	Train loss: 0.1915, Val roc_auc: 0.96, Best Epoch: 12
Epoch 30 (Update 49230).	Train loss: 0.1913, Val roc_auc: 0.9599, Best Epoch: 12
Epoch 31 (Update 50871).	Train loss: 0.1913, Val roc_auc: 0.9601, Best Epoch: 12
Epoch 32 (Update 52512).	Train loss: 0.1906, Val roc_auc: 0.9599, Best Epoch: 12
Epoch 33 (Update 54153).	Train loss: 0.1903, Val roc_auc: 0.9598, Best Epoch: 12
Epoch 34 (Update 55794).	Train loss: 0.1902, Val roc_auc: 0.9597, Best Epoch: 12
Epoch 35 (Update 57435).	Train loss: 0.1901, Val roc_auc: 0.96, Best Epoch: 12
Epoch 36 (Update 59076).	Train loss: 0.1899, Val roc_auc: 0.9599, Best Epoch: 12
Epoch 37 (Update 60717).	Train loss: 0.1895, Val roc_auc: 0.9598, Best Epoch: 12
Epoch 38 (Update 62358).	Train loss: 0.1895, Val roc_auc: 0.9597, Best Epoch: 12
Best model found on Epoch 12 (Update 19692). Val roc_auc: 0.9609880290662555
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "ExtraTreesGini_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420345 examples, 28 features (25 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=60, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.2193, Val roc_auc: 0.9608, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2038, Val roc_auc: 0.9612, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2021, Val roc_auc: 0.9614, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.201, Val roc_auc: 0.9615, Best Epoch: 4
Epoch 5 (Update 8205).	Train loss: 0.2003, Val roc_auc: 0.9617, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.1997, Val roc_auc: 0.9616, Best Epoch: 5
Epoch 7 (Update 11487).	Train loss: 0.1993, Val roc_auc: 0.9617, Best Epoch: 7
Epoch 8 (Update 13128).	Train loss: 0.1986, Val roc_auc: 0.9617, Best Epoch: 8
Epoch 9 (Update 14769).	Train loss: 0.1984, Val roc_auc: 0.9618, Best Epoch: 9
Epoch 10 (Update 16410).	Train loss: 0.1979, Val roc_auc: 0.9618, Best Epoch: 9
Epoch 11 (Update 18051).	Train loss: 0.1975, Val roc_auc: 0.9619, Best Epoch: 11
Epoch 12 (Update 19692).	Train loss: 0.1972, Val roc_auc: 0.9618, Best Epoch: 11
Epoch 13 (Update 21333).	Train loss: 0.1969, Val roc_auc: 0.9618, Best Epoch: 11
Epoch 14 (Update 22974).	Train loss: 0.1966, Val roc_auc: 0.9618, Best Epoch: 11
Epoch 15 (Update 24615).	Train loss: 0.1961, Val roc_auc: 0.9618, Best Epoch: 11
Epoch 16 (Update 26256).	Train loss: 0.1959, Val roc_auc: 0.9619, Best Epoch: 16
Epoch 17 (Update 27897).	Train loss: 0.1955, Val roc_auc: 0.9617, Best Epoch: 16
Epoch 18 (Update 29538).	Train loss: 0.1952, Val roc_auc: 0.9617, Best Epoch: 16
Epoch 19 (Update 31179).	Train loss: 0.1949, Val roc_auc: 0.9617, Best Epoch: 16
Epoch 20 (Update 32820).	Train loss: 0.1946, Val roc_auc: 0.9617, Best Epoch: 16
Epoch 21 (Update 34461).	Train loss: 0.1943, Val roc_auc: 0.9616, Best Epoch: 16
Epoch 22 (Update 36102).	Train loss: 0.1938, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 23 (Update 37743).	Train loss: 0.1935, Val roc_auc: 0.9616, Best Epoch: 16
Epoch 24 (Update 39384).	Train loss: 0.1932, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 25 (Update 41025).	Train loss: 0.193, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 26 (Update 42666).	Train loss: 0.1925, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 27 (Update 44307).	Train loss: 0.1923, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 28 (Update 45948).	Train loss: 0.192, Val roc_auc: 0.961, Best Epoch: 16
Epoch 29 (Update 47589).	Train loss: 0.1918, Val roc_auc: 0.9614, Best Epoch: 16
Epoch 30 (Update 49230).	Train loss: 0.1914, Val roc_auc: 0.9613, Best Epoch: 16
Epoch 31 (Update 50871).	Train loss: 0.1911, Val roc_auc: 0.9609, Best Epoch: 16
Epoch 32 (Update 52512).	Train loss: 0.1909, Val roc_auc: 0.9612, Best Epoch: 16
Epoch 33 (Update 54153).	Train loss: 0.1906, Val roc_auc: 0.961, Best Epoch: 16
Epoch 34 (Update 55794).	Train loss: 0.1903, Val roc_auc: 0.9609, Best Epoch: 16
Epoch 35 (Update 57435).	Train loss: 0.1901, Val roc_auc: 0.9609, Best Epoch: 16
Epoch 36 (Update 59076).	Train loss: 0.1897, Val roc_auc: 0.9606, Best Epoch: 16
Epoch 37 (Update 60717).	Train loss: 0.1894, Val roc_auc: 0.9607, Best Epoch: 16
Epoch 38 (Update 62358).	Train loss: 0.1892, Val roc_auc: 0.9606, Best Epoch: 16
Epoch 39 (Update 63999).	Train loss: 0.1888, Val roc_auc: 0.9602, Best Epoch: 16
Epoch 40 (Update 65640).	Train loss: 0.1886, Val roc_auc: 0.9605, Best Epoch: 16
Epoch 41 (Update 67281).	Train loss: 0.1884, Val roc_auc: 0.9604, Best Epoch: 16
Epoch 42 (Update 68922).	Train loss: 0.1881, Val roc_auc: 0.9604, Best Epoch: 16
Epoch 43 (Update 70563).	Train loss: 0.1879, Val roc_auc: 0.9602, Best Epoch: 16
Epoch 44 (Update 72204).	Train loss: 0.1876, Val roc_auc: 0.9605, Best Epoch: 16
Best model found on Epoch 16 (Update 26256). Val roc_auc: 0.9618780578247209
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "ExtraTreesGini_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 420346 examples, 28 features (25 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=60, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1641).	Train loss: 0.2196, Val roc_auc: 0.9602, Best Epoch: 1
Epoch 2 (Update 3282).	Train loss: 0.2035, Val roc_auc: 0.9607, Best Epoch: 2
Epoch 3 (Update 4923).	Train loss: 0.2021, Val roc_auc: 0.9609, Best Epoch: 3
Epoch 4 (Update 6564).	Train loss: 0.2007, Val roc_auc: 0.9612, Best Epoch: 4
Epoch 5 (Update 8205).	Train loss: 0.2, Val roc_auc: 0.9612, Best Epoch: 5
Epoch 6 (Update 9846).	Train loss: 0.1994, Val roc_auc: 0.9612, Best Epoch: 5
Epoch 7 (Update 11487).	Train loss: 0.1988, Val roc_auc: 0.9613, Best Epoch: 7
Epoch 8 (Update 13128).	Train loss: 0.1984, Val roc_auc: 0.9613, Best Epoch: 7
Epoch 9 (Update 14769).	Train loss: 0.198, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 10 (Update 16410).	Train loss: 0.1976, Val roc_auc: 0.9612, Best Epoch: 9
Epoch 11 (Update 18051).	Train loss: 0.197, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 12 (Update 19692).	Train loss: 0.197, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 13 (Update 21333).	Train loss: 0.1968, Val roc_auc: 0.9613, Best Epoch: 9
Epoch 14 (Update 22974).	Train loss: 0.1961, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 15 (Update 24615).	Train loss: 0.196, Val roc_auc: 0.9612, Best Epoch: 9
Epoch 16 (Update 26256).	Train loss: 0.1956, Val roc_auc: 0.9613, Best Epoch: 9
Epoch 17 (Update 27897).	Train loss: 0.1952, Val roc_auc: 0.961, Best Epoch: 9
Epoch 18 (Update 29538).	Train loss: 0.1949, Val roc_auc: 0.961, Best Epoch: 9
Epoch 19 (Update 31179).	Train loss: 0.1944, Val roc_auc: 0.9611, Best Epoch: 9
Epoch 20 (Update 32820).	Train loss: 0.1943, Val roc_auc: 0.9611, Best Epoch: 9
Epoch 21 (Update 34461).	Train loss: 0.1941, Val roc_auc: 0.9608, Best Epoch: 9
Epoch 22 (Update 36102).	Train loss: 0.1935, Val roc_auc: 0.9611, Best Epoch: 9
Epoch 23 (Update 37743).	Train loss: 0.1934, Val roc_auc: 0.9609, Best Epoch: 9
Epoch 24 (Update 39384).	Train loss: 0.1932, Val roc_auc: 0.961, Best Epoch: 9
Epoch 25 (Update 41025).	Train loss: 0.1928, Val roc_auc: 0.9607, Best Epoch: 9
Epoch 26 (Update 42666).	Train loss: 0.1926, Val roc_auc: 0.9607, Best Epoch: 9
Epoch 27 (Update 44307).	Train loss: 0.1919, Val roc_auc: 0.9608, Best Epoch: 9
Epoch 28 (Update 45948).	Train loss: 0.1918, Val roc_auc: 0.9608, Best Epoch: 9
Epoch 29 (Update 47589).	Train loss: 0.1917, Val roc_auc: 0.9605, Best Epoch: 9
Epoch 30 (Update 49230).	Train loss: 0.1912, Val roc_auc: 0.9602, Best Epoch: 9
Epoch 31 (Update 50871).	Train loss: 0.191, Val roc_auc: 0.9604, Best Epoch: 9
Epoch 32 (Update 52512).	Train loss: 0.1907, Val roc_auc: 0.9603, Best Epoch: 9
Epoch 33 (Update 54153).	Train loss: 0.1904, Val roc_auc: 0.9604, Best Epoch: 9

[50]	valid_set's binary_logloss: 0.283323
[100]	valid_set's binary_logloss: 0.260562
[150]	valid_set's binary_logloss: 0.251288
[200]	valid_set's binary_logloss: 0.246148
[250]	valid_set's binary_logloss: 0.242052
[300]	valid_set's binary_logloss: 0.239459
[350]	valid_set's binary_logloss: 0.237322
[400]	valid_set's binary_logloss: 0.235122
[450]	valid_set's binary_logloss: 0.233585
[500]	valid_set's binary_logloss: 0.23242
[550]	valid_set's binary_logloss: 0.231263
[600]	valid_set's binary_logloss: 0.230295
[650]	valid_set's binary_logloss: 0.229496
[700]	valid_set's binary_logloss: 0.228779
[750]	valid_set's binary_logloss: 0.228188
[800]	valid_set's binary_logloss: 0.227512
[850]	valid_set's binary_logloss: 0.226951
[900]	valid_set's binary_logloss: 0.226497
[950]	valid_set's binary_logloss: 0.226007
[1000]	valid_set's binary_logloss: 0.225526
[1050]	valid_set's binary_logloss: 0.225237
[1100]	valid_set's binary_logloss: 0.224949
[1150]	valid_set's binary_logloss: 0.224708
[1200]	valid_set's binary_logloss: 0.224442
[1250]	valid_set's binary_logloss: 0.224198
[1300]	valid_set's binary_logloss: 0.223938
[1350]	valid_set's binary_logloss: 0.223701
[1400]	valid_set's binary_logloss: 0.223421
[1450]	valid_set's binary_logloss: 0.223351
[1500]	valid_set's binary_logloss: 0.223187
[1550]	valid_set's binary_logloss: 0.223148
[1600]	valid_set's binary_logloss: 0.223044
[1650]	valid_set's binary_logloss: 0.222981
[1700]	valid_set's binary_logloss: 0.222901
[1750]	valid_set's binary_logloss: 0.222815
[1800]	valid_set's binary_logloss: 0.222785
[1850]	valid_set's binary_logloss: 0.222661
[1900]	valid_set's binary_logloss: 0.222664
[1950]	valid_set's binary_logloss: 0.222646
[2000]	valid_set's binary_logloss: 0.222542
[2050]	valid_set's binary_logloss: 0.222531
[2100]	valid_set's binary_logloss: 0.222547
[2150]	valid_set's binary_logloss: 0.222461
[2200]	valid_set's binary_logloss: 0.222434
[2250]	valid_set's binary_logloss: 0.222399
[2300]	valid_set's binary_logloss: 0.222409
[2350]	valid_set's binary_logloss: 0.222407
[2400]	valid_set's binary_logloss: 0.222444
[2450]	valid_set's binary_logloss: 0.222463
[2500]	valid_set's binary_logloss: 0.222488
[2550]	valid_set's binary_logloss: 0.222498
[2600]	valid_set's binary_logloss: 0.222528
[2650]	valid_set's binary_logloss: 0.222603
[2700]	valid_set's binary_logloss: 0.222605
[2750]	valid_set's binary_logloss: 0.222642
[2800]	valid_set's binary_logloss: 0.222658
[2850]	valid_set's binary_logloss: 0.222695
[2900]	valid_set's binary_logloss: 0.222758
[2950]	valid_set's binary_logloss: 0.222782

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284803
[100]	valid_set's binary_logloss: 0.262136
[150]	valid_set's binary_logloss: 0.253508
[200]	valid_set's binary_logloss: 0.248086
[250]	valid_set's binary_logloss: 0.244479
[300]	valid_set's binary_logloss: 0.242022
[350]	valid_set's binary_logloss: 0.239586
[400]	valid_set's binary_logloss: 0.237857
[450]	valid_set's binary_logloss: 0.236703
[500]	valid_set's binary_logloss: 0.235129
[550]	valid_set's binary_logloss: 0.234002
[600]	valid_set's binary_logloss: 0.233101
[650]	valid_set's binary_logloss: 0.232317
[700]	valid_set's binary_logloss: 0.231694
[750]	valid_set's binary_logloss: 0.230995
[800]	valid_set's binary_logloss: 0.230439
[850]	valid_set's binary_logloss: 0.230029
[900]	valid_set's binary_logloss: 0.229363
[950]	valid_set's binary_logloss: 0.228919
[1000]	valid_set's binary_logloss: 0.228542
[1050]	valid_set's binary_logloss: 0.228239
[1100]	valid_set's binary_logloss: 0.227949
[1150]	valid_set's binary_logloss: 0.227751
[1200]	valid_set's binary_logloss: 0.227594
[1250]	valid_set's binary_logloss: 0.227405
[1300]	valid_set's binary_logloss: 0.227194
[1350]	valid_set's binary_logloss: 0.226962
[1400]	valid_set's binary_logloss: 0.226756
[1450]	valid_set's binary_logloss: 0.226594
[1500]	valid_set's binary_logloss: 0.226473
[1550]	valid_set's binary_logloss: 0.226374
[1600]	valid_set's binary_logloss: 0.22627
[1650]	valid_set's binary_logloss: 0.226204
[1700]	valid_set's binary_logloss: 0.226143
[1750]	valid_set's binary_logloss: 0.226087
[1800]	valid_set's binary_logloss: 0.226035
[1850]	valid_set's binary_logloss: 0.22594
[1900]	valid_set's binary_logloss: 0.225805
[1950]	valid_set's binary_logloss: 0.225734
[2000]	valid_set's binary_logloss: 0.225721
[2050]	valid_set's binary_logloss: 0.225762
[2100]	valid_set's binary_logloss: 0.225751
[2150]	valid_set's binary_logloss: 0.225761
[2200]	valid_set's binary_logloss: 0.22572
[2250]	valid_set's binary_logloss: 0.225736
[2300]	valid_set's binary_logloss: 0.225792
[2350]	valid_set's binary_logloss: 0.225769
[2400]	valid_set's binary_logloss: 0.225797
[2450]	valid_set's binary_logloss: 0.225827
[2500]	valid_set's binary_logloss: 0.225781
[2550]	valid_set's binary_logloss: 0.225879
[2600]	valid_set's binary_logloss: 0.226001

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.286646
[100]	valid_set's binary_logloss: 0.264206
[150]	valid_set's binary_logloss: 0.255053
[200]	valid_set's binary_logloss: 0.249854
[250]	valid_set's binary_logloss: 0.245816
[300]	valid_set's binary_logloss: 0.2432
[350]	valid_set's binary_logloss: 0.240892
[400]	valid_set's binary_logloss: 0.239176
[450]	valid_set's binary_logloss: 0.237618
[500]	valid_set's binary_logloss: 0.236514
[550]	valid_set's binary_logloss: 0.23553
[600]	valid_set's binary_logloss: 0.234755
[650]	valid_set's binary_logloss: 0.233867
[700]	valid_set's binary_logloss: 0.233335
[750]	valid_set's binary_logloss: 0.232737
[800]	valid_set's binary_logloss: 0.232188
[850]	valid_set's binary_logloss: 0.231721
[900]	valid_set's binary_logloss: 0.231273
[950]	valid_set's binary_logloss: 0.23096
[1000]	valid_set's binary_logloss: 0.230733
[1050]	valid_set's binary_logloss: 0.230481
[1100]	valid_set's binary_logloss: 0.230113
[1150]	valid_set's binary_logloss: 0.229886
[1200]	valid_set's binary_logloss: 0.229591
[1250]	valid_set's binary_logloss: 0.229463
[1300]	valid_set's binary_logloss: 0.229372
[1350]	valid_set's binary_logloss: 0.229196
[1400]	valid_set's binary_logloss: 0.22909
[1450]	valid_set's binary_logloss: 0.229023
[1500]	valid_set's binary_logloss: 0.228902
[1550]	valid_set's binary_logloss: 0.228845
[1600]	valid_set's binary_logloss: 0.228748
[1650]	valid_set's binary_logloss: 0.228667
[1700]	valid_set's binary_logloss: 0.228641
[1750]	valid_set's binary_logloss: 0.228556
[1800]	valid_set's binary_logloss: 0.228577
[1850]	valid_set's binary_logloss: 0.228559
[1900]	valid_set's binary_logloss: 0.228536
[1950]	valid_set's binary_logloss: 0.228529
[2000]	valid_set's binary_logloss: 0.22853
[2050]	valid_set's binary_logloss: 0.228469
[2100]	valid_set's binary_logloss: 0.228551
[2150]	valid_set's binary_logloss: 0.228541
[2200]	valid_set's binary_logloss: 0.228577
[2250]	valid_set's binary_logloss: 0.228671
[2300]	valid_set's binary_logloss: 0.228777
[2350]	valid_set's binary_logloss: 0.228865
[2400]	valid_set's binary_logloss: 0.228895
[2450]	valid_set's binary_logloss: 0.228942
[2500]	valid_set's binary_logloss: 0.228977
[2550]	valid_set's binary_logloss: 0.228994
[2600]	valid_set's binary_logloss: 0.228913
[2650]	valid_set's binary_logloss: 0.228987

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283466
[100]	valid_set's binary_logloss: 0.260652
[150]	valid_set's binary_logloss: 0.252315
[200]	valid_set's binary_logloss: 0.246913
[250]	valid_set's binary_logloss: 0.242933
[300]	valid_set's binary_logloss: 0.240072
[350]	valid_set's binary_logloss: 0.237855
[400]	valid_set's binary_logloss: 0.23603
[450]	valid_set's binary_logloss: 0.234526
[500]	valid_set's binary_logloss: 0.233257
[550]	valid_set's binary_logloss: 0.232306
[600]	valid_set's binary_logloss: 0.23143
[650]	valid_set's binary_logloss: 0.230578
[700]	valid_set's binary_logloss: 0.229922
[750]	valid_set's binary_logloss: 0.229317
[800]	valid_set's binary_logloss: 0.228764
[850]	valid_set's binary_logloss: 0.228225
[900]	valid_set's binary_logloss: 0.227978
[950]	valid_set's binary_logloss: 0.227591
[1000]	valid_set's binary_logloss: 0.227387
[1050]	valid_set's binary_logloss: 0.22722
[1100]	valid_set's binary_logloss: 0.226896
[1150]	valid_set's binary_logloss: 0.226725
[1200]	valid_set's binary_logloss: 0.226538
[1250]	valid_set's binary_logloss: 0.226325
[1300]	valid_set's binary_logloss: 0.226057
[1350]	valid_set's binary_logloss: 0.225871
[1400]	valid_set's binary_logloss: 0.225601
[1450]	valid_set's binary_logloss: 0.225326
[1500]	valid_set's binary_logloss: 0.225205
[1550]	valid_set's binary_logloss: 0.225236
[1600]	valid_set's binary_logloss: 0.225127
[1650]	valid_set's binary_logloss: 0.225014
[1700]	valid_set's binary_logloss: 0.224915
[1750]	valid_set's binary_logloss: 0.224892
[1800]	valid_set's binary_logloss: 0.224888
[1850]	valid_set's binary_logloss: 0.224888
[1900]	valid_set's binary_logloss: 0.22488
[1950]	valid_set's binary_logloss: 0.224845
[2000]	valid_set's binary_logloss: 0.224863
[2050]	valid_set's binary_logloss: 0.224859
[2100]	valid_set's binary_logloss: 0.224879
[2150]	valid_set's binary_logloss: 0.224937
[2200]	valid_set's binary_logloss: 0.224973
[2250]	valid_set's binary_logloss: 0.22501
[2300]	valid_set's binary_logloss: 0.225087
[2350]	valid_set's binary_logloss: 0.225153
[2400]	valid_set's binary_logloss: 0.225306
[2450]	valid_set's binary_logloss: 0.225393
[2500]	valid_set's binary_logloss: 0.225493
[2550]	valid_set's binary_logloss: 0.225482
[2600]	valid_set's binary_logloss: 0.225566

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283492
[100]	valid_set's binary_logloss: 0.260722
[150]	valid_set's binary_logloss: 0.251227
[200]	valid_set's binary_logloss: 0.245731
[250]	valid_set's binary_logloss: 0.242348
[300]	valid_set's binary_logloss: 0.239814
[350]	valid_set's binary_logloss: 0.237678
[400]	valid_set's binary_logloss: 0.235876
[450]	valid_set's binary_logloss: 0.2343
[500]	valid_set's binary_logloss: 0.2329
[550]	valid_set's binary_logloss: 0.231857
[600]	valid_set's binary_logloss: 0.230921
[650]	valid_set's binary_logloss: 0.230176
[700]	valid_set's binary_logloss: 0.22954
[750]	valid_set's binary_logloss: 0.228839
[800]	valid_set's binary_logloss: 0.228295
[850]	valid_set's binary_logloss: 0.227796
[900]	valid_set's binary_logloss: 0.227343
[950]	valid_set's binary_logloss: 0.226991
[1000]	valid_set's binary_logloss: 0.226633
[1050]	valid_set's binary_logloss: 0.226315
[1100]	valid_set's binary_logloss: 0.225955
[1150]	valid_set's binary_logloss: 0.22569
[1200]	valid_set's binary_logloss: 0.225474
[1250]	valid_set's binary_logloss: 0.225298
[1300]	valid_set's binary_logloss: 0.225188
[1350]	valid_set's binary_logloss: 0.225014
[1400]	valid_set's binary_logloss: 0.224894
[1450]	valid_set's binary_logloss: 0.224584
[1500]	valid_set's binary_logloss: 0.224404
[1550]	valid_set's binary_logloss: 0.224271
[1600]	valid_set's binary_logloss: 0.224234
[1650]	valid_set's binary_logloss: 0.224178
[1700]	valid_set's binary_logloss: 0.224206
[1750]	valid_set's binary_logloss: 0.224013
[1800]	valid_set's binary_logloss: 0.223961
[1850]	valid_set's binary_logloss: 0.22392
[1900]	valid_set's binary_logloss: 0.223807
[1950]	valid_set's binary_logloss: 0.223734
[2000]	valid_set's binary_logloss: 0.223711
[2050]	valid_set's binary_logloss: 0.223547
[2100]	valid_set's binary_logloss: 0.223482
[2150]	valid_set's binary_logloss: 0.223443
[2200]	valid_set's binary_logloss: 0.223459
[2250]	valid_set's binary_logloss: 0.223522
[2300]	valid_set's binary_logloss: 0.223449
[2350]	valid_set's binary_logloss: 0.22343
[2400]	valid_set's binary_logloss: 0.223503
[2450]	valid_set's binary_logloss: 0.223495
[2500]	valid_set's binary_logloss: 0.223521
[2550]	valid_set's binary_logloss: 0.223549
[2600]	valid_set's binary_logloss: 0.223561
[2650]	valid_set's binary_logloss: 0.223603
[2700]	valid_set's binary_logloss: 0.223694
[2750]	valid_set's binary_logloss: 0.223723
[2800]	valid_set's binary_logloss: 0.223814
[2850]	valid_set's binary_logloss: 0.223896
[2900]	valid_set's binary_logloss: 0.223937
[2950]	valid_set's binary_logloss: 0.224048
[3000]	valid_set's binary_logloss: 0.224096
[3050]	valid_set's binary_logloss: 0.224214
[3100]	valid_set's binary_logloss: 0.224221

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283625
[100]	valid_set's binary_logloss: 0.260625
[150]	valid_set's binary_logloss: 0.251262
[200]	valid_set's binary_logloss: 0.245745
[250]	valid_set's binary_logloss: 0.242067
[300]	valid_set's binary_logloss: 0.239564
[350]	valid_set's binary_logloss: 0.237406
[400]	valid_set's binary_logloss: 0.235647
[450]	valid_set's binary_logloss: 0.234142
[500]	valid_set's binary_logloss: 0.232939
[550]	valid_set's binary_logloss: 0.231719
[600]	valid_set's binary_logloss: 0.230749
[650]	valid_set's binary_logloss: 0.230027
[700]	valid_set's binary_logloss: 0.229392
[750]	valid_set's binary_logloss: 0.228832
[800]	valid_set's binary_logloss: 0.228164
[850]	valid_set's binary_logloss: 0.227559
[900]	valid_set's binary_logloss: 0.226879
[950]	valid_set's binary_logloss: 0.226497
[1000]	valid_set's binary_logloss: 0.226115
[1050]	valid_set's binary_logloss: 0.225832
[1100]	valid_set's binary_logloss: 0.22558
[1150]	valid_set's binary_logloss: 0.225319
[1200]	valid_set's binary_logloss: 0.225127
[1250]	valid_set's binary_logloss: 0.224836
[1300]	valid_set's binary_logloss: 0.22468
[1350]	valid_set's binary_logloss: 0.224552
[1400]	valid_set's binary_logloss: 0.224365
[1450]	valid_set's binary_logloss: 0.224319
[1500]	valid_set's binary_logloss: 0.224205
[1550]	valid_set's binary_logloss: 0.224073
[1600]	valid_set's binary_logloss: 0.223997
[1650]	valid_set's binary_logloss: 0.223881
[1700]	valid_set's binary_logloss: 0.223828
[1750]	valid_set's binary_logloss: 0.223712
[1800]	valid_set's binary_logloss: 0.223583
[1850]	valid_set's binary_logloss: 0.223504
[1900]	valid_set's binary_logloss: 0.223416
[1950]	valid_set's binary_logloss: 0.223383
[2000]	valid_set's binary_logloss: 0.223368
[2050]	valid_set's binary_logloss: 0.22335
[2100]	valid_set's binary_logloss: 0.223289
[2150]	valid_set's binary_logloss: 0.223303
[2200]	valid_set's binary_logloss: 0.223276
[2250]	valid_set's binary_logloss: 0.223277
[2300]	valid_set's binary_logloss: 0.223318
[2350]	valid_set's binary_logloss: 0.22332
[2400]	valid_set's binary_logloss: 0.2233
[2450]	valid_set's binary_logloss: 0.223266
[2500]	valid_set's binary_logloss: 0.223334
[2550]	valid_set's binary_logloss: 0.223339
[2600]	valid_set's binary_logloss: 0.223337
[2650]	valid_set's binary_logloss: 0.223483
[2700]	valid_set's binary_logloss: 0.223489
[2750]	valid_set's binary_logloss: 0.223556
[2800]	valid_set's binary_logloss: 0.223695
[2850]	valid_set's binary_logloss: 0.223772
[2900]	valid_set's binary_logloss: 0.223808
[2950]	valid_set's binary_logloss: 0.22386
[3000]	valid_set's binary_logloss: 0.223887

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282846
[100]	valid_set's binary_logloss: 0.260612
[150]	valid_set's binary_logloss: 0.251377
[200]	valid_set's binary_logloss: 0.246252
[250]	valid_set's binary_logloss: 0.242661
[300]	valid_set's binary_logloss: 0.239921
[350]	valid_set's binary_logloss: 0.237628
[400]	valid_set's binary_logloss: 0.235969
[450]	valid_set's binary_logloss: 0.234702
[500]	valid_set's binary_logloss: 0.233419
[550]	valid_set's binary_logloss: 0.232117
[600]	valid_set's binary_logloss: 0.231258
[650]	valid_set's binary_logloss: 0.230531
[700]	valid_set's binary_logloss: 0.229814
[750]	valid_set's binary_logloss: 0.229258
[800]	valid_set's binary_logloss: 0.228817
[850]	valid_set's binary_logloss: 0.228231
[900]	valid_set's binary_logloss: 0.227681
[950]	valid_set's binary_logloss: 0.227419
[1000]	valid_set's binary_logloss: 0.227074
[1050]	valid_set's binary_logloss: 0.226712
[1100]	valid_set's binary_logloss: 0.226455
[1150]	valid_set's binary_logloss: 0.226242
[1200]	valid_set's binary_logloss: 0.226097
[1250]	valid_set's binary_logloss: 0.225987
[1300]	valid_set's binary_logloss: 0.225853
[1350]	valid_set's binary_logloss: 0.225687
[1400]	valid_set's binary_logloss: 0.225689
[1450]	valid_set's binary_logloss: 0.225572
[1500]	valid_set's binary_logloss: 0.225552
[1550]	valid_set's binary_logloss: 0.225519
[1600]	valid_set's binary_logloss: 0.225433
[1650]	valid_set's binary_logloss: 0.225361
[1700]	valid_set's binary_logloss: 0.22537
[1750]	valid_set's binary_logloss: 0.22535
[1800]	valid_set's binary_logloss: 0.2253
[1850]	valid_set's binary_logloss: 0.225257
[1900]	valid_set's binary_logloss: 0.225209
[1950]	valid_set's binary_logloss: 0.225229
[2000]	valid_set's binary_logloss: 0.22534
[2050]	valid_set's binary_logloss: 0.225419
[2100]	valid_set's binary_logloss: 0.22546
[2150]	valid_set's binary_logloss: 0.225482
[2200]	valid_set's binary_logloss: 0.225535
[2250]	valid_set's binary_logloss: 0.225518
[2300]	valid_set's binary_logloss: 0.225564
[2350]	valid_set's binary_logloss: 0.225537
[2400]	valid_set's binary_logloss: 0.225561

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281075
[100]	valid_set's binary_logloss: 0.258067
[150]	valid_set's binary_logloss: 0.248925
[200]	valid_set's binary_logloss: 0.243407
[250]	valid_set's binary_logloss: 0.239914
[300]	valid_set's binary_logloss: 0.23709
[350]	valid_set's binary_logloss: 0.234534
[400]	valid_set's binary_logloss: 0.232763
[450]	valid_set's binary_logloss: 0.231399
[500]	valid_set's binary_logloss: 0.230194
[550]	valid_set's binary_logloss: 0.229321
[600]	valid_set's binary_logloss: 0.228595
[650]	valid_set's binary_logloss: 0.227771
[700]	valid_set's binary_logloss: 0.2271
[750]	valid_set's binary_logloss: 0.226482
[800]	valid_set's binary_logloss: 0.226149
[850]	valid_set's binary_logloss: 0.22564
[900]	valid_set's binary_logloss: 0.22529
[950]	valid_set's binary_logloss: 0.224935
[1000]	valid_set's binary_logloss: 0.224626
[1050]	valid_set's binary_logloss: 0.224368
[1100]	valid_set's binary_logloss: 0.224134
[1150]	valid_set's binary_logloss: 0.223924
[1200]	valid_set's binary_logloss: 0.223703
[1250]	valid_set's binary_logloss: 0.223517
[1300]	valid_set's binary_logloss: 0.223379
[1350]	valid_set's binary_logloss: 0.22314
[1400]	valid_set's binary_logloss: 0.223088
[1450]	valid_set's binary_logloss: 0.22292
[1500]	valid_set's binary_logloss: 0.222556
[1550]	valid_set's binary_logloss: 0.222265
[1600]	valid_set's binary_logloss: 0.222107
[1650]	valid_set's binary_logloss: 0.221959
[1700]	valid_set's binary_logloss: 0.22182
[1750]	valid_set's binary_logloss: 0.221765
[1800]	valid_set's binary_logloss: 0.221765
[1850]	valid_set's binary_logloss: 0.22169
[1900]	valid_set's binary_logloss: 0.221615
[1950]	valid_set's binary_logloss: 0.221572
[2000]	valid_set's binary_logloss: 0.221666
[2050]	valid_set's binary_logloss: 0.22163
[2100]	valid_set's binary_logloss: 0.221589
[2150]	valid_set's binary_logloss: 0.221544
[2200]	valid_set's binary_logloss: 0.221534
[2250]	valid_set's binary_logloss: 0.221538
[2300]	valid_set's binary_logloss: 0.221637
[2350]	valid_set's binary_logloss: 0.221634
[2400]	valid_set's binary_logloss: 0.221659
[2450]	valid_set's binary_logloss: 0.221695
[2500]	valid_set's binary_logloss: 0.221647
[2550]	valid_set's binary_logloss: 0.221661
[2600]	valid_set's binary_logloss: 0.221698
[2650]	valid_set's binary_logloss: 0.22178
[2700]	valid_set's binary_logloss: 0.221833
[2750]	valid_set's binary_logloss: 0.221891

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L1\model.pkl
	0.9516	 = Validation score   (roc_auc)
	106.27s	 = Training   runtime
	5.3s	 = Validation runtime
	12753.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 17574.79s of the 26425.08s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.302354
[100]	valid_set's binary_logloss: 0.275238
[150]	valid_set's binary_logloss: 0.263743
[200]	valid_set's binary_logloss: 0.256204
[250]	valid_set's binary_logloss: 0.251193
[300]	valid_set's binary_logloss: 0.247625
[350]	valid_set's binary_logloss: 0.244643
[400]	valid_set's binary_logloss: 0.241851
[450]	valid_set's binary_logloss: 0.239986
[500]	valid_set's binary_logloss: 0.238076
[550]	valid_set's binary_logloss: 0.236579
[600]	valid_set's binary_logloss: 0.235148
[650]	valid_set's binary_logloss: 0.233981
[700]	valid_set's binary_logloss: 0.232899
[750]	valid_set's binary_logloss: 0.231693
[800]	valid_set's binary_logloss: 0.230699
[850]	valid_set's binary_logloss: 0.229875
[900]	valid_set's binary_logloss: 0.228986
[950]	valid_set's binary_logloss: 0.228226
[1000]	valid_set's binary_logloss: 0.22749
[1050]	valid_set's binary_logloss: 0.226978
[1100]	valid_set's binary_logloss: 0.226562
[1150]	valid_set's binary_logloss: 0.226051
[1200]	valid_set's binary_logloss: 0.225636
[1250]	valid_set's binary_logloss: 0.225145
[1300]	valid_set's binary_logloss: 0.224718
[1350]	valid_set's binary_logloss: 0.224185
[1400]	valid_set's binary_logloss: 0.22384
[1450]	valid_set's binary_logloss: 0.223513
[1500]	valid_set's binary_logloss: 0.223251
[1550]	valid_set's binary_logloss: 0.222909
[1600]	valid_set's binary_logloss: 0.222648
[1650]	valid_set's binary_logloss: 0.222342
[1700]	valid_set's binary_logloss: 0.222118
[1750]	valid_set's binary_logloss: 0.221858
[1800]	valid_set's binary_logloss: 0.221669
[1850]	valid_set's binary_logloss: 0.221455
[1900]	valid_set's binary_logloss: 0.221224
[1950]	valid_set's binary_logloss: 0.221027
[2000]	valid_set's binary_logloss: 0.220774
[2050]	valid_set's binary_logloss: 0.220616
[2100]	valid_set's binary_logloss: 0.220413
[2150]	valid_set's binary_logloss: 0.220248
[2200]	valid_set's binary_logloss: 0.220142
[2250]	valid_set's binary_logloss: 0.220005
[2300]	valid_set's binary_logloss: 0.219844
[2350]	valid_set's binary_logloss: 0.219666
[2400]	valid_set's binary_logloss: 0.219549
[2450]	valid_set's binary_logloss: 0.219447
[2500]	valid_set's binary_logloss: 0.219367
[2550]	valid_set's binary_logloss: 0.21927
[2600]	valid_set's binary_logloss: 0.21917
[2650]	valid_set's binary_logloss: 0.219051
[2700]	valid_set's binary_logloss: 0.218961
[2750]	valid_set's binary_logloss: 0.21883
[2800]	valid_set's binary_logloss: 0.218716
[2850]	valid_set's binary_logloss: 0.218654
[2900]	valid_set's binary_logloss: 0.218597
[2950]	valid_set's binary_logloss: 0.218521
[3000]	valid_set's binary_logloss: 0.218489
[3050]	valid_set's binary_logloss: 0.218401
[3100]	valid_set's binary_logloss: 0.218404
[3150]	valid_set's binary_logloss: 0.218343
[3200]	valid_set's binary_logloss: 0.218302
[3250]	valid_set's binary_logloss: 0.218221
[3300]	valid_set's binary_logloss: 0.218207
[3350]	valid_set's binary_logloss: 0.21818
[3400]	valid_set's binary_logloss: 0.218111
[3450]	valid_set's binary_logloss: 0.218057
[3500]	valid_set's binary_logloss: 0.218029
[3550]	valid_set's binary_logloss: 0.217928
[3600]	valid_set's binary_logloss: 0.217905
[3650]	valid_set's binary_logloss: 0.217873
[3700]	valid_set's binary_logloss: 0.217857
[3750]	valid_set's binary_logloss: 0.217865
[3800]	valid_set's binary_logloss: 0.217831
[3850]	valid_set's binary_logloss: 0.217812
[3900]	valid_set's binary_logloss: 0.217785
[3950]	valid_set's binary_logloss: 0.217766
[4000]	valid_set's binary_logloss: 0.217775
[4050]	valid_set's binary_logloss: 0.217765
[4100]	valid_set's binary_logloss: 0.217791
[4150]	valid_set's binary_logloss: 0.217825
[4200]	valid_set's binary_logloss: 0.217822
[4250]	valid_set's binary_logloss: 0.217791
[4300]	valid_set's binary_logloss: 0.217785
[4350]	valid_set's binary_logloss: 0.21777
[4400]	valid_set's binary_logloss: 0.217785
[4450]	valid_set's binary_logloss: 0.217763
[4500]	valid_set's binary_logloss: 0.217764
[4550]	valid_set's binary_logloss: 0.217763
[4600]	valid_set's binary_logloss: 0.217765
[4650]	valid_set's binary_logloss: 0.217788
[4700]	valid_set's binary_logloss: 0.217814
[4750]	valid_set's binary_logloss: 0.217819
[4800]	valid_set's binary_logloss: 0.217803
[4850]	valid_set's binary_logloss: 0.21779
[4900]	valid_set's binary_logloss: 0.217832
[4950]	valid_set's binary_logloss: 0.217869
[5000]	valid_set's binary_logloss: 0.217894
[5050]	valid_set's binary_logloss: 0.217908
[5100]	valid_set's binary_logloss: 0.217904
[5150]	valid_set's binary_logloss: 0.217911
[5200]	valid_set's binary_logloss: 0.217895
[5250]	valid_set's binary_logloss: 0.217866
[5300]	valid_set's binary_logloss: 0.217843
[5350]	valid_set's binary_logloss: 0.217841
[5400]	valid_set's binary_logloss: 0.217863
[5450]	valid_set's binary_logloss: 0.217886
[5500]	valid_set's binary_logloss: 0.217879
[5550]	valid_set's binary_logloss: 0.217931
[5600]	valid_set's binary_logloss: 0.218
[5650]	valid_set's binary_logloss: 0.218041
[5700]	valid_set's binary_logloss: 0.218057
[5750]	valid_set's binary_logloss: 0.218105
[5800]	valid_set's binary_logloss: 0.218147
[5850]	valid_set's binary_logloss: 0.218163

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.304575
[100]	valid_set's binary_logloss: 0.277638
[150]	valid_set's binary_logloss: 0.26536
[200]	valid_set's binary_logloss: 0.258268
[250]	valid_set's binary_logloss: 0.25331
[300]	valid_set's binary_logloss: 0.24984
[350]	valid_set's binary_logloss: 0.246778
[400]	valid_set's binary_logloss: 0.244222
[450]	valid_set's binary_logloss: 0.242003
[500]	valid_set's binary_logloss: 0.240098
[550]	valid_set's binary_logloss: 0.238601
[600]	valid_set's binary_logloss: 0.237136
[650]	valid_set's binary_logloss: 0.235831
[700]	valid_set's binary_logloss: 0.234779
[750]	valid_set's binary_logloss: 0.233817
[800]	valid_set's binary_logloss: 0.23283
[850]	valid_set's binary_logloss: 0.23193
[900]	valid_set's binary_logloss: 0.231241
[950]	valid_set's binary_logloss: 0.230382
[1000]	valid_set's binary_logloss: 0.22973
[1050]	valid_set's binary_logloss: 0.22918
[1100]	valid_set's binary_logloss: 0.22868
[1150]	valid_set's binary_logloss: 0.228182
[1200]	valid_set's binary_logloss: 0.227792
[1250]	valid_set's binary_logloss: 0.227385
[1300]	valid_set's binary_logloss: 0.227054
[1350]	valid_set's binary_logloss: 0.226717
[1400]	valid_set's binary_logloss: 0.226386
[1450]	valid_set's binary_logloss: 0.226052
[1500]	valid_set's binary_logloss: 0.225766
[1550]	valid_set's binary_logloss: 0.225488
[1600]	valid_set's binary_logloss: 0.225231
[1650]	valid_set's binary_logloss: 0.225009
[1700]	valid_set's binary_logloss: 0.224614
[1750]	valid_set's binary_logloss: 0.224369
[1800]	valid_set's binary_logloss: 0.224175
[1850]	valid_set's binary_logloss: 0.224002
[1900]	valid_set's binary_logloss: 0.223792
[1950]	valid_set's binary_logloss: 0.223564
[2000]	valid_set's binary_logloss: 0.223352
[2050]	valid_set's binary_logloss: 0.223241
[2100]	valid_set's binary_logloss: 0.223026
[2150]	valid_set's binary_logloss: 0.222794
[2200]	valid_set's binary_logloss: 0.222666
[2250]	valid_set's binary_logloss: 0.222519
[2300]	valid_set's binary_logloss: 0.222405
[2350]	valid_set's binary_logloss: 0.222276
[2400]	valid_set's binary_logloss: 0.222106
[2450]	valid_set's binary_logloss: 0.221987
[2500]	valid_set's binary_logloss: 0.221803
[2550]	valid_set's binary_logloss: 0.221672
[2600]	valid_set's binary_logloss: 0.221609
[2650]	valid_set's binary_logloss: 0.221547
[2700]	valid_set's binary_logloss: 0.221454
[2750]	valid_set's binary_logloss: 0.221406
[2800]	valid_set's binary_logloss: 0.221309
[2850]	valid_set's binary_logloss: 0.221222
[2900]	valid_set's binary_logloss: 0.221163
[2950]	valid_set's binary_logloss: 0.221096
[3000]	valid_set's binary_logloss: 0.220951
[3050]	valid_set's binary_logloss: 0.220817
[3100]	valid_set's binary_logloss: 0.220807
[3150]	valid_set's binary_logloss: 0.220784
[3200]	valid_set's binary_logloss: 0.220722
[3250]	valid_set's binary_logloss: 0.220685
[3300]	valid_set's binary_logloss: 0.22066
[3350]	valid_set's binary_logloss: 0.220652
[3400]	valid_set's binary_logloss: 0.220605
[3450]	valid_set's binary_logloss: 0.220518
[3500]	valid_set's binary_logloss: 0.220489
[3550]	valid_set's binary_logloss: 0.220443
[3600]	valid_set's binary_logloss: 0.220385
[3650]	valid_set's binary_logloss: 0.220328
[3700]	valid_set's binary_logloss: 0.220325
[3750]	valid_set's binary_logloss: 0.22029
[3800]	valid_set's binary_logloss: 0.220255
[3850]	valid_set's binary_logloss: 0.220209
[3900]	valid_set's binary_logloss: 0.22019
[3950]	valid_set's binary_logloss: 0.220153
[4000]	valid_set's binary_logloss: 0.220164
[4050]	valid_set's binary_logloss: 0.220102
[4100]	valid_set's binary_logloss: 0.22012
[4150]	valid_set's binary_logloss: 0.220134
[4200]	valid_set's binary_logloss: 0.220105
[4250]	valid_set's binary_logloss: 0.220129
[4300]	valid_set's binary_logloss: 0.220101
[4350]	valid_set's binary_logloss: 0.220067
[4400]	valid_set's binary_logloss: 0.220065
[4450]	valid_set's binary_logloss: 0.220037
[4500]	valid_set's binary_logloss: 0.220056
[4550]	valid_set's binary_logloss: 0.220014
[4600]	valid_set's binary_logloss: 0.21996
[4650]	valid_set's binary_logloss: 0.219986
[4700]	valid_set's binary_logloss: 0.220009
[4750]	valid_set's binary_logloss: 0.220017
[4800]	valid_set's binary_logloss: 0.219946
[4850]	valid_set's binary_logloss: 0.219922
[4900]	valid_set's binary_logloss: 0.219921
[4950]	valid_set's binary_logloss: 0.219988
[5000]	valid_set's binary_logloss: 0.22002
[5050]	valid_set's binary_logloss: 0.220047
[5100]	valid_set's binary_logloss: 0.220051
[5150]	valid_set's binary_logloss: 0.220083
[5200]	valid_set's binary_logloss: 0.220147
[5250]	valid_set's binary_logloss: 0.220196
[5300]	valid_set's binary_logloss: 0.220272
[5350]	valid_set's binary_logloss: 0.220298
[5400]	valid_set's binary_logloss: 0.220291
[5450]	valid_set's binary_logloss: 0.220297
[5500]	valid_set's binary_logloss: 0.22031
[5550]	valid_set's binary_logloss: 0.220339
[5600]	valid_set's binary_logloss: 0.220371
[5650]	valid_set's binary_logloss: 0.220409
[5700]	valid_set's binary_logloss: 0.22042
[5750]	valid_set's binary_logloss: 0.220444
[5800]	valid_set's binary_logloss: 0.22047
[5850]	valid_set's binary_logloss: 0.220487
[5900]	valid_set's binary_logloss: 0.22052
[5950]	valid_set's binary_logloss: 0.220535
[6000]	valid_set's binary_logloss: 0.220587
[6050]	valid_set's binary_logloss: 0.220627
[6100]	valid_set's binary_logloss: 0.220668
[6150]	valid_set's binary_logloss: 0.220701
[6200]	valid_set's binary_logloss: 0.220713
[6250]	valid_set's binary_logloss: 0.220715
[6300]	valid_set's binary_logloss: 0.220715
[6350]	valid_set's binary_logloss: 0.220778

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303685
[100]	valid_set's binary_logloss: 0.276644
[150]	valid_set's binary_logloss: 0.265384
[200]	valid_set's binary_logloss: 0.258499
[250]	valid_set's binary_logloss: 0.253654
[300]	valid_set's binary_logloss: 0.250225
[350]	valid_set's binary_logloss: 0.247333
[400]	valid_set's binary_logloss: 0.244989
[450]	valid_set's binary_logloss: 0.243103
[500]	valid_set's binary_logloss: 0.241425
[550]	valid_set's binary_logloss: 0.239782
[600]	valid_set's binary_logloss: 0.238472
[650]	valid_set's binary_logloss: 0.237224
[700]	valid_set's binary_logloss: 0.236148
[750]	valid_set's binary_logloss: 0.235155
[800]	valid_set's binary_logloss: 0.234235
[850]	valid_set's binary_logloss: 0.233491
[900]	valid_set's binary_logloss: 0.232716
[950]	valid_set's binary_logloss: 0.23197
[1000]	valid_set's binary_logloss: 0.231437
[1050]	valid_set's binary_logloss: 0.23088
[1100]	valid_set's binary_logloss: 0.230426
[1150]	valid_set's binary_logloss: 0.229936
[1200]	valid_set's binary_logloss: 0.229526
[1250]	valid_set's binary_logloss: 0.22917
[1300]	valid_set's binary_logloss: 0.228771
[1350]	valid_set's binary_logloss: 0.228415
[1400]	valid_set's binary_logloss: 0.228126
[1450]	valid_set's binary_logloss: 0.227814
[1500]	valid_set's binary_logloss: 0.22749
[1550]	valid_set's binary_logloss: 0.227196
[1600]	valid_set's binary_logloss: 0.227002
[1650]	valid_set's binary_logloss: 0.226826
[1700]	valid_set's binary_logloss: 0.226652
[1750]	valid_set's binary_logloss: 0.226436
[1800]	valid_set's binary_logloss: 0.226215
[1850]	valid_set's binary_logloss: 0.226068
[1900]	valid_set's binary_logloss: 0.225902
[1950]	valid_set's binary_logloss: 0.225754
[2000]	valid_set's binary_logloss: 0.225531
[2050]	valid_set's binary_logloss: 0.225366
[2100]	valid_set's binary_logloss: 0.225301
[2150]	valid_set's binary_logloss: 0.22512
[2200]	valid_set's binary_logloss: 0.224981
[2250]	valid_set's binary_logloss: 0.224902
[2300]	valid_set's binary_logloss: 0.224818
[2350]	valid_set's binary_logloss: 0.22469
[2400]	valid_set's binary_logloss: 0.224603
[2450]	valid_set's binary_logloss: 0.224542
[2500]	valid_set's binary_logloss: 0.224472
[2550]	valid_set's binary_logloss: 0.224402
[2600]	valid_set's binary_logloss: 0.224314
[2650]	valid_set's binary_logloss: 0.224279
[2700]	valid_set's binary_logloss: 0.224125
[2750]	valid_set's binary_logloss: 0.224027
[2800]	valid_set's binary_logloss: 0.224017
[2850]	valid_set's binary_logloss: 0.223919
[2900]	valid_set's binary_logloss: 0.223881
[2950]	valid_set's binary_logloss: 0.223844
[3000]	valid_set's binary_logloss: 0.223801
[3050]	valid_set's binary_logloss: 0.223739
[3100]	valid_set's binary_logloss: 0.22372
[3150]	valid_set's binary_logloss: 0.223641
[3200]	valid_set's binary_logloss: 0.223608
[3250]	valid_set's binary_logloss: 0.223616
[3300]	valid_set's binary_logloss: 0.223594
[3350]	valid_set's binary_logloss: 0.223541
[3400]	valid_set's binary_logloss: 0.223528
[3450]	valid_set's binary_logloss: 0.22346
[3500]	valid_set's binary_logloss: 0.223445
[3550]	valid_set's binary_logloss: 0.223416
[3600]	valid_set's binary_logloss: 0.223371
[3650]	valid_set's binary_logloss: 0.223319
[3700]	valid_set's binary_logloss: 0.223361
[3750]	valid_set's binary_logloss: 0.223404
[3800]	valid_set's binary_logloss: 0.223423
[3850]	valid_set's binary_logloss: 0.223422
[3900]	valid_set's binary_logloss: 0.223456
[3950]	valid_set's binary_logloss: 0.223492
[4000]	valid_set's binary_logloss: 0.223419
[4050]	valid_set's binary_logloss: 0.223438
[4100]	valid_set's binary_logloss: 0.223433
[4150]	valid_set's binary_logloss: 0.223394
[4200]	valid_set's binary_logloss: 0.223408
[4250]	valid_set's binary_logloss: 0.22338
[4300]	valid_set's binary_logloss: 0.223377
[4350]	valid_set's binary_logloss: 0.223357
[4400]	valid_set's binary_logloss: 0.223363
[4450]	valid_set's binary_logloss: 0.223352
[4500]	valid_set's binary_logloss: 0.223348
[4550]	valid_set's binary_logloss: 0.223359
[4600]	valid_set's binary_logloss: 0.223376
[4650]	valid_set's binary_logloss: 0.223397
[4700]	valid_set's binary_logloss: 0.223424
[4750]	valid_set's binary_logloss: 0.223442

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.3024
[100]	valid_set's binary_logloss: 0.274499
[150]	valid_set's binary_logloss: 0.263286
[200]	valid_set's binary_logloss: 0.256527
[250]	valid_set's binary_logloss: 0.251505
[300]	valid_set's binary_logloss: 0.247978
[350]	valid_set's binary_logloss: 0.244971
[400]	valid_set's binary_logloss: 0.242423
[450]	valid_set's binary_logloss: 0.240418
[500]	valid_set's binary_logloss: 0.23837
[550]	valid_set's binary_logloss: 0.236924
[600]	valid_set's binary_logloss: 0.23556
[650]	valid_set's binary_logloss: 0.234505
[700]	valid_set's binary_logloss: 0.233394
[750]	valid_set's binary_logloss: 0.232478
[800]	valid_set's binary_logloss: 0.231483
[850]	valid_set's binary_logloss: 0.230657
[900]	valid_set's binary_logloss: 0.229918
[950]	valid_set's binary_logloss: 0.229233
[1000]	valid_set's binary_logloss: 0.228562
[1050]	valid_set's binary_logloss: 0.22791
[1100]	valid_set's binary_logloss: 0.227383
[1150]	valid_set's binary_logloss: 0.226838
[1200]	valid_set's binary_logloss: 0.226405
[1250]	valid_set's binary_logloss: 0.226003
[1300]	valid_set's binary_logloss: 0.225605
[1350]	valid_set's binary_logloss: 0.225262
[1400]	valid_set's binary_logloss: 0.224869
[1450]	valid_set's binary_logloss: 0.224526
[1500]	valid_set's binary_logloss: 0.224259
[1550]	valid_set's binary_logloss: 0.223992
[1600]	valid_set's binary_logloss: 0.223667
[1650]	valid_set's binary_logloss: 0.223374
[1700]	valid_set's binary_logloss: 0.223134
[1750]	valid_set's binary_logloss: 0.22292
[1800]	valid_set's binary_logloss: 0.222694
[1850]	valid_set's binary_logloss: 0.222507
[1900]	valid_set's binary_logloss: 0.222337
[1950]	valid_set's binary_logloss: 0.222204
[2000]	valid_set's binary_logloss: 0.222072
[2050]	valid_set's binary_logloss: 0.221895
[2100]	valid_set's binary_logloss: 0.221738
[2150]	valid_set's binary_logloss: 0.221621
[2200]	valid_set's binary_logloss: 0.221496
[2250]	valid_set's binary_logloss: 0.221352
[2300]	valid_set's binary_logloss: 0.221234
[2350]	valid_set's binary_logloss: 0.221147
[2400]	valid_set's binary_logloss: 0.221093
[2450]	valid_set's binary_logloss: 0.220964
[2500]	valid_set's binary_logloss: 0.220808
[2550]	valid_set's binary_logloss: 0.220694
[2600]	valid_set's binary_logloss: 0.220597
[2650]	valid_set's binary_logloss: 0.220486
[2700]	valid_set's binary_logloss: 0.220429
[2750]	valid_set's binary_logloss: 0.220412
[2800]	valid_set's binary_logloss: 0.22039
[2850]	valid_set's binary_logloss: 0.220349
[2900]	valid_set's binary_logloss: 0.220235
[2950]	valid_set's binary_logloss: 0.220179
[3000]	valid_set's binary_logloss: 0.220112
[3050]	valid_set's binary_logloss: 0.220046
[3100]	valid_set's binary_logloss: 0.219995
[3150]	valid_set's binary_logloss: 0.219944
[3200]	valid_set's binary_logloss: 0.219859
[3250]	valid_set's binary_logloss: 0.219857
[3300]	valid_set's binary_logloss: 0.219792
[3350]	valid_set's binary_logloss: 0.219751
[3400]	valid_set's binary_logloss: 0.219683
[3450]	valid_set's binary_logloss: 0.21961
[3500]	valid_set's binary_logloss: 0.219624
[3550]	valid_set's binary_logloss: 0.21963
[3600]	valid_set's binary_logloss: 0.219641
[3650]	valid_set's binary_logloss: 0.21956
[3700]	valid_set's binary_logloss: 0.219525
[3750]	valid_set's binary_logloss: 0.219498
[3800]	valid_set's binary_logloss: 0.219503
[3850]	valid_set's binary_logloss: 0.219481
[3900]	valid_set's binary_logloss: 0.219462
[3950]	valid_set's binary_logloss: 0.219512
[4000]	valid_set's binary_logloss: 0.219537
[4050]	valid_set's binary_logloss: 0.219496
[4100]	valid_set's binary_logloss: 0.219484
[4150]	valid_set's binary_logloss: 0.219453
[4200]	valid_set's binary_logloss: 0.219521
[4250]	valid_set's binary_logloss: 0.219521
[4300]	valid_set's binary_logloss: 0.219518
[4350]	valid_set's binary_logloss: 0.219564
[4400]	valid_set's binary_logloss: 0.219559
[4450]	valid_set's binary_logloss: 0.219592
[4500]	valid_set's binary_logloss: 0.219535
[4550]	valid_set's binary_logloss: 0.219566
[4600]	valid_set's binary_logloss: 0.219553
[4650]	valid_set's binary_logloss: 0.219551
[4700]	valid_set's binary_logloss: 0.219538
[4750]	valid_set's binary_logloss: 0.219548
[4800]	valid_set's binary_logloss: 0.219628
[4850]	valid_set's binary_logloss: 0.219606
[4900]	valid_set's binary_logloss: 0.219598
[4950]	valid_set's binary_logloss: 0.219653
[5000]	valid_set's binary_logloss: 0.219729
[5050]	valid_set's binary_logloss: 0.219731
[5100]	valid_set's binary_logloss: 0.219746
[5150]	valid_set's binary_logloss: 0.219752
[5200]	valid_set's binary_logloss: 0.219771
[5250]	valid_set's binary_logloss: 0.219825
[5300]	valid_set's binary_logloss: 0.219891
[5350]	valid_set's binary_logloss: 0.219922
[5400]	valid_set's binary_logloss: 0.219954

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.30544
[100]	valid_set's binary_logloss: 0.276341
[150]	valid_set's binary_logloss: 0.263759
[200]	valid_set's binary_logloss: 0.256607
[250]	valid_set's binary_logloss: 0.25213
[300]	valid_set's binary_logloss: 0.248363
[350]	valid_set's binary_logloss: 0.245224
[400]	valid_set's binary_logloss: 0.242741
[450]	valid_set's binary_logloss: 0.240497
[500]	valid_set's binary_logloss: 0.238408
[550]	valid_set's binary_logloss: 0.236752
[600]	valid_set's binary_logloss: 0.235402
[650]	valid_set's binary_logloss: 0.234153
[700]	valid_set's binary_logloss: 0.233074
[750]	valid_set's binary_logloss: 0.232053
[800]	valid_set's binary_logloss: 0.231037
[850]	valid_set's binary_logloss: 0.230294
[900]	valid_set's binary_logloss: 0.229485
[950]	valid_set's binary_logloss: 0.228765
[1000]	valid_set's binary_logloss: 0.228181
[1050]	valid_set's binary_logloss: 0.227539
[1100]	valid_set's binary_logloss: 0.22706
[1150]	valid_set's binary_logloss: 0.226466
[1200]	valid_set's binary_logloss: 0.226017
[1250]	valid_set's binary_logloss: 0.225492
[1300]	valid_set's binary_logloss: 0.225087
[1350]	valid_set's binary_logloss: 0.224674
[1400]	valid_set's binary_logloss: 0.224346
[1450]	valid_set's binary_logloss: 0.224001
[1500]	valid_set's binary_logloss: 0.22367
[1550]	valid_set's binary_logloss: 0.223382
[1600]	valid_set's binary_logloss: 0.223021
[1650]	valid_set's binary_logloss: 0.222752
[1700]	valid_set's binary_logloss: 0.222518
[1750]	valid_set's binary_logloss: 0.222353
[1800]	valid_set's binary_logloss: 0.222109
[1850]	valid_set's binary_logloss: 0.22183
[1900]	valid_set's binary_logloss: 0.221621
[1950]	valid_set's binary_logloss: 0.221334
[2000]	valid_set's binary_logloss: 0.221165
[2050]	valid_set's binary_logloss: 0.220997
[2100]	valid_set's binary_logloss: 0.22085
[2150]	valid_set's binary_logloss: 0.220677
[2200]	valid_set's binary_logloss: 0.220545
[2250]	valid_set's binary_logloss: 0.220438
[2300]	valid_set's binary_logloss: 0.220279
[2350]	valid_set's binary_logloss: 0.220166
[2400]	valid_set's binary_logloss: 0.220065
[2450]	valid_set's binary_logloss: 0.21993
[2500]	valid_set's binary_logloss: 0.219818
[2550]	valid_set's binary_logloss: 0.21965
[2600]	valid_set's binary_logloss: 0.219573
[2650]	valid_set's binary_logloss: 0.219436
[2700]	valid_set's binary_logloss: 0.219308
[2750]	valid_set's binary_logloss: 0.219217
[2800]	valid_set's binary_logloss: 0.219123
[2850]	valid_set's binary_logloss: 0.2191
[2900]	valid_set's binary_logloss: 0.21905
[2950]	valid_set's binary_logloss: 0.218979
[3000]	valid_set's binary_logloss: 0.218902
[3050]	valid_set's binary_logloss: 0.21885
[3100]	valid_set's binary_logloss: 0.218811
[3150]	valid_set's binary_logloss: 0.218759
[3200]	valid_set's binary_logloss: 0.218659
[3250]	valid_set's binary_logloss: 0.218606
[3300]	valid_set's binary_logloss: 0.218503
[3350]	valid_set's binary_logloss: 0.218447
[3400]	valid_set's binary_logloss: 0.218443
[3450]	valid_set's binary_logloss: 0.218355
[3500]	valid_set's binary_logloss: 0.218337
[3550]	valid_set's binary_logloss: 0.218286
[3600]	valid_set's binary_logloss: 0.218252
[3650]	valid_set's binary_logloss: 0.218227
[3700]	valid_set's binary_logloss: 0.218225
[3750]	valid_set's binary_logloss: 0.218199
[3800]	valid_set's binary_logloss: 0.218159
[3850]	valid_set's binary_logloss: 0.21814
[3900]	valid_set's binary_logloss: 0.21814
[3950]	valid_set's binary_logloss: 0.218091
[4000]	valid_set's binary_logloss: 0.218091
[4050]	valid_set's binary_logloss: 0.218097
[4100]	valid_set's binary_logloss: 0.218082
[4150]	valid_set's binary_logloss: 0.218015
[4200]	valid_set's binary_logloss: 0.217983
[4250]	valid_set's binary_logloss: 0.217943
[4300]	valid_set's binary_logloss: 0.21794
[4350]	valid_set's binary_logloss: 0.217945
[4400]	valid_set's binary_logloss: 0.217944
[4450]	valid_set's binary_logloss: 0.21793
[4500]	valid_set's binary_logloss: 0.21796
[4550]	valid_set's binary_logloss: 0.217974
[4600]	valid_set's binary_logloss: 0.218005
[4650]	valid_set's binary_logloss: 0.218028
[4700]	valid_set's binary_logloss: 0.218046
[4750]	valid_set's binary_logloss: 0.218064
[4800]	valid_set's binary_logloss: 0.218129
[4850]	valid_set's binary_logloss: 0.218139
[4900]	valid_set's binary_logloss: 0.218147
[4950]	valid_set's binary_logloss: 0.218131
[5000]	valid_set's binary_logloss: 0.218187
[5050]	valid_set's binary_logloss: 0.218204
[5100]	valid_set's binary_logloss: 0.218169
[5150]	valid_set's binary_logloss: 0.218206
[5200]	valid_set's binary_logloss: 0.218237
[5250]	valid_set's binary_logloss: 0.218262
[5300]	valid_set's binary_logloss: 0.218303
[5350]	valid_set's binary_logloss: 0.218312
[5400]	valid_set's binary_logloss: 0.218323
[5450]	valid_set's binary_logloss: 0.218313
[5500]	valid_set's binary_logloss: 0.218324
[5550]	valid_set's binary_logloss: 0.218378
[5600]	valid_set's binary_logloss: 0.218392
[5650]	valid_set's binary_logloss: 0.218419
[5700]	valid_set's binary_logloss: 0.2184
[5750]	valid_set's binary_logloss: 0.21843

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303134
[100]	valid_set's binary_logloss: 0.274969
[150]	valid_set's binary_logloss: 0.263184
[200]	valid_set's binary_logloss: 0.256201
[250]	valid_set's binary_logloss: 0.251205
[300]	valid_set's binary_logloss: 0.24732
[350]	valid_set's binary_logloss: 0.244513
[400]	valid_set's binary_logloss: 0.2421
[450]	valid_set's binary_logloss: 0.239852
[500]	valid_set's binary_logloss: 0.237991
[550]	valid_set's binary_logloss: 0.236401
[600]	valid_set's binary_logloss: 0.235005
[650]	valid_set's binary_logloss: 0.233679
[700]	valid_set's binary_logloss: 0.23261
[750]	valid_set's binary_logloss: 0.231474
[800]	valid_set's binary_logloss: 0.230635
[850]	valid_set's binary_logloss: 0.229855
[900]	valid_set's binary_logloss: 0.22917
[950]	valid_set's binary_logloss: 0.228424
[1000]	valid_set's binary_logloss: 0.227781
[1050]	valid_set's binary_logloss: 0.227271
[1100]	valid_set's binary_logloss: 0.226665
[1150]	valid_set's binary_logloss: 0.226123
[1200]	valid_set's binary_logloss: 0.22567
[1250]	valid_set's binary_logloss: 0.225246
[1300]	valid_set's binary_logloss: 0.224857
[1350]	valid_set's binary_logloss: 0.224524
[1400]	valid_set's binary_logloss: 0.224096
[1450]	valid_set's binary_logloss: 0.223749
[1500]	valid_set's binary_logloss: 0.223423
[1550]	valid_set's binary_logloss: 0.223141
[1600]	valid_set's binary_logloss: 0.222796
[1650]	valid_set's binary_logloss: 0.222536
[1700]	valid_set's binary_logloss: 0.222264
[1750]	valid_set's binary_logloss: 0.222036
[1800]	valid_set's binary_logloss: 0.22178
[1850]	valid_set's binary_logloss: 0.221548
[1900]	valid_set's binary_logloss: 0.22138
[1950]	valid_set's binary_logloss: 0.221166
[2000]	valid_set's binary_logloss: 0.220971
[2050]	valid_set's binary_logloss: 0.220786
[2100]	valid_set's binary_logloss: 0.220589
[2150]	valid_set's binary_logloss: 0.220428
[2200]	valid_set's binary_logloss: 0.220337
[2250]	valid_set's binary_logloss: 0.22024
[2300]	valid_set's binary_logloss: 0.220089
[2350]	valid_set's binary_logloss: 0.219942
[2400]	valid_set's binary_logloss: 0.219901
[2450]	valid_set's binary_logloss: 0.219801
[2500]	valid_set's binary_logloss: 0.219694
[2550]	valid_set's binary_logloss: 0.219549
[2600]	valid_set's binary_logloss: 0.219468
[2650]	valid_set's binary_logloss: 0.219393
[2700]	valid_set's binary_logloss: 0.219259
[2750]	valid_set's binary_logloss: 0.219166
[2800]	valid_set's binary_logloss: 0.21912
[2850]	valid_set's binary_logloss: 0.218967
[2900]	valid_set's binary_logloss: 0.218824
[2950]	valid_set's binary_logloss: 0.218737
[3000]	valid_set's binary_logloss: 0.21869
[3050]	valid_set's binary_logloss: 0.218585
[3100]	valid_set's binary_logloss: 0.218494
[3150]	valid_set's binary_logloss: 0.218464
[3200]	valid_set's binary_logloss: 0.218407
[3250]	valid_set's binary_logloss: 0.218347
[3300]	valid_set's binary_logloss: 0.218309
[3350]	valid_set's binary_logloss: 0.218273
[3400]	valid_set's binary_logloss: 0.218185
[3450]	valid_set's binary_logloss: 0.218158
[3500]	valid_set's binary_logloss: 0.218068
[3550]	valid_set's binary_logloss: 0.218057
[3600]	valid_set's binary_logloss: 0.218007
[3650]	valid_set's binary_logloss: 0.218008
[3700]	valid_set's binary_logloss: 0.218057
[3750]	valid_set's binary_logloss: 0.218034
[3800]	valid_set's binary_logloss: 0.218038
[3850]	valid_set's binary_logloss: 0.217941
[3900]	valid_set's binary_logloss: 0.217952
[3950]	valid_set's binary_logloss: 0.217922
[4000]	valid_set's binary_logloss: 0.217938
[4050]	valid_set's binary_logloss: 0.217956
[4100]	valid_set's binary_logloss: 0.21787
[4150]	valid_set's binary_logloss: 0.217866
[4200]	valid_set's binary_logloss: 0.21786
[4250]	valid_set's binary_logloss: 0.217865
[4300]	valid_set's binary_logloss: 0.21785
[4350]	valid_set's binary_logloss: 0.217824
[4400]	valid_set's binary_logloss: 0.217816
[4450]	valid_set's binary_logloss: 0.217847
[4500]	valid_set's binary_logloss: 0.217876
[4550]	valid_set's binary_logloss: 0.217919
[4600]	valid_set's binary_logloss: 0.21792
[4650]	valid_set's binary_logloss: 0.217847
[4700]	valid_set's binary_logloss: 0.217878
[4750]	valid_set's binary_logloss: 0.217866
[4800]	valid_set's binary_logloss: 0.217845
[4850]	valid_set's binary_logloss: 0.217908
[4900]	valid_set's binary_logloss: 0.217909
[4950]	valid_set's binary_logloss: 0.217933
[5000]	valid_set's binary_logloss: 0.217958
[5050]	valid_set's binary_logloss: 0.217957
[5100]	valid_set's binary_logloss: 0.217969
[5150]	valid_set's binary_logloss: 0.218005
[5200]	valid_set's binary_logloss: 0.218014
[5250]	valid_set's binary_logloss: 0.218024
[5300]	valid_set's binary_logloss: 0.218008
[5350]	valid_set's binary_logloss: 0.218012
[5400]	valid_set's binary_logloss: 0.218027
[5450]	valid_set's binary_logloss: 0.217999
[5500]	valid_set's binary_logloss: 0.218026
[5550]	valid_set's binary_logloss: 0.218038
[5600]	valid_set's binary_logloss: 0.218049
[5650]	valid_set's binary_logloss: 0.21809
[5700]	valid_set's binary_logloss: 0.218113

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.300069
[100]	valid_set's binary_logloss: 0.273062
[150]	valid_set's binary_logloss: 0.262181
[200]	valid_set's binary_logloss: 0.25541
[250]	valid_set's binary_logloss: 0.250769
[300]	valid_set's binary_logloss: 0.246969
[350]	valid_set's binary_logloss: 0.243991
[400]	valid_set's binary_logloss: 0.241585
[450]	valid_set's binary_logloss: 0.239587
[500]	valid_set's binary_logloss: 0.237968
[550]	valid_set's binary_logloss: 0.236505
[600]	valid_set's binary_logloss: 0.235021
[650]	valid_set's binary_logloss: 0.233786
[700]	valid_set's binary_logloss: 0.232609
[750]	valid_set's binary_logloss: 0.231597
[800]	valid_set's binary_logloss: 0.230613
[850]	valid_set's binary_logloss: 0.229914
[900]	valid_set's binary_logloss: 0.229302
[950]	valid_set's binary_logloss: 0.228612
[1000]	valid_set's binary_logloss: 0.228019
[1050]	valid_set's binary_logloss: 0.22756
[1100]	valid_set's binary_logloss: 0.22713
[1150]	valid_set's binary_logloss: 0.226654
[1200]	valid_set's binary_logloss: 0.226209
[1250]	valid_set's binary_logloss: 0.225766
[1300]	valid_set's binary_logloss: 0.225308
[1350]	valid_set's binary_logloss: 0.224933
[1400]	valid_set's binary_logloss: 0.224586
[1450]	valid_set's binary_logloss: 0.224359
[1500]	valid_set's binary_logloss: 0.224088
[1550]	valid_set's binary_logloss: 0.223758
[1600]	valid_set's binary_logloss: 0.223448
[1650]	valid_set's binary_logloss: 0.223201
[1700]	valid_set's binary_logloss: 0.222933
[1750]	valid_set's binary_logloss: 0.222726
[1800]	valid_set's binary_logloss: 0.222576
[1850]	valid_set's binary_logloss: 0.222373
[1900]	valid_set's binary_logloss: 0.222193
[1950]	valid_set's binary_logloss: 0.222003
[2000]	valid_set's binary_logloss: 0.221876
[2050]	valid_set's binary_logloss: 0.221694
[2100]	valid_set's binary_logloss: 0.221565
[2150]	valid_set's binary_logloss: 0.221447
[2200]	valid_set's binary_logloss: 0.221321
[2250]	valid_set's binary_logloss: 0.221124
[2300]	valid_set's binary_logloss: 0.221008
[2350]	valid_set's binary_logloss: 0.220901
[2400]	valid_set's binary_logloss: 0.220791
[2450]	valid_set's binary_logloss: 0.220744
[2500]	valid_set's binary_logloss: 0.220698
[2550]	valid_set's binary_logloss: 0.22063
[2600]	valid_set's binary_logloss: 0.220533
[2650]	valid_set's binary_logloss: 0.220429
[2700]	valid_set's binary_logloss: 0.220408
[2750]	valid_set's binary_logloss: 0.22039
[2800]	valid_set's binary_logloss: 0.220338
[2850]	valid_set's binary_logloss: 0.22031
[2900]	valid_set's binary_logloss: 0.220242
[2950]	valid_set's binary_logloss: 0.220162
[3000]	valid_set's binary_logloss: 0.220143
[3050]	valid_set's binary_logloss: 0.220183
[3100]	valid_set's binary_logloss: 0.220094
[3150]	valid_set's binary_logloss: 0.220039
[3200]	valid_set's binary_logloss: 0.219979
[3250]	valid_set's binary_logloss: 0.219957
[3300]	valid_set's binary_logloss: 0.219946
[3350]	valid_set's binary_logloss: 0.219878
[3400]	valid_set's binary_logloss: 0.219833
[3450]	valid_set's binary_logloss: 0.219835
[3500]	valid_set's binary_logloss: 0.219799
[3550]	valid_set's binary_logloss: 0.219806
[3600]	valid_set's binary_logloss: 0.219768
[3650]	valid_set's binary_logloss: 0.219738
[3700]	valid_set's binary_logloss: 0.219725
[3750]	valid_set's binary_logloss: 0.219692
[3800]	valid_set's binary_logloss: 0.219693
[3850]	valid_set's binary_logloss: 0.219685
[3900]	valid_set's binary_logloss: 0.219724
[3950]	valid_set's binary_logloss: 0.219727
[4000]	valid_set's binary_logloss: 0.219739
[4050]	valid_set's binary_logloss: 0.219763
[4100]	valid_set's binary_logloss: 0.2198
[4150]	valid_set's binary_logloss: 0.21978
[4200]	valid_set's binary_logloss: 0.219791
[4250]	valid_set's binary_logloss: 0.219756
[4300]	valid_set's binary_logloss: 0.219773
[4350]	valid_set's binary_logloss: 0.219793
[4400]	valid_set's binary_logloss: 0.219821
[4450]	valid_set's binary_logloss: 0.219791
[4500]	valid_set's binary_logloss: 0.219815
[4550]	valid_set's binary_logloss: 0.219853
[4600]	valid_set's binary_logloss: 0.219911
[4650]	valid_set's binary_logloss: 0.219979
[4700]	valid_set's binary_logloss: 0.220005
[4750]	valid_set's binary_logloss: 0.22002
[4800]	valid_set's binary_logloss: 0.220044
[4850]	valid_set's binary_logloss: 0.220067
[4900]	valid_set's binary_logloss: 0.220071

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.301585
[100]	valid_set's binary_logloss: 0.273424
[150]	valid_set's binary_logloss: 0.260696
[200]	valid_set's binary_logloss: 0.253834
[250]	valid_set's binary_logloss: 0.249273
[300]	valid_set's binary_logloss: 0.24514
[350]	valid_set's binary_logloss: 0.242179
[400]	valid_set's binary_logloss: 0.239529
[450]	valid_set's binary_logloss: 0.237508
[500]	valid_set's binary_logloss: 0.235519
[550]	valid_set's binary_logloss: 0.233945
[600]	valid_set's binary_logloss: 0.232647
[650]	valid_set's binary_logloss: 0.231417
[700]	valid_set's binary_logloss: 0.230371
[750]	valid_set's binary_logloss: 0.229454
[800]	valid_set's binary_logloss: 0.228685
[850]	valid_set's binary_logloss: 0.227896
[900]	valid_set's binary_logloss: 0.227228
[950]	valid_set's binary_logloss: 0.226567
[1000]	valid_set's binary_logloss: 0.225926
[1050]	valid_set's binary_logloss: 0.225292
[1100]	valid_set's binary_logloss: 0.22482
[1150]	valid_set's binary_logloss: 0.224429
[1200]	valid_set's binary_logloss: 0.223974
[1250]	valid_set's binary_logloss: 0.22359
[1300]	valid_set's binary_logloss: 0.223208
[1350]	valid_set's binary_logloss: 0.222828
[1400]	valid_set's binary_logloss: 0.222419
[1450]	valid_set's binary_logloss: 0.222126
[1500]	valid_set's binary_logloss: 0.221833
[1550]	valid_set's binary_logloss: 0.221562
[1600]	valid_set's binary_logloss: 0.221226
[1650]	valid_set's binary_logloss: 0.22096
[1700]	valid_set's binary_logloss: 0.220712
[1750]	valid_set's binary_logloss: 0.220546
[1800]	valid_set's binary_logloss: 0.220311
[1850]	valid_set's binary_logloss: 0.220145
[1900]	valid_set's binary_logloss: 0.219975
[1950]	valid_set's binary_logloss: 0.219753
[2000]	valid_set's binary_logloss: 0.219638
[2050]	valid_set's binary_logloss: 0.219392
[2100]	valid_set's binary_logloss: 0.219236
[2150]	valid_set's binary_logloss: 0.219159
[2200]	valid_set's binary_logloss: 0.219024
[2250]	valid_set's binary_logloss: 0.218922
[2300]	valid_set's binary_logloss: 0.218777
[2350]	valid_set's binary_logloss: 0.218636
[2400]	valid_set's binary_logloss: 0.218492
[2450]	valid_set's binary_logloss: 0.218378
[2500]	valid_set's binary_logloss: 0.218357
[2550]	valid_set's binary_logloss: 0.218216
[2600]	valid_set's binary_logloss: 0.218135
[2650]	valid_set's binary_logloss: 0.218033
[2700]	valid_set's binary_logloss: 0.217873
[2750]	valid_set's binary_logloss: 0.217785
[2800]	valid_set's binary_logloss: 0.217727
[2850]	valid_set's binary_logloss: 0.217706
[2900]	valid_set's binary_logloss: 0.217634
[2950]	valid_set's binary_logloss: 0.217538
[3000]	valid_set's binary_logloss: 0.21749
[3050]	valid_set's binary_logloss: 0.217437
[3100]	valid_set's binary_logloss: 0.217403
[3150]	valid_set's binary_logloss: 0.217323
[3200]	valid_set's binary_logloss: 0.217253
[3250]	valid_set's binary_logloss: 0.217143
[3300]	valid_set's binary_logloss: 0.217171
[3350]	valid_set's binary_logloss: 0.21707
[3400]	valid_set's binary_logloss: 0.217114
[3450]	valid_set's binary_logloss: 0.217113
[3500]	valid_set's binary_logloss: 0.217095
[3550]	valid_set's binary_logloss: 0.21707
[3600]	valid_set's binary_logloss: 0.217064
[3650]	valid_set's binary_logloss: 0.217031
[3700]	valid_set's binary_logloss: 0.217069
[3750]	valid_set's binary_logloss: 0.217098
[3800]	valid_set's binary_logloss: 0.217068
[3850]	valid_set's binary_logloss: 0.217072
[3900]	valid_set's binary_logloss: 0.217067
[3950]	valid_set's binary_logloss: 0.217086
[4000]	valid_set's binary_logloss: 0.217064
[4050]	valid_set's binary_logloss: 0.216969
[4100]	valid_set's binary_logloss: 0.216911
[4150]	valid_set's binary_logloss: 0.216902
[4200]	valid_set's binary_logloss: 0.216912
[4250]	valid_set's binary_logloss: 0.216927
[4300]	valid_set's binary_logloss: 0.216896
[4350]	valid_set's binary_logloss: 0.216971
[4400]	valid_set's binary_logloss: 0.216979
[4450]	valid_set's binary_logloss: 0.21698
[4500]	valid_set's binary_logloss: 0.216987
[4550]	valid_set's binary_logloss: 0.217006
[4600]	valid_set's binary_logloss: 0.217046
[4650]	valid_set's binary_logloss: 0.217022
[4700]	valid_set's binary_logloss: 0.217041
[4750]	valid_set's binary_logloss: 0.217043
[4800]	valid_set's binary_logloss: 0.21706
[4850]	valid_set's binary_logloss: 0.217043
[4900]	valid_set's binary_logloss: 0.217029
[4950]	valid_set's binary_logloss: 0.217055
[5000]	valid_set's binary_logloss: 0.217107
[5050]	valid_set's binary_logloss: 0.217111
[5100]	valid_set's binary_logloss: 0.217105
[5150]	valid_set's binary_logloss: 0.217148
[5200]	valid_set's binary_logloss: 0.217115
[5250]	valid_set's binary_logloss: 0.217152
[5300]	valid_set's binary_logloss: 0.217182
[5350]	valid_set's binary_logloss: 0.217209
[5400]	valid_set's binary_logloss: 0.217257

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L1\model.pkl
	0.9539	 = Validation score   (roc_auc)
	202.52s	 = Training   runtime
	13.12s	 = Validation runtime
	5149.0	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 17357.81s of the 26208.10s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403876	test: 0.6404671	best: 0.6404671 (0)	total: 9.32ms	remaining: 9.32ms
1:	learn: 0.5954066	test: 0.5955208	best: 0.5955208 (1)	total: 18.6ms	remaining: 0us
bestTest = 0.595520811
bestIteration = 1
0:	learn: 0.6414593	test: 0.6415237	best: 0.6415237 (0)	total: 17.2ms	remaining: 1m 7s
20:	learn: 0.3366332	test: 0.3368724	best: 0.3368724 (20)	total: 405ms	remaining: 1m 15s
40:	learn: 0.3033545	test: 0.3036541	best: 0.3036541 (40)	total: 799ms	remaining: 1m 15s
60:	learn: 0.2900201	test: 0.2902175	best: 0.2902175 (60)	total: 1.2s	remaining: 1m 15s
80:	learn: 0.2812589	test: 0.2809010	best: 0.2809010 (80)	total: 1.58s	remaining: 1m 14s
100:	learn: 0.2749282	test: 0.2741804	best: 0.2741804 (100)	total: 1.96s	remaining: 1m 13s
120:	learn: 0.2704434	test: 0.2695925	best: 0.2695925 (120)	total: 2.35s	remaining: 1m 13s
140:	learn: 0.2664359	test: 0.2654167	best: 0.2654167 (140)	total: 2.73s	remaining: 1m 12s
160:	learn: 0.2628198	test: 0.2617223	best: 0.2617223 (160)	total: 3.09s	remaining: 1m 11s
180:	learn: 0.2595944	test: 0.2584425	best: 0.2584425 (180)	total: 3.45s	remaining: 1m 11s
200:	learn: 0.2566878	test: 0.2555058	best: 0.2555058 (200)	total: 3.83s	remaining: 1m 10s
220:	learn: 0.2542192	test: 0.2529819	best: 0.2529819 (220)	total: 4.2s	remaining: 1m 10s
240:	learn: 0.2521520	test: 0.2508657	best: 0.2508657 (240)	total: 4.58s	remaining: 1m 9s
260:	learn: 0.2504544	test: 0.2490916	best: 0.2490916 (260)	total: 4.96s	remaining: 1m 9s
280:	learn: 0.2488322	test: 0.2475688	best: 0.2475688 (280)	total: 5.32s	remaining: 1m 8s
300:	learn: 0.2473725	test: 0.2461016	best: 0.2461016 (300)	total: 5.68s	remaining: 1m 8s
320:	learn: 0.2458676	test: 0.2446080	best: 0.2446080 (320)	total: 6.05s	remaining: 1m 7s
340:	learn: 0.2443809	test: 0.2430416	best: 0.2430416 (340)	total: 6.41s	remaining: 1m 7s
360:	learn: 0.2429911	test: 0.2416827	best: 0.2416827 (360)	total: 6.78s	remaining: 1m 6s
380:	learn: 0.2420067	test: 0.2407682	best: 0.2407682 (380)	total: 7.15s	remaining: 1m 6s
400:	learn: 0.2407389	test: 0.2395276	best: 0.2395276 (400)	total: 7.53s	remaining: 1m 5s
420:	learn: 0.2394707	test: 0.2382764	best: 0.2382764 (420)	total: 7.9s	remaining: 1m 5s
440:	learn: 0.2384185	test: 0.2373285	best: 0.2373285 (440)	total: 8.27s	remaining: 1m 5s
460:	learn: 0.2374258	test: 0.2363910	best: 0.2363910 (460)	total: 8.64s	remaining: 1m 4s
480:	learn: 0.2364841	test: 0.2355401	best: 0.2355401 (480)	total: 9.01s	remaining: 1m 4s
500:	learn: 0.2356372	test: 0.2347829	best: 0.2347829 (500)	total: 9.36s	remaining: 1m 3s
520:	learn: 0.2347407	test: 0.2339885	best: 0.2339885 (520)	total: 9.73s	remaining: 1m 3s
540:	learn: 0.2339589	test: 0.2333220	best: 0.2333220 (540)	total: 10.1s	remaining: 1m 3s
560:	learn: 0.2332403	test: 0.2327298	best: 0.2327298 (560)	total: 10.5s	remaining: 1m 2s
580:	learn: 0.2324653	test: 0.2319239	best: 0.2319239 (580)	total: 10.8s	remaining: 1m 2s
600:	learn: 0.2318135	test: 0.2313785	best: 0.2313785 (600)	total: 11.2s	remaining: 1m 1s
620:	learn: 0.2310667	test: 0.2307542	best: 0.2307542 (620)	total: 11.6s	remaining: 1m 1s
640:	learn: 0.2303064	test: 0.2300703	best: 0.2300703 (640)	total: 11.9s	remaining: 1m
660:	learn: 0.2296191	test: 0.2294491	best: 0.2294491 (660)	total: 12.3s	remaining: 1m
680:	learn: 0.2290046	test: 0.2289232	best: 0.2289232 (680)	total: 12.7s	remaining: 1m
700:	learn: 0.2284749	test: 0.2284906	best: 0.2284906 (700)	total: 13s	remaining: 59.7s
720:	learn: 0.2279006	test: 0.2280197	best: 0.2280197 (720)	total: 13.4s	remaining: 59.2s
740:	learn: 0.2273725	test: 0.2275860	best: 0.2275860 (740)	total: 13.7s	remaining: 58.8s
760:	learn: 0.2267446	test: 0.2270465	best: 0.2270465 (760)	total: 14.1s	remaining: 58.4s
780:	learn: 0.2262746	test: 0.2266383	best: 0.2266383 (780)	total: 14.5s	remaining: 58s
800:	learn: 0.2258150	test: 0.2262823	best: 0.2262823 (800)	total: 14.8s	remaining: 57.5s
820:	learn: 0.2252795	test: 0.2258177	best: 0.2258177 (820)	total: 15.2s	remaining: 57.1s
840:	learn: 0.2247160	test: 0.2253744	best: 0.2253744 (840)	total: 15.5s	remaining: 56.7s
860:	learn: 0.2242410	test: 0.2249868	best: 0.2249868 (860)	total: 15.9s	remaining: 56.4s
880:	learn: 0.2237950	test: 0.2246366	best: 0.2246366 (880)	total: 16.3s	remaining: 55.9s
900:	learn: 0.2233770	test: 0.2243365	best: 0.2243365 (900)	total: 16.6s	remaining: 55.5s
920:	learn: 0.2229197	test: 0.2239502	best: 0.2239502 (920)	total: 17s	remaining: 55.1s
940:	learn: 0.2224944	test: 0.2236413	best: 0.2236413 (940)	total: 17.3s	remaining: 54.7s
960:	learn: 0.2221284	test: 0.2233617	best: 0.2233617 (960)	total: 17.7s	remaining: 54.3s
980:	learn: 0.2217570	test: 0.2230856	best: 0.2230856 (980)	total: 18s	remaining: 53.9s
1000:	learn: 0.2214255	test: 0.2228580	best: 0.2228580 (1000)	total: 18.4s	remaining: 53.6s
1020:	learn: 0.2210253	test: 0.2225725	best: 0.2225725 (1020)	total: 18.8s	remaining: 53.2s
1040:	learn: 0.2206867	test: 0.2223148	best: 0.2223148 (1040)	total: 19.2s	remaining: 52.9s
1060:	learn: 0.2203775	test: 0.2221082	best: 0.2221082 (1060)	total: 19.5s	remaining: 52.4s
1080:	learn: 0.2200676	test: 0.2218864	best: 0.2218864 (1080)	total: 19.9s	remaining: 52.1s
1100:	learn: 0.2197315	test: 0.2216262	best: 0.2216262 (1100)	total: 20.3s	remaining: 51.7s
1120:	learn: 0.2194179	test: 0.2214001	best: 0.2214001 (1120)	total: 20.6s	remaining: 51.3s
1140:	learn: 0.2190328	test: 0.2211339	best: 0.2211339 (1140)	total: 21s	remaining: 51s
1160:	learn: 0.2187289	test: 0.2209387	best: 0.2209387 (1160)	total: 21.3s	remaining: 50.5s
1180:	learn: 0.2184019	test: 0.2207349	best: 0.2207349 (1180)	total: 21.7s	remaining: 50.2s
1200:	learn: 0.2180457	test: 0.2204613	best: 0.2204613 (1200)	total: 22s	remaining: 49.8s
1220:	learn: 0.2177587	test: 0.2202707	best: 0.2202707 (1220)	total: 22.4s	remaining: 49.4s
1240:	learn: 0.2174917	test: 0.2200943	best: 0.2200943 (1240)	total: 22.8s	remaining: 49s
1260:	learn: 0.2171395	test: 0.2198064	best: 0.2198064 (1260)	total: 23.1s	remaining: 48.6s
1280:	learn: 0.2168294	test: 0.2195459	best: 0.2195459 (1280)	total: 23.5s	remaining: 48.2s
1300:	learn: 0.2165768	test: 0.2193969	best: 0.2193969 (1300)	total: 23.8s	remaining: 47.8s
1320:	learn: 0.2162990	test: 0.2192394	best: 0.2192394 (1320)	total: 24.2s	remaining: 47.5s
1340:	learn: 0.2159913	test: 0.2190201	best: 0.2190201 (1340)	total: 24.6s	remaining: 47.1s
1360:	learn: 0.2157526	test: 0.2188721	best: 0.2188721 (1360)	total: 24.9s	remaining: 46.8s
1380:	learn: 0.2154759	test: 0.2187007	best: 0.2187007 (1380)	total: 25.3s	remaining: 46.4s
1400:	learn: 0.2151596	test: 0.2184877	best: 0.2184877 (1400)	total: 25.7s	remaining: 46s
1420:	learn: 0.2148622	test: 0.2183025	best: 0.2183025 (1420)	total: 26s	remaining: 45.6s
1440:	learn: 0.2146112	test: 0.2181408	best: 0.2181408 (1440)	total: 26.4s	remaining: 45.2s
1460:	learn: 0.2143657	test: 0.2179945	best: 0.2179945 (1460)	total: 26.7s	remaining: 44.9s
1480:	learn: 0.2141381	test: 0.2178547	best: 0.2178547 (1480)	total: 27.1s	remaining: 44.5s
1500:	learn: 0.2139178	test: 0.2177342	best: 0.2177342 (1500)	total: 27.5s	remaining: 44.1s
1520:	learn: 0.2136868	test: 0.2175892	best: 0.2175892 (1520)	total: 27.8s	remaining: 43.8s
1540:	learn: 0.2134296	test: 0.2174431	best: 0.2174431 (1540)	total: 28.2s	remaining: 43.4s
1560:	learn: 0.2131795	test: 0.2172788	best: 0.2172788 (1560)	total: 28.6s	remaining: 43s
1580:	learn: 0.2129688	test: 0.2171729	best: 0.2171729 (1580)	total: 28.9s	remaining: 42.7s
1600:	learn: 0.2127769	test: 0.2170488	best: 0.2170488 (1600)	total: 29.3s	remaining: 42.3s
1620:	learn: 0.2125346	test: 0.2168956	best: 0.2168956 (1620)	total: 29.6s	remaining: 41.9s
1640:	learn: 0.2123524	test: 0.2167863	best: 0.2167863 (1640)	total: 30s	remaining: 41.6s
1660:	learn: 0.2121231	test: 0.2166541	best: 0.2166494 (1659)	total: 30.4s	remaining: 41.2s
1680:	learn: 0.2119089	test: 0.2165378	best: 0.2165374 (1678)	total: 30.7s	remaining: 40.8s
1700:	learn: 0.2116654	test: 0.2163759	best: 0.2163759 (1700)	total: 31.1s	remaining: 40.4s
1720:	learn: 0.2114488	test: 0.2162577	best: 0.2162577 (1720)	total: 31.5s	remaining: 40.1s
1740:	learn: 0.2112490	test: 0.2161303	best: 0.2161303 (1740)	total: 31.9s	remaining: 39.7s
1760:	learn: 0.2110176	test: 0.2160342	best: 0.2160342 (1760)	total: 32.2s	remaining: 39.4s
1780:	learn: 0.2107992	test: 0.2159051	best: 0.2159051 (1780)	total: 32.6s	remaining: 39s
1800:	learn: 0.2105994	test: 0.2158140	best: 0.2158140 (1800)	total: 32.9s	remaining: 38.6s
1820:	learn: 0.2103725	test: 0.2156661	best: 0.2156661 (1820)	total: 33.3s	remaining: 38.3s
1840:	learn: 0.2101612	test: 0.2155533	best: 0.2155533 (1840)	total: 33.7s	remaining: 37.9s
1860:	learn: 0.2099649	test: 0.2154654	best: 0.2154649 (1859)	total: 34s	remaining: 37.5s
1880:	learn: 0.2097564	test: 0.2153690	best: 0.2153690 (1880)	total: 34.4s	remaining: 37.2s
1900:	learn: 0.2095571	test: 0.2152779	best: 0.2152779 (1900)	total: 34.8s	remaining: 36.8s
1920:	learn: 0.2093343	test: 0.2151279	best: 0.2151224 (1919)	total: 35.1s	remaining: 36.4s
1940:	learn: 0.2091316	test: 0.2150392	best: 0.2150392 (1940)	total: 35.5s	remaining: 36.1s
1960:	learn: 0.2089392	test: 0.2149519	best: 0.2149519 (1960)	total: 35.9s	remaining: 35.7s
1980:	learn: 0.2087383	test: 0.2148364	best: 0.2148364 (1980)	total: 36.2s	remaining: 35.3s
2000:	learn: 0.2085747	test: 0.2147772	best: 0.2147772 (2000)	total: 36.6s	remaining: 35s
2020:	learn: 0.2083731	test: 0.2146748	best: 0.2146742 (2019)	total: 37s	remaining: 34.6s
2040:	learn: 0.2081996	test: 0.2145749	best: 0.2145749 (2040)	total: 37.3s	remaining: 34.2s
2060:	learn: 0.2079969	test: 0.2144383	best: 0.2144383 (2060)	total: 37.7s	remaining: 33.9s
2080:	learn: 0.2078086	test: 0.2143410	best: 0.2143410 (2080)	total: 38.1s	remaining: 33.5s
2100:	learn: 0.2076234	test: 0.2142395	best: 0.2142395 (2100)	total: 38.5s	remaining: 33.2s
2120:	learn: 0.2074355	test: 0.2141437	best: 0.2141437 (2120)	total: 38.9s	remaining: 32.8s
2140:	learn: 0.2072498	test: 0.2140702	best: 0.2140702 (2140)	total: 39.2s	remaining: 32.5s
2160:	learn: 0.2070776	test: 0.2139812	best: 0.2139812 (2160)	total: 39.6s	remaining: 32.1s
2180:	learn: 0.2069125	test: 0.2139149	best: 0.2139149 (2180)	total: 40s	remaining: 31.7s
2200:	learn: 0.2067466	test: 0.2138463	best: 0.2138463 (2200)	total: 40.3s	remaining: 31.4s
2220:	learn: 0.2065887	test: 0.2137788	best: 0.2137783 (2219)	total: 40.7s	remaining: 31s
2240:	learn: 0.2064046	test: 0.2137014	best: 0.2137014 (2240)	total: 41.1s	remaining: 30.7s
2260:	learn: 0.2061753	test: 0.2135551	best: 0.2135551 (2260)	total: 41.5s	remaining: 30.3s
2280:	learn: 0.2059874	test: 0.2134947	best: 0.2134947 (2280)	total: 41.8s	remaining: 29.9s
2300:	learn: 0.2058402	test: 0.2134054	best: 0.2134054 (2300)	total: 42.2s	remaining: 29.5s
2320:	learn: 0.2056575	test: 0.2133095	best: 0.2133095 (2320)	total: 42.5s	remaining: 29.2s
2340:	learn: 0.2054907	test: 0.2132483	best: 0.2132467 (2338)	total: 42.9s	remaining: 28.8s
2360:	learn: 0.2053438	test: 0.2131891	best: 0.2131891 (2360)	total: 43.3s	remaining: 28.5s
2380:	learn: 0.2051708	test: 0.2131290	best: 0.2131290 (2380)	total: 43.7s	remaining: 28.1s
2400:	learn: 0.2049960	test: 0.2130630	best: 0.2130630 (2400)	total: 44s	remaining: 27.7s
2420:	learn: 0.2048127	test: 0.2129512	best: 0.2129512 (2420)	total: 44.4s	remaining: 27.4s
2440:	learn: 0.2046738	test: 0.2128904	best: 0.2128902 (2439)	total: 44.8s	remaining: 27s
2460:	learn: 0.2045033	test: 0.2128146	best: 0.2128146 (2460)	total: 45.1s	remaining: 26.6s
2480:	learn: 0.2043122	test: 0.2126951	best: 0.2126951 (2480)	total: 45.5s	remaining: 26.3s
2500:	learn: 0.2041639	test: 0.2126157	best: 0.2126157 (2500)	total: 45.9s	remaining: 25.9s
2520:	learn: 0.2040155	test: 0.2125663	best: 0.2125623 (2517)	total: 46.3s	remaining: 25.5s
2540:	learn: 0.2038531	test: 0.2125001	best: 0.2125001 (2540)	total: 46.6s	remaining: 25.2s
2560:	learn: 0.2037104	test: 0.2124339	best: 0.2124339 (2560)	total: 47s	remaining: 24.8s
2580:	learn: 0.2035724	test: 0.2123837	best: 0.2123837 (2580)	total: 47.4s	remaining: 24.4s
2600:	learn: 0.2034363	test: 0.2123399	best: 0.2123394 (2599)	total: 47.7s	remaining: 24.1s
2620:	learn: 0.2032705	test: 0.2122704	best: 0.2122694 (2619)	total: 48.1s	remaining: 23.7s
2640:	learn: 0.2031594	test: 0.2122412	best: 0.2122402 (2635)	total: 48.5s	remaining: 23.3s
2660:	learn: 0.2030060	test: 0.2121728	best: 0.2121728 (2660)	total: 48.8s	remaining: 23s
2680:	learn: 0.2028534	test: 0.2121011	best: 0.2121011 (2680)	total: 49.2s	remaining: 22.6s
2700:	learn: 0.2026573	test: 0.2119776	best: 0.2119769 (2698)	total: 49.6s	remaining: 22.2s
2720:	learn: 0.2025049	test: 0.2119153	best: 0.2119140 (2719)	total: 49.9s	remaining: 21.9s
2740:	learn: 0.2023523	test: 0.2118601	best: 0.2118601 (2740)	total: 50.3s	remaining: 21.5s
2760:	learn: 0.2022151	test: 0.2118227	best: 0.2118227 (2760)	total: 50.7s	remaining: 21.1s
2780:	learn: 0.2020742	test: 0.2117727	best: 0.2117727 (2780)	total: 51.1s	remaining: 20.8s
2800:	learn: 0.2019036	test: 0.2116961	best: 0.2116958 (2799)	total: 51.5s	remaining: 20.4s
2820:	learn: 0.2017563	test: 0.2116009	best: 0.2116009 (2820)	total: 51.8s	remaining: 20.1s
2840:	learn: 0.2015810	test: 0.2115055	best: 0.2115055 (2840)	total: 52.2s	remaining: 19.7s
2860:	learn: 0.2014513	test: 0.2114549	best: 0.2114549 (2860)	total: 52.6s	remaining: 19.3s
2880:	learn: 0.2013175	test: 0.2114322	best: 0.2114322 (2880)	total: 53s	remaining: 19s
2900:	learn: 0.2011691	test: 0.2113948	best: 0.2113931 (2895)	total: 53.3s	remaining: 18.6s
2920:	learn: 0.2010150	test: 0.2113463	best: 0.2113440 (2919)	total: 53.7s	remaining: 18.2s
2940:	learn: 0.2008620	test: 0.2112768	best: 0.2112768 (2940)	total: 54.1s	remaining: 17.9s
2960:	learn: 0.2007279	test: 0.2112280	best: 0.2112280 (2960)	total: 54.4s	remaining: 17.5s
2980:	learn: 0.2006156	test: 0.2112012	best: 0.2111957 (2977)	total: 54.8s	remaining: 17.1s
3000:	learn: 0.2004682	test: 0.2111205	best: 0.2111205 (3000)	total: 55.2s	remaining: 16.8s
3020:	learn: 0.2003301	test: 0.2110704	best: 0.2110703 (3018)	total: 55.6s	remaining: 16.4s
3040:	learn: 0.2001673	test: 0.2110189	best: 0.2110189 (3040)	total: 55.9s	remaining: 16s
3060:	learn: 0.2000152	test: 0.2109324	best: 0.2109324 (3060)	total: 56.3s	remaining: 15.7s
3080:	learn: 0.1998293	test: 0.2108317	best: 0.2108299 (3079)	total: 56.6s	remaining: 15.3s
3100:	learn: 0.1996947	test: 0.2107802	best: 0.2107802 (3100)	total: 57s	remaining: 14.9s
3120:	learn: 0.1995409	test: 0.2107224	best: 0.2107209 (3119)	total: 57.4s	remaining: 14.6s
3140:	learn: 0.1993974	test: 0.2106742	best: 0.2106742 (3140)	total: 57.7s	remaining: 14.2s
3160:	learn: 0.1992835	test: 0.2106514	best: 0.2106514 (3160)	total: 58.1s	remaining: 13.8s
3180:	learn: 0.1991616	test: 0.2106033	best: 0.2106033 (3180)	total: 58.5s	remaining: 13.5s
3200:	learn: 0.1990238	test: 0.2105386	best: 0.2105386 (3200)	total: 58.9s	remaining: 13.1s
3220:	learn: 0.1988784	test: 0.2104835	best: 0.2104835 (3220)	total: 59.3s	remaining: 12.7s
3240:	learn: 0.1987487	test: 0.2104207	best: 0.2104207 (3240)	total: 59.6s	remaining: 12.4s
3260:	learn: 0.1986290	test: 0.2103835	best: 0.2103835 (3260)	total: 60s	remaining: 12s
3280:	learn: 0.1984934	test: 0.2103242	best: 0.2103242 (3280)	total: 1m	remaining: 11.6s
3300:	learn: 0.1983409	test: 0.2102687	best: 0.2102677 (3299)	total: 1m	remaining: 11.3s
3320:	learn: 0.1981983	test: 0.2102264	best: 0.2102254 (3319)	total: 1m 1s	remaining: 10.9s
3340:	learn: 0.1980647	test: 0.2101460	best: 0.2101460 (3340)	total: 1m 1s	remaining: 10.5s
3360:	learn: 0.1979267	test: 0.2100717	best: 0.2100716 (3359)	total: 1m 1s	remaining: 10.2s
3380:	learn: 0.1978038	test: 0.2100343	best: 0.2100343 (3380)	total: 1m 2s	remaining: 9.79s
3400:	learn: 0.1976771	test: 0.2099789	best: 0.2099789 (3400)	total: 1m 2s	remaining: 9.42s
3420:	learn: 0.1975346	test: 0.2099112	best: 0.2099112 (3420)	total: 1m 2s	remaining: 9.05s
3440:	learn: 0.1974165	test: 0.2098752	best: 0.2098752 (3440)	total: 1m 3s	remaining: 8.69s
3460:	learn: 0.1972773	test: 0.2098213	best: 0.2098196 (3459)	total: 1m 3s	remaining: 8.32s
3480:	learn: 0.1971633	test: 0.2097756	best: 0.2097752 (3479)	total: 1m 4s	remaining: 7.95s
3500:	learn: 0.1970290	test: 0.2097325	best: 0.2097292 (3498)	total: 1m 4s	remaining: 7.58s
3520:	learn: 0.1968995	test: 0.2097041	best: 0.2097041 (3520)	total: 1m 4s	remaining: 7.22s
3540:	learn: 0.1967710	test: 0.2096510	best: 0.2096510 (3540)	total: 1m 5s	remaining: 6.85s
3560:	learn: 0.1966472	test: 0.2096269	best: 0.2096269 (3560)	total: 1m 5s	remaining: 6.48s
3580:	learn: 0.1965286	test: 0.2095842	best: 0.2095842 (3580)	total: 1m 5s	remaining: 6.11s
3600:	learn: 0.1964196	test: 0.2095692	best: 0.2095637 (3595)	total: 1m 6s	remaining: 5.74s
3620:	learn: 0.1963070	test: 0.2095466	best: 0.2095466 (3620)	total: 1m 6s	remaining: 5.38s
3640:	learn: 0.1961930	test: 0.2095136	best: 0.2095119 (3638)	total: 1m 7s	remaining: 5.01s
3660:	learn: 0.1960539	test: 0.2094623	best: 0.2094615 (3659)	total: 1m 7s	remaining: 4.64s
3680:	learn: 0.1959316	test: 0.2094341	best: 0.2094341 (3680)	total: 1m 7s	remaining: 4.27s
3700:	learn: 0.1958265	test: 0.2094063	best: 0.2094050 (3698)	total: 1m 8s	remaining: 3.91s
3720:	learn: 0.1957189	test: 0.2093868	best: 0.2093868 (3720)	total: 1m 8s	remaining: 3.54s
3740:	learn: 0.1955852	test: 0.2093364	best: 0.2093364 (3740)	total: 1m 8s	remaining: 3.17s
3760:	learn: 0.1954707	test: 0.2093141	best: 0.2093131 (3757)	total: 1m 9s	remaining: 2.8s
3780:	learn: 0.1953417	test: 0.2092686	best: 0.2092686 (3780)	total: 1m 9s	remaining: 2.43s
3800:	learn: 0.1952209	test: 0.2092477	best: 0.2092449 (3793)	total: 1m 10s	remaining: 2.06s
3820:	learn: 0.1951039	test: 0.2092102	best: 0.2092075 (3818)	total: 1m 10s	remaining: 1.7s
3840:	learn: 0.1949730	test: 0.2091830	best: 0.2091830 (3840)	total: 1m 10s	remaining: 1.33s
3860:	learn: 0.1948425	test: 0.2091344	best: 0.2091343 (3859)	total: 1m 11s	remaining: 959ms
3880:	learn: 0.1947240	test: 0.2090999	best: 0.2090999 (3880)	total: 1m 11s	remaining: 590ms
3900:	learn: 0.1945949	test: 0.2090531	best: 0.2090524 (3898)	total: 1m 11s	remaining: 221ms
3912:	learn: 0.1945233	test: 0.2090251	best: 0.2090251 (3912)	total: 1m 12s	remaining: 0us
bestTest = 0.209025082
bestIteration = 3912

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403322	test: 0.6405435	best: 0.6405435 (0)	total: 9.62ms	remaining: 9.62ms
1:	learn: 0.5953287	test: 0.5957294	best: 0.5957294 (1)	total: 18.9ms	remaining: 0us
bestTest = 0.5957293764
bestIteration = 1
0:	learn: 0.6411087	test: 0.6412505	best: 0.6412505 (0)	total: 17.3ms	remaining: 1m 16s
20:	learn: 0.3363460	test: 0.3378834	best: 0.3378834 (20)	total: 412ms	remaining: 1m 27s
40:	learn: 0.3030903	test: 0.3050608	best: 0.3050608 (40)	total: 804ms	remaining: 1m 26s
60:	learn: 0.2881475	test: 0.2899114	best: 0.2899114 (60)	total: 1.21s	remaining: 1m 27s
80:	learn: 0.2809843	test: 0.2825871	best: 0.2825871 (80)	total: 1.61s	remaining: 1m 26s
100:	learn: 0.2754117	test: 0.2770442	best: 0.2770442 (100)	total: 1.98s	remaining: 1m 25s
120:	learn: 0.2706145	test: 0.2722527	best: 0.2722527 (120)	total: 2.35s	remaining: 1m 24s
140:	learn: 0.2665566	test: 0.2681485	best: 0.2681485 (140)	total: 2.72s	remaining: 1m 23s
160:	learn: 0.2623205	test: 0.2639511	best: 0.2639511 (160)	total: 3.11s	remaining: 1m 23s
180:	learn: 0.2595151	test: 0.2610477	best: 0.2610477 (180)	total: 3.49s	remaining: 1m 22s
200:	learn: 0.2565857	test: 0.2580564	best: 0.2580564 (200)	total: 3.87s	remaining: 1m 21s
220:	learn: 0.2540918	test: 0.2555506	best: 0.2555506 (220)	total: 4.24s	remaining: 1m 21s
240:	learn: 0.2520543	test: 0.2535148	best: 0.2535148 (240)	total: 4.62s	remaining: 1m 20s
260:	learn: 0.2496517	test: 0.2510294	best: 0.2510294 (260)	total: 5.01s	remaining: 1m 20s
280:	learn: 0.2482141	test: 0.2495809	best: 0.2495809 (280)	total: 5.36s	remaining: 1m 19s
300:	learn: 0.2462905	test: 0.2476386	best: 0.2476386 (300)	total: 5.73s	remaining: 1m 19s
320:	learn: 0.2446989	test: 0.2460320	best: 0.2460320 (320)	total: 6.1s	remaining: 1m 18s
340:	learn: 0.2434529	test: 0.2447786	best: 0.2447786 (340)	total: 6.46s	remaining: 1m 18s
360:	learn: 0.2422839	test: 0.2437202	best: 0.2437202 (360)	total: 6.83s	remaining: 1m 17s
380:	learn: 0.2411286	test: 0.2425772	best: 0.2425772 (380)	total: 7.2s	remaining: 1m 17s
400:	learn: 0.2400718	test: 0.2415924	best: 0.2415924 (400)	total: 7.57s	remaining: 1m 16s
420:	learn: 0.2391410	test: 0.2407189	best: 0.2407189 (420)	total: 7.94s	remaining: 1m 16s
440:	learn: 0.2379028	test: 0.2395009	best: 0.2395009 (440)	total: 8.31s	remaining: 1m 15s
460:	learn: 0.2368759	test: 0.2385109	best: 0.2385109 (460)	total: 8.68s	remaining: 1m 15s
480:	learn: 0.2357517	test: 0.2374384	best: 0.2374384 (480)	total: 9.06s	remaining: 1m 14s
500:	learn: 0.2346993	test: 0.2364342	best: 0.2364342 (500)	total: 9.44s	remaining: 1m 14s
520:	learn: 0.2337650	test: 0.2355697	best: 0.2355697 (520)	total: 9.8s	remaining: 1m 14s
540:	learn: 0.2329262	test: 0.2348258	best: 0.2348258 (540)	total: 10.2s	remaining: 1m 13s
560:	learn: 0.2320785	test: 0.2340702	best: 0.2340702 (560)	total: 10.5s	remaining: 1m 13s
580:	learn: 0.2313313	test: 0.2333996	best: 0.2333996 (580)	total: 10.9s	remaining: 1m 12s
600:	learn: 0.2306938	test: 0.2328412	best: 0.2328412 (600)	total: 11.3s	remaining: 1m 12s
620:	learn: 0.2299702	test: 0.2322280	best: 0.2322280 (620)	total: 11.6s	remaining: 1m 11s
640:	learn: 0.2293382	test: 0.2316462	best: 0.2316462 (640)	total: 12s	remaining: 1m 11s
660:	learn: 0.2287734	test: 0.2311891	best: 0.2311891 (660)	total: 12.3s	remaining: 1m 10s
680:	learn: 0.2282053	test: 0.2307063	best: 0.2307063 (680)	total: 12.7s	remaining: 1m 10s
700:	learn: 0.2276403	test: 0.2302454	best: 0.2302454 (700)	total: 13s	remaining: 1m 9s
720:	learn: 0.2271866	test: 0.2299291	best: 0.2299291 (720)	total: 13.4s	remaining: 1m 9s
740:	learn: 0.2265046	test: 0.2293470	best: 0.2293470 (740)	total: 13.8s	remaining: 1m 9s
760:	learn: 0.2259743	test: 0.2289540	best: 0.2289540 (760)	total: 14.1s	remaining: 1m 8s
780:	learn: 0.2254949	test: 0.2285724	best: 0.2285724 (780)	total: 14.5s	remaining: 1m 8s
800:	learn: 0.2250027	test: 0.2281625	best: 0.2281625 (800)	total: 14.8s	remaining: 1m 7s
820:	learn: 0.2245101	test: 0.2277821	best: 0.2277821 (820)	total: 15.2s	remaining: 1m 7s
840:	learn: 0.2240705	test: 0.2274042	best: 0.2274042 (840)	total: 15.6s	remaining: 1m 7s
860:	learn: 0.2235511	test: 0.2269395	best: 0.2269395 (860)	total: 15.9s	remaining: 1m 6s
880:	learn: 0.2231587	test: 0.2266547	best: 0.2266547 (880)	total: 16.3s	remaining: 1m 6s
900:	learn: 0.2227533	test: 0.2263610	best: 0.2263610 (900)	total: 16.7s	remaining: 1m 5s
920:	learn: 0.2223562	test: 0.2260809	best: 0.2260809 (920)	total: 17s	remaining: 1m 5s
940:	learn: 0.2220264	test: 0.2258338	best: 0.2258338 (940)	total: 17.4s	remaining: 1m 4s
960:	learn: 0.2216190	test: 0.2255264	best: 0.2255264 (960)	total: 17.7s	remaining: 1m 4s
980:	learn: 0.2211390	test: 0.2251029	best: 0.2251029 (980)	total: 18.1s	remaining: 1m 4s
1000:	learn: 0.2206852	test: 0.2247290	best: 0.2247290 (1000)	total: 18.5s	remaining: 1m 3s
1020:	learn: 0.2203398	test: 0.2244395	best: 0.2244395 (1020)	total: 18.8s	remaining: 1m 3s
1040:	learn: 0.2199783	test: 0.2241857	best: 0.2241857 (1040)	total: 19.2s	remaining: 1m 2s
1060:	learn: 0.2196619	test: 0.2239403	best: 0.2239403 (1060)	total: 19.5s	remaining: 1m 2s
1080:	learn: 0.2194086	test: 0.2237445	best: 0.2237445 (1080)	total: 19.9s	remaining: 1m 2s
1100:	learn: 0.2189856	test: 0.2233959	best: 0.2233959 (1100)	total: 20.3s	remaining: 1m 1s
1120:	learn: 0.2186646	test: 0.2231330	best: 0.2231330 (1120)	total: 20.6s	remaining: 1m 1s
1140:	learn: 0.2183487	test: 0.2228882	best: 0.2228882 (1140)	total: 21s	remaining: 1m 1s
1160:	learn: 0.2180107	test: 0.2226437	best: 0.2226437 (1160)	total: 21.4s	remaining: 1m
1180:	learn: 0.2176973	test: 0.2224032	best: 0.2224032 (1180)	total: 21.7s	remaining: 1m
1200:	learn: 0.2173540	test: 0.2221644	best: 0.2221644 (1200)	total: 22.1s	remaining: 59.9s
1220:	learn: 0.2170960	test: 0.2220025	best: 0.2220016 (1219)	total: 22.5s	remaining: 59.5s
1240:	learn: 0.2168548	test: 0.2218280	best: 0.2218280 (1240)	total: 22.8s	remaining: 59.2s
1260:	learn: 0.2165555	test: 0.2216141	best: 0.2216141 (1260)	total: 23.2s	remaining: 58.8s
1280:	learn: 0.2162649	test: 0.2214183	best: 0.2214183 (1280)	total: 23.5s	remaining: 58.4s
1300:	learn: 0.2159544	test: 0.2212333	best: 0.2212333 (1300)	total: 23.9s	remaining: 58s
1320:	learn: 0.2157239	test: 0.2210970	best: 0.2210970 (1320)	total: 24.3s	remaining: 57.6s
1340:	learn: 0.2153710	test: 0.2208197	best: 0.2208197 (1340)	total: 24.6s	remaining: 57.3s
1360:	learn: 0.2150881	test: 0.2206446	best: 0.2206446 (1360)	total: 25s	remaining: 56.9s
1380:	learn: 0.2148420	test: 0.2205028	best: 0.2205028 (1380)	total: 25.4s	remaining: 56.5s
1400:	learn: 0.2145836	test: 0.2203413	best: 0.2203413 (1400)	total: 25.7s	remaining: 56.1s
1420:	learn: 0.2143271	test: 0.2201930	best: 0.2201930 (1420)	total: 26.1s	remaining: 55.8s
1440:	learn: 0.2140851	test: 0.2200113	best: 0.2200113 (1440)	total: 26.5s	remaining: 55.4s
1460:	learn: 0.2138254	test: 0.2198349	best: 0.2198349 (1460)	total: 26.8s	remaining: 55s
1480:	learn: 0.2136013	test: 0.2197081	best: 0.2197081 (1480)	total: 27.2s	remaining: 54.7s
1500:	learn: 0.2133440	test: 0.2195514	best: 0.2195514 (1500)	total: 27.6s	remaining: 54.3s
1520:	learn: 0.2130725	test: 0.2193668	best: 0.2193668 (1520)	total: 27.9s	remaining: 53.9s
1540:	learn: 0.2128316	test: 0.2192445	best: 0.2192445 (1540)	total: 28.3s	remaining: 53.6s
1560:	learn: 0.2126080	test: 0.2191205	best: 0.2191205 (1560)	total: 28.7s	remaining: 53.2s
1580:	learn: 0.2123521	test: 0.2189529	best: 0.2189529 (1580)	total: 29s	remaining: 52.8s
1600:	learn: 0.2121638	test: 0.2188387	best: 0.2188387 (1600)	total: 29.4s	remaining: 52.4s
1620:	learn: 0.2119292	test: 0.2186908	best: 0.2186908 (1620)	total: 29.7s	remaining: 52.1s
1640:	learn: 0.2117292	test: 0.2185797	best: 0.2185772 (1638)	total: 30.1s	remaining: 51.7s
1660:	learn: 0.2115407	test: 0.2184717	best: 0.2184717 (1660)	total: 30.5s	remaining: 51.3s
1680:	learn: 0.2113447	test: 0.2183683	best: 0.2183683 (1680)	total: 30.8s	remaining: 51s
1700:	learn: 0.2110857	test: 0.2181999	best: 0.2181999 (1700)	total: 31.2s	remaining: 50.6s
1720:	learn: 0.2108470	test: 0.2180505	best: 0.2180505 (1720)	total: 31.6s	remaining: 50.2s
1740:	learn: 0.2106069	test: 0.2179166	best: 0.2179166 (1740)	total: 31.9s	remaining: 49.8s
1760:	learn: 0.2103423	test: 0.2177365	best: 0.2177365 (1760)	total: 32.3s	remaining: 49.5s
1780:	learn: 0.2101321	test: 0.2175944	best: 0.2175944 (1780)	total: 32.6s	remaining: 49.1s
1800:	learn: 0.2099348	test: 0.2174916	best: 0.2174916 (1800)	total: 33s	remaining: 48.7s
1820:	learn: 0.2097283	test: 0.2173718	best: 0.2173718 (1820)	total: 33.4s	remaining: 48.3s
1840:	learn: 0.2095267	test: 0.2173019	best: 0.2173019 (1840)	total: 33.7s	remaining: 48s
1860:	learn: 0.2093265	test: 0.2172164	best: 0.2172164 (1860)	total: 34.1s	remaining: 47.6s
1880:	learn: 0.2091180	test: 0.2171082	best: 0.2171082 (1880)	total: 34.5s	remaining: 47.2s
1900:	learn: 0.2089114	test: 0.2169853	best: 0.2169853 (1900)	total: 34.8s	remaining: 46.9s
1920:	learn: 0.2086989	test: 0.2168105	best: 0.2168105 (1920)	total: 35.2s	remaining: 46.5s
1940:	learn: 0.2084558	test: 0.2166676	best: 0.2166676 (1940)	total: 35.6s	remaining: 46.2s
1960:	learn: 0.2082409	test: 0.2165449	best: 0.2165444 (1959)	total: 35.9s	remaining: 45.8s
1980:	learn: 0.2080591	test: 0.2164587	best: 0.2164587 (1980)	total: 36.3s	remaining: 45.4s
2000:	learn: 0.2078674	test: 0.2163309	best: 0.2163309 (2000)	total: 36.7s	remaining: 45.1s
2020:	learn: 0.2076989	test: 0.2162315	best: 0.2162315 (2020)	total: 37s	remaining: 44.7s
2040:	learn: 0.2075103	test: 0.2161258	best: 0.2161258 (2040)	total: 37.4s	remaining: 44.3s
2060:	learn: 0.2073166	test: 0.2160339	best: 0.2160339 (2060)	total: 37.8s	remaining: 43.9s
2080:	learn: 0.2070971	test: 0.2159144	best: 0.2159144 (2080)	total: 38.1s	remaining: 43.6s
2100:	learn: 0.2069166	test: 0.2158126	best: 0.2158126 (2100)	total: 38.5s	remaining: 43.2s
2120:	learn: 0.2067604	test: 0.2157606	best: 0.2157606 (2120)	total: 38.9s	remaining: 42.9s
2140:	learn: 0.2065743	test: 0.2156681	best: 0.2156681 (2140)	total: 39.2s	remaining: 42.5s
2160:	learn: 0.2064122	test: 0.2155849	best: 0.2155849 (2160)	total: 39.6s	remaining: 42.1s
2180:	learn: 0.2062195	test: 0.2154751	best: 0.2154751 (2180)	total: 40s	remaining: 41.8s
2200:	learn: 0.2060514	test: 0.2153915	best: 0.2153915 (2200)	total: 40.3s	remaining: 41.4s
2220:	learn: 0.2058339	test: 0.2152815	best: 0.2152815 (2220)	total: 40.7s	remaining: 41s
2240:	learn: 0.2056355	test: 0.2151738	best: 0.2151738 (2240)	total: 41.1s	remaining: 40.6s
2260:	learn: 0.2054491	test: 0.2150803	best: 0.2150803 (2260)	total: 41.4s	remaining: 40.3s
2280:	learn: 0.2052475	test: 0.2149669	best: 0.2149647 (2278)	total: 41.8s	remaining: 39.9s
2300:	learn: 0.2050809	test: 0.2148802	best: 0.2148802 (2300)	total: 42.2s	remaining: 39.5s
2320:	learn: 0.2048830	test: 0.2147659	best: 0.2147659 (2320)	total: 42.5s	remaining: 39.2s
2340:	learn: 0.2046774	test: 0.2146640	best: 0.2146640 (2340)	total: 42.9s	remaining: 38.8s
2360:	learn: 0.2045176	test: 0.2146010	best: 0.2146010 (2360)	total: 43.3s	remaining: 38.4s
2380:	learn: 0.2043458	test: 0.2145211	best: 0.2145211 (2380)	total: 43.6s	remaining: 38.1s
2400:	learn: 0.2041879	test: 0.2144465	best: 0.2144448 (2399)	total: 44s	remaining: 37.7s
2420:	learn: 0.2040435	test: 0.2143923	best: 0.2143923 (2420)	total: 44.4s	remaining: 37.3s
2440:	learn: 0.2038744	test: 0.2143189	best: 0.2143189 (2440)	total: 44.7s	remaining: 37s
2460:	learn: 0.2037160	test: 0.2142774	best: 0.2142774 (2460)	total: 45.1s	remaining: 36.6s
2480:	learn: 0.2035652	test: 0.2141992	best: 0.2141992 (2480)	total: 45.5s	remaining: 36.2s
2500:	learn: 0.2034204	test: 0.2141515	best: 0.2141515 (2500)	total: 45.8s	remaining: 35.9s
2520:	learn: 0.2032534	test: 0.2140786	best: 0.2140786 (2520)	total: 46.2s	remaining: 35.5s
2540:	learn: 0.2031037	test: 0.2140177	best: 0.2140165 (2539)	total: 46.6s	remaining: 35.1s
2560:	learn: 0.2029683	test: 0.2139812	best: 0.2139812 (2560)	total: 46.9s	remaining: 34.8s
2580:	learn: 0.2028291	test: 0.2139137	best: 0.2139137 (2580)	total: 47.3s	remaining: 34.4s
2600:	learn: 0.2027046	test: 0.2138798	best: 0.2138794 (2599)	total: 47.7s	remaining: 34.1s
2620:	learn: 0.2025487	test: 0.2138167	best: 0.2138167 (2620)	total: 48s	remaining: 33.7s
2640:	learn: 0.2023945	test: 0.2137399	best: 0.2137399 (2640)	total: 48.4s	remaining: 33.3s
2660:	learn: 0.2022426	test: 0.2136817	best: 0.2136817 (2660)	total: 48.8s	remaining: 33s
2680:	learn: 0.2021173	test: 0.2136130	best: 0.2136127 (2679)	total: 49.2s	remaining: 32.6s
2700:	learn: 0.2019655	test: 0.2135430	best: 0.2135430 (2700)	total: 49.5s	remaining: 32.2s
2720:	learn: 0.2017973	test: 0.2134654	best: 0.2134643 (2718)	total: 49.9s	remaining: 31.9s
2740:	learn: 0.2016608	test: 0.2133985	best: 0.2133985 (2740)	total: 50.3s	remaining: 31.5s
2760:	learn: 0.2015116	test: 0.2133599	best: 0.2133593 (2758)	total: 50.6s	remaining: 31.1s
2780:	learn: 0.2013654	test: 0.2132836	best: 0.2132836 (2780)	total: 51s	remaining: 30.8s
2800:	learn: 0.2012253	test: 0.2132118	best: 0.2132118 (2800)	total: 51.4s	remaining: 30.4s
2820:	learn: 0.2010798	test: 0.2131482	best: 0.2131482 (2820)	total: 51.8s	remaining: 30.1s
2840:	learn: 0.2009336	test: 0.2130839	best: 0.2130839 (2840)	total: 52.1s	remaining: 29.7s
2860:	learn: 0.2008051	test: 0.2130328	best: 0.2130328 (2860)	total: 52.5s	remaining: 29.3s
2880:	learn: 0.2006478	test: 0.2129690	best: 0.2129690 (2880)	total: 52.9s	remaining: 29s
2900:	learn: 0.2005110	test: 0.2129088	best: 0.2129088 (2900)	total: 53.2s	remaining: 28.6s
2920:	learn: 0.2003301	test: 0.2128057	best: 0.2128057 (2920)	total: 53.6s	remaining: 28.2s
2940:	learn: 0.2001895	test: 0.2127627	best: 0.2127612 (2939)	total: 54s	remaining: 27.9s
2960:	learn: 0.2000369	test: 0.2127081	best: 0.2127081 (2960)	total: 54.3s	remaining: 27.5s
2980:	learn: 0.1998888	test: 0.2126622	best: 0.2126622 (2980)	total: 54.7s	remaining: 27.1s
3000:	learn: 0.1997241	test: 0.2125396	best: 0.2125396 (3000)	total: 55.1s	remaining: 26.8s
3020:	learn: 0.1995919	test: 0.2124749	best: 0.2124749 (3020)	total: 55.4s	remaining: 26.4s
3040:	learn: 0.1994297	test: 0.2123963	best: 0.2123963 (3040)	total: 55.8s	remaining: 26s
3060:	learn: 0.1992906	test: 0.2123601	best: 0.2123601 (3060)	total: 56.2s	remaining: 25.7s
3080:	learn: 0.1991696	test: 0.2123089	best: 0.2123089 (3080)	total: 56.5s	remaining: 25.3s
3100:	learn: 0.1990235	test: 0.2122631	best: 0.2122631 (3100)	total: 56.9s	remaining: 24.9s
3120:	learn: 0.1988857	test: 0.2122110	best: 0.2122110 (3120)	total: 57.3s	remaining: 24.6s
3140:	learn: 0.1987581	test: 0.2121549	best: 0.2121513 (3138)	total: 57.6s	remaining: 24.2s
3160:	learn: 0.1986239	test: 0.2120898	best: 0.2120898 (3160)	total: 58s	remaining: 23.8s
3180:	learn: 0.1984753	test: 0.2120532	best: 0.2120532 (3180)	total: 58.4s	remaining: 23.5s
3200:	learn: 0.1983576	test: 0.2120189	best: 0.2120189 (3200)	total: 58.8s	remaining: 23.1s
3220:	learn: 0.1982124	test: 0.2119735	best: 0.2119708 (3218)	total: 59.1s	remaining: 22.7s
3240:	learn: 0.1980752	test: 0.2119046	best: 0.2119046 (3240)	total: 59.5s	remaining: 22.4s
3260:	learn: 0.1979215	test: 0.2118418	best: 0.2118418 (3260)	total: 59.9s	remaining: 22s
3280:	learn: 0.1977750	test: 0.2117823	best: 0.2117815 (3279)	total: 1m	remaining: 21.6s
3300:	learn: 0.1976469	test: 0.2117358	best: 0.2117358 (3300)	total: 1m	remaining: 21.3s
3320:	learn: 0.1975282	test: 0.2116871	best: 0.2116871 (3320)	total: 1m 1s	remaining: 20.9s
3340:	learn: 0.1974039	test: 0.2116559	best: 0.2116559 (3340)	total: 1m 1s	remaining: 20.5s
3360:	learn: 0.1972658	test: 0.2115786	best: 0.2115786 (3360)	total: 1m 1s	remaining: 20.2s
3380:	learn: 0.1971303	test: 0.2115183	best: 0.2115168 (3379)	total: 1m 2s	remaining: 19.8s
3400:	learn: 0.1970222	test: 0.2114759	best: 0.2114759 (3400)	total: 1m 2s	remaining: 19.4s
3420:	learn: 0.1968780	test: 0.2114136	best: 0.2114136 (3420)	total: 1m 2s	remaining: 19.1s
3440:	learn: 0.1967549	test: 0.2113618	best: 0.2113618 (3440)	total: 1m 3s	remaining: 18.7s
3460:	learn: 0.1966311	test: 0.2113396	best: 0.2113396 (3460)	total: 1m 3s	remaining: 18.4s
3480:	learn: 0.1964989	test: 0.2112819	best: 0.2112819 (3480)	total: 1m 4s	remaining: 18s
3500:	learn: 0.1963709	test: 0.2112332	best: 0.2112332 (3500)	total: 1m 4s	remaining: 17.6s
3520:	learn: 0.1962392	test: 0.2111882	best: 0.2111882 (3520)	total: 1m 4s	remaining: 17.2s
3540:	learn: 0.1961143	test: 0.2111295	best: 0.2111295 (3540)	total: 1m 5s	remaining: 16.9s
3560:	learn: 0.1960024	test: 0.2110946	best: 0.2110946 (3560)	total: 1m 5s	remaining: 16.5s
3580:	learn: 0.1958608	test: 0.2110469	best: 0.2110469 (3580)	total: 1m 5s	remaining: 16.2s
3600:	learn: 0.1957610	test: 0.2110014	best: 0.2110014 (3600)	total: 1m 6s	remaining: 15.8s
3620:	learn: 0.1956357	test: 0.2109407	best: 0.2109407 (3620)	total: 1m 6s	remaining: 15.4s
3640:	learn: 0.1955187	test: 0.2109105	best: 0.2109080 (3638)	total: 1m 6s	remaining: 15.1s
3660:	learn: 0.1954030	test: 0.2108684	best: 0.2108670 (3659)	total: 1m 7s	remaining: 14.7s
3680:	learn: 0.1952797	test: 0.2108385	best: 0.2108375 (3676)	total: 1m 7s	remaining: 14.3s
3700:	learn: 0.1951575	test: 0.2107904	best: 0.2107904 (3700)	total: 1m 8s	remaining: 13.9s
3720:	learn: 0.1950017	test: 0.2107231	best: 0.2107220 (3719)	total: 1m 8s	remaining: 13.6s
3740:	learn: 0.1948824	test: 0.2106962	best: 0.2106957 (3739)	total: 1m 8s	remaining: 13.2s
3760:	learn: 0.1947633	test: 0.2106552	best: 0.2106552 (3760)	total: 1m 9s	remaining: 12.8s
3780:	learn: 0.1946292	test: 0.2106088	best: 0.2106085 (3779)	total: 1m 9s	remaining: 12.5s
3800:	learn: 0.1944891	test: 0.2105728	best: 0.2105728 (3800)	total: 1m 9s	remaining: 12.1s
3820:	learn: 0.1943738	test: 0.2105277	best: 0.2105277 (3820)	total: 1m 10s	remaining: 11.7s
3840:	learn: 0.1942791	test: 0.2105156	best: 0.2105143 (3839)	total: 1m 10s	remaining: 11.4s
3860:	learn: 0.1941454	test: 0.2104876	best: 0.2104869 (3859)	total: 1m 11s	remaining: 11s
3880:	learn: 0.1940451	test: 0.2104641	best: 0.2104641 (3880)	total: 1m 11s	remaining: 10.6s
3900:	learn: 0.1939233	test: 0.2104093	best: 0.2104093 (3900)	total: 1m 11s	remaining: 10.3s
3920:	learn: 0.1938153	test: 0.2103561	best: 0.2103561 (3920)	total: 1m 12s	remaining: 9.91s
3940:	learn: 0.1936903	test: 0.2103093	best: 0.2103093 (3940)	total: 1m 12s	remaining: 9.54s
3960:	learn: 0.1935653	test: 0.2102500	best: 0.2102498 (3959)	total: 1m 12s	remaining: 9.17s
3980:	learn: 0.1934541	test: 0.2102067	best: 0.2102064 (3979)	total: 1m 13s	remaining: 8.81s
4000:	learn: 0.1933318	test: 0.2101853	best: 0.2101853 (4000)	total: 1m 13s	remaining: 8.44s
4020:	learn: 0.1932243	test: 0.2101445	best: 0.2101445 (4020)	total: 1m 14s	remaining: 8.07s
4040:	learn: 0.1931247	test: 0.2101173	best: 0.2101156 (4038)	total: 1m 14s	remaining: 7.7s
4060:	learn: 0.1930129	test: 0.2101001	best: 0.2100990 (4052)	total: 1m 14s	remaining: 7.33s
4080:	learn: 0.1928978	test: 0.2100606	best: 0.2100606 (4080)	total: 1m 15s	remaining: 6.97s
4100:	learn: 0.1927814	test: 0.2100291	best: 0.2100291 (4100)	total: 1m 15s	remaining: 6.6s
4120:	learn: 0.1926823	test: 0.2100044	best: 0.2100044 (4120)	total: 1m 15s	remaining: 6.23s
4140:	learn: 0.1925621	test: 0.2099738	best: 0.2099738 (4140)	total: 1m 16s	remaining: 5.86s
4160:	learn: 0.1924564	test: 0.2099319	best: 0.2099319 (4160)	total: 1m 16s	remaining: 5.5s
4180:	learn: 0.1923591	test: 0.2098934	best: 0.2098934 (4180)	total: 1m 17s	remaining: 5.13s
4200:	learn: 0.1922566	test: 0.2098644	best: 0.2098631 (4194)	total: 1m 17s	remaining: 4.76s
4220:	learn: 0.1921437	test: 0.2098397	best: 0.2098397 (4220)	total: 1m 17s	remaining: 4.39s
4240:	learn: 0.1920346	test: 0.2097981	best: 0.2097967 (4238)	total: 1m 18s	remaining: 4.02s
4260:	learn: 0.1919250	test: 0.2097693	best: 0.2097693 (4260)	total: 1m 18s	remaining: 3.65s
4280:	learn: 0.1917895	test: 0.2097052	best: 0.2097052 (4280)	total: 1m 19s	remaining: 3.29s
4300:	learn: 0.1916705	test: 0.2096733	best: 0.2096733 (4300)	total: 1m 19s	remaining: 2.92s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403954	test: 0.6405105	best: 0.6405105 (0)	total: 9.08ms	remaining: 9.08ms
1:	learn: 0.5956032	test: 0.5958550	best: 0.5958550 (1)	total: 18ms	remaining: 0us
bestTest = 0.5958550244
bestIteration = 1
0:	learn: 0.6413868	test: 0.6413772	best: 0.6413772 (0)	total: 17.8ms	remaining: 1m 37s
20:	learn: 0.3357610	test: 0.3370296	best: 0.3370296 (20)	total: 430ms	remaining: 1m 51s
40:	learn: 0.3018334	test: 0.3036474	best: 0.3036474 (40)	total: 836ms	remaining: 1m 50s
60:	learn: 0.2894257	test: 0.2911827	best: 0.2911827 (60)	total: 1.23s	remaining: 1m 49s
80:	learn: 0.2807822	test: 0.2820798	best: 0.2820798 (80)	total: 1.63s	remaining: 1m 48s
100:	learn: 0.2742035	test: 0.2755118	best: 0.2755118 (100)	total: 2.01s	remaining: 1m 47s
120:	learn: 0.2689011	test: 0.2702573	best: 0.2702573 (120)	total: 2.37s	remaining: 1m 45s
140:	learn: 0.2653866	test: 0.2667803	best: 0.2667803 (140)	total: 2.77s	remaining: 1m 44s
160:	learn: 0.2611556	test: 0.2624918	best: 0.2624918 (160)	total: 3.15s	remaining: 1m 44s
180:	learn: 0.2578186	test: 0.2591210	best: 0.2591210 (180)	total: 3.54s	remaining: 1m 43s
200:	learn: 0.2554599	test: 0.2568424	best: 0.2568424 (200)	total: 3.94s	remaining: 1m 43s
220:	learn: 0.2532688	test: 0.2547524	best: 0.2547524 (220)	total: 4.32s	remaining: 1m 42s
240:	learn: 0.2513768	test: 0.2529585	best: 0.2529585 (240)	total: 4.69s	remaining: 1m 41s
260:	learn: 0.2491237	test: 0.2506432	best: 0.2506432 (260)	total: 5.08s	remaining: 1m 41s
280:	learn: 0.2474447	test: 0.2491189	best: 0.2491189 (280)	total: 5.47s	remaining: 1m 41s
300:	learn: 0.2459796	test: 0.2477487	best: 0.2477487 (300)	total: 5.84s	remaining: 1m 40s
320:	learn: 0.2442333	test: 0.2461186	best: 0.2461186 (320)	total: 6.21s	remaining: 1m 39s
340:	learn: 0.2429344	test: 0.2449120	best: 0.2449120 (340)	total: 6.58s	remaining: 1m 39s
360:	learn: 0.2416786	test: 0.2437553	best: 0.2437553 (360)	total: 6.94s	remaining: 1m 38s
380:	learn: 0.2402639	test: 0.2423516	best: 0.2423516 (380)	total: 7.31s	remaining: 1m 37s
400:	learn: 0.2393005	test: 0.2415204	best: 0.2415204 (400)	total: 7.68s	remaining: 1m 37s
420:	learn: 0.2381061	test: 0.2404374	best: 0.2404374 (420)	total: 8.08s	remaining: 1m 37s
440:	learn: 0.2369828	test: 0.2393949	best: 0.2393949 (440)	total: 8.45s	remaining: 1m 36s
460:	learn: 0.2359433	test: 0.2384711	best: 0.2384711 (460)	total: 8.82s	remaining: 1m 36s
480:	learn: 0.2349004	test: 0.2375306	best: 0.2375306 (480)	total: 9.19s	remaining: 1m 35s
500:	learn: 0.2341254	test: 0.2368584	best: 0.2368584 (500)	total: 9.55s	remaining: 1m 34s
520:	learn: 0.2333666	test: 0.2362699	best: 0.2362699 (520)	total: 9.91s	remaining: 1m 34s
540:	learn: 0.2325511	test: 0.2355504	best: 0.2355504 (540)	total: 10.3s	remaining: 1m 33s
560:	learn: 0.2316906	test: 0.2347928	best: 0.2347928 (560)	total: 10.6s	remaining: 1m 33s
580:	learn: 0.2310617	test: 0.2342640	best: 0.2342640 (580)	total: 11s	remaining: 1m 32s
600:	learn: 0.2303237	test: 0.2336027	best: 0.2336027 (600)	total: 11.3s	remaining: 1m 32s
620:	learn: 0.2297163	test: 0.2331291	best: 0.2331291 (620)	total: 11.7s	remaining: 1m 31s
640:	learn: 0.2290864	test: 0.2326402	best: 0.2326402 (640)	total: 12.1s	remaining: 1m 31s
660:	learn: 0.2282793	test: 0.2318905	best: 0.2318905 (660)	total: 12.4s	remaining: 1m 30s
680:	learn: 0.2276372	test: 0.2313511	best: 0.2313511 (680)	total: 12.8s	remaining: 1m 30s
700:	learn: 0.2270928	test: 0.2309285	best: 0.2309285 (700)	total: 13.2s	remaining: 1m 29s
720:	learn: 0.2265188	test: 0.2304955	best: 0.2304955 (720)	total: 13.5s	remaining: 1m 29s
740:	learn: 0.2259705	test: 0.2300662	best: 0.2300662 (740)	total: 13.9s	remaining: 1m 28s
760:	learn: 0.2254949	test: 0.2296716	best: 0.2296716 (760)	total: 14.3s	remaining: 1m 28s
780:	learn: 0.2248888	test: 0.2291501	best: 0.2291501 (780)	total: 14.7s	remaining: 1m 28s
800:	learn: 0.2245088	test: 0.2289061	best: 0.2289061 (800)	total: 15s	remaining: 1m 27s
820:	learn: 0.2240378	test: 0.2285449	best: 0.2285449 (820)	total: 15.4s	remaining: 1m 27s
840:	learn: 0.2234508	test: 0.2280206	best: 0.2280206 (840)	total: 15.7s	remaining: 1m 26s
860:	learn: 0.2230277	test: 0.2276975	best: 0.2276975 (860)	total: 16.1s	remaining: 1m 26s
880:	learn: 0.2224338	test: 0.2271871	best: 0.2271871 (880)	total: 16.5s	remaining: 1m 26s
900:	learn: 0.2221093	test: 0.2269495	best: 0.2269495 (900)	total: 16.9s	remaining: 1m 25s
920:	learn: 0.2216844	test: 0.2266263	best: 0.2266263 (920)	total: 17.2s	remaining: 1m 25s
940:	learn: 0.2213579	test: 0.2264040	best: 0.2264040 (940)	total: 17.6s	remaining: 1m 24s
960:	learn: 0.2210471	test: 0.2262102	best: 0.2262102 (960)	total: 17.9s	remaining: 1m 24s
980:	learn: 0.2206628	test: 0.2259301	best: 0.2259301 (980)	total: 18.3s	remaining: 1m 23s
1000:	learn: 0.2203020	test: 0.2257017	best: 0.2257017 (1000)	total: 18.6s	remaining: 1m 23s
1020:	learn: 0.2199372	test: 0.2254284	best: 0.2254284 (1020)	total: 19s	remaining: 1m 22s
1040:	learn: 0.2195818	test: 0.2251803	best: 0.2251803 (1040)	total: 19.4s	remaining: 1m 22s
1060:	learn: 0.2192071	test: 0.2249202	best: 0.2249202 (1060)	total: 19.7s	remaining: 1m 22s
1080:	learn: 0.2188264	test: 0.2246408	best: 0.2246408 (1080)	total: 20.1s	remaining: 1m 21s
1100:	learn: 0.2184749	test: 0.2243801	best: 0.2243801 (1100)	total: 20.4s	remaining: 1m 21s
1120:	learn: 0.2180819	test: 0.2240861	best: 0.2240861 (1120)	total: 20.8s	remaining: 1m 20s
1140:	learn: 0.2177764	test: 0.2239027	best: 0.2239027 (1140)	total: 21.2s	remaining: 1m 20s
1160:	learn: 0.2174711	test: 0.2237091	best: 0.2237091 (1160)	total: 21.5s	remaining: 1m 20s
1180:	learn: 0.2171801	test: 0.2235349	best: 0.2235349 (1180)	total: 21.9s	remaining: 1m 19s
1200:	learn: 0.2168480	test: 0.2233328	best: 0.2233328 (1200)	total: 22.2s	remaining: 1m 19s
1220:	learn: 0.2165315	test: 0.2231428	best: 0.2231428 (1220)	total: 22.6s	remaining: 1m 18s
1240:	learn: 0.2162734	test: 0.2229823	best: 0.2229823 (1240)	total: 23s	remaining: 1m 18s
1260:	learn: 0.2159483	test: 0.2227466	best: 0.2227466 (1260)	total: 23.3s	remaining: 1m 18s
1280:	learn: 0.2156647	test: 0.2225798	best: 0.2225791 (1279)	total: 23.7s	remaining: 1m 17s
1300:	learn: 0.2153445	test: 0.2223817	best: 0.2223817 (1300)	total: 24.1s	remaining: 1m 17s
1320:	learn: 0.2150725	test: 0.2222304	best: 0.2222304 (1320)	total: 24.4s	remaining: 1m 16s
1340:	learn: 0.2147169	test: 0.2219927	best: 0.2219927 (1340)	total: 24.8s	remaining: 1m 16s
1360:	learn: 0.2144556	test: 0.2218011	best: 0.2218011 (1360)	total: 25.1s	remaining: 1m 16s
1380:	learn: 0.2142037	test: 0.2216503	best: 0.2216503 (1380)	total: 25.5s	remaining: 1m 15s
1400:	learn: 0.2139102	test: 0.2214721	best: 0.2214721 (1400)	total: 25.9s	remaining: 1m 15s
1420:	learn: 0.2136012	test: 0.2212838	best: 0.2212838 (1420)	total: 26.2s	remaining: 1m 14s
1440:	learn: 0.2133451	test: 0.2211238	best: 0.2211238 (1440)	total: 26.6s	remaining: 1m 14s
1460:	learn: 0.2131352	test: 0.2209945	best: 0.2209945 (1460)	total: 26.9s	remaining: 1m 14s
1480:	learn: 0.2129004	test: 0.2208624	best: 0.2208624 (1480)	total: 27.3s	remaining: 1m 13s
1500:	learn: 0.2126459	test: 0.2206993	best: 0.2206993 (1500)	total: 27.7s	remaining: 1m 13s
1520:	learn: 0.2124176	test: 0.2205627	best: 0.2205627 (1520)	total: 28s	remaining: 1m 12s
1540:	learn: 0.2121840	test: 0.2204582	best: 0.2204582 (1540)	total: 28.4s	remaining: 1m 12s
1560:	learn: 0.2119551	test: 0.2203516	best: 0.2203516 (1560)	total: 28.8s	remaining: 1m 12s
1580:	learn: 0.2116964	test: 0.2201742	best: 0.2201742 (1580)	total: 29.1s	remaining: 1m 11s
1600:	learn: 0.2114389	test: 0.2200224	best: 0.2200224 (1600)	total: 29.5s	remaining: 1m 11s
1620:	learn: 0.2111894	test: 0.2198661	best: 0.2198653 (1619)	total: 29.9s	remaining: 1m 11s
1640:	learn: 0.2109866	test: 0.2197555	best: 0.2197555 (1640)	total: 30.2s	remaining: 1m 10s
1660:	learn: 0.2107306	test: 0.2195982	best: 0.2195982 (1660)	total: 30.6s	remaining: 1m 10s
1680:	learn: 0.2105212	test: 0.2195068	best: 0.2195068 (1680)	total: 31s	remaining: 1m 9s
1700:	learn: 0.2103092	test: 0.2193762	best: 0.2193762 (1700)	total: 31.3s	remaining: 1m 9s
1720:	learn: 0.2100687	test: 0.2192159	best: 0.2192159 (1720)	total: 31.7s	remaining: 1m 9s
1740:	learn: 0.2098721	test: 0.2191132	best: 0.2191132 (1740)	total: 32.1s	remaining: 1m 8s
1760:	learn: 0.2096855	test: 0.2190237	best: 0.2190237 (1760)	total: 32.5s	remaining: 1m 8s
1780:	learn: 0.2094841	test: 0.2188975	best: 0.2188975 (1780)	total: 32.8s	remaining: 1m 8s
1800:	learn: 0.2092739	test: 0.2187617	best: 0.2187617 (1800)	total: 33.2s	remaining: 1m 7s
1820:	learn: 0.2090946	test: 0.2187083	best: 0.2187046 (1818)	total: 33.6s	remaining: 1m 7s
1840:	learn: 0.2088852	test: 0.2185831	best: 0.2185831 (1840)	total: 33.9s	remaining: 1m 7s
1860:	learn: 0.2086885	test: 0.2185027	best: 0.2185027 (1860)	total: 34.3s	remaining: 1m 6s
1880:	learn: 0.2085097	test: 0.2184312	best: 0.2184312 (1880)	total: 34.7s	remaining: 1m 6s
1900:	learn: 0.2083225	test: 0.2183306	best: 0.2183306 (1900)	total: 35.1s	remaining: 1m 5s
1920:	learn: 0.2081203	test: 0.2182341	best: 0.2182341 (1920)	total: 35.4s	remaining: 1m 5s
1940:	learn: 0.2079351	test: 0.2181479	best: 0.2181479 (1940)	total: 35.8s	remaining: 1m 5s
1960:	learn: 0.2077190	test: 0.2180222	best: 0.2180222 (1960)	total: 36.2s	remaining: 1m 4s
1980:	learn: 0.2075284	test: 0.2179213	best: 0.2179213 (1980)	total: 36.6s	remaining: 1m 4s
2000:	learn: 0.2073655	test: 0.2178545	best: 0.2178514 (1999)	total: 36.9s	remaining: 1m 4s
2020:	learn: 0.2071857	test: 0.2177605	best: 0.2177605 (2020)	total: 37.3s	remaining: 1m 3s
2040:	learn: 0.2069882	test: 0.2176653	best: 0.2176653 (2040)	total: 37.7s	remaining: 1m 3s
2060:	learn: 0.2067442	test: 0.2175121	best: 0.2175121 (2060)	total: 38s	remaining: 1m 3s
2080:	learn: 0.2065484	test: 0.2173907	best: 0.2173907 (2080)	total: 38.4s	remaining: 1m 2s
2100:	learn: 0.2063556	test: 0.2172969	best: 0.2172969 (2100)	total: 38.8s	remaining: 1m 2s
2120:	learn: 0.2061646	test: 0.2171906	best: 0.2171906 (2120)	total: 39.2s	remaining: 1m 1s
2140:	learn: 0.2059944	test: 0.2171268	best: 0.2171268 (2140)	total: 39.5s	remaining: 1m 1s
2160:	learn: 0.2058189	test: 0.2170568	best: 0.2170568 (2160)	total: 39.9s	remaining: 1m 1s
2180:	learn: 0.2056412	test: 0.2169666	best: 0.2169666 (2180)	total: 40.3s	remaining: 1m
2200:	learn: 0.2054790	test: 0.2169021	best: 0.2169020 (2199)	total: 40.6s	remaining: 1m
2220:	learn: 0.2052959	test: 0.2168359	best: 0.2168359 (2220)	total: 41s	remaining: 1m
2240:	learn: 0.2051432	test: 0.2167822	best: 0.2167822 (2240)	total: 41.4s	remaining: 59.8s
2260:	learn: 0.2049961	test: 0.2167253	best: 0.2167253 (2260)	total: 41.8s	remaining: 59.5s
2280:	learn: 0.2048414	test: 0.2166497	best: 0.2166497 (2280)	total: 42.2s	remaining: 59.1s
2300:	learn: 0.2046658	test: 0.2165691	best: 0.2165691 (2300)	total: 42.6s	remaining: 58.8s
2320:	learn: 0.2044688	test: 0.2164952	best: 0.2164952 (2320)	total: 42.9s	remaining: 58.4s
2340:	learn: 0.2043130	test: 0.2164376	best: 0.2164376 (2340)	total: 43.3s	remaining: 58.1s
2360:	learn: 0.2041204	test: 0.2163144	best: 0.2163144 (2360)	total: 43.7s	remaining: 57.7s
2380:	learn: 0.2039210	test: 0.2162257	best: 0.2162257 (2380)	total: 44.1s	remaining: 57.4s
2400:	learn: 0.2037570	test: 0.2161440	best: 0.2161440 (2400)	total: 44.5s	remaining: 57s
2420:	learn: 0.2035972	test: 0.2160737	best: 0.2160737 (2420)	total: 44.8s	remaining: 56.6s
2440:	learn: 0.2034508	test: 0.2160223	best: 0.2160223 (2440)	total: 45.2s	remaining: 56.3s
2460:	learn: 0.2032860	test: 0.2159523	best: 0.2159523 (2460)	total: 45.6s	remaining: 55.9s
2480:	learn: 0.2030964	test: 0.2158637	best: 0.2158637 (2480)	total: 45.9s	remaining: 55.5s
2500:	learn: 0.2029199	test: 0.2157860	best: 0.2157860 (2500)	total: 46.3s	remaining: 55.1s
2520:	learn: 0.2027309	test: 0.2156626	best: 0.2156626 (2520)	total: 46.7s	remaining: 54.7s
2540:	learn: 0.2025836	test: 0.2155942	best: 0.2155942 (2540)	total: 47s	remaining: 54.4s
2560:	learn: 0.2024498	test: 0.2155329	best: 0.2155329 (2560)	total: 47.4s	remaining: 54s
2580:	learn: 0.2022866	test: 0.2154695	best: 0.2154695 (2580)	total: 47.8s	remaining: 53.6s
2600:	learn: 0.2021199	test: 0.2153992	best: 0.2153992 (2600)	total: 48.1s	remaining: 53.3s
2620:	learn: 0.2019697	test: 0.2153353	best: 0.2153353 (2620)	total: 48.5s	remaining: 52.9s
2640:	learn: 0.2018167	test: 0.2152792	best: 0.2152792 (2640)	total: 48.9s	remaining: 52.5s
2660:	learn: 0.2016654	test: 0.2152401	best: 0.2152382 (2658)	total: 49.2s	remaining: 52.1s
2680:	learn: 0.2015230	test: 0.2151934	best: 0.2151934 (2680)	total: 49.6s	remaining: 51.8s
2700:	learn: 0.2013913	test: 0.2151264	best: 0.2151240 (2699)	total: 50s	remaining: 51.4s
2720:	learn: 0.2012674	test: 0.2150926	best: 0.2150926 (2720)	total: 50.4s	remaining: 51s
2740:	learn: 0.2011053	test: 0.2150356	best: 0.2150356 (2740)	total: 50.7s	remaining: 50.7s
2760:	learn: 0.2009567	test: 0.2149720	best: 0.2149720 (2760)	total: 51.1s	remaining: 50.3s
2780:	learn: 0.2007635	test: 0.2148684	best: 0.2148684 (2780)	total: 51.5s	remaining: 49.9s
2800:	learn: 0.2006232	test: 0.2147963	best: 0.2147962 (2799)	total: 51.9s	remaining: 49.6s
2820:	learn: 0.2004944	test: 0.2147616	best: 0.2147616 (2820)	total: 52.2s	remaining: 49.2s
2840:	learn: 0.2003560	test: 0.2147103	best: 0.2147103 (2840)	total: 52.6s	remaining: 48.8s
2860:	learn: 0.2001976	test: 0.2146097	best: 0.2146094 (2859)	total: 53s	remaining: 48.5s
2880:	learn: 0.2000494	test: 0.2145446	best: 0.2145446 (2880)	total: 53.3s	remaining: 48.1s
2900:	learn: 0.1998842	test: 0.2144502	best: 0.2144502 (2900)	total: 53.7s	remaining: 47.7s
2920:	learn: 0.1997183	test: 0.2143709	best: 0.2143709 (2920)	total: 54.1s	remaining: 47.4s
2940:	learn: 0.1995713	test: 0.2143062	best: 0.2143062 (2940)	total: 54.5s	remaining: 47s
2960:	learn: 0.1994170	test: 0.2142245	best: 0.2142245 (2960)	total: 54.8s	remaining: 46.6s
2980:	learn: 0.1992925	test: 0.2141841	best: 0.2141841 (2980)	total: 55.2s	remaining: 46.3s
3000:	learn: 0.1991464	test: 0.2141242	best: 0.2141242 (3000)	total: 55.6s	remaining: 45.9s
3020:	learn: 0.1990179	test: 0.2140705	best: 0.2140687 (3019)	total: 56s	remaining: 45.5s
3040:	learn: 0.1988910	test: 0.2140122	best: 0.2140122 (3040)	total: 56.4s	remaining: 45.2s
3060:	learn: 0.1987625	test: 0.2139724	best: 0.2139724 (3060)	total: 56.7s	remaining: 44.8s
3080:	learn: 0.1986426	test: 0.2139466	best: 0.2139452 (3079)	total: 57.1s	remaining: 44.4s
3100:	learn: 0.1985025	test: 0.2139147	best: 0.2139137 (3092)	total: 57.5s	remaining: 44.1s
3120:	learn: 0.1983598	test: 0.2138643	best: 0.2138643 (3120)	total: 57.8s	remaining: 43.7s
3140:	learn: 0.1982448	test: 0.2138366	best: 0.2138366 (3140)	total: 58.2s	remaining: 43.3s
3160:	learn: 0.1981183	test: 0.2138119	best: 0.2138119 (3160)	total: 58.6s	remaining: 43s
3180:	learn: 0.1979724	test: 0.2137523	best: 0.2137523 (3180)	total: 59s	remaining: 42.6s
3200:	learn: 0.1978410	test: 0.2137086	best: 0.2137046 (3199)	total: 59.3s	remaining: 42.2s
3220:	learn: 0.1976984	test: 0.2136604	best: 0.2136575 (3219)	total: 59.7s	remaining: 41.8s
3240:	learn: 0.1975621	test: 0.2136292	best: 0.2136265 (3235)	total: 1m	remaining: 41.5s
3260:	learn: 0.1974384	test: 0.2135802	best: 0.2135801 (3258)	total: 1m	remaining: 41.1s
3280:	learn: 0.1973139	test: 0.2135453	best: 0.2135453 (3280)	total: 1m	remaining: 40.8s
3300:	learn: 0.1971995	test: 0.2135053	best: 0.2135053 (3300)	total: 1m 1s	remaining: 40.4s
3320:	learn: 0.1970764	test: 0.2134791	best: 0.2134789 (3319)	total: 1m 1s	remaining: 40s
3340:	learn: 0.1969623	test: 0.2134674	best: 0.2134656 (3338)	total: 1m 1s	remaining: 39.6s
3360:	learn: 0.1968189	test: 0.2134488	best: 0.2134446 (3353)	total: 1m 2s	remaining: 39.3s
3380:	learn: 0.1967071	test: 0.2134239	best: 0.2134230 (3378)	total: 1m 2s	remaining: 38.9s
3400:	learn: 0.1965827	test: 0.2133724	best: 0.2133724 (3400)	total: 1m 3s	remaining: 38.5s
3420:	learn: 0.1964747	test: 0.2133557	best: 0.2133557 (3420)	total: 1m 3s	remaining: 38.1s
3440:	learn: 0.1963577	test: 0.2133133	best: 0.2133133 (3440)	total: 1m 3s	remaining: 37.8s
3460:	learn: 0.1962461	test: 0.2132906	best: 0.2132893 (3456)	total: 1m 4s	remaining: 37.4s
3480:	learn: 0.1961073	test: 0.2132236	best: 0.2132236 (3480)	total: 1m 4s	remaining: 37.1s
3500:	learn: 0.1959914	test: 0.2131902	best: 0.2131886 (3499)	total: 1m 4s	remaining: 36.7s
3520:	learn: 0.1958728	test: 0.2131551	best: 0.2131551 (3520)	total: 1m 5s	remaining: 36.3s
3540:	learn: 0.1957453	test: 0.2131309	best: 0.2131309 (3540)	total: 1m 5s	remaining: 36s
3560:	learn: 0.1956254	test: 0.2130912	best: 0.2130912 (3560)	total: 1m 6s	remaining: 35.6s
3580:	learn: 0.1955073	test: 0.2130342	best: 0.2130342 (3580)	total: 1m 6s	remaining: 35.2s
3600:	learn: 0.1953586	test: 0.2129752	best: 0.2129752 (3600)	total: 1m 6s	remaining: 34.8s
3620:	learn: 0.1952283	test: 0.2129444	best: 0.2129444 (3620)	total: 1m 7s	remaining: 34.5s
3640:	learn: 0.1951115	test: 0.2129201	best: 0.2129172 (3633)	total: 1m 7s	remaining: 34.1s
3660:	learn: 0.1950019	test: 0.2128831	best: 0.2128831 (3660)	total: 1m 7s	remaining: 33.7s
3680:	learn: 0.1948793	test: 0.2128516	best: 0.2128516 (3680)	total: 1m 8s	remaining: 33.4s
3700:	learn: 0.1947410	test: 0.2128005	best: 0.2128002 (3699)	total: 1m 8s	remaining: 33s
3720:	learn: 0.1946399	test: 0.2127697	best: 0.2127697 (3720)	total: 1m 9s	remaining: 32.6s
3740:	learn: 0.1944998	test: 0.2127159	best: 0.2127159 (3740)	total: 1m 9s	remaining: 32.2s
3760:	learn: 0.1944008	test: 0.2126854	best: 0.2126854 (3760)	total: 1m 9s	remaining: 31.9s
3780:	learn: 0.1942743	test: 0.2126627	best: 0.2126627 (3780)	total: 1m 10s	remaining: 31.5s
3800:	learn: 0.1941381	test: 0.2125909	best: 0.2125909 (3800)	total: 1m 10s	remaining: 31.1s
3820:	learn: 0.1940196	test: 0.2125589	best: 0.2125561 (3818)	total: 1m 10s	remaining: 30.8s
3840:	learn: 0.1938999	test: 0.2125228	best: 0.2125228 (3840)	total: 1m 11s	remaining: 30.4s
3860:	learn: 0.1937519	test: 0.2124572	best: 0.2124572 (3860)	total: 1m 11s	remaining: 30s
3880:	learn: 0.1936179	test: 0.2124085	best: 0.2124058 (3875)	total: 1m 12s	remaining: 29.7s
3900:	learn: 0.1934969	test: 0.2123514	best: 0.2123514 (3900)	total: 1m 12s	remaining: 29.3s
3920:	learn: 0.1933751	test: 0.2123175	best: 0.2123175 (3920)	total: 1m 12s	remaining: 28.9s
3940:	learn: 0.1932646	test: 0.2122864	best: 0.2122856 (3939)	total: 1m 13s	remaining: 28.6s
3960:	learn: 0.1931348	test: 0.2122581	best: 0.2122544 (3952)	total: 1m 13s	remaining: 28.2s
3980:	learn: 0.1930077	test: 0.2122228	best: 0.2122228 (3980)	total: 1m 13s	remaining: 27.8s
4000:	learn: 0.1928888	test: 0.2121883	best: 0.2121883 (4000)	total: 1m 14s	remaining: 27.5s
4020:	learn: 0.1927695	test: 0.2121423	best: 0.2121423 (4020)	total: 1m 14s	remaining: 27.1s
4040:	learn: 0.1926464	test: 0.2121167	best: 0.2121167 (4040)	total: 1m 15s	remaining: 26.7s
4060:	learn: 0.1925310	test: 0.2121040	best: 0.2121040 (4060)	total: 1m 15s	remaining: 26.3s
4080:	learn: 0.1924071	test: 0.2120512	best: 0.2120512 (4080)	total: 1m 15s	remaining: 26s
4100:	learn: 0.1922840	test: 0.2120129	best: 0.2120129 (4100)	total: 1m 16s	remaining: 25.6s
4120:	learn: 0.1921832	test: 0.2119724	best: 0.2119724 (4120)	total: 1m 16s	remaining: 25.2s
4140:	learn: 0.1920727	test: 0.2119338	best: 0.2119338 (4140)	total: 1m 16s	remaining: 24.9s
4160:	learn: 0.1919489	test: 0.2119032	best: 0.2119032 (4160)	total: 1m 17s	remaining: 24.5s
4180:	learn: 0.1918319	test: 0.2118717	best: 0.2118717 (4180)	total: 1m 17s	remaining: 24.1s
4200:	learn: 0.1917056	test: 0.2118420	best: 0.2118420 (4200)	total: 1m 18s	remaining: 23.8s
4220:	learn: 0.1915930	test: 0.2118160	best: 0.2118160 (4220)	total: 1m 18s	remaining: 23.4s
4240:	learn: 0.1914778	test: 0.2118070	best: 0.2118070 (4240)	total: 1m 18s	remaining: 23s
4260:	learn: 0.1913692	test: 0.2117761	best: 0.2117761 (4260)	total: 1m 19s	remaining: 22.7s
4280:	learn: 0.1912601	test: 0.2117284	best: 0.2117284 (4280)	total: 1m 19s	remaining: 22.3s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404918	test: 0.6404277	best: 0.6404277 (0)	total: 9.27ms	remaining: 9.27ms
1:	learn: 0.5956907	test: 0.5955782	best: 0.5955782 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.5955781708
bestIteration = 1
0:	learn: 0.6414934	test: 0.6414190	best: 0.6414190 (0)	total: 17.1ms	remaining: 1m 32s
20:	learn: 0.3369749	test: 0.3362004	best: 0.3362004 (20)	total: 405ms	remaining: 1m 44s
40:	learn: 0.3041411	test: 0.3034035	best: 0.3034035 (40)	total: 817ms	remaining: 1m 47s
60:	learn: 0.2895538	test: 0.2883817	best: 0.2883817 (60)	total: 1.21s	remaining: 1m 46s
80:	learn: 0.2812320	test: 0.2801284	best: 0.2801284 (80)	total: 1.58s	remaining: 1m 44s
100:	learn: 0.2758822	test: 0.2746166	best: 0.2746166 (100)	total: 1.98s	remaining: 1m 44s
120:	learn: 0.2709859	test: 0.2696579	best: 0.2696579 (120)	total: 2.37s	remaining: 1m 43s
140:	learn: 0.2671017	test: 0.2657993	best: 0.2657993 (140)	total: 2.75s	remaining: 1m 42s
160:	learn: 0.2638928	test: 0.2627191	best: 0.2627191 (160)	total: 3.14s	remaining: 1m 42s
180:	learn: 0.2601932	test: 0.2588411	best: 0.2588411 (180)	total: 3.51s	remaining: 1m 41s
200:	learn: 0.2569951	test: 0.2556460	best: 0.2556460 (200)	total: 3.89s	remaining: 1m 41s
220:	learn: 0.2542156	test: 0.2527037	best: 0.2527037 (220)	total: 4.28s	remaining: 1m 40s
240:	learn: 0.2522326	test: 0.2507611	best: 0.2507611 (240)	total: 4.64s	remaining: 1m 39s
260:	learn: 0.2503789	test: 0.2487887	best: 0.2487887 (260)	total: 5.02s	remaining: 1m 39s
280:	learn: 0.2484499	test: 0.2469764	best: 0.2469764 (280)	total: 5.39s	remaining: 1m 38s
300:	learn: 0.2467968	test: 0.2453508	best: 0.2453508 (300)	total: 5.76s	remaining: 1m 38s
320:	learn: 0.2453796	test: 0.2439766	best: 0.2439766 (320)	total: 6.14s	remaining: 1m 37s
340:	learn: 0.2439525	test: 0.2426810	best: 0.2426810 (340)	total: 6.51s	remaining: 1m 37s
360:	learn: 0.2425353	test: 0.2412438	best: 0.2412438 (360)	total: 6.89s	remaining: 1m 36s
380:	learn: 0.2414040	test: 0.2402466	best: 0.2402466 (380)	total: 7.25s	remaining: 1m 36s
400:	learn: 0.2404215	test: 0.2393531	best: 0.2393531 (400)	total: 7.62s	remaining: 1m 35s
420:	learn: 0.2391528	test: 0.2380867	best: 0.2380867 (420)	total: 8s	remaining: 1m 35s
440:	learn: 0.2380753	test: 0.2370648	best: 0.2370648 (440)	total: 8.37s	remaining: 1m 34s
460:	learn: 0.2371334	test: 0.2362540	best: 0.2362540 (460)	total: 8.73s	remaining: 1m 34s
480:	learn: 0.2361311	test: 0.2353716	best: 0.2353716 (480)	total: 9.1s	remaining: 1m 33s
500:	learn: 0.2350709	test: 0.2343604	best: 0.2343604 (500)	total: 9.47s	remaining: 1m 33s
520:	learn: 0.2342543	test: 0.2335940	best: 0.2335940 (520)	total: 9.84s	remaining: 1m 32s
540:	learn: 0.2335249	test: 0.2329685	best: 0.2329685 (540)	total: 10.2s	remaining: 1m 32s
560:	learn: 0.2328071	test: 0.2323612	best: 0.2323612 (560)	total: 10.6s	remaining: 1m 31s
580:	learn: 0.2320103	test: 0.2316693	best: 0.2316693 (580)	total: 10.9s	remaining: 1m 31s
600:	learn: 0.2314598	test: 0.2312346	best: 0.2312346 (600)	total: 11.3s	remaining: 1m 30s
620:	learn: 0.2306737	test: 0.2305738	best: 0.2305738 (620)	total: 11.6s	remaining: 1m 30s
640:	learn: 0.2300637	test: 0.2300664	best: 0.2300664 (640)	total: 12s	remaining: 1m 29s
660:	learn: 0.2295119	test: 0.2296375	best: 0.2296375 (660)	total: 12.4s	remaining: 1m 29s
680:	learn: 0.2289098	test: 0.2291829	best: 0.2291829 (680)	total: 12.7s	remaining: 1m 28s
700:	learn: 0.2283666	test: 0.2287616	best: 0.2287616 (700)	total: 13.1s	remaining: 1m 28s
720:	learn: 0.2277244	test: 0.2281794	best: 0.2281794 (720)	total: 13.5s	remaining: 1m 27s
740:	learn: 0.2270723	test: 0.2276010	best: 0.2276010 (740)	total: 13.8s	remaining: 1m 27s
760:	learn: 0.2264159	test: 0.2270523	best: 0.2270523 (760)	total: 14.2s	remaining: 1m 26s
780:	learn: 0.2258951	test: 0.2266174	best: 0.2266174 (780)	total: 14.5s	remaining: 1m 26s
800:	learn: 0.2252224	test: 0.2260215	best: 0.2260215 (800)	total: 14.9s	remaining: 1m 26s
820:	learn: 0.2246981	test: 0.2255954	best: 0.2255954 (820)	total: 15.3s	remaining: 1m 25s
840:	learn: 0.2241651	test: 0.2251514	best: 0.2251514 (840)	total: 15.6s	remaining: 1m 25s
860:	learn: 0.2237209	test: 0.2248059	best: 0.2248059 (860)	total: 16s	remaining: 1m 24s
880:	learn: 0.2232913	test: 0.2244650	best: 0.2244650 (880)	total: 16.4s	remaining: 1m 24s
900:	learn: 0.2227990	test: 0.2240939	best: 0.2240939 (900)	total: 16.7s	remaining: 1m 24s
920:	learn: 0.2224334	test: 0.2238407	best: 0.2238407 (920)	total: 17.1s	remaining: 1m 23s
940:	learn: 0.2219587	test: 0.2234782	best: 0.2234782 (940)	total: 17.4s	remaining: 1m 23s
960:	learn: 0.2215659	test: 0.2231930	best: 0.2231930 (960)	total: 17.8s	remaining: 1m 22s
980:	learn: 0.2211688	test: 0.2229664	best: 0.2229664 (980)	total: 18.1s	remaining: 1m 22s
1000:	learn: 0.2207457	test: 0.2226627	best: 0.2226627 (1000)	total: 18.5s	remaining: 1m 21s
1020:	learn: 0.2203306	test: 0.2223428	best: 0.2223428 (1020)	total: 18.9s	remaining: 1m 21s
1040:	learn: 0.2199717	test: 0.2221072	best: 0.2221072 (1040)	total: 19.2s	remaining: 1m 20s
1060:	learn: 0.2195566	test: 0.2217739	best: 0.2217739 (1060)	total: 19.6s	remaining: 1m 20s
1080:	learn: 0.2192168	test: 0.2215236	best: 0.2215236 (1080)	total: 19.9s	remaining: 1m 20s
1100:	learn: 0.2188759	test: 0.2212578	best: 0.2212578 (1100)	total: 20.3s	remaining: 1m 19s
1120:	learn: 0.2184394	test: 0.2208966	best: 0.2208966 (1120)	total: 20.7s	remaining: 1m 19s
1140:	learn: 0.2181027	test: 0.2206855	best: 0.2206855 (1140)	total: 21s	remaining: 1m 18s
1160:	learn: 0.2177219	test: 0.2204225	best: 0.2204225 (1160)	total: 21.4s	remaining: 1m 18s
1180:	learn: 0.2174581	test: 0.2202478	best: 0.2202478 (1180)	total: 21.7s	remaining: 1m 18s
1200:	learn: 0.2171697	test: 0.2200657	best: 0.2200657 (1200)	total: 22.1s	remaining: 1m 17s
1220:	learn: 0.2168317	test: 0.2198573	best: 0.2198573 (1220)	total: 22.5s	remaining: 1m 17s
1240:	learn: 0.2164931	test: 0.2196026	best: 0.2196026 (1240)	total: 22.8s	remaining: 1m 16s
1260:	learn: 0.2162518	test: 0.2194520	best: 0.2194520 (1260)	total: 23.2s	remaining: 1m 16s
1280:	learn: 0.2160024	test: 0.2193111	best: 0.2193111 (1280)	total: 23.6s	remaining: 1m 16s
1300:	learn: 0.2157223	test: 0.2191414	best: 0.2191414 (1300)	total: 23.9s	remaining: 1m 15s
1320:	learn: 0.2154689	test: 0.2189712	best: 0.2189712 (1320)	total: 24.3s	remaining: 1m 15s
1340:	learn: 0.2152193	test: 0.2188241	best: 0.2188241 (1340)	total: 24.6s	remaining: 1m 15s
1360:	learn: 0.2149236	test: 0.2186612	best: 0.2186612 (1360)	total: 25s	remaining: 1m 14s
1380:	learn: 0.2146915	test: 0.2185559	best: 0.2185559 (1380)	total: 25.4s	remaining: 1m 14s
1400:	learn: 0.2144002	test: 0.2183995	best: 0.2183995 (1400)	total: 25.7s	remaining: 1m 13s
1420:	learn: 0.2141814	test: 0.2182992	best: 0.2182992 (1420)	total: 26.1s	remaining: 1m 13s
1440:	learn: 0.2139607	test: 0.2181682	best: 0.2181682 (1440)	total: 26.4s	remaining: 1m 13s
1460:	learn: 0.2136895	test: 0.2179993	best: 0.2179993 (1460)	total: 26.8s	remaining: 1m 12s
1480:	learn: 0.2134523	test: 0.2178744	best: 0.2178744 (1480)	total: 27.2s	remaining: 1m 12s
1500:	learn: 0.2131886	test: 0.2177098	best: 0.2177098 (1500)	total: 27.5s	remaining: 1m 12s
1520:	learn: 0.2129347	test: 0.2175659	best: 0.2175659 (1520)	total: 27.9s	remaining: 1m 11s
1540:	learn: 0.2126610	test: 0.2173708	best: 0.2173708 (1540)	total: 28.3s	remaining: 1m 11s
1560:	learn: 0.2123829	test: 0.2171818	best: 0.2171818 (1560)	total: 28.6s	remaining: 1m 10s
1580:	learn: 0.2121741	test: 0.2170516	best: 0.2170516 (1580)	total: 29s	remaining: 1m 10s
1600:	learn: 0.2119449	test: 0.2169026	best: 0.2169026 (1600)	total: 29.3s	remaining: 1m 10s
1620:	learn: 0.2117112	test: 0.2167816	best: 0.2167816 (1620)	total: 29.7s	remaining: 1m 9s
1640:	learn: 0.2115254	test: 0.2166771	best: 0.2166771 (1640)	total: 30.1s	remaining: 1m 9s
1660:	learn: 0.2112835	test: 0.2165357	best: 0.2165357 (1660)	total: 30.4s	remaining: 1m 9s
1680:	learn: 0.2110596	test: 0.2164096	best: 0.2164096 (1680)	total: 30.8s	remaining: 1m 8s
1700:	learn: 0.2107871	test: 0.2162551	best: 0.2162551 (1700)	total: 31.2s	remaining: 1m 8s
1720:	learn: 0.2105626	test: 0.2161022	best: 0.2161022 (1720)	total: 31.5s	remaining: 1m 7s
1740:	learn: 0.2103149	test: 0.2159302	best: 0.2159302 (1740)	total: 31.9s	remaining: 1m 7s
1760:	learn: 0.2100906	test: 0.2158505	best: 0.2158505 (1760)	total: 32.3s	remaining: 1m 7s
1780:	learn: 0.2098836	test: 0.2157545	best: 0.2157545 (1780)	total: 32.6s	remaining: 1m 6s
1800:	learn: 0.2096808	test: 0.2156307	best: 0.2156307 (1800)	total: 33s	remaining: 1m 6s
1820:	learn: 0.2094363	test: 0.2154703	best: 0.2154703 (1820)	total: 33.4s	remaining: 1m 6s
1840:	learn: 0.2092110	test: 0.2153434	best: 0.2153434 (1840)	total: 33.7s	remaining: 1m 5s
1860:	learn: 0.2090122	test: 0.2152483	best: 0.2152483 (1860)	total: 34.1s	remaining: 1m 5s
1880:	learn: 0.2088234	test: 0.2151550	best: 0.2151550 (1880)	total: 34.4s	remaining: 1m 4s
1900:	learn: 0.2085857	test: 0.2150142	best: 0.2150142 (1900)	total: 34.8s	remaining: 1m 4s
1920:	learn: 0.2083784	test: 0.2149050	best: 0.2149050 (1920)	total: 35.2s	remaining: 1m 4s
1940:	learn: 0.2081801	test: 0.2148132	best: 0.2148132 (1940)	total: 35.5s	remaining: 1m 3s
1960:	learn: 0.2079708	test: 0.2146978	best: 0.2146978 (1960)	total: 35.9s	remaining: 1m 3s
1980:	learn: 0.2077712	test: 0.2145699	best: 0.2145699 (1980)	total: 36.3s	remaining: 1m 3s
2000:	learn: 0.2075781	test: 0.2144809	best: 0.2144800 (1999)	total: 36.6s	remaining: 1m 2s
2020:	learn: 0.2074055	test: 0.2144154	best: 0.2144154 (2020)	total: 37s	remaining: 1m 2s
2040:	learn: 0.2072278	test: 0.2143081	best: 0.2143081 (2040)	total: 37.4s	remaining: 1m 2s
2060:	learn: 0.2070357	test: 0.2142118	best: 0.2142118 (2060)	total: 37.7s	remaining: 1m 1s
2080:	learn: 0.2067821	test: 0.2140353	best: 0.2140353 (2080)	total: 38.1s	remaining: 1m 1s
2100:	learn: 0.2066161	test: 0.2139695	best: 0.2139695 (2100)	total: 38.5s	remaining: 1m
2120:	learn: 0.2064448	test: 0.2138907	best: 0.2138907 (2120)	total: 38.8s	remaining: 1m
2140:	learn: 0.2062836	test: 0.2138119	best: 0.2138119 (2140)	total: 39.2s	remaining: 1m
2160:	learn: 0.2060853	test: 0.2137178	best: 0.2137178 (2160)	total: 39.6s	remaining: 59.8s
2180:	learn: 0.2058989	test: 0.2136235	best: 0.2136235 (2180)	total: 39.9s	remaining: 59.4s
2200:	learn: 0.2057171	test: 0.2135347	best: 0.2135347 (2200)	total: 40.3s	remaining: 59.1s
2220:	learn: 0.2055513	test: 0.2134739	best: 0.2134739 (2220)	total: 40.6s	remaining: 58.7s
2240:	learn: 0.2053841	test: 0.2133813	best: 0.2133813 (2240)	total: 41s	remaining: 58.3s
2260:	learn: 0.2052077	test: 0.2132994	best: 0.2132994 (2260)	total: 41.4s	remaining: 58s
2280:	learn: 0.2050286	test: 0.2132182	best: 0.2132182 (2280)	total: 41.8s	remaining: 57.6s
2300:	learn: 0.2048806	test: 0.2131566	best: 0.2131566 (2300)	total: 42.1s	remaining: 57.3s
2320:	learn: 0.2047205	test: 0.2130863	best: 0.2130861 (2318)	total: 42.5s	remaining: 56.9s
2340:	learn: 0.2045484	test: 0.2130024	best: 0.2130024 (2340)	total: 42.9s	remaining: 56.5s
2360:	learn: 0.2043667	test: 0.2129217	best: 0.2129217 (2360)	total: 43.2s	remaining: 56.2s
2380:	learn: 0.2041829	test: 0.2128380	best: 0.2128380 (2380)	total: 43.6s	remaining: 55.8s
2400:	learn: 0.2040372	test: 0.2127581	best: 0.2127581 (2400)	total: 44s	remaining: 55.5s
2420:	learn: 0.2038665	test: 0.2126989	best: 0.2126989 (2420)	total: 44.4s	remaining: 55.1s
2440:	learn: 0.2037141	test: 0.2126391	best: 0.2126391 (2440)	total: 44.7s	remaining: 54.8s
2460:	learn: 0.2035746	test: 0.2125763	best: 0.2125763 (2460)	total: 45.1s	remaining: 54.4s
2480:	learn: 0.2034292	test: 0.2125210	best: 0.2125210 (2480)	total: 45.5s	remaining: 54s
2500:	learn: 0.2032621	test: 0.2124415	best: 0.2124415 (2500)	total: 45.9s	remaining: 53.7s
2520:	learn: 0.2030771	test: 0.2123649	best: 0.2123649 (2520)	total: 46.3s	remaining: 53.3s
2540:	learn: 0.2028906	test: 0.2122681	best: 0.2122646 (2538)	total: 46.6s	remaining: 53s
2560:	learn: 0.2027286	test: 0.2121965	best: 0.2121965 (2560)	total: 47s	remaining: 52.7s
2580:	learn: 0.2025987	test: 0.2121592	best: 0.2121515 (2578)	total: 47.4s	remaining: 52.3s
2600:	learn: 0.2024632	test: 0.2121232	best: 0.2121232 (2600)	total: 47.8s	remaining: 52s
2620:	learn: 0.2022808	test: 0.2120350	best: 0.2120350 (2620)	total: 48.2s	remaining: 51.6s
2640:	learn: 0.2021291	test: 0.2119608	best: 0.2119608 (2640)	total: 48.6s	remaining: 51.3s
2660:	learn: 0.2019724	test: 0.2118691	best: 0.2118691 (2660)	total: 49s	remaining: 51s
2680:	learn: 0.2018385	test: 0.2118199	best: 0.2118199 (2680)	total: 49.4s	remaining: 50.6s
2700:	learn: 0.2016732	test: 0.2117472	best: 0.2117472 (2697)	total: 49.8s	remaining: 50.3s
2720:	learn: 0.2015126	test: 0.2116451	best: 0.2116425 (2718)	total: 50.2s	remaining: 49.9s
2740:	learn: 0.2013734	test: 0.2115993	best: 0.2115993 (2740)	total: 50.6s	remaining: 49.6s
2760:	learn: 0.2012021	test: 0.2115292	best: 0.2115292 (2760)	total: 50.9s	remaining: 49.2s
2780:	learn: 0.2010394	test: 0.2114430	best: 0.2114430 (2780)	total: 51.3s	remaining: 48.8s
2800:	learn: 0.2008923	test: 0.2113813	best: 0.2113813 (2800)	total: 51.7s	remaining: 48.5s
2820:	learn: 0.2007397	test: 0.2113074	best: 0.2113074 (2820)	total: 52s	remaining: 48.1s
2840:	learn: 0.2005688	test: 0.2112118	best: 0.2112118 (2840)	total: 52.4s	remaining: 47.7s
2860:	learn: 0.2004202	test: 0.2111629	best: 0.2111610 (2858)	total: 52.8s	remaining: 47.4s
2880:	learn: 0.2002646	test: 0.2111049	best: 0.2111049 (2880)	total: 53.2s	remaining: 47s
2900:	learn: 0.2001079	test: 0.2110488	best: 0.2110488 (2900)	total: 53.6s	remaining: 46.7s
2920:	learn: 0.1999325	test: 0.2109397	best: 0.2109397 (2920)	total: 54s	remaining: 46.3s
2940:	learn: 0.1998110	test: 0.2109047	best: 0.2109030 (2939)	total: 54.3s	remaining: 45.9s
2960:	learn: 0.1996534	test: 0.2108486	best: 0.2108472 (2958)	total: 54.7s	remaining: 45.6s
2980:	learn: 0.1994870	test: 0.2107784	best: 0.2107784 (2980)	total: 55.1s	remaining: 45.2s
3000:	learn: 0.1993497	test: 0.2107285	best: 0.2107285 (3000)	total: 55.5s	remaining: 44.9s
3020:	learn: 0.1991780	test: 0.2106413	best: 0.2106413 (3020)	total: 55.8s	remaining: 44.5s
3040:	learn: 0.1990497	test: 0.2105868	best: 0.2105868 (3040)	total: 56.2s	remaining: 44.1s
3060:	learn: 0.1989184	test: 0.2105301	best: 0.2105301 (3060)	total: 56.6s	remaining: 43.8s
3080:	learn: 0.1987885	test: 0.2104776	best: 0.2104776 (3080)	total: 57s	remaining: 43.4s
3100:	learn: 0.1986519	test: 0.2104255	best: 0.2104255 (3100)	total: 57.4s	remaining: 43s
3120:	learn: 0.1984901	test: 0.2103446	best: 0.2103446 (3120)	total: 57.7s	remaining: 42.7s
3140:	learn: 0.1983646	test: 0.2103220	best: 0.2103195 (3137)	total: 58.1s	remaining: 42.3s
3160:	learn: 0.1982349	test: 0.2102882	best: 0.2102875 (3159)	total: 58.5s	remaining: 41.9s
3180:	learn: 0.1980920	test: 0.2102480	best: 0.2102472 (3174)	total: 58.9s	remaining: 41.6s
3200:	learn: 0.1979478	test: 0.2101932	best: 0.2101932 (3200)	total: 59.3s	remaining: 41.2s
3220:	learn: 0.1978017	test: 0.2101545	best: 0.2101545 (3220)	total: 59.6s	remaining: 40.9s
3240:	learn: 0.1976810	test: 0.2101242	best: 0.2101183 (3238)	total: 1m	remaining: 40.5s
3260:	learn: 0.1975764	test: 0.2101157	best: 0.2101117 (3255)	total: 1m	remaining: 40.1s
3280:	learn: 0.1974585	test: 0.2100610	best: 0.2100610 (3280)	total: 1m	remaining: 39.8s
3300:	learn: 0.1973353	test: 0.2100167	best: 0.2100167 (3300)	total: 1m 1s	remaining: 39.4s
3320:	learn: 0.1971767	test: 0.2099466	best: 0.2099466 (3320)	total: 1m 1s	remaining: 39s
3340:	learn: 0.1970438	test: 0.2098870	best: 0.2098870 (3340)	total: 1m 1s	remaining: 38.6s
3360:	learn: 0.1969138	test: 0.2098562	best: 0.2098562 (3360)	total: 1m 2s	remaining: 38.3s
3380:	learn: 0.1968080	test: 0.2098336	best: 0.2098336 (3380)	total: 1m 2s	remaining: 37.9s
3400:	learn: 0.1966920	test: 0.2097930	best: 0.2097930 (3400)	total: 1m 2s	remaining: 37.5s
3420:	learn: 0.1965618	test: 0.2097515	best: 0.2097515 (3420)	total: 1m 3s	remaining: 37.2s
3440:	learn: 0.1964272	test: 0.2097016	best: 0.2096999 (3439)	total: 1m 3s	remaining: 36.8s
3460:	learn: 0.1963280	test: 0.2096596	best: 0.2096596 (3460)	total: 1m 4s	remaining: 36.4s
3480:	learn: 0.1961893	test: 0.2096012	best: 0.2096012 (3480)	total: 1m 4s	remaining: 36.1s
3500:	learn: 0.1960695	test: 0.2095825	best: 0.2095825 (3500)	total: 1m 4s	remaining: 35.7s
3520:	learn: 0.1959550	test: 0.2095483	best: 0.2095483 (3520)	total: 1m 5s	remaining: 35.3s
3540:	learn: 0.1957904	test: 0.2094705	best: 0.2094705 (3540)	total: 1m 5s	remaining: 34.9s
3560:	learn: 0.1956562	test: 0.2094183	best: 0.2094183 (3560)	total: 1m 5s	remaining: 34.6s
3580:	learn: 0.1955341	test: 0.2093812	best: 0.2093812 (3580)	total: 1m 6s	remaining: 34.2s
3600:	learn: 0.1954286	test: 0.2093376	best: 0.2093376 (3600)	total: 1m 6s	remaining: 33.8s
3620:	learn: 0.1953209	test: 0.2093184	best: 0.2093181 (3618)	total: 1m 7s	remaining: 33.5s
3640:	learn: 0.1952199	test: 0.2092942	best: 0.2092942 (3640)	total: 1m 7s	remaining: 33.1s
3660:	learn: 0.1950885	test: 0.2092540	best: 0.2092540 (3660)	total: 1m 7s	remaining: 32.7s
3680:	learn: 0.1949765	test: 0.2092207	best: 0.2092207 (3680)	total: 1m 8s	remaining: 32.3s
3700:	learn: 0.1948486	test: 0.2092000	best: 0.2091987 (3696)	total: 1m 8s	remaining: 32s
3720:	learn: 0.1947199	test: 0.2091439	best: 0.2091439 (3720)	total: 1m 8s	remaining: 31.6s
3740:	learn: 0.1946092	test: 0.2091197	best: 0.2091197 (3740)	total: 1m 9s	remaining: 31.2s
3760:	learn: 0.1944848	test: 0.2090664	best: 0.2090664 (3760)	total: 1m 9s	remaining: 30.9s
3780:	learn: 0.1943635	test: 0.2090276	best: 0.2090276 (3780)	total: 1m 10s	remaining: 30.5s
3800:	learn: 0.1942161	test: 0.2089428	best: 0.2089428 (3800)	total: 1m 10s	remaining: 30.1s
3820:	learn: 0.1940913	test: 0.2089126	best: 0.2089126 (3820)	total: 1m 10s	remaining: 29.8s
3840:	learn: 0.1939739	test: 0.2088745	best: 0.2088743 (3838)	total: 1m 11s	remaining: 29.4s
3860:	learn: 0.1938799	test: 0.2088515	best: 0.2088515 (3860)	total: 1m 11s	remaining: 29s
3880:	learn: 0.1937716	test: 0.2088405	best: 0.2088378 (3875)	total: 1m 11s	remaining: 28.7s
3900:	learn: 0.1936591	test: 0.2087980	best: 0.2087980 (3900)	total: 1m 12s	remaining: 28.3s
3920:	learn: 0.1935474	test: 0.2087717	best: 0.2087717 (3920)	total: 1m 12s	remaining: 27.9s
3940:	learn: 0.1934221	test: 0.2087364	best: 0.2087364 (3940)	total: 1m 13s	remaining: 27.5s
3960:	learn: 0.1933043	test: 0.2086946	best: 0.2086946 (3960)	total: 1m 13s	remaining: 27.2s
3980:	learn: 0.1931899	test: 0.2086572	best: 0.2086498 (3979)	total: 1m 13s	remaining: 26.8s
4000:	learn: 0.1930736	test: 0.2086249	best: 0.2086249 (4000)	total: 1m 14s	remaining: 26.4s
4020:	learn: 0.1929658	test: 0.2085945	best: 0.2085945 (4020)	total: 1m 14s	remaining: 26.1s
4040:	learn: 0.1928335	test: 0.2085411	best: 0.2085411 (4040)	total: 1m 14s	remaining: 25.7s
4060:	learn: 0.1926926	test: 0.2084886	best: 0.2084875 (4059)	total: 1m 15s	remaining: 25.3s
4080:	learn: 0.1925923	test: 0.2084672	best: 0.2084672 (4080)	total: 1m 15s	remaining: 25s
4100:	learn: 0.1924957	test: 0.2084706	best: 0.2084635 (4090)	total: 1m 16s	remaining: 24.6s
4120:	learn: 0.1923982	test: 0.2084390	best: 0.2084370 (4118)	total: 1m 16s	remaining: 24.2s
4140:	learn: 0.1923154	test: 0.2084235	best: 0.2084221 (4133)	total: 1m 16s	remaining: 23.9s
4160:	learn: 0.1922034	test: 0.2084052	best: 0.2084047 (4159)	total: 1m 17s	remaining: 23.5s
4180:	learn: 0.1921010	test: 0.2083701	best: 0.2083701 (4180)	total: 1m 17s	remaining: 23.1s
4200:	learn: 0.1919968	test: 0.2083580	best: 0.2083580 (4200)	total: 1m 17s	remaining: 22.8s
4220:	learn: 0.1918973	test: 0.2083228	best: 0.2083228 (4220)	total: 1m 18s	remaining: 22.4s
4240:	learn: 0.1918063	test: 0.2083028	best: 0.2083028 (4240)	total: 1m 18s	remaining: 22s
4260:	learn: 0.1916926	test: 0.2082771	best: 0.2082771 (4260)	total: 1m 19s	remaining: 21.6s
4280:	learn: 0.1915819	test: 0.2082418	best: 0.2082418 (4280)	total: 1m 19s	remaining: 21.3s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404101	test: 0.6404601	best: 0.6404601 (0)	total: 9.24ms	remaining: 9.24ms
1:	learn: 0.5954212	test: 0.5955476	best: 0.5955476 (1)	total: 18.2ms	remaining: 0us
bestTest = 0.5955475827
bestIteration = 1
0:	learn: 0.6415007	test: 0.6416794	best: 0.6416794 (0)	total: 16.6ms	remaining: 1m 32s
20:	learn: 0.3354650	test: 0.3357593	best: 0.3357593 (20)	total: 407ms	remaining: 1m 47s
40:	learn: 0.3034883	test: 0.3039692	best: 0.3039692 (40)	total: 790ms	remaining: 1m 46s
60:	learn: 0.2889850	test: 0.2886771	best: 0.2886771 (60)	total: 1.19s	remaining: 1m 47s
80:	learn: 0.2806223	test: 0.2800065	best: 0.2800065 (80)	total: 1.56s	remaining: 1m 46s
100:	learn: 0.2757454	test: 0.2750206	best: 0.2750206 (100)	total: 1.92s	remaining: 1m 44s
120:	learn: 0.2705225	test: 0.2694924	best: 0.2694924 (120)	total: 2.3s	remaining: 1m 43s
140:	learn: 0.2661250	test: 0.2648726	best: 0.2648726 (140)	total: 2.68s	remaining: 1m 43s
160:	learn: 0.2628899	test: 0.2615109	best: 0.2615109 (160)	total: 3.04s	remaining: 1m 42s
180:	learn: 0.2594919	test: 0.2578920	best: 0.2578920 (180)	total: 3.4s	remaining: 1m 41s
200:	learn: 0.2567379	test: 0.2550807	best: 0.2550807 (200)	total: 3.75s	remaining: 1m 40s
220:	learn: 0.2537299	test: 0.2518650	best: 0.2518650 (220)	total: 4.12s	remaining: 1m 39s
240:	learn: 0.2516616	test: 0.2497582	best: 0.2497582 (240)	total: 4.49s	remaining: 1m 39s
260:	learn: 0.2499096	test: 0.2480526	best: 0.2480526 (260)	total: 4.86s	remaining: 1m 38s
280:	learn: 0.2482890	test: 0.2464686	best: 0.2464686 (280)	total: 5.23s	remaining: 1m 38s
300:	learn: 0.2464441	test: 0.2445563	best: 0.2445563 (300)	total: 5.6s	remaining: 1m 38s
320:	learn: 0.2449177	test: 0.2430480	best: 0.2430480 (320)	total: 5.97s	remaining: 1m 37s
340:	learn: 0.2435142	test: 0.2417242	best: 0.2417242 (340)	total: 6.33s	remaining: 1m 37s
360:	learn: 0.2422023	test: 0.2404395	best: 0.2404395 (360)	total: 6.69s	remaining: 1m 36s
380:	learn: 0.2410647	test: 0.2393768	best: 0.2393768 (380)	total: 7.05s	remaining: 1m 36s
400:	learn: 0.2399708	test: 0.2383773	best: 0.2383773 (400)	total: 7.41s	remaining: 1m 35s
420:	learn: 0.2389119	test: 0.2373547	best: 0.2373547 (420)	total: 7.77s	remaining: 1m 35s
440:	learn: 0.2379225	test: 0.2364037	best: 0.2364037 (440)	total: 8.13s	remaining: 1m 34s
460:	learn: 0.2369477	test: 0.2355077	best: 0.2355077 (460)	total: 8.5s	remaining: 1m 34s
480:	learn: 0.2359226	test: 0.2345154	best: 0.2345154 (480)	total: 8.86s	remaining: 1m 33s
500:	learn: 0.2349875	test: 0.2336654	best: 0.2336654 (500)	total: 9.22s	remaining: 1m 33s
520:	learn: 0.2342540	test: 0.2330666	best: 0.2330666 (520)	total: 9.59s	remaining: 1m 33s
540:	learn: 0.2334782	test: 0.2323409	best: 0.2323409 (540)	total: 9.94s	remaining: 1m 32s
560:	learn: 0.2327377	test: 0.2317050	best: 0.2317050 (560)	total: 10.3s	remaining: 1m 32s
580:	learn: 0.2321048	test: 0.2311540	best: 0.2311540 (580)	total: 10.7s	remaining: 1m 31s
600:	learn: 0.2314130	test: 0.2305780	best: 0.2305780 (600)	total: 11s	remaining: 1m 31s
620:	learn: 0.2307682	test: 0.2300440	best: 0.2300440 (620)	total: 11.4s	remaining: 1m 30s
640:	learn: 0.2301113	test: 0.2294451	best: 0.2294451 (640)	total: 11.7s	remaining: 1m 30s
660:	learn: 0.2295195	test: 0.2289392	best: 0.2289392 (660)	total: 12.1s	remaining: 1m 30s
680:	learn: 0.2288859	test: 0.2283965	best: 0.2283965 (680)	total: 12.5s	remaining: 1m 29s
700:	learn: 0.2282613	test: 0.2278807	best: 0.2278807 (700)	total: 12.8s	remaining: 1m 29s
720:	learn: 0.2276299	test: 0.2273251	best: 0.2273251 (720)	total: 13.2s	remaining: 1m 28s
740:	learn: 0.2269720	test: 0.2267290	best: 0.2267290 (740)	total: 13.5s	remaining: 1m 28s
760:	learn: 0.2263901	test: 0.2262510	best: 0.2262510 (760)	total: 13.9s	remaining: 1m 28s
780:	learn: 0.2257721	test: 0.2256304	best: 0.2256304 (780)	total: 14.3s	remaining: 1m 27s
800:	learn: 0.2253164	test: 0.2252828	best: 0.2252828 (800)	total: 14.6s	remaining: 1m 27s
820:	learn: 0.2249030	test: 0.2249748	best: 0.2249748 (820)	total: 15s	remaining: 1m 27s
840:	learn: 0.2243811	test: 0.2245100	best: 0.2245100 (840)	total: 15.4s	remaining: 1m 26s
860:	learn: 0.2238818	test: 0.2240847	best: 0.2240847 (860)	total: 15.7s	remaining: 1m 26s
880:	learn: 0.2234311	test: 0.2237397	best: 0.2237397 (880)	total: 16.1s	remaining: 1m 25s
900:	learn: 0.2230437	test: 0.2234028	best: 0.2234028 (900)	total: 16.5s	remaining: 1m 25s
920:	learn: 0.2227171	test: 0.2231490	best: 0.2231490 (920)	total: 16.8s	remaining: 1m 25s
940:	learn: 0.2223174	test: 0.2228593	best: 0.2228593 (940)	total: 17.2s	remaining: 1m 24s
960:	learn: 0.2218939	test: 0.2224825	best: 0.2224825 (960)	total: 17.6s	remaining: 1m 24s
980:	learn: 0.2214615	test: 0.2221393	best: 0.2221393 (980)	total: 17.9s	remaining: 1m 23s
1000:	learn: 0.2210332	test: 0.2217436	best: 0.2217436 (1000)	total: 18.3s	remaining: 1m 23s
1020:	learn: 0.2206906	test: 0.2214770	best: 0.2214770 (1020)	total: 18.6s	remaining: 1m 23s
1040:	learn: 0.2203328	test: 0.2212287	best: 0.2212287 (1040)	total: 19s	remaining: 1m 22s
1060:	learn: 0.2198695	test: 0.2208456	best: 0.2208456 (1060)	total: 19.4s	remaining: 1m 22s
1080:	learn: 0.2196247	test: 0.2206839	best: 0.2206839 (1080)	total: 19.8s	remaining: 1m 22s
1100:	learn: 0.2192759	test: 0.2204677	best: 0.2204677 (1100)	total: 20.2s	remaining: 1m 21s
1120:	learn: 0.2189466	test: 0.2202272	best: 0.2202272 (1120)	total: 20.5s	remaining: 1m 21s
1140:	learn: 0.2185615	test: 0.2199153	best: 0.2199153 (1140)	total: 20.9s	remaining: 1m 21s
1160:	learn: 0.2182548	test: 0.2197071	best: 0.2197071 (1160)	total: 21.3s	remaining: 1m 21s
1180:	learn: 0.2179821	test: 0.2195436	best: 0.2195436 (1180)	total: 21.7s	remaining: 1m 20s
1200:	learn: 0.2176593	test: 0.2193140	best: 0.2193140 (1200)	total: 22s	remaining: 1m 20s
1220:	learn: 0.2173989	test: 0.2191703	best: 0.2191703 (1220)	total: 22.4s	remaining: 1m 19s
1240:	learn: 0.2170773	test: 0.2189800	best: 0.2189800 (1240)	total: 22.8s	remaining: 1m 19s
1260:	learn: 0.2168113	test: 0.2188055	best: 0.2188055 (1260)	total: 23.1s	remaining: 1m 19s
1280:	learn: 0.2165115	test: 0.2186178	best: 0.2186178 (1280)	total: 23.5s	remaining: 1m 18s
1300:	learn: 0.2162250	test: 0.2184594	best: 0.2184594 (1300)	total: 23.9s	remaining: 1m 18s
1320:	learn: 0.2159068	test: 0.2182365	best: 0.2182365 (1320)	total: 24.2s	remaining: 1m 18s
1340:	learn: 0.2156840	test: 0.2181169	best: 0.2181169 (1340)	total: 24.6s	remaining: 1m 17s
1360:	learn: 0.2153683	test: 0.2179109	best: 0.2179109 (1360)	total: 25s	remaining: 1m 17s
1380:	learn: 0.2150909	test: 0.2177330	best: 0.2177330 (1380)	total: 25.3s	remaining: 1m 17s
1400:	learn: 0.2148354	test: 0.2175815	best: 0.2175815 (1400)	total: 25.7s	remaining: 1m 16s
1420:	learn: 0.2145871	test: 0.2174100	best: 0.2174100 (1420)	total: 26.1s	remaining: 1m 16s
1440:	learn: 0.2143085	test: 0.2172415	best: 0.2172415 (1440)	total: 26.5s	remaining: 1m 15s
1460:	learn: 0.2140770	test: 0.2171028	best: 0.2171028 (1460)	total: 26.8s	remaining: 1m 15s
1480:	learn: 0.2138203	test: 0.2169644	best: 0.2169644 (1480)	total: 27.2s	remaining: 1m 15s
1500:	learn: 0.2135993	test: 0.2168176	best: 0.2168176 (1500)	total: 27.6s	remaining: 1m 14s
1520:	learn: 0.2133610	test: 0.2166427	best: 0.2166417 (1519)	total: 27.9s	remaining: 1m 14s
1540:	learn: 0.2130700	test: 0.2164405	best: 0.2164405 (1540)	total: 28.3s	remaining: 1m 14s
1560:	learn: 0.2127565	test: 0.2162183	best: 0.2162183 (1560)	total: 28.7s	remaining: 1m 13s
1580:	learn: 0.2125238	test: 0.2160820	best: 0.2160820 (1580)	total: 29s	remaining: 1m 13s
1600:	learn: 0.2123183	test: 0.2159678	best: 0.2159678 (1600)	total: 29.4s	remaining: 1m 13s
1620:	learn: 0.2121008	test: 0.2158042	best: 0.2158042 (1620)	total: 29.8s	remaining: 1m 12s
1640:	learn: 0.2118464	test: 0.2156369	best: 0.2156369 (1640)	total: 30.2s	remaining: 1m 12s
1660:	learn: 0.2116030	test: 0.2154636	best: 0.2154636 (1660)	total: 30.5s	remaining: 1m 12s
1680:	learn: 0.2113582	test: 0.2153198	best: 0.2153198 (1680)	total: 30.9s	remaining: 1m 11s
1700:	learn: 0.2111396	test: 0.2152095	best: 0.2152086 (1699)	total: 31.3s	remaining: 1m 11s
1720:	learn: 0.2109418	test: 0.2151091	best: 0.2151091 (1720)	total: 31.6s	remaining: 1m 10s
1740:	learn: 0.2107675	test: 0.2150136	best: 0.2150136 (1740)	total: 32s	remaining: 1m 10s
1760:	learn: 0.2105336	test: 0.2148665	best: 0.2148665 (1760)	total: 32.4s	remaining: 1m 10s
1780:	learn: 0.2103352	test: 0.2147521	best: 0.2147521 (1780)	total: 32.8s	remaining: 1m 9s
1800:	learn: 0.2101254	test: 0.2146048	best: 0.2146048 (1800)	total: 33.1s	remaining: 1m 9s
1820:	learn: 0.2098702	test: 0.2144574	best: 0.2144574 (1820)	total: 33.5s	remaining: 1m 9s
1840:	learn: 0.2096888	test: 0.2143658	best: 0.2143658 (1840)	total: 33.8s	remaining: 1m 8s
1860:	learn: 0.2094774	test: 0.2142632	best: 0.2142632 (1860)	total: 34.2s	remaining: 1m 8s
1880:	learn: 0.2092855	test: 0.2141620	best: 0.2141620 (1880)	total: 34.6s	remaining: 1m 7s
1900:	learn: 0.2091129	test: 0.2140876	best: 0.2140876 (1900)	total: 34.9s	remaining: 1m 7s
1920:	learn: 0.2089455	test: 0.2140182	best: 0.2140182 (1920)	total: 35.3s	remaining: 1m 7s
1940:	learn: 0.2087525	test: 0.2139226	best: 0.2139226 (1940)	total: 35.7s	remaining: 1m 6s
1960:	learn: 0.2085672	test: 0.2138099	best: 0.2138099 (1960)	total: 36s	remaining: 1m 6s
1980:	learn: 0.2083637	test: 0.2136913	best: 0.2136913 (1980)	total: 36.4s	remaining: 1m 6s
2000:	learn: 0.2081747	test: 0.2135806	best: 0.2135806 (2000)	total: 36.7s	remaining: 1m 5s
2020:	learn: 0.2080003	test: 0.2134963	best: 0.2134963 (2020)	total: 37.1s	remaining: 1m 5s
2040:	learn: 0.2078097	test: 0.2133954	best: 0.2133937 (2037)	total: 37.5s	remaining: 1m 4s
2060:	learn: 0.2075949	test: 0.2132489	best: 0.2132489 (2060)	total: 37.9s	remaining: 1m 4s
2080:	learn: 0.2074098	test: 0.2131645	best: 0.2131645 (2080)	total: 38.2s	remaining: 1m 4s
2100:	learn: 0.2072217	test: 0.2130529	best: 0.2130529 (2100)	total: 38.6s	remaining: 1m 3s
2120:	learn: 0.2070313	test: 0.2129370	best: 0.2129370 (2120)	total: 39s	remaining: 1m 3s
2140:	learn: 0.2068405	test: 0.2128370	best: 0.2128370 (2140)	total: 39.4s	remaining: 1m 3s
2160:	learn: 0.2066569	test: 0.2127497	best: 0.2127497 (2160)	total: 39.7s	remaining: 1m 2s
2180:	learn: 0.2064720	test: 0.2126629	best: 0.2126629 (2180)	total: 40.1s	remaining: 1m 2s
2200:	learn: 0.2062582	test: 0.2125376	best: 0.2125376 (2200)	total: 40.4s	remaining: 1m 2s
2220:	learn: 0.2060813	test: 0.2124693	best: 0.2124693 (2220)	total: 40.8s	remaining: 1m 1s
2240:	learn: 0.2058995	test: 0.2123412	best: 0.2123412 (2240)	total: 41.2s	remaining: 1m 1s
2260:	learn: 0.2057161	test: 0.2122535	best: 0.2122520 (2259)	total: 41.5s	remaining: 1m
2280:	learn: 0.2055717	test: 0.2121950	best: 0.2121946 (2279)	total: 41.9s	remaining: 1m
2300:	learn: 0.2054265	test: 0.2121244	best: 0.2121244 (2300)	total: 42.3s	remaining: 1m
2320:	learn: 0.2052489	test: 0.2120453	best: 0.2120453 (2320)	total: 42.6s	remaining: 59.8s
2340:	learn: 0.2051033	test: 0.2119749	best: 0.2119749 (2340)	total: 43s	remaining: 59.4s
2360:	learn: 0.2049514	test: 0.2119083	best: 0.2119083 (2360)	total: 43.4s	remaining: 59.1s
2380:	learn: 0.2047791	test: 0.2118232	best: 0.2118232 (2380)	total: 43.7s	remaining: 58.7s
2400:	learn: 0.2045870	test: 0.2117066	best: 0.2117066 (2400)	total: 44.1s	remaining: 58.4s
2420:	learn: 0.2044341	test: 0.2116605	best: 0.2116605 (2420)	total: 44.5s	remaining: 58s
2440:	learn: 0.2042952	test: 0.2116041	best: 0.2116041 (2440)	total: 44.8s	remaining: 57.6s
2460:	learn: 0.2041607	test: 0.2115443	best: 0.2115443 (2460)	total: 45.2s	remaining: 57.3s
2480:	learn: 0.2040158	test: 0.2114941	best: 0.2114941 (2480)	total: 45.6s	remaining: 56.9s
2500:	learn: 0.2038489	test: 0.2114093	best: 0.2114093 (2500)	total: 45.9s	remaining: 56.5s
2520:	learn: 0.2037007	test: 0.2113392	best: 0.2113392 (2520)	total: 46.3s	remaining: 56.2s
2540:	learn: 0.2035397	test: 0.2112651	best: 0.2112651 (2540)	total: 46.7s	remaining: 55.8s
2560:	learn: 0.2033952	test: 0.2111739	best: 0.2111739 (2560)	total: 47s	remaining: 55.4s
2580:	learn: 0.2032243	test: 0.2111000	best: 0.2111000 (2580)	total: 47.4s	remaining: 55.1s
2600:	learn: 0.2030835	test: 0.2110234	best: 0.2110234 (2600)	total: 47.8s	remaining: 54.7s
2620:	learn: 0.2029186	test: 0.2109393	best: 0.2109393 (2620)	total: 48.2s	remaining: 54.3s
2640:	learn: 0.2027567	test: 0.2108648	best: 0.2108648 (2640)	total: 48.5s	remaining: 54s
2660:	learn: 0.2026351	test: 0.2108351	best: 0.2108351 (2660)	total: 48.9s	remaining: 53.6s
2680:	learn: 0.2024654	test: 0.2107737	best: 0.2107718 (2679)	total: 49.2s	remaining: 53.2s
2700:	learn: 0.2023338	test: 0.2107241	best: 0.2107241 (2700)	total: 49.6s	remaining: 52.9s
2720:	learn: 0.2021506	test: 0.2106255	best: 0.2106255 (2720)	total: 50s	remaining: 52.5s
2740:	learn: 0.2019968	test: 0.2105622	best: 0.2105622 (2740)	total: 50.4s	remaining: 52.1s
2760:	learn: 0.2018742	test: 0.2105307	best: 0.2105298 (2759)	total: 50.7s	remaining: 51.8s
2780:	learn: 0.2017226	test: 0.2104660	best: 0.2104644 (2778)	total: 51.1s	remaining: 51.4s
2800:	learn: 0.2015786	test: 0.2104002	best: 0.2104002 (2800)	total: 51.5s	remaining: 51.1s
2820:	learn: 0.2014512	test: 0.2103434	best: 0.2103426 (2819)	total: 51.9s	remaining: 50.7s
2840:	learn: 0.2013170	test: 0.2102951	best: 0.2102951 (2840)	total: 52.2s	remaining: 50.3s
2860:	learn: 0.2011865	test: 0.2102413	best: 0.2102413 (2860)	total: 52.6s	remaining: 50s
2880:	learn: 0.2010464	test: 0.2101953	best: 0.2101953 (2880)	total: 53s	remaining: 49.6s
2900:	learn: 0.2008802	test: 0.2101382	best: 0.2101382 (2900)	total: 53.3s	remaining: 49.2s
2920:	learn: 0.2007642	test: 0.2100869	best: 0.2100869 (2920)	total: 53.7s	remaining: 48.9s
2940:	learn: 0.2006218	test: 0.2100141	best: 0.2100141 (2940)	total: 54.1s	remaining: 48.5s
2960:	learn: 0.2004725	test: 0.2099519	best: 0.2099474 (2958)	total: 54.4s	remaining: 48.1s
2980:	learn: 0.2003239	test: 0.2098823	best: 0.2098823 (2980)	total: 54.8s	remaining: 47.8s
3000:	learn: 0.2001874	test: 0.2098113	best: 0.2098113 (3000)	total: 55.2s	remaining: 47.4s
3020:	learn: 0.2000517	test: 0.2097563	best: 0.2097563 (3020)	total: 55.5s	remaining: 47s
3040:	learn: 0.1999083	test: 0.2097013	best: 0.2097013 (3040)	total: 55.9s	remaining: 46.7s
3060:	learn: 0.1997654	test: 0.2096377	best: 0.2096368 (3059)	total: 56.3s	remaining: 46.3s
3080:	learn: 0.1996428	test: 0.2096117	best: 0.2096111 (3076)	total: 56.7s	remaining: 45.9s
3100:	learn: 0.1995138	test: 0.2095680	best: 0.2095680 (3100)	total: 57s	remaining: 45.6s
3120:	learn: 0.1993816	test: 0.2095062	best: 0.2095062 (3120)	total: 57.4s	remaining: 45.2s
3140:	learn: 0.1992239	test: 0.2094173	best: 0.2094149 (3138)	total: 57.8s	remaining: 44.8s
3160:	learn: 0.1990995	test: 0.2093674	best: 0.2093674 (3160)	total: 58.2s	remaining: 44.5s
3180:	learn: 0.1989497	test: 0.2093029	best: 0.2093029 (3180)	total: 58.5s	remaining: 44.1s
3200:	learn: 0.1988059	test: 0.2092539	best: 0.2092539 (3200)	total: 58.9s	remaining: 43.8s
3220:	learn: 0.1986796	test: 0.2092183	best: 0.2092140 (3216)	total: 59.3s	remaining: 43.4s
3240:	learn: 0.1985457	test: 0.2091609	best: 0.2091609 (3240)	total: 59.7s	remaining: 43s
3260:	learn: 0.1984087	test: 0.2091070	best: 0.2091070 (3260)	total: 1m	remaining: 42.7s
3280:	learn: 0.1983008	test: 0.2090728	best: 0.2090728 (3280)	total: 1m	remaining: 42.3s
3300:	learn: 0.1981668	test: 0.2090121	best: 0.2090121 (3300)	total: 1m	remaining: 41.9s
3320:	learn: 0.1980562	test: 0.2089672	best: 0.2089672 (3320)	total: 1m 1s	remaining: 41.6s
3340:	learn: 0.1979208	test: 0.2089295	best: 0.2089295 (3340)	total: 1m 1s	remaining: 41.2s
3360:	learn: 0.1977784	test: 0.2088760	best: 0.2088760 (3360)	total: 1m 1s	remaining: 40.8s
3380:	learn: 0.1976441	test: 0.2088312	best: 0.2088312 (3380)	total: 1m 2s	remaining: 40.5s
3400:	learn: 0.1975083	test: 0.2087945	best: 0.2087945 (3400)	total: 1m 2s	remaining: 40.1s
3420:	learn: 0.1973757	test: 0.2087531	best: 0.2087493 (3416)	total: 1m 2s	remaining: 39.7s
3440:	learn: 0.1972545	test: 0.2087224	best: 0.2087221 (3439)	total: 1m 3s	remaining: 39.4s
3460:	learn: 0.1970919	test: 0.2086353	best: 0.2086340 (3458)	total: 1m 3s	remaining: 39s
3480:	learn: 0.1969892	test: 0.2086133	best: 0.2086114 (3477)	total: 1m 4s	remaining: 38.6s
3500:	learn: 0.1968506	test: 0.2085577	best: 0.2085577 (3500)	total: 1m 4s	remaining: 38.3s
3520:	learn: 0.1967070	test: 0.2085132	best: 0.2085132 (3520)	total: 1m 4s	remaining: 37.9s
3540:	learn: 0.1965752	test: 0.2084625	best: 0.2084625 (3540)	total: 1m 5s	remaining: 37.5s
3560:	learn: 0.1964603	test: 0.2084326	best: 0.2084326 (3560)	total: 1m 5s	remaining: 37.2s
3580:	learn: 0.1963184	test: 0.2083852	best: 0.2083852 (3580)	total: 1m 5s	remaining: 36.8s
3600:	learn: 0.1961926	test: 0.2083429	best: 0.2083429 (3600)	total: 1m 6s	remaining: 36.4s
3620:	learn: 0.1960800	test: 0.2083071	best: 0.2083058 (3618)	total: 1m 6s	remaining: 36.1s
3640:	learn: 0.1959485	test: 0.2082674	best: 0.2082674 (3640)	total: 1m 7s	remaining: 35.7s
3660:	learn: 0.1958362	test: 0.2082524	best: 0.2082524 (3660)	total: 1m 7s	remaining: 35.3s
3680:	learn: 0.1957274	test: 0.2082186	best: 0.2082186 (3680)	total: 1m 7s	remaining: 35s
3700:	learn: 0.1956077	test: 0.2081855	best: 0.2081851 (3697)	total: 1m 8s	remaining: 34.6s
3720:	learn: 0.1954775	test: 0.2081331	best: 0.2081331 (3720)	total: 1m 8s	remaining: 34.2s
3740:	learn: 0.1953496	test: 0.2080732	best: 0.2080710 (3734)	total: 1m 8s	remaining: 33.9s
3760:	learn: 0.1952124	test: 0.2080386	best: 0.2080386 (3760)	total: 1m 9s	remaining: 33.5s
3780:	learn: 0.1950818	test: 0.2079704	best: 0.2079693 (3778)	total: 1m 9s	remaining: 33.1s
3800:	learn: 0.1949269	test: 0.2078794	best: 0.2078784 (3799)	total: 1m 10s	remaining: 32.8s
3820:	learn: 0.1948234	test: 0.2078467	best: 0.2078466 (3817)	total: 1m 10s	remaining: 32.4s
3840:	learn: 0.1946992	test: 0.2078152	best: 0.2078147 (3835)	total: 1m 10s	remaining: 32s
3860:	learn: 0.1945492	test: 0.2077596	best: 0.2077596 (3860)	total: 1m 11s	remaining: 31.7s
3880:	learn: 0.1944438	test: 0.2077408	best: 0.2077408 (3879)	total: 1m 11s	remaining: 31.3s
3900:	learn: 0.1943122	test: 0.2077150	best: 0.2077150 (3900)	total: 1m 11s	remaining: 30.9s
3920:	learn: 0.1941818	test: 0.2076711	best: 0.2076709 (3919)	total: 1m 12s	remaining: 30.6s
3940:	learn: 0.1940756	test: 0.2076426	best: 0.2076421 (3933)	total: 1m 12s	remaining: 30.2s
3960:	learn: 0.1939616	test: 0.2076068	best: 0.2076068 (3960)	total: 1m 13s	remaining: 29.8s
3980:	learn: 0.1938527	test: 0.2075796	best: 0.2075787 (3973)	total: 1m 13s	remaining: 29.5s
4000:	learn: 0.1937461	test: 0.2075481	best: 0.2075481 (4000)	total: 1m 13s	remaining: 29.1s
4020:	learn: 0.1936111	test: 0.2074897	best: 0.2074897 (4020)	total: 1m 14s	remaining: 28.7s
4040:	learn: 0.1935052	test: 0.2074623	best: 0.2074623 (4040)	total: 1m 14s	remaining: 28.4s
4060:	learn: 0.1934151	test: 0.2074295	best: 0.2074295 (4060)	total: 1m 14s	remaining: 28s
4080:	learn: 0.1932961	test: 0.2074082	best: 0.2074082 (4080)	total: 1m 15s	remaining: 27.6s
4100:	learn: 0.1931765	test: 0.2073545	best: 0.2073545 (4100)	total: 1m 15s	remaining: 27.3s
4120:	learn: 0.1930667	test: 0.2073139	best: 0.2073137 (4119)	total: 1m 16s	remaining: 26.9s
4140:	learn: 0.1929572	test: 0.2072939	best: 0.2072939 (4140)	total: 1m 16s	remaining: 26.5s
4160:	learn: 0.1928422	test: 0.2072655	best: 0.2072609 (4158)	total: 1m 16s	remaining: 26.2s
4180:	learn: 0.1927188	test: 0.2072266	best: 0.2072266 (4180)	total: 1m 17s	remaining: 25.8s
4200:	learn: 0.1926409	test: 0.2072132	best: 0.2072111 (4193)	total: 1m 17s	remaining: 25.4s
4220:	learn: 0.1925441	test: 0.2071976	best: 0.2071955 (4215)	total: 1m 17s	remaining: 25.1s
4240:	learn: 0.1924308	test: 0.2071806	best: 0.2071787 (4232)	total: 1m 18s	remaining: 24.7s
4260:	learn: 0.1922905	test: 0.2071372	best: 0.2071372 (4260)	total: 1m 18s	remaining: 24.3s
4280:	learn: 0.1921905	test: 0.2071096	best: 0.2071096 (4280)	total: 1m 19s	remaining: 24s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404723	test: 0.6403624	best: 0.6403624 (0)	total: 9.08ms	remaining: 9.08ms
1:	learn: 0.5956634	test: 0.5954553	best: 0.5954553 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5954553234
bestIteration = 1
0:	learn: 0.6415008	test: 0.6415956	best: 0.6415956 (0)	total: 16.8ms	remaining: 1m 33s
20:	learn: 0.3356117	test: 0.3353669	best: 0.3353669 (20)	total: 406ms	remaining: 1m 46s
40:	learn: 0.3013334	test: 0.3011655	best: 0.3011655 (40)	total: 783ms	remaining: 1m 45s
60:	learn: 0.2888286	test: 0.2887044	best: 0.2887044 (60)	total: 1.17s	remaining: 1m 45s
80:	learn: 0.2813243	test: 0.2809695	best: 0.2809695 (80)	total: 1.55s	remaining: 1m 44s
100:	learn: 0.2759515	test: 0.2753587	best: 0.2753587 (100)	total: 1.91s	remaining: 1m 42s
120:	learn: 0.2709104	test: 0.2702431	best: 0.2702431 (120)	total: 2.27s	remaining: 1m 41s
140:	learn: 0.2671969	test: 0.2664994	best: 0.2664994 (140)	total: 2.63s	remaining: 1m 40s
160:	learn: 0.2631126	test: 0.2622503	best: 0.2622503 (160)	total: 2.99s	remaining: 1m 39s
180:	learn: 0.2599669	test: 0.2590268	best: 0.2590268 (180)	total: 3.36s	remaining: 1m 39s
200:	learn: 0.2575953	test: 0.2567659	best: 0.2567659 (200)	total: 3.72s	remaining: 1m 38s
220:	learn: 0.2547099	test: 0.2537196	best: 0.2537196 (220)	total: 4.07s	remaining: 1m 38s
240:	learn: 0.2523372	test: 0.2512269	best: 0.2512269 (240)	total: 4.45s	remaining: 1m 37s
260:	learn: 0.2506936	test: 0.2495573	best: 0.2495573 (260)	total: 4.82s	remaining: 1m 37s
280:	learn: 0.2487013	test: 0.2475897	best: 0.2475897 (280)	total: 5.17s	remaining: 1m 36s
300:	learn: 0.2471730	test: 0.2460955	best: 0.2460955 (300)	total: 5.53s	remaining: 1m 36s
320:	learn: 0.2455757	test: 0.2445576	best: 0.2445576 (320)	total: 5.89s	remaining: 1m 35s
340:	learn: 0.2440504	test: 0.2431044	best: 0.2431044 (340)	total: 6.25s	remaining: 1m 35s
360:	learn: 0.2427471	test: 0.2419069	best: 0.2419069 (360)	total: 6.61s	remaining: 1m 34s
380:	learn: 0.2414273	test: 0.2405561	best: 0.2405561 (380)	total: 6.97s	remaining: 1m 34s
400:	learn: 0.2401073	test: 0.2392008	best: 0.2392008 (400)	total: 7.34s	remaining: 1m 34s
420:	learn: 0.2386842	test: 0.2377164	best: 0.2377164 (420)	total: 7.71s	remaining: 1m 33s
440:	learn: 0.2375399	test: 0.2365553	best: 0.2365553 (440)	total: 8.08s	remaining: 1m 33s
460:	learn: 0.2367087	test: 0.2358537	best: 0.2358537 (460)	total: 8.44s	remaining: 1m 32s
480:	learn: 0.2359669	test: 0.2352366	best: 0.2352366 (480)	total: 8.81s	remaining: 1m 32s
500:	learn: 0.2349908	test: 0.2343426	best: 0.2343426 (500)	total: 9.17s	remaining: 1m 32s
520:	learn: 0.2340853	test: 0.2334933	best: 0.2334933 (520)	total: 9.53s	remaining: 1m 31s
540:	learn: 0.2332845	test: 0.2328094	best: 0.2328094 (540)	total: 9.89s	remaining: 1m 31s
560:	learn: 0.2326949	test: 0.2323164	best: 0.2323164 (560)	total: 10.3s	remaining: 1m 31s
580:	learn: 0.2318633	test: 0.2316029	best: 0.2316029 (580)	total: 10.6s	remaining: 1m 30s
600:	learn: 0.2311739	test: 0.2309801	best: 0.2309801 (600)	total: 11s	remaining: 1m 30s
620:	learn: 0.2305267	test: 0.2304458	best: 0.2304458 (620)	total: 11.4s	remaining: 1m 30s
640:	learn: 0.2298536	test: 0.2298701	best: 0.2298701 (640)	total: 11.7s	remaining: 1m 29s
660:	learn: 0.2291269	test: 0.2292895	best: 0.2292895 (660)	total: 12.1s	remaining: 1m 29s
680:	learn: 0.2284742	test: 0.2287468	best: 0.2287468 (680)	total: 12.4s	remaining: 1m 28s
700:	learn: 0.2279038	test: 0.2282934	best: 0.2282934 (700)	total: 12.8s	remaining: 1m 28s
720:	learn: 0.2273701	test: 0.2278751	best: 0.2278751 (720)	total: 13.2s	remaining: 1m 28s
740:	learn: 0.2266856	test: 0.2273191	best: 0.2273191 (740)	total: 13.5s	remaining: 1m 27s
760:	learn: 0.2261309	test: 0.2268681	best: 0.2268681 (760)	total: 13.9s	remaining: 1m 27s
780:	learn: 0.2256915	test: 0.2265572	best: 0.2265572 (780)	total: 14.3s	remaining: 1m 27s
800:	learn: 0.2250740	test: 0.2260734	best: 0.2260734 (800)	total: 14.6s	remaining: 1m 26s
820:	learn: 0.2246373	test: 0.2257264	best: 0.2257264 (820)	total: 15s	remaining: 1m 26s
840:	learn: 0.2241920	test: 0.2253848	best: 0.2253848 (840)	total: 15.3s	remaining: 1m 25s
860:	learn: 0.2238049	test: 0.2251446	best: 0.2251446 (860)	total: 15.7s	remaining: 1m 25s
880:	learn: 0.2232882	test: 0.2247410	best: 0.2247410 (880)	total: 16.1s	remaining: 1m 24s
900:	learn: 0.2228057	test: 0.2243582	best: 0.2243582 (900)	total: 16.4s	remaining: 1m 24s
920:	learn: 0.2223935	test: 0.2240417	best: 0.2240417 (920)	total: 16.8s	remaining: 1m 24s
940:	learn: 0.2220509	test: 0.2238301	best: 0.2238301 (940)	total: 17.1s	remaining: 1m 23s
960:	learn: 0.2216720	test: 0.2235537	best: 0.2235537 (960)	total: 17.5s	remaining: 1m 23s
980:	learn: 0.2212524	test: 0.2232074	best: 0.2232074 (980)	total: 17.9s	remaining: 1m 23s
1000:	learn: 0.2209015	test: 0.2229644	best: 0.2229644 (1000)	total: 18.2s	remaining: 1m 22s
1020:	learn: 0.2204635	test: 0.2226100	best: 0.2226100 (1020)	total: 18.6s	remaining: 1m 22s
1040:	learn: 0.2200917	test: 0.2223732	best: 0.2223732 (1040)	total: 18.9s	remaining: 1m 21s
1060:	learn: 0.2197435	test: 0.2221461	best: 0.2221461 (1060)	total: 19.3s	remaining: 1m 21s
1080:	learn: 0.2194128	test: 0.2219053	best: 0.2219053 (1080)	total: 19.7s	remaining: 1m 21s
1100:	learn: 0.2190277	test: 0.2216494	best: 0.2216494 (1100)	total: 20s	remaining: 1m 20s
1120:	learn: 0.2186996	test: 0.2214110	best: 0.2214110 (1120)	total: 20.4s	remaining: 1m 20s
1140:	learn: 0.2184154	test: 0.2212413	best: 0.2212413 (1140)	total: 20.7s	remaining: 1m 19s
1160:	learn: 0.2181545	test: 0.2210876	best: 0.2210876 (1160)	total: 21.1s	remaining: 1m 19s
1180:	learn: 0.2177883	test: 0.2208304	best: 0.2208304 (1180)	total: 21.4s	remaining: 1m 19s
1200:	learn: 0.2175080	test: 0.2206456	best: 0.2206456 (1200)	total: 21.8s	remaining: 1m 18s
1220:	learn: 0.2171718	test: 0.2204355	best: 0.2204355 (1220)	total: 22.1s	remaining: 1m 18s
1240:	learn: 0.2168703	test: 0.2202414	best: 0.2202414 (1240)	total: 22.5s	remaining: 1m 18s
1260:	learn: 0.2165111	test: 0.2200050	best: 0.2200050 (1260)	total: 22.9s	remaining: 1m 17s
1280:	learn: 0.2161316	test: 0.2197092	best: 0.2197092 (1280)	total: 23.2s	remaining: 1m 17s
1300:	learn: 0.2158419	test: 0.2194975	best: 0.2194975 (1300)	total: 23.6s	remaining: 1m 16s
1320:	learn: 0.2156120	test: 0.2193635	best: 0.2193632 (1319)	total: 23.9s	remaining: 1m 16s
1340:	learn: 0.2153375	test: 0.2191936	best: 0.2191936 (1340)	total: 24.3s	remaining: 1m 16s
1360:	learn: 0.2150608	test: 0.2190300	best: 0.2190300 (1360)	total: 24.6s	remaining: 1m 15s
1380:	learn: 0.2148110	test: 0.2188870	best: 0.2188870 (1380)	total: 25s	remaining: 1m 15s
1400:	learn: 0.2145515	test: 0.2187316	best: 0.2187316 (1400)	total: 25.4s	remaining: 1m 15s
1420:	learn: 0.2143176	test: 0.2185831	best: 0.2185831 (1420)	total: 25.8s	remaining: 1m 14s
1440:	learn: 0.2141190	test: 0.2184802	best: 0.2184802 (1440)	total: 26.1s	remaining: 1m 14s
1460:	learn: 0.2138975	test: 0.2183736	best: 0.2183736 (1460)	total: 26.5s	remaining: 1m 13s
1480:	learn: 0.2136204	test: 0.2181895	best: 0.2181895 (1480)	total: 26.9s	remaining: 1m 13s
1500:	learn: 0.2132835	test: 0.2179492	best: 0.2179492 (1500)	total: 27.2s	remaining: 1m 13s
1520:	learn: 0.2130482	test: 0.2178301	best: 0.2178301 (1520)	total: 27.6s	remaining: 1m 12s
1540:	learn: 0.2127373	test: 0.2176064	best: 0.2176064 (1540)	total: 28s	remaining: 1m 12s
1560:	learn: 0.2125302	test: 0.2175078	best: 0.2175078 (1560)	total: 28.3s	remaining: 1m 12s
1580:	learn: 0.2122059	test: 0.2173344	best: 0.2173344 (1580)	total: 28.7s	remaining: 1m 11s
1600:	learn: 0.2119569	test: 0.2171705	best: 0.2171705 (1600)	total: 29s	remaining: 1m 11s
1620:	learn: 0.2117034	test: 0.2169845	best: 0.2169845 (1620)	total: 29.4s	remaining: 1m 11s
1640:	learn: 0.2114878	test: 0.2168777	best: 0.2168777 (1640)	total: 29.8s	remaining: 1m 10s
1660:	learn: 0.2112998	test: 0.2167942	best: 0.2167942 (1660)	total: 30.1s	remaining: 1m 10s
1680:	learn: 0.2110803	test: 0.2166864	best: 0.2166864 (1680)	total: 30.5s	remaining: 1m 10s
1700:	learn: 0.2108772	test: 0.2165768	best: 0.2165768 (1700)	total: 30.9s	remaining: 1m 9s
1720:	learn: 0.2106602	test: 0.2164544	best: 0.2164544 (1720)	total: 31.2s	remaining: 1m 9s
1740:	learn: 0.2104657	test: 0.2163317	best: 0.2163317 (1740)	total: 31.6s	remaining: 1m 8s
1760:	learn: 0.2102553	test: 0.2162309	best: 0.2162309 (1760)	total: 31.9s	remaining: 1m 8s
1780:	learn: 0.2100198	test: 0.2161047	best: 0.2161047 (1780)	total: 32.3s	remaining: 1m 8s
1800:	learn: 0.2098162	test: 0.2159885	best: 0.2159885 (1800)	total: 32.7s	remaining: 1m 7s
1820:	learn: 0.2096093	test: 0.2159032	best: 0.2159032 (1820)	total: 33s	remaining: 1m 7s
1840:	learn: 0.2093797	test: 0.2158134	best: 0.2158134 (1840)	total: 33.4s	remaining: 1m 7s
1860:	learn: 0.2091953	test: 0.2157504	best: 0.2157504 (1860)	total: 33.7s	remaining: 1m 6s
1880:	learn: 0.2089994	test: 0.2156496	best: 0.2156496 (1880)	total: 34.1s	remaining: 1m 6s
1900:	learn: 0.2087891	test: 0.2155233	best: 0.2155233 (1900)	total: 34.4s	remaining: 1m 5s
1920:	learn: 0.2085332	test: 0.2153965	best: 0.2153960 (1919)	total: 34.8s	remaining: 1m 5s
1940:	learn: 0.2083613	test: 0.2153085	best: 0.2153085 (1940)	total: 35.2s	remaining: 1m 5s
1960:	learn: 0.2081041	test: 0.2151569	best: 0.2151569 (1960)	total: 35.5s	remaining: 1m 4s
1980:	learn: 0.2079220	test: 0.2150555	best: 0.2150552 (1979)	total: 35.9s	remaining: 1m 4s
2000:	learn: 0.2077456	test: 0.2149859	best: 0.2149859 (2000)	total: 36.2s	remaining: 1m 4s
2020:	learn: 0.2075811	test: 0.2149282	best: 0.2149282 (2020)	total: 36.6s	remaining: 1m 3s
2040:	learn: 0.2073757	test: 0.2147984	best: 0.2147969 (2039)	total: 37s	remaining: 1m 3s
2060:	learn: 0.2071913	test: 0.2147168	best: 0.2147159 (2059)	total: 37.3s	remaining: 1m 3s
2080:	learn: 0.2070173	test: 0.2146331	best: 0.2146331 (2080)	total: 37.7s	remaining: 1m 2s
2100:	learn: 0.2068321	test: 0.2145509	best: 0.2145509 (2100)	total: 38s	remaining: 1m 2s
2120:	learn: 0.2066350	test: 0.2144655	best: 0.2144655 (2120)	total: 38.4s	remaining: 1m 1s
2140:	learn: 0.2064034	test: 0.2143233	best: 0.2143233 (2140)	total: 38.8s	remaining: 1m 1s
2160:	learn: 0.2062301	test: 0.2142386	best: 0.2142386 (2160)	total: 39.1s	remaining: 1m 1s
2180:	learn: 0.2060215	test: 0.2141417	best: 0.2141417 (2180)	total: 39.5s	remaining: 1m
2200:	learn: 0.2058563	test: 0.2141046	best: 0.2141037 (2198)	total: 39.9s	remaining: 1m
2220:	learn: 0.2056898	test: 0.2140384	best: 0.2140384 (2220)	total: 40.2s	remaining: 1m
2240:	learn: 0.2055031	test: 0.2139382	best: 0.2139381 (2239)	total: 40.6s	remaining: 59.8s
2260:	learn: 0.2053301	test: 0.2138408	best: 0.2138408 (2260)	total: 41s	remaining: 59.4s
2280:	learn: 0.2051563	test: 0.2137545	best: 0.2137545 (2280)	total: 41.3s	remaining: 59.1s
2300:	learn: 0.2049926	test: 0.2136765	best: 0.2136765 (2300)	total: 41.7s	remaining: 58.7s
2320:	learn: 0.2048470	test: 0.2136166	best: 0.2136166 (2320)	total: 42.1s	remaining: 58.3s
2340:	learn: 0.2047041	test: 0.2135699	best: 0.2135699 (2340)	total: 42.4s	remaining: 58s
2360:	learn: 0.2045453	test: 0.2134914	best: 0.2134914 (2360)	total: 42.8s	remaining: 57.6s
2380:	learn: 0.2043603	test: 0.2134071	best: 0.2134071 (2380)	total: 43.2s	remaining: 57.3s
2400:	learn: 0.2041985	test: 0.2133303	best: 0.2133303 (2400)	total: 43.5s	remaining: 56.9s
2420:	learn: 0.2040425	test: 0.2132629	best: 0.2132629 (2420)	total: 43.9s	remaining: 56.6s
2440:	learn: 0.2038933	test: 0.2131658	best: 0.2131658 (2440)	total: 44.3s	remaining: 56.2s
2460:	learn: 0.2037331	test: 0.2130891	best: 0.2130891 (2460)	total: 44.7s	remaining: 55.9s
2480:	learn: 0.2035492	test: 0.2129921	best: 0.2129921 (2480)	total: 45s	remaining: 55.5s
2500:	learn: 0.2033636	test: 0.2128925	best: 0.2128925 (2500)	total: 45.4s	remaining: 55.1s
2520:	learn: 0.2032248	test: 0.2128387	best: 0.2128387 (2520)	total: 45.7s	remaining: 54.8s
2540:	learn: 0.2030497	test: 0.2127670	best: 0.2127670 (2540)	total: 46.1s	remaining: 54.4s
2560:	learn: 0.2028774	test: 0.2127002	best: 0.2126988 (2559)	total: 46.5s	remaining: 54.1s
2580:	learn: 0.2027291	test: 0.2126574	best: 0.2126555 (2576)	total: 46.8s	remaining: 53.7s
2600:	learn: 0.2025995	test: 0.2125977	best: 0.2125977 (2600)	total: 47.2s	remaining: 53.4s
2620:	learn: 0.2024457	test: 0.2125178	best: 0.2125178 (2620)	total: 47.6s	remaining: 53s
2640:	learn: 0.2022902	test: 0.2124451	best: 0.2124451 (2640)	total: 47.9s	remaining: 52.6s
2660:	learn: 0.2021535	test: 0.2124079	best: 0.2124077 (2658)	total: 48.3s	remaining: 52.3s
2680:	learn: 0.2020022	test: 0.2123451	best: 0.2123435 (2679)	total: 48.7s	remaining: 51.9s
2700:	learn: 0.2018629	test: 0.2122679	best: 0.2122670 (2699)	total: 49.1s	remaining: 51.6s
2720:	learn: 0.2017333	test: 0.2122409	best: 0.2122402 (2718)	total: 49.4s	remaining: 51.2s
2740:	learn: 0.2015660	test: 0.2121857	best: 0.2121857 (2740)	total: 49.8s	remaining: 50.9s
2760:	learn: 0.2014351	test: 0.2121240	best: 0.2121226 (2759)	total: 50.2s	remaining: 50.5s
2780:	learn: 0.2013003	test: 0.2120896	best: 0.2120896 (2780)	total: 50.5s	remaining: 50.1s
2800:	learn: 0.2011122	test: 0.2119874	best: 0.2119874 (2800)	total: 50.9s	remaining: 49.8s
2820:	learn: 0.2009849	test: 0.2119362	best: 0.2119345 (2819)	total: 51.3s	remaining: 49.5s
2840:	learn: 0.2007979	test: 0.2118342	best: 0.2118336 (2838)	total: 51.7s	remaining: 49.1s
2860:	learn: 0.2006738	test: 0.2117815	best: 0.2117799 (2859)	total: 52s	remaining: 48.8s
2880:	learn: 0.2005266	test: 0.2117226	best: 0.2117226 (2880)	total: 52.4s	remaining: 48.4s
2900:	learn: 0.2003948	test: 0.2116755	best: 0.2116755 (2900)	total: 52.8s	remaining: 48.1s
2920:	learn: 0.2002587	test: 0.2116405	best: 0.2116405 (2920)	total: 53.2s	remaining: 47.7s
2940:	learn: 0.2001364	test: 0.2115845	best: 0.2115828 (2939)	total: 53.6s	remaining: 47.4s
2960:	learn: 0.1999978	test: 0.2115410	best: 0.2115410 (2960)	total: 54s	remaining: 47s
2980:	learn: 0.1998647	test: 0.2115027	best: 0.2114996 (2977)	total: 54.3s	remaining: 46.7s
3000:	learn: 0.1997192	test: 0.2114402	best: 0.2114402 (3000)	total: 54.7s	remaining: 46.3s
3020:	learn: 0.1995562	test: 0.2113643	best: 0.2113626 (3019)	total: 55.1s	remaining: 46s
3040:	learn: 0.1994169	test: 0.2113145	best: 0.2113145 (3040)	total: 55.5s	remaining: 45.6s
3060:	learn: 0.1992730	test: 0.2112636	best: 0.2112636 (3060)	total: 55.8s	remaining: 45.2s
3080:	learn: 0.1991221	test: 0.2112049	best: 0.2112042 (3079)	total: 56.2s	remaining: 44.9s
3100:	learn: 0.1989941	test: 0.2111528	best: 0.2111528 (3100)	total: 56.6s	remaining: 44.5s
3120:	learn: 0.1988604	test: 0.2110869	best: 0.2110869 (3120)	total: 57s	remaining: 44.2s
3140:	learn: 0.1987173	test: 0.2110235	best: 0.2110235 (3140)	total: 57.3s	remaining: 43.8s
3160:	learn: 0.1985807	test: 0.2109647	best: 0.2109647 (3160)	total: 57.7s	remaining: 43.5s
3180:	learn: 0.1984480	test: 0.2109085	best: 0.2109085 (3180)	total: 58.1s	remaining: 43.1s
3200:	learn: 0.1983250	test: 0.2108651	best: 0.2108651 (3200)	total: 58.5s	remaining: 42.8s
3220:	learn: 0.1981918	test: 0.2108257	best: 0.2108255 (3219)	total: 58.8s	remaining: 42.4s
3240:	learn: 0.1980239	test: 0.2107485	best: 0.2107485 (3240)	total: 59.2s	remaining: 42s
3260:	learn: 0.1978950	test: 0.2106937	best: 0.2106937 (3260)	total: 59.6s	remaining: 41.7s
3280:	learn: 0.1977485	test: 0.2106419	best: 0.2106406 (3279)	total: 60s	remaining: 41.3s
3300:	learn: 0.1976068	test: 0.2105837	best: 0.2105837 (3300)	total: 1m	remaining: 41s
3320:	learn: 0.1974920	test: 0.2105442	best: 0.2105442 (3320)	total: 1m	remaining: 40.6s
3340:	learn: 0.1973629	test: 0.2105059	best: 0.2105049 (3339)	total: 1m 1s	remaining: 40.3s
3360:	learn: 0.1972246	test: 0.2104446	best: 0.2104446 (3360)	total: 1m 1s	remaining: 39.9s
3380:	learn: 0.1970701	test: 0.2104086	best: 0.2104054 (3378)	total: 1m 1s	remaining: 39.5s
3400:	learn: 0.1969292	test: 0.2103588	best: 0.2103560 (3396)	total: 1m 2s	remaining: 39.2s
3420:	learn: 0.1968081	test: 0.2103175	best: 0.2103175 (3420)	total: 1m 2s	remaining: 38.8s
3440:	learn: 0.1966654	test: 0.2102661	best: 0.2102647 (3439)	total: 1m 3s	remaining: 38.5s
3460:	learn: 0.1965286	test: 0.2102460	best: 0.2102383 (3455)	total: 1m 3s	remaining: 38.1s
3480:	learn: 0.1964367	test: 0.2102298	best: 0.2102293 (3475)	total: 1m 3s	remaining: 37.7s
3500:	learn: 0.1963039	test: 0.2101697	best: 0.2101697 (3500)	total: 1m 4s	remaining: 37.4s
3520:	learn: 0.1961938	test: 0.2101356	best: 0.2101356 (3520)	total: 1m 4s	remaining: 37s
3540:	learn: 0.1960651	test: 0.2101018	best: 0.2101018 (3540)	total: 1m 4s	remaining: 36.6s
3560:	learn: 0.1959438	test: 0.2100648	best: 0.2100648 (3560)	total: 1m 5s	remaining: 36.3s
3580:	learn: 0.1958219	test: 0.2100371	best: 0.2100371 (3580)	total: 1m 5s	remaining: 35.9s
3600:	learn: 0.1956882	test: 0.2099883	best: 0.2099883 (3600)	total: 1m 6s	remaining: 35.6s
3620:	learn: 0.1955858	test: 0.2099727	best: 0.2099727 (3620)	total: 1m 6s	remaining: 35.2s
3640:	learn: 0.1954473	test: 0.2099155	best: 0.2099155 (3640)	total: 1m 6s	remaining: 34.8s
3660:	learn: 0.1953235	test: 0.2098754	best: 0.2098733 (3659)	total: 1m 7s	remaining: 34.5s
3680:	learn: 0.1951822	test: 0.2098300	best: 0.2098300 (3680)	total: 1m 7s	remaining: 34.1s
3700:	learn: 0.1950666	test: 0.2097867	best: 0.2097867 (3700)	total: 1m 7s	remaining: 33.7s
3720:	learn: 0.1949651	test: 0.2097628	best: 0.2097619 (3718)	total: 1m 8s	remaining: 33.4s
3740:	learn: 0.1948431	test: 0.2097334	best: 0.2097319 (3738)	total: 1m 8s	remaining: 33s
3760:	learn: 0.1947332	test: 0.2097013	best: 0.2097011 (3759)	total: 1m 8s	remaining: 32.6s
3780:	learn: 0.1945939	test: 0.2096569	best: 0.2096569 (3780)	total: 1m 9s	remaining: 32.3s
3800:	learn: 0.1944699	test: 0.2096275	best: 0.2096275 (3800)	total: 1m 9s	remaining: 31.9s
3820:	learn: 0.1943554	test: 0.2095979	best: 0.2095979 (3820)	total: 1m 10s	remaining: 31.5s
3840:	learn: 0.1942365	test: 0.2095445	best: 0.2095445 (3840)	total: 1m 10s	remaining: 31.2s
3860:	learn: 0.1941126	test: 0.2095182	best: 0.2095182 (3860)	total: 1m 10s	remaining: 30.8s
3880:	learn: 0.1940151	test: 0.2094730	best: 0.2094730 (3880)	total: 1m 11s	remaining: 30.5s
3900:	learn: 0.1938848	test: 0.2094403	best: 0.2094374 (3898)	total: 1m 11s	remaining: 30.1s
3920:	learn: 0.1937681	test: 0.2093942	best: 0.2093942 (3920)	total: 1m 11s	remaining: 29.7s
3940:	learn: 0.1936186	test: 0.2093287	best: 0.2093287 (3940)	total: 1m 12s	remaining: 29.4s
3960:	learn: 0.1935090	test: 0.2093025	best: 0.2093025 (3960)	total: 1m 12s	remaining: 29s
3980:	learn: 0.1934091	test: 0.2092927	best: 0.2092915 (3978)	total: 1m 13s	remaining: 28.6s
4000:	learn: 0.1932592	test: 0.2092449	best: 0.2092421 (3999)	total: 1m 13s	remaining: 28.3s
4020:	learn: 0.1931165	test: 0.2091991	best: 0.2091991 (4020)	total: 1m 13s	remaining: 27.9s
4040:	learn: 0.1930182	test: 0.2091833	best: 0.2091796 (4037)	total: 1m 14s	remaining: 27.5s
4060:	learn: 0.1929072	test: 0.2091747	best: 0.2091727 (4052)	total: 1m 14s	remaining: 27.2s
4080:	learn: 0.1927951	test: 0.2091298	best: 0.2091298 (4080)	total: 1m 14s	remaining: 26.8s
4100:	learn: 0.1926781	test: 0.2090861	best: 0.2090861 (4100)	total: 1m 15s	remaining: 26.5s
4120:	learn: 0.1925662	test: 0.2090497	best: 0.2090497 (4120)	total: 1m 15s	remaining: 26.1s
4140:	learn: 0.1924358	test: 0.2089973	best: 0.2089973 (4140)	total: 1m 16s	remaining: 25.7s
4160:	learn: 0.1923512	test: 0.2090012	best: 0.2089919 (4144)	total: 1m 16s	remaining: 25.4s
4180:	learn: 0.1922283	test: 0.2089365	best: 0.2089363 (4179)	total: 1m 16s	remaining: 25s
4200:	learn: 0.1921098	test: 0.2088900	best: 0.2088900 (4200)	total: 1m 17s	remaining: 24.6s
4220:	learn: 0.1919903	test: 0.2088488	best: 0.2088488 (4220)	total: 1m 17s	remaining: 24.3s
4240:	learn: 0.1918878	test: 0.2088310	best: 0.2088310 (4240)	total: 1m 18s	remaining: 23.9s
4260:	learn: 0.1917880	test: 0.2088052	best: 0.2088052 (4260)	total: 1m 18s	remaining: 23.5s
4280:	learn: 0.1916720	test: 0.2087691	best: 0.2087681 (4277)	total: 1m 18s	remaining: 23.2s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404088	test: 0.6403363	best: 0.6403363 (0)	total: 8.95ms	remaining: 8.95ms
1:	learn: 0.5954912	test: 0.5953480	best: 0.5953480 (1)	total: 17.7ms	remaining: 0us
bestTest = 0.5953480035
bestIteration = 1
0:	learn: 0.6413678	test: 0.6412252	best: 0.6412252 (0)	total: 16.8ms	remaining: 1m 31s
20:	learn: 0.3353469	test: 0.3336807	best: 0.3336807 (20)	total: 408ms	remaining: 1m 45s
40:	learn: 0.3023496	test: 0.3004106	best: 0.3004106 (40)	total: 798ms	remaining: 1m 45s
60:	learn: 0.2885451	test: 0.2867023	best: 0.2867023 (60)	total: 1.18s	remaining: 1m 44s
80:	learn: 0.2803732	test: 0.2783983	best: 0.2783983 (80)	total: 1.55s	remaining: 1m 42s
100:	learn: 0.2750163	test: 0.2731616	best: 0.2731616 (100)	total: 1.91s	remaining: 1m 41s
120:	learn: 0.2705284	test: 0.2687671	best: 0.2687671 (120)	total: 2.26s	remaining: 1m 39s
140:	learn: 0.2661491	test: 0.2642431	best: 0.2642431 (140)	total: 2.64s	remaining: 1m 39s
160:	learn: 0.2617617	test: 0.2597578	best: 0.2597578 (160)	total: 3.02s	remaining: 1m 39s
180:	learn: 0.2581400	test: 0.2564254	best: 0.2564254 (180)	total: 3.37s	remaining: 1m 38s
200:	learn: 0.2551308	test: 0.2534239	best: 0.2534239 (200)	total: 3.74s	remaining: 1m 37s
220:	learn: 0.2530783	test: 0.2514382	best: 0.2514382 (220)	total: 4.11s	remaining: 1m 37s
240:	learn: 0.2509313	test: 0.2493896	best: 0.2493896 (240)	total: 4.48s	remaining: 1m 36s
260:	learn: 0.2487408	test: 0.2473136	best: 0.2473136 (260)	total: 4.84s	remaining: 1m 36s
280:	learn: 0.2469849	test: 0.2457347	best: 0.2457347 (280)	total: 5.2s	remaining: 1m 35s
300:	learn: 0.2453746	test: 0.2442703	best: 0.2442703 (300)	total: 5.55s	remaining: 1m 35s
320:	learn: 0.2440381	test: 0.2430385	best: 0.2430385 (320)	total: 5.92s	remaining: 1m 34s
340:	learn: 0.2426774	test: 0.2418066	best: 0.2418066 (340)	total: 6.28s	remaining: 1m 34s
360:	learn: 0.2414751	test: 0.2408005	best: 0.2408005 (360)	total: 6.63s	remaining: 1m 33s
380:	learn: 0.2404707	test: 0.2398849	best: 0.2398849 (380)	total: 6.98s	remaining: 1m 32s
400:	learn: 0.2393029	test: 0.2388208	best: 0.2388208 (400)	total: 7.34s	remaining: 1m 32s
420:	learn: 0.2381823	test: 0.2378435	best: 0.2378435 (420)	total: 7.69s	remaining: 1m 31s
440:	learn: 0.2372596	test: 0.2369919	best: 0.2369919 (440)	total: 8.05s	remaining: 1m 31s
460:	learn: 0.2363852	test: 0.2362231	best: 0.2362231 (460)	total: 8.39s	remaining: 1m 30s
480:	learn: 0.2355041	test: 0.2354371	best: 0.2354371 (480)	total: 8.75s	remaining: 1m 30s
500:	learn: 0.2345750	test: 0.2346257	best: 0.2346257 (500)	total: 9.12s	remaining: 1m 30s
520:	learn: 0.2337403	test: 0.2338826	best: 0.2338826 (520)	total: 9.49s	remaining: 1m 29s
540:	learn: 0.2330749	test: 0.2333189	best: 0.2333189 (540)	total: 9.85s	remaining: 1m 29s
560:	learn: 0.2321170	test: 0.2324858	best: 0.2324858 (560)	total: 10.2s	remaining: 1m 29s
580:	learn: 0.2312671	test: 0.2317603	best: 0.2317603 (580)	total: 10.6s	remaining: 1m 28s
600:	learn: 0.2305979	test: 0.2312066	best: 0.2312066 (600)	total: 11s	remaining: 1m 28s
620:	learn: 0.2300233	test: 0.2307776	best: 0.2307776 (620)	total: 11.3s	remaining: 1m 28s
640:	learn: 0.2292828	test: 0.2301497	best: 0.2301497 (640)	total: 11.7s	remaining: 1m 27s
660:	learn: 0.2284872	test: 0.2294437	best: 0.2294437 (660)	total: 12s	remaining: 1m 27s
680:	learn: 0.2278489	test: 0.2288979	best: 0.2288979 (680)	total: 12.4s	remaining: 1m 26s
700:	learn: 0.2273271	test: 0.2285368	best: 0.2285368 (700)	total: 12.7s	remaining: 1m 26s
720:	learn: 0.2267715	test: 0.2280947	best: 0.2280947 (720)	total: 13.1s	remaining: 1m 25s
740:	learn: 0.2262839	test: 0.2277215	best: 0.2277215 (740)	total: 13.4s	remaining: 1m 25s
760:	learn: 0.2257465	test: 0.2272737	best: 0.2272737 (760)	total: 13.8s	remaining: 1m 25s
780:	learn: 0.2252323	test: 0.2268962	best: 0.2268962 (780)	total: 14.2s	remaining: 1m 24s
800:	learn: 0.2247166	test: 0.2264869	best: 0.2264869 (800)	total: 14.5s	remaining: 1m 24s
820:	learn: 0.2243245	test: 0.2261868	best: 0.2261868 (820)	total: 14.9s	remaining: 1m 23s
840:	learn: 0.2238478	test: 0.2258032	best: 0.2258032 (840)	total: 15.3s	remaining: 1m 23s
860:	learn: 0.2233595	test: 0.2254350	best: 0.2254350 (860)	total: 15.6s	remaining: 1m 23s
880:	learn: 0.2228993	test: 0.2251039	best: 0.2251039 (880)	total: 16s	remaining: 1m 22s
900:	learn: 0.2224242	test: 0.2247267	best: 0.2247267 (900)	total: 16.3s	remaining: 1m 22s
920:	learn: 0.2218968	test: 0.2243252	best: 0.2243252 (920)	total: 16.7s	remaining: 1m 22s
940:	learn: 0.2215378	test: 0.2240568	best: 0.2240568 (940)	total: 17s	remaining: 1m 21s
960:	learn: 0.2211492	test: 0.2237597	best: 0.2237597 (960)	total: 17.4s	remaining: 1m 21s
980:	learn: 0.2207733	test: 0.2235236	best: 0.2235236 (980)	total: 17.7s	remaining: 1m 20s
1000:	learn: 0.2204075	test: 0.2232145	best: 0.2232145 (1000)	total: 18.1s	remaining: 1m 20s
1020:	learn: 0.2200559	test: 0.2229696	best: 0.2229696 (1020)	total: 18.5s	remaining: 1m 20s
1040:	learn: 0.2196901	test: 0.2227428	best: 0.2227422 (1039)	total: 18.8s	remaining: 1m 19s
1060:	learn: 0.2192926	test: 0.2224317	best: 0.2224317 (1060)	total: 19.2s	remaining: 1m 19s
1080:	learn: 0.2189812	test: 0.2222115	best: 0.2222115 (1080)	total: 19.6s	remaining: 1m 19s
1100:	learn: 0.2186379	test: 0.2219972	best: 0.2219972 (1100)	total: 19.9s	remaining: 1m 18s
1120:	learn: 0.2182712	test: 0.2217654	best: 0.2217654 (1120)	total: 20.3s	remaining: 1m 18s
1140:	learn: 0.2179850	test: 0.2215783	best: 0.2215783 (1140)	total: 20.6s	remaining: 1m 18s
1160:	learn: 0.2176347	test: 0.2213277	best: 0.2213277 (1160)	total: 21s	remaining: 1m 17s
1180:	learn: 0.2173179	test: 0.2210570	best: 0.2210570 (1180)	total: 21.3s	remaining: 1m 17s
1200:	learn: 0.2170000	test: 0.2208579	best: 0.2208579 (1200)	total: 21.7s	remaining: 1m 16s
1220:	learn: 0.2167180	test: 0.2207065	best: 0.2207065 (1220)	total: 22s	remaining: 1m 16s
1240:	learn: 0.2164529	test: 0.2205631	best: 0.2205631 (1240)	total: 22.4s	remaining: 1m 16s
1260:	learn: 0.2161241	test: 0.2203305	best: 0.2203305 (1260)	total: 22.8s	remaining: 1m 15s
1280:	learn: 0.2158714	test: 0.2201758	best: 0.2201758 (1280)	total: 23.1s	remaining: 1m 15s
1300:	learn: 0.2155872	test: 0.2199914	best: 0.2199914 (1300)	total: 23.5s	remaining: 1m 14s
1320:	learn: 0.2153413	test: 0.2198643	best: 0.2198643 (1320)	total: 23.8s	remaining: 1m 14s
1340:	learn: 0.2150500	test: 0.2196825	best: 0.2196825 (1340)	total: 24.2s	remaining: 1m 14s
1360:	learn: 0.2147558	test: 0.2195052	best: 0.2195052 (1360)	total: 24.6s	remaining: 1m 13s
1380:	learn: 0.2145095	test: 0.2193623	best: 0.2193623 (1380)	total: 24.9s	remaining: 1m 13s
1400:	learn: 0.2142651	test: 0.2192243	best: 0.2192243 (1400)	total: 25.3s	remaining: 1m 13s
1420:	learn: 0.2139882	test: 0.2190647	best: 0.2190647 (1420)	total: 25.6s	remaining: 1m 12s
1440:	learn: 0.2137764	test: 0.2189647	best: 0.2189647 (1440)	total: 26s	remaining: 1m 12s
1460:	learn: 0.2134821	test: 0.2187817	best: 0.2187817 (1460)	total: 26.4s	remaining: 1m 12s
1480:	learn: 0.2132634	test: 0.2186838	best: 0.2186838 (1480)	total: 26.7s	remaining: 1m 11s
1500:	learn: 0.2129923	test: 0.2185011	best: 0.2185011 (1500)	total: 27.1s	remaining: 1m 11s
1520:	learn: 0.2127844	test: 0.2183850	best: 0.2183850 (1520)	total: 27.4s	remaining: 1m 10s
1540:	learn: 0.2125620	test: 0.2182537	best: 0.2182537 (1540)	total: 27.8s	remaining: 1m 10s
1560:	learn: 0.2123000	test: 0.2180672	best: 0.2180672 (1560)	total: 28.2s	remaining: 1m 10s
1580:	learn: 0.2120860	test: 0.2179435	best: 0.2179435 (1580)	total: 28.5s	remaining: 1m 9s
1600:	learn: 0.2118327	test: 0.2177952	best: 0.2177952 (1600)	total: 28.9s	remaining: 1m 9s
1620:	learn: 0.2115771	test: 0.2176557	best: 0.2176557 (1620)	total: 29.3s	remaining: 1m 9s
1640:	learn: 0.2113532	test: 0.2175226	best: 0.2175226 (1640)	total: 29.6s	remaining: 1m 8s
1660:	learn: 0.2111106	test: 0.2173828	best: 0.2173828 (1660)	total: 30s	remaining: 1m 8s
1680:	learn: 0.2108978	test: 0.2172651	best: 0.2172651 (1680)	total: 30.4s	remaining: 1m 8s
1700:	learn: 0.2106579	test: 0.2171646	best: 0.2171646 (1700)	total: 30.7s	remaining: 1m 7s
1720:	learn: 0.2104601	test: 0.2170713	best: 0.2170713 (1720)	total: 31.1s	remaining: 1m 7s
1740:	learn: 0.2102272	test: 0.2169372	best: 0.2169356 (1739)	total: 31.5s	remaining: 1m 7s
1760:	learn: 0.2099564	test: 0.2167586	best: 0.2167586 (1760)	total: 31.8s	remaining: 1m 6s
1780:	learn: 0.2097660	test: 0.2166700	best: 0.2166700 (1780)	total: 32.2s	remaining: 1m 6s
1800:	learn: 0.2095401	test: 0.2165329	best: 0.2165329 (1800)	total: 32.6s	remaining: 1m 6s
1820:	learn: 0.2093212	test: 0.2163895	best: 0.2163895 (1820)	total: 32.9s	remaining: 1m 5s
1840:	learn: 0.2091203	test: 0.2162721	best: 0.2162721 (1840)	total: 33.3s	remaining: 1m 5s
1860:	learn: 0.2089174	test: 0.2161806	best: 0.2161806 (1860)	total: 33.6s	remaining: 1m 4s
1880:	learn: 0.2087281	test: 0.2160663	best: 0.2160663 (1880)	total: 34s	remaining: 1m 4s
1900:	learn: 0.2085158	test: 0.2159702	best: 0.2159702 (1900)	total: 34.4s	remaining: 1m 4s
1920:	learn: 0.2083098	test: 0.2158538	best: 0.2158538 (1920)	total: 34.7s	remaining: 1m 3s
1940:	learn: 0.2081273	test: 0.2157434	best: 0.2157416 (1938)	total: 35.1s	remaining: 1m 3s
1960:	learn: 0.2079508	test: 0.2156657	best: 0.2156657 (1960)	total: 35.4s	remaining: 1m 3s
1980:	learn: 0.2077714	test: 0.2155856	best: 0.2155856 (1980)	total: 35.8s	remaining: 1m 2s
2000:	learn: 0.2075697	test: 0.2154727	best: 0.2154718 (1999)	total: 36.2s	remaining: 1m 2s
2020:	learn: 0.2073733	test: 0.2153478	best: 0.2153478 (2020)	total: 36.5s	remaining: 1m 2s
2040:	learn: 0.2071507	test: 0.2152082	best: 0.2152082 (2040)	total: 36.9s	remaining: 1m 1s
2060:	learn: 0.2069519	test: 0.2150900	best: 0.2150895 (2059)	total: 37.3s	remaining: 1m 1s
2080:	learn: 0.2067541	test: 0.2149955	best: 0.2149955 (2080)	total: 37.6s	remaining: 1m 1s
2100:	learn: 0.2065778	test: 0.2149184	best: 0.2149183 (2099)	total: 38s	remaining: 1m
2120:	learn: 0.2064171	test: 0.2148516	best: 0.2148516 (2120)	total: 38.4s	remaining: 1m
2140:	learn: 0.2061961	test: 0.2147448	best: 0.2147448 (2140)	total: 38.7s	remaining: 59.9s
2160:	learn: 0.2060433	test: 0.2146628	best: 0.2146628 (2160)	total: 39.1s	remaining: 59.6s
2180:	learn: 0.2058391	test: 0.2145738	best: 0.2145738 (2180)	total: 39.5s	remaining: 59.3s
2200:	learn: 0.2057019	test: 0.2145149	best: 0.2145146 (2199)	total: 39.8s	remaining: 58.9s
2220:	learn: 0.2055438	test: 0.2144364	best: 0.2144364 (2220)	total: 40.2s	remaining: 58.5s
2240:	learn: 0.2053990	test: 0.2143667	best: 0.2143667 (2240)	total: 40.6s	remaining: 58.2s
2260:	learn: 0.2052245	test: 0.2142873	best: 0.2142873 (2260)	total: 40.9s	remaining: 57.8s
2280:	learn: 0.2050460	test: 0.2141921	best: 0.2141921 (2280)	total: 41.3s	remaining: 57.4s
2300:	learn: 0.2048777	test: 0.2141018	best: 0.2141018 (2300)	total: 41.6s	remaining: 57.1s
2320:	learn: 0.2047213	test: 0.2140370	best: 0.2140370 (2319)	total: 42s	remaining: 56.7s
2340:	learn: 0.2045467	test: 0.2139792	best: 0.2139792 (2340)	total: 42.4s	remaining: 56.3s
2360:	learn: 0.2043910	test: 0.2138983	best: 0.2138983 (2360)	total: 42.7s	remaining: 56s
2380:	learn: 0.2042470	test: 0.2138326	best: 0.2138326 (2380)	total: 43.1s	remaining: 55.6s
2400:	learn: 0.2040726	test: 0.2137319	best: 0.2137319 (2400)	total: 43.4s	remaining: 55.2s
2420:	learn: 0.2038725	test: 0.2136572	best: 0.2136553 (2419)	total: 43.8s	remaining: 54.9s
2440:	learn: 0.2037168	test: 0.2136082	best: 0.2136082 (2440)	total: 44.2s	remaining: 54.5s
2460:	learn: 0.2035505	test: 0.2135353	best: 0.2135353 (2460)	total: 44.5s	remaining: 54.2s
2480:	learn: 0.2033490	test: 0.2134313	best: 0.2134313 (2480)	total: 44.9s	remaining: 53.8s
2500:	learn: 0.2032142	test: 0.2133617	best: 0.2133617 (2500)	total: 45.3s	remaining: 53.5s
2520:	learn: 0.2030350	test: 0.2132689	best: 0.2132689 (2520)	total: 45.7s	remaining: 53.1s
2540:	learn: 0.2028687	test: 0.2132193	best: 0.2132193 (2540)	total: 46s	remaining: 52.8s
2560:	learn: 0.2027253	test: 0.2131548	best: 0.2131548 (2560)	total: 46.4s	remaining: 52.4s
2580:	learn: 0.2025634	test: 0.2130738	best: 0.2130738 (2580)	total: 46.8s	remaining: 52.1s
2600:	learn: 0.2024103	test: 0.2130037	best: 0.2130037 (2600)	total: 47.1s	remaining: 51.7s
2620:	learn: 0.2022806	test: 0.2129606	best: 0.2129606 (2620)	total: 47.5s	remaining: 51.4s
2640:	learn: 0.2021007	test: 0.2128762	best: 0.2128762 (2640)	total: 47.9s	remaining: 51s
2660:	learn: 0.2019236	test: 0.2127758	best: 0.2127758 (2660)	total: 48.3s	remaining: 50.7s
2680:	learn: 0.2017721	test: 0.2127211	best: 0.2127211 (2680)	total: 48.6s	remaining: 50.3s
2700:	learn: 0.2016089	test: 0.2126278	best: 0.2126278 (2700)	total: 49s	remaining: 49.9s
2720:	learn: 0.2014773	test: 0.2125898	best: 0.2125898 (2719)	total: 49.4s	remaining: 49.6s
2740:	learn: 0.2013192	test: 0.2125444	best: 0.2125444 (2740)	total: 49.7s	remaining: 49.2s
2760:	learn: 0.2011780	test: 0.2124890	best: 0.2124880 (2759)	total: 50.1s	remaining: 48.9s
2780:	learn: 0.2010469	test: 0.2124605	best: 0.2124601 (2777)	total: 50.5s	remaining: 48.5s
2800:	learn: 0.2008998	test: 0.2123982	best: 0.2123982 (2800)	total: 50.8s	remaining: 48.2s
2820:	learn: 0.2007731	test: 0.2123520	best: 0.2123520 (2820)	total: 51.2s	remaining: 47.8s
2840:	learn: 0.2006324	test: 0.2122863	best: 0.2122863 (2840)	total: 51.6s	remaining: 47.5s
2860:	learn: 0.2004964	test: 0.2122286	best: 0.2122286 (2860)	total: 51.9s	remaining: 47.1s
2880:	learn: 0.2003530	test: 0.2121940	best: 0.2121936 (2876)	total: 52.3s	remaining: 46.7s
2900:	learn: 0.2002015	test: 0.2121384	best: 0.2121384 (2900)	total: 52.7s	remaining: 46.4s
2920:	learn: 0.2000648	test: 0.2120738	best: 0.2120716 (2918)	total: 53.1s	remaining: 46s
2940:	learn: 0.1999128	test: 0.2120175	best: 0.2120174 (2939)	total: 53.4s	remaining: 45.7s
2960:	learn: 0.1997438	test: 0.2119428	best: 0.2119428 (2960)	total: 53.8s	remaining: 45.3s
2980:	learn: 0.1995820	test: 0.2118693	best: 0.2118693 (2980)	total: 54.2s	remaining: 45s
3000:	learn: 0.1994276	test: 0.2118130	best: 0.2118130 (3000)	total: 54.5s	remaining: 44.6s
3020:	learn: 0.1992765	test: 0.2117483	best: 0.2117483 (3020)	total: 54.9s	remaining: 44.2s
3040:	learn: 0.1991571	test: 0.2116961	best: 0.2116961 (3040)	total: 55.3s	remaining: 43.9s
3060:	learn: 0.1990274	test: 0.2116451	best: 0.2116418 (3056)	total: 55.7s	remaining: 43.5s
3080:	learn: 0.1988806	test: 0.2116151	best: 0.2116125 (3075)	total: 56s	remaining: 43.2s
3100:	learn: 0.1987605	test: 0.2115699	best: 0.2115699 (3100)	total: 56.4s	remaining: 42.8s
3120:	learn: 0.1986408	test: 0.2115359	best: 0.2115359 (3120)	total: 56.8s	remaining: 42.5s
3140:	learn: 0.1985037	test: 0.2114951	best: 0.2114951 (3140)	total: 57.1s	remaining: 42.1s
3160:	learn: 0.1983463	test: 0.2114004	best: 0.2114004 (3160)	total: 57.5s	remaining: 41.7s
3180:	learn: 0.1982275	test: 0.2113410	best: 0.2113410 (3179)	total: 57.9s	remaining: 41.4s
3200:	learn: 0.1981084	test: 0.2113093	best: 0.2113093 (3200)	total: 58.3s	remaining: 41s
3220:	learn: 0.1979911	test: 0.2112978	best: 0.2112957 (3219)	total: 58.6s	remaining: 40.7s
3240:	learn: 0.1978545	test: 0.2112237	best: 0.2112237 (3240)	total: 59s	remaining: 40.3s
3260:	learn: 0.1977409	test: 0.2111947	best: 0.2111943 (3259)	total: 59.4s	remaining: 39.9s
3280:	learn: 0.1976029	test: 0.2111377	best: 0.2111377 (3280)	total: 59.7s	remaining: 39.6s
3300:	learn: 0.1974843	test: 0.2110914	best: 0.2110914 (3300)	total: 1m	remaining: 39.2s
3320:	learn: 0.1973287	test: 0.2110429	best: 0.2110401 (3318)	total: 1m	remaining: 38.8s
3340:	learn: 0.1971933	test: 0.2109763	best: 0.2109763 (3340)	total: 1m	remaining: 38.5s
3360:	learn: 0.1970463	test: 0.2109108	best: 0.2109108 (3360)	total: 1m 1s	remaining: 38.1s
3380:	learn: 0.1968922	test: 0.2108745	best: 0.2108738 (3378)	total: 1m 1s	remaining: 37.8s
3400:	learn: 0.1967639	test: 0.2108259	best: 0.2108259 (3400)	total: 1m 1s	remaining: 37.4s
3420:	learn: 0.1966464	test: 0.2107889	best: 0.2107889 (3420)	total: 1m 2s	remaining: 37.1s
3440:	learn: 0.1965315	test: 0.2107550	best: 0.2107550 (3440)	total: 1m 2s	remaining: 36.7s
3460:	learn: 0.1964210	test: 0.2107512	best: 0.2107498 (3454)	total: 1m 3s	remaining: 36.3s
3480:	learn: 0.1963019	test: 0.2107259	best: 0.2107259 (3480)	total: 1m 3s	remaining: 36s
3500:	learn: 0.1961872	test: 0.2106945	best: 0.2106945 (3499)	total: 1m 3s	remaining: 35.6s
3520:	learn: 0.1960717	test: 0.2106389	best: 0.2106371 (3519)	total: 1m 4s	remaining: 35.3s
3540:	learn: 0.1959665	test: 0.2106165	best: 0.2106148 (3539)	total: 1m 4s	remaining: 34.9s
3560:	learn: 0.1958679	test: 0.2106016	best: 0.2106016 (3560)	total: 1m 4s	remaining: 34.5s
3580:	learn: 0.1957591	test: 0.2105840	best: 0.2105823 (3577)	total: 1m 5s	remaining: 34.2s
3600:	learn: 0.1956565	test: 0.2105624	best: 0.2105624 (3600)	total: 1m 5s	remaining: 33.8s
3620:	learn: 0.1955189	test: 0.2104897	best: 0.2104897 (3620)	total: 1m 6s	remaining: 33.5s
3640:	learn: 0.1953932	test: 0.2104476	best: 0.2104476 (3640)	total: 1m 6s	remaining: 33.1s
3660:	learn: 0.1952734	test: 0.2104005	best: 0.2104005 (3660)	total: 1m 6s	remaining: 32.7s
3680:	learn: 0.1951153	test: 0.2103316	best: 0.2103316 (3680)	total: 1m 7s	remaining: 32.4s
3700:	learn: 0.1949949	test: 0.2102895	best: 0.2102895 (3700)	total: 1m 7s	remaining: 32s
3720:	learn: 0.1948963	test: 0.2102642	best: 0.2102630 (3718)	total: 1m 7s	remaining: 31.7s
3740:	learn: 0.1947753	test: 0.2102179	best: 0.2102179 (3740)	total: 1m 8s	remaining: 31.3s
3760:	learn: 0.1946486	test: 0.2101730	best: 0.2101730 (3760)	total: 1m 8s	remaining: 30.9s
3780:	learn: 0.1945264	test: 0.2101140	best: 0.2101140 (3780)	total: 1m 9s	remaining: 30.6s
3800:	learn: 0.1944125	test: 0.2100753	best: 0.2100753 (3800)	total: 1m 9s	remaining: 30.2s
3820:	learn: 0.1942943	test: 0.2100233	best: 0.2100230 (3819)	total: 1m 9s	remaining: 29.9s
3840:	learn: 0.1941650	test: 0.2099715	best: 0.2099715 (3840)	total: 1m 10s	remaining: 29.5s
3860:	learn: 0.1940410	test: 0.2099280	best: 0.2099273 (3859)	total: 1m 10s	remaining: 29.1s
3880:	learn: 0.1939330	test: 0.2099127	best: 0.2099127 (3880)	total: 1m 10s	remaining: 28.8s
3900:	learn: 0.1937980	test: 0.2098630	best: 0.2098628 (3898)	total: 1m 11s	remaining: 28.4s
3920:	learn: 0.1936719	test: 0.2098122	best: 0.2098122 (3920)	total: 1m 11s	remaining: 28s
3940:	learn: 0.1935673	test: 0.2097915	best: 0.2097915 (3940)	total: 1m 12s	remaining: 27.7s
3960:	learn: 0.1934317	test: 0.2097549	best: 0.2097533 (3959)	total: 1m 12s	remaining: 27.3s
3980:	learn: 0.1933373	test: 0.2097248	best: 0.2097248 (3980)	total: 1m 12s	remaining: 27s
4000:	learn: 0.1932044	test: 0.2096828	best: 0.2096828 (4000)	total: 1m 13s	remaining: 26.6s
4020:	learn: 0.1930738	test: 0.2096324	best: 0.2096298 (4019)	total: 1m 13s	remaining: 26.2s
4040:	learn: 0.1929578	test: 0.2096059	best: 0.2096059 (4040)	total: 1m 13s	remaining: 25.9s
4060:	learn: 0.1928374	test: 0.2095773	best: 0.2095773 (4060)	total: 1m 14s	remaining: 25.5s
4080:	learn: 0.1927299	test: 0.2095611	best: 0.2095581 (4072)	total: 1m 14s	remaining: 25.2s
4100:	learn: 0.1926020	test: 0.2095347	best: 0.2095347 (4100)	total: 1m 15s	remaining: 24.8s
4120:	learn: 0.1924674	test: 0.2094929	best: 0.2094929 (4120)	total: 1m 15s	remaining: 24.4s
4140:	learn: 0.1923525	test: 0.2094739	best: 0.2094708 (4137)	total: 1m 15s	remaining: 24.1s
4160:	learn: 0.1922412	test: 0.2094488	best: 0.2094476 (4158)	total: 1m 16s	remaining: 23.7s
4180:	learn: 0.1921161	test: 0.2094324	best: 0.2094299 (4172)	total: 1m 16s	remaining: 23.3s
4200:	learn: 0.1920067	test: 0.2093783	best: 0.2093783 (4200)	total: 1m 16s	remaining: 23s
4220:	learn: 0.1918790	test: 0.2093221	best: 0.2093221 (4220)	total: 1m 17s	remaining: 22.6s
4240:	learn: 0.1917792	test: 0.2092929	best: 0.2092929 (4240)	total: 1m 17s	remaining: 22.2s
4260:	learn: 0.1916716	test: 0.2092690	best: 0.2092633 (4254)	total: 1m 18s	remaining: 21.9s
4280:	learn: 0.1915698	test: 0.2092493	best: 0.2092493 (4280)	total: 1m 18s	remaining: 21.5s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6405756	test: 0.6404119	best: 0.6404119 (0)	total: 9.33ms	remaining: 9.33ms
1:	learn: 0.5957452	test: 0.5954493	best: 0.5954493 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.5954493098
bestIteration = 1
0:	learn: 0.6415704	test: 0.6413785	best: 0.6413785 (0)	total: 16.9ms	remaining: 1m 33s
20:	learn: 0.3376541	test: 0.3356240	best: 0.3356240 (20)	total: 407ms	remaining: 1m 46s
40:	learn: 0.3039842	test: 0.3011668	best: 0.3011668 (40)	total: 785ms	remaining: 1m 45s
60:	learn: 0.2899157	test: 0.2862783	best: 0.2862783 (60)	total: 1.16s	remaining: 1m 44s
80:	learn: 0.2812661	test: 0.2773072	best: 0.2773072 (80)	total: 1.55s	remaining: 1m 44s
100:	learn: 0.2743564	test: 0.2703298	best: 0.2703298 (100)	total: 1.93s	remaining: 1m 43s
120:	learn: 0.2704780	test: 0.2665069	best: 0.2665069 (120)	total: 2.29s	remaining: 1m 42s
140:	learn: 0.2659620	test: 0.2618557	best: 0.2618557 (140)	total: 2.66s	remaining: 1m 42s
160:	learn: 0.2624891	test: 0.2583638	best: 0.2583638 (160)	total: 3.03s	remaining: 1m 41s
180:	learn: 0.2592827	test: 0.2551061	best: 0.2551061 (180)	total: 3.39s	remaining: 1m 40s
200:	learn: 0.2565846	test: 0.2525506	best: 0.2525506 (200)	total: 3.76s	remaining: 1m 39s
220:	learn: 0.2540480	test: 0.2501259	best: 0.2501259 (220)	total: 4.15s	remaining: 1m 39s
240:	learn: 0.2518300	test: 0.2478159	best: 0.2478159 (240)	total: 4.51s	remaining: 1m 39s
260:	learn: 0.2500845	test: 0.2462142	best: 0.2462142 (260)	total: 4.86s	remaining: 1m 38s
280:	learn: 0.2484707	test: 0.2446803	best: 0.2446803 (280)	total: 5.21s	remaining: 1m 37s
300:	learn: 0.2468810	test: 0.2431168	best: 0.2431168 (300)	total: 5.58s	remaining: 1m 37s
320:	learn: 0.2452682	test: 0.2416141	best: 0.2416141 (320)	total: 5.96s	remaining: 1m 36s
340:	learn: 0.2440491	test: 0.2404981	best: 0.2404981 (340)	total: 6.31s	remaining: 1m 36s
360:	learn: 0.2429788	test: 0.2395317	best: 0.2395317 (360)	total: 6.66s	remaining: 1m 35s
380:	learn: 0.2416116	test: 0.2381477	best: 0.2381477 (380)	total: 7.04s	remaining: 1m 35s
400:	learn: 0.2403758	test: 0.2370210	best: 0.2370210 (400)	total: 7.38s	remaining: 1m 34s
420:	learn: 0.2393736	test: 0.2361743	best: 0.2361743 (420)	total: 7.74s	remaining: 1m 34s
440:	learn: 0.2383399	test: 0.2352029	best: 0.2352029 (440)	total: 8.1s	remaining: 1m 33s
460:	learn: 0.2371151	test: 0.2340099	best: 0.2340099 (460)	total: 8.46s	remaining: 1m 33s
480:	learn: 0.2363571	test: 0.2333912	best: 0.2333912 (480)	total: 8.83s	remaining: 1m 32s
500:	learn: 0.2354696	test: 0.2325841	best: 0.2325841 (500)	total: 9.19s	remaining: 1m 32s
520:	learn: 0.2345383	test: 0.2318133	best: 0.2318133 (520)	total: 9.55s	remaining: 1m 32s
540:	learn: 0.2336629	test: 0.2310050	best: 0.2310050 (540)	total: 9.91s	remaining: 1m 31s
560:	learn: 0.2329125	test: 0.2303717	best: 0.2303717 (560)	total: 10.3s	remaining: 1m 31s
580:	learn: 0.2321283	test: 0.2297223	best: 0.2297223 (580)	total: 10.6s	remaining: 1m 30s
600:	learn: 0.2314683	test: 0.2291857	best: 0.2291857 (600)	total: 11s	remaining: 1m 30s
620:	learn: 0.2307706	test: 0.2286152	best: 0.2286152 (620)	total: 11.3s	remaining: 1m 29s
640:	learn: 0.2301342	test: 0.2280919	best: 0.2280919 (640)	total: 11.7s	remaining: 1m 29s
660:	learn: 0.2295082	test: 0.2276030	best: 0.2276030 (660)	total: 12.1s	remaining: 1m 29s
680:	learn: 0.2289151	test: 0.2271165	best: 0.2271165 (680)	total: 12.4s	remaining: 1m 28s
700:	learn: 0.2280340	test: 0.2262621	best: 0.2262621 (700)	total: 12.8s	remaining: 1m 28s
720:	learn: 0.2274237	test: 0.2256911	best: 0.2256911 (720)	total: 13.2s	remaining: 1m 28s
740:	learn: 0.2267881	test: 0.2251363	best: 0.2251363 (740)	total: 13.5s	remaining: 1m 27s
760:	learn: 0.2262317	test: 0.2246397	best: 0.2246397 (760)	total: 13.9s	remaining: 1m 27s
780:	learn: 0.2257101	test: 0.2242206	best: 0.2242206 (780)	total: 14.2s	remaining: 1m 26s
800:	learn: 0.2251175	test: 0.2237345	best: 0.2237345 (800)	total: 14.6s	remaining: 1m 26s
820:	learn: 0.2246841	test: 0.2234076	best: 0.2234076 (820)	total: 15s	remaining: 1m 26s
840:	learn: 0.2242570	test: 0.2231145	best: 0.2231145 (840)	total: 15.3s	remaining: 1m 25s
860:	learn: 0.2238149	test: 0.2227565	best: 0.2227565 (860)	total: 15.7s	remaining: 1m 25s
880:	learn: 0.2233962	test: 0.2224691	best: 0.2224691 (880)	total: 16s	remaining: 1m 24s
900:	learn: 0.2229600	test: 0.2221729	best: 0.2221729 (900)	total: 16.4s	remaining: 1m 24s
920:	learn: 0.2225786	test: 0.2219171	best: 0.2219171 (920)	total: 16.7s	remaining: 1m 24s
940:	learn: 0.2221630	test: 0.2216331	best: 0.2216331 (940)	total: 17.1s	remaining: 1m 23s
960:	learn: 0.2217131	test: 0.2212984	best: 0.2212984 (960)	total: 17.5s	remaining: 1m 23s
980:	learn: 0.2213663	test: 0.2210253	best: 0.2210253 (980)	total: 17.8s	remaining: 1m 22s
1000:	learn: 0.2210239	test: 0.2207949	best: 0.2207949 (1000)	total: 18.2s	remaining: 1m 22s
1020:	learn: 0.2206864	test: 0.2205626	best: 0.2205626 (1020)	total: 18.5s	remaining: 1m 22s
1040:	learn: 0.2202894	test: 0.2202715	best: 0.2202715 (1040)	total: 18.9s	remaining: 1m 21s
1060:	learn: 0.2198649	test: 0.2199549	best: 0.2199549 (1060)	total: 19.3s	remaining: 1m 21s
1080:	learn: 0.2195349	test: 0.2197387	best: 0.2197387 (1080)	total: 19.6s	remaining: 1m 21s
1100:	learn: 0.2192026	test: 0.2195373	best: 0.2195373 (1100)	total: 20s	remaining: 1m 20s
1120:	learn: 0.2188169	test: 0.2192776	best: 0.2192776 (1120)	total: 20.3s	remaining: 1m 20s
1140:	learn: 0.2184856	test: 0.2190389	best: 0.2190389 (1140)	total: 20.7s	remaining: 1m 19s
1160:	learn: 0.2182016	test: 0.2188843	best: 0.2188843 (1160)	total: 21.1s	remaining: 1m 19s
1180:	learn: 0.2178955	test: 0.2187018	best: 0.2187018 (1180)	total: 21.4s	remaining: 1m 19s
1200:	learn: 0.2175844	test: 0.2184934	best: 0.2184934 (1200)	total: 21.8s	remaining: 1m 18s
1220:	learn: 0.2172215	test: 0.2182102	best: 0.2182096 (1219)	total: 22.1s	remaining: 1m 18s
1240:	learn: 0.2169292	test: 0.2180654	best: 0.2180654 (1240)	total: 22.5s	remaining: 1m 17s
1260:	learn: 0.2166836	test: 0.2179170	best: 0.2179170 (1260)	total: 22.8s	remaining: 1m 17s
1280:	learn: 0.2163477	test: 0.2177212	best: 0.2177212 (1280)	total: 23.2s	remaining: 1m 17s
1300:	learn: 0.2160428	test: 0.2175015	best: 0.2175015 (1300)	total: 23.6s	remaining: 1m 16s
1320:	learn: 0.2157339	test: 0.2173129	best: 0.2173129 (1320)	total: 24s	remaining: 1m 16s
1340:	learn: 0.2154136	test: 0.2171430	best: 0.2171430 (1340)	total: 24.3s	remaining: 1m 16s
1360:	learn: 0.2151113	test: 0.2169424	best: 0.2169424 (1360)	total: 24.7s	remaining: 1m 15s
1380:	learn: 0.2148380	test: 0.2168083	best: 0.2168083 (1380)	total: 25s	remaining: 1m 15s
1400:	learn: 0.2146171	test: 0.2167054	best: 0.2167054 (1400)	total: 25.4s	remaining: 1m 15s
1420:	learn: 0.2143614	test: 0.2165487	best: 0.2165487 (1420)	total: 25.8s	remaining: 1m 14s
1440:	learn: 0.2141594	test: 0.2164404	best: 0.2164404 (1440)	total: 26.1s	remaining: 1m 14s
1460:	learn: 0.2138946	test: 0.2162562	best: 0.2162562 (1460)	total: 26.5s	remaining: 1m 13s
1480:	learn: 0.2136177	test: 0.2161008	best: 0.2161008 (1480)	total: 26.9s	remaining: 1m 13s
1500:	learn: 0.2133447	test: 0.2159121	best: 0.2159121 (1500)	total: 27.2s	remaining: 1m 13s
1520:	learn: 0.2131285	test: 0.2157948	best: 0.2157942 (1519)	total: 27.6s	remaining: 1m 12s
1540:	learn: 0.2129019	test: 0.2157046	best: 0.2157046 (1540)	total: 27.9s	remaining: 1m 12s
1560:	learn: 0.2126200	test: 0.2155440	best: 0.2155440 (1560)	total: 28.3s	remaining: 1m 12s
1580:	learn: 0.2123753	test: 0.2154291	best: 0.2154291 (1580)	total: 28.7s	remaining: 1m 11s
1600:	learn: 0.2121523	test: 0.2152936	best: 0.2152936 (1600)	total: 29s	remaining: 1m 11s
1620:	learn: 0.2119090	test: 0.2151470	best: 0.2151470 (1620)	total: 29.4s	remaining: 1m 11s
1640:	learn: 0.2116891	test: 0.2150151	best: 0.2150151 (1640)	total: 29.8s	remaining: 1m 10s
1660:	learn: 0.2114765	test: 0.2149203	best: 0.2149187 (1658)	total: 30.1s	remaining: 1m 10s
1680:	learn: 0.2112034	test: 0.2147469	best: 0.2147469 (1680)	total: 30.5s	remaining: 1m 9s
1700:	learn: 0.2109927	test: 0.2146215	best: 0.2146215 (1700)	total: 30.8s	remaining: 1m 9s
1720:	learn: 0.2108103	test: 0.2145424	best: 0.2145423 (1719)	total: 31.2s	remaining: 1m 9s
1740:	learn: 0.2105556	test: 0.2143875	best: 0.2143841 (1739)	total: 31.6s	remaining: 1m 8s
1760:	learn: 0.2103381	test: 0.2142899	best: 0.2142899 (1760)	total: 31.9s	remaining: 1m 8s
1780:	learn: 0.2101580	test: 0.2142024	best: 0.2142024 (1780)	total: 32.3s	remaining: 1m 8s
1800:	learn: 0.2099620	test: 0.2141148	best: 0.2141148 (1800)	total: 32.6s	remaining: 1m 7s
1820:	learn: 0.2097434	test: 0.2140205	best: 0.2140205 (1820)	total: 33s	remaining: 1m 7s
1840:	learn: 0.2095418	test: 0.2139194	best: 0.2139194 (1840)	total: 33.4s	remaining: 1m 7s
1860:	learn: 0.2093487	test: 0.2138220	best: 0.2138220 (1860)	total: 33.7s	remaining: 1m 6s
1880:	learn: 0.2091783	test: 0.2137310	best: 0.2137310 (1880)	total: 34.1s	remaining: 1m 6s
1900:	learn: 0.2089710	test: 0.2136134	best: 0.2136134 (1900)	total: 34.5s	remaining: 1m 5s
1920:	learn: 0.2087825	test: 0.2135086	best: 0.2135086 (1920)	total: 34.8s	remaining: 1m 5s
1940:	learn: 0.2085661	test: 0.2133948	best: 0.2133948 (1940)	total: 35.2s	remaining: 1m 5s
1960:	learn: 0.2083868	test: 0.2133082	best: 0.2133082 (1960)	total: 35.5s	remaining: 1m 4s
1980:	learn: 0.2082105	test: 0.2132083	best: 0.2132039 (1979)	total: 35.9s	remaining: 1m 4s
2000:	learn: 0.2080174	test: 0.2131031	best: 0.2131031 (2000)	total: 36.3s	remaining: 1m 4s
2020:	learn: 0.2078074	test: 0.2129792	best: 0.2129792 (2020)	total: 36.6s	remaining: 1m 3s
2040:	learn: 0.2076291	test: 0.2129104	best: 0.2129104 (2040)	total: 37s	remaining: 1m 3s
2060:	learn: 0.2074642	test: 0.2128450	best: 0.2128450 (2060)	total: 37.4s	remaining: 1m 3s
2080:	learn: 0.2072635	test: 0.2127224	best: 0.2127224 (2080)	total: 37.7s	remaining: 1m 2s
2100:	learn: 0.2070233	test: 0.2126041	best: 0.2126041 (2100)	total: 38.1s	remaining: 1m 2s
2120:	learn: 0.2068670	test: 0.2125495	best: 0.2125495 (2120)	total: 38.4s	remaining: 1m 1s
2140:	learn: 0.2066892	test: 0.2124725	best: 0.2124725 (2140)	total: 38.8s	remaining: 1m 1s
2160:	learn: 0.2065082	test: 0.2123891	best: 0.2123891 (2160)	total: 39.2s	remaining: 1m 1s
2180:	learn: 0.2063074	test: 0.2122896	best: 0.2122896 (2180)	total: 39.5s	remaining: 1m
2200:	learn: 0.2061614	test: 0.2122320	best: 0.2122320 (2200)	total: 39.9s	remaining: 1m
2220:	learn: 0.2059470	test: 0.2121101	best: 0.2121101 (2220)	total: 40.3s	remaining: 1m
2240:	learn: 0.2057368	test: 0.2119999	best: 0.2119999 (2240)	total: 40.6s	remaining: 59.8s
2260:	learn: 0.2055754	test: 0.2119412	best: 0.2119412 (2260)	total: 41s	remaining: 59.5s
2280:	learn: 0.2053691	test: 0.2118181	best: 0.2118178 (2278)	total: 41.4s	remaining: 59.1s
2300:	learn: 0.2052073	test: 0.2117613	best: 0.2117613 (2300)	total: 41.7s	remaining: 58.8s
2320:	learn: 0.2050190	test: 0.2116460	best: 0.2116460 (2320)	total: 42.1s	remaining: 58.4s
2340:	learn: 0.2048145	test: 0.2115317	best: 0.2115317 (2340)	total: 42.5s	remaining: 58.1s
2360:	learn: 0.2046313	test: 0.2114679	best: 0.2114679 (2360)	total: 42.8s	remaining: 57.7s
2380:	learn: 0.2044801	test: 0.2113895	best: 0.2113895 (2380)	total: 43.2s	remaining: 57.3s
2400:	learn: 0.2043303	test: 0.2113191	best: 0.2113181 (2399)	total: 43.6s	remaining: 57s
2420:	learn: 0.2042013	test: 0.2112811	best: 0.2112811 (2420)	total: 43.9s	remaining: 56.6s
2440:	learn: 0.2040539	test: 0.2112416	best: 0.2112408 (2439)	total: 44.3s	remaining: 56.3s
2460:	learn: 0.2038919	test: 0.2111777	best: 0.2111777 (2460)	total: 44.7s	remaining: 55.9s
2480:	learn: 0.2037427	test: 0.2111232	best: 0.2111232 (2480)	total: 45s	remaining: 55.6s
2500:	learn: 0.2035895	test: 0.2110650	best: 0.2110650 (2500)	total: 45.4s	remaining: 55.2s
2520:	learn: 0.2034316	test: 0.2109837	best: 0.2109837 (2520)	total: 45.8s	remaining: 54.9s
2540:	learn: 0.2032587	test: 0.2108952	best: 0.2108952 (2540)	total: 46.2s	remaining: 54.5s
2560:	learn: 0.2030919	test: 0.2108328	best: 0.2108328 (2560)	total: 46.5s	remaining: 54.1s
2580:	learn: 0.2029650	test: 0.2107899	best: 0.2107832 (2577)	total: 46.9s	remaining: 53.8s
2600:	learn: 0.2028198	test: 0.2107505	best: 0.2107505 (2600)	total: 47.3s	remaining: 53.4s
2620:	learn: 0.2026757	test: 0.2107179	best: 0.2107125 (2615)	total: 47.6s	remaining: 53s
2640:	learn: 0.2025068	test: 0.2106561	best: 0.2106561 (2640)	total: 48s	remaining: 52.7s
2660:	learn: 0.2023427	test: 0.2105988	best: 0.2105988 (2660)	total: 48.3s	remaining: 52.3s
2680:	learn: 0.2021821	test: 0.2105383	best: 0.2105383 (2680)	total: 48.7s	remaining: 51.9s
2700:	learn: 0.2019871	test: 0.2104628	best: 0.2104628 (2700)	total: 49.1s	remaining: 51.6s
2720:	learn: 0.2018171	test: 0.2103978	best: 0.2103978 (2720)	total: 49.4s	remaining: 51.2s
2740:	learn: 0.2016517	test: 0.2103069	best: 0.2103069 (2740)	total: 49.8s	remaining: 50.9s
2760:	learn: 0.2014922	test: 0.2102404	best: 0.2102404 (2760)	total: 50.1s	remaining: 50.5s
2780:	learn: 0.2013398	test: 0.2101845	best: 0.2101845 (2780)	total: 50.5s	remaining: 50.1s
2800:	learn: 0.2011827	test: 0.2101328	best: 0.2101328 (2800)	total: 50.9s	remaining: 49.8s
2820:	learn: 0.2010347	test: 0.2100712	best: 0.2100712 (2820)	total: 51.3s	remaining: 49.4s
2840:	learn: 0.2008948	test: 0.2100233	best: 0.2100233 (2840)	total: 51.6s	remaining: 49.1s
2860:	learn: 0.2007400	test: 0.2099599	best: 0.2099582 (2859)	total: 52s	remaining: 48.7s
2880:	learn: 0.2005978	test: 0.2098823	best: 0.2098823 (2880)	total: 52.4s	remaining: 48.4s
2900:	learn: 0.2004602	test: 0.2098329	best: 0.2098321 (2899)	total: 52.7s	remaining: 48s
2920:	learn: 0.2003240	test: 0.2097820	best: 0.2097820 (2920)	total: 53.1s	remaining: 47.6s
2940:	learn: 0.2001694	test: 0.2097197	best: 0.2097197 (2940)	total: 53.5s	remaining: 47.3s
2960:	learn: 0.2000296	test: 0.2096747	best: 0.2096723 (2959)	total: 53.8s	remaining: 46.9s
2980:	learn: 0.1999042	test: 0.2096238	best: 0.2096236 (2979)	total: 54.2s	remaining: 46.5s
3000:	learn: 0.1997760	test: 0.2095495	best: 0.2095495 (3000)	total: 54.6s	remaining: 46.2s
3020:	learn: 0.1996425	test: 0.2095328	best: 0.2095319 (3015)	total: 54.9s	remaining: 45.8s
3040:	learn: 0.1995120	test: 0.2094945	best: 0.2094945 (3040)	total: 55.3s	remaining: 45.5s
3060:	learn: 0.1993749	test: 0.2094508	best: 0.2094491 (3059)	total: 55.7s	remaining: 45.1s
3080:	learn: 0.1992408	test: 0.2093880	best: 0.2093864 (3079)	total: 56s	remaining: 44.7s
3100:	learn: 0.1990811	test: 0.2093258	best: 0.2093239 (3098)	total: 56.4s	remaining: 44.4s
3120:	learn: 0.1989538	test: 0.2092782	best: 0.2092782 (3120)	total: 56.8s	remaining: 44s
3140:	learn: 0.1988199	test: 0.2092141	best: 0.2092141 (3140)	total: 57.1s	remaining: 43.7s
3160:	learn: 0.1986848	test: 0.2091652	best: 0.2091652 (3160)	total: 57.5s	remaining: 43.3s
3180:	learn: 0.1985360	test: 0.2090999	best: 0.2090999 (3180)	total: 57.9s	remaining: 42.9s
3200:	learn: 0.1983965	test: 0.2090293	best: 0.2090293 (3200)	total: 58.3s	remaining: 42.6s
3220:	learn: 0.1982709	test: 0.2089828	best: 0.2089828 (3220)	total: 58.7s	remaining: 42.2s
3240:	learn: 0.1981020	test: 0.2089019	best: 0.2089019 (3240)	total: 59s	remaining: 41.9s
3260:	learn: 0.1979714	test: 0.2088584	best: 0.2088569 (3259)	total: 59.4s	remaining: 41.5s
3280:	learn: 0.1978596	test: 0.2088303	best: 0.2088303 (3280)	total: 59.8s	remaining: 41.2s
3300:	learn: 0.1977330	test: 0.2087952	best: 0.2087944 (3298)	total: 1m	remaining: 40.8s
3320:	learn: 0.1976086	test: 0.2087548	best: 0.2087546 (3318)	total: 1m	remaining: 40.5s
3340:	learn: 0.1974861	test: 0.2087245	best: 0.2087245 (3340)	total: 1m	remaining: 40.1s
3360:	learn: 0.1973595	test: 0.2086805	best: 0.2086783 (3359)	total: 1m 1s	remaining: 39.7s
3380:	learn: 0.1972339	test: 0.2086553	best: 0.2086553 (3380)	total: 1m 1s	remaining: 39.4s
3400:	learn: 0.1970958	test: 0.2086162	best: 0.2086162 (3400)	total: 1m 2s	remaining: 39s
3420:	learn: 0.1969380	test: 0.2085357	best: 0.2085357 (3420)	total: 1m 2s	remaining: 38.7s
3440:	learn: 0.1968199	test: 0.2085072	best: 0.2085072 (3440)	total: 1m 2s	remaining: 38.3s
3460:	learn: 0.1966986	test: 0.2084735	best: 0.2084735 (3460)	total: 1m 3s	remaining: 37.9s
3480:	learn: 0.1965604	test: 0.2084197	best: 0.2084197 (3480)	total: 1m 3s	remaining: 37.6s
3500:	learn: 0.1964020	test: 0.2083370	best: 0.2083370 (3500)	total: 1m 3s	remaining: 37.2s
3520:	learn: 0.1962903	test: 0.2083161	best: 0.2083148 (3518)	total: 1m 4s	remaining: 36.9s
3540:	learn: 0.1961561	test: 0.2082707	best: 0.2082703 (3539)	total: 1m 4s	remaining: 36.5s
3560:	learn: 0.1960445	test: 0.2082447	best: 0.2082433 (3554)	total: 1m 5s	remaining: 36.1s
3580:	learn: 0.1959105	test: 0.2082071	best: 0.2082069 (3579)	total: 1m 5s	remaining: 35.8s
3600:	learn: 0.1958092	test: 0.2081788	best: 0.2081788 (3600)	total: 1m 5s	remaining: 35.4s
3620:	learn: 0.1957025	test: 0.2081407	best: 0.2081402 (3619)	total: 1m 6s	remaining: 35.1s
3640:	learn: 0.1955851	test: 0.2081262	best: 0.2081262 (3640)	total: 1m 6s	remaining: 34.7s
3660:	learn: 0.1954682	test: 0.2080712	best: 0.2080712 (3660)	total: 1m 6s	remaining: 34.3s
3680:	learn: 0.1953182	test: 0.2080005	best: 0.2080005 (3680)	total: 1m 7s	remaining: 34s
3700:	learn: 0.1951896	test: 0.2079580	best: 0.2079580 (3700)	total: 1m 7s	remaining: 33.6s
3720:	learn: 0.1950730	test: 0.2079136	best: 0.2079136 (3720)	total: 1m 7s	remaining: 33.3s
3740:	learn: 0.1949414	test: 0.2078704	best: 0.2078704 (3740)	total: 1m 8s	remaining: 32.9s
3760:	learn: 0.1948397	test: 0.2078558	best: 0.2078531 (3759)	total: 1m 8s	remaining: 32.5s
3780:	learn: 0.1947198	test: 0.2078274	best: 0.2078262 (3779)	total: 1m 9s	remaining: 32.2s
3800:	learn: 0.1945860	test: 0.2078042	best: 0.2077993 (3798)	total: 1m 9s	remaining: 31.8s
3820:	learn: 0.1944844	test: 0.2077925	best: 0.2077918 (3818)	total: 1m 9s	remaining: 31.4s
3840:	learn: 0.1943474	test: 0.2077508	best: 0.2077508 (3840)	total: 1m 10s	remaining: 31.1s
3860:	learn: 0.1942435	test: 0.2077140	best: 0.2077140 (3860)	total: 1m 10s	remaining: 30.7s
3880:	learn: 0.1941145	test: 0.2076682	best: 0.2076682 (3880)	total: 1m 10s	remaining: 30.4s
3900:	learn: 0.1939988	test: 0.2076354	best: 0.2076354 (3900)	total: 1m 11s	remaining: 30s
3920:	learn: 0.1939037	test: 0.2076258	best: 0.2076258 (3913)	total: 1m 11s	remaining: 29.6s
3940:	learn: 0.1937680	test: 0.2075861	best: 0.2075841 (3939)	total: 1m 12s	remaining: 29.3s
3960:	learn: 0.1936588	test: 0.2075723	best: 0.2075723 (3958)	total: 1m 12s	remaining: 28.9s
3980:	learn: 0.1935548	test: 0.2075537	best: 0.2075512 (3978)	total: 1m 12s	remaining: 28.6s
4000:	learn: 0.1934424	test: 0.2075204	best: 0.2075204 (4000)	total: 1m 13s	remaining: 28.2s
4020:	learn: 0.1933375	test: 0.2074752	best: 0.2074752 (4020)	total: 1m 13s	remaining: 27.8s
4040:	learn: 0.1932292	test: 0.2074422	best: 0.2074422 (4040)	total: 1m 14s	remaining: 27.5s
4060:	learn: 0.1931206	test: 0.2074287	best: 0.2074246 (4058)	total: 1m 14s	remaining: 27.1s
4080:	learn: 0.1930156	test: 0.2074061	best: 0.2074061 (4080)	total: 1m 14s	remaining: 26.8s
4100:	learn: 0.1929044	test: 0.2073787	best: 0.2073787 (4100)	total: 1m 15s	remaining: 26.4s
4120:	learn: 0.1927854	test: 0.2073442	best: 0.2073442 (4120)	total: 1m 15s	remaining: 26s
4140:	learn: 0.1926784	test: 0.2073270	best: 0.2073270 (4140)	total: 1m 15s	remaining: 25.7s
4160:	learn: 0.1925458	test: 0.2072800	best: 0.2072788 (4159)	total: 1m 16s	remaining: 25.3s
4180:	learn: 0.1924465	test: 0.2072475	best: 0.2072473 (4178)	total: 1m 16s	remaining: 24.9s
4200:	learn: 0.1923236	test: 0.2071888	best: 0.2071886 (4197)	total: 1m 17s	remaining: 24.6s
4220:	learn: 0.1921973	test: 0.2071729	best: 0.2071725 (4212)	total: 1m 17s	remaining: 24.2s
4240:	learn: 0.1920772	test: 0.2071492	best: 0.2071482 (4238)	total: 1m 17s	remaining: 23.9s
4260:	learn: 0.1919493	test: 0.2071085	best: 0.2071081 (4258)	total: 1m 18s	remaining: 23.5s
4280:	learn: 0.1918193	test: 0.2070879	best: 0.2070879 (4280)	total: 1m 18s	remaining: 23.1s

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L1\model.pkl
	0.959	 = Validation score   (roc_auc)
	812.77s	 = Training   runtime
	3.04s	 = Validation runtime
	22187.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 16536.22s of the 25386.50s of remaining time.
	Fitting ExtraTreesGini_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L1\utils\model_template.pkl
	Warning: Not enough memory to safely train model. Estimated to require 2.817 GB out of 5.487 GB available memory (51.332%)... (50.000% of avail memory is the max safe size)
	To force training the model, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.08 to avoid the error)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Not enough memory to train ExtraTreesGini_BAG_L1... Skipping this model.
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L1\utils\model_template.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 16535.90s of the 25386.19s of remaining time.
	Fitting ExtraTreesEntr_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
	Warning: Not enough memory to safely train model. Estimated to require 2.817 GB out of 5.487 GB available memory (51.335%)... (50.000% of avail memory is the max safe size)
	To force training the model, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.08 to avoid the error)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Not enough memory to train ExtraTreesEntr_BAG_L1... Skipping this model.
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L1\utils\model_template.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: XGBoost_BAG_L1 ... Training model for up to 16535.60s of the 25385.89s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47509
[50]	validation_0-logloss:0.26504
[100]	validation_0-logloss:0.24828
[150]	validation_0-logloss:0.23978
[200]	validation_0-logloss:0.23420
[250]	validation_0-logloss:0.23021
[300]	validation_0-logloss:0.22727
[350]	validation_0-logloss:0.22474
[400]	validation_0-logloss:0.22257
[450]	validation_0-logloss:0.22092
[500]	validation_0-logloss:0.21927
[550]	validation_0-logloss:0.21821
[600]	validation_0-logloss:0.21705
[650]	validation_0-logloss:0.21597
[700]	validation_0-logloss:0.21531
[750]	validation_0-logloss:0.21438
[800]	validation_0-logloss:0.21376
[850]	validation_0-logloss:0.21317
[900]	validation_0-logloss:0.21253
[950]	validation_0-logloss:0.21210
[1000]	validation_0-logloss:0.21164
[1050]	validation_0-logloss:0.21130
[1100]	validation_0-logloss:0.21080
[1150]	validation_0-logloss:0.21051
[1200]	validation_0-logloss:0.21013
[1250]	validation_0-logloss:0.20984
[1300]	validation_0-logloss:0.20958
[1350]	validation_0-logloss:0.20945
[1400]	validation_0-logloss:0.20916
[1450]	validation_0-logloss:0.20895
[1500]	validation_0-logloss:0.20882
[1550]	validation_0-logloss:0.20866
[1600]	validation_0-logloss:0.20852
[1650]	validation_0-logloss:0.20822
[1700]	validation_0-logloss:0.20822
[1750]	validation_0-logloss:0.20810
[1800]	validation_0-logloss:0.20808
[1850]	validation_0-logloss:0.20805
[1900]	validation_0-logloss:0.20802
[1950]	validation_0-logloss:0.20785
[2000]	validation_0-logloss:0.20775
[2050]	validation_0-logloss:0.20767
[2100]	validation_0-logloss:0.20761
[2150]	validation_0-logloss:0.20750
[2200]	validation_0-logloss:0.20744
[2250]	validation_0-logloss:0.20747
[2300]	validation_0-logloss:0.20745
[2350]	validation_0-logloss:0.20742
[2400]	validation_0-logloss:0.20742
[2450]	validation_0-logloss:0.20740
[2500]	validation_0-logloss:0.20739
[2550]	validation_0-logloss:0.20741
[2600]	validation_0-logloss:0.20735
[2650]	validation_0-logloss:0.20733
[2700]	validation_0-logloss:0.20732
[2750]	validation_0-logloss:0.20731
[2800]	validation_0-logloss:0.20728
[2850]	validation_0-logloss:0.20739
[2900]	validation_0-logloss:0.20750
[2950]	validation_0-logloss:0.20751
[3000]	validation_0-logloss:0.20760
[3050]	validation_0-logloss:0.20763
[3100]	validation_0-logloss:0.20760
[3150]	validation_0-logloss:0.20769
[3200]	validation_0-logloss:0.20779
[3250]	validation_0-logloss:0.20775
[3300]	validation_0-logloss:0.20779
[3350]	validation_0-logloss:0.20793
[3400]	validation_0-logloss:0.20796
[3450]	validation_0-logloss:0.20793
[3500]	validation_0-logloss:0.20797
[3550]	validation_0-logloss:0.20798
[3600]	validation_0-logloss:0.20792
[3650]	validation_0-logloss:0.20793
[3665]	validation_0-logloss:0.20795

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47517
[50]	validation_0-logloss:0.26543
[100]	validation_0-logloss:0.24950
[150]	validation_0-logloss:0.24147
[200]	validation_0-logloss:0.23602
[250]	validation_0-logloss:0.23181
[300]	validation_0-logloss:0.22822
[350]	validation_0-logloss:0.22554
[400]	validation_0-logloss:0.22311
[450]	validation_0-logloss:0.22133
[500]	validation_0-logloss:0.21946
[550]	validation_0-logloss:0.21826
[600]	validation_0-logloss:0.21677
[650]	validation_0-logloss:0.21598
[700]	validation_0-logloss:0.21519
[750]	validation_0-logloss:0.21470
[800]	validation_0-logloss:0.21411
[850]	validation_0-logloss:0.21361
[900]	validation_0-logloss:0.21309
[950]	validation_0-logloss:0.21271
[1000]	validation_0-logloss:0.21211
[1050]	validation_0-logloss:0.21168
[1100]	validation_0-logloss:0.21133
[1150]	validation_0-logloss:0.21106
[1200]	validation_0-logloss:0.21051
[1250]	validation_0-logloss:0.21023
[1300]	validation_0-logloss:0.20993
[1350]	validation_0-logloss:0.20979
[1400]	validation_0-logloss:0.20962
[1450]	validation_0-logloss:0.20941
[1500]	validation_0-logloss:0.20939
[1550]	validation_0-logloss:0.20928
[1600]	validation_0-logloss:0.20914
[1650]	validation_0-logloss:0.20896
[1700]	validation_0-logloss:0.20890
[1750]	validation_0-logloss:0.20882
[1800]	validation_0-logloss:0.20865
[1850]	validation_0-logloss:0.20855
[1900]	validation_0-logloss:0.20836
[1950]	validation_0-logloss:0.20830
[2000]	validation_0-logloss:0.20813
[2050]	validation_0-logloss:0.20801
[2100]	validation_0-logloss:0.20790
[2150]	validation_0-logloss:0.20777
[2200]	validation_0-logloss:0.20767
[2250]	validation_0-logloss:0.20760
[2300]	validation_0-logloss:0.20758
[2350]	validation_0-logloss:0.20748
[2400]	validation_0-logloss:0.20744
[2450]	validation_0-logloss:0.20743
[2500]	validation_0-logloss:0.20743
[2550]	validation_0-logloss:0.20742
[2600]	validation_0-logloss:0.20744
[2650]	validation_0-logloss:0.20746
[2700]	validation_0-logloss:0.20741
[2750]	validation_0-logloss:0.20738
[2800]	validation_0-logloss:0.20738
[2850]	validation_0-logloss:0.20742
[2900]	validation_0-logloss:0.20744
[2950]	validation_0-logloss:0.20747
[3000]	validation_0-logloss:0.20753
[3050]	validation_0-logloss:0.20758
[3100]	validation_0-logloss:0.20759
[3150]	validation_0-logloss:0.20756
[3200]	validation_0-logloss:0.20762
[3250]	validation_0-logloss:0.20765
[3300]	validation_0-logloss:0.20764
[3350]	validation_0-logloss:0.20764
[3400]	validation_0-logloss:0.20758
[3450]	validation_0-logloss:0.20761
[3500]	validation_0-logloss:0.20766
[3550]	validation_0-logloss:0.20772
[3600]	validation_0-logloss:0.20781
[3633]	validation_0-logloss:0.20782

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47522
[50]	validation_0-logloss:0.26828
[100]	validation_0-logloss:0.25160
[150]	validation_0-logloss:0.24346
[200]	validation_0-logloss:0.23778
[250]	validation_0-logloss:0.23376
[300]	validation_0-logloss:0.23051
[350]	validation_0-logloss:0.22810
[400]	validation_0-logloss:0.22631
[450]	validation_0-logloss:0.22426
[500]	validation_0-logloss:0.22282
[550]	validation_0-logloss:0.22180
[600]	validation_0-logloss:0.22079
[650]	validation_0-logloss:0.21983
[700]	validation_0-logloss:0.21905
[750]	validation_0-logloss:0.21833
[800]	validation_0-logloss:0.21769
[850]	validation_0-logloss:0.21707
[900]	validation_0-logloss:0.21673
[950]	validation_0-logloss:0.21632
[1000]	validation_0-logloss:0.21595
[1050]	validation_0-logloss:0.21554
[1100]	validation_0-logloss:0.21520
[1150]	validation_0-logloss:0.21488
[1200]	validation_0-logloss:0.21465
[1250]	validation_0-logloss:0.21439
[1300]	validation_0-logloss:0.21412
[1350]	validation_0-logloss:0.21391
[1400]	validation_0-logloss:0.21371
[1450]	validation_0-logloss:0.21365
[1500]	validation_0-logloss:0.21352
[1550]	validation_0-logloss:0.21340
[1600]	validation_0-logloss:0.21323
[1650]	validation_0-logloss:0.21321
[1700]	validation_0-logloss:0.21312
[1750]	validation_0-logloss:0.21296
[1800]	validation_0-logloss:0.21279
[1850]	validation_0-logloss:0.21284
[1900]	validation_0-logloss:0.21276
[1950]	validation_0-logloss:0.21267
[2000]	validation_0-logloss:0.21265
[2050]	validation_0-logloss:0.21256
[2100]	validation_0-logloss:0.21240
[2150]	validation_0-logloss:0.21238
[2200]	validation_0-logloss:0.21247
[2250]	validation_0-logloss:0.21250
[2300]	validation_0-logloss:0.21254
[2350]	validation_0-logloss:0.21247
[2400]	validation_0-logloss:0.21246
[2450]	validation_0-logloss:0.21248
[2500]	validation_0-logloss:0.21238
[2550]	validation_0-logloss:0.21234
[2600]	validation_0-logloss:0.21235
[2650]	validation_0-logloss:0.21237
[2700]	validation_0-logloss:0.21242
[2750]	validation_0-logloss:0.21249
[2800]	validation_0-logloss:0.21254
[2850]	validation_0-logloss:0.21262
[2900]	validation_0-logloss:0.21266
[2950]	validation_0-logloss:0.21272
[3000]	validation_0-logloss:0.21278
[3050]	validation_0-logloss:0.21289
[3100]	validation_0-logloss:0.21293
[3150]	validation_0-logloss:0.21295
[3200]	validation_0-logloss:0.21299
[3250]	validation_0-logloss:0.21305
[3300]	validation_0-logloss:0.21313
[3319]	validation_0-logloss:0.21316

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47498
[50]	validation_0-logloss:0.26385
[100]	validation_0-logloss:0.24810
[150]	validation_0-logloss:0.23947
[200]	validation_0-logloss:0.23358
[250]	validation_0-logloss:0.22956
[300]	validation_0-logloss:0.22580
[350]	validation_0-logloss:0.22332
[400]	validation_0-logloss:0.22131
[450]	validation_0-logloss:0.21948
[500]	validation_0-logloss:0.21826
[550]	validation_0-logloss:0.21749
[600]	validation_0-logloss:0.21653
[650]	validation_0-logloss:0.21556
[700]	validation_0-logloss:0.21487
[750]	validation_0-logloss:0.21433
[800]	validation_0-logloss:0.21338
[850]	validation_0-logloss:0.21280
[900]	validation_0-logloss:0.21225
[950]	validation_0-logloss:0.21170
[1000]	validation_0-logloss:0.21127
[1050]	validation_0-logloss:0.21089
[1100]	validation_0-logloss:0.21046
[1150]	validation_0-logloss:0.21016
[1200]	validation_0-logloss:0.20990
[1250]	validation_0-logloss:0.20965
[1300]	validation_0-logloss:0.20940
[1350]	validation_0-logloss:0.20922
[1400]	validation_0-logloss:0.20888
[1450]	validation_0-logloss:0.20873
[1500]	validation_0-logloss:0.20869
[1550]	validation_0-logloss:0.20861
[1600]	validation_0-logloss:0.20844
[1650]	validation_0-logloss:0.20827
[1700]	validation_0-logloss:0.20816
[1750]	validation_0-logloss:0.20809
[1800]	validation_0-logloss:0.20804
[1850]	validation_0-logloss:0.20782
[1900]	validation_0-logloss:0.20770
[1950]	validation_0-logloss:0.20761
[2000]	validation_0-logloss:0.20759
[2050]	validation_0-logloss:0.20754
[2100]	validation_0-logloss:0.20750
[2150]	validation_0-logloss:0.20748
[2200]	validation_0-logloss:0.20753
[2250]	validation_0-logloss:0.20742
[2300]	validation_0-logloss:0.20734
[2350]	validation_0-logloss:0.20736
[2400]	validation_0-logloss:0.20730
[2450]	validation_0-logloss:0.20727
[2500]	validation_0-logloss:0.20729
[2550]	validation_0-logloss:0.20730
[2600]	validation_0-logloss:0.20732
[2650]	validation_0-logloss:0.20726
[2700]	validation_0-logloss:0.20731
[2750]	validation_0-logloss:0.20731
[2800]	validation_0-logloss:0.20736
[2850]	validation_0-logloss:0.20738
[2900]	validation_0-logloss:0.20750
[2950]	validation_0-logloss:0.20755
[3000]	validation_0-logloss:0.20756
[3050]	validation_0-logloss:0.20754
[3100]	validation_0-logloss:0.20757
[3150]	validation_0-logloss:0.20766
[3200]	validation_0-logloss:0.20772
[3250]	validation_0-logloss:0.20776
[3300]	validation_0-logloss:0.20782
[3350]	validation_0-logloss:0.20796
[3400]	validation_0-logloss:0.20803
[3450]	validation_0-logloss:0.20807
[3473]	validation_0-logloss:0.20811

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47510
[50]	validation_0-logloss:0.26437
[100]	validation_0-logloss:0.24852
[150]	validation_0-logloss:0.23961
[200]	validation_0-logloss:0.23456
[250]	validation_0-logloss:0.23081
[300]	validation_0-logloss:0.22766
[350]	validation_0-logloss:0.22497
[400]	validation_0-logloss:0.22241
[450]	validation_0-logloss:0.22081
[500]	validation_0-logloss:0.21954
[550]	validation_0-logloss:0.21799
[600]	validation_0-logloss:0.21669
[650]	validation_0-logloss:0.21602
[700]	validation_0-logloss:0.21517
[750]	validation_0-logloss:0.21426
[800]	validation_0-logloss:0.21352
[850]	validation_0-logloss:0.21274
[900]	validation_0-logloss:0.21211
[950]	validation_0-logloss:0.21149
[1000]	validation_0-logloss:0.21112
[1050]	validation_0-logloss:0.21086
[1100]	validation_0-logloss:0.21045
[1150]	validation_0-logloss:0.21008
[1200]	validation_0-logloss:0.20976
[1250]	validation_0-logloss:0.20960
[1300]	validation_0-logloss:0.20940
[1350]	validation_0-logloss:0.20930
[1400]	validation_0-logloss:0.20913
[1450]	validation_0-logloss:0.20888
[1500]	validation_0-logloss:0.20880
[1550]	validation_0-logloss:0.20877
[1600]	validation_0-logloss:0.20865
[1650]	validation_0-logloss:0.20851
[1700]	validation_0-logloss:0.20826
[1750]	validation_0-logloss:0.20816
[1800]	validation_0-logloss:0.20797
[1850]	validation_0-logloss:0.20784
[1900]	validation_0-logloss:0.20784
[1950]	validation_0-logloss:0.20774
[2000]	validation_0-logloss:0.20765
[2050]	validation_0-logloss:0.20751
[2100]	validation_0-logloss:0.20741
[2150]	validation_0-logloss:0.20742
[2200]	validation_0-logloss:0.20736
[2250]	validation_0-logloss:0.20725
[2300]	validation_0-logloss:0.20722
[2350]	validation_0-logloss:0.20716
[2400]	validation_0-logloss:0.20704
[2450]	validation_0-logloss:0.20707
[2500]	validation_0-logloss:0.20711
[2550]	validation_0-logloss:0.20709
[2600]	validation_0-logloss:0.20708
[2650]	validation_0-logloss:0.20709
[2700]	validation_0-logloss:0.20701
[2750]	validation_0-logloss:0.20706
[2800]	validation_0-logloss:0.20705
[2850]	validation_0-logloss:0.20704
[2900]	validation_0-logloss:0.20700
[2950]	validation_0-logloss:0.20694
[3000]	validation_0-logloss:0.20690
[3050]	validation_0-logloss:0.20699
[3100]	validation_0-logloss:0.20694
[3150]	validation_0-logloss:0.20694
[3200]	validation_0-logloss:0.20704
[3250]	validation_0-logloss:0.20706
[3300]	validation_0-logloss:0.20705
[3350]	validation_0-logloss:0.20709
[3400]	validation_0-logloss:0.20713
[3450]	validation_0-logloss:0.20722
[3500]	validation_0-logloss:0.20727
[3550]	validation_0-logloss:0.20735
[3600]	validation_0-logloss:0.20739
[3650]	validation_0-logloss:0.20737
[3700]	validation_0-logloss:0.20736
[3750]	validation_0-logloss:0.20745
[3800]	validation_0-logloss:0.20753
[3850]	validation_0-logloss:0.20754
[3900]	validation_0-logloss:0.20761
[3901]	validation_0-logloss:0.20761

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47501
[50]	validation_0-logloss:0.26468
[100]	validation_0-logloss:0.24829
[150]	validation_0-logloss:0.24023
[200]	validation_0-logloss:0.23531
[250]	validation_0-logloss:0.23115
[300]	validation_0-logloss:0.22822
[350]	validation_0-logloss:0.22550
[400]	validation_0-logloss:0.22316
[450]	validation_0-logloss:0.22144
[500]	validation_0-logloss:0.21996
[550]	validation_0-logloss:0.21867
[600]	validation_0-logloss:0.21760
[650]	validation_0-logloss:0.21666
[700]	validation_0-logloss:0.21585
[750]	validation_0-logloss:0.21507
[800]	validation_0-logloss:0.21438
[850]	validation_0-logloss:0.21376
[900]	validation_0-logloss:0.21338
[950]	validation_0-logloss:0.21294
[1000]	validation_0-logloss:0.21258
[1050]	validation_0-logloss:0.21227
[1100]	validation_0-logloss:0.21194
[1150]	validation_0-logloss:0.21160
[1200]	validation_0-logloss:0.21127
[1250]	validation_0-logloss:0.21105
[1300]	validation_0-logloss:0.21068
[1350]	validation_0-logloss:0.21048
[1400]	validation_0-logloss:0.21029
[1450]	validation_0-logloss:0.21015
[1500]	validation_0-logloss:0.20995
[1550]	validation_0-logloss:0.20977
[1600]	validation_0-logloss:0.20959
[1650]	validation_0-logloss:0.20944
[1700]	validation_0-logloss:0.20931
[1750]	validation_0-logloss:0.20922
[1800]	validation_0-logloss:0.20915
[1850]	validation_0-logloss:0.20903
[1900]	validation_0-logloss:0.20898
[1950]	validation_0-logloss:0.20892
[2000]	validation_0-logloss:0.20884
[2050]	validation_0-logloss:0.20872
[2100]	validation_0-logloss:0.20870
[2150]	validation_0-logloss:0.20869
[2200]	validation_0-logloss:0.20865
[2250]	validation_0-logloss:0.20863
[2300]	validation_0-logloss:0.20859
[2350]	validation_0-logloss:0.20860
[2400]	validation_0-logloss:0.20858
[2450]	validation_0-logloss:0.20855
[2500]	validation_0-logloss:0.20851
[2550]	validation_0-logloss:0.20855
[2600]	validation_0-logloss:0.20847
[2650]	validation_0-logloss:0.20846
[2700]	validation_0-logloss:0.20853
[2750]	validation_0-logloss:0.20852
[2800]	validation_0-logloss:0.20847
[2850]	validation_0-logloss:0.20859
[2900]	validation_0-logloss:0.20854
[2950]	validation_0-logloss:0.20853
[3000]	validation_0-logloss:0.20860
[3050]	validation_0-logloss:0.20863
[3100]	validation_0-logloss:0.20867
[3150]	validation_0-logloss:0.20864
[3200]	validation_0-logloss:0.20878
[3250]	validation_0-logloss:0.20884
[3300]	validation_0-logloss:0.20889
[3350]	validation_0-logloss:0.20892
[3400]	validation_0-logloss:0.20894
[3429]	validation_0-logloss:0.20895

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47466
[50]	validation_0-logloss:0.26443
[100]	validation_0-logloss:0.24781
[150]	validation_0-logloss:0.23996
[200]	validation_0-logloss:0.23398
[250]	validation_0-logloss:0.23036
[300]	validation_0-logloss:0.22776
[350]	validation_0-logloss:0.22543
[400]	validation_0-logloss:0.22350
[450]	validation_0-logloss:0.22147
[500]	validation_0-logloss:0.22022
[550]	validation_0-logloss:0.21904
[600]	validation_0-logloss:0.21782
[650]	validation_0-logloss:0.21686
[700]	validation_0-logloss:0.21616
[750]	validation_0-logloss:0.21532
[800]	validation_0-logloss:0.21416
[850]	validation_0-logloss:0.21368
[900]	validation_0-logloss:0.21302
[950]	validation_0-logloss:0.21244
[1000]	validation_0-logloss:0.21194
[1050]	validation_0-logloss:0.21163
[1100]	validation_0-logloss:0.21139
[1150]	validation_0-logloss:0.21109
[1200]	validation_0-logloss:0.21088
[1250]	validation_0-logloss:0.21051
[1300]	validation_0-logloss:0.21032
[1350]	validation_0-logloss:0.21018
[1400]	validation_0-logloss:0.20997
[1450]	validation_0-logloss:0.20980
[1500]	validation_0-logloss:0.20968
[1550]	validation_0-logloss:0.20950
[1600]	validation_0-logloss:0.20937
[1650]	validation_0-logloss:0.20924
[1700]	validation_0-logloss:0.20906
[1750]	validation_0-logloss:0.20899
[1800]	validation_0-logloss:0.20892
[1850]	validation_0-logloss:0.20883
[1900]	validation_0-logloss:0.20879
[1950]	validation_0-logloss:0.20875
[2000]	validation_0-logloss:0.20872
[2050]	validation_0-logloss:0.20858
[2100]	validation_0-logloss:0.20849
[2150]	validation_0-logloss:0.20842
[2200]	validation_0-logloss:0.20840
[2250]	validation_0-logloss:0.20837
[2300]	validation_0-logloss:0.20835
[2350]	validation_0-logloss:0.20833
[2400]	validation_0-logloss:0.20827
[2450]	validation_0-logloss:0.20823
[2500]	validation_0-logloss:0.20825
[2550]	validation_0-logloss:0.20819
[2600]	validation_0-logloss:0.20817
[2650]	validation_0-logloss:0.20813
[2700]	validation_0-logloss:0.20813
[2750]	validation_0-logloss:0.20816
[2800]	validation_0-logloss:0.20818
[2850]	validation_0-logloss:0.20822
[2900]	validation_0-logloss:0.20822
[2950]	validation_0-logloss:0.20822
[3000]	validation_0-logloss:0.20819
[3050]	validation_0-logloss:0.20821
[3100]	validation_0-logloss:0.20832
[3150]	validation_0-logloss:0.20830
[3200]	validation_0-logloss:0.20834
[3250]	validation_0-logloss:0.20834
[3300]	validation_0-logloss:0.20844
[3350]	validation_0-logloss:0.20847
[3400]	validation_0-logloss:0.20850
[3450]	validation_0-logloss:0.20853
[3500]	validation_0-logloss:0.20860
[3503]	validation_0-logloss:0.20859

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47463
[50]	validation_0-logloss:0.26261
[100]	validation_0-logloss:0.24656
[150]	validation_0-logloss:0.23869
[200]	validation_0-logloss:0.23268
[250]	validation_0-logloss:0.22892
[300]	validation_0-logloss:0.22598
[350]	validation_0-logloss:0.22332
[400]	validation_0-logloss:0.22158
[450]	validation_0-logloss:0.22002
[500]	validation_0-logloss:0.21854
[550]	validation_0-logloss:0.21741
[600]	validation_0-logloss:0.21596
[650]	validation_0-logloss:0.21506
[700]	validation_0-logloss:0.21430
[750]	validation_0-logloss:0.21365
[800]	validation_0-logloss:0.21292
[850]	validation_0-logloss:0.21226
[900]	validation_0-logloss:0.21174
[950]	validation_0-logloss:0.21121
[1000]	validation_0-logloss:0.21073
[1050]	validation_0-logloss:0.21027
[1100]	validation_0-logloss:0.21002
[1150]	validation_0-logloss:0.20972
[1200]	validation_0-logloss:0.20935
[1250]	validation_0-logloss:0.20916
[1300]	validation_0-logloss:0.20897
[1350]	validation_0-logloss:0.20880
[1400]	validation_0-logloss:0.20861
[1450]	validation_0-logloss:0.20846
[1500]	validation_0-logloss:0.20834
[1550]	validation_0-logloss:0.20826
[1600]	validation_0-logloss:0.20813
[1650]	validation_0-logloss:0.20800
[1700]	validation_0-logloss:0.20787
[1750]	validation_0-logloss:0.20780
[1800]	validation_0-logloss:0.20769
[1850]	validation_0-logloss:0.20774
[1900]	validation_0-logloss:0.20755
[1950]	validation_0-logloss:0.20751
[2000]	validation_0-logloss:0.20751
[2050]	validation_0-logloss:0.20725
[2100]	validation_0-logloss:0.20714
[2150]	validation_0-logloss:0.20711
[2200]	validation_0-logloss:0.20704
[2250]	validation_0-logloss:0.20707
[2300]	validation_0-logloss:0.20705
[2350]	validation_0-logloss:0.20708
[2400]	validation_0-logloss:0.20707
[2450]	validation_0-logloss:0.20706
[2500]	validation_0-logloss:0.20707
[2550]	validation_0-logloss:0.20706
[2600]	validation_0-logloss:0.20705
[2650]	validation_0-logloss:0.20707
[2700]	validation_0-logloss:0.20704
[2750]	validation_0-logloss:0.20705
[2800]	validation_0-logloss:0.20702
[2850]	validation_0-logloss:0.20712
[2900]	validation_0-logloss:0.20710
[2950]	validation_0-logloss:0.20704
[3000]	validation_0-logloss:0.20703
[3050]	validation_0-logloss:0.20708
[3100]	validation_0-logloss:0.20706
[3150]	validation_0-logloss:0.20714
[3200]	validation_0-logloss:0.20722
[3250]	validation_0-logloss:0.20728
[3300]	validation_0-logloss:0.20732
[3350]	validation_0-logloss:0.20733
[3400]	validation_0-logloss:0.20739
[3450]	validation_0-logloss:0.20749
[3500]	validation_0-logloss:0.20757
[3550]	validation_0-logloss:0.20764
[3600]	validation_0-logloss:0.20773
[3650]	validation_0-logloss:0.20777
[3673]	validation_0-logloss:0.20780

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L1\model.pkl
	0.9587	 = Validation score   (roc_auc)
	617.69s	 = Training   runtime
	4.02s	 = Validation runtime
	16820.0	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 15913.15s of the 24763.44s of remaining time.
	Fitting NeuralNetTorch_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 22 features (19 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=54, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1847).	Train loss: 0.3212, Val roc_auc: 0.9191, Best Epoch: 1
Epoch 2 (Update 3694).	Train loss: 0.2834, Val roc_auc: 0.929, Best Epoch: 2
Epoch 3 (Update 5541).	Train loss: 0.2702, Val roc_auc: 0.9348, Best Epoch: 3
Epoch 4 (Update 7388).	Train loss: 0.2625, Val roc_auc: 0.9389, Best Epoch: 4
Epoch 5 (Update 9235).	Train loss: 0.2558, Val roc_auc: 0.941, Best Epoch: 5
Epoch 6 (Update 11082).	Train loss: 0.2511, Val roc_auc: 0.943, Best Epoch: 6
Epoch 7 (Update 12929).	Train loss: 0.2472, Val roc_auc: 0.9439, Best Epoch: 7
Epoch 8 (Update 14776).	Train loss: 0.2434, Val roc_auc: 0.9464, Best Epoch: 8
Epoch 9 (Update 16623).	Train loss: 0.241, Val roc_auc: 0.9466, Best Epoch: 9
Epoch 10 (Update 18470).	Train loss: 0.2379, Val roc_auc: 0.9474, Best Epoch: 10
Epoch 11 (Update 20317).	Train loss: 0.2369, Val roc_auc: 0.9486, Best Epoch: 11
Epoch 12 (Update 22164).	Train loss: 0.2342, Val roc_auc: 0.9499, Best Epoch: 12
Epoch 13 (Update 24011).	Train loss: 0.2324, Val roc_auc: 0.9502, Best Epoch: 13
Epoch 14 (Update 25858).	Train loss: 0.2304, Val roc_auc: 0.9509, Best Epoch: 14
Epoch 15 (Update 27705).	Train loss: 0.2292, Val roc_auc: 0.9511, Best Epoch: 15
Epoch 16 (Update 29552).	Train loss: 0.2276, Val roc_auc: 0.9521, Best Epoch: 16
Epoch 17 (Update 31399).	Train loss: 0.2263, Val roc_auc: 0.9523, Best Epoch: 17
Epoch 18 (Update 33246).	Train loss: 0.2251, Val roc_auc: 0.9526, Best Epoch: 18
Epoch 19 (Update 35093).	Train loss: 0.2242, Val roc_auc: 0.953, Best Epoch: 19
Epoch 20 (Update 36940).	Train loss: 0.2232, Val roc_auc: 0.9534, Best Epoch: 20
Epoch 21 (Update 38787).	Train loss: 0.2221, Val roc_auc: 0.9539, Best Epoch: 21
Epoch 22 (Update 40634).	Train loss: 0.2215, Val roc_auc: 0.9537, Best Epoch: 21
Epoch 23 (Update 42481).	Train loss: 0.2205, Val roc_auc: 0.9539, Best Epoch: 21
Epoch 24 (Update 44328).	Train loss: 0.2203, Val roc_auc: 0.9541, Best Epoch: 24
Epoch 25 (Update 46175).	Train loss: 0.2193, Val roc_auc: 0.954, Best Epoch: 24
Epoch 26 (Update 48022).	Train loss: 0.2186, Val roc_auc: 0.9549, Best Epoch: 26
Epoch 27 (Update 49869).	Train loss: 0.2182, Val roc_auc: 0.9549, Best Epoch: 26
Epoch 28 (Update 51716).	Train loss: 0.217, Val roc_auc: 0.9547, Best Epoch: 26
Epoch 29 (Update 53563).	Train loss: 0.2166, Val roc_auc: 0.955, Best Epoch: 29
Epoch 30 (Update 55410).	Train loss: 0.2162, Val roc_auc: 0.9549, Best Epoch: 29
Epoch 31 (Update 57257).	Train loss: 0.2159, Val roc_auc: 0.9548, Best Epoch: 29
Epoch 32 (Update 59104).	Train loss: 0.2151, Val roc_auc: 0.9554, Best Epoch: 32
Epoch 33 (Update 60951).	Train loss: 0.2143, Val roc_auc: 0.9555, Best Epoch: 33
Epoch 34 (Update 62798).	Train loss: 0.2144, Val roc_auc: 0.956, Best Epoch: 34
Epoch 35 (Update 64645).	Train loss: 0.2138, Val roc_auc: 0.956, Best Epoch: 35
Epoch 36 (Update 66492).	Train loss: 0.2133, Val roc_auc: 0.956, Best Epoch: 35
Epoch 37 (Update 68339).	Train loss: 0.2124, Val roc_auc: 0.956, Best Epoch: 37
Epoch 38 (Update 70186).	Train loss: 0.2123, Val roc_auc: 0.9559, Best Epoch: 37
Epoch 39 (Update 72033).	Train loss: 0.2126, Val roc_auc: 0.9557, Best Epoch: 37
Epoch 40 (Update 73880).	Train loss: 0.2118, Val roc_auc: 0.9564, Best Epoch: 40
Epoch 41 (Update 75727).	Train loss: 0.2115, Val roc_auc: 0.9558, Best Epoch: 40
Epoch 42 (Update 77574).	Train loss: 0.2109, Val roc_auc: 0.9562, Best Epoch: 40
Epoch 43 (Update 79421).	Train loss: 0.2107, Val roc_auc: 0.9559, Best Epoch: 40
Epoch 44 (Update 81268).	Train loss: 0.2106, Val roc_auc: 0.9566, Best Epoch: 44
Epoch 45 (Update 83115).	Train loss: 0.2096, Val roc_auc: 0.9562, Best Epoch: 44
Epoch 46 (Update 84962).	Train loss: 0.2098, Val roc_auc: 0.9561, Best Epoch: 44
Epoch 47 (Update 86809).	Train loss: 0.2096, Val roc_auc: 0.9565, Best Epoch: 44
Epoch 48 (Update 88656).	Train loss: 0.209, Val roc_auc: 0.9567, Best Epoch: 48
Epoch 49 (Update 90503).	Train loss: 0.2086, Val roc_auc: 0.9566, Best Epoch: 48
Epoch 50 (Update 92350).	Train loss: 0.2082, Val roc_auc: 0.9564, Best Epoch: 48
Epoch 51 (Update 94197).	Train loss: 0.2081, Val roc_auc: 0.9564, Best Epoch: 48
Epoch 52 (Update 96044).	Train loss: 0.208, Val roc_auc: 0.9565, Best Epoch: 48
Epoch 53 (Update 97891).	Train loss: 0.208, Val roc_auc: 0.9568, Best Epoch: 53
Epoch 54 (Update 99738).	Train loss: 0.2076, Val roc_auc: 0.9565, Best Epoch: 53
Epoch 55 (Update 101585).	Train loss: 0.2074, Val roc_auc: 0.9565, Best Epoch: 53
Epoch 56 (Update 103432).	Train loss: 0.2071, Val roc_auc: 0.9566, Best Epoch: 53
Epoch 57 (Update 105279).	Train loss: 0.2072, Val roc_auc: 0.957, Best Epoch: 57
Epoch 58 (Update 107126).	Train loss: 0.2068, Val roc_auc: 0.9565, Best Epoch: 57
Epoch 59 (Update 108973).	Train loss: 0.207, Val roc_auc: 0.9568, Best Epoch: 57
Epoch 60 (Update 110820).	Train loss: 0.2069, Val roc_auc: 0.9568, Best Epoch: 57
Epoch 61 (Update 112667).	Train loss: 0.2063, Val roc_auc: 0.9568, Best Epoch: 57
Epoch 62 (Update 114514).	Train loss: 0.2058, Val roc_auc: 0.957, Best Epoch: 57
Epoch 63 (Update 116361).	Train loss: 0.2053, Val roc_auc: 0.9568, Best Epoch: 57
Epoch 64 (Update 118208).	Train loss: 0.2057, Val roc_auc: 0.9571, Best Epoch: 64
Epoch 65 (Update 120055).	Train loss: 0.2058, Val roc_auc: 0.957, Best Epoch: 64
Epoch 66 (Update 121902).	Train loss: 0.2051, Val roc_auc: 0.9569, Best Epoch: 64
Epoch 67 (Update 123749).	Train loss: 0.2051, Val roc_auc: 0.957, Best Epoch: 64
Epoch 68 (Update 125596).	Train loss: 0.2047, Val roc_auc: 0.9574, Best Epoch: 68
Epoch 69 (Update 127443).	Train loss: 0.205, Val roc_auc: 0.9565, Best Epoch: 68
Epoch 70 (Update 129290).	Train loss: 0.2049, Val roc_auc: 0.9571, Best Epoch: 68
Epoch 71 (Update 131137).	Train loss: 0.2045, Val roc_auc: 0.9572, Best Epoch: 68
Epoch 72 (Update 132984).	Train loss: 0.2043, Val roc_auc: 0.9569, Best Epoch: 68
Epoch 73 (Update 134831).	Train loss: 0.204, Val roc_auc: 0.9567, Best Epoch: 68
Epoch 74 (Update 136678).	Train loss: 0.2036, Val roc_auc: 0.9567, Best Epoch: 68
Epoch 75 (Update 138525).	Train loss: 0.2038, Val roc_auc: 0.9572, Best Epoch: 68
Epoch 76 (Update 140372).	Train loss: 0.2035, Val roc_auc: 0.9567, Best Epoch: 68
Epoch 77 (Update 142219).	Train loss: 0.2032, Val roc_auc: 0.9569, Best Epoch: 68
Epoch 78 (Update 144066).	Train loss: 0.203, Val roc_auc: 0.9571, Best Epoch: 68
Epoch 79 (Update 145913).	Train loss: 0.2028, Val roc_auc: 0.9575, Best Epoch: 79
Epoch 80 (Update 147760).	Train loss: 0.2024, Val roc_auc: 0.9572, Best Epoch: 79
Epoch 81 (Update 149607).	Train loss: 0.2027, Val roc_auc: 0.9575, Best Epoch: 79
Epoch 82 (Update 151454).	Train loss: 0.2021, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 83 (Update 153301).	Train loss: 0.203, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 84 (Update 155148).	Train loss: 0.2022, Val roc_auc: 0.9574, Best Epoch: 79
Epoch 85 (Update 156995).	Train loss: 0.2021, Val roc_auc: 0.957, Best Epoch: 79
Epoch 86 (Update 158842).	Train loss: 0.2024, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 87 (Update 160689).	Train loss: 0.2021, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 88 (Update 162536).	Train loss: 0.2021, Val roc_auc: 0.9571, Best Epoch: 79
Epoch 89 (Update 164383).	Train loss: 0.2017, Val roc_auc: 0.9568, Best Epoch: 79
Epoch 90 (Update 166230).	Train loss: 0.2025, Val roc_auc: 0.9571, Best Epoch: 79
Epoch 91 (Update 168077).	Train loss: 0.2011, Val roc_auc: 0.9572, Best Epoch: 79
Epoch 92 (Update 169924).	Train loss: 0.2016, Val roc_auc: 0.9569, Best Epoch: 79
Epoch 93 (Update 171771).	Train loss: 0.2018, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 94 (Update 173618).	Train loss: 0.2012, Val roc_auc: 0.9572, Best Epoch: 79
Epoch 95 (Update 175465).	Train loss: 0.2011, Val roc_auc: 0.9571, Best Epoch: 79
Epoch 96 (Update 177312).	Train loss: 0.201, Val roc_auc: 0.9572, Best Epoch: 79
Epoch 97 (Update 179159).	Train loss: 0.2013, Val roc_auc: 0.957, Best Epoch: 79
Epoch 98 (Update 181006).	Train loss: 0.2007, Val roc_auc: 0.9573, Best Epoch: 79
Epoch 99 (Update 182853).	Train loss: 0.2005, Val roc_auc: 0.9574, Best Epoch: 79
Epoch 100 (Update 184700).	Train loss: 0.2006, Val roc_auc: 0.9576, Best Epoch: 100
Epoch 101 (Update 186547).	Train loss: 0.2007, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 102 (Update 188394).	Train loss: 0.2007, Val roc_auc: 0.9575, Best Epoch: 100
Epoch 103 (Update 190241).	Train loss: 0.2001, Val roc_auc: 0.9571, Best Epoch: 100
Epoch 104 (Update 192088).	Train loss: 0.2005, Val roc_auc: 0.9575, Best Epoch: 100
Epoch 105 (Update 193935).	Train loss: 0.2, Val roc_auc: 0.9568, Best Epoch: 100
Epoch 106 (Update 195782).	Train loss: 0.1998, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 107 (Update 197629).	Train loss: 0.2004, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 108 (Update 199476).	Train loss: 0.2002, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 109 (Update 201323).	Train loss: 0.1999, Val roc_auc: 0.9572, Best Epoch: 100
Epoch 110 (Update 203170).	Train loss: 0.1998, Val roc_auc: 0.9571, Best Epoch: 100
Epoch 111 (Update 205017).	Train loss: 0.2001, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 112 (Update 206864).	Train loss: 0.1994, Val roc_auc: 0.9573, Best Epoch: 100
Epoch 113 (Update 208711).	Train loss: 0.1992, Val roc_auc: 0.9568, Best Epoch: 100
Epoch 114 (Update 210558).	Train loss: 0.1993, Val roc_auc: 0.9574, Best Epoch: 100
Epoch 115 (Update 212405).	Train loss: 0.1992, Val roc_auc: 0.9573, Best Epoch: 100
Epoch 116 (Update 214252).	Train loss: 0.199, Val roc_auc: 0.9572, Best Epoch: 100
Epoch 117 (Update 216099).	Train loss: 0.1993, Val roc_auc: 0.9573, Best Epoch: 100
Epoch 118 (Update 217946).	Train loss: 0.1982, Val roc_auc: 0.9572, Best Epoch: 100
Epoch 119 (Update 219793).	Train loss: 0.1985, Val roc_auc: 0.9577, Best Epoch: 119
Epoch 120 (Update 221640).	Train loss: 0.1987, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 121 (Update 223487).	Train loss: 0.1989, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 122 (Update 225334).	Train loss: 0.1981, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 123 (Update 227181).	Train loss: 0.1985, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 124 (Update 229028).	Train loss: 0.1986, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 125 (Update 230875).	Train loss: 0.1978, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 126 (Update 232722).	Train loss: 0.1988, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 127 (Update 234569).	Train loss: 0.198, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 128 (Update 236416).	Train loss: 0.1978, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 129 (Update 238263).	Train loss: 0.1977, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 130 (Update 240110).	Train loss: 0.1986, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 131 (Update 241957).	Train loss: 0.1983, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 132 (Update 243804).	Train loss: 0.1978, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 133 (Update 245651).	Train loss: 0.1976, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 134 (Update 247498).	Train loss: 0.1974, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 135 (Update 249345).	Train loss: 0.1968, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 136 (Update 251192).	Train loss: 0.1976, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 137 (Update 253039).	Train loss: 0.1976, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 138 (Update 254886).	Train loss: 0.1974, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 139 (Update 256733).	Train loss: 0.1972, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 140 (Update 258580).	Train loss: 0.1974, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 141 (Update 260427).	Train loss: 0.1972, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 142 (Update 262274).	Train loss: 0.1972, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 143 (Update 264121).	Train loss: 0.1969, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 144 (Update 265968).	Train loss: 0.1971, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 145 (Update 267815).	Train loss: 0.1971, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 146 (Update 269662).	Train loss: 0.1971, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 147 (Update 271509).	Train loss: 0.1966, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 148 (Update 273356).	Train loss: 0.1962, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 149 (Update 275203).	Train loss: 0.1961, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 150 (Update 277050).	Train loss: 0.1971, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 151 (Update 278897).	Train loss: 0.1962, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 152 (Update 280744).	Train loss: 0.1962, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 153 (Update 282591).	Train loss: 0.1965, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 154 (Update 284438).	Train loss: 0.1963, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 155 (Update 286285).	Train loss: 0.1962, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 156 (Update 288132).	Train loss: 0.1961, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 157 (Update 289979).	Train loss: 0.196, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 158 (Update 291826).	Train loss: 0.1961, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 159 (Update 293673).	Train loss: 0.1958, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 160 (Update 295520).	Train loss: 0.1955, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 161 (Update 297367).	Train loss: 0.196, Val roc_auc: 0.957, Best Epoch: 119
Epoch 162 (Update 299214).	Train loss: 0.1953, Val roc_auc: 0.957, Best Epoch: 119
Epoch 163 (Update 301061).	Train loss: 0.1956, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 164 (Update 302908).	Train loss: 0.1958, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 165 (Update 304755).	Train loss: 0.1956, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 166 (Update 306602).	Train loss: 0.1954, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 167 (Update 308449).	Train loss: 0.1956, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 168 (Update 310296).	Train loss: 0.1952, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 169 (Update 312143).	Train loss: 0.1955, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 170 (Update 313990).	Train loss: 0.1954, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 171 (Update 315837).	Train loss: 0.195, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 172 (Update 317684).	Train loss: 0.1951, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 173 (Update 319531).	Train loss: 0.1947, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 174 (Update 321378).	Train loss: 0.1949, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 175 (Update 323225).	Train loss: 0.195, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 176 (Update 325072).	Train loss: 0.1949, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 177 (Update 326919).	Train loss: 0.1945, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 178 (Update 328766).	Train loss: 0.1949, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 179 (Update 330613).	Train loss: 0.1949, Val roc_auc: 0.9575, Best Epoch: 119
Epoch 180 (Update 332460).	Train loss: 0.1946, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 181 (Update 334307).	Train loss: 0.1942, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 182 (Update 336154).	Train loss: 0.1948, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 183 (Update 338001).	Train loss: 0.1947, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 184 (Update 339848).	Train loss: 0.1947, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 185 (Update 341695).	Train loss: 0.1942, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 186 (Update 343542).	Train loss: 0.1944, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 187 (Update 345389).	Train loss: 0.1941, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 188 (Update 347236).	Train loss: 0.1947, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 189 (Update 349083).	Train loss: 0.1948, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 190 (Update 350930).	Train loss: 0.1942, Val roc_auc: 0.957, Best Epoch: 119
Epoch 191 (Update 352777).	Train loss: 0.1938, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 192 (Update 354624).	Train loss: 0.1942, Val roc_auc: 0.9576, Best Epoch: 119
Epoch 193 (Update 356471).	Train loss: 0.1942, Val roc_auc: 0.9574, Best Epoch: 119
Epoch 194 (Update 358318).	Train loss: 0.1937, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 195 (Update 360165).	Train loss: 0.1941, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 196 (Update 362012).	Train loss: 0.1937, Val roc_auc: 0.9573, Best Epoch: 119
Epoch 197 (Update 363859).	Train loss: 0.1936, Val roc_auc: 0.9572, Best Epoch: 119
Epoch 198 (Update 365706).	Train loss: 0.1939, Val roc_auc: 0.957, Best Epoch: 119
Best model found on Epoch 119 (Update 219793). Val roc_auc: 0.9576656661520576
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 22 features (19 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)

[50]	valid_set's binary_logloss: 0.207424
[100]	valid_set's binary_logloss: 0.198719
[150]	valid_set's binary_logloss: 0.198766

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.206401
[100]	valid_set's binary_logloss: 0.197481
[150]	valid_set's binary_logloss: 0.197414

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.207826
[100]	valid_set's binary_logloss: 0.199052
[150]	valid_set's binary_logloss: 0.199049

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.208875
[100]	valid_set's binary_logloss: 0.200154
[150]	valid_set's binary_logloss: 0.200086

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.20742
[100]	valid_set's binary_logloss: 0.198123
[150]	valid_set's binary_logloss: 0.197921
[200]	valid_set's binary_logloss: 0.198107

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209483
[100]	valid_set's binary_logloss: 0.200985
[150]	valid_set's binary_logloss: 0.200885

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.20891
[100]	valid_set's binary_logloss: 0.200327
[150]	valid_set's binary_logloss: 0.200427

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.205961
[100]	valid_set's binary_logloss: 0.196409
[150]	valid_set's binary_logloss: 0.196123

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L2\model.pkl
	0.9622	 = Validation score   (roc_auc)
	13.32s	 = Training   runtime
	0.27s	 = Validation runtime
	2513.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 20474.64s of the 20474.61s of remaining time.
	Fitting LightGBMLarge_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209921
[100]	valid_set's binary_logloss: 0.199214
[150]	valid_set's binary_logloss: 0.198642
[200]	valid_set's binary_logloss: 0.198646

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.208764
[100]	valid_set's binary_logloss: 0.197696
[150]	valid_set's binary_logloss: 0.196909
[200]	valid_set's binary_logloss: 0.196823
[250]	valid_set's binary_logloss: 0.196836

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.21019
[100]	valid_set's binary_logloss: 0.199367
[150]	valid_set's binary_logloss: 0.19852
[200]	valid_set's binary_logloss: 0.198502

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.211469
[100]	valid_set's binary_logloss: 0.20051
[150]	valid_set's binary_logloss: 0.199675
[200]	valid_set's binary_logloss: 0.19963
[250]	valid_set's binary_logloss: 0.199756

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.209955
[100]	valid_set's binary_logloss: 0.198679
[150]	valid_set's binary_logloss: 0.197762
[200]	valid_set's binary_logloss: 0.197657
[250]	valid_set's binary_logloss: 0.197597
[300]	valid_set's binary_logloss: 0.197603

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.212261
[100]	valid_set's binary_logloss: 0.201292
[150]	valid_set's binary_logloss: 0.200539
[200]	valid_set's binary_logloss: 0.200348
[250]	valid_set's binary_logloss: 0.200324
[300]	valid_set's binary_logloss: 0.200392

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.211264
[100]	valid_set's binary_logloss: 0.200425
[150]	valid_set's binary_logloss: 0.199819
[200]	valid_set's binary_logloss: 0.199657
[250]	valid_set's binary_logloss: 0.199661

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.208003
[100]	valid_set's binary_logloss: 0.196468
[150]	valid_set's binary_logloss: 0.195609
[200]	valid_set's binary_logloss: 0.195376
[250]	valid_set's binary_logloss: 0.195393

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L2\model.pkl
	0.9624	 = Validation score   (roc_auc)
	18.06s	 = Training   runtime
	0.54s	 = Validation runtime
	2488.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: CatBoost_BAG_L2 ... Training model for up to 20455.48s of the 20455.45s of remaining time.
	Fitting CatBoost_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6215118	test: 0.6214610	best: 0.6214610 (0)	total: 9.55ms	remaining: 9.55ms
1:	learn: 0.5594836	test: 0.5593750	best: 0.5593750 (1)	total: 18.9ms	remaining: 0us
bestTest = 0.5593750463
bestIteration = 1
0:	learn: 0.6217382	test: 0.6216752	best: 0.6216752 (0)	total: 17.2ms	remaining: 1m 16s
20:	learn: 0.2298790	test: 0.2300037	best: 0.2300037 (20)	total: 350ms	remaining: 1m 13s
40:	learn: 0.2026015	test: 0.2030236	best: 0.2030236 (40)	total: 681ms	remaining: 1m 12s
60:	learn: 0.1986063	test: 0.1991923	best: 0.1991923 (60)	total: 1.02s	remaining: 1m 12s
80:	learn: 0.1974890	test: 0.1982345	best: 0.1982345 (80)	total: 1.36s	remaining: 1m 13s
100:	learn: 0.1969973	test: 0.1978496	best: 0.1978496 (100)	total: 1.72s	remaining: 1m 13s
120:	learn: 0.1966177	test: 0.1976293	best: 0.1976293 (120)	total: 2.07s	remaining: 1m 13s
140:	learn: 0.1963419	test: 0.1974900	best: 0.1974900 (140)	total: 2.42s	remaining: 1m 13s
160:	learn: 0.1960715	test: 0.1973693	best: 0.1973693 (160)	total: 2.76s	remaining: 1m 13s
180:	learn: 0.1958447	test: 0.1972670	best: 0.1972670 (180)	total: 3.12s	remaining: 1m 12s
200:	learn: 0.1956698	test: 0.1972072	best: 0.1972072 (200)	total: 3.47s	remaining: 1m 12s
220:	learn: 0.1954750	test: 0.1971534	best: 0.1971506 (218)	total: 3.82s	remaining: 1m 12s
240:	learn: 0.1952937	test: 0.1971093	best: 0.1971082 (235)	total: 4.16s	remaining: 1m 12s
260:	learn: 0.1951169	test: 0.1970682	best: 0.1970643 (258)	total: 4.5s	remaining: 1m 11s
280:	learn: 0.1949517	test: 0.1970196	best: 0.1970196 (280)	total: 4.86s	remaining: 1m 11s
300:	learn: 0.1947926	test: 0.1969863	best: 0.1969863 (300)	total: 5.22s	remaining: 1m 11s
320:	learn: 0.1946266	test: 0.1969563	best: 0.1969563 (320)	total: 5.56s	remaining: 1m 10s
340:	learn: 0.1944610	test: 0.1969635	best: 0.1969563 (320)	total: 5.91s	remaining: 1m 10s
360:	learn: 0.1942826	test: 0.1969241	best: 0.1969222 (359)	total: 6.27s	remaining: 1m 10s
380:	learn: 0.1941458	test: 0.1969087	best: 0.1969064 (374)	total: 6.63s	remaining: 1m 10s
400:	learn: 0.1939986	test: 0.1969063	best: 0.1969056 (399)	total: 6.99s	remaining: 1m 9s
420:	learn: 0.1938485	test: 0.1968949	best: 0.1968853 (402)	total: 7.35s	remaining: 1m 9s
440:	learn: 0.1937318	test: 0.1968875	best: 0.1968853 (402)	total: 7.73s	remaining: 1m 9s
460:	learn: 0.1935959	test: 0.1968806	best: 0.1968806 (460)	total: 8.08s	remaining: 1m 9s
480:	learn: 0.1934634	test: 0.1968826	best: 0.1968776 (462)	total: 8.45s	remaining: 1m 9s
500:	learn: 0.1933064	test: 0.1968561	best: 0.1968507 (493)	total: 8.8s	remaining: 1m 8s
520:	learn: 0.1931383	test: 0.1968541	best: 0.1968507 (493)	total: 9.15s	remaining: 1m 8s
540:	learn: 0.1930142	test: 0.1968589	best: 0.1968507 (493)	total: 9.5s	remaining: 1m 8s
bestTest = 0.1968506915
bestIteration = 493
Shrink model to first 494 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6207033	test: 0.6204844	best: 0.6204844 (0)	total: 9.15ms	remaining: 9.15ms
1:	learn: 0.5571009	test: 0.5567534	best: 0.5567534 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.5567534365
bestIteration = 1
0:	learn: 0.6166193	test: 0.6164257	best: 0.6164257 (0)	total: 17.1ms	remaining: 1m 49s
20:	learn: 0.2312241	test: 0.2293918	best: 0.2293918 (20)	total: 349ms	remaining: 1m 46s
40:	learn: 0.2031641	test: 0.2013679	best: 0.2013679 (40)	total: 684ms	remaining: 1m 46s
60:	learn: 0.1989609	test: 0.1972892	best: 0.1972892 (60)	total: 1.02s	remaining: 1m 46s
80:	learn: 0.1978302	test: 0.1963353	best: 0.1963353 (80)	total: 1.37s	remaining: 1m 47s
100:	learn: 0.1972603	test: 0.1959315	best: 0.1959315 (100)	total: 1.72s	remaining: 1m 47s
120:	learn: 0.1969346	test: 0.1957711	best: 0.1957711 (120)	total: 2.07s	remaining: 1m 47s
140:	learn: 0.1966664	test: 0.1956452	best: 0.1956452 (140)	total: 2.42s	remaining: 1m 47s
160:	learn: 0.1964332	test: 0.1955470	best: 0.1955426 (155)	total: 2.77s	remaining: 1m 47s
180:	learn: 0.1962014	test: 0.1954722	best: 0.1954721 (179)	total: 3.13s	remaining: 1m 47s
200:	learn: 0.1960067	test: 0.1954141	best: 0.1954141 (200)	total: 3.47s	remaining: 1m 47s
220:	learn: 0.1958198	test: 0.1953722	best: 0.1953670 (217)	total: 3.82s	remaining: 1m 47s
240:	learn: 0.1956368	test: 0.1953328	best: 0.1953328 (240)	total: 4.17s	remaining: 1m 46s
260:	learn: 0.1954645	test: 0.1952947	best: 0.1952947 (260)	total: 4.53s	remaining: 1m 47s
280:	learn: 0.1952740	test: 0.1952656	best: 0.1952646 (279)	total: 4.88s	remaining: 1m 46s
300:	learn: 0.1951095	test: 0.1952459	best: 0.1952437 (295)	total: 5.22s	remaining: 1m 46s
320:	learn: 0.1949578	test: 0.1952457	best: 0.1952388 (305)	total: 5.57s	remaining: 1m 45s
340:	learn: 0.1948136	test: 0.1952127	best: 0.1952127 (340)	total: 5.93s	remaining: 1m 45s
360:	learn: 0.1946688	test: 0.1951965	best: 0.1951908 (348)	total: 6.28s	remaining: 1m 45s
380:	learn: 0.1945090	test: 0.1951738	best: 0.1951662 (373)	total: 6.63s	remaining: 1m 45s
400:	learn: 0.1943616	test: 0.1951599	best: 0.1951596 (397)	total: 6.98s	remaining: 1m 44s
420:	learn: 0.1942123	test: 0.1951524	best: 0.1951506 (414)	total: 7.33s	remaining: 1m 44s
440:	learn: 0.1940685	test: 0.1951417	best: 0.1951391 (434)	total: 7.68s	remaining: 1m 44s
460:	learn: 0.1939211	test: 0.1951029	best: 0.1951029 (460)	total: 8.03s	remaining: 1m 43s
480:	learn: 0.1937707	test: 0.1950936	best: 0.1950936 (480)	total: 8.38s	remaining: 1m 43s
500:	learn: 0.1936285	test: 0.1950693	best: 0.1950656 (497)	total: 8.74s	remaining: 1m 43s
520:	learn: 0.1935038	test: 0.1950635	best: 0.1950628 (518)	total: 9.11s	remaining: 1m 43s
540:	learn: 0.1933528	test: 0.1950686	best: 0.1950559 (531)	total: 9.45s	remaining: 1m 42s
560:	learn: 0.1932238	test: 0.1950727	best: 0.1950559 (531)	total: 9.82s	remaining: 1m 42s
580:	learn: 0.1930808	test: 0.1950784	best: 0.1950559 (531)	total: 10.2s	remaining: 1m 42s
bestTest = 0.195055942
bestIteration = 531
Shrink model to first 532 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6213683	test: 0.6213952	best: 0.6213952 (0)	total: 9.06ms	remaining: 9.06ms
1:	learn: 0.5561220	test: 0.5561852	best: 0.5561852 (1)	total: 17.9ms	remaining: 0us
bestTest = 0.5561852158
bestIteration = 1
0:	learn: 0.6162795	test: 0.6163112	best: 0.6163112 (0)	total: 16.9ms	remaining: 1m 51s
20:	learn: 0.2303540	test: 0.2304981	best: 0.2304981 (20)	total: 351ms	remaining: 1m 49s
40:	learn: 0.2028028	test: 0.2030571	best: 0.2030571 (40)	total: 683ms	remaining: 1m 49s
60:	learn: 0.1987269	test: 0.1990934	best: 0.1990934 (60)	total: 1.02s	remaining: 1m 49s
80:	learn: 0.1975316	test: 0.1980700	best: 0.1980700 (80)	total: 1.37s	remaining: 1m 49s
100:	learn: 0.1969974	test: 0.1976782	best: 0.1976782 (100)	total: 1.72s	remaining: 1m 50s
120:	learn: 0.1966392	test: 0.1974547	best: 0.1974547 (120)	total: 2.06s	remaining: 1m 50s
140:	learn: 0.1963281	test: 0.1972907	best: 0.1972907 (140)	total: 2.42s	remaining: 1m 50s
160:	learn: 0.1961132	test: 0.1972232	best: 0.1972232 (160)	total: 2.77s	remaining: 1m 50s
180:	learn: 0.1958826	test: 0.1971400	best: 0.1971390 (179)	total: 3.12s	remaining: 1m 50s
200:	learn: 0.1956335	test: 0.1970343	best: 0.1970343 (200)	total: 3.48s	remaining: 1m 50s
220:	learn: 0.1954386	test: 0.1969703	best: 0.1969703 (220)	total: 3.82s	remaining: 1m 50s
240:	learn: 0.1952616	test: 0.1969223	best: 0.1969221 (239)	total: 4.16s	remaining: 1m 49s
260:	learn: 0.1950907	test: 0.1969098	best: 0.1969092 (256)	total: 4.52s	remaining: 1m 49s
280:	learn: 0.1949179	test: 0.1968682	best: 0.1968673 (279)	total: 4.88s	remaining: 1m 49s
300:	learn: 0.1947584	test: 0.1968373	best: 0.1968365 (298)	total: 5.23s	remaining: 1m 49s
320:	learn: 0.1945972	test: 0.1968131	best: 0.1968131 (320)	total: 5.58s	remaining: 1m 49s
340:	learn: 0.1944389	test: 0.1968140	best: 0.1968090 (322)	total: 5.93s	remaining: 1m 48s
360:	learn: 0.1942869	test: 0.1967967	best: 0.1967960 (356)	total: 6.29s	remaining: 1m 48s
380:	learn: 0.1941379	test: 0.1967866	best: 0.1967774 (366)	total: 6.64s	remaining: 1m 48s
400:	learn: 0.1939632	test: 0.1967767	best: 0.1967750 (388)	total: 6.99s	remaining: 1m 47s
420:	learn: 0.1937898	test: 0.1967505	best: 0.1967476 (408)	total: 7.34s	remaining: 1m 47s
440:	learn: 0.1936202	test: 0.1967370	best: 0.1967290 (429)	total: 7.69s	remaining: 1m 47s
460:	learn: 0.1934790	test: 0.1967262	best: 0.1967238 (455)	total: 8.04s	remaining: 1m 47s
480:	learn: 0.1933272	test: 0.1967086	best: 0.1967040 (473)	total: 8.39s	remaining: 1m 46s
500:	learn: 0.1931978	test: 0.1967028	best: 0.1966984 (499)	total: 8.75s	remaining: 1m 46s
520:	learn: 0.1930467	test: 0.1966960	best: 0.1966906 (514)	total: 9.11s	remaining: 1m 46s
540:	learn: 0.1929046	test: 0.1966871	best: 0.1966871 (540)	total: 9.46s	remaining: 1m 45s
560:	learn: 0.1927739	test: 0.1966988	best: 0.1966871 (540)	total: 9.82s	remaining: 1m 45s
580:	learn: 0.1926367	test: 0.1966944	best: 0.1966871 (540)	total: 10.2s	remaining: 1m 45s
bestTest = 0.1966871119
bestIteration = 540
Shrink model to first 541 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6215208	test: 0.6216987	best: 0.6216987 (0)	total: 8.9ms	remaining: 8.9ms
1:	learn: 0.5605120	test: 0.5608507	best: 0.5608507 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5608506739
bestIteration = 1
0:	learn: 0.6165063	test: 0.6165893	best: 0.6165893 (0)	total: 17.3ms	remaining: 1m 53s
20:	learn: 0.2304969	test: 0.2319500	best: 0.2319500 (20)	total: 349ms	remaining: 1m 49s
40:	learn: 0.2024020	test: 0.2041920	best: 0.2041920 (40)	total: 695ms	remaining: 1m 51s
60:	learn: 0.1986329	test: 0.2006039	best: 0.2006039 (60)	total: 1.04s	remaining: 1m 51s
80:	learn: 0.1973509	test: 0.1994924	best: 0.1994924 (80)	total: 1.39s	remaining: 1m 51s
100:	learn: 0.1968492	test: 0.1991175	best: 0.1991166 (99)	total: 1.74s	remaining: 1m 51s
120:	learn: 0.1965282	test: 0.1989250	best: 0.1989250 (120)	total: 2.08s	remaining: 1m 51s
140:	learn: 0.1961965	test: 0.1987260	best: 0.1987260 (140)	total: 2.43s	remaining: 1m 51s
160:	learn: 0.1959795	test: 0.1986536	best: 0.1986514 (159)	total: 2.77s	remaining: 1m 50s
180:	learn: 0.1957787	test: 0.1985967	best: 0.1985967 (180)	total: 3.12s	remaining: 1m 50s
200:	learn: 0.1955451	test: 0.1984911	best: 0.1984911 (200)	total: 3.47s	remaining: 1m 50s
220:	learn: 0.1953490	test: 0.1984269	best: 0.1984269 (220)	total: 3.82s	remaining: 1m 50s
240:	learn: 0.1951512	test: 0.1983758	best: 0.1983758 (240)	total: 4.17s	remaining: 1m 50s
260:	learn: 0.1949816	test: 0.1983555	best: 0.1983472 (252)	total: 4.52s	remaining: 1m 49s
280:	learn: 0.1948330	test: 0.1983344	best: 0.1983344 (280)	total: 4.87s	remaining: 1m 49s
300:	learn: 0.1946693	test: 0.1983139	best: 0.1983071 (299)	total: 5.23s	remaining: 1m 49s
320:	learn: 0.1945070	test: 0.1982845	best: 0.1982801 (319)	total: 5.58s	remaining: 1m 49s
340:	learn: 0.1943489	test: 0.1982378	best: 0.1982378 (340)	total: 5.95s	remaining: 1m 49s
360:	learn: 0.1941998	test: 0.1982121	best: 0.1982121 (360)	total: 6.3s	remaining: 1m 49s
380:	learn: 0.1940410	test: 0.1981863	best: 0.1981863 (380)	total: 6.65s	remaining: 1m 48s
400:	learn: 0.1938941	test: 0.1981621	best: 0.1981621 (400)	total: 7s	remaining: 1m 48s
420:	learn: 0.1937662	test: 0.1981762	best: 0.1981567 (412)	total: 7.36s	remaining: 1m 48s
440:	learn: 0.1936005	test: 0.1981470	best: 0.1981460 (438)	total: 7.71s	remaining: 1m 47s
460:	learn: 0.1934594	test: 0.1981308	best: 0.1981308 (460)	total: 8.06s	remaining: 1m 47s
480:	learn: 0.1932940	test: 0.1981194	best: 0.1981190 (478)	total: 8.41s	remaining: 1m 47s
500:	learn: 0.1931348	test: 0.1981038	best: 0.1981023 (498)	total: 8.76s	remaining: 1m 46s
520:	learn: 0.1930242	test: 0.1980901	best: 0.1980901 (520)	total: 9.13s	remaining: 1m 46s
540:	learn: 0.1928927	test: 0.1980826	best: 0.1980767 (536)	total: 9.48s	remaining: 1m 46s
560:	learn: 0.1927408	test: 0.1980677	best: 0.1980662 (558)	total: 9.83s	remaining: 1m 45s
580:	learn: 0.1926058	test: 0.1980509	best: 0.1980509 (580)	total: 10.2s	remaining: 1m 45s
600:	learn: 0.1924759	test: 0.1980453	best: 0.1980432 (599)	total: 10.5s	remaining: 1m 45s
620:	learn: 0.1923512	test: 0.1980386	best: 0.1980331 (607)	total: 10.9s	remaining: 1m 45s
640:	learn: 0.1922068	test: 0.1980273	best: 0.1980262 (636)	total: 11.2s	remaining: 1m 44s
660:	learn: 0.1920690	test: 0.1980081	best: 0.1980061 (656)	total: 11.6s	remaining: 1m 44s
680:	learn: 0.1919185	test: 0.1980032	best: 0.1979998 (670)	total: 11.9s	remaining: 1m 43s
700:	learn: 0.1917876	test: 0.1979978	best: 0.1979970 (693)	total: 12.3s	remaining: 1m 43s
720:	learn: 0.1916415	test: 0.1979968	best: 0.1979936 (708)	total: 12.6s	remaining: 1m 43s
740:	learn: 0.1915259	test: 0.1980212	best: 0.1979936 (708)	total: 13s	remaining: 1m 42s
bestTest = 0.1979936235
bestIteration = 708
Shrink model to first 709 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6207708	test: 0.6208588	best: 0.6208588 (0)	total: 9.17ms	remaining: 9.17ms
1:	learn: 0.5598988	test: 0.5599887	best: 0.5599887 (1)	total: 17.8ms	remaining: 0us
bestTest = 0.5599887154
bestIteration = 1
0:	learn: 0.6208153	test: 0.6209021	best: 0.6209021 (0)	total: 16.8ms	remaining: 1m 50s
20:	learn: 0.2301375	test: 0.2302314	best: 0.2302314 (20)	total: 350ms	remaining: 1m 49s
40:	learn: 0.2030962	test: 0.2030707	best: 0.2030707 (40)	total: 684ms	remaining: 1m 49s
60:	learn: 0.1987923	test: 0.1987987	best: 0.1987987 (60)	total: 1.02s	remaining: 1m 49s
80:	learn: 0.1976104	test: 0.1976790	best: 0.1976790 (80)	total: 1.37s	remaining: 1m 50s
100:	learn: 0.1971015	test: 0.1972555	best: 0.1972555 (100)	total: 1.72s	remaining: 1m 50s
120:	learn: 0.1967621	test: 0.1970231	best: 0.1970231 (120)	total: 2.07s	remaining: 1m 50s
140:	learn: 0.1965644	test: 0.1969328	best: 0.1969328 (140)	total: 2.43s	remaining: 1m 50s
160:	learn: 0.1963246	test: 0.1967881	best: 0.1967881 (160)	total: 2.78s	remaining: 1m 50s
180:	learn: 0.1960876	test: 0.1966424	best: 0.1966424 (180)	total: 3.13s	remaining: 1m 50s
200:	learn: 0.1958763	test: 0.1965746	best: 0.1965724 (199)	total: 3.48s	remaining: 1m 50s
220:	learn: 0.1956348	test: 0.1964710	best: 0.1964710 (220)	total: 3.83s	remaining: 1m 50s
240:	learn: 0.1954544	test: 0.1964345	best: 0.1964345 (240)	total: 4.18s	remaining: 1m 50s
260:	learn: 0.1952749	test: 0.1964175	best: 0.1964134 (254)	total: 4.53s	remaining: 1m 49s
280:	learn: 0.1951072	test: 0.1963782	best: 0.1963782 (280)	total: 4.88s	remaining: 1m 49s
300:	learn: 0.1949451	test: 0.1963408	best: 0.1963408 (300)	total: 5.24s	remaining: 1m 49s
320:	learn: 0.1947723	test: 0.1963022	best: 0.1963010 (319)	total: 5.58s	remaining: 1m 48s
340:	learn: 0.1946383	test: 0.1963067	best: 0.1962998 (329)	total: 5.93s	remaining: 1m 48s
360:	learn: 0.1944833	test: 0.1962779	best: 0.1962779 (360)	total: 6.29s	remaining: 1m 48s
380:	learn: 0.1943438	test: 0.1962513	best: 0.1962493 (379)	total: 6.63s	remaining: 1m 48s
400:	learn: 0.1942133	test: 0.1962415	best: 0.1962389 (397)	total: 6.98s	remaining: 1m 47s
420:	learn: 0.1940584	test: 0.1962126	best: 0.1962060 (413)	total: 7.33s	remaining: 1m 47s
440:	learn: 0.1938838	test: 0.1961638	best: 0.1961638 (440)	total: 7.68s	remaining: 1m 46s
460:	learn: 0.1937272	test: 0.1961551	best: 0.1961527 (459)	total: 8.03s	remaining: 1m 46s
480:	learn: 0.1935659	test: 0.1961300	best: 0.1961230 (472)	total: 8.38s	remaining: 1m 46s
500:	learn: 0.1934240	test: 0.1961387	best: 0.1961230 (472)	total: 8.73s	remaining: 1m 46s
520:	learn: 0.1932725	test: 0.1961231	best: 0.1961230 (472)	total: 9.08s	remaining: 1m 45s
bestTest = 0.1961230399
bestIteration = 472
Shrink model to first 473 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6209162	test: 0.6210398	best: 0.6210398 (0)	total: 9.41ms	remaining: 9.41ms
1:	learn: 0.5599123	test: 0.5601536	best: 0.5601536 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.560153648
bestIteration = 1
0:	learn: 0.6162722	test: 0.6163669	best: 0.6163669 (0)	total: 17.4ms	remaining: 1m 55s
20:	learn: 0.2286246	test: 0.2304931	best: 0.2304931 (20)	total: 352ms	remaining: 1m 50s
40:	learn: 0.2026490	test: 0.2051097	best: 0.2051097 (40)	total: 684ms	remaining: 1m 49s
60:	learn: 0.1983427	test: 0.2010348	best: 0.2010348 (60)	total: 1.02s	remaining: 1m 48s
80:	learn: 0.1971940	test: 0.2000605	best: 0.2000605 (80)	total: 1.37s	remaining: 1m 50s
100:	learn: 0.1966922	test: 0.1996642	best: 0.1996642 (100)	total: 1.73s	remaining: 1m 51s
120:	learn: 0.1963433	test: 0.1994283	best: 0.1994283 (120)	total: 2.08s	remaining: 1m 51s
140:	learn: 0.1960861	test: 0.1992887	best: 0.1992887 (140)	total: 2.43s	remaining: 1m 51s
160:	learn: 0.1958682	test: 0.1991857	best: 0.1991840 (158)	total: 2.78s	remaining: 1m 51s
180:	learn: 0.1956768	test: 0.1991001	best: 0.1991001 (180)	total: 3.13s	remaining: 1m 50s
200:	learn: 0.1954916	test: 0.1990255	best: 0.1990255 (200)	total: 3.48s	remaining: 1m 50s
220:	learn: 0.1953034	test: 0.1989381	best: 0.1989381 (220)	total: 3.83s	remaining: 1m 50s
240:	learn: 0.1951655	test: 0.1988980	best: 0.1988980 (240)	total: 4.17s	remaining: 1m 50s
260:	learn: 0.1949774	test: 0.1988588	best: 0.1988588 (260)	total: 4.53s	remaining: 1m 49s
280:	learn: 0.1948163	test: 0.1988369	best: 0.1988316 (278)	total: 4.89s	remaining: 1m 49s
300:	learn: 0.1946709	test: 0.1988333	best: 0.1988262 (284)	total: 5.24s	remaining: 1m 49s
320:	learn: 0.1944930	test: 0.1987950	best: 0.1987919 (317)	total: 5.6s	remaining: 1m 49s
340:	learn: 0.1943019	test: 0.1987541	best: 0.1987541 (340)	total: 5.95s	remaining: 1m 49s
360:	learn: 0.1941467	test: 0.1987379	best: 0.1987371 (359)	total: 6.3s	remaining: 1m 48s
380:	learn: 0.1939800	test: 0.1987034	best: 0.1987034 (380)	total: 6.65s	remaining: 1m 48s
400:	learn: 0.1938308	test: 0.1987000	best: 0.1986944 (388)	total: 7.01s	remaining: 1m 48s
420:	learn: 0.1936796	test: 0.1986819	best: 0.1986791 (417)	total: 7.35s	remaining: 1m 47s
440:	learn: 0.1935264	test: 0.1986580	best: 0.1986580 (440)	total: 7.7s	remaining: 1m 47s
460:	learn: 0.1933885	test: 0.1986743	best: 0.1986580 (440)	total: 8.05s	remaining: 1m 47s
480:	learn: 0.1932564	test: 0.1986563	best: 0.1986540 (477)	total: 8.41s	remaining: 1m 46s
500:	learn: 0.1931220	test: 0.1986379	best: 0.1986379 (500)	total: 8.76s	remaining: 1m 46s
520:	learn: 0.1929575	test: 0.1986062	best: 0.1986059 (518)	total: 9.13s	remaining: 1m 46s
540:	learn: 0.1928352	test: 0.1985838	best: 0.1985838 (540)	total: 9.48s	remaining: 1m 46s
560:	learn: 0.1926888	test: 0.1985692	best: 0.1985686 (550)	total: 9.83s	remaining: 1m 45s
580:	learn: 0.1925477	test: 0.1985383	best: 0.1985383 (580)	total: 10.2s	remaining: 1m 45s
600:	learn: 0.1924150	test: 0.1985085	best: 0.1985063 (599)	total: 10.5s	remaining: 1m 45s
620:	learn: 0.1922822	test: 0.1985051	best: 0.1984967 (612)	total: 10.9s	remaining: 1m 44s
640:	learn: 0.1921392	test: 0.1984882	best: 0.1984841 (638)	total: 11.3s	remaining: 1m 44s
660:	learn: 0.1919760	test: 0.1984780	best: 0.1984780 (660)	total: 11.6s	remaining: 1m 44s
680:	learn: 0.1918328	test: 0.1984652	best: 0.1984588 (677)	total: 12s	remaining: 1m 43s
700:	learn: 0.1916863	test: 0.1984482	best: 0.1984482 (700)	total: 12.3s	remaining: 1m 43s
720:	learn: 0.1915568	test: 0.1984474	best: 0.1984445 (702)	total: 12.7s	remaining: 1m 43s
740:	learn: 0.1914384	test: 0.1984695	best: 0.1984445 (702)	total: 13s	remaining: 1m 43s
bestTest = 0.1984444532
bestIteration = 702
Shrink model to first 703 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6180530	test: 0.6182775	best: 0.6182775 (0)	total: 9.17ms	remaining: 9.17ms
1:	learn: 0.5583614	test: 0.5587389	best: 0.5587389 (1)	total: 17.5ms	remaining: 0us
bestTest = 0.5587388864
bestIteration = 1
0:	learn: 0.6163953	test: 0.6166124	best: 0.6166124 (0)	total: 17ms	remaining: 1m 51s
20:	learn: 0.2298537	test: 0.2311955	best: 0.2311955 (20)	total: 351ms	remaining: 1m 49s
40:	learn: 0.2025451	test: 0.2041023	best: 0.2041023 (40)	total: 685ms	remaining: 1m 49s
60:	learn: 0.1984552	test: 0.2001424	best: 0.2001424 (60)	total: 1.02s	remaining: 1m 49s
80:	learn: 0.1973686	test: 0.1991958	best: 0.1991958 (80)	total: 1.36s	remaining: 1m 49s
100:	learn: 0.1968720	test: 0.1988142	best: 0.1988142 (100)	total: 1.71s	remaining: 1m 49s
120:	learn: 0.1964802	test: 0.1985740	best: 0.1985740 (120)	total: 2.06s	remaining: 1m 49s
140:	learn: 0.1962571	test: 0.1984629	best: 0.1984629 (140)	total: 2.42s	remaining: 1m 50s
160:	learn: 0.1960521	test: 0.1984043	best: 0.1984034 (159)	total: 2.77s	remaining: 1m 50s
180:	learn: 0.1958455	test: 0.1983286	best: 0.1983252 (178)	total: 3.12s	remaining: 1m 50s
200:	learn: 0.1956381	test: 0.1982395	best: 0.1982395 (200)	total: 3.46s	remaining: 1m 49s
220:	learn: 0.1954483	test: 0.1981740	best: 0.1981740 (220)	total: 3.83s	remaining: 1m 50s
240:	learn: 0.1952641	test: 0.1981406	best: 0.1981406 (240)	total: 4.19s	remaining: 1m 50s
260:	learn: 0.1950819	test: 0.1980638	best: 0.1980629 (258)	total: 4.55s	remaining: 1m 49s
280:	learn: 0.1948907	test: 0.1980099	best: 0.1980099 (280)	total: 4.9s	remaining: 1m 49s
300:	learn: 0.1947346	test: 0.1979831	best: 0.1979820 (299)	total: 5.25s	remaining: 1m 49s
320:	learn: 0.1945597	test: 0.1979569	best: 0.1979569 (320)	total: 5.6s	remaining: 1m 49s
340:	learn: 0.1943803	test: 0.1979259	best: 0.1979215 (336)	total: 5.96s	remaining: 1m 48s
360:	learn: 0.1942045	test: 0.1979012	best: 0.1979012 (360)	total: 6.31s	remaining: 1m 48s
380:	learn: 0.1940493	test: 0.1978787	best: 0.1978774 (379)	total: 6.66s	remaining: 1m 48s
400:	learn: 0.1938779	test: 0.1978727	best: 0.1978721 (399)	total: 7.01s	remaining: 1m 47s
420:	learn: 0.1937258	test: 0.1978419	best: 0.1978419 (420)	total: 7.37s	remaining: 1m 47s
440:	learn: 0.1935647	test: 0.1978274	best: 0.1978222 (430)	total: 7.74s	remaining: 1m 47s
460:	learn: 0.1934040	test: 0.1978252	best: 0.1978171 (456)	total: 8.1s	remaining: 1m 47s
480:	learn: 0.1932431	test: 0.1978281	best: 0.1978167 (476)	total: 8.46s	remaining: 1m 47s
500:	learn: 0.1931149	test: 0.1978248	best: 0.1978167 (476)	total: 8.82s	remaining: 1m 46s
520:	learn: 0.1929858	test: 0.1978393	best: 0.1978167 (476)	total: 9.18s	remaining: 1m 46s
bestTest = 0.1978166806
bestIteration = 476
Shrink model to first 477 iterations.

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6209925	test: 0.6208334	best: 0.6208334 (0)	total: 9.24ms	remaining: 9.24ms
1:	learn: 0.5591666	test: 0.5588323	best: 0.5588323 (1)	total: 18.2ms	remaining: 0us
bestTest = 0.5588323288
bestIteration = 1
0:	learn: 0.6172033	test: 0.6170629	best: 0.6170629 (0)	total: 17.3ms	remaining: 1m 57s
20:	learn: 0.2305246	test: 0.2288671	best: 0.2288671 (20)	total: 348ms	remaining: 1m 52s
40:	learn: 0.2028259	test: 0.2009957	best: 0.2009957 (40)	total: 680ms	remaining: 1m 52s
60:	learn: 0.1989999	test: 0.1970984	best: 0.1970984 (60)	total: 1.02s	remaining: 1m 52s
80:	learn: 0.1978510	test: 0.1959695	best: 0.1959695 (80)	total: 1.36s	remaining: 1m 52s
100:	learn: 0.1973271	test: 0.1955372	best: 0.1955372 (100)	total: 1.71s	remaining: 1m 53s
120:	learn: 0.1969768	test: 0.1953069	best: 0.1953069 (120)	total: 2.06s	remaining: 1m 53s
140:	learn: 0.1967251	test: 0.1951968	best: 0.1951864 (136)	total: 2.41s	remaining: 1m 54s
160:	learn: 0.1964913	test: 0.1950940	best: 0.1950940 (160)	total: 2.77s	remaining: 1m 54s
180:	learn: 0.1962996	test: 0.1950355	best: 0.1950355 (180)	total: 3.12s	remaining: 1m 54s
200:	learn: 0.1961064	test: 0.1949427	best: 0.1949398 (199)	total: 3.49s	remaining: 1m 54s
220:	learn: 0.1959125	test: 0.1949029	best: 0.1948997 (217)	total: 3.85s	remaining: 1m 54s
240:	learn: 0.1957476	test: 0.1948605	best: 0.1948554 (239)	total: 4.2s	remaining: 1m 54s
260:	learn: 0.1955854	test: 0.1948411	best: 0.1948411 (260)	total: 4.55s	remaining: 1m 54s
280:	learn: 0.1954158	test: 0.1948171	best: 0.1948170 (279)	total: 4.9s	remaining: 1m 54s
300:	learn: 0.1952379	test: 0.1947877	best: 0.1947854 (299)	total: 5.26s	remaining: 1m 53s
320:	learn: 0.1950823	test: 0.1947704	best: 0.1947704 (320)	total: 5.61s	remaining: 1m 53s
340:	learn: 0.1949253	test: 0.1947566	best: 0.1947516 (339)	total: 5.96s	remaining: 1m 53s
360:	learn: 0.1947693	test: 0.1947295	best: 0.1947228 (357)	total: 6.3s	remaining: 1m 52s
380:	learn: 0.1946084	test: 0.1946976	best: 0.1946976 (380)	total: 6.65s	remaining: 1m 52s
400:	learn: 0.1944589	test: 0.1946605	best: 0.1946594 (399)	total: 7.01s	remaining: 1m 52s
420:	learn: 0.1943256	test: 0.1946514	best: 0.1946514 (420)	total: 7.38s	remaining: 1m 52s
440:	learn: 0.1941979	test: 0.1946481	best: 0.1946481 (440)	total: 7.75s	remaining: 1m 52s
460:	learn: 0.1940668	test: 0.1946387	best: 0.1946387 (460)	total: 8.1s	remaining: 1m 51s
480:	learn: 0.1939226	test: 0.1946108	best: 0.1946097 (479)	total: 8.45s	remaining: 1m 51s
500:	learn: 0.1937845	test: 0.1945870	best: 0.1945852 (497)	total: 8.8s	remaining: 1m 50s
520:	learn: 0.1936535	test: 0.1945795	best: 0.1945768 (519)	total: 9.17s	remaining: 1m 50s
540:	learn: 0.1935226	test: 0.1945663	best: 0.1945656 (539)	total: 9.52s	remaining: 1m 50s
560:	learn: 0.1933886	test: 0.1945705	best: 0.1945656 (539)	total: 9.88s	remaining: 1m 50s
580:	learn: 0.1932116	test: 0.1945524	best: 0.1945499 (579)	total: 10.2s	remaining: 1m 49s
600:	learn: 0.1930796	test: 0.1945645	best: 0.1945479 (586)	total: 10.6s	remaining: 1m 49s
620:	learn: 0.1929527	test: 0.1945551	best: 0.1945479 (586)	total: 10.9s	remaining: 1m 49s
bestTest = 0.1945478886
bestIteration = 586
Shrink model to first 587 iterations.

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L2\model.pkl
	0.9631	 = Validation score   (roc_auc)
	101.46s	 = Training   runtime
	0.23s	 = Validation runtime
	2516.8	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 20353.20s of the 20353.17s of remaining time.
	Fitting ExtraTreesGini_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L2\utils\model_template.pkl
	Warning: Potentially not enough memory to safely train model. Estimated to require 2.857 GB out of 6.747 GB available memory (42.342%)... (50.000% of avail memory is the max safe size)
	To avoid this warning, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.11 to avoid the warning)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=2.9/6.7 GB
	42.42s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesGini_BAG_L2\model.pkl
	0.962	 = Validation score   (roc_auc)
	17.9s	 = Training   runtime
	9.67s	 = Validation runtime
	2428.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 20325.03s of the 20325.00s of remaining time.
	Fitting ExtraTreesEntr_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L2\utils\model_template.pkl
	Warning: Potentially not enough memory to safely train model. Estimated to require 2.857 GB out of 6.132 GB available memory (46.590%)... (50.000% of avail memory is the max safe size)
	To avoid this warning, specify the model hyperparameter "ag.max_memory_usage_ratio" to a larger value (currently 1.0, set to >=1.21 to avoid the warning)
		To set the same value for all models, do the following when calling predictor.fit: `predictor.fit(..., ag_args_fit={"ag.max_memory_usage_ratio": VALUE})`
		Setting "ag.max_memory_usage_ratio" to values above 1 may result in out-of-memory errors. You may consider using a machine with more memory as a safer alternative.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=2.9/6.1 GB
	42.62s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L2\model.pkl
	0.9623	 = Validation score   (roc_auc)
	22.53s	 = Training   runtime
	10.43s	 = Validation runtime
	2419.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: XGBoost_BAG_L2 ... Training model for up to 20291.49s of the 20291.46s of remaining time.
	Fitting XGBoost_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45352
[50]	validation_0-logloss:0.19801
[100]	validation_0-logloss:0.19776
[120]	validation_0-logloss:0.19782

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45316
[50]	validation_0-logloss:0.19644
[100]	validation_0-logloss:0.19616
[138]	validation_0-logloss:0.19621

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45355
[50]	validation_0-logloss:0.19799
[100]	validation_0-logloss:0.19774
[117]	validation_0-logloss:0.19779

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45361
[50]	validation_0-logloss:0.19936
[100]	validation_0-logloss:0.19919
[108]	validation_0-logloss:0.19925

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45350
[50]	validation_0-logloss:0.19781
[100]	validation_0-logloss:0.19734
[150]	validation_0-logloss:0.19749
[155]	validation_0-logloss:0.19750

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45395
[50]	validation_0-logloss:0.20008
[100]	validation_0-logloss:0.19974
[138]	validation_0-logloss:0.19988

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45368
[50]	validation_0-logloss:0.19921
[100]	validation_0-logloss:0.19893
[137]	validation_0-logloss:0.19904

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.45343
[50]	validation_0-logloss:0.19582
[100]	validation_0-logloss:0.19537
[150]	validation_0-logloss:0.19547
[172]	validation_0-logloss:0.19554

Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L2\model.pkl
	0.9627	 = Validation score   (roc_auc)
	35.61s	 = Training   runtime
	0.76s	 = Validation runtime
	2467.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\trainer.pkl
Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 20254.59s of the 20254.56s of remaining time.
	Fitting NeuralNetTorch_BAG_L2 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L2\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 27 features (24 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=59, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1847).	Train loss: 0.2181, Val roc_auc: 0.9614, Best Epoch: 1
Epoch 2 (Update 3694).	Train loss: 0.2025, Val roc_auc: 0.962, Best Epoch: 2
Epoch 3 (Update 5541).	Train loss: 0.2007, Val roc_auc: 0.9622, Best Epoch: 3
Epoch 4 (Update 7388).	Train loss: 0.2, Val roc_auc: 0.9623, Best Epoch: 4
Epoch 5 (Update 9235).	Train loss: 0.1992, Val roc_auc: 0.9623, Best Epoch: 4
Epoch 6 (Update 11082).	Train loss: 0.1986, Val roc_auc: 0.9623, Best Epoch: 4
Epoch 7 (Update 12929).	Train loss: 0.198, Val roc_auc: 0.9623, Best Epoch: 4
Epoch 8 (Update 14776).	Train loss: 0.1977, Val roc_auc: 0.9624, Best Epoch: 8
Epoch 9 (Update 16623).	Train loss: 0.1971, Val roc_auc: 0.9624, Best Epoch: 9
Epoch 10 (Update 18470).	Train loss: 0.1969, Val roc_auc: 0.9624, Best Epoch: 10
Epoch 11 (Update 20317).	Train loss: 0.1965, Val roc_auc: 0.9625, Best Epoch: 11
Epoch 12 (Update 22164).	Train loss: 0.1961, Val roc_auc: 0.9624, Best Epoch: 11
Epoch 13 (Update 24011).	Train loss: 0.1959, Val roc_auc: 0.9624, Best Epoch: 11
Epoch 14 (Update 25858).	Train loss: 0.1954, Val roc_auc: 0.9622, Best Epoch: 11
Epoch 15 (Update 27705).	Train loss: 0.1952, Val roc_auc: 0.9624, Best Epoch: 11
Epoch 16 (Update 29552).	Train loss: 0.195, Val roc_auc: 0.9623, Best Epoch: 11
Epoch 17 (Update 31399).	Train loss: 0.1946, Val roc_auc: 0.9621, Best Epoch: 11
Epoch 18 (Update 33246).	Train loss: 0.1943, Val roc_auc: 0.9621, Best Epoch: 11
Epoch 19 (Update 35093).	Train loss: 0.1939, Val roc_auc: 0.962, Best Epoch: 11
Epoch 20 (Update 36940).	Train loss: 0.1938, Val roc_auc: 0.9621, Best Epoch: 11
Epoch 21 (Update 38787).	Train loss: 0.1934, Val roc_auc: 0.962, Best Epoch: 11
Epoch 22 (Update 40634).	Train loss: 0.1932, Val roc_auc: 0.9617, Best Epoch: 11
Epoch 23 (Update 42481).	Train loss: 0.1928, Val roc_auc: 0.9618, Best Epoch: 11
Epoch 24 (Update 44328).	Train loss: 0.1925, Val roc_auc: 0.9616, Best Epoch: 11
Epoch 25 (Update 46175).	Train loss: 0.1924, Val roc_auc: 0.9616, Best Epoch: 11
Epoch 26 (Update 48022).	Train loss: 0.1918, Val roc_auc: 0.9616, Best Epoch: 11
Epoch 27 (Update 49869).	Train loss: 0.1918, Val roc_auc: 0.9616, Best Epoch: 11
Epoch 28 (Update 51716).	Train loss: 0.1913, Val roc_auc: 0.9613, Best Epoch: 11
Epoch 29 (Update 53563).	Train loss: 0.1911, Val roc_auc: 0.9613, Best Epoch: 11
Epoch 30 (Update 55410).	Train loss: 0.191, Val roc_auc: 0.9614, Best Epoch: 11
Epoch 31 (Update 57257).	Train loss: 0.1904, Val roc_auc: 0.9609, Best Epoch: 11
Epoch 32 (Update 59104).	Train loss: 0.1903, Val roc_auc: 0.9611, Best Epoch: 11
Epoch 33 (Update 60951).	Train loss: 0.1902, Val roc_auc: 0.9611, Best Epoch: 11
Epoch 34 (Update 62798).	Train loss: 0.1897, Val roc_auc: 0.9609, Best Epoch: 11
Epoch 35 (Update 64645).	Train loss: 0.1895, Val roc_auc: 0.961, Best Epoch: 11
Epoch 36 (Update 66492).	Train loss: 0.1893, Val roc_auc: 0.9606, Best Epoch: 11
Best model found on Epoch 11 (Update 20317). Val roc_auc: 0.9624742861992382
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 27 features (24 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=59, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1847).	Train loss: 0.2185, Val roc_auc: 0.9623, Best Epoch: 1
Epoch 2 (Update 3694).	Train loss: 0.2028, Val roc_auc: 0.9626, Best Epoch: 2
Epoch 3 (Update 5541).	Train loss: 0.2011, Val roc_auc: 0.9627, Best Epoch: 3
Epoch 4 (Update 7388).	Train loss: 0.2001, Val roc_auc: 0.9629, Best Epoch: 4
Epoch 5 (Update 9235).	Train loss: 0.1996, Val roc_auc: 0.963, Best Epoch: 5
Epoch 6 (Update 11082).	Train loss: 0.1989, Val roc_auc: 0.9631, Best Epoch: 6
Epoch 7 (Update 12929).	Train loss: 0.1984, Val roc_auc: 0.9631, Best Epoch: 7
Epoch 8 (Update 14776).	Train loss: 0.1979, Val roc_auc: 0.963, Best Epoch: 7
Epoch 9 (Update 16623).	Train loss: 0.1976, Val roc_auc: 0.9631, Best Epoch: 9
Epoch 10 (Update 18470).	Train loss: 0.1971, Val roc_auc: 0.9632, Best Epoch: 10
Epoch 11 (Update 20317).	Train loss: 0.197, Val roc_auc: 0.9632, Best Epoch: 10
Epoch 12 (Update 22164).	Train loss: 0.1966, Val roc_auc: 0.9631, Best Epoch: 10
Epoch 13 (Update 24011).	Train loss: 0.1961, Val roc_auc: 0.9631, Best Epoch: 10
Epoch 14 (Update 25858).	Train loss: 0.196, Val roc_auc: 0.963, Best Epoch: 10
Epoch 15 (Update 27705).	Train loss: 0.1954, Val roc_auc: 0.9629, Best Epoch: 10
Epoch 16 (Update 29552).	Train loss: 0.1952, Val roc_auc: 0.9629, Best Epoch: 10
Epoch 17 (Update 31399).	Train loss: 0.1949, Val roc_auc: 0.963, Best Epoch: 10
Epoch 18 (Update 33246).	Train loss: 0.1946, Val roc_auc: 0.9629, Best Epoch: 10
Epoch 19 (Update 35093).	Train loss: 0.1941, Val roc_auc: 0.9628, Best Epoch: 10
Epoch 20 (Update 36940).	Train loss: 0.1938, Val roc_auc: 0.9627, Best Epoch: 10
Epoch 21 (Update 38787).	Train loss: 0.1936, Val roc_auc: 0.9627, Best Epoch: 10
Epoch 22 (Update 40634).	Train loss: 0.1935, Val roc_auc: 0.9628, Best Epoch: 10
Epoch 23 (Update 42481).	Train loss: 0.1931, Val roc_auc: 0.9628, Best Epoch: 10
Epoch 24 (Update 44328).	Train loss: 0.1927, Val roc_auc: 0.9626, Best Epoch: 10
Epoch 25 (Update 46175).	Train loss: 0.1924, Val roc_auc: 0.9625, Best Epoch: 10
Epoch 26 (Update 48022).	Train loss: 0.1923, Val roc_auc: 0.9626, Best Epoch: 10
Epoch 27 (Update 49869).	Train loss: 0.192, Val roc_auc: 0.9626, Best Epoch: 10
Epoch 28 (Update 51716).	Train loss: 0.1917, Val roc_auc: 0.9624, Best Epoch: 10
Epoch 29 (Update 53563).	Train loss: 0.1912, Val roc_auc: 0.9625, Best Epoch: 10
Epoch 30 (Update 55410).	Train loss: 0.1912, Val roc_auc: 0.9623, Best Epoch: 10
Epoch 31 (Update 57257).	Train loss: 0.1908, Val roc_auc: 0.9623, Best Epoch: 10
Epoch 32 (Update 59104).	Train loss: 0.1904, Val roc_auc: 0.9622, Best Epoch: 10
Epoch 33 (Update 60951).	Train loss: 0.1905, Val roc_auc: 0.9623, Best Epoch: 10
Epoch 34 (Update 62798).	Train loss: 0.19, Val roc_auc: 0.962, Best Epoch: 10
Best model found on Epoch 10 (Update 18470). Val roc_auc: 0.9632382940741842
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 27 features (24 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=59, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1847).	Train loss: 0.2178, Val roc_auc: 0.9615, Best Epoch: 1
Epoch 2 (Update 3694).	Train loss: 0.2022, Val roc_auc: 0.9619, Best Epoch: 2
Epoch 3 (Update 5541).	Train loss: 0.2007, Val roc_auc: 0.9621, Best Epoch: 3
Epoch 4 (Update 7388).	Train loss: 0.1998, Val roc_auc: 0.9623, Best Epoch: 4
Epoch 5 (Update 9235).	Train loss: 0.1992, Val roc_auc: 0.9622, Best Epoch: 4
Epoch 6 (Update 11082).	Train loss: 0.1985, Val roc_auc: 0.9623, Best Epoch: 6
Epoch 7 (Update 12929).	Train loss: 0.1981, Val roc_auc: 0.9624, Best Epoch: 7
Epoch 8 (Update 14776).	Train loss: 0.1977, Val roc_auc: 0.9623, Best Epoch: 7
Epoch 9 (Update 16623).	Train loss: 0.1973, Val roc_auc: 0.9624, Best Epoch: 7
Epoch 10 (Update 18470).	Train loss: 0.1969, Val roc_auc: 0.9623, Best Epoch: 7
Epoch 11 (Update 20317).	Train loss: 0.1965, Val roc_auc: 0.9623, Best Epoch: 7
Epoch 12 (Update 22164).	Train loss: 0.1962, Val roc_auc: 0.9622, Best Epoch: 7
Epoch 13 (Update 24011).	Train loss: 0.1959, Val roc_auc: 0.9624, Best Epoch: 7
Epoch 14 (Update 25858).	Train loss: 0.1956, Val roc_auc: 0.9624, Best Epoch: 14
Epoch 15 (Update 27705).	Train loss: 0.1953, Val roc_auc: 0.9623, Best Epoch: 14
Epoch 16 (Update 29552).	Train loss: 0.195, Val roc_auc: 0.9622, Best Epoch: 14
Epoch 17 (Update 31399).	Train loss: 0.1948, Val roc_auc: 0.9621, Best Epoch: 14
Epoch 18 (Update 33246).	Train loss: 0.1945, Val roc_auc: 0.9619, Best Epoch: 14
Epoch 19 (Update 35093).	Train loss: 0.1942, Val roc_auc: 0.9621, Best Epoch: 14
Epoch 20 (Update 36940).	Train loss: 0.1941, Val roc_auc: 0.9619, Best Epoch: 14
Epoch 21 (Update 38787).	Train loss: 0.1938, Val roc_auc: 0.9619, Best Epoch: 14
Epoch 22 (Update 40634).	Train loss: 0.1933, Val roc_auc: 0.9618, Best Epoch: 14
Epoch 23 (Update 42481).	Train loss: 0.1932, Val roc_auc: 0.9619, Best Epoch: 14
Epoch 24 (Update 44328).	Train loss: 0.1928, Val roc_auc: 0.9618, Best Epoch: 14
Epoch 25 (Update 46175).	Train loss: 0.1925, Val roc_auc: 0.9618, Best Epoch: 14
Epoch 26 (Update 48022).	Train loss: 0.1923, Val roc_auc: 0.9617, Best Epoch: 14
Epoch 27 (Update 49869).	Train loss: 0.1921, Val roc_auc: 0.9619, Best Epoch: 14
Epoch 28 (Update 51716).	Train loss: 0.192, Val roc_auc: 0.9617, Best Epoch: 14
Epoch 29 (Update 53563).	Train loss: 0.1916, Val roc_auc: 0.9617, Best Epoch: 14
Epoch 30 (Update 55410).	Train loss: 0.1911, Val roc_auc: 0.9616, Best Epoch: 14
Epoch 31 (Update 57257).	Train loss: 0.1911, Val roc_auc: 0.9616, Best Epoch: 14
Epoch 32 (Update 59104).	Train loss: 0.1911, Val roc_auc: 0.9614, Best Epoch: 14
Epoch 33 (Update 60951).	Train loss: 0.1905, Val roc_auc: 0.9614, Best Epoch: 14
Epoch 34 (Update 62798).	Train loss: 0.1905, Val roc_auc: 0.9613, Best Epoch: 14
Epoch 35 (Update 64645).	Train loss: 0.1903, Val roc_auc: 0.9612, Best Epoch: 14
Epoch 36 (Update 66492).	Train loss: 0.19, Val roc_auc: 0.9614, Best Epoch: 14
Epoch 37 (Update 68339).	Train loss: 0.1897, Val roc_auc: 0.9613, Best Epoch: 14
Epoch 38 (Update 70186).	Train loss: 0.1897, Val roc_auc: 0.9611, Best Epoch: 14
Epoch 39 (Update 72033).	Train loss: 0.1894, Val roc_auc: 0.9614, Best Epoch: 14
Epoch 40 (Update 73880).	Train loss: 0.1892, Val roc_auc: 0.9612, Best Epoch: 14
Best model found on Epoch 14 (Update 25858). Val roc_auc: 0.9623769273384948
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:
{
    "continuous": [
        "Year",
        "LapNumber",
        "Position",
        "RaceProgress",
        "Position_Change",
        "MaxTireLife",
        "TireRemainingLife",
        "TireAgePct",
        "TireRemainingPct",
        "LapsRemaining",
        "Prev_Position"
    ],
    "skewed": [
        "LightGBM_BAG_L1",
        "LightGBMLarge_BAG_L1",
        "CatBoost_BAG_L1",
        "XGBoost_BAG_L1",
        "NeuralNetTorch_BAG_L1",
        "Stint",
        "TyreLife",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "RaceLaps",
        "LapTimeAvg_3"
    ],
    "onehot": [],
    "embed": [
        "Driver",
        "Compound",
        "Race"
    ],
    "language": [],
    "bool": [
        "PitStop"
    ]
}


Training data for TabularNeuralNetTorchModel has: 472889 examples, 27 features (24 vector, 3 embedding)
Training on GPU (CUDA)
Neural network architecture:
EmbedNet(
  (embed_blocks): ModuleList(
    (0): Embedding(102, 21)
    (1): Embedding(6, 4)
    (2): Embedding(29, 10)
  )
  (main_block): Sequential(
    (0): Linear(in_features=59, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=128, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=128, out_features=128, bias=True)
    (10): ReLU()
    (11): Linear(in_features=128, out_features=2, bias=True)
  )
  (softmax): Softmax(dim=1)
)
Training tabular neural network for up to 1000 epochs...
Epoch 1 (Update 1847).	Train loss: 0.2175, Val roc_auc: 0.9609, Best Epoch: 1
Epoch 2 (Update 3694).	Train loss: 0.202, Val roc_auc: 0.9614, Best Epoch: 2
Epoch 3 (Update 5541).	Train loss: 0.2004, Val roc_auc: 0.9615, Best Epoch: 3
Epoch 4 (Update 7388).	Train loss: 0.1995, Val roc_auc: 0.9616, Best Epoch: 4
Epoch 5 (Update 9235).	Train loss: 0.1988, Val roc_auc: 0.9616, Best Epoch: 4
Epoch 6 (Update 11082).	Train loss: 0.1984, Val roc_auc: 0.9616, Best Epoch: 6
Epoch 7 (Update 12929).	Train loss: 0.1978, Val roc_auc: 0.9616, Best Epoch: 6
Epoch 8 (Update 14776).	Train loss: 0.1973, Val roc_auc: 0.9616, Best Epoch: 6
Epoch 9 (Update 16623).	Train loss: 0.1969, Val roc_auc: 0.9617, Best Epoch: 9
Epoch 10 (Update 18470).	Train loss: 0.1964, Val roc_auc: 0.9616, Best Epoch: 9
Epoch 11 (Update 20317).	Train loss: 0.196, Val roc_auc: 0.9615, Best Epoch: 9
Epoch 12 (Update 22164).	Train loss: 0.1959, Val roc_auc: 0.9615, Best Epoch: 9
Epoch 13 (Update 24011).	Train loss: 0.1955, Val roc_auc: 0.9617, Best Epoch: 9
Epoch 14 (Update 25858).	Train loss: 0.1951, Val roc_auc: 0.9615, Best Epoch: 9
Epoch 15 (Update 27705).	Train loss: 0.1949, Val roc_auc: 0.9616, Best Epoch: 9
Epoch 16 (Update 29552).	Train loss: 0.1945, Val roc_auc: 0.9615, Best Epoch: 9
Epoch 17 (Update 31399).	Train loss: 0.1943, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 18 (Update 33246).	Train loss: 0.1938, Val roc_auc: 0.9614, Best Epoch: 9
Epoch 19 (Update 35093).	Train loss: 0.1937, Val roc_auc: 0.9613, Best Epoch: 9
Epoch 20 (Update 36940).	Train loss: 0.1933, Val roc_auc: 0.9612, Best Epoch: 9
Epoch 21 (Update 38787).	Train loss: 0.1931, Val roc_auc: 0.961, Best Epoch: 9
Epoch 22 (Update 40634).	Train loss: 0.1929, Val roc_auc: 0.9612, Best Epoch: 9
Epoch 23 (Update 42481).	Train loss: 0.1925, Val roc_auc: 0.9611, Best Epoch: 9
Epoch 24 (Update 44328).	Train loss: 0.1923, Val roc_auc: 0.9611, Best Epoch: 9
Epoch 25 (Update 46175).	Train loss: 0.192, Val roc_auc: 0.9609, Best Epoch: 9
Epoch 26 (Update 48022).	Train loss: 0.1917, Val roc_auc: 0.9609, Best Epoch: 9
Epoch 27 (Update 49869).	Train loss: 0.1914, Val roc_auc: 0.961, Best Epoch: 9
Epoch 28 (Update 51716).	Train loss: 0.1913, Val roc_auc: 0.961, Best Epoch: 9
Epoch 29 (Update 53563).	Train loss: 0.1911, Val roc_auc: 0.9609, Best Epoch: 9
Epoch 30 (Update 55410).	Train loss: 0.1905, Val roc_auc: 0.9609, Best Epoch: 9
Epoch 31 (Update 57257).	Train loss: 0.1905, Val roc_auc: 0.9607, Best Epoch: 9
Epoch 32 (Update 59104).	Train loss: 0.1903, Val roc_auc: 0.9606, Best Epoch: 9
Epoch 33 (Update 60951).	Train loss: 0.1901, Val roc_auc: 0.9606, Best Epoch: 9
Best model found on Epoch 9 (Update 16623). Val roc_auc: 0.9617030444422283
	Fit constraints were validated upstream on the full training data, skipping...
Tabular Neural Network treats features as the following types:

In [56]:
leaderboard = predictor.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3,0.963153,roc_auc,39.040957,6911.982308,0.049794,14.904287,3,True,14
1,CatBoost_BAG_L2,0.963068,roc_auc,26.842516,6107.423786,0.229042,101.455078,2,True,9
2,XGBoost_BAG_L2,0.962663,roc_auc,27.374064,6041.580454,0.760590,35.611746,2,True,12
3,LightGBMLarge_BAG_L2,0.962447,roc_auc,27.151249,6024.026470,0.537774,18.057762,2,True,8
4,ExtraTreesEntr_BAG_L2,0.962291,roc_auc,37.041260,6028.494108,10.427785,22.525400,2,True,11
5,NeuralNetTorch_BAG_L2,0.962266,roc_auc,28.066413,6759.773321,1.452938,753.804613,2,True,13
6,LightGBM_BAG_L2,0.962231,roc_auc,26.881398,6019.292931,0.267923,13.324223,2,True,7
7,ExtraTreesGini_BAG_L2,0.961966,roc_auc,36.283506,6023.864432,9.670032,17.895724,2,True,10
8,WeightedEnsemble_L2,0.961841,roc_auc,8.246526,5703.422764,0.050192,6.240369,2,True,6
9,CatBoost_BAG_L1,0.958953,roc_auc,3.044774,812.774353,3.044774,812.774353,1,True,3
10,XGBoost_BAG_L1,0.958686,roc_auc,4.016417,617.686424,4.016417,617.686424,1,True,4
11,NeuralNetTorch_BAG_L1,0.957119,roc_auc,1.135143,4266.721619,1.135143,4266.721619,1,True,5
12,LightGBMLarge_BAG_L1,0.953884,roc_auc,13.120243,202.518622,13.120243,202.518622,1,True,2
13,LightGBM_BAG_L1,0.951644,roc_auc,5.296898,106.267691,5.296898,106.267691,1,True,1

In [ ]:
# predictor = TabularPredictor.load(f"ag_models13")
# leaderboard = predictor.leaderboard()
# leaderboard

In [22]:
df_test.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [57]:
df=predictor.predict_proba(df_test_fe)
df.head()

Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\CatBoost_BAG_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\ExtraTreesEntr_BAG_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\LightGBM_BAG_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\NeuralNetTorch_BAG_L2\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models14\models\WeightedEnsemble_L3\model.pkl

          0         1
0  0.996255  0.003745
1  0.994461  0.005539
2  0.995770  0.004230
3  0.823691  0.176309
4  0.095334  0.904666

In [61]:
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [62]:
df_sample_out['PitNextLap']

0         0
1         0
2         0
3         0
4         0
         ..
188160    0
188161    0
188162    0
188163    0
188164    0
Name: PitNextLap, Length: 188165, dtype: int64

In [63]:
df_sample_out.count()

id            188165
PitNextLap    188165
dtype: int64

In [65]:
df_sample_out['PitNextLap']=df[1]

In [66]:
# df_sample_out.loc[df_sample_out['PitNextLap'].isna(), 'PitNextLap'] = 0.0

In [67]:
df_sample_out.head()

       id  PitNextLap
0  439140    0.003745
1  439141    0.005539
2  439142    0.004230
3  439143    0.176309
4  439144    0.904666

In [68]:
df_sample_out.to_csv("My_output/all_model_together_best_with_2_extra_models_normalizetl_fe_7.csv", index=False)

In [ ]:
#Try without driver

In [95]:
df_train_merged_wo_driver = df_train_merged.drop("Driver", axis=1)
df_train_wo_driver = df_train.drop("Driver", axis=1)
df_test_wo_driver = df_test.drop("Driver", axis=1)

In [96]:
predictor_wo_driver = TabularPredictor(label=TARGET,eval_metric='roc_auc', path='ag_models13').fit(
    train_data=df_train_merged_wo_driver,
    ag_args_fit={"num_gpus": 1},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=0,
    hyperparameters=models,
)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.8.0+cu129
CUDA Version:       12.9
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.98 GB / 15.06 GB (33.1%)
Disk Space Avail:   647.13 GB / 930.47 GB (69.5%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models13\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models13\predictor.pkl
Beginning AutoGluon training ... Time limit = 32400s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models13"
Train Data Rows:    540445
Train Data Columns: 22
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5125.65 MB
	Train Data (Original)  Memory Usage: 146.19 MB (2.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			20 features in original data used to generate 20 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int8', 'int')          :  1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 14 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int', ['bool']) :  1 | ['PitStop']
	0.8s = Fit runtime
	22 features in original data used to generate 22 features in processed data.
	Train Data (Processed) Memory Usage: 79.89 MB (1.6% of available memory)
Data preprocessing and feature engineering runtime = 0.94s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models13\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
	'XGB': [{}],
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models13\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models13\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 32399.06s of the 32399.06s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models13\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models13\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283358
[100]	valid_set's binary_logloss: 0.259077
[150]	valid_set's binary_logloss: 0.248858
[200]	valid_set's binary_logloss: 0.243297
[250]	valid_set's binary_logloss: 0.239875
[300]	valid_set's binary_logloss: 0.236859
[350]	valid_set's binary_logloss: 0.234092
[400]	valid_set's binary_logloss: 0.231986
[450]	valid_set's binary_logloss: 0.230119
[500]	valid_set's binary_logloss: 0.228529
[550]	valid_set's binary_logloss: 0.227317
[600]	valid_set's binary_logloss: 0.226227
[650]	valid_set's binary_logloss: 0.225313
[700]	valid_set's binary_logloss: 0.224299
[750]	valid_set's binary_logloss: 0.223344
[800]	valid_set's binary_logloss: 0.222493
[850]	valid_set's binary_logloss: 0.221834
[900]	valid_set's binary_logloss: 0.221128
[950]	valid_set's binary_logloss: 0.220607
[1000]	valid_set's binary_logloss: 0.22007
[1050]	valid_set's binary_logloss: 0.219543
[1100]	valid_set's binary_logloss: 0.219023
[1150]	valid_set's binary_logloss: 0.218692
[1200]	valid_set's binary_logloss: 0.218365
[1250]	valid_set's binary_logloss: 0.217862
[1300]	valid_set's binary_logloss: 0.217472
[1350]	valid_set's binary_logloss: 0.21709
[1400]	valid_set's binary_logloss: 0.216836
[1450]	valid_set's binary_logloss: 0.216512
[1500]	valid_set's binary_logloss: 0.216191
[1550]	valid_set's binary_logloss: 0.215928
[1600]	valid_set's binary_logloss: 0.215581
[1650]	valid_set's binary_logloss: 0.215286
[1700]	valid_set's binary_logloss: 0.215034
[1750]	valid_set's binary_logloss: 0.214701
[1800]	valid_set's binary_logloss: 0.214439
[1850]	valid_set's binary_logloss: 0.214214
[1900]	valid_set's binary_logloss: 0.214024
[1950]	valid_set's binary_logloss: 0.213784
[2000]	valid_set's binary_logloss: 0.213598
[2050]	valid_set's binary_logloss: 0.213274
[2100]	valid_set's binary_logloss: 0.21304
[2150]	valid_set's binary_logloss: 0.212908
[2200]	valid_set's binary_logloss: 0.212744
[2250]	valid_set's binary_logloss: 0.212613
[2300]	valid_set's binary_logloss: 0.212497
[2350]	valid_set's binary_logloss: 0.212349
[2400]	valid_set's binary_logloss: 0.212212
[2450]	valid_set's binary_logloss: 0.212058
[2500]	valid_set's binary_logloss: 0.211939
[2550]	valid_set's binary_logloss: 0.211813
[2600]	valid_set's binary_logloss: 0.211686
[2650]	valid_set's binary_logloss: 0.211555
[2700]	valid_set's binary_logloss: 0.211428
[2750]	valid_set's binary_logloss: 0.211344
[2800]	valid_set's binary_logloss: 0.21124
[2850]	valid_set's binary_logloss: 0.211064
[2900]	valid_set's binary_logloss: 0.210989
[2950]	valid_set's binary_logloss: 0.210841
[3000]	valid_set's binary_logloss: 0.210724
[3050]	valid_set's binary_logloss: 0.210625
[3100]	valid_set's binary_logloss: 0.210459
[3150]	valid_set's binary_logloss: 0.210372
[3200]	valid_set's binary_logloss: 0.210223
[3250]	valid_set's binary_logloss: 0.210122
[3300]	valid_set's binary_logloss: 0.210033
[3350]	valid_set's binary_logloss: 0.209983
[3400]	valid_set's binary_logloss: 0.209945
[3450]	valid_set's binary_logloss: 0.209819
[3500]	valid_set's binary_logloss: 0.209782
[3550]	valid_set's binary_logloss: 0.2097
[3600]	valid_set's binary_logloss: 0.209655
[3650]	valid_set's binary_logloss: 0.209647
[3700]	valid_set's binary_logloss: 0.209543
[3750]	valid_set's binary_logloss: 0.209478
[3800]	valid_set's binary_logloss: 0.209402
[3850]	valid_set's binary_logloss: 0.20937
[3900]	valid_set's binary_logloss: 0.209351
[3950]	valid_set's binary_logloss: 0.209279
[4000]	valid_set's binary_logloss: 0.209147
[4050]	valid_set's binary_logloss: 0.209049
[4100]	valid_set's binary_logloss: 0.209009
[4150]	valid_set's binary_logloss: 0.208963
[4200]	valid_set's binary_logloss: 0.208892
[4250]	valid_set's binary_logloss: 0.20883
[4300]	valid_set's binary_logloss: 0.208771
[4350]	valid_set's binary_logloss: 0.208782
[4400]	valid_set's binary_logloss: 0.208717
[4450]	valid_set's binary_logloss: 0.208688
[4500]	valid_set's binary_logloss: 0.208638
[4550]	valid_set's binary_logloss: 0.208627
[4600]	valid_set's binary_logloss: 0.208577
[4650]	valid_set's binary_logloss: 0.208528
[4700]	valid_set's binary_logloss: 0.20844
[4750]	valid_set's binary_logloss: 0.208435
[4800]	valid_set's binary_logloss: 0.208374
[4850]	valid_set's binary_logloss: 0.208362
[4900]	valid_set's binary_logloss: 0.208293
[4950]	valid_set's binary_logloss: 0.208263
[5000]	valid_set's binary_logloss: 0.208226
[5050]	valid_set's binary_logloss: 0.208191
[5100]	valid_set's binary_logloss: 0.208153
[5150]	valid_set's binary_logloss: 0.208105
[5200]	valid_set's binary_logloss: 0.208051
[5250]	valid_set's binary_logloss: 0.208028
[5300]	valid_set's binary_logloss: 0.208006
[5350]	valid_set's binary_logloss: 0.207974
[5400]	valid_set's binary_logloss: 0.207942
[5450]	valid_set's binary_logloss: 0.207923
[5500]	valid_set's binary_logloss: 0.207895
[5550]	valid_set's binary_logloss: 0.207885
[5600]	valid_set's binary_logloss: 0.207866
[5650]	valid_set's binary_logloss: 0.207846
[5700]	valid_set's binary_logloss: 0.207845
[5750]	valid_set's binary_logloss: 0.207874
[5800]	valid_set's binary_logloss: 0.207882
[5850]	valid_set's binary_logloss: 0.207837
[5900]	valid_set's binary_logloss: 0.207809
[5950]	valid_set's binary_logloss: 0.207835
[6000]	valid_set's binary_logloss: 0.20785
[6050]	valid_set's binary_logloss: 0.207807
[6100]	valid_set's binary_logloss: 0.20779
[6150]	valid_set's binary_logloss: 0.207794
[6200]	valid_set's binary_logloss: 0.20779
[6250]	valid_set's binary_logloss: 0.20776
[6300]	valid_set's binary_logloss: 0.207737
[6350]	valid_set's binary_logloss: 0.207736
[6400]	valid_set's binary_logloss: 0.207741
[6450]	valid_set's binary_logloss: 0.207748
[6500]	valid_set's binary_logloss: 0.207745
[6550]	valid_set's binary_logloss: 0.207779
[6600]	valid_set's binary_logloss: 0.207769
[6650]	valid_set's binary_logloss: 0.207764
[6700]	valid_set's binary_logloss: 0.207801
[6750]	valid_set's binary_logloss: 0.207811
[6800]	valid_set's binary_logloss: 0.207834
[6850]	valid_set's binary_logloss: 0.207871
[6900]	valid_set's binary_logloss: 0.207888
[6950]	valid_set's binary_logloss: 0.207862
[7000]	valid_set's binary_logloss: 0.207841
[7050]	valid_set's binary_logloss: 0.207928
[7100]	valid_set's binary_logloss: 0.20796
[7150]	valid_set's binary_logloss: 0.207969
[7200]	valid_set's binary_logloss: 0.207951
[7250]	valid_set's binary_logloss: 0.207948
[7300]	valid_set's binary_logloss: 0.207955
[7350]	valid_set's binary_logloss: 0.207983
[7400]	valid_set's binary_logloss: 0.208001
[7450]	valid_set's binary_logloss: 0.207994
[7500]	valid_set's binary_logloss: 0.207974
[7550]	valid_set's binary_logloss: 0.207965
[7600]	valid_set's binary_logloss: 0.207994
[7650]	valid_set's binary_logloss: 0.207999
[7700]	valid_set's binary_logloss: 0.208029
[7750]	valid_set's binary_logloss: 0.208049
[7800]	valid_set's binary_logloss: 0.208071
[7850]	valid_set's binary_logloss: 0.208089
[7900]	valid_set's binary_logloss: 0.208097
[7950]	valid_set's binary_logloss: 0.208123
[8000]	valid_set's binary_logloss: 0.208139
[8050]	valid_set's binary_logloss: 0.208159
[8100]	valid_set's binary_logloss: 0.208196
[8150]	valid_set's binary_logloss: 0.208234
[8200]	valid_set's binary_logloss: 0.208231
[8250]	valid_set's binary_logloss: 0.208258

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284252
[100]	valid_set's binary_logloss: 0.260215
[150]	valid_set's binary_logloss: 0.25003
[200]	valid_set's binary_logloss: 0.244546
[250]	valid_set's binary_logloss: 0.240755
[300]	valid_set's binary_logloss: 0.237883
[350]	valid_set's binary_logloss: 0.235311
[400]	valid_set's binary_logloss: 0.233384
[450]	valid_set's binary_logloss: 0.23183
[500]	valid_set's binary_logloss: 0.230181
[550]	valid_set's binary_logloss: 0.228827
[600]	valid_set's binary_logloss: 0.227761
[650]	valid_set's binary_logloss: 0.226591
[700]	valid_set's binary_logloss: 0.225568
[750]	valid_set's binary_logloss: 0.224623
[800]	valid_set's binary_logloss: 0.223895
[850]	valid_set's binary_logloss: 0.223081
[900]	valid_set's binary_logloss: 0.222201
[950]	valid_set's binary_logloss: 0.221693
[1000]	valid_set's binary_logloss: 0.221129
[1050]	valid_set's binary_logloss: 0.220547
[1100]	valid_set's binary_logloss: 0.220044
[1150]	valid_set's binary_logloss: 0.21958
[1200]	valid_set's binary_logloss: 0.219126
[1250]	valid_set's binary_logloss: 0.218538
[1300]	valid_set's binary_logloss: 0.218104
[1350]	valid_set's binary_logloss: 0.217681
[1400]	valid_set's binary_logloss: 0.217377
[1450]	valid_set's binary_logloss: 0.216916
[1500]	valid_set's binary_logloss: 0.216486
[1550]	valid_set's binary_logloss: 0.21617
[1600]	valid_set's binary_logloss: 0.215843
[1650]	valid_set's binary_logloss: 0.215498
[1700]	valid_set's binary_logloss: 0.215121
[1750]	valid_set's binary_logloss: 0.214802
[1800]	valid_set's binary_logloss: 0.214552
[1850]	valid_set's binary_logloss: 0.21429
[1900]	valid_set's binary_logloss: 0.214101
[1950]	valid_set's binary_logloss: 0.213828
[2000]	valid_set's binary_logloss: 0.213583
[2050]	valid_set's binary_logloss: 0.213382
[2100]	valid_set's binary_logloss: 0.213264
[2150]	valid_set's binary_logloss: 0.213076
[2200]	valid_set's binary_logloss: 0.21282
[2250]	valid_set's binary_logloss: 0.212705
[2300]	valid_set's binary_logloss: 0.212553
[2350]	valid_set's binary_logloss: 0.212419
[2400]	valid_set's binary_logloss: 0.212283
[2450]	valid_set's binary_logloss: 0.212108
[2500]	valid_set's binary_logloss: 0.211886
[2550]	valid_set's binary_logloss: 0.211765
[2600]	valid_set's binary_logloss: 0.211605
[2650]	valid_set's binary_logloss: 0.211424
[2700]	valid_set's binary_logloss: 0.211224
[2750]	valid_set's binary_logloss: 0.211114
[2800]	valid_set's binary_logloss: 0.210902
[2850]	valid_set's binary_logloss: 0.21074
[2900]	valid_set's binary_logloss: 0.210549
[2950]	valid_set's binary_logloss: 0.21041
[3000]	valid_set's binary_logloss: 0.210279
[3050]	valid_set's binary_logloss: 0.21013
[3100]	valid_set's binary_logloss: 0.210034
[3150]	valid_set's binary_logloss: 0.209968
[3200]	valid_set's binary_logloss: 0.209921
[3250]	valid_set's binary_logloss: 0.209869
[3300]	valid_set's binary_logloss: 0.209729
[3350]	valid_set's binary_logloss: 0.209687
[3400]	valid_set's binary_logloss: 0.209617
[3450]	valid_set's binary_logloss: 0.209558
[3500]	valid_set's binary_logloss: 0.209493
[3550]	valid_set's binary_logloss: 0.20947
[3600]	valid_set's binary_logloss: 0.209395
[3650]	valid_set's binary_logloss: 0.20935
[3700]	valid_set's binary_logloss: 0.209256
[3750]	valid_set's binary_logloss: 0.209198
[3800]	valid_set's binary_logloss: 0.209118
[3850]	valid_set's binary_logloss: 0.209016
[3900]	valid_set's binary_logloss: 0.208954
[3950]	valid_set's binary_logloss: 0.208853
[4000]	valid_set's binary_logloss: 0.208804
[4050]	valid_set's binary_logloss: 0.208751
[4100]	valid_set's binary_logloss: 0.20868
[4150]	valid_set's binary_logloss: 0.208607
[4200]	valid_set's binary_logloss: 0.208601
[4250]	valid_set's binary_logloss: 0.20857
[4300]	valid_set's binary_logloss: 0.208499
[4350]	valid_set's binary_logloss: 0.208443
[4400]	valid_set's binary_logloss: 0.208394
[4450]	valid_set's binary_logloss: 0.208353
[4500]	valid_set's binary_logloss: 0.208287
[4550]	valid_set's binary_logloss: 0.208249
[4600]	valid_set's binary_logloss: 0.208233
[4650]	valid_set's binary_logloss: 0.208205
[4700]	valid_set's binary_logloss: 0.208167
[4750]	valid_set's binary_logloss: 0.208144
[4800]	valid_set's binary_logloss: 0.208109
[4850]	valid_set's binary_logloss: 0.208051
[4900]	valid_set's binary_logloss: 0.208019
[4950]	valid_set's binary_logloss: 0.208005
[5000]	valid_set's binary_logloss: 0.207984
[5050]	valid_set's binary_logloss: 0.207925
[5100]	valid_set's binary_logloss: 0.207914
[5150]	valid_set's binary_logloss: 0.207856
[5200]	valid_set's binary_logloss: 0.207835
[5250]	valid_set's binary_logloss: 0.20781
[5300]	valid_set's binary_logloss: 0.207754
[5350]	valid_set's binary_logloss: 0.207736
[5400]	valid_set's binary_logloss: 0.207687
[5450]	valid_set's binary_logloss: 0.207617
[5500]	valid_set's binary_logloss: 0.207602
[5550]	valid_set's binary_logloss: 0.207563
[5600]	valid_set's binary_logloss: 0.207528
[5650]	valid_set's binary_logloss: 0.207467
[5700]	valid_set's binary_logloss: 0.207496
[5750]	valid_set's binary_logloss: 0.207489
[5800]	valid_set's binary_logloss: 0.207464
[5850]	valid_set's binary_logloss: 0.207418
[5900]	valid_set's binary_logloss: 0.207381
[5950]	valid_set's binary_logloss: 0.207397
[6000]	valid_set's binary_logloss: 0.207426
[6050]	valid_set's binary_logloss: 0.207418
[6100]	valid_set's binary_logloss: 0.207399
[6150]	valid_set's binary_logloss: 0.207355
[6200]	valid_set's binary_logloss: 0.20729
[6250]	valid_set's binary_logloss: 0.207306
[6300]	valid_set's binary_logloss: 0.207331
[6350]	valid_set's binary_logloss: 0.20734
[6400]	valid_set's binary_logloss: 0.207304
[6450]	valid_set's binary_logloss: 0.207277
[6500]	valid_set's binary_logloss: 0.207258
[6550]	valid_set's binary_logloss: 0.207241
[6600]	valid_set's binary_logloss: 0.207248
[6650]	valid_set's binary_logloss: 0.20723
[6700]	valid_set's binary_logloss: 0.207222
[6750]	valid_set's binary_logloss: 0.207234
[6800]	valid_set's binary_logloss: 0.207226
[6850]	valid_set's binary_logloss: 0.207241
[6900]	valid_set's binary_logloss: 0.207266
[6950]	valid_set's binary_logloss: 0.207273
[7000]	valid_set's binary_logloss: 0.207253
[7050]	valid_set's binary_logloss: 0.207244
[7100]	valid_set's binary_logloss: 0.207286
[7150]	valid_set's binary_logloss: 0.207291
[7200]	valid_set's binary_logloss: 0.20728
[7250]	valid_set's binary_logloss: 0.207287
[7300]	valid_set's binary_logloss: 0.207314
[7350]	valid_set's binary_logloss: 0.2073
[7400]	valid_set's binary_logloss: 0.207327
[7450]	valid_set's binary_logloss: 0.20732
[7500]	valid_set's binary_logloss: 0.207317
[7550]	valid_set's binary_logloss: 0.207308
[7600]	valid_set's binary_logloss: 0.207332
[7650]	valid_set's binary_logloss: 0.207337
[7700]	valid_set's binary_logloss: 0.207279
[7750]	valid_set's binary_logloss: 0.207263
[7800]	valid_set's binary_logloss: 0.207257
[7850]	valid_set's binary_logloss: 0.207285
[7900]	valid_set's binary_logloss: 0.207304
[7950]	valid_set's binary_logloss: 0.207351
[8000]	valid_set's binary_logloss: 0.207378
[8050]	valid_set's binary_logloss: 0.207398
[8100]	valid_set's binary_logloss: 0.207402
[8150]	valid_set's binary_logloss: 0.207392
[8200]	valid_set's binary_logloss: 0.207412
[8250]	valid_set's binary_logloss: 0.207415
[8300]	valid_set's binary_logloss: 0.207395
[8350]	valid_set's binary_logloss: 0.207382
[8400]	valid_set's binary_logloss: 0.207369
[8450]	valid_set's binary_logloss: 0.207382
[8500]	valid_set's binary_logloss: 0.207356
[8550]	valid_set's binary_logloss: 0.207384
[8600]	valid_set's binary_logloss: 0.207397
[8650]	valid_set's binary_logloss: 0.207409
[8700]	valid_set's binary_logloss: 0.207403
[8750]	valid_set's binary_logloss: 0.207417
[8800]	valid_set's binary_logloss: 0.207469

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.286501
[100]	valid_set's binary_logloss: 0.261955
[150]	valid_set's binary_logloss: 0.252519
[200]	valid_set's binary_logloss: 0.247066
[250]	valid_set's binary_logloss: 0.243133
[300]	valid_set's binary_logloss: 0.240279
[350]	valid_set's binary_logloss: 0.238456
[400]	valid_set's binary_logloss: 0.236295
[450]	valid_set's binary_logloss: 0.234466
[500]	valid_set's binary_logloss: 0.232939
[550]	valid_set's binary_logloss: 0.231343
[600]	valid_set's binary_logloss: 0.230143
[650]	valid_set's binary_logloss: 0.229197
[700]	valid_set's binary_logloss: 0.228222
[750]	valid_set's binary_logloss: 0.227372
[800]	valid_set's binary_logloss: 0.226579
[850]	valid_set's binary_logloss: 0.225595
[900]	valid_set's binary_logloss: 0.224974
[950]	valid_set's binary_logloss: 0.224463
[1000]	valid_set's binary_logloss: 0.22383
[1050]	valid_set's binary_logloss: 0.223402
[1100]	valid_set's binary_logloss: 0.222926
[1150]	valid_set's binary_logloss: 0.222412
[1200]	valid_set's binary_logloss: 0.221926
[1250]	valid_set's binary_logloss: 0.221333
[1300]	valid_set's binary_logloss: 0.220955
[1350]	valid_set's binary_logloss: 0.220698
[1400]	valid_set's binary_logloss: 0.220421
[1450]	valid_set's binary_logloss: 0.220011
[1500]	valid_set's binary_logloss: 0.219723
[1550]	valid_set's binary_logloss: 0.219491
[1600]	valid_set's binary_logloss: 0.219312
[1650]	valid_set's binary_logloss: 0.219107
[1700]	valid_set's binary_logloss: 0.218814

KeyboardInterrupt:

In [169]:
leaderboard = predictor_wo_driver.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.959125,roc_auc,37.932610,1384.518738,0.050312,5.060219,2,True,5
1,LightGBM_BAG_L1,0.958277,roc_auc,11.543802,210.660673,11.543802,210.660673,1,True,1
2,XGBoost_BAG_L1,0.957086,roc_auc,2.971786,273.060256,2.971786,273.060256,1,True,4
3,LightGBMLarge_BAG_L1,0.956886,roc_auc,22.951177,296.346481,22.951177,296.346481,1,True,2
4,CatBoost_BAG_L1,0.954769,roc_auc,0.415533,599.391110,0.415533,599.391110,1,True,3

In [170]:
df=predictor_wo_driver.predict_proba(df_test)
df.head()
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()
df_sample_out['PitNextLap']=df[1]
df_sample_out.to_csv("My_output/all_model_together_best_fe_without_driver_1.csv", index=False)

Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\model.pkl