In [10]:
import pandas as pd
df_train=pd.read_csv('data/train.csv')
df_test=pd.read_csv('data/test.csv')
df_train_merged = pd.read_csv('data/train_merged.csv')

In [11]:
print(df_train.columns)

Index(['id', 'Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber',
       'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [14]:
df_train_merged["Race"].unique()

array(['Mexico City Grand Prix', 'Italian Grand Prix',
       'Monaco Grand Prix', 'Azerbaijan Grand Prix',
       'São Paulo Grand Prix', 'Emilia Romagna Grand Prix',
       'Canadian Grand Prix', 'Chinese Grand Prix',
       'Singapore Grand Prix', 'Hungarian Grand Prix',
       'French Grand Prix', 'Abu Dhabi Grand Prix', 'Austrian Grand Prix',
       'Japanese Grand Prix', 'Belgian Grand Prix', 'British Grand Prix',
       'Dutch Grand Prix', 'United States Grand Prix', 'Miami Grand Prix',
       'Spanish Grand Prix', 'Saudi Arabian Grand Prix',
       'Las Vegas Grand Prix', 'Qatar Grand Prix',
       'Australian Grand Prix', 'Bahrain Grand Prix',
       'Pre-Season Testing', 'Pre-Season Track Session',
       'Pre-Season Test'], dtype=object)

In [15]:
df_train_merged.columns

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap'],
      dtype='object')

In [16]:
df_train_merged[["Compound"]].value_counts()

Compound
MEDIUM          248780
HARD            215485
SOFT             51488
INTERMEDIATE     22938
WET               1754
Name: count, dtype: int64

In [17]:
#Tire dataset
def add_tire_life_columns(df):
    max_tire_life = {
        "MEDIUM": 40,
        "HARD": 55,
        "SOFT": 30,
        "INTERMEDIATE": 25,
        "WET": 20
    }

    df["MaxTireLife"] = df["Compound"].map(max_tire_life)

    df["TireRemainingLife"] = (
        df["MaxTireLife"] - df["TyreLife"]
    ).clip(lower=0)
    df["TireAgePct"] = (
    df["TyreLife"] / df["MaxTireLife"]).clip(0, 1)
    df["TireRemainingPct"] = (df["TireRemainingLife"] / df["MaxTireLife"]).clip(0, 1)
    

    return df

In [18]:
df_train_merged.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,SWI,MEDIUM,Mexico City Grand Prix,2023,0,6,1,6.0,12,83.921,-21.244,-10.320,0.084507,0.0,0.0
1,TRU,HARD,Italian Grand Prix,2024,0,24,2,17.0,15,83.845,-22.913,-33.696,0.311688,-9.0,1.0
2,TSU,MEDIUM,Monaco Grand Prix,2023,0,23,1,23.0,9,79.239,0.087,-12.078,0.302632,0.0,0.0
3,PEA,HARD,Italian Grand Prix,2022,1,50,2,33.0,11,87.076,-13.929,-31.804,0.694444,3.0,1.0
4,ANT,HARD,Monaco Grand Prix,2025,0,49,1,49.0,12,78.328,-0.516,-33.315,0.653333,0.0,0.0

In [19]:
def add_laps_for_each_race(df):
    df["RaceLaps"] = (
    df["LapNumber"] / (df["RaceProgress"])
).round()
    df["LapsRemaining"] = df["RaceLaps"] - df["LapNumber"]
    return df

In [20]:
def prev_position_calcute(df):
    df["Prev_Position"] = df["Position"] + df["Position_Change"]
    return df

In [21]:
def get_trend_data(df):
    df["LapTimeAvg_3"] = (
        df.groupby(["Year", "Race", "Driver"])["LapTime (s)"]
        .transform(lambda x: x.rolling(3, min_periods=1).mean())
    )
    return df

In [22]:
def set_fe(df):
    df = add_tire_life_columns(df)
    df = add_laps_for_each_race(df)
    df= prev_position_calcute(df)
    df = get_trend_data(df)
    return df

In [23]:
df_train_merged = set_fe(df_train_merged)
df_train=set_fe(df_train)
df_test=set_fe(df_test)

In [24]:
df_train =df_train.drop("id",axis=1)
df_test =df_test.drop("id",axis=1)

In [152]:
df_train_merged.isnull().sum()

Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
PitNextLap                0
MaxTireLife               0
TireRemainingLife         0
TireAgePct                0
TireRemainingPct          0
RaceLaps                  0
LapsRemaining             0
Prev_Position             0
LapTimeAvg_3              0
dtype: int64

In [153]:
df_train.isnull().sum()

Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
PitNextLap                0
MaxTireLife               0
TireRemainingLife         0
TireAgePct                0
TireRemainingPct          0
RaceLaps                  0
LapsRemaining             0
Prev_Position             0
LapTimeAvg_3              0
dtype: int64

In [154]:
df_test.isnull().sum()

Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
MaxTireLife               0
TireRemainingLife         0
TireAgePct                0
TireRemainingPct          0
RaceLaps                  0
LapsRemaining             0
Prev_Position             0
LapTimeAvg_3              0
dtype: int64

In [7]:
from autogluon.tabular import TabularDataset, TabularPredictor
TARGET = 'PitNextLap'

print(df_train[TARGET].value_counts())
print(df_train_merged[TARGET].value_counts())

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64
PitNextLap
0.0    427273
1.0    113172
Name: count, dtype: int64

In [156]:
print(df_train.columns)
print(df_train.columns)

Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap', 'MaxTireLife', 'TireRemainingLife', 'TireAgePct',
       'TireRemainingPct', 'RaceLaps', 'LapsRemaining', 'Prev_Position',
       'LapTimeAvg_3'],
      dtype='object')
Index(['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint',
       'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta',
       'Cumulative_Degradation', 'RaceProgress', 'Position_Change',
       'PitNextLap', 'MaxTireLife', 'TireRemainingLife', 'TireAgePct',
       'TireRemainingPct', 'RaceLaps', 'LapsRemaining', 'Prev_Position',
       'LapTimeAvg_3'],
      dtype='object')

In [157]:
import warnings
warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*downcast.*"
)
_orig_fillna = pd.DataFrame.fillna
def _patched_fillna(self, *args, **kwargs):
    kwargs.pop("downcast", None)
    return _orig_fillna(self, *args, **kwargs)

In [158]:
models = {
    "GBM": [
        {},  # Generates LightGBM_BAG_L1
        {"extra_trees": True, "ag_args": {"name_suffix": "Large"}},  # Generates LightGBMLarge_BAG_L1
    ],
    "XGB": {},  # Generates XGBoost_BAG_L1
    "CAT": {},  # Generates CatBoost_BAG_L1
}

In [160]:
predictor = TabularPredictor(label=TARGET,eval_metric='roc_auc', path='ag_models4').fit(
    train_data=df_train_merged,
    ag_args_fit={"num_gpus": 1},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=0,
    hyperparameters=models,
)

Warning: path already exists! This predictor may overwrite an existing predictor! path="ag_models4"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.8.0+cu129
CUDA Version:       12.9
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.55 GB / 15.06 GB (30.2%)
Disk Space Avail:   666.86 GB / 930.47 GB (71.7%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models4\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\predictor.pkl
Beginning AutoGluon training ... Time limit = 32400s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models4"
Train Data Rows:    540445
Train Data Columns: 22
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4708.80 MB
	Train Data (Original)  Memory Usage: 169.12 MB (3.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  3 | ['Driver', 'Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			19 features in original data used to generate 19 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 3 | ['Driver', 'Compound', 'Race']
				0.0s = Fit runtime
				3 features in original data used to generate 3 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 3 | ['Driver', 'Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 3 | ['Driver', 'Compound', 'Race']
			0.1s = Fit runtime
			3 features in original data used to generate 3 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  3 | ['Driver', 'Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			22 features in original data used to generate 22 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  3 | ['Driver', 'Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  3 | ['Driver', 'Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  3 | ['Driver', 'Compound', 'Race']
		('float64', 'float')     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int8', 'int')          :  1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['Driver', 'Compound', 'Race']
		('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int', ['bool']) :  1 | ['PitStop']
	1.0s = Fit runtime
	22 features in original data used to generate 22 features in processed data.
	Train Data (Processed) Memory Usage: 76.80 MB (1.6% of available memory)
Data preprocessing and feature engineering runtime = 1.09s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models4\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
	'XGB': [{}],
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models4\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 32398.91s of the 32398.90s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283323
[100]	valid_set's binary_logloss: 0.260562
[150]	valid_set's binary_logloss: 0.251288
[200]	valid_set's binary_logloss: 0.246148
[250]	valid_set's binary_logloss: 0.242052
[300]	valid_set's binary_logloss: 0.239459
[350]	valid_set's binary_logloss: 0.237322
[400]	valid_set's binary_logloss: 0.235122
[450]	valid_set's binary_logloss: 0.233585
[500]	valid_set's binary_logloss: 0.23242
[550]	valid_set's binary_logloss: 0.231263
[600]	valid_set's binary_logloss: 0.230295
[650]	valid_set's binary_logloss: 0.229496
[700]	valid_set's binary_logloss: 0.228779
[750]	valid_set's binary_logloss: 0.228188
[800]	valid_set's binary_logloss: 0.227512
[850]	valid_set's binary_logloss: 0.226951
[900]	valid_set's binary_logloss: 0.226497
[950]	valid_set's binary_logloss: 0.226007
[1000]	valid_set's binary_logloss: 0.225526
[1050]	valid_set's binary_logloss: 0.225237
[1100]	valid_set's binary_logloss: 0.224949
[1150]	valid_set's binary_logloss: 0.224708
[1200]	valid_set's binary_logloss: 0.224442
[1250]	valid_set's binary_logloss: 0.224198
[1300]	valid_set's binary_logloss: 0.223938
[1350]	valid_set's binary_logloss: 0.223701
[1400]	valid_set's binary_logloss: 0.223421
[1450]	valid_set's binary_logloss: 0.223351
[1500]	valid_set's binary_logloss: 0.223187
[1550]	valid_set's binary_logloss: 0.223148
[1600]	valid_set's binary_logloss: 0.223044
[1650]	valid_set's binary_logloss: 0.222981
[1700]	valid_set's binary_logloss: 0.222901
[1750]	valid_set's binary_logloss: 0.222815
[1800]	valid_set's binary_logloss: 0.222785
[1850]	valid_set's binary_logloss: 0.222661
[1900]	valid_set's binary_logloss: 0.222664
[1950]	valid_set's binary_logloss: 0.222646
[2000]	valid_set's binary_logloss: 0.222542
[2050]	valid_set's binary_logloss: 0.222531
[2100]	valid_set's binary_logloss: 0.222547
[2150]	valid_set's binary_logloss: 0.222461
[2200]	valid_set's binary_logloss: 0.222434
[2250]	valid_set's binary_logloss: 0.222399
[2300]	valid_set's binary_logloss: 0.222409
[2350]	valid_set's binary_logloss: 0.222407
[2400]	valid_set's binary_logloss: 0.222444
[2450]	valid_set's binary_logloss: 0.222463
[2500]	valid_set's binary_logloss: 0.222488
[2550]	valid_set's binary_logloss: 0.222498
[2600]	valid_set's binary_logloss: 0.222528
[2650]	valid_set's binary_logloss: 0.222603
[2700]	valid_set's binary_logloss: 0.222605
[2750]	valid_set's binary_logloss: 0.222642
[2800]	valid_set's binary_logloss: 0.222658
[2850]	valid_set's binary_logloss: 0.222695
[2900]	valid_set's binary_logloss: 0.222758
[2950]	valid_set's binary_logloss: 0.222782

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284803
[100]	valid_set's binary_logloss: 0.262136
[150]	valid_set's binary_logloss: 0.253508
[200]	valid_set's binary_logloss: 0.248086
[250]	valid_set's binary_logloss: 0.244479
[300]	valid_set's binary_logloss: 0.242022
[350]	valid_set's binary_logloss: 0.239586
[400]	valid_set's binary_logloss: 0.237857
[450]	valid_set's binary_logloss: 0.236703
[500]	valid_set's binary_logloss: 0.235129
[550]	valid_set's binary_logloss: 0.234002
[600]	valid_set's binary_logloss: 0.233101
[650]	valid_set's binary_logloss: 0.232317
[700]	valid_set's binary_logloss: 0.231694
[750]	valid_set's binary_logloss: 0.230995
[800]	valid_set's binary_logloss: 0.230439
[850]	valid_set's binary_logloss: 0.230029
[900]	valid_set's binary_logloss: 0.229363
[950]	valid_set's binary_logloss: 0.228919
[1000]	valid_set's binary_logloss: 0.228542
[1050]	valid_set's binary_logloss: 0.228239
[1100]	valid_set's binary_logloss: 0.227949
[1150]	valid_set's binary_logloss: 0.227751
[1200]	valid_set's binary_logloss: 0.227594
[1250]	valid_set's binary_logloss: 0.227405
[1300]	valid_set's binary_logloss: 0.227194
[1350]	valid_set's binary_logloss: 0.226962
[1400]	valid_set's binary_logloss: 0.226756
[1450]	valid_set's binary_logloss: 0.226594
[1500]	valid_set's binary_logloss: 0.226473
[1550]	valid_set's binary_logloss: 0.226374
[1600]	valid_set's binary_logloss: 0.22627
[1650]	valid_set's binary_logloss: 0.226204
[1700]	valid_set's binary_logloss: 0.226143
[1750]	valid_set's binary_logloss: 0.226087
[1800]	valid_set's binary_logloss: 0.226035
[1850]	valid_set's binary_logloss: 0.22594
[1900]	valid_set's binary_logloss: 0.225805
[1950]	valid_set's binary_logloss: 0.225734
[2000]	valid_set's binary_logloss: 0.225721
[2050]	valid_set's binary_logloss: 0.225762
[2100]	valid_set's binary_logloss: 0.225751
[2150]	valid_set's binary_logloss: 0.225761
[2200]	valid_set's binary_logloss: 0.22572
[2250]	valid_set's binary_logloss: 0.225736
[2300]	valid_set's binary_logloss: 0.225792
[2350]	valid_set's binary_logloss: 0.225769
[2400]	valid_set's binary_logloss: 0.225797
[2450]	valid_set's binary_logloss: 0.225827
[2500]	valid_set's binary_logloss: 0.225781
[2550]	valid_set's binary_logloss: 0.225879
[2600]	valid_set's binary_logloss: 0.226001

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.286646
[100]	valid_set's binary_logloss: 0.264206
[150]	valid_set's binary_logloss: 0.255053
[200]	valid_set's binary_logloss: 0.249854
[250]	valid_set's binary_logloss: 0.245816
[300]	valid_set's binary_logloss: 0.2432
[350]	valid_set's binary_logloss: 0.240892
[400]	valid_set's binary_logloss: 0.239176
[450]	valid_set's binary_logloss: 0.237618
[500]	valid_set's binary_logloss: 0.236514
[550]	valid_set's binary_logloss: 0.23553
[600]	valid_set's binary_logloss: 0.234755
[650]	valid_set's binary_logloss: 0.233867
[700]	valid_set's binary_logloss: 0.233335
[750]	valid_set's binary_logloss: 0.232737
[800]	valid_set's binary_logloss: 0.232188
[850]	valid_set's binary_logloss: 0.231721
[900]	valid_set's binary_logloss: 0.231273
[950]	valid_set's binary_logloss: 0.23096
[1000]	valid_set's binary_logloss: 0.230733
[1050]	valid_set's binary_logloss: 0.230481
[1100]	valid_set's binary_logloss: 0.230113
[1150]	valid_set's binary_logloss: 0.229886
[1200]	valid_set's binary_logloss: 0.229591
[1250]	valid_set's binary_logloss: 0.229463
[1300]	valid_set's binary_logloss: 0.229372
[1350]	valid_set's binary_logloss: 0.229196
[1400]	valid_set's binary_logloss: 0.22909
[1450]	valid_set's binary_logloss: 0.229023
[1500]	valid_set's binary_logloss: 0.228902
[1550]	valid_set's binary_logloss: 0.228845
[1600]	valid_set's binary_logloss: 0.228748
[1650]	valid_set's binary_logloss: 0.228667
[1700]	valid_set's binary_logloss: 0.228641
[1750]	valid_set's binary_logloss: 0.228556
[1800]	valid_set's binary_logloss: 0.228577
[1850]	valid_set's binary_logloss: 0.228559
[1900]	valid_set's binary_logloss: 0.228536
[1950]	valid_set's binary_logloss: 0.228529
[2000]	valid_set's binary_logloss: 0.22853
[2050]	valid_set's binary_logloss: 0.228469
[2100]	valid_set's binary_logloss: 0.228551
[2150]	valid_set's binary_logloss: 0.228541
[2200]	valid_set's binary_logloss: 0.228577
[2250]	valid_set's binary_logloss: 0.228671
[2300]	valid_set's binary_logloss: 0.228777
[2350]	valid_set's binary_logloss: 0.228865
[2400]	valid_set's binary_logloss: 0.228895
[2450]	valid_set's binary_logloss: 0.228942
[2500]	valid_set's binary_logloss: 0.228977
[2550]	valid_set's binary_logloss: 0.228994
[2600]	valid_set's binary_logloss: 0.228913
[2650]	valid_set's binary_logloss: 0.228987

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283466
[100]	valid_set's binary_logloss: 0.260652
[150]	valid_set's binary_logloss: 0.252315
[200]	valid_set's binary_logloss: 0.246913
[250]	valid_set's binary_logloss: 0.242933
[300]	valid_set's binary_logloss: 0.240072
[350]	valid_set's binary_logloss: 0.237855
[400]	valid_set's binary_logloss: 0.23603
[450]	valid_set's binary_logloss: 0.234526
[500]	valid_set's binary_logloss: 0.233257
[550]	valid_set's binary_logloss: 0.232306
[600]	valid_set's binary_logloss: 0.23143
[650]	valid_set's binary_logloss: 0.230578
[700]	valid_set's binary_logloss: 0.229922
[750]	valid_set's binary_logloss: 0.229317
[800]	valid_set's binary_logloss: 0.228764
[850]	valid_set's binary_logloss: 0.228225
[900]	valid_set's binary_logloss: 0.227978
[950]	valid_set's binary_logloss: 0.227591
[1000]	valid_set's binary_logloss: 0.227387
[1050]	valid_set's binary_logloss: 0.22722
[1100]	valid_set's binary_logloss: 0.226896
[1150]	valid_set's binary_logloss: 0.226725
[1200]	valid_set's binary_logloss: 0.226538
[1250]	valid_set's binary_logloss: 0.226325
[1300]	valid_set's binary_logloss: 0.226057
[1350]	valid_set's binary_logloss: 0.225871
[1400]	valid_set's binary_logloss: 0.225601
[1450]	valid_set's binary_logloss: 0.225326
[1500]	valid_set's binary_logloss: 0.225205
[1550]	valid_set's binary_logloss: 0.225236
[1600]	valid_set's binary_logloss: 0.225127
[1650]	valid_set's binary_logloss: 0.225014
[1700]	valid_set's binary_logloss: 0.224915
[1750]	valid_set's binary_logloss: 0.224892
[1800]	valid_set's binary_logloss: 0.224888
[1850]	valid_set's binary_logloss: 0.224888
[1900]	valid_set's binary_logloss: 0.22488
[1950]	valid_set's binary_logloss: 0.224845
[2000]	valid_set's binary_logloss: 0.224863
[2050]	valid_set's binary_logloss: 0.224859
[2100]	valid_set's binary_logloss: 0.224879
[2150]	valid_set's binary_logloss: 0.224937
[2200]	valid_set's binary_logloss: 0.224973
[2250]	valid_set's binary_logloss: 0.22501
[2300]	valid_set's binary_logloss: 0.225087
[2350]	valid_set's binary_logloss: 0.225153
[2400]	valid_set's binary_logloss: 0.225306
[2450]	valid_set's binary_logloss: 0.225393
[2500]	valid_set's binary_logloss: 0.225493
[2550]	valid_set's binary_logloss: 0.225482
[2600]	valid_set's binary_logloss: 0.225566

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283492
[100]	valid_set's binary_logloss: 0.260722
[150]	valid_set's binary_logloss: 0.251227
[200]	valid_set's binary_logloss: 0.245731
[250]	valid_set's binary_logloss: 0.242348
[300]	valid_set's binary_logloss: 0.239814
[350]	valid_set's binary_logloss: 0.237678
[400]	valid_set's binary_logloss: 0.235876
[450]	valid_set's binary_logloss: 0.2343
[500]	valid_set's binary_logloss: 0.2329
[550]	valid_set's binary_logloss: 0.231857
[600]	valid_set's binary_logloss: 0.230921
[650]	valid_set's binary_logloss: 0.230176
[700]	valid_set's binary_logloss: 0.22954
[750]	valid_set's binary_logloss: 0.228839
[800]	valid_set's binary_logloss: 0.228295
[850]	valid_set's binary_logloss: 0.227796
[900]	valid_set's binary_logloss: 0.227343
[950]	valid_set's binary_logloss: 0.226991
[1000]	valid_set's binary_logloss: 0.226633
[1050]	valid_set's binary_logloss: 0.226315
[1100]	valid_set's binary_logloss: 0.225955
[1150]	valid_set's binary_logloss: 0.22569
[1200]	valid_set's binary_logloss: 0.225474
[1250]	valid_set's binary_logloss: 0.225298
[1300]	valid_set's binary_logloss: 0.225188
[1350]	valid_set's binary_logloss: 0.225014
[1400]	valid_set's binary_logloss: 0.224894
[1450]	valid_set's binary_logloss: 0.224584
[1500]	valid_set's binary_logloss: 0.224404
[1550]	valid_set's binary_logloss: 0.224271
[1600]	valid_set's binary_logloss: 0.224234
[1650]	valid_set's binary_logloss: 0.224178
[1700]	valid_set's binary_logloss: 0.224206
[1750]	valid_set's binary_logloss: 0.224013
[1800]	valid_set's binary_logloss: 0.223961
[1850]	valid_set's binary_logloss: 0.22392
[1900]	valid_set's binary_logloss: 0.223807
[1950]	valid_set's binary_logloss: 0.223734
[2000]	valid_set's binary_logloss: 0.223711
[2050]	valid_set's binary_logloss: 0.223547
[2100]	valid_set's binary_logloss: 0.223482
[2150]	valid_set's binary_logloss: 0.223443
[2200]	valid_set's binary_logloss: 0.223459
[2250]	valid_set's binary_logloss: 0.223522
[2300]	valid_set's binary_logloss: 0.223449
[2350]	valid_set's binary_logloss: 0.22343
[2400]	valid_set's binary_logloss: 0.223503
[2450]	valid_set's binary_logloss: 0.223495
[2500]	valid_set's binary_logloss: 0.223521
[2550]	valid_set's binary_logloss: 0.223549
[2600]	valid_set's binary_logloss: 0.223561
[2650]	valid_set's binary_logloss: 0.223603
[2700]	valid_set's binary_logloss: 0.223694
[2750]	valid_set's binary_logloss: 0.223723
[2800]	valid_set's binary_logloss: 0.223814
[2850]	valid_set's binary_logloss: 0.223896
[2900]	valid_set's binary_logloss: 0.223937
[2950]	valid_set's binary_logloss: 0.224048
[3000]	valid_set's binary_logloss: 0.224096
[3050]	valid_set's binary_logloss: 0.224214
[3100]	valid_set's binary_logloss: 0.224221

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283625
[100]	valid_set's binary_logloss: 0.260625
[150]	valid_set's binary_logloss: 0.251262
[200]	valid_set's binary_logloss: 0.245745
[250]	valid_set's binary_logloss: 0.242067
[300]	valid_set's binary_logloss: 0.239564
[350]	valid_set's binary_logloss: 0.237406
[400]	valid_set's binary_logloss: 0.235647
[450]	valid_set's binary_logloss: 0.234142
[500]	valid_set's binary_logloss: 0.232939
[550]	valid_set's binary_logloss: 0.231719
[600]	valid_set's binary_logloss: 0.230749
[650]	valid_set's binary_logloss: 0.230027
[700]	valid_set's binary_logloss: 0.229392
[750]	valid_set's binary_logloss: 0.228832
[800]	valid_set's binary_logloss: 0.228164
[850]	valid_set's binary_logloss: 0.227559
[900]	valid_set's binary_logloss: 0.226879
[950]	valid_set's binary_logloss: 0.226497
[1000]	valid_set's binary_logloss: 0.226115
[1050]	valid_set's binary_logloss: 0.225832
[1100]	valid_set's binary_logloss: 0.22558
[1150]	valid_set's binary_logloss: 0.225319
[1200]	valid_set's binary_logloss: 0.225127
[1250]	valid_set's binary_logloss: 0.224836
[1300]	valid_set's binary_logloss: 0.22468
[1350]	valid_set's binary_logloss: 0.224552
[1400]	valid_set's binary_logloss: 0.224365
[1450]	valid_set's binary_logloss: 0.224319
[1500]	valid_set's binary_logloss: 0.224205
[1550]	valid_set's binary_logloss: 0.224073
[1600]	valid_set's binary_logloss: 0.223997
[1650]	valid_set's binary_logloss: 0.223881
[1700]	valid_set's binary_logloss: 0.223828
[1750]	valid_set's binary_logloss: 0.223712
[1800]	valid_set's binary_logloss: 0.223583
[1850]	valid_set's binary_logloss: 0.223504
[1900]	valid_set's binary_logloss: 0.223416
[1950]	valid_set's binary_logloss: 0.223383
[2000]	valid_set's binary_logloss: 0.223368
[2050]	valid_set's binary_logloss: 0.22335
[2100]	valid_set's binary_logloss: 0.223289
[2150]	valid_set's binary_logloss: 0.223303
[2200]	valid_set's binary_logloss: 0.223276
[2250]	valid_set's binary_logloss: 0.223277
[2300]	valid_set's binary_logloss: 0.223318
[2350]	valid_set's binary_logloss: 0.22332
[2400]	valid_set's binary_logloss: 0.2233
[2450]	valid_set's binary_logloss: 0.223266
[2500]	valid_set's binary_logloss: 0.223334
[2550]	valid_set's binary_logloss: 0.223339
[2600]	valid_set's binary_logloss: 0.223337
[2650]	valid_set's binary_logloss: 0.223483
[2700]	valid_set's binary_logloss: 0.223489
[2750]	valid_set's binary_logloss: 0.223556
[2800]	valid_set's binary_logloss: 0.223695
[2850]	valid_set's binary_logloss: 0.223772
[2900]	valid_set's binary_logloss: 0.223808
[2950]	valid_set's binary_logloss: 0.22386
[3000]	valid_set's binary_logloss: 0.223887

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282846
[100]	valid_set's binary_logloss: 0.260612
[150]	valid_set's binary_logloss: 0.251377
[200]	valid_set's binary_logloss: 0.246252
[250]	valid_set's binary_logloss: 0.242661
[300]	valid_set's binary_logloss: 0.239921
[350]	valid_set's binary_logloss: 0.237628
[400]	valid_set's binary_logloss: 0.235969
[450]	valid_set's binary_logloss: 0.234702
[500]	valid_set's binary_logloss: 0.233419
[550]	valid_set's binary_logloss: 0.232117
[600]	valid_set's binary_logloss: 0.231258
[650]	valid_set's binary_logloss: 0.230531
[700]	valid_set's binary_logloss: 0.229814
[750]	valid_set's binary_logloss: 0.229258
[800]	valid_set's binary_logloss: 0.228817
[850]	valid_set's binary_logloss: 0.228231
[900]	valid_set's binary_logloss: 0.227681
[950]	valid_set's binary_logloss: 0.227419
[1000]	valid_set's binary_logloss: 0.227074
[1050]	valid_set's binary_logloss: 0.226712
[1100]	valid_set's binary_logloss: 0.226455
[1150]	valid_set's binary_logloss: 0.226242
[1200]	valid_set's binary_logloss: 0.226097
[1250]	valid_set's binary_logloss: 0.225987
[1300]	valid_set's binary_logloss: 0.225853
[1350]	valid_set's binary_logloss: 0.225687
[1400]	valid_set's binary_logloss: 0.225689
[1450]	valid_set's binary_logloss: 0.225572
[1500]	valid_set's binary_logloss: 0.225552
[1550]	valid_set's binary_logloss: 0.225519
[1600]	valid_set's binary_logloss: 0.225433
[1650]	valid_set's binary_logloss: 0.225361
[1700]	valid_set's binary_logloss: 0.22537
[1750]	valid_set's binary_logloss: 0.22535
[1800]	valid_set's binary_logloss: 0.2253
[1850]	valid_set's binary_logloss: 0.225257
[1900]	valid_set's binary_logloss: 0.225209
[1950]	valid_set's binary_logloss: 0.225229
[2000]	valid_set's binary_logloss: 0.22534
[2050]	valid_set's binary_logloss: 0.225419
[2100]	valid_set's binary_logloss: 0.22546
[2150]	valid_set's binary_logloss: 0.225482
[2200]	valid_set's binary_logloss: 0.225535
[2250]	valid_set's binary_logloss: 0.225518
[2300]	valid_set's binary_logloss: 0.225564
[2350]	valid_set's binary_logloss: 0.225537
[2400]	valid_set's binary_logloss: 0.225561

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281075
[100]	valid_set's binary_logloss: 0.258067
[150]	valid_set's binary_logloss: 0.248925
[200]	valid_set's binary_logloss: 0.243407
[250]	valid_set's binary_logloss: 0.239914
[300]	valid_set's binary_logloss: 0.23709
[350]	valid_set's binary_logloss: 0.234534
[400]	valid_set's binary_logloss: 0.232763
[450]	valid_set's binary_logloss: 0.231399
[500]	valid_set's binary_logloss: 0.230194
[550]	valid_set's binary_logloss: 0.229321
[600]	valid_set's binary_logloss: 0.228595
[650]	valid_set's binary_logloss: 0.227771
[700]	valid_set's binary_logloss: 0.2271
[750]	valid_set's binary_logloss: 0.226482
[800]	valid_set's binary_logloss: 0.226149
[850]	valid_set's binary_logloss: 0.22564
[900]	valid_set's binary_logloss: 0.22529
[950]	valid_set's binary_logloss: 0.224935
[1000]	valid_set's binary_logloss: 0.224626
[1050]	valid_set's binary_logloss: 0.224368
[1100]	valid_set's binary_logloss: 0.224134
[1150]	valid_set's binary_logloss: 0.223924
[1200]	valid_set's binary_logloss: 0.223703
[1250]	valid_set's binary_logloss: 0.223517
[1300]	valid_set's binary_logloss: 0.223379
[1350]	valid_set's binary_logloss: 0.22314
[1400]	valid_set's binary_logloss: 0.223088
[1450]	valid_set's binary_logloss: 0.22292
[1500]	valid_set's binary_logloss: 0.222556
[1550]	valid_set's binary_logloss: 0.222265
[1600]	valid_set's binary_logloss: 0.222107
[1650]	valid_set's binary_logloss: 0.221959
[1700]	valid_set's binary_logloss: 0.22182
[1750]	valid_set's binary_logloss: 0.221765
[1800]	valid_set's binary_logloss: 0.221765
[1850]	valid_set's binary_logloss: 0.22169
[1900]	valid_set's binary_logloss: 0.221615
[1950]	valid_set's binary_logloss: 0.221572
[2000]	valid_set's binary_logloss: 0.221666
[2050]	valid_set's binary_logloss: 0.22163
[2100]	valid_set's binary_logloss: 0.221589
[2150]	valid_set's binary_logloss: 0.221544
[2200]	valid_set's binary_logloss: 0.221534
[2250]	valid_set's binary_logloss: 0.221538
[2300]	valid_set's binary_logloss: 0.221637
[2350]	valid_set's binary_logloss: 0.221634
[2400]	valid_set's binary_logloss: 0.221659
[2450]	valid_set's binary_logloss: 0.221695
[2500]	valid_set's binary_logloss: 0.221647
[2550]	valid_set's binary_logloss: 0.221661
[2600]	valid_set's binary_logloss: 0.221698
[2650]	valid_set's binary_logloss: 0.22178
[2700]	valid_set's binary_logloss: 0.221833
[2750]	valid_set's binary_logloss: 0.221891

Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBM_BAG_L1\model.pkl
	0.9516	 = Validation score   (roc_auc)
	106.83s	 = Training   runtime
	5.27s	 = Validation runtime
	12808.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 32285.83s of the 32285.83s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.302354
[100]	valid_set's binary_logloss: 0.275238
[150]	valid_set's binary_logloss: 0.263743
[200]	valid_set's binary_logloss: 0.256204
[250]	valid_set's binary_logloss: 0.251193
[300]	valid_set's binary_logloss: 0.247625
[350]	valid_set's binary_logloss: 0.244643
[400]	valid_set's binary_logloss: 0.241851
[450]	valid_set's binary_logloss: 0.239986
[500]	valid_set's binary_logloss: 0.238076
[550]	valid_set's binary_logloss: 0.236579
[600]	valid_set's binary_logloss: 0.235148
[650]	valid_set's binary_logloss: 0.233981
[700]	valid_set's binary_logloss: 0.232899
[750]	valid_set's binary_logloss: 0.231693
[800]	valid_set's binary_logloss: 0.230699
[850]	valid_set's binary_logloss: 0.229875
[900]	valid_set's binary_logloss: 0.228986
[950]	valid_set's binary_logloss: 0.228226
[1000]	valid_set's binary_logloss: 0.22749
[1050]	valid_set's binary_logloss: 0.226978
[1100]	valid_set's binary_logloss: 0.226562
[1150]	valid_set's binary_logloss: 0.226051
[1200]	valid_set's binary_logloss: 0.225636
[1250]	valid_set's binary_logloss: 0.225145
[1300]	valid_set's binary_logloss: 0.224718
[1350]	valid_set's binary_logloss: 0.224185
[1400]	valid_set's binary_logloss: 0.22384
[1450]	valid_set's binary_logloss: 0.223513
[1500]	valid_set's binary_logloss: 0.223251
[1550]	valid_set's binary_logloss: 0.222909
[1600]	valid_set's binary_logloss: 0.222648
[1650]	valid_set's binary_logloss: 0.222342
[1700]	valid_set's binary_logloss: 0.222118
[1750]	valid_set's binary_logloss: 0.221858
[1800]	valid_set's binary_logloss: 0.221669
[1850]	valid_set's binary_logloss: 0.221455
[1900]	valid_set's binary_logloss: 0.221224
[1950]	valid_set's binary_logloss: 0.221027
[2000]	valid_set's binary_logloss: 0.220774
[2050]	valid_set's binary_logloss: 0.220616
[2100]	valid_set's binary_logloss: 0.220413
[2150]	valid_set's binary_logloss: 0.220248
[2200]	valid_set's binary_logloss: 0.220142
[2250]	valid_set's binary_logloss: 0.220005
[2300]	valid_set's binary_logloss: 0.219844
[2350]	valid_set's binary_logloss: 0.219666
[2400]	valid_set's binary_logloss: 0.219549
[2450]	valid_set's binary_logloss: 0.219447
[2500]	valid_set's binary_logloss: 0.219367
[2550]	valid_set's binary_logloss: 0.21927
[2600]	valid_set's binary_logloss: 0.21917
[2650]	valid_set's binary_logloss: 0.219051
[2700]	valid_set's binary_logloss: 0.218961
[2750]	valid_set's binary_logloss: 0.21883
[2800]	valid_set's binary_logloss: 0.218716
[2850]	valid_set's binary_logloss: 0.218654
[2900]	valid_set's binary_logloss: 0.218597
[2950]	valid_set's binary_logloss: 0.218521
[3000]	valid_set's binary_logloss: 0.218489
[3050]	valid_set's binary_logloss: 0.218401
[3100]	valid_set's binary_logloss: 0.218404
[3150]	valid_set's binary_logloss: 0.218343
[3200]	valid_set's binary_logloss: 0.218302
[3250]	valid_set's binary_logloss: 0.218221
[3300]	valid_set's binary_logloss: 0.218207
[3350]	valid_set's binary_logloss: 0.21818
[3400]	valid_set's binary_logloss: 0.218111
[3450]	valid_set's binary_logloss: 0.218057
[3500]	valid_set's binary_logloss: 0.218029
[3550]	valid_set's binary_logloss: 0.217928
[3600]	valid_set's binary_logloss: 0.217905
[3650]	valid_set's binary_logloss: 0.217873
[3700]	valid_set's binary_logloss: 0.217857
[3750]	valid_set's binary_logloss: 0.217865
[3800]	valid_set's binary_logloss: 0.217831
[3850]	valid_set's binary_logloss: 0.217812
[3900]	valid_set's binary_logloss: 0.217785
[3950]	valid_set's binary_logloss: 0.217766
[4000]	valid_set's binary_logloss: 0.217775
[4050]	valid_set's binary_logloss: 0.217765
[4100]	valid_set's binary_logloss: 0.217791
[4150]	valid_set's binary_logloss: 0.217825
[4200]	valid_set's binary_logloss: 0.217822
[4250]	valid_set's binary_logloss: 0.217791
[4300]	valid_set's binary_logloss: 0.217785
[4350]	valid_set's binary_logloss: 0.21777
[4400]	valid_set's binary_logloss: 0.217785
[4450]	valid_set's binary_logloss: 0.217763
[4500]	valid_set's binary_logloss: 0.217764
[4550]	valid_set's binary_logloss: 0.217763
[4600]	valid_set's binary_logloss: 0.217765
[4650]	valid_set's binary_logloss: 0.217788
[4700]	valid_set's binary_logloss: 0.217814
[4750]	valid_set's binary_logloss: 0.217819
[4800]	valid_set's binary_logloss: 0.217803
[4850]	valid_set's binary_logloss: 0.21779
[4900]	valid_set's binary_logloss: 0.217832
[4950]	valid_set's binary_logloss: 0.217869
[5000]	valid_set's binary_logloss: 0.217894
[5050]	valid_set's binary_logloss: 0.217908
[5100]	valid_set's binary_logloss: 0.217904
[5150]	valid_set's binary_logloss: 0.217911
[5200]	valid_set's binary_logloss: 0.217895
[5250]	valid_set's binary_logloss: 0.217866
[5300]	valid_set's binary_logloss: 0.217843
[5350]	valid_set's binary_logloss: 0.217841
[5400]	valid_set's binary_logloss: 0.217863
[5450]	valid_set's binary_logloss: 0.217886
[5500]	valid_set's binary_logloss: 0.217879
[5550]	valid_set's binary_logloss: 0.217931
[5600]	valid_set's binary_logloss: 0.218
[5650]	valid_set's binary_logloss: 0.218041
[5700]	valid_set's binary_logloss: 0.218057
[5750]	valid_set's binary_logloss: 0.218105
[5800]	valid_set's binary_logloss: 0.218147
[5850]	valid_set's binary_logloss: 0.218163

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.304575
[100]	valid_set's binary_logloss: 0.277638
[150]	valid_set's binary_logloss: 0.26536
[200]	valid_set's binary_logloss: 0.258268
[250]	valid_set's binary_logloss: 0.25331
[300]	valid_set's binary_logloss: 0.24984
[350]	valid_set's binary_logloss: 0.246778
[400]	valid_set's binary_logloss: 0.244222
[450]	valid_set's binary_logloss: 0.242003
[500]	valid_set's binary_logloss: 0.240098
[550]	valid_set's binary_logloss: 0.238601
[600]	valid_set's binary_logloss: 0.237136
[650]	valid_set's binary_logloss: 0.235831
[700]	valid_set's binary_logloss: 0.234779
[750]	valid_set's binary_logloss: 0.233817
[800]	valid_set's binary_logloss: 0.23283
[850]	valid_set's binary_logloss: 0.23193
[900]	valid_set's binary_logloss: 0.231241
[950]	valid_set's binary_logloss: 0.230382
[1000]	valid_set's binary_logloss: 0.22973
[1050]	valid_set's binary_logloss: 0.22918
[1100]	valid_set's binary_logloss: 0.22868
[1150]	valid_set's binary_logloss: 0.228182
[1200]	valid_set's binary_logloss: 0.227792
[1250]	valid_set's binary_logloss: 0.227385
[1300]	valid_set's binary_logloss: 0.227054
[1350]	valid_set's binary_logloss: 0.226717
[1400]	valid_set's binary_logloss: 0.226386
[1450]	valid_set's binary_logloss: 0.226052
[1500]	valid_set's binary_logloss: 0.225766
[1550]	valid_set's binary_logloss: 0.225488
[1600]	valid_set's binary_logloss: 0.225231
[1650]	valid_set's binary_logloss: 0.225009
[1700]	valid_set's binary_logloss: 0.224614
[1750]	valid_set's binary_logloss: 0.224369
[1800]	valid_set's binary_logloss: 0.224175
[1850]	valid_set's binary_logloss: 0.224002
[1900]	valid_set's binary_logloss: 0.223792
[1950]	valid_set's binary_logloss: 0.223564
[2000]	valid_set's binary_logloss: 0.223352
[2050]	valid_set's binary_logloss: 0.223241
[2100]	valid_set's binary_logloss: 0.223026
[2150]	valid_set's binary_logloss: 0.222794
[2200]	valid_set's binary_logloss: 0.222666
[2250]	valid_set's binary_logloss: 0.222519
[2300]	valid_set's binary_logloss: 0.222405
[2350]	valid_set's binary_logloss: 0.222276
[2400]	valid_set's binary_logloss: 0.222106
[2450]	valid_set's binary_logloss: 0.221987
[2500]	valid_set's binary_logloss: 0.221803
[2550]	valid_set's binary_logloss: 0.221672
[2600]	valid_set's binary_logloss: 0.221609
[2650]	valid_set's binary_logloss: 0.221547
[2700]	valid_set's binary_logloss: 0.221454
[2750]	valid_set's binary_logloss: 0.221406
[2800]	valid_set's binary_logloss: 0.221309
[2850]	valid_set's binary_logloss: 0.221222
[2900]	valid_set's binary_logloss: 0.221163
[2950]	valid_set's binary_logloss: 0.221096
[3000]	valid_set's binary_logloss: 0.220951
[3050]	valid_set's binary_logloss: 0.220817
[3100]	valid_set's binary_logloss: 0.220807
[3150]	valid_set's binary_logloss: 0.220784
[3200]	valid_set's binary_logloss: 0.220722
[3250]	valid_set's binary_logloss: 0.220685
[3300]	valid_set's binary_logloss: 0.22066
[3350]	valid_set's binary_logloss: 0.220652
[3400]	valid_set's binary_logloss: 0.220605
[3450]	valid_set's binary_logloss: 0.220518
[3500]	valid_set's binary_logloss: 0.220489
[3550]	valid_set's binary_logloss: 0.220443
[3600]	valid_set's binary_logloss: 0.220385
[3650]	valid_set's binary_logloss: 0.220328
[3700]	valid_set's binary_logloss: 0.220325
[3750]	valid_set's binary_logloss: 0.22029
[3800]	valid_set's binary_logloss: 0.220255
[3850]	valid_set's binary_logloss: 0.220209
[3900]	valid_set's binary_logloss: 0.22019
[3950]	valid_set's binary_logloss: 0.220153
[4000]	valid_set's binary_logloss: 0.220164
[4050]	valid_set's binary_logloss: 0.220102
[4100]	valid_set's binary_logloss: 0.22012
[4150]	valid_set's binary_logloss: 0.220134
[4200]	valid_set's binary_logloss: 0.220105
[4250]	valid_set's binary_logloss: 0.220129
[4300]	valid_set's binary_logloss: 0.220101
[4350]	valid_set's binary_logloss: 0.220067
[4400]	valid_set's binary_logloss: 0.220065
[4450]	valid_set's binary_logloss: 0.220037
[4500]	valid_set's binary_logloss: 0.220056
[4550]	valid_set's binary_logloss: 0.220014
[4600]	valid_set's binary_logloss: 0.21996
[4650]	valid_set's binary_logloss: 0.219986
[4700]	valid_set's binary_logloss: 0.220009
[4750]	valid_set's binary_logloss: 0.220017
[4800]	valid_set's binary_logloss: 0.219946
[4850]	valid_set's binary_logloss: 0.219922
[4900]	valid_set's binary_logloss: 0.219921
[4950]	valid_set's binary_logloss: 0.219988
[5000]	valid_set's binary_logloss: 0.22002
[5050]	valid_set's binary_logloss: 0.220047
[5100]	valid_set's binary_logloss: 0.220051
[5150]	valid_set's binary_logloss: 0.220083
[5200]	valid_set's binary_logloss: 0.220147
[5250]	valid_set's binary_logloss: 0.220196
[5300]	valid_set's binary_logloss: 0.220272
[5350]	valid_set's binary_logloss: 0.220298
[5400]	valid_set's binary_logloss: 0.220291
[5450]	valid_set's binary_logloss: 0.220297
[5500]	valid_set's binary_logloss: 0.22031
[5550]	valid_set's binary_logloss: 0.220339
[5600]	valid_set's binary_logloss: 0.220371
[5650]	valid_set's binary_logloss: 0.220409
[5700]	valid_set's binary_logloss: 0.22042
[5750]	valid_set's binary_logloss: 0.220444
[5800]	valid_set's binary_logloss: 0.22047
[5850]	valid_set's binary_logloss: 0.220487
[5900]	valid_set's binary_logloss: 0.22052
[5950]	valid_set's binary_logloss: 0.220535
[6000]	valid_set's binary_logloss: 0.220587
[6050]	valid_set's binary_logloss: 0.220627
[6100]	valid_set's binary_logloss: 0.220668
[6150]	valid_set's binary_logloss: 0.220701
[6200]	valid_set's binary_logloss: 0.220713
[6250]	valid_set's binary_logloss: 0.220715
[6300]	valid_set's binary_logloss: 0.220715
[6350]	valid_set's binary_logloss: 0.220778

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303685
[100]	valid_set's binary_logloss: 0.276644
[150]	valid_set's binary_logloss: 0.265384
[200]	valid_set's binary_logloss: 0.258499
[250]	valid_set's binary_logloss: 0.253654
[300]	valid_set's binary_logloss: 0.250225
[350]	valid_set's binary_logloss: 0.247333
[400]	valid_set's binary_logloss: 0.244989
[450]	valid_set's binary_logloss: 0.243103
[500]	valid_set's binary_logloss: 0.241425
[550]	valid_set's binary_logloss: 0.239782
[600]	valid_set's binary_logloss: 0.238472
[650]	valid_set's binary_logloss: 0.237224
[700]	valid_set's binary_logloss: 0.236148
[750]	valid_set's binary_logloss: 0.235155
[800]	valid_set's binary_logloss: 0.234235
[850]	valid_set's binary_logloss: 0.233491
[900]	valid_set's binary_logloss: 0.232716
[950]	valid_set's binary_logloss: 0.23197
[1000]	valid_set's binary_logloss: 0.231437
[1050]	valid_set's binary_logloss: 0.23088
[1100]	valid_set's binary_logloss: 0.230426
[1150]	valid_set's binary_logloss: 0.229936
[1200]	valid_set's binary_logloss: 0.229526
[1250]	valid_set's binary_logloss: 0.22917
[1300]	valid_set's binary_logloss: 0.228771
[1350]	valid_set's binary_logloss: 0.228415
[1400]	valid_set's binary_logloss: 0.228126
[1450]	valid_set's binary_logloss: 0.227814
[1500]	valid_set's binary_logloss: 0.22749
[1550]	valid_set's binary_logloss: 0.227196
[1600]	valid_set's binary_logloss: 0.227002
[1650]	valid_set's binary_logloss: 0.226826
[1700]	valid_set's binary_logloss: 0.226652
[1750]	valid_set's binary_logloss: 0.226436
[1800]	valid_set's binary_logloss: 0.226215
[1850]	valid_set's binary_logloss: 0.226068
[1900]	valid_set's binary_logloss: 0.225902
[1950]	valid_set's binary_logloss: 0.225754
[2000]	valid_set's binary_logloss: 0.225531
[2050]	valid_set's binary_logloss: 0.225366
[2100]	valid_set's binary_logloss: 0.225301
[2150]	valid_set's binary_logloss: 0.22512
[2200]	valid_set's binary_logloss: 0.224981
[2250]	valid_set's binary_logloss: 0.224902
[2300]	valid_set's binary_logloss: 0.224818
[2350]	valid_set's binary_logloss: 0.22469
[2400]	valid_set's binary_logloss: 0.224603
[2450]	valid_set's binary_logloss: 0.224542
[2500]	valid_set's binary_logloss: 0.224472
[2550]	valid_set's binary_logloss: 0.224402
[2600]	valid_set's binary_logloss: 0.224314
[2650]	valid_set's binary_logloss: 0.224279
[2700]	valid_set's binary_logloss: 0.224125
[2750]	valid_set's binary_logloss: 0.224027
[2800]	valid_set's binary_logloss: 0.224017
[2850]	valid_set's binary_logloss: 0.223919
[2900]	valid_set's binary_logloss: 0.223881
[2950]	valid_set's binary_logloss: 0.223844
[3000]	valid_set's binary_logloss: 0.223801
[3050]	valid_set's binary_logloss: 0.223739
[3100]	valid_set's binary_logloss: 0.22372
[3150]	valid_set's binary_logloss: 0.223641
[3200]	valid_set's binary_logloss: 0.223608
[3250]	valid_set's binary_logloss: 0.223616
[3300]	valid_set's binary_logloss: 0.223594
[3350]	valid_set's binary_logloss: 0.223541
[3400]	valid_set's binary_logloss: 0.223528
[3450]	valid_set's binary_logloss: 0.22346
[3500]	valid_set's binary_logloss: 0.223445
[3550]	valid_set's binary_logloss: 0.223416
[3600]	valid_set's binary_logloss: 0.223371
[3650]	valid_set's binary_logloss: 0.223319
[3700]	valid_set's binary_logloss: 0.223361
[3750]	valid_set's binary_logloss: 0.223404
[3800]	valid_set's binary_logloss: 0.223423
[3850]	valid_set's binary_logloss: 0.223422
[3900]	valid_set's binary_logloss: 0.223456
[3950]	valid_set's binary_logloss: 0.223492
[4000]	valid_set's binary_logloss: 0.223419
[4050]	valid_set's binary_logloss: 0.223438
[4100]	valid_set's binary_logloss: 0.223433
[4150]	valid_set's binary_logloss: 0.223394
[4200]	valid_set's binary_logloss: 0.223408
[4250]	valid_set's binary_logloss: 0.22338
[4300]	valid_set's binary_logloss: 0.223377
[4350]	valid_set's binary_logloss: 0.223357
[4400]	valid_set's binary_logloss: 0.223363
[4450]	valid_set's binary_logloss: 0.223352
[4500]	valid_set's binary_logloss: 0.223348
[4550]	valid_set's binary_logloss: 0.223359
[4600]	valid_set's binary_logloss: 0.223376
[4650]	valid_set's binary_logloss: 0.223397
[4700]	valid_set's binary_logloss: 0.223424
[4750]	valid_set's binary_logloss: 0.223442

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.3024
[100]	valid_set's binary_logloss: 0.274499
[150]	valid_set's binary_logloss: 0.263286
[200]	valid_set's binary_logloss: 0.256527
[250]	valid_set's binary_logloss: 0.251505
[300]	valid_set's binary_logloss: 0.247978
[350]	valid_set's binary_logloss: 0.244971
[400]	valid_set's binary_logloss: 0.242423
[450]	valid_set's binary_logloss: 0.240418
[500]	valid_set's binary_logloss: 0.23837
[550]	valid_set's binary_logloss: 0.236924
[600]	valid_set's binary_logloss: 0.23556
[650]	valid_set's binary_logloss: 0.234505
[700]	valid_set's binary_logloss: 0.233394
[750]	valid_set's binary_logloss: 0.232478
[800]	valid_set's binary_logloss: 0.231483
[850]	valid_set's binary_logloss: 0.230657
[900]	valid_set's binary_logloss: 0.229918
[950]	valid_set's binary_logloss: 0.229233
[1000]	valid_set's binary_logloss: 0.228562
[1050]	valid_set's binary_logloss: 0.22791
[1100]	valid_set's binary_logloss: 0.227383
[1150]	valid_set's binary_logloss: 0.226838
[1200]	valid_set's binary_logloss: 0.226405
[1250]	valid_set's binary_logloss: 0.226003
[1300]	valid_set's binary_logloss: 0.225605
[1350]	valid_set's binary_logloss: 0.225262
[1400]	valid_set's binary_logloss: 0.224869
[1450]	valid_set's binary_logloss: 0.224526
[1500]	valid_set's binary_logloss: 0.224259
[1550]	valid_set's binary_logloss: 0.223992
[1600]	valid_set's binary_logloss: 0.223667
[1650]	valid_set's binary_logloss: 0.223374
[1700]	valid_set's binary_logloss: 0.223134
[1750]	valid_set's binary_logloss: 0.22292
[1800]	valid_set's binary_logloss: 0.222694
[1850]	valid_set's binary_logloss: 0.222507
[1900]	valid_set's binary_logloss: 0.222337
[1950]	valid_set's binary_logloss: 0.222204
[2000]	valid_set's binary_logloss: 0.222072
[2050]	valid_set's binary_logloss: 0.221895
[2100]	valid_set's binary_logloss: 0.221738
[2150]	valid_set's binary_logloss: 0.221621
[2200]	valid_set's binary_logloss: 0.221496
[2250]	valid_set's binary_logloss: 0.221352
[2300]	valid_set's binary_logloss: 0.221234
[2350]	valid_set's binary_logloss: 0.221147
[2400]	valid_set's binary_logloss: 0.221093
[2450]	valid_set's binary_logloss: 0.220964
[2500]	valid_set's binary_logloss: 0.220808
[2550]	valid_set's binary_logloss: 0.220694
[2600]	valid_set's binary_logloss: 0.220597
[2650]	valid_set's binary_logloss: 0.220486
[2700]	valid_set's binary_logloss: 0.220429
[2750]	valid_set's binary_logloss: 0.220412
[2800]	valid_set's binary_logloss: 0.22039
[2850]	valid_set's binary_logloss: 0.220349
[2900]	valid_set's binary_logloss: 0.220235
[2950]	valid_set's binary_logloss: 0.220179
[3000]	valid_set's binary_logloss: 0.220112
[3050]	valid_set's binary_logloss: 0.220046
[3100]	valid_set's binary_logloss: 0.219995
[3150]	valid_set's binary_logloss: 0.219944
[3200]	valid_set's binary_logloss: 0.219859
[3250]	valid_set's binary_logloss: 0.219857
[3300]	valid_set's binary_logloss: 0.219792
[3350]	valid_set's binary_logloss: 0.219751
[3400]	valid_set's binary_logloss: 0.219683
[3450]	valid_set's binary_logloss: 0.21961
[3500]	valid_set's binary_logloss: 0.219624
[3550]	valid_set's binary_logloss: 0.21963
[3600]	valid_set's binary_logloss: 0.219641
[3650]	valid_set's binary_logloss: 0.21956
[3700]	valid_set's binary_logloss: 0.219525
[3750]	valid_set's binary_logloss: 0.219498
[3800]	valid_set's binary_logloss: 0.219503
[3850]	valid_set's binary_logloss: 0.219481
[3900]	valid_set's binary_logloss: 0.219462
[3950]	valid_set's binary_logloss: 0.219512
[4000]	valid_set's binary_logloss: 0.219537
[4050]	valid_set's binary_logloss: 0.219496
[4100]	valid_set's binary_logloss: 0.219484
[4150]	valid_set's binary_logloss: 0.219453
[4200]	valid_set's binary_logloss: 0.219521
[4250]	valid_set's binary_logloss: 0.219521
[4300]	valid_set's binary_logloss: 0.219518
[4350]	valid_set's binary_logloss: 0.219564
[4400]	valid_set's binary_logloss: 0.219559
[4450]	valid_set's binary_logloss: 0.219592
[4500]	valid_set's binary_logloss: 0.219535
[4550]	valid_set's binary_logloss: 0.219566
[4600]	valid_set's binary_logloss: 0.219553
[4650]	valid_set's binary_logloss: 0.219551
[4700]	valid_set's binary_logloss: 0.219538
[4750]	valid_set's binary_logloss: 0.219548
[4800]	valid_set's binary_logloss: 0.219628
[4850]	valid_set's binary_logloss: 0.219606
[4900]	valid_set's binary_logloss: 0.219598
[4950]	valid_set's binary_logloss: 0.219653
[5000]	valid_set's binary_logloss: 0.219729
[5050]	valid_set's binary_logloss: 0.219731
[5100]	valid_set's binary_logloss: 0.219746
[5150]	valid_set's binary_logloss: 0.219752
[5200]	valid_set's binary_logloss: 0.219771
[5250]	valid_set's binary_logloss: 0.219825
[5300]	valid_set's binary_logloss: 0.219891
[5350]	valid_set's binary_logloss: 0.219922
[5400]	valid_set's binary_logloss: 0.219954

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.30544
[100]	valid_set's binary_logloss: 0.276341
[150]	valid_set's binary_logloss: 0.263759
[200]	valid_set's binary_logloss: 0.256607
[250]	valid_set's binary_logloss: 0.25213
[300]	valid_set's binary_logloss: 0.248363
[350]	valid_set's binary_logloss: 0.245224
[400]	valid_set's binary_logloss: 0.242741
[450]	valid_set's binary_logloss: 0.240497
[500]	valid_set's binary_logloss: 0.238408
[550]	valid_set's binary_logloss: 0.236752
[600]	valid_set's binary_logloss: 0.235402
[650]	valid_set's binary_logloss: 0.234153
[700]	valid_set's binary_logloss: 0.233074
[750]	valid_set's binary_logloss: 0.232053
[800]	valid_set's binary_logloss: 0.231037
[850]	valid_set's binary_logloss: 0.230294
[900]	valid_set's binary_logloss: 0.229485
[950]	valid_set's binary_logloss: 0.228765
[1000]	valid_set's binary_logloss: 0.228181
[1050]	valid_set's binary_logloss: 0.227539
[1100]	valid_set's binary_logloss: 0.22706
[1150]	valid_set's binary_logloss: 0.226466
[1200]	valid_set's binary_logloss: 0.226017
[1250]	valid_set's binary_logloss: 0.225492
[1300]	valid_set's binary_logloss: 0.225087
[1350]	valid_set's binary_logloss: 0.224674
[1400]	valid_set's binary_logloss: 0.224346
[1450]	valid_set's binary_logloss: 0.224001
[1500]	valid_set's binary_logloss: 0.22367
[1550]	valid_set's binary_logloss: 0.223382
[1600]	valid_set's binary_logloss: 0.223021
[1650]	valid_set's binary_logloss: 0.222752
[1700]	valid_set's binary_logloss: 0.222518
[1750]	valid_set's binary_logloss: 0.222353
[1800]	valid_set's binary_logloss: 0.222109
[1850]	valid_set's binary_logloss: 0.22183
[1900]	valid_set's binary_logloss: 0.221621
[1950]	valid_set's binary_logloss: 0.221334
[2000]	valid_set's binary_logloss: 0.221165
[2050]	valid_set's binary_logloss: 0.220997
[2100]	valid_set's binary_logloss: 0.22085
[2150]	valid_set's binary_logloss: 0.220677
[2200]	valid_set's binary_logloss: 0.220545
[2250]	valid_set's binary_logloss: 0.220438
[2300]	valid_set's binary_logloss: 0.220279
[2350]	valid_set's binary_logloss: 0.220166
[2400]	valid_set's binary_logloss: 0.220065
[2450]	valid_set's binary_logloss: 0.21993
[2500]	valid_set's binary_logloss: 0.219818
[2550]	valid_set's binary_logloss: 0.21965
[2600]	valid_set's binary_logloss: 0.219573
[2650]	valid_set's binary_logloss: 0.219436
[2700]	valid_set's binary_logloss: 0.219308
[2750]	valid_set's binary_logloss: 0.219217
[2800]	valid_set's binary_logloss: 0.219123
[2850]	valid_set's binary_logloss: 0.2191
[2900]	valid_set's binary_logloss: 0.21905
[2950]	valid_set's binary_logloss: 0.218979
[3000]	valid_set's binary_logloss: 0.218902
[3050]	valid_set's binary_logloss: 0.21885
[3100]	valid_set's binary_logloss: 0.218811
[3150]	valid_set's binary_logloss: 0.218759
[3200]	valid_set's binary_logloss: 0.218659
[3250]	valid_set's binary_logloss: 0.218606
[3300]	valid_set's binary_logloss: 0.218503
[3350]	valid_set's binary_logloss: 0.218447
[3400]	valid_set's binary_logloss: 0.218443
[3450]	valid_set's binary_logloss: 0.218355
[3500]	valid_set's binary_logloss: 0.218337
[3550]	valid_set's binary_logloss: 0.218286
[3600]	valid_set's binary_logloss: 0.218252
[3650]	valid_set's binary_logloss: 0.218227
[3700]	valid_set's binary_logloss: 0.218225
[3750]	valid_set's binary_logloss: 0.218199
[3800]	valid_set's binary_logloss: 0.218159
[3850]	valid_set's binary_logloss: 0.21814
[3900]	valid_set's binary_logloss: 0.21814
[3950]	valid_set's binary_logloss: 0.218091
[4000]	valid_set's binary_logloss: 0.218091
[4050]	valid_set's binary_logloss: 0.218097
[4100]	valid_set's binary_logloss: 0.218082
[4150]	valid_set's binary_logloss: 0.218015
[4200]	valid_set's binary_logloss: 0.217983
[4250]	valid_set's binary_logloss: 0.217943
[4300]	valid_set's binary_logloss: 0.21794
[4350]	valid_set's binary_logloss: 0.217945
[4400]	valid_set's binary_logloss: 0.217944
[4450]	valid_set's binary_logloss: 0.21793
[4500]	valid_set's binary_logloss: 0.21796
[4550]	valid_set's binary_logloss: 0.217974
[4600]	valid_set's binary_logloss: 0.218005
[4650]	valid_set's binary_logloss: 0.218028
[4700]	valid_set's binary_logloss: 0.218046
[4750]	valid_set's binary_logloss: 0.218064
[4800]	valid_set's binary_logloss: 0.218129
[4850]	valid_set's binary_logloss: 0.218139
[4900]	valid_set's binary_logloss: 0.218147
[4950]	valid_set's binary_logloss: 0.218131
[5000]	valid_set's binary_logloss: 0.218187
[5050]	valid_set's binary_logloss: 0.218204
[5100]	valid_set's binary_logloss: 0.218169
[5150]	valid_set's binary_logloss: 0.218206
[5200]	valid_set's binary_logloss: 0.218237
[5250]	valid_set's binary_logloss: 0.218262
[5300]	valid_set's binary_logloss: 0.218303
[5350]	valid_set's binary_logloss: 0.218312
[5400]	valid_set's binary_logloss: 0.218323
[5450]	valid_set's binary_logloss: 0.218313
[5500]	valid_set's binary_logloss: 0.218324
[5550]	valid_set's binary_logloss: 0.218378
[5600]	valid_set's binary_logloss: 0.218392
[5650]	valid_set's binary_logloss: 0.218419
[5700]	valid_set's binary_logloss: 0.2184
[5750]	valid_set's binary_logloss: 0.21843

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303134
[100]	valid_set's binary_logloss: 0.274969
[150]	valid_set's binary_logloss: 0.263184
[200]	valid_set's binary_logloss: 0.256201
[250]	valid_set's binary_logloss: 0.251205
[300]	valid_set's binary_logloss: 0.24732
[350]	valid_set's binary_logloss: 0.244513
[400]	valid_set's binary_logloss: 0.2421
[450]	valid_set's binary_logloss: 0.239852
[500]	valid_set's binary_logloss: 0.237991
[550]	valid_set's binary_logloss: 0.236401
[600]	valid_set's binary_logloss: 0.235005
[650]	valid_set's binary_logloss: 0.233679
[700]	valid_set's binary_logloss: 0.23261
[750]	valid_set's binary_logloss: 0.231474
[800]	valid_set's binary_logloss: 0.230635
[850]	valid_set's binary_logloss: 0.229855
[900]	valid_set's binary_logloss: 0.22917
[950]	valid_set's binary_logloss: 0.228424
[1000]	valid_set's binary_logloss: 0.227781
[1050]	valid_set's binary_logloss: 0.227271
[1100]	valid_set's binary_logloss: 0.226665
[1150]	valid_set's binary_logloss: 0.226123
[1200]	valid_set's binary_logloss: 0.22567
[1250]	valid_set's binary_logloss: 0.225246
[1300]	valid_set's binary_logloss: 0.224857
[1350]	valid_set's binary_logloss: 0.224524
[1400]	valid_set's binary_logloss: 0.224096
[1450]	valid_set's binary_logloss: 0.223749
[1500]	valid_set's binary_logloss: 0.223423
[1550]	valid_set's binary_logloss: 0.223141
[1600]	valid_set's binary_logloss: 0.222796
[1650]	valid_set's binary_logloss: 0.222536
[1700]	valid_set's binary_logloss: 0.222264
[1750]	valid_set's binary_logloss: 0.222036
[1800]	valid_set's binary_logloss: 0.22178
[1850]	valid_set's binary_logloss: 0.221548
[1900]	valid_set's binary_logloss: 0.22138
[1950]	valid_set's binary_logloss: 0.221166
[2000]	valid_set's binary_logloss: 0.220971
[2050]	valid_set's binary_logloss: 0.220786
[2100]	valid_set's binary_logloss: 0.220589
[2150]	valid_set's binary_logloss: 0.220428
[2200]	valid_set's binary_logloss: 0.220337
[2250]	valid_set's binary_logloss: 0.22024
[2300]	valid_set's binary_logloss: 0.220089
[2350]	valid_set's binary_logloss: 0.219942
[2400]	valid_set's binary_logloss: 0.219901
[2450]	valid_set's binary_logloss: 0.219801
[2500]	valid_set's binary_logloss: 0.219694
[2550]	valid_set's binary_logloss: 0.219549
[2600]	valid_set's binary_logloss: 0.219468
[2650]	valid_set's binary_logloss: 0.219393
[2700]	valid_set's binary_logloss: 0.219259
[2750]	valid_set's binary_logloss: 0.219166
[2800]	valid_set's binary_logloss: 0.21912
[2850]	valid_set's binary_logloss: 0.218967
[2900]	valid_set's binary_logloss: 0.218824
[2950]	valid_set's binary_logloss: 0.218737
[3000]	valid_set's binary_logloss: 0.21869
[3050]	valid_set's binary_logloss: 0.218585
[3100]	valid_set's binary_logloss: 0.218494
[3150]	valid_set's binary_logloss: 0.218464
[3200]	valid_set's binary_logloss: 0.218407
[3250]	valid_set's binary_logloss: 0.218347
[3300]	valid_set's binary_logloss: 0.218309
[3350]	valid_set's binary_logloss: 0.218273
[3400]	valid_set's binary_logloss: 0.218185
[3450]	valid_set's binary_logloss: 0.218158
[3500]	valid_set's binary_logloss: 0.218068
[3550]	valid_set's binary_logloss: 0.218057
[3600]	valid_set's binary_logloss: 0.218007
[3650]	valid_set's binary_logloss: 0.218008
[3700]	valid_set's binary_logloss: 0.218057
[3750]	valid_set's binary_logloss: 0.218034
[3800]	valid_set's binary_logloss: 0.218038
[3850]	valid_set's binary_logloss: 0.217941
[3900]	valid_set's binary_logloss: 0.217952
[3950]	valid_set's binary_logloss: 0.217922
[4000]	valid_set's binary_logloss: 0.217938
[4050]	valid_set's binary_logloss: 0.217956
[4100]	valid_set's binary_logloss: 0.21787
[4150]	valid_set's binary_logloss: 0.217866
[4200]	valid_set's binary_logloss: 0.21786
[4250]	valid_set's binary_logloss: 0.217865
[4300]	valid_set's binary_logloss: 0.21785
[4350]	valid_set's binary_logloss: 0.217824
[4400]	valid_set's binary_logloss: 0.217816
[4450]	valid_set's binary_logloss: 0.217847
[4500]	valid_set's binary_logloss: 0.217876
[4550]	valid_set's binary_logloss: 0.217919
[4600]	valid_set's binary_logloss: 0.21792
[4650]	valid_set's binary_logloss: 0.217847
[4700]	valid_set's binary_logloss: 0.217878
[4750]	valid_set's binary_logloss: 0.217866
[4800]	valid_set's binary_logloss: 0.217845
[4850]	valid_set's binary_logloss: 0.217908
[4900]	valid_set's binary_logloss: 0.217909
[4950]	valid_set's binary_logloss: 0.217933
[5000]	valid_set's binary_logloss: 0.217958
[5050]	valid_set's binary_logloss: 0.217957
[5100]	valid_set's binary_logloss: 0.217969
[5150]	valid_set's binary_logloss: 0.218005
[5200]	valid_set's binary_logloss: 0.218014
[5250]	valid_set's binary_logloss: 0.218024
[5300]	valid_set's binary_logloss: 0.218008
[5350]	valid_set's binary_logloss: 0.218012
[5400]	valid_set's binary_logloss: 0.218027
[5450]	valid_set's binary_logloss: 0.217999
[5500]	valid_set's binary_logloss: 0.218026
[5550]	valid_set's binary_logloss: 0.218038
[5600]	valid_set's binary_logloss: 0.218049
[5650]	valid_set's binary_logloss: 0.21809
[5700]	valid_set's binary_logloss: 0.218113

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.300069
[100]	valid_set's binary_logloss: 0.273062
[150]	valid_set's binary_logloss: 0.262181
[200]	valid_set's binary_logloss: 0.25541
[250]	valid_set's binary_logloss: 0.250769
[300]	valid_set's binary_logloss: 0.246969
[350]	valid_set's binary_logloss: 0.243991
[400]	valid_set's binary_logloss: 0.241585
[450]	valid_set's binary_logloss: 0.239587
[500]	valid_set's binary_logloss: 0.237968
[550]	valid_set's binary_logloss: 0.236505
[600]	valid_set's binary_logloss: 0.235021
[650]	valid_set's binary_logloss: 0.233786
[700]	valid_set's binary_logloss: 0.232609
[750]	valid_set's binary_logloss: 0.231597
[800]	valid_set's binary_logloss: 0.230613
[850]	valid_set's binary_logloss: 0.229914
[900]	valid_set's binary_logloss: 0.229302
[950]	valid_set's binary_logloss: 0.228612
[1000]	valid_set's binary_logloss: 0.228019
[1050]	valid_set's binary_logloss: 0.22756
[1100]	valid_set's binary_logloss: 0.22713
[1150]	valid_set's binary_logloss: 0.226654
[1200]	valid_set's binary_logloss: 0.226209
[1250]	valid_set's binary_logloss: 0.225766
[1300]	valid_set's binary_logloss: 0.225308
[1350]	valid_set's binary_logloss: 0.224933
[1400]	valid_set's binary_logloss: 0.224586
[1450]	valid_set's binary_logloss: 0.224359
[1500]	valid_set's binary_logloss: 0.224088
[1550]	valid_set's binary_logloss: 0.223758
[1600]	valid_set's binary_logloss: 0.223448
[1650]	valid_set's binary_logloss: 0.223201
[1700]	valid_set's binary_logloss: 0.222933
[1750]	valid_set's binary_logloss: 0.222726
[1800]	valid_set's binary_logloss: 0.222576
[1850]	valid_set's binary_logloss: 0.222373
[1900]	valid_set's binary_logloss: 0.222193
[1950]	valid_set's binary_logloss: 0.222003
[2000]	valid_set's binary_logloss: 0.221876
[2050]	valid_set's binary_logloss: 0.221694
[2100]	valid_set's binary_logloss: 0.221565
[2150]	valid_set's binary_logloss: 0.221447
[2200]	valid_set's binary_logloss: 0.221321
[2250]	valid_set's binary_logloss: 0.221124
[2300]	valid_set's binary_logloss: 0.221008
[2350]	valid_set's binary_logloss: 0.220901
[2400]	valid_set's binary_logloss: 0.220791
[2450]	valid_set's binary_logloss: 0.220744
[2500]	valid_set's binary_logloss: 0.220698
[2550]	valid_set's binary_logloss: 0.22063
[2600]	valid_set's binary_logloss: 0.220533
[2650]	valid_set's binary_logloss: 0.220429
[2700]	valid_set's binary_logloss: 0.220408
[2750]	valid_set's binary_logloss: 0.22039
[2800]	valid_set's binary_logloss: 0.220338
[2850]	valid_set's binary_logloss: 0.22031
[2900]	valid_set's binary_logloss: 0.220242
[2950]	valid_set's binary_logloss: 0.220162
[3000]	valid_set's binary_logloss: 0.220143
[3050]	valid_set's binary_logloss: 0.220183
[3100]	valid_set's binary_logloss: 0.220094
[3150]	valid_set's binary_logloss: 0.220039
[3200]	valid_set's binary_logloss: 0.219979
[3250]	valid_set's binary_logloss: 0.219957
[3300]	valid_set's binary_logloss: 0.219946
[3350]	valid_set's binary_logloss: 0.219878
[3400]	valid_set's binary_logloss: 0.219833
[3450]	valid_set's binary_logloss: 0.219835
[3500]	valid_set's binary_logloss: 0.219799
[3550]	valid_set's binary_logloss: 0.219806
[3600]	valid_set's binary_logloss: 0.219768
[3650]	valid_set's binary_logloss: 0.219738
[3700]	valid_set's binary_logloss: 0.219725
[3750]	valid_set's binary_logloss: 0.219692
[3800]	valid_set's binary_logloss: 0.219693
[3850]	valid_set's binary_logloss: 0.219685
[3900]	valid_set's binary_logloss: 0.219724
[3950]	valid_set's binary_logloss: 0.219727
[4000]	valid_set's binary_logloss: 0.219739
[4050]	valid_set's binary_logloss: 0.219763
[4100]	valid_set's binary_logloss: 0.2198
[4150]	valid_set's binary_logloss: 0.21978
[4200]	valid_set's binary_logloss: 0.219791
[4250]	valid_set's binary_logloss: 0.219756
[4300]	valid_set's binary_logloss: 0.219773
[4350]	valid_set's binary_logloss: 0.219793
[4400]	valid_set's binary_logloss: 0.219821
[4450]	valid_set's binary_logloss: 0.219791
[4500]	valid_set's binary_logloss: 0.219815
[4550]	valid_set's binary_logloss: 0.219853
[4600]	valid_set's binary_logloss: 0.219911
[4650]	valid_set's binary_logloss: 0.219979
[4700]	valid_set's binary_logloss: 0.220005
[4750]	valid_set's binary_logloss: 0.22002
[4800]	valid_set's binary_logloss: 0.220044
[4850]	valid_set's binary_logloss: 0.220067
[4900]	valid_set's binary_logloss: 0.220071

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.301585
[100]	valid_set's binary_logloss: 0.273424
[150]	valid_set's binary_logloss: 0.260696
[200]	valid_set's binary_logloss: 0.253834
[250]	valid_set's binary_logloss: 0.249273
[300]	valid_set's binary_logloss: 0.24514
[350]	valid_set's binary_logloss: 0.242179
[400]	valid_set's binary_logloss: 0.239529
[450]	valid_set's binary_logloss: 0.237508
[500]	valid_set's binary_logloss: 0.235519
[550]	valid_set's binary_logloss: 0.233945
[600]	valid_set's binary_logloss: 0.232647
[650]	valid_set's binary_logloss: 0.231417
[700]	valid_set's binary_logloss: 0.230371
[750]	valid_set's binary_logloss: 0.229454
[800]	valid_set's binary_logloss: 0.228685
[850]	valid_set's binary_logloss: 0.227896
[900]	valid_set's binary_logloss: 0.227228
[950]	valid_set's binary_logloss: 0.226567
[1000]	valid_set's binary_logloss: 0.225926
[1050]	valid_set's binary_logloss: 0.225292
[1100]	valid_set's binary_logloss: 0.22482
[1150]	valid_set's binary_logloss: 0.224429
[1200]	valid_set's binary_logloss: 0.223974
[1250]	valid_set's binary_logloss: 0.22359
[1300]	valid_set's binary_logloss: 0.223208
[1350]	valid_set's binary_logloss: 0.222828
[1400]	valid_set's binary_logloss: 0.222419
[1450]	valid_set's binary_logloss: 0.222126
[1500]	valid_set's binary_logloss: 0.221833
[1550]	valid_set's binary_logloss: 0.221562
[1600]	valid_set's binary_logloss: 0.221226
[1650]	valid_set's binary_logloss: 0.22096
[1700]	valid_set's binary_logloss: 0.220712
[1750]	valid_set's binary_logloss: 0.220546
[1800]	valid_set's binary_logloss: 0.220311
[1850]	valid_set's binary_logloss: 0.220145
[1900]	valid_set's binary_logloss: 0.219975
[1950]	valid_set's binary_logloss: 0.219753
[2000]	valid_set's binary_logloss: 0.219638
[2050]	valid_set's binary_logloss: 0.219392
[2100]	valid_set's binary_logloss: 0.219236
[2150]	valid_set's binary_logloss: 0.219159
[2200]	valid_set's binary_logloss: 0.219024
[2250]	valid_set's binary_logloss: 0.218922
[2300]	valid_set's binary_logloss: 0.218777
[2350]	valid_set's binary_logloss: 0.218636
[2400]	valid_set's binary_logloss: 0.218492
[2450]	valid_set's binary_logloss: 0.218378
[2500]	valid_set's binary_logloss: 0.218357
[2550]	valid_set's binary_logloss: 0.218216
[2600]	valid_set's binary_logloss: 0.218135
[2650]	valid_set's binary_logloss: 0.218033
[2700]	valid_set's binary_logloss: 0.217873
[2750]	valid_set's binary_logloss: 0.217785
[2800]	valid_set's binary_logloss: 0.217727
[2850]	valid_set's binary_logloss: 0.217706
[2900]	valid_set's binary_logloss: 0.217634
[2950]	valid_set's binary_logloss: 0.217538
[3000]	valid_set's binary_logloss: 0.21749
[3050]	valid_set's binary_logloss: 0.217437
[3100]	valid_set's binary_logloss: 0.217403
[3150]	valid_set's binary_logloss: 0.217323
[3200]	valid_set's binary_logloss: 0.217253
[3250]	valid_set's binary_logloss: 0.217143
[3300]	valid_set's binary_logloss: 0.217171
[3350]	valid_set's binary_logloss: 0.21707
[3400]	valid_set's binary_logloss: 0.217114
[3450]	valid_set's binary_logloss: 0.217113
[3500]	valid_set's binary_logloss: 0.217095
[3550]	valid_set's binary_logloss: 0.21707
[3600]	valid_set's binary_logloss: 0.217064
[3650]	valid_set's binary_logloss: 0.217031
[3700]	valid_set's binary_logloss: 0.217069
[3750]	valid_set's binary_logloss: 0.217098
[3800]	valid_set's binary_logloss: 0.217068
[3850]	valid_set's binary_logloss: 0.217072
[3900]	valid_set's binary_logloss: 0.217067
[3950]	valid_set's binary_logloss: 0.217086
[4000]	valid_set's binary_logloss: 0.217064
[4050]	valid_set's binary_logloss: 0.216969
[4100]	valid_set's binary_logloss: 0.216911
[4150]	valid_set's binary_logloss: 0.216902
[4200]	valid_set's binary_logloss: 0.216912
[4250]	valid_set's binary_logloss: 0.216927
[4300]	valid_set's binary_logloss: 0.216896
[4350]	valid_set's binary_logloss: 0.216971
[4400]	valid_set's binary_logloss: 0.216979
[4450]	valid_set's binary_logloss: 0.21698
[4500]	valid_set's binary_logloss: 0.216987
[4550]	valid_set's binary_logloss: 0.217006
[4600]	valid_set's binary_logloss: 0.217046
[4650]	valid_set's binary_logloss: 0.217022
[4700]	valid_set's binary_logloss: 0.217041
[4750]	valid_set's binary_logloss: 0.217043
[4800]	valid_set's binary_logloss: 0.21706
[4850]	valid_set's binary_logloss: 0.217043
[4900]	valid_set's binary_logloss: 0.217029
[4950]	valid_set's binary_logloss: 0.217055
[5000]	valid_set's binary_logloss: 0.217107
[5050]	valid_set's binary_logloss: 0.217111
[5100]	valid_set's binary_logloss: 0.217105
[5150]	valid_set's binary_logloss: 0.217148
[5200]	valid_set's binary_logloss: 0.217115
[5250]	valid_set's binary_logloss: 0.217152
[5300]	valid_set's binary_logloss: 0.217182
[5350]	valid_set's binary_logloss: 0.217209
[5400]	valid_set's binary_logloss: 0.217257

Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBMLarge_BAG_L1\model.pkl
	0.9539	 = Validation score   (roc_auc)
	203.14s	 = Training   runtime
	12.68s	 = Validation runtime
	5326.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 32068.64s of the 32068.63s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403856	test: 0.6404649	best: 0.6404649 (0)	total: 89.6ms	remaining: 89.6ms
1:	learn: 0.5954054	test: 0.5955191	best: 0.5955191 (1)	total: 98.7ms	remaining: 0us
bestTest = 0.5955191341
bestIteration = 1
0:	learn: 0.6414591	test: 0.6415236	best: 0.6415236 (0)	total: 17.6ms	remaining: 1m 29s
20:	learn: 0.3366335	test: 0.3368725	best: 0.3368725 (20)	total: 402ms	remaining: 1m 36s
40:	learn: 0.3033546	test: 0.3036542	best: 0.3036542 (40)	total: 793ms	remaining: 1m 37s
60:	learn: 0.2900203	test: 0.2902176	best: 0.2902176 (60)	total: 1.19s	remaining: 1m 37s
80:	learn: 0.2812590	test: 0.2809011	best: 0.2809011 (80)	total: 1.57s	remaining: 1m 37s
100:	learn: 0.2749282	test: 0.2741805	best: 0.2741805 (100)	total: 1.95s	remaining: 1m 35s
120:	learn: 0.2704434	test: 0.2695925	best: 0.2695925 (120)	total: 2.33s	remaining: 1m 35s
140:	learn: 0.2664360	test: 0.2654167	best: 0.2654167 (140)	total: 2.71s	remaining: 1m 34s
160:	learn: 0.2628198	test: 0.2617223	best: 0.2617223 (160)	total: 3.06s	remaining: 1m 33s
180:	learn: 0.2595945	test: 0.2584427	best: 0.2584427 (180)	total: 3.43s	remaining: 1m 32s
200:	learn: 0.2566880	test: 0.2555059	best: 0.2555059 (200)	total: 3.8s	remaining: 1m 32s
220:	learn: 0.2542193	test: 0.2529820	best: 0.2529820 (220)	total: 4.16s	remaining: 1m 31s
240:	learn: 0.2521521	test: 0.2508658	best: 0.2508658 (240)	total: 4.54s	remaining: 1m 31s
260:	learn: 0.2504545	test: 0.2490917	best: 0.2490917 (260)	total: 4.91s	remaining: 1m 30s
280:	learn: 0.2488322	test: 0.2475688	best: 0.2475688 (280)	total: 5.28s	remaining: 1m 30s
300:	learn: 0.2473725	test: 0.2461015	best: 0.2461015 (300)	total: 5.63s	remaining: 1m 29s
320:	learn: 0.2458677	test: 0.2446080	best: 0.2446080 (320)	total: 6s	remaining: 1m 28s
340:	learn: 0.2443810	test: 0.2430417	best: 0.2430417 (340)	total: 6.36s	remaining: 1m 28s
360:	learn: 0.2429912	test: 0.2416829	best: 0.2416829 (360)	total: 6.73s	remaining: 1m 27s
380:	learn: 0.2420068	test: 0.2407684	best: 0.2407684 (380)	total: 7.09s	remaining: 1m 27s
400:	learn: 0.2407390	test: 0.2395276	best: 0.2395276 (400)	total: 7.47s	remaining: 1m 27s
420:	learn: 0.2394707	test: 0.2382765	best: 0.2382765 (420)	total: 7.84s	remaining: 1m 26s
440:	learn: 0.2384186	test: 0.2373285	best: 0.2373285 (440)	total: 8.21s	remaining: 1m 26s
460:	learn: 0.2374258	test: 0.2363911	best: 0.2363911 (460)	total: 8.57s	remaining: 1m 25s
480:	learn: 0.2364840	test: 0.2355402	best: 0.2355402 (480)	total: 8.94s	remaining: 1m 25s
500:	learn: 0.2356372	test: 0.2347829	best: 0.2347829 (500)	total: 9.29s	remaining: 1m 24s
520:	learn: 0.2347409	test: 0.2339883	best: 0.2339883 (520)	total: 9.67s	remaining: 1m 24s
540:	learn: 0.2339590	test: 0.2333219	best: 0.2333219 (540)	total: 10s	remaining: 1m 24s
560:	learn: 0.2332403	test: 0.2327297	best: 0.2327297 (560)	total: 10.4s	remaining: 1m 23s
580:	learn: 0.2324654	test: 0.2319240	best: 0.2319240 (580)	total: 10.8s	remaining: 1m 23s
600:	learn: 0.2318135	test: 0.2313785	best: 0.2313785 (600)	total: 11.1s	remaining: 1m 23s
620:	learn: 0.2310316	test: 0.2306987	best: 0.2306987 (620)	total: 11.5s	remaining: 1m 22s
640:	learn: 0.2302455	test: 0.2300190	best: 0.2300190 (640)	total: 11.9s	remaining: 1m 22s
660:	learn: 0.2296756	test: 0.2295441	best: 0.2295441 (660)	total: 12.3s	remaining: 1m 21s
680:	learn: 0.2291275	test: 0.2290614	best: 0.2290614 (680)	total: 12.6s	remaining: 1m 21s
700:	learn: 0.2285589	test: 0.2286320	best: 0.2286320 (700)	total: 13s	remaining: 1m 21s
720:	learn: 0.2279251	test: 0.2281333	best: 0.2281333 (720)	total: 13.4s	remaining: 1m 20s
740:	learn: 0.2272828	test: 0.2275488	best: 0.2275488 (740)	total: 13.7s	remaining: 1m 20s
760:	learn: 0.2267914	test: 0.2271240	best: 0.2271240 (760)	total: 14.1s	remaining: 1m 19s
780:	learn: 0.2262298	test: 0.2266450	best: 0.2266450 (780)	total: 14.5s	remaining: 1m 19s
800:	learn: 0.2257217	test: 0.2262569	best: 0.2262569 (800)	total: 14.8s	remaining: 1m 19s
820:	learn: 0.2251330	test: 0.2257483	best: 0.2257483 (820)	total: 15.2s	remaining: 1m 18s
840:	learn: 0.2245772	test: 0.2253116	best: 0.2253116 (840)	total: 15.6s	remaining: 1m 18s
860:	learn: 0.2241042	test: 0.2249537	best: 0.2249537 (860)	total: 15.9s	remaining: 1m 18s
880:	learn: 0.2236801	test: 0.2246692	best: 0.2246692 (880)	total: 16.3s	remaining: 1m 17s
900:	learn: 0.2232527	test: 0.2243469	best: 0.2243469 (900)	total: 16.6s	remaining: 1m 17s
920:	learn: 0.2228526	test: 0.2240463	best: 0.2240463 (920)	total: 17s	remaining: 1m 16s
940:	learn: 0.2224694	test: 0.2237475	best: 0.2237475 (940)	total: 17.4s	remaining: 1m 16s
960:	learn: 0.2221510	test: 0.2235107	best: 0.2235107 (960)	total: 17.7s	remaining: 1m 16s
980:	learn: 0.2217878	test: 0.2232448	best: 0.2232448 (980)	total: 18.1s	remaining: 1m 15s
1000:	learn: 0.2214021	test: 0.2229456	best: 0.2229456 (1000)	total: 18.5s	remaining: 1m 15s
1020:	learn: 0.2209890	test: 0.2226241	best: 0.2226241 (1020)	total: 18.8s	remaining: 1m 14s
1040:	learn: 0.2206671	test: 0.2224013	best: 0.2224013 (1040)	total: 19.2s	remaining: 1m 14s
1060:	learn: 0.2203508	test: 0.2221915	best: 0.2221915 (1060)	total: 19.6s	remaining: 1m 14s
1080:	learn: 0.2200288	test: 0.2219629	best: 0.2219629 (1080)	total: 19.9s	remaining: 1m 13s
1100:	learn: 0.2196950	test: 0.2217353	best: 0.2217353 (1100)	total: 20.3s	remaining: 1m 13s
1120:	learn: 0.2193895	test: 0.2215248	best: 0.2215248 (1120)	total: 20.6s	remaining: 1m 12s
1140:	learn: 0.2190247	test: 0.2212763	best: 0.2212763 (1140)	total: 21s	remaining: 1m 12s
1160:	learn: 0.2186749	test: 0.2209842	best: 0.2209842 (1160)	total: 21.4s	remaining: 1m 12s
1180:	learn: 0.2183299	test: 0.2207423	best: 0.2207423 (1180)	total: 21.7s	remaining: 1m 11s
1200:	learn: 0.2180059	test: 0.2205206	best: 0.2205206 (1200)	total: 22.1s	remaining: 1m 11s
1220:	learn: 0.2176902	test: 0.2203253	best: 0.2203253 (1220)	total: 22.4s	remaining: 1m 10s
1240:	learn: 0.2173761	test: 0.2201554	best: 0.2201554 (1240)	total: 22.8s	remaining: 1m 10s
1260:	learn: 0.2170075	test: 0.2198634	best: 0.2198634 (1260)	total: 23.1s	remaining: 1m 10s
1280:	learn: 0.2167393	test: 0.2196989	best: 0.2196989 (1280)	total: 23.5s	remaining: 1m 9s
1300:	learn: 0.2164675	test: 0.2195368	best: 0.2195368 (1300)	total: 23.9s	remaining: 1m 9s
1320:	learn: 0.2161672	test: 0.2193512	best: 0.2193512 (1320)	total: 24.2s	remaining: 1m 8s
1340:	learn: 0.2158493	test: 0.2191143	best: 0.2191143 (1340)	total: 24.6s	remaining: 1m 8s
1360:	learn: 0.2155898	test: 0.2189235	best: 0.2189235 (1360)	total: 24.9s	remaining: 1m 8s
1380:	learn: 0.2153308	test: 0.2187531	best: 0.2187531 (1380)	total: 25.3s	remaining: 1m 7s
1400:	learn: 0.2150240	test: 0.2185210	best: 0.2185210 (1400)	total: 25.6s	remaining: 1m 7s
1420:	learn: 0.2147771	test: 0.2183964	best: 0.2183964 (1420)	total: 26s	remaining: 1m 6s
1440:	learn: 0.2145090	test: 0.2182087	best: 0.2182087 (1440)	total: 26.3s	remaining: 1m 6s
1460:	learn: 0.2143004	test: 0.2181127	best: 0.2181127 (1460)	total: 26.7s	remaining: 1m 6s
1480:	learn: 0.2140277	test: 0.2179316	best: 0.2179276 (1479)	total: 27.1s	remaining: 1m 5s
1500:	learn: 0.2138042	test: 0.2177925	best: 0.2177925 (1500)	total: 27.4s	remaining: 1m 5s
1520:	learn: 0.2135758	test: 0.2176353	best: 0.2176353 (1520)	total: 27.8s	remaining: 1m 4s
1540:	learn: 0.2133201	test: 0.2174802	best: 0.2174802 (1540)	total: 28.1s	remaining: 1m 4s
1560:	learn: 0.2130864	test: 0.2173230	best: 0.2173230 (1560)	total: 28.5s	remaining: 1m 4s
1580:	learn: 0.2128820	test: 0.2171969	best: 0.2171969 (1580)	total: 28.8s	remaining: 1m 3s
1600:	learn: 0.2127046	test: 0.2171019	best: 0.2171019 (1600)	total: 29.2s	remaining: 1m 3s
1620:	learn: 0.2124928	test: 0.2169892	best: 0.2169892 (1620)	total: 29.6s	remaining: 1m 3s
1640:	learn: 0.2122925	test: 0.2168741	best: 0.2168741 (1640)	total: 29.9s	remaining: 1m 2s
1660:	learn: 0.2120887	test: 0.2167863	best: 0.2167863 (1660)	total: 30.3s	remaining: 1m 2s
1680:	learn: 0.2118764	test: 0.2166871	best: 0.2166871 (1680)	total: 30.6s	remaining: 1m 1s
1700:	learn: 0.2116021	test: 0.2165063	best: 0.2165063 (1700)	total: 31s	remaining: 1m 1s
1720:	learn: 0.2114220	test: 0.2164169	best: 0.2164169 (1720)	total: 31.4s	remaining: 1m 1s
1740:	learn: 0.2112278	test: 0.2163247	best: 0.2163247 (1740)	total: 31.7s	remaining: 1m
1760:	learn: 0.2110142	test: 0.2162364	best: 0.2162364 (1760)	total: 32.1s	remaining: 1m
1780:	learn: 0.2108022	test: 0.2161228	best: 0.2161228 (1780)	total: 32.4s	remaining: 1m
1800:	learn: 0.2106206	test: 0.2160569	best: 0.2160569 (1800)	total: 32.8s	remaining: 59.7s
1820:	learn: 0.2103743	test: 0.2158860	best: 0.2158860 (1820)	total: 33.1s	remaining: 59.3s
1840:	learn: 0.2101814	test: 0.2158071	best: 0.2158063 (1838)	total: 33.5s	remaining: 58.9s
1860:	learn: 0.2099536	test: 0.2156964	best: 0.2156964 (1860)	total: 33.8s	remaining: 58.6s
1880:	learn: 0.2097730	test: 0.2156162	best: 0.2156162 (1880)	total: 34.2s	remaining: 58.2s
1900:	learn: 0.2095597	test: 0.2154839	best: 0.2154839 (1900)	total: 34.6s	remaining: 57.8s
1920:	learn: 0.2093518	test: 0.2153612	best: 0.2153551 (1919)	total: 34.9s	remaining: 57.5s
1940:	learn: 0.2091597	test: 0.2152677	best: 0.2152663 (1939)	total: 35.3s	remaining: 57.1s
1960:	learn: 0.2089698	test: 0.2151556	best: 0.2151556 (1960)	total: 35.7s	remaining: 56.7s
1980:	learn: 0.2087320	test: 0.2150021	best: 0.2150021 (1980)	total: 36s	remaining: 56.4s
2000:	learn: 0.2085428	test: 0.2149292	best: 0.2149292 (2000)	total: 36.4s	remaining: 56s
2020:	learn: 0.2083103	test: 0.2147933	best: 0.2147933 (2020)	total: 36.7s	remaining: 55.6s
2040:	learn: 0.2081654	test: 0.2147369	best: 0.2147354 (2038)	total: 37.1s	remaining: 55.3s
2060:	learn: 0.2079975	test: 0.2146667	best: 0.2146667 (2060)	total: 37.5s	remaining: 54.9s
2080:	learn: 0.2078333	test: 0.2145723	best: 0.2145723 (2080)	total: 37.8s	remaining: 54.5s
2100:	learn: 0.2076153	test: 0.2144617	best: 0.2144617 (2100)	total: 38.2s	remaining: 54.2s
2120:	learn: 0.2074415	test: 0.2143794	best: 0.2143794 (2120)	total: 38.6s	remaining: 53.8s
2140:	learn: 0.2071827	test: 0.2142223	best: 0.2142223 (2140)	total: 38.9s	remaining: 53.5s
2160:	learn: 0.2069984	test: 0.2141155	best: 0.2141142 (2159)	total: 39.3s	remaining: 53.1s
2180:	learn: 0.2068300	test: 0.2140498	best: 0.2140498 (2180)	total: 39.6s	remaining: 52.7s
2200:	learn: 0.2066791	test: 0.2140064	best: 0.2140064 (2200)	total: 40s	remaining: 52.3s
2220:	learn: 0.2065166	test: 0.2139416	best: 0.2139408 (2217)	total: 40.4s	remaining: 52s
2240:	learn: 0.2063562	test: 0.2138953	best: 0.2138953 (2240)	total: 40.7s	remaining: 51.6s
2260:	learn: 0.2061504	test: 0.2138044	best: 0.2138039 (2259)	total: 41.1s	remaining: 51.3s
2280:	learn: 0.2059775	test: 0.2137289	best: 0.2137289 (2280)	total: 41.4s	remaining: 50.9s
2300:	learn: 0.2058181	test: 0.2136717	best: 0.2136717 (2300)	total: 41.8s	remaining: 50.5s
2320:	learn: 0.2056138	test: 0.2135393	best: 0.2135377 (2318)	total: 42.2s	remaining: 50.2s
2340:	learn: 0.2054538	test: 0.2134772	best: 0.2134761 (2339)	total: 42.6s	remaining: 49.8s
2360:	learn: 0.2052863	test: 0.2134160	best: 0.2134160 (2360)	total: 42.9s	remaining: 49.4s
2380:	learn: 0.2050915	test: 0.2133233	best: 0.2133233 (2380)	total: 43.3s	remaining: 49.1s
2400:	learn: 0.2048985	test: 0.2132094	best: 0.2132094 (2400)	total: 43.6s	remaining: 48.7s
2420:	learn: 0.2047373	test: 0.2131376	best: 0.2131376 (2420)	total: 44s	remaining: 48.3s
2440:	learn: 0.2045858	test: 0.2130745	best: 0.2130745 (2440)	total: 44.4s	remaining: 48s
2460:	learn: 0.2044174	test: 0.2130103	best: 0.2130062 (2458)	total: 44.7s	remaining: 47.6s
2480:	learn: 0.2042079	test: 0.2128941	best: 0.2128941 (2477)	total: 45.1s	remaining: 47.3s
2500:	learn: 0.2040774	test: 0.2128417	best: 0.2128417 (2500)	total: 45.5s	remaining: 46.9s
2520:	learn: 0.2039377	test: 0.2127876	best: 0.2127876 (2520)	total: 45.8s	remaining: 46.5s
2540:	learn: 0.2037184	test: 0.2126721	best: 0.2126709 (2537)	total: 46.2s	remaining: 46.2s
2560:	learn: 0.2035595	test: 0.2125936	best: 0.2125936 (2560)	total: 46.6s	remaining: 45.8s
2580:	learn: 0.2033936	test: 0.2125309	best: 0.2125309 (2580)	total: 46.9s	remaining: 45.4s
2600:	learn: 0.2032320	test: 0.2124604	best: 0.2124604 (2600)	total: 47.3s	remaining: 45.1s
2620:	learn: 0.2030623	test: 0.2123538	best: 0.2123538 (2620)	total: 47.6s	remaining: 44.7s
2640:	learn: 0.2029238	test: 0.2122922	best: 0.2122922 (2640)	total: 48s	remaining: 44.3s
2660:	learn: 0.2027784	test: 0.2122323	best: 0.2122323 (2660)	total: 48.4s	remaining: 44s
2680:	learn: 0.2026166	test: 0.2121569	best: 0.2121569 (2680)	total: 48.7s	remaining: 43.6s
2700:	learn: 0.2024361	test: 0.2120499	best: 0.2120499 (2700)	total: 49.1s	remaining: 43.3s
2720:	learn: 0.2023034	test: 0.2119925	best: 0.2119911 (2719)	total: 49.5s	remaining: 42.9s
2740:	learn: 0.2021355	test: 0.2119231	best: 0.2119215 (2739)	total: 49.8s	remaining: 42.5s
2760:	learn: 0.2020037	test: 0.2118916	best: 0.2118910 (2759)	total: 50.2s	remaining: 42.2s
2780:	learn: 0.2018822	test: 0.2118579	best: 0.2118579 (2780)	total: 50.5s	remaining: 41.8s
2800:	learn: 0.2016950	test: 0.2117300	best: 0.2117300 (2800)	total: 50.9s	remaining: 41.5s
2820:	learn: 0.2015459	test: 0.2116727	best: 0.2116727 (2820)	total: 51.3s	remaining: 41.1s
2840:	learn: 0.2014117	test: 0.2116037	best: 0.2116037 (2840)	total: 51.7s	remaining: 40.7s
2860:	learn: 0.2012802	test: 0.2115391	best: 0.2115391 (2860)	total: 52s	remaining: 40.4s
2880:	learn: 0.2011374	test: 0.2114949	best: 0.2114949 (2880)	total: 52.4s	remaining: 40s
2900:	learn: 0.2009903	test: 0.2114460	best: 0.2114460 (2900)	total: 52.8s	remaining: 39.7s
2920:	learn: 0.2008248	test: 0.2114010	best: 0.2114010 (2920)	total: 53.1s	remaining: 39.3s
2940:	learn: 0.2006812	test: 0.2113234	best: 0.2113234 (2940)	total: 53.5s	remaining: 38.9s
2960:	learn: 0.2005423	test: 0.2112716	best: 0.2112716 (2960)	total: 53.9s	remaining: 38.6s
2980:	learn: 0.2004078	test: 0.2112136	best: 0.2112125 (2979)	total: 54.3s	remaining: 38.2s
3000:	learn: 0.2002585	test: 0.2111487	best: 0.2111487 (3000)	total: 54.6s	remaining: 37.9s
3020:	learn: 0.2001154	test: 0.2111112	best: 0.2111112 (3020)	total: 55s	remaining: 37.5s
3040:	learn: 0.1999813	test: 0.2110618	best: 0.2110618 (3040)	total: 55.4s	remaining: 37.1s
3060:	learn: 0.1998726	test: 0.2110292	best: 0.2110292 (3060)	total: 55.7s	remaining: 36.8s
3080:	learn: 0.1996928	test: 0.2109269	best: 0.2109265 (3077)	total: 56.1s	remaining: 36.4s
3100:	learn: 0.1995521	test: 0.2108703	best: 0.2108697 (3099)	total: 56.5s	remaining: 36s
3120:	learn: 0.1994040	test: 0.2108151	best: 0.2108114 (3113)	total: 56.8s	remaining: 35.7s
3140:	learn: 0.1992711	test: 0.2107693	best: 0.2107693 (3140)	total: 57.2s	remaining: 35.3s
3160:	learn: 0.1991284	test: 0.2107079	best: 0.2107079 (3160)	total: 57.6s	remaining: 35s
3180:	learn: 0.1990033	test: 0.2106800	best: 0.2106800 (3180)	total: 57.9s	remaining: 34.6s
3200:	learn: 0.1988676	test: 0.2106227	best: 0.2106227 (3200)	total: 58.3s	remaining: 34.2s
3220:	learn: 0.1987071	test: 0.2105155	best: 0.2105155 (3220)	total: 58.7s	remaining: 33.9s
3240:	learn: 0.1985662	test: 0.2104633	best: 0.2104633 (3240)	total: 59s	remaining: 33.5s
3260:	learn: 0.1984347	test: 0.2104205	best: 0.2104205 (3260)	total: 59.4s	remaining: 33.2s
3280:	learn: 0.1982927	test: 0.2103601	best: 0.2103601 (3280)	total: 59.8s	remaining: 32.8s
3300:	learn: 0.1981664	test: 0.2103160	best: 0.2103136 (3298)	total: 1m	remaining: 32.4s
3320:	learn: 0.1979801	test: 0.2102034	best: 0.2102016 (3319)	total: 1m	remaining: 32.1s
3340:	learn: 0.1978441	test: 0.2101231	best: 0.2101231 (3340)	total: 1m	remaining: 31.7s
3360:	learn: 0.1977219	test: 0.2100866	best: 0.2100866 (3360)	total: 1m 1s	remaining: 31.3s
3380:	learn: 0.1975949	test: 0.2100577	best: 0.2100577 (3380)	total: 1m 1s	remaining: 31s
3400:	learn: 0.1974668	test: 0.2100205	best: 0.2100205 (3400)	total: 1m 1s	remaining: 30.6s
3420:	learn: 0.1973409	test: 0.2099910	best: 0.2099910 (3420)	total: 1m 2s	remaining: 30.3s
3440:	learn: 0.1972285	test: 0.2099727	best: 0.2099718 (3434)	total: 1m 2s	remaining: 29.9s
3460:	learn: 0.1971065	test: 0.2099225	best: 0.2099225 (3460)	total: 1m 3s	remaining: 29.5s
3480:	learn: 0.1970012	test: 0.2098868	best: 0.2098857 (3479)	total: 1m 3s	remaining: 29.2s
3500:	learn: 0.1968943	test: 0.2098711	best: 0.2098699 (3498)	total: 1m 3s	remaining: 28.8s
3520:	learn: 0.1967629	test: 0.2098244	best: 0.2098244 (3520)	total: 1m 4s	remaining: 28.5s
3540:	learn: 0.1966417	test: 0.2097822	best: 0.2097820 (3538)	total: 1m 4s	remaining: 28.1s
3560:	learn: 0.1965259	test: 0.2097257	best: 0.2097257 (3560)	total: 1m 4s	remaining: 27.7s
3580:	learn: 0.1964206	test: 0.2096936	best: 0.2096935 (3579)	total: 1m 5s	remaining: 27.4s
3600:	learn: 0.1963134	test: 0.2096618	best: 0.2096607 (3599)	total: 1m 5s	remaining: 27s
3620:	learn: 0.1961916	test: 0.2096284	best: 0.2096284 (3620)	total: 1m 6s	remaining: 26.6s
3640:	learn: 0.1960615	test: 0.2095705	best: 0.2095681 (3638)	total: 1m 6s	remaining: 26.3s
3660:	learn: 0.1959293	test: 0.2095098	best: 0.2095098 (3660)	total: 1m 6s	remaining: 25.9s
3680:	learn: 0.1958159	test: 0.2094903	best: 0.2094863 (3671)	total: 1m 7s	remaining: 25.6s
3700:	learn: 0.1956993	test: 0.2094672	best: 0.2094646 (3695)	total: 1m 7s	remaining: 25.2s
3720:	learn: 0.1955711	test: 0.2094235	best: 0.2094235 (3720)	total: 1m 8s	remaining: 24.9s
3740:	learn: 0.1954360	test: 0.2093749	best: 0.2093740 (3737)	total: 1m 8s	remaining: 24.5s
3760:	learn: 0.1952937	test: 0.2093196	best: 0.2093196 (3760)	total: 1m 8s	remaining: 24.2s
3780:	learn: 0.1951624	test: 0.2092629	best: 0.2092590 (3778)	total: 1m 9s	remaining: 23.8s
3800:	learn: 0.1950453	test: 0.2092336	best: 0.2092334 (3799)	total: 1m 9s	remaining: 23.5s
3820:	learn: 0.1949407	test: 0.2092004	best: 0.2092004 (3820)	total: 1m 10s	remaining: 23.1s
3840:	learn: 0.1948128	test: 0.2091719	best: 0.2091719 (3840)	total: 1m 10s	remaining: 22.7s
3860:	learn: 0.1946813	test: 0.2091182	best: 0.2091160 (3859)	total: 1m 10s	remaining: 22.4s
3880:	learn: 0.1945556	test: 0.2090511	best: 0.2090511 (3880)	total: 1m 11s	remaining: 22s
3900:	learn: 0.1944283	test: 0.2090212	best: 0.2090167 (3891)	total: 1m 11s	remaining: 21.7s
3920:	learn: 0.1943154	test: 0.2090003	best: 0.2089960 (3918)	total: 1m 11s	remaining: 21.3s
3940:	learn: 0.1942036	test: 0.2089573	best: 0.2089569 (3939)	total: 1m 12s	remaining: 20.9s
3960:	learn: 0.1940835	test: 0.2089280	best: 0.2089280 (3960)	total: 1m 12s	remaining: 20.6s
3980:	learn: 0.1939813	test: 0.2089050	best: 0.2089018 (3977)	total: 1m 13s	remaining: 20.2s
4000:	learn: 0.1938547	test: 0.2088647	best: 0.2088647 (4000)	total: 1m 13s	remaining: 19.8s
4020:	learn: 0.1937498	test: 0.2088412	best: 0.2088412 (4020)	total: 1m 13s	remaining: 19.5s
4040:	learn: 0.1936377	test: 0.2088027	best: 0.2088027 (4040)	total: 1m 14s	remaining: 19.1s
4060:	learn: 0.1935224	test: 0.2087602	best: 0.2087602 (4060)	total: 1m 14s	remaining: 18.8s
4080:	learn: 0.1934109	test: 0.2087164	best: 0.2087164 (4080)	total: 1m 15s	remaining: 18.4s
4100:	learn: 0.1933004	test: 0.2086862	best: 0.2086862 (4100)	total: 1m 15s	remaining: 18s
4120:	learn: 0.1931723	test: 0.2086540	best: 0.2086529 (4119)	total: 1m 15s	remaining: 17.7s
4140:	learn: 0.1930511	test: 0.2086215	best: 0.2086215 (4140)	total: 1m 16s	remaining: 17.3s
4160:	learn: 0.1929392	test: 0.2085982	best: 0.2085927 (4158)	total: 1m 16s	remaining: 16.9s
4180:	learn: 0.1928241	test: 0.2085566	best: 0.2085566 (4180)	total: 1m 16s	remaining: 16.6s
4200:	learn: 0.1927136	test: 0.2084974	best: 0.2084974 (4200)	total: 1m 17s	remaining: 16.2s
4220:	learn: 0.1925982	test: 0.2084538	best: 0.2084538 (4220)	total: 1m 17s	remaining: 15.8s
4240:	learn: 0.1924963	test: 0.2084326	best: 0.2084326 (4240)	total: 1m 18s	remaining: 15.5s
4260:	learn: 0.1923922	test: 0.2084007	best: 0.2084007 (4260)	total: 1m 18s	remaining: 15.1s
4280:	learn: 0.1922925	test: 0.2083778	best: 0.2083762 (4279)	total: 1m 18s	remaining: 14.7s
4300:	learn: 0.1921822	test: 0.2083294	best: 0.2083283 (4299)	total: 1m 19s	remaining: 14.4s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403320	test: 0.6405436	best: 0.6405436 (0)	total: 9.22ms	remaining: 9.22ms
1:	learn: 0.5953287	test: 0.5957294	best: 0.5957294 (1)	total: 18.5ms	remaining: 0us
bestTest = 0.5957293764
bestIteration = 1
0:	learn: 0.6411247	test: 0.6412663	best: 0.6412663 (0)	total: 18.1ms	remaining: 1m 34s
20:	learn: 0.3363466	test: 0.3378839	best: 0.3378839 (20)	total: 430ms	remaining: 1m 46s
40:	learn: 0.3030904	test: 0.3050609	best: 0.3050609 (40)	total: 816ms	remaining: 1m 43s
60:	learn: 0.2881474	test: 0.2899113	best: 0.2899113 (60)	total: 1.22s	remaining: 1m 43s
80:	learn: 0.2809843	test: 0.2825871	best: 0.2825871 (80)	total: 1.6s	remaining: 1m 41s
100:	learn: 0.2754117	test: 0.2770441	best: 0.2770441 (100)	total: 1.97s	remaining: 1m 39s
120:	learn: 0.2706144	test: 0.2722527	best: 0.2722527 (120)	total: 2.33s	remaining: 1m 38s
140:	learn: 0.2665566	test: 0.2681486	best: 0.2681486 (140)	total: 2.7s	remaining: 1m 37s
160:	learn: 0.2623209	test: 0.2639514	best: 0.2639514 (160)	total: 3.07s	remaining: 1m 36s
180:	learn: 0.2595153	test: 0.2610481	best: 0.2610481 (180)	total: 3.45s	remaining: 1m 36s
200:	learn: 0.2565856	test: 0.2580562	best: 0.2580562 (200)	total: 3.83s	remaining: 1m 35s
220:	learn: 0.2540916	test: 0.2555505	best: 0.2555505 (220)	total: 4.2s	remaining: 1m 34s
240:	learn: 0.2520542	test: 0.2535147	best: 0.2535147 (240)	total: 4.58s	remaining: 1m 34s
260:	learn: 0.2496515	test: 0.2510294	best: 0.2510294 (260)	total: 4.96s	remaining: 1m 34s
280:	learn: 0.2482141	test: 0.2495808	best: 0.2495808 (280)	total: 5.31s	remaining: 1m 33s
300:	learn: 0.2462904	test: 0.2476386	best: 0.2476386 (300)	total: 5.67s	remaining: 1m 32s
320:	learn: 0.2446988	test: 0.2460319	best: 0.2460319 (320)	total: 6.04s	remaining: 1m 32s
340:	learn: 0.2434528	test: 0.2447785	best: 0.2447785 (340)	total: 6.4s	remaining: 1m 31s
360:	learn: 0.2422840	test: 0.2437203	best: 0.2437203 (360)	total: 6.77s	remaining: 1m 31s
380:	learn: 0.2411287	test: 0.2425774	best: 0.2425774 (380)	total: 7.14s	remaining: 1m 30s
400:	learn: 0.2400720	test: 0.2415925	best: 0.2415925 (400)	total: 7.51s	remaining: 1m 30s
420:	learn: 0.2391411	test: 0.2407190	best: 0.2407190 (420)	total: 7.88s	remaining: 1m 29s
440:	learn: 0.2379028	test: 0.2395010	best: 0.2395010 (440)	total: 8.25s	remaining: 1m 29s
460:	learn: 0.2368761	test: 0.2385109	best: 0.2385109 (460)	total: 8.62s	remaining: 1m 28s
480:	learn: 0.2357517	test: 0.2374384	best: 0.2374384 (480)	total: 8.99s	remaining: 1m 28s
500:	learn: 0.2346994	test: 0.2364343	best: 0.2364343 (500)	total: 9.37s	remaining: 1m 28s
520:	learn: 0.2337651	test: 0.2355698	best: 0.2355698 (520)	total: 9.73s	remaining: 1m 27s
540:	learn: 0.2329262	test: 0.2348258	best: 0.2348258 (540)	total: 10.1s	remaining: 1m 27s
560:	learn: 0.2320784	test: 0.2340703	best: 0.2340703 (560)	total: 10.4s	remaining: 1m 26s
580:	learn: 0.2313312	test: 0.2333997	best: 0.2333997 (580)	total: 10.8s	remaining: 1m 26s
600:	learn: 0.2306939	test: 0.2328413	best: 0.2328413 (600)	total: 11.2s	remaining: 1m 25s
620:	learn: 0.2299703	test: 0.2322281	best: 0.2322281 (620)	total: 11.5s	remaining: 1m 25s
640:	learn: 0.2293382	test: 0.2316463	best: 0.2316463 (640)	total: 11.9s	remaining: 1m 24s
660:	learn: 0.2287733	test: 0.2311892	best: 0.2311892 (660)	total: 12.2s	remaining: 1m 24s
680:	learn: 0.2282053	test: 0.2307064	best: 0.2307064 (680)	total: 12.6s	remaining: 1m 23s
700:	learn: 0.2276403	test: 0.2302454	best: 0.2302454 (700)	total: 12.9s	remaining: 1m 23s
720:	learn: 0.2271867	test: 0.2299293	best: 0.2299293 (720)	total: 13.3s	remaining: 1m 22s
740:	learn: 0.2265046	test: 0.2293470	best: 0.2293470 (740)	total: 13.7s	remaining: 1m 22s
760:	learn: 0.2259743	test: 0.2289540	best: 0.2289540 (760)	total: 14s	remaining: 1m 22s
780:	learn: 0.2254949	test: 0.2285724	best: 0.2285724 (780)	total: 14.4s	remaining: 1m 21s
800:	learn: 0.2250026	test: 0.2281625	best: 0.2281625 (800)	total: 14.7s	remaining: 1m 21s
820:	learn: 0.2245100	test: 0.2277821	best: 0.2277821 (820)	total: 15.1s	remaining: 1m 20s
840:	learn: 0.2240705	test: 0.2274041	best: 0.2274041 (840)	total: 15.4s	remaining: 1m 20s
860:	learn: 0.2235510	test: 0.2269395	best: 0.2269395 (860)	total: 15.8s	remaining: 1m 19s
880:	learn: 0.2231588	test: 0.2266547	best: 0.2266547 (880)	total: 16.2s	remaining: 1m 19s
900:	learn: 0.2227533	test: 0.2263609	best: 0.2263609 (900)	total: 16.5s	remaining: 1m 19s
920:	learn: 0.2223562	test: 0.2260810	best: 0.2260810 (920)	total: 16.9s	remaining: 1m 18s
940:	learn: 0.2220264	test: 0.2258338	best: 0.2258338 (940)	total: 17.2s	remaining: 1m 18s
960:	learn: 0.2216190	test: 0.2255263	best: 0.2255263 (960)	total: 17.6s	remaining: 1m 17s
980:	learn: 0.2211389	test: 0.2251028	best: 0.2251028 (980)	total: 17.9s	remaining: 1m 17s
1000:	learn: 0.2206852	test: 0.2247289	best: 0.2247289 (1000)	total: 18.3s	remaining: 1m 17s
1020:	learn: 0.2203397	test: 0.2244394	best: 0.2244394 (1020)	total: 18.6s	remaining: 1m 16s
1040:	learn: 0.2199782	test: 0.2241856	best: 0.2241856 (1040)	total: 19s	remaining: 1m 16s
1060:	learn: 0.2196618	test: 0.2239401	best: 0.2239401 (1060)	total: 19.4s	remaining: 1m 15s
1080:	learn: 0.2194086	test: 0.2237445	best: 0.2237445 (1080)	total: 19.7s	remaining: 1m 15s
1100:	learn: 0.2189855	test: 0.2233958	best: 0.2233958 (1100)	total: 20.1s	remaining: 1m 15s
1120:	learn: 0.2186647	test: 0.2231329	best: 0.2231329 (1120)	total: 20.4s	remaining: 1m 14s
1140:	learn: 0.2183488	test: 0.2228881	best: 0.2228881 (1140)	total: 20.8s	remaining: 1m 14s
1160:	learn: 0.2180108	test: 0.2226436	best: 0.2226436 (1160)	total: 21.2s	remaining: 1m 13s
1180:	learn: 0.2176973	test: 0.2224031	best: 0.2224031 (1180)	total: 21.5s	remaining: 1m 13s
1200:	learn: 0.2173541	test: 0.2221643	best: 0.2221643 (1200)	total: 21.9s	remaining: 1m 13s
1220:	learn: 0.2170961	test: 0.2220025	best: 0.2220014 (1219)	total: 22.2s	remaining: 1m 12s
1240:	learn: 0.2168548	test: 0.2218280	best: 0.2218280 (1240)	total: 22.6s	remaining: 1m 12s
1260:	learn: 0.2165554	test: 0.2216140	best: 0.2216140 (1260)	total: 23s	remaining: 1m 12s
1280:	learn: 0.2162649	test: 0.2214182	best: 0.2214182 (1280)	total: 23.3s	remaining: 1m 11s
1300:	learn: 0.2159546	test: 0.2212333	best: 0.2212333 (1300)	total: 23.7s	remaining: 1m 11s
1320:	learn: 0.2157242	test: 0.2210970	best: 0.2210970 (1320)	total: 24s	remaining: 1m 10s
1340:	learn: 0.2153710	test: 0.2208198	best: 0.2208198 (1340)	total: 24.4s	remaining: 1m 10s
1360:	learn: 0.2150882	test: 0.2206447	best: 0.2206447 (1360)	total: 24.8s	remaining: 1m 10s
1380:	learn: 0.2148421	test: 0.2205028	best: 0.2205028 (1380)	total: 25.1s	remaining: 1m 9s
1400:	learn: 0.2145838	test: 0.2203413	best: 0.2203413 (1400)	total: 25.5s	remaining: 1m 9s
1420:	learn: 0.2143271	test: 0.2201929	best: 0.2201929 (1420)	total: 25.8s	remaining: 1m 9s
1440:	learn: 0.2140852	test: 0.2200113	best: 0.2200113 (1440)	total: 26.2s	remaining: 1m 8s
1460:	learn: 0.2138256	test: 0.2198348	best: 0.2198348 (1460)	total: 26.6s	remaining: 1m 8s
1480:	learn: 0.2136014	test: 0.2197080	best: 0.2197080 (1480)	total: 26.9s	remaining: 1m 7s
1500:	learn: 0.2133455	test: 0.2195519	best: 0.2195519 (1500)	total: 27.3s	remaining: 1m 7s
1520:	learn: 0.2130742	test: 0.2193674	best: 0.2193674 (1520)	total: 27.7s	remaining: 1m 7s
1540:	learn: 0.2128334	test: 0.2192450	best: 0.2192450 (1540)	total: 28s	remaining: 1m 6s
1560:	learn: 0.2126098	test: 0.2191209	best: 0.2191209 (1560)	total: 28.4s	remaining: 1m 6s
1580:	learn: 0.2123537	test: 0.2189534	best: 0.2189534 (1580)	total: 28.8s	remaining: 1m 6s
1600:	learn: 0.2121654	test: 0.2188391	best: 0.2188391 (1600)	total: 29.1s	remaining: 1m 5s
1620:	learn: 0.2119207	test: 0.2186807	best: 0.2186807 (1620)	total: 29.5s	remaining: 1m 5s
1640:	learn: 0.2117202	test: 0.2185661	best: 0.2185636 (1638)	total: 29.8s	remaining: 1m 4s
1660:	learn: 0.2114930	test: 0.2184088	best: 0.2184088 (1660)	total: 30.2s	remaining: 1m 4s
1680:	learn: 0.2112147	test: 0.2182483	best: 0.2182483 (1680)	total: 30.5s	remaining: 1m 4s
1700:	learn: 0.2109808	test: 0.2180708	best: 0.2180708 (1700)	total: 30.9s	remaining: 1m 3s
1720:	learn: 0.2107460	test: 0.2179059	best: 0.2179059 (1720)	total: 31.3s	remaining: 1m 3s
1740:	learn: 0.2105543	test: 0.2178108	best: 0.2178093 (1739)	total: 31.6s	remaining: 1m 3s
1760:	learn: 0.2103214	test: 0.2176603	best: 0.2176603 (1760)	total: 32s	remaining: 1m 2s
1780:	learn: 0.2101179	test: 0.2175499	best: 0.2175499 (1780)	total: 32.3s	remaining: 1m 2s
1800:	learn: 0.2099316	test: 0.2174673	best: 0.2174673 (1800)	total: 32.7s	remaining: 1m 1s
1820:	learn: 0.2097330	test: 0.2173613	best: 0.2173613 (1820)	total: 33s	remaining: 1m 1s
1840:	learn: 0.2095273	test: 0.2172565	best: 0.2172565 (1840)	total: 33.4s	remaining: 1m 1s
1860:	learn: 0.2093434	test: 0.2171829	best: 0.2171829 (1860)	total: 33.7s	remaining: 1m
1880:	learn: 0.2091414	test: 0.2170646	best: 0.2170646 (1880)	total: 34.1s	remaining: 1m
1900:	learn: 0.2088611	test: 0.2168772	best: 0.2168772 (1900)	total: 34.5s	remaining: 1m
1920:	learn: 0.2086756	test: 0.2167796	best: 0.2167796 (1920)	total: 34.9s	remaining: 59.8s
1940:	learn: 0.2084729	test: 0.2166772	best: 0.2166772 (1940)	total: 35.2s	remaining: 59.4s
1960:	learn: 0.2082526	test: 0.2165438	best: 0.2165435 (1959)	total: 35.6s	remaining: 59.1s
1980:	learn: 0.2080514	test: 0.2164467	best: 0.2164467 (1980)	total: 35.9s	remaining: 58.7s
2000:	learn: 0.2078402	test: 0.2162901	best: 0.2162901 (2000)	total: 36.3s	remaining: 58.4s
2020:	learn: 0.2076608	test: 0.2161817	best: 0.2161817 (2020)	total: 36.7s	remaining: 58s
2040:	learn: 0.2074656	test: 0.2160790	best: 0.2160790 (2040)	total: 37.1s	remaining: 57.6s
2060:	learn: 0.2072536	test: 0.2160159	best: 0.2160154 (2058)	total: 37.4s	remaining: 57.3s
2080:	learn: 0.2070684	test: 0.2159032	best: 0.2159032 (2080)	total: 37.8s	remaining: 56.9s
2100:	learn: 0.2068844	test: 0.2157934	best: 0.2157916 (2098)	total: 38.1s	remaining: 56.5s
2120:	learn: 0.2067350	test: 0.2157369	best: 0.2157369 (2120)	total: 38.5s	remaining: 56.2s
2140:	learn: 0.2065615	test: 0.2156595	best: 0.2156595 (2140)	total: 38.9s	remaining: 55.8s
2160:	learn: 0.2063919	test: 0.2155615	best: 0.2155615 (2160)	total: 39.2s	remaining: 55.5s
2180:	learn: 0.2061867	test: 0.2154539	best: 0.2154539 (2180)	total: 39.6s	remaining: 55.1s
2200:	learn: 0.2060403	test: 0.2153711	best: 0.2153711 (2200)	total: 40s	remaining: 54.7s
2220:	learn: 0.2058654	test: 0.2152701	best: 0.2152701 (2220)	total: 40.3s	remaining: 54.4s
2240:	learn: 0.2056827	test: 0.2151966	best: 0.2151966 (2240)	total: 40.7s	remaining: 54s
2260:	learn: 0.2055313	test: 0.2151394	best: 0.2151394 (2260)	total: 41.1s	remaining: 53.7s
2280:	learn: 0.2053292	test: 0.2150403	best: 0.2150403 (2280)	total: 41.4s	remaining: 53.3s
2300:	learn: 0.2051426	test: 0.2149415	best: 0.2149415 (2300)	total: 41.8s	remaining: 52.9s
2320:	learn: 0.2049660	test: 0.2148534	best: 0.2148534 (2319)	total: 42.1s	remaining: 52.6s
2340:	learn: 0.2047654	test: 0.2147251	best: 0.2147251 (2340)	total: 42.5s	remaining: 52.2s
2360:	learn: 0.2045950	test: 0.2146601	best: 0.2146601 (2360)	total: 42.9s	remaining: 51.8s
2380:	learn: 0.2044354	test: 0.2145828	best: 0.2145828 (2380)	total: 43.2s	remaining: 51.5s
2400:	learn: 0.2042730	test: 0.2144983	best: 0.2144983 (2400)	total: 43.6s	remaining: 51.1s
2420:	learn: 0.2041184	test: 0.2144235	best: 0.2144235 (2420)	total: 44s	remaining: 50.8s
2440:	learn: 0.2039266	test: 0.2143166	best: 0.2143166 (2440)	total: 44.3s	remaining: 50.4s
2460:	learn: 0.2037654	test: 0.2142792	best: 0.2142792 (2460)	total: 44.7s	remaining: 50s
2480:	learn: 0.2036208	test: 0.2142252	best: 0.2142252 (2480)	total: 45.1s	remaining: 49.7s
2500:	learn: 0.2034331	test: 0.2141477	best: 0.2141477 (2500)	total: 45.5s	remaining: 49.3s
2520:	learn: 0.2032671	test: 0.2140851	best: 0.2140851 (2520)	total: 45.8s	remaining: 49s
2540:	learn: 0.2031098	test: 0.2140095	best: 0.2140095 (2540)	total: 46.2s	remaining: 48.6s
2560:	learn: 0.2029728	test: 0.2139484	best: 0.2139484 (2560)	total: 46.6s	remaining: 48.3s
2580:	learn: 0.2027884	test: 0.2138416	best: 0.2138404 (2579)	total: 46.9s	remaining: 47.9s
2600:	learn: 0.2026384	test: 0.2137643	best: 0.2137643 (2600)	total: 47.3s	remaining: 47.5s
2620:	learn: 0.2024927	test: 0.2137058	best: 0.2137058 (2620)	total: 47.7s	remaining: 47.2s
2640:	learn: 0.2023460	test: 0.2136349	best: 0.2136349 (2640)	total: 48s	remaining: 46.8s
2660:	learn: 0.2021724	test: 0.2135682	best: 0.2135682 (2660)	total: 48.4s	remaining: 46.5s
2680:	learn: 0.2020322	test: 0.2135157	best: 0.2135157 (2680)	total: 48.8s	remaining: 46.1s
2700:	learn: 0.2018689	test: 0.2134348	best: 0.2134348 (2700)	total: 49.1s	remaining: 45.7s
2720:	learn: 0.2017213	test: 0.2133764	best: 0.2133764 (2720)	total: 49.5s	remaining: 45.4s
2740:	learn: 0.2015690	test: 0.2132995	best: 0.2132995 (2740)	total: 49.9s	remaining: 45s
2760:	learn: 0.2014364	test: 0.2132499	best: 0.2132499 (2760)	total: 50.2s	remaining: 44.7s
2780:	learn: 0.2013140	test: 0.2131959	best: 0.2131959 (2780)	total: 50.6s	remaining: 44.3s
2800:	learn: 0.2011820	test: 0.2131351	best: 0.2131351 (2800)	total: 51s	remaining: 44s
2820:	learn: 0.2010469	test: 0.2131031	best: 0.2131031 (2820)	total: 51.4s	remaining: 43.6s
2840:	learn: 0.2009106	test: 0.2130476	best: 0.2130476 (2840)	total: 51.7s	remaining: 43.2s
2860:	learn: 0.2007764	test: 0.2129891	best: 0.2129891 (2860)	total: 52.1s	remaining: 42.9s
2880:	learn: 0.2006586	test: 0.2129505	best: 0.2129505 (2880)	total: 52.4s	remaining: 42.5s
2900:	learn: 0.2005126	test: 0.2128794	best: 0.2128793 (2899)	total: 52.8s	remaining: 42.1s
2920:	learn: 0.2003497	test: 0.2127909	best: 0.2127909 (2920)	total: 53.2s	remaining: 41.8s
2940:	learn: 0.2002254	test: 0.2127367	best: 0.2127367 (2940)	total: 53.5s	remaining: 41.4s
2960:	learn: 0.2000753	test: 0.2126859	best: 0.2126859 (2960)	total: 53.9s	remaining: 41.1s
2980:	learn: 0.1999312	test: 0.2126495	best: 0.2126495 (2980)	total: 54.3s	remaining: 40.7s
3000:	learn: 0.1997658	test: 0.2125638	best: 0.2125638 (3000)	total: 54.6s	remaining: 40.3s
3020:	learn: 0.1996280	test: 0.2125121	best: 0.2125121 (3020)	total: 55s	remaining: 40s
3040:	learn: 0.1994628	test: 0.2124314	best: 0.2124314 (3040)	total: 55.4s	remaining: 39.6s
3060:	learn: 0.1993262	test: 0.2123912	best: 0.2123912 (3060)	total: 55.7s	remaining: 39.2s
3080:	learn: 0.1991701	test: 0.2123107	best: 0.2123107 (3080)	total: 56.1s	remaining: 38.9s
3100:	learn: 0.1990263	test: 0.2122540	best: 0.2122540 (3100)	total: 56.4s	remaining: 38.5s
3120:	learn: 0.1988901	test: 0.2121956	best: 0.2121956 (3120)	total: 56.8s	remaining: 38.1s
3140:	learn: 0.1987574	test: 0.2121470	best: 0.2121407 (3138)	total: 57.2s	remaining: 37.8s
3160:	learn: 0.1986383	test: 0.2121114	best: 0.2121114 (3160)	total: 57.5s	remaining: 37.4s
3180:	learn: 0.1984792	test: 0.2120595	best: 0.2120575 (3179)	total: 57.9s	remaining: 37s
3200:	learn: 0.1983588	test: 0.2120225	best: 0.2120225 (3200)	total: 58.3s	remaining: 36.7s
3220:	learn: 0.1982337	test: 0.2119783	best: 0.2119783 (3220)	total: 58.6s	remaining: 36.3s
3240:	learn: 0.1981056	test: 0.2119065	best: 0.2119065 (3240)	total: 59s	remaining: 36s
3260:	learn: 0.1979687	test: 0.2118698	best: 0.2118698 (3260)	total: 59.4s	remaining: 35.6s
3280:	learn: 0.1978330	test: 0.2118031	best: 0.2118008 (3278)	total: 59.8s	remaining: 35.2s
3300:	learn: 0.1976805	test: 0.2117206	best: 0.2117206 (3300)	total: 1m	remaining: 34.9s
3320:	learn: 0.1975442	test: 0.2116705	best: 0.2116705 (3320)	total: 1m	remaining: 34.5s
3340:	learn: 0.1974081	test: 0.2116124	best: 0.2116124 (3340)	total: 1m	remaining: 34.2s
3360:	learn: 0.1972538	test: 0.2115228	best: 0.2115228 (3360)	total: 1m 1s	remaining: 33.8s
3380:	learn: 0.1971188	test: 0.2114500	best: 0.2114500 (3380)	total: 1m 1s	remaining: 33.4s
3400:	learn: 0.1970006	test: 0.2114124	best: 0.2114124 (3400)	total: 1m 1s	remaining: 33.1s
3420:	learn: 0.1968750	test: 0.2113722	best: 0.2113722 (3420)	total: 1m 2s	remaining: 32.7s
3440:	learn: 0.1967770	test: 0.2113258	best: 0.2113258 (3440)	total: 1m 2s	remaining: 32.4s
3460:	learn: 0.1966402	test: 0.2112981	best: 0.2112979 (3459)	total: 1m 3s	remaining: 32s
3480:	learn: 0.1965208	test: 0.2112581	best: 0.2112581 (3480)	total: 1m 3s	remaining: 31.6s
3500:	learn: 0.1963663	test: 0.2112002	best: 0.2111996 (3499)	total: 1m 3s	remaining: 31.3s
3520:	learn: 0.1962451	test: 0.2111726	best: 0.2111722 (3518)	total: 1m 4s	remaining: 30.9s
3540:	learn: 0.1961239	test: 0.2111406	best: 0.2111406 (3540)	total: 1m 4s	remaining: 30.5s
3560:	learn: 0.1960095	test: 0.2111127	best: 0.2111127 (3560)	total: 1m 4s	remaining: 30.2s
3580:	learn: 0.1958874	test: 0.2111020	best: 0.2110994 (3569)	total: 1m 5s	remaining: 29.8s
3600:	learn: 0.1957791	test: 0.2110565	best: 0.2110534 (3599)	total: 1m 5s	remaining: 29.5s
3620:	learn: 0.1956589	test: 0.2110004	best: 0.2110004 (3620)	total: 1m 6s	remaining: 29.1s
3640:	learn: 0.1955315	test: 0.2109702	best: 0.2109677 (3638)	total: 1m 6s	remaining: 28.7s
3660:	learn: 0.1953956	test: 0.2109148	best: 0.2109108 (3659)	total: 1m 6s	remaining: 28.4s
3680:	learn: 0.1952790	test: 0.2108737	best: 0.2108717 (3677)	total: 1m 7s	remaining: 28s
3700:	learn: 0.1951404	test: 0.2108094	best: 0.2108094 (3700)	total: 1m 7s	remaining: 27.7s
3720:	learn: 0.1949851	test: 0.2107357	best: 0.2107357 (3720)	total: 1m 7s	remaining: 27.3s
3740:	learn: 0.1948720	test: 0.2106992	best: 0.2106988 (3739)	total: 1m 8s	remaining: 26.9s
3760:	learn: 0.1947465	test: 0.2106559	best: 0.2106559 (3760)	total: 1m 8s	remaining: 26.6s
3780:	learn: 0.1946041	test: 0.2106109	best: 0.2106104 (3779)	total: 1m 9s	remaining: 26.2s
3800:	learn: 0.1944806	test: 0.2105749	best: 0.2105749 (3800)	total: 1m 9s	remaining: 25.8s
3820:	learn: 0.1943647	test: 0.2105479	best: 0.2105479 (3820)	total: 1m 9s	remaining: 25.5s
3840:	learn: 0.1942463	test: 0.2105089	best: 0.2105076 (3839)	total: 1m 10s	remaining: 25.1s
3860:	learn: 0.1941165	test: 0.2104637	best: 0.2104637 (3860)	total: 1m 10s	remaining: 24.8s
3880:	learn: 0.1940126	test: 0.2104271	best: 0.2104271 (3880)	total: 1m 10s	remaining: 24.4s
3900:	learn: 0.1938723	test: 0.2103704	best: 0.2103704 (3900)	total: 1m 11s	remaining: 24s
3920:	learn: 0.1937669	test: 0.2103278	best: 0.2103268 (3918)	total: 1m 11s	remaining: 23.7s
3940:	learn: 0.1936334	test: 0.2102766	best: 0.2102766 (3940)	total: 1m 12s	remaining: 23.3s
3960:	learn: 0.1935057	test: 0.2102217	best: 0.2102217 (3960)	total: 1m 12s	remaining: 22.9s
3980:	learn: 0.1933827	test: 0.2101875	best: 0.2101874 (3979)	total: 1m 12s	remaining: 22.6s
4000:	learn: 0.1932590	test: 0.2101214	best: 0.2101214 (4000)	total: 1m 13s	remaining: 22.2s
4020:	learn: 0.1931496	test: 0.2100812	best: 0.2100812 (4020)	total: 1m 13s	remaining: 21.9s
4040:	learn: 0.1930519	test: 0.2100801	best: 0.2100775 (4031)	total: 1m 13s	remaining: 21.5s
4060:	learn: 0.1929302	test: 0.2100349	best: 0.2100349 (4060)	total: 1m 14s	remaining: 21.1s
4080:	learn: 0.1928345	test: 0.2100230	best: 0.2100230 (4080)	total: 1m 14s	remaining: 20.8s
4100:	learn: 0.1927246	test: 0.2099847	best: 0.2099847 (4100)	total: 1m 15s	remaining: 20.4s
4120:	learn: 0.1926112	test: 0.2099643	best: 0.2099643 (4120)	total: 1m 15s	remaining: 20s
4140:	learn: 0.1924925	test: 0.2099212	best: 0.2099209 (4138)	total: 1m 15s	remaining: 19.7s
4160:	learn: 0.1924075	test: 0.2099070	best: 0.2099053 (4158)	total: 1m 16s	remaining: 19.3s
4180:	learn: 0.1923208	test: 0.2098690	best: 0.2098690 (4180)	total: 1m 16s	remaining: 19s
4200:	learn: 0.1922141	test: 0.2098391	best: 0.2098391 (4200)	total: 1m 16s	remaining: 18.6s
4220:	learn: 0.1920991	test: 0.2098219	best: 0.2098155 (4214)	total: 1m 17s	remaining: 18.2s
4240:	learn: 0.1919749	test: 0.2097653	best: 0.2097640 (4239)	total: 1m 17s	remaining: 17.9s
4260:	learn: 0.1918622	test: 0.2097118	best: 0.2097118 (4260)	total: 1m 18s	remaining: 17.5s
4280:	learn: 0.1917472	test: 0.2096802	best: 0.2096733 (4279)	total: 1m 18s	remaining: 17.1s
4300:	learn: 0.1916287	test: 0.2096419	best: 0.2096419 (4300)	total: 1m 18s	remaining: 16.8s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403955	test: 0.6405105	best: 0.6405105 (0)	total: 9.5ms	remaining: 9.5ms
1:	learn: 0.5956017	test: 0.5958536	best: 0.5958536 (1)	total: 18.4ms	remaining: 0us
bestTest = 0.5958535789
bestIteration = 1
0:	learn: 0.6413728	test: 0.6413636	best: 0.6413636 (0)	total: 16.9ms	remaining: 1m 29s
20:	learn: 0.3357604	test: 0.3370290	best: 0.3370290 (20)	total: 405ms	remaining: 1m 41s
40:	learn: 0.3018332	test: 0.3036473	best: 0.3036473 (40)	total: 791ms	remaining: 1m 40s
60:	learn: 0.2894256	test: 0.2911826	best: 0.2911826 (60)	total: 1.18s	remaining: 1m 40s
80:	learn: 0.2807820	test: 0.2820796	best: 0.2820796 (80)	total: 1.57s	remaining: 1m 40s
100:	learn: 0.2742035	test: 0.2755118	best: 0.2755118 (100)	total: 1.94s	remaining: 1m 39s
120:	learn: 0.2689010	test: 0.2702572	best: 0.2702572 (120)	total: 2.29s	remaining: 1m 37s
140:	learn: 0.2653866	test: 0.2667803	best: 0.2667803 (140)	total: 2.67s	remaining: 1m 37s
160:	learn: 0.2611556	test: 0.2624917	best: 0.2624917 (160)	total: 3.04s	remaining: 1m 36s
180:	learn: 0.2578185	test: 0.2591209	best: 0.2591209 (180)	total: 3.41s	remaining: 1m 35s
200:	learn: 0.2554598	test: 0.2568423	best: 0.2568423 (200)	total: 3.77s	remaining: 1m 35s
220:	learn: 0.2532687	test: 0.2547522	best: 0.2547522 (220)	total: 4.13s	remaining: 1m 34s
240:	learn: 0.2513767	test: 0.2529583	best: 0.2529583 (240)	total: 4.5s	remaining: 1m 33s
260:	learn: 0.2491235	test: 0.2506430	best: 0.2506430 (260)	total: 4.88s	remaining: 1m 33s
280:	learn: 0.2474443	test: 0.2491187	best: 0.2491187 (280)	total: 5.24s	remaining: 1m 33s
300:	learn: 0.2459794	test: 0.2477485	best: 0.2477485 (300)	total: 5.61s	remaining: 1m 32s
320:	learn: 0.2442330	test: 0.2461185	best: 0.2461185 (320)	total: 5.97s	remaining: 1m 32s
340:	learn: 0.2429340	test: 0.2449118	best: 0.2449118 (340)	total: 6.34s	remaining: 1m 31s
360:	learn: 0.2416782	test: 0.2437550	best: 0.2437550 (360)	total: 6.71s	remaining: 1m 31s
380:	learn: 0.2402635	test: 0.2423514	best: 0.2423514 (380)	total: 7.07s	remaining: 1m 30s
400:	learn: 0.2393002	test: 0.2415202	best: 0.2415202 (400)	total: 7.45s	remaining: 1m 30s
420:	learn: 0.2381057	test: 0.2404372	best: 0.2404372 (420)	total: 7.82s	remaining: 1m 30s
440:	learn: 0.2369826	test: 0.2393947	best: 0.2393947 (440)	total: 8.18s	remaining: 1m 29s
460:	learn: 0.2359431	test: 0.2384709	best: 0.2384709 (460)	total: 8.55s	remaining: 1m 29s
480:	learn: 0.2349002	test: 0.2375305	best: 0.2375305 (480)	total: 8.92s	remaining: 1m 28s
500:	learn: 0.2341252	test: 0.2368583	best: 0.2368583 (500)	total: 9.28s	remaining: 1m 28s
520:	learn: 0.2333665	test: 0.2362698	best: 0.2362698 (520)	total: 9.63s	remaining: 1m 27s
540:	learn: 0.2325509	test: 0.2355502	best: 0.2355502 (540)	total: 9.97s	remaining: 1m 27s
560:	learn: 0.2316904	test: 0.2347927	best: 0.2347927 (560)	total: 10.3s	remaining: 1m 26s
580:	learn: 0.2310615	test: 0.2342639	best: 0.2342639 (580)	total: 10.7s	remaining: 1m 26s
600:	learn: 0.2303236	test: 0.2336027	best: 0.2336027 (600)	total: 11s	remaining: 1m 25s
620:	learn: 0.2297162	test: 0.2331291	best: 0.2331291 (620)	total: 11.4s	remaining: 1m 25s
640:	learn: 0.2290861	test: 0.2326401	best: 0.2326401 (640)	total: 11.7s	remaining: 1m 24s
660:	learn: 0.2282791	test: 0.2318904	best: 0.2318904 (660)	total: 12.1s	remaining: 1m 24s
680:	learn: 0.2276371	test: 0.2313510	best: 0.2313510 (680)	total: 12.5s	remaining: 1m 23s
700:	learn: 0.2270926	test: 0.2309285	best: 0.2309285 (700)	total: 12.8s	remaining: 1m 23s
720:	learn: 0.2265185	test: 0.2304954	best: 0.2304954 (720)	total: 13.2s	remaining: 1m 23s
740:	learn: 0.2259705	test: 0.2300663	best: 0.2300663 (740)	total: 13.5s	remaining: 1m 22s
760:	learn: 0.2254947	test: 0.2296716	best: 0.2296716 (760)	total: 13.9s	remaining: 1m 22s
780:	learn: 0.2248886	test: 0.2291500	best: 0.2291500 (780)	total: 14.3s	remaining: 1m 21s
800:	learn: 0.2245085	test: 0.2289061	best: 0.2289061 (800)	total: 14.6s	remaining: 1m 21s
820:	learn: 0.2240376	test: 0.2285449	best: 0.2285449 (820)	total: 15s	remaining: 1m 21s
840:	learn: 0.2234508	test: 0.2280206	best: 0.2280206 (840)	total: 15.3s	remaining: 1m 20s
860:	learn: 0.2230275	test: 0.2276975	best: 0.2276975 (860)	total: 15.7s	remaining: 1m 20s
880:	learn: 0.2224337	test: 0.2271871	best: 0.2271871 (880)	total: 16s	remaining: 1m 19s
900:	learn: 0.2221091	test: 0.2269495	best: 0.2269495 (900)	total: 16.4s	remaining: 1m 19s
920:	learn: 0.2216842	test: 0.2266263	best: 0.2266263 (920)	total: 16.7s	remaining: 1m 19s
940:	learn: 0.2213578	test: 0.2264040	best: 0.2264040 (940)	total: 17.1s	remaining: 1m 18s
960:	learn: 0.2210469	test: 0.2262101	best: 0.2262101 (960)	total: 17.4s	remaining: 1m 18s
980:	learn: 0.2206627	test: 0.2259300	best: 0.2259300 (980)	total: 17.8s	remaining: 1m 17s
1000:	learn: 0.2203019	test: 0.2257015	best: 0.2257015 (1000)	total: 18.1s	remaining: 1m 17s
1020:	learn: 0.2199371	test: 0.2254283	best: 0.2254283 (1020)	total: 18.5s	remaining: 1m 17s
1040:	learn: 0.2195817	test: 0.2251801	best: 0.2251801 (1040)	total: 18.9s	remaining: 1m 16s
1060:	learn: 0.2192069	test: 0.2249202	best: 0.2249202 (1060)	total: 19.2s	remaining: 1m 16s
1080:	learn: 0.2188263	test: 0.2246406	best: 0.2246406 (1080)	total: 19.6s	remaining: 1m 15s
1100:	learn: 0.2184748	test: 0.2243800	best: 0.2243800 (1100)	total: 19.9s	remaining: 1m 15s
1120:	learn: 0.2180817	test: 0.2240859	best: 0.2240859 (1120)	total: 20.3s	remaining: 1m 15s
1140:	learn: 0.2177762	test: 0.2239025	best: 0.2239025 (1140)	total: 20.7s	remaining: 1m 14s
1160:	learn: 0.2174710	test: 0.2237088	best: 0.2237088 (1160)	total: 21s	remaining: 1m 14s
1180:	learn: 0.2171798	test: 0.2235348	best: 0.2235348 (1180)	total: 21.4s	remaining: 1m 14s
1200:	learn: 0.2168477	test: 0.2233326	best: 0.2233326 (1200)	total: 21.7s	remaining: 1m 13s
1220:	learn: 0.2165313	test: 0.2231426	best: 0.2231426 (1220)	total: 22.1s	remaining: 1m 13s
1240:	learn: 0.2162731	test: 0.2229821	best: 0.2229821 (1240)	total: 22.4s	remaining: 1m 12s
1260:	learn: 0.2159481	test: 0.2227464	best: 0.2227464 (1260)	total: 22.8s	remaining: 1m 12s
1280:	learn: 0.2156645	test: 0.2225796	best: 0.2225789 (1279)	total: 23.2s	remaining: 1m 12s
1300:	learn: 0.2153442	test: 0.2223815	best: 0.2223815 (1300)	total: 23.5s	remaining: 1m 11s
1320:	learn: 0.2150723	test: 0.2222302	best: 0.2222302 (1320)	total: 23.9s	remaining: 1m 11s
1340:	learn: 0.2147167	test: 0.2219926	best: 0.2219926 (1340)	total: 24.2s	remaining: 1m 11s
1360:	learn: 0.2144554	test: 0.2218010	best: 0.2218010 (1360)	total: 24.6s	remaining: 1m 10s
1380:	learn: 0.2142035	test: 0.2216501	best: 0.2216501 (1380)	total: 24.9s	remaining: 1m 10s
1400:	learn: 0.2139101	test: 0.2214720	best: 0.2214720 (1400)	total: 25.3s	remaining: 1m 9s
1420:	learn: 0.2136009	test: 0.2212837	best: 0.2212837 (1420)	total: 25.7s	remaining: 1m 9s
1440:	learn: 0.2133449	test: 0.2211237	best: 0.2211237 (1440)	total: 26s	remaining: 1m 9s
1460:	learn: 0.2131349	test: 0.2209943	best: 0.2209943 (1460)	total: 26.4s	remaining: 1m 8s
1480:	learn: 0.2129001	test: 0.2208622	best: 0.2208622 (1480)	total: 26.7s	remaining: 1m 8s
1500:	learn: 0.2126456	test: 0.2206991	best: 0.2206991 (1500)	total: 27.1s	remaining: 1m 8s
1520:	learn: 0.2124174	test: 0.2205625	best: 0.2205625 (1520)	total: 27.5s	remaining: 1m 7s
1540:	learn: 0.2121837	test: 0.2204579	best: 0.2204579 (1540)	total: 27.8s	remaining: 1m 7s
1560:	learn: 0.2119484	test: 0.2203493	best: 0.2203493 (1560)	total: 28.2s	remaining: 1m 6s
1580:	learn: 0.2117115	test: 0.2201901	best: 0.2201901 (1580)	total: 28.5s	remaining: 1m 6s
1600:	learn: 0.2114607	test: 0.2200321	best: 0.2200321 (1600)	total: 28.9s	remaining: 1m 6s
1620:	learn: 0.2112161	test: 0.2198806	best: 0.2198798 (1619)	total: 29.3s	remaining: 1m 5s
1640:	learn: 0.2110144	test: 0.2197638	best: 0.2197638 (1640)	total: 29.6s	remaining: 1m 5s
1660:	learn: 0.2107472	test: 0.2195874	best: 0.2195874 (1660)	total: 30s	remaining: 1m 5s
1680:	learn: 0.2104751	test: 0.2194132	best: 0.2194132 (1680)	total: 30.3s	remaining: 1m 4s
1700:	learn: 0.2102679	test: 0.2192952	best: 0.2192952 (1700)	total: 30.7s	remaining: 1m 4s
1720:	learn: 0.2099889	test: 0.2191256	best: 0.2191256 (1720)	total: 31s	remaining: 1m 4s
1740:	learn: 0.2097999	test: 0.2190243	best: 0.2190243 (1740)	total: 31.4s	remaining: 1m 3s
1760:	learn: 0.2096038	test: 0.2189315	best: 0.2189315 (1760)	total: 31.8s	remaining: 1m 3s
1780:	learn: 0.2094061	test: 0.2188100	best: 0.2188100 (1780)	total: 32.1s	remaining: 1m 2s
1800:	learn: 0.2092214	test: 0.2187042	best: 0.2187042 (1800)	total: 32.5s	remaining: 1m 2s
1820:	learn: 0.2090368	test: 0.2186188	best: 0.2186188 (1820)	total: 32.8s	remaining: 1m 2s
1840:	learn: 0.2088690	test: 0.2185492	best: 0.2185492 (1840)	total: 33.2s	remaining: 1m 1s
1860:	learn: 0.2086824	test: 0.2184560	best: 0.2184560 (1860)	total: 33.6s	remaining: 1m 1s
1880:	learn: 0.2085056	test: 0.2183799	best: 0.2183799 (1880)	total: 33.9s	remaining: 1m 1s
1900:	learn: 0.2083194	test: 0.2182736	best: 0.2182736 (1900)	total: 34.3s	remaining: 1m
1920:	learn: 0.2080951	test: 0.2181540	best: 0.2181540 (1920)	total: 34.7s	remaining: 1m
1940:	learn: 0.2078642	test: 0.2180347	best: 0.2180347 (1940)	total: 35s	remaining: 1m
1960:	learn: 0.2076618	test: 0.2179376	best: 0.2179376 (1960)	total: 35.4s	remaining: 59.7s
1980:	learn: 0.2074710	test: 0.2178400	best: 0.2178400 (1980)	total: 35.7s	remaining: 59.4s
2000:	learn: 0.2072625	test: 0.2177508	best: 0.2177508 (2000)	total: 36.1s	remaining: 59s
2020:	learn: 0.2070837	test: 0.2176416	best: 0.2176416 (2020)	total: 36.5s	remaining: 58.7s
2040:	learn: 0.2069105	test: 0.2175519	best: 0.2175519 (2040)	total: 36.8s	remaining: 58.3s
2060:	learn: 0.2066647	test: 0.2174008	best: 0.2174008 (2060)	total: 37.2s	remaining: 57.9s
2080:	learn: 0.2064483	test: 0.2172721	best: 0.2172721 (2080)	total: 37.6s	remaining: 57.6s
2100:	learn: 0.2062328	test: 0.2171594	best: 0.2171594 (2100)	total: 37.9s	remaining: 57.2s
2120:	learn: 0.2060329	test: 0.2170825	best: 0.2170825 (2120)	total: 38.3s	remaining: 56.8s
2140:	learn: 0.2058676	test: 0.2170202	best: 0.2170202 (2140)	total: 38.6s	remaining: 56.5s
2160:	learn: 0.2056862	test: 0.2169336	best: 0.2169336 (2160)	total: 39s	remaining: 56.1s
2180:	learn: 0.2055191	test: 0.2168502	best: 0.2168502 (2180)	total: 39.4s	remaining: 55.8s
2200:	learn: 0.2053713	test: 0.2167752	best: 0.2167752 (2200)	total: 39.7s	remaining: 55.4s
2220:	learn: 0.2052026	test: 0.2166970	best: 0.2166970 (2220)	total: 40.1s	remaining: 55s
2240:	learn: 0.2049498	test: 0.2165267	best: 0.2165267 (2240)	total: 40.4s	remaining: 54.7s
2260:	learn: 0.2047862	test: 0.2164853	best: 0.2164853 (2260)	total: 40.8s	remaining: 54.3s
2280:	learn: 0.2046156	test: 0.2164177	best: 0.2164177 (2280)	total: 41.2s	remaining: 54s
2300:	learn: 0.2044597	test: 0.2163491	best: 0.2163491 (2300)	total: 41.5s	remaining: 53.6s
2320:	learn: 0.2042720	test: 0.2162921	best: 0.2162921 (2320)	total: 41.9s	remaining: 53.2s
2340:	learn: 0.2041105	test: 0.2162243	best: 0.2162243 (2340)	total: 42.3s	remaining: 52.9s
2360:	learn: 0.2039296	test: 0.2161201	best: 0.2161201 (2360)	total: 42.6s	remaining: 52.5s
2380:	learn: 0.2037456	test: 0.2160542	best: 0.2160542 (2380)	total: 43s	remaining: 52.2s
2400:	learn: 0.2035874	test: 0.2159759	best: 0.2159748 (2399)	total: 43.4s	remaining: 51.8s
2420:	learn: 0.2034333	test: 0.2159150	best: 0.2159137 (2419)	total: 43.7s	remaining: 51.5s
2440:	learn: 0.2033044	test: 0.2158560	best: 0.2158560 (2440)	total: 44.1s	remaining: 51.1s
2460:	learn: 0.2031392	test: 0.2157752	best: 0.2157752 (2460)	total: 44.4s	remaining: 50.7s
2480:	learn: 0.2029388	test: 0.2156712	best: 0.2156712 (2480)	total: 44.8s	remaining: 50.4s
2500:	learn: 0.2027518	test: 0.2155663	best: 0.2155663 (2500)	total: 45.2s	remaining: 50s
2520:	learn: 0.2025838	test: 0.2154921	best: 0.2154908 (2519)	total: 45.5s	remaining: 49.7s
2540:	learn: 0.2024404	test: 0.2154242	best: 0.2154242 (2540)	total: 45.9s	remaining: 49.3s
2560:	learn: 0.2023076	test: 0.2153589	best: 0.2153589 (2560)	total: 46.2s	remaining: 48.9s
2580:	learn: 0.2021623	test: 0.2152957	best: 0.2152957 (2580)	total: 46.6s	remaining: 48.6s
2600:	learn: 0.2019749	test: 0.2151992	best: 0.2151972 (2599)	total: 47s	remaining: 48.2s
2620:	learn: 0.2018259	test: 0.2151307	best: 0.2151294 (2619)	total: 47.3s	remaining: 47.8s
2640:	learn: 0.2016722	test: 0.2150615	best: 0.2150615 (2640)	total: 47.7s	remaining: 47.5s
2660:	learn: 0.2015381	test: 0.2150254	best: 0.2150254 (2660)	total: 48.1s	remaining: 47.1s
2680:	learn: 0.2013547	test: 0.2149463	best: 0.2149463 (2680)	total: 48.4s	remaining: 46.8s
2700:	learn: 0.2011759	test: 0.2148335	best: 0.2148312 (2699)	total: 48.8s	remaining: 46.4s
2720:	learn: 0.2010402	test: 0.2147665	best: 0.2147665 (2720)	total: 49.2s	remaining: 46.1s
2740:	learn: 0.2008952	test: 0.2147140	best: 0.2147140 (2740)	total: 49.6s	remaining: 45.7s
2760:	learn: 0.2007505	test: 0.2146554	best: 0.2146554 (2760)	total: 49.9s	remaining: 45.4s
2780:	learn: 0.2005850	test: 0.2145884	best: 0.2145884 (2780)	total: 50.3s	remaining: 45s
2800:	learn: 0.2004467	test: 0.2145324	best: 0.2145324 (2800)	total: 50.7s	remaining: 44.7s
2820:	learn: 0.2003092	test: 0.2144905	best: 0.2144905 (2820)	total: 51s	remaining: 44.3s
2840:	learn: 0.2001826	test: 0.2144415	best: 0.2144415 (2840)	total: 51.4s	remaining: 44s
2860:	learn: 0.2000576	test: 0.2143916	best: 0.2143899 (2857)	total: 51.8s	remaining: 43.6s
2880:	learn: 0.1998969	test: 0.2143093	best: 0.2143093 (2880)	total: 52.1s	remaining: 43.2s
2900:	learn: 0.1997548	test: 0.2142673	best: 0.2142673 (2900)	total: 52.5s	remaining: 42.9s
2920:	learn: 0.1995539	test: 0.2141451	best: 0.2141451 (2920)	total: 52.9s	remaining: 42.5s
2940:	learn: 0.1993937	test: 0.2140859	best: 0.2140859 (2940)	total: 53.3s	remaining: 42.2s
2960:	learn: 0.1992406	test: 0.2140275	best: 0.2140275 (2960)	total: 53.6s	remaining: 41.8s
2980:	learn: 0.1991102	test: 0.2139795	best: 0.2139795 (2980)	total: 54s	remaining: 41.5s
3000:	learn: 0.1989736	test: 0.2139341	best: 0.2139341 (3000)	total: 54.4s	remaining: 41.2s
3020:	learn: 0.1988384	test: 0.2138757	best: 0.2138739 (3019)	total: 54.8s	remaining: 40.8s
3040:	learn: 0.1987151	test: 0.2138178	best: 0.2138178 (3040)	total: 55.2s	remaining: 40.5s
3060:	learn: 0.1985682	test: 0.2137613	best: 0.2137613 (3060)	total: 55.6s	remaining: 40.1s
3080:	learn: 0.1984457	test: 0.2137278	best: 0.2137278 (3080)	total: 56s	remaining: 39.8s
3100:	learn: 0.1983135	test: 0.2136946	best: 0.2136946 (3100)	total: 56.4s	remaining: 39.4s
3120:	learn: 0.1981740	test: 0.2136431	best: 0.2136431 (3120)	total: 56.7s	remaining: 39.1s
3140:	learn: 0.1980557	test: 0.2136063	best: 0.2136063 (3140)	total: 57.1s	remaining: 38.7s
3160:	learn: 0.1979334	test: 0.2135758	best: 0.2135758 (3160)	total: 57.5s	remaining: 38.4s
3180:	learn: 0.1977896	test: 0.2135172	best: 0.2135172 (3180)	total: 57.9s	remaining: 38s
3200:	learn: 0.1976464	test: 0.2134507	best: 0.2134507 (3200)	total: 58.3s	remaining: 37.7s
3220:	learn: 0.1975267	test: 0.2133942	best: 0.2133942 (3220)	total: 58.6s	remaining: 37.3s
3240:	learn: 0.1973948	test: 0.2133451	best: 0.2133451 (3240)	total: 59s	remaining: 37s
3260:	learn: 0.1972562	test: 0.2132984	best: 0.2132973 (3258)	total: 59.4s	remaining: 36.6s
3280:	learn: 0.1971392	test: 0.2132732	best: 0.2132732 (3280)	total: 59.8s	remaining: 36.3s
3300:	learn: 0.1970171	test: 0.2132403	best: 0.2132403 (3300)	total: 1m	remaining: 35.9s
3320:	learn: 0.1968991	test: 0.2132138	best: 0.2132138 (3320)	total: 1m	remaining: 35.6s
3340:	learn: 0.1967948	test: 0.2131648	best: 0.2131648 (3340)	total: 1m	remaining: 35.2s
3360:	learn: 0.1966466	test: 0.2131188	best: 0.2131188 (3360)	total: 1m 1s	remaining: 34.9s
3380:	learn: 0.1965281	test: 0.2130790	best: 0.2130790 (3380)	total: 1m 1s	remaining: 34.5s
3400:	learn: 0.1964041	test: 0.2130445	best: 0.2130406 (3395)	total: 1m 2s	remaining: 34.1s
3420:	learn: 0.1962895	test: 0.2130173	best: 0.2130173 (3420)	total: 1m 2s	remaining: 33.8s
3440:	learn: 0.1961730	test: 0.2129811	best: 0.2129809 (3439)	total: 1m 2s	remaining: 33.4s
3460:	learn: 0.1960492	test: 0.2129450	best: 0.2129450 (3460)	total: 1m 3s	remaining: 33.1s
3480:	learn: 0.1959193	test: 0.2128972	best: 0.2128972 (3480)	total: 1m 3s	remaining: 32.7s
3500:	learn: 0.1958033	test: 0.2128645	best: 0.2128645 (3500)	total: 1m 3s	remaining: 32.3s
3520:	learn: 0.1956560	test: 0.2127996	best: 0.2127996 (3520)	total: 1m 4s	remaining: 32s
3540:	learn: 0.1955446	test: 0.2127703	best: 0.2127703 (3540)	total: 1m 4s	remaining: 31.6s
3560:	learn: 0.1954139	test: 0.2127283	best: 0.2127283 (3560)	total: 1m 5s	remaining: 31.3s
3580:	learn: 0.1953014	test: 0.2126751	best: 0.2126751 (3580)	total: 1m 5s	remaining: 30.9s
3600:	learn: 0.1951739	test: 0.2126376	best: 0.2126376 (3600)	total: 1m 5s	remaining: 30.6s
3620:	learn: 0.1950454	test: 0.2125946	best: 0.2125946 (3620)	total: 1m 6s	remaining: 30.2s
3640:	learn: 0.1949295	test: 0.2125588	best: 0.2125566 (3639)	total: 1m 6s	remaining: 29.8s
3660:	learn: 0.1948058	test: 0.2125213	best: 0.2125213 (3660)	total: 1m 7s	remaining: 29.5s
3680:	learn: 0.1946906	test: 0.2124743	best: 0.2124743 (3680)	total: 1m 7s	remaining: 29.1s
3700:	learn: 0.1945591	test: 0.2124275	best: 0.2124272 (3699)	total: 1m 7s	remaining: 28.8s
3720:	learn: 0.1944498	test: 0.2123913	best: 0.2123910 (3719)	total: 1m 8s	remaining: 28.4s
3740:	learn: 0.1943213	test: 0.2123423	best: 0.2123423 (3740)	total: 1m 8s	remaining: 28s
3760:	learn: 0.1942116	test: 0.2123101	best: 0.2123101 (3760)	total: 1m 8s	remaining: 27.7s
3780:	learn: 0.1941042	test: 0.2122888	best: 0.2122888 (3780)	total: 1m 9s	remaining: 27.3s
3800:	learn: 0.1939658	test: 0.2122127	best: 0.2122127 (3800)	total: 1m 9s	remaining: 27s
3820:	learn: 0.1938378	test: 0.2121778	best: 0.2121778 (3820)	total: 1m 10s	remaining: 26.6s
3840:	learn: 0.1937248	test: 0.2121515	best: 0.2121495 (3838)	total: 1m 10s	remaining: 26.2s
3860:	learn: 0.1936040	test: 0.2121015	best: 0.2121015 (3860)	total: 1m 10s	remaining: 25.9s
3880:	learn: 0.1934770	test: 0.2120458	best: 0.2120432 (3876)	total: 1m 11s	remaining: 25.5s
3900:	learn: 0.1933654	test: 0.2120019	best: 0.2119995 (3898)	total: 1m 11s	remaining: 25.2s
3920:	learn: 0.1932290	test: 0.2119503	best: 0.2119503 (3920)	total: 1m 12s	remaining: 24.8s
3940:	learn: 0.1931104	test: 0.2119185	best: 0.2119185 (3940)	total: 1m 12s	remaining: 24.4s
3960:	learn: 0.1929961	test: 0.2118916	best: 0.2118863 (3955)	total: 1m 12s	remaining: 24.1s
3980:	learn: 0.1928798	test: 0.2118566	best: 0.2118566 (3980)	total: 1m 13s	remaining: 23.7s
4000:	learn: 0.1927796	test: 0.2118264	best: 0.2118264 (4000)	total: 1m 13s	remaining: 23.4s
4020:	learn: 0.1926677	test: 0.2118023	best: 0.2118014 (4018)	total: 1m 13s	remaining: 23s
4040:	learn: 0.1925290	test: 0.2117559	best: 0.2117559 (4040)	total: 1m 14s	remaining: 22.6s
4060:	learn: 0.1924138	test: 0.2117420	best: 0.2117415 (4059)	total: 1m 14s	remaining: 22.3s
4080:	learn: 0.1923001	test: 0.2117145	best: 0.2117145 (4080)	total: 1m 15s	remaining: 21.9s
4100:	learn: 0.1921759	test: 0.2116753	best: 0.2116753 (4100)	total: 1m 15s	remaining: 21.5s
4120:	learn: 0.1920727	test: 0.2116380	best: 0.2116372 (4119)	total: 1m 15s	remaining: 21.2s
4140:	learn: 0.1919690	test: 0.2116304	best: 0.2116278 (4136)	total: 1m 16s	remaining: 20.8s
4160:	learn: 0.1918098	test: 0.2115621	best: 0.2115621 (4160)	total: 1m 16s	remaining: 20.5s
4180:	learn: 0.1916972	test: 0.2115373	best: 0.2115373 (4180)	total: 1m 17s	remaining: 20.1s
4200:	learn: 0.1915852	test: 0.2115025	best: 0.2115025 (4200)	total: 1m 17s	remaining: 19.7s
4220:	learn: 0.1914752	test: 0.2114821	best: 0.2114821 (4220)	total: 1m 17s	remaining: 19.4s
4240:	learn: 0.1913623	test: 0.2114657	best: 0.2114652 (4237)	total: 1m 18s	remaining: 19s
4260:	learn: 0.1912595	test: 0.2114429	best: 0.2114399 (4258)	total: 1m 18s	remaining: 18.6s
4280:	learn: 0.1911382	test: 0.2113967	best: 0.2113967 (4280)	total: 1m 18s	remaining: 18.3s
4300:	learn: 0.1910348	test: 0.2113662	best: 0.2113661 (4299)	total: 1m 19s	remaining: 17.9s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404901	test: 0.6404259	best: 0.6404259 (0)	total: 8.83ms	remaining: 8.83ms
1:	learn: 0.5956915	test: 0.5955792	best: 0.5955792 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5955791538
bestIteration = 1
0:	learn: 0.6414933	test: 0.6414190	best: 0.6414190 (0)	total: 16.9ms	remaining: 1m 28s
20:	learn: 0.3369748	test: 0.3362003	best: 0.3362003 (20)	total: 396ms	remaining: 1m 38s
40:	learn: 0.3041411	test: 0.3034036	best: 0.3034036 (40)	total: 784ms	remaining: 1m 39s
60:	learn: 0.2895539	test: 0.2883818	best: 0.2883818 (60)	total: 1.17s	remaining: 1m 39s
80:	learn: 0.2812321	test: 0.2801285	best: 0.2801285 (80)	total: 1.53s	remaining: 1m 37s
100:	learn: 0.2758823	test: 0.2746167	best: 0.2746167 (100)	total: 1.91s	remaining: 1m 37s
120:	learn: 0.2709860	test: 0.2696579	best: 0.2696579 (120)	total: 2.29s	remaining: 1m 36s
140:	learn: 0.2671018	test: 0.2657993	best: 0.2657993 (140)	total: 2.65s	remaining: 1m 35s
160:	learn: 0.2638929	test: 0.2627191	best: 0.2627191 (160)	total: 3.03s	remaining: 1m 35s
180:	learn: 0.2601933	test: 0.2588412	best: 0.2588412 (180)	total: 3.39s	remaining: 1m 34s
200:	learn: 0.2569951	test: 0.2556459	best: 0.2556459 (200)	total: 3.75s	remaining: 1m 34s
220:	learn: 0.2542157	test: 0.2527037	best: 0.2527037 (220)	total: 4.13s	remaining: 1m 33s
240:	learn: 0.2522326	test: 0.2507611	best: 0.2507611 (240)	total: 4.48s	remaining: 1m 32s
260:	learn: 0.2503790	test: 0.2487887	best: 0.2487887 (260)	total: 4.85s	remaining: 1m 32s
280:	learn: 0.2484500	test: 0.2469763	best: 0.2469763 (280)	total: 5.2s	remaining: 1m 31s
300:	learn: 0.2467969	test: 0.2453508	best: 0.2453508 (300)	total: 5.56s	remaining: 1m 31s
320:	learn: 0.2453796	test: 0.2439766	best: 0.2439766 (320)	total: 5.93s	remaining: 1m 30s
340:	learn: 0.2439526	test: 0.2426810	best: 0.2426810 (340)	total: 6.29s	remaining: 1m 30s
360:	learn: 0.2425353	test: 0.2412437	best: 0.2412437 (360)	total: 6.65s	remaining: 1m 29s
380:	learn: 0.2414040	test: 0.2402465	best: 0.2402465 (380)	total: 7s	remaining: 1m 29s
400:	learn: 0.2404216	test: 0.2393531	best: 0.2393531 (400)	total: 7.36s	remaining: 1m 28s
420:	learn: 0.2391527	test: 0.2380867	best: 0.2380867 (420)	total: 7.72s	remaining: 1m 28s
440:	learn: 0.2380753	test: 0.2370648	best: 0.2370648 (440)	total: 8.08s	remaining: 1m 27s
460:	learn: 0.2371334	test: 0.2362539	best: 0.2362539 (460)	total: 8.43s	remaining: 1m 27s
480:	learn: 0.2361310	test: 0.2353716	best: 0.2353716 (480)	total: 8.79s	remaining: 1m 26s
500:	learn: 0.2350709	test: 0.2343604	best: 0.2343604 (500)	total: 9.14s	remaining: 1m 26s
520:	learn: 0.2342544	test: 0.2335940	best: 0.2335940 (520)	total: 9.49s	remaining: 1m 25s
540:	learn: 0.2335249	test: 0.2329686	best: 0.2329686 (540)	total: 9.85s	remaining: 1m 25s
560:	learn: 0.2328072	test: 0.2323612	best: 0.2323612 (560)	total: 10.2s	remaining: 1m 25s
580:	learn: 0.2320104	test: 0.2316691	best: 0.2316691 (580)	total: 10.6s	remaining: 1m 24s
600:	learn: 0.2314597	test: 0.2312345	best: 0.2312345 (600)	total: 10.9s	remaining: 1m 24s
620:	learn: 0.2306738	test: 0.2305738	best: 0.2305738 (620)	total: 11.3s	remaining: 1m 23s
640:	learn: 0.2300636	test: 0.2300663	best: 0.2300663 (640)	total: 11.7s	remaining: 1m 23s
660:	learn: 0.2295119	test: 0.2296374	best: 0.2296374 (660)	total: 12s	remaining: 1m 23s
680:	learn: 0.2289096	test: 0.2291828	best: 0.2291828 (680)	total: 12.4s	remaining: 1m 22s
700:	learn: 0.2283665	test: 0.2287615	best: 0.2287615 (700)	total: 12.8s	remaining: 1m 22s
720:	learn: 0.2277243	test: 0.2281793	best: 0.2281793 (720)	total: 13.1s	remaining: 1m 22s
740:	learn: 0.2270723	test: 0.2276009	best: 0.2276009 (740)	total: 13.5s	remaining: 1m 21s
760:	learn: 0.2264158	test: 0.2270522	best: 0.2270522 (760)	total: 13.8s	remaining: 1m 21s
780:	learn: 0.2258951	test: 0.2266174	best: 0.2266174 (780)	total: 14.2s	remaining: 1m 21s
800:	learn: 0.2252223	test: 0.2260214	best: 0.2260214 (800)	total: 14.6s	remaining: 1m 20s
820:	learn: 0.2246979	test: 0.2255953	best: 0.2255953 (820)	total: 14.9s	remaining: 1m 20s
840:	learn: 0.2241650	test: 0.2251513	best: 0.2251513 (840)	total: 15.3s	remaining: 1m 19s
860:	learn: 0.2237208	test: 0.2248057	best: 0.2248057 (860)	total: 15.7s	remaining: 1m 19s
880:	learn: 0.2232912	test: 0.2244648	best: 0.2244648 (880)	total: 16s	remaining: 1m 19s
900:	learn: 0.2227989	test: 0.2240938	best: 0.2240938 (900)	total: 16.4s	remaining: 1m 18s
920:	learn: 0.2224333	test: 0.2238406	best: 0.2238406 (920)	total: 16.7s	remaining: 1m 18s
940:	learn: 0.2219585	test: 0.2234782	best: 0.2234782 (940)	total: 17.1s	remaining: 1m 18s
960:	learn: 0.2215658	test: 0.2231929	best: 0.2231929 (960)	total: 17.5s	remaining: 1m 17s
980:	learn: 0.2211689	test: 0.2229663	best: 0.2229663 (980)	total: 17.8s	remaining: 1m 17s
1000:	learn: 0.2207456	test: 0.2226626	best: 0.2226626 (1000)	total: 18.2s	remaining: 1m 16s
1020:	learn: 0.2203304	test: 0.2223426	best: 0.2223426 (1020)	total: 18.6s	remaining: 1m 16s
1040:	learn: 0.2199717	test: 0.2221072	best: 0.2221072 (1040)	total: 18.9s	remaining: 1m 16s
1060:	learn: 0.2195566	test: 0.2217739	best: 0.2217739 (1060)	total: 19.3s	remaining: 1m 15s
1080:	learn: 0.2192166	test: 0.2215236	best: 0.2215236 (1080)	total: 19.7s	remaining: 1m 15s
1100:	learn: 0.2188758	test: 0.2212578	best: 0.2212578 (1100)	total: 20s	remaining: 1m 15s
1120:	learn: 0.2184395	test: 0.2208966	best: 0.2208966 (1120)	total: 20.4s	remaining: 1m 14s
1140:	learn: 0.2181027	test: 0.2206855	best: 0.2206855 (1140)	total: 20.8s	remaining: 1m 14s
1160:	learn: 0.2177219	test: 0.2204225	best: 0.2204225 (1160)	total: 21.1s	remaining: 1m 14s
1180:	learn: 0.2174582	test: 0.2202477	best: 0.2202477 (1180)	total: 21.5s	remaining: 1m 13s
1200:	learn: 0.2171697	test: 0.2200657	best: 0.2200657 (1200)	total: 21.9s	remaining: 1m 13s
1220:	learn: 0.2168316	test: 0.2198573	best: 0.2198573 (1220)	total: 22.3s	remaining: 1m 13s
1240:	learn: 0.2164931	test: 0.2196027	best: 0.2196027 (1240)	total: 22.6s	remaining: 1m 12s
1260:	learn: 0.2162519	test: 0.2194520	best: 0.2194520 (1260)	total: 23s	remaining: 1m 12s
1280:	learn: 0.2160023	test: 0.2193112	best: 0.2193112 (1280)	total: 23.4s	remaining: 1m 12s
1300:	learn: 0.2157223	test: 0.2191414	best: 0.2191414 (1300)	total: 23.8s	remaining: 1m 11s
1320:	learn: 0.2154688	test: 0.2189712	best: 0.2189712 (1320)	total: 24.2s	remaining: 1m 11s
1340:	learn: 0.2152193	test: 0.2188241	best: 0.2188241 (1340)	total: 24.5s	remaining: 1m 11s
1360:	learn: 0.2149234	test: 0.2186611	best: 0.2186611 (1360)	total: 24.9s	remaining: 1m 10s
1380:	learn: 0.2146916	test: 0.2185558	best: 0.2185558 (1380)	total: 25.3s	remaining: 1m 10s
1400:	learn: 0.2144002	test: 0.2183995	best: 0.2183995 (1400)	total: 25.6s	remaining: 1m 10s
1420:	learn: 0.2141813	test: 0.2182991	best: 0.2182991 (1420)	total: 26s	remaining: 1m 9s
1440:	learn: 0.2139606	test: 0.2181681	best: 0.2181681 (1440)	total: 26.4s	remaining: 1m 9s
1460:	learn: 0.2136894	test: 0.2179992	best: 0.2179992 (1460)	total: 26.7s	remaining: 1m 9s
1480:	learn: 0.2134521	test: 0.2178744	best: 0.2178744 (1480)	total: 27.1s	remaining: 1m 8s
1500:	learn: 0.2131885	test: 0.2177097	best: 0.2177097 (1500)	total: 27.5s	remaining: 1m 8s
1520:	learn: 0.2129345	test: 0.2175659	best: 0.2175659 (1520)	total: 27.8s	remaining: 1m 7s
1540:	learn: 0.2126608	test: 0.2173707	best: 0.2173707 (1540)	total: 28.2s	remaining: 1m 7s
1560:	learn: 0.2123826	test: 0.2171817	best: 0.2171817 (1560)	total: 28.6s	remaining: 1m 7s
1580:	learn: 0.2121740	test: 0.2170516	best: 0.2170516 (1580)	total: 28.9s	remaining: 1m 6s
1600:	learn: 0.2119433	test: 0.2168910	best: 0.2168910 (1600)	total: 29.3s	remaining: 1m 6s
1620:	learn: 0.2117045	test: 0.2167606	best: 0.2167606 (1620)	total: 29.7s	remaining: 1m 6s
1640:	learn: 0.2115102	test: 0.2166530	best: 0.2166530 (1640)	total: 30s	remaining: 1m 5s
1660:	learn: 0.2112663	test: 0.2165047	best: 0.2165047 (1660)	total: 30.4s	remaining: 1m 5s
1680:	learn: 0.2110246	test: 0.2163588	best: 0.2163588 (1680)	total: 30.8s	remaining: 1m 5s
1700:	learn: 0.2107442	test: 0.2161986	best: 0.2161986 (1700)	total: 31.2s	remaining: 1m 4s
1720:	learn: 0.2105484	test: 0.2160865	best: 0.2160865 (1720)	total: 31.5s	remaining: 1m 4s
1740:	learn: 0.2102971	test: 0.2159149	best: 0.2159149 (1740)	total: 31.9s	remaining: 1m 4s
1760:	learn: 0.2100686	test: 0.2158189	best: 0.2158189 (1760)	total: 32.3s	remaining: 1m 3s
1780:	learn: 0.2098571	test: 0.2156819	best: 0.2156819 (1780)	total: 32.7s	remaining: 1m 3s
1800:	learn: 0.2096527	test: 0.2155864	best: 0.2155864 (1800)	total: 33s	remaining: 1m 3s
1820:	learn: 0.2094238	test: 0.2154697	best: 0.2154697 (1820)	total: 33.4s	remaining: 1m 2s
1840:	learn: 0.2091316	test: 0.2152595	best: 0.2152595 (1840)	total: 33.8s	remaining: 1m 2s
1860:	learn: 0.2089443	test: 0.2151679	best: 0.2151679 (1860)	total: 34.1s	remaining: 1m 1s
1880:	learn: 0.2087713	test: 0.2150658	best: 0.2150658 (1880)	total: 34.5s	remaining: 1m 1s
1900:	learn: 0.2085738	test: 0.2149817	best: 0.2149817 (1900)	total: 34.8s	remaining: 1m 1s
1920:	learn: 0.2083675	test: 0.2148968	best: 0.2148968 (1920)	total: 35.2s	remaining: 1m
1940:	learn: 0.2081711	test: 0.2148015	best: 0.2148015 (1940)	total: 35.6s	remaining: 1m
1960:	learn: 0.2079850	test: 0.2147150	best: 0.2147150 (1960)	total: 36s	remaining: 1m
1980:	learn: 0.2077977	test: 0.2146075	best: 0.2146075 (1980)	total: 36.3s	remaining: 59.7s
2000:	learn: 0.2076225	test: 0.2145394	best: 0.2145360 (1998)	total: 36.7s	remaining: 59.3s
2020:	learn: 0.2074392	test: 0.2144628	best: 0.2144628 (2020)	total: 37s	remaining: 58.9s
2040:	learn: 0.2072275	test: 0.2143502	best: 0.2143502 (2040)	total: 37.4s	remaining: 58.6s
2060:	learn: 0.2070400	test: 0.2142751	best: 0.2142745 (2059)	total: 37.8s	remaining: 58.2s
2080:	learn: 0.2068456	test: 0.2141660	best: 0.2141660 (2080)	total: 38.1s	remaining: 57.8s
2100:	learn: 0.2066806	test: 0.2140973	best: 0.2140973 (2100)	total: 38.5s	remaining: 57.4s
2120:	learn: 0.2064963	test: 0.2140252	best: 0.2140252 (2120)	total: 38.8s	remaining: 57.1s
2140:	learn: 0.2063535	test: 0.2139443	best: 0.2139437 (2139)	total: 39.2s	remaining: 56.7s
2160:	learn: 0.2061928	test: 0.2138871	best: 0.2138856 (2159)	total: 39.6s	remaining: 56.3s
2180:	learn: 0.2059889	test: 0.2138158	best: 0.2138158 (2180)	total: 40s	remaining: 56s
2200:	learn: 0.2058054	test: 0.2137329	best: 0.2137329 (2200)	total: 40.3s	remaining: 55.6s
2220:	learn: 0.2056362	test: 0.2136652	best: 0.2136652 (2220)	total: 40.7s	remaining: 55.2s
2240:	learn: 0.2054787	test: 0.2135571	best: 0.2135571 (2240)	total: 41s	remaining: 54.8s
2260:	learn: 0.2052881	test: 0.2134600	best: 0.2134600 (2260)	total: 41.4s	remaining: 54.5s
2280:	learn: 0.2051211	test: 0.2133805	best: 0.2133805 (2280)	total: 41.8s	remaining: 54.1s
2300:	learn: 0.2049366	test: 0.2132773	best: 0.2132773 (2300)	total: 42.1s	remaining: 53.8s
2320:	learn: 0.2047739	test: 0.2132064	best: 0.2132064 (2320)	total: 42.5s	remaining: 53.4s
2340:	learn: 0.2045774	test: 0.2131119	best: 0.2131119 (2340)	total: 42.9s	remaining: 53s
2360:	learn: 0.2044077	test: 0.2130362	best: 0.2130355 (2358)	total: 43.2s	remaining: 52.7s
2380:	learn: 0.2042455	test: 0.2129701	best: 0.2129701 (2380)	total: 43.6s	remaining: 52.3s
2400:	learn: 0.2040941	test: 0.2128975	best: 0.2128975 (2400)	total: 44s	remaining: 51.9s
2420:	learn: 0.2039253	test: 0.2128185	best: 0.2128185 (2420)	total: 44.3s	remaining: 51.5s
2440:	learn: 0.2037769	test: 0.2127470	best: 0.2127470 (2440)	total: 44.7s	remaining: 51.2s
2460:	learn: 0.2036368	test: 0.2126882	best: 0.2126882 (2460)	total: 45.1s	remaining: 50.8s
2480:	learn: 0.2034875	test: 0.2126227	best: 0.2126227 (2480)	total: 45.4s	remaining: 50.4s
2500:	learn: 0.2033083	test: 0.2125343	best: 0.2125343 (2500)	total: 45.8s	remaining: 50.1s
2520:	learn: 0.2031373	test: 0.2124683	best: 0.2124683 (2520)	total: 46.2s	remaining: 49.7s
2540:	learn: 0.2029530	test: 0.2123942	best: 0.2123942 (2539)	total: 46.5s	remaining: 49.4s
2560:	learn: 0.2027972	test: 0.2123359	best: 0.2123359 (2560)	total: 46.9s	remaining: 49s
2580:	learn: 0.2026468	test: 0.2122463	best: 0.2122417 (2579)	total: 47.3s	remaining: 48.6s
2600:	learn: 0.2025079	test: 0.2121733	best: 0.2121733 (2600)	total: 47.7s	remaining: 48.3s
2620:	learn: 0.2023353	test: 0.2121129	best: 0.2121129 (2620)	total: 48s	remaining: 47.9s
2640:	learn: 0.2021785	test: 0.2120584	best: 0.2120584 (2640)	total: 48.4s	remaining: 47.6s
2660:	learn: 0.2019982	test: 0.2119506	best: 0.2119506 (2660)	total: 48.8s	remaining: 47.2s
2680:	learn: 0.2018628	test: 0.2118904	best: 0.2118904 (2680)	total: 49.2s	remaining: 46.9s
2700:	learn: 0.2017193	test: 0.2118422	best: 0.2118422 (2700)	total: 49.5s	remaining: 46.5s
2720:	learn: 0.2015648	test: 0.2117709	best: 0.2117699 (2719)	total: 49.9s	remaining: 46.1s
2740:	learn: 0.2014334	test: 0.2117444	best: 0.2117444 (2740)	total: 50.3s	remaining: 45.8s
2760:	learn: 0.2012709	test: 0.2116878	best: 0.2116878 (2760)	total: 50.6s	remaining: 45.4s
2780:	learn: 0.2011209	test: 0.2116200	best: 0.2116200 (2780)	total: 51s	remaining: 45s
2800:	learn: 0.2009833	test: 0.2115747	best: 0.2115747 (2800)	total: 51.3s	remaining: 44.6s
2820:	learn: 0.2008175	test: 0.2114856	best: 0.2114853 (2819)	total: 51.7s	remaining: 44.3s
2840:	learn: 0.2006635	test: 0.2114234	best: 0.2114234 (2840)	total: 52.1s	remaining: 43.9s
2860:	learn: 0.2004938	test: 0.2113487	best: 0.2113487 (2860)	total: 52.4s	remaining: 43.5s
2880:	learn: 0.2003635	test: 0.2112951	best: 0.2112951 (2880)	total: 52.8s	remaining: 43.2s
2900:	learn: 0.2002002	test: 0.2112286	best: 0.2112266 (2899)	total: 53.2s	remaining: 42.8s
2920:	learn: 0.2000695	test: 0.2111741	best: 0.2111741 (2920)	total: 53.6s	remaining: 42.5s
2940:	learn: 0.1999372	test: 0.2111375	best: 0.2111375 (2940)	total: 54s	remaining: 42.1s
2960:	learn: 0.1997872	test: 0.2111048	best: 0.2111037 (2959)	total: 54.3s	remaining: 41.7s
2980:	learn: 0.1996198	test: 0.2110367	best: 0.2110367 (2980)	total: 54.7s	remaining: 41.4s
3000:	learn: 0.1994910	test: 0.2109968	best: 0.2109968 (3000)	total: 55.1s	remaining: 41s
3020:	learn: 0.1993509	test: 0.2109338	best: 0.2109338 (3020)	total: 55.4s	remaining: 40.6s
3040:	learn: 0.1992272	test: 0.2108883	best: 0.2108883 (3040)	total: 55.8s	remaining: 40.3s
3060:	learn: 0.1990920	test: 0.2108398	best: 0.2108398 (3060)	total: 56.2s	remaining: 39.9s
3080:	learn: 0.1989394	test: 0.2107343	best: 0.2107343 (3080)	total: 56.5s	remaining: 39.6s
3100:	learn: 0.1987916	test: 0.2106754	best: 0.2106754 (3100)	total: 56.9s	remaining: 39.2s
3120:	learn: 0.1985998	test: 0.2105601	best: 0.2105601 (3120)	total: 57.3s	remaining: 38.8s
3140:	learn: 0.1984748	test: 0.2105153	best: 0.2105142 (3137)	total: 57.7s	remaining: 38.5s
3160:	learn: 0.1983575	test: 0.2104857	best: 0.2104839 (3159)	total: 58s	remaining: 38.1s
3180:	learn: 0.1982251	test: 0.2104445	best: 0.2104435 (3177)	total: 58.4s	remaining: 37.7s
3200:	learn: 0.1980514	test: 0.2103469	best: 0.2103469 (3200)	total: 58.8s	remaining: 37.4s
3220:	learn: 0.1979116	test: 0.2102894	best: 0.2102894 (3220)	total: 59.1s	remaining: 37s
3240:	learn: 0.1977768	test: 0.2102565	best: 0.2102565 (3240)	total: 59.5s	remaining: 36.6s
3260:	learn: 0.1976560	test: 0.2102417	best: 0.2102417 (3260)	total: 59.9s	remaining: 36.3s
3280:	learn: 0.1975388	test: 0.2101944	best: 0.2101944 (3280)	total: 1m	remaining: 35.9s
3300:	learn: 0.1974093	test: 0.2101472	best: 0.2101472 (3300)	total: 1m	remaining: 35.6s
3320:	learn: 0.1972531	test: 0.2100732	best: 0.2100732 (3320)	total: 1m 1s	remaining: 35.2s
3340:	learn: 0.1971516	test: 0.2100524	best: 0.2100524 (3340)	total: 1m 1s	remaining: 34.9s
3360:	learn: 0.1970153	test: 0.2100421	best: 0.2100358 (3352)	total: 1m 1s	remaining: 34.6s
3380:	learn: 0.1969009	test: 0.2100089	best: 0.2100089 (3380)	total: 1m 2s	remaining: 34.2s
3400:	learn: 0.1967806	test: 0.2099582	best: 0.2099582 (3400)	total: 1m 2s	remaining: 33.8s
3420:	learn: 0.1966393	test: 0.2099084	best: 0.2099084 (3420)	total: 1m 3s	remaining: 33.5s
3440:	learn: 0.1965082	test: 0.2098383	best: 0.2098383 (3440)	total: 1m 3s	remaining: 33.2s
3460:	learn: 0.1963991	test: 0.2098167	best: 0.2098158 (3456)	total: 1m 4s	remaining: 32.9s
3480:	learn: 0.1962415	test: 0.2097397	best: 0.2097381 (3478)	total: 1m 4s	remaining: 32.5s
3500:	learn: 0.1961072	test: 0.2096896	best: 0.2096896 (3500)	total: 1m 4s	remaining: 32.2s
3520:	learn: 0.1959857	test: 0.2096697	best: 0.2096697 (3520)	total: 1m 5s	remaining: 31.8s
3540:	learn: 0.1958514	test: 0.2096078	best: 0.2096078 (3540)	total: 1m 5s	remaining: 31.5s
3560:	learn: 0.1957291	test: 0.2095499	best: 0.2095499 (3560)	total: 1m 6s	remaining: 31.1s
3580:	learn: 0.1956261	test: 0.2095332	best: 0.2095325 (3579)	total: 1m 6s	remaining: 30.8s
3600:	learn: 0.1955195	test: 0.2095108	best: 0.2095108 (3600)	total: 1m 6s	remaining: 30.4s
3620:	learn: 0.1953834	test: 0.2094914	best: 0.2094914 (3620)	total: 1m 7s	remaining: 30s
3640:	learn: 0.1952630	test: 0.2094585	best: 0.2094585 (3640)	total: 1m 7s	remaining: 29.7s
3660:	learn: 0.1951299	test: 0.2093999	best: 0.2093999 (3660)	total: 1m 8s	remaining: 29.3s
3680:	learn: 0.1950035	test: 0.2093754	best: 0.2093754 (3680)	total: 1m 8s	remaining: 28.9s
3700:	learn: 0.1948876	test: 0.2093505	best: 0.2093499 (3699)	total: 1m 8s	remaining: 28.6s
3720:	learn: 0.1947648	test: 0.2093196	best: 0.2093156 (3716)	total: 1m 9s	remaining: 28.2s
3740:	learn: 0.1946577	test: 0.2093010	best: 0.2093005 (3735)	total: 1m 9s	remaining: 27.9s
3760:	learn: 0.1945219	test: 0.2092550	best: 0.2092550 (3760)	total: 1m 10s	remaining: 27.5s
3780:	learn: 0.1944031	test: 0.2092254	best: 0.2092254 (3780)	total: 1m 10s	remaining: 27.1s
3800:	learn: 0.1942851	test: 0.2091871	best: 0.2091871 (3800)	total: 1m 10s	remaining: 26.8s
3820:	learn: 0.1941678	test: 0.2091373	best: 0.2091373 (3820)	total: 1m 11s	remaining: 26.4s
3840:	learn: 0.1940273	test: 0.2090765	best: 0.2090765 (3840)	total: 1m 11s	remaining: 26s
3860:	learn: 0.1939288	test: 0.2090536	best: 0.2090536 (3860)	total: 1m 12s	remaining: 25.7s
3880:	learn: 0.1938167	test: 0.2090185	best: 0.2090183 (3878)	total: 1m 12s	remaining: 25.3s
3900:	learn: 0.1936961	test: 0.2089775	best: 0.2089775 (3900)	total: 1m 12s	remaining: 25s
3920:	learn: 0.1935923	test: 0.2089587	best: 0.2089584 (3919)	total: 1m 13s	remaining: 24.6s
3940:	learn: 0.1934691	test: 0.2089385	best: 0.2089385 (3940)	total: 1m 13s	remaining: 24.2s
3960:	learn: 0.1933506	test: 0.2089051	best: 0.2089036 (3959)	total: 1m 14s	remaining: 23.9s
3980:	learn: 0.1932242	test: 0.2088737	best: 0.2088666 (3979)	total: 1m 14s	remaining: 23.5s
4000:	learn: 0.1931070	test: 0.2088155	best: 0.2088155 (4000)	total: 1m 14s	remaining: 23.1s
4020:	learn: 0.1929855	test: 0.2087752	best: 0.2087752 (4020)	total: 1m 15s	remaining: 22.8s
4040:	learn: 0.1928793	test: 0.2087505	best: 0.2087505 (4040)	total: 1m 15s	remaining: 22.4s
4060:	learn: 0.1927550	test: 0.2087062	best: 0.2087062 (4060)	total: 1m 16s	remaining: 22s
4080:	learn: 0.1926483	test: 0.2086898	best: 0.2086888 (4078)	total: 1m 16s	remaining: 21.7s
4100:	learn: 0.1925523	test: 0.2086669	best: 0.2086659 (4099)	total: 1m 16s	remaining: 21.3s
4120:	learn: 0.1924188	test: 0.2085940	best: 0.2085940 (4120)	total: 1m 17s	remaining: 20.9s
4140:	learn: 0.1923234	test: 0.2085590	best: 0.2085564 (4138)	total: 1m 17s	remaining: 20.5s
4160:	learn: 0.1922024	test: 0.2085316	best: 0.2085316 (4160)	total: 1m 18s	remaining: 20.2s
4180:	learn: 0.1920836	test: 0.2084973	best: 0.2084973 (4180)	total: 1m 18s	remaining: 19.8s
4200:	learn: 0.1919827	test: 0.2084879	best: 0.2084874 (4199)	total: 1m 18s	remaining: 19.4s
4220:	learn: 0.1918717	test: 0.2084565	best: 0.2084565 (4220)	total: 1m 19s	remaining: 19.1s
4240:	learn: 0.1917710	test: 0.2084415	best: 0.2084412 (4239)	total: 1m 19s	remaining: 18.7s
4260:	learn: 0.1916553	test: 0.2084154	best: 0.2084140 (4258)	total: 1m 20s	remaining: 18.3s
4280:	learn: 0.1915284	test: 0.2083876	best: 0.2083876 (4280)	total: 1m 20s	remaining: 17.9s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404037	test: 0.6404534	best: 0.6404534 (0)	total: 10.3ms	remaining: 10.3ms
1:	learn: 0.5954137	test: 0.5955397	best: 0.5955397 (1)	total: 19.8ms	remaining: 0us
bestTest = 0.5955396611
bestIteration = 1
0:	learn: 0.6415008	test: 0.6416794	best: 0.6416794 (0)	total: 18.2ms	remaining: 1m 32s
20:	learn: 0.3354649	test: 0.3357592	best: 0.3357592 (20)	total: 425ms	remaining: 1m 42s
40:	learn: 0.3034884	test: 0.3039689	best: 0.3039689 (40)	total: 833ms	remaining: 1m 42s
60:	learn: 0.2889849	test: 0.2886768	best: 0.2886768 (60)	total: 1.26s	remaining: 1m 43s
80:	learn: 0.2806223	test: 0.2800063	best: 0.2800063 (80)	total: 1.65s	remaining: 1m 42s
100:	learn: 0.2757453	test: 0.2750205	best: 0.2750205 (100)	total: 2.03s	remaining: 1m 40s
120:	learn: 0.2705225	test: 0.2694922	best: 0.2694922 (120)	total: 2.43s	remaining: 1m 39s
140:	learn: 0.2661250	test: 0.2648725	best: 0.2648725 (140)	total: 2.84s	remaining: 1m 39s
160:	learn: 0.2628900	test: 0.2615108	best: 0.2615108 (160)	total: 3.22s	remaining: 1m 38s
180:	learn: 0.2594920	test: 0.2578919	best: 0.2578919 (180)	total: 3.61s	remaining: 1m 37s
200:	learn: 0.2567380	test: 0.2550806	best: 0.2550806 (200)	total: 3.98s	remaining: 1m 36s
220:	learn: 0.2537299	test: 0.2518648	best: 0.2518648 (220)	total: 4.38s	remaining: 1m 36s
240:	learn: 0.2516617	test: 0.2497582	best: 0.2497582 (240)	total: 4.77s	remaining: 1m 35s
260:	learn: 0.2499097	test: 0.2480525	best: 0.2480525 (260)	total: 5.16s	remaining: 1m 35s
280:	learn: 0.2482890	test: 0.2464685	best: 0.2464685 (280)	total: 5.56s	remaining: 1m 35s
300:	learn: 0.2464441	test: 0.2445561	best: 0.2445561 (300)	total: 5.95s	remaining: 1m 34s
320:	learn: 0.2449176	test: 0.2430478	best: 0.2430478 (320)	total: 6.35s	remaining: 1m 34s
340:	learn: 0.2435140	test: 0.2417241	best: 0.2417241 (340)	total: 6.74s	remaining: 1m 33s
360:	learn: 0.2422022	test: 0.2404393	best: 0.2404393 (360)	total: 7.13s	remaining: 1m 33s
380:	learn: 0.2410647	test: 0.2393766	best: 0.2393766 (380)	total: 7.51s	remaining: 1m 32s
400:	learn: 0.2399708	test: 0.2383772	best: 0.2383772 (400)	total: 7.88s	remaining: 1m 32s
420:	learn: 0.2389119	test: 0.2373546	best: 0.2373546 (420)	total: 8.28s	remaining: 1m 31s
440:	learn: 0.2379225	test: 0.2364035	best: 0.2364035 (440)	total: 8.66s	remaining: 1m 31s
460:	learn: 0.2369475	test: 0.2355075	best: 0.2355075 (460)	total: 9.05s	remaining: 1m 30s
480:	learn: 0.2359225	test: 0.2345153	best: 0.2345153 (480)	total: 9.45s	remaining: 1m 30s
500:	learn: 0.2349875	test: 0.2336653	best: 0.2336653 (500)	total: 9.82s	remaining: 1m 29s
520:	learn: 0.2342539	test: 0.2330665	best: 0.2330665 (520)	total: 10.2s	remaining: 1m 29s
540:	learn: 0.2334783	test: 0.2323408	best: 0.2323408 (540)	total: 10.6s	remaining: 1m 28s
560:	learn: 0.2327376	test: 0.2317049	best: 0.2317049 (560)	total: 10.9s	remaining: 1m 28s
580:	learn: 0.2321049	test: 0.2311540	best: 0.2311540 (580)	total: 11.3s	remaining: 1m 27s
600:	learn: 0.2314130	test: 0.2305778	best: 0.2305778 (600)	total: 11.7s	remaining: 1m 27s
620:	learn: 0.2307682	test: 0.2300439	best: 0.2300439 (620)	total: 12.1s	remaining: 1m 26s
640:	learn: 0.2301113	test: 0.2294450	best: 0.2294450 (640)	total: 12.5s	remaining: 1m 26s
660:	learn: 0.2295194	test: 0.2289391	best: 0.2289391 (660)	total: 12.9s	remaining: 1m 26s
680:	learn: 0.2288857	test: 0.2283964	best: 0.2283964 (680)	total: 13.2s	remaining: 1m 25s
700:	learn: 0.2282612	test: 0.2278806	best: 0.2278806 (700)	total: 13.6s	remaining: 1m 25s
720:	learn: 0.2276298	test: 0.2273250	best: 0.2273250 (720)	total: 14s	remaining: 1m 24s
740:	learn: 0.2269720	test: 0.2267289	best: 0.2267289 (740)	total: 14.4s	remaining: 1m 24s
760:	learn: 0.2263901	test: 0.2262510	best: 0.2262510 (760)	total: 14.7s	remaining: 1m 23s
780:	learn: 0.2257618	test: 0.2256218	best: 0.2256218 (780)	total: 15.1s	remaining: 1m 23s
800:	learn: 0.2253275	test: 0.2252981	best: 0.2252981 (800)	total: 15.5s	remaining: 1m 22s
820:	learn: 0.2249133	test: 0.2249830	best: 0.2249830 (820)	total: 15.9s	remaining: 1m 22s
840:	learn: 0.2244278	test: 0.2245662	best: 0.2245662 (840)	total: 16.3s	remaining: 1m 22s
860:	learn: 0.2239621	test: 0.2242014	best: 0.2242014 (860)	total: 16.6s	remaining: 1m 21s
880:	learn: 0.2235713	test: 0.2238995	best: 0.2238995 (880)	total: 17s	remaining: 1m 21s
900:	learn: 0.2231683	test: 0.2235852	best: 0.2235852 (900)	total: 17.4s	remaining: 1m 20s
920:	learn: 0.2227404	test: 0.2232246	best: 0.2232246 (920)	total: 17.8s	remaining: 1m 20s
940:	learn: 0.2222869	test: 0.2228490	best: 0.2228490 (940)	total: 18.2s	remaining: 1m 20s
960:	learn: 0.2219169	test: 0.2225662	best: 0.2225662 (960)	total: 18.6s	remaining: 1m 19s
980:	learn: 0.2215122	test: 0.2222498	best: 0.2222498 (980)	total: 18.9s	remaining: 1m 19s
1000:	learn: 0.2211140	test: 0.2219281	best: 0.2219281 (1000)	total: 19.3s	remaining: 1m 18s
1020:	learn: 0.2207319	test: 0.2216418	best: 0.2216418 (1020)	total: 19.7s	remaining: 1m 18s
1040:	learn: 0.2203705	test: 0.2214251	best: 0.2214251 (1040)	total: 20.1s	remaining: 1m 17s
1060:	learn: 0.2200134	test: 0.2211669	best: 0.2211669 (1060)	total: 20.4s	remaining: 1m 17s
1080:	learn: 0.2196810	test: 0.2209307	best: 0.2209307 (1080)	total: 20.8s	remaining: 1m 17s
1100:	learn: 0.2193220	test: 0.2206843	best: 0.2206843 (1100)	total: 21.2s	remaining: 1m 16s
1120:	learn: 0.2190102	test: 0.2204928	best: 0.2204928 (1120)	total: 21.6s	remaining: 1m 16s
1140:	learn: 0.2186644	test: 0.2202437	best: 0.2202437 (1140)	total: 22s	remaining: 1m 15s
1160:	learn: 0.2183055	test: 0.2199719	best: 0.2199719 (1160)	total: 22.3s	remaining: 1m 15s
1180:	learn: 0.2179874	test: 0.2197600	best: 0.2197600 (1180)	total: 22.7s	remaining: 1m 15s
1200:	learn: 0.2176471	test: 0.2194977	best: 0.2194977 (1200)	total: 23.1s	remaining: 1m 14s
1220:	learn: 0.2173580	test: 0.2193325	best: 0.2193325 (1220)	total: 23.5s	remaining: 1m 14s
1240:	learn: 0.2170147	test: 0.2190764	best: 0.2190764 (1240)	total: 23.9s	remaining: 1m 13s
1260:	learn: 0.2167372	test: 0.2188872	best: 0.2188872 (1260)	total: 24.2s	remaining: 1m 13s
1280:	learn: 0.2163831	test: 0.2186290	best: 0.2186290 (1280)	total: 24.6s	remaining: 1m 13s
1300:	learn: 0.2161320	test: 0.2184750	best: 0.2184750 (1300)	total: 25s	remaining: 1m 12s
1320:	learn: 0.2158754	test: 0.2183220	best: 0.2183220 (1320)	total: 25.4s	remaining: 1m 12s
1340:	learn: 0.2156191	test: 0.2181788	best: 0.2181788 (1340)	total: 25.7s	remaining: 1m 11s
1360:	learn: 0.2152962	test: 0.2179513	best: 0.2179513 (1360)	total: 26.1s	remaining: 1m 11s
1380:	learn: 0.2150224	test: 0.2178002	best: 0.2178002 (1380)	total: 26.5s	remaining: 1m 11s
1400:	learn: 0.2146984	test: 0.2175581	best: 0.2175581 (1400)	total: 26.9s	remaining: 1m 10s
1420:	learn: 0.2144209	test: 0.2173779	best: 0.2173779 (1420)	total: 27.2s	remaining: 1m 10s
1440:	learn: 0.2141275	test: 0.2171768	best: 0.2171768 (1440)	total: 27.6s	remaining: 1m 9s
1460:	learn: 0.2138825	test: 0.2170087	best: 0.2170087 (1460)	total: 28s	remaining: 1m 9s
1480:	learn: 0.2136462	test: 0.2168766	best: 0.2168766 (1480)	total: 28.4s	remaining: 1m 9s
1500:	learn: 0.2134463	test: 0.2167697	best: 0.2167697 (1500)	total: 28.8s	remaining: 1m 8s
1520:	learn: 0.2132320	test: 0.2166598	best: 0.2166598 (1520)	total: 29.1s	remaining: 1m 8s
1540:	learn: 0.2130063	test: 0.2165257	best: 0.2165257 (1540)	total: 29.5s	remaining: 1m 7s
1560:	learn: 0.2126847	test: 0.2162903	best: 0.2162903 (1560)	total: 29.9s	remaining: 1m 7s
1580:	learn: 0.2124562	test: 0.2161547	best: 0.2161547 (1580)	total: 30.3s	remaining: 1m 7s
1600:	learn: 0.2122537	test: 0.2160353	best: 0.2160353 (1600)	total: 30.7s	remaining: 1m 6s
1620:	learn: 0.2120365	test: 0.2158962	best: 0.2158962 (1620)	total: 31s	remaining: 1m 6s
1640:	learn: 0.2117787	test: 0.2157499	best: 0.2157499 (1640)	total: 31.4s	remaining: 1m 5s
1660:	learn: 0.2115850	test: 0.2156430	best: 0.2156430 (1660)	total: 31.8s	remaining: 1m 5s
1680:	learn: 0.2113730	test: 0.2155137	best: 0.2155137 (1680)	total: 32.2s	remaining: 1m 5s
1700:	learn: 0.2111441	test: 0.2153797	best: 0.2153797 (1700)	total: 32.6s	remaining: 1m 4s
1720:	learn: 0.2109496	test: 0.2152864	best: 0.2152864 (1720)	total: 33s	remaining: 1m 4s
1740:	learn: 0.2107751	test: 0.2152020	best: 0.2152020 (1740)	total: 33.4s	remaining: 1m 4s
1760:	learn: 0.2105508	test: 0.2150525	best: 0.2150525 (1760)	total: 33.7s	remaining: 1m 3s
1780:	learn: 0.2103315	test: 0.2149095	best: 0.2149082 (1778)	total: 34.1s	remaining: 1m 3s
1800:	learn: 0.2101226	test: 0.2147865	best: 0.2147865 (1800)	total: 34.5s	remaining: 1m 2s
1820:	learn: 0.2098944	test: 0.2146538	best: 0.2146538 (1820)	total: 34.9s	remaining: 1m 2s
1840:	learn: 0.2096854	test: 0.2145399	best: 0.2145399 (1840)	total: 35.3s	remaining: 1m 2s
1860:	learn: 0.2094806	test: 0.2144486	best: 0.2144486 (1860)	total: 35.7s	remaining: 1m 1s
1880:	learn: 0.2093094	test: 0.2143613	best: 0.2143612 (1879)	total: 36s	remaining: 1m 1s
1900:	learn: 0.2091424	test: 0.2142866	best: 0.2142866 (1900)	total: 36.4s	remaining: 1m 1s
1920:	learn: 0.2089444	test: 0.2141806	best: 0.2141806 (1920)	total: 36.8s	remaining: 1m
1940:	learn: 0.2087604	test: 0.2141002	best: 0.2140999 (1939)	total: 37.2s	remaining: 1m
1960:	learn: 0.2086130	test: 0.2140361	best: 0.2140361 (1960)	total: 37.6s	remaining: 60s
1980:	learn: 0.2084131	test: 0.2139311	best: 0.2139311 (1980)	total: 38s	remaining: 59.6s
2000:	learn: 0.2081795	test: 0.2137653	best: 0.2137653 (2000)	total: 38.4s	remaining: 59.2s
2020:	learn: 0.2079878	test: 0.2136685	best: 0.2136685 (2020)	total: 38.8s	remaining: 58.8s
2040:	learn: 0.2077919	test: 0.2135805	best: 0.2135789 (2037)	total: 39.2s	remaining: 58.5s
2060:	learn: 0.2076376	test: 0.2135135	best: 0.2135135 (2060)	total: 39.6s	remaining: 58.1s
2080:	learn: 0.2074266	test: 0.2134271	best: 0.2134271 (2080)	total: 40s	remaining: 57.7s
2100:	learn: 0.2071890	test: 0.2132360	best: 0.2132360 (2100)	total: 40.3s	remaining: 57.3s
2120:	learn: 0.2070127	test: 0.2131305	best: 0.2131305 (2120)	total: 40.7s	remaining: 57s
2140:	learn: 0.2068342	test: 0.2130453	best: 0.2130453 (2140)	total: 41.1s	remaining: 56.6s
2160:	learn: 0.2066814	test: 0.2129748	best: 0.2129748 (2160)	total: 41.5s	remaining: 56.2s
2180:	learn: 0.2065068	test: 0.2129122	best: 0.2129122 (2180)	total: 41.9s	remaining: 55.8s
2200:	learn: 0.2063507	test: 0.2128523	best: 0.2128523 (2200)	total: 42.3s	remaining: 55.4s
2220:	learn: 0.2061740	test: 0.2127707	best: 0.2127707 (2220)	total: 42.6s	remaining: 55s
2240:	learn: 0.2059819	test: 0.2126718	best: 0.2126703 (2239)	total: 43s	remaining: 54.6s
2260:	learn: 0.2058014	test: 0.2125784	best: 0.2125770 (2259)	total: 43.4s	remaining: 54.3s
2280:	learn: 0.2056442	test: 0.2124861	best: 0.2124861 (2280)	total: 43.8s	remaining: 53.9s
2300:	learn: 0.2054606	test: 0.2123777	best: 0.2123777 (2300)	total: 44.2s	remaining: 53.5s
2320:	learn: 0.2052886	test: 0.2123065	best: 0.2123065 (2320)	total: 44.6s	remaining: 53.1s
2340:	learn: 0.2051219	test: 0.2122334	best: 0.2122334 (2340)	total: 45s	remaining: 52.7s
2360:	learn: 0.2049532	test: 0.2121738	best: 0.2121698 (2359)	total: 45.3s	remaining: 52.3s
2380:	learn: 0.2047714	test: 0.2120691	best: 0.2120691 (2380)	total: 45.7s	remaining: 52s
2400:	learn: 0.2046040	test: 0.2119799	best: 0.2119799 (2400)	total: 46.1s	remaining: 51.6s
2420:	learn: 0.2044570	test: 0.2119175	best: 0.2119174 (2419)	total: 46.5s	remaining: 51.2s
2440:	learn: 0.2042541	test: 0.2117763	best: 0.2117763 (2440)	total: 46.9s	remaining: 50.8s
2460:	learn: 0.2040740	test: 0.2116782	best: 0.2116782 (2460)	total: 47.3s	remaining: 50.5s
2480:	learn: 0.2038986	test: 0.2116013	best: 0.2116013 (2480)	total: 47.7s	remaining: 50.1s
2500:	learn: 0.2037425	test: 0.2115528	best: 0.2115516 (2499)	total: 48.1s	remaining: 49.7s
2520:	learn: 0.2035546	test: 0.2114366	best: 0.2114366 (2520)	total: 48.5s	remaining: 49.3s
2540:	learn: 0.2034269	test: 0.2113994	best: 0.2113994 (2540)	total: 48.9s	remaining: 49s
2560:	learn: 0.2032519	test: 0.2113128	best: 0.2113128 (2560)	total: 49.3s	remaining: 48.6s
2580:	learn: 0.2031008	test: 0.2112371	best: 0.2112371 (2580)	total: 49.7s	remaining: 48.2s
2600:	learn: 0.2029318	test: 0.2111610	best: 0.2111610 (2600)	total: 50s	remaining: 47.8s
2620:	learn: 0.2027930	test: 0.2110882	best: 0.2110882 (2620)	total: 50.4s	remaining: 47.4s
2640:	learn: 0.2026544	test: 0.2110421	best: 0.2110421 (2640)	total: 50.8s	remaining: 47.1s
2660:	learn: 0.2025180	test: 0.2109903	best: 0.2109903 (2660)	total: 51.2s	remaining: 46.7s
2680:	learn: 0.2023712	test: 0.2109509	best: 0.2109509 (2680)	total: 51.6s	remaining: 46.3s
2700:	learn: 0.2022366	test: 0.2108992	best: 0.2108992 (2700)	total: 52s	remaining: 45.9s
2720:	learn: 0.2020192	test: 0.2107687	best: 0.2107687 (2720)	total: 52.4s	remaining: 45.5s
2740:	learn: 0.2018613	test: 0.2107101	best: 0.2107093 (2739)	total: 52.7s	remaining: 45.1s
2760:	learn: 0.2017206	test: 0.2106549	best: 0.2106549 (2760)	total: 53.1s	remaining: 44.8s
2780:	learn: 0.2015431	test: 0.2105524	best: 0.2105524 (2780)	total: 53.5s	remaining: 44.4s
2800:	learn: 0.2013884	test: 0.2104723	best: 0.2104723 (2800)	total: 53.9s	remaining: 44s
2820:	learn: 0.2012553	test: 0.2103868	best: 0.2103868 (2820)	total: 54.3s	remaining: 43.6s
2840:	learn: 0.2011232	test: 0.2103347	best: 0.2103347 (2840)	total: 54.7s	remaining: 43.2s
2860:	learn: 0.2009750	test: 0.2102619	best: 0.2102619 (2860)	total: 55s	remaining: 42.8s
2880:	learn: 0.2008435	test: 0.2102094	best: 0.2102094 (2880)	total: 55.4s	remaining: 42.4s
2900:	learn: 0.2006898	test: 0.2101550	best: 0.2101550 (2900)	total: 55.8s	remaining: 42.1s
2920:	learn: 0.2005641	test: 0.2100923	best: 0.2100901 (2919)	total: 56.2s	remaining: 41.7s
2940:	learn: 0.2004279	test: 0.2100424	best: 0.2100424 (2940)	total: 56.6s	remaining: 41.3s
2960:	learn: 0.2002729	test: 0.2099848	best: 0.2099797 (2955)	total: 57s	remaining: 40.9s
2980:	learn: 0.2001282	test: 0.2099342	best: 0.2099342 (2980)	total: 57.4s	remaining: 40.6s
3000:	learn: 0.1999950	test: 0.2098808	best: 0.2098808 (3000)	total: 57.8s	remaining: 40.2s
3020:	learn: 0.1998573	test: 0.2098241	best: 0.2098241 (3020)	total: 58.2s	remaining: 39.8s
3040:	learn: 0.1997183	test: 0.2097941	best: 0.2097940 (3038)	total: 58.6s	remaining: 39.4s
3060:	learn: 0.1995728	test: 0.2097305	best: 0.2097305 (3060)	total: 59s	remaining: 39s
3080:	learn: 0.1994443	test: 0.2097148	best: 0.2097107 (3075)	total: 59.4s	remaining: 38.6s
3100:	learn: 0.1992891	test: 0.2096318	best: 0.2096318 (3100)	total: 59.8s	remaining: 38.3s
3120:	learn: 0.1991684	test: 0.2095871	best: 0.2095871 (3120)	total: 1m	remaining: 37.9s
3140:	learn: 0.1990346	test: 0.2095522	best: 0.2095488 (3137)	total: 1m	remaining: 37.5s
3160:	learn: 0.1989035	test: 0.2094925	best: 0.2094924 (3159)	total: 1m	remaining: 37.1s
3180:	learn: 0.1987594	test: 0.2094277	best: 0.2094277 (3180)	total: 1m 1s	remaining: 36.7s
3200:	learn: 0.1986383	test: 0.2093999	best: 0.2093999 (3200)	total: 1m 1s	remaining: 36.4s
3220:	learn: 0.1985215	test: 0.2093640	best: 0.2093640 (3220)	total: 1m 2s	remaining: 36s
3240:	learn: 0.1983806	test: 0.2093167	best: 0.2093167 (3240)	total: 1m 2s	remaining: 35.6s
3260:	learn: 0.1982589	test: 0.2092665	best: 0.2092665 (3260)	total: 1m 2s	remaining: 35.2s
3280:	learn: 0.1981270	test: 0.2092205	best: 0.2092205 (3280)	total: 1m 3s	remaining: 34.8s
3300:	learn: 0.1979947	test: 0.2091741	best: 0.2091741 (3300)	total: 1m 3s	remaining: 34.4s
3320:	learn: 0.1978831	test: 0.2091424	best: 0.2091424 (3320)	total: 1m 4s	remaining: 34.1s
3340:	learn: 0.1977221	test: 0.2090792	best: 0.2090792 (3340)	total: 1m 4s	remaining: 33.7s
3360:	learn: 0.1975852	test: 0.2090374	best: 0.2090374 (3360)	total: 1m 4s	remaining: 33.3s
3380:	learn: 0.1974454	test: 0.2089564	best: 0.2089564 (3380)	total: 1m 5s	remaining: 32.9s
3400:	learn: 0.1973183	test: 0.2089118	best: 0.2089118 (3400)	total: 1m 5s	remaining: 32.5s
3420:	learn: 0.1971799	test: 0.2088627	best: 0.2088627 (3420)	total: 1m 5s	remaining: 32.1s
3440:	learn: 0.1970414	test: 0.2088143	best: 0.2088143 (3440)	total: 1m 6s	remaining: 31.7s
3460:	learn: 0.1969155	test: 0.2087841	best: 0.2087809 (3454)	total: 1m 6s	remaining: 31.4s
3480:	learn: 0.1967891	test: 0.2087458	best: 0.2087458 (3480)	total: 1m 7s	remaining: 31s
3500:	learn: 0.1966758	test: 0.2087276	best: 0.2087276 (3500)	total: 1m 7s	remaining: 30.6s
3520:	learn: 0.1965546	test: 0.2086967	best: 0.2086967 (3520)	total: 1m 7s	remaining: 30.2s
3540:	learn: 0.1964205	test: 0.2086555	best: 0.2086555 (3540)	total: 1m 8s	remaining: 29.8s
3560:	learn: 0.1962973	test: 0.2086332	best: 0.2086332 (3560)	total: 1m 8s	remaining: 29.4s
3580:	learn: 0.1961581	test: 0.2085710	best: 0.2085707 (3578)	total: 1m 9s	remaining: 29.1s
3600:	learn: 0.1960387	test: 0.2085274	best: 0.2085265 (3599)	total: 1m 9s	remaining: 28.7s
3620:	learn: 0.1959110	test: 0.2084528	best: 0.2084528 (3620)	total: 1m 9s	remaining: 28.3s
3640:	learn: 0.1958005	test: 0.2084296	best: 0.2084273 (3638)	total: 1m 10s	remaining: 27.9s
3660:	learn: 0.1956441	test: 0.2083552	best: 0.2083552 (3660)	total: 1m 10s	remaining: 27.5s
3680:	learn: 0.1955229	test: 0.2083122	best: 0.2083122 (3680)	total: 1m 11s	remaining: 27.1s
3700:	learn: 0.1953924	test: 0.2082688	best: 0.2082688 (3700)	total: 1m 11s	remaining: 26.8s
3720:	learn: 0.1952515	test: 0.2082200	best: 0.2082200 (3720)	total: 1m 11s	remaining: 26.4s
3740:	learn: 0.1951482	test: 0.2081991	best: 0.2081971 (3739)	total: 1m 12s	remaining: 26s
3760:	learn: 0.1950240	test: 0.2081665	best: 0.2081665 (3760)	total: 1m 12s	remaining: 25.6s
3780:	learn: 0.1949057	test: 0.2081247	best: 0.2081239 (3778)	total: 1m 13s	remaining: 25.2s
3800:	learn: 0.1947786	test: 0.2080962	best: 0.2080956 (3799)	total: 1m 13s	remaining: 24.8s
3820:	learn: 0.1946800	test: 0.2080765	best: 0.2080761 (3817)	total: 1m 13s	remaining: 24.5s
3840:	learn: 0.1945610	test: 0.2080322	best: 0.2080322 (3840)	total: 1m 14s	remaining: 24.1s
3860:	learn: 0.1944296	test: 0.2079759	best: 0.2079759 (3860)	total: 1m 14s	remaining: 23.7s
3880:	learn: 0.1943247	test: 0.2079447	best: 0.2079447 (3880)	total: 1m 15s	remaining: 23.3s
3900:	learn: 0.1942107	test: 0.2079380	best: 0.2079332 (3893)	total: 1m 15s	remaining: 22.9s
3920:	learn: 0.1940967	test: 0.2078893	best: 0.2078893 (3918)	total: 1m 15s	remaining: 22.5s
3940:	learn: 0.1939965	test: 0.2078698	best: 0.2078697 (3937)	total: 1m 16s	remaining: 22.2s
3960:	learn: 0.1938770	test: 0.2078459	best: 0.2078459 (3960)	total: 1m 16s	remaining: 21.8s
3980:	learn: 0.1937767	test: 0.2078118	best: 0.2078118 (3980)	total: 1m 17s	remaining: 21.4s
4000:	learn: 0.1936812	test: 0.2077650	best: 0.2077650 (4000)	total: 1m 17s	remaining: 21s
4020:	learn: 0.1935630	test: 0.2077400	best: 0.2077400 (4020)	total: 1m 17s	remaining: 20.6s
4040:	learn: 0.1934602	test: 0.2077093	best: 0.2077074 (4039)	total: 1m 18s	remaining: 20.2s
4060:	learn: 0.1933496	test: 0.2076732	best: 0.2076732 (4060)	total: 1m 18s	remaining: 19.9s
4080:	learn: 0.1932435	test: 0.2076612	best: 0.2076575 (4076)	total: 1m 19s	remaining: 19.5s
4100:	learn: 0.1931324	test: 0.2076337	best: 0.2076337 (4100)	total: 1m 19s	remaining: 19.1s
4120:	learn: 0.1930158	test: 0.2076003	best: 0.2075949 (4117)	total: 1m 19s	remaining: 18.7s
4140:	learn: 0.1929158	test: 0.2075613	best: 0.2075613 (4140)	total: 1m 20s	remaining: 18.3s
4160:	learn: 0.1927980	test: 0.2075121	best: 0.2075119 (4158)	total: 1m 20s	remaining: 17.9s
4180:	learn: 0.1926956	test: 0.2074998	best: 0.2074998 (4180)	total: 1m 20s	remaining: 17.6s
4200:	learn: 0.1926007	test: 0.2074685	best: 0.2074685 (4200)	total: 1m 21s	remaining: 17.2s
4220:	learn: 0.1924830	test: 0.2074353	best: 0.2074353 (4220)	total: 1m 21s	remaining: 16.8s
4240:	learn: 0.1923982	test: 0.2074243	best: 0.2074243 (4238)	total: 1m 22s	remaining: 16.4s
4260:	learn: 0.1922957	test: 0.2074001	best: 0.2074000 (4256)	total: 1m 22s	remaining: 16s
4280:	learn: 0.1921838	test: 0.2073792	best: 0.2073792 (4280)	total: 1m 22s	remaining: 15.6s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404743	test: 0.6403642	best: 0.6403642 (0)	total: 10.5ms	remaining: 10.5ms
1:	learn: 0.5956634	test: 0.5954553	best: 0.5954553 (1)	total: 19.8ms	remaining: 0us
bestTest = 0.5954553234
bestIteration = 1
0:	learn: 0.6414895	test: 0.6415848	best: 0.6415848 (0)	total: 17.6ms	remaining: 1m 30s
20:	learn: 0.3356115	test: 0.3353667	best: 0.3353667 (20)	total: 430ms	remaining: 1m 45s
40:	learn: 0.3013331	test: 0.3011654	best: 0.3011654 (40)	total: 831ms	remaining: 1m 44s
60:	learn: 0.2888285	test: 0.2887042	best: 0.2887042 (60)	total: 1.24s	remaining: 1m 44s
80:	learn: 0.2813242	test: 0.2809693	best: 0.2809693 (80)	total: 1.64s	remaining: 1m 43s
100:	learn: 0.2759514	test: 0.2753586	best: 0.2753586 (100)	total: 2.03s	remaining: 1m 41s
120:	learn: 0.2709104	test: 0.2702431	best: 0.2702431 (120)	total: 2.42s	remaining: 1m 41s
140:	learn: 0.2671970	test: 0.2664994	best: 0.2664994 (140)	total: 2.81s	remaining: 1m 40s
160:	learn: 0.2631126	test: 0.2622503	best: 0.2622503 (160)	total: 3.18s	remaining: 1m 39s
180:	learn: 0.2599670	test: 0.2590268	best: 0.2590268 (180)	total: 3.57s	remaining: 1m 38s
200:	learn: 0.2575953	test: 0.2567659	best: 0.2567659 (200)	total: 3.96s	remaining: 1m 37s
220:	learn: 0.2547099	test: 0.2537195	best: 0.2537195 (220)	total: 4.34s	remaining: 1m 37s
240:	learn: 0.2523372	test: 0.2512267	best: 0.2512267 (240)	total: 4.73s	remaining: 1m 36s
260:	learn: 0.2506936	test: 0.2495572	best: 0.2495572 (260)	total: 5.13s	remaining: 1m 36s
280:	learn: 0.2487013	test: 0.2475895	best: 0.2475895 (280)	total: 5.51s	remaining: 1m 35s
300:	learn: 0.2471729	test: 0.2460954	best: 0.2460954 (300)	total: 5.88s	remaining: 1m 35s
320:	learn: 0.2455758	test: 0.2445574	best: 0.2445574 (320)	total: 6.27s	remaining: 1m 34s
340:	learn: 0.2440504	test: 0.2431043	best: 0.2431043 (340)	total: 6.66s	remaining: 1m 34s
360:	learn: 0.2427471	test: 0.2419068	best: 0.2419068 (360)	total: 7.04s	remaining: 1m 33s
380:	learn: 0.2414275	test: 0.2405561	best: 0.2405561 (380)	total: 7.42s	remaining: 1m 33s
400:	learn: 0.2401075	test: 0.2392008	best: 0.2392008 (400)	total: 7.82s	remaining: 1m 33s
420:	learn: 0.2386844	test: 0.2377163	best: 0.2377163 (420)	total: 8.22s	remaining: 1m 32s
440:	learn: 0.2375401	test: 0.2365552	best: 0.2365552 (440)	total: 8.61s	remaining: 1m 32s
460:	learn: 0.2367088	test: 0.2358536	best: 0.2358536 (460)	total: 8.99s	remaining: 1m 31s
480:	learn: 0.2359669	test: 0.2352364	best: 0.2352364 (480)	total: 9.38s	remaining: 1m 31s
500:	learn: 0.2349908	test: 0.2343423	best: 0.2343423 (500)	total: 9.76s	remaining: 1m 31s
520:	learn: 0.2340852	test: 0.2334932	best: 0.2334932 (520)	total: 10.1s	remaining: 1m 30s
540:	learn: 0.2332846	test: 0.2328093	best: 0.2328093 (540)	total: 10.5s	remaining: 1m 30s
560:	learn: 0.2326951	test: 0.2323163	best: 0.2323163 (560)	total: 10.9s	remaining: 1m 29s
580:	learn: 0.2318636	test: 0.2316027	best: 0.2316027 (580)	total: 11.3s	remaining: 1m 29s
600:	learn: 0.2311742	test: 0.2309799	best: 0.2309799 (600)	total: 11.7s	remaining: 1m 28s
620:	learn: 0.2305268	test: 0.2304455	best: 0.2304455 (620)	total: 12.1s	remaining: 1m 28s
640:	learn: 0.2298536	test: 0.2298698	best: 0.2298698 (640)	total: 12.5s	remaining: 1m 28s
660:	learn: 0.2291272	test: 0.2292893	best: 0.2292893 (660)	total: 12.8s	remaining: 1m 27s
680:	learn: 0.2284743	test: 0.2287466	best: 0.2287466 (680)	total: 13.2s	remaining: 1m 27s
700:	learn: 0.2279040	test: 0.2282932	best: 0.2282932 (700)	total: 13.6s	remaining: 1m 26s
720:	learn: 0.2273701	test: 0.2278748	best: 0.2278748 (720)	total: 14s	remaining: 1m 26s
740:	learn: 0.2266857	test: 0.2273189	best: 0.2273189 (740)	total: 14.4s	remaining: 1m 26s
760:	learn: 0.2261310	test: 0.2268678	best: 0.2268678 (760)	total: 14.8s	remaining: 1m 25s
780:	learn: 0.2256916	test: 0.2265569	best: 0.2265569 (780)	total: 15.2s	remaining: 1m 25s
800:	learn: 0.2250742	test: 0.2260731	best: 0.2260731 (800)	total: 15.5s	remaining: 1m 24s
820:	learn: 0.2246085	test: 0.2256953	best: 0.2256953 (820)	total: 15.9s	remaining: 1m 24s
840:	learn: 0.2241755	test: 0.2253692	best: 0.2253692 (840)	total: 16.3s	remaining: 1m 24s
860:	learn: 0.2237618	test: 0.2250953	best: 0.2250953 (860)	total: 16.7s	remaining: 1m 23s
880:	learn: 0.2232332	test: 0.2247108	best: 0.2247108 (880)	total: 17.1s	remaining: 1m 23s
900:	learn: 0.2228251	test: 0.2243957	best: 0.2243957 (900)	total: 17.4s	remaining: 1m 22s
920:	learn: 0.2224394	test: 0.2241060	best: 0.2241060 (920)	total: 17.8s	remaining: 1m 22s
940:	learn: 0.2220940	test: 0.2238851	best: 0.2238851 (940)	total: 18.2s	remaining: 1m 21s
960:	learn: 0.2217084	test: 0.2235927	best: 0.2235927 (960)	total: 18.6s	remaining: 1m 21s
980:	learn: 0.2213350	test: 0.2233214	best: 0.2233214 (980)	total: 19s	remaining: 1m 21s
1000:	learn: 0.2209685	test: 0.2230608	best: 0.2230608 (1000)	total: 19.3s	remaining: 1m 20s
1020:	learn: 0.2206073	test: 0.2228268	best: 0.2228268 (1020)	total: 19.7s	remaining: 1m 20s
1040:	learn: 0.2202167	test: 0.2225779	best: 0.2225779 (1040)	total: 20.1s	remaining: 1m 19s
1060:	learn: 0.2198686	test: 0.2223397	best: 0.2223397 (1060)	total: 20.5s	remaining: 1m 19s
1080:	learn: 0.2195199	test: 0.2221212	best: 0.2221212 (1080)	total: 20.9s	remaining: 1m 19s
1100:	learn: 0.2191773	test: 0.2218617	best: 0.2218617 (1100)	total: 21.2s	remaining: 1m 18s
1120:	learn: 0.2189321	test: 0.2217173	best: 0.2217173 (1120)	total: 21.6s	remaining: 1m 18s
1140:	learn: 0.2186200	test: 0.2214873	best: 0.2214873 (1140)	total: 22s	remaining: 1m 17s
1160:	learn: 0.2182788	test: 0.2212599	best: 0.2212599 (1160)	total: 22.4s	remaining: 1m 17s
1180:	learn: 0.2178399	test: 0.2208977	best: 0.2208977 (1180)	total: 22.7s	remaining: 1m 16s
1200:	learn: 0.2175099	test: 0.2206612	best: 0.2206612 (1200)	total: 23.1s	remaining: 1m 16s
1220:	learn: 0.2172178	test: 0.2204892	best: 0.2204892 (1220)	total: 23.5s	remaining: 1m 16s
1240:	learn: 0.2169121	test: 0.2202607	best: 0.2202607 (1240)	total: 23.9s	remaining: 1m 15s
1260:	learn: 0.2165569	test: 0.2200495	best: 0.2200495 (1260)	total: 24.3s	remaining: 1m 15s
1280:	learn: 0.2161746	test: 0.2197595	best: 0.2197595 (1280)	total: 24.7s	remaining: 1m 15s
1300:	learn: 0.2159013	test: 0.2195843	best: 0.2195843 (1300)	total: 25s	remaining: 1m 14s
1320:	learn: 0.2156813	test: 0.2194902	best: 0.2194902 (1320)	total: 25.4s	remaining: 1m 14s
1340:	learn: 0.2154384	test: 0.2193619	best: 0.2193619 (1340)	total: 25.8s	remaining: 1m 13s
1360:	learn: 0.2151791	test: 0.2191980	best: 0.2191980 (1360)	total: 26.2s	remaining: 1m 13s
1380:	learn: 0.2149036	test: 0.2190342	best: 0.2190342 (1380)	total: 26.5s	remaining: 1m 12s
1400:	learn: 0.2146348	test: 0.2188749	best: 0.2188749 (1400)	total: 26.9s	remaining: 1m 12s
1420:	learn: 0.2143724	test: 0.2186453	best: 0.2186453 (1420)	total: 27.3s	remaining: 1m 12s
1440:	learn: 0.2141496	test: 0.2185109	best: 0.2185109 (1440)	total: 27.7s	remaining: 1m 11s
1460:	learn: 0.2139115	test: 0.2183769	best: 0.2183769 (1460)	total: 28.1s	remaining: 1m 11s
1480:	learn: 0.2136959	test: 0.2182444	best: 0.2182444 (1480)	total: 28.5s	remaining: 1m 11s
1500:	learn: 0.2133395	test: 0.2180092	best: 0.2180092 (1500)	total: 28.9s	remaining: 1m 10s
1520:	learn: 0.2130881	test: 0.2178512	best: 0.2178512 (1520)	total: 29.2s	remaining: 1m 10s
1540:	learn: 0.2128251	test: 0.2176699	best: 0.2176699 (1540)	total: 29.6s	remaining: 1m 9s
1560:	learn: 0.2126319	test: 0.2175819	best: 0.2175819 (1560)	total: 30s	remaining: 1m 9s
1580:	learn: 0.2123208	test: 0.2174059	best: 0.2174059 (1580)	total: 30.4s	remaining: 1m 9s
1600:	learn: 0.2120704	test: 0.2172503	best: 0.2172503 (1600)	total: 30.8s	remaining: 1m 8s
1620:	learn: 0.2118207	test: 0.2170785	best: 0.2170785 (1620)	total: 31.1s	remaining: 1m 8s
1640:	learn: 0.2115613	test: 0.2169206	best: 0.2169206 (1640)	total: 31.5s	remaining: 1m 7s
1660:	learn: 0.2113753	test: 0.2168369	best: 0.2168369 (1660)	total: 31.9s	remaining: 1m 7s
1680:	learn: 0.2111713	test: 0.2167451	best: 0.2167451 (1680)	total: 32.3s	remaining: 1m 7s
1700:	learn: 0.2109965	test: 0.2166864	best: 0.2166864 (1700)	total: 32.7s	remaining: 1m 6s
1720:	learn: 0.2107756	test: 0.2165519	best: 0.2165519 (1720)	total: 33.1s	remaining: 1m 6s
1740:	learn: 0.2105421	test: 0.2163981	best: 0.2163981 (1740)	total: 33.5s	remaining: 1m 6s
1760:	learn: 0.2103285	test: 0.2162747	best: 0.2162747 (1760)	total: 33.8s	remaining: 1m 5s
1780:	learn: 0.2100998	test: 0.2161500	best: 0.2161500 (1780)	total: 34.2s	remaining: 1m 5s
1800:	learn: 0.2099021	test: 0.2160479	best: 0.2160479 (1800)	total: 34.6s	remaining: 1m 4s
1820:	learn: 0.2096981	test: 0.2159533	best: 0.2159506 (1819)	total: 35s	remaining: 1m 4s
1840:	learn: 0.2094200	test: 0.2158058	best: 0.2158058 (1840)	total: 35.3s	remaining: 1m 4s
1860:	learn: 0.2092354	test: 0.2157215	best: 0.2157215 (1860)	total: 35.7s	remaining: 1m 3s
1880:	learn: 0.2090202	test: 0.2155956	best: 0.2155956 (1880)	total: 36.1s	remaining: 1m 3s
1900:	learn: 0.2088219	test: 0.2154970	best: 0.2154970 (1900)	total: 36.5s	remaining: 1m 2s
1920:	learn: 0.2085776	test: 0.2153610	best: 0.2153579 (1917)	total: 36.9s	remaining: 1m 2s
1940:	learn: 0.2083773	test: 0.2152613	best: 0.2152613 (1940)	total: 37.2s	remaining: 1m 2s
1960:	learn: 0.2081882	test: 0.2151902	best: 0.2151902 (1960)	total: 37.6s	remaining: 1m 1s
1980:	learn: 0.2079980	test: 0.2150952	best: 0.2150940 (1979)	total: 38s	remaining: 1m 1s
2000:	learn: 0.2078184	test: 0.2150415	best: 0.2150415 (2000)	total: 38.4s	remaining: 1m
2020:	learn: 0.2076423	test: 0.2149470	best: 0.2149470 (2020)	total: 38.8s	remaining: 1m
2040:	learn: 0.2074210	test: 0.2148033	best: 0.2148001 (2037)	total: 39.2s	remaining: 1m
2060:	learn: 0.2072339	test: 0.2147264	best: 0.2147256 (2059)	total: 39.5s	remaining: 59.8s
2080:	learn: 0.2070694	test: 0.2146719	best: 0.2146719 (2080)	total: 39.9s	remaining: 59.4s
2100:	learn: 0.2069184	test: 0.2146100	best: 0.2146100 (2100)	total: 40.3s	remaining: 59.1s
2120:	learn: 0.2067327	test: 0.2145333	best: 0.2145333 (2120)	total: 40.7s	remaining: 58.7s
2140:	learn: 0.2065245	test: 0.2144368	best: 0.2144368 (2140)	total: 41.1s	remaining: 58.3s
2160:	learn: 0.2063141	test: 0.2143545	best: 0.2143545 (2160)	total: 41.5s	remaining: 57.9s
2180:	learn: 0.2061498	test: 0.2142712	best: 0.2142712 (2180)	total: 41.8s	remaining: 57.5s
2200:	learn: 0.2059751	test: 0.2141821	best: 0.2141821 (2200)	total: 42.2s	remaining: 57.1s
2220:	learn: 0.2057879	test: 0.2140978	best: 0.2140978 (2220)	total: 42.6s	remaining: 56.7s
2240:	learn: 0.2056160	test: 0.2140299	best: 0.2140298 (2239)	total: 43s	remaining: 56.3s
2260:	learn: 0.2054553	test: 0.2139546	best: 0.2139546 (2260)	total: 43.4s	remaining: 56s
2280:	learn: 0.2052769	test: 0.2138910	best: 0.2138910 (2280)	total: 43.8s	remaining: 55.6s
2300:	learn: 0.2051041	test: 0.2138052	best: 0.2138052 (2300)	total: 44.1s	remaining: 55.2s
2320:	learn: 0.2049367	test: 0.2137354	best: 0.2137350 (2318)	total: 44.5s	remaining: 54.8s
2340:	learn: 0.2047683	test: 0.2136515	best: 0.2136515 (2336)	total: 44.9s	remaining: 54.4s
2360:	learn: 0.2046109	test: 0.2135702	best: 0.2135702 (2360)	total: 45.3s	remaining: 54s
2380:	learn: 0.2043965	test: 0.2134644	best: 0.2134644 (2380)	total: 45.7s	remaining: 53.6s
2400:	learn: 0.2042019	test: 0.2133219	best: 0.2133219 (2400)	total: 46.1s	remaining: 53.3s
2420:	learn: 0.2040572	test: 0.2132640	best: 0.2132640 (2417)	total: 46.5s	remaining: 52.9s
2440:	learn: 0.2038976	test: 0.2131810	best: 0.2131810 (2440)	total: 46.9s	remaining: 52.5s
2460:	learn: 0.2037520	test: 0.2131094	best: 0.2131094 (2460)	total: 47.2s	remaining: 52.1s
2480:	learn: 0.2035870	test: 0.2130264	best: 0.2130264 (2480)	total: 47.6s	remaining: 51.8s
2500:	learn: 0.2034260	test: 0.2129428	best: 0.2129428 (2500)	total: 48s	remaining: 51.4s
2520:	learn: 0.2032818	test: 0.2128811	best: 0.2128811 (2520)	total: 48.4s	remaining: 51s
2540:	learn: 0.2031358	test: 0.2128336	best: 0.2128295 (2538)	total: 48.8s	remaining: 50.6s
2560:	learn: 0.2029841	test: 0.2127805	best: 0.2127805 (2560)	total: 49.2s	remaining: 50.2s
2580:	learn: 0.2028352	test: 0.2127333	best: 0.2127317 (2577)	total: 49.6s	remaining: 49.9s
2600:	learn: 0.2026811	test: 0.2126480	best: 0.2126478 (2599)	total: 50s	remaining: 49.5s
2620:	learn: 0.2025121	test: 0.2125529	best: 0.2125529 (2620)	total: 50.4s	remaining: 49.1s
2640:	learn: 0.2023594	test: 0.2124899	best: 0.2124899 (2640)	total: 50.7s	remaining: 48.7s
2660:	learn: 0.2022358	test: 0.2124575	best: 0.2124573 (2659)	total: 51.2s	remaining: 48.4s
2680:	learn: 0.2020768	test: 0.2123922	best: 0.2123922 (2680)	total: 51.5s	remaining: 48s
2700:	learn: 0.2019360	test: 0.2123521	best: 0.2123512 (2699)	total: 51.9s	remaining: 47.6s
2720:	learn: 0.2017996	test: 0.2123018	best: 0.2123018 (2720)	total: 52.3s	remaining: 47.2s
2740:	learn: 0.2016421	test: 0.2122472	best: 0.2122456 (2739)	total: 52.7s	remaining: 46.9s
2760:	learn: 0.2015282	test: 0.2122081	best: 0.2122060 (2759)	total: 53.1s	remaining: 46.5s
2780:	learn: 0.2013776	test: 0.2121495	best: 0.2121495 (2780)	total: 53.5s	remaining: 46.1s
2800:	learn: 0.2012160	test: 0.2120634	best: 0.2120634 (2800)	total: 53.9s	remaining: 45.7s
2820:	learn: 0.2010884	test: 0.2120147	best: 0.2120133 (2819)	total: 54.3s	remaining: 45.3s
2840:	learn: 0.2008808	test: 0.2118921	best: 0.2118919 (2839)	total: 54.6s	remaining: 44.9s
2860:	learn: 0.2007488	test: 0.2118460	best: 0.2118447 (2859)	total: 55s	remaining: 44.6s
2880:	learn: 0.2005972	test: 0.2117878	best: 0.2117878 (2880)	total: 55.4s	remaining: 44.2s
2900:	learn: 0.2004778	test: 0.2117425	best: 0.2117425 (2900)	total: 55.9s	remaining: 43.8s
2920:	learn: 0.2003344	test: 0.2116564	best: 0.2116564 (2920)	total: 56.3s	remaining: 43.5s
2940:	learn: 0.2001957	test: 0.2116060	best: 0.2116060 (2940)	total: 56.7s	remaining: 43.1s
2960:	learn: 0.2000864	test: 0.2115638	best: 0.2115638 (2960)	total: 57s	remaining: 42.7s
2980:	learn: 0.1999257	test: 0.2115012	best: 0.2115009 (2979)	total: 57.5s	remaining: 42.3s
3000:	learn: 0.1997874	test: 0.2114384	best: 0.2114384 (3000)	total: 57.8s	remaining: 42s
3020:	learn: 0.1996312	test: 0.2113770	best: 0.2113756 (3019)	total: 58.2s	remaining: 41.6s
3040:	learn: 0.1994851	test: 0.2113178	best: 0.2113160 (3039)	total: 58.6s	remaining: 41.2s
3060:	learn: 0.1993517	test: 0.2112863	best: 0.2112863 (3060)	total: 59s	remaining: 40.8s
3080:	learn: 0.1991971	test: 0.2112313	best: 0.2112313 (3080)	total: 59.4s	remaining: 40.4s
3100:	learn: 0.1990552	test: 0.2111621	best: 0.2111602 (3097)	total: 59.8s	remaining: 40.1s
3120:	learn: 0.1989245	test: 0.2111110	best: 0.2111110 (3120)	total: 1m	remaining: 39.7s
3140:	learn: 0.1987928	test: 0.2110499	best: 0.2110499 (3140)	total: 1m	remaining: 39.3s
3160:	learn: 0.1986495	test: 0.2109871	best: 0.2109871 (3160)	total: 1m	remaining: 38.9s
3180:	learn: 0.1985310	test: 0.2109392	best: 0.2109392 (3180)	total: 1m 1s	remaining: 38.5s
3200:	learn: 0.1983989	test: 0.2109024	best: 0.2109024 (3200)	total: 1m 1s	remaining: 38.1s
3220:	learn: 0.1982537	test: 0.2108417	best: 0.2108415 (3219)	total: 1m 2s	remaining: 37.8s
3240:	learn: 0.1981186	test: 0.2108099	best: 0.2108099 (3240)	total: 1m 2s	remaining: 37.4s
3260:	learn: 0.1979891	test: 0.2107614	best: 0.2107614 (3260)	total: 1m 2s	remaining: 37s
3280:	learn: 0.1978363	test: 0.2107031	best: 0.2107031 (3280)	total: 1m 3s	remaining: 36.6s
3300:	learn: 0.1976943	test: 0.2106587	best: 0.2106587 (3300)	total: 1m 3s	remaining: 36.2s
3320:	learn: 0.1975692	test: 0.2106008	best: 0.2105997 (3319)	total: 1m 4s	remaining: 35.8s
3340:	learn: 0.1974368	test: 0.2105398	best: 0.2105364 (3337)	total: 1m 4s	remaining: 35.5s
3360:	learn: 0.1973026	test: 0.2105093	best: 0.2105093 (3360)	total: 1m 4s	remaining: 35.1s
3380:	learn: 0.1971488	test: 0.2104509	best: 0.2104509 (3380)	total: 1m 5s	remaining: 34.7s
3400:	learn: 0.1970083	test: 0.2104024	best: 0.2104024 (3400)	total: 1m 5s	remaining: 34.3s
3420:	learn: 0.1968923	test: 0.2103532	best: 0.2103532 (3420)	total: 1m 6s	remaining: 33.9s
3440:	learn: 0.1967462	test: 0.2102890	best: 0.2102868 (3439)	total: 1m 6s	remaining: 33.5s
3460:	learn: 0.1966158	test: 0.2102634	best: 0.2102623 (3456)	total: 1m 6s	remaining: 33.2s
3480:	learn: 0.1965134	test: 0.2102454	best: 0.2102427 (3478)	total: 1m 7s	remaining: 32.8s
3500:	learn: 0.1963810	test: 0.2101939	best: 0.2101939 (3500)	total: 1m 7s	remaining: 32.4s
3520:	learn: 0.1962632	test: 0.2101653	best: 0.2101653 (3520)	total: 1m 7s	remaining: 32s
3540:	learn: 0.1961404	test: 0.2101329	best: 0.2101329 (3540)	total: 1m 8s	remaining: 31.6s
3560:	learn: 0.1960351	test: 0.2101119	best: 0.2101119 (3560)	total: 1m 8s	remaining: 31.2s
3580:	learn: 0.1959146	test: 0.2100842	best: 0.2100842 (3580)	total: 1m 9s	remaining: 30.8s
3600:	learn: 0.1957946	test: 0.2100610	best: 0.2100600 (3593)	total: 1m 9s	remaining: 30.5s
3620:	learn: 0.1956885	test: 0.2100430	best: 0.2100430 (3620)	total: 1m 9s	remaining: 30.1s
3640:	learn: 0.1955660	test: 0.2100049	best: 0.2100049 (3640)	total: 1m 10s	remaining: 29.7s
3660:	learn: 0.1954462	test: 0.2099598	best: 0.2099576 (3659)	total: 1m 10s	remaining: 29.3s
3680:	learn: 0.1953088	test: 0.2099116	best: 0.2099116 (3680)	total: 1m 11s	remaining: 28.9s
3700:	learn: 0.1951714	test: 0.2098851	best: 0.2098851 (3700)	total: 1m 11s	remaining: 28.5s
3720:	learn: 0.1950499	test: 0.2098563	best: 0.2098562 (3719)	total: 1m 11s	remaining: 28.2s
3740:	learn: 0.1949312	test: 0.2098310	best: 0.2098287 (3737)	total: 1m 12s	remaining: 27.8s
3760:	learn: 0.1948308	test: 0.2098116	best: 0.2098116 (3760)	total: 1m 12s	remaining: 27.4s
3780:	learn: 0.1947039	test: 0.2097827	best: 0.2097827 (3780)	total: 1m 13s	remaining: 27s
3800:	learn: 0.1945709	test: 0.2097383	best: 0.2097383 (3800)	total: 1m 13s	remaining: 26.6s
3820:	learn: 0.1944606	test: 0.2097056	best: 0.2097056 (3820)	total: 1m 13s	remaining: 26.2s
3840:	learn: 0.1943424	test: 0.2096536	best: 0.2096536 (3840)	total: 1m 14s	remaining: 25.9s
3860:	learn: 0.1942224	test: 0.2096201	best: 0.2096196 (3856)	total: 1m 14s	remaining: 25.5s
3880:	learn: 0.1941076	test: 0.2095975	best: 0.2095973 (3878)	total: 1m 15s	remaining: 25.1s
3900:	learn: 0.1939920	test: 0.2095629	best: 0.2095590 (3895)	total: 1m 15s	remaining: 24.7s
3920:	learn: 0.1938839	test: 0.2095323	best: 0.2095321 (3919)	total: 1m 15s	remaining: 24.3s
3940:	learn: 0.1937244	test: 0.2094484	best: 0.2094484 (3940)	total: 1m 16s	remaining: 23.9s
3960:	learn: 0.1936176	test: 0.2094309	best: 0.2094309 (3960)	total: 1m 16s	remaining: 23.5s
3980:	learn: 0.1935047	test: 0.2094052	best: 0.2094052 (3980)	total: 1m 17s	remaining: 23.2s
4000:	learn: 0.1933815	test: 0.2093651	best: 0.2093651 (4000)	total: 1m 17s	remaining: 22.8s
4020:	learn: 0.1932804	test: 0.2093497	best: 0.2093497 (4020)	total: 1m 17s	remaining: 22.4s
4040:	learn: 0.1931667	test: 0.2093187	best: 0.2093187 (4040)	total: 1m 18s	remaining: 22s
4060:	learn: 0.1930352	test: 0.2092817	best: 0.2092806 (4059)	total: 1m 18s	remaining: 21.6s
4080:	learn: 0.1929157	test: 0.2092498	best: 0.2092498 (4080)	total: 1m 19s	remaining: 21.2s
4100:	learn: 0.1927962	test: 0.2092076	best: 0.2092076 (4100)	total: 1m 19s	remaining: 20.9s
4120:	learn: 0.1926944	test: 0.2091721	best: 0.2091719 (4119)	total: 1m 19s	remaining: 20.5s
4140:	learn: 0.1925668	test: 0.2091250	best: 0.2091250 (4140)	total: 1m 20s	remaining: 20.1s
4160:	learn: 0.1924584	test: 0.2091068	best: 0.2091068 (4160)	total: 1m 20s	remaining: 19.7s
4180:	learn: 0.1923266	test: 0.2090546	best: 0.2090546 (4180)	total: 1m 20s	remaining: 19.3s
4200:	learn: 0.1922092	test: 0.2090186	best: 0.2090186 (4200)	total: 1m 21s	remaining: 18.9s
4220:	learn: 0.1920926	test: 0.2089841	best: 0.2089836 (4219)	total: 1m 21s	remaining: 18.5s
4240:	learn: 0.1919872	test: 0.2089642	best: 0.2089607 (4226)	total: 1m 22s	remaining: 18.1s
4260:	learn: 0.1918734	test: 0.2089548	best: 0.2089541 (4259)	total: 1m 22s	remaining: 17.8s
4280:	learn: 0.1917833	test: 0.2089264	best: 0.2089264 (4280)	total: 1m 22s	remaining: 17.4s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404067	test: 0.6403343	best: 0.6403343 (0)	total: 10ms	remaining: 10ms
1:	learn: 0.5954892	test: 0.5953462	best: 0.5953462 (1)	total: 19.2ms	remaining: 0us
bestTest = 0.595346211
bestIteration = 1
0:	learn: 0.6413692	test: 0.6412266	best: 0.6412266 (0)	total: 18.4ms	remaining: 1m 34s
20:	learn: 0.3366304	test: 0.3348398	best: 0.3348398 (20)	total: 429ms	remaining: 1m 45s
40:	learn: 0.3045000	test: 0.3023551	best: 0.3023551 (40)	total: 834ms	remaining: 1m 44s
60:	learn: 0.2898713	test: 0.2875772	best: 0.2875772 (60)	total: 1.25s	remaining: 1m 44s
80:	learn: 0.2812280	test: 0.2787613	best: 0.2787613 (80)	total: 1.66s	remaining: 1m 44s
100:	learn: 0.2752025	test: 0.2727627	best: 0.2727627 (100)	total: 2.05s	remaining: 1m 42s
120:	learn: 0.2703577	test: 0.2680431	best: 0.2680431 (120)	total: 2.42s	remaining: 1m 41s
140:	learn: 0.2659801	test: 0.2637054	best: 0.2637054 (140)	total: 2.82s	remaining: 1m 40s
160:	learn: 0.2623044	test: 0.2602173	best: 0.2602173 (160)	total: 3.21s	remaining: 1m 40s
180:	learn: 0.2586385	test: 0.2566958	best: 0.2566958 (180)	total: 3.59s	remaining: 1m 39s
200:	learn: 0.2561247	test: 0.2543362	best: 0.2543362 (200)	total: 3.97s	remaining: 1m 38s
220:	learn: 0.2540336	test: 0.2524686	best: 0.2524686 (220)	total: 4.35s	remaining: 1m 37s
240:	learn: 0.2514467	test: 0.2499815	best: 0.2499815 (240)	total: 4.76s	remaining: 1m 37s
260:	learn: 0.2493276	test: 0.2479140	best: 0.2479140 (260)	total: 5.14s	remaining: 1m 36s
280:	learn: 0.2476012	test: 0.2461803	best: 0.2461803 (280)	total: 5.52s	remaining: 1m 36s
300:	learn: 0.2458312	test: 0.2445460	best: 0.2445460 (300)	total: 5.91s	remaining: 1m 35s
320:	learn: 0.2444651	test: 0.2432344	best: 0.2432344 (320)	total: 6.31s	remaining: 1m 35s
340:	learn: 0.2430577	test: 0.2419958	best: 0.2419958 (340)	total: 6.7s	remaining: 1m 34s
360:	learn: 0.2417424	test: 0.2408538	best: 0.2408538 (360)	total: 7.08s	remaining: 1m 34s
380:	learn: 0.2406171	test: 0.2398481	best: 0.2398481 (380)	total: 7.46s	remaining: 1m 33s
400:	learn: 0.2393935	test: 0.2387435	best: 0.2387435 (400)	total: 7.82s	remaining: 1m 33s
420:	learn: 0.2384043	test: 0.2378538	best: 0.2378538 (420)	total: 8.21s	remaining: 1m 32s
440:	learn: 0.2372981	test: 0.2368553	best: 0.2368553 (440)	total: 8.58s	remaining: 1m 32s
460:	learn: 0.2362209	test: 0.2358812	best: 0.2358812 (460)	total: 8.97s	remaining: 1m 31s
480:	learn: 0.2352543	test: 0.2349926	best: 0.2349926 (480)	total: 9.35s	remaining: 1m 31s
500:	learn: 0.2343451	test: 0.2342281	best: 0.2342281 (500)	total: 9.72s	remaining: 1m 30s
520:	learn: 0.2334431	test: 0.2334519	best: 0.2334519 (520)	total: 10.1s	remaining: 1m 30s
540:	learn: 0.2326497	test: 0.2328023	best: 0.2328023 (540)	total: 10.5s	remaining: 1m 29s
560:	learn: 0.2318643	test: 0.2321348	best: 0.2321348 (560)	total: 10.9s	remaining: 1m 29s
580:	learn: 0.2311348	test: 0.2315236	best: 0.2315236 (580)	total: 11.3s	remaining: 1m 29s
600:	learn: 0.2305090	test: 0.2310290	best: 0.2310290 (600)	total: 11.7s	remaining: 1m 28s
620:	learn: 0.2298626	test: 0.2305226	best: 0.2305226 (620)	total: 12s	remaining: 1m 28s
640:	learn: 0.2292060	test: 0.2299762	best: 0.2299762 (640)	total: 12.4s	remaining: 1m 27s
660:	learn: 0.2286107	test: 0.2295370	best: 0.2295370 (660)	total: 12.8s	remaining: 1m 27s
680:	learn: 0.2279842	test: 0.2290102	best: 0.2290102 (680)	total: 13.2s	remaining: 1m 26s
700:	learn: 0.2274793	test: 0.2286484	best: 0.2286484 (700)	total: 13.6s	remaining: 1m 26s
720:	learn: 0.2268533	test: 0.2281538	best: 0.2281538 (720)	total: 13.9s	remaining: 1m 26s
740:	learn: 0.2262728	test: 0.2276754	best: 0.2276754 (740)	total: 14.3s	remaining: 1m 25s
760:	learn: 0.2257838	test: 0.2272645	best: 0.2272645 (760)	total: 14.7s	remaining: 1m 25s
780:	learn: 0.2252988	test: 0.2269231	best: 0.2269231 (780)	total: 15.1s	remaining: 1m 24s
800:	learn: 0.2248330	test: 0.2265501	best: 0.2265501 (800)	total: 15.4s	remaining: 1m 24s
820:	learn: 0.2243665	test: 0.2261713	best: 0.2261713 (820)	total: 15.8s	remaining: 1m 23s
840:	learn: 0.2239513	test: 0.2258884	best: 0.2258884 (840)	total: 16.2s	remaining: 1m 23s
860:	learn: 0.2235327	test: 0.2255842	best: 0.2255842 (860)	total: 16.6s	remaining: 1m 23s
880:	learn: 0.2230563	test: 0.2251606	best: 0.2251606 (880)	total: 16.9s	remaining: 1m 22s
900:	learn: 0.2225953	test: 0.2248069	best: 0.2248069 (900)	total: 17.3s	remaining: 1m 22s
920:	learn: 0.2222052	test: 0.2245594	best: 0.2245594 (920)	total: 17.7s	remaining: 1m 21s
940:	learn: 0.2218487	test: 0.2243144	best: 0.2243144 (940)	total: 18.1s	remaining: 1m 21s
960:	learn: 0.2214220	test: 0.2239653	best: 0.2239653 (960)	total: 18.5s	remaining: 1m 20s
980:	learn: 0.2210866	test: 0.2237496	best: 0.2237496 (980)	total: 18.8s	remaining: 1m 20s
1000:	learn: 0.2206907	test: 0.2234486	best: 0.2234486 (1000)	total: 19.2s	remaining: 1m 20s
1020:	learn: 0.2202995	test: 0.2231816	best: 0.2231816 (1020)	total: 19.6s	remaining: 1m 19s
1040:	learn: 0.2199375	test: 0.2229472	best: 0.2229472 (1040)	total: 20s	remaining: 1m 19s
1060:	learn: 0.2195841	test: 0.2226794	best: 0.2226794 (1060)	total: 20.3s	remaining: 1m 18s
1080:	learn: 0.2192708	test: 0.2224847	best: 0.2224847 (1080)	total: 20.7s	remaining: 1m 18s
1100:	learn: 0.2189380	test: 0.2222556	best: 0.2222556 (1100)	total: 21.1s	remaining: 1m 18s
1120:	learn: 0.2186059	test: 0.2220260	best: 0.2220260 (1120)	total: 21.5s	remaining: 1m 17s
1140:	learn: 0.2183237	test: 0.2218404	best: 0.2218404 (1140)	total: 21.8s	remaining: 1m 17s
1160:	learn: 0.2180039	test: 0.2216482	best: 0.2216482 (1160)	total: 22.2s	remaining: 1m 16s
1180:	learn: 0.2177496	test: 0.2214862	best: 0.2214862 (1180)	total: 22.6s	remaining: 1m 16s
1200:	learn: 0.2174526	test: 0.2213031	best: 0.2213031 (1200)	total: 23s	remaining: 1m 16s
1220:	learn: 0.2171902	test: 0.2211580	best: 0.2211580 (1220)	total: 23.4s	remaining: 1m 15s
1240:	learn: 0.2168808	test: 0.2209563	best: 0.2209563 (1240)	total: 23.7s	remaining: 1m 15s
1260:	learn: 0.2165664	test: 0.2207384	best: 0.2207384 (1260)	total: 24.1s	remaining: 1m 14s
1280:	learn: 0.2163170	test: 0.2205753	best: 0.2205753 (1280)	total: 24.5s	remaining: 1m 14s
1300:	learn: 0.2160113	test: 0.2203656	best: 0.2203656 (1300)	total: 24.9s	remaining: 1m 14s
1320:	learn: 0.2157404	test: 0.2202363	best: 0.2202363 (1320)	total: 25.3s	remaining: 1m 13s
1340:	learn: 0.2154823	test: 0.2200900	best: 0.2200900 (1340)	total: 25.6s	remaining: 1m 13s
1360:	learn: 0.2152462	test: 0.2199494	best: 0.2199494 (1360)	total: 26s	remaining: 1m 12s
1380:	learn: 0.2149447	test: 0.2197428	best: 0.2197428 (1380)	total: 26.4s	remaining: 1m 12s
1400:	learn: 0.2146589	test: 0.2195821	best: 0.2195821 (1400)	total: 26.8s	remaining: 1m 12s
1420:	learn: 0.2143930	test: 0.2194243	best: 0.2194243 (1420)	total: 27.2s	remaining: 1m 11s
1440:	learn: 0.2141520	test: 0.2193016	best: 0.2193016 (1440)	total: 27.5s	remaining: 1m 11s
1460:	learn: 0.2139026	test: 0.2191836	best: 0.2191836 (1460)	total: 27.9s	remaining: 1m 11s
1480:	learn: 0.2136293	test: 0.2189885	best: 0.2189885 (1480)	total: 28.3s	remaining: 1m 10s
1500:	learn: 0.2133443	test: 0.2187964	best: 0.2187964 (1500)	total: 28.7s	remaining: 1m 10s
1520:	learn: 0.2130782	test: 0.2186238	best: 0.2186238 (1520)	total: 29.1s	remaining: 1m 9s
1540:	learn: 0.2128678	test: 0.2185118	best: 0.2185118 (1540)	total: 29.5s	remaining: 1m 9s
1560:	learn: 0.2126262	test: 0.2183842	best: 0.2183842 (1560)	total: 29.8s	remaining: 1m 9s
1580:	learn: 0.2124074	test: 0.2182474	best: 0.2182474 (1580)	total: 30.2s	remaining: 1m 8s
1600:	learn: 0.2121622	test: 0.2181191	best: 0.2181191 (1600)	total: 30.6s	remaining: 1m 8s
1620:	learn: 0.2118978	test: 0.2179726	best: 0.2179726 (1620)	total: 31s	remaining: 1m 7s
1640:	learn: 0.2116701	test: 0.2178360	best: 0.2178360 (1640)	total: 31.4s	remaining: 1m 7s
1660:	learn: 0.2114688	test: 0.2177310	best: 0.2177310 (1660)	total: 31.8s	remaining: 1m 7s
1680:	learn: 0.2112243	test: 0.2175947	best: 0.2175947 (1680)	total: 32.1s	remaining: 1m 6s
1700:	learn: 0.2110207	test: 0.2174823	best: 0.2174823 (1700)	total: 32.5s	remaining: 1m 6s
1720:	learn: 0.2107976	test: 0.2173633	best: 0.2173633 (1720)	total: 32.9s	remaining: 1m 5s
1740:	learn: 0.2105613	test: 0.2172558	best: 0.2172558 (1740)	total: 33.3s	remaining: 1m 5s
1760:	learn: 0.2102963	test: 0.2171108	best: 0.2171108 (1760)	total: 33.6s	remaining: 1m 5s
1780:	learn: 0.2101040	test: 0.2170233	best: 0.2170233 (1780)	total: 34s	remaining: 1m 4s
1800:	learn: 0.2098218	test: 0.2168367	best: 0.2168367 (1800)	total: 34.4s	remaining: 1m 4s
1820:	learn: 0.2095843	test: 0.2167032	best: 0.2167032 (1820)	total: 34.7s	remaining: 1m 3s
1840:	learn: 0.2093665	test: 0.2166032	best: 0.2166032 (1840)	total: 35.1s	remaining: 1m 3s
1860:	learn: 0.2091649	test: 0.2165099	best: 0.2165083 (1858)	total: 35.4s	remaining: 1m 3s
1880:	learn: 0.2089873	test: 0.2164138	best: 0.2164126 (1879)	total: 35.8s	remaining: 1m 2s
1900:	learn: 0.2087719	test: 0.2163078	best: 0.2163078 (1898)	total: 36.2s	remaining: 1m 2s
1920:	learn: 0.2085641	test: 0.2162007	best: 0.2162007 (1920)	total: 36.5s	remaining: 1m 1s
1940:	learn: 0.2083600	test: 0.2160699	best: 0.2160699 (1940)	total: 36.9s	remaining: 1m 1s
1960:	learn: 0.2081802	test: 0.2159913	best: 0.2159913 (1960)	total: 37.3s	remaining: 1m 1s
1980:	learn: 0.2079846	test: 0.2158744	best: 0.2158744 (1980)	total: 37.7s	remaining: 1m
2000:	learn: 0.2077872	test: 0.2157557	best: 0.2157555 (1999)	total: 38s	remaining: 1m
2020:	learn: 0.2076221	test: 0.2156927	best: 0.2156927 (2020)	total: 38.4s	remaining: 59.9s
2040:	learn: 0.2073640	test: 0.2155028	best: 0.2155028 (2040)	total: 38.8s	remaining: 59.5s
2060:	learn: 0.2071892	test: 0.2154037	best: 0.2154037 (2060)	total: 39.1s	remaining: 59.1s
2080:	learn: 0.2070060	test: 0.2153427	best: 0.2153425 (2079)	total: 39.5s	remaining: 58.7s
2100:	learn: 0.2068265	test: 0.2152610	best: 0.2152610 (2099)	total: 39.9s	remaining: 58.3s
2120:	learn: 0.2066393	test: 0.2151568	best: 0.2151564 (2119)	total: 40.2s	remaining: 57.9s
2140:	learn: 0.2064519	test: 0.2150518	best: 0.2150518 (2140)	total: 40.6s	remaining: 57.6s
2160:	learn: 0.2063223	test: 0.2149916	best: 0.2149916 (2160)	total: 41s	remaining: 57.2s
2180:	learn: 0.2061365	test: 0.2149158	best: 0.2149158 (2180)	total: 41.4s	remaining: 56.8s
2200:	learn: 0.2059648	test: 0.2148561	best: 0.2148561 (2200)	total: 41.8s	remaining: 56.4s
2220:	learn: 0.2057951	test: 0.2147950	best: 0.2147950 (2220)	total: 42.1s	remaining: 56s
2240:	learn: 0.2056355	test: 0.2147142	best: 0.2147142 (2240)	total: 42.5s	remaining: 55.7s
2260:	learn: 0.2054691	test: 0.2146407	best: 0.2146407 (2260)	total: 42.9s	remaining: 55.3s
2280:	learn: 0.2052713	test: 0.2145412	best: 0.2145412 (2280)	total: 43.3s	remaining: 54.9s
2300:	learn: 0.2051102	test: 0.2144581	best: 0.2144581 (2300)	total: 43.6s	remaining: 54.5s
2320:	learn: 0.2049069	test: 0.2143546	best: 0.2143546 (2320)	total: 44s	remaining: 54.1s
2340:	learn: 0.2047465	test: 0.2142984	best: 0.2142984 (2340)	total: 44.4s	remaining: 53.7s
2360:	learn: 0.2045979	test: 0.2142352	best: 0.2142346 (2359)	total: 44.8s	remaining: 53.3s
2380:	learn: 0.2044321	test: 0.2141741	best: 0.2141681 (2377)	total: 45.1s	remaining: 52.9s
2400:	learn: 0.2042818	test: 0.2140932	best: 0.2140932 (2400)	total: 45.5s	remaining: 52.5s
2420:	learn: 0.2041192	test: 0.2140326	best: 0.2140320 (2418)	total: 45.9s	remaining: 52.2s
2440:	learn: 0.2039558	test: 0.2139728	best: 0.2139728 (2440)	total: 46.2s	remaining: 51.8s
2460:	learn: 0.2037931	test: 0.2139126	best: 0.2139126 (2460)	total: 46.6s	remaining: 51.4s
2480:	learn: 0.2036175	test: 0.2138179	best: 0.2138179 (2480)	total: 47s	remaining: 51s
2500:	learn: 0.2034485	test: 0.2137387	best: 0.2137387 (2500)	total: 47.4s	remaining: 50.6s
2520:	learn: 0.2032777	test: 0.2136482	best: 0.2136482 (2520)	total: 47.8s	remaining: 50.3s
2540:	learn: 0.2031288	test: 0.2135779	best: 0.2135779 (2540)	total: 48.1s	remaining: 49.9s
2560:	learn: 0.2029774	test: 0.2135191	best: 0.2135191 (2560)	total: 48.5s	remaining: 49.5s
2580:	learn: 0.2027662	test: 0.2133730	best: 0.2133730 (2580)	total: 48.9s	remaining: 49.1s
2600:	learn: 0.2026250	test: 0.2133094	best: 0.2133094 (2600)	total: 49.3s	remaining: 48.7s
2620:	learn: 0.2024775	test: 0.2132253	best: 0.2132253 (2620)	total: 49.6s	remaining: 48.3s
2640:	learn: 0.2023228	test: 0.2131681	best: 0.2131681 (2640)	total: 50s	remaining: 48s
2660:	learn: 0.2021244	test: 0.2130360	best: 0.2130360 (2660)	total: 50.4s	remaining: 47.6s
2680:	learn: 0.2019603	test: 0.2129784	best: 0.2129784 (2680)	total: 50.7s	remaining: 47.2s
2700:	learn: 0.2017919	test: 0.2128796	best: 0.2128796 (2700)	total: 51.1s	remaining: 46.8s
2720:	learn: 0.2016495	test: 0.2128200	best: 0.2128200 (2720)	total: 51.5s	remaining: 46.4s
2740:	learn: 0.2014804	test: 0.2127355	best: 0.2127355 (2740)	total: 51.8s	remaining: 46s
2760:	learn: 0.2013144	test: 0.2126600	best: 0.2126600 (2760)	total: 52.2s	remaining: 45.6s
2780:	learn: 0.2011835	test: 0.2126219	best: 0.2126219 (2780)	total: 52.6s	remaining: 45.3s
2800:	learn: 0.2010553	test: 0.2125805	best: 0.2125805 (2800)	total: 53s	remaining: 44.9s
2820:	learn: 0.2009290	test: 0.2125348	best: 0.2125328 (2819)	total: 53.4s	remaining: 44.5s
2840:	learn: 0.2007769	test: 0.2124555	best: 0.2124555 (2840)	total: 53.7s	remaining: 44.1s
2860:	learn: 0.2006340	test: 0.2123937	best: 0.2123937 (2860)	total: 54.1s	remaining: 43.7s
2880:	learn: 0.2004723	test: 0.2123152	best: 0.2123148 (2878)	total: 54.5s	remaining: 43.3s
2900:	learn: 0.2003107	test: 0.2122420	best: 0.2122420 (2900)	total: 54.8s	remaining: 43s
2920:	learn: 0.2001608	test: 0.2122074	best: 0.2122066 (2918)	total: 55.2s	remaining: 42.6s
2940:	learn: 0.2000296	test: 0.2121672	best: 0.2121672 (2940)	total: 55.6s	remaining: 42.2s
2960:	learn: 0.1998936	test: 0.2121278	best: 0.2121278 (2960)	total: 56s	remaining: 41.8s
2980:	learn: 0.1997647	test: 0.2120809	best: 0.2120809 (2980)	total: 56.3s	remaining: 41.4s
3000:	learn: 0.1996337	test: 0.2120345	best: 0.2120345 (3000)	total: 56.7s	remaining: 41.1s
3020:	learn: 0.1994891	test: 0.2119840	best: 0.2119840 (3020)	total: 57.1s	remaining: 40.7s
3040:	learn: 0.1993693	test: 0.2119352	best: 0.2119352 (3040)	total: 57.6s	remaining: 40.4s
3060:	learn: 0.1992247	test: 0.2118917	best: 0.2118897 (3059)	total: 57.9s	remaining: 40s
3080:	learn: 0.1990529	test: 0.2118186	best: 0.2118171 (3076)	total: 58.3s	remaining: 39.6s
3100:	learn: 0.1989231	test: 0.2117893	best: 0.2117893 (3100)	total: 58.7s	remaining: 39.3s
3120:	learn: 0.1987927	test: 0.2117422	best: 0.2117422 (3120)	total: 59.1s	remaining: 38.9s
3140:	learn: 0.1986536	test: 0.2117079	best: 0.2117079 (3140)	total: 59.5s	remaining: 38.5s
3160:	learn: 0.1985017	test: 0.2116640	best: 0.2116640 (3160)	total: 59.9s	remaining: 38.1s
3180:	learn: 0.1983659	test: 0.2116063	best: 0.2116041 (3178)	total: 1m	remaining: 37.7s
3200:	learn: 0.1982256	test: 0.2115596	best: 0.2115596 (3200)	total: 1m	remaining: 37.4s
3220:	learn: 0.1980973	test: 0.2115299	best: 0.2115299 (3220)	total: 1m	remaining: 37s
3240:	learn: 0.1979519	test: 0.2114673	best: 0.2114673 (3240)	total: 1m 1s	remaining: 36.6s
3260:	learn: 0.1978202	test: 0.2114228	best: 0.2114228 (3260)	total: 1m 1s	remaining: 36.2s
3280:	learn: 0.1976691	test: 0.2113630	best: 0.2113630 (3280)	total: 1m 2s	remaining: 35.8s
3300:	learn: 0.1975530	test: 0.2113307	best: 0.2113307 (3300)	total: 1m 2s	remaining: 35.4s
3320:	learn: 0.1974150	test: 0.2112900	best: 0.2112899 (3319)	total: 1m 2s	remaining: 35.1s
3340:	learn: 0.1972945	test: 0.2112493	best: 0.2112462 (3337)	total: 1m 3s	remaining: 34.7s
3360:	learn: 0.1971361	test: 0.2111759	best: 0.2111759 (3360)	total: 1m 3s	remaining: 34.3s
3380:	learn: 0.1969964	test: 0.2111413	best: 0.2111413 (3380)	total: 1m 3s	remaining: 33.9s
3400:	learn: 0.1968756	test: 0.2110893	best: 0.2110893 (3400)	total: 1m 4s	remaining: 33.6s
3420:	learn: 0.1967339	test: 0.2110298	best: 0.2110298 (3420)	total: 1m 4s	remaining: 33.2s
3440:	learn: 0.1966008	test: 0.2109918	best: 0.2109918 (3440)	total: 1m 5s	remaining: 32.8s
3460:	learn: 0.1964726	test: 0.2109385	best: 0.2109385 (3460)	total: 1m 5s	remaining: 32.4s
3480:	learn: 0.1963547	test: 0.2108961	best: 0.2108961 (3480)	total: 1m 5s	remaining: 32s
3500:	learn: 0.1962268	test: 0.2108603	best: 0.2108598 (3499)	total: 1m 6s	remaining: 31.7s
3520:	learn: 0.1961024	test: 0.2108105	best: 0.2108105 (3520)	total: 1m 6s	remaining: 31.3s
3540:	learn: 0.1959914	test: 0.2107884	best: 0.2107871 (3539)	total: 1m 7s	remaining: 30.9s
3560:	learn: 0.1958657	test: 0.2107465	best: 0.2107448 (3558)	total: 1m 7s	remaining: 30.5s
3580:	learn: 0.1957316	test: 0.2107063	best: 0.2107063 (3580)	total: 1m 7s	remaining: 30.2s
3600:	learn: 0.1955804	test: 0.2106473	best: 0.2106473 (3600)	total: 1m 8s	remaining: 29.8s
3620:	learn: 0.1954569	test: 0.2105983	best: 0.2105983 (3620)	total: 1m 8s	remaining: 29.4s
3640:	learn: 0.1953138	test: 0.2105512	best: 0.2105512 (3640)	total: 1m 8s	remaining: 29s
3660:	learn: 0.1951895	test: 0.2104971	best: 0.2104971 (3660)	total: 1m 9s	remaining: 28.6s
3680:	learn: 0.1950775	test: 0.2104683	best: 0.2104683 (3680)	total: 1m 9s	remaining: 28.3s
3700:	learn: 0.1949660	test: 0.2104507	best: 0.2104446 (3697)	total: 1m 10s	remaining: 27.9s
3720:	learn: 0.1948455	test: 0.2103891	best: 0.2103886 (3717)	total: 1m 10s	remaining: 27.5s
3740:	learn: 0.1947218	test: 0.2103510	best: 0.2103510 (3740)	total: 1m 10s	remaining: 27.1s
3760:	learn: 0.1946036	test: 0.2103030	best: 0.2103024 (3759)	total: 1m 11s	remaining: 26.7s
3780:	learn: 0.1944761	test: 0.2102570	best: 0.2102570 (3780)	total: 1m 11s	remaining: 26.4s
3800:	learn: 0.1943537	test: 0.2102323	best: 0.2102323 (3800)	total: 1m 11s	remaining: 26s
3820:	learn: 0.1942312	test: 0.2101928	best: 0.2101928 (3820)	total: 1m 12s	remaining: 25.6s
3840:	learn: 0.1941225	test: 0.2101674	best: 0.2101674 (3840)	total: 1m 12s	remaining: 25.2s
3860:	learn: 0.1940072	test: 0.2101225	best: 0.2101225 (3860)	total: 1m 13s	remaining: 24.8s
3880:	learn: 0.1938892	test: 0.2101023	best: 0.2101023 (3880)	total: 1m 13s	remaining: 24.5s
3900:	learn: 0.1937493	test: 0.2100639	best: 0.2100639 (3900)	total: 1m 13s	remaining: 24.1s
3920:	learn: 0.1936275	test: 0.2100180	best: 0.2100180 (3920)	total: 1m 14s	remaining: 23.7s
3940:	learn: 0.1935292	test: 0.2100054	best: 0.2100054 (3940)	total: 1m 14s	remaining: 23.3s
3960:	learn: 0.1934190	test: 0.2099748	best: 0.2099748 (3960)	total: 1m 14s	remaining: 22.9s
3980:	learn: 0.1932964	test: 0.2099366	best: 0.2099366 (3980)	total: 1m 15s	remaining: 22.6s
4000:	learn: 0.1931674	test: 0.2098982	best: 0.2098959 (3994)	total: 1m 15s	remaining: 22.2s
4020:	learn: 0.1930397	test: 0.2098841	best: 0.2098825 (4019)	total: 1m 16s	remaining: 21.8s
4040:	learn: 0.1929081	test: 0.2098345	best: 0.2098345 (4040)	total: 1m 16s	remaining: 21.4s
4060:	learn: 0.1927983	test: 0.2098047	best: 0.2098047 (4060)	total: 1m 16s	remaining: 21s
4080:	learn: 0.1926777	test: 0.2097582	best: 0.2097550 (4079)	total: 1m 17s	remaining: 20.7s
4100:	learn: 0.1925613	test: 0.2097199	best: 0.2097199 (4100)	total: 1m 17s	remaining: 20.3s
4120:	learn: 0.1924542	test: 0.2096898	best: 0.2096898 (4120)	total: 1m 17s	remaining: 19.9s
4140:	learn: 0.1923296	test: 0.2096586	best: 0.2096580 (4137)	total: 1m 18s	remaining: 19.5s
4160:	learn: 0.1922163	test: 0.2096340	best: 0.2096331 (4159)	total: 1m 18s	remaining: 19.2s
4180:	learn: 0.1921104	test: 0.2096158	best: 0.2096158 (4180)	total: 1m 19s	remaining: 18.8s
4200:	learn: 0.1919994	test: 0.2095809	best: 0.2095809 (4200)	total: 1m 19s	remaining: 18.4s
4220:	learn: 0.1918662	test: 0.2095271	best: 0.2095271 (4220)	total: 1m 19s	remaining: 18s
4240:	learn: 0.1917773	test: 0.2095041	best: 0.2095031 (4238)	total: 1m 20s	remaining: 17.6s
4260:	learn: 0.1916663	test: 0.2094816	best: 0.2094785 (4259)	total: 1m 20s	remaining: 17.3s
4280:	learn: 0.1915660	test: 0.2094337	best: 0.2094337 (4280)	total: 1m 20s	remaining: 16.9s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6405756	test: 0.6404119	best: 0.6404119 (0)	total: 9.48ms	remaining: 9.48ms
1:	learn: 0.5957443	test: 0.5954482	best: 0.5954482 (1)	total: 18.3ms	remaining: 0us
bestTest = 0.5954482112
bestIteration = 1
0:	learn: 0.6415704	test: 0.6413785	best: 0.6413785 (0)	total: 17.3ms	remaining: 1m 31s
20:	learn: 0.3376542	test: 0.3356240	best: 0.3356240 (20)	total: 411ms	remaining: 1m 43s
40:	learn: 0.3039845	test: 0.3011669	best: 0.3011669 (40)	total: 796ms	remaining: 1m 42s
60:	learn: 0.2899157	test: 0.2862784	best: 0.2862784 (60)	total: 1.18s	remaining: 1m 41s
80:	learn: 0.2812662	test: 0.2773071	best: 0.2773071 (80)	total: 1.57s	remaining: 1m 41s
100:	learn: 0.2743565	test: 0.2703298	best: 0.2703298 (100)	total: 1.96s	remaining: 1m 41s
120:	learn: 0.2704780	test: 0.2665068	best: 0.2665068 (120)	total: 2.33s	remaining: 1m 39s
140:	learn: 0.2659620	test: 0.2618556	best: 0.2618556 (140)	total: 2.71s	remaining: 1m 39s
160:	learn: 0.2624892	test: 0.2583638	best: 0.2583638 (160)	total: 3.08s	remaining: 1m 38s
180:	learn: 0.2592828	test: 0.2551061	best: 0.2551061 (180)	total: 3.45s	remaining: 1m 37s
200:	learn: 0.2565846	test: 0.2525506	best: 0.2525506 (200)	total: 3.82s	remaining: 1m 37s
220:	learn: 0.2540481	test: 0.2501258	best: 0.2501258 (220)	total: 4.2s	remaining: 1m 36s
240:	learn: 0.2518302	test: 0.2478158	best: 0.2478158 (240)	total: 4.56s	remaining: 1m 36s
260:	learn: 0.2500846	test: 0.2462141	best: 0.2462141 (260)	total: 4.93s	remaining: 1m 35s
280:	learn: 0.2484707	test: 0.2446803	best: 0.2446803 (280)	total: 5.28s	remaining: 1m 34s
300:	learn: 0.2468810	test: 0.2431166	best: 0.2431166 (300)	total: 5.65s	remaining: 1m 34s
320:	learn: 0.2452682	test: 0.2416139	best: 0.2416139 (320)	total: 6.05s	remaining: 1m 34s
340:	learn: 0.2440491	test: 0.2404980	best: 0.2404980 (340)	total: 6.41s	remaining: 1m 33s
360:	learn: 0.2429788	test: 0.2395315	best: 0.2395315 (360)	total: 6.77s	remaining: 1m 32s
380:	learn: 0.2416116	test: 0.2381475	best: 0.2381475 (380)	total: 7.15s	remaining: 1m 32s
400:	learn: 0.2403758	test: 0.2370209	best: 0.2370209 (400)	total: 7.5s	remaining: 1m 31s
420:	learn: 0.2393736	test: 0.2361741	best: 0.2361741 (420)	total: 7.85s	remaining: 1m 31s
440:	learn: 0.2383399	test: 0.2352028	best: 0.2352028 (440)	total: 8.22s	remaining: 1m 30s
460:	learn: 0.2371150	test: 0.2340098	best: 0.2340098 (460)	total: 8.59s	remaining: 1m 30s
480:	learn: 0.2363571	test: 0.2333910	best: 0.2333910 (480)	total: 8.96s	remaining: 1m 29s
500:	learn: 0.2354697	test: 0.2325841	best: 0.2325841 (500)	total: 9.33s	remaining: 1m 29s
520:	learn: 0.2345384	test: 0.2318132	best: 0.2318132 (520)	total: 9.69s	remaining: 1m 29s
540:	learn: 0.2336629	test: 0.2310049	best: 0.2310049 (540)	total: 10.1s	remaining: 1m 28s
560:	learn: 0.2329126	test: 0.2303716	best: 0.2303716 (560)	total: 10.4s	remaining: 1m 28s
580:	learn: 0.2321283	test: 0.2297222	best: 0.2297222 (580)	total: 10.8s	remaining: 1m 27s
600:	learn: 0.2314683	test: 0.2291856	best: 0.2291856 (600)	total: 11.1s	remaining: 1m 27s
620:	learn: 0.2307707	test: 0.2286152	best: 0.2286152 (620)	total: 11.5s	remaining: 1m 26s
640:	learn: 0.2301342	test: 0.2280918	best: 0.2280918 (640)	total: 11.9s	remaining: 1m 26s
660:	learn: 0.2295081	test: 0.2276029	best: 0.2276029 (660)	total: 12.2s	remaining: 1m 25s
680:	learn: 0.2289150	test: 0.2271164	best: 0.2271164 (680)	total: 12.6s	remaining: 1m 25s
700:	learn: 0.2280341	test: 0.2262621	best: 0.2262621 (700)	total: 12.9s	remaining: 1m 25s
720:	learn: 0.2274238	test: 0.2256910	best: 0.2256910 (720)	total: 13.3s	remaining: 1m 24s
740:	learn: 0.2267881	test: 0.2251363	best: 0.2251363 (740)	total: 13.7s	remaining: 1m 24s
760:	learn: 0.2262317	test: 0.2246398	best: 0.2246398 (760)	total: 14s	remaining: 1m 23s
780:	learn: 0.2257102	test: 0.2242207	best: 0.2242207 (780)	total: 14.4s	remaining: 1m 23s
800:	learn: 0.2251175	test: 0.2237345	best: 0.2237345 (800)	total: 14.7s	remaining: 1m 23s
820:	learn: 0.2246842	test: 0.2234076	best: 0.2234076 (820)	total: 15.1s	remaining: 1m 22s
840:	learn: 0.2242570	test: 0.2231143	best: 0.2231143 (840)	total: 15.5s	remaining: 1m 22s
860:	learn: 0.2238149	test: 0.2227563	best: 0.2227563 (860)	total: 15.8s	remaining: 1m 21s
880:	learn: 0.2233963	test: 0.2224691	best: 0.2224691 (880)	total: 16.2s	remaining: 1m 21s
900:	learn: 0.2229600	test: 0.2221728	best: 0.2221728 (900)	total: 16.5s	remaining: 1m 20s
920:	learn: 0.2225787	test: 0.2219171	best: 0.2219171 (920)	total: 16.9s	remaining: 1m 20s
940:	learn: 0.2221629	test: 0.2216330	best: 0.2216330 (940)	total: 17.3s	remaining: 1m 20s
960:	learn: 0.2217130	test: 0.2212982	best: 0.2212982 (960)	total: 17.6s	remaining: 1m 19s
980:	learn: 0.2213663	test: 0.2210252	best: 0.2210252 (980)	total: 18s	remaining: 1m 19s
1000:	learn: 0.2210239	test: 0.2207948	best: 0.2207948 (1000)	total: 18.3s	remaining: 1m 18s
1020:	learn: 0.2206866	test: 0.2205625	best: 0.2205625 (1020)	total: 18.7s	remaining: 1m 18s
1040:	learn: 0.2202895	test: 0.2202714	best: 0.2202714 (1040)	total: 19s	remaining: 1m 18s
1060:	learn: 0.2198648	test: 0.2199548	best: 0.2199548 (1060)	total: 19.4s	remaining: 1m 17s
1080:	learn: 0.2195349	test: 0.2197385	best: 0.2197385 (1080)	total: 19.8s	remaining: 1m 17s
1100:	learn: 0.2192027	test: 0.2195372	best: 0.2195372 (1100)	total: 20.1s	remaining: 1m 17s
1120:	learn: 0.2188170	test: 0.2192774	best: 0.2192774 (1120)	total: 20.5s	remaining: 1m 16s
1140:	learn: 0.2184855	test: 0.2190387	best: 0.2190387 (1140)	total: 20.8s	remaining: 1m 16s
1160:	learn: 0.2182015	test: 0.2188841	best: 0.2188841 (1160)	total: 21.2s	remaining: 1m 15s
1180:	learn: 0.2178955	test: 0.2187016	best: 0.2187016 (1180)	total: 21.5s	remaining: 1m 15s
1200:	learn: 0.2175845	test: 0.2184933	best: 0.2184933 (1200)	total: 21.9s	remaining: 1m 14s
1220:	learn: 0.2172215	test: 0.2182101	best: 0.2182095 (1219)	total: 22.3s	remaining: 1m 14s
1240:	learn: 0.2169292	test: 0.2180652	best: 0.2180652 (1240)	total: 22.6s	remaining: 1m 14s
1260:	learn: 0.2166837	test: 0.2179168	best: 0.2179168 (1260)	total: 23s	remaining: 1m 13s
1280:	learn: 0.2163478	test: 0.2177211	best: 0.2177211 (1280)	total: 23.3s	remaining: 1m 13s
1300:	learn: 0.2160428	test: 0.2175014	best: 0.2175014 (1300)	total: 23.7s	remaining: 1m 13s
1320:	learn: 0.2157339	test: 0.2173128	best: 0.2173128 (1320)	total: 24.1s	remaining: 1m 12s
1340:	learn: 0.2154137	test: 0.2171428	best: 0.2171428 (1340)	total: 24.4s	remaining: 1m 12s
1360:	learn: 0.2151114	test: 0.2169423	best: 0.2169423 (1360)	total: 24.8s	remaining: 1m 12s
1380:	learn: 0.2148381	test: 0.2168082	best: 0.2168082 (1380)	total: 25.2s	remaining: 1m 11s
1400:	learn: 0.2146171	test: 0.2167052	best: 0.2167052 (1400)	total: 25.5s	remaining: 1m 11s
1420:	learn: 0.2143615	test: 0.2165486	best: 0.2165486 (1420)	total: 25.9s	remaining: 1m 10s
1440:	learn: 0.2141595	test: 0.2164402	best: 0.2164402 (1440)	total: 26.2s	remaining: 1m 10s
1460:	learn: 0.2138948	test: 0.2162560	best: 0.2162560 (1460)	total: 26.6s	remaining: 1m 10s
1480:	learn: 0.2136270	test: 0.2161074	best: 0.2161074 (1480)	total: 27s	remaining: 1m 9s
1500:	learn: 0.2133590	test: 0.2159217	best: 0.2159217 (1500)	total: 27.3s	remaining: 1m 9s
1520:	learn: 0.2131316	test: 0.2158030	best: 0.2158022 (1519)	total: 27.7s	remaining: 1m 9s
1540:	learn: 0.2128682	test: 0.2156813	best: 0.2156813 (1540)	total: 28s	remaining: 1m 8s
1560:	learn: 0.2125645	test: 0.2154939	best: 0.2154939 (1560)	total: 28.4s	remaining: 1m 8s
1580:	learn: 0.2123252	test: 0.2153829	best: 0.2153829 (1580)	total: 28.8s	remaining: 1m 7s
1600:	learn: 0.2121294	test: 0.2152704	best: 0.2152704 (1600)	total: 29.1s	remaining: 1m 7s
1620:	learn: 0.2118753	test: 0.2151103	best: 0.2151103 (1620)	total: 29.5s	remaining: 1m 7s
1640:	learn: 0.2116754	test: 0.2149887	best: 0.2149887 (1640)	total: 29.9s	remaining: 1m 6s
1660:	learn: 0.2114763	test: 0.2148901	best: 0.2148896 (1658)	total: 30.2s	remaining: 1m 6s
1680:	learn: 0.2112153	test: 0.2147328	best: 0.2147328 (1680)	total: 30.6s	remaining: 1m 6s
1700:	learn: 0.2109955	test: 0.2146161	best: 0.2146161 (1700)	total: 30.9s	remaining: 1m 5s
1720:	learn: 0.2108163	test: 0.2145472	best: 0.2145472 (1720)	total: 31.3s	remaining: 1m 5s
1740:	learn: 0.2105763	test: 0.2143979	best: 0.2143946 (1739)	total: 31.7s	remaining: 1m 4s
1760:	learn: 0.2103721	test: 0.2142897	best: 0.2142897 (1760)	total: 32s	remaining: 1m 4s
1780:	learn: 0.2102048	test: 0.2142174	best: 0.2142174 (1780)	total: 32.4s	remaining: 1m 4s
1800:	learn: 0.2099728	test: 0.2141126	best: 0.2141126 (1800)	total: 32.7s	remaining: 1m 3s
1820:	learn: 0.2097487	test: 0.2140024	best: 0.2140024 (1820)	total: 33.1s	remaining: 1m 3s
1840:	learn: 0.2095533	test: 0.2138940	best: 0.2138940 (1840)	total: 33.5s	remaining: 1m 3s
1860:	learn: 0.2093466	test: 0.2137862	best: 0.2137862 (1860)	total: 33.8s	remaining: 1m 2s
1880:	learn: 0.2091677	test: 0.2136784	best: 0.2136784 (1880)	total: 34.2s	remaining: 1m 2s
1900:	learn: 0.2089302	test: 0.2135367	best: 0.2135367 (1900)	total: 34.6s	remaining: 1m 2s
1920:	learn: 0.2087325	test: 0.2134215	best: 0.2134215 (1920)	total: 34.9s	remaining: 1m 1s
1940:	learn: 0.2085594	test: 0.2133314	best: 0.2133314 (1940)	total: 35.3s	remaining: 1m 1s
1960:	learn: 0.2083488	test: 0.2132048	best: 0.2132048 (1960)	total: 35.6s	remaining: 1m
1980:	learn: 0.2081727	test: 0.2131329	best: 0.2131282 (1979)	total: 36s	remaining: 1m
2000:	learn: 0.2079956	test: 0.2130669	best: 0.2130669 (2000)	total: 36.4s	remaining: 1m
2020:	learn: 0.2078152	test: 0.2129983	best: 0.2129983 (2020)	total: 36.8s	remaining: 59.9s
2040:	learn: 0.2076353	test: 0.2129126	best: 0.2129126 (2040)	total: 37.1s	remaining: 59.5s
2060:	learn: 0.2074258	test: 0.2128015	best: 0.2128015 (2060)	total: 37.5s	remaining: 59.1s
2080:	learn: 0.2072345	test: 0.2127004	best: 0.2127004 (2080)	total: 37.9s	remaining: 58.8s
2100:	learn: 0.2070419	test: 0.2126174	best: 0.2126174 (2100)	total: 38.2s	remaining: 58.4s
2120:	learn: 0.2068702	test: 0.2125488	best: 0.2125488 (2120)	total: 38.6s	remaining: 58.1s
2140:	learn: 0.2067126	test: 0.2124866	best: 0.2124866 (2140)	total: 39s	remaining: 57.7s
2160:	learn: 0.2065499	test: 0.2123956	best: 0.2123956 (2160)	total: 39.3s	remaining: 57.3s
2180:	learn: 0.2063785	test: 0.2123195	best: 0.2123195 (2180)	total: 39.7s	remaining: 57s
2200:	learn: 0.2062078	test: 0.2122573	best: 0.2122553 (2199)	total: 40.1s	remaining: 56.6s
2220:	learn: 0.2060388	test: 0.2121570	best: 0.2121570 (2220)	total: 40.4s	remaining: 56.3s
2240:	learn: 0.2058311	test: 0.2120474	best: 0.2120471 (2239)	total: 40.8s	remaining: 55.9s
2260:	learn: 0.2056527	test: 0.2119703	best: 0.2119703 (2260)	total: 41.2s	remaining: 55.5s
2280:	learn: 0.2054605	test: 0.2118701	best: 0.2118701 (2280)	total: 41.5s	remaining: 55.2s
2300:	learn: 0.2052914	test: 0.2118037	best: 0.2118037 (2300)	total: 41.9s	remaining: 54.8s
2320:	learn: 0.2051172	test: 0.2117252	best: 0.2117252 (2320)	total: 42.3s	remaining: 54.5s
2340:	learn: 0.2048963	test: 0.2115967	best: 0.2115967 (2340)	total: 42.6s	remaining: 54.1s
2360:	learn: 0.2047335	test: 0.2115398	best: 0.2115398 (2360)	total: 43s	remaining: 53.8s
2380:	learn: 0.2045952	test: 0.2114698	best: 0.2114698 (2380)	total: 43.4s	remaining: 53.4s
2400:	learn: 0.2044277	test: 0.2114062	best: 0.2114052 (2399)	total: 43.8s	remaining: 53.1s
2420:	learn: 0.2042842	test: 0.2113567	best: 0.2113567 (2420)	total: 44.1s	remaining: 52.7s
2440:	learn: 0.2041075	test: 0.2112963	best: 0.2112957 (2439)	total: 44.5s	remaining: 52.3s
2460:	learn: 0.2039704	test: 0.2112291	best: 0.2112291 (2457)	total: 44.9s	remaining: 52s
2480:	learn: 0.2038342	test: 0.2111805	best: 0.2111805 (2480)	total: 45.2s	remaining: 51.6s
2500:	learn: 0.2036736	test: 0.2111385	best: 0.2111385 (2500)	total: 45.6s	remaining: 51.2s
2520:	learn: 0.2035357	test: 0.2110821	best: 0.2110803 (2516)	total: 46s	remaining: 50.9s
2540:	learn: 0.2033561	test: 0.2109995	best: 0.2109995 (2540)	total: 46.3s	remaining: 50.5s
2560:	learn: 0.2031851	test: 0.2109209	best: 0.2109209 (2560)	total: 46.7s	remaining: 50.2s
2580:	learn: 0.2030561	test: 0.2108833	best: 0.2108833 (2580)	total: 47.1s	remaining: 49.8s
2600:	learn: 0.2029383	test: 0.2108414	best: 0.2108414 (2600)	total: 47.5s	remaining: 49.5s
2620:	learn: 0.2027849	test: 0.2107991	best: 0.2107991 (2620)	total: 47.8s	remaining: 49.1s
2640:	learn: 0.2026154	test: 0.2107332	best: 0.2107332 (2640)	total: 48.2s	remaining: 48.7s
2660:	learn: 0.2024403	test: 0.2106452	best: 0.2106440 (2659)	total: 48.6s	remaining: 48.4s
2680:	learn: 0.2022764	test: 0.2105466	best: 0.2105466 (2680)	total: 48.9s	remaining: 48s
2700:	learn: 0.2020825	test: 0.2104574	best: 0.2104574 (2700)	total: 49.3s	remaining: 47.7s
2720:	learn: 0.2019318	test: 0.2104000	best: 0.2104000 (2720)	total: 49.7s	remaining: 47.3s
2740:	learn: 0.2017792	test: 0.2103350	best: 0.2103350 (2740)	total: 50.1s	remaining: 47s
2760:	learn: 0.2016279	test: 0.2102766	best: 0.2102766 (2760)	total: 50.5s	remaining: 46.6s
2780:	learn: 0.2014713	test: 0.2102230	best: 0.2102230 (2780)	total: 50.8s	remaining: 46.3s
2800:	learn: 0.2012985	test: 0.2101675	best: 0.2101665 (2798)	total: 51.2s	remaining: 45.9s
2820:	learn: 0.2011519	test: 0.2101238	best: 0.2101208 (2819)	total: 51.6s	remaining: 45.6s
2840:	learn: 0.2009944	test: 0.2100536	best: 0.2100536 (2840)	total: 52s	remaining: 45.2s
2860:	learn: 0.2008615	test: 0.2100075	best: 0.2100058 (2859)	total: 52.4s	remaining: 44.9s
2880:	learn: 0.2007001	test: 0.2099378	best: 0.2099372 (2878)	total: 52.8s	remaining: 44.5s
2900:	learn: 0.2005634	test: 0.2098738	best: 0.2098738 (2900)	total: 53.1s	remaining: 44.2s
2920:	learn: 0.2004270	test: 0.2098313	best: 0.2098313 (2920)	total: 53.5s	remaining: 43.8s
2940:	learn: 0.2002699	test: 0.2097810	best: 0.2097810 (2940)	total: 53.9s	remaining: 43.5s
2960:	learn: 0.2001275	test: 0.2097520	best: 0.2097441 (2959)	total: 54.3s	remaining: 43.1s
2980:	learn: 0.1999750	test: 0.2096703	best: 0.2096699 (2978)	total: 54.7s	remaining: 42.7s
3000:	learn: 0.1998479	test: 0.2096170	best: 0.2096169 (2998)	total: 55s	remaining: 42.4s
3020:	learn: 0.1996808	test: 0.2095210	best: 0.2095210 (3020)	total: 55.4s	remaining: 42s
3040:	learn: 0.1995444	test: 0.2094637	best: 0.2094637 (3040)	total: 55.8s	remaining: 41.7s
3060:	learn: 0.1994213	test: 0.2094328	best: 0.2094328 (3060)	total: 56.2s	remaining: 41.3s
3080:	learn: 0.1992990	test: 0.2094047	best: 0.2094047 (3080)	total: 56.6s	remaining: 41s
3100:	learn: 0.1991607	test: 0.2093731	best: 0.2093692 (3098)	total: 57s	remaining: 40.6s
3120:	learn: 0.1990224	test: 0.2093086	best: 0.2093086 (3120)	total: 57.4s	remaining: 40.3s
3140:	learn: 0.1989008	test: 0.2092523	best: 0.2092523 (3140)	total: 57.8s	remaining: 39.9s
3160:	learn: 0.1987719	test: 0.2092008	best: 0.2092008 (3160)	total: 58.1s	remaining: 39.6s
3180:	learn: 0.1986263	test: 0.2091515	best: 0.2091515 (3180)	total: 58.5s	remaining: 39.2s
3200:	learn: 0.1984871	test: 0.2090958	best: 0.2090958 (3200)	total: 58.9s	remaining: 38.9s
3220:	learn: 0.1983685	test: 0.2090582	best: 0.2090573 (3219)	total: 59.3s	remaining: 38.5s
3240:	learn: 0.1982314	test: 0.2090192	best: 0.2090192 (3240)	total: 59.7s	remaining: 38.2s
3260:	learn: 0.1981031	test: 0.2089658	best: 0.2089658 (3260)	total: 1m	remaining: 37.8s
3280:	learn: 0.1979654	test: 0.2089208	best: 0.2089208 (3280)	total: 1m	remaining: 37.4s
3300:	learn: 0.1978319	test: 0.2088750	best: 0.2088749 (3299)	total: 1m	remaining: 37.1s
3320:	learn: 0.1977037	test: 0.2088377	best: 0.2088377 (3320)	total: 1m 1s	remaining: 36.7s
3340:	learn: 0.1975722	test: 0.2087916	best: 0.2087916 (3340)	total: 1m 1s	remaining: 36.3s
3360:	learn: 0.1974460	test: 0.2087428	best: 0.2087428 (3360)	total: 1m 1s	remaining: 36s
3380:	learn: 0.1973202	test: 0.2087024	best: 0.2087024 (3380)	total: 1m 2s	remaining: 35.6s
3400:	learn: 0.1971893	test: 0.2086677	best: 0.2086677 (3400)	total: 1m 2s	remaining: 35.3s
3420:	learn: 0.1970613	test: 0.2086327	best: 0.2086327 (3420)	total: 1m 3s	remaining: 34.9s
3440:	learn: 0.1969048	test: 0.2085818	best: 0.2085818 (3440)	total: 1m 3s	remaining: 34.5s
3460:	learn: 0.1967808	test: 0.2085480	best: 0.2085480 (3460)	total: 1m 3s	remaining: 34.2s
3480:	learn: 0.1966534	test: 0.2085193	best: 0.2085193 (3480)	total: 1m 4s	remaining: 33.8s
3500:	learn: 0.1965171	test: 0.2084737	best: 0.2084737 (3500)	total: 1m 4s	remaining: 33.4s
3520:	learn: 0.1963966	test: 0.2084505	best: 0.2084481 (3518)	total: 1m 5s	remaining: 33.1s
3540:	learn: 0.1962747	test: 0.2084266	best: 0.2084244 (3537)	total: 1m 5s	remaining: 32.7s
3560:	learn: 0.1961619	test: 0.2083940	best: 0.2083939 (3559)	total: 1m 5s	remaining: 32.4s
3580:	learn: 0.1960325	test: 0.2083648	best: 0.2083612 (3579)	total: 1m 6s	remaining: 32s
3600:	learn: 0.1959247	test: 0.2083320	best: 0.2083320 (3600)	total: 1m 6s	remaining: 31.6s
3620:	learn: 0.1958226	test: 0.2083063	best: 0.2083056 (3619)	total: 1m 6s	remaining: 31.2s
3640:	learn: 0.1957133	test: 0.2082849	best: 0.2082849 (3640)	total: 1m 7s	remaining: 30.9s
3660:	learn: 0.1955963	test: 0.2082512	best: 0.2082481 (3656)	total: 1m 7s	remaining: 30.5s
3680:	learn: 0.1954311	test: 0.2081719	best: 0.2081719 (3680)	total: 1m 8s	remaining: 30.2s
3700:	learn: 0.1952972	test: 0.2081075	best: 0.2081075 (3700)	total: 1m 8s	remaining: 29.8s
3720:	learn: 0.1951762	test: 0.2080701	best: 0.2080701 (3720)	total: 1m 8s	remaining: 29.4s
3740:	learn: 0.1950408	test: 0.2080206	best: 0.2080206 (3740)	total: 1m 9s	remaining: 29.1s
3760:	learn: 0.1949291	test: 0.2079876	best: 0.2079876 (3760)	total: 1m 9s	remaining: 28.7s
3780:	learn: 0.1948257	test: 0.2079615	best: 0.2079603 (3779)	total: 1m 10s	remaining: 28.3s
3800:	learn: 0.1947043	test: 0.2079285	best: 0.2079197 (3796)	total: 1m 10s	remaining: 28s
3820:	learn: 0.1945787	test: 0.2078737	best: 0.2078737 (3820)	total: 1m 10s	remaining: 27.6s
3840:	learn: 0.1944679	test: 0.2078374	best: 0.2078374 (3840)	total: 1m 11s	remaining: 27.2s
3860:	learn: 0.1943626	test: 0.2077977	best: 0.2077977 (3860)	total: 1m 11s	remaining: 26.9s
3880:	learn: 0.1942291	test: 0.2077571	best: 0.2077571 (3880)	total: 1m 11s	remaining: 26.5s
3900:	learn: 0.1940997	test: 0.2077201	best: 0.2077190 (3899)	total: 1m 12s	remaining: 26.1s
3920:	learn: 0.1939999	test: 0.2076963	best: 0.2076963 (3920)	total: 1m 12s	remaining: 25.8s
3940:	learn: 0.1938703	test: 0.2076675	best: 0.2076654 (3939)	total: 1m 13s	remaining: 25.4s
3960:	learn: 0.1937672	test: 0.2076393	best: 0.2076393 (3960)	total: 1m 13s	remaining: 25.1s
3980:	learn: 0.1936751	test: 0.2076236	best: 0.2076180 (3977)	total: 1m 13s	remaining: 24.7s
4000:	learn: 0.1935597	test: 0.2075907	best: 0.2075907 (4000)	total: 1m 14s	remaining: 24.3s
4020:	learn: 0.1934427	test: 0.2075425	best: 0.2075425 (4020)	total: 1m 14s	remaining: 24s
4040:	learn: 0.1933345	test: 0.2075111	best: 0.2075098 (4037)	total: 1m 15s	remaining: 23.6s
4060:	learn: 0.1932093	test: 0.2074686	best: 0.2074686 (4060)	total: 1m 15s	remaining: 23.2s
4080:	learn: 0.1931016	test: 0.2074557	best: 0.2074557 (4080)	total: 1m 15s	remaining: 22.9s
4100:	learn: 0.1929806	test: 0.2074349	best: 0.2074349 (4100)	total: 1m 16s	remaining: 22.5s
4120:	learn: 0.1928740	test: 0.2074098	best: 0.2074072 (4116)	total: 1m 16s	remaining: 22.1s
4140:	learn: 0.1927658	test: 0.2073767	best: 0.2073767 (4140)	total: 1m 16s	remaining: 21.8s
4160:	learn: 0.1926450	test: 0.2073414	best: 0.2073414 (4160)	total: 1m 17s	remaining: 21.4s
4180:	learn: 0.1925366	test: 0.2073100	best: 0.2073092 (4177)	total: 1m 17s	remaining: 21s
4200:	learn: 0.1924209	test: 0.2072832	best: 0.2072808 (4199)	total: 1m 18s	remaining: 20.6s
4220:	learn: 0.1922947	test: 0.2072262	best: 0.2072231 (4218)	total: 1m 18s	remaining: 20.3s
4240:	learn: 0.1921805	test: 0.2071906	best: 0.2071906 (4240)	total: 1m 18s	remaining: 19.9s
4260:	learn: 0.1920579	test: 0.2071437	best: 0.2071433 (4258)	total: 1m 19s	remaining: 19.5s
4280:	learn: 0.1919440	test: 0.2071140	best: 0.2071130 (4278)	total: 1m 19s	remaining: 19.2s

Saving c:\Darshak\Projects\Hackathon\ag_models4\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\CatBoost_BAG_L1\model.pkl
	0.959	 = Validation score   (roc_auc)
	829.78s	 = Training   runtime
	3.17s	 = Validation runtime
	21338.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Fitting model: XGBoost_BAG_L1 ... Training model for up to 31229.43s of the 31229.43s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47509
[50]	validation_0-logloss:0.26504
[100]	validation_0-logloss:0.24828
[150]	validation_0-logloss:0.23978
[200]	validation_0-logloss:0.23420
[250]	validation_0-logloss:0.23021
[300]	validation_0-logloss:0.22727
[350]	validation_0-logloss:0.22474
[400]	validation_0-logloss:0.22257
[450]	validation_0-logloss:0.22092
[500]	validation_0-logloss:0.21927
[550]	validation_0-logloss:0.21821
[600]	validation_0-logloss:0.21705
[650]	validation_0-logloss:0.21597
[700]	validation_0-logloss:0.21531
[750]	validation_0-logloss:0.21438
[800]	validation_0-logloss:0.21376
[850]	validation_0-logloss:0.21317
[900]	validation_0-logloss:0.21253
[950]	validation_0-logloss:0.21210
[1000]	validation_0-logloss:0.21164
[1050]	validation_0-logloss:0.21130
[1100]	validation_0-logloss:0.21080
[1150]	validation_0-logloss:0.21051
[1200]	validation_0-logloss:0.21013
[1250]	validation_0-logloss:0.20984
[1300]	validation_0-logloss:0.20958
[1350]	validation_0-logloss:0.20945
[1400]	validation_0-logloss:0.20916
[1450]	validation_0-logloss:0.20895
[1500]	validation_0-logloss:0.20882
[1550]	validation_0-logloss:0.20866
[1600]	validation_0-logloss:0.20852
[1650]	validation_0-logloss:0.20822
[1700]	validation_0-logloss:0.20822
[1750]	validation_0-logloss:0.20810
[1800]	validation_0-logloss:0.20808
[1850]	validation_0-logloss:0.20805
[1900]	validation_0-logloss:0.20802
[1950]	validation_0-logloss:0.20785
[2000]	validation_0-logloss:0.20775
[2050]	validation_0-logloss:0.20767
[2100]	validation_0-logloss:0.20761
[2150]	validation_0-logloss:0.20750
[2200]	validation_0-logloss:0.20744
[2250]	validation_0-logloss:0.20747
[2300]	validation_0-logloss:0.20745
[2350]	validation_0-logloss:0.20742
[2400]	validation_0-logloss:0.20742
[2450]	validation_0-logloss:0.20740
[2500]	validation_0-logloss:0.20739
[2550]	validation_0-logloss:0.20741
[2600]	validation_0-logloss:0.20735
[2650]	validation_0-logloss:0.20733
[2700]	validation_0-logloss:0.20732
[2750]	validation_0-logloss:0.20731
[2800]	validation_0-logloss:0.20728
[2850]	validation_0-logloss:0.20739
[2900]	validation_0-logloss:0.20750
[2950]	validation_0-logloss:0.20751
[3000]	validation_0-logloss:0.20760
[3050]	validation_0-logloss:0.20763
[3100]	validation_0-logloss:0.20760
[3150]	validation_0-logloss:0.20769
[3200]	validation_0-logloss:0.20779
[3250]	validation_0-logloss:0.20775
[3300]	validation_0-logloss:0.20779
[3350]	validation_0-logloss:0.20793
[3400]	validation_0-logloss:0.20796
[3450]	validation_0-logloss:0.20793
[3500]	validation_0-logloss:0.20797
[3550]	validation_0-logloss:0.20798
[3600]	validation_0-logloss:0.20792
[3650]	validation_0-logloss:0.20793
[3665]	validation_0-logloss:0.20795

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47517
[50]	validation_0-logloss:0.26543
[100]	validation_0-logloss:0.24950
[150]	validation_0-logloss:0.24147
[200]	validation_0-logloss:0.23602
[250]	validation_0-logloss:0.23181
[300]	validation_0-logloss:0.22822
[350]	validation_0-logloss:0.22554
[400]	validation_0-logloss:0.22311
[450]	validation_0-logloss:0.22133
[500]	validation_0-logloss:0.21946
[550]	validation_0-logloss:0.21826
[600]	validation_0-logloss:0.21677
[650]	validation_0-logloss:0.21598
[700]	validation_0-logloss:0.21519
[750]	validation_0-logloss:0.21470
[800]	validation_0-logloss:0.21411
[850]	validation_0-logloss:0.21361
[900]	validation_0-logloss:0.21309
[950]	validation_0-logloss:0.21271
[1000]	validation_0-logloss:0.21211
[1050]	validation_0-logloss:0.21168
[1100]	validation_0-logloss:0.21133
[1150]	validation_0-logloss:0.21106
[1200]	validation_0-logloss:0.21051
[1250]	validation_0-logloss:0.21023
[1300]	validation_0-logloss:0.20993
[1350]	validation_0-logloss:0.20979
[1400]	validation_0-logloss:0.20962
[1450]	validation_0-logloss:0.20941
[1500]	validation_0-logloss:0.20939
[1550]	validation_0-logloss:0.20928
[1600]	validation_0-logloss:0.20914
[1650]	validation_0-logloss:0.20896
[1700]	validation_0-logloss:0.20890
[1750]	validation_0-logloss:0.20882
[1800]	validation_0-logloss:0.20865
[1850]	validation_0-logloss:0.20855
[1900]	validation_0-logloss:0.20836
[1950]	validation_0-logloss:0.20830
[2000]	validation_0-logloss:0.20813
[2050]	validation_0-logloss:0.20801
[2100]	validation_0-logloss:0.20790
[2150]	validation_0-logloss:0.20777
[2200]	validation_0-logloss:0.20767
[2250]	validation_0-logloss:0.20760
[2300]	validation_0-logloss:0.20758
[2350]	validation_0-logloss:0.20748
[2400]	validation_0-logloss:0.20744
[2450]	validation_0-logloss:0.20743
[2500]	validation_0-logloss:0.20743
[2550]	validation_0-logloss:0.20742
[2600]	validation_0-logloss:0.20744
[2650]	validation_0-logloss:0.20746
[2700]	validation_0-logloss:0.20741
[2750]	validation_0-logloss:0.20738
[2800]	validation_0-logloss:0.20738
[2850]	validation_0-logloss:0.20742
[2900]	validation_0-logloss:0.20744
[2950]	validation_0-logloss:0.20747
[3000]	validation_0-logloss:0.20753
[3050]	validation_0-logloss:0.20758
[3100]	validation_0-logloss:0.20759
[3150]	validation_0-logloss:0.20756
[3200]	validation_0-logloss:0.20762
[3250]	validation_0-logloss:0.20765
[3300]	validation_0-logloss:0.20764
[3350]	validation_0-logloss:0.20764
[3400]	validation_0-logloss:0.20758
[3450]	validation_0-logloss:0.20761
[3500]	validation_0-logloss:0.20766
[3550]	validation_0-logloss:0.20772
[3600]	validation_0-logloss:0.20781
[3633]	validation_0-logloss:0.20782

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47522
[50]	validation_0-logloss:0.26828
[100]	validation_0-logloss:0.25160
[150]	validation_0-logloss:0.24346
[200]	validation_0-logloss:0.23778
[250]	validation_0-logloss:0.23376
[300]	validation_0-logloss:0.23051
[350]	validation_0-logloss:0.22810
[400]	validation_0-logloss:0.22631
[450]	validation_0-logloss:0.22426
[500]	validation_0-logloss:0.22282
[550]	validation_0-logloss:0.22180
[600]	validation_0-logloss:0.22079
[650]	validation_0-logloss:0.21983
[700]	validation_0-logloss:0.21905
[750]	validation_0-logloss:0.21833
[800]	validation_0-logloss:0.21769
[850]	validation_0-logloss:0.21707
[900]	validation_0-logloss:0.21673
[950]	validation_0-logloss:0.21632
[1000]	validation_0-logloss:0.21595
[1050]	validation_0-logloss:0.21554
[1100]	validation_0-logloss:0.21520
[1150]	validation_0-logloss:0.21488
[1200]	validation_0-logloss:0.21465
[1250]	validation_0-logloss:0.21439
[1300]	validation_0-logloss:0.21412
[1350]	validation_0-logloss:0.21391
[1400]	validation_0-logloss:0.21371
[1450]	validation_0-logloss:0.21365
[1500]	validation_0-logloss:0.21352
[1550]	validation_0-logloss:0.21340
[1600]	validation_0-logloss:0.21323
[1650]	validation_0-logloss:0.21321
[1700]	validation_0-logloss:0.21312
[1750]	validation_0-logloss:0.21296
[1800]	validation_0-logloss:0.21279
[1850]	validation_0-logloss:0.21284
[1900]	validation_0-logloss:0.21276
[1950]	validation_0-logloss:0.21267
[2000]	validation_0-logloss:0.21265
[2050]	validation_0-logloss:0.21256
[2100]	validation_0-logloss:0.21240
[2150]	validation_0-logloss:0.21238
[2200]	validation_0-logloss:0.21247
[2250]	validation_0-logloss:0.21250
[2300]	validation_0-logloss:0.21254
[2350]	validation_0-logloss:0.21247
[2400]	validation_0-logloss:0.21246
[2450]	validation_0-logloss:0.21248
[2500]	validation_0-logloss:0.21238
[2550]	validation_0-logloss:0.21234
[2600]	validation_0-logloss:0.21235
[2650]	validation_0-logloss:0.21237
[2700]	validation_0-logloss:0.21242
[2750]	validation_0-logloss:0.21249
[2800]	validation_0-logloss:0.21254
[2850]	validation_0-logloss:0.21262
[2900]	validation_0-logloss:0.21266
[2950]	validation_0-logloss:0.21272
[3000]	validation_0-logloss:0.21278
[3050]	validation_0-logloss:0.21289
[3100]	validation_0-logloss:0.21293
[3150]	validation_0-logloss:0.21295
[3200]	validation_0-logloss:0.21299
[3250]	validation_0-logloss:0.21305
[3300]	validation_0-logloss:0.21313
[3319]	validation_0-logloss:0.21316

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47498
[50]	validation_0-logloss:0.26385
[100]	validation_0-logloss:0.24810
[150]	validation_0-logloss:0.23947
[200]	validation_0-logloss:0.23358
[250]	validation_0-logloss:0.22956
[300]	validation_0-logloss:0.22580
[350]	validation_0-logloss:0.22332
[400]	validation_0-logloss:0.22131
[450]	validation_0-logloss:0.21948
[500]	validation_0-logloss:0.21826
[550]	validation_0-logloss:0.21749
[600]	validation_0-logloss:0.21653
[650]	validation_0-logloss:0.21556
[700]	validation_0-logloss:0.21487
[750]	validation_0-logloss:0.21433
[800]	validation_0-logloss:0.21338
[850]	validation_0-logloss:0.21280
[900]	validation_0-logloss:0.21225
[950]	validation_0-logloss:0.21170
[1000]	validation_0-logloss:0.21127
[1050]	validation_0-logloss:0.21089
[1100]	validation_0-logloss:0.21046
[1150]	validation_0-logloss:0.21016
[1200]	validation_0-logloss:0.20990
[1250]	validation_0-logloss:0.20965
[1300]	validation_0-logloss:0.20940
[1350]	validation_0-logloss:0.20922
[1400]	validation_0-logloss:0.20888
[1450]	validation_0-logloss:0.20873
[1500]	validation_0-logloss:0.20869
[1550]	validation_0-logloss:0.20861
[1600]	validation_0-logloss:0.20844
[1650]	validation_0-logloss:0.20827
[1700]	validation_0-logloss:0.20816
[1750]	validation_0-logloss:0.20809
[1800]	validation_0-logloss:0.20804
[1850]	validation_0-logloss:0.20782
[1900]	validation_0-logloss:0.20770
[1950]	validation_0-logloss:0.20761
[2000]	validation_0-logloss:0.20759
[2050]	validation_0-logloss:0.20754
[2100]	validation_0-logloss:0.20750
[2150]	validation_0-logloss:0.20748
[2200]	validation_0-logloss:0.20753
[2250]	validation_0-logloss:0.20742
[2300]	validation_0-logloss:0.20734
[2350]	validation_0-logloss:0.20736
[2400]	validation_0-logloss:0.20730
[2450]	validation_0-logloss:0.20727
[2500]	validation_0-logloss:0.20729
[2550]	validation_0-logloss:0.20730
[2600]	validation_0-logloss:0.20732
[2650]	validation_0-logloss:0.20726
[2700]	validation_0-logloss:0.20731
[2750]	validation_0-logloss:0.20731
[2800]	validation_0-logloss:0.20736
[2850]	validation_0-logloss:0.20738
[2900]	validation_0-logloss:0.20750
[2950]	validation_0-logloss:0.20755
[3000]	validation_0-logloss:0.20756
[3050]	validation_0-logloss:0.20754
[3100]	validation_0-logloss:0.20757
[3150]	validation_0-logloss:0.20766
[3200]	validation_0-logloss:0.20772
[3250]	validation_0-logloss:0.20776
[3300]	validation_0-logloss:0.20782
[3350]	validation_0-logloss:0.20796
[3400]	validation_0-logloss:0.20803
[3450]	validation_0-logloss:0.20807
[3473]	validation_0-logloss:0.20811

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47510
[50]	validation_0-logloss:0.26437
[100]	validation_0-logloss:0.24852
[150]	validation_0-logloss:0.23961
[200]	validation_0-logloss:0.23456
[250]	validation_0-logloss:0.23081
[300]	validation_0-logloss:0.22766
[350]	validation_0-logloss:0.22497
[400]	validation_0-logloss:0.22241
[450]	validation_0-logloss:0.22081
[500]	validation_0-logloss:0.21954
[550]	validation_0-logloss:0.21799
[600]	validation_0-logloss:0.21669
[650]	validation_0-logloss:0.21602
[700]	validation_0-logloss:0.21517
[750]	validation_0-logloss:0.21426
[800]	validation_0-logloss:0.21352
[850]	validation_0-logloss:0.21274
[900]	validation_0-logloss:0.21211
[950]	validation_0-logloss:0.21149
[1000]	validation_0-logloss:0.21112
[1050]	validation_0-logloss:0.21086
[1100]	validation_0-logloss:0.21045
[1150]	validation_0-logloss:0.21008
[1200]	validation_0-logloss:0.20976
[1250]	validation_0-logloss:0.20960
[1300]	validation_0-logloss:0.20940
[1350]	validation_0-logloss:0.20930
[1400]	validation_0-logloss:0.20913
[1450]	validation_0-logloss:0.20888
[1500]	validation_0-logloss:0.20880
[1550]	validation_0-logloss:0.20877
[1600]	validation_0-logloss:0.20865
[1650]	validation_0-logloss:0.20851
[1700]	validation_0-logloss:0.20826
[1750]	validation_0-logloss:0.20816
[1800]	validation_0-logloss:0.20797
[1850]	validation_0-logloss:0.20784
[1900]	validation_0-logloss:0.20784
[1950]	validation_0-logloss:0.20774
[2000]	validation_0-logloss:0.20765
[2050]	validation_0-logloss:0.20751
[2100]	validation_0-logloss:0.20741
[2150]	validation_0-logloss:0.20742
[2200]	validation_0-logloss:0.20736
[2250]	validation_0-logloss:0.20725
[2300]	validation_0-logloss:0.20722
[2350]	validation_0-logloss:0.20716
[2400]	validation_0-logloss:0.20704
[2450]	validation_0-logloss:0.20707
[2500]	validation_0-logloss:0.20711
[2550]	validation_0-logloss:0.20709
[2600]	validation_0-logloss:0.20708
[2650]	validation_0-logloss:0.20709
[2700]	validation_0-logloss:0.20701
[2750]	validation_0-logloss:0.20706
[2800]	validation_0-logloss:0.20705
[2850]	validation_0-logloss:0.20704
[2900]	validation_0-logloss:0.20700
[2950]	validation_0-logloss:0.20694
[3000]	validation_0-logloss:0.20690
[3050]	validation_0-logloss:0.20699
[3100]	validation_0-logloss:0.20694
[3150]	validation_0-logloss:0.20694
[3200]	validation_0-logloss:0.20704
[3250]	validation_0-logloss:0.20706
[3300]	validation_0-logloss:0.20705
[3350]	validation_0-logloss:0.20709
[3400]	validation_0-logloss:0.20713
[3450]	validation_0-logloss:0.20722
[3500]	validation_0-logloss:0.20727
[3550]	validation_0-logloss:0.20735
[3600]	validation_0-logloss:0.20739
[3650]	validation_0-logloss:0.20737
[3700]	validation_0-logloss:0.20736
[3750]	validation_0-logloss:0.20745
[3800]	validation_0-logloss:0.20753
[3850]	validation_0-logloss:0.20754
[3900]	validation_0-logloss:0.20761
[3901]	validation_0-logloss:0.20761

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47501
[50]	validation_0-logloss:0.26468
[100]	validation_0-logloss:0.24829
[150]	validation_0-logloss:0.24023
[200]	validation_0-logloss:0.23531
[250]	validation_0-logloss:0.23115
[300]	validation_0-logloss:0.22822
[350]	validation_0-logloss:0.22550
[400]	validation_0-logloss:0.22316
[450]	validation_0-logloss:0.22144
[500]	validation_0-logloss:0.21996
[550]	validation_0-logloss:0.21867
[600]	validation_0-logloss:0.21760
[650]	validation_0-logloss:0.21666
[700]	validation_0-logloss:0.21585
[750]	validation_0-logloss:0.21507
[800]	validation_0-logloss:0.21438
[850]	validation_0-logloss:0.21376
[900]	validation_0-logloss:0.21338
[950]	validation_0-logloss:0.21294
[1000]	validation_0-logloss:0.21258
[1050]	validation_0-logloss:0.21227
[1100]	validation_0-logloss:0.21194
[1150]	validation_0-logloss:0.21160
[1200]	validation_0-logloss:0.21127
[1250]	validation_0-logloss:0.21105
[1300]	validation_0-logloss:0.21068
[1350]	validation_0-logloss:0.21048
[1400]	validation_0-logloss:0.21029
[1450]	validation_0-logloss:0.21015
[1500]	validation_0-logloss:0.20995
[1550]	validation_0-logloss:0.20977
[1600]	validation_0-logloss:0.20959
[1650]	validation_0-logloss:0.20944
[1700]	validation_0-logloss:0.20931
[1750]	validation_0-logloss:0.20922
[1800]	validation_0-logloss:0.20915
[1850]	validation_0-logloss:0.20903
[1900]	validation_0-logloss:0.20898
[1950]	validation_0-logloss:0.20892
[2000]	validation_0-logloss:0.20884
[2050]	validation_0-logloss:0.20872
[2100]	validation_0-logloss:0.20870
[2150]	validation_0-logloss:0.20869
[2200]	validation_0-logloss:0.20865
[2250]	validation_0-logloss:0.20863
[2300]	validation_0-logloss:0.20859
[2350]	validation_0-logloss:0.20860
[2400]	validation_0-logloss:0.20858
[2450]	validation_0-logloss:0.20855
[2500]	validation_0-logloss:0.20851
[2550]	validation_0-logloss:0.20855
[2600]	validation_0-logloss:0.20847
[2650]	validation_0-logloss:0.20846
[2700]	validation_0-logloss:0.20853
[2750]	validation_0-logloss:0.20852
[2800]	validation_0-logloss:0.20847
[2850]	validation_0-logloss:0.20859
[2900]	validation_0-logloss:0.20854
[2950]	validation_0-logloss:0.20853
[3000]	validation_0-logloss:0.20860
[3050]	validation_0-logloss:0.20863
[3100]	validation_0-logloss:0.20867
[3150]	validation_0-logloss:0.20864
[3200]	validation_0-logloss:0.20878
[3250]	validation_0-logloss:0.20884
[3300]	validation_0-logloss:0.20889
[3350]	validation_0-logloss:0.20892
[3400]	validation_0-logloss:0.20894
[3429]	validation_0-logloss:0.20895

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47466
[50]	validation_0-logloss:0.26443
[100]	validation_0-logloss:0.24781
[150]	validation_0-logloss:0.23996
[200]	validation_0-logloss:0.23398
[250]	validation_0-logloss:0.23036
[300]	validation_0-logloss:0.22776
[350]	validation_0-logloss:0.22543
[400]	validation_0-logloss:0.22350
[450]	validation_0-logloss:0.22147
[500]	validation_0-logloss:0.22022
[550]	validation_0-logloss:0.21904
[600]	validation_0-logloss:0.21782
[650]	validation_0-logloss:0.21686
[700]	validation_0-logloss:0.21616
[750]	validation_0-logloss:0.21532
[800]	validation_0-logloss:0.21416
[850]	validation_0-logloss:0.21368
[900]	validation_0-logloss:0.21302
[950]	validation_0-logloss:0.21244
[1000]	validation_0-logloss:0.21194
[1050]	validation_0-logloss:0.21163
[1100]	validation_0-logloss:0.21139
[1150]	validation_0-logloss:0.21109
[1200]	validation_0-logloss:0.21088
[1250]	validation_0-logloss:0.21051
[1300]	validation_0-logloss:0.21032
[1350]	validation_0-logloss:0.21018
[1400]	validation_0-logloss:0.20997
[1450]	validation_0-logloss:0.20980
[1500]	validation_0-logloss:0.20968
[1550]	validation_0-logloss:0.20950
[1600]	validation_0-logloss:0.20937
[1650]	validation_0-logloss:0.20924
[1700]	validation_0-logloss:0.20906
[1750]	validation_0-logloss:0.20899
[1800]	validation_0-logloss:0.20892
[1850]	validation_0-logloss:0.20883
[1900]	validation_0-logloss:0.20879
[1950]	validation_0-logloss:0.20875
[2000]	validation_0-logloss:0.20872
[2050]	validation_0-logloss:0.20858
[2100]	validation_0-logloss:0.20849
[2150]	validation_0-logloss:0.20842
[2200]	validation_0-logloss:0.20840
[2250]	validation_0-logloss:0.20837
[2300]	validation_0-logloss:0.20835
[2350]	validation_0-logloss:0.20833
[2400]	validation_0-logloss:0.20827
[2450]	validation_0-logloss:0.20823
[2500]	validation_0-logloss:0.20825
[2550]	validation_0-logloss:0.20819
[2600]	validation_0-logloss:0.20817
[2650]	validation_0-logloss:0.20813
[2700]	validation_0-logloss:0.20813
[2750]	validation_0-logloss:0.20816
[2800]	validation_0-logloss:0.20818
[2850]	validation_0-logloss:0.20822
[2900]	validation_0-logloss:0.20822
[2950]	validation_0-logloss:0.20822
[3000]	validation_0-logloss:0.20819
[3050]	validation_0-logloss:0.20821
[3100]	validation_0-logloss:0.20832
[3150]	validation_0-logloss:0.20830
[3200]	validation_0-logloss:0.20834
[3250]	validation_0-logloss:0.20834
[3300]	validation_0-logloss:0.20844
[3350]	validation_0-logloss:0.20847
[3400]	validation_0-logloss:0.20850
[3450]	validation_0-logloss:0.20853
[3500]	validation_0-logloss:0.20860
[3503]	validation_0-logloss:0.20859

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47463
[50]	validation_0-logloss:0.26261
[100]	validation_0-logloss:0.24656
[150]	validation_0-logloss:0.23869
[200]	validation_0-logloss:0.23268
[250]	validation_0-logloss:0.22892
[300]	validation_0-logloss:0.22598
[350]	validation_0-logloss:0.22332
[400]	validation_0-logloss:0.22158
[450]	validation_0-logloss:0.22002
[500]	validation_0-logloss:0.21854
[550]	validation_0-logloss:0.21741
[600]	validation_0-logloss:0.21596
[650]	validation_0-logloss:0.21506
[700]	validation_0-logloss:0.21430
[750]	validation_0-logloss:0.21365
[800]	validation_0-logloss:0.21292
[850]	validation_0-logloss:0.21226
[900]	validation_0-logloss:0.21174
[950]	validation_0-logloss:0.21121
[1000]	validation_0-logloss:0.21073
[1050]	validation_0-logloss:0.21027
[1100]	validation_0-logloss:0.21002
[1150]	validation_0-logloss:0.20972
[1200]	validation_0-logloss:0.20935
[1250]	validation_0-logloss:0.20916
[1300]	validation_0-logloss:0.20897
[1350]	validation_0-logloss:0.20880
[1400]	validation_0-logloss:0.20861
[1450]	validation_0-logloss:0.20846
[1500]	validation_0-logloss:0.20834
[1550]	validation_0-logloss:0.20826
[1600]	validation_0-logloss:0.20813
[1650]	validation_0-logloss:0.20800
[1700]	validation_0-logloss:0.20787
[1750]	validation_0-logloss:0.20780
[1800]	validation_0-logloss:0.20769
[1850]	validation_0-logloss:0.20774
[1900]	validation_0-logloss:0.20755
[1950]	validation_0-logloss:0.20751
[2000]	validation_0-logloss:0.20751
[2050]	validation_0-logloss:0.20725
[2100]	validation_0-logloss:0.20714
[2150]	validation_0-logloss:0.20711
[2200]	validation_0-logloss:0.20704
[2250]	validation_0-logloss:0.20707
[2300]	validation_0-logloss:0.20705
[2350]	validation_0-logloss:0.20708
[2400]	validation_0-logloss:0.20707
[2450]	validation_0-logloss:0.20706
[2500]	validation_0-logloss:0.20707
[2550]	validation_0-logloss:0.20706
[2600]	validation_0-logloss:0.20705
[2650]	validation_0-logloss:0.20707
[2700]	validation_0-logloss:0.20704
[2750]	validation_0-logloss:0.20705
[2800]	validation_0-logloss:0.20702
[2850]	validation_0-logloss:0.20712
[2900]	validation_0-logloss:0.20710
[2950]	validation_0-logloss:0.20704
[3000]	validation_0-logloss:0.20703
[3050]	validation_0-logloss:0.20708
[3100]	validation_0-logloss:0.20706
[3150]	validation_0-logloss:0.20714
[3200]	validation_0-logloss:0.20722
[3250]	validation_0-logloss:0.20728
[3300]	validation_0-logloss:0.20732
[3350]	validation_0-logloss:0.20733
[3400]	validation_0-logloss:0.20739
[3450]	validation_0-logloss:0.20749
[3500]	validation_0-logloss:0.20757
[3550]	validation_0-logloss:0.20764
[3600]	validation_0-logloss:0.20773
[3650]	validation_0-logloss:0.20777
[3673]	validation_0-logloss:0.20780

Saving c:\Darshak\Projects\Hackathon\ag_models4\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\XGBoost_BAG_L1\model.pkl
	0.9587	 = Validation score   (roc_auc)
	613.84s	 = Training   runtime
	4.05s	 = Validation runtime
	16664.4	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\CatBoost_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 3239.89s of the 30610.71s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/5.5 GB
Ensemble size: 24
Ensemble weights:
[0.04166667 0.04166667 0.45833333 0.45833333]
	0.57s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'CatBoost_BAG_L1': 0.458, 'XGBoost_BAG_L1': 0.458, 'LightGBM_BAG_L1': 0.042, 'LightGBMLarge_BAG_L1': 0.042}
	0.9605	 = Validation score   (roc_auc)
	5.02s	 = Training   runtime
	0.05s	 = Validation runtime
	2682.7	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
AutoGluon training complete, total runtime = 1794.45s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 2682.7 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models4\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models4\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models4")

In [161]:
leaderboard = predictor.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.960512,roc_auc,25.226204,1758.618675,0.050089,5.023120,2,True,5
1,CatBoost_BAG_L1,0.959010,roc_auc,3.165922,829.781863,3.165922,829.781863,1,True,3
2,XGBoost_BAG_L1,0.958686,roc_auc,4.053901,613.844760,4.053901,613.844760,1,True,4
3,LightGBMLarge_BAG_L1,0.953884,roc_auc,12.682142,203.142475,12.682142,203.142475,1,True,2
4,LightGBM_BAG_L1,0.951644,roc_auc,5.274150,106.826458,5.274150,106.826458,1,True,1

In [8]:
predictor = TabularPredictor.load(f"ag_models4")

In [25]:
df=predictor.predict_proba(df_test)
df.head()

          0         1
0  0.994774  0.005226
1  0.992815  0.007185
2  0.994747  0.005253
3  0.881715  0.118285
4  0.090523  0.909477

In [163]:
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [164]:
df_sample_out['PitNextLap']=df[1]

In [165]:
df_sample_out.to_csv("My_output/all_model_together_best_fe_1.csv", index=False)

In [ ]:
#Try without driver

In [166]:
df_train_merged_wo_driver = df_train_merged.drop("Driver", axis=1)
df_train_wo_driver = df_train.drop("Driver", axis=1)
df_test_wo_driver = df_test.drop("Driver", axis=1)

In [ ]:
predictor_wo_driver = TabularPredictor(label=TARGET,eval_metric='roc_auc', path='ag_models8').fit(
    train_data=df_train_merged_wo_driver,
    ag_args_fit={"num_gpus": 1},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=0,
    hyperparameters=models,
)

Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.8.0+cu129
CUDA Version:       12.9
GPU Memory:         GPU 0: 15.93/15.93 GB
Total GPU Memory:   Free: 15.93 GB, Allocated: 0.00 GB, Total: 15.93 GB
GPU Count:          1
Memory Avail:       4.30 GB / 15.06 GB (28.6%)
Disk Space Avail:   663.17 GB / 930.47 GB (71.3%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'adapt_num_bag_folds_to_n_classes': False,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 1},
 'auto_stack': True,
 'aux_kwargs': None,
 'calibrate': 'auto',
 'core_kwargs': None,
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'time_limit_preprocessing': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'validation_size_curves': None,
 'validation_structure': None,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving c:\Darshak\Projects\Hackathon\ag_models8\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\predictor.pkl
Beginning AutoGluon training ... Time limit = 32400s
AutoGluon will save models to "c:\Darshak\Projects\Hackathon\ag_models8"
Train Data Rows:    540445
Train Data Columns: 21
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4428.89 MB
	Train Data (Original)  Memory Usage: 142.07 MB (3.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', 'object') :  2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
				('object', []) :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			21 features in original data used to generate 21 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
				('object', [])    :  2 | ['Compound', 'Race']
			0.1s = Fit runtime
			21 features in original data used to generate 21 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			19 features in original data used to generate 19 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.0s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.1s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.1s = Fit runtime
			21 features in original data used to generate 21 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  2 | ['Compound', 'Race']
				('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
				('int', ['bool']) :  1 | ['PitStop']
			0.0s = Fit runtime
			21 features in original data used to generate 21 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', 'object') :  2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    :  6 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position', ...]
		('object', []) :  2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  2 | ['Compound', 'Race']
		('float64', 'float')     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int8', 'int')          :  1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['Compound', 'Race']
		('float', [])     : 13 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       :  5 | ['Year', 'LapNumber', 'Stint', 'Position', 'MaxTireLife']
		('int', ['bool']) :  1 | ['PitStop']
	0.9s = Fit runtime
	21 features in original data used to generate 21 features in processed data.
	Train Data (Processed) Memory Usage: 75.77 MB (1.8% of available memory)
Data preprocessing and feature engineering runtime = 0.96s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving c:\Darshak\Projects\Hackathon\ag_models8\learner.pkl
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'Large'}}],
	'XGB': [{}],
	'CAT': [{}],
}
Saving c:\Darshak\Projects\Hackathon\ag_models8\utils\data\X.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\utils\data\y.pkl
Model configs that will be trained (in order):
	LightGBM_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	LightGBMLarge_BAG_L1: 	{'extra_trees': True, 'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'name_suffix': 'Large', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}, 'ag_args_fit': {'num_gpus': 1}}
	CatBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}, 'ag_args_fit': {'num_gpus': 1}}
	XGBoost_BAG_L1: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'softclass'], 'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}, 'ag_args_fit': {'num_gpus': 1}}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 32399.04s of the 32399.03s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.28329
[100]	valid_set's binary_logloss: 0.258729
[150]	valid_set's binary_logloss: 0.248807
[200]	valid_set's binary_logloss: 0.243726
[250]	valid_set's binary_logloss: 0.240096
[300]	valid_set's binary_logloss: 0.237042
[350]	valid_set's binary_logloss: 0.234653
[400]	valid_set's binary_logloss: 0.232601
[450]	valid_set's binary_logloss: 0.230833
[500]	valid_set's binary_logloss: 0.22939
[550]	valid_set's binary_logloss: 0.228018
[600]	valid_set's binary_logloss: 0.226967
[650]	valid_set's binary_logloss: 0.225923
[700]	valid_set's binary_logloss: 0.225019
[750]	valid_set's binary_logloss: 0.22409
[800]	valid_set's binary_logloss: 0.223413
[850]	valid_set's binary_logloss: 0.222513
[900]	valid_set's binary_logloss: 0.221685
[950]	valid_set's binary_logloss: 0.220989
[1000]	valid_set's binary_logloss: 0.22048
[1050]	valid_set's binary_logloss: 0.220011
[1100]	valid_set's binary_logloss: 0.219554
[1150]	valid_set's binary_logloss: 0.219099
[1200]	valid_set's binary_logloss: 0.218756
[1250]	valid_set's binary_logloss: 0.218389
[1300]	valid_set's binary_logloss: 0.218011
[1350]	valid_set's binary_logloss: 0.217575
[1400]	valid_set's binary_logloss: 0.21703
[1450]	valid_set's binary_logloss: 0.216701
[1500]	valid_set's binary_logloss: 0.216422
[1550]	valid_set's binary_logloss: 0.216108
[1600]	valid_set's binary_logloss: 0.215896
[1650]	valid_set's binary_logloss: 0.215534
[1700]	valid_set's binary_logloss: 0.215368
[1750]	valid_set's binary_logloss: 0.215086
[1800]	valid_set's binary_logloss: 0.214756
[1850]	valid_set's binary_logloss: 0.214546
[1900]	valid_set's binary_logloss: 0.214323
[1950]	valid_set's binary_logloss: 0.214119
[2000]	valid_set's binary_logloss: 0.213902
[2050]	valid_set's binary_logloss: 0.213761
[2100]	valid_set's binary_logloss: 0.213583
[2150]	valid_set's binary_logloss: 0.213487
[2200]	valid_set's binary_logloss: 0.213392
[2250]	valid_set's binary_logloss: 0.213244
[2300]	valid_set's binary_logloss: 0.213098
[2350]	valid_set's binary_logloss: 0.212973
[2400]	valid_set's binary_logloss: 0.212812
[2450]	valid_set's binary_logloss: 0.212655
[2500]	valid_set's binary_logloss: 0.212531
[2550]	valid_set's binary_logloss: 0.212395
[2600]	valid_set's binary_logloss: 0.212269
[2650]	valid_set's binary_logloss: 0.212153
[2700]	valid_set's binary_logloss: 0.212051
[2750]	valid_set's binary_logloss: 0.211924
[2800]	valid_set's binary_logloss: 0.211717
[2850]	valid_set's binary_logloss: 0.211621
[2900]	valid_set's binary_logloss: 0.211511
[2950]	valid_set's binary_logloss: 0.211441
[3000]	valid_set's binary_logloss: 0.211336
[3050]	valid_set's binary_logloss: 0.211238
[3100]	valid_set's binary_logloss: 0.211141
[3150]	valid_set's binary_logloss: 0.211085
[3200]	valid_set's binary_logloss: 0.211006
[3250]	valid_set's binary_logloss: 0.210981
[3300]	valid_set's binary_logloss: 0.210889
[3350]	valid_set's binary_logloss: 0.210817
[3400]	valid_set's binary_logloss: 0.21071
[3450]	valid_set's binary_logloss: 0.210649
[3500]	valid_set's binary_logloss: 0.210607
[3550]	valid_set's binary_logloss: 0.210559
[3600]	valid_set's binary_logloss: 0.210505
[3650]	valid_set's binary_logloss: 0.210441
[3700]	valid_set's binary_logloss: 0.210323
[3750]	valid_set's binary_logloss: 0.21018
[3800]	valid_set's binary_logloss: 0.210153
[3850]	valid_set's binary_logloss: 0.210081
[3900]	valid_set's binary_logloss: 0.210037
[3950]	valid_set's binary_logloss: 0.209958
[4000]	valid_set's binary_logloss: 0.209896
[4050]	valid_set's binary_logloss: 0.209801
[4100]	valid_set's binary_logloss: 0.20977
[4150]	valid_set's binary_logloss: 0.209711
[4200]	valid_set's binary_logloss: 0.209642
[4250]	valid_set's binary_logloss: 0.209589
[4300]	valid_set's binary_logloss: 0.209548
[4350]	valid_set's binary_logloss: 0.209439
[4400]	valid_set's binary_logloss: 0.209415
[4450]	valid_set's binary_logloss: 0.209404
[4500]	valid_set's binary_logloss: 0.209388
[4550]	valid_set's binary_logloss: 0.209369
[4600]	valid_set's binary_logloss: 0.209319
[4650]	valid_set's binary_logloss: 0.209323
[4700]	valid_set's binary_logloss: 0.20927
[4750]	valid_set's binary_logloss: 0.209238
[4800]	valid_set's binary_logloss: 0.209202
[4850]	valid_set's binary_logloss: 0.209166
[4900]	valid_set's binary_logloss: 0.209164
[4950]	valid_set's binary_logloss: 0.20917
[5000]	valid_set's binary_logloss: 0.209145
[5050]	valid_set's binary_logloss: 0.209091
[5100]	valid_set's binary_logloss: 0.209062
[5150]	valid_set's binary_logloss: 0.209042
[5200]	valid_set's binary_logloss: 0.209004
[5250]	valid_set's binary_logloss: 0.208988
[5300]	valid_set's binary_logloss: 0.208966
[5350]	valid_set's binary_logloss: 0.208939
[5400]	valid_set's binary_logloss: 0.2089
[5450]	valid_set's binary_logloss: 0.208927
[5500]	valid_set's binary_logloss: 0.208956
[5550]	valid_set's binary_logloss: 0.20892
[5600]	valid_set's binary_logloss: 0.208904
[5650]	valid_set's binary_logloss: 0.208872
[5700]	valid_set's binary_logloss: 0.208842
[5750]	valid_set's binary_logloss: 0.208847
[5800]	valid_set's binary_logloss: 0.208834
[5850]	valid_set's binary_logloss: 0.208818
[5900]	valid_set's binary_logloss: 0.2088
[5950]	valid_set's binary_logloss: 0.208799
[6000]	valid_set's binary_logloss: 0.208753
[6050]	valid_set's binary_logloss: 0.208766
[6100]	valid_set's binary_logloss: 0.208761
[6150]	valid_set's binary_logloss: 0.208744
[6200]	valid_set's binary_logloss: 0.208752
[6250]	valid_set's binary_logloss: 0.208763
[6300]	valid_set's binary_logloss: 0.208755
[6350]	valid_set's binary_logloss: 0.20877
[6400]	valid_set's binary_logloss: 0.208711
[6450]	valid_set's binary_logloss: 0.208691
[6500]	valid_set's binary_logloss: 0.208705
[6550]	valid_set's binary_logloss: 0.208698
[6600]	valid_set's binary_logloss: 0.20866
[6650]	valid_set's binary_logloss: 0.208649
[6700]	valid_set's binary_logloss: 0.208686
[6750]	valid_set's binary_logloss: 0.208664
[6800]	valid_set's binary_logloss: 0.208666
[6850]	valid_set's binary_logloss: 0.208701
[6900]	valid_set's binary_logloss: 0.208727
[6950]	valid_set's binary_logloss: 0.208724
[7000]	valid_set's binary_logloss: 0.208717
[7050]	valid_set's binary_logloss: 0.208703
[7100]	valid_set's binary_logloss: 0.208707
[7150]	valid_set's binary_logloss: 0.208709
[7200]	valid_set's binary_logloss: 0.208712
[7250]	valid_set's binary_logloss: 0.208733
[7300]	valid_set's binary_logloss: 0.208741
[7350]	valid_set's binary_logloss: 0.208726
[7400]	valid_set's binary_logloss: 0.208699
[7450]	valid_set's binary_logloss: 0.208755
[7500]	valid_set's binary_logloss: 0.208785
[7550]	valid_set's binary_logloss: 0.208823
[7600]	valid_set's binary_logloss: 0.208852
[7650]	valid_set's binary_logloss: 0.208866
[7700]	valid_set's binary_logloss: 0.208879
[7750]	valid_set's binary_logloss: 0.208902
[7800]	valid_set's binary_logloss: 0.208883
[7850]	valid_set's binary_logloss: 0.208884
[7900]	valid_set's binary_logloss: 0.208907
[7950]	valid_set's binary_logloss: 0.208922
[8000]	valid_set's binary_logloss: 0.208913
[8050]	valid_set's binary_logloss: 0.208939
[8100]	valid_set's binary_logloss: 0.20896
[8150]	valid_set's binary_logloss: 0.208992
[8200]	valid_set's binary_logloss: 0.209028
[8250]	valid_set's binary_logloss: 0.209028
[8300]	valid_set's binary_logloss: 0.20902
[8350]	valid_set's binary_logloss: 0.20902
[8400]	valid_set's binary_logloss: 0.209035
[8450]	valid_set's binary_logloss: 0.209081
[8500]	valid_set's binary_logloss: 0.209125
[8550]	valid_set's binary_logloss: 0.209134
[8600]	valid_set's binary_logloss: 0.209183

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.285085
[100]	valid_set's binary_logloss: 0.260159
[150]	valid_set's binary_logloss: 0.249919
[200]	valid_set's binary_logloss: 0.24446
[250]	valid_set's binary_logloss: 0.240438
[300]	valid_set's binary_logloss: 0.237546
[350]	valid_set's binary_logloss: 0.235152
[400]	valid_set's binary_logloss: 0.233362
[450]	valid_set's binary_logloss: 0.231823
[500]	valid_set's binary_logloss: 0.230332
[550]	valid_set's binary_logloss: 0.228916
[600]	valid_set's binary_logloss: 0.227803
[650]	valid_set's binary_logloss: 0.226619
[700]	valid_set's binary_logloss: 0.225739
[750]	valid_set's binary_logloss: 0.224895
[800]	valid_set's binary_logloss: 0.223947
[850]	valid_set's binary_logloss: 0.223155
[900]	valid_set's binary_logloss: 0.222446
[950]	valid_set's binary_logloss: 0.221821
[1000]	valid_set's binary_logloss: 0.22103
[1050]	valid_set's binary_logloss: 0.220512
[1100]	valid_set's binary_logloss: 0.21986
[1150]	valid_set's binary_logloss: 0.219265
[1200]	valid_set's binary_logloss: 0.218877
[1250]	valid_set's binary_logloss: 0.218531
[1300]	valid_set's binary_logloss: 0.21802
[1350]	valid_set's binary_logloss: 0.217609
[1400]	valid_set's binary_logloss: 0.217332
[1450]	valid_set's binary_logloss: 0.216951
[1500]	valid_set's binary_logloss: 0.216668
[1550]	valid_set's binary_logloss: 0.216353
[1600]	valid_set's binary_logloss: 0.216097
[1650]	valid_set's binary_logloss: 0.21586
[1700]	valid_set's binary_logloss: 0.215647
[1750]	valid_set's binary_logloss: 0.215356
[1800]	valid_set's binary_logloss: 0.215045
[1850]	valid_set's binary_logloss: 0.214729
[1900]	valid_set's binary_logloss: 0.214426
[1950]	valid_set's binary_logloss: 0.214157
[2000]	valid_set's binary_logloss: 0.213879
[2050]	valid_set's binary_logloss: 0.213678
[2100]	valid_set's binary_logloss: 0.213463
[2150]	valid_set's binary_logloss: 0.213174
[2200]	valid_set's binary_logloss: 0.212969
[2250]	valid_set's binary_logloss: 0.21271
[2300]	valid_set's binary_logloss: 0.212583
[2350]	valid_set's binary_logloss: 0.212451
[2400]	valid_set's binary_logloss: 0.212309
[2450]	valid_set's binary_logloss: 0.212239
[2500]	valid_set's binary_logloss: 0.212087
[2550]	valid_set's binary_logloss: 0.211973
[2600]	valid_set's binary_logloss: 0.211823
[2650]	valid_set's binary_logloss: 0.211687
[2700]	valid_set's binary_logloss: 0.211507
[2750]	valid_set's binary_logloss: 0.211344
[2800]	valid_set's binary_logloss: 0.211178
[2850]	valid_set's binary_logloss: 0.211001
[2900]	valid_set's binary_logloss: 0.210927
[2950]	valid_set's binary_logloss: 0.210832
[3000]	valid_set's binary_logloss: 0.210696
[3050]	valid_set's binary_logloss: 0.210603
[3100]	valid_set's binary_logloss: 0.210496
[3150]	valid_set's binary_logloss: 0.210431
[3200]	valid_set's binary_logloss: 0.210336
[3250]	valid_set's binary_logloss: 0.210287
[3300]	valid_set's binary_logloss: 0.210228
[3350]	valid_set's binary_logloss: 0.210144
[3400]	valid_set's binary_logloss: 0.210071
[3450]	valid_set's binary_logloss: 0.209957
[3500]	valid_set's binary_logloss: 0.209879
[3550]	valid_set's binary_logloss: 0.209842
[3600]	valid_set's binary_logloss: 0.209798
[3650]	valid_set's binary_logloss: 0.209767
[3700]	valid_set's binary_logloss: 0.209647
[3750]	valid_set's binary_logloss: 0.209571
[3800]	valid_set's binary_logloss: 0.209512
[3850]	valid_set's binary_logloss: 0.209441
[3900]	valid_set's binary_logloss: 0.209384
[3950]	valid_set's binary_logloss: 0.209356
[4000]	valid_set's binary_logloss: 0.209333
[4050]	valid_set's binary_logloss: 0.209299
[4100]	valid_set's binary_logloss: 0.209292
[4150]	valid_set's binary_logloss: 0.20925
[4200]	valid_set's binary_logloss: 0.209228
[4250]	valid_set's binary_logloss: 0.2092
[4300]	valid_set's binary_logloss: 0.209156
[4350]	valid_set's binary_logloss: 0.209098
[4400]	valid_set's binary_logloss: 0.209068
[4450]	valid_set's binary_logloss: 0.209032
[4500]	valid_set's binary_logloss: 0.208968
[4550]	valid_set's binary_logloss: 0.208929
[4600]	valid_set's binary_logloss: 0.208853
[4650]	valid_set's binary_logloss: 0.2088
[4700]	valid_set's binary_logloss: 0.208757
[4750]	valid_set's binary_logloss: 0.208739
[4800]	valid_set's binary_logloss: 0.208751
[4850]	valid_set's binary_logloss: 0.208715
[4900]	valid_set's binary_logloss: 0.208699
[4950]	valid_set's binary_logloss: 0.208683
[5000]	valid_set's binary_logloss: 0.208663
[5050]	valid_set's binary_logloss: 0.208628
[5100]	valid_set's binary_logloss: 0.208573
[5150]	valid_set's binary_logloss: 0.208592
[5200]	valid_set's binary_logloss: 0.208551
[5250]	valid_set's binary_logloss: 0.208521
[5300]	valid_set's binary_logloss: 0.208521
[5350]	valid_set's binary_logloss: 0.208528
[5400]	valid_set's binary_logloss: 0.208508
[5450]	valid_set's binary_logloss: 0.208542
[5500]	valid_set's binary_logloss: 0.208537
[5550]	valid_set's binary_logloss: 0.208497
[5600]	valid_set's binary_logloss: 0.208453
[5650]	valid_set's binary_logloss: 0.208448
[5700]	valid_set's binary_logloss: 0.208443
[5750]	valid_set's binary_logloss: 0.20841
[5800]	valid_set's binary_logloss: 0.208385
[5850]	valid_set's binary_logloss: 0.20834
[5900]	valid_set's binary_logloss: 0.208303
[5950]	valid_set's binary_logloss: 0.208305
[6000]	valid_set's binary_logloss: 0.208337
[6050]	valid_set's binary_logloss: 0.208304
[6100]	valid_set's binary_logloss: 0.208314
[6150]	valid_set's binary_logloss: 0.208297
[6200]	valid_set's binary_logloss: 0.208292
[6250]	valid_set's binary_logloss: 0.208296
[6300]	valid_set's binary_logloss: 0.208307
[6350]	valid_set's binary_logloss: 0.208265
[6400]	valid_set's binary_logloss: 0.208242
[6450]	valid_set's binary_logloss: 0.208254
[6500]	valid_set's binary_logloss: 0.208215
[6550]	valid_set's binary_logloss: 0.208224
[6600]	valid_set's binary_logloss: 0.208257
[6650]	valid_set's binary_logloss: 0.20823
[6700]	valid_set's binary_logloss: 0.208212
[6750]	valid_set's binary_logloss: 0.208195
[6800]	valid_set's binary_logloss: 0.208156
[6850]	valid_set's binary_logloss: 0.208106
[6900]	valid_set's binary_logloss: 0.208124
[6950]	valid_set's binary_logloss: 0.208113
[7000]	valid_set's binary_logloss: 0.208121
[7050]	valid_set's binary_logloss: 0.208133
[7100]	valid_set's binary_logloss: 0.208132
[7150]	valid_set's binary_logloss: 0.208166
[7200]	valid_set's binary_logloss: 0.208145
[7250]	valid_set's binary_logloss: 0.20812
[7300]	valid_set's binary_logloss: 0.208102
[7350]	valid_set's binary_logloss: 0.208073
[7400]	valid_set's binary_logloss: 0.208043
[7450]	valid_set's binary_logloss: 0.208022
[7500]	valid_set's binary_logloss: 0.208044
[7550]	valid_set's binary_logloss: 0.208068
[7600]	valid_set's binary_logloss: 0.208047
[7650]	valid_set's binary_logloss: 0.208048
[7700]	valid_set's binary_logloss: 0.208024
[7750]	valid_set's binary_logloss: 0.208036
[7800]	valid_set's binary_logloss: 0.208024
[7850]	valid_set's binary_logloss: 0.208038
[7900]	valid_set's binary_logloss: 0.208036
[7950]	valid_set's binary_logloss: 0.208045
[8000]	valid_set's binary_logloss: 0.20805
[8050]	valid_set's binary_logloss: 0.208061
[8100]	valid_set's binary_logloss: 0.208058
[8150]	valid_set's binary_logloss: 0.208056
[8200]	valid_set's binary_logloss: 0.20808
[8250]	valid_set's binary_logloss: 0.208093
[8300]	valid_set's binary_logloss: 0.208106
[8350]	valid_set's binary_logloss: 0.208124
[8400]	valid_set's binary_logloss: 0.208156
[8450]	valid_set's binary_logloss: 0.208194
[8500]	valid_set's binary_logloss: 0.208189
[8550]	valid_set's binary_logloss: 0.2082
[8600]	valid_set's binary_logloss: 0.208223
[8650]	valid_set's binary_logloss: 0.208264
[8700]	valid_set's binary_logloss: 0.208287
[8750]	valid_set's binary_logloss: 0.208295
[8800]	valid_set's binary_logloss: 0.208269
[8850]	valid_set's binary_logloss: 0.208305
[8900]	valid_set's binary_logloss: 0.208338
[8950]	valid_set's binary_logloss: 0.208354
[9000]	valid_set's binary_logloss: 0.208403
[9050]	valid_set's binary_logloss: 0.208387
[9100]	valid_set's binary_logloss: 0.208407
[9150]	valid_set's binary_logloss: 0.208474
[9200]	valid_set's binary_logloss: 0.20849
[9250]	valid_set's binary_logloss: 0.208519
[9300]	valid_set's binary_logloss: 0.208548
[9350]	valid_set's binary_logloss: 0.208548
[9400]	valid_set's binary_logloss: 0.208575
[9450]	valid_set's binary_logloss: 0.208586
[9500]	valid_set's binary_logloss: 0.208626
[9550]	valid_set's binary_logloss: 0.208688
[9600]	valid_set's binary_logloss: 0.208718
[9650]	valid_set's binary_logloss: 0.208756
[9700]	valid_set's binary_logloss: 0.208771
[9750]	valid_set's binary_logloss: 0.208764
[9800]	valid_set's binary_logloss: 0.208802
[9850]	valid_set's binary_logloss: 0.208824
[9900]	valid_set's binary_logloss: 0.208889
[9950]	valid_set's binary_logloss: 0.2089
[10000]	valid_set's binary_logloss: 0.208935

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.286944
[100]	valid_set's binary_logloss: 0.262049
[150]	valid_set's binary_logloss: 0.252021
[200]	valid_set's binary_logloss: 0.246446
[250]	valid_set's binary_logloss: 0.242621
[300]	valid_set's binary_logloss: 0.23988
[350]	valid_set's binary_logloss: 0.237522
[400]	valid_set's binary_logloss: 0.235599
[450]	valid_set's binary_logloss: 0.233499
[500]	valid_set's binary_logloss: 0.231977
[550]	valid_set's binary_logloss: 0.230728
[600]	valid_set's binary_logloss: 0.229281
[650]	valid_set's binary_logloss: 0.228149
[700]	valid_set's binary_logloss: 0.227346
[750]	valid_set's binary_logloss: 0.226493
[800]	valid_set's binary_logloss: 0.225915
[850]	valid_set's binary_logloss: 0.225134
[900]	valid_set's binary_logloss: 0.22459
[950]	valid_set's binary_logloss: 0.22405
[1000]	valid_set's binary_logloss: 0.223349
[1050]	valid_set's binary_logloss: 0.222761
[1100]	valid_set's binary_logloss: 0.222274
[1150]	valid_set's binary_logloss: 0.221856
[1200]	valid_set's binary_logloss: 0.221458
[1250]	valid_set's binary_logloss: 0.221048
[1300]	valid_set's binary_logloss: 0.220701
[1350]	valid_set's binary_logloss: 0.220322
[1400]	valid_set's binary_logloss: 0.219908
[1450]	valid_set's binary_logloss: 0.219606
[1500]	valid_set's binary_logloss: 0.219379
[1550]	valid_set's binary_logloss: 0.219141
[1600]	valid_set's binary_logloss: 0.218887
[1650]	valid_set's binary_logloss: 0.218694
[1700]	valid_set's binary_logloss: 0.218482
[1750]	valid_set's binary_logloss: 0.218274
[1800]	valid_set's binary_logloss: 0.218138
[1850]	valid_set's binary_logloss: 0.217899
[1900]	valid_set's binary_logloss: 0.217758
[1950]	valid_set's binary_logloss: 0.217523
[2000]	valid_set's binary_logloss: 0.217414
[2050]	valid_set's binary_logloss: 0.217258
[2100]	valid_set's binary_logloss: 0.217113
[2150]	valid_set's binary_logloss: 0.216901
[2200]	valid_set's binary_logloss: 0.216775
[2250]	valid_set's binary_logloss: 0.216691
[2300]	valid_set's binary_logloss: 0.216506
[2350]	valid_set's binary_logloss: 0.21642
[2400]	valid_set's binary_logloss: 0.216261
[2450]	valid_set's binary_logloss: 0.216111
[2500]	valid_set's binary_logloss: 0.21596
[2550]	valid_set's binary_logloss: 0.215853
[2600]	valid_set's binary_logloss: 0.215737
[2650]	valid_set's binary_logloss: 0.215619
[2700]	valid_set's binary_logloss: 0.215467
[2750]	valid_set's binary_logloss: 0.215383
[2800]	valid_set's binary_logloss: 0.21527
[2850]	valid_set's binary_logloss: 0.215235
[2900]	valid_set's binary_logloss: 0.215141
[2950]	valid_set's binary_logloss: 0.215069
[3000]	valid_set's binary_logloss: 0.214932
[3050]	valid_set's binary_logloss: 0.2149
[3100]	valid_set's binary_logloss: 0.214866
[3150]	valid_set's binary_logloss: 0.21479
[3200]	valid_set's binary_logloss: 0.214716
[3250]	valid_set's binary_logloss: 0.214675
[3300]	valid_set's binary_logloss: 0.214681
[3350]	valid_set's binary_logloss: 0.214594
[3400]	valid_set's binary_logloss: 0.214527
[3450]	valid_set's binary_logloss: 0.214502
[3500]	valid_set's binary_logloss: 0.214488
[3550]	valid_set's binary_logloss: 0.214453
[3600]	valid_set's binary_logloss: 0.214404
[3650]	valid_set's binary_logloss: 0.214314
[3700]	valid_set's binary_logloss: 0.214235
[3750]	valid_set's binary_logloss: 0.214187
[3800]	valid_set's binary_logloss: 0.214147
[3850]	valid_set's binary_logloss: 0.214134
[3900]	valid_set's binary_logloss: 0.21411
[3950]	valid_set's binary_logloss: 0.21412
[4000]	valid_set's binary_logloss: 0.214063
[4050]	valid_set's binary_logloss: 0.214016
[4100]	valid_set's binary_logloss: 0.21403
[4150]	valid_set's binary_logloss: 0.213968
[4200]	valid_set's binary_logloss: 0.21398
[4250]	valid_set's binary_logloss: 0.213933
[4300]	valid_set's binary_logloss: 0.213935
[4350]	valid_set's binary_logloss: 0.213939
[4400]	valid_set's binary_logloss: 0.213915
[4450]	valid_set's binary_logloss: 0.213869
[4500]	valid_set's binary_logloss: 0.213829
[4550]	valid_set's binary_logloss: 0.213804
[4600]	valid_set's binary_logloss: 0.213726
[4650]	valid_set's binary_logloss: 0.213718
[4700]	valid_set's binary_logloss: 0.213721
[4750]	valid_set's binary_logloss: 0.21367
[4800]	valid_set's binary_logloss: 0.213626
[4850]	valid_set's binary_logloss: 0.21361
[4900]	valid_set's binary_logloss: 0.213579
[4950]	valid_set's binary_logloss: 0.213592
[5000]	valid_set's binary_logloss: 0.213568
[5050]	valid_set's binary_logloss: 0.213537
[5100]	valid_set's binary_logloss: 0.21352
[5150]	valid_set's binary_logloss: 0.213481
[5200]	valid_set's binary_logloss: 0.213499
[5250]	valid_set's binary_logloss: 0.213499
[5300]	valid_set's binary_logloss: 0.213448
[5350]	valid_set's binary_logloss: 0.213476
[5400]	valid_set's binary_logloss: 0.213449
[5450]	valid_set's binary_logloss: 0.213431
[5500]	valid_set's binary_logloss: 0.213423
[5550]	valid_set's binary_logloss: 0.213487
[5600]	valid_set's binary_logloss: 0.213457
[5650]	valid_set's binary_logloss: 0.213499
[5700]	valid_set's binary_logloss: 0.213494
[5750]	valid_set's binary_logloss: 0.213462
[5800]	valid_set's binary_logloss: 0.213462
[5850]	valid_set's binary_logloss: 0.213497
[5900]	valid_set's binary_logloss: 0.213457
[5950]	valid_set's binary_logloss: 0.213452
[6000]	valid_set's binary_logloss: 0.213461
[6050]	valid_set's binary_logloss: 0.213474
[6100]	valid_set's binary_logloss: 0.213445
[6150]	valid_set's binary_logloss: 0.21345
[6200]	valid_set's binary_logloss: 0.213418
[6250]	valid_set's binary_logloss: 0.213438
[6300]	valid_set's binary_logloss: 0.213456
[6350]	valid_set's binary_logloss: 0.213438
[6400]	valid_set's binary_logloss: 0.213466
[6450]	valid_set's binary_logloss: 0.21352
[6500]	valid_set's binary_logloss: 0.213539
[6550]	valid_set's binary_logloss: 0.213539
[6600]	valid_set's binary_logloss: 0.213555
[6650]	valid_set's binary_logloss: 0.213535
[6700]	valid_set's binary_logloss: 0.213524
[6750]	valid_set's binary_logloss: 0.213518
[6800]	valid_set's binary_logloss: 0.213515
[6850]	valid_set's binary_logloss: 0.21352
[6900]	valid_set's binary_logloss: 0.213521
[6950]	valid_set's binary_logloss: 0.213516
[7000]	valid_set's binary_logloss: 0.213536
[7050]	valid_set's binary_logloss: 0.213597
[7100]	valid_set's binary_logloss: 0.213604
[7150]	valid_set's binary_logloss: 0.213654
[7200]	valid_set's binary_logloss: 0.213697
[7250]	valid_set's binary_logloss: 0.213704
[7300]	valid_set's binary_logloss: 0.213737
[7350]	valid_set's binary_logloss: 0.213767
[7400]	valid_set's binary_logloss: 0.2138
[7450]	valid_set's binary_logloss: 0.213827
[7500]	valid_set's binary_logloss: 0.213838
[7550]	valid_set's binary_logloss: 0.213848
[7600]	valid_set's binary_logloss: 0.213811
[7650]	valid_set's binary_logloss: 0.21379
[7700]	valid_set's binary_logloss: 0.213798
[7750]	valid_set's binary_logloss: 0.213831
[7800]	valid_set's binary_logloss: 0.213834
[7850]	valid_set's binary_logloss: 0.213866
[7900]	valid_set's binary_logloss: 0.213862
[7950]	valid_set's binary_logloss: 0.21387
[8000]	valid_set's binary_logloss: 0.213919
[8050]	valid_set's binary_logloss: 0.213933

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283288
[100]	valid_set's binary_logloss: 0.258609
[150]	valid_set's binary_logloss: 0.248793
[200]	valid_set's binary_logloss: 0.243107
[250]	valid_set's binary_logloss: 0.23926
[300]	valid_set's binary_logloss: 0.236303
[350]	valid_set's binary_logloss: 0.233992
[400]	valid_set's binary_logloss: 0.232196
[450]	valid_set's binary_logloss: 0.230555
[500]	valid_set's binary_logloss: 0.229086
[550]	valid_set's binary_logloss: 0.227634
[600]	valid_set's binary_logloss: 0.226537
[650]	valid_set's binary_logloss: 0.225499
[700]	valid_set's binary_logloss: 0.224591
[750]	valid_set's binary_logloss: 0.223382
[800]	valid_set's binary_logloss: 0.222523
[850]	valid_set's binary_logloss: 0.221992
[900]	valid_set's binary_logloss: 0.221354
[950]	valid_set's binary_logloss: 0.220799
[1000]	valid_set's binary_logloss: 0.220261
[1050]	valid_set's binary_logloss: 0.219828
[1100]	valid_set's binary_logloss: 0.219373
[1150]	valid_set's binary_logloss: 0.218995
[1200]	valid_set's binary_logloss: 0.218605
[1250]	valid_set's binary_logloss: 0.218327
[1300]	valid_set's binary_logloss: 0.217983
[1350]	valid_set's binary_logloss: 0.217722
[1400]	valid_set's binary_logloss: 0.21724
[1450]	valid_set's binary_logloss: 0.216948
[1500]	valid_set's binary_logloss: 0.216702
[1550]	valid_set's binary_logloss: 0.216454
[1600]	valid_set's binary_logloss: 0.216093
[1650]	valid_set's binary_logloss: 0.215742
[1700]	valid_set's binary_logloss: 0.215524
[1750]	valid_set's binary_logloss: 0.215259
[1800]	valid_set's binary_logloss: 0.215101
[1850]	valid_set's binary_logloss: 0.21492
[1900]	valid_set's binary_logloss: 0.214748
[1950]	valid_set's binary_logloss: 0.21458
[2000]	valid_set's binary_logloss: 0.214427
[2050]	valid_set's binary_logloss: 0.214265
[2100]	valid_set's binary_logloss: 0.214106
[2150]	valid_set's binary_logloss: 0.213868
[2200]	valid_set's binary_logloss: 0.213637
[2250]	valid_set's binary_logloss: 0.213461
[2300]	valid_set's binary_logloss: 0.213263
[2350]	valid_set's binary_logloss: 0.213126
[2400]	valid_set's binary_logloss: 0.213045
[2450]	valid_set's binary_logloss: 0.212889
[2500]	valid_set's binary_logloss: 0.212755
[2550]	valid_set's binary_logloss: 0.212642
[2600]	valid_set's binary_logloss: 0.212518
[2650]	valid_set's binary_logloss: 0.212404
[2700]	valid_set's binary_logloss: 0.212316
[2750]	valid_set's binary_logloss: 0.212299
[2800]	valid_set's binary_logloss: 0.212242
[2850]	valid_set's binary_logloss: 0.212152
[2900]	valid_set's binary_logloss: 0.21207
[2950]	valid_set's binary_logloss: 0.211952
[3000]	valid_set's binary_logloss: 0.211847
[3050]	valid_set's binary_logloss: 0.211785
[3100]	valid_set's binary_logloss: 0.211697
[3150]	valid_set's binary_logloss: 0.211623
[3200]	valid_set's binary_logloss: 0.211526
[3250]	valid_set's binary_logloss: 0.21143
[3300]	valid_set's binary_logloss: 0.211402
[3350]	valid_set's binary_logloss: 0.211383
[3400]	valid_set's binary_logloss: 0.21128
[3450]	valid_set's binary_logloss: 0.211194
[3500]	valid_set's binary_logloss: 0.21115
[3550]	valid_set's binary_logloss: 0.211151
[3600]	valid_set's binary_logloss: 0.211121
[3650]	valid_set's binary_logloss: 0.211066
[3700]	valid_set's binary_logloss: 0.211016
[3750]	valid_set's binary_logloss: 0.211006
[3800]	valid_set's binary_logloss: 0.210981
[3850]	valid_set's binary_logloss: 0.210929
[3900]	valid_set's binary_logloss: 0.210874
[3950]	valid_set's binary_logloss: 0.210821
[4000]	valid_set's binary_logloss: 0.210765
[4050]	valid_set's binary_logloss: 0.210729
[4100]	valid_set's binary_logloss: 0.210705
[4150]	valid_set's binary_logloss: 0.210647
[4200]	valid_set's binary_logloss: 0.210611
[4250]	valid_set's binary_logloss: 0.210553
[4300]	valid_set's binary_logloss: 0.210539
[4350]	valid_set's binary_logloss: 0.210479
[4400]	valid_set's binary_logloss: 0.210385
[4450]	valid_set's binary_logloss: 0.210333
[4500]	valid_set's binary_logloss: 0.21025
[4550]	valid_set's binary_logloss: 0.210224
[4600]	valid_set's binary_logloss: 0.210252
[4650]	valid_set's binary_logloss: 0.210224
[4700]	valid_set's binary_logloss: 0.210199
[4750]	valid_set's binary_logloss: 0.210189
[4800]	valid_set's binary_logloss: 0.210191
[4850]	valid_set's binary_logloss: 0.210192
[4900]	valid_set's binary_logloss: 0.21019
[4950]	valid_set's binary_logloss: 0.210138
[5000]	valid_set's binary_logloss: 0.210129
[5050]	valid_set's binary_logloss: 0.210123
[5100]	valid_set's binary_logloss: 0.210115
[5150]	valid_set's binary_logloss: 0.210087
[5200]	valid_set's binary_logloss: 0.210067
[5250]	valid_set's binary_logloss: 0.210089
[5300]	valid_set's binary_logloss: 0.210058
[5350]	valid_set's binary_logloss: 0.210055
[5400]	valid_set's binary_logloss: 0.210026
[5450]	valid_set's binary_logloss: 0.209974
[5500]	valid_set's binary_logloss: 0.20998
[5550]	valid_set's binary_logloss: 0.209991
[5600]	valid_set's binary_logloss: 0.20998
[5650]	valid_set's binary_logloss: 0.209995
[5700]	valid_set's binary_logloss: 0.209991
[5750]	valid_set's binary_logloss: 0.210031
[5800]	valid_set's binary_logloss: 0.210034
[5850]	valid_set's binary_logloss: 0.210005
[5900]	valid_set's binary_logloss: 0.209999
[5950]	valid_set's binary_logloss: 0.210012
[6000]	valid_set's binary_logloss: 0.210018
[6050]	valid_set's binary_logloss: 0.210067
[6100]	valid_set's binary_logloss: 0.210082
[6150]	valid_set's binary_logloss: 0.210109
[6200]	valid_set's binary_logloss: 0.210103
[6250]	valid_set's binary_logloss: 0.210107
[6300]	valid_set's binary_logloss: 0.210129
[6350]	valid_set's binary_logloss: 0.210124
[6400]	valid_set's binary_logloss: 0.210107
[6450]	valid_set's binary_logloss: 0.210074
[6500]	valid_set's binary_logloss: 0.210089
[6550]	valid_set's binary_logloss: 0.210079
[6600]	valid_set's binary_logloss: 0.210087
[6650]	valid_set's binary_logloss: 0.210081
[6700]	valid_set's binary_logloss: 0.210091
[6750]	valid_set's binary_logloss: 0.21012
[6800]	valid_set's binary_logloss: 0.210143
[6850]	valid_set's binary_logloss: 0.210154
[6900]	valid_set's binary_logloss: 0.21017
[6950]	valid_set's binary_logloss: 0.210194
[7000]	valid_set's binary_logloss: 0.21018
[7050]	valid_set's binary_logloss: 0.21016
[7100]	valid_set's binary_logloss: 0.210215

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.284962
[100]	valid_set's binary_logloss: 0.259881
[150]	valid_set's binary_logloss: 0.249686
[200]	valid_set's binary_logloss: 0.244451
[250]	valid_set's binary_logloss: 0.240577
[300]	valid_set's binary_logloss: 0.237664
[350]	valid_set's binary_logloss: 0.235315
[400]	valid_set's binary_logloss: 0.23291
[450]	valid_set's binary_logloss: 0.23098
[500]	valid_set's binary_logloss: 0.229433
[550]	valid_set's binary_logloss: 0.228086
[600]	valid_set's binary_logloss: 0.226809
[650]	valid_set's binary_logloss: 0.225706
[700]	valid_set's binary_logloss: 0.224749
[750]	valid_set's binary_logloss: 0.224138
[800]	valid_set's binary_logloss: 0.223042
[850]	valid_set's binary_logloss: 0.222306
[900]	valid_set's binary_logloss: 0.221513
[950]	valid_set's binary_logloss: 0.22091
[1000]	valid_set's binary_logloss: 0.220455
[1050]	valid_set's binary_logloss: 0.219749
[1100]	valid_set's binary_logloss: 0.219249
[1150]	valid_set's binary_logloss: 0.21888
[1200]	valid_set's binary_logloss: 0.218485
[1250]	valid_set's binary_logloss: 0.218146
[1300]	valid_set's binary_logloss: 0.217745
[1350]	valid_set's binary_logloss: 0.217292
[1400]	valid_set's binary_logloss: 0.216855
[1450]	valid_set's binary_logloss: 0.21639
[1500]	valid_set's binary_logloss: 0.21605
[1550]	valid_set's binary_logloss: 0.215741
[1600]	valid_set's binary_logloss: 0.21552
[1650]	valid_set's binary_logloss: 0.215288
[1700]	valid_set's binary_logloss: 0.214984
[1750]	valid_set's binary_logloss: 0.2147
[1800]	valid_set's binary_logloss: 0.214564
[1850]	valid_set's binary_logloss: 0.21435
[1900]	valid_set's binary_logloss: 0.214088
[1950]	valid_set's binary_logloss: 0.213784
[2000]	valid_set's binary_logloss: 0.213546
[2050]	valid_set's binary_logloss: 0.213366
[2100]	valid_set's binary_logloss: 0.213218
[2150]	valid_set's binary_logloss: 0.21308
[2200]	valid_set's binary_logloss: 0.212974
[2250]	valid_set's binary_logloss: 0.212818
[2300]	valid_set's binary_logloss: 0.212631
[2350]	valid_set's binary_logloss: 0.212502
[2400]	valid_set's binary_logloss: 0.21234
[2450]	valid_set's binary_logloss: 0.212116
[2500]	valid_set's binary_logloss: 0.211989
[2550]	valid_set's binary_logloss: 0.211866
[2600]	valid_set's binary_logloss: 0.211718
[2650]	valid_set's binary_logloss: 0.211606
[2700]	valid_set's binary_logloss: 0.211461
[2750]	valid_set's binary_logloss: 0.211394
[2800]	valid_set's binary_logloss: 0.211302
[2850]	valid_set's binary_logloss: 0.211248
[2900]	valid_set's binary_logloss: 0.211168
[2950]	valid_set's binary_logloss: 0.211063
[3000]	valid_set's binary_logloss: 0.210985
[3050]	valid_set's binary_logloss: 0.210914
[3100]	valid_set's binary_logloss: 0.210793
[3150]	valid_set's binary_logloss: 0.210621
[3200]	valid_set's binary_logloss: 0.210531
[3250]	valid_set's binary_logloss: 0.210543
[3300]	valid_set's binary_logloss: 0.210526
[3350]	valid_set's binary_logloss: 0.210436
[3400]	valid_set's binary_logloss: 0.21035
[3450]	valid_set's binary_logloss: 0.210257
[3500]	valid_set's binary_logloss: 0.210183
[3550]	valid_set's binary_logloss: 0.210111
[3600]	valid_set's binary_logloss: 0.210028
[3650]	valid_set's binary_logloss: 0.209975
[3700]	valid_set's binary_logloss: 0.20992
[3750]	valid_set's binary_logloss: 0.209885
[3800]	valid_set's binary_logloss: 0.209829
[3850]	valid_set's binary_logloss: 0.209745
[3900]	valid_set's binary_logloss: 0.209655
[3950]	valid_set's binary_logloss: 0.209548
[4000]	valid_set's binary_logloss: 0.209496
[4050]	valid_set's binary_logloss: 0.209446
[4100]	valid_set's binary_logloss: 0.209373
[4150]	valid_set's binary_logloss: 0.209276
[4200]	valid_set's binary_logloss: 0.20921
[4250]	valid_set's binary_logloss: 0.209128
[4300]	valid_set's binary_logloss: 0.209061
[4350]	valid_set's binary_logloss: 0.20899
[4400]	valid_set's binary_logloss: 0.208957
[4450]	valid_set's binary_logloss: 0.208979
[4500]	valid_set's binary_logloss: 0.208956
[4550]	valid_set's binary_logloss: 0.20891
[4600]	valid_set's binary_logloss: 0.208888
[4650]	valid_set's binary_logloss: 0.208884
[4700]	valid_set's binary_logloss: 0.20886
[4750]	valid_set's binary_logloss: 0.208836
[4800]	valid_set's binary_logloss: 0.208783
[4850]	valid_set's binary_logloss: 0.208832
[4900]	valid_set's binary_logloss: 0.208798
[4950]	valid_set's binary_logloss: 0.208772
[5000]	valid_set's binary_logloss: 0.208759
[5050]	valid_set's binary_logloss: 0.208706
[5100]	valid_set's binary_logloss: 0.208677
[5150]	valid_set's binary_logloss: 0.208658
[5200]	valid_set's binary_logloss: 0.208636
[5250]	valid_set's binary_logloss: 0.208647
[5300]	valid_set's binary_logloss: 0.208665
[5350]	valid_set's binary_logloss: 0.208632
[5400]	valid_set's binary_logloss: 0.208605
[5450]	valid_set's binary_logloss: 0.20862
[5500]	valid_set's binary_logloss: 0.208624
[5550]	valid_set's binary_logloss: 0.208602
[5600]	valid_set's binary_logloss: 0.208617
[5650]	valid_set's binary_logloss: 0.208621
[5700]	valid_set's binary_logloss: 0.208638
[5750]	valid_set's binary_logloss: 0.208621
[5800]	valid_set's binary_logloss: 0.208638
[5850]	valid_set's binary_logloss: 0.208641
[5900]	valid_set's binary_logloss: 0.208663
[5950]	valid_set's binary_logloss: 0.208667
[6000]	valid_set's binary_logloss: 0.208607
[6050]	valid_set's binary_logloss: 0.208622
[6100]	valid_set's binary_logloss: 0.208623
[6150]	valid_set's binary_logloss: 0.208636
[6200]	valid_set's binary_logloss: 0.208643
[6250]	valid_set's binary_logloss: 0.208662
[6300]	valid_set's binary_logloss: 0.208634
[6350]	valid_set's binary_logloss: 0.208567
[6400]	valid_set's binary_logloss: 0.208572
[6450]	valid_set's binary_logloss: 0.208582
[6500]	valid_set's binary_logloss: 0.208597
[6550]	valid_set's binary_logloss: 0.208558
[6600]	valid_set's binary_logloss: 0.208549
[6650]	valid_set's binary_logloss: 0.208546
[6700]	valid_set's binary_logloss: 0.208544
[6750]	valid_set's binary_logloss: 0.208556
[6800]	valid_set's binary_logloss: 0.20858
[6850]	valid_set's binary_logloss: 0.208585
[6900]	valid_set's binary_logloss: 0.208647
[6950]	valid_set's binary_logloss: 0.208643
[7000]	valid_set's binary_logloss: 0.208633
[7050]	valid_set's binary_logloss: 0.20866
[7100]	valid_set's binary_logloss: 0.208681
[7150]	valid_set's binary_logloss: 0.208693
[7200]	valid_set's binary_logloss: 0.208676
[7250]	valid_set's binary_logloss: 0.208696
[7300]	valid_set's binary_logloss: 0.208721
[7350]	valid_set's binary_logloss: 0.208724
[7400]	valid_set's binary_logloss: 0.208761
[7450]	valid_set's binary_logloss: 0.20879
[7500]	valid_set's binary_logloss: 0.208746
[7550]	valid_set's binary_logloss: 0.208715
[7600]	valid_set's binary_logloss: 0.20871
[7650]	valid_set's binary_logloss: 0.208715
[7700]	valid_set's binary_logloss: 0.208752
[7750]	valid_set's binary_logloss: 0.208769
[7800]	valid_set's binary_logloss: 0.208829
[7850]	valid_set's binary_logloss: 0.208847
[7900]	valid_set's binary_logloss: 0.20887
[7950]	valid_set's binary_logloss: 0.20892
[8000]	valid_set's binary_logloss: 0.208941
[8050]	valid_set's binary_logloss: 0.208954
[8100]	valid_set's binary_logloss: 0.208968
[8150]	valid_set's binary_logloss: 0.209005
[8200]	valid_set's binary_logloss: 0.208987
[8250]	valid_set's binary_logloss: 0.208963
[8300]	valid_set's binary_logloss: 0.208972
[8350]	valid_set's binary_logloss: 0.208989
[8400]	valid_set's binary_logloss: 0.209029
[8450]	valid_set's binary_logloss: 0.209044
[8500]	valid_set's binary_logloss: 0.209084
[8550]	valid_set's binary_logloss: 0.209124

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.283799
[100]	valid_set's binary_logloss: 0.25886
[150]	valid_set's binary_logloss: 0.249023
[200]	valid_set's binary_logloss: 0.243524
[250]	valid_set's binary_logloss: 0.239946
[300]	valid_set's binary_logloss: 0.237002
[350]	valid_set's binary_logloss: 0.235138
[400]	valid_set's binary_logloss: 0.233309
[450]	valid_set's binary_logloss: 0.231588
[500]	valid_set's binary_logloss: 0.230182
[550]	valid_set's binary_logloss: 0.228754
[600]	valid_set's binary_logloss: 0.227548
[650]	valid_set's binary_logloss: 0.226355
[700]	valid_set's binary_logloss: 0.225397
[750]	valid_set's binary_logloss: 0.224594
[800]	valid_set's binary_logloss: 0.223639
[850]	valid_set's binary_logloss: 0.222906
[900]	valid_set's binary_logloss: 0.222148
[950]	valid_set's binary_logloss: 0.221536
[1000]	valid_set's binary_logloss: 0.220836
[1050]	valid_set's binary_logloss: 0.220411
[1100]	valid_set's binary_logloss: 0.219819
[1150]	valid_set's binary_logloss: 0.219348
[1200]	valid_set's binary_logloss: 0.218944
[1250]	valid_set's binary_logloss: 0.218495
[1300]	valid_set's binary_logloss: 0.218136
[1350]	valid_set's binary_logloss: 0.217738
[1400]	valid_set's binary_logloss: 0.217368
[1450]	valid_set's binary_logloss: 0.217097
[1500]	valid_set's binary_logloss: 0.216778
[1550]	valid_set's binary_logloss: 0.216441
[1600]	valid_set's binary_logloss: 0.21618
[1650]	valid_set's binary_logloss: 0.21588
[1700]	valid_set's binary_logloss: 0.215567
[1750]	valid_set's binary_logloss: 0.215339
[1800]	valid_set's binary_logloss: 0.215092
[1850]	valid_set's binary_logloss: 0.214847
[1900]	valid_set's binary_logloss: 0.214653
[1950]	valid_set's binary_logloss: 0.214381
[2000]	valid_set's binary_logloss: 0.214121
[2050]	valid_set's binary_logloss: 0.21395
[2100]	valid_set's binary_logloss: 0.213738
[2150]	valid_set's binary_logloss: 0.213465
[2200]	valid_set's binary_logloss: 0.213229
[2250]	valid_set's binary_logloss: 0.213007
[2300]	valid_set's binary_logloss: 0.212866
[2350]	valid_set's binary_logloss: 0.212767
[2400]	valid_set's binary_logloss: 0.212715
[2450]	valid_set's binary_logloss: 0.212601
[2500]	valid_set's binary_logloss: 0.212497
[2550]	valid_set's binary_logloss: 0.212409
[2600]	valid_set's binary_logloss: 0.212347
[2650]	valid_set's binary_logloss: 0.212192
[2700]	valid_set's binary_logloss: 0.212079
[2750]	valid_set's binary_logloss: 0.211959
[2800]	valid_set's binary_logloss: 0.211866
[2850]	valid_set's binary_logloss: 0.211814
[2900]	valid_set's binary_logloss: 0.211703
[2950]	valid_set's binary_logloss: 0.211607
[3000]	valid_set's binary_logloss: 0.211472
[3050]	valid_set's binary_logloss: 0.211416
[3100]	valid_set's binary_logloss: 0.211377
[3150]	valid_set's binary_logloss: 0.21132
[3200]	valid_set's binary_logloss: 0.211244
[3250]	valid_set's binary_logloss: 0.211133
[3300]	valid_set's binary_logloss: 0.211098
[3350]	valid_set's binary_logloss: 0.211016
[3400]	valid_set's binary_logloss: 0.210927
[3450]	valid_set's binary_logloss: 0.210899
[3500]	valid_set's binary_logloss: 0.210848
[3550]	valid_set's binary_logloss: 0.210816
[3600]	valid_set's binary_logloss: 0.210666
[3650]	valid_set's binary_logloss: 0.21061
[3700]	valid_set's binary_logloss: 0.210546
[3750]	valid_set's binary_logloss: 0.210457
[3800]	valid_set's binary_logloss: 0.21043
[3850]	valid_set's binary_logloss: 0.210331
[3900]	valid_set's binary_logloss: 0.210333
[3950]	valid_set's binary_logloss: 0.210287
[4000]	valid_set's binary_logloss: 0.210203
[4050]	valid_set's binary_logloss: 0.210156
[4100]	valid_set's binary_logloss: 0.210062
[4150]	valid_set's binary_logloss: 0.209974
[4200]	valid_set's binary_logloss: 0.20989
[4250]	valid_set's binary_logloss: 0.20986
[4300]	valid_set's binary_logloss: 0.20981
[4350]	valid_set's binary_logloss: 0.209796
[4400]	valid_set's binary_logloss: 0.209776
[4450]	valid_set's binary_logloss: 0.209768
[4500]	valid_set's binary_logloss: 0.209736
[4550]	valid_set's binary_logloss: 0.209713
[4600]	valid_set's binary_logloss: 0.20967
[4650]	valid_set's binary_logloss: 0.209655
[4700]	valid_set's binary_logloss: 0.209581
[4750]	valid_set's binary_logloss: 0.209614
[4800]	valid_set's binary_logloss: 0.209612
[4850]	valid_set's binary_logloss: 0.209593
[4900]	valid_set's binary_logloss: 0.209522
[4950]	valid_set's binary_logloss: 0.209478
[5000]	valid_set's binary_logloss: 0.209419
[5050]	valid_set's binary_logloss: 0.209407
[5100]	valid_set's binary_logloss: 0.20939
[5150]	valid_set's binary_logloss: 0.209355
[5200]	valid_set's binary_logloss: 0.209296
[5250]	valid_set's binary_logloss: 0.20926
[5300]	valid_set's binary_logloss: 0.209241
[5350]	valid_set's binary_logloss: 0.209241
[5400]	valid_set's binary_logloss: 0.209265
[5450]	valid_set's binary_logloss: 0.209274
[5500]	valid_set's binary_logloss: 0.209246
[5550]	valid_set's binary_logloss: 0.209255
[5600]	valid_set's binary_logloss: 0.209222
[5650]	valid_set's binary_logloss: 0.209174
[5700]	valid_set's binary_logloss: 0.209094
[5750]	valid_set's binary_logloss: 0.209075
[5800]	valid_set's binary_logloss: 0.209077
[5850]	valid_set's binary_logloss: 0.20905
[5900]	valid_set's binary_logloss: 0.209061
[5950]	valid_set's binary_logloss: 0.209074
[6000]	valid_set's binary_logloss: 0.209043
[6050]	valid_set's binary_logloss: 0.209026
[6100]	valid_set's binary_logloss: 0.209017
[6150]	valid_set's binary_logloss: 0.209012
[6200]	valid_set's binary_logloss: 0.209029
[6250]	valid_set's binary_logloss: 0.209008
[6300]	valid_set's binary_logloss: 0.209049
[6350]	valid_set's binary_logloss: 0.209034
[6400]	valid_set's binary_logloss: 0.209051
[6450]	valid_set's binary_logloss: 0.209043
[6500]	valid_set's binary_logloss: 0.209015
[6550]	valid_set's binary_logloss: 0.209064
[6600]	valid_set's binary_logloss: 0.209009
[6650]	valid_set's binary_logloss: 0.208996
[6700]	valid_set's binary_logloss: 0.208975
[6750]	valid_set's binary_logloss: 0.208959
[6800]	valid_set's binary_logloss: 0.208991
[6850]	valid_set's binary_logloss: 0.208986
[6900]	valid_set's binary_logloss: 0.20898
[6950]	valid_set's binary_logloss: 0.208963
[7000]	valid_set's binary_logloss: 0.208979
[7050]	valid_set's binary_logloss: 0.208964
[7100]	valid_set's binary_logloss: 0.208974
[7150]	valid_set's binary_logloss: 0.208987
[7200]	valid_set's binary_logloss: 0.208978
[7250]	valid_set's binary_logloss: 0.209001
[7300]	valid_set's binary_logloss: 0.208995
[7350]	valid_set's binary_logloss: 0.209017
[7400]	valid_set's binary_logloss: 0.209059
[7450]	valid_set's binary_logloss: 0.209065
[7500]	valid_set's binary_logloss: 0.209059
[7550]	valid_set's binary_logloss: 0.209053
[7600]	valid_set's binary_logloss: 0.209089
[7650]	valid_set's binary_logloss: 0.209087
[7700]	valid_set's binary_logloss: 0.209087
[7750]	valid_set's binary_logloss: 0.209113
[7800]	valid_set's binary_logloss: 0.20914
[7850]	valid_set's binary_logloss: 0.209138
[7900]	valid_set's binary_logloss: 0.209157
[7950]	valid_set's binary_logloss: 0.209185
[8000]	valid_set's binary_logloss: 0.209195
[8050]	valid_set's binary_logloss: 0.209249
[8100]	valid_set's binary_logloss: 0.209265
[8150]	valid_set's binary_logloss: 0.209279
[8200]	valid_set's binary_logloss: 0.209303
[8250]	valid_set's binary_logloss: 0.20932
[8300]	valid_set's binary_logloss: 0.209368
[8350]	valid_set's binary_logloss: 0.209373
[8400]	valid_set's binary_logloss: 0.209396
[8450]	valid_set's binary_logloss: 0.209425
[8500]	valid_set's binary_logloss: 0.209428
[8550]	valid_set's binary_logloss: 0.209426
[8600]	valid_set's binary_logloss: 0.209476
[8650]	valid_set's binary_logloss: 0.209499
[8700]	valid_set's binary_logloss: 0.20954
[8750]	valid_set's binary_logloss: 0.209535

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.282103
[100]	valid_set's binary_logloss: 0.258438
[150]	valid_set's binary_logloss: 0.248706
[200]	valid_set's binary_logloss: 0.243355
[250]	valid_set's binary_logloss: 0.239433
[300]	valid_set's binary_logloss: 0.237043
[350]	valid_set's binary_logloss: 0.234581
[400]	valid_set's binary_logloss: 0.232725
[450]	valid_set's binary_logloss: 0.231116
[500]	valid_set's binary_logloss: 0.229644
[550]	valid_set's binary_logloss: 0.228298
[600]	valid_set's binary_logloss: 0.227043
[650]	valid_set's binary_logloss: 0.225921
[700]	valid_set's binary_logloss: 0.225107
[750]	valid_set's binary_logloss: 0.224363
[800]	valid_set's binary_logloss: 0.22363
[850]	valid_set's binary_logloss: 0.222958
[900]	valid_set's binary_logloss: 0.222332
[950]	valid_set's binary_logloss: 0.221729
[1000]	valid_set's binary_logloss: 0.221226
[1050]	valid_set's binary_logloss: 0.220702
[1100]	valid_set's binary_logloss: 0.220281
[1150]	valid_set's binary_logloss: 0.219852
[1200]	valid_set's binary_logloss: 0.219403
[1250]	valid_set's binary_logloss: 0.219017
[1300]	valid_set's binary_logloss: 0.218617
[1350]	valid_set's binary_logloss: 0.218224
[1400]	valid_set's binary_logloss: 0.217949
[1450]	valid_set's binary_logloss: 0.217676
[1500]	valid_set's binary_logloss: 0.217331
[1550]	valid_set's binary_logloss: 0.217111
[1600]	valid_set's binary_logloss: 0.216904
[1650]	valid_set's binary_logloss: 0.216609
[1700]	valid_set's binary_logloss: 0.216349
[1750]	valid_set's binary_logloss: 0.216105
[1800]	valid_set's binary_logloss: 0.215828
[1850]	valid_set's binary_logloss: 0.215627
[1900]	valid_set's binary_logloss: 0.215453
[1950]	valid_set's binary_logloss: 0.215215
[2000]	valid_set's binary_logloss: 0.215033
[2050]	valid_set's binary_logloss: 0.214852
[2100]	valid_set's binary_logloss: 0.214645
[2150]	valid_set's binary_logloss: 0.214489
[2200]	valid_set's binary_logloss: 0.214315
[2250]	valid_set's binary_logloss: 0.214187
[2300]	valid_set's binary_logloss: 0.214073
[2350]	valid_set's binary_logloss: 0.213906
[2400]	valid_set's binary_logloss: 0.213614
[2450]	valid_set's binary_logloss: 0.213472
[2500]	valid_set's binary_logloss: 0.213348
[2550]	valid_set's binary_logloss: 0.213196
[2600]	valid_set's binary_logloss: 0.213096
[2650]	valid_set's binary_logloss: 0.21292
[2700]	valid_set's binary_logloss: 0.212752
[2750]	valid_set's binary_logloss: 0.212676
[2800]	valid_set's binary_logloss: 0.212601
[2850]	valid_set's binary_logloss: 0.212496
[2900]	valid_set's binary_logloss: 0.212424
[2950]	valid_set's binary_logloss: 0.212339
[3000]	valid_set's binary_logloss: 0.212165
[3050]	valid_set's binary_logloss: 0.212091
[3100]	valid_set's binary_logloss: 0.211982
[3150]	valid_set's binary_logloss: 0.211881
[3200]	valid_set's binary_logloss: 0.211777
[3250]	valid_set's binary_logloss: 0.211711
[3300]	valid_set's binary_logloss: 0.211717
[3350]	valid_set's binary_logloss: 0.211659
[3400]	valid_set's binary_logloss: 0.211612
[3450]	valid_set's binary_logloss: 0.211495
[3500]	valid_set's binary_logloss: 0.211424
[3550]	valid_set's binary_logloss: 0.211372
[3600]	valid_set's binary_logloss: 0.211312
[3650]	valid_set's binary_logloss: 0.211303
[3700]	valid_set's binary_logloss: 0.211262
[3750]	valid_set's binary_logloss: 0.211195
[3800]	valid_set's binary_logloss: 0.211102
[3850]	valid_set's binary_logloss: 0.21104
[3900]	valid_set's binary_logloss: 0.211024
[3950]	valid_set's binary_logloss: 0.211021
[4000]	valid_set's binary_logloss: 0.211007
[4050]	valid_set's binary_logloss: 0.210969
[4100]	valid_set's binary_logloss: 0.210916
[4150]	valid_set's binary_logloss: 0.21093
[4200]	valid_set's binary_logloss: 0.210907
[4250]	valid_set's binary_logloss: 0.210911
[4300]	valid_set's binary_logloss: 0.210906
[4350]	valid_set's binary_logloss: 0.21094
[4400]	valid_set's binary_logloss: 0.21098
[4450]	valid_set's binary_logloss: 0.210943
[4500]	valid_set's binary_logloss: 0.210951
[4550]	valid_set's binary_logloss: 0.210965
[4600]	valid_set's binary_logloss: 0.210941
[4650]	valid_set's binary_logloss: 0.210901
[4700]	valid_set's binary_logloss: 0.210896
[4750]	valid_set's binary_logloss: 0.210859
[4800]	valid_set's binary_logloss: 0.210847
[4850]	valid_set's binary_logloss: 0.21083
[4900]	valid_set's binary_logloss: 0.210845
[4950]	valid_set's binary_logloss: 0.210802
[5000]	valid_set's binary_logloss: 0.210786
[5050]	valid_set's binary_logloss: 0.210732
[5100]	valid_set's binary_logloss: 0.210728
[5150]	valid_set's binary_logloss: 0.210684
[5200]	valid_set's binary_logloss: 0.210636
[5250]	valid_set's binary_logloss: 0.210606
[5300]	valid_set's binary_logloss: 0.210595
[5350]	valid_set's binary_logloss: 0.210601
[5400]	valid_set's binary_logloss: 0.210594
[5450]	valid_set's binary_logloss: 0.210601
[5500]	valid_set's binary_logloss: 0.210576
[5550]	valid_set's binary_logloss: 0.210564
[5600]	valid_set's binary_logloss: 0.210565
[5650]	valid_set's binary_logloss: 0.210561
[5700]	valid_set's binary_logloss: 0.210543
[5750]	valid_set's binary_logloss: 0.210522
[5800]	valid_set's binary_logloss: 0.2105
[5850]	valid_set's binary_logloss: 0.210478
[5900]	valid_set's binary_logloss: 0.210452
[5950]	valid_set's binary_logloss: 0.21043
[6000]	valid_set's binary_logloss: 0.210402
[6050]	valid_set's binary_logloss: 0.210412
[6100]	valid_set's binary_logloss: 0.210409
[6150]	valid_set's binary_logloss: 0.210355
[6200]	valid_set's binary_logloss: 0.210398
[6250]	valid_set's binary_logloss: 0.210411
[6300]	valid_set's binary_logloss: 0.210492
[6350]	valid_set's binary_logloss: 0.210485
[6400]	valid_set's binary_logloss: 0.210482
[6450]	valid_set's binary_logloss: 0.2105
[6500]	valid_set's binary_logloss: 0.210522
[6550]	valid_set's binary_logloss: 0.210538
[6600]	valid_set's binary_logloss: 0.210581
[6650]	valid_set's binary_logloss: 0.210607
[6700]	valid_set's binary_logloss: 0.210581
[6750]	valid_set's binary_logloss: 0.210587
[6800]	valid_set's binary_logloss: 0.21059
[6850]	valid_set's binary_logloss: 0.210594
[6900]	valid_set's binary_logloss: 0.210581
[6950]	valid_set's binary_logloss: 0.210589
[7000]	valid_set's binary_logloss: 0.210607
[7050]	valid_set's binary_logloss: 0.21059
[7100]	valid_set's binary_logloss: 0.210614
[7150]	valid_set's binary_logloss: 0.21064
[7200]	valid_set's binary_logloss: 0.21066
[7250]	valid_set's binary_logloss: 0.210673
[7300]	valid_set's binary_logloss: 0.210649
[7350]	valid_set's binary_logloss: 0.210644
[7400]	valid_set's binary_logloss: 0.210646
[7450]	valid_set's binary_logloss: 0.210636
[7500]	valid_set's binary_logloss: 0.210624
[7550]	valid_set's binary_logloss: 0.210627
[7600]	valid_set's binary_logloss: 0.210646
[7650]	valid_set's binary_logloss: 0.21067
[7700]	valid_set's binary_logloss: 0.210648
[7750]	valid_set's binary_logloss: 0.210668
[7800]	valid_set's binary_logloss: 0.210671
[7850]	valid_set's binary_logloss: 0.210654
[7900]	valid_set's binary_logloss: 0.210702
[7950]	valid_set's binary_logloss: 0.210727
[8000]	valid_set's binary_logloss: 0.210762

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.281462
[100]	valid_set's binary_logloss: 0.256382
[150]	valid_set's binary_logloss: 0.246599
[200]	valid_set's binary_logloss: 0.240962
[250]	valid_set's binary_logloss: 0.23775
[300]	valid_set's binary_logloss: 0.23518
[350]	valid_set's binary_logloss: 0.232786
[400]	valid_set's binary_logloss: 0.231108
[450]	valid_set's binary_logloss: 0.229272
[500]	valid_set's binary_logloss: 0.22768
[550]	valid_set's binary_logloss: 0.226481
[600]	valid_set's binary_logloss: 0.225584
[650]	valid_set's binary_logloss: 0.224517
[700]	valid_set's binary_logloss: 0.22363
[750]	valid_set's binary_logloss: 0.222554
[800]	valid_set's binary_logloss: 0.221731
[850]	valid_set's binary_logloss: 0.221096
[900]	valid_set's binary_logloss: 0.220161
[950]	valid_set's binary_logloss: 0.219549
[1000]	valid_set's binary_logloss: 0.219005
[1050]	valid_set's binary_logloss: 0.218323
[1100]	valid_set's binary_logloss: 0.217886
[1150]	valid_set's binary_logloss: 0.217491
[1200]	valid_set's binary_logloss: 0.216991
[1250]	valid_set's binary_logloss: 0.216513
[1300]	valid_set's binary_logloss: 0.216108
[1350]	valid_set's binary_logloss: 0.215735
[1400]	valid_set's binary_logloss: 0.21538
[1450]	valid_set's binary_logloss: 0.215061
[1500]	valid_set's binary_logloss: 0.214773
[1550]	valid_set's binary_logloss: 0.214398
[1600]	valid_set's binary_logloss: 0.214132
[1650]	valid_set's binary_logloss: 0.213857
[1700]	valid_set's binary_logloss: 0.213586
[1750]	valid_set's binary_logloss: 0.213338
[1800]	valid_set's binary_logloss: 0.21311
[1850]	valid_set's binary_logloss: 0.212897
[1900]	valid_set's binary_logloss: 0.212626
[1950]	valid_set's binary_logloss: 0.212345
[2000]	valid_set's binary_logloss: 0.21216
[2050]	valid_set's binary_logloss: 0.211952
[2100]	valid_set's binary_logloss: 0.211794
[2150]	valid_set's binary_logloss: 0.211602
[2200]	valid_set's binary_logloss: 0.211449
[2250]	valid_set's binary_logloss: 0.211265
[2300]	valid_set's binary_logloss: 0.211068
[2350]	valid_set's binary_logloss: 0.210893
[2400]	valid_set's binary_logloss: 0.210761
[2450]	valid_set's binary_logloss: 0.210592
[2500]	valid_set's binary_logloss: 0.210508
[2550]	valid_set's binary_logloss: 0.2104
[2600]	valid_set's binary_logloss: 0.210309
[2650]	valid_set's binary_logloss: 0.210197
[2700]	valid_set's binary_logloss: 0.210009
[2750]	valid_set's binary_logloss: 0.209861
[2800]	valid_set's binary_logloss: 0.209755
[2850]	valid_set's binary_logloss: 0.20965
[2900]	valid_set's binary_logloss: 0.209564
[2950]	valid_set's binary_logloss: 0.209501
[3000]	valid_set's binary_logloss: 0.209445
[3050]	valid_set's binary_logloss: 0.209308
[3100]	valid_set's binary_logloss: 0.209234
[3150]	valid_set's binary_logloss: 0.209149
[3200]	valid_set's binary_logloss: 0.209107
[3250]	valid_set's binary_logloss: 0.20902
[3300]	valid_set's binary_logloss: 0.208963
[3350]	valid_set's binary_logloss: 0.208886
[3400]	valid_set's binary_logloss: 0.208833
[3450]	valid_set's binary_logloss: 0.208715
[3500]	valid_set's binary_logloss: 0.208717
[3550]	valid_set's binary_logloss: 0.208623
[3600]	valid_set's binary_logloss: 0.208542
[3650]	valid_set's binary_logloss: 0.208509
[3700]	valid_set's binary_logloss: 0.20845
[3750]	valid_set's binary_logloss: 0.208372
[3800]	valid_set's binary_logloss: 0.208296
[3850]	valid_set's binary_logloss: 0.208271
[3900]	valid_set's binary_logloss: 0.208201
[3950]	valid_set's binary_logloss: 0.20818
[4000]	valid_set's binary_logloss: 0.208141
[4050]	valid_set's binary_logloss: 0.208104
[4100]	valid_set's binary_logloss: 0.208082
[4150]	valid_set's binary_logloss: 0.208056
[4200]	valid_set's binary_logloss: 0.208029
[4250]	valid_set's binary_logloss: 0.208029
[4300]	valid_set's binary_logloss: 0.207976
[4350]	valid_set's binary_logloss: 0.207976
[4400]	valid_set's binary_logloss: 0.207917
[4450]	valid_set's binary_logloss: 0.20787
[4500]	valid_set's binary_logloss: 0.207817
[4550]	valid_set's binary_logloss: 0.207787
[4600]	valid_set's binary_logloss: 0.207788
[4650]	valid_set's binary_logloss: 0.207763
[4700]	valid_set's binary_logloss: 0.207708
[4750]	valid_set's binary_logloss: 0.207677
[4800]	valid_set's binary_logloss: 0.207631
[4850]	valid_set's binary_logloss: 0.207639
[4900]	valid_set's binary_logloss: 0.207644
[4950]	valid_set's binary_logloss: 0.207569
[5000]	valid_set's binary_logloss: 0.207562
[5050]	valid_set's binary_logloss: 0.207607
[5100]	valid_set's binary_logloss: 0.207624
[5150]	valid_set's binary_logloss: 0.207625
[5200]	valid_set's binary_logloss: 0.207646
[5250]	valid_set's binary_logloss: 0.207594
[5300]	valid_set's binary_logloss: 0.207617
[5350]	valid_set's binary_logloss: 0.207572
[5400]	valid_set's binary_logloss: 0.207578
[5450]	valid_set's binary_logloss: 0.207543
[5500]	valid_set's binary_logloss: 0.207516
[5550]	valid_set's binary_logloss: 0.207456
[5600]	valid_set's binary_logloss: 0.207469
[5650]	valid_set's binary_logloss: 0.207509
[5700]	valid_set's binary_logloss: 0.207518
[5750]	valid_set's binary_logloss: 0.207519
[5800]	valid_set's binary_logloss: 0.207508
[5850]	valid_set's binary_logloss: 0.207529
[5900]	valid_set's binary_logloss: 0.207489
[5950]	valid_set's binary_logloss: 0.207492
[6000]	valid_set's binary_logloss: 0.207462
[6050]	valid_set's binary_logloss: 0.207466
[6100]	valid_set's binary_logloss: 0.207473
[6150]	valid_set's binary_logloss: 0.207495
[6200]	valid_set's binary_logloss: 0.207511
[6250]	valid_set's binary_logloss: 0.207513
[6300]	valid_set's binary_logloss: 0.20752
[6350]	valid_set's binary_logloss: 0.207538
[6400]	valid_set's binary_logloss: 0.207578
[6450]	valid_set's binary_logloss: 0.207589
[6500]	valid_set's binary_logloss: 0.207584
[6550]	valid_set's binary_logloss: 0.20761
[6600]	valid_set's binary_logloss: 0.207599
[6650]	valid_set's binary_logloss: 0.207635
[6700]	valid_set's binary_logloss: 0.207644
[6750]	valid_set's binary_logloss: 0.207656
[6800]	valid_set's binary_logloss: 0.20764
[6850]	valid_set's binary_logloss: 0.207629
[6900]	valid_set's binary_logloss: 0.207635
[6950]	valid_set's binary_logloss: 0.207649
[7000]	valid_set's binary_logloss: 0.207675
[7050]	valid_set's binary_logloss: 0.207692
[7100]	valid_set's binary_logloss: 0.207717
[7150]	valid_set's binary_logloss: 0.207693
[7200]	valid_set's binary_logloss: 0.207658
[7250]	valid_set's binary_logloss: 0.207669
[7300]	valid_set's binary_logloss: 0.207679
[7350]	valid_set's binary_logloss: 0.207668
[7400]	valid_set's binary_logloss: 0.207665
[7450]	valid_set's binary_logloss: 0.207698
[7500]	valid_set's binary_logloss: 0.207705
[7550]	valid_set's binary_logloss: 0.207668
[7600]	valid_set's binary_logloss: 0.20768
[7650]	valid_set's binary_logloss: 0.207657
[7700]	valid_set's binary_logloss: 0.207679
[7750]	valid_set's binary_logloss: 0.207737
[7800]	valid_set's binary_logloss: 0.207725

Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\model.pkl
	0.9583	 = Validation score   (roc_auc)
	210.66s	 = Training   runtime
	11.54s	 = Validation runtime
	5852.1	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 32175.16s of the 32175.15s of remaining time.
	Fitting LightGBMLarge_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.308614
[100]	valid_set's binary_logloss: 0.278981
[150]	valid_set's binary_logloss: 0.266652
[200]	valid_set's binary_logloss: 0.259301
[250]	valid_set's binary_logloss: 0.254399
[300]	valid_set's binary_logloss: 0.250441
[350]	valid_set's binary_logloss: 0.24745
[400]	valid_set's binary_logloss: 0.244881
[450]	valid_set's binary_logloss: 0.242828
[500]	valid_set's binary_logloss: 0.240948
[550]	valid_set's binary_logloss: 0.239347
[600]	valid_set's binary_logloss: 0.237934
[650]	valid_set's binary_logloss: 0.236627
[700]	valid_set's binary_logloss: 0.235481
[750]	valid_set's binary_logloss: 0.234471
[800]	valid_set's binary_logloss: 0.233535
[850]	valid_set's binary_logloss: 0.232549
[900]	valid_set's binary_logloss: 0.231835
[950]	valid_set's binary_logloss: 0.231027
[1000]	valid_set's binary_logloss: 0.230297
[1050]	valid_set's binary_logloss: 0.229559
[1100]	valid_set's binary_logloss: 0.228992
[1150]	valid_set's binary_logloss: 0.228469
[1200]	valid_set's binary_logloss: 0.227856
[1250]	valid_set's binary_logloss: 0.227439
[1300]	valid_set's binary_logloss: 0.226953
[1350]	valid_set's binary_logloss: 0.226415
[1400]	valid_set's binary_logloss: 0.225806
[1450]	valid_set's binary_logloss: 0.225419
[1500]	valid_set's binary_logloss: 0.225039
[1550]	valid_set's binary_logloss: 0.22463
[1600]	valid_set's binary_logloss: 0.224265
[1650]	valid_set's binary_logloss: 0.223859
[1700]	valid_set's binary_logloss: 0.223532
[1750]	valid_set's binary_logloss: 0.223174
[1800]	valid_set's binary_logloss: 0.222872
[1850]	valid_set's binary_logloss: 0.222588
[1900]	valid_set's binary_logloss: 0.222334
[1950]	valid_set's binary_logloss: 0.222035
[2000]	valid_set's binary_logloss: 0.221754
[2050]	valid_set's binary_logloss: 0.221522
[2100]	valid_set's binary_logloss: 0.221335
[2150]	valid_set's binary_logloss: 0.221081
[2200]	valid_set's binary_logloss: 0.22087
[2250]	valid_set's binary_logloss: 0.220635
[2300]	valid_set's binary_logloss: 0.220434
[2350]	valid_set's binary_logloss: 0.220211
[2400]	valid_set's binary_logloss: 0.220038
[2450]	valid_set's binary_logloss: 0.219889
[2500]	valid_set's binary_logloss: 0.219752
[2550]	valid_set's binary_logloss: 0.219617
[2600]	valid_set's binary_logloss: 0.219429
[2650]	valid_set's binary_logloss: 0.219248
[2700]	valid_set's binary_logloss: 0.219123
[2750]	valid_set's binary_logloss: 0.218933
[2800]	valid_set's binary_logloss: 0.218785
[2850]	valid_set's binary_logloss: 0.218662
[2900]	valid_set's binary_logloss: 0.218545
[2950]	valid_set's binary_logloss: 0.218436
[3000]	valid_set's binary_logloss: 0.218302
[3050]	valid_set's binary_logloss: 0.218154
[3100]	valid_set's binary_logloss: 0.218031
[3150]	valid_set's binary_logloss: 0.217898
[3200]	valid_set's binary_logloss: 0.217791
[3250]	valid_set's binary_logloss: 0.217689
[3300]	valid_set's binary_logloss: 0.217556
[3350]	valid_set's binary_logloss: 0.217425
[3400]	valid_set's binary_logloss: 0.217311
[3450]	valid_set's binary_logloss: 0.217214
[3500]	valid_set's binary_logloss: 0.217109
[3550]	valid_set's binary_logloss: 0.217016
[3600]	valid_set's binary_logloss: 0.216909
[3650]	valid_set's binary_logloss: 0.2168
[3700]	valid_set's binary_logloss: 0.216718
[3750]	valid_set's binary_logloss: 0.216655
[3800]	valid_set's binary_logloss: 0.216557
[3850]	valid_set's binary_logloss: 0.216459
[3900]	valid_set's binary_logloss: 0.216349
[3950]	valid_set's binary_logloss: 0.216284
[4000]	valid_set's binary_logloss: 0.216139
[4050]	valid_set's binary_logloss: 0.216026
[4100]	valid_set's binary_logloss: 0.215939
[4150]	valid_set's binary_logloss: 0.215862
[4200]	valid_set's binary_logloss: 0.215824
[4250]	valid_set's binary_logloss: 0.215758
[4300]	valid_set's binary_logloss: 0.215675
[4350]	valid_set's binary_logloss: 0.215587
[4400]	valid_set's binary_logloss: 0.215498
[4450]	valid_set's binary_logloss: 0.215445
[4500]	valid_set's binary_logloss: 0.215355
[4550]	valid_set's binary_logloss: 0.215273
[4600]	valid_set's binary_logloss: 0.215218
[4650]	valid_set's binary_logloss: 0.215158
[4700]	valid_set's binary_logloss: 0.215088
[4750]	valid_set's binary_logloss: 0.215001
[4800]	valid_set's binary_logloss: 0.214923
[4850]	valid_set's binary_logloss: 0.214898
[4900]	valid_set's binary_logloss: 0.21483
[4950]	valid_set's binary_logloss: 0.214799
[5000]	valid_set's binary_logloss: 0.214735
[5050]	valid_set's binary_logloss: 0.214702
[5100]	valid_set's binary_logloss: 0.214619
[5150]	valid_set's binary_logloss: 0.214584
[5200]	valid_set's binary_logloss: 0.214547
[5250]	valid_set's binary_logloss: 0.214535
[5300]	valid_set's binary_logloss: 0.214503
[5350]	valid_set's binary_logloss: 0.214453
[5400]	valid_set's binary_logloss: 0.214434
[5450]	valid_set's binary_logloss: 0.214404
[5500]	valid_set's binary_logloss: 0.214339
[5550]	valid_set's binary_logloss: 0.214294
[5600]	valid_set's binary_logloss: 0.214235
[5650]	valid_set's binary_logloss: 0.214211
[5700]	valid_set's binary_logloss: 0.214158
[5750]	valid_set's binary_logloss: 0.214097
[5800]	valid_set's binary_logloss: 0.214105
[5850]	valid_set's binary_logloss: 0.214044
[5900]	valid_set's binary_logloss: 0.214009
[5950]	valid_set's binary_logloss: 0.213978
[6000]	valid_set's binary_logloss: 0.213922
[6050]	valid_set's binary_logloss: 0.213887
[6100]	valid_set's binary_logloss: 0.213858
[6150]	valid_set's binary_logloss: 0.213814
[6200]	valid_set's binary_logloss: 0.213766
[6250]	valid_set's binary_logloss: 0.213733
[6300]	valid_set's binary_logloss: 0.213695
[6350]	valid_set's binary_logloss: 0.213669
[6400]	valid_set's binary_logloss: 0.213617
[6450]	valid_set's binary_logloss: 0.2136
[6500]	valid_set's binary_logloss: 0.213562
[6550]	valid_set's binary_logloss: 0.213557
[6600]	valid_set's binary_logloss: 0.213522
[6650]	valid_set's binary_logloss: 0.213514
[6700]	valid_set's binary_logloss: 0.21347
[6750]	valid_set's binary_logloss: 0.213447
[6800]	valid_set's binary_logloss: 0.213422
[6850]	valid_set's binary_logloss: 0.213369
[6900]	valid_set's binary_logloss: 0.213357
[6950]	valid_set's binary_logloss: 0.213343
[7000]	valid_set's binary_logloss: 0.213302
[7050]	valid_set's binary_logloss: 0.213253
[7100]	valid_set's binary_logloss: 0.21322
[7150]	valid_set's binary_logloss: 0.213192
[7200]	valid_set's binary_logloss: 0.213159
[7250]	valid_set's binary_logloss: 0.213134
[7300]	valid_set's binary_logloss: 0.213109
[7350]	valid_set's binary_logloss: 0.213091
[7400]	valid_set's binary_logloss: 0.213119
[7450]	valid_set's binary_logloss: 0.213108
[7500]	valid_set's binary_logloss: 0.213085
[7550]	valid_set's binary_logloss: 0.213073
[7600]	valid_set's binary_logloss: 0.213063
[7650]	valid_set's binary_logloss: 0.213049
[7700]	valid_set's binary_logloss: 0.213035
[7750]	valid_set's binary_logloss: 0.213034
[7800]	valid_set's binary_logloss: 0.21301
[7850]	valid_set's binary_logloss: 0.213
[7900]	valid_set's binary_logloss: 0.212934
[7950]	valid_set's binary_logloss: 0.212915
[8000]	valid_set's binary_logloss: 0.212888
[8050]	valid_set's binary_logloss: 0.212858
[8100]	valid_set's binary_logloss: 0.212849
[8150]	valid_set's binary_logloss: 0.212814
[8200]	valid_set's binary_logloss: 0.212809
[8250]	valid_set's binary_logloss: 0.2128
[8300]	valid_set's binary_logloss: 0.212781
[8350]	valid_set's binary_logloss: 0.212753
[8400]	valid_set's binary_logloss: 0.212702
[8450]	valid_set's binary_logloss: 0.212655
[8500]	valid_set's binary_logloss: 0.212629
[8550]	valid_set's binary_logloss: 0.212595
[8600]	valid_set's binary_logloss: 0.212578
[8650]	valid_set's binary_logloss: 0.212548
[8700]	valid_set's binary_logloss: 0.212548
[8750]	valid_set's binary_logloss: 0.212523
[8800]	valid_set's binary_logloss: 0.21252
[8850]	valid_set's binary_logloss: 0.212498
[8900]	valid_set's binary_logloss: 0.212468
[8950]	valid_set's binary_logloss: 0.212439
[9000]	valid_set's binary_logloss: 0.212405
[9050]	valid_set's binary_logloss: 0.212389
[9100]	valid_set's binary_logloss: 0.212386
[9150]	valid_set's binary_logloss: 0.212372
[9200]	valid_set's binary_logloss: 0.212359
[9250]	valid_set's binary_logloss: 0.212356
[9300]	valid_set's binary_logloss: 0.212358
[9350]	valid_set's binary_logloss: 0.212347
[9400]	valid_set's binary_logloss: 0.212373
[9450]	valid_set's binary_logloss: 0.212351
[9500]	valid_set's binary_logloss: 0.212342
[9550]	valid_set's binary_logloss: 0.212339
[9600]	valid_set's binary_logloss: 0.212334
[9650]	valid_set's binary_logloss: 0.212302
[9700]	valid_set's binary_logloss: 0.212296
[9750]	valid_set's binary_logloss: 0.212282
[9800]	valid_set's binary_logloss: 0.212273
[9850]	valid_set's binary_logloss: 0.212264
[9900]	valid_set's binary_logloss: 0.212269
[9950]	valid_set's binary_logloss: 0.212242
[10000]	valid_set's binary_logloss: 0.212244

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.30754
[100]	valid_set's binary_logloss: 0.280061
[150]	valid_set's binary_logloss: 0.268053
[200]	valid_set's binary_logloss: 0.260707
[250]	valid_set's binary_logloss: 0.255903
[300]	valid_set's binary_logloss: 0.252144
[350]	valid_set's binary_logloss: 0.248891
[400]	valid_set's binary_logloss: 0.246297
[450]	valid_set's binary_logloss: 0.244048
[500]	valid_set's binary_logloss: 0.242162
[550]	valid_set's binary_logloss: 0.240424
[600]	valid_set's binary_logloss: 0.238741
[650]	valid_set's binary_logloss: 0.237309
[700]	valid_set's binary_logloss: 0.236031
[750]	valid_set's binary_logloss: 0.23508
[800]	valid_set's binary_logloss: 0.234118
[850]	valid_set's binary_logloss: 0.233131
[900]	valid_set's binary_logloss: 0.232293
[950]	valid_set's binary_logloss: 0.231465
[1000]	valid_set's binary_logloss: 0.230713
[1050]	valid_set's binary_logloss: 0.23007
[1100]	valid_set's binary_logloss: 0.229465
[1150]	valid_set's binary_logloss: 0.228872
[1200]	valid_set's binary_logloss: 0.228312
[1250]	valid_set's binary_logloss: 0.227813
[1300]	valid_set's binary_logloss: 0.227342
[1350]	valid_set's binary_logloss: 0.226884
[1400]	valid_set's binary_logloss: 0.226345
[1450]	valid_set's binary_logloss: 0.225932
[1500]	valid_set's binary_logloss: 0.225526
[1550]	valid_set's binary_logloss: 0.225156
[1600]	valid_set's binary_logloss: 0.224755
[1650]	valid_set's binary_logloss: 0.224375
[1700]	valid_set's binary_logloss: 0.224082
[1750]	valid_set's binary_logloss: 0.223722
[1800]	valid_set's binary_logloss: 0.223391
[1850]	valid_set's binary_logloss: 0.223055
[1900]	valid_set's binary_logloss: 0.222765
[1950]	valid_set's binary_logloss: 0.222483
[2000]	valid_set's binary_logloss: 0.222165
[2050]	valid_set's binary_logloss: 0.221895
[2100]	valid_set's binary_logloss: 0.221632
[2150]	valid_set's binary_logloss: 0.221379
[2200]	valid_set's binary_logloss: 0.221071
[2250]	valid_set's binary_logloss: 0.22082
[2300]	valid_set's binary_logloss: 0.220584
[2350]	valid_set's binary_logloss: 0.220337
[2400]	valid_set's binary_logloss: 0.220147
[2450]	valid_set's binary_logloss: 0.220016
[2500]	valid_set's binary_logloss: 0.219796
[2550]	valid_set's binary_logloss: 0.219636
[2600]	valid_set's binary_logloss: 0.21944
[2650]	valid_set's binary_logloss: 0.21928
[2700]	valid_set's binary_logloss: 0.219098
[2750]	valid_set's binary_logloss: 0.218874
[2800]	valid_set's binary_logloss: 0.218666
[2850]	valid_set's binary_logloss: 0.21853
[2900]	valid_set's binary_logloss: 0.218404
[2950]	valid_set's binary_logloss: 0.218271
[3000]	valid_set's binary_logloss: 0.218099
[3050]	valid_set's binary_logloss: 0.217947
[3100]	valid_set's binary_logloss: 0.217777
[3150]	valid_set's binary_logloss: 0.217656
[3200]	valid_set's binary_logloss: 0.217525
[3250]	valid_set's binary_logloss: 0.217371
[3300]	valid_set's binary_logloss: 0.217269
[3350]	valid_set's binary_logloss: 0.217101
[3400]	valid_set's binary_logloss: 0.216981
[3450]	valid_set's binary_logloss: 0.216847
[3500]	valid_set's binary_logloss: 0.216722
[3550]	valid_set's binary_logloss: 0.216577
[3600]	valid_set's binary_logloss: 0.216481
[3650]	valid_set's binary_logloss: 0.216352
[3700]	valid_set's binary_logloss: 0.216247
[3750]	valid_set's binary_logloss: 0.216168
[3800]	valid_set's binary_logloss: 0.216077
[3850]	valid_set's binary_logloss: 0.21594
[3900]	valid_set's binary_logloss: 0.215834
[3950]	valid_set's binary_logloss: 0.215724
[4000]	valid_set's binary_logloss: 0.215624
[4050]	valid_set's binary_logloss: 0.21553
[4100]	valid_set's binary_logloss: 0.215485
[4150]	valid_set's binary_logloss: 0.215385
[4200]	valid_set's binary_logloss: 0.215316
[4250]	valid_set's binary_logloss: 0.215204
[4300]	valid_set's binary_logloss: 0.215115
[4350]	valid_set's binary_logloss: 0.21507
[4400]	valid_set's binary_logloss: 0.214978
[4450]	valid_set's binary_logloss: 0.214893
[4500]	valid_set's binary_logloss: 0.214807
[4550]	valid_set's binary_logloss: 0.21473
[4600]	valid_set's binary_logloss: 0.21466
[4650]	valid_set's binary_logloss: 0.214615
[4700]	valid_set's binary_logloss: 0.214523
[4750]	valid_set's binary_logloss: 0.214451
[4800]	valid_set's binary_logloss: 0.214389
[4850]	valid_set's binary_logloss: 0.214302
[4900]	valid_set's binary_logloss: 0.214241
[4950]	valid_set's binary_logloss: 0.214156
[5000]	valid_set's binary_logloss: 0.214086
[5050]	valid_set's binary_logloss: 0.214036
[5100]	valid_set's binary_logloss: 0.213949
[5150]	valid_set's binary_logloss: 0.213884
[5200]	valid_set's binary_logloss: 0.213796
[5250]	valid_set's binary_logloss: 0.213747
[5300]	valid_set's binary_logloss: 0.213698
[5350]	valid_set's binary_logloss: 0.213647
[5400]	valid_set's binary_logloss: 0.213574
[5450]	valid_set's binary_logloss: 0.213539
[5500]	valid_set's binary_logloss: 0.213497
[5550]	valid_set's binary_logloss: 0.213453
[5600]	valid_set's binary_logloss: 0.213404
[5650]	valid_set's binary_logloss: 0.213337
[5700]	valid_set's binary_logloss: 0.213305
[5750]	valid_set's binary_logloss: 0.213234
[5800]	valid_set's binary_logloss: 0.213145
[5850]	valid_set's binary_logloss: 0.213124
[5900]	valid_set's binary_logloss: 0.213061
[5950]	valid_set's binary_logloss: 0.21297
[6000]	valid_set's binary_logloss: 0.212914
[6050]	valid_set's binary_logloss: 0.212865
[6100]	valid_set's binary_logloss: 0.212843
[6150]	valid_set's binary_logloss: 0.212803
[6200]	valid_set's binary_logloss: 0.21276
[6250]	valid_set's binary_logloss: 0.212719
[6300]	valid_set's binary_logloss: 0.212672
[6350]	valid_set's binary_logloss: 0.212626
[6400]	valid_set's binary_logloss: 0.2126
[6450]	valid_set's binary_logloss: 0.212572
[6500]	valid_set's binary_logloss: 0.212546
[6550]	valid_set's binary_logloss: 0.212506
[6600]	valid_set's binary_logloss: 0.212463
[6650]	valid_set's binary_logloss: 0.212443
[6700]	valid_set's binary_logloss: 0.212392
[6750]	valid_set's binary_logloss: 0.212367
[6800]	valid_set's binary_logloss: 0.212344
[6850]	valid_set's binary_logloss: 0.212312
[6900]	valid_set's binary_logloss: 0.212253
[6950]	valid_set's binary_logloss: 0.212214
[7000]	valid_set's binary_logloss: 0.212168
[7050]	valid_set's binary_logloss: 0.212154
[7100]	valid_set's binary_logloss: 0.212145
[7150]	valid_set's binary_logloss: 0.212143
[7200]	valid_set's binary_logloss: 0.212096
[7250]	valid_set's binary_logloss: 0.212076
[7300]	valid_set's binary_logloss: 0.212051
[7350]	valid_set's binary_logloss: 0.212021
[7400]	valid_set's binary_logloss: 0.21198
[7450]	valid_set's binary_logloss: 0.211978
[7500]	valid_set's binary_logloss: 0.211949
[7550]	valid_set's binary_logloss: 0.211912
[7600]	valid_set's binary_logloss: 0.211873
[7650]	valid_set's binary_logloss: 0.211842
[7700]	valid_set's binary_logloss: 0.211829
[7750]	valid_set's binary_logloss: 0.211826
[7800]	valid_set's binary_logloss: 0.211832
[7850]	valid_set's binary_logloss: 0.211812
[7900]	valid_set's binary_logloss: 0.211786
[7950]	valid_set's binary_logloss: 0.211793
[8000]	valid_set's binary_logloss: 0.211776
[8050]	valid_set's binary_logloss: 0.211748
[8100]	valid_set's binary_logloss: 0.211725
[8150]	valid_set's binary_logloss: 0.211703
[8200]	valid_set's binary_logloss: 0.211689
[8250]	valid_set's binary_logloss: 0.211668
[8300]	valid_set's binary_logloss: 0.211646
[8350]	valid_set's binary_logloss: 0.211622
[8400]	valid_set's binary_logloss: 0.211579
[8450]	valid_set's binary_logloss: 0.211572
[8500]	valid_set's binary_logloss: 0.211549
[8550]	valid_set's binary_logloss: 0.21154
[8600]	valid_set's binary_logloss: 0.211549
[8650]	valid_set's binary_logloss: 0.211544
[8700]	valid_set's binary_logloss: 0.211538
[8750]	valid_set's binary_logloss: 0.211523
[8800]	valid_set's binary_logloss: 0.211515
[8850]	valid_set's binary_logloss: 0.211517
[8900]	valid_set's binary_logloss: 0.2115
[8950]	valid_set's binary_logloss: 0.211474
[9000]	valid_set's binary_logloss: 0.211495
[9050]	valid_set's binary_logloss: 0.211472
[9100]	valid_set's binary_logloss: 0.211455
[9150]	valid_set's binary_logloss: 0.211447
[9200]	valid_set's binary_logloss: 0.211458
[9250]	valid_set's binary_logloss: 0.211458
[9300]	valid_set's binary_logloss: 0.211443
[9350]	valid_set's binary_logloss: 0.211459
[9400]	valid_set's binary_logloss: 0.211451
[9450]	valid_set's binary_logloss: 0.211444
[9500]	valid_set's binary_logloss: 0.211425
[9550]	valid_set's binary_logloss: 0.211428
[9600]	valid_set's binary_logloss: 0.211425
[9650]	valid_set's binary_logloss: 0.211408
[9700]	valid_set's binary_logloss: 0.211404
[9750]	valid_set's binary_logloss: 0.211428
[9800]	valid_set's binary_logloss: 0.211428
[9850]	valid_set's binary_logloss: 0.211423
[9900]	valid_set's binary_logloss: 0.211426
[9950]	valid_set's binary_logloss: 0.211458
[10000]	valid_set's binary_logloss: 0.211463

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.307235
[100]	valid_set's binary_logloss: 0.279697
[150]	valid_set's binary_logloss: 0.268615
[200]	valid_set's binary_logloss: 0.261452
[250]	valid_set's binary_logloss: 0.256443
[300]	valid_set's binary_logloss: 0.252682
[350]	valid_set's binary_logloss: 0.24963
[400]	valid_set's binary_logloss: 0.247018
[450]	valid_set's binary_logloss: 0.244803
[500]	valid_set's binary_logloss: 0.243038
[550]	valid_set's binary_logloss: 0.241571
[600]	valid_set's binary_logloss: 0.240239
[650]	valid_set's binary_logloss: 0.239023
[700]	valid_set's binary_logloss: 0.237981
[750]	valid_set's binary_logloss: 0.236883
[800]	valid_set's binary_logloss: 0.235799
[850]	valid_set's binary_logloss: 0.234945
[900]	valid_set's binary_logloss: 0.234256
[950]	valid_set's binary_logloss: 0.233648
[1000]	valid_set's binary_logloss: 0.232982
[1050]	valid_set's binary_logloss: 0.232294
[1100]	valid_set's binary_logloss: 0.231725
[1150]	valid_set's binary_logloss: 0.231164
[1200]	valid_set's binary_logloss: 0.230705
[1250]	valid_set's binary_logloss: 0.230293
[1300]	valid_set's binary_logloss: 0.229827
[1350]	valid_set's binary_logloss: 0.229368
[1400]	valid_set's binary_logloss: 0.229016
[1450]	valid_set's binary_logloss: 0.228653
[1500]	valid_set's binary_logloss: 0.228205
[1550]	valid_set's binary_logloss: 0.227888
[1600]	valid_set's binary_logloss: 0.227531
[1650]	valid_set's binary_logloss: 0.227152
[1700]	valid_set's binary_logloss: 0.226811
[1750]	valid_set's binary_logloss: 0.226513
[1800]	valid_set's binary_logloss: 0.226218
[1850]	valid_set's binary_logloss: 0.225944
[1900]	valid_set's binary_logloss: 0.225659
[1950]	valid_set's binary_logloss: 0.225402
[2000]	valid_set's binary_logloss: 0.225112
[2050]	valid_set's binary_logloss: 0.22485
[2100]	valid_set's binary_logloss: 0.224608
[2150]	valid_set's binary_logloss: 0.224442
[2200]	valid_set's binary_logloss: 0.224235
[2250]	valid_set's binary_logloss: 0.224042
[2300]	valid_set's binary_logloss: 0.223863
[2350]	valid_set's binary_logloss: 0.223616
[2400]	valid_set's binary_logloss: 0.223412
[2450]	valid_set's binary_logloss: 0.223224
[2500]	valid_set's binary_logloss: 0.223028
[2550]	valid_set's binary_logloss: 0.222829
[2600]	valid_set's binary_logloss: 0.22263
[2650]	valid_set's binary_logloss: 0.22244
[2700]	valid_set's binary_logloss: 0.222254
[2750]	valid_set's binary_logloss: 0.222113
[2800]	valid_set's binary_logloss: 0.221994
[2850]	valid_set's binary_logloss: 0.221893
[2900]	valid_set's binary_logloss: 0.221767
[2950]	valid_set's binary_logloss: 0.221653
[3000]	valid_set's binary_logloss: 0.221524
[3050]	valid_set's binary_logloss: 0.221445
[3100]	valid_set's binary_logloss: 0.221316
[3150]	valid_set's binary_logloss: 0.221195
[3200]	valid_set's binary_logloss: 0.221059
[3250]	valid_set's binary_logloss: 0.220947
[3300]	valid_set's binary_logloss: 0.220815
[3350]	valid_set's binary_logloss: 0.220662
[3400]	valid_set's binary_logloss: 0.220582
[3450]	valid_set's binary_logloss: 0.22046
[3500]	valid_set's binary_logloss: 0.220384
[3550]	valid_set's binary_logloss: 0.220275
[3600]	valid_set's binary_logloss: 0.220173
[3650]	valid_set's binary_logloss: 0.220049
[3700]	valid_set's binary_logloss: 0.219904
[3750]	valid_set's binary_logloss: 0.219777
[3800]	valid_set's binary_logloss: 0.219649
[3850]	valid_set's binary_logloss: 0.219543
[3900]	valid_set's binary_logloss: 0.219457
[3950]	valid_set's binary_logloss: 0.219411
[4000]	valid_set's binary_logloss: 0.219332
[4050]	valid_set's binary_logloss: 0.219212
[4100]	valid_set's binary_logloss: 0.219114
[4150]	valid_set's binary_logloss: 0.219001
[4200]	valid_set's binary_logloss: 0.218939
[4250]	valid_set's binary_logloss: 0.218859
[4300]	valid_set's binary_logloss: 0.218809
[4350]	valid_set's binary_logloss: 0.21877
[4400]	valid_set's binary_logloss: 0.218736
[4450]	valid_set's binary_logloss: 0.21866
[4500]	valid_set's binary_logloss: 0.218576
[4550]	valid_set's binary_logloss: 0.218537
[4600]	valid_set's binary_logloss: 0.21848
[4650]	valid_set's binary_logloss: 0.218397
[4700]	valid_set's binary_logloss: 0.218352
[4750]	valid_set's binary_logloss: 0.21831
[4800]	valid_set's binary_logloss: 0.218287
[4850]	valid_set's binary_logloss: 0.218217
[4900]	valid_set's binary_logloss: 0.218148
[4950]	valid_set's binary_logloss: 0.218103
[5000]	valid_set's binary_logloss: 0.21806
[5050]	valid_set's binary_logloss: 0.218025
[5100]	valid_set's binary_logloss: 0.217973
[5150]	valid_set's binary_logloss: 0.217956
[5200]	valid_set's binary_logloss: 0.217915
[5250]	valid_set's binary_logloss: 0.217893
[5300]	valid_set's binary_logloss: 0.217879
[5350]	valid_set's binary_logloss: 0.217852
[5400]	valid_set's binary_logloss: 0.21781
[5450]	valid_set's binary_logloss: 0.217785
[5500]	valid_set's binary_logloss: 0.217738
[5550]	valid_set's binary_logloss: 0.217689
[5600]	valid_set's binary_logloss: 0.217623
[5650]	valid_set's binary_logloss: 0.21758
[5700]	valid_set's binary_logloss: 0.217524
[5750]	valid_set's binary_logloss: 0.217495
[5800]	valid_set's binary_logloss: 0.217503
[5850]	valid_set's binary_logloss: 0.217464
[5900]	valid_set's binary_logloss: 0.217406
[5950]	valid_set's binary_logloss: 0.217392
[6000]	valid_set's binary_logloss: 0.217352
[6050]	valid_set's binary_logloss: 0.217323
[6100]	valid_set's binary_logloss: 0.217289
[6150]	valid_set's binary_logloss: 0.217268
[6200]	valid_set's binary_logloss: 0.217254
[6250]	valid_set's binary_logloss: 0.217207
[6300]	valid_set's binary_logloss: 0.217171
[6350]	valid_set's binary_logloss: 0.217094
[6400]	valid_set's binary_logloss: 0.217073
[6450]	valid_set's binary_logloss: 0.217042
[6500]	valid_set's binary_logloss: 0.217026
[6550]	valid_set's binary_logloss: 0.217009
[6600]	valid_set's binary_logloss: 0.21695
[6650]	valid_set's binary_logloss: 0.216944
[6700]	valid_set's binary_logloss: 0.21695
[6750]	valid_set's binary_logloss: 0.216909
[6800]	valid_set's binary_logloss: 0.216888
[6850]	valid_set's binary_logloss: 0.216883
[6900]	valid_set's binary_logloss: 0.216873
[6950]	valid_set's binary_logloss: 0.216853
[7000]	valid_set's binary_logloss: 0.216861
[7050]	valid_set's binary_logloss: 0.216831
[7100]	valid_set's binary_logloss: 0.216792
[7150]	valid_set's binary_logloss: 0.216769
[7200]	valid_set's binary_logloss: 0.216727
[7250]	valid_set's binary_logloss: 0.2167
[7300]	valid_set's binary_logloss: 0.216693
[7350]	valid_set's binary_logloss: 0.216663
[7400]	valid_set's binary_logloss: 0.216624
[7450]	valid_set's binary_logloss: 0.216621
[7500]	valid_set's binary_logloss: 0.21661
[7550]	valid_set's binary_logloss: 0.216613
[7600]	valid_set's binary_logloss: 0.216588
[7650]	valid_set's binary_logloss: 0.216548
[7700]	valid_set's binary_logloss: 0.216515
[7750]	valid_set's binary_logloss: 0.216473
[7800]	valid_set's binary_logloss: 0.216463
[7850]	valid_set's binary_logloss: 0.216426
[7900]	valid_set's binary_logloss: 0.216409
[7950]	valid_set's binary_logloss: 0.216401
[8000]	valid_set's binary_logloss: 0.216393
[8050]	valid_set's binary_logloss: 0.216372
[8100]	valid_set's binary_logloss: 0.216342
[8150]	valid_set's binary_logloss: 0.216336
[8200]	valid_set's binary_logloss: 0.216333
[8250]	valid_set's binary_logloss: 0.216328
[8300]	valid_set's binary_logloss: 0.216288
[8350]	valid_set's binary_logloss: 0.216283
[8400]	valid_set's binary_logloss: 0.21626
[8450]	valid_set's binary_logloss: 0.216237
[8500]	valid_set's binary_logloss: 0.216237
[8550]	valid_set's binary_logloss: 0.216237
[8600]	valid_set's binary_logloss: 0.216191
[8650]	valid_set's binary_logloss: 0.21618
[8700]	valid_set's binary_logloss: 0.21619
[8750]	valid_set's binary_logloss: 0.216165
[8800]	valid_set's binary_logloss: 0.216156
[8850]	valid_set's binary_logloss: 0.216116
[8900]	valid_set's binary_logloss: 0.216099
[8950]	valid_set's binary_logloss: 0.216088
[9000]	valid_set's binary_logloss: 0.216074
[9050]	valid_set's binary_logloss: 0.216049
[9100]	valid_set's binary_logloss: 0.216027
[9150]	valid_set's binary_logloss: 0.216028
[9200]	valid_set's binary_logloss: 0.216039
[9250]	valid_set's binary_logloss: 0.216027
[9300]	valid_set's binary_logloss: 0.21601
[9350]	valid_set's binary_logloss: 0.215995
[9400]	valid_set's binary_logloss: 0.215991
[9450]	valid_set's binary_logloss: 0.216015
[9500]	valid_set's binary_logloss: 0.216026
[9550]	valid_set's binary_logloss: 0.216059
[9600]	valid_set's binary_logloss: 0.216052
[9650]	valid_set's binary_logloss: 0.216053
[9700]	valid_set's binary_logloss: 0.216042
[9750]	valid_set's binary_logloss: 0.21602
[9800]	valid_set's binary_logloss: 0.216027
[9850]	valid_set's binary_logloss: 0.216023
[9900]	valid_set's binary_logloss: 0.216011
[9950]	valid_set's binary_logloss: 0.216025
[10000]	valid_set's binary_logloss: 0.216038

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.307592
[100]	valid_set's binary_logloss: 0.278806
[150]	valid_set's binary_logloss: 0.26644
[200]	valid_set's binary_logloss: 0.258831
[250]	valid_set's binary_logloss: 0.253808
[300]	valid_set's binary_logloss: 0.250066
[350]	valid_set's binary_logloss: 0.247202
[400]	valid_set's binary_logloss: 0.244493
[450]	valid_set's binary_logloss: 0.242353
[500]	valid_set's binary_logloss: 0.240587
[550]	valid_set's binary_logloss: 0.239043
[600]	valid_set's binary_logloss: 0.237675
[650]	valid_set's binary_logloss: 0.23636
[700]	valid_set's binary_logloss: 0.235192
[750]	valid_set's binary_logloss: 0.234178
[800]	valid_set's binary_logloss: 0.233295
[850]	valid_set's binary_logloss: 0.232445
[900]	valid_set's binary_logloss: 0.231696
[950]	valid_set's binary_logloss: 0.230951
[1000]	valid_set's binary_logloss: 0.230308
[1050]	valid_set's binary_logloss: 0.229659
[1100]	valid_set's binary_logloss: 0.229046
[1150]	valid_set's binary_logloss: 0.228478
[1200]	valid_set's binary_logloss: 0.227993
[1250]	valid_set's binary_logloss: 0.227506
[1300]	valid_set's binary_logloss: 0.226979
[1350]	valid_set's binary_logloss: 0.226528
[1400]	valid_set's binary_logloss: 0.226069
[1450]	valid_set's binary_logloss: 0.225627
[1500]	valid_set's binary_logloss: 0.225242
[1550]	valid_set's binary_logloss: 0.224806
[1600]	valid_set's binary_logloss: 0.224437
[1650]	valid_set's binary_logloss: 0.224032
[1700]	valid_set's binary_logloss: 0.223716
[1750]	valid_set's binary_logloss: 0.223354
[1800]	valid_set's binary_logloss: 0.223062
[1850]	valid_set's binary_logloss: 0.222745
[1900]	valid_set's binary_logloss: 0.222438
[1950]	valid_set's binary_logloss: 0.22216
[2000]	valid_set's binary_logloss: 0.221893
[2050]	valid_set's binary_logloss: 0.221676
[2100]	valid_set's binary_logloss: 0.221479
[2150]	valid_set's binary_logloss: 0.221234
[2200]	valid_set's binary_logloss: 0.22105
[2250]	valid_set's binary_logloss: 0.220849
[2300]	valid_set's binary_logloss: 0.22059
[2350]	valid_set's binary_logloss: 0.220377
[2400]	valid_set's binary_logloss: 0.220213
[2450]	valid_set's binary_logloss: 0.220017
[2500]	valid_set's binary_logloss: 0.219827
[2550]	valid_set's binary_logloss: 0.219673
[2600]	valid_set's binary_logloss: 0.219516
[2650]	valid_set's binary_logloss: 0.219349
[2700]	valid_set's binary_logloss: 0.219216
[2750]	valid_set's binary_logloss: 0.219079
[2800]	valid_set's binary_logloss: 0.218855
[2850]	valid_set's binary_logloss: 0.218723
[2900]	valid_set's binary_logloss: 0.218578
[2950]	valid_set's binary_logloss: 0.218451
[3000]	valid_set's binary_logloss: 0.21832
[3050]	valid_set's binary_logloss: 0.218205
[3100]	valid_set's binary_logloss: 0.218109
[3150]	valid_set's binary_logloss: 0.217988
[3200]	valid_set's binary_logloss: 0.217849
[3250]	valid_set's binary_logloss: 0.2177
[3300]	valid_set's binary_logloss: 0.217561
[3350]	valid_set's binary_logloss: 0.217453
[3400]	valid_set's binary_logloss: 0.217333
[3450]	valid_set's binary_logloss: 0.217195
[3500]	valid_set's binary_logloss: 0.217066
[3550]	valid_set's binary_logloss: 0.216948
[3600]	valid_set's binary_logloss: 0.216841
[3650]	valid_set's binary_logloss: 0.216742
[3700]	valid_set's binary_logloss: 0.216669
[3750]	valid_set's binary_logloss: 0.216574
[3800]	valid_set's binary_logloss: 0.216508
[3850]	valid_set's binary_logloss: 0.216422
[3900]	valid_set's binary_logloss: 0.216343
[3950]	valid_set's binary_logloss: 0.216281
[4000]	valid_set's binary_logloss: 0.216202
[4050]	valid_set's binary_logloss: 0.216151
[4100]	valid_set's binary_logloss: 0.216075
[4150]	valid_set's binary_logloss: 0.216015
[4200]	valid_set's binary_logloss: 0.21598
[4250]	valid_set's binary_logloss: 0.215884
[4300]	valid_set's binary_logloss: 0.215804
[4350]	valid_set's binary_logloss: 0.215721
[4400]	valid_set's binary_logloss: 0.215664
[4450]	valid_set's binary_logloss: 0.215559
[4500]	valid_set's binary_logloss: 0.215502
[4550]	valid_set's binary_logloss: 0.215437
[4600]	valid_set's binary_logloss: 0.215367
[4650]	valid_set's binary_logloss: 0.215275
[4700]	valid_set's binary_logloss: 0.215224
[4750]	valid_set's binary_logloss: 0.21517
[4800]	valid_set's binary_logloss: 0.215104
[4850]	valid_set's binary_logloss: 0.215058
[4900]	valid_set's binary_logloss: 0.215037
[4950]	valid_set's binary_logloss: 0.214991
[5000]	valid_set's binary_logloss: 0.214949
[5050]	valid_set's binary_logloss: 0.2149
[5100]	valid_set's binary_logloss: 0.214891
[5150]	valid_set's binary_logloss: 0.214808
[5200]	valid_set's binary_logloss: 0.214747
[5250]	valid_set's binary_logloss: 0.214676
[5300]	valid_set's binary_logloss: 0.214644
[5350]	valid_set's binary_logloss: 0.214613
[5400]	valid_set's binary_logloss: 0.214563
[5450]	valid_set's binary_logloss: 0.214514
[5500]	valid_set's binary_logloss: 0.214469
[5550]	valid_set's binary_logloss: 0.214435
[5600]	valid_set's binary_logloss: 0.214379
[5650]	valid_set's binary_logloss: 0.214369
[5700]	valid_set's binary_logloss: 0.214313
[5750]	valid_set's binary_logloss: 0.214305
[5800]	valid_set's binary_logloss: 0.214277
[5850]	valid_set's binary_logloss: 0.214219
[5900]	valid_set's binary_logloss: 0.214189
[5950]	valid_set's binary_logloss: 0.214131
[6000]	valid_set's binary_logloss: 0.214079
[6050]	valid_set's binary_logloss: 0.213994
[6100]	valid_set's binary_logloss: 0.213936
[6150]	valid_set's binary_logloss: 0.213905
[6200]	valid_set's binary_logloss: 0.213883
[6250]	valid_set's binary_logloss: 0.213823
[6300]	valid_set's binary_logloss: 0.213752
[6350]	valid_set's binary_logloss: 0.213709
[6400]	valid_set's binary_logloss: 0.213664
[6450]	valid_set's binary_logloss: 0.213637
[6500]	valid_set's binary_logloss: 0.21362
[6550]	valid_set's binary_logloss: 0.213589
[6600]	valid_set's binary_logloss: 0.213554
[6650]	valid_set's binary_logloss: 0.213527
[6700]	valid_set's binary_logloss: 0.213499
[6750]	valid_set's binary_logloss: 0.213471
[6800]	valid_set's binary_logloss: 0.213427
[6850]	valid_set's binary_logloss: 0.213384
[6900]	valid_set's binary_logloss: 0.213349
[6950]	valid_set's binary_logloss: 0.213331
[7000]	valid_set's binary_logloss: 0.213297
[7050]	valid_set's binary_logloss: 0.213277
[7100]	valid_set's binary_logloss: 0.213265
[7150]	valid_set's binary_logloss: 0.213237
[7200]	valid_set's binary_logloss: 0.213246
[7250]	valid_set's binary_logloss: 0.213222
[7300]	valid_set's binary_logloss: 0.213182
[7350]	valid_set's binary_logloss: 0.213168
[7400]	valid_set's binary_logloss: 0.213174
[7450]	valid_set's binary_logloss: 0.213183
[7500]	valid_set's binary_logloss: 0.213181
[7550]	valid_set's binary_logloss: 0.21316
[7600]	valid_set's binary_logloss: 0.213106
[7650]	valid_set's binary_logloss: 0.213083
[7700]	valid_set's binary_logloss: 0.213032
[7750]	valid_set's binary_logloss: 0.213011
[7800]	valid_set's binary_logloss: 0.213018
[7850]	valid_set's binary_logloss: 0.212984
[7900]	valid_set's binary_logloss: 0.212977
[7950]	valid_set's binary_logloss: 0.212959
[8000]	valid_set's binary_logloss: 0.212919
[8050]	valid_set's binary_logloss: 0.212887
[8100]	valid_set's binary_logloss: 0.212858
[8150]	valid_set's binary_logloss: 0.212848
[8200]	valid_set's binary_logloss: 0.212839
[8250]	valid_set's binary_logloss: 0.212817
[8300]	valid_set's binary_logloss: 0.212802
[8350]	valid_set's binary_logloss: 0.212827
[8400]	valid_set's binary_logloss: 0.212797
[8450]	valid_set's binary_logloss: 0.212803
[8500]	valid_set's binary_logloss: 0.212793
[8550]	valid_set's binary_logloss: 0.212787
[8600]	valid_set's binary_logloss: 0.212774
[8650]	valid_set's binary_logloss: 0.212753
[8700]	valid_set's binary_logloss: 0.212742
[8750]	valid_set's binary_logloss: 0.212736
[8800]	valid_set's binary_logloss: 0.212722
[8850]	valid_set's binary_logloss: 0.212711
[8900]	valid_set's binary_logloss: 0.212659
[8950]	valid_set's binary_logloss: 0.212626
[9000]	valid_set's binary_logloss: 0.212614
[9050]	valid_set's binary_logloss: 0.212622
[9100]	valid_set's binary_logloss: 0.212611
[9150]	valid_set's binary_logloss: 0.212596
[9200]	valid_set's binary_logloss: 0.212582
[9250]	valid_set's binary_logloss: 0.212585
[9300]	valid_set's binary_logloss: 0.21259
[9350]	valid_set's binary_logloss: 0.212594
[9400]	valid_set's binary_logloss: 0.212598
[9450]	valid_set's binary_logloss: 0.2126
[9500]	valid_set's binary_logloss: 0.212583
[9550]	valid_set's binary_logloss: 0.212578
[9600]	valid_set's binary_logloss: 0.212592
[9650]	valid_set's binary_logloss: 0.212609
[9700]	valid_set's binary_logloss: 0.212581
[9750]	valid_set's binary_logloss: 0.212585
[9800]	valid_set's binary_logloss: 0.212587
[9850]	valid_set's binary_logloss: 0.212577
[9900]	valid_set's binary_logloss: 0.212559
[9950]	valid_set's binary_logloss: 0.212571
[10000]	valid_set's binary_logloss: 0.212557

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.307225
[100]	valid_set's binary_logloss: 0.278494
[150]	valid_set's binary_logloss: 0.26643
[200]	valid_set's binary_logloss: 0.259483
[250]	valid_set's binary_logloss: 0.254191
[300]	valid_set's binary_logloss: 0.250364
[350]	valid_set's binary_logloss: 0.247091
[400]	valid_set's binary_logloss: 0.244507
[450]	valid_set's binary_logloss: 0.242047
[500]	valid_set's binary_logloss: 0.240435
[550]	valid_set's binary_logloss: 0.238762
[600]	valid_set's binary_logloss: 0.237166
[650]	valid_set's binary_logloss: 0.235913
[700]	valid_set's binary_logloss: 0.234724
[750]	valid_set's binary_logloss: 0.233805
[800]	valid_set's binary_logloss: 0.232938
[850]	valid_set's binary_logloss: 0.232115
[900]	valid_set's binary_logloss: 0.231367
[950]	valid_set's binary_logloss: 0.23066
[1000]	valid_set's binary_logloss: 0.22996
[1050]	valid_set's binary_logloss: 0.229205
[1100]	valid_set's binary_logloss: 0.228552
[1150]	valid_set's binary_logloss: 0.228048
[1200]	valid_set's binary_logloss: 0.227532
[1250]	valid_set's binary_logloss: 0.226996
[1300]	valid_set's binary_logloss: 0.226493
[1350]	valid_set's binary_logloss: 0.226019
[1400]	valid_set's binary_logloss: 0.225612
[1450]	valid_set's binary_logloss: 0.225245
[1500]	valid_set's binary_logloss: 0.224865
[1550]	valid_set's binary_logloss: 0.224451
[1600]	valid_set's binary_logloss: 0.223965
[1650]	valid_set's binary_logloss: 0.223609
[1700]	valid_set's binary_logloss: 0.22326
[1750]	valid_set's binary_logloss: 0.222907
[1800]	valid_set's binary_logloss: 0.222595
[1850]	valid_set's binary_logloss: 0.222255
[1900]	valid_set's binary_logloss: 0.222001
[1950]	valid_set's binary_logloss: 0.221753
[2000]	valid_set's binary_logloss: 0.221526
[2050]	valid_set's binary_logloss: 0.221191
[2100]	valid_set's binary_logloss: 0.220974
[2150]	valid_set's binary_logloss: 0.220639
[2200]	valid_set's binary_logloss: 0.220404
[2250]	valid_set's binary_logloss: 0.220186
[2300]	valid_set's binary_logloss: 0.220009
[2350]	valid_set's binary_logloss: 0.219822
[2400]	valid_set's binary_logloss: 0.219596
[2450]	valid_set's binary_logloss: 0.219379
[2500]	valid_set's binary_logloss: 0.219164
[2550]	valid_set's binary_logloss: 0.21897
[2600]	valid_set's binary_logloss: 0.21873
[2650]	valid_set's binary_logloss: 0.218592
[2700]	valid_set's binary_logloss: 0.218407
[2750]	valid_set's binary_logloss: 0.218248
[2800]	valid_set's binary_logloss: 0.218057
[2850]	valid_set's binary_logloss: 0.217884
[2900]	valid_set's binary_logloss: 0.217794
[2950]	valid_set's binary_logloss: 0.217605
[3000]	valid_set's binary_logloss: 0.217436
[3050]	valid_set's binary_logloss: 0.217306
[3100]	valid_set's binary_logloss: 0.217144
[3150]	valid_set's binary_logloss: 0.217033
[3200]	valid_set's binary_logloss: 0.216911
[3250]	valid_set's binary_logloss: 0.216714
[3300]	valid_set's binary_logloss: 0.216601
[3350]	valid_set's binary_logloss: 0.216439
[3400]	valid_set's binary_logloss: 0.216349
[3450]	valid_set's binary_logloss: 0.2162
[3500]	valid_set's binary_logloss: 0.216075
[3550]	valid_set's binary_logloss: 0.215983
[3600]	valid_set's binary_logloss: 0.215838
[3650]	valid_set's binary_logloss: 0.215669
[3700]	valid_set's binary_logloss: 0.215554
[3750]	valid_set's binary_logloss: 0.215419
[3800]	valid_set's binary_logloss: 0.21529
[3850]	valid_set's binary_logloss: 0.215187
[3900]	valid_set's binary_logloss: 0.215083
[3950]	valid_set's binary_logloss: 0.215022
[4000]	valid_set's binary_logloss: 0.214938
[4050]	valid_set's binary_logloss: 0.214883
[4100]	valid_set's binary_logloss: 0.214806
[4150]	valid_set's binary_logloss: 0.214731
[4200]	valid_set's binary_logloss: 0.214687
[4250]	valid_set's binary_logloss: 0.2146
[4300]	valid_set's binary_logloss: 0.214508
[4350]	valid_set's binary_logloss: 0.21442
[4400]	valid_set's binary_logloss: 0.214343
[4450]	valid_set's binary_logloss: 0.214283
[4500]	valid_set's binary_logloss: 0.214197
[4550]	valid_set's binary_logloss: 0.21415
[4600]	valid_set's binary_logloss: 0.214073
[4650]	valid_set's binary_logloss: 0.213989
[4700]	valid_set's binary_logloss: 0.213897
[4750]	valid_set's binary_logloss: 0.213815
[4800]	valid_set's binary_logloss: 0.213737
[4850]	valid_set's binary_logloss: 0.213663
[4900]	valid_set's binary_logloss: 0.213574
[4950]	valid_set's binary_logloss: 0.213492
[5000]	valid_set's binary_logloss: 0.213453
[5050]	valid_set's binary_logloss: 0.2134
[5100]	valid_set's binary_logloss: 0.213347
[5150]	valid_set's binary_logloss: 0.213296
[5200]	valid_set's binary_logloss: 0.213235
[5250]	valid_set's binary_logloss: 0.213181
[5300]	valid_set's binary_logloss: 0.213083
[5350]	valid_set's binary_logloss: 0.213013
[5400]	valid_set's binary_logloss: 0.212958
[5450]	valid_set's binary_logloss: 0.212928
[5500]	valid_set's binary_logloss: 0.212884
[5550]	valid_set's binary_logloss: 0.212806
[5600]	valid_set's binary_logloss: 0.212749
[5650]	valid_set's binary_logloss: 0.212728
[5700]	valid_set's binary_logloss: 0.212683
[5750]	valid_set's binary_logloss: 0.21265
[5800]	valid_set's binary_logloss: 0.212638
[5850]	valid_set's binary_logloss: 0.212587
[5900]	valid_set's binary_logloss: 0.21255
[5950]	valid_set's binary_logloss: 0.212492
[6000]	valid_set's binary_logloss: 0.212435
[6050]	valid_set's binary_logloss: 0.212385
[6100]	valid_set's binary_logloss: 0.212331
[6150]	valid_set's binary_logloss: 0.212285
[6200]	valid_set's binary_logloss: 0.212215
[6250]	valid_set's binary_logloss: 0.212164
[6300]	valid_set's binary_logloss: 0.212104
[6350]	valid_set's binary_logloss: 0.212057
[6400]	valid_set's binary_logloss: 0.212034
[6450]	valid_set's binary_logloss: 0.211987
[6500]	valid_set's binary_logloss: 0.211961
[6550]	valid_set's binary_logloss: 0.21194
[6600]	valid_set's binary_logloss: 0.211924
[6650]	valid_set's binary_logloss: 0.211868
[6700]	valid_set's binary_logloss: 0.211813
[6750]	valid_set's binary_logloss: 0.211777
[6800]	valid_set's binary_logloss: 0.211758
[6850]	valid_set's binary_logloss: 0.211681
[6900]	valid_set's binary_logloss: 0.211669
[6950]	valid_set's binary_logloss: 0.211672
[7000]	valid_set's binary_logloss: 0.21165
[7050]	valid_set's binary_logloss: 0.211637
[7100]	valid_set's binary_logloss: 0.211615
[7150]	valid_set's binary_logloss: 0.2116
[7200]	valid_set's binary_logloss: 0.211562
[7250]	valid_set's binary_logloss: 0.21152
[7300]	valid_set's binary_logloss: 0.211493
[7350]	valid_set's binary_logloss: 0.211483
[7400]	valid_set's binary_logloss: 0.211447
[7450]	valid_set's binary_logloss: 0.211419
[7500]	valid_set's binary_logloss: 0.211408
[7550]	valid_set's binary_logloss: 0.211376
[7600]	valid_set's binary_logloss: 0.211328
[7650]	valid_set's binary_logloss: 0.211279
[7700]	valid_set's binary_logloss: 0.211233
[7750]	valid_set's binary_logloss: 0.211235
[7800]	valid_set's binary_logloss: 0.211238
[7850]	valid_set's binary_logloss: 0.211182
[7900]	valid_set's binary_logloss: 0.211176
[7950]	valid_set's binary_logloss: 0.211154
[8000]	valid_set's binary_logloss: 0.21112
[8050]	valid_set's binary_logloss: 0.211103
[8100]	valid_set's binary_logloss: 0.21108
[8150]	valid_set's binary_logloss: 0.211084
[8200]	valid_set's binary_logloss: 0.211076
[8250]	valid_set's binary_logloss: 0.211075
[8300]	valid_set's binary_logloss: 0.211072
[8350]	valid_set's binary_logloss: 0.211065
[8400]	valid_set's binary_logloss: 0.211057
[8450]	valid_set's binary_logloss: 0.211048
[8500]	valid_set's binary_logloss: 0.211024
[8550]	valid_set's binary_logloss: 0.211019
[8600]	valid_set's binary_logloss: 0.211005
[8650]	valid_set's binary_logloss: 0.210987
[8700]	valid_set's binary_logloss: 0.210964
[8750]	valid_set's binary_logloss: 0.210942
[8800]	valid_set's binary_logloss: 0.210931
[8850]	valid_set's binary_logloss: 0.210889
[8900]	valid_set's binary_logloss: 0.210868
[8950]	valid_set's binary_logloss: 0.21086
[9000]	valid_set's binary_logloss: 0.210854
[9050]	valid_set's binary_logloss: 0.210816
[9100]	valid_set's binary_logloss: 0.210801
[9150]	valid_set's binary_logloss: 0.210796
[9200]	valid_set's binary_logloss: 0.210804
[9250]	valid_set's binary_logloss: 0.2108
[9300]	valid_set's binary_logloss: 0.210784
[9350]	valid_set's binary_logloss: 0.210775
[9400]	valid_set's binary_logloss: 0.210753
[9450]	valid_set's binary_logloss: 0.210739
[9500]	valid_set's binary_logloss: 0.210739
[9550]	valid_set's binary_logloss: 0.210746
[9600]	valid_set's binary_logloss: 0.210758
[9650]	valid_set's binary_logloss: 0.210752
[9700]	valid_set's binary_logloss: 0.210764
[9750]	valid_set's binary_logloss: 0.210785
[9800]	valid_set's binary_logloss: 0.210773
[9850]	valid_set's binary_logloss: 0.210763
[9900]	valid_set's binary_logloss: 0.210764
[9950]	valid_set's binary_logloss: 0.210757
[10000]	valid_set's binary_logloss: 0.210754

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.300709
[100]	valid_set's binary_logloss: 0.27541
[150]	valid_set's binary_logloss: 0.26512
[200]	valid_set's binary_logloss: 0.258717
[250]	valid_set's binary_logloss: 0.254142
[300]	valid_set's binary_logloss: 0.250465
[350]	valid_set's binary_logloss: 0.247369
[400]	valid_set's binary_logloss: 0.24507
[450]	valid_set's binary_logloss: 0.243074
[500]	valid_set's binary_logloss: 0.241336
[550]	valid_set's binary_logloss: 0.239691
[600]	valid_set's binary_logloss: 0.23823
[650]	valid_set's binary_logloss: 0.236773
[700]	valid_set's binary_logloss: 0.235637
[750]	valid_set's binary_logloss: 0.234574
[800]	valid_set's binary_logloss: 0.233694
[850]	valid_set's binary_logloss: 0.23284
[900]	valid_set's binary_logloss: 0.232148
[950]	valid_set's binary_logloss: 0.231332
[1000]	valid_set's binary_logloss: 0.230527
[1050]	valid_set's binary_logloss: 0.22988
[1100]	valid_set's binary_logloss: 0.229269
[1150]	valid_set's binary_logloss: 0.228781
[1200]	valid_set's binary_logloss: 0.228281
[1250]	valid_set's binary_logloss: 0.227732
[1300]	valid_set's binary_logloss: 0.227213
[1350]	valid_set's binary_logloss: 0.226746
[1400]	valid_set's binary_logloss: 0.226257
[1450]	valid_set's binary_logloss: 0.225815
[1500]	valid_set's binary_logloss: 0.225402
[1550]	valid_set's binary_logloss: 0.225074
[1600]	valid_set's binary_logloss: 0.224728
[1650]	valid_set's binary_logloss: 0.224322
[1700]	valid_set's binary_logloss: 0.22404
[1750]	valid_set's binary_logloss: 0.223724
[1800]	valid_set's binary_logloss: 0.223413
[1850]	valid_set's binary_logloss: 0.223045
[1900]	valid_set's binary_logloss: 0.222786
[1950]	valid_set's binary_logloss: 0.222535
[2000]	valid_set's binary_logloss: 0.222237
[2050]	valid_set's binary_logloss: 0.221978
[2100]	valid_set's binary_logloss: 0.22173
[2150]	valid_set's binary_logloss: 0.221449
[2200]	valid_set's binary_logloss: 0.221164
[2250]	valid_set's binary_logloss: 0.220961
[2300]	valid_set's binary_logloss: 0.220754
[2350]	valid_set's binary_logloss: 0.220436
[2400]	valid_set's binary_logloss: 0.220237
[2450]	valid_set's binary_logloss: 0.220006
[2500]	valid_set's binary_logloss: 0.21981
[2550]	valid_set's binary_logloss: 0.219598
[2600]	valid_set's binary_logloss: 0.219447
[2650]	valid_set's binary_logloss: 0.219247
[2700]	valid_set's binary_logloss: 0.219066
[2750]	valid_set's binary_logloss: 0.218946
[2800]	valid_set's binary_logloss: 0.218737
[2850]	valid_set's binary_logloss: 0.218549
[2900]	valid_set's binary_logloss: 0.218387
[2950]	valid_set's binary_logloss: 0.218194
[3000]	valid_set's binary_logloss: 0.218011
[3050]	valid_set's binary_logloss: 0.217873
[3100]	valid_set's binary_logloss: 0.217781
[3150]	valid_set's binary_logloss: 0.217614
[3200]	valid_set's binary_logloss: 0.217482
[3250]	valid_set's binary_logloss: 0.217399
[3300]	valid_set's binary_logloss: 0.217292
[3350]	valid_set's binary_logloss: 0.217123
[3400]	valid_set's binary_logloss: 0.216948
[3450]	valid_set's binary_logloss: 0.216841
[3500]	valid_set's binary_logloss: 0.216757
[3550]	valid_set's binary_logloss: 0.21666
[3600]	valid_set's binary_logloss: 0.216532
[3650]	valid_set's binary_logloss: 0.216426
[3700]	valid_set's binary_logloss: 0.216312
[3750]	valid_set's binary_logloss: 0.216168
[3800]	valid_set's binary_logloss: 0.216046
[3850]	valid_set's binary_logloss: 0.215956
[3900]	valid_set's binary_logloss: 0.215834
[3950]	valid_set's binary_logloss: 0.215769
[4000]	valid_set's binary_logloss: 0.215688
[4050]	valid_set's binary_logloss: 0.215602
[4100]	valid_set's binary_logloss: 0.215499
[4150]	valid_set's binary_logloss: 0.215443
[4200]	valid_set's binary_logloss: 0.215352
[4250]	valid_set's binary_logloss: 0.215252
[4300]	valid_set's binary_logloss: 0.215231
[4350]	valid_set's binary_logloss: 0.21515
[4400]	valid_set's binary_logloss: 0.21508
[4450]	valid_set's binary_logloss: 0.215026
[4500]	valid_set's binary_logloss: 0.214988
[4550]	valid_set's binary_logloss: 0.214908
[4600]	valid_set's binary_logloss: 0.214868
[4650]	valid_set's binary_logloss: 0.214793
[4700]	valid_set's binary_logloss: 0.214701
[4750]	valid_set's binary_logloss: 0.214624
[4800]	valid_set's binary_logloss: 0.214575
[4850]	valid_set's binary_logloss: 0.214492
[4900]	valid_set's binary_logloss: 0.214471
[4950]	valid_set's binary_logloss: 0.214431
[5000]	valid_set's binary_logloss: 0.214377
[5050]	valid_set's binary_logloss: 0.214369
[5100]	valid_set's binary_logloss: 0.214328
[5150]	valid_set's binary_logloss: 0.214252
[5200]	valid_set's binary_logloss: 0.214202
[5250]	valid_set's binary_logloss: 0.214161
[5300]	valid_set's binary_logloss: 0.214097
[5350]	valid_set's binary_logloss: 0.214061
[5400]	valid_set's binary_logloss: 0.214017
[5450]	valid_set's binary_logloss: 0.213985
[5500]	valid_set's binary_logloss: 0.21393
[5550]	valid_set's binary_logloss: 0.213894
[5600]	valid_set's binary_logloss: 0.213809
[5650]	valid_set's binary_logloss: 0.2138
[5700]	valid_set's binary_logloss: 0.213786
[5750]	valid_set's binary_logloss: 0.213737
[5800]	valid_set's binary_logloss: 0.213712
[5850]	valid_set's binary_logloss: 0.213653
[5900]	valid_set's binary_logloss: 0.213598
[5950]	valid_set's binary_logloss: 0.21353
[6000]	valid_set's binary_logloss: 0.213478
[6050]	valid_set's binary_logloss: 0.213424
[6100]	valid_set's binary_logloss: 0.21341
[6150]	valid_set's binary_logloss: 0.21338
[6200]	valid_set's binary_logloss: 0.213385
[6250]	valid_set's binary_logloss: 0.213373
[6300]	valid_set's binary_logloss: 0.213333
[6350]	valid_set's binary_logloss: 0.213298
[6400]	valid_set's binary_logloss: 0.21328
[6450]	valid_set's binary_logloss: 0.213244
[6500]	valid_set's binary_logloss: 0.213228
[6550]	valid_set's binary_logloss: 0.213179
[6600]	valid_set's binary_logloss: 0.213135
[6650]	valid_set's binary_logloss: 0.213124
[6700]	valid_set's binary_logloss: 0.213106
[6750]	valid_set's binary_logloss: 0.2131
[6800]	valid_set's binary_logloss: 0.213063
[6850]	valid_set's binary_logloss: 0.213063
[6900]	valid_set's binary_logloss: 0.213026
[6950]	valid_set's binary_logloss: 0.213033
[7000]	valid_set's binary_logloss: 0.21301
[7050]	valid_set's binary_logloss: 0.212975
[7100]	valid_set's binary_logloss: 0.212967
[7150]	valid_set's binary_logloss: 0.212915
[7200]	valid_set's binary_logloss: 0.212888
[7250]	valid_set's binary_logloss: 0.212884
[7300]	valid_set's binary_logloss: 0.212875
[7350]	valid_set's binary_logloss: 0.212864
[7400]	valid_set's binary_logloss: 0.212825
[7450]	valid_set's binary_logloss: 0.212806
[7500]	valid_set's binary_logloss: 0.212783
[7550]	valid_set's binary_logloss: 0.212776
[7600]	valid_set's binary_logloss: 0.212729
[7650]	valid_set's binary_logloss: 0.212735
[7700]	valid_set's binary_logloss: 0.212749
[7750]	valid_set's binary_logloss: 0.212755
[7800]	valid_set's binary_logloss: 0.212717
[7850]	valid_set's binary_logloss: 0.212679
[7900]	valid_set's binary_logloss: 0.212683
[7950]	valid_set's binary_logloss: 0.212665
[8000]	valid_set's binary_logloss: 0.212634
[8050]	valid_set's binary_logloss: 0.212629
[8100]	valid_set's binary_logloss: 0.212626
[8150]	valid_set's binary_logloss: 0.212627
[8200]	valid_set's binary_logloss: 0.212623
[8250]	valid_set's binary_logloss: 0.212597
[8300]	valid_set's binary_logloss: 0.212591
[8350]	valid_set's binary_logloss: 0.212579
[8400]	valid_set's binary_logloss: 0.212583
[8450]	valid_set's binary_logloss: 0.212564
[8500]	valid_set's binary_logloss: 0.212534
[8550]	valid_set's binary_logloss: 0.21252
[8600]	valid_set's binary_logloss: 0.212481
[8650]	valid_set's binary_logloss: 0.212446
[8700]	valid_set's binary_logloss: 0.212454
[8750]	valid_set's binary_logloss: 0.212426
[8800]	valid_set's binary_logloss: 0.212402
[8850]	valid_set's binary_logloss: 0.212389
[8900]	valid_set's binary_logloss: 0.212374
[8950]	valid_set's binary_logloss: 0.212366
[9000]	valid_set's binary_logloss: 0.212373
[9050]	valid_set's binary_logloss: 0.212349
[9100]	valid_set's binary_logloss: 0.212318
[9150]	valid_set's binary_logloss: 0.212302
[9200]	valid_set's binary_logloss: 0.21229
[9250]	valid_set's binary_logloss: 0.212251
[9300]	valid_set's binary_logloss: 0.212224
[9350]	valid_set's binary_logloss: 0.212205
[9400]	valid_set's binary_logloss: 0.212225
[9450]	valid_set's binary_logloss: 0.212212
[9500]	valid_set's binary_logloss: 0.212213
[9550]	valid_set's binary_logloss: 0.212205
[9600]	valid_set's binary_logloss: 0.212219
[9650]	valid_set's binary_logloss: 0.212217
[9700]	valid_set's binary_logloss: 0.212205
[9750]	valid_set's binary_logloss: 0.212202
[9800]	valid_set's binary_logloss: 0.212215
[9850]	valid_set's binary_logloss: 0.212211
[9900]	valid_set's binary_logloss: 0.212192
[9950]	valid_set's binary_logloss: 0.212171
[10000]	valid_set's binary_logloss: 0.212153

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.302225
[100]	valid_set's binary_logloss: 0.276446
[150]	valid_set's binary_logloss: 0.264887
[200]	valid_set's binary_logloss: 0.257743
[250]	valid_set's binary_logloss: 0.252718
[300]	valid_set's binary_logloss: 0.249236
[350]	valid_set's binary_logloss: 0.246281
[400]	valid_set's binary_logloss: 0.24389
[450]	valid_set's binary_logloss: 0.242029
[500]	valid_set's binary_logloss: 0.240223
[550]	valid_set's binary_logloss: 0.238731
[600]	valid_set's binary_logloss: 0.237342
[650]	valid_set's binary_logloss: 0.236222
[700]	valid_set's binary_logloss: 0.235104
[750]	valid_set's binary_logloss: 0.234182
[800]	valid_set's binary_logloss: 0.233317
[850]	valid_set's binary_logloss: 0.232641
[900]	valid_set's binary_logloss: 0.231871
[950]	valid_set's binary_logloss: 0.231216
[1000]	valid_set's binary_logloss: 0.23063
[1050]	valid_set's binary_logloss: 0.230033
[1100]	valid_set's binary_logloss: 0.229492
[1150]	valid_set's binary_logloss: 0.228973
[1200]	valid_set's binary_logloss: 0.228491
[1250]	valid_set's binary_logloss: 0.228037
[1300]	valid_set's binary_logloss: 0.227583
[1350]	valid_set's binary_logloss: 0.22721
[1400]	valid_set's binary_logloss: 0.226761
[1450]	valid_set's binary_logloss: 0.226354
[1500]	valid_set's binary_logloss: 0.226034
[1550]	valid_set's binary_logloss: 0.225704
[1600]	valid_set's binary_logloss: 0.225429
[1650]	valid_set's binary_logloss: 0.225078
[1700]	valid_set's binary_logloss: 0.224761
[1750]	valid_set's binary_logloss: 0.224455
[1800]	valid_set's binary_logloss: 0.224186
[1850]	valid_set's binary_logloss: 0.223894
[1900]	valid_set's binary_logloss: 0.223578
[1950]	valid_set's binary_logloss: 0.223291
[2000]	valid_set's binary_logloss: 0.223073
[2050]	valid_set's binary_logloss: 0.222819
[2100]	valid_set's binary_logloss: 0.222597
[2150]	valid_set's binary_logloss: 0.222422
[2200]	valid_set's binary_logloss: 0.222137
[2250]	valid_set's binary_logloss: 0.22196
[2300]	valid_set's binary_logloss: 0.221764
[2350]	valid_set's binary_logloss: 0.221556
[2400]	valid_set's binary_logloss: 0.221415
[2450]	valid_set's binary_logloss: 0.221213
[2500]	valid_set's binary_logloss: 0.221028
[2550]	valid_set's binary_logloss: 0.22083
[2600]	valid_set's binary_logloss: 0.22066
[2650]	valid_set's binary_logloss: 0.22051
[2700]	valid_set's binary_logloss: 0.220344
[2750]	valid_set's binary_logloss: 0.220183
[2800]	valid_set's binary_logloss: 0.220024
[2850]	valid_set's binary_logloss: 0.219877
[2900]	valid_set's binary_logloss: 0.21974
[2950]	valid_set's binary_logloss: 0.219612
[3000]	valid_set's binary_logloss: 0.21949
[3050]	valid_set's binary_logloss: 0.21932
[3100]	valid_set's binary_logloss: 0.219209
[3150]	valid_set's binary_logloss: 0.219096
[3200]	valid_set's binary_logloss: 0.218962
[3250]	valid_set's binary_logloss: 0.218847
[3300]	valid_set's binary_logloss: 0.218769
[3350]	valid_set's binary_logloss: 0.218655
[3400]	valid_set's binary_logloss: 0.218546
[3450]	valid_set's binary_logloss: 0.218429
[3500]	valid_set's binary_logloss: 0.218319
[3550]	valid_set's binary_logloss: 0.218157
[3600]	valid_set's binary_logloss: 0.218059
[3650]	valid_set's binary_logloss: 0.21797
[3700]	valid_set's binary_logloss: 0.217886
[3750]	valid_set's binary_logloss: 0.21785
[3800]	valid_set's binary_logloss: 0.217807
[3850]	valid_set's binary_logloss: 0.217684
[3900]	valid_set's binary_logloss: 0.217596
[3950]	valid_set's binary_logloss: 0.217497
[4000]	valid_set's binary_logloss: 0.217403
[4050]	valid_set's binary_logloss: 0.217306
[4100]	valid_set's binary_logloss: 0.217241
[4150]	valid_set's binary_logloss: 0.217149
[4200]	valid_set's binary_logloss: 0.21708
[4250]	valid_set's binary_logloss: 0.217021
[4300]	valid_set's binary_logloss: 0.216955
[4350]	valid_set's binary_logloss: 0.216876
[4400]	valid_set's binary_logloss: 0.216825
[4450]	valid_set's binary_logloss: 0.216749
[4500]	valid_set's binary_logloss: 0.21667
[4550]	valid_set's binary_logloss: 0.216603
[4600]	valid_set's binary_logloss: 0.216544
[4650]	valid_set's binary_logloss: 0.216469
[4700]	valid_set's binary_logloss: 0.216408
[4750]	valid_set's binary_logloss: 0.216332
[4800]	valid_set's binary_logloss: 0.216235
[4850]	valid_set's binary_logloss: 0.216184
[4900]	valid_set's binary_logloss: 0.21616
[4950]	valid_set's binary_logloss: 0.216125
[5000]	valid_set's binary_logloss: 0.216079
[5050]	valid_set's binary_logloss: 0.216038
[5100]	valid_set's binary_logloss: 0.215997
[5150]	valid_set's binary_logloss: 0.215939
[5200]	valid_set's binary_logloss: 0.215897
[5250]	valid_set's binary_logloss: 0.215871
[5300]	valid_set's binary_logloss: 0.215808
[5350]	valid_set's binary_logloss: 0.215716
[5400]	valid_set's binary_logloss: 0.215683
[5450]	valid_set's binary_logloss: 0.215661
[5500]	valid_set's binary_logloss: 0.215628
[5550]	valid_set's binary_logloss: 0.215581
[5600]	valid_set's binary_logloss: 0.215528
[5650]	valid_set's binary_logloss: 0.215475
[5700]	valid_set's binary_logloss: 0.21544
[5750]	valid_set's binary_logloss: 0.215409
[5800]	valid_set's binary_logloss: 0.215374
[5850]	valid_set's binary_logloss: 0.215356
[5900]	valid_set's binary_logloss: 0.21532
[5950]	valid_set's binary_logloss: 0.215292
[6000]	valid_set's binary_logloss: 0.21525
[6050]	valid_set's binary_logloss: 0.21522
[6100]	valid_set's binary_logloss: 0.215202
[6150]	valid_set's binary_logloss: 0.215164
[6200]	valid_set's binary_logloss: 0.215136
[6250]	valid_set's binary_logloss: 0.215074
[6300]	valid_set's binary_logloss: 0.215058
[6350]	valid_set's binary_logloss: 0.215029
[6400]	valid_set's binary_logloss: 0.21501
[6450]	valid_set's binary_logloss: 0.214989
[6500]	valid_set's binary_logloss: 0.214982
[6550]	valid_set's binary_logloss: 0.214936
[6600]	valid_set's binary_logloss: 0.214893
[6650]	valid_set's binary_logloss: 0.214845
[6700]	valid_set's binary_logloss: 0.21482
[6750]	valid_set's binary_logloss: 0.214779
[6800]	valid_set's binary_logloss: 0.214777
[6850]	valid_set's binary_logloss: 0.214746
[6900]	valid_set's binary_logloss: 0.214707
[6950]	valid_set's binary_logloss: 0.214697
[7000]	valid_set's binary_logloss: 0.214663
[7050]	valid_set's binary_logloss: 0.21467
[7100]	valid_set's binary_logloss: 0.214663
[7150]	valid_set's binary_logloss: 0.214638
[7200]	valid_set's binary_logloss: 0.214632
[7250]	valid_set's binary_logloss: 0.214602
[7300]	valid_set's binary_logloss: 0.214543
[7350]	valid_set's binary_logloss: 0.214513
[7400]	valid_set's binary_logloss: 0.21449
[7450]	valid_set's binary_logloss: 0.214465
[7500]	valid_set's binary_logloss: 0.214459
[7550]	valid_set's binary_logloss: 0.214441
[7600]	valid_set's binary_logloss: 0.214417
[7650]	valid_set's binary_logloss: 0.214393
[7700]	valid_set's binary_logloss: 0.214368
[7750]	valid_set's binary_logloss: 0.214346
[7800]	valid_set's binary_logloss: 0.214308
[7850]	valid_set's binary_logloss: 0.214277
[7900]	valid_set's binary_logloss: 0.214274
[7950]	valid_set's binary_logloss: 0.214277
[8000]	valid_set's binary_logloss: 0.214243
[8050]	valid_set's binary_logloss: 0.214221
[8100]	valid_set's binary_logloss: 0.21421
[8150]	valid_set's binary_logloss: 0.214164
[8200]	valid_set's binary_logloss: 0.214143
[8250]	valid_set's binary_logloss: 0.214145
[8300]	valid_set's binary_logloss: 0.214125
[8350]	valid_set's binary_logloss: 0.214102
[8400]	valid_set's binary_logloss: 0.214091
[8450]	valid_set's binary_logloss: 0.214088
[8500]	valid_set's binary_logloss: 0.214096
[8550]	valid_set's binary_logloss: 0.214087
[8600]	valid_set's binary_logloss: 0.214068
[8650]	valid_set's binary_logloss: 0.214063
[8700]	valid_set's binary_logloss: 0.21405
[8750]	valid_set's binary_logloss: 0.21404
[8800]	valid_set's binary_logloss: 0.214017
[8850]	valid_set's binary_logloss: 0.214018
[8900]	valid_set's binary_logloss: 0.214017
[8950]	valid_set's binary_logloss: 0.213975
[9000]	valid_set's binary_logloss: 0.21394
[9050]	valid_set's binary_logloss: 0.213931
[9100]	valid_set's binary_logloss: 0.213921
[9150]	valid_set's binary_logloss: 0.213938
[9200]	valid_set's binary_logloss: 0.213933
[9250]	valid_set's binary_logloss: 0.213915
[9300]	valid_set's binary_logloss: 0.213924
[9350]	valid_set's binary_logloss: 0.213911
[9400]	valid_set's binary_logloss: 0.213914
[9450]	valid_set's binary_logloss: 0.213953
[9500]	valid_set's binary_logloss: 0.213948
[9550]	valid_set's binary_logloss: 0.213961
[9600]	valid_set's binary_logloss: 0.213942
[9650]	valid_set's binary_logloss: 0.213919
[9700]	valid_set's binary_logloss: 0.213905
[9750]	valid_set's binary_logloss: 0.213885
[9800]	valid_set's binary_logloss: 0.21385
[9850]	valid_set's binary_logloss: 0.213849
[9900]	valid_set's binary_logloss: 0.213853
[9950]	valid_set's binary_logloss: 0.213824
[10000]	valid_set's binary_logloss: 0.213791

	Fit constraints were validated upstream on the full training data, skipping...
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0, 'device': 'gpu'}
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu

[50]	valid_set's binary_logloss: 0.303216
[100]	valid_set's binary_logloss: 0.274106
[150]	valid_set's binary_logloss: 0.26239
[200]	valid_set's binary_logloss: 0.255607
[250]	valid_set's binary_logloss: 0.250828
[300]	valid_set's binary_logloss: 0.247362
[350]	valid_set's binary_logloss: 0.244608
[400]	valid_set's binary_logloss: 0.242182
[450]	valid_set's binary_logloss: 0.240143
[500]	valid_set's binary_logloss: 0.238142
[550]	valid_set's binary_logloss: 0.236597
[600]	valid_set's binary_logloss: 0.235356
[650]	valid_set's binary_logloss: 0.234189
[700]	valid_set's binary_logloss: 0.232993
[750]	valid_set's binary_logloss: 0.232051
[800]	valid_set's binary_logloss: 0.231133
[850]	valid_set's binary_logloss: 0.230276
[900]	valid_set's binary_logloss: 0.229585
[950]	valid_set's binary_logloss: 0.228747
[1000]	valid_set's binary_logloss: 0.228164
[1050]	valid_set's binary_logloss: 0.227524
[1100]	valid_set's binary_logloss: 0.226942
[1150]	valid_set's binary_logloss: 0.226412
[1200]	valid_set's binary_logloss: 0.226009
[1250]	valid_set's binary_logloss: 0.225543
[1300]	valid_set's binary_logloss: 0.22509
[1350]	valid_set's binary_logloss: 0.224602
[1400]	valid_set's binary_logloss: 0.224186
[1450]	valid_set's binary_logloss: 0.223789
[1500]	valid_set's binary_logloss: 0.223412
[1550]	valid_set's binary_logloss: 0.223093
[1600]	valid_set's binary_logloss: 0.222781
[1650]	valid_set's binary_logloss: 0.222519
[1700]	valid_set's binary_logloss: 0.222201
[1750]	valid_set's binary_logloss: 0.221918
[1800]	valid_set's binary_logloss: 0.221628
[1850]	valid_set's binary_logloss: 0.221349
[1900]	valid_set's binary_logloss: 0.221065
[1950]	valid_set's binary_logloss: 0.220777
[2000]	valid_set's binary_logloss: 0.220532
[2050]	valid_set's binary_logloss: 0.220287
[2100]	valid_set's binary_logloss: 0.22004
[2150]	valid_set's binary_logloss: 0.219809
[2200]	valid_set's binary_logloss: 0.219608
[2250]	valid_set's binary_logloss: 0.219461
[2300]	valid_set's binary_logloss: 0.219313
[2350]	valid_set's binary_logloss: 0.219142
[2400]	valid_set's binary_logloss: 0.218987
[2450]	valid_set's binary_logloss: 0.218805
[2500]	valid_set's binary_logloss: 0.218623
[2550]	valid_set's binary_logloss: 0.218432
[2600]	valid_set's binary_logloss: 0.218281
[2650]	valid_set's binary_logloss: 0.218124
[2700]	valid_set's binary_logloss: 0.21794
[2750]	valid_set's binary_logloss: 0.217742
[2800]	valid_set's binary_logloss: 0.217559
[2850]	valid_set's binary_logloss: 0.217427
[2900]	valid_set's binary_logloss: 0.217194
[2950]	valid_set's binary_logloss: 0.217052
[3000]	valid_set's binary_logloss: 0.216895
[3050]	valid_set's binary_logloss: 0.216755
[3100]	valid_set's binary_logloss: 0.216612
[3150]	valid_set's binary_logloss: 0.216504
[3200]	valid_set's binary_logloss: 0.216384
[3250]	valid_set's binary_logloss: 0.216278
[3300]	valid_set's binary_logloss: 0.216166
[3350]	valid_set's binary_logloss: 0.216008
[3400]	valid_set's binary_logloss: 0.215871
[3450]	valid_set's binary_logloss: 0.215749
[3500]	valid_set's binary_logloss: 0.215645
[3550]	valid_set's binary_logloss: 0.215556
[3600]	valid_set's binary_logloss: 0.215471
[3650]	valid_set's binary_logloss: 0.215361
[3700]	valid_set's binary_logloss: 0.215296
[3750]	valid_set's binary_logloss: 0.21518
[3800]	valid_set's binary_logloss: 0.215103
[3850]	valid_set's binary_logloss: 0.215023
[3900]	valid_set's binary_logloss: 0.214872
[3950]	valid_set's binary_logloss: 0.21474
[4000]	valid_set's binary_logloss: 0.2146
[4050]	valid_set's binary_logloss: 0.214512
[4100]	valid_set's binary_logloss: 0.214427
[4150]	valid_set's binary_logloss: 0.214282
[4200]	valid_set's binary_logloss: 0.214209
[4250]	valid_set's binary_logloss: 0.214139
[4300]	valid_set's binary_logloss: 0.214098
[4350]	valid_set's binary_logloss: 0.214038
[4400]	valid_set's binary_logloss: 0.213999
[4450]	valid_set's binary_logloss: 0.213895
[4500]	valid_set's binary_logloss: 0.213785
[4550]	valid_set's binary_logloss: 0.213742
[4600]	valid_set's binary_logloss: 0.213685
[4650]	valid_set's binary_logloss: 0.21361
[4700]	valid_set's binary_logloss: 0.213576
[4750]	valid_set's binary_logloss: 0.213491
[4800]	valid_set's binary_logloss: 0.213432
[4850]	valid_set's binary_logloss: 0.213331
[4900]	valid_set's binary_logloss: 0.21325
[4950]	valid_set's binary_logloss: 0.213189
[5000]	valid_set's binary_logloss: 0.213106
[5050]	valid_set's binary_logloss: 0.213038
[5100]	valid_set's binary_logloss: 0.212998
[5150]	valid_set's binary_logloss: 0.21294
[5200]	valid_set's binary_logloss: 0.212852
[5250]	valid_set's binary_logloss: 0.212808
[5300]	valid_set's binary_logloss: 0.21275
[5350]	valid_set's binary_logloss: 0.212713
[5400]	valid_set's binary_logloss: 0.212672
[5450]	valid_set's binary_logloss: 0.212597
[5500]	valid_set's binary_logloss: 0.212527
[5550]	valid_set's binary_logloss: 0.212481
[5600]	valid_set's binary_logloss: 0.212443
[5650]	valid_set's binary_logloss: 0.212371
[5700]	valid_set's binary_logloss: 0.212322
[5750]	valid_set's binary_logloss: 0.212249
[5800]	valid_set's binary_logloss: 0.212191
[5850]	valid_set's binary_logloss: 0.212165
[5900]	valid_set's binary_logloss: 0.212133
[5950]	valid_set's binary_logloss: 0.212128
[6000]	valid_set's binary_logloss: 0.212078
[6050]	valid_set's binary_logloss: 0.212021
[6100]	valid_set's binary_logloss: 0.211985
[6150]	valid_set's binary_logloss: 0.211942
[6200]	valid_set's binary_logloss: 0.211901
[6250]	valid_set's binary_logloss: 0.211864
[6300]	valid_set's binary_logloss: 0.21181
[6350]	valid_set's binary_logloss: 0.211772
[6400]	valid_set's binary_logloss: 0.211736
[6450]	valid_set's binary_logloss: 0.211653
[6500]	valid_set's binary_logloss: 0.211624
[6550]	valid_set's binary_logloss: 0.211597
[6600]	valid_set's binary_logloss: 0.21153
[6650]	valid_set's binary_logloss: 0.211503
[6700]	valid_set's binary_logloss: 0.211513
[6750]	valid_set's binary_logloss: 0.21147
[6800]	valid_set's binary_logloss: 0.211449
[6850]	valid_set's binary_logloss: 0.211444
[6900]	valid_set's binary_logloss: 0.211402
[6950]	valid_set's binary_logloss: 0.211355
[7000]	valid_set's binary_logloss: 0.211304
[7050]	valid_set's binary_logloss: 0.211288
[7100]	valid_set's binary_logloss: 0.211292
[7150]	valid_set's binary_logloss: 0.21128
[7200]	valid_set's binary_logloss: 0.211257
[7250]	valid_set's binary_logloss: 0.211222
[7300]	valid_set's binary_logloss: 0.211176
[7350]	valid_set's binary_logloss: 0.211163
[7400]	valid_set's binary_logloss: 0.211143
[7450]	valid_set's binary_logloss: 0.211131
[7500]	valid_set's binary_logloss: 0.211079
[7550]	valid_set's binary_logloss: 0.211073
[7600]	valid_set's binary_logloss: 0.211036
[7650]	valid_set's binary_logloss: 0.211031
[7700]	valid_set's binary_logloss: 0.210996
[7750]	valid_set's binary_logloss: 0.21101
[7800]	valid_set's binary_logloss: 0.210991
[7850]	valid_set's binary_logloss: 0.210966
[7900]	valid_set's binary_logloss: 0.210945
[7950]	valid_set's binary_logloss: 0.210944
[8000]	valid_set's binary_logloss: 0.21096
[8050]	valid_set's binary_logloss: 0.210936
[8100]	valid_set's binary_logloss: 0.210914
[8150]	valid_set's binary_logloss: 0.210927
[8200]	valid_set's binary_logloss: 0.21092
[8250]	valid_set's binary_logloss: 0.210911
[8300]	valid_set's binary_logloss: 0.21087
[8350]	valid_set's binary_logloss: 0.210834
[8400]	valid_set's binary_logloss: 0.210834
[8450]	valid_set's binary_logloss: 0.210808
[8500]	valid_set's binary_logloss: 0.210796
[8550]	valid_set's binary_logloss: 0.210776
[8600]	valid_set's binary_logloss: 0.210779
[8650]	valid_set's binary_logloss: 0.210757
[8700]	valid_set's binary_logloss: 0.210737
[8750]	valid_set's binary_logloss: 0.210697
[8800]	valid_set's binary_logloss: 0.210667
[8850]	valid_set's binary_logloss: 0.210642
[8900]	valid_set's binary_logloss: 0.210637
[8950]	valid_set's binary_logloss: 0.210631
[9000]	valid_set's binary_logloss: 0.210626
[9050]	valid_set's binary_logloss: 0.210644
[9100]	valid_set's binary_logloss: 0.210635
[9150]	valid_set's binary_logloss: 0.210612
[9200]	valid_set's binary_logloss: 0.210599
[9250]	valid_set's binary_logloss: 0.210593
[9300]	valid_set's binary_logloss: 0.210561
[9350]	valid_set's binary_logloss: 0.210559
[9400]	valid_set's binary_logloss: 0.210549
[9450]	valid_set's binary_logloss: 0.210547
[9500]	valid_set's binary_logloss: 0.210541
[9550]	valid_set's binary_logloss: 0.210522
[9600]	valid_set's binary_logloss: 0.210504
[9650]	valid_set's binary_logloss: 0.210487
[9700]	valid_set's binary_logloss: 0.210485
[9750]	valid_set's binary_logloss: 0.21047
[9800]	valid_set's binary_logloss: 0.21048
[9850]	valid_set's binary_logloss: 0.210453
[9900]	valid_set's binary_logloss: 0.210455
[9950]	valid_set's binary_logloss: 0.210456
[10000]	valid_set's binary_logloss: 0.210463

Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\model.pkl
	0.9569	 = Validation score   (roc_auc)
	296.35s	 = Training   runtime
	22.95s	 = Validation runtime
	2943.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 31853.52s of the 31853.52s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403844	test: 0.6404638	best: 0.6404638 (0)	total: 10ms	remaining: 10ms
1:	learn: 0.5954043	test: 0.5955182	best: 0.5955182 (1)	total: 19ms	remaining: 0us
bestTest = 0.595518209
bestIteration = 1
0:	learn: 0.6414673	test: 0.6415323	best: 0.6415323 (0)	total: 15.3ms	remaining: 1m 12s
20:	learn: 0.3419102	test: 0.3428234	best: 0.3428234 (20)	total: 316ms	remaining: 1m 10s
40:	learn: 0.3096303	test: 0.3105558	best: 0.3105558 (40)	total: 625ms	remaining: 1m 11s
60:	learn: 0.2968145	test: 0.2977843	best: 0.2977843 (60)	total: 932ms	remaining: 1m 11s
80:	learn: 0.2888585	test: 0.2896869	best: 0.2896869 (80)	total: 1.24s	remaining: 1m 11s
100:	learn: 0.2838984	test: 0.2847352	best: 0.2847352 (100)	total: 1.55s	remaining: 1m 10s
120:	learn: 0.2791284	test: 0.2798723	best: 0.2798723 (120)	total: 1.85s	remaining: 1m 10s
140:	learn: 0.2757711	test: 0.2764977	best: 0.2764977 (140)	total: 2.16s	remaining: 1m 10s
160:	learn: 0.2724604	test: 0.2733380	best: 0.2733380 (160)	total: 2.47s	remaining: 1m 10s
180:	learn: 0.2695698	test: 0.2704401	best: 0.2704401 (180)	total: 2.77s	remaining: 1m 9s
200:	learn: 0.2669149	test: 0.2678211	best: 0.2678211 (200)	total: 3.09s	remaining: 1m 9s
220:	learn: 0.2649719	test: 0.2659396	best: 0.2659396 (220)	total: 3.41s	remaining: 1m 9s
240:	learn: 0.2625425	test: 0.2635516	best: 0.2635516 (240)	total: 3.72s	remaining: 1m 9s
260:	learn: 0.2606344	test: 0.2617058	best: 0.2617058 (260)	total: 4.03s	remaining: 1m 8s
280:	learn: 0.2586970	test: 0.2598472	best: 0.2598472 (280)	total: 4.34s	remaining: 1m 8s
300:	learn: 0.2573282	test: 0.2585592	best: 0.2585592 (300)	total: 4.64s	remaining: 1m 8s
320:	learn: 0.2557683	test: 0.2571147	best: 0.2571147 (320)	total: 4.96s	remaining: 1m 8s
340:	learn: 0.2544748	test: 0.2558860	best: 0.2558860 (340)	total: 5.27s	remaining: 1m 7s
360:	learn: 0.2531894	test: 0.2546701	best: 0.2546701 (360)	total: 5.57s	remaining: 1m 7s
380:	learn: 0.2519296	test: 0.2534931	best: 0.2534931 (380)	total: 5.88s	remaining: 1m 7s
400:	learn: 0.2507673	test: 0.2524226	best: 0.2524226 (400)	total: 6.2s	remaining: 1m 6s
420:	learn: 0.2497037	test: 0.2514377	best: 0.2514377 (420)	total: 6.51s	remaining: 1m 6s
440:	learn: 0.2487141	test: 0.2505615	best: 0.2505615 (440)	total: 6.81s	remaining: 1m 6s
460:	learn: 0.2477563	test: 0.2497070	best: 0.2497070 (460)	total: 7.12s	remaining: 1m 5s
480:	learn: 0.2469316	test: 0.2489822	best: 0.2489822 (480)	total: 7.43s	remaining: 1m 5s
500:	learn: 0.2459781	test: 0.2480907	best: 0.2480907 (500)	total: 7.73s	remaining: 1m 5s
520:	learn: 0.2452584	test: 0.2474621	best: 0.2474621 (520)	total: 8.04s	remaining: 1m 4s
540:	learn: 0.2444888	test: 0.2467416	best: 0.2467416 (540)	total: 8.35s	remaining: 1m 4s
560:	learn: 0.2436922	test: 0.2460602	best: 0.2460602 (560)	total: 8.65s	remaining: 1m 4s
580:	learn: 0.2429607	test: 0.2454159	best: 0.2454159 (580)	total: 8.96s	remaining: 1m 3s
600:	learn: 0.2423169	test: 0.2448546	best: 0.2448546 (600)	total: 9.26s	remaining: 1m 3s
620:	learn: 0.2416055	test: 0.2442410	best: 0.2442410 (620)	total: 9.56s	remaining: 1m 3s
640:	learn: 0.2409584	test: 0.2437229	best: 0.2437229 (640)	total: 9.87s	remaining: 1m 2s
660:	learn: 0.2402791	test: 0.2431229	best: 0.2431229 (660)	total: 10.2s	remaining: 1m 2s
680:	learn: 0.2396285	test: 0.2425809	best: 0.2425809 (680)	total: 10.5s	remaining: 1m 2s
700:	learn: 0.2389797	test: 0.2419319	best: 0.2419319 (700)	total: 10.8s	remaining: 1m 1s
720:	learn: 0.2383339	test: 0.2413876	best: 0.2413876 (720)	total: 11.1s	remaining: 1m 1s
740:	learn: 0.2376761	test: 0.2408243	best: 0.2408243 (740)	total: 11.4s	remaining: 1m 1s
760:	learn: 0.2370269	test: 0.2402948	best: 0.2402948 (760)	total: 11.7s	remaining: 1m
780:	learn: 0.2364891	test: 0.2398762	best: 0.2398762 (780)	total: 12s	remaining: 1m
800:	learn: 0.2360037	test: 0.2394941	best: 0.2394941 (800)	total: 12.3s	remaining: 1m
820:	learn: 0.2355095	test: 0.2391235	best: 0.2391235 (820)	total: 12.6s	remaining: 60s
840:	learn: 0.2350134	test: 0.2387586	best: 0.2387586 (840)	total: 12.9s	remaining: 59.6s
860:	learn: 0.2345159	test: 0.2383451	best: 0.2383451 (860)	total: 13.2s	remaining: 59.3s
880:	learn: 0.2340494	test: 0.2380015	best: 0.2380015 (880)	total: 13.5s	remaining: 59s
900:	learn: 0.2336172	test: 0.2376288	best: 0.2376288 (900)	total: 13.8s	remaining: 58.7s
920:	learn: 0.2331522	test: 0.2372646	best: 0.2372646 (920)	total: 14.1s	remaining: 58.4s
940:	learn: 0.2327397	test: 0.2369568	best: 0.2369568 (940)	total: 14.4s	remaining: 58.1s
960:	learn: 0.2323555	test: 0.2366455	best: 0.2366455 (960)	total: 14.7s	remaining: 57.8s
980:	learn: 0.2319391	test: 0.2363354	best: 0.2363354 (980)	total: 15.1s	remaining: 57.5s
1000:	learn: 0.2314935	test: 0.2360410	best: 0.2360410 (1000)	total: 15.4s	remaining: 57.1s
1020:	learn: 0.2310649	test: 0.2357014	best: 0.2357014 (1020)	total: 15.7s	remaining: 56.8s
1040:	learn: 0.2306641	test: 0.2353911	best: 0.2353911 (1040)	total: 16s	remaining: 56.5s
1060:	learn: 0.2303272	test: 0.2351598	best: 0.2351598 (1060)	total: 16.3s	remaining: 56.2s
1080:	learn: 0.2299626	test: 0.2348857	best: 0.2348857 (1080)	total: 16.6s	remaining: 55.9s
1100:	learn: 0.2295848	test: 0.2345909	best: 0.2345909 (1100)	total: 16.9s	remaining: 55.6s
1120:	learn: 0.2292299	test: 0.2343427	best: 0.2343427 (1120)	total: 17.2s	remaining: 55.3s
1140:	learn: 0.2288601	test: 0.2341032	best: 0.2341032 (1140)	total: 17.5s	remaining: 54.9s
1160:	learn: 0.2284491	test: 0.2338124	best: 0.2338124 (1160)	total: 17.8s	remaining: 54.7s
1180:	learn: 0.2280736	test: 0.2335298	best: 0.2335298 (1180)	total: 18.1s	remaining: 54.3s
1200:	learn: 0.2277445	test: 0.2332926	best: 0.2332926 (1200)	total: 18.4s	remaining: 54s
1220:	learn: 0.2273771	test: 0.2330398	best: 0.2330398 (1220)	total: 18.7s	remaining: 53.7s
1240:	learn: 0.2270887	test: 0.2328301	best: 0.2328301 (1240)	total: 19s	remaining: 53.4s
1260:	learn: 0.2267637	test: 0.2326360	best: 0.2326360 (1260)	total: 19.3s	remaining: 53.1s
1280:	learn: 0.2264803	test: 0.2324388	best: 0.2324388 (1280)	total: 19.6s	remaining: 52.8s
1300:	learn: 0.2261854	test: 0.2322335	best: 0.2322335 (1300)	total: 19.9s	remaining: 52.4s
1320:	learn: 0.2258657	test: 0.2320150	best: 0.2320150 (1320)	total: 20.2s	remaining: 52.1s
1340:	learn: 0.2255200	test: 0.2317390	best: 0.2317390 (1340)	total: 20.5s	remaining: 51.8s
1360:	learn: 0.2252278	test: 0.2315220	best: 0.2315210 (1359)	total: 20.8s	remaining: 51.5s
1380:	learn: 0.2249050	test: 0.2313121	best: 0.2313121 (1380)	total: 21.1s	remaining: 51.2s
1400:	learn: 0.2245707	test: 0.2310878	best: 0.2310878 (1400)	total: 21.4s	remaining: 50.9s
1420:	learn: 0.2242968	test: 0.2309212	best: 0.2309212 (1420)	total: 21.8s	remaining: 50.6s
1440:	learn: 0.2240426	test: 0.2307706	best: 0.2307697 (1439)	total: 22.1s	remaining: 50.3s
1460:	learn: 0.2237598	test: 0.2305931	best: 0.2305931 (1460)	total: 22.4s	remaining: 50s
1480:	learn: 0.2235143	test: 0.2304489	best: 0.2304489 (1480)	total: 22.7s	remaining: 49.7s
1500:	learn: 0.2232952	test: 0.2303161	best: 0.2303161 (1500)	total: 23s	remaining: 49.4s
1520:	learn: 0.2229961	test: 0.2300814	best: 0.2300814 (1520)	total: 23.3s	remaining: 49s
1540:	learn: 0.2226894	test: 0.2298593	best: 0.2298593 (1540)	total: 23.6s	remaining: 48.7s
1560:	learn: 0.2223835	test: 0.2296446	best: 0.2296446 (1560)	total: 23.9s	remaining: 48.4s
1580:	learn: 0.2221124	test: 0.2294762	best: 0.2294762 (1580)	total: 24.2s	remaining: 48.1s
1600:	learn: 0.2218629	test: 0.2293174	best: 0.2293174 (1600)	total: 24.5s	remaining: 47.8s
1620:	learn: 0.2216050	test: 0.2291376	best: 0.2291376 (1620)	total: 24.8s	remaining: 47.5s
1640:	learn: 0.2213275	test: 0.2289230	best: 0.2289230 (1640)	total: 25.1s	remaining: 47.2s
1660:	learn: 0.2210930	test: 0.2287987	best: 0.2287987 (1660)	total: 25.4s	remaining: 46.9s
1680:	learn: 0.2208521	test: 0.2286500	best: 0.2286500 (1680)	total: 25.7s	remaining: 46.6s
1700:	learn: 0.2205910	test: 0.2284687	best: 0.2284687 (1700)	total: 26s	remaining: 46.3s
1720:	learn: 0.2203316	test: 0.2282963	best: 0.2282963 (1720)	total: 26.3s	remaining: 46s
1740:	learn: 0.2201092	test: 0.2281550	best: 0.2281550 (1740)	total: 26.6s	remaining: 45.7s
1760:	learn: 0.2198487	test: 0.2279901	best: 0.2279901 (1760)	total: 26.9s	remaining: 45.4s
1780:	learn: 0.2196012	test: 0.2278165	best: 0.2278165 (1780)	total: 27.3s	remaining: 45.1s
1800:	learn: 0.2193461	test: 0.2276654	best: 0.2276654 (1800)	total: 27.6s	remaining: 44.8s
1820:	learn: 0.2190867	test: 0.2274930	best: 0.2274930 (1820)	total: 27.9s	remaining: 44.5s
1840:	learn: 0.2188284	test: 0.2272987	best: 0.2272987 (1840)	total: 28.2s	remaining: 44.1s
1860:	learn: 0.2186186	test: 0.2271641	best: 0.2271641 (1860)	total: 28.5s	remaining: 43.8s
1880:	learn: 0.2183971	test: 0.2270177	best: 0.2270177 (1880)	total: 28.8s	remaining: 43.5s
1900:	learn: 0.2181370	test: 0.2268776	best: 0.2268776 (1900)	total: 29.1s	remaining: 43.2s
1920:	learn: 0.2179213	test: 0.2267612	best: 0.2267612 (1920)	total: 29.4s	remaining: 42.9s
1940:	learn: 0.2176884	test: 0.2266048	best: 0.2266048 (1940)	total: 29.7s	remaining: 42.6s
1960:	learn: 0.2174566	test: 0.2264576	best: 0.2264576 (1960)	total: 30s	remaining: 42.3s
1980:	learn: 0.2172724	test: 0.2263642	best: 0.2263642 (1980)	total: 30.3s	remaining: 42s
2000:	learn: 0.2170605	test: 0.2262658	best: 0.2262658 (2000)	total: 30.6s	remaining: 41.7s
2020:	learn: 0.2168469	test: 0.2261254	best: 0.2261254 (2020)	total: 30.9s	remaining: 41.4s
2040:	learn: 0.2166372	test: 0.2260121	best: 0.2260121 (2040)	total: 31.2s	remaining: 41.1s
2060:	learn: 0.2164637	test: 0.2259393	best: 0.2259393 (2060)	total: 31.5s	remaining: 40.8s
2080:	learn: 0.2162453	test: 0.2258404	best: 0.2258404 (2080)	total: 31.8s	remaining: 40.4s
2100:	learn: 0.2160265	test: 0.2257211	best: 0.2257169 (2099)	total: 32.1s	remaining: 40.1s
2120:	learn: 0.2158161	test: 0.2256179	best: 0.2256179 (2120)	total: 32.4s	remaining: 39.8s
2140:	learn: 0.2156126	test: 0.2255053	best: 0.2255053 (2140)	total: 32.7s	remaining: 39.5s
2160:	learn: 0.2154226	test: 0.2254305	best: 0.2254305 (2160)	total: 33s	remaining: 39.2s
2180:	learn: 0.2152307	test: 0.2253407	best: 0.2253407 (2180)	total: 33.3s	remaining: 38.9s
2200:	learn: 0.2150296	test: 0.2252422	best: 0.2252420 (2199)	total: 33.7s	remaining: 38.6s
2220:	learn: 0.2148164	test: 0.2251216	best: 0.2251216 (2220)	total: 34s	remaining: 38.3s
2240:	learn: 0.2146236	test: 0.2250248	best: 0.2250248 (2240)	total: 34.3s	remaining: 38s
2260:	learn: 0.2144185	test: 0.2249238	best: 0.2249238 (2260)	total: 34.6s	remaining: 37.7s
2280:	learn: 0.2142111	test: 0.2248124	best: 0.2248124 (2280)	total: 34.9s	remaining: 37.4s
2300:	learn: 0.2140218	test: 0.2247091	best: 0.2247091 (2300)	total: 35.2s	remaining: 37.1s
2320:	learn: 0.2138077	test: 0.2245786	best: 0.2245786 (2320)	total: 35.5s	remaining: 36.8s
2340:	learn: 0.2136141	test: 0.2244953	best: 0.2244953 (2340)	total: 35.8s	remaining: 36.5s
2360:	learn: 0.2134135	test: 0.2244012	best: 0.2244012 (2360)	total: 36.1s	remaining: 36.2s
2380:	learn: 0.2132256	test: 0.2243222	best: 0.2243222 (2380)	total: 36.4s	remaining: 35.9s
2400:	learn: 0.2130386	test: 0.2242471	best: 0.2242471 (2400)	total: 36.7s	remaining: 35.6s
2420:	learn: 0.2128581	test: 0.2241340	best: 0.2241340 (2420)	total: 37s	remaining: 35.3s
2440:	learn: 0.2126922	test: 0.2240758	best: 0.2240750 (2439)	total: 37.3s	remaining: 34.9s
2460:	learn: 0.2124966	test: 0.2239800	best: 0.2239800 (2460)	total: 37.6s	remaining: 34.6s
2480:	learn: 0.2122834	test: 0.2238692	best: 0.2238692 (2480)	total: 38s	remaining: 34.3s
2500:	learn: 0.2120938	test: 0.2237684	best: 0.2237684 (2500)	total: 38.3s	remaining: 34s
2520:	learn: 0.2119425	test: 0.2237237	best: 0.2237225 (2517)	total: 38.6s	remaining: 33.7s
2540:	learn: 0.2117451	test: 0.2236398	best: 0.2236398 (2540)	total: 38.9s	remaining: 33.4s
2560:	learn: 0.2115591	test: 0.2235583	best: 0.2235583 (2560)	total: 39.2s	remaining: 33.1s
2580:	learn: 0.2113850	test: 0.2234742	best: 0.2234742 (2580)	total: 39.5s	remaining: 32.8s
2600:	learn: 0.2112167	test: 0.2234067	best: 0.2234064 (2599)	total: 39.8s	remaining: 32.5s
2620:	learn: 0.2110170	test: 0.2233156	best: 0.2233156 (2620)	total: 40.1s	remaining: 32.2s
2640:	learn: 0.2108687	test: 0.2232412	best: 0.2232412 (2640)	total: 40.4s	remaining: 31.9s
2660:	learn: 0.2106810	test: 0.2231489	best: 0.2231489 (2660)	total: 40.7s	remaining: 31.6s
2680:	learn: 0.2105150	test: 0.2230501	best: 0.2230501 (2680)	total: 41s	remaining: 31.3s
2700:	learn: 0.2103429	test: 0.2229640	best: 0.2229640 (2700)	total: 41.3s	remaining: 31s
2720:	learn: 0.2101723	test: 0.2228926	best: 0.2228926 (2720)	total: 41.6s	remaining: 30.7s
2740:	learn: 0.2099824	test: 0.2227906	best: 0.2227906 (2740)	total: 41.9s	remaining: 30.4s
2760:	learn: 0.2098147	test: 0.2227331	best: 0.2227305 (2758)	total: 42.2s	remaining: 30.1s
2780:	learn: 0.2096385	test: 0.2226343	best: 0.2226343 (2780)	total: 42.5s	remaining: 29.8s
2800:	learn: 0.2094531	test: 0.2225273	best: 0.2225273 (2800)	total: 42.8s	remaining: 29.4s
2820:	learn: 0.2092686	test: 0.2224272	best: 0.2224272 (2820)	total: 43.1s	remaining: 29.1s
2840:	learn: 0.2091176	test: 0.2223526	best: 0.2223526 (2840)	total: 43.5s	remaining: 28.8s
2860:	learn: 0.2089662	test: 0.2222832	best: 0.2222808 (2859)	total: 43.8s	remaining: 28.5s
2880:	learn: 0.2088039	test: 0.2222118	best: 0.2222118 (2880)	total: 44.1s	remaining: 28.2s
2900:	learn: 0.2086603	test: 0.2221556	best: 0.2221556 (2900)	total: 44.4s	remaining: 27.9s
2920:	learn: 0.2084972	test: 0.2221101	best: 0.2221101 (2920)	total: 44.7s	remaining: 27.6s
2940:	learn: 0.2083360	test: 0.2220201	best: 0.2220201 (2940)	total: 45s	remaining: 27.3s
2960:	learn: 0.2081843	test: 0.2219641	best: 0.2219641 (2960)	total: 45.3s	remaining: 27s
2980:	learn: 0.2080360	test: 0.2219060	best: 0.2219060 (2980)	total: 45.6s	remaining: 26.7s
3000:	learn: 0.2078782	test: 0.2218580	best: 0.2218580 (3000)	total: 45.9s	remaining: 26.4s
3020:	learn: 0.2077202	test: 0.2217987	best: 0.2217987 (3020)	total: 46.2s	remaining: 26.1s
3040:	learn: 0.2075616	test: 0.2217332	best: 0.2217332 (3040)	total: 46.5s	remaining: 25.8s
3060:	learn: 0.2074215	test: 0.2216693	best: 0.2216693 (3060)	total: 46.8s	remaining: 25.5s
3080:	learn: 0.2072549	test: 0.2215690	best: 0.2215690 (3080)	total: 47.1s	remaining: 25.2s
3100:	learn: 0.2071106	test: 0.2215221	best: 0.2215221 (3100)	total: 47.4s	remaining: 24.9s
3120:	learn: 0.2069310	test: 0.2214675	best: 0.2214675 (3120)	total: 47.8s	remaining: 24.6s
3140:	learn: 0.2067788	test: 0.2214081	best: 0.2214081 (3140)	total: 48.1s	remaining: 24.3s
3160:	learn: 0.2066370	test: 0.2213569	best: 0.2213569 (3160)	total: 48.4s	remaining: 23.9s
3180:	learn: 0.2064911	test: 0.2212932	best: 0.2212932 (3180)	total: 48.7s	remaining: 23.6s
3200:	learn: 0.2063468	test: 0.2212509	best: 0.2212506 (3199)	total: 49s	remaining: 23.3s
3220:	learn: 0.2062045	test: 0.2211795	best: 0.2211795 (3220)	total: 49.3s	remaining: 23s
3240:	learn: 0.2060538	test: 0.2211237	best: 0.2211237 (3240)	total: 49.6s	remaining: 22.7s
3260:	learn: 0.2059178	test: 0.2210460	best: 0.2210460 (3260)	total: 49.9s	remaining: 22.4s
3280:	learn: 0.2057850	test: 0.2209938	best: 0.2209932 (3278)	total: 50.2s	remaining: 22.1s
3300:	learn: 0.2056358	test: 0.2209286	best: 0.2209286 (3300)	total: 50.5s	remaining: 21.8s
3320:	learn: 0.2054951	test: 0.2208680	best: 0.2208680 (3320)	total: 50.8s	remaining: 21.5s
3340:	learn: 0.2053598	test: 0.2208055	best: 0.2208055 (3340)	total: 51.1s	remaining: 21.2s
3360:	learn: 0.2052342	test: 0.2207431	best: 0.2207431 (3360)	total: 51.4s	remaining: 20.9s
3380:	learn: 0.2050666	test: 0.2206720	best: 0.2206720 (3380)	total: 51.7s	remaining: 20.6s
3400:	learn: 0.2049186	test: 0.2206121	best: 0.2206106 (3399)	total: 52s	remaining: 20.3s
3420:	learn: 0.2047500	test: 0.2205411	best: 0.2205411 (3420)	total: 52.4s	remaining: 20s
3440:	learn: 0.2045972	test: 0.2204716	best: 0.2204716 (3440)	total: 52.7s	remaining: 19.7s
3460:	learn: 0.2044678	test: 0.2204132	best: 0.2204132 (3460)	total: 53s	remaining: 19.4s
3480:	learn: 0.2043374	test: 0.2203676	best: 0.2203659 (3478)	total: 53.3s	remaining: 19.1s
3500:	learn: 0.2042010	test: 0.2203283	best: 0.2203283 (3500)	total: 53.6s	remaining: 18.8s
3520:	learn: 0.2040358	test: 0.2202627	best: 0.2202627 (3520)	total: 53.9s	remaining: 18.4s
3540:	learn: 0.2039031	test: 0.2202291	best: 0.2202291 (3540)	total: 54.2s	remaining: 18.1s
3560:	learn: 0.2037730	test: 0.2201782	best: 0.2201782 (3560)	total: 54.5s	remaining: 17.8s
3580:	learn: 0.2036449	test: 0.2201294	best: 0.2201294 (3580)	total: 54.8s	remaining: 17.5s
3600:	learn: 0.2035108	test: 0.2200969	best: 0.2200959 (3597)	total: 55.1s	remaining: 17.2s
3620:	learn: 0.2033795	test: 0.2200176	best: 0.2200176 (3620)	total: 55.4s	remaining: 16.9s
3640:	learn: 0.2032551	test: 0.2199732	best: 0.2199732 (3640)	total: 55.7s	remaining: 16.6s
3660:	learn: 0.2031205	test: 0.2199422	best: 0.2199422 (3660)	total: 56s	remaining: 16.3s
3680:	learn: 0.2029758	test: 0.2198940	best: 0.2198940 (3680)	total: 56.4s	remaining: 16s
3700:	learn: 0.2028241	test: 0.2198379	best: 0.2198379 (3700)	total: 56.7s	remaining: 15.7s
3720:	learn: 0.2026990	test: 0.2197993	best: 0.2197993 (3720)	total: 57s	remaining: 15.4s
3740:	learn: 0.2025523	test: 0.2197391	best: 0.2197391 (3740)	total: 57.3s	remaining: 15.1s
3760:	learn: 0.2023876	test: 0.2196548	best: 0.2196548 (3760)	total: 57.6s	remaining: 14.8s
3780:	learn: 0.2022665	test: 0.2196182	best: 0.2196182 (3780)	total: 57.9s	remaining: 14.5s
3800:	learn: 0.2021456	test: 0.2195783	best: 0.2195759 (3799)	total: 58.2s	remaining: 14.2s
3820:	learn: 0.2020208	test: 0.2195443	best: 0.2195439 (3819)	total: 58.5s	remaining: 13.9s
3840:	learn: 0.2018811	test: 0.2194961	best: 0.2194923 (3839)	total: 58.8s	remaining: 13.6s
3860:	learn: 0.2017409	test: 0.2194376	best: 0.2194376 (3860)	total: 59.1s	remaining: 13.2s
3880:	learn: 0.2016038	test: 0.2194027	best: 0.2194027 (3880)	total: 59.4s	remaining: 12.9s
3900:	learn: 0.2014669	test: 0.2193408	best: 0.2193408 (3900)	total: 59.7s	remaining: 12.6s
3920:	learn: 0.2013377	test: 0.2193158	best: 0.2193158 (3920)	total: 1m	remaining: 12.3s
3940:	learn: 0.2012119	test: 0.2192717	best: 0.2192717 (3940)	total: 1m	remaining: 12s
3960:	learn: 0.2010612	test: 0.2192116	best: 0.2192116 (3960)	total: 1m	remaining: 11.7s
3980:	learn: 0.2009311	test: 0.2191558	best: 0.2191558 (3980)	total: 1m	remaining: 11.4s
4000:	learn: 0.2007969	test: 0.2191118	best: 0.2191118 (4000)	total: 1m 1s	remaining: 11.1s
4020:	learn: 0.2006827	test: 0.2190721	best: 0.2190720 (4019)	total: 1m 1s	remaining: 10.8s
4040:	learn: 0.2005553	test: 0.2190223	best: 0.2190222 (4039)	total: 1m 1s	remaining: 10.5s
4060:	learn: 0.2004184	test: 0.2189695	best: 0.2189695 (4060)	total: 1m 2s	remaining: 10.2s
4080:	learn: 0.2003068	test: 0.2189250	best: 0.2189250 (4080)	total: 1m 2s	remaining: 9.88s
4100:	learn: 0.2001660	test: 0.2188857	best: 0.2188857 (4100)	total: 1m 2s	remaining: 9.57s
4120:	learn: 0.2000342	test: 0.2188215	best: 0.2188215 (4120)	total: 1m 3s	remaining: 9.27s
4140:	learn: 0.1999148	test: 0.2187914	best: 0.2187883 (4138)	total: 1m 3s	remaining: 8.96s
4160:	learn: 0.1997936	test: 0.2187403	best: 0.2187403 (4160)	total: 1m 3s	remaining: 8.66s
4180:	learn: 0.1996586	test: 0.2186906	best: 0.2186906 (4180)	total: 1m 4s	remaining: 8.35s
4200:	learn: 0.1995297	test: 0.2186593	best: 0.2186593 (4200)	total: 1m 4s	remaining: 8.04s
4220:	learn: 0.1994067	test: 0.2185995	best: 0.2185989 (4219)	total: 1m 4s	remaining: 7.74s
4240:	learn: 0.1992857	test: 0.2185700	best: 0.2185700 (4240)	total: 1m 4s	remaining: 7.43s
4260:	learn: 0.1991541	test: 0.2185326	best: 0.2185326 (4260)	total: 1m 5s	remaining: 7.13s
4280:	learn: 0.1990427	test: 0.2184983	best: 0.2184964 (4278)	total: 1m 5s	remaining: 6.82s
4300:	learn: 0.1989065	test: 0.2184579	best: 0.2184579 (4300)	total: 1m 5s	remaining: 6.51s
4320:	learn: 0.1987708	test: 0.2184211	best: 0.2184204 (4319)	total: 1m 6s	remaining: 6.21s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403339	test: 0.6405458	best: 0.6405458 (0)	total: 9.24ms	remaining: 9.24ms
1:	learn: 0.5953317	test: 0.5957325	best: 0.5957325 (1)	total: 17.9ms	remaining: 0us
bestTest = 0.5957324988
bestIteration = 1
0:	learn: 0.6411088	test: 0.6412504	best: 0.6412504 (0)	total: 15.1ms	remaining: 1m 10s
20:	learn: 0.3410161	test: 0.3425513	best: 0.3425513 (20)	total: 313ms	remaining: 1m 9s
40:	learn: 0.3085486	test: 0.3103319	best: 0.3103319 (40)	total: 617ms	remaining: 1m 9s
60:	learn: 0.2970054	test: 0.2989734	best: 0.2989734 (60)	total: 922ms	remaining: 1m 9s
80:	learn: 0.2892556	test: 0.2913708	best: 0.2913708 (80)	total: 1.23s	remaining: 1m 9s
100:	learn: 0.2836256	test: 0.2858956	best: 0.2858956 (100)	total: 1.53s	remaining: 1m 9s
120:	learn: 0.2794058	test: 0.2817791	best: 0.2817791 (120)	total: 1.84s	remaining: 1m 8s
140:	learn: 0.2757193	test: 0.2782169	best: 0.2782169 (140)	total: 2.16s	remaining: 1m 9s
160:	learn: 0.2726665	test: 0.2752830	best: 0.2752830 (160)	total: 2.48s	remaining: 1m 9s
180:	learn: 0.2698328	test: 0.2724498	best: 0.2724498 (180)	total: 2.79s	remaining: 1m 8s
200:	learn: 0.2668870	test: 0.2696052	best: 0.2696052 (200)	total: 3.09s	remaining: 1m 8s
220:	learn: 0.2641162	test: 0.2669763	best: 0.2669763 (220)	total: 3.4s	remaining: 1m 8s
240:	learn: 0.2620701	test: 0.2650552	best: 0.2650552 (240)	total: 3.71s	remaining: 1m 8s
260:	learn: 0.2605193	test: 0.2636372	best: 0.2636372 (260)	total: 4.02s	remaining: 1m 7s
280:	learn: 0.2589135	test: 0.2621178	best: 0.2621178 (280)	total: 4.32s	remaining: 1m 7s
300:	learn: 0.2572348	test: 0.2605072	best: 0.2605072 (300)	total: 4.63s	remaining: 1m 7s
320:	learn: 0.2558098	test: 0.2592533	best: 0.2592533 (320)	total: 4.93s	remaining: 1m 6s
340:	learn: 0.2545311	test: 0.2580157	best: 0.2580157 (340)	total: 5.24s	remaining: 1m 6s
360:	learn: 0.2531752	test: 0.2567076	best: 0.2567076 (360)	total: 5.55s	remaining: 1m 6s
380:	learn: 0.2519934	test: 0.2555423	best: 0.2555423 (380)	total: 5.86s	remaining: 1m 5s
400:	learn: 0.2506852	test: 0.2544063	best: 0.2544063 (400)	total: 6.16s	remaining: 1m 5s
420:	learn: 0.2497357	test: 0.2535744	best: 0.2535744 (420)	total: 6.47s	remaining: 1m 5s
440:	learn: 0.2488512	test: 0.2527317	best: 0.2527317 (440)	total: 6.77s	remaining: 1m 4s
460:	learn: 0.2480494	test: 0.2519968	best: 0.2519968 (460)	total: 7.07s	remaining: 1m 4s
480:	learn: 0.2470194	test: 0.2510331	best: 0.2510331 (480)	total: 7.38s	remaining: 1m 4s
500:	learn: 0.2458017	test: 0.2498875	best: 0.2498875 (500)	total: 7.7s	remaining: 1m 3s
520:	learn: 0.2449176	test: 0.2491040	best: 0.2491040 (520)	total: 8s	remaining: 1m 3s
540:	learn: 0.2441995	test: 0.2485109	best: 0.2485109 (540)	total: 8.3s	remaining: 1m 3s
560:	learn: 0.2434124	test: 0.2478264	best: 0.2478264 (560)	total: 8.61s	remaining: 1m 2s
580:	learn: 0.2426526	test: 0.2471819	best: 0.2471819 (580)	total: 8.91s	remaining: 1m 2s
600:	learn: 0.2418509	test: 0.2465167	best: 0.2465167 (600)	total: 9.22s	remaining: 1m 2s
620:	learn: 0.2412027	test: 0.2459038	best: 0.2459038 (620)	total: 9.53s	remaining: 1m 1s
640:	learn: 0.2406141	test: 0.2454110	best: 0.2454110 (640)	total: 9.83s	remaining: 1m 1s
660:	learn: 0.2399497	test: 0.2448155	best: 0.2448155 (660)	total: 10.1s	remaining: 1m 1s
680:	learn: 0.2393605	test: 0.2442872	best: 0.2442872 (680)	total: 10.4s	remaining: 1m
700:	learn: 0.2387751	test: 0.2438271	best: 0.2438271 (700)	total: 10.7s	remaining: 1m
720:	learn: 0.2381840	test: 0.2433292	best: 0.2433292 (720)	total: 11.1s	remaining: 1m
740:	learn: 0.2375573	test: 0.2428060	best: 0.2428060 (740)	total: 11.4s	remaining: 1m
760:	learn: 0.2370849	test: 0.2424359	best: 0.2424359 (760)	total: 11.7s	remaining: 59.8s
780:	learn: 0.2365483	test: 0.2419774	best: 0.2419774 (780)	total: 12s	remaining: 59.4s
800:	learn: 0.2359891	test: 0.2414879	best: 0.2414879 (800)	total: 12.3s	remaining: 59.1s
820:	learn: 0.2354392	test: 0.2410274	best: 0.2410274 (820)	total: 12.6s	remaining: 58.8s
840:	learn: 0.2348906	test: 0.2405406	best: 0.2405406 (840)	total: 12.9s	remaining: 58.5s
860:	learn: 0.2344133	test: 0.2401393	best: 0.2401393 (860)	total: 13.2s	remaining: 58.2s
880:	learn: 0.2340072	test: 0.2397905	best: 0.2397905 (880)	total: 13.5s	remaining: 57.9s
900:	learn: 0.2335007	test: 0.2393673	best: 0.2393673 (900)	total: 13.8s	remaining: 57.6s
920:	learn: 0.2330812	test: 0.2390335	best: 0.2390335 (920)	total: 14.1s	remaining: 57.2s
940:	learn: 0.2326481	test: 0.2386776	best: 0.2386776 (940)	total: 14.4s	remaining: 56.9s
960:	learn: 0.2322089	test: 0.2383467	best: 0.2383467 (960)	total: 14.7s	remaining: 56.6s
980:	learn: 0.2317730	test: 0.2380137	best: 0.2380137 (980)	total: 15s	remaining: 56.2s
1000:	learn: 0.2312522	test: 0.2375472	best: 0.2375472 (1000)	total: 15.3s	remaining: 56s
1020:	learn: 0.2309043	test: 0.2372674	best: 0.2372674 (1020)	total: 15.6s	remaining: 55.7s
1040:	learn: 0.2304895	test: 0.2369501	best: 0.2369501 (1040)	total: 15.9s	remaining: 55.3s
1060:	learn: 0.2300971	test: 0.2366043	best: 0.2366043 (1060)	total: 16.2s	remaining: 55.1s
1080:	learn: 0.2297573	test: 0.2363475	best: 0.2363475 (1080)	total: 16.5s	remaining: 54.8s
1100:	learn: 0.2294159	test: 0.2360923	best: 0.2360923 (1100)	total: 16.9s	remaining: 54.4s
1120:	learn: 0.2291172	test: 0.2359020	best: 0.2359020 (1120)	total: 17.2s	remaining: 54.2s
1140:	learn: 0.2287719	test: 0.2356478	best: 0.2356478 (1140)	total: 17.5s	remaining: 53.8s
1160:	learn: 0.2284123	test: 0.2354014	best: 0.2354014 (1160)	total: 17.8s	remaining: 53.5s
1180:	learn: 0.2280580	test: 0.2351789	best: 0.2351789 (1180)	total: 18.1s	remaining: 53.2s
1200:	learn: 0.2277505	test: 0.2349766	best: 0.2349766 (1200)	total: 18.4s	remaining: 52.9s
1220:	learn: 0.2273386	test: 0.2346307	best: 0.2346307 (1220)	total: 18.7s	remaining: 52.6s
1240:	learn: 0.2270478	test: 0.2344414	best: 0.2344414 (1240)	total: 19s	remaining: 52.3s
1260:	learn: 0.2267147	test: 0.2341965	best: 0.2341965 (1260)	total: 19.3s	remaining: 52s
1280:	learn: 0.2263808	test: 0.2338993	best: 0.2338993 (1280)	total: 19.6s	remaining: 51.7s
1300:	learn: 0.2260364	test: 0.2336802	best: 0.2336802 (1300)	total: 19.9s	remaining: 51.4s
1320:	learn: 0.2257476	test: 0.2334712	best: 0.2334712 (1320)	total: 20.2s	remaining: 51.1s
1340:	learn: 0.2254831	test: 0.2333007	best: 0.2333007 (1340)	total: 20.5s	remaining: 50.8s
1360:	learn: 0.2251525	test: 0.2330596	best: 0.2330596 (1360)	total: 20.8s	remaining: 50.5s
1380:	learn: 0.2248482	test: 0.2328405	best: 0.2328405 (1380)	total: 21.1s	remaining: 50.1s
1400:	learn: 0.2246010	test: 0.2326855	best: 0.2326855 (1400)	total: 21.4s	remaining: 49.8s
1420:	learn: 0.2243117	test: 0.2324903	best: 0.2324903 (1420)	total: 21.7s	remaining: 49.5s
1440:	learn: 0.2240178	test: 0.2322617	best: 0.2322617 (1440)	total: 22s	remaining: 49.2s
1460:	learn: 0.2237365	test: 0.2320809	best: 0.2320809 (1460)	total: 22.4s	remaining: 48.9s
1480:	learn: 0.2235076	test: 0.2319508	best: 0.2319508 (1480)	total: 22.7s	remaining: 48.6s
1500:	learn: 0.2231757	test: 0.2317033	best: 0.2317033 (1500)	total: 23s	remaining: 48.3s
1520:	learn: 0.2228884	test: 0.2315116	best: 0.2315116 (1520)	total: 23.3s	remaining: 48s
1540:	learn: 0.2226157	test: 0.2313468	best: 0.2313468 (1540)	total: 23.6s	remaining: 47.7s
1560:	learn: 0.2223713	test: 0.2311943	best: 0.2311943 (1560)	total: 23.9s	remaining: 47.4s
1580:	learn: 0.2221173	test: 0.2310333	best: 0.2310333 (1580)	total: 24.2s	remaining: 47.1s
1600:	learn: 0.2218425	test: 0.2308664	best: 0.2308664 (1600)	total: 24.5s	remaining: 46.8s
1620:	learn: 0.2216109	test: 0.2307210	best: 0.2307210 (1620)	total: 24.8s	remaining: 46.5s
1640:	learn: 0.2213578	test: 0.2305543	best: 0.2305543 (1640)	total: 25.1s	remaining: 46.2s
1660:	learn: 0.2211432	test: 0.2304293	best: 0.2304257 (1659)	total: 25.4s	remaining: 45.9s
1680:	learn: 0.2208775	test: 0.2302530	best: 0.2302530 (1680)	total: 25.8s	remaining: 45.6s
1700:	learn: 0.2206034	test: 0.2300621	best: 0.2300621 (1700)	total: 26.1s	remaining: 45.3s
1720:	learn: 0.2203615	test: 0.2299093	best: 0.2299093 (1720)	total: 26.4s	remaining: 45s
1740:	learn: 0.2201209	test: 0.2297431	best: 0.2297431 (1740)	total: 26.7s	remaining: 44.7s
1760:	learn: 0.2198844	test: 0.2296033	best: 0.2296033 (1760)	total: 27s	remaining: 44.4s
1780:	learn: 0.2196782	test: 0.2294830	best: 0.2294830 (1780)	total: 27.3s	remaining: 44.1s
1800:	learn: 0.2194557	test: 0.2293355	best: 0.2293355 (1800)	total: 27.6s	remaining: 43.8s
1820:	learn: 0.2192202	test: 0.2291699	best: 0.2291699 (1820)	total: 27.9s	remaining: 43.5s
1840:	learn: 0.2189815	test: 0.2290338	best: 0.2290338 (1840)	total: 28.2s	remaining: 43.2s
1860:	learn: 0.2187674	test: 0.2289237	best: 0.2289237 (1860)	total: 28.5s	remaining: 42.9s
1880:	learn: 0.2185553	test: 0.2287857	best: 0.2287857 (1880)	total: 28.8s	remaining: 42.6s
1900:	learn: 0.2182988	test: 0.2286268	best: 0.2286268 (1900)	total: 29.1s	remaining: 42.3s
1920:	learn: 0.2180936	test: 0.2284967	best: 0.2284967 (1920)	total: 29.4s	remaining: 41.9s
1940:	learn: 0.2178531	test: 0.2283462	best: 0.2283462 (1940)	total: 29.7s	remaining: 41.6s
1960:	learn: 0.2176341	test: 0.2282028	best: 0.2282028 (1960)	total: 30.1s	remaining: 41.3s
1980:	learn: 0.2174086	test: 0.2280645	best: 0.2280644 (1978)	total: 30.4s	remaining: 41s
2000:	learn: 0.2171786	test: 0.2279144	best: 0.2279144 (2000)	total: 30.7s	remaining: 40.7s
2020:	learn: 0.2169951	test: 0.2278058	best: 0.2278058 (2020)	total: 31s	remaining: 40.4s
2040:	learn: 0.2167937	test: 0.2277053	best: 0.2277053 (2040)	total: 31.3s	remaining: 40.1s
2060:	learn: 0.2165946	test: 0.2275962	best: 0.2275962 (2060)	total: 31.6s	remaining: 39.8s
2080:	learn: 0.2163762	test: 0.2274764	best: 0.2274764 (2080)	total: 31.9s	remaining: 39.5s
2100:	learn: 0.2161649	test: 0.2273504	best: 0.2273504 (2100)	total: 32.2s	remaining: 39.2s
2120:	learn: 0.2159621	test: 0.2272198	best: 0.2272198 (2120)	total: 32.5s	remaining: 38.9s
2140:	learn: 0.2157604	test: 0.2271048	best: 0.2271048 (2140)	total: 32.8s	remaining: 38.6s
2160:	learn: 0.2155318	test: 0.2269235	best: 0.2269235 (2160)	total: 33.1s	remaining: 38.3s
2180:	learn: 0.2153314	test: 0.2268323	best: 0.2268323 (2180)	total: 33.4s	remaining: 37.9s
2200:	learn: 0.2151099	test: 0.2266852	best: 0.2266852 (2200)	total: 33.7s	remaining: 37.6s
2220:	learn: 0.2149009	test: 0.2265586	best: 0.2265586 (2220)	total: 34s	remaining: 37.3s
2240:	learn: 0.2146734	test: 0.2264365	best: 0.2264365 (2240)	total: 34.3s	remaining: 37s
2260:	learn: 0.2144867	test: 0.2263557	best: 0.2263557 (2260)	total: 34.6s	remaining: 36.7s
2280:	learn: 0.2142822	test: 0.2262482	best: 0.2262472 (2279)	total: 34.9s	remaining: 36.4s
2300:	learn: 0.2140642	test: 0.2261123	best: 0.2261123 (2300)	total: 35.3s	remaining: 36.1s
2320:	learn: 0.2138244	test: 0.2259624	best: 0.2259624 (2320)	total: 35.6s	remaining: 35.8s
2340:	learn: 0.2136393	test: 0.2258556	best: 0.2258556 (2340)	total: 35.9s	remaining: 35.5s
2360:	learn: 0.2134699	test: 0.2257634	best: 0.2257634 (2360)	total: 36.2s	remaining: 35.2s
2380:	learn: 0.2132899	test: 0.2256664	best: 0.2256664 (2380)	total: 36.5s	remaining: 34.9s
2400:	learn: 0.2130872	test: 0.2255554	best: 0.2255536 (2399)	total: 36.8s	remaining: 34.6s
2420:	learn: 0.2129091	test: 0.2254296	best: 0.2254296 (2420)	total: 37.1s	remaining: 34.3s
2440:	learn: 0.2127124	test: 0.2253303	best: 0.2253303 (2440)	total: 37.4s	remaining: 34s
2460:	learn: 0.2125185	test: 0.2251988	best: 0.2251988 (2460)	total: 37.7s	remaining: 33.6s
2480:	learn: 0.2123200	test: 0.2250735	best: 0.2250705 (2478)	total: 38s	remaining: 33.3s
2500:	learn: 0.2121334	test: 0.2249896	best: 0.2249896 (2500)	total: 38.3s	remaining: 33s
2520:	learn: 0.2119361	test: 0.2248783	best: 0.2248783 (2520)	total: 38.6s	remaining: 32.7s
2540:	learn: 0.2117632	test: 0.2247916	best: 0.2247916 (2540)	total: 38.9s	remaining: 32.4s
2560:	learn: 0.2115867	test: 0.2246936	best: 0.2246936 (2560)	total: 39.2s	remaining: 32.1s
2580:	learn: 0.2114141	test: 0.2246134	best: 0.2246134 (2580)	total: 39.5s	remaining: 31.8s
2600:	learn: 0.2112240	test: 0.2245047	best: 0.2245047 (2600)	total: 39.8s	remaining: 31.5s
2620:	learn: 0.2110641	test: 0.2244368	best: 0.2244368 (2620)	total: 40.1s	remaining: 31.2s
2640:	learn: 0.2108833	test: 0.2243519	best: 0.2243519 (2640)	total: 40.4s	remaining: 30.9s
2660:	learn: 0.2107263	test: 0.2242757	best: 0.2242757 (2660)	total: 40.7s	remaining: 30.6s
2680:	learn: 0.2105458	test: 0.2241653	best: 0.2241653 (2680)	total: 41s	remaining: 30.3s
2700:	learn: 0.2103595	test: 0.2240675	best: 0.2240675 (2700)	total: 41.3s	remaining: 30s
2720:	learn: 0.2101841	test: 0.2239960	best: 0.2239960 (2720)	total: 41.6s	remaining: 29.6s
2740:	learn: 0.2100151	test: 0.2239204	best: 0.2239198 (2739)	total: 42s	remaining: 29.3s
2760:	learn: 0.2098557	test: 0.2238528	best: 0.2238496 (2758)	total: 42.3s	remaining: 29s
2780:	learn: 0.2096842	test: 0.2237626	best: 0.2237626 (2780)	total: 42.6s	remaining: 28.7s
2800:	learn: 0.2095124	test: 0.2236738	best: 0.2236738 (2800)	total: 42.9s	remaining: 28.4s
2820:	learn: 0.2093693	test: 0.2236050	best: 0.2236050 (2820)	total: 43.2s	remaining: 28.1s
2840:	learn: 0.2092356	test: 0.2235504	best: 0.2235504 (2840)	total: 43.5s	remaining: 27.8s
2860:	learn: 0.2090944	test: 0.2234915	best: 0.2234915 (2860)	total: 43.8s	remaining: 27.5s
2880:	learn: 0.2089499	test: 0.2234144	best: 0.2234144 (2880)	total: 44.1s	remaining: 27.2s
2900:	learn: 0.2087826	test: 0.2233554	best: 0.2233554 (2900)	total: 44.4s	remaining: 26.9s
2920:	learn: 0.2086336	test: 0.2233050	best: 0.2233050 (2920)	total: 44.7s	remaining: 26.6s
2940:	learn: 0.2084806	test: 0.2232617	best: 0.2232604 (2939)	total: 45.1s	remaining: 26.3s
2960:	learn: 0.2083121	test: 0.2231849	best: 0.2231832 (2957)	total: 45.4s	remaining: 26s
2980:	learn: 0.2081751	test: 0.2231370	best: 0.2231345 (2979)	total: 45.7s	remaining: 25.7s
3000:	learn: 0.2080051	test: 0.2230637	best: 0.2230637 (3000)	total: 46s	remaining: 25.4s
3020:	learn: 0.2078791	test: 0.2230219	best: 0.2230219 (3020)	total: 46.3s	remaining: 25.1s
3040:	learn: 0.2077027	test: 0.2229364	best: 0.2229364 (3040)	total: 46.6s	remaining: 24.8s
3060:	learn: 0.2075612	test: 0.2228654	best: 0.2228654 (3060)	total: 46.9s	remaining: 24.5s
3080:	learn: 0.2073906	test: 0.2227882	best: 0.2227882 (3080)	total: 47.2s	remaining: 24.2s
3100:	learn: 0.2072181	test: 0.2226956	best: 0.2226956 (3100)	total: 47.5s	remaining: 23.9s
3120:	learn: 0.2070691	test: 0.2226441	best: 0.2226441 (3120)	total: 47.8s	remaining: 23.6s
3140:	learn: 0.2069118	test: 0.2225827	best: 0.2225827 (3140)	total: 48.1s	remaining: 23.2s
3160:	learn: 0.2067676	test: 0.2225312	best: 0.2225312 (3160)	total: 48.4s	remaining: 22.9s
3180:	learn: 0.2065840	test: 0.2224742	best: 0.2224742 (3179)	total: 48.8s	remaining: 22.6s
3200:	learn: 0.2064299	test: 0.2224121	best: 0.2224121 (3200)	total: 49.1s	remaining: 22.3s
3220:	learn: 0.2062951	test: 0.2223439	best: 0.2223439 (3220)	total: 49.4s	remaining: 22s
3240:	learn: 0.2061420	test: 0.2222901	best: 0.2222901 (3240)	total: 49.7s	remaining: 21.7s
3260:	learn: 0.2059714	test: 0.2222124	best: 0.2222124 (3260)	total: 50s	remaining: 21.4s
3280:	learn: 0.2057999	test: 0.2221372	best: 0.2221372 (3280)	total: 50.3s	remaining: 21.1s
3300:	learn: 0.2056503	test: 0.2220833	best: 0.2220833 (3300)	total: 50.6s	remaining: 20.8s
3320:	learn: 0.2055125	test: 0.2220262	best: 0.2220252 (3319)	total: 50.9s	remaining: 20.5s
3340:	learn: 0.2053661	test: 0.2219708	best: 0.2219699 (3338)	total: 51.2s	remaining: 20.2s
3360:	learn: 0.2052232	test: 0.2218859	best: 0.2218859 (3360)	total: 51.5s	remaining: 19.9s
3380:	learn: 0.2050895	test: 0.2218257	best: 0.2218243 (3379)	total: 51.8s	remaining: 19.6s
3400:	learn: 0.2049465	test: 0.2217643	best: 0.2217643 (3400)	total: 52.2s	remaining: 19.3s
3420:	learn: 0.2048130	test: 0.2217104	best: 0.2217104 (3419)	total: 52.5s	remaining: 19s
3440:	learn: 0.2046579	test: 0.2216437	best: 0.2216437 (3440)	total: 52.8s	remaining: 18.7s
3460:	learn: 0.2045290	test: 0.2215931	best: 0.2215931 (3460)	total: 53.1s	remaining: 18.4s
3480:	learn: 0.2043592	test: 0.2215359	best: 0.2215359 (3480)	total: 53.4s	remaining: 18.1s
3500:	learn: 0.2042177	test: 0.2214737	best: 0.2214737 (3500)	total: 53.7s	remaining: 17.7s
3520:	learn: 0.2040685	test: 0.2214243	best: 0.2214197 (3518)	total: 54s	remaining: 17.4s
3540:	learn: 0.2039343	test: 0.2213608	best: 0.2213608 (3540)	total: 54.3s	remaining: 17.1s
3560:	learn: 0.2038053	test: 0.2213024	best: 0.2213024 (3560)	total: 54.6s	remaining: 16.8s
3580:	learn: 0.2036608	test: 0.2212602	best: 0.2212602 (3580)	total: 54.9s	remaining: 16.5s
3600:	learn: 0.2035225	test: 0.2211949	best: 0.2211945 (3599)	total: 55.2s	remaining: 16.2s
3620:	learn: 0.2033798	test: 0.2211204	best: 0.2211162 (3619)	total: 55.5s	remaining: 15.9s
3640:	learn: 0.2032436	test: 0.2210895	best: 0.2210895 (3640)	total: 55.9s	remaining: 15.6s
3660:	learn: 0.2030896	test: 0.2210242	best: 0.2210233 (3659)	total: 56.2s	remaining: 15.3s
3680:	learn: 0.2029507	test: 0.2209724	best: 0.2209724 (3680)	total: 56.5s	remaining: 15s
3700:	learn: 0.2028162	test: 0.2209351	best: 0.2209351 (3700)	total: 56.8s	remaining: 14.7s
3720:	learn: 0.2026703	test: 0.2208705	best: 0.2208705 (3720)	total: 57.1s	remaining: 14.4s
3740:	learn: 0.2025407	test: 0.2208344	best: 0.2208344 (3740)	total: 57.4s	remaining: 14.1s
3760:	learn: 0.2024235	test: 0.2207960	best: 0.2207960 (3760)	total: 57.7s	remaining: 13.8s
3780:	learn: 0.2022793	test: 0.2207601	best: 0.2207601 (3780)	total: 58s	remaining: 13.5s
3800:	learn: 0.2021380	test: 0.2206932	best: 0.2206932 (3800)	total: 58.3s	remaining: 13.2s
3820:	learn: 0.2019998	test: 0.2206220	best: 0.2206220 (3820)	total: 58.6s	remaining: 12.8s
3840:	learn: 0.2018580	test: 0.2205817	best: 0.2205792 (3838)	total: 58.9s	remaining: 12.5s
3860:	learn: 0.2017223	test: 0.2205182	best: 0.2205182 (3860)	total: 59.3s	remaining: 12.2s
3880:	learn: 0.2016112	test: 0.2204994	best: 0.2204945 (3878)	total: 59.6s	remaining: 11.9s
3900:	learn: 0.2014806	test: 0.2204587	best: 0.2204587 (3900)	total: 59.9s	remaining: 11.6s
3920:	learn: 0.2013677	test: 0.2204198	best: 0.2204169 (3917)	total: 1m	remaining: 11.3s
3940:	learn: 0.2012421	test: 0.2203735	best: 0.2203735 (3940)	total: 1m	remaining: 11s
3960:	learn: 0.2010973	test: 0.2203372	best: 0.2203372 (3960)	total: 1m	remaining: 10.7s
3980:	learn: 0.2009761	test: 0.2203035	best: 0.2203035 (3980)	total: 1m 1s	remaining: 10.4s
4000:	learn: 0.2008416	test: 0.2202335	best: 0.2202335 (4000)	total: 1m 1s	remaining: 10.1s
4020:	learn: 0.2007139	test: 0.2201987	best: 0.2201987 (4020)	total: 1m 1s	remaining: 9.78s
4040:	learn: 0.2006083	test: 0.2201729	best: 0.2201729 (4040)	total: 1m 2s	remaining: 9.47s
4060:	learn: 0.2004895	test: 0.2201225	best: 0.2201225 (4060)	total: 1m 2s	remaining: 9.16s
4080:	learn: 0.2003760	test: 0.2200894	best: 0.2200894 (4080)	total: 1m 2s	remaining: 8.86s
4100:	learn: 0.2002395	test: 0.2200485	best: 0.2200485 (4100)	total: 1m 2s	remaining: 8.55s
4120:	learn: 0.2001330	test: 0.2200141	best: 0.2200141 (4120)	total: 1m 3s	remaining: 8.24s
4140:	learn: 0.1999964	test: 0.2199559	best: 0.2199548 (4139)	total: 1m 3s	remaining: 7.94s
4160:	learn: 0.1998763	test: 0.2199110	best: 0.2199110 (4160)	total: 1m 3s	remaining: 7.63s
4180:	learn: 0.1997411	test: 0.2198544	best: 0.2198544 (4180)	total: 1m 4s	remaining: 7.33s
4200:	learn: 0.1996184	test: 0.2197953	best: 0.2197922 (4199)	total: 1m 4s	remaining: 7.02s
4220:	learn: 0.1994976	test: 0.2197493	best: 0.2197493 (4220)	total: 1m 4s	remaining: 6.71s
4240:	learn: 0.1993746	test: 0.2197083	best: 0.2197083 (4240)	total: 1m 5s	remaining: 6.4s
4260:	learn: 0.1992537	test: 0.2196848	best: 0.2196844 (4259)	total: 1m 5s	remaining: 6.1s
4280:	learn: 0.1991223	test: 0.2196547	best: 0.2196547 (4280)	total: 1m 5s	remaining: 5.79s
4300:	learn: 0.1989860	test: 0.2195961	best: 0.2195959 (4299)	total: 1m 6s	remaining: 5.48s
4320:	learn: 0.1988698	test: 0.2195743	best: 0.2195743 (4320)	total: 1m 6s	remaining: 5.18s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6403945	test: 0.6405093	best: 0.6405093 (0)	total: 8.63ms	remaining: 8.63ms
1:	learn: 0.5956007	test: 0.5958525	best: 0.5958525 (1)	total: 17.4ms	remaining: 0us
bestTest = 0.5958524803
bestIteration = 1
0:	learn: 0.6413728	test: 0.6413635	best: 0.6413635 (0)	total: 14.9ms	remaining: 1m 10s
20:	learn: 0.3388153	test: 0.3401458	best: 0.3401458 (20)	total: 314ms	remaining: 1m 10s
40:	learn: 0.3087793	test: 0.3104046	best: 0.3104046 (40)	total: 617ms	remaining: 1m 10s
60:	learn: 0.2960938	test: 0.2982074	best: 0.2982074 (60)	total: 940ms	remaining: 1m 12s
80:	learn: 0.2890718	test: 0.2914126	best: 0.2914126 (80)	total: 1.25s	remaining: 1m 11s
100:	learn: 0.2838705	test: 0.2864867	best: 0.2864867 (100)	total: 1.55s	remaining: 1m 11s
120:	learn: 0.2793830	test: 0.2821275	best: 0.2821275 (120)	total: 1.85s	remaining: 1m 10s
140:	learn: 0.2757973	test: 0.2787739	best: 0.2787739 (140)	total: 2.16s	remaining: 1m 10s
160:	learn: 0.2718933	test: 0.2750373	best: 0.2750373 (160)	total: 2.47s	remaining: 1m 10s
180:	learn: 0.2688228	test: 0.2722364	best: 0.2722364 (180)	total: 2.78s	remaining: 1m 10s
200:	learn: 0.2662832	test: 0.2698497	best: 0.2698497 (200)	total: 3.09s	remaining: 1m 9s
220:	learn: 0.2640182	test: 0.2677348	best: 0.2677348 (220)	total: 3.4s	remaining: 1m 9s
240:	learn: 0.2618449	test: 0.2658576	best: 0.2658576 (240)	total: 3.71s	remaining: 1m 9s
260:	learn: 0.2599637	test: 0.2641449	best: 0.2641449 (260)	total: 4.01s	remaining: 1m 8s
280:	learn: 0.2585519	test: 0.2628938	best: 0.2628938 (280)	total: 4.33s	remaining: 1m 8s
300:	learn: 0.2570531	test: 0.2615420	best: 0.2615420 (300)	total: 4.63s	remaining: 1m 8s
320:	learn: 0.2555050	test: 0.2601141	best: 0.2601141 (320)	total: 4.94s	remaining: 1m 8s
340:	learn: 0.2542459	test: 0.2589712	best: 0.2589712 (340)	total: 5.25s	remaining: 1m 7s
360:	learn: 0.2530650	test: 0.2578655	best: 0.2578655 (360)	total: 5.57s	remaining: 1m 7s
380:	learn: 0.2519668	test: 0.2568928	best: 0.2568928 (380)	total: 5.87s	remaining: 1m 7s
400:	learn: 0.2505559	test: 0.2556126	best: 0.2556126 (400)	total: 6.19s	remaining: 1m 6s
420:	learn: 0.2495719	test: 0.2547550	best: 0.2547550 (420)	total: 6.5s	remaining: 1m 6s
440:	learn: 0.2485056	test: 0.2538082	best: 0.2538082 (440)	total: 6.81s	remaining: 1m 6s
460:	learn: 0.2475766	test: 0.2529987	best: 0.2529987 (460)	total: 7.11s	remaining: 1m 6s
480:	learn: 0.2466700	test: 0.2521102	best: 0.2521102 (480)	total: 7.42s	remaining: 1m 5s
500:	learn: 0.2458500	test: 0.2514217	best: 0.2514217 (500)	total: 7.72s	remaining: 1m 5s
520:	learn: 0.2450333	test: 0.2507548	best: 0.2507548 (520)	total: 8.03s	remaining: 1m 5s
540:	learn: 0.2441797	test: 0.2500573	best: 0.2500573 (540)	total: 8.34s	remaining: 1m 4s
560:	learn: 0.2434402	test: 0.2494094	best: 0.2494094 (560)	total: 8.65s	remaining: 1m 4s
580:	learn: 0.2425874	test: 0.2486750	best: 0.2486750 (580)	total: 8.96s	remaining: 1m 4s
600:	learn: 0.2418466	test: 0.2480378	best: 0.2480378 (600)	total: 9.27s	remaining: 1m 3s
620:	learn: 0.2411172	test: 0.2474595	best: 0.2474595 (620)	total: 9.57s	remaining: 1m 3s
640:	learn: 0.2405036	test: 0.2469806	best: 0.2469806 (640)	total: 9.87s	remaining: 1m 3s
660:	learn: 0.2398400	test: 0.2464097	best: 0.2464097 (660)	total: 10.2s	remaining: 1m 2s
680:	learn: 0.2391815	test: 0.2458826	best: 0.2458826 (680)	total: 10.5s	remaining: 1m 2s
700:	learn: 0.2384991	test: 0.2453497	best: 0.2453497 (700)	total: 10.8s	remaining: 1m 2s
720:	learn: 0.2379391	test: 0.2448801	best: 0.2448801 (720)	total: 11.1s	remaining: 1m 1s
740:	learn: 0.2374288	test: 0.2444802	best: 0.2444802 (740)	total: 11.4s	remaining: 1m 1s
760:	learn: 0.2368593	test: 0.2440252	best: 0.2440252 (760)	total: 11.7s	remaining: 1m 1s
780:	learn: 0.2362500	test: 0.2435601	best: 0.2435601 (780)	total: 12s	remaining: 1m 1s
800:	learn: 0.2357141	test: 0.2431059	best: 0.2431059 (800)	total: 12.4s	remaining: 1m
820:	learn: 0.2352243	test: 0.2427048	best: 0.2427048 (820)	total: 12.7s	remaining: 1m
840:	learn: 0.2347193	test: 0.2422960	best: 0.2422960 (840)	total: 13s	remaining: 1m
860:	learn: 0.2342934	test: 0.2419913	best: 0.2419913 (860)	total: 13.3s	remaining: 1m
880:	learn: 0.2337983	test: 0.2415784	best: 0.2415784 (880)	total: 13.6s	remaining: 59.8s
900:	learn: 0.2333186	test: 0.2412113	best: 0.2412113 (900)	total: 14s	remaining: 59.5s
920:	learn: 0.2328645	test: 0.2408483	best: 0.2408483 (920)	total: 14.3s	remaining: 59.2s
940:	learn: 0.2324120	test: 0.2405507	best: 0.2405507 (940)	total: 14.6s	remaining: 58.9s
960:	learn: 0.2319774	test: 0.2401930	best: 0.2401930 (960)	total: 14.9s	remaining: 58.7s
980:	learn: 0.2315605	test: 0.2398725	best: 0.2398725 (980)	total: 15.2s	remaining: 58.4s
1000:	learn: 0.2310738	test: 0.2394623	best: 0.2394623 (1000)	total: 15.6s	remaining: 58.1s
1020:	learn: 0.2306700	test: 0.2391396	best: 0.2391396 (1020)	total: 15.9s	remaining: 57.8s
1040:	learn: 0.2302319	test: 0.2388029	best: 0.2388029 (1040)	total: 16.2s	remaining: 57.5s
1060:	learn: 0.2298363	test: 0.2385420	best: 0.2385420 (1060)	total: 16.5s	remaining: 57.2s
1080:	learn: 0.2294747	test: 0.2382810	best: 0.2382810 (1080)	total: 16.8s	remaining: 56.9s
1100:	learn: 0.2290557	test: 0.2379476	best: 0.2379476 (1100)	total: 17.1s	remaining: 56.6s
1120:	learn: 0.2287739	test: 0.2377708	best: 0.2377708 (1120)	total: 17.4s	remaining: 56.3s
1140:	learn: 0.2283869	test: 0.2375233	best: 0.2375233 (1140)	total: 17.7s	remaining: 55.9s
1160:	learn: 0.2280125	test: 0.2372543	best: 0.2372543 (1160)	total: 18s	remaining: 55.6s
1180:	learn: 0.2276716	test: 0.2370251	best: 0.2370251 (1180)	total: 18.4s	remaining: 55.3s
1200:	learn: 0.2273470	test: 0.2367952	best: 0.2367952 (1200)	total: 18.7s	remaining: 55s
1220:	learn: 0.2270135	test: 0.2365803	best: 0.2365803 (1220)	total: 19s	remaining: 54.7s
1240:	learn: 0.2266891	test: 0.2363797	best: 0.2363797 (1240)	total: 19.3s	remaining: 54.4s
1260:	learn: 0.2263509	test: 0.2361217	best: 0.2361217 (1260)	total: 19.6s	remaining: 54.1s
1280:	learn: 0.2260424	test: 0.2359065	best: 0.2359065 (1280)	total: 19.9s	remaining: 53.8s
1300:	learn: 0.2256679	test: 0.2356403	best: 0.2356403 (1300)	total: 20.2s	remaining: 53.5s
1320:	learn: 0.2253513	test: 0.2354450	best: 0.2354450 (1320)	total: 20.6s	remaining: 53.2s
1340:	learn: 0.2250035	test: 0.2352048	best: 0.2352048 (1340)	total: 20.9s	remaining: 52.9s
1360:	learn: 0.2247298	test: 0.2350225	best: 0.2350225 (1360)	total: 21.2s	remaining: 52.6s
1380:	learn: 0.2244366	test: 0.2348498	best: 0.2348498 (1380)	total: 21.5s	remaining: 52.3s
1400:	learn: 0.2241615	test: 0.2346731	best: 0.2346731 (1400)	total: 21.8s	remaining: 52s
1420:	learn: 0.2238329	test: 0.2343984	best: 0.2343984 (1420)	total: 22.1s	remaining: 51.7s
1440:	learn: 0.2235659	test: 0.2342379	best: 0.2342379 (1440)	total: 22.4s	remaining: 51.3s
1460:	learn: 0.2232953	test: 0.2340977	best: 0.2340977 (1460)	total: 22.7s	remaining: 51s
1480:	learn: 0.2230092	test: 0.2339565	best: 0.2339565 (1480)	total: 23.1s	remaining: 50.7s
1500:	learn: 0.2227178	test: 0.2337794	best: 0.2337794 (1500)	total: 23.4s	remaining: 50.4s
1520:	learn: 0.2224810	test: 0.2336398	best: 0.2336398 (1520)	total: 23.7s	remaining: 50.1s
1540:	learn: 0.2221856	test: 0.2334536	best: 0.2334536 (1540)	total: 24s	remaining: 49.8s
1560:	learn: 0.2218779	test: 0.2332552	best: 0.2332552 (1560)	total: 24.3s	remaining: 49.5s
1580:	learn: 0.2215911	test: 0.2330565	best: 0.2330565 (1580)	total: 24.6s	remaining: 49.2s
1600:	learn: 0.2213606	test: 0.2329257	best: 0.2329257 (1600)	total: 24.9s	remaining: 48.8s
1620:	learn: 0.2211175	test: 0.2327610	best: 0.2327610 (1620)	total: 25.2s	remaining: 48.5s
1640:	learn: 0.2208486	test: 0.2325818	best: 0.2325818 (1640)	total: 25.5s	remaining: 48.2s
1660:	learn: 0.2205838	test: 0.2324284	best: 0.2324284 (1660)	total: 25.8s	remaining: 47.9s
1680:	learn: 0.2203301	test: 0.2323050	best: 0.2323050 (1680)	total: 26.1s	remaining: 47.6s
1700:	learn: 0.2200882	test: 0.2321714	best: 0.2321714 (1700)	total: 26.4s	remaining: 47.2s
1720:	learn: 0.2197945	test: 0.2319992	best: 0.2319992 (1720)	total: 26.7s	remaining: 46.9s
1740:	learn: 0.2195794	test: 0.2318705	best: 0.2318705 (1740)	total: 27.1s	remaining: 46.6s
1760:	learn: 0.2193498	test: 0.2317243	best: 0.2317243 (1760)	total: 27.4s	remaining: 46.3s
1780:	learn: 0.2191110	test: 0.2315812	best: 0.2315812 (1780)	total: 27.7s	remaining: 46s
1800:	learn: 0.2188849	test: 0.2314434	best: 0.2314434 (1800)	total: 28s	remaining: 45.7s
1820:	learn: 0.2186479	test: 0.2313080	best: 0.2313080 (1820)	total: 28.3s	remaining: 45.3s
1840:	learn: 0.2184355	test: 0.2312052	best: 0.2312052 (1840)	total: 28.6s	remaining: 45s
1860:	learn: 0.2182229	test: 0.2310956	best: 0.2310956 (1860)	total: 28.9s	remaining: 44.7s
1880:	learn: 0.2179907	test: 0.2309338	best: 0.2309338 (1880)	total: 29.2s	remaining: 44.4s
1900:	learn: 0.2177636	test: 0.2308143	best: 0.2308143 (1900)	total: 29.5s	remaining: 44.1s
1920:	learn: 0.2175355	test: 0.2306974	best: 0.2306974 (1920)	total: 29.8s	remaining: 43.8s
1940:	learn: 0.2173237	test: 0.2305913	best: 0.2305913 (1940)	total: 30.1s	remaining: 43.4s
1960:	learn: 0.2170760	test: 0.2304563	best: 0.2304563 (1960)	total: 30.4s	remaining: 43.1s
1980:	learn: 0.2168541	test: 0.2303226	best: 0.2303226 (1980)	total: 30.7s	remaining: 42.8s
2000:	learn: 0.2166519	test: 0.2302259	best: 0.2302259 (2000)	total: 31s	remaining: 42.5s
2020:	learn: 0.2164313	test: 0.2301034	best: 0.2301034 (2020)	total: 31.3s	remaining: 42.2s
2040:	learn: 0.2162154	test: 0.2299895	best: 0.2299895 (2040)	total: 31.6s	remaining: 41.8s
2060:	learn: 0.2159941	test: 0.2298555	best: 0.2298555 (2060)	total: 31.9s	remaining: 41.5s
2080:	learn: 0.2157755	test: 0.2297286	best: 0.2297286 (2080)	total: 32.2s	remaining: 41.2s
2100:	learn: 0.2155689	test: 0.2296234	best: 0.2296234 (2100)	total: 32.6s	remaining: 40.9s
2120:	learn: 0.2153571	test: 0.2295143	best: 0.2295143 (2120)	total: 32.9s	remaining: 40.6s
2140:	learn: 0.2151414	test: 0.2293998	best: 0.2293998 (2140)	total: 33.2s	remaining: 40.3s
2160:	learn: 0.2149170	test: 0.2292768	best: 0.2292768 (2160)	total: 33.5s	remaining: 39.9s
2180:	learn: 0.2147212	test: 0.2291825	best: 0.2291825 (2180)	total: 33.8s	remaining: 39.6s
2200:	learn: 0.2145109	test: 0.2290612	best: 0.2290612 (2200)	total: 34.1s	remaining: 39.3s
2220:	learn: 0.2143094	test: 0.2289547	best: 0.2289547 (2220)	total: 34.4s	remaining: 39s
2240:	learn: 0.2141041	test: 0.2288566	best: 0.2288566 (2240)	total: 34.7s	remaining: 38.7s
2260:	learn: 0.2139085	test: 0.2287537	best: 0.2287537 (2260)	total: 35s	remaining: 38.4s
2280:	learn: 0.2137559	test: 0.2287021	best: 0.2287019 (2279)	total: 35.3s	remaining: 38.1s
2300:	learn: 0.2135427	test: 0.2285934	best: 0.2285934 (2300)	total: 35.6s	remaining: 37.7s
2320:	learn: 0.2133515	test: 0.2284986	best: 0.2284986 (2320)	total: 35.9s	remaining: 37.4s
2340:	learn: 0.2131539	test: 0.2283904	best: 0.2283904 (2340)	total: 36.2s	remaining: 37.1s
2360:	learn: 0.2129613	test: 0.2282671	best: 0.2282671 (2360)	total: 36.5s	remaining: 36.8s
2380:	learn: 0.2127665	test: 0.2281503	best: 0.2281503 (2380)	total: 36.8s	remaining: 36.5s
2400:	learn: 0.2125941	test: 0.2280653	best: 0.2280653 (2400)	total: 37.1s	remaining: 36.2s
2420:	learn: 0.2123990	test: 0.2279371	best: 0.2279371 (2420)	total: 37.4s	remaining: 35.9s
2440:	learn: 0.2121847	test: 0.2278298	best: 0.2278298 (2440)	total: 37.8s	remaining: 35.6s
2460:	learn: 0.2119860	test: 0.2277236	best: 0.2277236 (2460)	total: 38.1s	remaining: 35.2s
2480:	learn: 0.2117970	test: 0.2276238	best: 0.2276238 (2480)	total: 38.4s	remaining: 34.9s
2500:	learn: 0.2116059	test: 0.2275341	best: 0.2275341 (2500)	total: 38.7s	remaining: 34.6s
2520:	learn: 0.2114190	test: 0.2274319	best: 0.2274319 (2520)	total: 39s	remaining: 34.3s
2540:	learn: 0.2112700	test: 0.2273755	best: 0.2273755 (2540)	total: 39.3s	remaining: 34s
2560:	learn: 0.2110952	test: 0.2273015	best: 0.2273015 (2560)	total: 39.6s	remaining: 33.7s
2580:	learn: 0.2108969	test: 0.2271962	best: 0.2271962 (2580)	total: 39.9s	remaining: 33.4s
2600:	learn: 0.2107101	test: 0.2271134	best: 0.2271134 (2600)	total: 40.2s	remaining: 33.1s
2620:	learn: 0.2105564	test: 0.2270534	best: 0.2270516 (2618)	total: 40.5s	remaining: 32.8s
2640:	learn: 0.2103992	test: 0.2269710	best: 0.2269710 (2640)	total: 40.8s	remaining: 32.4s
2660:	learn: 0.2102271	test: 0.2268808	best: 0.2268808 (2660)	total: 41.1s	remaining: 32.1s
2680:	learn: 0.2100735	test: 0.2268108	best: 0.2268108 (2680)	total: 41.4s	remaining: 31.8s
2700:	learn: 0.2099360	test: 0.2267439	best: 0.2267439 (2700)	total: 41.7s	remaining: 31.5s
2720:	learn: 0.2097749	test: 0.2266887	best: 0.2266887 (2720)	total: 42s	remaining: 31.2s
2740:	learn: 0.2096171	test: 0.2266249	best: 0.2266249 (2740)	total: 42.3s	remaining: 30.9s
2760:	learn: 0.2094539	test: 0.2265367	best: 0.2265367 (2760)	total: 42.6s	remaining: 30.6s
2780:	learn: 0.2092734	test: 0.2264617	best: 0.2264617 (2780)	total: 43s	remaining: 30.3s
2800:	learn: 0.2091102	test: 0.2263601	best: 0.2263601 (2800)	total: 43.3s	remaining: 29.9s
2820:	learn: 0.2089478	test: 0.2262952	best: 0.2262952 (2820)	total: 43.6s	remaining: 29.6s
2840:	learn: 0.2088060	test: 0.2262377	best: 0.2262377 (2840)	total: 43.9s	remaining: 29.3s
2860:	learn: 0.2086605	test: 0.2261677	best: 0.2261677 (2860)	total: 44.2s	remaining: 29s
2880:	learn: 0.2084795	test: 0.2260946	best: 0.2260942 (2879)	total: 44.5s	remaining: 28.7s
2900:	learn: 0.2083230	test: 0.2260436	best: 0.2260436 (2900)	total: 44.8s	remaining: 28.4s
2920:	learn: 0.2081578	test: 0.2259580	best: 0.2259580 (2920)	total: 45.1s	remaining: 28.1s
2940:	learn: 0.2080066	test: 0.2258854	best: 0.2258854 (2940)	total: 45.4s	remaining: 27.8s
2960:	learn: 0.2078257	test: 0.2257878	best: 0.2257878 (2960)	total: 45.7s	remaining: 27.5s
2980:	learn: 0.2076717	test: 0.2257142	best: 0.2257142 (2980)	total: 46s	remaining: 27.2s
3000:	learn: 0.2075077	test: 0.2256368	best: 0.2256368 (3000)	total: 46.3s	remaining: 26.9s
3020:	learn: 0.2073640	test: 0.2255988	best: 0.2255988 (3020)	total: 46.6s	remaining: 26.5s
3040:	learn: 0.2071910	test: 0.2255076	best: 0.2255076 (3040)	total: 47s	remaining: 26.2s
3060:	learn: 0.2070132	test: 0.2254231	best: 0.2254231 (3060)	total: 47.3s	remaining: 25.9s
3080:	learn: 0.2068326	test: 0.2253374	best: 0.2253374 (3080)	total: 47.6s	remaining: 25.6s
3100:	learn: 0.2066835	test: 0.2252637	best: 0.2252637 (3100)	total: 47.9s	remaining: 25.3s
3120:	learn: 0.2065227	test: 0.2251936	best: 0.2251930 (3119)	total: 48.2s	remaining: 25s
3140:	learn: 0.2063784	test: 0.2251207	best: 0.2251207 (3140)	total: 48.5s	remaining: 24.7s
3160:	learn: 0.2062259	test: 0.2250644	best: 0.2250644 (3160)	total: 48.8s	remaining: 24.4s
3180:	learn: 0.2060532	test: 0.2249763	best: 0.2249763 (3180)	total: 49.1s	remaining: 24.1s
3200:	learn: 0.2058945	test: 0.2249078	best: 0.2249078 (3200)	total: 49.4s	remaining: 23.8s
3220:	learn: 0.2057491	test: 0.2248321	best: 0.2248321 (3220)	total: 49.7s	remaining: 23.4s
3240:	learn: 0.2055995	test: 0.2247704	best: 0.2247704 (3240)	total: 50s	remaining: 23.1s
3260:	learn: 0.2054458	test: 0.2247030	best: 0.2247030 (3259)	total: 50.3s	remaining: 22.8s
3280:	learn: 0.2052963	test: 0.2246502	best: 0.2246502 (3280)	total: 50.6s	remaining: 22.5s
3300:	learn: 0.2051465	test: 0.2245758	best: 0.2245758 (3300)	total: 50.9s	remaining: 22.2s
3320:	learn: 0.2050071	test: 0.2245359	best: 0.2245348 (3319)	total: 51.2s	remaining: 21.9s
3340:	learn: 0.2048644	test: 0.2244976	best: 0.2244976 (3340)	total: 51.5s	remaining: 21.6s
3360:	learn: 0.2047241	test: 0.2244516	best: 0.2244515 (3358)	total: 51.9s	remaining: 21.3s
3380:	learn: 0.2045565	test: 0.2243906	best: 0.2243906 (3380)	total: 52.2s	remaining: 21s
3400:	learn: 0.2044213	test: 0.2243236	best: 0.2243236 (3400)	total: 52.5s	remaining: 20.7s
3420:	learn: 0.2042673	test: 0.2242589	best: 0.2242589 (3420)	total: 52.8s	remaining: 20.3s
3440:	learn: 0.2041315	test: 0.2242037	best: 0.2242037 (3440)	total: 53.1s	remaining: 20s
3460:	learn: 0.2039835	test: 0.2241531	best: 0.2241531 (3460)	total: 53.4s	remaining: 19.7s
3480:	learn: 0.2038398	test: 0.2240752	best: 0.2240752 (3480)	total: 53.7s	remaining: 19.4s
3500:	learn: 0.2036846	test: 0.2240031	best: 0.2240031 (3500)	total: 54s	remaining: 19.1s
3520:	learn: 0.2035482	test: 0.2239531	best: 0.2239531 (3520)	total: 54.3s	remaining: 18.8s
3540:	learn: 0.2034199	test: 0.2239002	best: 0.2239002 (3540)	total: 54.6s	remaining: 18.5s
3560:	learn: 0.2032660	test: 0.2238461	best: 0.2238426 (3558)	total: 54.9s	remaining: 18.2s
3580:	learn: 0.2031447	test: 0.2238075	best: 0.2238075 (3580)	total: 55.2s	remaining: 17.9s
3600:	learn: 0.2029865	test: 0.2237461	best: 0.2237461 (3600)	total: 55.5s	remaining: 17.6s
3620:	learn: 0.2028305	test: 0.2236726	best: 0.2236726 (3620)	total: 55.8s	remaining: 17.3s
3640:	learn: 0.2026812	test: 0.2236128	best: 0.2236119 (3639)	total: 56.1s	remaining: 16.9s
3660:	learn: 0.2025387	test: 0.2235556	best: 0.2235556 (3660)	total: 56.5s	remaining: 16.6s
3680:	learn: 0.2024160	test: 0.2235165	best: 0.2235165 (3680)	total: 56.8s	remaining: 16.3s
3700:	learn: 0.2022860	test: 0.2234613	best: 0.2234613 (3700)	total: 57.1s	remaining: 16s
3720:	learn: 0.2021528	test: 0.2234208	best: 0.2234194 (3719)	total: 57.4s	remaining: 15.7s
3740:	learn: 0.2020257	test: 0.2233757	best: 0.2233757 (3740)	total: 57.7s	remaining: 15.4s
3760:	learn: 0.2018780	test: 0.2233270	best: 0.2233258 (3757)	total: 58s	remaining: 15.1s
3780:	learn: 0.2017459	test: 0.2232830	best: 0.2232830 (3780)	total: 58.3s	remaining: 14.8s
3800:	learn: 0.2015894	test: 0.2232048	best: 0.2232048 (3800)	total: 58.6s	remaining: 14.5s
3820:	learn: 0.2014574	test: 0.2231462	best: 0.2231462 (3820)	total: 58.9s	remaining: 14.2s
3840:	learn: 0.2013223	test: 0.2230964	best: 0.2230951 (3838)	total: 59.2s	remaining: 13.9s
3860:	learn: 0.2011850	test: 0.2230633	best: 0.2230633 (3860)	total: 59.5s	remaining: 13.6s
3880:	learn: 0.2010559	test: 0.2230261	best: 0.2230261 (3880)	total: 59.8s	remaining: 13.2s
3900:	learn: 0.2009204	test: 0.2229853	best: 0.2229853 (3900)	total: 1m	remaining: 12.9s
3920:	learn: 0.2007951	test: 0.2229518	best: 0.2229518 (3920)	total: 1m	remaining: 12.6s
3940:	learn: 0.2006429	test: 0.2228822	best: 0.2228813 (3939)	total: 1m	remaining: 12.3s
3960:	learn: 0.2004852	test: 0.2228115	best: 0.2228115 (3960)	total: 1m 1s	remaining: 12s
3980:	learn: 0.2003391	test: 0.2227580	best: 0.2227580 (3980)	total: 1m 1s	remaining: 11.7s
4000:	learn: 0.2002135	test: 0.2227203	best: 0.2227186 (3999)	total: 1m 1s	remaining: 11.4s
4020:	learn: 0.2000858	test: 0.2226774	best: 0.2226767 (4019)	total: 1m 2s	remaining: 11.1s
4040:	learn: 0.1999578	test: 0.2226251	best: 0.2226247 (4039)	total: 1m 2s	remaining: 10.8s
4060:	learn: 0.1998192	test: 0.2225627	best: 0.2225627 (4060)	total: 1m 2s	remaining: 10.5s
4080:	learn: 0.1996812	test: 0.2225006	best: 0.2225006 (4080)	total: 1m 2s	remaining: 10.2s
4100:	learn: 0.1995591	test: 0.2224725	best: 0.2224725 (4100)	total: 1m 3s	remaining: 9.85s
4120:	learn: 0.1994370	test: 0.2224403	best: 0.2224403 (4120)	total: 1m 3s	remaining: 9.54s
4140:	learn: 0.1993119	test: 0.2224041	best: 0.2224041 (4140)	total: 1m 3s	remaining: 9.24s
4160:	learn: 0.1991833	test: 0.2223538	best: 0.2223538 (4160)	total: 1m 4s	remaining: 8.93s
4180:	learn: 0.1990584	test: 0.2223393	best: 0.2223393 (4180)	total: 1m 4s	remaining: 8.62s
4200:	learn: 0.1989307	test: 0.2222914	best: 0.2222914 (4200)	total: 1m 4s	remaining: 8.31s
4220:	learn: 0.1988242	test: 0.2222626	best: 0.2222626 (4220)	total: 1m 5s	remaining: 8s
4240:	learn: 0.1987035	test: 0.2222232	best: 0.2222232 (4240)	total: 1m 5s	remaining: 7.7s
4260:	learn: 0.1985836	test: 0.2221792	best: 0.2221792 (4260)	total: 1m 5s	remaining: 7.39s
4280:	learn: 0.1984546	test: 0.2221271	best: 0.2221271 (4280)	total: 1m 6s	remaining: 7.08s
4300:	learn: 0.1983312	test: 0.2221079	best: 0.2221079 (4300)	total: 1m 6s	remaining: 6.77s
4320:	learn: 0.1981851	test: 0.2220380	best: 0.2220380 (4320)	total: 1m 6s	remaining: 6.46s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404902	test: 0.6404259	best: 0.6404259 (0)	total: 9.46ms	remaining: 9.46ms
1:	learn: 0.5956872	test: 0.5955752	best: 0.5955752 (1)	total: 18ms	remaining: 0us
bestTest = 0.595575164
bestIteration = 1
0:	learn: 0.6414934	test: 0.6414190	best: 0.6414190 (0)	total: 15.8ms	remaining: 1m 14s
20:	learn: 0.3405446	test: 0.3406851	best: 0.3406851 (20)	total: 322ms	remaining: 1m 12s
40:	learn: 0.3098646	test: 0.3102270	best: 0.3102270 (40)	total: 630ms	remaining: 1m 12s
60:	learn: 0.2971016	test: 0.2974117	best: 0.2974117 (60)	total: 947ms	remaining: 1m 12s
80:	learn: 0.2895485	test: 0.2899070	best: 0.2899070 (80)	total: 1.26s	remaining: 1m 12s
100:	learn: 0.2845528	test: 0.2849178	best: 0.2849178 (100)	total: 1.57s	remaining: 1m 12s
120:	learn: 0.2803005	test: 0.2807381	best: 0.2807381 (120)	total: 1.92s	remaining: 1m 13s
140:	learn: 0.2762545	test: 0.2767409	best: 0.2767409 (140)	total: 2.24s	remaining: 1m 12s
160:	learn: 0.2734007	test: 0.2738778	best: 0.2738778 (160)	total: 2.55s	remaining: 1m 12s
180:	learn: 0.2700739	test: 0.2705628	best: 0.2705628 (180)	total: 2.87s	remaining: 1m 12s
200:	learn: 0.2676007	test: 0.2682379	best: 0.2682379 (200)	total: 3.19s	remaining: 1m 11s
220:	learn: 0.2652134	test: 0.2658613	best: 0.2658613 (220)	total: 3.5s	remaining: 1m 11s
240:	learn: 0.2628332	test: 0.2635413	best: 0.2635413 (240)	total: 3.84s	remaining: 1m 11s
260:	learn: 0.2611188	test: 0.2618055	best: 0.2618055 (260)	total: 4.15s	remaining: 1m 11s
280:	learn: 0.2592910	test: 0.2601084	best: 0.2601084 (280)	total: 4.46s	remaining: 1m 10s
300:	learn: 0.2575666	test: 0.2585126	best: 0.2585126 (300)	total: 4.78s	remaining: 1m 10s
320:	learn: 0.2562127	test: 0.2572545	best: 0.2572545 (320)	total: 5.09s	remaining: 1m 9s
340:	learn: 0.2548005	test: 0.2559239	best: 0.2559239 (340)	total: 5.41s	remaining: 1m 9s
360:	learn: 0.2534681	test: 0.2546311	best: 0.2546311 (360)	total: 5.72s	remaining: 1m 9s
380:	learn: 0.2523196	test: 0.2535626	best: 0.2535626 (380)	total: 6.04s	remaining: 1m 9s
400:	learn: 0.2512670	test: 0.2525907	best: 0.2525907 (400)	total: 6.36s	remaining: 1m 8s
420:	learn: 0.2500673	test: 0.2514613	best: 0.2514613 (420)	total: 6.69s	remaining: 1m 8s
440:	learn: 0.2491611	test: 0.2506749	best: 0.2506749 (440)	total: 7s	remaining: 1m 8s
460:	learn: 0.2481594	test: 0.2497911	best: 0.2497911 (460)	total: 7.32s	remaining: 1m 7s
480:	learn: 0.2472095	test: 0.2489453	best: 0.2489453 (480)	total: 7.64s	remaining: 1m 7s
500:	learn: 0.2463584	test: 0.2482091	best: 0.2482091 (500)	total: 7.95s	remaining: 1m 7s
520:	learn: 0.2453988	test: 0.2472791	best: 0.2472791 (520)	total: 8.28s	remaining: 1m 6s
540:	learn: 0.2446570	test: 0.2466144	best: 0.2466144 (540)	total: 8.59s	remaining: 1m 6s
560:	learn: 0.2437591	test: 0.2458080	best: 0.2458080 (560)	total: 8.9s	remaining: 1m 6s
580:	learn: 0.2429887	test: 0.2451400	best: 0.2451400 (580)	total: 9.22s	remaining: 1m 5s
600:	learn: 0.2422306	test: 0.2444508	best: 0.2444508 (600)	total: 9.53s	remaining: 1m 5s
620:	learn: 0.2414639	test: 0.2437737	best: 0.2437737 (620)	total: 9.86s	remaining: 1m 5s
640:	learn: 0.2407173	test: 0.2431346	best: 0.2431346 (640)	total: 10.2s	remaining: 1m 4s
660:	learn: 0.2400919	test: 0.2426227	best: 0.2426227 (660)	total: 10.5s	remaining: 1m 4s
680:	learn: 0.2394117	test: 0.2420593	best: 0.2420593 (680)	total: 10.8s	remaining: 1m 4s
700:	learn: 0.2388200	test: 0.2415726	best: 0.2415726 (700)	total: 11.1s	remaining: 1m 3s
720:	learn: 0.2382297	test: 0.2411530	best: 0.2411530 (720)	total: 11.4s	remaining: 1m 3s
740:	learn: 0.2376418	test: 0.2406835	best: 0.2406835 (740)	total: 11.7s	remaining: 1m 3s
760:	learn: 0.2371089	test: 0.2402430	best: 0.2402430 (760)	total: 12s	remaining: 1m 2s
780:	learn: 0.2366096	test: 0.2398556	best: 0.2398556 (780)	total: 12.3s	remaining: 1m 2s
800:	learn: 0.2359625	test: 0.2393331	best: 0.2393331 (800)	total: 12.7s	remaining: 1m 2s
820:	learn: 0.2354729	test: 0.2389630	best: 0.2389630 (820)	total: 13s	remaining: 1m 1s
840:	learn: 0.2349871	test: 0.2386010	best: 0.2386010 (840)	total: 13.3s	remaining: 1m 1s
860:	learn: 0.2345222	test: 0.2382437	best: 0.2382437 (860)	total: 13.6s	remaining: 1m 1s
880:	learn: 0.2340552	test: 0.2378918	best: 0.2378918 (880)	total: 13.9s	remaining: 1m
900:	learn: 0.2335670	test: 0.2374935	best: 0.2374935 (900)	total: 14.2s	remaining: 1m
920:	learn: 0.2331514	test: 0.2371910	best: 0.2371910 (920)	total: 14.5s	remaining: 1m
940:	learn: 0.2327133	test: 0.2368737	best: 0.2368737 (940)	total: 14.9s	remaining: 59.8s
960:	learn: 0.2322287	test: 0.2364974	best: 0.2364974 (960)	total: 15.2s	remaining: 59.5s
980:	learn: 0.2317592	test: 0.2361750	best: 0.2361750 (980)	total: 15.5s	remaining: 59.2s
1000:	learn: 0.2312986	test: 0.2358549	best: 0.2358549 (1000)	total: 15.8s	remaining: 58.8s
1020:	learn: 0.2308585	test: 0.2355050	best: 0.2355050 (1020)	total: 16.1s	remaining: 58.5s
1040:	learn: 0.2304836	test: 0.2352142	best: 0.2352142 (1040)	total: 16.4s	remaining: 58.1s
1060:	learn: 0.2300982	test: 0.2349333	best: 0.2349333 (1060)	total: 16.7s	remaining: 57.8s
1080:	learn: 0.2296672	test: 0.2345988	best: 0.2345988 (1080)	total: 17s	remaining: 57.5s
1100:	learn: 0.2293081	test: 0.2343597	best: 0.2343597 (1100)	total: 17.3s	remaining: 57.2s
1120:	learn: 0.2289170	test: 0.2340640	best: 0.2340640 (1120)	total: 17.7s	remaining: 56.9s
1140:	learn: 0.2285168	test: 0.2337642	best: 0.2337642 (1140)	total: 18s	remaining: 56.6s
1160:	learn: 0.2281526	test: 0.2334976	best: 0.2334976 (1160)	total: 18.3s	remaining: 56.2s
1180:	learn: 0.2278372	test: 0.2332862	best: 0.2332862 (1180)	total: 18.6s	remaining: 55.9s
1200:	learn: 0.2274814	test: 0.2330624	best: 0.2330624 (1200)	total: 18.9s	remaining: 55.5s
1220:	learn: 0.2271732	test: 0.2328329	best: 0.2328329 (1220)	total: 19.2s	remaining: 55.2s
1240:	learn: 0.2268320	test: 0.2326016	best: 0.2326016 (1240)	total: 19.5s	remaining: 54.8s
1260:	learn: 0.2264950	test: 0.2323625	best: 0.2323625 (1260)	total: 19.8s	remaining: 54.5s
1280:	learn: 0.2261903	test: 0.2321425	best: 0.2321425 (1280)	total: 20.1s	remaining: 54.1s
1300:	learn: 0.2258837	test: 0.2319342	best: 0.2319342 (1300)	total: 20.4s	remaining: 53.8s
1320:	learn: 0.2255901	test: 0.2317296	best: 0.2317296 (1320)	total: 20.7s	remaining: 53.4s
1340:	learn: 0.2253017	test: 0.2315396	best: 0.2315396 (1340)	total: 21s	remaining: 53.1s
1360:	learn: 0.2250185	test: 0.2313854	best: 0.2313849 (1359)	total: 21.3s	remaining: 52.8s
1380:	learn: 0.2247366	test: 0.2311979	best: 0.2311979 (1380)	total: 21.6s	remaining: 52.5s
1400:	learn: 0.2244128	test: 0.2309846	best: 0.2309846 (1400)	total: 21.9s	remaining: 52.2s
1420:	learn: 0.2241262	test: 0.2307861	best: 0.2307861 (1420)	total: 22.2s	remaining: 51.8s
1440:	learn: 0.2238423	test: 0.2306216	best: 0.2306216 (1440)	total: 22.6s	remaining: 51.5s
1460:	learn: 0.2235435	test: 0.2304386	best: 0.2304386 (1460)	total: 22.9s	remaining: 51.2s
1480:	learn: 0.2232665	test: 0.2302484	best: 0.2302484 (1480)	total: 23.2s	remaining: 50.8s
1500:	learn: 0.2229696	test: 0.2300619	best: 0.2300619 (1500)	total: 23.5s	remaining: 50.5s
1520:	learn: 0.2226584	test: 0.2298717	best: 0.2298717 (1520)	total: 23.8s	remaining: 50.2s
1540:	learn: 0.2223876	test: 0.2296767	best: 0.2296767 (1540)	total: 24.1s	remaining: 49.9s
1560:	learn: 0.2221613	test: 0.2295563	best: 0.2295563 (1560)	total: 24.4s	remaining: 49.6s
1580:	learn: 0.2219236	test: 0.2294103	best: 0.2294103 (1580)	total: 24.7s	remaining: 49.2s
1600:	learn: 0.2216755	test: 0.2292508	best: 0.2292508 (1600)	total: 25s	remaining: 48.9s
1620:	learn: 0.2214081	test: 0.2290954	best: 0.2290954 (1620)	total: 25.3s	remaining: 48.6s
1640:	learn: 0.2211927	test: 0.2289704	best: 0.2289704 (1640)	total: 25.6s	remaining: 48.2s
1660:	learn: 0.2209497	test: 0.2288038	best: 0.2288038 (1660)	total: 25.9s	remaining: 47.9s
1680:	learn: 0.2207184	test: 0.2286737	best: 0.2286737 (1680)	total: 26.2s	remaining: 47.6s
1700:	learn: 0.2204880	test: 0.2285302	best: 0.2285302 (1700)	total: 26.5s	remaining: 47.3s
1720:	learn: 0.2202640	test: 0.2283985	best: 0.2283985 (1720)	total: 26.8s	remaining: 46.9s
1740:	learn: 0.2200342	test: 0.2282765	best: 0.2282765 (1740)	total: 27.1s	remaining: 46.6s
1760:	learn: 0.2197890	test: 0.2280993	best: 0.2280993 (1760)	total: 27.4s	remaining: 46.3s
1780:	learn: 0.2195680	test: 0.2280135	best: 0.2280135 (1780)	total: 27.8s	remaining: 46s
1800:	learn: 0.2193209	test: 0.2278732	best: 0.2278732 (1800)	total: 28.1s	remaining: 45.7s
1820:	learn: 0.2190822	test: 0.2277458	best: 0.2277451 (1819)	total: 28.4s	remaining: 45.3s
1840:	learn: 0.2188147	test: 0.2276007	best: 0.2276007 (1840)	total: 28.7s	remaining: 45s
1860:	learn: 0.2185987	test: 0.2274779	best: 0.2274779 (1860)	total: 29s	remaining: 44.7s
1880:	learn: 0.2183866	test: 0.2273875	best: 0.2273875 (1880)	total: 29.3s	remaining: 44.4s
1900:	learn: 0.2181730	test: 0.2272894	best: 0.2272886 (1898)	total: 29.6s	remaining: 44.1s
1920:	learn: 0.2179457	test: 0.2271461	best: 0.2271461 (1920)	total: 29.9s	remaining: 43.8s
1940:	learn: 0.2177599	test: 0.2270481	best: 0.2270481 (1940)	total: 30.2s	remaining: 43.5s
1960:	learn: 0.2175183	test: 0.2269246	best: 0.2269246 (1960)	total: 30.5s	remaining: 43.1s
1980:	learn: 0.2173010	test: 0.2268160	best: 0.2268160 (1980)	total: 30.8s	remaining: 42.8s
2000:	learn: 0.2171042	test: 0.2267066	best: 0.2267066 (2000)	total: 31.1s	remaining: 42.5s
2020:	learn: 0.2168866	test: 0.2266066	best: 0.2266066 (2020)	total: 31.5s	remaining: 42.2s
2040:	learn: 0.2166436	test: 0.2264678	best: 0.2264678 (2040)	total: 31.8s	remaining: 41.9s
2060:	learn: 0.2164267	test: 0.2263313	best: 0.2263313 (2060)	total: 32.1s	remaining: 41.6s
2080:	learn: 0.2161964	test: 0.2261764	best: 0.2261764 (2080)	total: 32.4s	remaining: 41.3s
2100:	learn: 0.2159705	test: 0.2260290	best: 0.2260290 (2100)	total: 32.7s	remaining: 40.9s
2120:	learn: 0.2157724	test: 0.2259303	best: 0.2259303 (2120)	total: 33s	remaining: 40.6s
2140:	learn: 0.2155435	test: 0.2258229	best: 0.2258229 (2140)	total: 33.3s	remaining: 40.3s
2160:	learn: 0.2153185	test: 0.2256899	best: 0.2256899 (2160)	total: 33.6s	remaining: 40s
2180:	learn: 0.2150941	test: 0.2255615	best: 0.2255615 (2180)	total: 33.9s	remaining: 39.7s
2200:	learn: 0.2148827	test: 0.2254402	best: 0.2254402 (2200)	total: 34.2s	remaining: 39.4s
2220:	learn: 0.2146985	test: 0.2253457	best: 0.2253457 (2220)	total: 34.5s	remaining: 39.1s
2240:	learn: 0.2144868	test: 0.2252285	best: 0.2252285 (2240)	total: 34.8s	remaining: 38.7s
2260:	learn: 0.2142699	test: 0.2251175	best: 0.2251175 (2260)	total: 35.2s	remaining: 38.4s
2280:	learn: 0.2140548	test: 0.2250152	best: 0.2250152 (2280)	total: 35.5s	remaining: 38.1s
2300:	learn: 0.2138490	test: 0.2249019	best: 0.2249019 (2300)	total: 35.8s	remaining: 37.8s
2320:	learn: 0.2136403	test: 0.2248088	best: 0.2248088 (2320)	total: 36.1s	remaining: 37.5s
2340:	learn: 0.2134418	test: 0.2247184	best: 0.2247184 (2340)	total: 36.4s	remaining: 37.2s
2360:	learn: 0.2132274	test: 0.2245955	best: 0.2245955 (2360)	total: 36.7s	remaining: 36.8s
2380:	learn: 0.2130548	test: 0.2245156	best: 0.2245156 (2380)	total: 37s	remaining: 36.5s
2400:	learn: 0.2128668	test: 0.2244182	best: 0.2244182 (2400)	total: 37.3s	remaining: 36.2s
2420:	learn: 0.2126627	test: 0.2243055	best: 0.2243055 (2420)	total: 37.6s	remaining: 35.9s
2440:	learn: 0.2124918	test: 0.2242320	best: 0.2242320 (2440)	total: 37.9s	remaining: 35.6s
2460:	learn: 0.2123290	test: 0.2241573	best: 0.2241573 (2460)	total: 38.2s	remaining: 35.3s
2480:	learn: 0.2121612	test: 0.2240778	best: 0.2240778 (2480)	total: 38.5s	remaining: 35s
2500:	learn: 0.2119470	test: 0.2239475	best: 0.2239475 (2500)	total: 38.9s	remaining: 34.7s
2520:	learn: 0.2117439	test: 0.2238540	best: 0.2238540 (2520)	total: 39.2s	remaining: 34.3s
2540:	learn: 0.2115706	test: 0.2237740	best: 0.2237740 (2540)	total: 39.5s	remaining: 34s
2560:	learn: 0.2114138	test: 0.2237132	best: 0.2237121 (2559)	total: 39.8s	remaining: 33.7s
2580:	learn: 0.2112347	test: 0.2236191	best: 0.2236191 (2580)	total: 40.1s	remaining: 33.4s
2600:	learn: 0.2110491	test: 0.2235273	best: 0.2235273 (2600)	total: 40.4s	remaining: 33.1s
2620:	learn: 0.2108698	test: 0.2234429	best: 0.2234429 (2619)	total: 40.7s	remaining: 32.8s
2640:	learn: 0.2106876	test: 0.2233751	best: 0.2233751 (2640)	total: 41s	remaining: 32.5s
2660:	learn: 0.2105043	test: 0.2232713	best: 0.2232713 (2660)	total: 41.3s	remaining: 32.2s
2680:	learn: 0.2103512	test: 0.2232130	best: 0.2232130 (2680)	total: 41.6s	remaining: 31.9s
2700:	learn: 0.2101967	test: 0.2231381	best: 0.2231381 (2700)	total: 41.9s	remaining: 31.5s
2720:	learn: 0.2100212	test: 0.2230463	best: 0.2230463 (2720)	total: 42.3s	remaining: 31.2s
2740:	learn: 0.2098451	test: 0.2229741	best: 0.2229741 (2740)	total: 42.6s	remaining: 30.9s
2760:	learn: 0.2096740	test: 0.2229150	best: 0.2229150 (2760)	total: 42.9s	remaining: 30.6s
2780:	learn: 0.2095191	test: 0.2228536	best: 0.2228514 (2779)	total: 43.2s	remaining: 30.3s
2800:	learn: 0.2093533	test: 0.2227508	best: 0.2227463 (2799)	total: 43.5s	remaining: 30s
2820:	learn: 0.2092104	test: 0.2226947	best: 0.2226947 (2820)	total: 43.8s	remaining: 29.7s
2840:	learn: 0.2090385	test: 0.2226094	best: 0.2226094 (2840)	total: 44.1s	remaining: 29.4s
2860:	learn: 0.2088840	test: 0.2225419	best: 0.2225419 (2860)	total: 44.4s	remaining: 29s
2880:	learn: 0.2087192	test: 0.2224858	best: 0.2224843 (2875)	total: 44.7s	remaining: 28.7s
2900:	learn: 0.2085168	test: 0.2223887	best: 0.2223887 (2900)	total: 45s	remaining: 28.4s
2920:	learn: 0.2083642	test: 0.2223369	best: 0.2223368 (2918)	total: 45.3s	remaining: 28.1s
2940:	learn: 0.2082244	test: 0.2222755	best: 0.2222755 (2940)	total: 45.7s	remaining: 27.8s
2960:	learn: 0.2080613	test: 0.2222178	best: 0.2222178 (2960)	total: 46s	remaining: 27.5s
2980:	learn: 0.2078912	test: 0.2221457	best: 0.2221449 (2978)	total: 46.3s	remaining: 27.2s
3000:	learn: 0.2077377	test: 0.2220713	best: 0.2220713 (3000)	total: 46.6s	remaining: 26.9s
3020:	learn: 0.2075738	test: 0.2220081	best: 0.2220081 (3020)	total: 46.9s	remaining: 26.6s
3040:	learn: 0.2074212	test: 0.2219578	best: 0.2219578 (3040)	total: 47.2s	remaining: 26.2s
3060:	learn: 0.2072719	test: 0.2219133	best: 0.2219110 (3059)	total: 47.5s	remaining: 25.9s
3080:	learn: 0.2071022	test: 0.2218294	best: 0.2218294 (3080)	total: 47.8s	remaining: 25.6s
3100:	learn: 0.2069390	test: 0.2217863	best: 0.2217863 (3100)	total: 48.1s	remaining: 25.3s
3120:	learn: 0.2067653	test: 0.2217134	best: 0.2217134 (3120)	total: 48.4s	remaining: 25s
3140:	learn: 0.2066172	test: 0.2216531	best: 0.2216509 (3139)	total: 48.8s	remaining: 24.7s
3160:	learn: 0.2064453	test: 0.2215823	best: 0.2215823 (3160)	total: 49.1s	remaining: 24.4s
3180:	learn: 0.2062897	test: 0.2215336	best: 0.2215336 (3180)	total: 49.4s	remaining: 24.1s
3200:	learn: 0.2061409	test: 0.2214596	best: 0.2214596 (3200)	total: 49.7s	remaining: 23.8s
3220:	learn: 0.2060005	test: 0.2214106	best: 0.2214106 (3220)	total: 50s	remaining: 23.4s
3240:	learn: 0.2058640	test: 0.2213549	best: 0.2213549 (3240)	total: 50.3s	remaining: 23.1s
3260:	learn: 0.2057187	test: 0.2213037	best: 0.2213007 (3259)	total: 50.6s	remaining: 22.8s
3280:	learn: 0.2055618	test: 0.2212390	best: 0.2212390 (3280)	total: 50.9s	remaining: 22.5s
3300:	learn: 0.2053940	test: 0.2211609	best: 0.2211609 (3300)	total: 51.2s	remaining: 22.2s
3320:	learn: 0.2052674	test: 0.2211186	best: 0.2211175 (3319)	total: 51.5s	remaining: 21.9s
3340:	learn: 0.2051287	test: 0.2210759	best: 0.2210747 (3339)	total: 51.8s	remaining: 21.6s
3360:	learn: 0.2049985	test: 0.2210505	best: 0.2210505 (3360)	total: 52.1s	remaining: 21.3s
3380:	learn: 0.2048514	test: 0.2209985	best: 0.2209985 (3380)	total: 52.4s	remaining: 21s
3400:	learn: 0.2047231	test: 0.2209597	best: 0.2209597 (3400)	total: 52.8s	remaining: 20.6s
3420:	learn: 0.2045826	test: 0.2209022	best: 0.2209022 (3420)	total: 53.1s	remaining: 20.3s
3440:	learn: 0.2044400	test: 0.2208488	best: 0.2208475 (3439)	total: 53.4s	remaining: 20s
3460:	learn: 0.2043150	test: 0.2208044	best: 0.2208038 (3458)	total: 53.7s	remaining: 19.7s
3480:	learn: 0.2041561	test: 0.2207292	best: 0.2207292 (3480)	total: 54s	remaining: 19.4s
3500:	learn: 0.2040079	test: 0.2206650	best: 0.2206650 (3500)	total: 54.3s	remaining: 19.1s
3520:	learn: 0.2038499	test: 0.2205945	best: 0.2205945 (3520)	total: 54.6s	remaining: 18.8s
3540:	learn: 0.2037152	test: 0.2205203	best: 0.2205203 (3540)	total: 54.9s	remaining: 18.5s
3560:	learn: 0.2035896	test: 0.2204894	best: 0.2204873 (3558)	total: 55.2s	remaining: 18.2s
3580:	learn: 0.2034610	test: 0.2204512	best: 0.2204454 (3576)	total: 55.5s	remaining: 17.8s
3600:	learn: 0.2033299	test: 0.2203955	best: 0.2203955 (3600)	total: 55.8s	remaining: 17.5s
3620:	learn: 0.2032000	test: 0.2203476	best: 0.2203476 (3620)	total: 56.2s	remaining: 17.2s
3640:	learn: 0.2030609	test: 0.2202875	best: 0.2202875 (3640)	total: 56.5s	remaining: 16.9s
3660:	learn: 0.2029235	test: 0.2202373	best: 0.2202371 (3659)	total: 56.8s	remaining: 16.6s
3680:	learn: 0.2027923	test: 0.2201900	best: 0.2201900 (3680)	total: 57.1s	remaining: 16.3s
3700:	learn: 0.2026541	test: 0.2201399	best: 0.2201399 (3700)	total: 57.4s	remaining: 16s
3720:	learn: 0.2025062	test: 0.2200774	best: 0.2200774 (3720)	total: 57.7s	remaining: 15.7s
3740:	learn: 0.2023710	test: 0.2200244	best: 0.2200244 (3740)	total: 58s	remaining: 15.4s
3760:	learn: 0.2022573	test: 0.2199770	best: 0.2199770 (3760)	total: 58.3s	remaining: 15.1s
3780:	learn: 0.2021170	test: 0.2199296	best: 0.2199296 (3780)	total: 58.6s	remaining: 14.7s
3800:	learn: 0.2019795	test: 0.2198840	best: 0.2198840 (3800)	total: 58.9s	remaining: 14.4s
3820:	learn: 0.2018340	test: 0.2198352	best: 0.2198352 (3820)	total: 59.2s	remaining: 14.1s
3840:	learn: 0.2016859	test: 0.2197957	best: 0.2197957 (3840)	total: 59.5s	remaining: 13.8s
3860:	learn: 0.2015587	test: 0.2197703	best: 0.2197701 (3859)	total: 59.8s	remaining: 13.5s
3880:	learn: 0.2014230	test: 0.2197250	best: 0.2197231 (3877)	total: 1m	remaining: 13.2s
3900:	learn: 0.2013048	test: 0.2197009	best: 0.2196993 (3899)	total: 1m	remaining: 12.9s
3920:	learn: 0.2011821	test: 0.2196762	best: 0.2196762 (3920)	total: 1m	remaining: 12.6s
3940:	learn: 0.2010567	test: 0.2196558	best: 0.2196558 (3940)	total: 1m 1s	remaining: 12.3s
3960:	learn: 0.2009204	test: 0.2196069	best: 0.2196069 (3960)	total: 1m 1s	remaining: 11.9s
3980:	learn: 0.2007951	test: 0.2195495	best: 0.2195495 (3980)	total: 1m 1s	remaining: 11.6s
4000:	learn: 0.2006592	test: 0.2194785	best: 0.2194785 (4000)	total: 1m 2s	remaining: 11.3s
4020:	learn: 0.2005213	test: 0.2194317	best: 0.2194317 (4020)	total: 1m 2s	remaining: 11s
4040:	learn: 0.2003737	test: 0.2193897	best: 0.2193897 (4040)	total: 1m 2s	remaining: 10.7s
4060:	learn: 0.2002510	test: 0.2193444	best: 0.2193444 (4060)	total: 1m 2s	remaining: 10.4s
4080:	learn: 0.2001170	test: 0.2193115	best: 0.2193115 (4080)	total: 1m 3s	remaining: 10.1s
4100:	learn: 0.1999886	test: 0.2192643	best: 0.2192643 (4100)	total: 1m 3s	remaining: 9.78s
4120:	learn: 0.1998669	test: 0.2192295	best: 0.2192285 (4119)	total: 1m 3s	remaining: 9.47s
4140:	learn: 0.1997619	test: 0.2191947	best: 0.2191947 (4140)	total: 1m 4s	remaining: 9.16s
4160:	learn: 0.1996095	test: 0.2191249	best: 0.2191249 (4160)	total: 1m 4s	remaining: 8.85s
4180:	learn: 0.1994849	test: 0.2190702	best: 0.2190702 (4180)	total: 1m 4s	remaining: 8.54s
4200:	learn: 0.1993437	test: 0.2190294	best: 0.2190294 (4200)	total: 1m 5s	remaining: 8.23s
4220:	learn: 0.1992296	test: 0.2189804	best: 0.2189802 (4219)	total: 1m 5s	remaining: 7.92s
4240:	learn: 0.1991066	test: 0.2189467	best: 0.2189467 (4240)	total: 1m 5s	remaining: 7.61s
4260:	learn: 0.1989849	test: 0.2189025	best: 0.2189025 (4260)	total: 1m 6s	remaining: 7.3s
4280:	learn: 0.1988495	test: 0.2188504	best: 0.2188504 (4280)	total: 1m 6s	remaining: 6.99s
4300:	learn: 0.1987289	test: 0.2188051	best: 0.2188013 (4298)	total: 1m 6s	remaining: 6.68s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404102	test: 0.6404601	best: 0.6404601 (0)	total: 8.88ms	remaining: 8.88ms
1:	learn: 0.5954186	test: 0.5955452	best: 0.5955452 (1)	total: 17.6ms	remaining: 0us
bestTest = 0.5955451542
bestIteration = 1
0:	learn: 0.6415199	test: 0.6416980	best: 0.6416980 (0)	total: 15.7ms	remaining: 1m 15s
20:	learn: 0.3423868	test: 0.3427163	best: 0.3427163 (20)	total: 322ms	remaining: 1m 13s
40:	learn: 0.3097249	test: 0.3103510	best: 0.3103510 (40)	total: 635ms	remaining: 1m 13s
60:	learn: 0.2974974	test: 0.2983806	best: 0.2983806 (60)	total: 945ms	remaining: 1m 13s
80:	learn: 0.2897528	test: 0.2906865	best: 0.2906865 (80)	total: 1.26s	remaining: 1m 13s
100:	learn: 0.2836697	test: 0.2847019	best: 0.2847019 (100)	total: 1.57s	remaining: 1m 13s
120:	learn: 0.2792307	test: 0.2803448	best: 0.2803448 (120)	total: 1.89s	remaining: 1m 13s
140:	learn: 0.2757663	test: 0.2769139	best: 0.2769139 (140)	total: 2.21s	remaining: 1m 12s
160:	learn: 0.2722652	test: 0.2733551	best: 0.2733551 (160)	total: 2.53s	remaining: 1m 12s
180:	learn: 0.2698717	test: 0.2710517	best: 0.2710517 (180)	total: 2.85s	remaining: 1m 12s
200:	learn: 0.2677693	test: 0.2690264	best: 0.2690264 (200)	total: 3.16s	remaining: 1m 12s
220:	learn: 0.2654516	test: 0.2667202	best: 0.2667202 (220)	total: 3.48s	remaining: 1m 12s
240:	learn: 0.2633397	test: 0.2646244	best: 0.2646244 (240)	total: 3.8s	remaining: 1m 11s
260:	learn: 0.2615734	test: 0.2629406	best: 0.2629406 (260)	total: 4.11s	remaining: 1m 11s
280:	learn: 0.2597548	test: 0.2611602	best: 0.2611602 (280)	total: 4.43s	remaining: 1m 11s
300:	learn: 0.2580217	test: 0.2594907	best: 0.2594907 (300)	total: 4.78s	remaining: 1m 11s
320:	learn: 0.2564868	test: 0.2580828	best: 0.2580828 (320)	total: 5.1s	remaining: 1m 11s
340:	learn: 0.2550558	test: 0.2566556	best: 0.2566556 (340)	total: 5.42s	remaining: 1m 10s
360:	learn: 0.2536498	test: 0.2552391	best: 0.2552391 (360)	total: 5.74s	remaining: 1m 10s
380:	learn: 0.2524491	test: 0.2540151	best: 0.2540151 (380)	total: 6.05s	remaining: 1m 10s
400:	learn: 0.2513370	test: 0.2530247	best: 0.2530247 (400)	total: 6.37s	remaining: 1m 9s
420:	learn: 0.2502295	test: 0.2520187	best: 0.2520187 (420)	total: 6.68s	remaining: 1m 9s
440:	learn: 0.2490363	test: 0.2508844	best: 0.2508844 (440)	total: 7s	remaining: 1m 9s
460:	learn: 0.2480012	test: 0.2498698	best: 0.2498698 (460)	total: 7.32s	remaining: 1m 8s
480:	learn: 0.2471746	test: 0.2491899	best: 0.2491899 (480)	total: 7.63s	remaining: 1m 8s
500:	learn: 0.2462480	test: 0.2483276	best: 0.2483276 (500)	total: 7.94s	remaining: 1m 8s
520:	learn: 0.2454490	test: 0.2476691	best: 0.2476691 (520)	total: 8.25s	remaining: 1m 7s
540:	learn: 0.2445721	test: 0.2469408	best: 0.2469408 (540)	total: 8.56s	remaining: 1m 7s
560:	learn: 0.2438094	test: 0.2462154	best: 0.2462154 (560)	total: 8.88s	remaining: 1m 7s
580:	learn: 0.2430021	test: 0.2454835	best: 0.2454835 (580)	total: 9.2s	remaining: 1m 6s
600:	learn: 0.2423096	test: 0.2448510	best: 0.2448510 (600)	total: 9.51s	remaining: 1m 6s
620:	learn: 0.2416785	test: 0.2443521	best: 0.2443521 (620)	total: 9.82s	remaining: 1m 6s
640:	learn: 0.2410156	test: 0.2437850	best: 0.2437850 (640)	total: 10.1s	remaining: 1m 5s
660:	learn: 0.2403400	test: 0.2432049	best: 0.2432049 (660)	total: 10.4s	remaining: 1m 5s
680:	learn: 0.2397076	test: 0.2426814	best: 0.2426814 (680)	total: 10.8s	remaining: 1m 5s
700:	learn: 0.2389962	test: 0.2420588	best: 0.2420588 (700)	total: 11.1s	remaining: 1m 4s
720:	learn: 0.2383776	test: 0.2415197	best: 0.2415197 (720)	total: 11.4s	remaining: 1m 4s
740:	learn: 0.2377277	test: 0.2409926	best: 0.2409926 (740)	total: 11.7s	remaining: 1m 4s
760:	learn: 0.2372361	test: 0.2406425	best: 0.2406425 (760)	total: 12s	remaining: 1m 3s
780:	learn: 0.2367824	test: 0.2403115	best: 0.2403115 (780)	total: 12.3s	remaining: 1m 3s
800:	learn: 0.2362224	test: 0.2398183	best: 0.2398183 (800)	total: 12.6s	remaining: 1m 3s
820:	learn: 0.2356597	test: 0.2393155	best: 0.2393155 (820)	total: 13s	remaining: 1m 2s
840:	learn: 0.2351348	test: 0.2389187	best: 0.2389187 (840)	total: 13.3s	remaining: 1m 2s
860:	learn: 0.2345933	test: 0.2384595	best: 0.2384595 (860)	total: 13.6s	remaining: 1m 2s
880:	learn: 0.2341146	test: 0.2380731	best: 0.2380731 (880)	total: 13.9s	remaining: 1m 1s
900:	learn: 0.2337125	test: 0.2377602	best: 0.2377602 (900)	total: 14.2s	remaining: 1m 1s
920:	learn: 0.2332918	test: 0.2374369	best: 0.2374369 (920)	total: 14.5s	remaining: 1m 1s
940:	learn: 0.2328131	test: 0.2370480	best: 0.2370480 (940)	total: 14.8s	remaining: 1m
960:	learn: 0.2323724	test: 0.2367028	best: 0.2367028 (960)	total: 15.1s	remaining: 1m
980:	learn: 0.2319452	test: 0.2363605	best: 0.2363605 (980)	total: 15.4s	remaining: 1m
1000:	learn: 0.2315164	test: 0.2359992	best: 0.2359992 (1000)	total: 15.8s	remaining: 59.8s
1020:	learn: 0.2311878	test: 0.2357552	best: 0.2357552 (1020)	total: 16.1s	remaining: 59.4s
1040:	learn: 0.2308080	test: 0.2354554	best: 0.2354554 (1040)	total: 16.4s	remaining: 59.1s
1060:	learn: 0.2304596	test: 0.2351686	best: 0.2351686 (1060)	total: 16.7s	remaining: 58.8s
1080:	learn: 0.2301094	test: 0.2349173	best: 0.2349173 (1080)	total: 17s	remaining: 58.4s
1100:	learn: 0.2297208	test: 0.2346277	best: 0.2346277 (1100)	total: 17.3s	remaining: 58.1s
1120:	learn: 0.2293241	test: 0.2343616	best: 0.2343616 (1120)	total: 17.6s	remaining: 57.8s
1140:	learn: 0.2289192	test: 0.2340594	best: 0.2340594 (1140)	total: 17.9s	remaining: 57.4s
1160:	learn: 0.2285642	test: 0.2337809	best: 0.2337809 (1160)	total: 18.2s	remaining: 57.1s
1180:	learn: 0.2282161	test: 0.2335376	best: 0.2335376 (1180)	total: 18.6s	remaining: 56.8s
1200:	learn: 0.2278634	test: 0.2332365	best: 0.2332365 (1200)	total: 18.9s	remaining: 56.4s
1220:	learn: 0.2275026	test: 0.2329709	best: 0.2329709 (1220)	total: 19.2s	remaining: 56.1s
1240:	learn: 0.2272017	test: 0.2327613	best: 0.2327613 (1240)	total: 19.5s	remaining: 55.8s
1260:	learn: 0.2268601	test: 0.2324925	best: 0.2324925 (1260)	total: 19.8s	remaining: 55.4s
1280:	learn: 0.2265587	test: 0.2322717	best: 0.2322717 (1280)	total: 20.1s	remaining: 55.1s
1300:	learn: 0.2262696	test: 0.2320888	best: 0.2320888 (1300)	total: 20.4s	remaining: 54.8s
1320:	learn: 0.2259683	test: 0.2318481	best: 0.2318481 (1320)	total: 20.7s	remaining: 54.4s
1340:	learn: 0.2256379	test: 0.2316138	best: 0.2316138 (1340)	total: 21s	remaining: 54.1s
1360:	learn: 0.2252982	test: 0.2313805	best: 0.2313805 (1360)	total: 21.3s	remaining: 53.8s
1380:	learn: 0.2249800	test: 0.2311658	best: 0.2311658 (1380)	total: 21.6s	remaining: 53.5s
1400:	learn: 0.2246750	test: 0.2309539	best: 0.2309539 (1400)	total: 21.9s	remaining: 53.1s
1420:	learn: 0.2243692	test: 0.2307403	best: 0.2307403 (1420)	total: 22.2s	remaining: 52.8s
1440:	learn: 0.2240477	test: 0.2304948	best: 0.2304948 (1440)	total: 22.6s	remaining: 52.5s
1460:	learn: 0.2237410	test: 0.2302590	best: 0.2302590 (1460)	total: 22.9s	remaining: 52.2s
1480:	learn: 0.2234530	test: 0.2300429	best: 0.2300429 (1480)	total: 23.2s	remaining: 51.9s
1500:	learn: 0.2231834	test: 0.2298295	best: 0.2298295 (1500)	total: 23.5s	remaining: 51.6s
1520:	learn: 0.2228708	test: 0.2295989	best: 0.2295989 (1520)	total: 23.8s	remaining: 51.3s
1540:	learn: 0.2226229	test: 0.2294679	best: 0.2294679 (1540)	total: 24.1s	remaining: 51s
1560:	learn: 0.2223420	test: 0.2292938	best: 0.2292938 (1560)	total: 24.5s	remaining: 50.7s
1580:	learn: 0.2220769	test: 0.2291175	best: 0.2291170 (1579)	total: 24.8s	remaining: 50.4s
1600:	learn: 0.2218279	test: 0.2289544	best: 0.2289544 (1600)	total: 25.1s	remaining: 50.1s
1620:	learn: 0.2215663	test: 0.2287820	best: 0.2287820 (1620)	total: 25.4s	remaining: 49.7s
1640:	learn: 0.2212983	test: 0.2286407	best: 0.2286407 (1640)	total: 25.7s	remaining: 49.4s
1660:	learn: 0.2210693	test: 0.2284997	best: 0.2284997 (1660)	total: 26s	remaining: 49.1s
1680:	learn: 0.2208200	test: 0.2283532	best: 0.2283532 (1680)	total: 26.3s	remaining: 48.8s
1700:	learn: 0.2205778	test: 0.2282080	best: 0.2282080 (1700)	total: 26.6s	remaining: 48.5s
1720:	learn: 0.2203383	test: 0.2280619	best: 0.2280619 (1720)	total: 27s	remaining: 48.2s
1740:	learn: 0.2201130	test: 0.2279516	best: 0.2279516 (1740)	total: 27.3s	remaining: 47.9s
1760:	learn: 0.2198845	test: 0.2278053	best: 0.2278053 (1760)	total: 27.6s	remaining: 47.5s
1780:	learn: 0.2196357	test: 0.2276326	best: 0.2276326 (1780)	total: 27.9s	remaining: 47.2s
1800:	learn: 0.2193989	test: 0.2274908	best: 0.2274906 (1799)	total: 28.2s	remaining: 46.9s
1820:	learn: 0.2191841	test: 0.2273566	best: 0.2273566 (1820)	total: 28.5s	remaining: 46.6s
1840:	learn: 0.2189513	test: 0.2272299	best: 0.2272299 (1840)	total: 28.8s	remaining: 46.3s
1860:	learn: 0.2187615	test: 0.2271477	best: 0.2271428 (1858)	total: 29.1s	remaining: 45.9s
1880:	learn: 0.2185485	test: 0.2270169	best: 0.2270169 (1880)	total: 29.4s	remaining: 45.6s
1900:	learn: 0.2183688	test: 0.2268993	best: 0.2268993 (1900)	total: 29.8s	remaining: 45.3s
1920:	learn: 0.2180976	test: 0.2267232	best: 0.2267232 (1920)	total: 30.1s	remaining: 45s
1940:	learn: 0.2178578	test: 0.2266078	best: 0.2266066 (1939)	total: 30.4s	remaining: 44.7s
1960:	learn: 0.2176823	test: 0.2265306	best: 0.2265306 (1960)	total: 30.7s	remaining: 44.4s
1980:	learn: 0.2174084	test: 0.2263387	best: 0.2263387 (1980)	total: 31s	remaining: 44.1s
2000:	learn: 0.2172114	test: 0.2262434	best: 0.2262434 (2000)	total: 31.3s	remaining: 43.8s
2020:	learn: 0.2169868	test: 0.2261158	best: 0.2261158 (2020)	total: 31.7s	remaining: 43.5s
2040:	learn: 0.2167774	test: 0.2259976	best: 0.2259976 (2040)	total: 32s	remaining: 43.1s
2060:	learn: 0.2165977	test: 0.2259165	best: 0.2259165 (2060)	total: 32.3s	remaining: 42.8s
2080:	learn: 0.2163717	test: 0.2257679	best: 0.2257679 (2080)	total: 32.6s	remaining: 42.5s
2100:	learn: 0.2161467	test: 0.2256219	best: 0.2256219 (2100)	total: 32.9s	remaining: 42.2s
2120:	learn: 0.2159496	test: 0.2254818	best: 0.2254818 (2120)	total: 33.2s	remaining: 41.9s
2140:	learn: 0.2157127	test: 0.2253328	best: 0.2253328 (2140)	total: 33.5s	remaining: 41.6s
2160:	learn: 0.2155156	test: 0.2252239	best: 0.2252239 (2160)	total: 33.8s	remaining: 41.2s
2180:	learn: 0.2153046	test: 0.2250888	best: 0.2250888 (2180)	total: 34.1s	remaining: 40.9s
2200:	learn: 0.2151185	test: 0.2249890	best: 0.2249890 (2200)	total: 34.4s	remaining: 40.6s
2220:	learn: 0.2149459	test: 0.2248828	best: 0.2248828 (2220)	total: 34.7s	remaining: 40.3s
2240:	learn: 0.2147486	test: 0.2247729	best: 0.2247729 (2240)	total: 35s	remaining: 39.9s
2260:	learn: 0.2145426	test: 0.2246729	best: 0.2246729 (2260)	total: 35.3s	remaining: 39.6s
2280:	learn: 0.2143409	test: 0.2245567	best: 0.2245567 (2280)	total: 35.6s	remaining: 39.3s
2300:	learn: 0.2141626	test: 0.2244705	best: 0.2244659 (2298)	total: 35.9s	remaining: 39s
2320:	learn: 0.2139774	test: 0.2243782	best: 0.2243782 (2320)	total: 36.3s	remaining: 38.7s
2340:	learn: 0.2137937	test: 0.2242790	best: 0.2242790 (2340)	total: 36.6s	remaining: 38.3s
2360:	learn: 0.2136120	test: 0.2241523	best: 0.2241523 (2360)	total: 36.9s	remaining: 38s
2380:	learn: 0.2134280	test: 0.2240657	best: 0.2240657 (2380)	total: 37.2s	remaining: 37.7s
2400:	learn: 0.2132450	test: 0.2239665	best: 0.2239665 (2400)	total: 37.5s	remaining: 37.4s
2420:	learn: 0.2130561	test: 0.2238648	best: 0.2238629 (2419)	total: 37.8s	remaining: 37.1s
2440:	learn: 0.2128721	test: 0.2237838	best: 0.2237818 (2439)	total: 38.1s	remaining: 36.8s
2460:	learn: 0.2127074	test: 0.2236906	best: 0.2236906 (2460)	total: 38.4s	remaining: 36.4s
2480:	learn: 0.2125051	test: 0.2235943	best: 0.2235937 (2479)	total: 38.7s	remaining: 36.1s
2500:	learn: 0.2123251	test: 0.2235007	best: 0.2235007 (2500)	total: 39s	remaining: 35.8s
2520:	learn: 0.2121458	test: 0.2233733	best: 0.2233733 (2520)	total: 39.3s	remaining: 35.5s
2540:	learn: 0.2119807	test: 0.2233036	best: 0.2233036 (2540)	total: 39.6s	remaining: 35.2s
2560:	learn: 0.2117971	test: 0.2231931	best: 0.2231931 (2560)	total: 39.9s	remaining: 34.8s
2580:	learn: 0.2115771	test: 0.2230611	best: 0.2230611 (2580)	total: 40.2s	remaining: 34.5s
2600:	learn: 0.2113988	test: 0.2229794	best: 0.2229794 (2600)	total: 40.6s	remaining: 34.2s
2620:	learn: 0.2112277	test: 0.2228804	best: 0.2228804 (2620)	total: 40.9s	remaining: 33.9s
2640:	learn: 0.2110518	test: 0.2227886	best: 0.2227886 (2640)	total: 41.2s	remaining: 33.6s
2660:	learn: 0.2108885	test: 0.2226975	best: 0.2226975 (2660)	total: 41.5s	remaining: 33.3s
2680:	learn: 0.2107223	test: 0.2226162	best: 0.2226142 (2679)	total: 41.8s	remaining: 33s
2700:	learn: 0.2105630	test: 0.2225397	best: 0.2225397 (2700)	total: 42.1s	remaining: 32.7s
2720:	learn: 0.2103796	test: 0.2224442	best: 0.2224442 (2720)	total: 42.4s	remaining: 32.4s
2740:	learn: 0.2102118	test: 0.2223489	best: 0.2223489 (2740)	total: 42.7s	remaining: 32s
2760:	learn: 0.2100493	test: 0.2222959	best: 0.2222946 (2759)	total: 43s	remaining: 31.7s
2780:	learn: 0.2098912	test: 0.2222377	best: 0.2222377 (2780)	total: 43.3s	remaining: 31.4s
2800:	learn: 0.2097368	test: 0.2221811	best: 0.2221794 (2799)	total: 43.7s	remaining: 31.1s
2820:	learn: 0.2095747	test: 0.2220909	best: 0.2220900 (2817)	total: 44s	remaining: 30.8s
2840:	learn: 0.2094376	test: 0.2220461	best: 0.2220461 (2840)	total: 44.3s	remaining: 30.5s
2860:	learn: 0.2092651	test: 0.2219778	best: 0.2219778 (2860)	total: 44.6s	remaining: 30.1s
2880:	learn: 0.2091201	test: 0.2219271	best: 0.2219256 (2879)	total: 44.9s	remaining: 29.8s
2900:	learn: 0.2089480	test: 0.2218398	best: 0.2218398 (2900)	total: 45.2s	remaining: 29.5s
2920:	learn: 0.2087969	test: 0.2217564	best: 0.2217564 (2920)	total: 45.5s	remaining: 29.2s
2940:	learn: 0.2086608	test: 0.2217058	best: 0.2217049 (2938)	total: 45.8s	remaining: 28.9s
2960:	learn: 0.2085049	test: 0.2216431	best: 0.2216431 (2960)	total: 46.1s	remaining: 28.6s
2980:	learn: 0.2083561	test: 0.2215686	best: 0.2215686 (2980)	total: 46.4s	remaining: 28.3s
3000:	learn: 0.2081786	test: 0.2214738	best: 0.2214738 (3000)	total: 46.7s	remaining: 28s
3020:	learn: 0.2080097	test: 0.2214048	best: 0.2214048 (3020)	total: 47s	remaining: 27.6s
3040:	learn: 0.2078584	test: 0.2213464	best: 0.2213464 (3040)	total: 47.4s	remaining: 27.3s
3060:	learn: 0.2077121	test: 0.2212703	best: 0.2212703 (3060)	total: 47.7s	remaining: 27s
3080:	learn: 0.2075557	test: 0.2212098	best: 0.2212092 (3079)	total: 48s	remaining: 26.7s
3100:	learn: 0.2074046	test: 0.2211337	best: 0.2211337 (3100)	total: 48.3s	remaining: 26.4s
3120:	learn: 0.2072439	test: 0.2210393	best: 0.2210393 (3120)	total: 48.6s	remaining: 26.1s
3140:	learn: 0.2071039	test: 0.2209685	best: 0.2209673 (3137)	total: 48.9s	remaining: 25.8s
3160:	learn: 0.2069556	test: 0.2209272	best: 0.2209264 (3157)	total: 49.2s	remaining: 25.4s
3180:	learn: 0.2068186	test: 0.2208798	best: 0.2208798 (3180)	total: 49.5s	remaining: 25.1s
3200:	learn: 0.2066461	test: 0.2208005	best: 0.2207987 (3198)	total: 49.8s	remaining: 24.8s
3220:	learn: 0.2065152	test: 0.2207569	best: 0.2207552 (3216)	total: 50.1s	remaining: 24.5s
3240:	learn: 0.2063717	test: 0.2206804	best: 0.2206804 (3240)	total: 50.5s	remaining: 24.2s
3260:	learn: 0.2062184	test: 0.2206334	best: 0.2206334 (3260)	total: 50.8s	remaining: 23.9s
3280:	learn: 0.2060767	test: 0.2205738	best: 0.2205738 (3280)	total: 51.1s	remaining: 23.6s
3300:	learn: 0.2059151	test: 0.2204845	best: 0.2204845 (3300)	total: 51.4s	remaining: 23.3s
3320:	learn: 0.2057661	test: 0.2204125	best: 0.2204125 (3320)	total: 51.7s	remaining: 23s
3340:	learn: 0.2056422	test: 0.2203629	best: 0.2203629 (3340)	total: 52s	remaining: 22.6s
3360:	learn: 0.2054818	test: 0.2202905	best: 0.2202898 (3353)	total: 52.3s	remaining: 22.3s
3380:	learn: 0.2053299	test: 0.2202129	best: 0.2202129 (3380)	total: 52.6s	remaining: 22s
3400:	learn: 0.2051858	test: 0.2201450	best: 0.2201443 (3399)	total: 52.9s	remaining: 21.7s
3420:	learn: 0.2050305	test: 0.2200713	best: 0.2200713 (3420)	total: 53.2s	remaining: 21.4s
3440:	learn: 0.2048771	test: 0.2200090	best: 0.2200090 (3440)	total: 53.5s	remaining: 21.1s
3460:	learn: 0.2047413	test: 0.2199483	best: 0.2199483 (3460)	total: 53.8s	remaining: 20.8s
3480:	learn: 0.2046089	test: 0.2199064	best: 0.2199061 (3479)	total: 54.2s	remaining: 20.5s
3500:	learn: 0.2044731	test: 0.2198640	best: 0.2198633 (3499)	total: 54.5s	remaining: 20.1s
3520:	learn: 0.2043192	test: 0.2198076	best: 0.2198076 (3520)	total: 54.8s	remaining: 19.8s
3540:	learn: 0.2041876	test: 0.2197606	best: 0.2197606 (3540)	total: 55.1s	remaining: 19.5s
3560:	learn: 0.2040484	test: 0.2197017	best: 0.2197017 (3560)	total: 55.4s	remaining: 19.2s
3580:	learn: 0.2039163	test: 0.2196503	best: 0.2196462 (3579)	total: 55.7s	remaining: 18.9s
3600:	learn: 0.2037684	test: 0.2195883	best: 0.2195883 (3600)	total: 56s	remaining: 18.6s
3620:	learn: 0.2036270	test: 0.2195406	best: 0.2195372 (3619)	total: 56.3s	remaining: 18.3s
3640:	learn: 0.2034884	test: 0.2194752	best: 0.2194752 (3640)	total: 56.6s	remaining: 18s
3660:	learn: 0.2033387	test: 0.2194104	best: 0.2194104 (3660)	total: 56.9s	remaining: 17.6s
3680:	learn: 0.2032099	test: 0.2193525	best: 0.2193525 (3680)	total: 57.2s	remaining: 17.3s
3700:	learn: 0.2030915	test: 0.2193099	best: 0.2193099 (3700)	total: 57.5s	remaining: 17s
3720:	learn: 0.2029588	test: 0.2192665	best: 0.2192640 (3719)	total: 57.9s	remaining: 16.7s
3740:	learn: 0.2028267	test: 0.2192089	best: 0.2192089 (3740)	total: 58.2s	remaining: 16.4s
3760:	learn: 0.2026947	test: 0.2191686	best: 0.2191680 (3759)	total: 58.5s	remaining: 16.1s
3780:	learn: 0.2025529	test: 0.2190988	best: 0.2190988 (3780)	total: 58.8s	remaining: 15.8s
3800:	learn: 0.2024085	test: 0.2190269	best: 0.2190263 (3799)	total: 59.1s	remaining: 15.5s
3820:	learn: 0.2022810	test: 0.2189927	best: 0.2189927 (3820)	total: 59.4s	remaining: 15.2s
3840:	learn: 0.2021404	test: 0.2189288	best: 0.2189288 (3840)	total: 59.7s	remaining: 14.8s
3860:	learn: 0.2019996	test: 0.2188939	best: 0.2188933 (3859)	total: 1m	remaining: 14.5s
3880:	learn: 0.2018771	test: 0.2188572	best: 0.2188572 (3880)	total: 1m	remaining: 14.2s
3900:	learn: 0.2017132	test: 0.2187757	best: 0.2187757 (3900)	total: 1m	remaining: 13.9s
3920:	learn: 0.2015672	test: 0.2187067	best: 0.2187067 (3920)	total: 1m	remaining: 13.6s
3940:	learn: 0.2014386	test: 0.2186516	best: 0.2186516 (3940)	total: 1m 1s	remaining: 13.3s
3960:	learn: 0.2013178	test: 0.2186186	best: 0.2186186 (3960)	total: 1m 1s	remaining: 13s
3980:	learn: 0.2012008	test: 0.2185758	best: 0.2185758 (3980)	total: 1m 1s	remaining: 12.7s
4000:	learn: 0.2010776	test: 0.2185286	best: 0.2185286 (4000)	total: 1m 2s	remaining: 12.4s
4020:	learn: 0.2009546	test: 0.2184862	best: 0.2184862 (4020)	total: 1m 2s	remaining: 12s
4040:	learn: 0.2008189	test: 0.2184435	best: 0.2184433 (4038)	total: 1m 2s	remaining: 11.7s
4060:	learn: 0.2007091	test: 0.2184034	best: 0.2184027 (4059)	total: 1m 3s	remaining: 11.4s
4080:	learn: 0.2005774	test: 0.2183465	best: 0.2183465 (4080)	total: 1m 3s	remaining: 11.1s
4100:	learn: 0.2004452	test: 0.2183207	best: 0.2183198 (4099)	total: 1m 3s	remaining: 10.8s
4120:	learn: 0.2003131	test: 0.2182812	best: 0.2182812 (4120)	total: 1m 4s	remaining: 10.5s
4140:	learn: 0.2001816	test: 0.2182184	best: 0.2182184 (4140)	total: 1m 4s	remaining: 10.2s
4160:	learn: 0.2000455	test: 0.2181704	best: 0.2181704 (4160)	total: 1m 4s	remaining: 9.87s
4180:	learn: 0.1999137	test: 0.2181145	best: 0.2181145 (4180)	total: 1m 4s	remaining: 9.56s
4200:	learn: 0.1998118	test: 0.2180834	best: 0.2180834 (4200)	total: 1m 5s	remaining: 9.25s
4220:	learn: 0.1996774	test: 0.2180460	best: 0.2180460 (4220)	total: 1m 5s	remaining: 8.94s
4240:	learn: 0.1995526	test: 0.2179979	best: 0.2179979 (4240)	total: 1m 5s	remaining: 8.62s
4260:	learn: 0.1994403	test: 0.2179692	best: 0.2179692 (4260)	total: 1m 6s	remaining: 8.31s
4280:	learn: 0.1993373	test: 0.2179289	best: 0.2179289 (4280)	total: 1m 6s	remaining: 8s
4300:	learn: 0.1992195	test: 0.2179058	best: 0.2179058 (4300)	total: 1m 6s	remaining: 7.69s
4320:	learn: 0.1991055	test: 0.2178777	best: 0.2178777 (4320)	total: 1m 7s	remaining: 7.38s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404743	test: 0.6403641	best: 0.6403641 (0)	total: 9.27ms	remaining: 9.27ms
1:	learn: 0.5956648	test: 0.5954566	best: 0.5954566 (1)	total: 18.2ms	remaining: 0us
bestTest = 0.5954565956
bestIteration = 1
0:	learn: 0.6415009	test: 0.6415957	best: 0.6415957 (0)	total: 15.7ms	remaining: 1m 14s
20:	learn: 0.3413624	test: 0.3411381	best: 0.3411381 (20)	total: 362ms	remaining: 1m 20s
40:	learn: 0.3089858	test: 0.3088938	best: 0.3088938 (40)	total: 681ms	remaining: 1m 17s
60:	learn: 0.2959662	test: 0.2958555	best: 0.2958555 (60)	total: 1.03s	remaining: 1m 18s
80:	learn: 0.2888870	test: 0.2889514	best: 0.2889514 (80)	total: 1.35s	remaining: 1m 17s
100:	learn: 0.2838575	test: 0.2840006	best: 0.2840006 (100)	total: 1.7s	remaining: 1m 17s
120:	learn: 0.2795582	test: 0.2797537	best: 0.2797537 (120)	total: 2.02s	remaining: 1m 16s
140:	learn: 0.2761653	test: 0.2764277	best: 0.2764277 (140)	total: 2.34s	remaining: 1m 16s
160:	learn: 0.2727806	test: 0.2731094	best: 0.2731094 (160)	total: 2.67s	remaining: 1m 15s
180:	learn: 0.2699034	test: 0.2702773	best: 0.2702773 (180)	total: 2.99s	remaining: 1m 14s
200:	learn: 0.2676313	test: 0.2681548	best: 0.2681548 (200)	total: 3.31s	remaining: 1m 14s
220:	learn: 0.2652974	test: 0.2659439	best: 0.2659439 (220)	total: 3.63s	remaining: 1m 13s
240:	learn: 0.2632930	test: 0.2640263	best: 0.2640263 (240)	total: 3.96s	remaining: 1m 13s
260:	learn: 0.2616159	test: 0.2624066	best: 0.2624066 (260)	total: 4.27s	remaining: 1m 12s
280:	learn: 0.2600620	test: 0.2608945	best: 0.2608945 (280)	total: 4.59s	remaining: 1m 12s
300:	learn: 0.2585080	test: 0.2593899	best: 0.2593899 (300)	total: 4.91s	remaining: 1m 11s
320:	learn: 0.2569557	test: 0.2578893	best: 0.2578893 (320)	total: 5.23s	remaining: 1m 11s
340:	learn: 0.2554733	test: 0.2565045	best: 0.2565045 (340)	total: 5.55s	remaining: 1m 11s
360:	learn: 0.2540535	test: 0.2551880	best: 0.2551880 (360)	total: 5.87s	remaining: 1m 10s
380:	learn: 0.2525090	test: 0.2537487	best: 0.2537487 (380)	total: 6.19s	remaining: 1m 10s
400:	learn: 0.2512432	test: 0.2525749	best: 0.2525749 (400)	total: 6.51s	remaining: 1m 10s
420:	learn: 0.2500974	test: 0.2515444	best: 0.2515444 (420)	total: 6.83s	remaining: 1m 9s
440:	learn: 0.2490829	test: 0.2506305	best: 0.2506305 (440)	total: 7.14s	remaining: 1m 9s
460:	learn: 0.2482175	test: 0.2498577	best: 0.2498577 (460)	total: 7.45s	remaining: 1m 8s
480:	learn: 0.2472809	test: 0.2489985	best: 0.2489985 (480)	total: 7.77s	remaining: 1m 8s
500:	learn: 0.2464253	test: 0.2482213	best: 0.2482213 (500)	total: 8.08s	remaining: 1m 7s
520:	learn: 0.2455698	test: 0.2474595	best: 0.2474595 (520)	total: 8.39s	remaining: 1m 7s
540:	learn: 0.2447140	test: 0.2467150	best: 0.2467150 (540)	total: 8.71s	remaining: 1m 7s
560:	learn: 0.2440377	test: 0.2461424	best: 0.2461424 (560)	total: 9.03s	remaining: 1m 6s
580:	learn: 0.2432217	test: 0.2454716	best: 0.2454716 (580)	total: 9.37s	remaining: 1m 6s
600:	learn: 0.2424817	test: 0.2448095	best: 0.2448095 (600)	total: 9.7s	remaining: 1m 6s
620:	learn: 0.2416840	test: 0.2441490	best: 0.2441490 (620)	total: 10s	remaining: 1m 6s
640:	learn: 0.2409289	test: 0.2434904	best: 0.2434904 (640)	total: 10.3s	remaining: 1m 5s
660:	learn: 0.2402865	test: 0.2429515	best: 0.2429515 (660)	total: 10.6s	remaining: 1m 5s
680:	learn: 0.2396488	test: 0.2423911	best: 0.2423911 (680)	total: 11s	remaining: 1m 4s
700:	learn: 0.2390098	test: 0.2418549	best: 0.2418549 (700)	total: 11.3s	remaining: 1m 4s
720:	learn: 0.2384816	test: 0.2414465	best: 0.2414465 (720)	total: 11.6s	remaining: 1m 4s
740:	learn: 0.2378241	test: 0.2408517	best: 0.2408517 (740)	total: 11.9s	remaining: 1m 3s
760:	learn: 0.2371953	test: 0.2403164	best: 0.2403164 (760)	total: 12.2s	remaining: 1m 3s
780:	learn: 0.2366377	test: 0.2398270	best: 0.2398270 (780)	total: 12.5s	remaining: 1m 3s
800:	learn: 0.2360487	test: 0.2393599	best: 0.2393599 (800)	total: 12.8s	remaining: 1m 2s
820:	learn: 0.2355642	test: 0.2389369	best: 0.2389369 (820)	total: 13.2s	remaining: 1m 2s
840:	learn: 0.2350782	test: 0.2385408	best: 0.2385408 (840)	total: 13.5s	remaining: 1m 2s
860:	learn: 0.2345617	test: 0.2381523	best: 0.2381523 (860)	total: 13.8s	remaining: 1m 1s
880:	learn: 0.2341117	test: 0.2378591	best: 0.2378591 (880)	total: 14.1s	remaining: 1m 1s
900:	learn: 0.2336414	test: 0.2374922	best: 0.2374922 (900)	total: 14.4s	remaining: 1m 1s
920:	learn: 0.2331656	test: 0.2371403	best: 0.2371403 (920)	total: 14.7s	remaining: 1m
940:	learn: 0.2327052	test: 0.2367691	best: 0.2367691 (940)	total: 15s	remaining: 1m
960:	learn: 0.2323060	test: 0.2364996	best: 0.2364996 (960)	total: 15.3s	remaining: 60s
980:	learn: 0.2319068	test: 0.2362239	best: 0.2362239 (980)	total: 15.7s	remaining: 59.6s
1000:	learn: 0.2315076	test: 0.2359029	best: 0.2359029 (1000)	total: 16s	remaining: 59.2s
1020:	learn: 0.2311257	test: 0.2356376	best: 0.2356376 (1020)	total: 16.3s	remaining: 58.9s
1040:	learn: 0.2307090	test: 0.2353129	best: 0.2353129 (1040)	total: 16.6s	remaining: 58.6s
1060:	learn: 0.2302996	test: 0.2350126	best: 0.2350126 (1060)	total: 16.9s	remaining: 58.2s
1080:	learn: 0.2298701	test: 0.2346781	best: 0.2346781 (1080)	total: 17.2s	remaining: 57.9s
1100:	learn: 0.2295512	test: 0.2344463	best: 0.2344463 (1100)	total: 17.5s	remaining: 57.5s
1120:	learn: 0.2292305	test: 0.2342242	best: 0.2342242 (1120)	total: 17.8s	remaining: 57.2s
1140:	learn: 0.2288734	test: 0.2339661	best: 0.2339661 (1140)	total: 18.2s	remaining: 56.9s
1160:	learn: 0.2285540	test: 0.2337531	best: 0.2337531 (1160)	total: 18.5s	remaining: 56.5s
1180:	learn: 0.2281263	test: 0.2333938	best: 0.2333938 (1180)	total: 18.8s	remaining: 56.2s
1200:	learn: 0.2278216	test: 0.2331811	best: 0.2331811 (1200)	total: 19.1s	remaining: 55.9s
1220:	learn: 0.2274813	test: 0.2329480	best: 0.2329480 (1220)	total: 19.4s	remaining: 55.5s
1240:	learn: 0.2272078	test: 0.2327797	best: 0.2327797 (1240)	total: 19.7s	remaining: 55.2s
1260:	learn: 0.2268470	test: 0.2325143	best: 0.2325143 (1260)	total: 20s	remaining: 54.8s
1280:	learn: 0.2265145	test: 0.2322949	best: 0.2322949 (1280)	total: 20.3s	remaining: 54.5s
1300:	learn: 0.2262129	test: 0.2321065	best: 0.2321065 (1300)	total: 20.6s	remaining: 54.1s
1320:	learn: 0.2258661	test: 0.2318809	best: 0.2318809 (1320)	total: 20.9s	remaining: 53.8s
1340:	learn: 0.2255712	test: 0.2317177	best: 0.2317177 (1340)	total: 21.2s	remaining: 53.4s
1360:	learn: 0.2252807	test: 0.2315043	best: 0.2315043 (1360)	total: 21.5s	remaining: 53.1s
1380:	learn: 0.2249647	test: 0.2312976	best: 0.2312976 (1380)	total: 21.8s	remaining: 52.7s
1400:	learn: 0.2246376	test: 0.2310639	best: 0.2310639 (1400)	total: 22.2s	remaining: 52.4s
1420:	learn: 0.2243623	test: 0.2308919	best: 0.2308919 (1420)	total: 22.5s	remaining: 52.1s
1440:	learn: 0.2240706	test: 0.2307025	best: 0.2307025 (1440)	total: 22.8s	remaining: 51.7s
1460:	learn: 0.2237960	test: 0.2305569	best: 0.2305569 (1460)	total: 23.1s	remaining: 51.4s
1480:	learn: 0.2235228	test: 0.2303716	best: 0.2303716 (1480)	total: 23.4s	remaining: 51s
1500:	learn: 0.2232628	test: 0.2302390	best: 0.2302390 (1500)	total: 23.7s	remaining: 50.7s
1520:	learn: 0.2229594	test: 0.2300288	best: 0.2300288 (1520)	total: 24s	remaining: 50.4s
1540:	learn: 0.2226965	test: 0.2298919	best: 0.2298919 (1540)	total: 24.3s	remaining: 50s
1560:	learn: 0.2224529	test: 0.2297361	best: 0.2297361 (1560)	total: 24.6s	remaining: 49.7s
1580:	learn: 0.2221895	test: 0.2295884	best: 0.2295884 (1580)	total: 24.9s	remaining: 49.3s
1600:	learn: 0.2219651	test: 0.2294598	best: 0.2294598 (1600)	total: 25.2s	remaining: 49s
1620:	learn: 0.2217152	test: 0.2293352	best: 0.2293352 (1620)	total: 25.5s	remaining: 48.7s
1640:	learn: 0.2214522	test: 0.2291542	best: 0.2291542 (1640)	total: 25.8s	remaining: 48.3s
1660:	learn: 0.2211475	test: 0.2289327	best: 0.2289327 (1660)	total: 26.1s	remaining: 48s
1680:	learn: 0.2208844	test: 0.2287535	best: 0.2287535 (1680)	total: 26.4s	remaining: 47.7s
1700:	learn: 0.2206465	test: 0.2286186	best: 0.2286180 (1699)	total: 26.7s	remaining: 47.4s
1720:	learn: 0.2203852	test: 0.2284379	best: 0.2284379 (1720)	total: 27s	remaining: 47s
1740:	learn: 0.2200979	test: 0.2282633	best: 0.2282633 (1740)	total: 27.3s	remaining: 46.7s
1760:	learn: 0.2198564	test: 0.2281479	best: 0.2281479 (1760)	total: 27.6s	remaining: 46.4s
1780:	learn: 0.2196190	test: 0.2280053	best: 0.2280053 (1780)	total: 27.9s	remaining: 46s
1800:	learn: 0.2193750	test: 0.2278855	best: 0.2278855 (1800)	total: 28.3s	remaining: 45.7s
1820:	learn: 0.2191595	test: 0.2277578	best: 0.2277578 (1820)	total: 28.6s	remaining: 45.4s
1840:	learn: 0.2189240	test: 0.2276078	best: 0.2276078 (1840)	total: 28.9s	remaining: 45.1s
1860:	learn: 0.2186808	test: 0.2274549	best: 0.2274549 (1860)	total: 29.2s	remaining: 44.7s
1880:	learn: 0.2184508	test: 0.2272992	best: 0.2272992 (1880)	total: 29.5s	remaining: 44.4s
1900:	learn: 0.2182166	test: 0.2271589	best: 0.2271589 (1900)	total: 29.8s	remaining: 44.1s
1920:	learn: 0.2179920	test: 0.2270387	best: 0.2270387 (1920)	total: 30.1s	remaining: 43.8s
1940:	learn: 0.2177518	test: 0.2268945	best: 0.2268945 (1940)	total: 30.4s	remaining: 43.4s
1960:	learn: 0.2175132	test: 0.2267448	best: 0.2267448 (1960)	total: 30.7s	remaining: 43.1s
1980:	learn: 0.2172999	test: 0.2266283	best: 0.2266283 (1980)	total: 31s	remaining: 42.8s
2000:	learn: 0.2170836	test: 0.2265057	best: 0.2265057 (2000)	total: 31.3s	remaining: 42.5s
2020:	learn: 0.2168647	test: 0.2264101	best: 0.2264101 (2020)	total: 31.6s	remaining: 42.2s
2040:	learn: 0.2166452	test: 0.2262813	best: 0.2262813 (2040)	total: 31.9s	remaining: 41.9s
2060:	learn: 0.2164424	test: 0.2261644	best: 0.2261634 (2059)	total: 32.3s	remaining: 41.5s
2080:	learn: 0.2162389	test: 0.2260742	best: 0.2260742 (2080)	total: 32.6s	remaining: 41.2s
2100:	learn: 0.2160220	test: 0.2259730	best: 0.2259730 (2100)	total: 32.9s	remaining: 40.9s
2120:	learn: 0.2158176	test: 0.2258857	best: 0.2258854 (2119)	total: 33.2s	remaining: 40.6s
2140:	learn: 0.2156202	test: 0.2257714	best: 0.2257714 (2140)	total: 33.5s	remaining: 40.3s
2160:	learn: 0.2154109	test: 0.2256707	best: 0.2256707 (2160)	total: 33.8s	remaining: 39.9s
2180:	learn: 0.2152004	test: 0.2255519	best: 0.2255519 (2180)	total: 34.1s	remaining: 39.6s
2200:	learn: 0.2150006	test: 0.2254417	best: 0.2254417 (2200)	total: 34.4s	remaining: 39.3s
2220:	learn: 0.2148210	test: 0.2253569	best: 0.2253569 (2220)	total: 34.7s	remaining: 39s
2240:	learn: 0.2146267	test: 0.2252631	best: 0.2252631 (2240)	total: 35s	remaining: 38.7s
2260:	learn: 0.2144240	test: 0.2251508	best: 0.2251508 (2260)	total: 35.4s	remaining: 38.4s
2280:	learn: 0.2142426	test: 0.2250749	best: 0.2250747 (2279)	total: 35.7s	remaining: 38.1s
2300:	learn: 0.2140525	test: 0.2249999	best: 0.2249999 (2300)	total: 36s	remaining: 37.8s
2320:	learn: 0.2138609	test: 0.2248907	best: 0.2248907 (2320)	total: 36.3s	remaining: 37.4s
2340:	learn: 0.2136912	test: 0.2248024	best: 0.2248024 (2340)	total: 36.6s	remaining: 37.1s
2360:	learn: 0.2134783	test: 0.2246801	best: 0.2246801 (2360)	total: 36.9s	remaining: 36.8s
2380:	learn: 0.2132469	test: 0.2245579	best: 0.2245579 (2380)	total: 37.2s	remaining: 36.5s
2400:	learn: 0.2131011	test: 0.2244839	best: 0.2244839 (2400)	total: 37.5s	remaining: 36.2s
2420:	learn: 0.2129143	test: 0.2243950	best: 0.2243950 (2420)	total: 37.8s	remaining: 35.8s
2440:	learn: 0.2127427	test: 0.2243229	best: 0.2243229 (2440)	total: 38.1s	remaining: 35.5s
2460:	learn: 0.2125883	test: 0.2242524	best: 0.2242524 (2460)	total: 38.4s	remaining: 35.2s
2480:	learn: 0.2124094	test: 0.2241398	best: 0.2241398 (2480)	total: 38.8s	remaining: 34.9s
2500:	learn: 0.2122489	test: 0.2240819	best: 0.2240786 (2499)	total: 39.1s	remaining: 34.6s
2520:	learn: 0.2120727	test: 0.2239907	best: 0.2239907 (2520)	total: 39.4s	remaining: 34.3s
2540:	learn: 0.2118907	test: 0.2239053	best: 0.2239053 (2540)	total: 39.7s	remaining: 34s
2560:	learn: 0.2117189	test: 0.2238372	best: 0.2238372 (2560)	total: 40s	remaining: 33.6s
2580:	learn: 0.2115324	test: 0.2237526	best: 0.2237526 (2580)	total: 40.3s	remaining: 33.3s
2600:	learn: 0.2113415	test: 0.2236446	best: 0.2236446 (2600)	total: 40.6s	remaining: 33s
2620:	learn: 0.2111697	test: 0.2235653	best: 0.2235639 (2619)	total: 40.9s	remaining: 32.7s
2640:	learn: 0.2110027	test: 0.2234884	best: 0.2234884 (2640)	total: 41.2s	remaining: 32.4s
2660:	learn: 0.2108310	test: 0.2234231	best: 0.2234231 (2660)	total: 41.5s	remaining: 32.1s
2680:	learn: 0.2106655	test: 0.2233486	best: 0.2233486 (2680)	total: 41.8s	remaining: 31.7s
2700:	learn: 0.2104835	test: 0.2232663	best: 0.2232663 (2700)	total: 42.1s	remaining: 31.4s
2720:	learn: 0.2103558	test: 0.2232013	best: 0.2232013 (2720)	total: 42.5s	remaining: 31.1s
2740:	learn: 0.2101726	test: 0.2231119	best: 0.2231073 (2739)	total: 42.8s	remaining: 30.8s
2760:	learn: 0.2100025	test: 0.2230479	best: 0.2230479 (2760)	total: 43.1s	remaining: 30.5s
2780:	learn: 0.2098124	test: 0.2229598	best: 0.2229598 (2780)	total: 43.4s	remaining: 30.2s
2800:	learn: 0.2095966	test: 0.2228259	best: 0.2228259 (2800)	total: 43.7s	remaining: 29.9s
2820:	learn: 0.2094259	test: 0.2227558	best: 0.2227558 (2820)	total: 44s	remaining: 29.6s
2840:	learn: 0.2092553	test: 0.2226643	best: 0.2226643 (2840)	total: 44.3s	remaining: 29.2s
2860:	learn: 0.2091124	test: 0.2226047	best: 0.2226047 (2860)	total: 44.6s	remaining: 28.9s
2880:	learn: 0.2089454	test: 0.2225209	best: 0.2225189 (2879)	total: 44.9s	remaining: 28.6s
2900:	learn: 0.2087678	test: 0.2224287	best: 0.2224287 (2900)	total: 45.2s	remaining: 28.3s
2920:	learn: 0.2086122	test: 0.2223750	best: 0.2223750 (2920)	total: 45.6s	remaining: 28s
2940:	learn: 0.2084655	test: 0.2223230	best: 0.2223230 (2940)	total: 45.9s	remaining: 27.7s
2960:	learn: 0.2083144	test: 0.2222646	best: 0.2222646 (2960)	total: 46.2s	remaining: 27.4s
2980:	learn: 0.2081623	test: 0.2222136	best: 0.2222136 (2980)	total: 46.5s	remaining: 27s
3000:	learn: 0.2080052	test: 0.2221300	best: 0.2221300 (3000)	total: 46.8s	remaining: 26.7s
3020:	learn: 0.2078644	test: 0.2220585	best: 0.2220571 (3019)	total: 47.1s	remaining: 26.4s
3040:	learn: 0.2077250	test: 0.2220280	best: 0.2220280 (3040)	total: 47.4s	remaining: 26.1s
3060:	learn: 0.2075789	test: 0.2219749	best: 0.2219735 (3057)	total: 47.7s	remaining: 25.8s
3080:	learn: 0.2074023	test: 0.2219041	best: 0.2219041 (3080)	total: 48s	remaining: 25.5s
3100:	learn: 0.2072269	test: 0.2218319	best: 0.2218319 (3100)	total: 48.3s	remaining: 25.2s
3120:	learn: 0.2070640	test: 0.2217892	best: 0.2217892 (3120)	total: 48.6s	remaining: 24.8s
3140:	learn: 0.2069198	test: 0.2217293	best: 0.2217269 (3138)	total: 48.9s	remaining: 24.5s
3160:	learn: 0.2067589	test: 0.2216628	best: 0.2216628 (3160)	total: 49.2s	remaining: 24.2s
3180:	learn: 0.2066123	test: 0.2216027	best: 0.2216027 (3180)	total: 49.6s	remaining: 23.9s
3200:	learn: 0.2064454	test: 0.2215116	best: 0.2215116 (3200)	total: 49.9s	remaining: 23.6s
3220:	learn: 0.2062967	test: 0.2214690	best: 0.2214690 (3220)	total: 50.2s	remaining: 23.3s
3240:	learn: 0.2061660	test: 0.2214222	best: 0.2214192 (3239)	total: 50.5s	remaining: 23s
3260:	learn: 0.2060246	test: 0.2213691	best: 0.2213691 (3260)	total: 50.8s	remaining: 22.6s
3280:	learn: 0.2058758	test: 0.2213112	best: 0.2213112 (3280)	total: 51.1s	remaining: 22.3s
3300:	learn: 0.2057099	test: 0.2212339	best: 0.2212339 (3300)	total: 51.4s	remaining: 22s
3320:	learn: 0.2055544	test: 0.2211790	best: 0.2211782 (3319)	total: 51.7s	remaining: 21.7s
3340:	learn: 0.2054053	test: 0.2210927	best: 0.2210927 (3340)	total: 52s	remaining: 21.4s
3360:	learn: 0.2052449	test: 0.2210288	best: 0.2210288 (3360)	total: 52.3s	remaining: 21.1s
3380:	learn: 0.2051094	test: 0.2209763	best: 0.2209761 (3379)	total: 52.6s	remaining: 20.8s
3400:	learn: 0.2049734	test: 0.2209080	best: 0.2209080 (3400)	total: 53s	remaining: 20.5s
3420:	learn: 0.2048174	test: 0.2208617	best: 0.2208617 (3420)	total: 53.3s	remaining: 20.1s
3440:	learn: 0.2046825	test: 0.2208010	best: 0.2208010 (3440)	total: 53.6s	remaining: 19.8s
3460:	learn: 0.2045430	test: 0.2207574	best: 0.2207574 (3460)	total: 53.9s	remaining: 19.5s
3480:	learn: 0.2044228	test: 0.2207178	best: 0.2207166 (3478)	total: 54.2s	remaining: 19.2s
3500:	learn: 0.2042741	test: 0.2206541	best: 0.2206541 (3500)	total: 54.5s	remaining: 18.9s
3520:	learn: 0.2041491	test: 0.2205851	best: 0.2205851 (3520)	total: 54.8s	remaining: 18.6s
3540:	learn: 0.2040016	test: 0.2205153	best: 0.2205153 (3540)	total: 55.1s	remaining: 18.3s
3560:	learn: 0.2038604	test: 0.2204883	best: 0.2204883 (3560)	total: 55.4s	remaining: 18s
3580:	learn: 0.2037311	test: 0.2204441	best: 0.2204441 (3580)	total: 55.7s	remaining: 17.6s
3600:	learn: 0.2035916	test: 0.2203938	best: 0.2203938 (3600)	total: 56s	remaining: 17.3s
3620:	learn: 0.2034728	test: 0.2203632	best: 0.2203632 (3620)	total: 56.3s	remaining: 17s
3640:	learn: 0.2033213	test: 0.2202910	best: 0.2202910 (3640)	total: 56.6s	remaining: 16.7s
3660:	learn: 0.2031887	test: 0.2202405	best: 0.2202405 (3660)	total: 57s	remaining: 16.4s
3680:	learn: 0.2030238	test: 0.2201701	best: 0.2201701 (3680)	total: 57.3s	remaining: 16.1s
3700:	learn: 0.2028985	test: 0.2201276	best: 0.2201276 (3700)	total: 57.6s	remaining: 15.8s
3720:	learn: 0.2027768	test: 0.2200958	best: 0.2200958 (3720)	total: 57.9s	remaining: 15.5s
3740:	learn: 0.2026573	test: 0.2200393	best: 0.2200393 (3740)	total: 58.2s	remaining: 15.1s
3760:	learn: 0.2025065	test: 0.2199827	best: 0.2199827 (3760)	total: 58.5s	remaining: 14.8s
3780:	learn: 0.2023732	test: 0.2199427	best: 0.2199427 (3780)	total: 58.8s	remaining: 14.5s
3800:	learn: 0.2022291	test: 0.2198930	best: 0.2198930 (3800)	total: 59.1s	remaining: 14.2s
3820:	learn: 0.2021201	test: 0.2198578	best: 0.2198577 (3819)	total: 59.4s	remaining: 13.9s
3840:	learn: 0.2020006	test: 0.2198385	best: 0.2198385 (3840)	total: 59.7s	remaining: 13.6s
3860:	learn: 0.2018654	test: 0.2198054	best: 0.2198054 (3860)	total: 1m	remaining: 13.3s
3880:	learn: 0.2017440	test: 0.2197433	best: 0.2197433 (3880)	total: 1m	remaining: 13s
3900:	learn: 0.2016116	test: 0.2196967	best: 0.2196940 (3897)	total: 1m	remaining: 12.7s
3920:	learn: 0.2014736	test: 0.2196537	best: 0.2196537 (3920)	total: 1m	remaining: 12.3s
3940:	learn: 0.2013365	test: 0.2195922	best: 0.2195922 (3940)	total: 1m 1s	remaining: 12s
3960:	learn: 0.2011966	test: 0.2195341	best: 0.2195341 (3960)	total: 1m 1s	remaining: 11.7s
3980:	learn: 0.2010846	test: 0.2195114	best: 0.2195074 (3976)	total: 1m 1s	remaining: 11.4s
4000:	learn: 0.2009573	test: 0.2194806	best: 0.2194791 (3999)	total: 1m 2s	remaining: 11.1s
4020:	learn: 0.2008099	test: 0.2194390	best: 0.2194390 (4020)	total: 1m 2s	remaining: 10.8s
4040:	learn: 0.2006836	test: 0.2194064	best: 0.2194064 (4040)	total: 1m 2s	remaining: 10.5s
4060:	learn: 0.2005610	test: 0.2193648	best: 0.2193648 (4060)	total: 1m 3s	remaining: 10.2s
4080:	learn: 0.2004254	test: 0.2193182	best: 0.2193182 (4080)	total: 1m 3s	remaining: 9.85s
4100:	learn: 0.2003016	test: 0.2192779	best: 0.2192779 (4100)	total: 1m 3s	remaining: 9.54s
4120:	learn: 0.2001805	test: 0.2192323	best: 0.2192323 (4120)	total: 1m 4s	remaining: 9.23s
4140:	learn: 0.2000350	test: 0.2191802	best: 0.2191802 (4140)	total: 1m 4s	remaining: 8.92s
4160:	learn: 0.1999164	test: 0.2191506	best: 0.2191506 (4160)	total: 1m 4s	remaining: 8.61s
4180:	learn: 0.1997994	test: 0.2191192	best: 0.2191190 (4179)	total: 1m 4s	remaining: 8.29s
4200:	learn: 0.1996688	test: 0.2190705	best: 0.2190705 (4200)	total: 1m 5s	remaining: 7.98s
4220:	learn: 0.1995245	test: 0.2190013	best: 0.2190013 (4220)	total: 1m 5s	remaining: 7.67s
4240:	learn: 0.1994110	test: 0.2189685	best: 0.2189685 (4240)	total: 1m 5s	remaining: 7.36s
4260:	learn: 0.1992812	test: 0.2189174	best: 0.2189174 (4260)	total: 1m 6s	remaining: 7.05s
4280:	learn: 0.1991731	test: 0.2188803	best: 0.2188786 (4279)	total: 1m 6s	remaining: 6.74s
4300:	learn: 0.1990615	test: 0.2188396	best: 0.2188396 (4300)	total: 1m 6s	remaining: 6.43s
4320:	learn: 0.1989304	test: 0.2188079	best: 0.2188058 (4319)	total: 1m 7s	remaining: 6.12s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6404090	test: 0.6403363	best: 0.6403363 (0)	total: 9.46ms	remaining: 9.46ms
1:	learn: 0.5954911	test: 0.5953479	best: 0.5953479 (1)	total: 18.1ms	remaining: 0us
bestTest = 0.5953478878
bestIteration = 1
0:	learn: 0.6413692	test: 0.6412265	best: 0.6412265 (0)	total: 15ms	remaining: 1m 10s
20:	learn: 0.3427894	test: 0.3417769	best: 0.3417769 (20)	total: 324ms	remaining: 1m 12s
40:	learn: 0.3095291	test: 0.3085100	best: 0.3085100 (40)	total: 635ms	remaining: 1m 12s
60:	learn: 0.2972360	test: 0.2963909	best: 0.2963909 (60)	total: 954ms	remaining: 1m 12s
80:	learn: 0.2888154	test: 0.2880355	best: 0.2880355 (80)	total: 1.27s	remaining: 1m 12s
100:	learn: 0.2841408	test: 0.2835323	best: 0.2835323 (100)	total: 1.58s	remaining: 1m 11s
120:	learn: 0.2798281	test: 0.2792997	best: 0.2792997 (120)	total: 1.9s	remaining: 1m 11s
140:	learn: 0.2761159	test: 0.2757053	best: 0.2757053 (140)	total: 2.21s	remaining: 1m 11s
160:	learn: 0.2723290	test: 0.2720805	best: 0.2720805 (160)	total: 2.54s	remaining: 1m 11s
180:	learn: 0.2695523	test: 0.2695005	best: 0.2695005 (180)	total: 2.85s	remaining: 1m 11s
200:	learn: 0.2668734	test: 0.2669363	best: 0.2669363 (200)	total: 3.17s	remaining: 1m 10s
220:	learn: 0.2647344	test: 0.2649726	best: 0.2649726 (220)	total: 3.48s	remaining: 1m 10s
240:	learn: 0.2627559	test: 0.2631618	best: 0.2631618 (240)	total: 3.8s	remaining: 1m 10s
260:	learn: 0.2604171	test: 0.2609333	best: 0.2609333 (260)	total: 4.12s	remaining: 1m 10s
280:	learn: 0.2587379	test: 0.2594497	best: 0.2594497 (280)	total: 4.43s	remaining: 1m 9s
300:	learn: 0.2571427	test: 0.2580231	best: 0.2580231 (300)	total: 4.75s	remaining: 1m 9s
320:	learn: 0.2557155	test: 0.2567934	best: 0.2567934 (320)	total: 5.06s	remaining: 1m 9s
340:	learn: 0.2543981	test: 0.2555883	best: 0.2555883 (340)	total: 5.37s	remaining: 1m 8s
360:	learn: 0.2531707	test: 0.2545440	best: 0.2545440 (360)	total: 5.68s	remaining: 1m 8s
380:	learn: 0.2519724	test: 0.2534934	best: 0.2534934 (380)	total: 6s	remaining: 1m 8s
400:	learn: 0.2507936	test: 0.2524793	best: 0.2524793 (400)	total: 6.32s	remaining: 1m 7s
420:	learn: 0.2496599	test: 0.2514157	best: 0.2514157 (420)	total: 6.64s	remaining: 1m 7s
440:	learn: 0.2486337	test: 0.2505287	best: 0.2505287 (440)	total: 6.96s	remaining: 1m 7s
460:	learn: 0.2475420	test: 0.2495677	best: 0.2495677 (460)	total: 7.27s	remaining: 1m 6s
480:	learn: 0.2465880	test: 0.2487540	best: 0.2487540 (480)	total: 7.58s	remaining: 1m 6s
500:	learn: 0.2457022	test: 0.2479859	best: 0.2479859 (500)	total: 7.9s	remaining: 1m 6s
520:	learn: 0.2448762	test: 0.2473041	best: 0.2473041 (520)	total: 8.22s	remaining: 1m 5s
540:	learn: 0.2440345	test: 0.2466151	best: 0.2466151 (540)	total: 8.53s	remaining: 1m 5s
560:	learn: 0.2432951	test: 0.2459516	best: 0.2459516 (560)	total: 8.85s	remaining: 1m 5s
580:	learn: 0.2425950	test: 0.2453849	best: 0.2453849 (580)	total: 9.17s	remaining: 1m 5s
600:	learn: 0.2417711	test: 0.2446771	best: 0.2446771 (600)	total: 9.49s	remaining: 1m 4s
620:	learn: 0.2411793	test: 0.2441965	best: 0.2441965 (620)	total: 9.8s	remaining: 1m 4s
640:	learn: 0.2404563	test: 0.2436017	best: 0.2436017 (640)	total: 10.1s	remaining: 1m 4s
660:	learn: 0.2397745	test: 0.2430135	best: 0.2430135 (660)	total: 10.4s	remaining: 1m 3s
680:	learn: 0.2391072	test: 0.2424734	best: 0.2424734 (680)	total: 10.7s	remaining: 1m 3s
700:	learn: 0.2385159	test: 0.2419999	best: 0.2419999 (700)	total: 11.1s	remaining: 1m 3s
720:	learn: 0.2379943	test: 0.2416309	best: 0.2416309 (720)	total: 11.4s	remaining: 1m 2s
740:	learn: 0.2374660	test: 0.2412661	best: 0.2412661 (740)	total: 11.7s	remaining: 1m 2s
760:	learn: 0.2368907	test: 0.2408503	best: 0.2408503 (760)	total: 12s	remaining: 1m 2s
780:	learn: 0.2362772	test: 0.2403402	best: 0.2403402 (780)	total: 12.3s	remaining: 1m 1s
800:	learn: 0.2357547	test: 0.2399363	best: 0.2399363 (800)	total: 12.6s	remaining: 1m 1s
820:	learn: 0.2352202	test: 0.2394920	best: 0.2394920 (820)	total: 12.9s	remaining: 1m 1s
840:	learn: 0.2346008	test: 0.2389967	best: 0.2389967 (840)	total: 13.2s	remaining: 1m
860:	learn: 0.2341332	test: 0.2386945	best: 0.2386945 (860)	total: 13.5s	remaining: 1m
880:	learn: 0.2336911	test: 0.2383765	best: 0.2383765 (880)	total: 13.9s	remaining: 1m
900:	learn: 0.2332282	test: 0.2380534	best: 0.2380534 (900)	total: 14.2s	remaining: 59.8s
920:	learn: 0.2327414	test: 0.2376948	best: 0.2376948 (920)	total: 14.5s	remaining: 59.4s
940:	learn: 0.2323113	test: 0.2373863	best: 0.2373863 (940)	total: 14.8s	remaining: 59.1s
960:	learn: 0.2318986	test: 0.2370527	best: 0.2370527 (960)	total: 15.1s	remaining: 58.8s
980:	learn: 0.2314252	test: 0.2367012	best: 0.2367012 (980)	total: 15.4s	remaining: 58.5s
1000:	learn: 0.2311006	test: 0.2365032	best: 0.2365032 (1000)	total: 15.7s	remaining: 58.1s
1020:	learn: 0.2306728	test: 0.2361922	best: 0.2361922 (1020)	total: 16s	remaining: 57.8s
1040:	learn: 0.2302426	test: 0.2358417	best: 0.2358417 (1040)	total: 16.3s	remaining: 57.5s
1060:	learn: 0.2298856	test: 0.2355969	best: 0.2355969 (1060)	total: 16.7s	remaining: 57.1s
1080:	learn: 0.2295211	test: 0.2353369	best: 0.2353369 (1080)	total: 17s	remaining: 56.8s
1100:	learn: 0.2291544	test: 0.2350680	best: 0.2350680 (1100)	total: 17.3s	remaining: 56.5s
1120:	learn: 0.2287525	test: 0.2348015	best: 0.2348015 (1120)	total: 17.6s	remaining: 56.2s
1140:	learn: 0.2284097	test: 0.2345583	best: 0.2345583 (1140)	total: 17.9s	remaining: 55.8s
1160:	learn: 0.2280632	test: 0.2342841	best: 0.2342841 (1160)	total: 18.2s	remaining: 55.5s
1180:	learn: 0.2277455	test: 0.2340728	best: 0.2340728 (1180)	total: 18.5s	remaining: 55.2s
1200:	learn: 0.2274191	test: 0.2338605	best: 0.2338605 (1200)	total: 18.8s	remaining: 54.9s
1220:	learn: 0.2270860	test: 0.2336671	best: 0.2336671 (1220)	total: 19.1s	remaining: 54.5s
1240:	learn: 0.2267278	test: 0.2334169	best: 0.2334169 (1240)	total: 19.4s	remaining: 54.2s
1260:	learn: 0.2264179	test: 0.2332027	best: 0.2332027 (1260)	total: 19.7s	remaining: 53.8s
1280:	learn: 0.2261090	test: 0.2329890	best: 0.2329890 (1280)	total: 20s	remaining: 53.5s
1300:	learn: 0.2258167	test: 0.2328232	best: 0.2328232 (1300)	total: 20.3s	remaining: 53.2s
1320:	learn: 0.2255214	test: 0.2326348	best: 0.2326348 (1320)	total: 20.6s	remaining: 52.8s
1340:	learn: 0.2252076	test: 0.2324330	best: 0.2324330 (1340)	total: 20.9s	remaining: 52.5s
1360:	learn: 0.2249215	test: 0.2322205	best: 0.2322205 (1360)	total: 21.2s	remaining: 52.1s
1380:	learn: 0.2246684	test: 0.2320438	best: 0.2320438 (1380)	total: 21.5s	remaining: 51.8s
1400:	learn: 0.2243991	test: 0.2318911	best: 0.2318911 (1400)	total: 21.9s	remaining: 51.5s
1420:	learn: 0.2240803	test: 0.2317065	best: 0.2317065 (1420)	total: 22.2s	remaining: 51.2s
1440:	learn: 0.2237935	test: 0.2315336	best: 0.2315336 (1440)	total: 22.5s	remaining: 50.8s
1460:	learn: 0.2235125	test: 0.2313793	best: 0.2313793 (1460)	total: 22.8s	remaining: 50.5s
1480:	learn: 0.2232352	test: 0.2312067	best: 0.2312067 (1480)	total: 23.1s	remaining: 50.2s
1500:	learn: 0.2229546	test: 0.2310348	best: 0.2310348 (1500)	total: 23.4s	remaining: 49.9s
1520:	learn: 0.2226582	test: 0.2308240	best: 0.2308240 (1520)	total: 23.7s	remaining: 49.6s
1540:	learn: 0.2223845	test: 0.2306316	best: 0.2306316 (1540)	total: 24s	remaining: 49.2s
1560:	learn: 0.2221319	test: 0.2304417	best: 0.2304417 (1560)	total: 24.3s	remaining: 48.9s
1580:	learn: 0.2218019	test: 0.2302283	best: 0.2302283 (1580)	total: 24.6s	remaining: 48.6s
1600:	learn: 0.2215521	test: 0.2300959	best: 0.2300959 (1600)	total: 24.9s	remaining: 48.3s
1620:	learn: 0.2212723	test: 0.2299271	best: 0.2299271 (1620)	total: 25.2s	remaining: 47.9s
1640:	learn: 0.2210543	test: 0.2297881	best: 0.2297881 (1640)	total: 25.5s	remaining: 47.6s
1660:	learn: 0.2208126	test: 0.2296065	best: 0.2296065 (1660)	total: 25.8s	remaining: 47.3s
1680:	learn: 0.2205322	test: 0.2294068	best: 0.2294068 (1680)	total: 26.1s	remaining: 47s
1700:	learn: 0.2202981	test: 0.2292676	best: 0.2292676 (1700)	total: 26.4s	remaining: 46.7s
1720:	learn: 0.2200796	test: 0.2291290	best: 0.2291290 (1720)	total: 26.8s	remaining: 46.3s
1740:	learn: 0.2198660	test: 0.2290276	best: 0.2290275 (1739)	total: 27.1s	remaining: 46s
1760:	learn: 0.2196105	test: 0.2288927	best: 0.2288927 (1760)	total: 27.4s	remaining: 45.7s
1780:	learn: 0.2194021	test: 0.2287948	best: 0.2287948 (1780)	total: 27.7s	remaining: 45.4s
1800:	learn: 0.2191975	test: 0.2286952	best: 0.2286952 (1800)	total: 28s	remaining: 45.1s
1820:	learn: 0.2189713	test: 0.2285683	best: 0.2285683 (1820)	total: 28.3s	remaining: 44.7s
1840:	learn: 0.2186951	test: 0.2284046	best: 0.2284046 (1840)	total: 28.6s	remaining: 44.4s
1860:	learn: 0.2184889	test: 0.2283142	best: 0.2283142 (1860)	total: 28.9s	remaining: 44.1s
1880:	learn: 0.2182892	test: 0.2282197	best: 0.2282197 (1880)	total: 29.2s	remaining: 43.8s
1900:	learn: 0.2180270	test: 0.2280533	best: 0.2280533 (1900)	total: 29.5s	remaining: 43.5s
1920:	learn: 0.2178134	test: 0.2279352	best: 0.2279352 (1920)	total: 29.8s	remaining: 43.2s
1940:	learn: 0.2175929	test: 0.2278082	best: 0.2278082 (1940)	total: 30.1s	remaining: 42.8s
1960:	learn: 0.2173817	test: 0.2277046	best: 0.2277034 (1959)	total: 30.4s	remaining: 42.5s
1980:	learn: 0.2171724	test: 0.2275888	best: 0.2275888 (1980)	total: 30.7s	remaining: 42.2s
2000:	learn: 0.2169390	test: 0.2274788	best: 0.2274788 (2000)	total: 31s	remaining: 41.9s
2020:	learn: 0.2167034	test: 0.2273185	best: 0.2273185 (2020)	total: 31.4s	remaining: 41.6s
2040:	learn: 0.2164983	test: 0.2272120	best: 0.2272105 (2039)	total: 31.7s	remaining: 41.3s
2060:	learn: 0.2162804	test: 0.2270885	best: 0.2270885 (2060)	total: 32s	remaining: 41s
2080:	learn: 0.2160669	test: 0.2269933	best: 0.2269933 (2080)	total: 32.3s	remaining: 40.6s
2100:	learn: 0.2158455	test: 0.2268702	best: 0.2268702 (2100)	total: 32.6s	remaining: 40.3s
2120:	learn: 0.2156105	test: 0.2267330	best: 0.2267330 (2120)	total: 32.9s	remaining: 40s
2140:	learn: 0.2154215	test: 0.2266490	best: 0.2266490 (2140)	total: 33.2s	remaining: 39.7s
2160:	learn: 0.2151939	test: 0.2265052	best: 0.2265052 (2160)	total: 33.5s	remaining: 39.4s
2180:	learn: 0.2149827	test: 0.2263868	best: 0.2263868 (2180)	total: 33.8s	remaining: 39.1s
2200:	learn: 0.2147876	test: 0.2263019	best: 0.2263019 (2200)	total: 34.1s	remaining: 38.8s
2220:	learn: 0.2146131	test: 0.2262074	best: 0.2262074 (2220)	total: 34.4s	remaining: 38.5s
2240:	learn: 0.2144240	test: 0.2260907	best: 0.2260907 (2240)	total: 34.7s	remaining: 38.2s
2260:	learn: 0.2142425	test: 0.2260017	best: 0.2260017 (2260)	total: 35s	remaining: 37.8s
2280:	learn: 0.2140550	test: 0.2258924	best: 0.2258924 (2280)	total: 35.3s	remaining: 37.5s
2300:	learn: 0.2138732	test: 0.2257891	best: 0.2257891 (2300)	total: 35.7s	remaining: 37.2s
2320:	learn: 0.2136757	test: 0.2257039	best: 0.2257039 (2320)	total: 36s	remaining: 36.9s
2340:	learn: 0.2135010	test: 0.2256014	best: 0.2256014 (2340)	total: 36.3s	remaining: 36.6s
2360:	learn: 0.2133395	test: 0.2255152	best: 0.2255152 (2360)	total: 36.6s	remaining: 36.3s
2380:	learn: 0.2131709	test: 0.2254340	best: 0.2254340 (2380)	total: 36.9s	remaining: 36s
2400:	learn: 0.2129779	test: 0.2253358	best: 0.2253358 (2400)	total: 37.2s	remaining: 35.6s
2420:	learn: 0.2127575	test: 0.2252059	best: 0.2252059 (2420)	total: 37.5s	remaining: 35.3s
2440:	learn: 0.2125768	test: 0.2251103	best: 0.2251098 (2439)	total: 37.8s	remaining: 35s
2460:	learn: 0.2123938	test: 0.2250107	best: 0.2250107 (2460)	total: 38.1s	remaining: 34.7s
2480:	learn: 0.2121994	test: 0.2249048	best: 0.2249048 (2480)	total: 38.4s	remaining: 34.4s
2500:	learn: 0.2120165	test: 0.2248124	best: 0.2248124 (2500)	total: 38.7s	remaining: 34.1s
2520:	learn: 0.2118584	test: 0.2247459	best: 0.2247459 (2520)	total: 39s	remaining: 33.8s
2540:	learn: 0.2116903	test: 0.2246605	best: 0.2246605 (2540)	total: 39.3s	remaining: 33.5s
2560:	learn: 0.2115033	test: 0.2245572	best: 0.2245572 (2560)	total: 39.6s	remaining: 33.1s
2580:	learn: 0.2113161	test: 0.2244486	best: 0.2244486 (2580)	total: 39.9s	remaining: 32.8s
2600:	learn: 0.2111114	test: 0.2243293	best: 0.2243293 (2600)	total: 40.2s	remaining: 32.5s
2620:	learn: 0.2109174	test: 0.2242330	best: 0.2242330 (2620)	total: 40.6s	remaining: 32.2s
2640:	learn: 0.2107072	test: 0.2241187	best: 0.2241187 (2640)	total: 40.9s	remaining: 31.9s
2660:	learn: 0.2105149	test: 0.2240071	best: 0.2240052 (2656)	total: 41.2s	remaining: 31.6s
2680:	learn: 0.2103501	test: 0.2239462	best: 0.2239462 (2680)	total: 41.5s	remaining: 31.3s
2700:	learn: 0.2101778	test: 0.2238621	best: 0.2238621 (2700)	total: 41.8s	remaining: 30.9s
2720:	learn: 0.2100129	test: 0.2237751	best: 0.2237751 (2720)	total: 42.1s	remaining: 30.6s
2740:	learn: 0.2098347	test: 0.2237081	best: 0.2237081 (2740)	total: 42.4s	remaining: 30.3s
2760:	learn: 0.2096763	test: 0.2236538	best: 0.2236538 (2760)	total: 42.7s	remaining: 30s
2780:	learn: 0.2095127	test: 0.2235757	best: 0.2235757 (2780)	total: 43s	remaining: 29.7s
2800:	learn: 0.2093641	test: 0.2235112	best: 0.2235095 (2799)	total: 43.3s	remaining: 29.4s
2820:	learn: 0.2092016	test: 0.2234481	best: 0.2234481 (2820)	total: 43.6s	remaining: 29.1s
2840:	learn: 0.2090395	test: 0.2233728	best: 0.2233728 (2840)	total: 43.9s	remaining: 28.8s
2860:	learn: 0.2088550	test: 0.2233032	best: 0.2233032 (2860)	total: 44.2s	remaining: 28.5s
2880:	learn: 0.2086925	test: 0.2232475	best: 0.2232475 (2880)	total: 44.5s	remaining: 28.2s
2900:	learn: 0.2085153	test: 0.2231742	best: 0.2231737 (2899)	total: 44.9s	remaining: 27.8s
2920:	learn: 0.2083443	test: 0.2230876	best: 0.2230876 (2920)	total: 45.2s	remaining: 27.5s
2940:	learn: 0.2081670	test: 0.2229927	best: 0.2229927 (2940)	total: 45.5s	remaining: 27.2s
2960:	learn: 0.2080137	test: 0.2229325	best: 0.2229320 (2959)	total: 45.8s	remaining: 26.9s
2980:	learn: 0.2078768	test: 0.2228628	best: 0.2228628 (2980)	total: 46.1s	remaining: 26.6s
3000:	learn: 0.2077298	test: 0.2228010	best: 0.2228010 (3000)	total: 46.4s	remaining: 26.3s
3020:	learn: 0.2075738	test: 0.2227401	best: 0.2227401 (3020)	total: 46.7s	remaining: 26s
3040:	learn: 0.2074399	test: 0.2227117	best: 0.2227102 (3039)	total: 47s	remaining: 25.7s
3060:	learn: 0.2072861	test: 0.2226580	best: 0.2226580 (3060)	total: 47.3s	remaining: 25.3s
3080:	learn: 0.2071276	test: 0.2226010	best: 0.2226010 (3080)	total: 47.6s	remaining: 25s
3100:	learn: 0.2069982	test: 0.2225382	best: 0.2225340 (3099)	total: 47.9s	remaining: 24.7s
3120:	learn: 0.2068540	test: 0.2224906	best: 0.2224906 (3120)	total: 48.2s	remaining: 24.4s
3140:	learn: 0.2066941	test: 0.2224401	best: 0.2224401 (3140)	total: 48.5s	remaining: 24.1s
3160:	learn: 0.2065353	test: 0.2223774	best: 0.2223774 (3160)	total: 48.8s	remaining: 23.8s
3180:	learn: 0.2063847	test: 0.2223052	best: 0.2223049 (3179)	total: 49.1s	remaining: 23.5s
3200:	learn: 0.2062321	test: 0.2222494	best: 0.2222494 (3200)	total: 49.4s	remaining: 23.2s
3220:	learn: 0.2060942	test: 0.2221872	best: 0.2221872 (3220)	total: 49.7s	remaining: 22.9s
3240:	learn: 0.2059510	test: 0.2221229	best: 0.2221229 (3240)	total: 50s	remaining: 22.6s
3260:	learn: 0.2058242	test: 0.2220822	best: 0.2220812 (3255)	total: 50.4s	remaining: 22.3s
3280:	learn: 0.2056599	test: 0.2220129	best: 0.2220129 (3280)	total: 50.7s	remaining: 21.9s
3300:	learn: 0.2055069	test: 0.2219441	best: 0.2219441 (3300)	total: 51s	remaining: 21.6s
3320:	learn: 0.2053633	test: 0.2218961	best: 0.2218961 (3320)	total: 51.3s	remaining: 21.3s
3340:	learn: 0.2052196	test: 0.2218117	best: 0.2218117 (3340)	total: 51.6s	remaining: 21s
3360:	learn: 0.2050729	test: 0.2217551	best: 0.2217510 (3358)	total: 51.9s	remaining: 20.7s
3380:	learn: 0.2049241	test: 0.2217105	best: 0.2217099 (3378)	total: 52.2s	remaining: 20.4s
3400:	learn: 0.2047930	test: 0.2216551	best: 0.2216551 (3400)	total: 52.5s	remaining: 20.1s
3420:	learn: 0.2046588	test: 0.2216113	best: 0.2216109 (3419)	total: 52.8s	remaining: 19.8s
3440:	learn: 0.2045173	test: 0.2215771	best: 0.2215771 (3440)	total: 53.1s	remaining: 19.5s
3460:	learn: 0.2043719	test: 0.2215190	best: 0.2215190 (3460)	total: 53.4s	remaining: 19.2s
3480:	learn: 0.2042415	test: 0.2214637	best: 0.2214637 (3480)	total: 53.8s	remaining: 18.9s
3500:	learn: 0.2041260	test: 0.2214226	best: 0.2214226 (3500)	total: 54.1s	remaining: 18.5s
3520:	learn: 0.2040073	test: 0.2213761	best: 0.2213761 (3520)	total: 54.4s	remaining: 18.2s
3540:	learn: 0.2038596	test: 0.2213018	best: 0.2213018 (3540)	total: 54.7s	remaining: 17.9s
3560:	learn: 0.2037476	test: 0.2212612	best: 0.2212612 (3560)	total: 55s	remaining: 17.6s
3580:	learn: 0.2036341	test: 0.2212312	best: 0.2212312 (3580)	total: 55.3s	remaining: 17.3s
3600:	learn: 0.2034967	test: 0.2211905	best: 0.2211905 (3600)	total: 55.6s	remaining: 17s
3620:	learn: 0.2033573	test: 0.2211312	best: 0.2211312 (3620)	total: 55.9s	remaining: 16.7s
3640:	learn: 0.2032001	test: 0.2210761	best: 0.2210751 (3638)	total: 56.2s	remaining: 16.4s
3660:	learn: 0.2030718	test: 0.2210365	best: 0.2210365 (3660)	total: 56.5s	remaining: 16.1s
3680:	learn: 0.2029404	test: 0.2209966	best: 0.2209966 (3680)	total: 56.8s	remaining: 15.8s
3700:	learn: 0.2028124	test: 0.2209456	best: 0.2209456 (3700)	total: 57.1s	remaining: 15.5s
3720:	learn: 0.2026649	test: 0.2208869	best: 0.2208869 (3720)	total: 57.5s	remaining: 15.1s
3740:	learn: 0.2025186	test: 0.2208453	best: 0.2208422 (3738)	total: 57.8s	remaining: 14.8s
3760:	learn: 0.2023731	test: 0.2207755	best: 0.2207746 (3759)	total: 58.1s	remaining: 14.5s
3780:	learn: 0.2022269	test: 0.2207038	best: 0.2207038 (3780)	total: 58.4s	remaining: 14.2s
3800:	learn: 0.2021049	test: 0.2206664	best: 0.2206664 (3800)	total: 58.7s	remaining: 13.9s
3820:	learn: 0.2019846	test: 0.2206160	best: 0.2206160 (3820)	total: 59s	remaining: 13.6s
3840:	learn: 0.2018475	test: 0.2205587	best: 0.2205587 (3840)	total: 59.3s	remaining: 13.3s
3860:	learn: 0.2017292	test: 0.2205082	best: 0.2205080 (3859)	total: 59.6s	remaining: 13s
3880:	learn: 0.2015904	test: 0.2204359	best: 0.2204359 (3880)	total: 59.9s	remaining: 12.7s
3900:	learn: 0.2014552	test: 0.2203859	best: 0.2203859 (3900)	total: 1m	remaining: 12.4s
3920:	learn: 0.2013408	test: 0.2203523	best: 0.2203523 (3920)	total: 1m	remaining: 12.1s
3940:	learn: 0.2012051	test: 0.2203221	best: 0.2203215 (3939)	total: 1m	remaining: 11.8s
3960:	learn: 0.2010749	test: 0.2202775	best: 0.2202774 (3958)	total: 1m 1s	remaining: 11.4s
3980:	learn: 0.2009574	test: 0.2202363	best: 0.2202352 (3979)	total: 1m 1s	remaining: 11.1s
4000:	learn: 0.2008210	test: 0.2201751	best: 0.2201751 (4000)	total: 1m 1s	remaining: 10.8s
4020:	learn: 0.2006937	test: 0.2201375	best: 0.2201375 (4020)	total: 1m 2s	remaining: 10.5s
4040:	learn: 0.2005593	test: 0.2201132	best: 0.2201118 (4039)	total: 1m 2s	remaining: 10.2s
4060:	learn: 0.2004303	test: 0.2200559	best: 0.2200559 (4060)	total: 1m 2s	remaining: 9.9s
4080:	learn: 0.2003036	test: 0.2200212	best: 0.2200212 (4080)	total: 1m 3s	remaining: 9.59s
4100:	learn: 0.2001807	test: 0.2199895	best: 0.2199871 (4097)	total: 1m 3s	remaining: 9.28s
4120:	learn: 0.2000671	test: 0.2199621	best: 0.2199621 (4120)	total: 1m 3s	remaining: 8.97s
4140:	learn: 0.1999434	test: 0.2199083	best: 0.2199083 (4140)	total: 1m 3s	remaining: 8.66s
4160:	learn: 0.1998069	test: 0.2198559	best: 0.2198559 (4160)	total: 1m 4s	remaining: 8.36s
4180:	learn: 0.1996726	test: 0.2197892	best: 0.2197892 (4180)	total: 1m 4s	remaining: 8.04s
4200:	learn: 0.1995243	test: 0.2197604	best: 0.2197604 (4200)	total: 1m 4s	remaining: 7.74s
4220:	learn: 0.1994099	test: 0.2197179	best: 0.2197179 (4220)	total: 1m 5s	remaining: 7.43s
4240:	learn: 0.1992905	test: 0.2196699	best: 0.2196699 (4240)	total: 1m 5s	remaining: 7.12s
4260:	learn: 0.1991668	test: 0.2196463	best: 0.2196461 (4257)	total: 1m 5s	remaining: 6.81s
4280:	learn: 0.1990363	test: 0.2196061	best: 0.2196058 (4279)	total: 1m 6s	remaining: 6.5s
4300:	learn: 0.1989227	test: 0.2195740	best: 0.2195740 (4300)	total: 1m 6s	remaining: 6.19s
4320:	learn: 0.1988138	test: 0.2195340	best: 0.2195301 (4319)	total: 1m 6s	remaining: 5.88s

	Fit constraints were validated upstream on the full training data, skipping...
	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
	Catboost model hyperparameters: {'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'Logloss', 'random_seed': 0, 'thread_count': 16, 'task_type': 'GPU'}
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

0:	learn: 0.6405756	test: 0.6404120	best: 0.6404120 (0)	total: 9.34ms	remaining: 9.34ms
1:	learn: 0.5957443	test: 0.5954482	best: 0.5954482 (1)	total: 18.3ms	remaining: 0us
bestTest = 0.5954482112
bestIteration = 1
0:	learn: 0.6415789	test: 0.6413864	best: 0.6413864 (0)	total: 15.6ms	remaining: 1m 13s
20:	learn: 0.3414519	test: 0.3394604	best: 0.3394604 (20)	total: 326ms	remaining: 1m 12s
40:	learn: 0.3093753	test: 0.3066716	best: 0.3066716 (40)	total: 633ms	remaining: 1m 11s
60:	learn: 0.2972328	test: 0.2943020	best: 0.2943020 (60)	total: 966ms	remaining: 1m 13s
80:	learn: 0.2902118	test: 0.2873536	best: 0.2873536 (80)	total: 1.29s	remaining: 1m 13s
100:	learn: 0.2847864	test: 0.2819381	best: 0.2819381 (100)	total: 1.6s	remaining: 1m 12s
120:	learn: 0.2800633	test: 0.2773792	best: 0.2773792 (120)	total: 1.92s	remaining: 1m 12s
140:	learn: 0.2764647	test: 0.2739598	best: 0.2739598 (140)	total: 2.23s	remaining: 1m 12s
160:	learn: 0.2734515	test: 0.2711073	best: 0.2711073 (160)	total: 2.55s	remaining: 1m 11s
180:	learn: 0.2703760	test: 0.2681708	best: 0.2681708 (180)	total: 2.87s	remaining: 1m 11s
200:	learn: 0.2675534	test: 0.2654747	best: 0.2654747 (200)	total: 3.18s	remaining: 1m 11s
220:	learn: 0.2654231	test: 0.2635713	best: 0.2635713 (220)	total: 3.49s	remaining: 1m 10s
240:	learn: 0.2633972	test: 0.2616682	best: 0.2616682 (240)	total: 3.81s	remaining: 1m 10s
260:	learn: 0.2617090	test: 0.2601667	best: 0.2601667 (260)	total: 4.12s	remaining: 1m 10s
280:	learn: 0.2600207	test: 0.2585448	best: 0.2585448 (280)	total: 4.46s	remaining: 1m 9s
300:	learn: 0.2583227	test: 0.2569384	best: 0.2569384 (300)	total: 4.78s	remaining: 1m 9s
320:	learn: 0.2568423	test: 0.2555539	best: 0.2555539 (320)	total: 5.1s	remaining: 1m 9s
340:	learn: 0.2555229	test: 0.2544230	best: 0.2544230 (340)	total: 5.41s	remaining: 1m 9s
360:	learn: 0.2542598	test: 0.2532885	best: 0.2532885 (360)	total: 5.72s	remaining: 1m 8s
380:	learn: 0.2530877	test: 0.2522849	best: 0.2522849 (380)	total: 6.03s	remaining: 1m 8s
400:	learn: 0.2520037	test: 0.2513140	best: 0.2513140 (400)	total: 6.35s	remaining: 1m 7s
420:	learn: 0.2505933	test: 0.2501083	best: 0.2501083 (420)	total: 6.67s	remaining: 1m 7s
440:	learn: 0.2495839	test: 0.2492121	best: 0.2492121 (440)	total: 6.98s	remaining: 1m 7s
460:	learn: 0.2486625	test: 0.2484565	best: 0.2484565 (460)	total: 7.29s	remaining: 1m 6s
480:	learn: 0.2477104	test: 0.2476376	best: 0.2476376 (480)	total: 7.61s	remaining: 1m 6s
500:	learn: 0.2466796	test: 0.2467080	best: 0.2467080 (500)	total: 7.94s	remaining: 1m 6s
520:	learn: 0.2458137	test: 0.2459701	best: 0.2459701 (520)	total: 8.25s	remaining: 1m 6s
540:	learn: 0.2450590	test: 0.2453141	best: 0.2453141 (540)	total: 8.56s	remaining: 1m 5s
560:	learn: 0.2441367	test: 0.2444702	best: 0.2444702 (560)	total: 8.87s	remaining: 1m 5s
580:	learn: 0.2432999	test: 0.2437557	best: 0.2437557 (580)	total: 9.19s	remaining: 1m 5s
600:	learn: 0.2425542	test: 0.2431324	best: 0.2431324 (600)	total: 9.5s	remaining: 1m 4s
620:	learn: 0.2419126	test: 0.2425842	best: 0.2425842 (620)	total: 9.8s	remaining: 1m 4s
640:	learn: 0.2412051	test: 0.2419845	best: 0.2419845 (640)	total: 10.1s	remaining: 1m 3s
660:	learn: 0.2406208	test: 0.2415067	best: 0.2415067 (660)	total: 10.4s	remaining: 1m 3s
680:	learn: 0.2399303	test: 0.2409532	best: 0.2409532 (680)	total: 10.7s	remaining: 1m 3s
700:	learn: 0.2392186	test: 0.2403252	best: 0.2403252 (700)	total: 11s	remaining: 1m 2s
720:	learn: 0.2386257	test: 0.2397964	best: 0.2397964 (720)	total: 11.4s	remaining: 1m 2s
740:	learn: 0.2380249	test: 0.2393511	best: 0.2393511 (740)	total: 11.7s	remaining: 1m 2s
760:	learn: 0.2374176	test: 0.2388894	best: 0.2388894 (760)	total: 12s	remaining: 1m 1s
780:	learn: 0.2368918	test: 0.2385162	best: 0.2385162 (780)	total: 12.3s	remaining: 1m 1s
800:	learn: 0.2363080	test: 0.2380561	best: 0.2380561 (800)	total: 12.6s	remaining: 1m 1s
820:	learn: 0.2358310	test: 0.2376805	best: 0.2376805 (820)	total: 12.9s	remaining: 1m
840:	learn: 0.2353687	test: 0.2373394	best: 0.2373394 (840)	total: 13.2s	remaining: 1m
860:	learn: 0.2349270	test: 0.2370116	best: 0.2370116 (860)	total: 13.5s	remaining: 1m
880:	learn: 0.2344043	test: 0.2366288	best: 0.2366288 (880)	total: 13.9s	remaining: 60s
900:	learn: 0.2339295	test: 0.2362813	best: 0.2362813 (900)	total: 14.2s	remaining: 59.7s
920:	learn: 0.2334903	test: 0.2359617	best: 0.2359617 (920)	total: 14.5s	remaining: 59.3s
940:	learn: 0.2330568	test: 0.2356526	best: 0.2356526 (940)	total: 14.8s	remaining: 59s
960:	learn: 0.2325662	test: 0.2353051	best: 0.2353051 (960)	total: 15.1s	remaining: 58.7s
980:	learn: 0.2321921	test: 0.2350537	best: 0.2350537 (980)	total: 15.4s	remaining: 58.3s
1000:	learn: 0.2317439	test: 0.2347230	best: 0.2347230 (1000)	total: 15.7s	remaining: 58s
1020:	learn: 0.2313363	test: 0.2344261	best: 0.2344261 (1020)	total: 16s	remaining: 57.7s
1040:	learn: 0.2309260	test: 0.2341673	best: 0.2341673 (1040)	total: 16.4s	remaining: 57.4s
1060:	learn: 0.2304994	test: 0.2338572	best: 0.2338572 (1060)	total: 16.7s	remaining: 57s
1080:	learn: 0.2300929	test: 0.2335741	best: 0.2335741 (1080)	total: 17s	remaining: 56.7s
1100:	learn: 0.2297110	test: 0.2332827	best: 0.2332827 (1100)	total: 17.3s	remaining: 56.4s
1120:	learn: 0.2293163	test: 0.2330014	best: 0.2330014 (1120)	total: 17.6s	remaining: 56.1s
1140:	learn: 0.2289973	test: 0.2327791	best: 0.2327791 (1140)	total: 17.9s	remaining: 55.7s
1160:	learn: 0.2286544	test: 0.2325671	best: 0.2325671 (1160)	total: 18.2s	remaining: 55.4s
1180:	learn: 0.2283386	test: 0.2323513	best: 0.2323513 (1180)	total: 18.5s	remaining: 55.1s
1200:	learn: 0.2279986	test: 0.2320871	best: 0.2320871 (1200)	total: 18.8s	remaining: 54.7s
1220:	learn: 0.2276338	test: 0.2318242	best: 0.2318242 (1220)	total: 19.1s	remaining: 54.4s
1240:	learn: 0.2273661	test: 0.2316591	best: 0.2316591 (1240)	total: 19.4s	remaining: 54.1s
1260:	learn: 0.2270397	test: 0.2314455	best: 0.2314455 (1260)	total: 19.7s	remaining: 53.7s
1280:	learn: 0.2267117	test: 0.2312068	best: 0.2312068 (1280)	total: 20.1s	remaining: 53.4s
1300:	learn: 0.2263671	test: 0.2309738	best: 0.2309738 (1300)	total: 20.4s	remaining: 53.1s
1320:	learn: 0.2260303	test: 0.2307474	best: 0.2307474 (1320)	total: 20.7s	remaining: 52.8s
1340:	learn: 0.2257042	test: 0.2304959	best: 0.2304959 (1340)	total: 21s	remaining: 52.4s
1360:	learn: 0.2254143	test: 0.2303017	best: 0.2303017 (1360)	total: 21.3s	remaining: 52.1s
1380:	learn: 0.2251144	test: 0.2301247	best: 0.2301247 (1380)	total: 21.6s	remaining: 51.8s
1400:	learn: 0.2248483	test: 0.2299747	best: 0.2299747 (1400)	total: 21.9s	remaining: 51.4s
1420:	learn: 0.2245332	test: 0.2297329	best: 0.2297329 (1420)	total: 22.2s	remaining: 51.1s
1440:	learn: 0.2242649	test: 0.2295413	best: 0.2295413 (1440)	total: 22.5s	remaining: 50.8s
1460:	learn: 0.2239625	test: 0.2293629	best: 0.2293620 (1458)	total: 22.8s	remaining: 50.5s
1480:	learn: 0.2236987	test: 0.2291916	best: 0.2291916 (1480)	total: 23.1s	remaining: 50.2s
1500:	learn: 0.2234066	test: 0.2289892	best: 0.2289892 (1500)	total: 23.4s	remaining: 49.8s
1520:	learn: 0.2231312	test: 0.2288085	best: 0.2288085 (1520)	total: 23.7s	remaining: 49.5s
1540:	learn: 0.2228393	test: 0.2286323	best: 0.2286323 (1540)	total: 24s	remaining: 49.2s
1560:	learn: 0.2225927	test: 0.2284489	best: 0.2284489 (1560)	total: 24.3s	remaining: 48.8s
1580:	learn: 0.2223209	test: 0.2282693	best: 0.2282693 (1580)	total: 24.6s	remaining: 48.5s
1600:	learn: 0.2220591	test: 0.2280997	best: 0.2280997 (1600)	total: 25s	remaining: 48.2s
1620:	learn: 0.2218102	test: 0.2279486	best: 0.2279486 (1620)	total: 25.3s	remaining: 47.9s
1640:	learn: 0.2215579	test: 0.2278082	best: 0.2278082 (1640)	total: 25.6s	remaining: 47.6s
1660:	learn: 0.2213128	test: 0.2276584	best: 0.2276584 (1660)	total: 25.9s	remaining: 47.2s
1680:	learn: 0.2210455	test: 0.2275059	best: 0.2275059 (1680)	total: 26.2s	remaining: 46.9s
1700:	learn: 0.2207662	test: 0.2273572	best: 0.2273572 (1700)	total: 26.5s	remaining: 46.6s
1720:	learn: 0.2205271	test: 0.2272398	best: 0.2272398 (1720)	total: 26.8s	remaining: 46.3s
1740:	learn: 0.2203073	test: 0.2271379	best: 0.2271379 (1740)	total: 27.1s	remaining: 45.9s
1760:	learn: 0.2200556	test: 0.2269978	best: 0.2269978 (1760)	total: 27.4s	remaining: 45.6s
1780:	learn: 0.2198069	test: 0.2268501	best: 0.2268501 (1780)	total: 27.7s	remaining: 45.3s
1800:	learn: 0.2195609	test: 0.2266910	best: 0.2266910 (1800)	total: 28s	remaining: 45s
1820:	learn: 0.2193145	test: 0.2265542	best: 0.2265542 (1820)	total: 28.3s	remaining: 44.7s
1840:	learn: 0.2190788	test: 0.2264360	best: 0.2264360 (1840)	total: 28.6s	remaining: 44.4s
1860:	learn: 0.2188468	test: 0.2262927	best: 0.2262927 (1860)	total: 28.9s	remaining: 44s
1880:	learn: 0.2186268	test: 0.2261766	best: 0.2261766 (1880)	total: 29.2s	remaining: 43.7s
1900:	learn: 0.2183925	test: 0.2260467	best: 0.2260467 (1900)	total: 29.5s	remaining: 43.4s
1920:	learn: 0.2181984	test: 0.2259359	best: 0.2259359 (1920)	total: 29.8s	remaining: 43.1s
1940:	learn: 0.2179679	test: 0.2258094	best: 0.2258094 (1940)	total: 30.2s	remaining: 42.8s
1960:	learn: 0.2177280	test: 0.2256749	best: 0.2256749 (1960)	total: 30.5s	remaining: 42.4s
1980:	learn: 0.2175243	test: 0.2255828	best: 0.2255828 (1980)	total: 30.8s	remaining: 42.1s
2000:	learn: 0.2173183	test: 0.2254784	best: 0.2254772 (1999)	total: 31.1s	remaining: 41.8s
2020:	learn: 0.2170981	test: 0.2253563	best: 0.2253563 (2020)	total: 31.4s	remaining: 41.5s
2040:	learn: 0.2168619	test: 0.2252290	best: 0.2252290 (2040)	total: 31.7s	remaining: 41.2s
2060:	learn: 0.2166417	test: 0.2251116	best: 0.2251116 (2060)	total: 32s	remaining: 40.8s
2080:	learn: 0.2164130	test: 0.2249806	best: 0.2249806 (2080)	total: 32.3s	remaining: 40.5s
2100:	learn: 0.2162126	test: 0.2248710	best: 0.2248710 (2100)	total: 32.6s	remaining: 40.2s
2120:	learn: 0.2160090	test: 0.2247629	best: 0.2247629 (2120)	total: 32.9s	remaining: 39.9s
2140:	learn: 0.2158191	test: 0.2246601	best: 0.2246601 (2140)	total: 33.2s	remaining: 39.6s
2160:	learn: 0.2156330	test: 0.2245369	best: 0.2245369 (2160)	total: 33.5s	remaining: 39.3s
2180:	learn: 0.2154363	test: 0.2244405	best: 0.2244405 (2180)	total: 33.8s	remaining: 38.9s
2200:	learn: 0.2152442	test: 0.2243385	best: 0.2243385 (2200)	total: 34.1s	remaining: 38.6s
2220:	learn: 0.2150651	test: 0.2242481	best: 0.2242481 (2220)	total: 34.4s	remaining: 38.3s
2240:	learn: 0.2148763	test: 0.2241622	best: 0.2241622 (2240)	total: 34.7s	remaining: 38s
2260:	learn: 0.2146971	test: 0.2240613	best: 0.2240613 (2260)	total: 35s	remaining: 37.7s
2280:	learn: 0.2144879	test: 0.2239634	best: 0.2239634 (2280)	total: 35.3s	remaining: 37.4s
2300:	learn: 0.2143001	test: 0.2238773	best: 0.2238773 (2300)	total: 35.6s	remaining: 37s
2320:	learn: 0.2141165	test: 0.2237891	best: 0.2237889 (2318)	total: 35.9s	remaining: 36.7s
2340:	learn: 0.2139180	test: 0.2236536	best: 0.2236536 (2340)	total: 36.2s	remaining: 36.4s
2360:	learn: 0.2137261	test: 0.2235533	best: 0.2235533 (2360)	total: 36.6s	remaining: 36.1s
2380:	learn: 0.2135405	test: 0.2234599	best: 0.2234599 (2380)	total: 36.9s	remaining: 35.8s
2400:	learn: 0.2133333	test: 0.2233475	best: 0.2233475 (2400)	total: 37.2s	remaining: 35.5s
2420:	learn: 0.2131620	test: 0.2232670	best: 0.2232670 (2420)	total: 37.5s	remaining: 35.2s
2440:	learn: 0.2129889	test: 0.2232086	best: 0.2232086 (2440)	total: 37.8s	remaining: 34.9s
2460:	learn: 0.2128207	test: 0.2230955	best: 0.2230955 (2460)	total: 38.1s	remaining: 34.5s
2480:	learn: 0.2126698	test: 0.2230457	best: 0.2230457 (2480)	total: 38.4s	remaining: 34.2s
2500:	learn: 0.2124951	test: 0.2229719	best: 0.2229704 (2498)	total: 38.7s	remaining: 33.9s
2520:	learn: 0.2123385	test: 0.2228929	best: 0.2228929 (2520)	total: 39s	remaining: 33.6s
2540:	learn: 0.2121726	test: 0.2228067	best: 0.2228067 (2540)	total: 39.3s	remaining: 33.3s
2560:	learn: 0.2119890	test: 0.2226942	best: 0.2226942 (2560)	total: 39.6s	remaining: 33s
2580:	learn: 0.2118383	test: 0.2226286	best: 0.2226286 (2580)	total: 39.9s	remaining: 32.7s
2600:	learn: 0.2116574	test: 0.2225396	best: 0.2225396 (2600)	total: 40.2s	remaining: 32.4s
2620:	learn: 0.2114870	test: 0.2224654	best: 0.2224654 (2620)	total: 40.5s	remaining: 32s
2640:	learn: 0.2113267	test: 0.2223828	best: 0.2223828 (2640)	total: 40.8s	remaining: 31.7s
2660:	learn: 0.2111574	test: 0.2223322	best: 0.2223322 (2660)	total: 41.1s	remaining: 31.4s
2680:	learn: 0.2109667	test: 0.2222332	best: 0.2222332 (2680)	total: 41.5s	remaining: 31.1s
2700:	learn: 0.2107487	test: 0.2221099	best: 0.2221099 (2700)	total: 41.8s	remaining: 30.8s
2720:	learn: 0.2105565	test: 0.2220091	best: 0.2220091 (2720)	total: 42.1s	remaining: 30.5s
2740:	learn: 0.2103766	test: 0.2219090	best: 0.2219090 (2740)	total: 42.4s	remaining: 30.2s
2760:	learn: 0.2102103	test: 0.2218326	best: 0.2218326 (2760)	total: 42.7s	remaining: 29.9s
2780:	learn: 0.2100292	test: 0.2217675	best: 0.2217675 (2780)	total: 43s	remaining: 29.5s
2800:	learn: 0.2098665	test: 0.2216920	best: 0.2216920 (2800)	total: 43.3s	remaining: 29.2s
2820:	learn: 0.2097320	test: 0.2216467	best: 0.2216458 (2819)	total: 43.6s	remaining: 28.9s
2840:	learn: 0.2095624	test: 0.2215675	best: 0.2215675 (2840)	total: 43.9s	remaining: 28.6s
2860:	learn: 0.2094025	test: 0.2214921	best: 0.2214912 (2859)	total: 44.2s	remaining: 28.3s
2880:	learn: 0.2092298	test: 0.2214150	best: 0.2214150 (2880)	total: 44.5s	remaining: 28s
2900:	learn: 0.2090663	test: 0.2213515	best: 0.2213515 (2900)	total: 44.8s	remaining: 27.7s
2920:	learn: 0.2088955	test: 0.2212788	best: 0.2212788 (2920)	total: 45.1s	remaining: 27.4s
2940:	learn: 0.2087607	test: 0.2212294	best: 0.2212294 (2940)	total: 45.4s	remaining: 27.1s
2960:	learn: 0.2085768	test: 0.2211465	best: 0.2211465 (2960)	total: 45.7s	remaining: 26.7s
2980:	learn: 0.2084221	test: 0.2210744	best: 0.2210744 (2980)	total: 46s	remaining: 26.4s
3000:	learn: 0.2082549	test: 0.2210003	best: 0.2209989 (2998)	total: 46.3s	remaining: 26.1s
3020:	learn: 0.2080915	test: 0.2209375	best: 0.2209375 (3020)	total: 46.6s	remaining: 25.8s
3040:	learn: 0.2079205	test: 0.2208617	best: 0.2208617 (3040)	total: 46.9s	remaining: 25.5s
3060:	learn: 0.2077723	test: 0.2208177	best: 0.2208177 (3060)	total: 47.3s	remaining: 25.2s
3080:	learn: 0.2076241	test: 0.2207602	best: 0.2207574 (3079)	total: 47.6s	remaining: 24.9s
3100:	learn: 0.2074799	test: 0.2207074	best: 0.2207074 (3100)	total: 47.9s	remaining: 24.6s
3120:	learn: 0.2073268	test: 0.2206448	best: 0.2206448 (3120)	total: 48.2s	remaining: 24.3s
3140:	learn: 0.2071952	test: 0.2206003	best: 0.2206003 (3140)	total: 48.5s	remaining: 24s
3160:	learn: 0.2070214	test: 0.2205256	best: 0.2205256 (3160)	total: 48.8s	remaining: 23.6s
3180:	learn: 0.2068686	test: 0.2204599	best: 0.2204599 (3180)	total: 49.1s	remaining: 23.3s
3200:	learn: 0.2067171	test: 0.2203515	best: 0.2203515 (3200)	total: 49.4s	remaining: 23s
3220:	learn: 0.2065575	test: 0.2202833	best: 0.2202833 (3220)	total: 49.7s	remaining: 22.7s
3240:	learn: 0.2063925	test: 0.2202314	best: 0.2202314 (3240)	total: 50s	remaining: 22.4s
3260:	learn: 0.2062399	test: 0.2201617	best: 0.2201617 (3260)	total: 50.3s	remaining: 22.1s
3280:	learn: 0.2061101	test: 0.2201185	best: 0.2201185 (3280)	total: 50.6s	remaining: 21.8s
3300:	learn: 0.2059808	test: 0.2200708	best: 0.2200708 (3300)	total: 50.9s	remaining: 21.5s
3320:	learn: 0.2058316	test: 0.2200339	best: 0.2200319 (3318)	total: 51.2s	remaining: 21.2s
3340:	learn: 0.2056917	test: 0.2199834	best: 0.2199834 (3340)	total: 51.5s	remaining: 20.9s
3360:	learn: 0.2055450	test: 0.2199174	best: 0.2199142 (3358)	total: 51.8s	remaining: 20.5s
3380:	learn: 0.2053790	test: 0.2198623	best: 0.2198623 (3380)	total: 52.1s	remaining: 20.2s
3400:	learn: 0.2052245	test: 0.2198020	best: 0.2198020 (3400)	total: 52.5s	remaining: 19.9s
3420:	learn: 0.2050726	test: 0.2197413	best: 0.2197413 (3420)	total: 52.8s	remaining: 19.6s
3440:	learn: 0.2049262	test: 0.2197044	best: 0.2197031 (3439)	total: 53.1s	remaining: 19.3s
3460:	learn: 0.2047653	test: 0.2196476	best: 0.2196473 (3459)	total: 53.4s	remaining: 19s
3480:	learn: 0.2046314	test: 0.2195940	best: 0.2195935 (3479)	total: 53.7s	remaining: 18.7s
3500:	learn: 0.2044923	test: 0.2195262	best: 0.2195232 (3499)	total: 54s	remaining: 18.4s
3520:	learn: 0.2043540	test: 0.2194764	best: 0.2194764 (3520)	total: 54.3s	remaining: 18.1s
3540:	learn: 0.2042247	test: 0.2194331	best: 0.2194331 (3540)	total: 54.6s	remaining: 17.8s
3560:	learn: 0.2040887	test: 0.2193896	best: 0.2193875 (3558)	total: 54.9s	remaining: 17.5s
3580:	learn: 0.2039466	test: 0.2193555	best: 0.2193546 (3578)	total: 55.2s	remaining: 17.1s
3600:	learn: 0.2038266	test: 0.2193170	best: 0.2193170 (3600)	total: 55.5s	remaining: 16.8s
3620:	learn: 0.2036873	test: 0.2192595	best: 0.2192594 (3619)	total: 55.8s	remaining: 16.5s
3640:	learn: 0.2035413	test: 0.2192095	best: 0.2192095 (3640)	total: 56.2s	remaining: 16.2s
3660:	learn: 0.2034012	test: 0.2191577	best: 0.2191567 (3659)	total: 56.5s	remaining: 15.9s
3680:	learn: 0.2032646	test: 0.2191111	best: 0.2191111 (3680)	total: 56.8s	remaining: 15.6s
3700:	learn: 0.2031397	test: 0.2190710	best: 0.2190710 (3700)	total: 57.1s	remaining: 15.3s
3720:	learn: 0.2030161	test: 0.2190409	best: 0.2190403 (3719)	total: 57.4s	remaining: 15s
3740:	learn: 0.2028685	test: 0.2189678	best: 0.2189678 (3740)	total: 57.7s	remaining: 14.7s
3760:	learn: 0.2027311	test: 0.2189217	best: 0.2189217 (3760)	total: 58s	remaining: 14.4s
3780:	learn: 0.2025962	test: 0.2188707	best: 0.2188707 (3780)	total: 58.3s	remaining: 14.1s
3800:	learn: 0.2024629	test: 0.2188072	best: 0.2188072 (3800)	total: 58.6s	remaining: 13.8s
3820:	learn: 0.2023225	test: 0.2187543	best: 0.2187543 (3820)	total: 58.9s	remaining: 13.5s
3840:	learn: 0.2022030	test: 0.2187265	best: 0.2187265 (3840)	total: 59.3s	remaining: 13.1s
3860:	learn: 0.2020588	test: 0.2186596	best: 0.2186596 (3860)	total: 59.6s	remaining: 12.8s
3880:	learn: 0.2019346	test: 0.2186250	best: 0.2186250 (3880)	total: 59.9s	remaining: 12.5s
3900:	learn: 0.2017950	test: 0.2185486	best: 0.2185486 (3900)	total: 1m	remaining: 12.2s
3920:	learn: 0.2016684	test: 0.2185114	best: 0.2185089 (3917)	total: 1m	remaining: 11.9s
3940:	learn: 0.2015398	test: 0.2184570	best: 0.2184567 (3939)	total: 1m	remaining: 11.6s
3960:	learn: 0.2014084	test: 0.2183924	best: 0.2183924 (3960)	total: 1m 1s	remaining: 11.3s
3980:	learn: 0.2012626	test: 0.2183412	best: 0.2183412 (3980)	total: 1m 1s	remaining: 11s
4000:	learn: 0.2011304	test: 0.2183078	best: 0.2183070 (3998)	total: 1m 1s	remaining: 10.7s
4020:	learn: 0.2010138	test: 0.2182565	best: 0.2182565 (4020)	total: 1m 2s	remaining: 10.4s
4040:	learn: 0.2008871	test: 0.2182026	best: 0.2182026 (4040)	total: 1m 2s	remaining: 10.1s
4060:	learn: 0.2007745	test: 0.2181464	best: 0.2181464 (4060)	total: 1m 2s	remaining: 9.75s
4080:	learn: 0.2006285	test: 0.2180971	best: 0.2180971 (4080)	total: 1m 2s	remaining: 9.44s
4100:	learn: 0.2004985	test: 0.2180489	best: 0.2180489 (4100)	total: 1m 3s	remaining: 9.13s
4120:	learn: 0.2003866	test: 0.2180152	best: 0.2180144 (4117)	total: 1m 3s	remaining: 8.82s
4140:	learn: 0.2002677	test: 0.2179598	best: 0.2179589 (4139)	total: 1m 3s	remaining: 8.52s
4160:	learn: 0.2001368	test: 0.2179319	best: 0.2179314 (4157)	total: 1m 4s	remaining: 8.21s
4180:	learn: 0.2000038	test: 0.2179065	best: 0.2179034 (4175)	total: 1m 4s	remaining: 7.9s
4200:	learn: 0.1998839	test: 0.2178623	best: 0.2178607 (4198)	total: 1m 4s	remaining: 7.59s
4220:	learn: 0.1997481	test: 0.2178295	best: 0.2178282 (4219)	total: 1m 5s	remaining: 7.28s
4240:	learn: 0.1996349	test: 0.2177837	best: 0.2177837 (4240)	total: 1m 5s	remaining: 6.97s
4260:	learn: 0.1995012	test: 0.2177597	best: 0.2177597 (4260)	total: 1m 5s	remaining: 6.66s
4280:	learn: 0.1993774	test: 0.2177445	best: 0.2177394 (4278)	total: 1m 6s	remaining: 6.36s
4300:	learn: 0.1992548	test: 0.2177086	best: 0.2177086 (4300)	total: 1m 6s	remaining: 6.05s
4320:	learn: 0.1991357	test: 0.2176882	best: 0.2176882 (4320)	total: 1m 6s	remaining: 5.74s

Saving c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\model.pkl
	0.9548	 = Validation score   (roc_auc)
	599.39s	 = Training   runtime
	0.42s	 = Validation runtime
	162576.9	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Fitting model: XGBoost_BAG_L1 ... Training model for up to 31253.22s of the 31253.22s of remaining time.
	Fitting XGBoost_BAG_L1 with 'num_gpus': 1, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\utils\model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=8, gpus=1)
	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47514
[50]	validation_0-logloss:0.26479
[100]	validation_0-logloss:0.24896
[150]	validation_0-logloss:0.24085
[200]	validation_0-logloss:0.23547
[250]	validation_0-logloss:0.23096
[300]	validation_0-logloss:0.22804
[350]	validation_0-logloss:0.22556
[400]	validation_0-logloss:0.22367
[450]	validation_0-logloss:0.22222
[500]	validation_0-logloss:0.22082
[550]	validation_0-logloss:0.21977
[600]	validation_0-logloss:0.21873
[650]	validation_0-logloss:0.21813
[700]	validation_0-logloss:0.21754
[750]	validation_0-logloss:0.21691
[800]	validation_0-logloss:0.21649
[850]	validation_0-logloss:0.21605
[900]	validation_0-logloss:0.21567
[950]	validation_0-logloss:0.21538
[1000]	validation_0-logloss:0.21495
[1050]	validation_0-logloss:0.21478
[1100]	validation_0-logloss:0.21443
[1150]	validation_0-logloss:0.21405
[1200]	validation_0-logloss:0.21375
[1250]	validation_0-logloss:0.21357
[1300]	validation_0-logloss:0.21342
[1350]	validation_0-logloss:0.21322
[1400]	validation_0-logloss:0.21315
[1450]	validation_0-logloss:0.21300
[1500]	validation_0-logloss:0.21299
[1550]	validation_0-logloss:0.21284
[1600]	validation_0-logloss:0.21275
[1650]	validation_0-logloss:0.21266
[1700]	validation_0-logloss:0.21256
[1750]	validation_0-logloss:0.21253
[1800]	validation_0-logloss:0.21246
[1850]	validation_0-logloss:0.21237
[1900]	validation_0-logloss:0.21237
[1950]	validation_0-logloss:0.21227
[2000]	validation_0-logloss:0.21215
[2050]	validation_0-logloss:0.21218
[2100]	validation_0-logloss:0.21220
[2150]	validation_0-logloss:0.21219
[2200]	validation_0-logloss:0.21217
[2250]	validation_0-logloss:0.21215
[2300]	validation_0-logloss:0.21225
[2350]	validation_0-logloss:0.21226
[2400]	validation_0-logloss:0.21235
[2450]	validation_0-logloss:0.21237
[2500]	validation_0-logloss:0.21232
[2550]	validation_0-logloss:0.21241
[2600]	validation_0-logloss:0.21246
[2650]	validation_0-logloss:0.21249
[2700]	validation_0-logloss:0.21254
[2750]	validation_0-logloss:0.21252
[2772]	validation_0-logloss:0.21260

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47517
[50]	validation_0-logloss:0.26573
[100]	validation_0-logloss:0.24949
[150]	validation_0-logloss:0.24144
[200]	validation_0-logloss:0.23530
[250]	validation_0-logloss:0.23107
[300]	validation_0-logloss:0.22862
[350]	validation_0-logloss:0.22626
[400]	validation_0-logloss:0.22447
[450]	validation_0-logloss:0.22246
[500]	validation_0-logloss:0.22098
[550]	validation_0-logloss:0.21982
[600]	validation_0-logloss:0.21870
[650]	validation_0-logloss:0.21775
[700]	validation_0-logloss:0.21724
[750]	validation_0-logloss:0.21657
[800]	validation_0-logloss:0.21601
[850]	validation_0-logloss:0.21535
[900]	validation_0-logloss:0.21492
[950]	validation_0-logloss:0.21447
[1000]	validation_0-logloss:0.21409
[1050]	validation_0-logloss:0.21388
[1100]	validation_0-logloss:0.21335
[1150]	validation_0-logloss:0.21315
[1200]	validation_0-logloss:0.21284
[1250]	validation_0-logloss:0.21250
[1300]	validation_0-logloss:0.21226
[1350]	validation_0-logloss:0.21211
[1400]	validation_0-logloss:0.21200
[1450]	validation_0-logloss:0.21187
[1500]	validation_0-logloss:0.21167
[1550]	validation_0-logloss:0.21149
[1600]	validation_0-logloss:0.21138
[1650]	validation_0-logloss:0.21125
[1700]	validation_0-logloss:0.21111
[1750]	validation_0-logloss:0.21101
[1800]	validation_0-logloss:0.21094
[1850]	validation_0-logloss:0.21087
[1900]	validation_0-logloss:0.21076
[1950]	validation_0-logloss:0.21060
[2000]	validation_0-logloss:0.21055
[2050]	validation_0-logloss:0.21054
[2100]	validation_0-logloss:0.21050
[2150]	validation_0-logloss:0.21039
[2200]	validation_0-logloss:0.21037
[2250]	validation_0-logloss:0.21036
[2300]	validation_0-logloss:0.21043
[2350]	validation_0-logloss:0.21042
[2400]	validation_0-logloss:0.21052
[2450]	validation_0-logloss:0.21057
[2500]	validation_0-logloss:0.21061
[2550]	validation_0-logloss:0.21066
[2600]	validation_0-logloss:0.21069
[2650]	validation_0-logloss:0.21067
[2700]	validation_0-logloss:0.21074
[2750]	validation_0-logloss:0.21068
[2800]	validation_0-logloss:0.21067
[2850]	validation_0-logloss:0.21069
[2900]	validation_0-logloss:0.21076
[2919]	validation_0-logloss:0.21084

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47521
[50]	validation_0-logloss:0.26837
[100]	validation_0-logloss:0.25196
[150]	validation_0-logloss:0.24344
[200]	validation_0-logloss:0.23823
[250]	validation_0-logloss:0.23420
[300]	validation_0-logloss:0.23181
[350]	validation_0-logloss:0.22941
[400]	validation_0-logloss:0.22779
[450]	validation_0-logloss:0.22627
[500]	validation_0-logloss:0.22498
[550]	validation_0-logloss:0.22368
[600]	validation_0-logloss:0.22290
[650]	validation_0-logloss:0.22198
[700]	validation_0-logloss:0.22123
[750]	validation_0-logloss:0.22060
[800]	validation_0-logloss:0.22022
[850]	validation_0-logloss:0.21975
[900]	validation_0-logloss:0.21935
[950]	validation_0-logloss:0.21903
[1000]	validation_0-logloss:0.21870
[1050]	validation_0-logloss:0.21840
[1100]	validation_0-logloss:0.21805
[1150]	validation_0-logloss:0.21782
[1200]	validation_0-logloss:0.21763
[1250]	validation_0-logloss:0.21736
[1300]	validation_0-logloss:0.21721
[1350]	validation_0-logloss:0.21702
[1400]	validation_0-logloss:0.21685
[1450]	validation_0-logloss:0.21665
[1500]	validation_0-logloss:0.21654
[1550]	validation_0-logloss:0.21641
[1600]	validation_0-logloss:0.21636
[1650]	validation_0-logloss:0.21629
[1700]	validation_0-logloss:0.21621
[1750]	validation_0-logloss:0.21618
[1800]	validation_0-logloss:0.21614
[1850]	validation_0-logloss:0.21611
[1900]	validation_0-logloss:0.21611
[1950]	validation_0-logloss:0.21608
[2000]	validation_0-logloss:0.21608
[2050]	validation_0-logloss:0.21612
[2100]	validation_0-logloss:0.21618
[2150]	validation_0-logloss:0.21615
[2200]	validation_0-logloss:0.21618
[2250]	validation_0-logloss:0.21623
[2300]	validation_0-logloss:0.21618
[2350]	validation_0-logloss:0.21619
[2400]	validation_0-logloss:0.21626
[2450]	validation_0-logloss:0.21635
[2500]	validation_0-logloss:0.21636
[2550]	validation_0-logloss:0.21643
[2600]	validation_0-logloss:0.21645
[2615]	validation_0-logloss:0.21647

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47499
[50]	validation_0-logloss:0.26440
[100]	validation_0-logloss:0.24855
[150]	validation_0-logloss:0.23983
[200]	validation_0-logloss:0.23421
[250]	validation_0-logloss:0.23024
[300]	validation_0-logloss:0.22770
[350]	validation_0-logloss:0.22580
[400]	validation_0-logloss:0.22361
[450]	validation_0-logloss:0.22239
[500]	validation_0-logloss:0.22099
[550]	validation_0-logloss:0.21985
[600]	validation_0-logloss:0.21926
[650]	validation_0-logloss:0.21819
[700]	validation_0-logloss:0.21764
[750]	validation_0-logloss:0.21681
[800]	validation_0-logloss:0.21627
[850]	validation_0-logloss:0.21580
[900]	validation_0-logloss:0.21537
[950]	validation_0-logloss:0.21505
[1000]	validation_0-logloss:0.21477
[1050]	validation_0-logloss:0.21438
[1100]	validation_0-logloss:0.21416
[1150]	validation_0-logloss:0.21406
[1200]	validation_0-logloss:0.21388
[1250]	validation_0-logloss:0.21363
[1300]	validation_0-logloss:0.21342
[1350]	validation_0-logloss:0.21337
[1400]	validation_0-logloss:0.21322
[1450]	validation_0-logloss:0.21315
[1500]	validation_0-logloss:0.21301
[1550]	validation_0-logloss:0.21293
[1600]	validation_0-logloss:0.21276
[1650]	validation_0-logloss:0.21271
[1700]	validation_0-logloss:0.21245
[1750]	validation_0-logloss:0.21230
[1800]	validation_0-logloss:0.21225
[1850]	validation_0-logloss:0.21222
[1900]	validation_0-logloss:0.21221
[1950]	validation_0-logloss:0.21224
[2000]	validation_0-logloss:0.21233
[2050]	validation_0-logloss:0.21233
[2100]	validation_0-logloss:0.21233
[2150]	validation_0-logloss:0.21236
[2200]	validation_0-logloss:0.21234
[2250]	validation_0-logloss:0.21239
[2300]	validation_0-logloss:0.21243
[2350]	validation_0-logloss:0.21240
[2400]	validation_0-logloss:0.21240
[2450]	validation_0-logloss:0.21246
[2480]	validation_0-logloss:0.21248

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47509
[50]	validation_0-logloss:0.26452
[100]	validation_0-logloss:0.24825
[150]	validation_0-logloss:0.23990
[200]	validation_0-logloss:0.23455
[250]	validation_0-logloss:0.23070
[300]	validation_0-logloss:0.22786
[350]	validation_0-logloss:0.22603
[400]	validation_0-logloss:0.22353
[450]	validation_0-logloss:0.22218
[500]	validation_0-logloss:0.22058
[550]	validation_0-logloss:0.21960
[600]	validation_0-logloss:0.21873
[650]	validation_0-logloss:0.21756
[700]	validation_0-logloss:0.21683
[750]	validation_0-logloss:0.21620
[800]	validation_0-logloss:0.21562
[850]	validation_0-logloss:0.21528
[900]	validation_0-logloss:0.21475
[950]	validation_0-logloss:0.21436
[1000]	validation_0-logloss:0.21379
[1050]	validation_0-logloss:0.21360
[1100]	validation_0-logloss:0.21354
[1150]	validation_0-logloss:0.21323
[1200]	validation_0-logloss:0.21298
[1250]	validation_0-logloss:0.21279
[1300]	validation_0-logloss:0.21250
[1350]	validation_0-logloss:0.21238
[1400]	validation_0-logloss:0.21220
[1450]	validation_0-logloss:0.21211
[1500]	validation_0-logloss:0.21206
[1550]	validation_0-logloss:0.21195
[1600]	validation_0-logloss:0.21176
[1650]	validation_0-logloss:0.21184
[1700]	validation_0-logloss:0.21166
[1750]	validation_0-logloss:0.21153
[1800]	validation_0-logloss:0.21141
[1850]	validation_0-logloss:0.21152
[1900]	validation_0-logloss:0.21151
[1950]	validation_0-logloss:0.21147
[2000]	validation_0-logloss:0.21145
[2050]	validation_0-logloss:0.21147
[2100]	validation_0-logloss:0.21150
[2150]	validation_0-logloss:0.21156
[2200]	validation_0-logloss:0.21158
[2250]	validation_0-logloss:0.21156
[2300]	validation_0-logloss:0.21150
[2350]	validation_0-logloss:0.21150
[2353]	validation_0-logloss:0.21150

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47499
[50]	validation_0-logloss:0.26500
[100]	validation_0-logloss:0.24906
[150]	validation_0-logloss:0.24106
[200]	validation_0-logloss:0.23549
[250]	validation_0-logloss:0.23167
[300]	validation_0-logloss:0.22827
[350]	validation_0-logloss:0.22590
[400]	validation_0-logloss:0.22422
[450]	validation_0-logloss:0.22267
[500]	validation_0-logloss:0.22121
[550]	validation_0-logloss:0.22033
[600]	validation_0-logloss:0.21943
[650]	validation_0-logloss:0.21862
[700]	validation_0-logloss:0.21816
[750]	validation_0-logloss:0.21770
[800]	validation_0-logloss:0.21721
[850]	validation_0-logloss:0.21668
[900]	validation_0-logloss:0.21606
[950]	validation_0-logloss:0.21575
[1000]	validation_0-logloss:0.21550
[1050]	validation_0-logloss:0.21516
[1100]	validation_0-logloss:0.21475
[1150]	validation_0-logloss:0.21430
[1200]	validation_0-logloss:0.21408
[1250]	validation_0-logloss:0.21387
[1300]	validation_0-logloss:0.21359
[1350]	validation_0-logloss:0.21341
[1400]	validation_0-logloss:0.21327
[1450]	validation_0-logloss:0.21311
[1500]	validation_0-logloss:0.21303
[1550]	validation_0-logloss:0.21301
[1600]	validation_0-logloss:0.21296
[1650]	validation_0-logloss:0.21303
[1700]	validation_0-logloss:0.21301
[1750]	validation_0-logloss:0.21293
[1800]	validation_0-logloss:0.21286
[1850]	validation_0-logloss:0.21274
[1900]	validation_0-logloss:0.21259
[1950]	validation_0-logloss:0.21259
[2000]	validation_0-logloss:0.21253
[2050]	validation_0-logloss:0.21247
[2100]	validation_0-logloss:0.21245
[2150]	validation_0-logloss:0.21245
[2200]	validation_0-logloss:0.21248
[2250]	validation_0-logloss:0.21250
[2300]	validation_0-logloss:0.21252
[2350]	validation_0-logloss:0.21252
[2400]	validation_0-logloss:0.21254
[2450]	validation_0-logloss:0.21260
[2500]	validation_0-logloss:0.21270
[2550]	validation_0-logloss:0.21268
[2600]	validation_0-logloss:0.21268
[2650]	validation_0-logloss:0.21270
[2700]	validation_0-logloss:0.21276
[2750]	validation_0-logloss:0.21282
[2788]	validation_0-logloss:0.21294

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47462
[50]	validation_0-logloss:0.26407
[100]	validation_0-logloss:0.24778
[150]	validation_0-logloss:0.23980
[200]	validation_0-logloss:0.23436
[250]	validation_0-logloss:0.23077
[300]	validation_0-logloss:0.22777
[350]	validation_0-logloss:0.22587
[400]	validation_0-logloss:0.22379
[450]	validation_0-logloss:0.22224
[500]	validation_0-logloss:0.22126
[550]	validation_0-logloss:0.22014
[600]	validation_0-logloss:0.21905
[650]	validation_0-logloss:0.21815
[700]	validation_0-logloss:0.21740
[750]	validation_0-logloss:0.21677
[800]	validation_0-logloss:0.21632
[850]	validation_0-logloss:0.21581
[900]	validation_0-logloss:0.21552
[950]	validation_0-logloss:0.21506
[1000]	validation_0-logloss:0.21471
[1050]	validation_0-logloss:0.21445
[1100]	validation_0-logloss:0.21425
[1150]	validation_0-logloss:0.21411
[1200]	validation_0-logloss:0.21383
[1250]	validation_0-logloss:0.21369
[1300]	validation_0-logloss:0.21353
[1350]	validation_0-logloss:0.21332
[1400]	validation_0-logloss:0.21306
[1450]	validation_0-logloss:0.21288
[1500]	validation_0-logloss:0.21284
[1550]	validation_0-logloss:0.21267
[1600]	validation_0-logloss:0.21249
[1650]	validation_0-logloss:0.21231
[1700]	validation_0-logloss:0.21228
[1750]	validation_0-logloss:0.21225
[1800]	validation_0-logloss:0.21211
[1850]	validation_0-logloss:0.21204
[1900]	validation_0-logloss:0.21201
[1950]	validation_0-logloss:0.21194
[2000]	validation_0-logloss:0.21189
[2050]	validation_0-logloss:0.21183
[2100]	validation_0-logloss:0.21180
[2150]	validation_0-logloss:0.21176
[2200]	validation_0-logloss:0.21181
[2250]	validation_0-logloss:0.21183
[2300]	validation_0-logloss:0.21183
[2350]	validation_0-logloss:0.21194
[2400]	validation_0-logloss:0.21203
[2450]	validation_0-logloss:0.21204
[2500]	validation_0-logloss:0.21217
[2550]	validation_0-logloss:0.21222
[2600]	validation_0-logloss:0.21232
[2650]	validation_0-logloss:0.21236
[2700]	validation_0-logloss:0.21235
[2750]	validation_0-logloss:0.21244
[2800]	validation_0-logloss:0.21246
[2845]	validation_0-logloss:0.21258

	Fit constraints were validated upstream on the full training data, skipping...

[0]	validation_0-logloss:0.47463
[50]	validation_0-logloss:0.26295
[100]	validation_0-logloss:0.24648
[150]	validation_0-logloss:0.23843
[200]	validation_0-logloss:0.23284
[250]	validation_0-logloss:0.22911
[300]	validation_0-logloss:0.22644
[350]	validation_0-logloss:0.22413
[400]	validation_0-logloss:0.22246
[450]	validation_0-logloss:0.22087
[500]	validation_0-logloss:0.21990
[550]	validation_0-logloss:0.21874
[600]	validation_0-logloss:0.21792
[650]	validation_0-logloss:0.21725
[700]	validation_0-logloss:0.21651
[750]	validation_0-logloss:0.21597
[800]	validation_0-logloss:0.21558
[850]	validation_0-logloss:0.21527
[900]	validation_0-logloss:0.21477
[950]	validation_0-logloss:0.21449
[1000]	validation_0-logloss:0.21397
[1050]	validation_0-logloss:0.21382
[1100]	validation_0-logloss:0.21337
[1150]	validation_0-logloss:0.21324
[1200]	validation_0-logloss:0.21307
[1250]	validation_0-logloss:0.21285
[1300]	validation_0-logloss:0.21263
[1350]	validation_0-logloss:0.21252
[1400]	validation_0-logloss:0.21245
[1450]	validation_0-logloss:0.21239
[1500]	validation_0-logloss:0.21203
[1550]	validation_0-logloss:0.21197
[1600]	validation_0-logloss:0.21192
[1650]	validation_0-logloss:0.21182
[1700]	validation_0-logloss:0.21182
[1750]	validation_0-logloss:0.21175
[1800]	validation_0-logloss:0.21166
[1850]	validation_0-logloss:0.21153
[1900]	validation_0-logloss:0.21150
[1950]	validation_0-logloss:0.21153
[2000]	validation_0-logloss:0.21160
[2050]	validation_0-logloss:0.21152
[2100]	validation_0-logloss:0.21147
[2150]	validation_0-logloss:0.21146
[2200]	validation_0-logloss:0.21152
[2250]	validation_0-logloss:0.21157
[2300]	validation_0-logloss:0.21156
[2350]	validation_0-logloss:0.21154
[2400]	validation_0-logloss:0.21148
[2450]	validation_0-logloss:0.21149
[2500]	validation_0-logloss:0.21146
[2550]	validation_0-logloss:0.21144
[2600]	validation_0-logloss:0.21142
[2650]	validation_0-logloss:0.21148
[2700]	validation_0-logloss:0.21152
[2750]	validation_0-logloss:0.21152
[2764]	validation_0-logloss:0.21150

Saving c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\model.pkl
	0.9571	 = Validation score   (roc_auc)
	273.06s	 = Training   runtime
	2.97s	 = Validation runtime
	22732.5	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\utils\oof.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\utils\oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'problem_types': ['binary', 'multiclass', 'regression', 'quantile', 'softclass'], 'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 3239.90s of the 30976.44s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 16
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\utils\model_template.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\utils\model_template.pkl
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/4.7 GB
Ensemble size: 20
Ensemble weights:
[0.45 0.25 0.05 0.25]
	0.55s	= Estimated out-of-fold prediction time...
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\utils\oof.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\model.pkl
	Ensemble Weights: {'LightGBM_BAG_L1': 0.45, 'LightGBMLarge_BAG_L1': 0.25, 'XGBoost_BAG_L1': 0.25, 'CatBoost_BAG_L1': 0.05}
	0.9591	 = Validation score   (roc_auc)
	5.06s	 = Training   runtime
	0.05s	 = Validation runtime
	1783.0	 = Inference  throughput (rows/s | 67556 batch size)
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
AutoGluon training complete, total runtime = 1428.76s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1783.0 rows/s (67556 batch size)
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\models\trainer.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\learner.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\predictor.pkl
Saving c:\Darshak\Projects\Hackathon\ag_models8\version.txt with contents "1.6.1"
Saving c:\Darshak\Projects\Hackathon\ag_models8\metadata.json
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Darshak\Projects\Hackathon\ag_models8")

In [169]:
leaderboard = predictor_wo_driver.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.959125,roc_auc,37.932610,1384.518738,0.050312,5.060219,2,True,5
1,LightGBM_BAG_L1,0.958277,roc_auc,11.543802,210.660673,11.543802,210.660673,1,True,1
2,XGBoost_BAG_L1,0.957086,roc_auc,2.971786,273.060256,2.971786,273.060256,1,True,4
3,LightGBMLarge_BAG_L1,0.956886,roc_auc,22.951177,296.346481,22.951177,296.346481,1,True,2
4,CatBoost_BAG_L1,0.954769,roc_auc,0.415533,599.391110,0.415533,599.391110,1,True,3

In [170]:
df=predictor_wo_driver.predict_proba(df_test)
df.head()
df_sample_out=pd.read_csv('data/sample_submission.csv')
df_sample_out.head()
df_sample_out['PitNextLap']=df[1]
df_sample_out.to_csv("My_output/all_model_together_best_fe_without_driver_1.csv", index=False)

Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\CatBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBMLarge_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\LightGBM_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\XGBoost_BAG_L1\model.pkl
Loading: c:\Darshak\Projects\Hackathon\ag_models8\models\WeightedEnsemble_L2\model.pkl